
// Country codes for phone input
export const COUNTRY_CODES = [
  { code: 'FR', dial: '+33', flag: '🇫🇷', name: 'France' },
  { code: 'US', dial: '+1', flag: '🇺🇸', name: 'États-Unis' },
  { code: 'GB', dial: '+44', flag: '🇬🇧', name: 'Royaume-Uni' },
  { code: 'DE', dial: '+49', flag: '🇩🇪', name: 'Allemagne' },
  { code: 'ES', dial: '+34', flag: '🇪🇸', name: 'Espagne' },
  { code: 'IT', dial: '+39', flag: '🇮🇹', name: 'Italie' },
  { code: 'PT', dial: '+351', flag: '🇵🇹', name: 'Portugal' },
  { code: 'BE', dial: '+32', flag: '🇧🇪', name: 'Belgique' },
  { code: 'CH', dial: '+41', flag: '🇨🇭', name: 'Suisse' },
  { code: 'CA', dial: '+1', flag: '🇨🇦', name: 'Canada' },
  { code: 'MA', dial: '+212', flag: '🇲🇦', name: 'Maroc' },
  { code: 'DZ', dial: '+213', flag: '🇩🇿', name: 'Algérie' },
  { code: 'TN', dial: '+216', flag: '🇹🇳', name: 'Tunisie' },
  { code: 'SN', dial: '+221', flag: '🇸🇳', name: 'Sénégal' },
  { code: 'CI', dial: '+225', flag: '🇨🇮', name: 'Côte d\'Ivoire' },
  { code: 'CM', dial: '+237', flag: '🇨🇲', name: 'Cameroun' },
  { code: 'BJ', dial: '+229', flag: '🇧🇯', name: 'Bénin' },
  { code: 'BF', dial: '+226', flag: '🇧🇫', name: 'Burkina Faso' },
  { code: 'NE', dial: '+227', flag: '🇳🇪', name: 'Niger' },
  { code: 'ML', dial: '+223', flag: '🇲🇱', name: 'Mali' },
  { code: 'GN', dial: '+224', flag: '🇬🇳', name: 'Guinée' },
  { code: 'TG', dial: '+228', flag: '🇹🇬', name: 'Togo' },
  { code: 'GA', dial: '+241', flag: '🇬🇦', name: 'Gabon' },
  { code: 'CG', dial: '+242', flag: '🇨🇬', name: 'Congo' },
  { code: 'CD', dial: '+243', flag: '🇨🇩', name: 'RDC' },
  { code: 'MG', dial: '+261', flag: '🇲🇬', name: 'Madagascar' },
  { code: 'RU', dial: '+7', flag: '🇷🇺', name: 'Russie' },
  { code: 'CN', dial: '+86', flag: '🇨🇳', name: 'Chine' },
  { code: 'JP', dial: '+81', flag: '🇯🇵', name: 'Japon' },
  { code: 'IN', dial: '+91', flag: '🇮🇳', name: 'Inde' },
  { code: 'BR', dial: '+55', flag: '🇧🇷', name: 'Brésil' },
  { code: 'MX', dial: '+52', flag: '🇲🇽', name: 'Mexique' },
  { code: 'AR', dial: '+54', flag: '🇦🇷', name: 'Argentine' },
  { code: 'CO', dial: '+57', flag: '🇨🇴', name: 'Colombie' },
  { code: 'PE', dial: '+51', flag: '🇵🇪', name: 'Pérou' },
  { code: 'CL', dial: '+56', flag: '🇨🇱', name: 'Chili' },
  { code: 'TR', dial: '+90', flag: '🇹🇷', name: 'Turquie' },
  { code: 'EG', dial: '+20', flag: '🇪🇬', name: 'Égypte' },
  { code: 'SA', dial: '+966', flag: '🇸🇦', name: 'Arabie saoudite' },
  { code: 'AE', dial: '+971', flag: '🇦🇪', name: 'Émirats arabes unis' },
  { code: 'ZA', dial: '+27', flag: '🇿🇦', name: 'Afrique du Sud' },
  { code: 'NG', dial: '+234', flag: '🇳🇬', name: 'Nigéria' },
  { code: 'KE', dial: '+254', flag: '🇰🇪', name: 'Kenya' },
  { code: 'AU', dial: '+61', flag: '🇦🇺', name: 'Australie' },
  { code: 'NZ', dial: '+64', flag: '🇳🇿', name: 'Nouvelle-Zélande' },
];
