import { describe, it, expect, jest } from '@jest/globals';
import Fastify from 'fastify';
import { registerStoryAudioRoutes } from '../audio';
import { authorAccentColor } from '@meeshy/shared/utils/conversation-colors';

/**
 * #6605 — un `Sound` né d'un post VOCAL (donc sans `coverUrl`/`coverThumbHash`,
 * cf. `SoundCaptureService.findCover`) et dont l'auteur n'a pas d'avatar
 * n'avait AUCUNE vignette servie par `GET /stories/audio`. Témoin de
 * COMPORTEMENT sur la route nommée par l'issue, pas une garde de source.
 */
const ID = '507f1f77bcf86cd799439011';

function auth() {
  return async (request: unknown) => {
    (request as Record<string, unknown>)['authContext'] = {
      type: 'registered', registeredUser: { id: 'user-abc', username: 'tester' },
      userId: 'user-abc', hasFullAccess: true,
    };
  };
}

async function buildApp(prisma: unknown) {
  const app = Fastify();
  registerStoryAudioRoutes(app, prisma as import('@meeshy/shared/prisma/client').PrismaClient, auth());
  await app.ready();
  return app;
}

const sound = {
  id: ID, title: '', fileUrl: '/f.m4a', durationMs: 12000, waveform: [0.1, 0.2],
  usageCount: 1, isPublic: true, mutedAt: null, isAutoGenerated: true,
  coverUrl: null, coverThumbHash: null,
  uploader: { id: 'author-1', username: 'atabeth', displayName: null, avatar: null },
};

function buildPrisma(sounds: unknown[]) {
  return {
    sound: { findMany: jest.fn<() => Promise<unknown[]>>().mockResolvedValue(sounds) },
    soundUsage: { findMany: jest.fn<() => Promise<unknown[]>>().mockResolvedValue([]) },
    post: { findMany: jest.fn<() => Promise<unknown[]>>().mockResolvedValue([]) },
  };
}

describe('GET /stories/audio — vignette de repli (#6605)', () => {
  it('test_storiesAudio_soundFromVoicePost_withoutAvatar_stillServesANonEmptyCoverColor', async () => {
    const res = await (await buildApp(buildPrisma([sound]))).inject({ method: 'GET', url: '/stories/audio' });

    expect(res.statusCode).toBe(200);
    const [row] = res.json().data;
    expect(row.coverUrl).toBeNull();
    expect(row.coverThumbHash).toBeNull();
    // Même graine que `authorAccentColor` sur les posts/commentaires/réels
    // (web-v2) : un son sans image porte la MÊME teinte que le reste du
    // contenu de son auteur.
    expect(row.coverColor).toBe(authorAccentColor('author-1', 'atabeth'));
    expect(row.coverColor).toMatch(/^#[0-9A-F]{6}$/);
  });

  it('test_storiesAudio_soundWithCoverUrl_keepsItAlongsideCoverColor', async () => {
    const withCover = { ...sound, coverUrl: '/cover.jpg', coverThumbHash: 'hash' };
    const res = await (await buildApp(buildPrisma([withCover]))).inject({ method: 'GET', url: '/stories/audio' });

    const [row] = res.json().data;
    expect(row.coverUrl).toBe('/cover.jpg');
    expect(row.coverThumbHash).toBe('hash');
    expect(row.coverColor).toBeTruthy();
  });
});
