import { QueryClient } from '@tanstack/react-query';
import { describe, expect, test } from 'bun:test';

import type { PaginationMeta } from '@meeshy/shared/types/api-responses';

import { scriptedGateway } from '@/test-support/scripted-transport';

import {
  MY_SOUNDS_QUERY_KEY,
  decodeMySound,
  flattenMySounds,
  loadMySounds,
  performRemoveSound,
  removeSound,
  withoutSound,
  type MySound,
  type MySoundsData,
} from './my-sounds';

/**
 * **« MES SONS » ET LEUR RETRAIT** (#9848) — `GET sounds.mine` liste les sons
 * de l'appelant, `DELETE sounds.byId` en retire un de SA bibliothèque. Le
 * retrait est OPTIMISTE : la ligne part au geste, et un refus la remet à SA
 * place — pas en tête, pas en fin.
 */

const sound = (id: string, overrides: Partial<MySound> = {}): MySound => ({
  id,
  title: `Son ${id}`,
  durationMs: 4000,
  postCount: 0,
  playCount: 0,
  isAutoGenerated: false,
  coverUrl: null,
  coverColor: null,
  createdAt: '2026-10-01T10:00:00.000Z',
  ...overrides,
});

const data = (...pages: ReadonlyArray<readonly MySound[]>): MySoundsData => ({
  pages: pages.map((sounds, index) => ({ sounds, nextCursor: index < pages.length - 1 ? `c${index}` : null })),
  pageParams: pages.map((_, index) => (index === 0 ? null : `c${index - 1}`)),
});

describe('le décodage d’un son servi', () => {
  test('lit les champs du DTO, compteurs compris', () => {
    const decoded = decodeMySound({
      id: 's1', title: '', fileUrl: '/api/v1/static/a.m4a', durationMs: 12000, waveform: [],
      usageCount: 4, isPublic: true, postCount: 3, playCount: 120, isAutoGenerated: true,
      coverUrl: '/c.jpg', coverThumbHash: null, coverColor: '#aabbcc', createdAt: '2026-10-01T10:00:00.000Z',
      uploader: { id: 'u1', username: 'alice', displayName: null, avatar: null },
    });
    expect(decoded).toEqual({
      id: 's1', title: '', durationMs: 12000, postCount: 3, playCount: 120, isAutoGenerated: true,
      coverUrl: '/c.jpg', coverColor: '#aabbcc', createdAt: '2026-10-01T10:00:00.000Z',
    });
  });

  test('un son sans identifiant n’est pas une ligne', () => {
    expect(decodeMySound({ title: 'x' })).toBeNull();
  });

  test('des compteurs absents valent zéro, jamais un état inconnu', () => {
    expect(decodeMySound({ id: 's1', title: 'x' })?.postCount).toBe(0);
  });
});

describe('le port', () => {
  test('« Mes sons » lit sounds.mine avec la page et le curseur', async () => {
    const gateway = scriptedGateway({
      'GET /api/v1/sounds/mine?limit=30&cursor=2026-10-01T10%3A00%3A00.000Z': {
        ok: true, status: 200, data: [{ id: 's1', title: 'Pluie' }],
        // La passerelle sert un curseur à côté de `hasMore` (`sounds.ts`) : la
        // forme que `PaginationMeta` (décalage) ne déclare pas, d'où la conversion.
        pagination: { limit: 30, hasMore: true, nextCursor: '2026-09-01T10:00:00.000Z' } as unknown as PaginationMeta,
      },
    });
    const result = await loadMySounds({ ...gateway.deps, cursor: '2026-10-01T10:00:00.000Z' });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.data.sounds.map((s) => s.id)).toEqual(['s1']);
    expect(result.data.nextCursor).toBe('2026-09-01T10:00:00.000Z');
  });

  test('retirer part en DELETE sur l’adresse du son, et rend le nombre de publications', async () => {
    const gateway = scriptedGateway({
      'DELETE /api/v1/sounds/s1': { ok: true, status: 200, data: { id: 's1', deletedAt: '2026-10-09T20:00:00.000Z', postCount: 2 } },
    });
    const result = await removeSound(gateway.deps, 's1');
    expect(gateway.calls().map((c) => `${c.method} ${c.path}`)).toEqual(['DELETE /api/v1/sounds/s1']);
    expect(result).toEqual({ ok: true, status: 200, data: { postCount: 2 } });
  });
});

describe('le retrait de la liste', () => {
  test('retire la ligne où qu’elle soit, sans toucher aux autres pages', () => {
    const next = withoutSound(data([sound('a'), sound('b')], [sound('c')]), 'c');
    expect(flattenMySounds(next).map((s) => s.id)).toEqual(['a', 'b']);
    expect(next?.pages).toHaveLength(2);
  });

  test('un cache vide reste vide', () => {
    expect(withoutSound(undefined, 'a')).toBeUndefined();
  });
});

describe('performRemoveSound — optimiste, retour arrière À SA PLACE', () => {
  const deps = (reply: { ok: boolean }, online = true) => {
    const gateway = scriptedGateway({
      'DELETE /api/v1/sounds/b': reply.ok
        ? { ok: true, status: 200, data: { id: 'b', deletedAt: null, postCount: 0 } }
        : { ok: false, status: 500, error: 'boom' },
    });
    const queryClient = new QueryClient();
    queryClient.setQueryData(MY_SOUNDS_QUERY_KEY, data([sound('a'), sound('b'), sound('c')]));
    return { gateway, queryClient, deps: { ...gateway.deps, queryClient, isOnline: () => online } };
  };

  test('la ligne quitte le cache AVANT la réponse', async () => {
    const { queryClient, deps: d } = deps({ ok: true });
    const pending = performRemoveSound({ sound: sound('b'), deps: d });
    expect(flattenMySounds(queryClient.getQueryData(MY_SOUNDS_QUERY_KEY)).map((s) => s.id)).toEqual(['a', 'c']);
    expect(await pending).toBe('done');
    expect(flattenMySounds(queryClient.getQueryData(MY_SOUNDS_QUERY_KEY)).map((s) => s.id)).toEqual(['a', 'c']);
  });

  test('un refus remet la ligne à SA place', async () => {
    const { queryClient, deps: d } = deps({ ok: false });
    expect(await performRemoveSound({ sound: sound('b'), deps: d })).toBe('failed');
    expect(flattenMySounds(queryClient.getQueryData(MY_SOUNDS_QUERY_KEY)).map((s) => s.id)).toEqual(['a', 'b', 'c']);
  });

  test('un refus ne ressuscite pas un AUTRE son retiré entre-temps', async () => {
    const { queryClient, deps: d } = deps({ ok: false });
    const pending = performRemoveSound({ sound: sound('b'), deps: d });
    queryClient.setQueryData<MySoundsData>(MY_SOUNDS_QUERY_KEY, (current) => withoutSound(current, 'a'));
    await pending;
    expect(flattenMySounds(queryClient.getQueryData(MY_SOUNDS_QUERY_KEY)).map((s) => s.id)).toEqual(['b', 'c']);
  });

  test('hors ligne, rien ne part et rien ne bouge', async () => {
    const { gateway, queryClient, deps: d } = deps({ ok: true }, false);
    expect(await performRemoveSound({ sound: sound('b'), deps: d })).toBe('offline');
    expect(gateway.calls()).toHaveLength(0);
    expect(flattenMySounds(queryClient.getQueryData(MY_SOUNDS_QUERY_KEY)).map((s) => s.id)).toEqual(['a', 'b', 'c']);
  });
});
