import { ConfigSection } from '@/types/admin-settings';
import {
  Settings,
  Database,
  Shield,
  Zap,
  MessageSquare,
  Upload,
  Server,
  Globe,
} from 'lucide-react';

/**
 * Admin settings configuration
 * Centralized configuration for all system settings
 */
export const configSections: ConfigSection[] = [
  {
    id: 'general',
    title: 'Configuration générale',
    description: "Paramètres globaux de l'application",
    icon: Settings,
    settings: [
      {
        key: 'NODE_ENV',
        label: 'Environnement',
        description: "Environnement d'exécution de l'application",
        type: 'select',
        value: 'production',
        defaultValue: 'production',
        envVar: 'NODE_ENV',
        options: [
          { label: 'Production', value: 'production' },
          { label: 'Development', value: 'development' },
          { label: 'Test', value: 'test' },
        ],
        implemented: true,
        category: 'system',
      },
      {
        key: 'DOMAIN',
        label: 'Domaine principal',
        description: "Nom de domaine de l'application",
        type: 'text',
        value: 'meeshy.me',
        defaultValue: 'localhost',
        envVar: 'DOMAIN',
        implemented: true,
        category: 'system',
      },
      {
        key: 'FRONTEND_URL',
        label: 'URL Frontend',
        description: 'URL complète du frontend (utilisée pour les liens)',
        type: 'text',
        value: 'https://meeshy.me',
        defaultValue: 'http://localhost:3100',
        envVar: 'FRONTEND_URL',
        implemented: true,
        category: 'system',
      },
      {
        key: 'BACKEND_URL',
        label: 'URL Backend',
        description: 'URL complète du backend (API)',
        type: 'text',
        value: 'https://api.meeshy.me',
        defaultValue: 'http://localhost:3000',
        envVar: 'BACKEND_URL',
        implemented: true,
        category: 'system',
      },
      {
        key: 'USE_HTTPS',
        label: 'Utiliser HTTPS',
        description: 'Activer le protocole HTTPS pour toutes les communications',
        type: 'boolean',
        value: true,
        defaultValue: false,
        envVar: 'USE_HTTPS',
        implemented: true,
        category: 'security',
      },
      {
        key: 'DEBUG',
        label: 'Mode Debug',
        description: 'Activer les logs détaillés pour le débogage',
        type: 'boolean',
        value: false,
        defaultValue: false,
        envVar: 'DEBUG',
        implemented: true,
        category: 'system',
      },
    ],
  },
  {
    id: 'database',
    title: 'Base de données',
    description: 'Configuration de la base de données PostgreSQL',
    icon: Database,
    settings: [
      {
        key: 'DATABASE_URL',
        label: 'URL de connexion',
        description:
          'URL de connexion PostgreSQL (format: postgresql://user:password@host:port/db)',
        type: 'text',
        value: 'postgresql://meeshy:***@localhost:5432/meeshy',
        defaultValue: '',
        envVar: 'DATABASE_URL',
        implemented: true,
        category: 'system',
      },
      {
        key: 'FORCE_DB_RESET',
        label: 'Réinitialisation forcée',
        description:
          'DANGER : Réinitialiser complètement la base de données au démarrage',
        type: 'boolean',
        value: false,
        defaultValue: false,
        envVar: 'FORCE_DB_RESET',
        implemented: true,
        category: 'system',
      },
      {
        key: 'DB_POOL_SIZE',
        label: 'Taille du pool de connexions',
        description:
          'Nombre maximum de connexions simultanées à la base de données',
        type: 'number',
        value: 20,
        defaultValue: 10,
        envVar: 'DB_POOL_SIZE',
        implemented: false,
        category: 'performance',
      },
      {
        key: 'DB_CONNECTION_TIMEOUT',
        label: 'Timeout de connexion',
        description:
          'Durée maximale pour établir une connexion (en secondes)',
        type: 'number',
        value: 30,
        defaultValue: 30,
        unit: 's',
        envVar: 'DB_CONNECTION_TIMEOUT',
        implemented: false,
        category: 'performance',
      },
    ],
  },
  {
    id: 'security',
    title: 'Sécurité',
    description: 'Paramètres de sécurité et authentification',
    icon: Shield,
    settings: [
      {
        key: 'JWT_SECRET',
        label: 'Clé secrète JWT',
        description:
          'Clé utilisée pour signer les tokens JWT (ne jamais exposer)',
        type: 'text',
        value: '••••••••••••••••',
        defaultValue: 'meeshy-secret-key-dev',
        envVar: 'JWT_SECRET',
        implemented: true,
        category: 'security',
      },
      {
        key: 'JWT_EXPIRY',
        label: 'Durée de validité JWT',
        description: "Durée de validité des tokens d'authentification",
        type: 'number',
        value: 7,
        defaultValue: 7,
        unit: 'jours',
        envVar: 'JWT_EXPIRY',
        implemented: false,
        category: 'security',
      },
      {
        key: 'CORS_ORIGINS',
        label: 'Origines CORS autorisées',
        description:
          "Liste des domaines autorisés à accéder à l'API (séparés par virgule)",
        type: 'text',
        value: 'https://meeshy.me,https://www.meeshy.me',
        defaultValue: 'http://localhost:3100',
        envVar: 'CORS_ORIGINS',
        implemented: true,
        category: 'security',
      },
      {
        key: 'MAX_LOGIN_ATTEMPTS',
        label: 'Tentatives de connexion max',
        description: 'Nombre de tentatives avant blocage temporaire du compte',
        type: 'number',
        value: 5,
        defaultValue: 5,
        envVar: 'MAX_LOGIN_ATTEMPTS',
        implemented: false,
        category: 'security',
      },
      {
        key: 'LOCKOUT_DURATION',
        label: 'Durée de blocage',
        description: 'Durée de blocage après échec de connexions multiples',
        type: 'number',
        value: 30,
        defaultValue: 30,
        unit: 'minutes',
        envVar: 'LOCKOUT_DURATION',
        implemented: false,
        category: 'security',
      },
      {
        key: 'PASSWORD_MIN_LENGTH',
        label: 'Longueur minimale mot de passe',
        description: 'Nombre minimum de caractères requis pour les mots de passe',
        type: 'number',
        value: 8,
        defaultValue: 8,
        envVar: 'PASSWORD_MIN_LENGTH',
        implemented: false,
        category: 'security',
      },
    ],
  },
  {
    id: 'rate-limiting',
    title: 'Rate Limiting',
    description: 'Protection contre les abus et surcharge',
    icon: Zap,
    settings: [
      {
        key: 'ENABLE_RATE_LIMITING',
        label: 'Activer rate limiting',
        description: 'Limiter le nombre de requêtes par utilisateur',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_RATE_LIMITING',
        implemented: true,
        category: 'performance',
      },
      {
        key: 'RATE_LIMIT_MAX',
        label: 'Nombre maximum de requêtes',
        description: 'Nombre de requêtes autorisées par fenêtre de temps',
        type: 'number',
        value: 100,
        defaultValue: 100,
        envVar: 'RATE_LIMIT_MAX',
        implemented: true,
        category: 'performance',
      },
      {
        key: 'RATE_LIMIT_WINDOW',
        label: 'Fenêtre de temps',
        description: 'Durée de la fenêtre pour le rate limiting',
        type: 'number',
        value: 60000,
        defaultValue: 60000,
        unit: 'ms',
        envVar: 'RATE_LIMIT_WINDOW',
        implemented: true,
        category: 'performance',
      },
      {
        key: 'RATE_LIMIT_BAN_DURATION',
        label: 'Durée de bannissement',
        description:
          'Durée du bannissement temporaire après dépassement des limites',
        type: 'number',
        value: 15,
        defaultValue: 15,
        unit: 'minutes',
        envVar: 'RATE_LIMIT_BAN_DURATION',
        implemented: false,
        category: 'performance',
      },
    ],
  },
  {
    id: 'messages',
    title: 'Messages et contenus',
    description: 'Configuration des messages et traductions',
    icon: MessageSquare,
    settings: [
      {
        key: 'MAX_MESSAGE_LENGTH',
        label: 'Longueur maximale message',
        description: 'Nombre maximum de caractères par message',
        type: 'number',
        value: 2000,
        defaultValue: 2000,
        envVar: 'MAX_MESSAGE_LENGTH',
        implemented: true,
        category: 'features',
      },
      {
        key: 'MAX_TEXT_ATTACHMENT_THRESHOLD',
        label: 'Seuil pièce jointe texte',
        description:
          'Longueur à partir de laquelle le texte devient une pièce jointe',
        type: 'number',
        value: 2000,
        defaultValue: 2000,
        envVar: 'MAX_TEXT_ATTACHMENT_THRESHOLD',
        implemented: true,
        category: 'features',
      },
      {
        key: 'MAX_TRANSLATION_LENGTH',
        label: 'Longueur max traduction',
        description: "Longueur maximale d'un message pouvant être traduit",
        type: 'number',
        value: 10000,
        defaultValue: 10000,
        envVar: 'MAX_TRANSLATION_LENGTH',
        implemented: true,
        category: 'features',
      },
      {
        key: 'AUTO_TRANSLATE',
        label: 'Traduction automatique',
        description: 'Activer la traduction automatique des messages',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'AUTO_TRANSLATE',
        implemented: false,
        category: 'features',
      },
      {
        key: 'MESSAGE_RETENTION_DAYS',
        label: 'Rétention des messages',
        description:
          'Durée de conservation des messages supprimés (0 = permanent)',
        type: 'number',
        value: 30,
        defaultValue: 30,
        unit: 'jours',
        envVar: 'MESSAGE_RETENTION_DAYS',
        implemented: false,
        category: 'system',
      },
      {
        key: 'ENABLE_MESSAGE_EDIT',
        label: "Autoriser l'édition",
        description: 'Permettre aux utilisateurs de modifier leurs messages',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_MESSAGE_EDIT',
        implemented: false,
        category: 'features',
      },
      {
        key: 'MESSAGE_EDIT_TIME_LIMIT',
        label: "Limite d'édition",
        description:
          'Durée pendant laquelle un message peut être modifié (0 = illimité)',
        type: 'number',
        value: 15,
        defaultValue: 15,
        unit: 'minutes',
        envVar: 'MESSAGE_EDIT_TIME_LIMIT',
        implemented: false,
        category: 'features',
      },
    ],
  },
  {
    id: 'uploads',
    title: 'Upload et stockage',
    description: 'Configuration des fichiers et médias',
    icon: Upload,
    settings: [
      {
        key: 'UPLOAD_PATH',
        label: "Dossier d'upload",
        description: 'Chemin du dossier où sont stockés les fichiers uploadés',
        type: 'text',
        value: '/app/uploads/attachments',
        defaultValue: './uploads/attachments',
        envVar: 'UPLOAD_PATH',
        implemented: true,
        category: 'system',
      },
      {
        key: 'PUBLIC_URL',
        label: 'URL publique des uploads',
        description: 'URL publique pour accéder aux fichiers uploadés',
        type: 'text',
        value: 'https://api.meeshy.me',
        defaultValue: 'http://localhost:3000',
        envVar: 'PUBLIC_URL',
        implemented: true,
        category: 'system',
      },
      {
        key: 'MAX_FILE_SIZE',
        label: 'Taille maximale fichier',
        description: 'Taille maximale autorisée pour un fichier',
        type: 'number',
        value: 50,
        defaultValue: 50,
        unit: 'MB',
        envVar: 'MAX_FILE_SIZE',
        implemented: false,
        category: 'features',
      },
      {
        key: 'MAX_IMAGE_SIZE',
        label: 'Taille maximale image',
        description: 'Taille maximale pour les images',
        type: 'number',
        value: 10,
        defaultValue: 10,
        unit: 'MB',
        envVar: 'MAX_IMAGE_SIZE',
        implemented: false,
        category: 'features',
      },
      {
        key: 'MAX_VIDEO_SIZE',
        label: 'Taille maximale vidéo',
        description: 'Taille maximale pour les vidéos',
        type: 'number',
        value: 100,
        defaultValue: 100,
        unit: 'MB',
        envVar: 'MAX_VIDEO_SIZE',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ALLOWED_IMAGE_TYPES',
        label: "Types d'images autorisés",
        description: "Extensions d'images acceptées (séparées par virgule)",
        type: 'text',
        value: 'jpg,jpeg,png,gif,webp',
        defaultValue: 'jpg,jpeg,png,gif,webp',
        envVar: 'ALLOWED_IMAGE_TYPES',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ALLOWED_VIDEO_TYPES',
        label: 'Types de vidéos autorisés',
        description: 'Extensions de vidéos acceptées (séparées par virgule)',
        type: 'text',
        value: 'mp4,webm,mov',
        defaultValue: 'mp4,webm,mov',
        envVar: 'ALLOWED_VIDEO_TYPES',
        implemented: false,
        category: 'features',
      },
      {
        key: 'AUTO_COMPRESS_IMAGES',
        label: 'Compression auto des images',
        description: 'Compresser automatiquement les images uploadées',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'AUTO_COMPRESS_IMAGES',
        implemented: false,
        category: 'performance',
      },
      {
        key: 'IMAGE_QUALITY',
        label: 'Qualité compression',
        description: "Qualité de compression des images (0-100)",
        type: 'number',
        value: 85,
        defaultValue: 85,
        unit: '%',
        envVar: 'IMAGE_QUALITY',
        implemented: false,
        category: 'performance',
      },
    ],
  },
  {
    id: 'server',
    title: 'Serveur et réseau',
    description: 'Configuration du serveur et des services',
    icon: Server,
    settings: [
      {
        key: 'PORT',
        label: 'Port du serveur',
        description: 'Port sur lequel le serveur écoute les requêtes HTTP',
        type: 'number',
        value: 3000,
        defaultValue: 3000,
        envVar: 'PORT',
        implemented: true,
        category: 'system',
      },
      {
        key: 'ZMQ_TRANSLATOR_PORT',
        label: 'Port service traduction',
        description: 'Port ZMQ pour le service de traduction',
        type: 'number',
        value: 5555,
        defaultValue: 5555,
        envVar: 'ZMQ_TRANSLATOR_PORT',
        implemented: true,
        category: 'system',
      },
      {
        key: 'LOCAL_IP',
        label: 'IP locale',
        description: 'Adresse IP locale du serveur',
        type: 'text',
        value: '192.168.1.39',
        defaultValue: '127.0.0.1',
        envVar: 'LOCAL_IP',
        implemented: true,
        category: 'system',
      },
      {
        key: 'SERVER_TIMEOUT',
        label: 'Timeout serveur',
        description: "Durée maximale de traitement d'une requête",
        type: 'number',
        value: 30,
        defaultValue: 30,
        unit: 's',
        envVar: 'SERVER_TIMEOUT',
        implemented: false,
        category: 'performance',
      },
      {
        key: 'KEEP_ALIVE_TIMEOUT',
        label: 'Keep-alive timeout',
        description: 'Durée de maintien des connexions HTTP',
        type: 'number',
        value: 65,
        defaultValue: 65,
        unit: 's',
        envVar: 'KEEP_ALIVE_TIMEOUT',
        implemented: false,
        category: 'performance',
      },
      {
        key: 'MAX_CONNECTIONS',
        label: 'Connexions simultanées max',
        description: 'Nombre maximum de connexions simultanées',
        type: 'number',
        value: 1000,
        defaultValue: 1000,
        envVar: 'MAX_CONNECTIONS',
        implemented: false,
        category: 'performance',
      },
    ],
  },
  {
    id: 'features',
    title: 'Fonctionnalités',
    description: 'Activation/désactivation des fonctionnalités',
    icon: Globe,
    settings: [
      {
        key: 'ENABLE_COMMUNITIES',
        label: 'Activer les communautés',
        description: 'Permettre la création et gestion de communautés',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_COMMUNITIES',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_ANONYMOUS',
        label: 'Activer mode anonyme',
        description: 'Permettre les utilisateurs anonymes via liens de partage',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_ANONYMOUS',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_VOICE_CALLS',
        label: 'Activer appels vocaux',
        description: 'Activer les appels vocaux et vidéo WebRTC',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_VOICE_CALLS',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_REACTIONS',
        label: 'Activer réactions',
        description: 'Permettre les réactions emoji sur les messages',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_REACTIONS',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_MENTIONS',
        label: 'Activer mentions',
        description: 'Permettre les mentions @utilisateur dans les messages',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_MENTIONS',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_NOTIFICATIONS',
        label: 'Activer notifications',
        description: 'Système de notifications en temps réel',
        type: 'boolean',
        value: true,
        defaultValue: true,
        envVar: 'ENABLE_NOTIFICATIONS',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_EMAIL_NOTIFICATIONS',
        label: 'Notifications par email',
        description: 'Envoyer des notifications par email',
        type: 'boolean',
        value: false,
        defaultValue: false,
        envVar: 'ENABLE_EMAIL_NOTIFICATIONS',
        implemented: false,
        category: 'features',
      },
      {
        key: 'ENABLE_MAINTENANCE_MODE',
        label: 'Mode maintenance',
        description: "Activer le mode maintenance (bloque l'accès)",
        type: 'boolean',
        value: false,
        defaultValue: false,
        envVar: 'ENABLE_MAINTENANCE_MODE',
        implemented: false,
        category: 'system',
      },
    ],
  },
];
