import XCTest
@testable import MeeshySDK

/// `APISound` porte un `CodingKeys` EXPLICITE. Ajouter une propriété sans
/// ajouter son `case` compile sans le moindre avertissement, et le champ cesse
/// simplement de voyager — c'est le piège qui a déjà coûté un `soundId` perdu
/// entre le composer et le serveur. Ces tests sont le garde-fou.
final class SoundModelsDecodingTests: XCTestCase {

    private func decode(_ json: String) throws -> APISound {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(APISound.self, from: Data(json.utf8))
    }

    /// Payload COMPLET, tel que `toDTO` le produit. Chaque champ est vérifié :
    /// un `case` oublié dans `CodingKeys` fait retomber la propriété sur sa
    /// valeur par défaut et casse une assertion ici.
    func test_decode_couvreTousLesChamps() throws {
        let sound = try decode("""
        {
          "id": "507f1f77bcf86cd799439011",
          "title": "Ma prod",
          "fileUrl": "/api/v1/static/abc.m4a",
          "durationMs": 4321,
          "waveform": [0.1, 0.9],
          "usageCount": 7,
          "postCount": 3,
          "playCount": 940,
          "isPublic": true,
          "isAutoGenerated": false,
          "coverUrl": "https://cdn/cover.jpg",
          "coverThumbHash": "hash",
          "createdAt": "2026-07-30T10:00:00Z",
          "uploader": { "id": "u1", "username": "alice", "displayName": "Alice", "avatar": "https://cdn/a.png" }
        }
        """)

        XCTAssertEqual(sound.id, "507f1f77bcf86cd799439011")
        XCTAssertEqual(sound.title, "Ma prod")
        XCTAssertEqual(sound.fileUrl, "/api/v1/static/abc.m4a")
        XCTAssertEqual(sound.durationMs, 4321)
        XCTAssertEqual(sound.waveform, [0.1, 0.9])
        XCTAssertEqual(sound.usageCount, 7)
        XCTAssertEqual(sound.postCount, 3)
        XCTAssertEqual(sound.playCount, 940)
        XCTAssertTrue(sound.isPublic)
        XCTAssertFalse(sound.isAutoGenerated)
        XCTAssertEqual(sound.coverUrl, "https://cdn/cover.jpg")
        XCTAssertEqual(sound.coverThumbHash, "hash")
        XCTAssertNotNil(sound.createdAt)
        XCTAssertEqual(sound.uploader?.username, "alice")
        XCTAssertEqual(sound.uploader?.displayName, "Alice")
        XCTAssertEqual(sound.uploader?.avatar, "https://cdn/a.png")
    }

    /// Une app plus récente que sa gateway reçoit ces deux compteurs ABSENTS.
    /// Le décodage synthétisé aurait fait échouer la LISTE ENTIÈRE sur deux
    /// nombres décoratifs.
    func test_decode_sansLesNouveauxCompteurs_rendZeroEtNeLevePas() throws {
        let sound = try decode("""
        { "id": "s1", "title": "", "fileUrl": "/f.m4a", "usageCount": 4, "isPublic": true }
        """)

        XCTAssertEqual(sound.postCount, 0)
        XCTAssertEqual(sound.playCount, 0)
        XCTAssertEqual(sound.usageCount, 4)
        XCTAssertEqual(sound.waveform, [])
    }

    /// Le strict minimum qu'on ne peut pas fabriquer : sans identifiant ni
    /// fichier, l'entrée n'est pas jouable et doit être rejetée franchement.
    func test_decode_sansFileUrl_leve() {
        XCTAssertThrowsError(try decode(#"{ "id": "s1", "title": "x" }"#))
    }

    func test_decode_sansId_leve() {
        XCTAssertThrowsError(try decode(#"{ "title": "x", "fileUrl": "/f.m4a" }"#))
    }

    func test_encodeDecode_faitUnAllerRetourFidele() throws {
        let original = APISound(
            id: "s1", title: "T", fileUrl: "/f.m4a", durationMs: 100, waveform: [0.5],
            usageCount: 2, postCount: 1, playCount: 50, isPublic: false, isAutoGenerated: true,
            coverUrl: "c", coverThumbHash: "h", createdAt: nil,
            uploader: APISoundUploader(id: "u", username: "bob"))

        let data = try JSONEncoder().encode(original)
        let round = try JSONDecoder().decode(APISound.self, from: data)

        XCTAssertEqual(round, original)
    }

    // MARK: - Libellés dérivés

    func test_hasAuthoredTitle_ignoreLesBlancs() {
        XCTAssertFalse(APISound(id: "s", title: "   ", fileUrl: "/f").hasAuthoredTitle)
        XCTAssertTrue(APISound(id: "s", title: " x ", fileUrl: "/f").hasAuthoredTitle)
    }

    func test_authorLabel_prefereLeNomAffichePuisLArobase() {
        XCTAssertEqual(APISound(id: "s", title: "", fileUrl: "/f",
                                uploader: .init(id: "u", username: "bob", displayName: "Robert")).authorLabel,
                       "Robert")
        XCTAssertEqual(APISound(id: "s", title: "", fileUrl: "/f",
                                uploader: .init(id: "u", username: "bob")).authorLabel, "@bob")
        XCTAssertNil(APISound(id: "s", title: "", fileUrl: "/f").authorLabel)
    }
}
