/**
 * Manual mock for lucide-react to avoid ESM issues in Jest
 */
const React = require('react');

// Create a generic icon component factory
const createIcon = (name) => {
  const Icon = React.forwardRef((props, ref) =>
    React.createElement('svg', { ref, 'data-testid': `${name.toLowerCase()}-icon`, ...props })
  );
  Icon.displayName = name;
  return Icon;
};

// Export all commonly used icons
module.exports = {
  Loader2: createIcon('Loader2'),
  Bell: createIcon('Bell'),
  BellOff: createIcon('BellOff'),
  Check: createIcon('Check'),
  CheckCheck: createIcon('CheckCheck'),
  X: createIcon('X'),
  MessageSquare: createIcon('MessageSquare'),
  Settings: createIcon('Settings'),
  Trash2: createIcon('Trash2'),
  AlertTriangle: createIcon('AlertTriangle'),
  RefreshCw: createIcon('RefreshCw'),
  ChevronDown: createIcon('ChevronDown'),
  ChevronUp: createIcon('ChevronUp'),
  ChevronLeft: createIcon('ChevronLeft'),
  ChevronRight: createIcon('ChevronRight'),
  Search: createIcon('Search'),
  Plus: createIcon('Plus'),
  Download: createIcon('Download'),
  Upload: createIcon('Upload'),
  Eye: createIcon('Eye'),
  EyeOff: createIcon('EyeOff'),
  Lock: createIcon('Lock'),
  User: createIcon('User'),
  Users: createIcon('Users'),
  Mail: createIcon('Mail'),
  Phone: createIcon('Phone'),
  PhoneOff: createIcon('PhoneOff'),
  Video: createIcon('Video'),
  VideoOff: createIcon('VideoOff'),
  Mic: createIcon('Mic'),
  MicOff: createIcon('MicOff'),
  Camera: createIcon('Camera'),
  Image: createIcon('Image'),
  File: createIcon('File'),
  FileText: createIcon('FileText'),
  Folder: createIcon('Folder'),
  Link: createIcon('Link'),
  Link2: createIcon('Link2'),
  ExternalLink: createIcon('ExternalLink'),
  Share: createIcon('Share'),
  Share2: createIcon('Share2'),
  Copy: createIcon('Copy'),
  Edit: createIcon('Edit'),
  Save: createIcon('Save'),
  Info: createIcon('Info'),
  AlertCircle: createIcon('AlertCircle'),
  CheckCircle: createIcon('CheckCircle'),
  CheckCircle2: createIcon('CheckCircle2'),
  XCircle: createIcon('XCircle'),
  Globe: createIcon('Globe'),
  Globe2: createIcon('Globe2'),
  Languages: createIcon('Languages'),
  Sparkles: createIcon('Sparkles'),
  Star: createIcon('Star'),
  Heart: createIcon('Heart'),
  Smile: createIcon('Smile'),
  Flag: createIcon('Flag'),
  Pin: createIcon('Pin'),
  Archive: createIcon('Archive'),
  ArchiveRestore: createIcon('ArchiveRestore'),
  MoreVertical: createIcon('MoreVertical'),
  ArrowLeft: createIcon('ArrowLeft'),
  ArrowRight: createIcon('ArrowRight'),
  ArrowUp: createIcon('ArrowUp'),
  ArrowDown: createIcon('ArrowDown'),
  Home: createIcon('Home'),
  Clock: createIcon('Clock'),
  Calendar: createIcon('Calendar'),
  Filter: createIcon('Filter'),
  Wifi: createIcon('Wifi'),
  WifiOff: createIcon('WifiOff'),
  Signal: createIcon('Signal'),
  SignalHigh: createIcon('SignalHigh'),
  SignalLow: createIcon('SignalLow'),
  SignalMedium: createIcon('SignalMedium'),
  Send: createIcon('Send'),
  MapPin: createIcon('MapPin'),
  MessageCircle: createIcon('MessageCircle'),
  Paperclip: createIcon('Paperclip'),
  Square: createIcon('Square'),
  Play: createIcon('Play'),
  Pause: createIcon('Pause'),
  Volume2: createIcon('Volume2'),
  VolumeX: createIcon('VolumeX'),
  Maximize: createIcon('Maximize'),
  Maximize2: createIcon('Maximize2'),
  Minimize: createIcon('Minimize'),
  ZoomIn: createIcon('ZoomIn'),
  ZoomOut: createIcon('ZoomOut'),
  RotateCw: createIcon('RotateCw'),
  RotateCcw: createIcon('RotateCcw'),
  SwitchCamera: createIcon('SwitchCamera'),
  BarChart3: createIcon('BarChart3'),
  TrendingUp: createIcon('TrendingUp'),
  TrendingDown: createIcon('TrendingDown'),
  Hash: createIcon('Hash'),
  Building2: createIcon('Building2'),
  UserPlus: createIcon('UserPlus'),
  Shield: createIcon('Shield'),
  ShieldCheck: createIcon('ShieldCheck'),
  Database: createIcon('Database'),
  Cpu: createIcon('Cpu'),
  Zap: createIcon('Zap'),
  Gem: createIcon('Gem'),
  Target: createIcon('Target'),
  Tag: createIcon('Tag'),
  HelpCircle: createIcon('HelpCircle'),
  Palette: createIcon('Palette'),
  Monitor: createIcon('Monitor'),
  Sun: createIcon('Sun'),
  Moon: createIcon('Moon'),
  Gauge: createIcon('Gauge'),
  Music: createIcon('Music'),
  Mic2: createIcon('Mic2'),
  Baby: createIcon('Baby'),
  Skull: createIcon('Skull'),
  Radio: createIcon('Radio'),
  Sliders: createIcon('Sliders'),
  TestTube: createIcon('TestTube'),
  Smartphone: createIcon('Smartphone'),
  Ghost: createIcon('Ghost'),
  ChevronsUpDown: createIcon('ChevronsUpDown'),
  Grid3X3: createIcon('Grid3X3'),
  Grid3x3: createIcon('Grid3x3'),
  WrapText: createIcon('WrapText'),
  FileImage: createIcon('FileImage'),
  FileArchive: createIcon('FileArchive'),
  KeyRound: createIcon('KeyRound'),
  LogIn: createIcon('LogIn'),
  UserMinus: createIcon('UserMinus'),
  // Admin page icons
  Trophy: createIcon('Trophy'),
  Medal: createIcon('Medal'),
  Award: createIcon('Award'),
  Activity: createIcon('Activity'),
  Reply: createIcon('Reply'),
  AtSign: createIcon('AtSign'),
  BarChart2: createIcon('BarChart2'),
  MousePointerClick: createIcon('MousePointerClick'),
  Users2: createIcon('Users2'),
  UserCheck: createIcon('UserCheck'),
  Crown: createIcon('Crown'),
  LogOut: createIcon('LogOut'),
  Menu: createIcon('Menu'),
  Laptop: createIcon('Laptop'),
  Edit2: createIcon('Edit2'),
  Key: createIcon('Key'),
  // Landing page icons
  GraduationCap: createIcon('GraduationCap'),
  Youtube: createIcon('Youtube'),
  Twitter: createIcon('Twitter'),
  Linkedin: createIcon('Linkedin'),
  Instagram: createIcon('Instagram'),
  Building: createIcon('Building'),
  // Search page icons
  MoreHorizontal: createIcon('MoreHorizontal'),
  XOctagon: createIcon('XOctagon'),
  // Settings page icons
  SettingsIcon: createIcon('SettingsIcon'),
  // Dashboard page icons
  LayoutDashboard: createIcon('LayoutDashboard'),
  FileAudio: createIcon('FileAudio'),
  Repeat: createIcon('Repeat'),
  // Tracking links page icons
  BarChart: createIcon('BarChart'),
  MousePointer: createIcon('MousePointer'),
  TrendingFlat: createIcon('TrendingFlat'),
  Earth: createIcon('Earth'),
  Chrome: createIcon('Chrome'),
  Safari: createIcon('Safari'),
  Firefox: createIcon('Firefox'),
  RefreshCcw: createIcon('RefreshCcw'),
  // TikTok icon (custom)
  TikTok: createIcon('TikTok'),
};

// Add a fallback for any icon not explicitly defined
const handler = {
  get: function(target, prop) {
    if (prop in target) {
      return target[prop];
    }
    // Return a dynamically created icon for any missing icon
    if (typeof prop === 'string' && prop[0] === prop[0].toUpperCase()) {
      return createIcon(prop);
    }
    return undefined;
  }
};

module.exports = new Proxy(module.exports, handler);
