import { act, solo } from './build';
import { hearts, many, shadow, sparkles, zs } from './kit';
import { P, at, confettiBurst, sign } from './props';
import type { MeeSticker } from './types';

/**
 * MEO SEUL, SUITE (#9058) — vingt gestes de plus, dans le même repère que
 * `catalog-meo.ts`. Meo garde sa manière : il salue du doigt, file au lieu de
 * s'envoler, et la gêne lui fait hausser les épaules plutôt que se cacher.
 */

const ground = shadow(100, 177);

export const MEO_SOLO_MORE: readonly MeeSticker[] = [
  solo('meo', {
    id: 'meo-yo',
    title: 'Yo !',
    feeling: 'salut',
    emoji: '🤙',
    pose: { eyes: 'cool', beak: 'smile' },
    back: ground,
    front: sparkles('p1', [[166, 70], [180, 96]], 1.4),
    motion: act({ wr1: ['pointR', 1.4], p1: ['twinkle', 1.4] }),
  }),
  solo('meo', {
    id: 'meo-bonne-nuit',
    title: 'Bonne nuit',
    feeling: 'salut',
    emoji: '🕯️',
    pose: { eyes: 'closed', beak: 'smile', acc: ['nightcap'] },
    back: `${at(36, 40, P.moon())}${ground}`,
    front: `${at(168, 152, P.candle())}${at(168, 146, P.flame(), { role: 'p1' })}${zs('p2', 150, 62)}`,
    motion: act({ wr1: ['waveR', 2.4], p1: ['flicker', 0.5], p2: ['zzz', 2.4] }),
  }),
  solo('meo', {
    id: 'meo-merci',
    title: 'Merci mille fois',
    feeling: 'joie',
    intent: 'bonjour',
    emoji: '🙏',
    pose: { eyes: 'closed', beak: 'smile' },
    back: ground,
    front: hearts('p1', [[40, 70], [164, 62]], 1.6, '#8b5cf6'),
    motion: act({ b1: ['nod', 0.8], wl1: ['clapL', 1.6], wr1: ['clapR', 1.6], p1: ['glow', 1.6] }),
  }),
  solo('meo', {
    id: 'meo-desole',
    title: 'Désolé',
    feeling: 'gene',
    intent: 'bonjour',
    emoji: '🥺',
    pose: { eyes: 'teary', beak: 'frown' },
    back: ground,
    front: at(170, 128, P.rose(), { role: 'p1', rot: 12 }),
    motion: act({ wr1: ['offerR', 2.6], p1: ['sway', 2.6] }),
  }),
  solo('meo', {
    id: 'meo-a-plus',
    title: 'À plus !',
    feeling: 'salut',
    emoji: '💨',
    pose: { eyes: 'wink', beak: 'tongue' },
    back: ground,
    motion: act({ b1: ['sneak', 3.2], wr1: ['waveR', 0.8] }),
  }),
  solo('meo', {
    id: 'meo-a-table',
    title: 'À table !',
    feeling: 'quotidien',
    emoji: '🍲',
    pose: { eyes: 'joy', beak: 'open', acc: ['chef'] },
    back: ground,
    front: `${at(162, 160, P.bowl())}${many([[154, 138], [166, 136]], P.steamPuff(), 'p1', 1.4)}`,
    motion: act({ b1: ['hop', 1.4], wr1: ['waveR', 1.4], p1: ['steam', 1.4] }),
  }),
  solo('meo', {
    id: 'meo-j-arrive',
    title: 'J’arrive !',
    feeling: 'quotidien',
    emoji: '🏃',
    pose: { eyes: 'open', beak: 'open', acc: ['sweat'] },
    back: `${at(34, 120, P.speedLines(), { role: 'p1' })}${ground}`,
    motion: act({ b1: ['approach', 1.2], p1: ['drift', 0.6] }),
  }),
  solo('meo', {
    id: 'meo-hmm',
    title: 'Hmm…',
    feeling: 'quotidien',
    emoji: '🧐',
    pose: { eyes: 'side', beak: 'flat' },
    back: ground,
    front: `${at(158, 50, P.thought())}${many([[148, 50], [156, 50], [164, 50]], '<circle r="2.6" fill="#7c3aed"/>', 'p1', 1.2)}`,
    motion: act({ e1: ['lookSide', 3], b1: ['sway', 3], p1: ['type', 1.2] }),
  }),
  solo('meo', {
    id: 'meo-tiens-bon',
    title: 'Tiens bon',
    feeling: 'consolation',
    emoji: '✊',
    pose: { eyes: 'closed', beak: 'smile' },
    back: ground,
    front: at(100, 30, sign('Tiens bon !', { w: 104, fill: '#ede9fe' }), { role: 'p1' }),
    motion: act({ wr1: ['raiseR', 2], p1: ['dangle', 2] }),
  }),
  solo('meo', {
    id: 'meo-viens-la',
    title: 'Viens là',
    feeling: 'consolation',
    emoji: '🫂',
    pose: { eyes: 'sad', beak: 'smile' },
    back: ground,
    front: at(100, 40, P.heart('#8b5cf6', 12), { role: 'p1' }),
    motion: act({ wl1: ['raiseL', 2.6], wr1: ['hugR', 2.6], p1: ['grow', 2.6] }),
  }),
  solo('meo', {
    id: 'meo-bonne-chance',
    title: 'Bonne chance',
    feeling: 'consolation',
    emoji: '🍀',
    pose: { eyes: 'wink', beak: 'smile' },
    back: ground,
    front: at(164, 70, P.clover(), { role: 'p1', s: 1.3 }),
    motion: act({ b1: ['nod', 1.4], p1: ['spin', 2.8] }),
  }),
  solo('meo', {
    id: 'meo-hein',
    title: 'Hein ?!',
    feeling: 'surprise',
    emoji: '😳',
    pose: { eyes: 'wide', beak: 'o' },
    back: ground,
    front: `${at(160, 66, P.question(), { role: 'p1' })}${at(176, 70, P.exclaim(), { role: 'p1', d: -0.4 })}`,
    motion: act({ e1: ['widen', 1.6], b1: ['tremble', 0.3], p1: ['wiggle', 0.8] }),
  }),
  solo('meo', {
    id: 'meo-araignee',
    title: 'Une araignée !',
    feeling: 'peur',
    emoji: '🕷️',
    pose: { eyes: 'wide', beak: 'grit', acc: ['sweat'] },
    back: ground,
    front: at(164, 76, P.spider(), { role: 'p1' }),
    motion: act({ b1: ['shiver', 0.5], p1: ['dangle', 1.6] }),
  }),
  solo('meo', {
    id: 'meo-tout-rouge',
    title: 'Tout rouge',
    feeling: 'timidite',
    emoji: '☺️',
    pose: { eyes: 'closed', beak: 'smile', acc: ['blush'] },
    back: ground,
    front: hearts('p1', [[64, 66], [140, 60]], 2.4, '#a78bfa'),
    motion: act({ b1: ['wiggle', 2.4], wl1: ['coverL', 2.4], p1: ['rise', 2.4] }),
  }),
  solo('meo', {
    id: 'meo-euh',
    title: 'Euh…',
    feeling: 'gene',
    emoji: '😅',
    pose: { eyes: 'side', beak: 'flat', acc: ['sweat'] },
    back: ground,
    front: at(140, 88, P.drop(), { role: 'p1' }),
    motion: act({ wl1: ['shrugL', 2.2], wr1: ['shrugR', 2.2], p1: ['tearFall', 1.1] }),
  }),
  solo('meo', {
    id: 'meo-baille',
    title: 'Je bâille',
    feeling: 'fatigue',
    emoji: '🥱',
    pose: { eyes: 'closed', beak: 'o' },
    back: ground,
    front: zs('p1', 152, 64),
    motion: act({ wl1: ['raiseL', 3], wr1: ['raiseR', 3], p1: ['zzz', 2.4] }),
  }),
  solo('meo', {
    id: 'meo-batterie-a-plat',
    title: 'Batterie à plat',
    feeling: 'fatigue',
    emoji: '🪫',
    pose: { eyes: 'sad', beak: 'flat' },
    back: ground,
    front: `${at(162, 56, P.battery(), { s: 1.1 })}${at(162, 56, P.batteryLevel(), { role: 'p1', s: 1.1 })}`,
    motion: act({ b1: ['melt', 3], p1: ['sand', 3] }),
  }),
  solo('meo', {
    id: 'meo-mort-de-honte',
    title: 'Mort de honte',
    feeling: 'morbide',
    emoji: '🫠',
    pose: { eyes: 'dead', beak: 'o', acc: ['blush'] },
    back: ground,
    front: at(150, 90, P.ghost(), { role: 'p1', s: 0.8 }),
    motion: act({ b1: ['sink', 3.2], p1: ['ghost', 3.2] }),
  }),
  solo('meo', {
    id: 'meo-bravo',
    title: 'Bravo !',
    feeling: 'celebration',
    emoji: '👏',
    pose: { eyes: 'star', beak: 'open' },
    back: ground,
    front: `${many([[34, 66], [170, 60], [100, 26]], P.star('#fbbf24', 8), 'p2', 1.2)}${confettiBurst(100, 50, 'p1', 10)}`,
    motion: act({ wl1: ['clapL', 0.6], wr1: ['clapR', 0.6], p1: ['burst', 1.8], p2: ['twinkle', 1.2] }),
  }),
  solo('meo', {
    id: 'meo-selfie',
    title: 'Selfie',
    feeling: 'joie',
    emoji: '🤳',
    pose: { eyes: 'wink', beak: 'tongue' },
    back: ground,
    front: `${at(166, 64, P.phone(), { rot: 12 })}${at(166, 52, P.sparkle('#fff', 16), { role: 'p1' })}`,
    motion: act({ wr1: ['raiseR', 2.2], p1: ['flash', 2.2] }),
  }),
];
