import { act, ambient, solo } from './build';
import { hearts, label, many, notes, rain, shadow, sparkles, tears, zs } from './kit';
import { P, at, confettiBurst, sign } from './props';
import type { MeeSticker } from './types';

/**
 * MEO SEUL (#9034) — trente stickers, dans le même repère que Mee. Meo
 * n'est pas un Mee repeint : ses gestes sont les siens (il gratte la guitare,
 * soulève des haltères, fait le zombie) et ses émotions passent par d'autres
 * mouvements que les siens.
 */

const ground = shadow(100, 177);

export const MEO_SOLO: readonly MeeSticker[] = [
  solo('meo', {
    id: 'meo-salut',
    title: 'Salut',
    feeling: 'salut',
    emoji: '✌️',
    pose: { eyes: 'wink', beak: 'smile' },
    back: ground,
    motion: act({ wr1: ['waveR', 1.4], b1: ['nod', 1.4] }),
  }),
  solo('meo', {
    id: 'meo-clin',
    title: 'Clin d’œil',
    feeling: 'humour',
    emoji: '😉',
    pose: { eyes: 'wink', beak: 'smile' },
    back: ground,
    front: at(126, 104, P.sparkle('#fde047', 7), { role: 'p1' }),
    motion: ambient({ e1: ['blink', 2.2], p1: ['twinkle', 2.2] }),
  }),
  solo('meo', {
    id: 'meo-bisou',
    title: 'Bisou',
    feeling: 'amour',
    emoji: '💋',
    pose: { eyes: 'closed', beak: 'kiss' },
    back: ground,
    front: at(150, 130, P.heart('#e11d48', 10), { role: 'p1' }),
    motion: act({ b1: ['leanIn', 2.6], p1: ['flyR', 2.6] }),
  }),
  solo('meo', {
    id: 'meo-serenade',
    title: 'Sérénade',
    feeling: 'amour',
    emoji: '🎸',
    pose: { eyes: 'closed', beak: 'open' },
    back: ground,
    front: `${at(118, 150, P.guitar(), { s: 1.3, rot: -20 })}${notes('p1', [[160, 90], [174, 70], [150, 60]], 2.4)}`,
    motion: act({ wr1: ['tapR', 0.5], p1: ['rise', 2.4] }),
  }),
  solo('meo', {
    id: 'meo-muscles',
    title: 'Costaud',
    feeling: 'fierte',
    emoji: '🏋️',
    pose: { eyes: 'angry', beak: 'grit', acc: ['sweat'] },
    back: ground,
    front: at(100, 40, P.dumbbell(), { role: 'p1', s: 1.6 }),
    motion: act({ wl1: ['raiseL', 1.6], wr1: ['raiseR', 1.6], p1: ['toss', 1.6] }),
  }),
  solo('meo', {
    id: 'meo-cool',
    title: 'Trop cool',
    feeling: 'fierte',
    emoji: '😎',
    pose: { eyes: 'cool', beak: 'smile' },
    back: shadow(100, 182),
    front: at(82, 108, P.sparkle('#fff', 6), { role: 'p1' }),
    motion: ambient({ b1: ['float', 2.6], p1: ['twinkle', 1.6] }),
  }),
  solo('meo', {
    id: 'meo-rit',
    title: 'Fou rire',
    feeling: 'joie',
    emoji: '😂',
    pose: { eyes: 'joy', beak: 'open' },
    back: ground,
    front: `${tears('p1', [[78, 118], [122, 118]], 1.2)}${at(160, 64, label(0, 0, 'HA HA', { size: 16, fill: '#7c3aed' }), { role: 'p2' })}`,
    motion: act({ b1: ['tremble', 0.3], p1: ['tearFall', 1.2], p2: ['pop', 1.2] }),
  }),
  solo('meo', {
    id: 'meo-mdr-ko',
    title: 'K.-O. de rire',
    feeling: 'morbide',
    emoji: '☠️',
    pose: { eyes: 'dead', beak: 'tongue' },
    back: ground,
    front: at(160, 58, P.skull(), { role: 'p1' }),
    motion: act({ b1: ['topple', 3.2], p1: ['pop', 3.2] }),
  }),
  solo('meo', {
    id: 'meo-creuse',
    title: 'Je creuse ma tombe',
    feeling: 'morbide',
    emoji: '⚰️',
    pose: { eyes: 'closed', beak: 'flat' },
    back: `${at(36, 146, P.tombstone('MEO'))}${ground}`,
    front: `${at(162, 100, P.shovel(), { role: 'p1' })}${at(170, 170, P.dust(), { role: 'p2' })}`,
    motion: act({ p1: ['shovel', 1.2], p2: ['steam', 1.2] }),
  }),
  solo('meo', {
    id: 'meo-zombie',
    title: 'Zombie',
    feeling: 'morbide',
    emoji: '🧟',
    pose: { eyes: 'dizzy', beak: 'tongue', acc: ['bandage'] },
    back: ground,
    motion: act({ b1: ['sneak', 4], wr1: ['pointR', 4] }),
  }),
  solo('meo', {
    id: 'meo-non-merci',
    title: 'Non merci',
    feeling: 'rejet',
    emoji: '🙅',
    pose: { eyes: 'angry', beak: 'flat' },
    back: ground,
    front: at(56, 70, P.anger(), { role: 'p1', s: 1.4 }),
    motion: act({ b1: ['headshake', 1.6], p1: ['pop', 1.6] }),
  }),
  solo('meo', {
    id: 'meo-rage',
    title: 'La rage',
    feeling: 'colere',
    emoji: '🤬',
    pose: { eyes: 'angry', beak: 'grit' },
    back: `${at(32, 160, P.fire(), { role: 'p1' })}${at(170, 160, P.fire(), { role: 'p1', d: -0.25 })}`,
    front: many([[86, 64], [116, 62]], P.steamPuff(), 'p2', 1),
    motion: act({ b1: ['shake', 0.8], p1: ['flicker', 0.5], p2: ['steam', 1] }),
  }),
  solo('meo', {
    id: 'meo-facepalm',
    title: 'Sérieux…',
    feeling: 'frustration',
    emoji: '🤦',
    pose: { eyes: 'closed', beak: 'frown' },
    back: ground,
    front: at(62, 84, P.drop(), { role: 'p1' }),
    motion: act({ wr1: ['facepalmR', 2.6], p1: ['tearFall', 2.6] }),
  }),
  solo('meo', {
    id: 'meo-bof',
    title: 'Bof',
    feeling: 'humour',
    emoji: '🤷',
    pose: { eyes: 'side', beak: 'flat' },
    back: ground,
    front: at(100, 44, P.question(), { role: 'p1' }),
    motion: act({ wl1: ['shrugL', 2], wr1: ['shrugR', 2], p1: ['pop', 2] }),
  }),
  solo('meo', {
    id: 'meo-effondre',
    title: 'Effondré',
    feeling: 'tristesse',
    emoji: '😿',
    pose: { eyes: 'teary', beak: 'frown' },
    back: ground,
    front: tears('p1', [[88, 124], [112, 124]], 2),
    motion: act({ p1: ['tearFall', 2], b1: ['sink', 4] }),
  }),
  solo('meo', {
    id: 'meo-nuage-noir',
    title: 'Petit nuage noir',
    feeling: 'tristesse',
    emoji: '🌧️',
    pose: { eyes: 'sad', beak: 'frown' },
    back: ground,
    front: `${at(100, 34, P.darkCloud(), { role: 'p2', s: 0.9 })}${rain('p1', 76, 124, 54, 4)}`,
    motion: act({ p1: ['fall', 1.2], p2: ['drift', 4] }),
  }),
  solo('meo', {
    id: 'meo-coeur-brise',
    title: 'Le cœur en miettes',
    feeling: 'tristesse',
    emoji: '💔',
    pose: { eyes: 'closed', beak: 'frown' },
    back: ground,
    front: `${at(158, 56, P.heartHalfL('#7c3aed'), { role: 'p1', s: 1.6 })}${at(158, 56, P.heartHalfR('#7c3aed'), { role: 'p2', s: 1.6 })}`,
    motion: act({ p1: ['breakL', 2.8], p2: ['breakR', 2.8], b1: ['sulk', 2.8] }),
  }),
  solo('meo', {
    id: 'meo-champagne',
    title: 'Champagne',
    feeling: 'celebration',
    emoji: '🍾',
    pose: { eyes: 'joy', beak: 'open' },
    back: ground,
    front: `${at(164, 136, P.bottle(), { rot: 30 })}${at(178, 108, '<rect x="-4" y="-4" width="8" height="8" rx="2" fill="#fcd34d"/>', { role: 'p1' })}${many([[176, 110], [170, 104], [182, 114]], P.bubble(), 'p2', 1.6)}${confettiBurst(150, 60, 'p3', 8, 0.5)}`,
    motion: act({ p1: ['launch', 2], p2: ['rise', 1.6], p3: ['burst', 2] }),
  }),
  solo('meo', {
    id: 'meo-trophee',
    title: 'Champion',
    feeling: 'fierte',
    emoji: '🏆',
    pose: { eyes: 'star', beak: 'open' },
    back: ground,
    front: `${at(160, 52, P.trophy())}${confettiBurst(160, 40, 'p1', 10)}${sparkles('p2', [[40, 60], [36, 110]], 1)}`,
    motion: act({ wr1: ['raiseR', 2], p1: ['burst', 2], p2: ['twinkle', 1] }),
  }),
  solo('meo', {
    id: 'meo-feu-artifice',
    title: 'Feu d’artifice',
    feeling: 'celebration',
    emoji: '🎆',
    pose: { eyes: 'wide', beak: 'o' },
    back: `${[[40, 40, '#f472b6'], [160, 34, '#fbbf24'], [100, 26, '#22d3ee']]
      .map(([x, y, c], i) => at(Number(x), Number(y), `<circle r="20" fill="none" stroke="${c}" stroke-width="3" stroke-dasharray="4 5"/>`, { role: 'p1', d: -i * 0.6 }))
      .join('')}${ground}`,
    front: sparkles('p2', [[60, 70], [140, 64], [30, 90]], 1),
    motion: act({ p1: ['ring', 2], p2: ['twinkle', 1], e1: ['widen', 2] }),
  }),
  solo('meo', {
    id: 'meo-dodo',
    title: 'Je pique du nez',
    feeling: 'fatigue',
    emoji: '🥱',
    pose: { eyes: 'closed', beak: 'flat' },
    back: ground,
    front: zs('p1', 152, 72),
    motion: act({ b1: ['nod', 3], p1: ['zzz', 2.4] }),
  }),
  solo('meo', {
    id: 'meo-pizza',
    title: 'Pizza',
    feeling: 'quotidien',
    emoji: '🍕',
    pose: { eyes: 'joy', beak: 'open' },
    back: ground,
    front: at(168, 140, P.pizza(), { role: 'p1', rot: -30 }),
    motion: act({ p1: ['nibble', 3], b1: ['nod', 0.6] }),
  }),
  solo('meo', {
    id: 'meo-peur',
    title: 'Un fantôme !',
    feeling: 'peur',
    emoji: '👻',
    pose: { eyes: 'wide', beak: 'grit', acc: ['sweat'] },
    back: ground,
    front: at(100, 46, P.ghost(), { role: 'p1', s: 1.2 }),
    motion: act({ p1: ['dash', 2.4], b1: ['tremble', 0.3] }),
  }),
  solo('meo', {
    id: 'meo-quoi',
    title: 'Quoi ?!',
    feeling: 'surprise',
    emoji: '😲',
    pose: { eyes: 'wide', beak: 'open' },
    back: ground,
    front: `${at(150, 60, P.question(), { role: 'p1' })}${at(170, 66, P.exclaim(), { role: 'p1', d: -0.3 })}`,
    motion: act({ b1: ['hop', 1.8], p1: ['pop', 1.8] }),
  }),
  solo('meo', {
    id: 'meo-gene',
    title: 'Gêné',
    feeling: 'gene',
    emoji: '😳',
    pose: { eyes: 'side', beak: 'flat', acc: ['blush'] },
    back: ground,
    motion: act({ e1: ['lookSide', 2.6], wl1: ['coverL', 2.6] }),
  }),
  solo('meo', {
    id: 'meo-calin',
    title: 'Gros câlin',
    feeling: 'amour',
    emoji: '🫂',
    pose: { eyes: 'closed', beak: 'smile' },
    back: ground,
    front: hearts('p1', [[100, 50], [70, 60], [130, 58]], 2.2, '#8b5cf6'),
    motion: act({ wl1: ['raiseL', 2.2], wr1: ['hugR', 2.2], p1: ['pop', 2.2] }),
  }),
  solo('meo', {
    id: 'meo-ok',
    title: 'OK',
    feeling: 'joie',
    emoji: '👌',
    pose: { eyes: 'wink', beak: 'smile' },
    back: ground,
    front: at(100, 34, sign('OK !', { w: 80, fill: '#dcfce7' })),
  }),
  solo('meo', {
    id: 'meo-love',
    title: 'Love',
    feeling: 'amour',
    emoji: '🥰',
    pose: { eyes: 'heart', beak: 'smile' },
    back: ground,
    front: `${at(44, 66, P.heart('#7c3aed', 10))}${at(160, 50, P.heart('#e11d48', 9))}`,
  }),
  solo('meo', {
    id: 'meo-roi',
    title: 'Le roi',
    feeling: 'fierte',
    emoji: '👑',
    pose: { eyes: 'smirk', beak: 'smile', acc: ['crown'] },
    back: ground,
  }),
  solo('meo', {
    id: 'meo-gamer',
    title: 'En partie',
    feeling: 'quotidien',
    emoji: '🎮',
    pose: { eyes: 'angry', beak: 'tongue', acc: ['headphones'] },
    back: ground,
    front: at(166, 150, P.phone(), { rot: 70 }),
  }),
];
