import { act, duo } from './build';
import { hearts, many, notes, rain, shadow, sparkles, zs } from './kit';
import { P, at, confettiBurst } from './props';
import type { MeeSticker } from './types';

/**
 * MEE & MEO, SUITE (#9058) — vingt scènes à deux, chacune jouée dans UN seul
 * sens (`duo-<geste>`) : saluer ensemble, partager un café, se faire peur,
 * traîner un lundi matin. Même repère que `catalog-duo.ts` : l'acteur à
 * gauche (corps en (50, 118)), le partenaire à droite, retourné vers lui
 * (corps en (150, 118)).
 */

const floor = `${shadow(50, 160, 24)}${shadow(150, 160, 24)}`;

export const DUO_MORE: readonly MeeSticker[] = [
  duo('mee', {
    id: 'duo-coucou',
    title: 'Coucou vous deux',
    feeling: 'salut',
    emoji: '👋',
    actor: { eyes: 'joy', beak: 'open' },
    partner: { eyes: 'joy', beak: 'open' },
    back: floor,
    front: sparkles('p1', [[100, 56], [86, 40], [116, 34]], 1.6),
    motion: act({ wr1: ['waveR', 1.6], wr2: ['waveR', 1.6, 0.4], p1: ['twinkle', 1.6] }),
  }),
  duo('meo', {
    id: 'duo-bonne-nuit',
    title: 'Bonne nuit, toi',
    feeling: 'salut',
    emoji: '🌙',
    actor: { eyes: 'closed', beak: 'smile' },
    partner: { eyes: 'closed', beak: 'flat', acc: ['nightcap'] },
    back: `${at(100, 38, P.moon())}${floor}`,
    front: zs('p1', 160, 62),
    motion: act({ wr1: ['patR', 2.4], p1: ['zzz', 2.4] }),
  }),
  duo('mee', {
    id: 'duo-merci',
    title: 'Merci à toi',
    feeling: 'joie',
    intent: 'bonjour',
    emoji: '🙏',
    actor: { eyes: 'closed', beak: 'smile' },
    partner: { eyes: 'joy', beak: 'smile', acc: ['blush'] },
    back: floor,
    front: hearts('p1', [[100, 96], [108, 88]], 2.4),
    motion: act({ b1: ['bow', 2.4], b2: ['nod', 1.2], p1: ['rise', 2.4] }),
  }),
  duo('mee', {
    id: 'duo-a-bientot',
    title: 'À bientôt',
    feeling: 'salut',
    emoji: '🫡',
    actor: { eyes: 'teary', beak: 'smile' },
    partner: { eyes: 'wink', beak: 'smile' },
    back: floor,
    motion: act({ wr1: ['waveR', 1.2], b2: ['flyOff', 3.6] }),
  }),
  duo('meo', {
    id: 'duo-pardon',
    title: 'Pardon…',
    feeling: 'gene',
    intent: 'bonjour',
    emoji: '🌷',
    actor: { eyes: 'sad', beak: 'flat', acc: ['sweat'] },
    partner: { eyes: 'side', beak: 'flat' },
    back: floor,
    front: at(98, 120, P.rose(), { role: 'p1', rot: -20, s: 0.8 }),
    motion: act({ wr1: ['offerR', 3], p1: ['grow', 3], b2: ['sulk', 3] }),
  }),
  duo('mee', {
    id: 'duo-jour-de-pluie',
    title: 'Jour de pluie',
    feeling: 'tristesse',
    emoji: '🌧️',
    actor: { eyes: 'sad', beak: 'frown' },
    partner: { eyes: 'teary', beak: 'frown' },
    back: `${at(100, 36, P.darkCloud(), { s: 1.3 })}${rain('p1', 46, 154, 52, 6)}${floor}`,
    motion: act({ p1: ['fall', 1.1], b1: ['tremble', 0.4], b2: ['shiver', 0.6] }),
  }),
  duo('meo', {
    id: 'duo-creves',
    title: 'Crevés',
    feeling: 'fatigue',
    emoji: '😴',
    actor: { eyes: 'closed', beak: 'o' },
    partner: { eyes: 'closed', beak: 'flat' },
    back: floor,
    front: zs('p1', 96, 62),
    motion: act({ b1: ['leanIn', 4], p1: ['zzz', 2.4] }),
  }),
  duo('mee', {
    id: 'duo-lundi-matin',
    title: 'Lundi matin',
    feeling: 'fatigue',
    emoji: '☕',
    actor: { eyes: 'closed', beak: 'flat' },
    partner: { eyes: 'dizzy', beak: 'o' },
    back: floor,
    front: `${at(100, 148, P.cup(), { s: 0.9 })}${at(98, 130, P.steamPuff(), { role: 'p1' })}`,
    motion: act({ b1: ['bow', 3.2], b2: ['melt', 3.2], p1: ['steam', 1.6] }),
  }),
  duo('mee', {
    id: 'duo-bouh',
    title: 'Bouh !',
    feeling: 'peur',
    emoji: '👻',
    actor: { eyes: 'smirk', beak: 'open' },
    partner: { eyes: 'wide', beak: 'grit', acc: ['sweat'] },
    back: floor,
    front: `${at(152, 52, P.exclaim(), { role: 'p1' })}${at(166, 56, P.exclaim(), { role: 'p1', d: -0.2 })}`,
    motion: act({ b1: ['approach', 2.4], b2: ['recoil', 2.4], p1: ['flash', 2.4] }),
  }),
  duo('meo', {
    id: 'duo-oups',
    title: 'Oups',
    feeling: 'gene',
    emoji: '🫢',
    actor: { eyes: 'side', beak: 'grit', acc: ['sweat'] },
    partner: { eyes: 'wide', beak: 'o' },
    back: floor,
    front: at(104, 96, P.glass(), { role: 'p1', rot: 30 }),
    motion: act({ wr1: ['pushR', 2.4], p1: ['fall', 2.4], e2: ['widen', 2.4] }),
  }),
  duo('mee', {
    id: 'duo-surprise',
    title: 'Surprise !',
    feeling: 'surprise',
    emoji: '🎉',
    actor: { eyes: 'joy', beak: 'open', acc: ['party'] },
    partner: { eyes: 'wide', beak: 'o' },
    back: floor,
    front: `${sparkles('p2', [[100, 50], [82, 70], [120, 66]], 1.2, '#f472b6')}${confettiBurst(100, 80, 'p1', 10)}`,
    motion: act({ b2: ['hop', 1.8], e2: ['widen', 1.8], p1: ['burst', 1.8], p2: ['twinkle', 1.2] }),
  }),
  duo('meo', {
    id: 'duo-un-cafe',
    title: 'Un café ?',
    feeling: 'quotidien',
    emoji: '☕',
    actor: { eyes: 'joy', beak: 'smile' },
    partner: { eyes: 'closed', beak: 'smile' },
    back: floor,
    front: `${at(84, 150, P.cup(), { s: 0.8 })}${at(118, 150, P.cup(), { s: 0.8 })}${at(82, 134, P.steamPuff(), { role: 'p1' })}${at(116, 134, P.steamPuff(), { role: 'p2', d: -0.8 })}`,
    motion: act({ b1: ['nod', 1.6], b2: ['nod', 1.6, 0.8], p1: ['steam', 1.6], p2: ['steam', 1.6] }),
  }),
  duo('mee', {
    id: 'duo-on-mange',
    title: 'On mange ?',
    feeling: 'quotidien',
    emoji: '🍕',
    actor: { eyes: 'joy', beak: 'open' },
    partner: { eyes: 'star', beak: 'tongue' },
    back: floor,
    front: at(100, 132, P.pizza(), { role: 'p1', rot: 180, s: 0.9 }),
    motion: act({ wr1: ['scoopR', 1.5], p1: ['nibble', 3], b2: ['hops', 1.5] }),
  }),
  duo('meo', {
    id: 'duo-on-reflechit',
    title: 'On réfléchit',
    feeling: 'quotidien',
    emoji: '🤔',
    actor: { eyes: 'side', beak: 'flat' },
    partner: { eyes: 'side', beak: 'flat' },
    back: floor,
    front: `${at(88, 50, P.question(), { role: 'p1' })}${at(114, 44, P.question(), { role: 'p1', d: -1.2 })}`,
    motion: act({ e1: ['lookSide', 3], e2: ['lookSide', 3, 1], p1: ['reveal', 2.4] }),
  }),
  duo('mee', {
    id: 'duo-en-retard',
    title: 'Tu es en retard !',
    feeling: 'quotidien',
    emoji: '⏰',
    actor: { eyes: 'angry', beak: 'flat' },
    partner: { eyes: 'wide', beak: 'open', acc: ['sweat'] },
    back: `${at(100, 46, P.clockFace())}${floor}`,
    front: at(100, 46, P.clockHand(), { role: 'p1' }),
    motion: act({ wr1: ['tapR', 0.5], b2: ['approach', 1.2], p1: ['ticktock', 2.4] }),
  }),
  duo('meo', {
    id: 'duo-on-danse',
    title: 'On danse',
    feeling: 'joie',
    emoji: '💃',
    actor: { eyes: 'closed', beak: 'open' },
    partner: { eyes: 'joy', beak: 'open' },
    back: floor,
    front: notes('p1', [[100, 80], [90, 52], [112, 40]], 1.8),
    motion: act({ b1: ['dance', 1.2], b2: ['dance', 1.2, 0.6], p1: ['rise', 1.8] }),
  }),
  duo('mee', {
    id: 'duo-bravo',
    title: 'Bravo à toi',
    feeling: 'celebration',
    emoji: '🏅',
    actor: { eyes: 'joy', beak: 'open' },
    partner: { eyes: 'star', beak: 'smile' },
    back: floor,
    front: `${at(150, 146, P.medal(), { role: 'p1' })}${sparkles('p2', [[170, 74], [130, 66]], 1.2)}`,
    motion: act({ wl1: ['clapL', 0.6], wr1: ['clapR', 0.6], p1: ['grow', 2.4], p2: ['twinkle', 1.2] }),
  }),
  duo('mee', {
    id: 'duo-main-dans-la-main',
    title: 'Main dans la main',
    feeling: 'amour',
    emoji: '💞',
    actor: { eyes: 'closed', beak: 'smile', acc: ['blush'] },
    partner: { eyes: 'closed', beak: 'smile', acc: ['blush'] },
    back: floor,
    front: hearts('p1', [[100, 90], [92, 76], [108, 70]], 2.6),
    motion: act({ wr1: ['hugR', 2.6], wr2: ['hugR', 2.6], p1: ['rise', 2.6] }),
  }),
  duo('meo', {
    id: 'duo-zombies',
    title: 'Zombies du lundi',
    feeling: 'morbide',
    emoji: '🧟',
    actor: { eyes: 'dead', beak: 'open' },
    partner: { eyes: 'dead', beak: 'tongue' },
    back: `${at(100, 148, P.tombstone('LUNDI'), { s: 0.8 })}${floor}`,
    motion: act({ b1: ['sway', 2], b2: ['sway', 2, 1], wr1: ['pointR', 2], wr2: ['pointR', 2, 1] }),
  }),
  duo('mee', {
    id: 'duo-je-te-releve',
    title: 'Je te relève',
    feeling: 'consolation',
    emoji: '🤝',
    actor: { eyes: 'open', beak: 'smile' },
    partner: { eyes: 'teary', beak: 'smile', acc: ['bandage'] },
    back: floor,
    front: many([[150, 66], [168, 80]], P.sparkle('#fde047', 7), 'p1', 1.4),
    motion: act({ wr1: ['scoopR', 2.4], b2: ['hop', 2.4, 0.6], p1: ['twinkle', 1.4] }),
  }),
];
