import { act, ambient, solo } from './build';
import { hearts, many, notes, shadow, sparkles, sunAt, tears, zs } from './kit';
import { P, at, confettiBurst, sign } from './props';
import type { MeeSticker } from './types';

/**
 * MEE SEULE (#9034) — trente stickers. Le repère de la scène : son corps est
 * centré en (100, 120), son bec pointe vers (160, 139), ses ailes s'ouvrent
 * en (56, 110) et (144, 110), ses yeux sont en (87, 114) et (113, 114).
 */

const ground = shadow(100, 177);

export const MEE_SOLO: readonly MeeSticker[] = [
  solo('mee', {
    id: 'mee-coucou',
    title: 'Coucou',
    feeling: 'salut',
    emoji: '👋',
    pose: { eyes: 'open', beak: 'smile' },
    back: ground,
    front: sparkles('p1', [[172, 74], [186, 100], [160, 56]], 1.6),
    motion: act({ wr1: ['waveR', 1.6], e1: ['blink', 3.2], p1: ['twinkle', 1.6] }),
  }),
  solo('mee', {
    id: 'mee-bisou-vole',
    title: 'Bisou volé',
    feeling: 'amour',
    emoji: '😘',
    pose: { eyes: 'closed', beak: 'kiss' },
    back: ground,
    front: hearts('p1', [[166, 126], [174, 116], [162, 112]], 2.4),
    motion: act({ b1: ['leanIn', 2.4], p1: ['rise', 2.4] }),
  }),
  solo('mee', {
    id: 'mee-coeur-battant',
    title: 'Mon cœur bat',
    feeling: 'amour',
    emoji: '💓',
    pose: { eyes: 'heart', beak: 'open' },
    back: ground,
    front: hearts('p1', [[40, 70], [164, 60], [34, 130], [172, 150]], 1.8),
    motion: act({ b1: ['beat', 0.9], e1: ['widen', 1.8], p1: ['pop', 1.8] }),
  }),
  solo('mee', {
    id: 'mee-rougit',
    title: 'Je rougis',
    feeling: 'timidite',
    emoji: '☺️',
    pose: { eyes: 'closed', beak: 'smile', acc: ['blush'] },
    back: ground,
    front: hearts('p1', [[70, 70], [130, 66]], 2.6, '#fb7185'),
    motion: act({ wl1: ['coverL', 2.6], wr1: ['coverR', 2.6], p1: ['rise', 2.6] }),
  }),
  solo('mee', {
    id: 'mee-pleure',
    title: 'Je pleure',
    feeling: 'tristesse',
    emoji: '😢',
    pose: { eyes: 'sad', beak: 'frown' },
    back: ground,
    front: tears('p1', [[86, 126], [114, 126], [86, 126], [114, 126]], 1.4),
    motion: act({ p1: ['tearFall', 1.4], b1: ['tremble', 0.4] }),
  }),
  solo('mee', {
    id: 'mee-sanglote',
    title: 'Je sanglote',
    feeling: 'tristesse',
    emoji: '😭',
    pose: { eyes: 'closed', beak: 'open' },
    back: `${at(100, 182, '<ellipse rx="44" ry="6" fill="#93c5fd" opacity=".75"/>', { role: 'p2' })}`,
    front: tears('p1', [[80, 120], [120, 120], [76, 124], [124, 124], [82, 118], [118, 118]], 1.2),
    motion: act({ p1: ['tearFall', 1.2], p2: ['grow', 4], b1: ['shiver', 0.6] }),
  }),
  solo('mee', {
    id: 'mee-boude',
    title: 'Je boude',
    feeling: 'frustration',
    emoji: '😤',
    pose: { eyes: 'angry', beak: 'flat' },
    back: ground,
    front: many([[64, 70], [74, 62]], P.angerPuff(), 'p1', 1.4),
    motion: act({ b1: ['sulk', 2.8], p1: ['steam', 1.4] }),
  }),
  solo('mee', {
    id: 'mee-colere',
    title: 'En colère',
    feeling: 'colere',
    emoji: '😡',
    pose: { eyes: 'angry', beak: 'grit' },
    back: ground,
    front: `${many([[84, 66], [116, 66]], P.steamPuff(), 'p1', 1)}${at(158, 78, P.anger(), { role: 'p2', s: 1.5 })}`,
    motion: act({ b1: ['stomp', 0.7], p1: ['steam', 1], p2: ['flash', 1.4] }),
  }),
  solo('mee', {
    id: 'mee-evanouie',
    title: 'Évanouie d’amour',
    feeling: 'amour',
    emoji: '😵‍💫',
    pose: { eyes: 'dizzy', beak: 'o' },
    back: ground,
    front: at(100, 64, `${at(-26, 0, P.star('#fbbf24', 7))}${at(22, -14, P.heart('#e11d48', 7))}${at(14, 20, P.star('#f472b6', 6))}`, { role: 'p1' }),
    motion: act({ b1: ['faint', 3.4], p1: ['orbit', 1.6] }),
  }),
  solo('mee', {
    id: 'mee-morte-de-rire',
    title: 'Morte de rire',
    feeling: 'morbide',
    emoji: '💀',
    pose: { eyes: 'dead', beak: 'tongue', acc: ['halo'] },
    back: at(158, 150, P.tombstone('MDR'), { s: 1.1 }),
    front: many([[160, 128], [150, 132]], P.ghost(), 'p1', 3),
    motion: act({ b1: ['float', 2.4], p1: ['ghost', 3] }),
  }),
  solo('mee', {
    id: 'mee-fond',
    title: 'Je fonds',
    feeling: 'fatigue',
    emoji: '🫠',
    pose: { eyes: 'closed', beak: 'open', acc: ['sweat'] },
    back: `${sunAt(36, 36, 'p1', 0.9)}${ground}`,
    front: many([[78, 102], [126, 100]], P.drop(), 'p2', 1.2),
    motion: act({ b1: ['melt', 3.6], p1: ['rays', 6], p2: ['tearFall', 1.2] }),
  }),
  solo('mee', {
    id: 'mee-fete',
    title: 'C’est la fête',
    feeling: 'celebration',
    emoji: '🥳',
    pose: { eyes: 'joy', beak: 'open', acc: ['party'] },
    back: ground,
    front: confettiBurst(100, 60, 'p1', 12),
    motion: act({ b1: ['hops', 1.6], p1: ['burst', 1.6] }),
  }),
  solo('mee', {
    id: 'mee-gateau',
    title: 'Mon gâteau',
    feeling: 'celebration',
    emoji: '🎂',
    pose: { eyes: 'star', beak: 'smile', acc: ['party'] },
    back: ground,
    front: `${at(40, 160, P.cake(), { s: 0.9 })}${at(40, 138, P.flame(), { role: 'p1' })}${confettiBurst(40, 130, 'p2', 8, 0.4)}`,
    motion: act({ b1: ['nod', 2], p1: ['flicker', 0.5], p2: ['burst', 2] }),
  }),
  solo('mee', {
    id: 'mee-danse',
    title: 'Je danse',
    feeling: 'joie',
    emoji: '💃',
    pose: { eyes: 'closed', beak: 'smile', acc: ['headphones'] },
    back: ground,
    front: notes('p1', [[34, 90], [168, 70], [176, 112]], 1.8),
    motion: act({ b1: ['dance', 1.2], p1: ['rise', 1.8] }),
  }),
  solo('mee', {
    id: 'mee-dodo',
    title: 'Dodo',
    feeling: 'fatigue',
    emoji: '😴',
    pose: { eyes: 'closed', beak: 'flat', acc: ['nightcap'] },
    back: `${at(40, 40, P.moon())}${ground}`,
    front: zs('p1', 150, 70),
    motion: act({ b1: ['breathe', 3], p1: ['zzz', 2.4] }),
  }),
  solo('mee', {
    id: 'mee-lettre',
    title: 'Une lettre pour toi',
    feeling: 'amour',
    emoji: '💌',
    pose: { eyes: 'wink', beak: 'smile' },
    back: ground,
    front: at(150, 112, P.envelope('#fff1f2'), { role: 'p1', s: 0.8 }),
    motion: act({ wr1: ['offerR', 3], p1: ['flyR', 3] }),
  }),
  solo('mee', {
    id: 'mee-rose',
    title: 'Une rose',
    feeling: 'amour',
    emoji: '🌹',
    pose: { eyes: 'heart', beak: 'smile' },
    back: ground,
    front: at(172, 132, P.rose(), { role: 'p1' }),
    motion: act({ wr1: ['offerR', 3], p1: ['grow', 3], e1: ['blink', 3] }),
  }),
  solo('mee', {
    id: 'mee-wow',
    title: 'Waouh',
    feeling: 'surprise',
    emoji: '😮',
    pose: { eyes: 'wide', beak: 'o' },
    back: ground,
    front: `${at(160, 66, P.exclaim(), { role: 'p1' })}${at(176, 70, P.exclaim(), { role: 'p1', d: -0.2 })}`,
    motion: act({ e1: ['widen', 2], p1: ['pop', 2], b1: ['hop', 2] }),
  }),
  solo('mee', {
    id: 'mee-peur',
    title: 'J’ai peur',
    feeling: 'peur',
    emoji: '😱',
    pose: { eyes: 'wide', beak: 'grit', acc: ['sweat'] },
    back: `${at(46, 36, P.darkCloud(), { s: 0.8 })}${ground}`,
    front: at(46, 60, P.bolt(), { role: 'p1' }),
    motion: act({ b1: ['shiver', 0.5], p1: ['flash', 2] }),
  }),
  solo('mee', {
    id: 'mee-calin-moi',
    title: 'Câlin ?',
    feeling: 'amour',
    emoji: '🤗',
    pose: { eyes: 'joy', beak: 'open' },
    back: ground,
    front: at(100, 48, P.heart('#e11d48', 14), { role: 'p1' }),
    motion: act({ wl1: ['raiseL', 2.4], wr1: ['raiseR', 2.4], p1: ['pop', 2.4] }),
  }),
  solo('mee', {
    id: 'mee-merci',
    title: 'Merci',
    feeling: 'joie',
    emoji: '🙏',
    pose: { eyes: 'closed', beak: 'smile' },
    back: ground,
    front: sparkles('p1', [[40, 80], [170, 70], [160, 40]], 1.3),
    motion: act({ b1: ['bow', 2.6], p1: ['twinkle', 1.3] }),
  }),
  solo('mee', {
    id: 'mee-oups',
    title: 'Oups',
    feeling: 'gene',
    emoji: '😅',
    pose: { eyes: 'side', beak: 'flat', acc: ['sweat'] },
    back: ground,
    front: at(140, 90, P.drop(), { role: 'p1' }),
    motion: act({ e1: ['lookSide', 2.4], p1: ['tearFall', 1.6], wl1: ['coverL', 2.4] }),
  }),
  solo('mee', {
    id: 'mee-jalouse',
    title: 'Jalouse',
    feeling: 'jalousie',
    emoji: '😒',
    pose: { eyes: 'side', beak: 'frown' },
    back: ground,
    front: at(150, 74, P.anger(), { role: 'p1', s: 1.4 }),
    motion: act({ e1: ['lookSide', 3], p1: ['pop', 1.5], b1: ['sulk', 3] }),
  }),
  solo('mee', {
    id: 'mee-bravo',
    title: 'Bravo',
    feeling: 'celebration',
    emoji: '👏',
    pose: { eyes: 'joy', beak: 'open' },
    back: ground,
    front: many([[40, 60], [164, 52], [100, 34]], P.star(), 'p1', 1.2),
    motion: act({ wl1: ['clapL', 0.6], wr1: ['clapR', 0.6], p1: ['twinkle', 1.2] }),
  }),
  solo('mee', {
    id: 'mee-jackpot',
    title: 'Jackpot',
    feeling: 'humour',
    emoji: '🤑',
    pose: { eyes: 'coin', beak: 'tongue' },
    back: ground,
    front: at(166, 92, at(0, 0, P.coin(), { role: 'p2' }), { role: 'p1' }),
    motion: act({ p1: ['toss', 1.4], p2: ['flip', 0.35] }),
  }),
  solo('mee', {
    id: 'mee-coeur-brise',
    title: 'Cœur brisé',
    feeling: 'tristesse',
    emoji: '💔',
    pose: { eyes: 'sad', beak: 'frown' },
    back: ground,
    front: `${at(100, 46, P.heartHalfL(), { role: 'p1', s: 1.8 })}${at(100, 46, P.heartHalfR(), { role: 'p2', s: 1.8 })}`,
    motion: act({ p1: ['breakL', 2.6], p2: ['breakR', 2.6], e1: ['blink', 2.6] }),
  }),
  solo('mee', {
    id: 'mee-courage',
    title: 'Courage',
    feeling: 'consolation',
    emoji: '💪',
    pose: { eyes: 'closed', beak: 'smile' },
    back: ground,
    front: at(100, 34, sign('Courage !', { fill: '#fef3c7' })),
  }),
  solo('mee', {
    id: 'mee-cafe',
    title: 'Café',
    feeling: 'quotidien',
    emoji: '☕',
    pose: { eyes: 'closed', beak: 'smile' },
    back: ground,
    front: `${at(168, 156, P.cup())}${at(166, 136, P.steamPuff())}`,
  }),
  solo('mee', {
    id: 'mee-sourire',
    title: 'Sourire',
    feeling: 'joie',
    emoji: '😊',
    pose: { eyes: 'joy', beak: 'smile', acc: ['flower'] },
    back: ground,
  }),
  solo('mee', {
    id: 'mee-amoureuse',
    title: 'Amoureuse',
    feeling: 'amour',
    emoji: '😍',
    pose: { eyes: 'heart', beak: 'smile', acc: ['blush'] },
    back: ground,
    front: `${at(40, 64, P.heart('#f43f5e', 10))}${at(166, 56, P.heart('#fb7185', 8))}${at(30, 120, P.heart('#e11d48', 6))}`,
  }),
];
