/**
 * Catalogue des chemins d'API Meeshy — GÉNÉRÉ, ne pas éditer à la main.
 *
 * Source : services/gateway/route-manifest.json (#4276), lui-même produit
 * mécaniquement depuis le serveur Fastify assemblé (jamais lu à la main).
 * Régénérer après tout changement de route :
 *
 *   cd packages/shared && npm run api-endpoints:generate
 *
 * Le cliquet packages/shared/api/__tests__/endpoints-manifest-ratchet.test.ts
 * compare ce fichier à une régénération fraîche du manifeste et rougit à la
 * moindre divergence — route retirée, ajoutée, ou verbe changé.
 *
 * API_ENDPOINTS est organisé par ADRESSE (une entrée par chemin unique, pas
 * par verbe) : GET et POST sur la même URL partagent une seule entrée, le
 * verbe se choisissant au site d'appel — voir build-catalog.ts pour la règle
 * complète de dérivation namespace/clé, et #4280 pour le contexte du lot.
 *
 * Les entrées vivent dans api/endpoints/<groupe>.ts, un module par namespace
 * (#7716) : un client importe le module de son groupe en espace de noms, et
 * le bundler ne garde que les adresses appelées, dans le paquet de leurs
 * seuls appelants. Les paramètres y sont encodés (encodeURIComponent).
 *
 * Aucun securityLevel n'apparaît ici : le manifeste le porte 'inconnu' par
 * refus délibéré de deviner (#4276) — un catalogue qui en dériverait une
 * valeur la propagerait, inventée, aux catalogues iOS/Android qui dériveront
 * de celui-ci (#4281/#4282).
 */

import * as accountGroup from './endpoints/account.js';
import * as adminGroup from './endpoints/admin.js';
import * as affiliateGroup from './endpoints/affiliate.js';
import * as anonymousGroup from './endpoints/anonymous.js';
import * as apiLegacyAttachmentsGroup from './endpoints/api-legacy-attachments.js';
import * as apiLegacyConversationsGroup from './endpoints/api-legacy-conversations.js';
import * as apiLegacyMessagesGroup from './endpoints/api-legacy-messages.js';
import * as apiLegacySocketioGroup from './endpoints/api-legacy-socketio.js';
import * as apiLegacyUserGroup from './endpoints/api-legacy-user.js';
import * as appGroup from './endpoints/app.js';
import * as attachmentsGroup from './endpoints/attachments.js';
import * as authGroup from './endpoints/auth.js';
import * as callsGroup from './endpoints/calls.js';
import * as communitiesGroup from './endpoints/communities.js';
import * as contactsGroup from './endpoints/contacts.js';
import * as conversationsGroup from './endpoints/conversations.js';
import * as directoryGroup from './endpoints/directory.js';
import * as friendRequestsGroup from './endpoints/friend-requests.js';
import * as guestSessionsGroup from './endpoints/guest-sessions.js';
import * as hashtagsGroup from './endpoints/hashtags.js';
import * as healthGroup from './endpoints/health.js';
import * as invitationsGroup from './endpoints/invitations.js';
import * as lGroup from './endpoints/l.js';
import * as languagesGroup from './endpoints/languages.js';
import * as linksGroup from './endpoints/links.js';
import * as meGroup from './endpoints/me.js';
import * as mentionsGroup from './endpoints/mentions.js';
import * as messagesGroup from './endpoints/messages.js';
import * as notificationsGroup from './endpoints/notifications.js';
import * as postsGroup from './endpoints/posts.js';
import * as reactionsGroup from './endpoints/reactions.js';
import * as reportsGroup from './endpoints/reports.js';
import * as rootLegacyAttachmentsGroup from './endpoints/root-legacy-attachments.js';
import * as rootLegacyVoiceGroup from './endpoints/root-legacy-voice.js';
import * as signalGroup from './endpoints/signal.js';
import * as socialGroup from './endpoints/social.js';
import * as socketioGroup from './endpoints/socketio.js';
import * as soundsGroup from './endpoints/sounds.js';
import * as staticGroup from './endpoints/static.js';
import * as statusMetricsGroup from './endpoints/status-metrics.js';
import * as storiesGroup from './endpoints/stories.js';
import * as syncGroup from './endpoints/sync.js';
import * as trackingLinksGroup from './endpoints/tracking-links.js';
import * as translateGroup from './endpoints/translate.js';
import * as translateBlockingGroup from './endpoints/translate-blocking.js';
import * as uGroup from './endpoints/u.js';
import * as uploadsGroup from './endpoints/uploads.js';
import * as userGroup from './endpoints/user.js';
import * as userPreferencesGroup from './endpoints/user-preferences.js';
import * as usersGroup from './endpoints/users.js';
import * as voiceGroup from './endpoints/voice.js';

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/** Tous les groupes réunis. Un CLIENT importe le module de son groupe (`./endpoints/<groupe>.js`), jamais cet objet entier. */
export const API_ENDPOINTS = {
  account: accountGroup,
  admin: adminGroup,
  affiliate: affiliateGroup,
  anonymous: anonymousGroup,
  apiLegacyAttachments: apiLegacyAttachmentsGroup,
  apiLegacyConversations: apiLegacyConversationsGroup,
  apiLegacyMessages: apiLegacyMessagesGroup,
  apiLegacySocketio: apiLegacySocketioGroup,
  apiLegacyUser: apiLegacyUserGroup,
  app: appGroup,
  attachments: attachmentsGroup,
  auth: authGroup,
  calls: callsGroup,
  communities: communitiesGroup,
  contacts: contactsGroup,
  conversations: conversationsGroup,
  directory: directoryGroup,
  friendRequests: friendRequestsGroup,
  guestSessions: guestSessionsGroup,
  hashtags: hashtagsGroup,
  health: healthGroup,
  invitations: invitationsGroup,
  l: lGroup,
  languages: languagesGroup,
  links: linksGroup,
  me: meGroup,
  mentions: mentionsGroup,
  messages: messagesGroup,
  notifications: notificationsGroup,
  posts: postsGroup,
  reactions: reactionsGroup,
  reports: reportsGroup,
  rootLegacyAttachments: rootLegacyAttachmentsGroup,
  rootLegacyVoice: rootLegacyVoiceGroup,
  signal: signalGroup,
  social: socialGroup,
  socketio: socketioGroup,
  sounds: soundsGroup,
  static: staticGroup,
  statusMetrics: statusMetricsGroup,
  stories: storiesGroup,
  sync: syncGroup,
  trackingLinks: trackingLinksGroup,
  translate: translateGroup,
  translateBlocking: translateBlockingGroup,
  u: uGroup,
  uploads: uploadsGroup,
  user: userGroup,
  userPreferences: userPreferencesGroup,
  users: usersGroup,
  voice: voiceGroup,
} as const;

/** Les 419 (au 2026-08-29) chemins uniques du manifeste — dédupliqués par verbe. */
export const API_PATH_TEMPLATES = [
  '/api/attachments/file/*',
  '/api/conversations/:conversationId/clear-history',
  '/api/conversations/:conversationId/delete-for-me',
  '/api/conversations/:conversationId/restore-for-me',
  '/api/messages/:messageId/delete-for-me',
  '/api/messages/:messageId/restore-for-me',
  '/api/messages/bulk/delete-for-me',
  '/api/socketio/disconnect-user',
  '/api/socketio/stats',
  '/api/user/deleted-conversations',
  '/api/v1/account/deletion/resolve',
  '/api/v1/admin/agent/archetypes',
  '/api/v1/admin/agent/configs',
  '/api/v1/admin/agent/configs/:conversationId',
  '/api/v1/admin/agent/configs/:conversationId/live',
  '/api/v1/admin/agent/configs/:conversationId/messages',
  '/api/v1/admin/agent/configs/:conversationId/roles',
  '/api/v1/admin/agent/configs/:conversationId/schedule',
  '/api/v1/admin/agent/configs/:conversationId/stop',
  '/api/v1/admin/agent/configs/:conversationId/summary',
  '/api/v1/admin/agent/configs/:conversationId/trigger',
  '/api/v1/admin/agent/delivery-queue',
  '/api/v1/admin/agent/delivery-queue/:id',
  '/api/v1/admin/agent/global-config',
  '/api/v1/admin/agent/llm',
  '/api/v1/admin/agent/recent-activity',
  '/api/v1/admin/agent/reset',
  '/api/v1/admin/agent/reset/conversation/:conversationId',
  '/api/v1/admin/agent/reset/user/:userId',
  '/api/v1/admin/agent/roles/:conversationId/:userId/assign',
  '/api/v1/admin/agent/roles/:conversationId/:userId/unlock',
  '/api/v1/admin/agent/scan-logs',
  '/api/v1/admin/agent/scan-logs/:logId',
  '/api/v1/admin/agent/scan-logs/stats',
  '/api/v1/admin/agent/stats',
  '/api/v1/admin/agent/topics',
  '/api/v1/admin/agent/topics/:id',
  '/api/v1/admin/agent/topics/:id/test',
  '/api/v1/admin/analytics/calls',
  '/api/v1/admin/analytics/hourly-activity',
  '/api/v1/admin/analytics/kpis',
  '/api/v1/admin/analytics/language-distribution',
  '/api/v1/admin/analytics/message-types',
  '/api/v1/admin/analytics/realtime',
  '/api/v1/admin/analytics/user-distribution',
  '/api/v1/admin/analytics/volume-timeline',
  '/api/v1/admin/anonymous-users',
  '/api/v1/admin/anonymous-users/:participantId',
  '/api/v1/admin/broadcasts',
  '/api/v1/admin/broadcasts/:id',
  '/api/v1/admin/broadcasts/:id/preview',
  '/api/v1/admin/broadcasts/:id/send',
  '/api/v1/admin/broadcasts/:id/send-inapp',
  '/api/v1/admin/communities',
  '/api/v1/admin/conversations',
  '/api/v1/admin/conversations/:conversationId',
  '/api/v1/admin/conversations/:conversationId/messages',
  '/api/v1/admin/conversations/:conversationId/participants',
  '/api/v1/admin/conversations/:conversationId/participants/:userId',
  '/api/v1/admin/conversations/:conversationId/participants/:userId/remove',
  '/api/v1/admin/dashboard',
  '/api/v1/admin/dashboard/invalidate-cache',
  '/api/v1/admin/invitations',
  '/api/v1/admin/invitations/:id',
  '/api/v1/admin/invitations/stats',
  '/api/v1/admin/invitations/timeline/daily',
  '/api/v1/admin/languages/stats',
  '/api/v1/admin/languages/timeline',
  '/api/v1/admin/languages/translation-accuracy',
  '/api/v1/admin/me/permissions',
  '/api/v1/admin/messages',
  '/api/v1/admin/messages/engagement',
  '/api/v1/admin/messages/stats',
  '/api/v1/admin/messages/trends',
  '/api/v1/admin/posts',
  '/api/v1/admin/posts/:postId',
  '/api/v1/admin/posts/stats',
  '/api/v1/admin/ranking',
  '/api/v1/admin/reports',
  '/api/v1/admin/reports/:id',
  '/api/v1/admin/reports/:id/assign',
  '/api/v1/admin/reports/entity/:type/:id',
  '/api/v1/admin/reports/moderator/mine',
  '/api/v1/admin/reports/recent',
  '/api/v1/admin/reports/stats',
  '/api/v1/admin/route-usage',
  '/api/v1/admin/share-links',
  '/api/v1/admin/share-links/:id',
  '/api/v1/admin/share-links/:id/reveal',
  '/api/v1/admin/translations',
  '/api/v1/admin/users',
  '/api/v1/admin/users/:userId',
  '/api/v1/admin/users/:userId/activity',
  '/api/v1/admin/users/:userId/ban',
  '/api/v1/admin/users/:userId/bans',
  '/api/v1/admin/users/:userId/bans/:banId/lift',
  '/api/v1/admin/users/:userId/communities',
  '/api/v1/admin/users/:userId/consents',
  '/api/v1/admin/users/:userId/conversations',
  '/api/v1/admin/users/:userId/disable-2fa',
  '/api/v1/admin/users/:userId/enable-2fa',
  '/api/v1/admin/users/:userId/media',
  '/api/v1/admin/users/:userId/password-proposals',
  '/api/v1/admin/users/:userId/preferences',
  '/api/v1/admin/users/:userId/preferences/:category',
  '/api/v1/admin/users/:userId/profile-image-candidates',
  '/api/v1/admin/users/:userId/profile-images/:kind',
  '/api/v1/admin/users/:userId/reported-messages',
  '/api/v1/admin/users/:userId/reports',
  '/api/v1/admin/users/:userId/reset-password',
  '/api/v1/admin/users/:userId/restore',
  '/api/v1/admin/users/:userId/role',
  '/api/v1/admin/users/:userId/security',
  '/api/v1/admin/users/:userId/security-events',
  '/api/v1/admin/users/:userId/sessions',
  '/api/v1/admin/users/:userId/sessions/:sessionId',
  '/api/v1/admin/users/:userId/stats',
  '/api/v1/admin/users/:userId/status',
  '/api/v1/admin/users/:userId/unlock',
  '/api/v1/admin/users/:userId/verifications',
  '/api/v1/admin/users/:userId/verify-age',
  '/api/v1/admin/users/:userId/verify-email',
  '/api/v1/admin/users/:userId/verify-phone',
  '/api/v1/admin/users/:userId/voice-consent',
  '/api/v1/admin/users/:userId/voice-profile',
  '/api/v1/affiliate/click/:token',
  '/api/v1/affiliate/register',
  '/api/v1/affiliate/stats',
  '/api/v1/affiliate/tokens',
  '/api/v1/affiliate/tokens/:id',
  '/api/v1/affiliate/track-visit',
  '/api/v1/affiliate/validate/:token',
  '/api/v1/anonymous/join/:linkId',
  '/api/v1/anonymous/leave',
  '/api/v1/anonymous/link/:identifier',
  '/api/v1/anonymous/refresh',
  '/api/v1/app/min-version',
  '/api/v1/app/shell-version',
  '/api/v1/attachments/:attachmentId',
  '/api/v1/attachments/:attachmentId/analysis',
  '/api/v1/attachments/:attachmentId/metadata',
  '/api/v1/attachments/:attachmentId/status',
  '/api/v1/attachments/:attachmentId/status-details',
  '/api/v1/attachments/:attachmentId/thumbnail',
  '/api/v1/attachments/:attachmentId/transcribe',
  '/api/v1/attachments/:attachmentId/translate',
  '/api/v1/attachments/batch/analysis',
  '/api/v1/attachments/file/*',
  '/api/v1/attachments/search',
  '/api/v1/attachments/upload',
  '/api/v1/attachments/upload-text',
  '/api/v1/auth/2fa/backup-codes',
  '/api/v1/auth/2fa/cancel',
  '/api/v1/auth/2fa/disable',
  '/api/v1/auth/2fa/enable',
  '/api/v1/auth/2fa/setup',
  '/api/v1/auth/2fa/status',
  '/api/v1/auth/2fa/verify',
  '/api/v1/auth/check-availability',
  '/api/v1/auth/forgot-password',
  '/api/v1/auth/forgot-password/phone/lookup',
  '/api/v1/auth/forgot-password/phone/resend',
  '/api/v1/auth/forgot-password/phone/verify-code',
  '/api/v1/auth/forgot-password/phone/verify-identity',
  '/api/v1/auth/login',
  '/api/v1/auth/login/2fa',
  '/api/v1/auth/logout',
  '/api/v1/auth/magic-link/request',
  '/api/v1/auth/magic-link/validate',
  '/api/v1/auth/me',
  '/api/v1/auth/phone-transfer/cancel',
  '/api/v1/auth/phone-transfer/check',
  '/api/v1/auth/phone-transfer/initiate',
  '/api/v1/auth/phone-transfer/initiate-registration',
  '/api/v1/auth/phone-transfer/resend',
  '/api/v1/auth/phone-transfer/verify',
  '/api/v1/auth/phone-transfer/verify-registration',
  '/api/v1/auth/refresh',
  '/api/v1/auth/register',
  '/api/v1/auth/resend-verification',
  '/api/v1/auth/reset-password',
  '/api/v1/auth/reset-password/verify-token',
  '/api/v1/auth/revoke-all-sessions',
  '/api/v1/auth/send-phone-code',
  '/api/v1/auth/sessions',
  '/api/v1/auth/sessions/:sessionId',
  '/api/v1/auth/verification/status',
  '/api/v1/auth/verify-email',
  '/api/v1/auth/verify-phone',
  '/api/v1/calls',
  '/api/v1/calls/:callId',
  '/api/v1/calls/:callId/participants',
  '/api/v1/calls/:callId/participants/:participantId',
  '/api/v1/calls/:callId/recordings/:recordingId/attachment',
  '/api/v1/calls/:callId/transcript',
  '/api/v1/calls/active',
  '/api/v1/calls/history',
  '/api/v1/calls/history/:callId',
  '/api/v1/communities',
  '/api/v1/communities/:id',
  '/api/v1/communities/:id/conversations',
  '/api/v1/communities/:id/conversations/:conversationId',
  '/api/v1/communities/:id/invite',
  '/api/v1/communities/:id/join',
  '/api/v1/communities/:id/leave',
  '/api/v1/communities/:id/members',
  '/api/v1/communities/:id/members/:memberId',
  '/api/v1/communities/:id/members/:memberId/role',
  '/api/v1/communities/check-identifier/:identifier',
  '/api/v1/communities/mine',
  '/api/v1/communities/search',
  '/api/v1/contacts/resolve',
  '/api/v1/conversations',
  '/api/v1/conversations/:conversationId/active-call',
  '/api/v1/conversations/:conversationId/attachments',
  '/api/v1/conversations/:conversationId/clear-history',
  '/api/v1/conversations/:conversationId/encryption',
  '/api/v1/conversations/:conversationId/encryption-status',
  '/api/v1/conversations/:conversationId/links',
  '/api/v1/conversations/:conversationId/mark-as-read',
  '/api/v1/conversations/:conversationId/mark-as-received',
  '/api/v1/conversations/:conversationId/messages/:messageId/delivery-receipt',
  '/api/v1/conversations/:conversationId/read-statuses',
  '/api/v1/conversations/:conversationId/receipts',
  '/api/v1/conversations/:conversationId/restore-for-me',
  '/api/v1/conversations/:id',
  '/api/v1/conversations/:id/analysis',
  '/api/v1/conversations/:id/card',
  '/api/v1/conversations/:id/delete-for-me',
  '/api/v1/conversations/:id/invite',
  '/api/v1/conversations/:id/leave',
  '/api/v1/conversations/:id/mark-read',
  '/api/v1/conversations/:id/mark-unread',
  '/api/v1/conversations/:id/messages',
  '/api/v1/conversations/:id/messages/:messageId',
  '/api/v1/conversations/:id/messages/:messageId/consume',
  '/api/v1/conversations/:id/messages/:messageId/pin',
  '/api/v1/conversations/:id/messages/search',
  '/api/v1/conversations/:id/new-link',
  '/api/v1/conversations/:id/participants',
  '/api/v1/conversations/:id/participants/:participantId/profile',
  '/api/v1/conversations/:id/participants/:participantId/rights',
  '/api/v1/conversations/:id/participants/:participantKey',
  '/api/v1/conversations/:id/participants/:userId',
  '/api/v1/conversations/:id/participants/:userId/ban',
  '/api/v1/conversations/:id/participants/:userId/role',
  '/api/v1/conversations/:id/participants/:userId/unban',
  '/api/v1/conversations/:id/pinned-messages',
  '/api/v1/conversations/:id/reactions',
  '/api/v1/conversations/:id/stats',
  '/api/v1/conversations/:id/status',
  '/api/v1/conversations/:id/threads/:messageId',
  '/api/v1/conversations/check-identifier/:identifier',
  '/api/v1/conversations/join/:linkId',
  '/api/v1/conversations/search',
  '/api/v1/directory/availability',
  '/api/v1/directory/blocks',
  '/api/v1/directory/blocks/:userId',
  '/api/v1/directory/contacts',
  '/api/v1/directory/friend-requests',
  '/api/v1/directory/friend-requests/:id',
  '/api/v1/directory/people',
  '/api/v1/directory/people/:handle',
  '/api/v1/directory/presence',
  '/api/v1/friend-requests',
  '/api/v1/friend-requests/:id',
  '/api/v1/friend-requests/received',
  '/api/v1/friend-requests/sent',
  '/api/v1/guest-sessions/me',
  '/api/v1/hashtags/trending',
  '/api/v1/health/circuit-breakers',
  '/api/v1/health/metrics',
  '/api/v1/health/ready',
  '/api/v1/invitations/email',
  '/api/v1/l/:token',
  '/api/v1/languages',
  '/api/v1/links',
  '/api/v1/links/:identifier',
  '/api/v1/links/:identifier/card',
  '/api/v1/links/:identifier/messages',
  '/api/v1/links/:key/members',
  '/api/v1/links/:linkId',
  '/api/v1/links/:linkId/extend',
  '/api/v1/links/:linkId/stats',
  '/api/v1/links/:linkId/toggle',
  '/api/v1/links/check-identifier/:identifier',
  '/api/v1/links/my-links',
  '/api/v1/links/stats',
  '/api/v1/me',
  '/api/v1/me/account/deletion',
  '/api/v1/me/categories',
  '/api/v1/me/categories/:categoryId',
  '/api/v1/me/categories/reorder',
  '/api/v1/me/consents',
  '/api/v1/me/consents/:purpose',
  '/api/v1/me/delete-account',
  '/api/v1/me/delete-account/cancel',
  '/api/v1/me/delete-account/confirm',
  '/api/v1/me/delete-account/delete-now',
  '/api/v1/me/engagement',
  '/api/v1/me/export',
  '/api/v1/me/meesh/mint',
  '/api/v1/me/onboarding',
  '/api/v1/me/permissions',
  '/api/v1/me/preferences',
  '/api/v1/me/preferences/application',
  '/api/v1/me/preferences/audio',
  '/api/v1/me/preferences/categories',
  '/api/v1/me/preferences/categories/:categoryId',
  '/api/v1/me/preferences/categories/reorder',
  '/api/v1/me/preferences/document',
  '/api/v1/me/preferences/encryption',
  '/api/v1/me/preferences/message',
  '/api/v1/me/preferences/notification',
  '/api/v1/me/preferences/privacy',
  '/api/v1/me/preferences/video',
  '/api/v1/me/starred-messages',
  '/api/v1/me/starred-messages/:messageId',
  '/api/v1/me/stickers',
  '/api/v1/me/stickers/:stickerId',
  '/api/v1/me/stickers/:stickerId/use',
  '/api/v1/me/terms',
  '/api/v1/mentions/me',
  '/api/v1/mentions/messages/:messageId',
  '/api/v1/mentions/suggestions',
  '/api/v1/messages/:messageId',
  '/api/v1/messages/:messageId/delete-for-me',
  '/api/v1/messages/:messageId/read-status',
  '/api/v1/messages/:messageId/restore-for-me',
  '/api/v1/messages/:messageId/status-details',
  '/api/v1/messages/:messageId/translations',
  '/api/v1/messages/bulk/delete-for-me',
  '/api/v1/notifications',
  '/api/v1/notifications/:id',
  '/api/v1/notifications/:id/read',
  '/api/v1/notifications/admin/clear-all',
  '/api/v1/notifications/conversation/:conversationId/read',
  '/api/v1/notifications/counts',
  '/api/v1/notifications/post/:postId/read',
  '/api/v1/notifications/read',
  '/api/v1/notifications/read-all',
  '/api/v1/notifications/read-by-types',
  '/api/v1/notifications/unread-count',
  '/api/v1/posts',
  '/api/v1/posts/:postId',
  '/api/v1/posts/:postId/anonymous-view',
  '/api/v1/posts/:postId/bookmark',
  '/api/v1/posts/:postId/comments',
  '/api/v1/posts/:postId/comments/:commentId',
  '/api/v1/posts/:postId/comments/:commentId/like',
  '/api/v1/posts/:postId/comments/:commentId/replies',
  '/api/v1/posts/:postId/comments/:commentId/translate',
  '/api/v1/posts/:postId/downloads',
  '/api/v1/posts/:postId/impression',
  '/api/v1/posts/:postId/interactions',
  '/api/v1/posts/:postId/like',
  '/api/v1/posts/:postId/media/:mediaId/export',
  '/api/v1/posts/:postId/objects/:objectId/responses',
  '/api/v1/posts/:postId/pin',
  '/api/v1/posts/:postId/repost',
  '/api/v1/posts/:postId/republish',
  '/api/v1/posts/:postId/share',
  '/api/v1/posts/:postId/translate',
  '/api/v1/posts/:postId/view',
  '/api/v1/posts/:postId/views',
  '/api/v1/posts/bookmarks',
  '/api/v1/posts/community/:communityId',
  '/api/v1/posts/engagement/batch',
  '/api/v1/posts/feed',
  '/api/v1/posts/feed/reels',
  '/api/v1/posts/feed/statuses',
  '/api/v1/posts/feed/statuses/discover',
  '/api/v1/posts/feed/stories',
  '/api/v1/posts/from-attachment',
  '/api/v1/posts/hashtag/:tag',
  '/api/v1/posts/impressions/batch',
  '/api/v1/posts/media/:mediaId',
  '/api/v1/posts/media/:mediaId/caption/translate',
  '/api/v1/posts/nearby',
  '/api/v1/posts/nearby/density',
  '/api/v1/posts/stories/mine',
  '/api/v1/posts/user/:userId',
  '/api/v1/reactions',
  '/api/v1/reactions/:messageId',
  '/api/v1/reactions/:messageId/:emoji',
  '/api/v1/reactions/user/:userId',
  '/api/v1/reports',
  '/api/v1/signal/keys',
  '/api/v1/signal/keys/:userId',
  '/api/v1/signal/session/establish',
  '/api/v1/social/events',
  '/api/v1/social/posts',
  '/api/v1/socketio/disconnect-user',
  '/api/v1/socketio/stats',
  '/api/v1/sounds/:id',
  '/api/v1/sounds/:id/posts',
  '/api/v1/sounds/mine',
  '/api/v1/static/:filename',
  '/api/v1/status-metrics',
  '/api/v1/status-metrics/reset',
  '/api/v1/stories/audio',
  '/api/v1/sync',
  '/api/v1/tracking-links',
  '/api/v1/tracking-links/:token',
  '/api/v1/tracking-links/:token/click',
  '/api/v1/tracking-links/:token/clicks',
  '/api/v1/tracking-links/:token/deactivate',
  '/api/v1/tracking-links/:token/redirect-status',
  '/api/v1/tracking-links/:token/resolve',
  '/api/v1/tracking-links/:token/stats',
  '/api/v1/tracking-links/admin/:token/clicks',
  '/api/v1/tracking-links/admin/all',
  '/api/v1/tracking-links/check-token/:token',
  '/api/v1/tracking-links/conversation/:conversationId',
  '/api/v1/tracking-links/stats',
  '/api/v1/tracking-links/user/me',
  '/api/v1/translate',
  '/api/v1/translate-blocking',
  '/api/v1/translate/jobs/:jobId',
  '/api/v1/u/:username',
  '/api/v1/uploads',
  '/api/v1/uploads/*',
  '/api/v1/user-preferences/communities',
  '/api/v1/user-preferences/communities/:communityId',
  '/api/v1/user-preferences/communities/reorder',
  '/api/v1/user-preferences/conversations',
  '/api/v1/user-preferences/conversations/:conversationId',
  '/api/v1/user-preferences/reorder',
  '/api/v1/user/deleted-conversations',
  '/api/v1/users/:id',
  '/api/v1/users/:userId/affiliate-token',
  '/api/v1/users/:userId/block',
  '/api/v1/users/:userId/stats',
  '/api/v1/users/email/:email',
  '/api/v1/users/friend-requests',
  '/api/v1/users/id/:id',
  '/api/v1/users/me',
  '/api/v1/users/me/avatar',
  '/api/v1/users/me/banner',
  '/api/v1/users/me/blocked-users',
  '/api/v1/users/me/change-email',
  '/api/v1/users/me/change-phone',
  '/api/v1/users/me/contact-changes',
  '/api/v1/users/me/contact-changes/:channel/resend',
  '/api/v1/users/me/contact-changes/:channel/verify',
  '/api/v1/users/me/contacts',
  '/api/v1/users/me/contacts/match',
  '/api/v1/users/me/contacts/sync',
  '/api/v1/users/me/dashboard-stats',
  '/api/v1/users/me/devices',
  '/api/v1/users/me/devices/:deviceId',
  '/api/v1/users/me/password',
  '/api/v1/users/me/referral-code',
  '/api/v1/users/me/resend-email-change-verification',
  '/api/v1/users/me/stats',
  '/api/v1/users/me/stats/achievements',
  '/api/v1/users/me/stats/timeline',
  '/api/v1/users/me/username',
  '/api/v1/users/me/verify-email-change',
  '/api/v1/users/me/verify-phone-change',
  '/api/v1/users/phone/:phone',
  '/api/v1/users/presence',
  '/api/v1/users/register-device-token',
  '/api/v1/users/search',
  '/api/v1/voice/admin/metrics',
  '/api/v1/voice/analysis',
  '/api/v1/voice/analyze',
  '/api/v1/voice/compare',
  '/api/v1/voice/feedback',
  '/api/v1/voice/history',
  '/api/v1/voice/job/:jobId',
  '/api/v1/voice/languages',
  '/api/v1/voice/profile',
  '/api/v1/voice/profile/:profileId',
  '/api/v1/voice/profile/consent',
  '/api/v1/voice/profile/register',
  '/api/v1/voice/transcribe',
  '/api/v1/voice/translate',
  '/api/v1/voice/translate/async',
  '/attachments/:attachmentId/analysis',
  '/attachments/batch/analysis',
  '/health',
  '/voice/analysis',
] as const;

/** Tout chemin réellement servi par la passerelle, dérivé du manifeste — jamais élargi à la main. */
export type ApiPath = (typeof API_PATH_TEMPLATES)[number];

/** Les verbes HTTP acceptés par chemin — `Record` total : un chemin sans entrée ne compile pas. */
export const API_PATH_METHODS: Readonly<Record<ApiPath, readonly HttpMethod[]>> = {
  '/api/attachments/file/*': ['GET'],
  '/api/conversations/:conversationId/clear-history': ['POST'],
  '/api/conversations/:conversationId/delete-for-me': ['DELETE'],
  '/api/conversations/:conversationId/restore-for-me': ['POST'],
  '/api/messages/:messageId/delete-for-me': ['DELETE'],
  '/api/messages/:messageId/restore-for-me': ['POST'],
  '/api/messages/bulk/delete-for-me': ['DELETE'],
  '/api/socketio/disconnect-user': ['POST'],
  '/api/socketio/stats': ['GET'],
  '/api/user/deleted-conversations': ['GET'],
  '/api/v1/account/deletion/resolve': ['POST'],
  '/api/v1/admin/agent/archetypes': ['GET'],
  '/api/v1/admin/agent/configs': ['GET'],
  '/api/v1/admin/agent/configs/:conversationId': ['GET', 'PUT', 'DELETE'],
  '/api/v1/admin/agent/configs/:conversationId/live': ['GET'],
  '/api/v1/admin/agent/configs/:conversationId/messages': ['GET'],
  '/api/v1/admin/agent/configs/:conversationId/roles': ['GET'],
  '/api/v1/admin/agent/configs/:conversationId/schedule': ['GET'],
  '/api/v1/admin/agent/configs/:conversationId/stop': ['POST'],
  '/api/v1/admin/agent/configs/:conversationId/summary': ['GET'],
  '/api/v1/admin/agent/configs/:conversationId/trigger': ['POST'],
  '/api/v1/admin/agent/delivery-queue': ['GET'],
  '/api/v1/admin/agent/delivery-queue/:id': ['PATCH', 'DELETE'],
  '/api/v1/admin/agent/global-config': ['GET', 'PUT'],
  '/api/v1/admin/agent/llm': ['GET', 'PUT'],
  '/api/v1/admin/agent/recent-activity': ['GET'],
  '/api/v1/admin/agent/reset': ['DELETE'],
  '/api/v1/admin/agent/reset/conversation/:conversationId': ['DELETE'],
  '/api/v1/admin/agent/reset/user/:userId': ['DELETE'],
  '/api/v1/admin/agent/roles/:conversationId/:userId/assign': ['POST'],
  '/api/v1/admin/agent/roles/:conversationId/:userId/unlock': ['POST'],
  '/api/v1/admin/agent/scan-logs': ['GET'],
  '/api/v1/admin/agent/scan-logs/:logId': ['GET'],
  '/api/v1/admin/agent/scan-logs/stats': ['GET'],
  '/api/v1/admin/agent/stats': ['GET'],
  '/api/v1/admin/agent/topics': ['GET', 'POST'],
  '/api/v1/admin/agent/topics/:id': ['GET', 'PATCH', 'DELETE'],
  '/api/v1/admin/agent/topics/:id/test': ['POST'],
  '/api/v1/admin/analytics/calls': ['GET'],
  '/api/v1/admin/analytics/hourly-activity': ['GET'],
  '/api/v1/admin/analytics/kpis': ['GET'],
  '/api/v1/admin/analytics/language-distribution': ['GET'],
  '/api/v1/admin/analytics/message-types': ['GET'],
  '/api/v1/admin/analytics/realtime': ['GET'],
  '/api/v1/admin/analytics/user-distribution': ['GET'],
  '/api/v1/admin/analytics/volume-timeline': ['GET'],
  '/api/v1/admin/anonymous-users': ['GET'],
  '/api/v1/admin/anonymous-users/:participantId': ['GET'],
  '/api/v1/admin/broadcasts': ['GET', 'POST'],
  '/api/v1/admin/broadcasts/:id': ['GET', 'PUT', 'DELETE'],
  '/api/v1/admin/broadcasts/:id/preview': ['POST'],
  '/api/v1/admin/broadcasts/:id/send': ['POST'],
  '/api/v1/admin/broadcasts/:id/send-inapp': ['POST'],
  '/api/v1/admin/communities': ['GET'],
  '/api/v1/admin/conversations': ['GET'],
  '/api/v1/admin/conversations/:conversationId': ['PATCH'],
  '/api/v1/admin/conversations/:conversationId/messages': ['GET'],
  '/api/v1/admin/conversations/:conversationId/participants': ['GET'],
  '/api/v1/admin/conversations/:conversationId/participants/:userId': ['PATCH'],
  '/api/v1/admin/conversations/:conversationId/participants/:userId/remove': ['POST'],
  '/api/v1/admin/dashboard': ['GET'],
  '/api/v1/admin/dashboard/invalidate-cache': ['POST'],
  '/api/v1/admin/invitations': ['GET'],
  '/api/v1/admin/invitations/:id': ['GET', 'PATCH'],
  '/api/v1/admin/invitations/stats': ['GET'],
  '/api/v1/admin/invitations/timeline/daily': ['GET'],
  '/api/v1/admin/languages/stats': ['GET'],
  '/api/v1/admin/languages/timeline': ['GET'],
  '/api/v1/admin/languages/translation-accuracy': ['GET'],
  '/api/v1/admin/me/permissions': ['GET'],
  '/api/v1/admin/messages': ['GET'],
  '/api/v1/admin/messages/engagement': ['GET'],
  '/api/v1/admin/messages/stats': ['GET'],
  '/api/v1/admin/messages/trends': ['GET'],
  '/api/v1/admin/posts': ['GET'],
  '/api/v1/admin/posts/:postId': ['GET', 'DELETE'],
  '/api/v1/admin/posts/stats': ['GET'],
  '/api/v1/admin/ranking': ['GET'],
  '/api/v1/admin/reports': ['GET', 'POST'],
  '/api/v1/admin/reports/:id': ['GET', 'PATCH', 'DELETE'],
  '/api/v1/admin/reports/:id/assign': ['POST'],
  '/api/v1/admin/reports/entity/:type/:id': ['GET'],
  '/api/v1/admin/reports/moderator/mine': ['GET'],
  '/api/v1/admin/reports/recent': ['GET'],
  '/api/v1/admin/reports/stats': ['GET'],
  '/api/v1/admin/route-usage': ['GET'],
  '/api/v1/admin/share-links': ['GET'],
  '/api/v1/admin/share-links/:id': ['PATCH', 'DELETE'],
  '/api/v1/admin/share-links/:id/reveal': ['POST'],
  '/api/v1/admin/translations': ['GET'],
  '/api/v1/admin/users': ['GET', 'POST'],
  '/api/v1/admin/users/:userId': ['GET', 'PATCH', 'DELETE'],
  '/api/v1/admin/users/:userId/activity': ['GET'],
  '/api/v1/admin/users/:userId/ban': ['POST'],
  '/api/v1/admin/users/:userId/bans': ['GET'],
  '/api/v1/admin/users/:userId/bans/:banId/lift': ['POST'],
  '/api/v1/admin/users/:userId/communities': ['GET'],
  '/api/v1/admin/users/:userId/consents': ['PATCH'],
  '/api/v1/admin/users/:userId/conversations': ['GET'],
  '/api/v1/admin/users/:userId/disable-2fa': ['POST'],
  '/api/v1/admin/users/:userId/enable-2fa': ['POST'],
  '/api/v1/admin/users/:userId/media': ['GET'],
  '/api/v1/admin/users/:userId/password-proposals': ['POST'],
  '/api/v1/admin/users/:userId/preferences': ['GET'],
  '/api/v1/admin/users/:userId/preferences/:category': ['PATCH'],
  '/api/v1/admin/users/:userId/profile-image-candidates': ['GET'],
  '/api/v1/admin/users/:userId/profile-images/:kind': ['PUT'],
  '/api/v1/admin/users/:userId/reported-messages': ['GET'],
  '/api/v1/admin/users/:userId/reports': ['GET'],
  '/api/v1/admin/users/:userId/reset-password': ['POST'],
  '/api/v1/admin/users/:userId/restore': ['POST'],
  '/api/v1/admin/users/:userId/role': ['PATCH'],
  '/api/v1/admin/users/:userId/security': ['PATCH'],
  '/api/v1/admin/users/:userId/security-events': ['GET'],
  '/api/v1/admin/users/:userId/sessions': ['GET'],
  '/api/v1/admin/users/:userId/sessions/:sessionId': ['DELETE'],
  '/api/v1/admin/users/:userId/stats': ['GET'],
  '/api/v1/admin/users/:userId/status': ['PATCH'],
  '/api/v1/admin/users/:userId/unlock': ['POST'],
  '/api/v1/admin/users/:userId/verifications': ['PATCH'],
  '/api/v1/admin/users/:userId/verify-age': ['POST'],
  '/api/v1/admin/users/:userId/verify-email': ['POST'],
  '/api/v1/admin/users/:userId/verify-phone': ['POST'],
  '/api/v1/admin/users/:userId/voice-consent': ['POST'],
  '/api/v1/admin/users/:userId/voice-profile': ['GET'],
  '/api/v1/affiliate/click/:token': ['POST'],
  '/api/v1/affiliate/register': ['POST'],
  '/api/v1/affiliate/stats': ['GET'],
  '/api/v1/affiliate/tokens': ['GET', 'POST'],
  '/api/v1/affiliate/tokens/:id': ['DELETE'],
  '/api/v1/affiliate/track-visit': ['POST'],
  '/api/v1/affiliate/validate/:token': ['GET'],
  '/api/v1/anonymous/join/:linkId': ['POST'],
  '/api/v1/anonymous/leave': ['POST'],
  '/api/v1/anonymous/link/:identifier': ['GET'],
  '/api/v1/anonymous/refresh': ['POST'],
  '/api/v1/app/min-version': ['GET'],
  '/api/v1/app/shell-version': ['GET'],
  '/api/v1/attachments/:attachmentId': ['GET', 'DELETE'],
  '/api/v1/attachments/:attachmentId/analysis': ['GET', 'POST'],
  '/api/v1/attachments/:attachmentId/metadata': ['GET'],
  '/api/v1/attachments/:attachmentId/status': ['POST'],
  '/api/v1/attachments/:attachmentId/status-details': ['GET'],
  '/api/v1/attachments/:attachmentId/thumbnail': ['GET'],
  '/api/v1/attachments/:attachmentId/transcribe': ['POST'],
  '/api/v1/attachments/:attachmentId/translate': ['POST'],
  '/api/v1/attachments/batch/analysis': ['POST'],
  '/api/v1/attachments/file/*': ['GET'],
  '/api/v1/attachments/search': ['GET'],
  '/api/v1/attachments/upload': ['POST'],
  '/api/v1/attachments/upload-text': ['POST'],
  '/api/v1/auth/2fa/backup-codes': ['POST'],
  '/api/v1/auth/2fa/cancel': ['POST'],
  '/api/v1/auth/2fa/disable': ['POST'],
  '/api/v1/auth/2fa/enable': ['POST'],
  '/api/v1/auth/2fa/setup': ['POST'],
  '/api/v1/auth/2fa/status': ['GET'],
  '/api/v1/auth/2fa/verify': ['POST'],
  '/api/v1/auth/check-availability': ['GET'],
  '/api/v1/auth/forgot-password': ['POST'],
  '/api/v1/auth/forgot-password/phone/lookup': ['POST'],
  '/api/v1/auth/forgot-password/phone/resend': ['POST'],
  '/api/v1/auth/forgot-password/phone/verify-code': ['POST'],
  '/api/v1/auth/forgot-password/phone/verify-identity': ['POST'],
  '/api/v1/auth/login': ['POST'],
  '/api/v1/auth/login/2fa': ['POST'],
  '/api/v1/auth/logout': ['POST'],
  '/api/v1/auth/magic-link/request': ['POST'],
  '/api/v1/auth/magic-link/validate': ['POST'],
  '/api/v1/auth/me': ['GET'],
  '/api/v1/auth/phone-transfer/cancel': ['POST'],
  '/api/v1/auth/phone-transfer/check': ['POST'],
  '/api/v1/auth/phone-transfer/initiate': ['POST'],
  '/api/v1/auth/phone-transfer/initiate-registration': ['POST'],
  '/api/v1/auth/phone-transfer/resend': ['POST'],
  '/api/v1/auth/phone-transfer/verify': ['POST'],
  '/api/v1/auth/phone-transfer/verify-registration': ['POST'],
  '/api/v1/auth/refresh': ['POST'],
  '/api/v1/auth/register': ['POST'],
  '/api/v1/auth/resend-verification': ['POST'],
  '/api/v1/auth/reset-password': ['POST'],
  '/api/v1/auth/reset-password/verify-token': ['GET'],
  '/api/v1/auth/revoke-all-sessions': ['GET'],
  '/api/v1/auth/send-phone-code': ['POST'],
  '/api/v1/auth/sessions': ['GET', 'DELETE'],
  '/api/v1/auth/sessions/:sessionId': ['DELETE'],
  '/api/v1/auth/verification/status': ['POST'],
  '/api/v1/auth/verify-email': ['POST'],
  '/api/v1/auth/verify-phone': ['POST'],
  '/api/v1/calls': ['POST'],
  '/api/v1/calls/:callId': ['GET', 'DELETE'],
  '/api/v1/calls/:callId/participants': ['POST'],
  '/api/v1/calls/:callId/participants/:participantId': ['DELETE'],
  '/api/v1/calls/:callId/recordings/:recordingId/attachment': ['POST'],
  '/api/v1/calls/:callId/transcript': ['GET'],
  '/api/v1/calls/active': ['GET'],
  '/api/v1/calls/history': ['GET', 'DELETE'],
  '/api/v1/calls/history/:callId': ['DELETE'],
  '/api/v1/communities': ['GET', 'POST'],
  '/api/v1/communities/:id': ['GET', 'PUT', 'DELETE'],
  '/api/v1/communities/:id/conversations': ['GET'],
  '/api/v1/communities/:id/conversations/:conversationId': ['POST'],
  '/api/v1/communities/:id/invite': ['POST'],
  '/api/v1/communities/:id/join': ['POST'],
  '/api/v1/communities/:id/leave': ['POST'],
  '/api/v1/communities/:id/members': ['GET', 'POST'],
  '/api/v1/communities/:id/members/:memberId': ['DELETE'],
  '/api/v1/communities/:id/members/:memberId/role': ['PATCH'],
  '/api/v1/communities/check-identifier/:identifier': ['GET'],
  '/api/v1/communities/mine': ['GET'],
  '/api/v1/communities/search': ['GET'],
  '/api/v1/contacts/resolve': ['POST'],
  '/api/v1/conversations': ['GET', 'POST'],
  '/api/v1/conversations/:conversationId/active-call': ['GET'],
  '/api/v1/conversations/:conversationId/attachments': ['GET'],
  '/api/v1/conversations/:conversationId/clear-history': ['POST'],
  '/api/v1/conversations/:conversationId/encryption': ['POST'],
  '/api/v1/conversations/:conversationId/encryption-status': ['GET'],
  '/api/v1/conversations/:conversationId/links': ['GET'],
  '/api/v1/conversations/:conversationId/mark-as-read': ['POST'],
  '/api/v1/conversations/:conversationId/mark-as-received': ['POST'],
  '/api/v1/conversations/:conversationId/messages/:messageId/delivery-receipt': ['POST'],
  '/api/v1/conversations/:conversationId/read-statuses': ['GET'],
  '/api/v1/conversations/:conversationId/receipts': ['GET', 'POST'],
  '/api/v1/conversations/:conversationId/restore-for-me': ['POST'],
  '/api/v1/conversations/:id': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/conversations/:id/analysis': ['GET'],
  '/api/v1/conversations/:id/card': ['GET'],
  '/api/v1/conversations/:id/delete-for-me': ['DELETE'],
  '/api/v1/conversations/:id/invite': ['POST'],
  '/api/v1/conversations/:id/leave': ['POST'],
  '/api/v1/conversations/:id/mark-read': ['POST'],
  '/api/v1/conversations/:id/mark-unread': ['POST'],
  '/api/v1/conversations/:id/messages': ['GET', 'POST'],
  '/api/v1/conversations/:id/messages/:messageId': ['PUT', 'DELETE'],
  '/api/v1/conversations/:id/messages/:messageId/consume': ['POST'],
  '/api/v1/conversations/:id/messages/:messageId/pin': ['PUT', 'DELETE'],
  '/api/v1/conversations/:id/messages/search': ['GET'],
  '/api/v1/conversations/:id/new-link': ['POST'],
  '/api/v1/conversations/:id/participants': ['GET', 'POST'],
  '/api/v1/conversations/:id/participants/:participantId/profile': ['GET'],
  '/api/v1/conversations/:id/participants/:participantId/rights': ['PATCH'],
  '/api/v1/conversations/:id/participants/:participantKey': ['PATCH'],
  '/api/v1/conversations/:id/participants/:userId': ['DELETE'],
  '/api/v1/conversations/:id/participants/:userId/ban': ['PATCH'],
  '/api/v1/conversations/:id/participants/:userId/role': ['PATCH'],
  '/api/v1/conversations/:id/participants/:userId/unban': ['PATCH'],
  '/api/v1/conversations/:id/pinned-messages': ['GET'],
  '/api/v1/conversations/:id/reactions': ['GET'],
  '/api/v1/conversations/:id/stats': ['GET'],
  '/api/v1/conversations/:id/status': ['GET'],
  '/api/v1/conversations/:id/threads/:messageId': ['GET'],
  '/api/v1/conversations/check-identifier/:identifier': ['GET'],
  '/api/v1/conversations/join/:linkId': ['POST'],
  '/api/v1/conversations/search': ['GET'],
  '/api/v1/directory/availability': ['GET'],
  '/api/v1/directory/blocks': ['GET'],
  '/api/v1/directory/blocks/:userId': ['PUT', 'DELETE'],
  '/api/v1/directory/contacts': ['GET', 'PUT', 'PATCH'],
  '/api/v1/directory/friend-requests': ['GET', 'POST'],
  '/api/v1/directory/friend-requests/:id': ['PATCH'],
  '/api/v1/directory/people': ['GET'],
  '/api/v1/directory/people/:handle': ['GET'],
  '/api/v1/directory/presence': ['GET'],
  '/api/v1/friend-requests': ['POST'],
  '/api/v1/friend-requests/:id': ['PATCH', 'DELETE'],
  '/api/v1/friend-requests/received': ['GET'],
  '/api/v1/friend-requests/sent': ['GET'],
  '/api/v1/guest-sessions/me': ['PATCH', 'DELETE'],
  '/api/v1/hashtags/trending': ['GET'],
  '/api/v1/health/circuit-breakers': ['GET'],
  '/api/v1/health/metrics': ['GET'],
  '/api/v1/health/ready': ['GET'],
  '/api/v1/invitations/email': ['POST'],
  '/api/v1/l/:token': ['GET'],
  '/api/v1/languages': ['GET'],
  '/api/v1/links': ['GET', 'POST'],
  '/api/v1/links/:identifier': ['GET'],
  '/api/v1/links/:identifier/card': ['GET'],
  '/api/v1/links/:identifier/messages': ['GET', 'POST'],
  '/api/v1/links/:key/members': ['POST'],
  '/api/v1/links/:linkId': ['PATCH', 'DELETE'],
  '/api/v1/links/:linkId/extend': ['PATCH'],
  '/api/v1/links/:linkId/stats': ['GET'],
  '/api/v1/links/:linkId/toggle': ['PATCH'],
  '/api/v1/links/check-identifier/:identifier': ['GET'],
  '/api/v1/links/my-links': ['GET'],
  '/api/v1/links/stats': ['GET'],
  '/api/v1/me': ['GET'],
  '/api/v1/me/account/deletion': ['GET', 'POST'],
  '/api/v1/me/categories': ['GET', 'POST'],
  '/api/v1/me/categories/:categoryId': ['PATCH', 'DELETE'],
  '/api/v1/me/categories/reorder': ['POST'],
  '/api/v1/me/consents': ['GET'],
  '/api/v1/me/consents/:purpose': ['PUT'],
  '/api/v1/me/delete-account': ['DELETE'],
  '/api/v1/me/delete-account/cancel': ['GET'],
  '/api/v1/me/delete-account/confirm': ['GET'],
  '/api/v1/me/delete-account/delete-now': ['GET'],
  '/api/v1/me/engagement': ['GET'],
  '/api/v1/me/export': ['GET'],
  '/api/v1/me/meesh/mint': ['POST'],
  '/api/v1/me/onboarding': ['GET', 'PATCH'],
  '/api/v1/me/permissions': ['GET'],
  '/api/v1/me/preferences': ['GET', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/application': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/audio': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/categories': ['GET', 'POST'],
  '/api/v1/me/preferences/categories/:categoryId': ['GET', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/categories/reorder': ['POST'],
  '/api/v1/me/preferences/document': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/encryption': ['GET'],
  '/api/v1/me/preferences/message': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/notification': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/privacy': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/preferences/video': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/me/starred-messages': ['GET'],
  '/api/v1/me/starred-messages/:messageId': ['PUT', 'DELETE'],
  '/api/v1/me/stickers': ['GET', 'POST'],
  '/api/v1/me/stickers/:stickerId': ['DELETE'],
  '/api/v1/me/stickers/:stickerId/use': ['POST'],
  '/api/v1/me/terms': ['GET', 'PUT'],
  '/api/v1/mentions/me': ['GET'],
  '/api/v1/mentions/messages/:messageId': ['GET'],
  '/api/v1/mentions/suggestions': ['GET'],
  '/api/v1/messages/:messageId': ['GET', 'PUT', 'PATCH', 'DELETE'],
  '/api/v1/messages/:messageId/delete-for-me': ['DELETE'],
  '/api/v1/messages/:messageId/read-status': ['GET'],
  '/api/v1/messages/:messageId/restore-for-me': ['POST'],
  '/api/v1/messages/:messageId/status-details': ['GET'],
  '/api/v1/messages/:messageId/translations': ['GET'],
  '/api/v1/messages/bulk/delete-for-me': ['DELETE'],
  '/api/v1/notifications': ['GET'],
  '/api/v1/notifications/:id': ['DELETE'],
  '/api/v1/notifications/:id/read': ['POST'],
  '/api/v1/notifications/admin/clear-all': ['DELETE'],
  '/api/v1/notifications/conversation/:conversationId/read': ['POST'],
  '/api/v1/notifications/counts': ['GET'],
  '/api/v1/notifications/post/:postId/read': ['POST'],
  '/api/v1/notifications/read': ['DELETE'],
  '/api/v1/notifications/read-all': ['POST'],
  '/api/v1/notifications/read-by-types': ['POST'],
  '/api/v1/notifications/unread-count': ['GET'],
  '/api/v1/posts': ['POST'],
  '/api/v1/posts/:postId': ['GET', 'PUT', 'DELETE'],
  '/api/v1/posts/:postId/anonymous-view': ['POST'],
  '/api/v1/posts/:postId/bookmark': ['POST', 'DELETE'],
  '/api/v1/posts/:postId/comments': ['GET', 'POST'],
  '/api/v1/posts/:postId/comments/:commentId': ['PATCH', 'DELETE'],
  '/api/v1/posts/:postId/comments/:commentId/like': ['POST', 'DELETE'],
  '/api/v1/posts/:postId/comments/:commentId/replies': ['GET'],
  '/api/v1/posts/:postId/comments/:commentId/translate': ['POST'],
  '/api/v1/posts/:postId/downloads': ['POST'],
  '/api/v1/posts/:postId/impression': ['POST'],
  '/api/v1/posts/:postId/interactions': ['GET'],
  '/api/v1/posts/:postId/like': ['POST', 'DELETE'],
  '/api/v1/posts/:postId/media/:mediaId/export': ['GET'],
  '/api/v1/posts/:postId/objects/:objectId/responses': ['GET', 'POST', 'DELETE'],
  '/api/v1/posts/:postId/pin': ['POST', 'DELETE'],
  '/api/v1/posts/:postId/repost': ['POST'],
  '/api/v1/posts/:postId/republish': ['POST'],
  '/api/v1/posts/:postId/share': ['POST'],
  '/api/v1/posts/:postId/translate': ['POST'],
  '/api/v1/posts/:postId/view': ['POST'],
  '/api/v1/posts/:postId/views': ['GET'],
  '/api/v1/posts/bookmarks': ['GET'],
  '/api/v1/posts/community/:communityId': ['GET'],
  '/api/v1/posts/engagement/batch': ['POST'],
  '/api/v1/posts/feed': ['GET'],
  '/api/v1/posts/feed/reels': ['GET'],
  '/api/v1/posts/feed/statuses': ['GET'],
  '/api/v1/posts/feed/statuses/discover': ['GET'],
  '/api/v1/posts/feed/stories': ['GET'],
  '/api/v1/posts/from-attachment': ['POST'],
  '/api/v1/posts/hashtag/:tag': ['GET'],
  '/api/v1/posts/impressions/batch': ['POST'],
  '/api/v1/posts/media/:mediaId': ['DELETE'],
  '/api/v1/posts/media/:mediaId/caption/translate': ['POST'],
  '/api/v1/posts/nearby': ['GET'],
  '/api/v1/posts/nearby/density': ['GET'],
  '/api/v1/posts/stories/mine': ['GET'],
  '/api/v1/posts/user/:userId': ['GET'],
  '/api/v1/reactions': ['POST'],
  '/api/v1/reactions/:messageId': ['GET'],
  '/api/v1/reactions/:messageId/:emoji': ['DELETE'],
  '/api/v1/reactions/user/:userId': ['GET'],
  '/api/v1/reports': ['POST'],
  '/api/v1/signal/keys': ['POST'],
  '/api/v1/signal/keys/:userId': ['GET'],
  '/api/v1/signal/session/establish': ['POST'],
  '/api/v1/social/events': ['POST'],
  '/api/v1/social/posts': ['GET'],
  '/api/v1/socketio/disconnect-user': ['POST'],
  '/api/v1/socketio/stats': ['GET'],
  '/api/v1/sounds/:id': ['GET', 'PATCH'],
  '/api/v1/sounds/:id/posts': ['GET'],
  '/api/v1/sounds/mine': ['GET'],
  '/api/v1/static/:filename': ['GET'],
  '/api/v1/status-metrics': ['GET'],
  '/api/v1/status-metrics/reset': ['POST'],
  '/api/v1/stories/audio': ['GET'],
  '/api/v1/sync': ['GET'],
  '/api/v1/tracking-links': ['POST'],
  '/api/v1/tracking-links/:token': ['GET', 'PATCH', 'DELETE'],
  '/api/v1/tracking-links/:token/click': ['POST'],
  '/api/v1/tracking-links/:token/clicks': ['GET'],
  '/api/v1/tracking-links/:token/deactivate': ['PATCH'],
  '/api/v1/tracking-links/:token/redirect-status': ['POST'],
  '/api/v1/tracking-links/:token/resolve': ['GET'],
  '/api/v1/tracking-links/:token/stats': ['GET'],
  '/api/v1/tracking-links/admin/:token/clicks': ['GET'],
  '/api/v1/tracking-links/admin/all': ['GET'],
  '/api/v1/tracking-links/check-token/:token': ['GET'],
  '/api/v1/tracking-links/conversation/:conversationId': ['GET'],
  '/api/v1/tracking-links/stats': ['GET'],
  '/api/v1/tracking-links/user/me': ['GET'],
  '/api/v1/translate': ['POST'],
  '/api/v1/translate-blocking': ['POST'],
  '/api/v1/translate/jobs/:jobId': ['GET', 'DELETE'],
  '/api/v1/u/:username': ['GET'],
  '/api/v1/uploads': ['POST'],
  '/api/v1/uploads/*': ['POST', 'PATCH', 'DELETE'],
  '/api/v1/user-preferences/communities': ['GET'],
  '/api/v1/user-preferences/communities/:communityId': ['GET', 'PUT', 'DELETE'],
  '/api/v1/user-preferences/communities/reorder': ['POST'],
  '/api/v1/user-preferences/conversations': ['GET'],
  '/api/v1/user-preferences/conversations/:conversationId': ['GET', 'PUT', 'DELETE'],
  '/api/v1/user-preferences/reorder': ['POST'],
  '/api/v1/user/deleted-conversations': ['GET'],
  '/api/v1/users/:id': ['GET'],
  '/api/v1/users/:userId/affiliate-token': ['GET'],
  '/api/v1/users/:userId/block': ['POST', 'DELETE'],
  '/api/v1/users/:userId/stats': ['GET'],
  '/api/v1/users/email/:email': ['GET'],
  '/api/v1/users/friend-requests': ['GET'],
  '/api/v1/users/id/:id': ['GET'],
  '/api/v1/users/me': ['PATCH'],
  '/api/v1/users/me/avatar': ['PATCH'],
  '/api/v1/users/me/banner': ['PATCH'],
  '/api/v1/users/me/blocked-users': ['GET'],
  '/api/v1/users/me/change-email': ['POST'],
  '/api/v1/users/me/change-phone': ['POST'],
  '/api/v1/users/me/contact-changes': ['GET', 'POST'],
  '/api/v1/users/me/contact-changes/:channel/resend': ['POST'],
  '/api/v1/users/me/contact-changes/:channel/verify': ['POST'],
  '/api/v1/users/me/contacts': ['GET'],
  '/api/v1/users/me/contacts/match': ['POST'],
  '/api/v1/users/me/contacts/sync': ['POST'],
  '/api/v1/users/me/dashboard-stats': ['GET'],
  '/api/v1/users/me/devices': ['GET'],
  '/api/v1/users/me/devices/:deviceId': ['DELETE'],
  '/api/v1/users/me/password': ['PATCH'],
  '/api/v1/users/me/referral-code': ['GET'],
  '/api/v1/users/me/resend-email-change-verification': ['POST'],
  '/api/v1/users/me/stats': ['GET'],
  '/api/v1/users/me/stats/achievements': ['GET'],
  '/api/v1/users/me/stats/timeline': ['GET'],
  '/api/v1/users/me/username': ['PATCH'],
  '/api/v1/users/me/verify-email-change': ['POST'],
  '/api/v1/users/me/verify-phone-change': ['POST'],
  '/api/v1/users/phone/:phone': ['GET'],
  '/api/v1/users/presence': ['GET'],
  '/api/v1/users/register-device-token': ['POST', 'DELETE'],
  '/api/v1/users/search': ['GET'],
  '/api/v1/voice/admin/metrics': ['GET'],
  '/api/v1/voice/analysis': ['GET', 'POST'],
  '/api/v1/voice/analyze': ['POST'],
  '/api/v1/voice/compare': ['POST'],
  '/api/v1/voice/feedback': ['POST'],
  '/api/v1/voice/history': ['GET'],
  '/api/v1/voice/job/:jobId': ['GET', 'DELETE'],
  '/api/v1/voice/languages': ['GET'],
  '/api/v1/voice/profile': ['GET', 'DELETE'],
  '/api/v1/voice/profile/:profileId': ['PUT'],
  '/api/v1/voice/profile/consent': ['GET', 'POST'],
  '/api/v1/voice/profile/register': ['POST'],
  '/api/v1/voice/transcribe': ['POST'],
  '/api/v1/voice/translate': ['POST'],
  '/api/v1/voice/translate/async': ['POST'],
  '/attachments/:attachmentId/analysis': ['GET', 'POST'],
  '/attachments/batch/analysis': ['POST'],
  '/health': ['GET'],
  '/voice/analysis': ['GET', 'POST'],
};
