import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const ar = {
  'admin.role': 'دورك: {role}',
  'admin.denied.title': 'منطقة محجوزة',
  'admin.denied.message': 'تتطلب هذه المنطقة صلاحية إدارية.',
  'admin.counters.title': 'لمحة سريعة',
  'admin.counters.unavailable': 'العدادات غير متاحة حاليًا.',
  'admin.counters.users': 'الحسابات',
  'admin.counters.activeUsers': 'الحسابات النشطة',
  'admin.counters.messages': 'الرسائل',
  'admin.counters.communities': 'المجتمعات',
  'admin.counters.reports': 'البلاغات',
  'admin.counters.newUsers': 'جديد (٢٤ ساعة)',
  'admin.sections.title': 'الأقسام',
  'admin.sections.legacy': 'الواجهة السابقة',
  'admin.nav.dashboard': 'لوحة المعلومات',
  'admin.nav.users': 'الحسابات',
  'admin.nav.moderation': 'الإشراف',
  'admin.nav.audit': 'سجلات التدقيق',
  'admin.nav.analytics': 'الإحصاءات',
  'admin.nav.trackingLinks': 'روابط التتبع',
  'admin.nav.ranking': 'الترتيب',
  'admin.nav.broadcasts': 'البثوث',
  'admin.nav.settings': 'الإعدادات',
  'admin.nav.agent': 'الوكيل',
  'admin.nav.monitoring': 'المراقبة',
  'admin.users.search': 'ابحث عن حساب',
  'admin.users.count': '{count} حساب',
  'admin.users.empty': 'لا يوجد حساب مطابق.',
  'admin.users.unavailable': 'القائمة غير متاحة حاليًا.',
  'admin.users.inactive': 'معطّل',
  'admin.users.previous': 'السابق',
  'admin.users.next': 'التالي',
  'admin.user.title': 'عضو',
  'admin.user.unavailable': 'البطاقة غير متاحة حاليًا.',
  'admin.user.identity': 'الهوية',
  'admin.user.account': 'الحساب',
  'admin.user.created': 'انضمّ في',
  'admin.user.lastActive': 'آخر نشاط',
  'admin.user.twoFactor': 'التحقق بخطوتين',
  'admin.user.enabled': 'مُفعّل',
  'admin.user.deleted': 'محذوف',
  'admin.user.role': 'الدور',
  'admin.edit.open': 'تعديل',
  'admin.edit.title': 'تعديل العضو',
  'admin.edit.displayName': 'الاسم المعروض',
  'admin.edit.email': 'البريد الإلكتروني',
  'admin.edit.bio': 'نبذة',
  'admin.edit.active': 'الحساب نشط',
  'admin.edit.save': 'حفظ',
  'admin.edit.reason': 'السبب (اختياري)',
  'admin.edit.warnRole': 'تغيير الدور يغيّر صلاحياته.',
  'admin.edit.warnDeactivate': 'التعطيل ينهي جلساته المفتوحة.',
  'admin.edit.confirm': 'تأكيد',
  'admin.edit.saved': 'تم حفظ التغييرات',
  'admin.edit.failed': 'تعذّر الحفظ',
  'admin.password.title': 'إعادة تعيين كلمة المرور',
  'admin.password.warn': 'هذا ينهي جميع جلساته المفتوحة.',
  'admin.password.generated': 'انسخها الآن: لن تُعرض مرة أخرى.',
  'admin.password.copy': 'نسخ',
  'admin.password.copied': 'تم النسخ',
  'admin.password.apply': 'إعادة التعيين',
  'admin.password.done': 'تم إعادة تعيين كلمة المرور',
  'admin.password.failed': 'تعذّرت إعادة التعيين',
  'admin.ban.open': 'حظر',
  'admin.ban.title': 'حظر هذا العضو',
  'admin.ban.reason': 'السبب (إلزامي)',
  'admin.ban.permanent': 'حظر دائم',
  'admin.ban.until': 'حتى',
  'admin.ban.apply': 'حظر',
  'admin.ban.lift': 'رفع الحظر',
  'admin.ban.active': 'ساري',
  'admin.ban.expired': 'منتهٍ',
  'admin.ban.lifted': 'مرفوع',
  'admin.ban.none': 'لا توجد حالات حظر',
  'admin.ban.done': 'تم تسجيل الحظر',
  'admin.ban.failed': 'تعذّر الحظر',
  'admin.media.title': 'الوسائط',
  'admin.media.empty': 'لا توجد وسائط',
  'admin.media.protected': 'محمي',
  'admin.media.fromPost': 'منشور',
  'admin.media.fromMessage': 'رسالة',
  'admin.conv.title': 'المحادثات',
  'admin.conv.empty': 'لا توجد محادثات',
  'admin.conv.members': '{count} عضوًا',
} satisfies AdminInterfaceCatalog;

export default ar;
