import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const it = {
  'announce.messageSent': 'Messaggio inviato',
  'announce.messageCopied': 'Messaggio copiato',
  'announce.messagesCopied': 'Messaggi copiati',
  'announce.messageProtected': 'Messaggio protetto',
  'announce.selectionCap': 'Massimo {count} messaggi',
  'announce.nothingToCopy': 'Niente da copiare',

  'message.author.self': 'Tu',
  'message.excerpt.protected': 'contenuto protetto',
  'a11y.message.menu.subject': 'Azioni del messaggio di {author}: {excerpt}',

  'typing.named': '{name} sta scrivendo',
  'typing.double': '{first} e {second} stanno scrivendo',
  'typing.several': 'Più persone stanno scrivendo',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'I miei link',
  'root.menu.notifications': 'Notifiche',
  'root.menu.calls': 'Chiamate',
  'root.menu.discover': 'Scopri',
  'root.menu.communities': 'Community',
  'root.menu.settings': 'Impostazioni',
  'root.menu.profile': 'Profilo',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Navigazione Meeshy',
  'a11y.floating.menu.unread.one': 'Menu, {count} notifica non letta',
  'a11y.floating.menu.unread.other': 'Menu, {count} notifiche non lette',
  'a11y.floating.rung.notifications.unread.one': 'Notifiche, {count} non letta',
  'a11y.floating.rung.notifications.unread.other': 'Notifiche, {count} non lette',

  'notifications.category.all': 'Tutte',
  'notifications.category.unread': 'Non lette',
  'notifications.category.messages': 'Messaggi',
  'notifications.category.reactions': 'Reazioni',
  'notifications.category.mentions': 'Menzioni',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contatti',
  'notifications.category.groups': 'Gruppi',
  'notifications.category.calls': 'Chiamate',
  'notifications.category.translations': 'Traduzioni',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorie di notifiche',
  'notifications.markAllRead': 'Segna tutte come lette',
  'notifications.unreadCount.one': '{count} non letta',
  'notifications.unreadCount.other': '{count} non lette',
  'notifications.unread': 'Non letta',
  'notifications.empty.all': 'Nessuna notifica',
  'notifications.empty.unread': 'Nessuna notifica non letta',
  'notifications.empty.category': 'Nessuna notifica in «{category}»',
  'notifications.empty.subtitle': 'Le tue notifiche appariranno qui',
  'notifications.loading': 'Caricamento delle notifiche',
  'notifications.error.title': 'Impossibile caricare le notifiche',
  'notifications.error.body': 'Riprova tra un momento.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Le tue notifiche appariranno quando tornerai online.',
  'notifications.retry': 'Riprova',
  'notifications.allLoaded': 'Tutte le notifiche sono state caricate',
  'notifications.actions': 'Azioni della notifica',
  'notifications.action.markRead': 'Segna come letta',
  'notifications.action.delete': 'Elimina',
  'notifications.failure': 'L’azione non è andata a buon fine. Riprova.',

  'notFound.title': 'Questo indirizzo non esiste.',

  'pending.back': 'Torna alle conversazioni',
  'pending.comingSoon': 'Questa schermata arriverà presto.',
  'pending.feed.promise': 'I post delle persone che segui.',
  'pending.links.promise': 'I link condivisi nelle tue conversazioni si raccoglieranno qui.',
  'pending.notifications.promise': 'Ciò che ti aspetta — menzioni, risposte, inviti — si leggerà qui.',
  'pending.calls.promise': 'La cronologia delle tue chiamate, e il modo per farne una.',
  'pending.discover.promise': 'Persone da conoscere, scelte in base a ciò che avete in comune.',
  'pending.communities.promise': 'Le community di cui fai parte, e quelle che ti somigliano.',
  'pending.settings.promise': 'Le tue lingue, la tua privacy, le tue notifiche.',
  'pending.profile.promise': 'La tua identità Meeshy — nome, foto, lingue e ciò che gli altri ne vedono.',

  'profile.title': 'Profilo',
  'profile.edit': 'Modifica',
  'profile.cancel': 'Annulla',
  'profile.save': 'Salva',
  'profile.saving': 'Salvataggio…',
  'profile.saved': 'Profilo salvato',
  'profile.save.error': 'Errore durante il salvataggio',
  'profile.save.offline': 'Offline — la modifica non è stata inviata.',
  'profile.save.invalid': 'Controlla il campo «{field}».',
  'profile.loading': 'Caricamento del profilo',
  'profile.error.title': 'Impossibile caricare il tuo profilo',
  'profile.error.body': 'Riprova tra un momento.',
  'profile.retry': 'Riprova',
  'profile.offline.title': 'Offline',
  'profile.offline.body': 'Il tuo profilo resta leggibile; la modifica torna con la rete.',
  'profile.avatar.edit': 'Modifica la foto del profilo',
  'profile.avatar.updated': 'Foto del profilo aggiornata',
  'profile.avatar.error': 'Impossibile aggiornare la foto del profilo',
  'profile.banner.edit': 'Modifica il banner',
  'profile.banner.updated': 'Banner aggiornato',
  'profile.banner.error': 'Impossibile aggiornare il banner',
  'profile.image.uploading': 'Invio in corso',
  'profile.image.cancel': 'Annulla l’invio',
  'profile.image.cancelled': 'Invio annullato',
  'profile.image.unreadable': 'Questa immagine non può essere letta.',
  'profile.section.identity': 'IDENTITÀ',
  'profile.section.contact': 'CONTATTO',
  'profile.section.languages': 'LINGUE',
  'profile.section.stats': 'STATISTICHE',
  'profile.section.requests': 'RICHIESTE',
  'profile.section.member_since': 'MEMBRO DAL',
  'profile.first_name': 'Nome',
  'profile.last_name': 'Cognome',
  'profile.username': 'Nome utente',
  'profile.display_name': 'Nome visualizzato',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Raccontaci di te...',
  'profile.email': 'Email',
  'profile.phone': 'Telefono',
  'profile.verified': 'Verificato',
  'profile.not_verified': 'Non verificato',
  'profile.language.primary': 'Lingua principale',
  'profile.language.primary.subtitle': 'I contenuti saranno tradotti in questa lingua',
  'profile.language.regional': 'Lingua regionale',
  'profile.language.custom': 'Lingua personalizzata',
  'profile.language.none': 'Nessuna',
  'profile.language.choose': 'Scegli',
  'profile.language.clear.regional': 'Rimuovi la lingua regionale',
  'profile.language.clear.custom': 'Rimuovi la lingua personalizzata',
  'profile.stats.messages': 'Messaggi',
  'profile.stats.translations': 'Traduzioni',
  'profile.stats.languages': 'Lingue',
  'profile.stats.days': 'Giorni',
  'profile.stats.loading': 'Caricamento delle statistiche',
  'profile.progression.title': 'Progressi',
  'profile.progression.subtitle': 'Badge, livello e serie',
  'profile.friend_requests': 'Richieste di amicizia',
  'profile.friend_requests.count.one': '{count} richiesta in attesa',
  'profile.friend_requests.count.other': '{count} richieste in attesa',

  'settings.title': 'Impostazioni',
  'settings.my_profile': 'Il mio profilo',
  'settings.section.account': 'Account',
  'settings.security.title': 'Sicurezza',
  'settings.delete_account': "Elimina l'account",
  'settings.privacy.title': 'Privacy',
  'settings.privacy.online_status': 'Stato online',
  'settings.privacy.online_status.info':
    'Il punto verde sul tuo avatar indica che sei attivo. Disattivato, nessuno lo vede, ma scrivere in una conversazione rivela comunque la tua presenza.',
  'settings.privacy.last_seen': 'Ultimo accesso',
  'settings.privacy.read_receipts': 'Conferme di lettura',
  'settings.privacy.read_receipts.info':
    'È reciproco: se non invii conferme di lettura, non vedrai nemmeno se i tuoi messaggi sono stati letti.',
  'settings.privacy.typing_indicator': 'Indicatore di digitazione',
  'settings.section.appearance': 'Aspetto',
  'settings.theme': 'Tema',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Chiaro',
  'settings.theme.dark': 'Scuro',
  'settings.interface_language': "Lingua dell'interfaccia",
  'settings.interface_language.automatic': 'Automatico',
  'settings.content_languages': 'Lingue di traduzione',
  'settings.section.notifications': 'Notifiche',
  'settings.notifications.title': 'Notifiche',
  'settings.notif.sounds': 'Suoni',
  'settings.notif.more_options': 'Altre opzioni',
  'settings.section.data': 'Dati',
  'settings.media': 'Contenuti multimediali',
  'settings.messages': 'Messaggi',
  'settings.export_data': 'Esporta i miei dati',
  'settings.section.tools': 'Strumenti',
  'settings.tools.progression': 'Progressi',
  'settings.section.about': 'Informazioni',
  'settings.terms': "Condizioni d'uso",
  'settings.privacy_policy': 'Informativa sulla privacy',
  'settings.version': 'Versione',
  'settings.logout.title': 'Esci',
  'settings.logout.message': 'Vuoi davvero uscire?',
  'settings.logout.inprogress': 'Disconnessione in corso...',
  'settings.legacy': 'Versione classica, nuova scheda',
  'settings.loading': 'Caricamento delle impostazioni',
  'settings.error.title': 'Impossibile caricare le impostazioni',
  'settings.retry': 'Riprova',
  'settings.offline.body': 'Offline: le impostazioni restano leggibili; potrai modificarle quando torna la rete.',
  'settings.save.error': "L'impostazione non è stata salvata.",
  'settings.theme.sync_error': 'Tema applicato su questo dispositivo, non sincronizzato.',
  'common.cancel': 'Annulla',

  'media.video.play': 'Riproduci video',
  'media.video.pause': 'Metti in pausa',
  'media.video.position': 'Posizione di riproduzione',
  'media.video.position.value': '{elapsed} di {total}',
  'media.video.mute': 'Disattiva audio',
  'media.video.unmute': 'Riattiva audio',
  'media.video.more_options': 'Altre opzioni',
  'media.video.speed': 'Velocità',
  'media.video.pip.enter': 'Picture-in-Picture',
  'media.video.pip.exit': 'Esci da Picture-in-Picture',

  'community.list.create.accessibilityLabel': 'Crea una community',
  'community.list.search.placeholder': 'Cerca community',
  'community.list.search.clear': 'Cancella la ricerca',
  'community.list.search.empty': 'Nessuna community corrisponde a «{query}».',
  'community.list.empty.title': 'Nessuna community',
  'community.list.empty.subtitle': 'Unisciti a una community o creane una per parlare insieme.',
  'community.list.loading': 'Caricamento delle community',
  'community.error.title': 'Impossibile caricare le community',
  'community.error.body': 'Controlla la connessione e riprova.',
  'community.retry': 'Riprova',
  'community.offline.title': 'Offline',
  'community.offline.body': 'Le tue community restano leggibili; per crearne una serve la connessione.',
  'community.privacy.private': 'Privata',
  'community.privacy.public': 'Pubblica',
  'community.members.one': '{count} membro',
  'community.members.other': '{count} membri',
  'community.conversations.one': '{count} conversazione',
  'community.conversations.other': '{count} conversazioni',
  'community.detail.stats.members': 'Membri',
  'community.detail.channels': 'Conversazioni',
  'community.detail.channels.empty': 'Non partecipi ancora a nessuna conversazione di questa community.',
  'community.detail.untitled': 'Conversazione senza titolo',
  'community.detail.back': 'Torna alle community',
  'community.detail.refused.title': 'Community non trovata',
  'community.detail.refused.body': 'Non esiste, oppure è privata e non ne sei membro.',
  'community.detail.error.title': 'Impossibile caricare questa community',
  'community.detail.loading': 'Caricamento della community',
  'community.create.title': 'Nuova community',
  'community.create.preview.placeholder': 'La mia community',
  'community.create.field.name': 'Nome',
  'community.create.field.name.placeholder': 'Nome della community',
  'community.create.field.identifier': 'Identificativo',
  'community.create.field.identifier.placeholder': 'mio-gruppo',
  'community.create.field.description': 'Descrizione',
  'community.create.field.description.placeholder': 'Di cosa parla questa community?',
  'community.create.privacy.title': 'Community privata',
  'community.create.privacy.private.description': 'Solo i membri invitati possono unirsi',
  'community.create.privacy.public.description': 'Chiunque può scoprirla e unirsi',
  'community.create.button': 'Crea la community',
  'community.create.inprogress': 'Creazione…',
  'community.create.error.name': 'Dalle un nome di al massimo 100 caratteri.',
  'community.create.error.identifier': 'Solo lettere, cifre, trattini e trattini bassi, al massimo 50.',
  'community.create.error.description': 'Al massimo 500 caratteri.',
  'community.create.error.conflict': 'Questo identificativo è già in uso.',
  'community.create.error.offline': 'Offline: la community non è stata inviata.',
  'community.create.error.default': 'La community non è stata creata. Riprova.',
  'calls.filters': 'Filtra il registro chiamate',
  'calls.filter.all': 'Tutte',
  'calls.filter.missed': 'Perse',
  'calls.direction.incoming': 'Ricevuta',
  'calls.direction.outgoing': 'Effettuata',
  'calls.direction.missed': 'Persa',
  'calls.a11y.incoming': 'chiamata ricevuta',
  'calls.a11y.outgoing': 'chiamata effettuata',
  'calls.a11y.missed': 'chiamata persa',
  'calls.type.audio': 'chiamata vocale',
  'calls.type.video': 'videochiamata',
  'calls.duration': 'durata {duration}',
  'calls.unknown': 'Sconosciuto',
  'calls.empty.title': 'Nessuna chiamata recente',
  'calls.empty.subtitle': 'Qui appariranno le tue chiamate ricevute, perse, annullate ed effettuate.',
  'calls.empty.missed.title': 'Nessuna chiamata persa',
  'calls.empty.missed.subtitle': 'Qui appariranno le chiamate a cui non hai risposto.',
  'calls.error.title': 'Impossibile caricare il registro chiamate',
  'calls.error.body': 'Controlla la connessione e riprova.',
  'calls.offline.title': 'Offline',
  'calls.offline.body': 'Stai vedendo il registro dell’ultimo caricamento.',
  'calls.retry': 'Riprova',
  'calls.loading': 'Caricamento del registro chiamate',
  'calls.allLoaded': 'Tutte le chiamate degli ultimi tre mesi sono caricate',

  'discover.tabs': 'Sezioni di Scopri',
  'discover.tab.discover': 'Scopri',
  'discover.tab.requests': 'Richieste',
  'discover.tab.blocked': 'Bloccati',
  'discover.tab.requests.count.one': 'Richieste, {count} ricevuta',
  'discover.tab.requests.count.other': 'Richieste, {count} ricevute',
  'discover.invite.title': 'Invita via email',
  'discover.invite.placeholder': 'Indirizzo email',
  'discover.invite.send': 'Invia',
  'discover.invite.sending': 'Invio…',
  'discover.invite.sendLabel': 'Invia l’invito via email',
  'discover.invite.sent': 'Invito inviato a {email}',
  'discover.invite.invalid': 'Questo indirizzo email non è valido.',
  'discover.invite.conflict': 'Questa persona è già su Meeshy: cercala qui sotto.',
  'discover.invite.error': 'Impossibile inviare l’invito. Riprova.',
  'discover.invite.offline': 'Offline: riconnettiti per inviare l’invito.',
  'discover.search.label': 'Cerca un utente Meeshy',
  'discover.search.clear': 'Cancella la ricerca',
  'discover.search.searching': 'Ricerca in corso',
  'discover.search.empty': 'Nessun utente trovato per «{query}»',
  'discover.search.error': 'La ricerca non è riuscita. Controlla la connessione.',
  'discover.connection.add': 'Aggiungi',
  'discover.connection.addLabel': 'Aggiungi {name}',
  'discover.connection.pending': 'In attesa',
  'discover.connection.cancelLabel': 'Annulla la richiesta inviata a {name}',
  'discover.connection.contact': 'Contatto',
  'discover.connection.blocked': 'Bloccato',
  'discover.connection.acceptLabel': 'Accetta la richiesta di {name}',
  'discover.connection.rejectLabel': 'Rifiuta la richiesta di {name}',
  'discover.requests.filters': 'Filtra le richieste',
  'discover.requests.received': 'Ricevute',
  'discover.requests.sent': 'Inviate',
  'discover.requests.intent': 'Vorrebbe entrare in contatto con te',
  'discover.requests.cancel': 'Annulla',
  'discover.requests.empty.received.title': 'Nessuna richiesta ricevuta',
  'discover.requests.empty.received.subtitle': 'Le richieste di contatto ricevute appariranno qui.',
  'discover.requests.empty.sent.title': 'Nessuna richiesta inviata',
  'discover.requests.empty.sent.subtitle': 'Le richieste che invii appariranno qui.',
  'discover.blocked.unblock': 'Sblocca',
  'discover.blocked.unblockLabel': 'Sblocca {name}',
  'discover.blocked.confirm.title': 'Sbloccare?',
  'discover.blocked.confirm.body': 'Sbloccare {name}?',
  'discover.blocked.confirm.cancel': 'Annulla',
  'discover.blocked.empty.title': 'Nessun utente bloccato',
  'discover.blocked.empty.subtitle': 'Le persone che blocchi appariranno qui.',
  'discover.unknown': 'Sconosciuto',
  'discover.loading': 'Caricamento',
  'discover.allLoaded': 'L’elenco completo è caricato',
  'discover.error.title': 'Impossibile caricare questo elenco',
  'discover.error.body': 'Controlla la connessione e riprova.',
  'discover.offline.title': 'Offline',
  'discover.offline.body': 'Stai vedendo l’elenco dell’ultimo caricamento.',
  'discover.retry': 'Riprova',
  'discover.announce.accepted': 'Connessione accettata',
  'discover.announce.rejected': 'Richiesta rifiutata',
  'discover.announce.cancelled': 'Richiesta annullata',
  'discover.announce.sent': 'Richiesta inviata',
  'discover.announce.unblocked': 'Utente sbloccato',
  'discover.announce.acceptFailed': 'Impossibile accettare questa richiesta',
  'discover.announce.rejectFailed': 'Impossibile rifiutare questa richiesta',
  'discover.announce.cancelFailed': 'Impossibile annullare questa richiesta',
  'discover.announce.sendFailed': 'Impossibile inviare la richiesta',
  'discover.announce.unblockFailed': 'Impossibile sbloccare',
  'discover.announce.offline': 'Offline: non è stato inviato nulla.',

  'a11y.floating.rung.discover.requests.one': 'Scopri, {count} richiesta ricevuta',
  'a11y.floating.rung.discover.requests.other': 'Scopri, {count} richieste ricevute',
} satisfies InterfaceCatalog;

export default it;
