import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const ar = {
  'announce.messageSent': 'تم إرسال الرسالة',
  'announce.messageCopied': 'تم نسخ الرسالة',
  'announce.messagesCopied': 'تم نسخ الرسائل',
  'announce.messageProtected': 'رسالة محمية',
  'announce.selectionCap': '{count} رسالة كحد أقصى',
  'announce.nothingToCopy': 'لا شيء للنسخ',

  'message.author.self': 'أنت',
  'message.excerpt.protected': 'محتوى محمي',
  'a11y.message.menu.subject': 'إجراءات رسالة {author}: {excerpt}',

  'typing.named': '{name} يكتب',
  'typing.double': '{first} و{second} يكتبان',
  'typing.several': 'عدة أشخاص يكتبون',

  'root.menu.feed': 'التدفق',
  'root.menu.links': 'روابطي',
  'root.menu.notifications': 'الإشعارات',
  'root.menu.calls': 'المكالمات',
  'root.menu.discover': 'اكتشاف',
  'root.menu.communities': 'المجتمعات',
  'root.menu.settings': 'الإعدادات',
  'root.menu.profile': 'الملف الشخصي',
  'a11y.floating.menu': 'القائمة',
  'a11y.floating.menu.ladder': 'التنقل في Meeshy',
  'a11y.floating.menu.unread.one': 'القائمة، {count} إشعار غير مقروء',
  'a11y.floating.menu.unread.other': 'القائمة، {count} إشعارات غير مقروءة',
  'a11y.floating.rung.notifications.unread.one': 'الإشعارات، {count} غير مقروء',
  'a11y.floating.rung.notifications.unread.other': 'الإشعارات، {count} غير مقروءة',

  'notifications.category.all': 'الكل',
  'notifications.category.unread': 'غير المقروءة',
  'notifications.category.messages': 'الرسائل',
  'notifications.category.reactions': 'التفاعلات',
  'notifications.category.mentions': 'الإشارات',
  'notifications.category.social': 'اجتماعي',
  'notifications.category.contacts': 'جهات الاتصال',
  'notifications.category.groups': 'المجموعات',
  'notifications.category.calls': 'المكالمات',
  'notifications.category.translations': 'الترجمات',
  'notifications.category.system': 'النظام',
  'notifications.categories': 'فئات الإشعارات',
  'notifications.markAllRead': 'قراءة الكل',
  'notifications.unreadCount.one': '{count} غير مقروء',
  'notifications.unreadCount.other': '{count} غير مقروءة',
  'notifications.unread': 'غير مقروء',
  'notifications.empty.all': 'لا توجد إشعارات',
  'notifications.empty.unread': 'لا توجد إشعارات غير مقروءة',
  'notifications.empty.category': 'لا توجد إشعارات في «{category}»',
  'notifications.empty.subtitle': 'ستظهر إشعاراتك هنا',
  'notifications.loading': 'جارٍ تحميل الإشعارات',
  'notifications.error.title': 'تعذّر تحميل الإشعارات',
  'notifications.error.body': 'أعد المحاولة بعد لحظة.',
  'notifications.offline.title': 'غير متصل',
  'notifications.offline.body': 'ستظهر إشعاراتك عند عودة الاتصال.',
  'notifications.retry': 'إعادة المحاولة',
  'notifications.allLoaded': 'تم تحميل جميع الإشعارات',
  'notifications.actions': 'إجراءات الإشعار',
  'notifications.action.markRead': 'وضع علامة كمقروء',
  'notifications.action.delete': 'حذف',
  'notifications.failure': 'لم يكتمل الإجراء. أعد المحاولة.',

  'notFound.title': 'هذا العنوان غير موجود.',

  'pending.back': 'العودة إلى المحادثات',
  'pending.comingSoon': 'هذه الشاشة قادمة قريبًا.',
  'pending.feed.promise': 'منشورات الأشخاص الذين تتابعهم.',
  'pending.links.promise': 'ستُجمع هنا الروابط التي تمت مشاركتها في محادثاتك.',
  'pending.notifications.promise': 'ما ينتظرك — الإشارات والردود والدعوات — ستقرؤه هنا.',
  'pending.calls.promise': 'سجل مكالماتك، وطريقة لإجراء مكالمة.',
  'pending.discover.promise': 'أشخاص للتعرف عليهم، يتم اختيارهم بحسب ما يجمعكم.',
  'pending.communities.promise': 'المجتمعات التي تنتمي إليها، وتلك التي تشبهك.',
  'pending.settings.promise': 'لغاتك وخصوصيتك وإشعاراتك.',
  'pending.profile.promise': 'هويتك على Meeshy — الاسم والصورة واللغات وما يراه الآخرون منها.',

  'profile.title': 'الملف الشخصي',
  'profile.edit': 'تعديل',
  'profile.cancel': 'إلغاء',
  'profile.save': 'حفظ',
  'profile.saving': 'جارٍ الحفظ…',
  'profile.saved': 'تم حفظ الملف الشخصي',
  'profile.save.error': 'خطأ أثناء الحفظ',
  'profile.save.offline': 'غير متصل — لم يُرسَل التعديل.',
  'profile.save.invalid': 'تحقّق من الحقل «{field}».',
  'profile.loading': 'جارٍ تحميل الملف الشخصي',
  'profile.error.title': 'تعذّر تحميل ملفك الشخصي',
  'profile.error.body': 'أعد المحاولة بعد قليل.',
  'profile.retry': 'إعادة المحاولة',
  'profile.offline.title': 'غير متصل',
  'profile.offline.body': 'يبقى ملفك الشخصي مقروءًا، ويعود التعديل مع عودة الشبكة.',
  'profile.avatar.edit': 'تعديل صورة الملف الشخصي',
  'profile.avatar.updated': 'تم تحديث صورة الملف الشخصي',
  'profile.avatar.error': 'تعذّر تحديث صورة الملف الشخصي',
  'profile.banner.edit': 'تعديل صورة الغلاف',
  'profile.banner.updated': 'تم تحديث صورة الغلاف',
  'profile.banner.error': 'تعذّر تحديث صورة الغلاف',
  'profile.image.uploading': 'جارٍ الإرسال',
  'profile.image.cancel': 'إلغاء الإرسال',
  'profile.image.cancelled': 'أُلغي الإرسال',
  'profile.image.unreadable': 'تعذّرت قراءة هذه الصورة.',
  'profile.section.identity': 'الهوية',
  'profile.section.contact': 'الاتصال',
  'profile.section.languages': 'اللغات',
  'profile.section.stats': 'الإحصائيات',
  'profile.section.requests': 'الطلبات',
  'profile.section.member_since': 'عضو منذ',
  'profile.first_name': 'الاسم الأول',
  'profile.last_name': 'اسم العائلة',
  'profile.username': 'اسم المستخدم',
  'profile.display_name': 'الاسم المعروض',
  'profile.bio': 'نبذة',
  'profile.bio.placeholder': 'عرّفنا بنفسك...',
  'profile.email': 'البريد الإلكتروني',
  'profile.phone': 'الهاتف',
  'profile.verified': 'موثّق',
  'profile.not_verified': 'غير موثّق',
  'profile.language.primary': 'اللغة الأساسية',
  'profile.language.primary.subtitle': 'ستُترجَم المحتويات إلى هذه اللغة',
  'profile.language.regional': 'اللغة الإقليمية',
  'profile.language.custom': 'لغة مخصّصة',
  'profile.language.none': 'لا شيء',
  'profile.language.choose': 'اختيار',
  'profile.language.clear.regional': 'إزالة اللغة الإقليمية',
  'profile.language.clear.custom': 'إزالة اللغة المخصّصة',
  'profile.stats.messages': 'الرسائل',
  'profile.stats.translations': 'الترجمات',
  'profile.stats.languages': 'اللغات',
  'profile.stats.days': 'الأيام',
  'profile.stats.loading': 'جارٍ تحميل الإحصائيات',
  'profile.progression.title': 'التقدّم',
  'profile.progression.subtitle': 'الشارات والمستوى والسلسلة',
  'profile.friend_requests': 'طلبات الصداقة',
  'profile.friend_requests.count.one': '{count} طلب معلّق',
  'profile.friend_requests.count.other': '{count} طلبات معلّقة',

  'settings.title': 'الإعدادات',
  'settings.my_profile': 'ملفي الشخصي',
  'settings.section.account': 'الحساب',
  'settings.security.title': 'الأمان',
  'settings.delete_account': 'حذف الحساب',
  'settings.privacy.title': 'الخصوصية',
  'settings.privacy.online_status': 'حالة الاتصال',
  'settings.privacy.online_status.info':
    'النقطة الخضراء على صورتك تعني أنك نشط. عند إيقافها لا يراها أحد، لكن الكتابة في محادثة تظل دليلاً على نشاطك.',
  'settings.privacy.last_seen': 'آخر تسجيل دخول',
  'settings.privacy.read_receipts': 'إيصالات القراءة',
  'settings.privacy.read_receipts.info': 'الأمر متبادل: إن لم تُرسل إشعارات القراءة، فلن ترى أيضًا ما إذا قُرئت رسائلك.',
  'settings.privacy.typing_indicator': 'مؤشر الكتابة',
  'settings.section.appearance': 'المظهر',
  'settings.theme': 'السمة',
  'settings.theme.auto': 'تلقائي',
  'settings.theme.light': 'فاتح',
  'settings.theme.dark': 'داكن',
  'settings.interface_language': 'لغة الواجهة',
  'settings.interface_language.automatic': 'تلقائي',
  'settings.content_languages': 'لغات الترجمة',
  'settings.section.notifications': 'الإشعارات',
  'settings.notifications.title': 'الإشعارات',
  'settings.notif.sounds': 'الأصوات',
  'settings.notif.more_options': 'المزيد من الخيارات',
  'settings.section.data': 'البيانات',
  'settings.media': 'الوسائط',
  'settings.messages': 'الرسائل',
  'settings.export_data': 'تصدير بياناتي',
  'settings.section.tools': 'الأدوات',
  'settings.tools.progression': 'التقدّم',
  'settings.section.about': 'حول',
  'settings.terms': 'شروط الاستخدام',
  'settings.privacy_policy': 'سياسة الخصوصية',
  'settings.version': 'الإصدار',
  'settings.logout.title': 'تسجيل الخروج',
  'settings.logout.message': 'هل تريد فعلاً تسجيل الخروج؟',
  'settings.logout.inprogress': 'جارٍ تسجيل الخروج...',
  'settings.legacy': 'النسخة الكلاسيكية، علامة تبويب جديدة',
  'settings.loading': 'جارٍ تحميل الإعدادات',
  'settings.error.title': 'تعذّر تحميل إعداداتك',
  'settings.retry': 'إعادة المحاولة',
  'settings.offline.body': 'غير متصل — تبقى إعداداتك مقروءة، ويمكنك تعديلها عند عودة الشبكة.',
  'settings.save.error': 'لم يُحفظ الإعداد.',
  'settings.theme.sync_error': 'طُبّق المظهر على هذا الجهاز دون مزامنة.',
  'common.cancel': 'إلغاء',

  'media.video.play': 'تشغيل الفيديو',
  'media.video.pause': 'إيقاف مؤقت',
  'media.video.position': 'موضع التشغيل',
  'media.video.position.value': '{elapsed} من {total}',
  'media.video.mute': 'كتم الصوت',
  'media.video.unmute': 'إلغاء كتم الصوت',
  'media.video.more_options': 'مزيد من الخيارات',
  'media.video.speed': 'السرعة',
  'media.video.pip.enter': 'صورة داخل صورة',
  'media.video.pip.exit': 'الخروج من صورة داخل صورة',

  'community.list.create.accessibilityLabel': 'إنشاء مجتمع',
  'community.list.search.placeholder': 'ابحث عن مجتمع',
  'community.list.search.clear': 'مسح البحث',
  'community.list.search.empty': 'لا يوجد مجتمع يطابق «{query}».',
  'community.list.empty.title': 'لا توجد مجتمعات',
  'community.list.empty.subtitle': 'انضم إلى مجتمع أو أنشئ واحدًا للتحدث معًا.',
  'community.list.loading': 'جارٍ تحميل المجتمعات',
  'community.error.title': 'تعذّر تحميل المجتمعات',
  'community.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'community.retry': 'إعادة المحاولة',
  'community.offline.title': 'غير متصل',
  'community.offline.body': 'تبقى مجتمعاتك قابلة للقراءة؛ يتطلب إنشاء مجتمع اتصالًا.',
  'community.privacy.private': 'خاص',
  'community.privacy.public': 'عام',
  'community.members.one': '{count} عضو',
  'community.members.other': '{count} أعضاء',
  'community.conversations.one': '{count} محادثة',
  'community.conversations.other': '{count} محادثات',
  'community.detail.stats.members': 'الأعضاء',
  'community.detail.channels': 'المحادثات',
  'community.detail.channels.empty': 'لم تنضم بعد إلى أي محادثة في هذا المجتمع.',
  'community.detail.untitled': 'محادثة بلا عنوان',
  'community.detail.back': 'العودة إلى المجتمعات',
  'community.detail.refused.title': 'المجتمع غير موجود',
  'community.detail.refused.body': 'إنه غير موجود، أو خاص ولست عضوًا فيه.',
  'community.detail.error.title': 'تعذّر تحميل هذا المجتمع',
  'community.detail.loading': 'جارٍ تحميل المجتمع',
  'community.create.title': 'مجتمع جديد',
  'community.create.preview.placeholder': 'مجتمعي',
  'community.create.field.name': 'الاسم',
  'community.create.field.name.placeholder': 'اسم المجتمع',
  'community.create.field.identifier': 'المعرّف',
  'community.create.field.identifier.placeholder': 'my-group',
  'community.create.field.description': 'الوصف',
  'community.create.field.description.placeholder': 'عمّ يدور هذا المجتمع؟',
  'community.create.privacy.title': 'مجتمع خاص',
  'community.create.privacy.private.description': 'يمكن للأعضاء المدعوين فقط الانضمام',
  'community.create.privacy.public.description': 'يمكن للجميع اكتشافه والانضمام إليه',
  'community.create.button': 'إنشاء المجتمع',
  'community.create.inprogress': 'جارٍ الإنشاء…',
  'community.create.error.name': 'أعطه اسمًا لا يتجاوز 100 حرف.',
  'community.create.error.identifier': 'أحرف وأرقام وشرطات وشرطات سفلية فقط، 50 على الأكثر.',
  'community.create.error.description': '500 حرف على الأكثر.',
  'community.create.error.conflict': 'هذا المعرّف مستخدم بالفعل.',
  'community.create.error.offline': 'غير متصل — لم يُرسَل المجتمع.',
  'community.create.error.default': 'لم يُنشأ المجتمع. أعد المحاولة.',
  'calls.filters': 'تصفية سجل المكالمات',
  'calls.filter.all': 'الكل',
  'calls.filter.missed': 'الفائتة',
  'calls.direction.incoming': 'واردة',
  'calls.direction.outgoing': 'صادرة',
  'calls.direction.missed': 'فائتة',
  'calls.a11y.incoming': 'مكالمة واردة',
  'calls.a11y.outgoing': 'مكالمة صادرة',
  'calls.a11y.missed': 'مكالمة فائتة',
  'calls.type.audio': 'مكالمة صوتية',
  'calls.type.video': 'مكالمة فيديو',
  'calls.duration': 'المدة {duration}',
  'calls.unknown': 'غير معروف',
  'calls.empty.title': 'لا مكالمات حديثة',
  'calls.empty.subtitle': 'ستظهر هنا مكالماتك الواردة والفائتة والملغاة والصادرة.',
  'calls.empty.missed.title': 'لا مكالمات فائتة',
  'calls.empty.missed.subtitle': 'ستظهر هنا المكالمات التي لم تُجب عليها.',
  'calls.error.title': 'تعذّر تحميل سجل المكالمات',
  'calls.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'calls.offline.title': 'غير متصل',
  'calls.offline.body': 'تعرض سجل آخر تحميل.',
  'calls.retry': 'أعد المحاولة',
  'calls.loading': 'جارٍ تحميل سجل المكالمات',
  'calls.allLoaded': 'تم تحميل كل مكالمات الأشهر الثلاثة الأخيرة',

  'discover.tabs': 'أقسام الاكتشاف',
  'discover.tab.discover': 'اكتشاف',
  'discover.tab.requests': 'الطلبات',
  'discover.tab.blocked': 'المحظورون',
  'discover.tab.requests.count.one': 'الطلبات، {count} طلب وارد',
  'discover.tab.requests.count.other': 'الطلبات، {count} طلبات واردة',
  'discover.invite.title': 'دعوة عبر البريد الإلكتروني',
  'discover.invite.placeholder': 'عنوان البريد الإلكتروني',
  'discover.invite.send': 'إرسال',
  'discover.invite.sending': 'جارٍ الإرسال…',
  'discover.invite.sendLabel': 'إرسال الدعوة عبر البريد الإلكتروني',
  'discover.invite.sent': 'أُرسلت الدعوة إلى {email}',
  'discover.invite.invalid': 'عنوان البريد الإلكتروني هذا غير صالح.',
  'discover.invite.conflict': 'هذا الشخص موجود على Meeshy بالفعل: ابحث عنه أدناه.',
  'discover.invite.error': 'تعذّر إرسال الدعوة. أعد المحاولة.',
  'discover.invite.offline': 'غير متصل: اتصل لإرسال الدعوة.',
  'discover.search.label': 'ابحث عن مستخدم على Meeshy',
  'discover.search.clear': 'مسح البحث',
  'discover.search.searching': 'جارٍ البحث',
  'discover.search.empty': 'لم يُعثر على أي مستخدم لـ «{query}»',
  'discover.search.error': 'تعذّر البحث. تحقّق من اتصالك.',
  'discover.connection.add': 'إضافة',
  'discover.connection.addLabel': 'إضافة {name}',
  'discover.connection.pending': 'قيد الانتظار',
  'discover.connection.cancelLabel': 'إلغاء الطلب المرسل إلى {name}',
  'discover.connection.contact': 'جهة اتصال',
  'discover.connection.blocked': 'محظور',
  'discover.connection.acceptLabel': 'قبول طلب {name}',
  'discover.connection.rejectLabel': 'رفض طلب {name}',
  'discover.requests.filters': 'تصفية الطلبات',
  'discover.requests.received': 'الواردة',
  'discover.requests.sent': 'المرسلة',
  'discover.requests.intent': 'يرغب في التواصل معك',
  'discover.requests.cancel': 'إلغاء',
  'discover.requests.empty.received.title': 'لا توجد طلبات واردة',
  'discover.requests.empty.received.subtitle': 'ستظهر هنا طلبات التواصل التي تتلقاها.',
  'discover.requests.empty.sent.title': 'لا توجد طلبات مرسلة',
  'discover.requests.empty.sent.subtitle': 'ستظهر هنا الطلبات التي ترسلها.',
  'discover.blocked.unblock': 'إلغاء الحظر',
  'discover.blocked.unblockLabel': 'إلغاء حظر {name}',
  'discover.blocked.confirm.title': 'إلغاء الحظر؟',
  'discover.blocked.confirm.body': 'إلغاء حظر {name}؟',
  'discover.blocked.confirm.cancel': 'إلغاء',
  'discover.blocked.empty.title': 'لا يوجد مستخدمون محظورون',
  'discover.blocked.empty.subtitle': 'سيظهر هنا الأشخاص الذين تحظرهم.',
  'discover.unknown': 'مجهول',
  'discover.loading': 'جارٍ التحميل',
  'discover.allLoaded': 'تم تحميل القائمة كاملة',
  'discover.error.title': 'تعذّر تحميل هذه القائمة',
  'discover.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'discover.offline.title': 'غير متصل',
  'discover.offline.body': 'تعرض قائمة آخر تحميل.',
  'discover.retry': 'إعادة المحاولة',
  'discover.announce.accepted': 'تم قبول التواصل',
  'discover.announce.rejected': 'تم رفض الطلب',
  'discover.announce.cancelled': 'تم إلغاء الطلب',
  'discover.announce.sent': 'تم إرسال الطلب',
  'discover.announce.unblocked': 'تم إلغاء حظر المستخدم',
  'discover.announce.acceptFailed': 'تعذّر قبول هذا الطلب',
  'discover.announce.rejectFailed': 'تعذّر رفض هذا الطلب',
  'discover.announce.cancelFailed': 'تعذّر إلغاء هذا الطلب',
  'discover.announce.sendFailed': 'تعذّر إرسال الطلب',
  'discover.announce.unblockFailed': 'تعذّر إلغاء الحظر',
  'discover.announce.offline': 'غير متصل: لم يُرسَل شيء.',

  'a11y.floating.rung.discover.requests.one': 'اكتشاف، {count} طلب وارد',
  'a11y.floating.rung.discover.requests.other': 'اكتشاف، {count} طلبات واردة',
} satisfies InterfaceCatalog;

export default ar;
