import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const en = {
  'announce.messageSent': 'Message sent',
  'announce.messageCopied': 'Message copied',
  'announce.messagesCopied': 'Messages copied',
  'announce.messageProtected': 'Protected message',
  'announce.selectionCap': 'Maximum {count} messages',
  'announce.nothingToCopy': 'Nothing to copy',

  'message.author.self': 'You',
  'message.excerpt.protected': 'protected content',
  'a11y.message.menu.subject': 'Actions for the message from {author}: {excerpt}',

  'typing.named': '{name} is typing',
  'typing.double': '{first} and {second} are typing',
  'typing.several': 'Several people are typing',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'My links',
  'root.menu.notifications': 'Notifications',
  'root.menu.calls': 'Calls',
  'root.menu.discover': 'Discover',
  'root.menu.communities': 'Communities',
  'root.menu.settings': 'Settings',
  'root.menu.profile': 'Profile',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Meeshy navigation',
  'a11y.floating.menu.unread.one': 'Menu, {count} unread notification',
  'a11y.floating.menu.unread.other': 'Menu, {count} unread notifications',

  'notifications.category.all': 'All',
  'notifications.category.unread': 'Unread',
  'notifications.category.messages': 'Messages',
  'notifications.category.reactions': 'Reactions',
  'notifications.category.mentions': 'Mentions',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contacts',
  'notifications.category.groups': 'Groups',
  'notifications.category.calls': 'Calls',
  'notifications.category.translations': 'Translations',
  'notifications.category.system': 'System',
  'notifications.categories': 'Notification categories',
  'notifications.markAllRead': 'Mark all read',
  'notifications.unreadCount.one': '{count} unread',
  'notifications.unreadCount.other': '{count} unread',
  'notifications.unread': 'Unread',
  'notifications.empty.all': 'No notifications',
  'notifications.empty.unread': 'No unread notifications',
  'notifications.empty.category': 'No notifications in “{category}”',
  'notifications.empty.subtitle': 'Your notifications will show up here',
  'notifications.loading': 'Loading notifications',
  'notifications.error.title': 'Couldn’t load notifications',
  'notifications.error.body': 'Try again in a moment.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Your notifications will show up once you’re back online.',
  'notifications.retry': 'Try again',
  'notifications.allLoaded': 'All notifications are loaded',
  'notifications.actions': 'Notification actions',
  'notifications.action.markRead': 'Mark as read',
  'notifications.action.delete': 'Delete',
  'notifications.failure': 'That didn’t go through. Try again.',

  'pending.back': 'Back to conversations',
  'pending.comingSoon': 'This screen is coming soon.',
  'pending.feed.promise': 'Posts from the people you follow.',
  'pending.links.promise': 'Links shared in your conversations will gather here.',
  'pending.notifications.promise': 'What is waiting for you — mentions, replies, invitations — will show up here.',
  'pending.calls.promise': 'Your call history, and a way to place a call.',
  'pending.discover.promise': 'People to meet, chosen by what you have in common.',
  'pending.communities.promise': 'The communities you belong to, and the ones that feel like you.',
  'pending.settings.promise': 'Your languages, your privacy, your notifications.',
  'pending.profile.promise': 'Your Meeshy identity — name, photo, languages, and what others see of it.',
} satisfies InterfaceCatalog;

export default en;
