import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const es = {
  'announce.messageSent': 'Mensaje enviado',
  'announce.messageCopied': 'Mensaje copiado',
  'announce.messagesCopied': 'Mensajes copiados',
  'announce.messageProtected': 'Mensaje protegido',
  'announce.selectionCap': 'Máximo {count} mensajes',
  'announce.nothingToCopy': 'Nada que copiar',

  'message.author.self': 'Tú',
  'message.excerpt.protected': 'contenido protegido',
  'a11y.message.menu.subject': 'Acciones del mensaje de {author}: {excerpt}',

  'typing.named': '{name} está escribiendo',
  'typing.double': '{first} y {second} están escribiendo',
  'typing.several': 'Varias personas están escribiendo',

  'feed.header.reels': 'Ver Reels',
  'reels.title': 'Reels',
  'reels.back': 'Atrás',
  'reels.open': 'Ver el reel de {author}',
  'reels.item': 'Reel de {author}, {index} de {count}',
  'reels.loading': 'Cargando reels',
  'reels.empty': 'Aún no hay reels',
  'reels.empty.hint': 'Los reels de tus contactos aparecerán aquí.',
  'reels.error': 'No se pudieron cargar los reels',
  'reels.error.hint': 'Inténtalo de nuevo en un momento.',
  'reels.retry': 'Reintentar',
  'reels.offline': 'Sin conexión',
  'reels.offline.cold': 'Los reels se cargarán cuando vuelva la conexión.',
  'reels.action.like': 'Me gusta',
  'reels.action.bookmark': 'Guardar',
  'reels.action.share': 'Compartir',
  'reels.sound.on': 'Activar el sonido',
  'reels.sound.off': 'Silenciar',
  'reels.play': 'Reproducir el reel',
  'reels.pause': 'Pausar el reel',
  'reels.media.error': 'No se puede reproducir — Reintentar',
  'reels.image': 'Imagen {index} de {count}',

  'stories.title': 'Historias',
  'stories.loading': 'Cargando historias…',
  'stories.error': 'No se pudieron cargar las historias.',
  'stories.empty.title': 'Aún no hay historias',
  'stories.empty.subtitle': 'Las historias de tus contactos aparecerán aquí durante veinticuatro horas.',
  'stories.create': 'Crear una historia',
  'stories.count.one': '{count} historia',
  'stories.count.other': '{count} historias',
  'stories.mine': 'Tu historia',

  'feed.post.action.like': 'Me gusta',
  'feed.post.action.comment': 'Comentar',
  'feed.post.action.repost': 'Republicar',
  'feed.post.action.bookmark': 'Guardar',
  'feed.post.action.share': 'Compartir',
  'feed.post.media.video': 'Vídeo',
  'feed.post.media.audio': 'Audio',
  'feed.post.media.previous': 'Media anterior',
  'feed.post.media.next': 'Media siguiente',
  'feed.post.media.mosaic': 'Mosaico de {count} medios',
  'feed.post.see_more': 'ver más',
  'feed.post.see_less': 'ver menos',
  'feed.post.reel.chip': 'Reel',
  'feed.post.reel.of': 'Reel de {author}',
  'feed.error.title': 'No se pudo cargar el feed',
  'feed.error.body': 'Inténtalo de nuevo en un momento.',
  'feed.offline.title': 'Sin conexión',
  'feed.offline.body': 'El feed aparecerá cuando vuelvas a estar en línea.',
  'feed.retry': 'Reintentar',
  'feed.empty.title': 'Aún no hay publicaciones',
  'feed.empty.subtitle': 'Las publicaciones de tus contactos aparecerán aquí.',
  'feed.loading': 'Cargando el feed',
  'feed.allLoaded': 'Todas las publicaciones están cargadas',
  'feed.like.error': 'Error al dar me gusta',
  'post.bookmark.error': 'No se pudo guardar',
  'feed.gesture.pending': 'Acción no confirmada — sin conexión',
  'feed.share.error': 'Error al compartir la publicación',
  'feed.share.copied': 'Enlace copiado — ya solo queda pegarlo.',
  'feed.share.text': 'Una publicación en Meeshy',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'Mis enlaces',
  'root.menu.notifications': 'Notificaciones',
  'root.menu.calls': 'Llamadas',
  'root.menu.discover': 'Descubrir',
  'root.menu.communities': 'Comunidades',
  'root.menu.settings': 'Ajustes',
  'root.menu.profile': 'Perfil',
  'root.menu.conversations': 'Conversaciones',
  'a11y.floating.feed.hint': 'Mantén pulsado para abrir los Reels',
  'a11y.floating.menu': 'Menú',
  'a11y.floating.menu.ladder': 'Navegación de Meeshy',
  'a11y.floating.menu.unread.one': 'Menú, {count} notificación no leída',
  'a11y.floating.menu.unread.other': 'Menú, {count} notificaciones no leídas',
  'a11y.floating.rung.notifications.unread.one': 'Notificaciones, {count} no leída',
  'a11y.floating.rung.notifications.unread.other': 'Notificaciones, {count} no leídas',

  'notifications.category.all': 'Todas',
  'notifications.category.unread': 'No leídas',
  'notifications.category.messages': 'Mensajes',
  'notifications.category.reactions': 'Reacciones',
  'notifications.category.mentions': 'Menciones',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contactos',
  'notifications.category.groups': 'Grupos',
  'notifications.category.calls': 'Llamadas',
  'notifications.category.translations': 'Traducciones',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorías de notificaciones',
  'notifications.markAllRead': 'Marcar todo como leído',
  'notifications.unreadCount.one': '{count} no leída',
  'notifications.unreadCount.other': '{count} no leídas',
  'notifications.unread': 'No leída',
  'notifications.empty.all': 'No hay notificaciones',
  'notifications.empty.unread': 'No hay notificaciones no leídas',
  'notifications.empty.category': 'No hay notificaciones en «{category}»',
  'notifications.empty.subtitle': 'Tus notificaciones aparecerán aquí',
  'notifications.loading': 'Cargando notificaciones',
  'notifications.error.title': 'No se pudieron cargar las notificaciones',
  'notifications.error.body': 'Inténtalo de nuevo en un momento.',
  'notifications.offline.title': 'Sin conexión',
  'notifications.offline.body': 'Tus notificaciones aparecerán cuando vuelvas a estar en línea.',
  'notifications.retry': 'Reintentar',
  'notifications.allLoaded': 'Todas las notificaciones están cargadas',
  'notifications.actions': 'Acciones de la notificación',
  'notifications.action.markRead': 'Marcar como leída',
  'notifications.action.delete': 'Eliminar',
  'notifications.failure': 'La acción no se completó. Inténtalo de nuevo.',

  'notFound.title': 'Esta dirección no existe.',

  'pending.back': 'Volver a las conversaciones',

  'profile.title': 'Perfil',
  'profile.edit': 'Editar',
  'profile.cancel': 'Cancelar',
  'profile.save': 'Guardar',
  'profile.saving': 'Guardando…',
  'profile.saved': 'Perfil guardado',
  'profile.save.error': 'Error al guardar',
  'profile.save.offline': 'Sin conexión — el cambio no se envió.',
  'profile.save.invalid': 'Revisa el campo «{field}».',
  'profile.loading': 'Cargando el perfil',
  'profile.error.title': 'No se pudo cargar tu perfil',
  'profile.error.body': 'Vuelve a intentarlo en un momento.',
  'profile.retry': 'Reintentar',
  'profile.offline.title': 'Sin conexión',
  'profile.offline.body': 'Tu perfil sigue visible; la edición vuelve con la red.',
  'profile.avatar.edit': 'Editar foto de perfil',
  'profile.avatar.updated': 'Foto de perfil actualizada',
  'profile.avatar.error': 'No se pudo actualizar la foto de perfil',
  'profile.banner.edit': 'Editar banner',
  'profile.banner.updated': 'Banner actualizado',
  'profile.banner.error': 'No se pudo actualizar el banner',
  'profile.image.uploading': 'Enviando',
  'profile.image.cancel': 'Cancelar el envío',
  'profile.image.cancelled': 'Envío cancelado',
  'profile.image.unreadable': 'Esta imagen no se puede leer.',
  'profile.section.identity': 'IDENTIDAD',
  'profile.section.contact': 'CONTACTO',
  'profile.section.languages': 'IDIOMAS',
  'profile.section.stats': 'ESTADÍSTICAS',
  'profile.section.requests': 'SOLICITUDES',
  'profile.section.member_since': 'MIEMBRO DESDE',
  'profile.first_name': 'Nombre',
  'profile.last_name': 'Apellido',
  'profile.username': 'Usuario',
  'profile.display_name': 'Nombre visible',
  'profile.bio': 'Biografía',
  'profile.bio.placeholder': 'Cuéntanos sobre ti...',
  'profile.email': 'Correo electrónico',
  'profile.phone': 'Teléfono',
  'profile.verified': 'Verificado',
  'profile.not_verified': 'No verificado',
  'profile.language.primary': 'Idioma principal',
  'profile.language.primary.subtitle': 'El contenido se traducirá a este idioma',
  'profile.language.regional': 'Idioma regional',
  'profile.language.custom': 'Idioma personalizado',
  'profile.language.none': 'Ninguno',
  'profile.language.choose': 'Elegir',
  'profile.language.clear.regional': 'Quitar el idioma regional',
  'profile.language.clear.custom': 'Quitar el idioma personalizado',

  'languageSheet.title.read': 'Idioma de lectura',
  'languageSheet.title.write': 'Idioma de escritura',
  'languageSheet.search': 'Buscar un idioma',
  'languageSheet.empty': 'Ningún idioma coincide con «{search}».',

  'profile.stats.messages': 'Mensajes',
  'profile.stats.translations': 'Traducciones',
  'profile.stats.languages': 'Idiomas',
  'profile.stats.days': 'Días',
  'profile.stats.loading': 'Cargando las estadísticas',
  'profile.progression.title': 'Progreso',
  'profile.progression.subtitle': 'Insignias, nivel y racha',
  'profile.friend_requests': 'Solicitudes de amistad',
  'profile.friend_requests.count.one': '{count} solicitud pendiente',
  'profile.friend_requests.count.other': '{count} solicitudes pendientes',

  'settings.title': 'Ajustes',
  'settings.my_profile': 'Mi perfil',
  'settings.section.account': 'Cuenta',
  'settings.security.title': 'Seguridad',
  'settings.delete_account': 'Eliminar cuenta',
  'settings.privacy.title': 'Privacidad',
  'settings.privacy.online_status': 'Estado en línea',
  'settings.privacy.online_status.info':
    'El punto verde en tu avatar indica que estás activo. Desactivado, nadie lo ve, pero escribir en una conversación sigue delatando tu actividad.',
  'settings.privacy.last_seen': 'Último inicio de sesión',
  'settings.privacy.read_receipts': 'Confirmaciones de lectura',
  'settings.privacy.read_receipts.info':
    'Es recíproco: si no envías confirmaciones de lectura, tampoco verás si han leído tus mensajes.',
  'settings.privacy.typing_indicator': 'Indicador de escritura',
  'settings.section.appearance': 'Apariencia',
  'settings.theme': 'Tema',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Claro',
  'settings.theme.dark': 'Oscuro',
  'settings.interface_language': 'Idioma de la interfaz',
  'settings.interface_language.automatic': 'Automático',
  'settings.content_languages': 'Idiomas de traducción',
  'settings.section.notifications': 'Notificaciones',
  'settings.notifications.title': 'Notificaciones',
  'settings.notif.sounds': 'Sonidos',
  'settings.notif.more_options': 'Más opciones',
  'settings.section.data': 'Datos',
  'settings.media': 'Multimedia',
  'settings.messages': 'Mensajes',
  'settings.export_data': 'Exportar mis datos',
  'settings.section.tools': 'Herramientas',
  'settings.tools.progression': 'Progreso',
  'settings.section.about': 'Acerca de',
  'settings.terms': 'Términos de servicio',
  'settings.privacy_policy': 'Política de privacidad',
  'settings.version': 'Versión',
  'settings.logout.title': 'Cerrar sesión',
  'settings.logout.message': '¿Seguro que quieres cerrar sesión?',
  'settings.logout.inprogress': 'Cerrando sesión...',
  'settings.legacy': 'Versión clásica, pestaña nueva',
  'settings.legacy.unavailable': 'No disponible en este entorno',
  'settings.loading': 'Cargando los ajustes',
  'settings.error.title': 'No se pudieron cargar tus ajustes',
  'settings.retry': 'Reintentar',
  'settings.offline.body': 'Sin conexión: tus ajustes siguen visibles; podrás cambiarlos cuando vuelva la red.',
  'settings.save.error': 'El ajuste no se guardó.',
  'settings.theme.sync_error': 'Tema aplicado en este dispositivo, sin sincronizar.',
  'common.cancel': 'Cancelar',

  'media.video.play': 'Reproducir vídeo',
  'media.video.pause': 'Pausa',
  'media.video.position': 'Posición de reproducción',
  'media.audio.position': 'Posición de reproducción',
  'media.audio.speed': 'Velocidad de reproducción',
  'media.video.position.value': '{elapsed} de {total}',
  'media.video.mute': 'Silenciar',
  'media.video.unmute': 'Activar sonido',
  'media.video.more_options': 'Más opciones',
  'media.video.speed': 'Velocidad',
  'media.video.pip.enter': 'Imagen en imagen',
  'media.video.pip.exit': 'Salir de imagen en imagen',

  'community.list.create.accessibilityLabel': 'Crear una comunidad',
  'community.list.search.placeholder': 'Buscar comunidades',
  'community.list.search.clear': 'Borrar la búsqueda',
  'community.list.search.empty': 'Ninguna comunidad coincide con «{query}».',
  'community.list.empty.title': 'Ninguna comunidad',
  'community.list.empty.subtitle': 'Únete a una comunidad o crea una para conversar en grupo.',
  'community.list.loading': 'Cargando comunidades',
  'community.error.title': 'No se pudieron cargar las comunidades',
  'community.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'community.retry': 'Reintentar',
  'community.offline.title': 'Sin conexión',
  'community.offline.body': 'Tus comunidades siguen visibles; crear una requiere conexión.',
  'community.privacy.private': 'Privada',
  'community.privacy.public': 'Pública',
  'community.members.one': '{count} miembro',
  'community.members.other': '{count} miembros',
  'community.conversations.one': '{count} conversación',
  'community.conversations.other': '{count} conversaciones',
  'community.detail.stats.members': 'Miembros',
  'community.detail.channels': 'Conversaciones',
  'community.detail.channels.empty': 'Aún no participas en ninguna conversación de esta comunidad.',
  'community.detail.untitled': 'Conversación sin título',
  'community.detail.back': 'Volver a las comunidades',
  'community.detail.refused.title': 'Comunidad no encontrada',
  'community.detail.refused.body': 'No existe, o es privada y no eres miembro.',
  'community.detail.error.title': 'No se pudo cargar esta comunidad',
  'community.detail.loading': 'Cargando la comunidad',
  'community.create.title': 'Nueva comunidad',
  'community.create.preview.placeholder': 'Mi comunidad',
  'community.create.field.name': 'Nombre',
  'community.create.field.name.placeholder': 'Nombre de la comunidad',
  'community.create.field.identifier': 'Identificador',
  'community.create.field.identifier.placeholder': 'mi-grupo',
  'community.create.field.description': 'Descripción',
  'community.create.field.description.placeholder': '¿De qué trata esta comunidad?',
  'community.create.privacy.title': 'Comunidad privada',
  'community.create.privacy.private.description': 'Solo los miembros invitados pueden unirse',
  'community.create.privacy.public.description': 'Cualquiera puede descubrirla y unirse',
  'community.create.button': 'Crear la comunidad',
  'community.create.inprogress': 'Creando…',
  'community.create.error.name': 'Ponle un nombre de 100 caracteres como máximo.',
  'community.create.error.identifier': 'Solo letras, números, guiones y guiones bajos, 50 como máximo.',
  'community.create.error.description': '500 caracteres como máximo.',
  'community.create.error.conflict': 'Este identificador ya está en uso.',
  'community.create.error.offline': 'Sin conexión: la comunidad no se envió.',
  'community.create.error.default': 'No se creó la comunidad. Vuelve a intentarlo.',
  'calls.filters': 'Filtrar el registro de llamadas',
  'calls.filter.all': 'Todas',
  'calls.filter.missed': 'Perdidas',
  'calls.direction.incoming': 'Recibida',
  'calls.direction.outgoing': 'Realizada',
  'calls.direction.missed': 'Perdida',
  'calls.a11y.incoming': 'llamada recibida',
  'calls.a11y.outgoing': 'llamada realizada',
  'calls.a11y.missed': 'llamada perdida',
  'calls.type.audio': 'llamada de voz',
  'calls.type.video': 'videollamada',
  'calls.duration': 'duración {duration}',
  'calls.unknown': 'Desconocido',
  'calls.empty.title': 'No hay llamadas recientes',
  'calls.empty.subtitle': 'Aquí aparecerán tus llamadas recibidas, perdidas, canceladas y realizadas.',
  'calls.empty.missed.title': 'No hay llamadas perdidas',
  'calls.empty.missed.subtitle': 'Aquí aparecerán las llamadas que no respondiste.',
  'calls.error.title': 'No se pudo cargar el registro de llamadas',
  'calls.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'calls.offline.title': 'Sin conexión',
  'calls.offline.body': 'Ves el registro de la última carga.',
  'calls.offline.cold.body': 'El registro se cargará en cuanto vuelva la conexión.',
  'calls.retry': 'Reintentar',
  'calls.loading': 'Cargando el registro de llamadas',
  'calls.allLoaded': 'Todas las llamadas de los últimos tres meses están cargadas',

  'discover.tabs': 'Secciones de descubrir',
  'discover.tab.discover': 'Descubrir',
  'discover.tab.requests': 'Solicitudes',
  'discover.tab.blocked': 'Bloqueados',
  'discover.tab.requests.count.one': 'Solicitudes, {count} recibida',
  'discover.tab.requests.count.other': 'Solicitudes, {count} recibidas',
  'discover.invite.title': 'Invitar por correo',
  'discover.invite.placeholder': 'Correo electrónico',
  'discover.invite.send': 'Enviar',
  'discover.invite.sending': 'Enviando…',
  'discover.invite.sendLabel': 'Enviar la invitación por correo',
  'discover.invite.sent': 'Invitación enviada a {email}',
  'discover.invite.invalid': 'Este correo electrónico no es válido.',
  'discover.invite.conflict': 'Esta persona ya está en Meeshy: búscala abajo.',
  'discover.invite.error': 'No se pudo enviar la invitación. Inténtalo de nuevo.',
  'discover.invite.offline': 'Sin conexión: vuelve a conectarte para enviar la invitación.',
  'discover.search.label': 'Buscar un usuario de Meeshy',
  'discover.search.clear': 'Borrar la búsqueda',
  'discover.search.searching': 'Buscando',
  'discover.search.empty': 'Ningún usuario encontrado para «{query}»',
  'discover.search.error': 'La búsqueda falló. Comprueba tu conexión.',
  'discover.connection.add': 'Añadir',
  'discover.connection.addLabel': 'Añadir a {name}',
  'discover.connection.pending': 'Pendiente',
  'discover.connection.cancelLabel': 'Cancelar la solicitud enviada a {name}',
  'discover.connection.contact': 'Contacto',
  'discover.connection.blocked': 'Bloqueado',
  'discover.connection.acceptLabel': 'Aceptar la solicitud de {name}',
  'discover.connection.rejectLabel': 'Rechazar la solicitud de {name}',
  'discover.requests.filters': 'Filtrar las solicitudes',
  'discover.requests.received': 'Recibidas',
  'discover.requests.sent': 'Enviadas',
  'discover.requests.intent': 'Quiere conectar contigo',
  'discover.requests.cancel': 'Cancelar',
  'discover.requests.empty.received.title': 'Ninguna solicitud recibida',
  'discover.requests.empty.received.subtitle': 'Las solicitudes de contacto que recibas aparecerán aquí.',
  'discover.requests.empty.sent.title': 'Ninguna solicitud enviada',
  'discover.requests.empty.sent.subtitle': 'Las solicitudes que envíes aparecerán aquí.',
  'discover.blocked.unblock': 'Desbloquear',
  'discover.blocked.unblockLabel': 'Desbloquear a {name}',
  'discover.blocked.confirm.title': '¿Desbloquear?',
  'discover.blocked.confirm.body': '¿Desbloquear a {name}?',
  'discover.blocked.confirm.cancel': 'Cancelar',
  'discover.blocked.empty.title': 'Ningún usuario bloqueado',
  'discover.blocked.empty.subtitle': 'Las personas que bloquees aparecerán aquí.',
  'discover.unknown': 'Desconocido',
  'discover.loading': 'Cargando',
  'discover.allLoaded': 'La lista completa está cargada',
  'discover.error.title': 'No se pudo cargar esta lista',
  'discover.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'discover.offline.title': 'Sin conexión',
  'discover.offline.body': 'Ves la lista de la última carga.',
  'discover.offline.cold.body': 'La lista se cargará en cuanto vuelva la conexión.',
  'discover.retry': 'Reintentar',
  'discover.announce.accepted': 'Conexión aceptada',
  'discover.announce.rejected': 'Solicitud rechazada',
  'discover.announce.cancelled': 'Solicitud cancelada',
  'discover.announce.sent': 'Solicitud enviada',
  'discover.announce.unblocked': 'Usuario desbloqueado',
  'discover.announce.acceptFailed': 'No se pudo aceptar esta solicitud',
  'discover.announce.rejectFailed': 'No se pudo rechazar esta solicitud',
  'discover.announce.cancelFailed': 'No se pudo cancelar esta solicitud',
  'discover.announce.sendFailed': 'No se pudo enviar la solicitud',
  'discover.announce.unblockFailed': 'No se pudo desbloquear',
  'discover.announce.offline': 'Sin conexión: no se envió nada.',

  'a11y.floating.rung.discover.requests.one': 'Descubrir, {count} solicitud recibida',
  'a11y.floating.rung.discover.requests.other': 'Descubrir, {count} solicitudes recibidas',

  'links.hub.banner.title': 'Gestiona tus enlaces',
  'links.hub.banner.subtitle': 'Invita a quien quieras a tus conversaciones',
  'links.hub.share.title': 'Enlaces para compartir',
  'links.hub.share.description': 'Invita a tus contactos a unirse a tus conversaciones',
  'links.hub.share.create': 'Crear un enlace para compartir',
  'links.share.back': 'Volver a Mis enlaces',
  'links.share.stats.total': 'Enlaces',
  'links.share.stats.active': 'Activos',
  'links.share.stats.joined': 'Unidos',
  'links.share.joined.one': '{count} unido',
  'links.share.joined.other': '{count} unidos',
  'links.share.copy': 'Copiar el enlace',
  'links.share.empty.title': 'Ningún enlace para compartir',
  'links.share.empty.subtitle': 'Crea un enlace para invitar a personas a una conversación',
  'links.share.loading': 'Cargando enlaces',
  'links.share.allLoaded': 'Todos tus enlaces están cargados',
  'links.status.active': 'Activo',
  'links.status.inactive': 'Inactivo',
  'links.unlimited': 'Ilimitado',
  'links.error.title': 'No se pudieron cargar tus enlaces',
  'links.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'links.retry': 'Reintentar',
  'links.offline.title': 'Sin conexión',
  'links.offline.body': 'Tus enlaces siguen visibles; para modificarlos se necesita la red.',
  'links.detail.back': 'Volver a los enlaces para compartir',
  'links.detail.copy': 'Copiar',
  'links.detail.copied': 'Copiado',
  'links.detail.share': 'Compartir',
  'links.detail.disable': 'Desactivar',
  'links.detail.activate': 'Activar',
  'links.detail.stats': 'Estadísticas',
  'links.detail.stats.uses': 'Usos',
  'links.detail.stats.max': 'Máximo',
  'links.detail.info': 'Información',
  'links.detail.identifier': 'Identificador',
  'links.detail.createdAt': 'Creado el',
  'links.detail.expiresAt': 'Caduca el',
  'links.detail.reason.closed': 'La conversación está cerrada: este enlace ya no permite entrar.',
  'links.detail.reason.expired': 'Este enlace ha caducado.',
  'links.detail.reason.revoked': 'Desactivaste este enlace.',
  'links.detail.refused.title': 'Enlace no encontrado',
  'links.detail.refused.body': 'Este enlace no existe o no es uno de los tuyos.',
  'links.detail.loading': 'Cargando el enlace',
  'links.announce.copied': 'Enlace copiado',
  'links.announce.copyFailed': 'No se pudo copiar el enlace',
  'links.announce.shareUnavailable': 'Compartir no está disponible aquí',
  'links.announce.disabled': 'Enlace desactivado',
  'links.announce.activated': 'Enlace activado',
  'links.announce.toggleFailed': 'No se pudo modificar este enlace',
  'links.announce.offline': 'Sin conexión: no se envió nada.',
  'links.create.title': 'Nuevo enlace para compartir',
  'links.create.section.conversation': 'Conversación',
  'links.create.choose': 'Elegir un grupo o una comunidad',
  'links.create.picker.title': 'Elegir una conversación',
  'links.create.picker.empty': 'Ninguna conversación puede recibir un enlace por ahora.',
  'links.create.section.identity': 'Identidad del enlace',
  'links.create.name': 'Nombre del enlace',
  'links.create.name.placeholder': 'p. ej.: Compartir en Twitter',
  'links.create.description': 'Descripción (opcional)',
  'links.create.description.placeholder': 'p. ej.: Únete a nuestro grupo…',
  'links.create.section.access': 'Acceso de invitados',
  'links.create.section.access.subtitle': 'Lo que los visitantes deben aportar para unirse',
  'links.create.access.account': 'Cuenta obligatoria',
  'links.create.access.account.caption': 'Solo los miembros de Meeshy pueden unirse',
  'links.create.access.nickname': 'Seudónimo obligatorio',
  'links.create.access.nickname.caption': 'El visitante debe elegir un seudónimo',
  'links.create.access.email': 'Correo electrónico obligatorio',
  'links.create.access.email.caption': 'El visitante debe indicar su correo electrónico',
  'links.create.access.birthday': 'Fecha de nacimiento obligatoria',
  'links.create.access.birthday.caption': 'Permite el control de edad',
  'links.create.section.permissions': 'Permisos',
  'links.create.section.permissions.subtitle': 'Lo que pueden hacer los invitados anónimos',
  'links.create.permission.messages': 'Enviar mensajes',
  'links.create.permission.messages.caption': 'Los invitados pueden escribir en la conversación',
  'links.create.permission.images': 'Enviar imágenes',
  'links.create.permission.images.caption': 'Los invitados pueden compartir fotos',
  'links.create.permission.files': 'Enviar archivos',
  'links.create.permission.files.caption': 'Los invitados pueden enviar documentos',
  'links.create.permission.history': 'Ver el historial',
  'links.create.permission.history.caption': 'Los invitados ven los mensajes anteriores',
  'links.create.section.limits': 'Límites',
  'links.create.section.limits.subtitle': 'Controla la audiencia y la duración del enlace',
  'links.create.limit.uses': 'Limitar los usos',
  'links.create.limit.max.one': 'Como máximo {count} uso',
  'links.create.limit.max.other': 'Como máximo {count} usos',
  'links.create.limit.count': 'Número de usos',
  'links.create.limit.invalid': 'Elige un número entero entre 1 y {max}.',
  'links.create.expiration': 'Caducidad',
  'links.create.expiration.never': 'Nunca',
  'links.create.expiration.h24': '24 horas',
  'links.create.expiration.d7': '7 días',
  'links.create.expiration.d30': '30 días',
  'links.create.expiration.m3': '3 meses',
  'links.create.button': 'Crear el enlace para compartir',
  'links.create.inprogress': 'Creando…',
  'links.create.error.conversation': 'Elige primero una conversación.',
  'links.create.error.offline': 'Sin conexión: el enlace no se creó.',
  'links.create.error.refused': 'No puedes crear un enlace para esta conversación.',
  'links.create.error.default': 'No se pudo crear el enlace. Vuelve a intentarlo.',

  /* L'ESPACE D'ADMINISTRATION (#6432) — les onze sections reprennent les
     libellés de la barre latérale du legacy (`AdminLayout.tsx`), pour qu'un
     administrateur retrouve ses repères d'une application à l'autre. */
  'admin.title': 'Administración',
  'admin.role': 'Tu rol: {role}',
  'admin.denied.title': 'Zona reservada',
  'admin.denied.message': 'Esta zona requiere un permiso de administración.',
  'admin.counters.title': 'De un vistazo',
  'admin.counters.unavailable': 'Contadores no disponibles por ahora.',
  'admin.counters.users': 'Cuentas',
  'admin.counters.activeUsers': 'Cuentas activas',
  'admin.counters.messages': 'Mensajes',
  'admin.counters.communities': 'Comunidades',
  'admin.counters.reports': 'Denuncias',
  'admin.counters.newUsers': 'Nuevas (24 h)',
  'admin.sections.title': 'Secciones',
  'admin.sections.legacy': 'interfaz anterior',
  'admin.nav.dashboard': 'Panel',
  'admin.nav.users': 'Cuentas',
  'admin.nav.moderation': 'Moderación',
  'admin.nav.audit': 'Registros de auditoría',
  'admin.nav.analytics': 'Estadísticas',
  'admin.nav.trackingLinks': 'Enlaces de seguimiento',
  'admin.nav.ranking': 'Clasificación',
  'admin.nav.broadcasts': 'Difusiones',
  'admin.nav.settings': 'Ajustes',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Supervisión',
  'admin.users.search': 'Buscar una cuenta',
  'admin.users.count': '{count} cuenta(s)',
  'admin.users.empty': 'Ninguna cuenta coincide.',
  'admin.users.unavailable': 'Lista no disponible por ahora.',
  'admin.users.inactive': 'desactivada',
  'admin.users.previous': 'Anteriores',
  'admin.users.next': 'Siguientes',

} satisfies InterfaceCatalog;

export default es;
