import type { InterfaceCatalog } from '@/lib/i18n-catalog';

/**
 * Le portugais du web est celui qu'iOS catalogue sous `pt-BR` : le script
 * d'amorçage réduit la locale du navigateur à sa langue (`pt-BR` → `pt`).
 */
const pt = {
  'announce.messageSent': 'Mensagem enviada',
  'announce.messageCopied': 'Mensagem copiada',
  'announce.messagesCopied': 'Mensagens copiadas',
  'announce.messageProtected': 'Mensagem protegida',
  'announce.selectionCap': 'Máximo de {count} mensagens',
  'announce.nothingToCopy': 'Nada para copiar',

  'message.author.self': 'Você',
  'message.excerpt.protected': 'conteúdo protegido',
  'a11y.message.menu.subject': 'Ações da mensagem de {author}: {excerpt}',

  'typing.named': '{name} está escrevendo',
  'typing.double': '{first} e {second} estão escrevendo',
  'typing.several': 'Várias pessoas estão escrevendo',

  'feed.header.reels': 'Abrir Reels',
  'reels.title': 'Reels',
  'reels.back': 'Voltar',
  'reels.open': 'Ver o reel de {author}',
  'reels.item': 'Reel de {author}, {index} de {count}',
  'reels.loading': 'Carregando reels',
  'reels.empty': 'Nenhum reel por enquanto',
  'reels.empty.hint': 'Os reels dos seus contatos aparecerão aqui.',
  'reels.error': 'Não foi possível carregar os reels',
  'reels.error.hint': 'Tente novamente em instantes.',
  'reels.retry': 'Tentar novamente',
  'reels.offline': 'Sem conexão',
  'reels.offline.cold': 'Os reels serão carregados quando a conexão voltar.',
  'reels.action.like': 'Curtir',
  'reels.action.bookmark': 'Salvar',
  'reels.action.share': 'Compartilhar',
  'reels.sound.on': 'Ativar o som',
  'reels.sound.off': 'Silenciar',
  'reels.play': 'Reproduzir o reel',
  'reels.pause': 'Pausar o reel',
  'reels.media.error': 'Não foi possível reproduzir — Tentar novamente',
  'reels.image': 'Imagem {index} de {count}',

  'stories.title': 'Stories',
  'stories.loading': 'Carregando stories…',
  'stories.error': 'Não foi possível carregar os stories.',
  'stories.empty.title': 'Nenhum story por enquanto',
  'stories.empty.subtitle': 'Os stories dos seus contatos vão aparecer aqui por vinte e quatro horas.',
  'stories.create': 'Criar um story',
  'stories.count.one': '{count} story',
  'stories.count.other': '{count} stories',
  'stories.mine': 'Seu story',

  'feed.post.action.like': 'Curtir',
  'feed.post.action.comment': 'Comentar',
  'feed.post.action.repost': 'Republicar',
  'feed.post.action.bookmark': 'Salvar',
  'feed.post.action.share': 'Compartilhar',
  'feed.post.media.video': 'Vídeo',
  'feed.post.media.audio': 'Áudio',
  'feed.post.media.previous': 'Mídia anterior',
  'feed.post.media.next': 'Próxima mídia',
  'feed.post.media.mosaic': 'Mosaico de {count} mídias',
  'feed.post.see_more': 'ver mais',
  'feed.post.see_less': 'ver menos',
  'feed.post.reel.chip': 'Reel',
  'feed.post.reel.of': 'Reel de {author}',
  'feed.error.title': 'Não foi possível carregar o feed',
  'feed.error.body': 'Tente novamente em instantes.',
  'feed.offline.title': 'Sem conexão',
  'feed.offline.body': 'O feed vai aparecer quando a conexão voltar.',
  'feed.retry': 'Tentar novamente',
  'feed.empty.title': 'Nenhuma publicação por enquanto',
  'feed.empty.subtitle': 'As publicações dos seus contatos vão aparecer aqui.',
  'feed.loading': 'Carregando o feed',
  'feed.allLoaded': 'Todas as publicações foram carregadas',
  'feed.like.error': 'Erro ao curtir a publicação',
  'post.bookmark.error': 'Não foi possível salvar',
  'feed.gesture.pending': 'Ação não confirmada — offline',
  'feed.share.error': 'Erro ao compartilhar a publicação',
  'feed.share.copied': 'Link copiado — é só colar.',
  'feed.share.text': 'Uma publicação no Meeshy',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'Meus links',
  'root.menu.notifications': 'Notificações',
  'root.menu.calls': 'Chamadas',
  'root.menu.discover': 'Descobrir',
  'root.menu.communities': 'Comunidades',
  'root.menu.settings': 'Ajustes',
  'root.menu.profile': 'Perfil',
  'root.menu.conversations': 'Conversas',
  'a11y.floating.feed.hint': 'Toque longo para abrir os Reels',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Navegação do Meeshy',
  'a11y.floating.menu.unread.one': 'Menu, {count} notificação não lida',
  'a11y.floating.menu.unread.other': 'Menu, {count} notificações não lidas',
  'a11y.floating.rung.notifications.unread.one': 'Notificações, {count} não lida',
  'a11y.floating.rung.notifications.unread.other': 'Notificações, {count} não lidas',

  'notifications.category.all': 'Todas',
  'notifications.category.unread': 'Não lidas',
  'notifications.category.messages': 'Mensagens',
  'notifications.category.reactions': 'Reações',
  'notifications.category.mentions': 'Menções',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contatos',
  'notifications.category.groups': 'Grupos',
  'notifications.category.calls': 'Chamadas',
  'notifications.category.translations': 'Traduções',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorias de notificações',
  'notifications.markAllRead': 'Marcar tudo como lido',
  'notifications.unreadCount.one': '{count} não lida',
  'notifications.unreadCount.other': '{count} não lidas',
  'notifications.unread': 'Não lida',
  'notifications.empty.all': 'Nenhuma notificação',
  'notifications.empty.unread': 'Nenhuma notificação não lida',
  'notifications.empty.category': 'Nenhuma notificação em “{category}”',
  'notifications.empty.subtitle': 'Suas notificações vão aparecer aqui',
  'notifications.loading': 'Carregando notificações',
  'notifications.error.title': 'Não foi possível carregar as notificações',
  'notifications.error.body': 'Tente novamente em instantes.',
  'notifications.offline.title': 'Sem conexão',
  'notifications.offline.body': 'Suas notificações vão aparecer quando a conexão voltar.',
  'notifications.retry': 'Tentar novamente',
  'notifications.allLoaded': 'Todas as notificações foram carregadas',
  'notifications.actions': 'Ações da notificação',
  'notifications.action.markRead': 'Marcar como lida',
  'notifications.action.delete': 'Excluir',
  'notifications.failure': 'A ação não foi concluída. Tente novamente.',

  'notFound.title': 'Este endereço não existe.',

  'pending.back': 'Voltar às conversas',

  'linkPage.home': 'Voltar ao Meeshy',
  'linkPage.retry': 'Tentar de novo',
  'linkPage.settings': 'Abrir as configurações',
  'linkPage.signIn': 'Entrar',
  'linkPage.offline.title': 'Sem conexão',
  'linkPage.offline.body': 'Conecte-se novamente à internet e tente de novo.',
  'linkPage.unavailable.title': 'O Meeshy não está respondendo',
  'linkPage.unavailable.body': 'O serviço está temporariamente indisponível. Tente de novo em alguns instantes.',
  'linkPage.rateLimited': 'Tentativas demais. Aguarde um pouco antes de tentar de novo.',
  'linkPage.signedOut.title': 'Entre para continuar',
  'linkPage.signedOut.body': 'Este link age sobre a sua conta. Entre e depois abra-o novamente pelo e-mail.',
  'linkPage.expired': 'Este link expirou. Faça o pedido novamente nas configurações.',
  'trackingLink.opening': 'Abrindo o link…',
  'trackingLink.dead.title': 'Este link não está mais disponível',
  'trackingLink.dead.body': 'Ele expirou, foi desativado ou nunca existiu.',
  'accountDeletion.incomplete.title': 'Link incompleto',
  'accountDeletion.incomplete.body': 'Faltam a este link as informações necessárias. Entre para pedir a exclusão da sua conta.',
  'accountDeletion.confirm.title': 'Confirmar a exclusão da sua conta',
  'accountDeletion.confirm.body':
    'Sua conta será desativada ao fim de um período de carência de 30 dias. Até lá, o link “Cancelar” do e-mail permite voltar atrás.',
  'accountDeletion.confirm.action': 'Confirmar a exclusão',
  'accountDeletion.cancel.title': 'Cancelar a exclusão da sua conta',
  'accountDeletion.cancel.body': 'Sua conta continua ativa e o pedido de exclusão é abandonado. Nada é perdido.',
  'accountDeletion.cancel.action': 'Cancelar a exclusão',
  'accountDeletion.purge.title': 'Excluir sua conta agora',
  'accountDeletion.purge.body': 'Sua conta será desativada imediatamente e todas as suas sessões serão encerradas. Esta ação é definitiva.',
  'accountDeletion.purge.action': 'Excluir agora',
  'accountDeletion.dismiss': 'Não fazer nada',
  'accountDeletion.working': 'Um instante…',
  'accountDeletion.done.title': 'Pronto',
  'accountDeletion.done.confirmed': 'Seu pedido está confirmado: sua conta será desativada em {date}. Você pode cancelar até lá.',
  'accountDeletion.done.cancelled': 'Sua conta continua ativa: o pedido de exclusão foi abandonado.',
  'accountDeletion.done.completed': 'Sua conta está desativada e todas as suas sessões foram encerradas.',
  'accountDeletion.done.purged': 'Seus dados foram apagados.',
  'accountDeletion.closed.title': 'Este link não serve mais',
  'accountDeletion.invalid': 'Este link é inválido ou já foi usado.',
  'accountDeletion.request.title': 'Excluir sua conta',
  'accountDeletion.request.body':
    'Suas conversas, mensagens, mídias, contatos e preferências serão excluídos. Um e-mail pedirá sua confirmação e, depois, um período de carência de 30 dias permitirá voltar atrás.',
  'accountDeletion.request.phrase': 'Digite {phrase} para confirmar',
  'accountDeletion.request.password': 'Senha atual',
  'accountDeletion.request.action': 'Pedir a exclusão',
  'accountDeletion.request.sent.title': 'Enviamos um e-mail de confirmação para você',
  'accountDeletion.request.sent.body': 'Abra-o para confirmar a exclusão da sua conta.',
  'accountDeletion.request.wrongPassword': 'Senha incorreta.',
  'accountDeletion.request.alreadyPending': 'Já existe um pedido em andamento. Abra o e-mail recebido para confirmá-lo ou cancelá-lo.',
  'accountDeletion.request.noEmail': 'Adicione e verifique um endereço de e-mail antes de pedir a exclusão.',
  'emailChange.verifying': 'Confirmando seu novo endereço…',
  'emailChange.done.title': 'Endereço de e-mail alterado',
  'emailChange.done.body': 'Agora você entra com {email}.',
  'emailChange.done.generic': 'Seu novo endereço de e-mail está confirmado.',
  'emailChange.failed.title': 'Endereço não alterado',
  'emailChange.missing': 'Este link não traz um código de confirmação. Abra o do e-mail mais recente.',
  'emailChange.invalid': 'Este link não corresponde a nenhuma alteração pendente nesta conta, ou já foi usado.',
  'emailChange.taken': 'Este endereço agora é usado por outra conta.',
  'emailNotifications.title': 'E-mails do Meeshy',
  'emailNotifications.loading': 'Lendo sua preferência…',
  'emailNotifications.on': 'Você recebe por e-mail os anúncios, resumos e notificações do Meeshy.',
  'emailNotifications.off': 'Você não recebe mais por e-mail os anúncios, resumos nem notificações do Meeshy.',
  'emailNotifications.security': 'Os e-mails de segurança da sua conta continuam chegando.',
  'emailNotifications.unsubscribe': 'Parar de receber estes e-mails',
  'emailNotifications.resubscribe': 'Voltar a receber estes e-mails',
  'emailNotifications.failed': 'A alteração não foi aplicada. Tente de novo.',

  'dataExport.title': 'Exportar meus dados',
  'dataExport.info.body': 'Em conformidade com o RGPD, receba um arquivo com seu perfil, suas mensagens, seus contatos e suas publicações.',
  'dataExport.action.start': 'Exportar meus dados',
  'dataExport.action.exporting': 'Exportando…',
  'dataExport.action.again': 'Exportar novamente',
  'dataExport.done.title': 'Exportação concluída',
  'dataExport.done.body': 'O arquivo foi baixado neste dispositivo.',

  'profile.title': 'Perfil',
  'profile.edit': 'Editar',
  'profile.cancel': 'Cancelar',
  'profile.save': 'Salvar',
  'profile.saving': 'Salvando…',
  'profile.saved': 'Perfil salvo',
  'profile.save.error': 'Erro ao salvar',
  'profile.save.offline': 'Sem conexão — a alteração não foi enviada.',
  'profile.save.invalid': 'Confira o campo “{field}”.',
  'profile.loading': 'Carregando o perfil',
  'profile.error.title': 'Não foi possível carregar seu perfil',
  'profile.error.body': 'Tente de novo em instantes.',
  'profile.retry': 'Tentar de novo',
  'profile.offline.title': 'Sem conexão',
  'profile.offline.body': 'Seu perfil continua legível; a edição volta com a rede.',
  'profile.avatar.edit': 'Editar foto de perfil',
  'profile.avatar.updated': 'Foto de perfil atualizada',
  'profile.avatar.error': 'Não foi possível atualizar a foto de perfil',
  'profile.banner.edit': 'Editar banner',
  'profile.banner.updated': 'Banner atualizado',
  'profile.banner.error': 'Não foi possível atualizar o banner',
  'profile.image.uploading': 'Enviando',
  'profile.image.cancel': 'Cancelar o envio',
  'profile.image.cancelled': 'Envio cancelado',
  'profile.image.unreadable': 'Esta imagem não pode ser lida.',
  'profile.section.identity': 'IDENTIDADE',
  'profile.section.contact': 'CONTATO',
  'profile.section.languages': 'IDIOMAS',
  'profile.section.stats': 'ESTATÍSTICAS',
  'profile.section.requests': 'SOLICITAÇÕES',
  'profile.section.member_since': 'MEMBRO DESDE',
  'profile.first_name': 'Nome',
  'profile.last_name': 'Sobrenome',
  'profile.username': 'Nome de usuário',
  'profile.display_name': 'Nome de exibição',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Fale sobre você...',
  'profile.email': 'E-mail',
  'profile.phone': 'Telefone',
  'profile.verified': 'Verificado',
  'profile.not_verified': 'Não verificado',
  'profile.language.primary': 'Idioma principal',
  'profile.language.primary.subtitle': 'O conteúdo será traduzido para este idioma',
  'profile.language.regional': 'Idioma regional',
  'profile.language.custom': 'Idioma personalizado',
  'profile.language.none': 'Nenhum',
  'profile.language.choose': 'Escolher',
  'profile.language.clear.regional': 'Remover o idioma regional',
  'profile.language.clear.custom': 'Remover o idioma personalizado',

  'languageSheet.title.read': 'Idioma de leitura',
  'languageSheet.title.write': 'Idioma de escrita',
  'languageSheet.search': 'Pesquisar um idioma',
  'languageSheet.empty': 'Nenhum idioma corresponde a “{search}”.',

  'profile.stats.messages': 'Mensagens',
  'profile.stats.translations': 'Traduções',
  'profile.stats.languages': 'Idiomas',
  'profile.stats.days': 'Dias',
  'profile.stats.loading': 'Carregando as estatísticas',
  'profile.progression.title': 'Progresso',
  'profile.progression.subtitle': 'Medalhas, nível e sequência',
  'profile.friend_requests': 'Solicitações de amizade',
  'profile.friend_requests.count.one': '{count} solicitação pendente',
  'profile.friend_requests.count.other': '{count} solicitações pendentes',

  'settings.title': 'Ajustes',
  'settings.my_profile': 'Meu perfil',
  'settings.section.account': 'Conta',
  'settings.security.title': 'Segurança',
  'settings.delete_account': 'Excluir conta',
  'settings.privacy.title': 'Privacidade',
  'settings.privacy.online_status': 'Status online',
  'settings.privacy.online_status.info':
    'O ponto verde no seu avatar indica que você está ativo. Desativado, ninguém o vê — mas escrever em uma conversa continua revelando sua atividade.',
  'settings.privacy.last_seen': 'Último acesso',
  'settings.privacy.read_receipts': 'Confirmações de leitura',
  'settings.privacy.read_receipts.info':
    'É recíproco: se você não enviar confirmações de leitura, também não verá se suas mensagens foram lidas.',
  'settings.privacy.typing_indicator': 'Indicador de digitação',
  'settings.section.appearance': 'Aparência',
  'settings.theme': 'Tema',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Claro',
  'settings.theme.dark': 'Escuro',
  'settings.interface_language': 'Idioma da interface',
  'settings.interface_language.automatic': 'Automático',
  'settings.content_languages': 'Idiomas de tradução',
  'settings.section.notifications': 'Notificações',
  'settings.notifications.title': 'Notificações',
  'settings.notif.sounds': 'Sons',
  'settings.notif.more_options': 'Mais opções',
  'settings.section.data': 'Dados',
  'settings.media': 'Mídia',
  'settings.messages': 'Mensagens',
  'settings.export_data': 'Exportar meus dados',
  'settings.section.tools': 'Ferramentas',
  'settings.tools.progression': 'Progresso',
  'settings.section.about': 'Sobre',
  'settings.terms': 'Termos de uso',
  'settings.privacy_policy': 'Política de privacidade',
  'settings.version': 'Versão',
  'settings.logout.title': 'Sair',
  'settings.logout.message': 'Tem certeza de que deseja sair?',
  'settings.logout.inprogress': 'Saindo...',
  'settings.loading': 'Carregando os ajustes',
  'settings.error.title': 'Não foi possível carregar seus ajustes',
  'settings.retry': 'Tentar de novo',
  'settings.offline.body': 'Sem conexão — seus ajustes continuam visíveis; você poderá alterá-los quando a rede voltar.',
  'settings.save.error': 'O ajuste não foi salvo.',
  'settings.theme.sync_error': 'Tema aplicado neste dispositivo, sem sincronização.',
  'common.cancel': 'Cancelar',

  'media.video.play': 'Reproduzir vídeo',
  'media.video.pause': 'Pausar',
  'media.video.position': 'Posição de reprodução',
  'media.audio.position': 'Posição de reprodução',
  'media.audio.speed': 'Velocidade de reprodução',
  'media.video.position.value': '{elapsed} de {total}',
  'media.video.mute': 'Silenciar',
  'media.video.unmute': 'Ativar som',
  'media.video.more_options': 'Mais opções',
  'media.video.speed': 'Velocidade',
  'media.video.pip.enter': 'Picture-in-Picture',
  'media.video.pip.exit': 'Sair do Picture-in-Picture',

  'community.list.create.accessibilityLabel': 'Criar uma comunidade',
  'community.list.search.placeholder': 'Pesquisar comunidades',
  'community.list.search.clear': 'Limpar a pesquisa',
  'community.list.search.empty': 'Nenhuma comunidade corresponde a “{query}”.',
  'community.list.empty.title': 'Nenhuma comunidade',
  'community.list.empty.subtitle': 'Participe de uma comunidade ou crie uma para conversar em grupo.',
  'community.list.loading': 'Carregando comunidades',
  'community.error.title': 'Não foi possível carregar as comunidades',
  'community.error.body': 'Verifique sua conexão e tente novamente.',
  'community.retry': 'Tentar novamente',
  'community.offline.title': 'Sem conexão',
  'community.offline.body': 'Suas comunidades continuam visíveis; criar uma exige conexão.',
  'community.privacy.private': 'Privada',
  'community.privacy.public': 'Pública',
  'community.members.one': '{count} membro',
  'community.members.other': '{count} membros',
  'community.conversations.one': '{count} conversa',
  'community.conversations.other': '{count} conversas',
  'community.detail.stats.members': 'Membros',
  'community.detail.channels': 'Conversas',
  'community.detail.channels.empty': 'Você ainda não participa de nenhuma conversa desta comunidade.',
  'community.detail.untitled': 'Conversa sem título',
  'community.detail.back': 'Voltar às comunidades',
  'community.detail.refused.title': 'Comunidade não encontrada',
  'community.detail.refused.body': 'Ela não existe, ou é privada e você não é membro.',
  'community.detail.error.title': 'Não foi possível carregar esta comunidade',
  'community.detail.loading': 'Carregando a comunidade',
  'community.create.title': 'Nova comunidade',
  'community.create.preview.placeholder': 'Minha comunidade',
  'community.create.field.name': 'Nome',
  'community.create.field.name.placeholder': 'Nome da comunidade',
  'community.create.field.identifier': 'Identificador',
  'community.create.field.identifier.placeholder': 'meu-grupo',
  'community.create.field.description': 'Descrição',
  'community.create.field.description.placeholder': 'Sobre o que é esta comunidade?',
  'community.create.privacy.title': 'Comunidade privada',
  'community.create.privacy.private.description': 'Somente membros convidados podem entrar',
  'community.create.privacy.public.description': 'Qualquer pessoa pode descobri-la e entrar',
  'community.create.button': 'Criar a comunidade',
  'community.create.inprogress': 'Criando…',
  'community.create.error.name': 'Dê um nome com no máximo 100 caracteres.',
  'community.create.error.identifier': 'Somente letras, números, hifens e sublinhados, no máximo 50.',
  'community.create.error.description': 'No máximo 500 caracteres.',
  'community.create.error.conflict': 'Este identificador já está em uso.',
  'community.create.error.offline': 'Sem conexão — a comunidade não foi enviada.',
  'community.create.error.default': 'A comunidade não foi criada. Tente novamente.',
  'calls.filters': 'Filtrar o histórico de chamadas',
  'calls.filter.all': 'Todas',
  'calls.filter.missed': 'Perdidas',
  'calls.direction.incoming': 'Recebida',
  'calls.direction.outgoing': 'Efetuada',
  'calls.direction.missed': 'Perdida',
  'calls.a11y.incoming': 'chamada recebida',
  'calls.a11y.outgoing': 'chamada efetuada',
  'calls.a11y.missed': 'chamada perdida',
  'calls.type.audio': 'chamada de voz',
  'calls.type.video': 'chamada de vídeo',
  'calls.duration': 'duração {duration}',
  'calls.unknown': 'Desconhecido',
  'calls.empty.title': 'Nenhuma chamada recente',
  'calls.empty.subtitle': 'Suas chamadas recebidas, perdidas, canceladas e feitas aparecerão aqui.',
  'calls.empty.missed.title': 'Nenhuma chamada perdida',
  'calls.empty.missed.subtitle': 'As chamadas que você não atendeu aparecerão aqui.',
  'calls.error.title': 'Não foi possível carregar o histórico de chamadas',
  'calls.error.body': 'Verifique sua conexão e tente novamente.',
  'calls.offline.title': 'Sem conexão',
  'calls.offline.body': 'Você está vendo o histórico do último carregamento.',
  'calls.offline.cold.body': 'O histórico será carregado assim que a conexão voltar.',
  'calls.retry': 'Tentar novamente',
  'calls.loading': 'Carregando o histórico de chamadas',
  'calls.allLoaded': 'Todas as chamadas dos últimos três meses foram carregadas',

  'discover.tabs': 'Seções de descoberta',
  'discover.tab.discover': 'Descobrir',
  'discover.tab.requests': 'Pedidos',
  'discover.tab.blocked': 'Bloqueados',
  'discover.tab.requests.count.one': 'Pedidos, {count} recebido',
  'discover.tab.requests.count.other': 'Pedidos, {count} recebidos',
  'discover.invite.title': 'Convidar por e-mail',
  'discover.invite.placeholder': 'Endereço de e-mail',
  'discover.invite.send': 'Enviar',
  'discover.invite.sending': 'Enviando…',
  'discover.invite.sendLabel': 'Enviar o convite por e-mail',
  'discover.invite.sent': 'Convite enviado para {email}',
  'discover.invite.invalid': 'Este endereço de e-mail não é válido.',
  'discover.invite.conflict': 'Esta pessoa já está no Meeshy: procure-a abaixo.',
  'discover.invite.error': 'Não foi possível enviar o convite. Tente novamente.',
  'discover.invite.offline': 'Sem conexão: conecte-se para enviar o convite.',
  'discover.search.label': 'Buscar um usuário do Meeshy',
  'discover.search.clear': 'Limpar a busca',
  'discover.search.searching': 'Buscando',
  'discover.search.empty': 'Nenhum usuário encontrado para “{query}”',
  'discover.search.error': 'A busca falhou. Verifique sua conexão.',
  'discover.connection.add': 'Adicionar',
  'discover.connection.addLabel': 'Adicionar {name}',
  'discover.connection.pending': 'Pendente',
  'discover.connection.cancelLabel': 'Cancelar o pedido enviado a {name}',
  'discover.connection.contact': 'Contato',
  'discover.connection.blocked': 'Bloqueado',
  'discover.connection.acceptLabel': 'Aceitar o pedido de {name}',
  'discover.connection.rejectLabel': 'Recusar o pedido de {name}',
  'discover.requests.filters': 'Filtrar os pedidos',
  'discover.requests.received': 'Recebidos',
  'discover.requests.sent': 'Enviados',
  'discover.requests.intent': 'Gostaria de se conectar com você',
  'discover.requests.cancel': 'Cancelar',
  'discover.requests.empty.received.title': 'Nenhum pedido recebido',
  'discover.requests.empty.received.subtitle': 'Os pedidos de contato que você receber aparecerão aqui.',
  'discover.requests.empty.sent.title': 'Nenhum pedido enviado',
  'discover.requests.empty.sent.subtitle': 'Os pedidos que você enviar aparecerão aqui.',
  'discover.blocked.unblock': 'Desbloquear',
  'discover.blocked.unblockLabel': 'Desbloquear {name}',
  'discover.blocked.confirm.title': 'Desbloquear?',
  'discover.blocked.confirm.body': 'Desbloquear {name}?',
  'discover.blocked.confirm.cancel': 'Cancelar',
  'discover.blocked.empty.title': 'Nenhum usuário bloqueado',
  'discover.blocked.empty.subtitle': 'As pessoas que você bloquear aparecerão aqui.',
  'discover.unknown': 'Desconhecido',
  'discover.loading': 'Carregando',
  'discover.allLoaded': 'A lista inteira foi carregada',
  'discover.error.title': 'Não foi possível carregar esta lista',
  'discover.error.body': 'Verifique sua conexão e tente novamente.',
  'discover.offline.title': 'Sem conexão',
  'discover.offline.body': 'Você está vendo a lista do último carregamento.',
  'discover.offline.cold.body': 'A lista será carregada assim que a conexão voltar.',
  'discover.retry': 'Tentar novamente',
  'discover.announce.accepted': 'Conexão aceita',
  'discover.announce.rejected': 'Pedido recusado',
  'discover.announce.cancelled': 'Pedido cancelado',
  'discover.announce.sent': 'Pedido enviado',
  'discover.announce.unblocked': 'Usuário desbloqueado',
  'discover.announce.acceptFailed': 'Não foi possível aceitar este pedido',
  'discover.announce.rejectFailed': 'Não foi possível recusar este pedido',
  'discover.announce.cancelFailed': 'Não foi possível cancelar este pedido',
  'discover.announce.sendFailed': 'Não foi possível enviar o pedido',
  'discover.announce.unblockFailed': 'Não foi possível desbloquear',
  'discover.announce.offline': 'Sem conexão: nada foi enviado.',

  'a11y.floating.rung.discover.requests.one': 'Descobrir, {count} pedido recebido',
  'a11y.floating.rung.discover.requests.other': 'Descobrir, {count} pedidos recebidos',

  'links.hub.banner.title': 'Gerencie seus links',
  'links.hub.banner.subtitle': 'Convide quem quiser para suas conversas',
  'links.hub.share.title': 'Links de compartilhamento',
  'links.hub.share.description': 'Convide contatos para entrar nas suas conversas',
  'links.hub.share.create': 'Criar um link de compartilhamento',
  'links.share.back': 'Voltar para Meus links',
  'links.share.stats.total': 'Links',
  'links.share.stats.active': 'Ativos',
  'links.share.stats.joined': 'Entraram',
  'links.share.joined.one': '{count} entrou',
  'links.share.joined.other': '{count} entraram',
  'links.share.copy': 'Copiar o link',
  'links.share.empty.title': 'Nenhum link de compartilhamento',
  'links.share.empty.subtitle': 'Crie um link para convidar pessoas para uma conversa',
  'links.share.loading': 'Carregando links',
  'links.share.allLoaded': 'Todos os seus links foram carregados',
  'links.status.active': 'Ativo',
  'links.status.inactive': 'Inativo',
  'links.unlimited': 'Ilimitado',
  'links.error.title': 'Não foi possível carregar seus links',
  'links.error.body': 'Verifique sua conexão e tente novamente.',
  'links.retry': 'Tentar novamente',
  'links.offline.title': 'Sem conexão',
  'links.offline.body': 'Seus links continuam visíveis; alterá-los exige a rede.',
  'links.detail.back': 'Voltar para os links de compartilhamento',
  'links.detail.copy': 'Copiar',
  'links.detail.copied': 'Copiado',
  'links.detail.share': 'Compartilhar',
  'links.detail.disable': 'Desativar',
  'links.detail.activate': 'Ativar',
  'links.detail.stats': 'Estatísticas',
  'links.detail.stats.uses': 'Usos',
  'links.detail.stats.max': 'Máximo',
  'links.detail.info': 'Informações',
  'links.detail.identifier': 'Identificador',
  'links.detail.createdAt': 'Criado em',
  'links.detail.expiresAt': 'Expira em',
  'links.detail.reason.closed': 'A conversa está encerrada: este link não permite mais entrar.',
  'links.detail.reason.expired': 'Este link expirou.',
  'links.detail.reason.revoked': 'Você desativou este link.',
  'links.detail.refused.title': 'Link não encontrado',
  'links.detail.refused.body': 'Este link não existe ou não é um dos seus.',
  'links.detail.loading': 'Carregando o link',
  'links.announce.copied': 'Link copiado',
  'links.announce.copyFailed': 'Não foi possível copiar o link',
  'links.announce.shareUnavailable': 'O compartilhamento não está disponível aqui',
  'links.announce.disabled': 'Link desativado',
  'links.announce.activated': 'Link ativado',
  'links.announce.toggleFailed': 'Não foi possível alterar este link',
  'links.announce.offline': 'Sem conexão: nada foi enviado.',
  'links.create.title': 'Novo link de compartilhamento',
  'links.create.section.conversation': 'Conversa',
  'links.create.choose': 'Escolher um grupo ou uma comunidade',
  'links.create.picker.title': 'Escolher uma conversa',
  'links.create.picker.empty': 'Nenhuma conversa pode receber um link por enquanto.',
  'links.create.section.identity': 'Identidade do link',
  'links.create.name': 'Nome do link',
  'links.create.name.placeholder': 'ex.: Compartilhamento no Twitter',
  'links.create.description': 'Descrição (opcional)',
  'links.create.description.placeholder': 'ex.: Entre no nosso grupo…',
  'links.create.section.access': 'Acesso de convidados',
  'links.create.section.access.subtitle': 'O que os visitantes devem fornecer para entrar',
  'links.create.access.account': 'Conta obrigatória',
  'links.create.access.account.caption': 'Só membros do Meeshy podem entrar',
  'links.create.access.nickname': 'Apelido obrigatório',
  'links.create.access.nickname.caption': 'O visitante deve escolher um apelido',
  'links.create.access.email': 'E-mail obrigatório',
  'links.create.access.email.caption': 'O visitante deve informar seu e-mail',
  'links.create.access.birthday': 'Data de nascimento obrigatória',
  'links.create.access.birthday.caption': 'Permite o controle de idade',
  'links.create.section.permissions': 'Permissões',
  'links.create.section.permissions.subtitle': 'O que convidados anônimos podem fazer',
  'links.create.permission.messages': 'Enviar mensagens',
  'links.create.permission.messages.caption': 'Os convidados podem escrever na conversa',
  'links.create.permission.images': 'Enviar imagens',
  'links.create.permission.images.caption': 'Os convidados podem compartilhar fotos',
  'links.create.permission.files': 'Enviar arquivos',
  'links.create.permission.files.caption': 'Os convidados podem enviar documentos',
  'links.create.permission.history': 'Ver o histórico',
  'links.create.permission.history.caption': 'Os convidados veem as mensagens anteriores',
  'links.create.section.limits': 'Limites',
  'links.create.section.limits.subtitle': 'Controle o público e a duração do link',
  'links.create.limit.uses': 'Limitar os usos',
  'links.create.limit.max.one': 'No máximo {count} uso',
  'links.create.limit.max.other': 'No máximo {count} usos',
  'links.create.limit.count': 'Número de usos',
  'links.create.limit.invalid': 'Escolha um número inteiro entre 1 e {max}.',
  'links.create.expiration': 'Expiração',
  'links.create.expiration.never': 'Nunca',
  'links.create.expiration.h24': '24 horas',
  'links.create.expiration.d7': '7 dias',
  'links.create.expiration.d30': '30 dias',
  'links.create.expiration.m3': '3 meses',
  'links.create.button': 'Criar o link de compartilhamento',
  'links.create.inprogress': 'Criando…',
  'links.create.error.conversation': 'Escolha primeiro uma conversa.',
  'links.create.error.offline': 'Sem conexão: o link não foi criado.',
  'links.create.error.refused': 'Você não pode criar um link para esta conversa.',
  'links.create.error.default': 'Não foi possível criar o link. Tente novamente.',

  /* L'ESPACE D'ADMINISTRATION (#6432) — les onze sections reprennent les
     libellés de la barre latérale du legacy (`AdminLayout.tsx`), pour qu'un
     administrateur retrouve ses repères d'une application à l'autre. */
  'admin.title': 'Administração',
  'admin.role': 'O seu papel: {role}',
  'admin.denied.title': 'Área reservada',
  'admin.denied.message': 'Esta área exige uma permissão de administração.',
  'admin.counters.title': 'Num relance',
  'admin.counters.unavailable': 'Contadores indisponíveis de momento.',
  'admin.counters.users': 'Contas',
  'admin.counters.activeUsers': 'Contas ativas',
  'admin.counters.messages': 'Mensagens',
  'admin.counters.communities': 'Comunidades',
  'admin.counters.reports': 'Denúncias',
  'admin.counters.newUsers': 'Novas (24 h)',
  'admin.sections.title': 'Secções',
  'admin.sections.legacy': 'interface anterior',
  'admin.nav.dashboard': 'Painel',
  'admin.nav.users': 'Contas',
  'admin.nav.moderation': 'Moderação',
  'admin.nav.audit': 'Registos de auditoria',
  'admin.nav.analytics': 'Estatísticas',
  'admin.nav.trackingLinks': 'Ligações de seguimento',
  'admin.nav.ranking': 'Classificação',
  'admin.nav.broadcasts': 'Difusões',
  'admin.nav.settings': 'Definições',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Supervisão',
  'admin.users.search': 'Procurar uma conta',
  'admin.users.count': '{count} conta(s)',
  'admin.users.empty': 'Nenhuma conta corresponde.',
  'admin.users.unavailable': 'Lista indisponível de momento.',
  'admin.users.inactive': 'desativada',
  'admin.users.previous': 'Anteriores',
  'admin.users.next': 'Seguintes',
  'admin.user.title': 'Membro',
  'admin.user.unavailable': 'Ficha indisponível de momento.',
  'admin.user.identity': 'Identidade',
  'admin.user.account': 'Conta',
  'admin.user.created': 'Aderiu em',
  'admin.user.lastActive': 'Última atividade',
  'admin.user.twoFactor': 'Duplo fator',
  'admin.user.enabled': 'ativado',
  'admin.user.deleted': 'eliminada',
  'admin.user.role': 'Função',
  'admin.edit.open': 'Editar',
  'admin.edit.title': 'Editar membro',
  'admin.edit.displayName': 'Nome visível',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Biografia',
  'admin.edit.active': 'Conta ativa',
  'admin.edit.save': 'Guardar',
  'admin.edit.reason': 'Motivo (opcional)',
  'admin.edit.warnRole': 'Alterar a função muda as suas permissões.',
  'admin.edit.warnDeactivate': 'Desativar encerra as sessões abertas.',
  'admin.edit.confirm': 'Confirmar',
  'admin.edit.saved': 'Alterações guardadas',
  'admin.edit.failed': 'Não foi possível guardar',
  'admin.password.title': 'Repor a palavra-passe',
  'admin.password.warn': 'Isto encerra todas as sessões abertas.',
  'admin.password.generated': 'Copie-a agora: não será mostrada novamente.',
  'admin.password.copy': 'Copiar',
  'admin.password.copied': 'Copiada',
  'admin.password.apply': 'Repor',
  'admin.password.done': 'Palavra-passe reposta',
  'admin.password.failed': 'Não foi possível repor',
  'admin.ban.open': 'Banir',
  'admin.ban.title': 'Banir este membro',
  'admin.ban.reason': 'Motivo (obrigatório)',
  'admin.ban.permanent': 'Banimento permanente',
  'admin.ban.until': 'Até',
  'admin.ban.apply': 'Banir',
  'admin.ban.lift': 'Levantar',
  'admin.ban.active': 'em vigor',
  'admin.ban.expired': 'expirado',
  'admin.ban.lifted': 'levantado',
  'admin.ban.none': 'Sem banimentos',
  'admin.ban.done': 'Banimento registado',
  'admin.ban.failed': 'Não foi possível banir',
  'admin.media.title': 'Média',
  'admin.media.empty': 'Sem média',
  'admin.media.protected': 'protegido',
  'admin.media.fromPost': 'publicação',
  'admin.media.fromMessage': 'mensagem',
  'admin.conv.title': 'Conversas',
  'admin.conv.empty': 'Sem conversas',
  'admin.conv.members': '{count} membros',
  'admin.nav.conversations': 'Conversas',
  'admin.convList.search': 'Procurar uma conversa',
  'admin.convList.count': '{count} conversa(s)',
  'admin.convList.empty': 'Nenhuma conversa corresponde.',
  'admin.convList.unavailable': 'Lista indisponível no momento.',
  'admin.convList.members': '{count} membros',
  'admin.convList.sovereign': 'Reservado ao nível de administração.',
  'admin.convDetail.title': 'Leitura de uma conversa',
  'admin.convDetail.reasonLabel': 'Motivo da leitura',
  'admin.convDetail.reasonHint': 'Dez caracteres mínimo, registado com o seu nome.',
  'admin.convDetail.read': 'Ler a conversa',
  'admin.convDetail.empty': 'Nenhuma mensagem',
  'admin.convDetail.protected': 'Protegido: existe, não se mostra',
  'admin.convDetail.attachmentProtected': 'anexo protegido',
  'admin.convDetail.edited': 'editado',
  'admin.convDetail.attachments': '{count} anexo(s)',

} satisfies InterfaceCatalog;

export default pt;
