import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const pt = {
  'admin.role': 'O seu papel: {role}',
  'admin.denied.title': 'Área reservada',
  'admin.denied.message': 'Esta área exige uma permissão de administração.',
  'admin.counters.title': 'Num relance',
  'admin.counters.unavailable': 'Contadores indisponíveis de momento.',
  'admin.counters.users': 'Contas',
  'admin.counters.activeUsers': 'Contas ativas',
  'admin.counters.messages': 'Mensagens',
  'admin.counters.communities': 'Comunidades',
  'admin.counters.reports': 'Denúncias',
  'admin.counters.newUsers': 'Novas (24 h)',
  'admin.sections.title': 'Secções',
  'admin.sections.legacy': 'interface anterior',
  'admin.nav.dashboard': 'Painel',
  'admin.nav.users': 'Contas',
  'admin.nav.moderation': 'Moderação',
  'admin.nav.audit': 'Registos de auditoria',
  'admin.nav.analytics': 'Estatísticas',
  'admin.nav.trackingLinks': 'Ligações de seguimento',
  'admin.nav.ranking': 'Classificação',
  'admin.nav.broadcasts': 'Difusões',
  'admin.nav.settings': 'Definições',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Supervisão',
  'admin.users.search': 'Procurar uma conta',
  'admin.users.count': '{count} conta(s)',
  'admin.users.empty': 'Nenhuma conta corresponde.',
  'admin.users.unavailable': 'Lista indisponível de momento.',
  'admin.users.inactive': 'desativada',
  'admin.users.previous': 'Anteriores',
  'admin.users.next': 'Seguintes',
  'admin.user.title': 'Membro',
  'admin.user.unavailable': 'Ficha indisponível de momento.',
  'admin.user.identity': 'Identidade',
  'admin.user.account': 'Conta',
  'admin.user.created': 'Aderiu em',
  'admin.user.lastActive': 'Última atividade',
  'admin.user.twoFactor': 'Duplo fator',
  'admin.user.enabled': 'ativado',
  'admin.user.deleted': 'eliminada',
  'admin.user.role': 'Função',
  'admin.edit.open': 'Editar',
  'admin.edit.title': 'Editar membro',
  'admin.edit.displayName': 'Nome visível',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Biografia',
  'admin.edit.active': 'Conta ativa',
  'admin.edit.save': 'Guardar',
  'admin.edit.reason': 'Motivo (opcional)',
  'admin.edit.warnRole': 'Alterar a função muda as suas permissões.',
  'admin.edit.warnDeactivate': 'Desativar encerra as sessões abertas.',
  'admin.edit.confirm': 'Confirmar',
  'admin.edit.saved': 'Alterações guardadas',
  'admin.edit.failed': 'Não foi possível guardar',
  'admin.password.title': 'Repor a palavra-passe',
  'admin.password.warn': 'Isto encerra todas as sessões abertas.',
  'admin.password.generated': 'Copie-a agora: não será mostrada novamente.',
  'admin.password.copy': 'Copiar',
  'admin.password.copied': 'Copiada',
  'admin.password.apply': 'Repor',
  'admin.password.done': 'Palavra-passe reposta',
  'admin.password.failed': 'Não foi possível repor',
  'admin.ban.open': 'Banir',
  'admin.ban.title': 'Banir este membro',
  'admin.ban.reason': 'Motivo (obrigatório)',
  'admin.ban.permanent': 'Banimento permanente',
  'admin.ban.until': 'Até',
  'admin.ban.apply': 'Banir',
  'admin.ban.lift': 'Levantar',
  'admin.ban.active': 'em vigor',
  'admin.ban.expired': 'expirado',
  'admin.ban.lifted': 'levantado',
  'admin.ban.none': 'Sem banimentos',
  'admin.ban.done': 'Banimento registado',
  'admin.ban.failed': 'Não foi possível banir',
  'admin.media.title': 'Média',
  'admin.media.empty': 'Sem média',
  'admin.media.protected': 'protegido',
  'admin.media.fromPost': 'publicação',
  'admin.media.fromMessage': 'mensagem',
  'admin.conv.title': 'Conversas',
  'admin.conv.empty': 'Sem conversas',
  'admin.conv.members': '{count} membros',
  'admin.nav.conversations': 'Conversas',
  'admin.convList.search': 'Procurar uma conversa',
  'admin.convList.count': '{count} conversa(s)',
  'admin.convList.empty': 'Nenhuma conversa corresponde.',
  'admin.convList.unavailable': 'Lista indisponível no momento.',
  'admin.convList.members': '{count} membros',
  'admin.convList.sovereign': 'Reservado ao nível de administração.',
  'admin.convDetail.title': 'Leitura de uma conversa',
  'admin.convDetail.reasonLabel': 'Motivo da leitura',
  'admin.convDetail.reasonHint': 'Dez caracteres mínimo, registado com o seu nome.',
  'admin.convDetail.read': 'Ler a conversa',
  'admin.convDetail.empty': 'Nenhuma mensagem',
  'admin.convDetail.protected': 'Protegido: existe, não se mostra',
  'admin.convDetail.attachmentProtected': 'anexo protegido',
  'admin.convDetail.edited': 'editado',
  'admin.convDetail.attachments': '{count} anexo(s)',
} satisfies AdminInterfaceCatalog;

export default pt;
