import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const it = {
  'admin.role': 'Il tuo ruolo: {role}',
  'admin.denied.title': 'Area riservata',
  'admin.denied.message': 'Quest\'area richiede un permesso di amministrazione.',
  'admin.counters.title': 'In sintesi',
  'admin.counters.unavailable': 'Contatori non disponibili al momento.',
  'admin.counters.users': 'Account',
  'admin.counters.activeUsers': 'Account attivi',
  'admin.counters.messages': 'Messaggi',
  'admin.counters.communities': 'Comunità',
  'admin.counters.reports': 'Segnalazioni',
  'admin.counters.newUsers': 'Nuovi (24 h)',
  'admin.sections.title': 'Sezioni',
  'admin.sections.legacy': 'interfaccia precedente',
  'admin.nav.dashboard': 'Cruscotto',
  'admin.nav.users': 'Account',
  'admin.nav.moderation': 'Moderazione',
  'admin.nav.audit': 'Registri di audit',
  'admin.nav.analytics': 'Statistiche',
  'admin.nav.trackingLinks': 'Link di tracciamento',
  'admin.nav.ranking': 'Classifica',
  'admin.nav.broadcasts': 'Trasmissioni',
  'admin.nav.settings': 'Impostazioni',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Monitoraggio',
  'admin.users.search': 'Cerca un account',
  'admin.users.count': '{count} account',
  'admin.users.empty': 'Nessun account corrisponde.',
  'admin.users.unavailable': 'Elenco non disponibile al momento.',
  'admin.users.inactive': 'disattivato',
  'admin.users.previous': 'Precedenti',
  'admin.users.next': 'Successivi',
  'admin.user.title': 'Membro',
  'admin.user.unavailable': 'Scheda non disponibile al momento.',
  'admin.user.identity': 'Identità',
  'admin.user.account': 'Account',
  'admin.user.created': 'Iscritto il',
  'admin.user.lastActive': 'Ultima attività',
  'admin.user.twoFactor': 'Due fattori',
  'admin.user.enabled': 'attivato',
  'admin.user.deleted': 'eliminato',
  'admin.user.role': 'Ruolo',
  'admin.edit.open': 'Modifica',
  'admin.edit.title': 'Modifica membro',
  'admin.edit.displayName': 'Nome visualizzato',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Account attivo',
  'admin.edit.save': 'Salva',
  'admin.edit.reason': 'Motivo (facoltativo)',
  'admin.edit.warnRole': 'Cambiare il ruolo modifica i permessi.',
  'admin.edit.warnDeactivate': 'Disattivare chiude le sessioni aperte.',
  'admin.edit.confirm': 'Conferma',
  'admin.edit.saved': 'Modifiche salvate',
  'admin.edit.failed': 'Salvataggio non riuscito',
  'admin.password.title': 'Reimposta la password',
  'admin.password.warn': 'Questo chiude tutte le sessioni aperte.',
  'admin.password.generated': 'Copiala ora: non verrà più mostrata.',
  'admin.password.copy': 'Copia',
  'admin.password.copied': 'Copiata',
  'admin.password.apply': 'Reimposta',
  'admin.password.done': 'Password reimpostata',
  'admin.password.failed': 'Reimpostazione non riuscita',
  'admin.ban.open': 'Blocca',
  'admin.ban.title': 'Blocca questo membro',
  'admin.ban.reason': 'Motivo (obbligatorio)',
  'admin.ban.permanent': 'Blocco permanente',
  'admin.ban.until': 'Fino al',
  'admin.ban.apply': 'Blocca',
  'admin.ban.lift': 'Revoca',
  'admin.ban.active': 'in vigore',
  'admin.ban.expired': 'scaduto',
  'admin.ban.lifted': 'revocato',
  'admin.ban.none': 'Nessun blocco',
  'admin.ban.done': 'Blocco registrato',
  'admin.ban.failed': 'Blocco non riuscito',
  'admin.media.title': 'Media',
  'admin.media.empty': 'Nessun media',
  'admin.media.protected': 'protetto',
  'admin.media.fromPost': 'post',
  'admin.media.fromMessage': 'messaggio',
  'admin.conv.title': 'Conversazioni',
  'admin.conv.empty': 'Nessuna conversazione',
  'admin.conv.members': '{count} membri',
} satisfies AdminInterfaceCatalog;

export default it;
