import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const en = {
  'announce.messageSent': 'Message sent',
  'announce.messageCopied': 'Message copied',
  'announce.messagesCopied': 'Messages copied',
  'announce.messageProtected': 'Protected message',
  'announce.selectionCap': 'Maximum {count} messages',
  'announce.nothingToCopy': 'Nothing to copy',

  'message.author.self': 'You',
  'message.excerpt.protected': 'protected content',
  'a11y.message.menu.subject': 'Actions for the message from {author}: {excerpt}',

  'typing.named': '{name} is typing',
  'typing.double': '{first} and {second} are typing',
  'typing.several': 'Several people are typing',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'My links',
  'root.menu.notifications': 'Notifications',
  'root.menu.calls': 'Calls',
  'root.menu.discover': 'Discover',
  'root.menu.communities': 'Communities',
  'root.menu.settings': 'Settings',
  'root.menu.profile': 'Profile',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Meeshy navigation',
  'a11y.floating.menu.unread.one': 'Menu, {count} unread notification',
  'a11y.floating.menu.unread.other': 'Menu, {count} unread notifications',
  'a11y.floating.rung.notifications.unread.one': 'Notifications, {count} unread',
  'a11y.floating.rung.notifications.unread.other': 'Notifications, {count} unread',

  'notifications.category.all': 'All',
  'notifications.category.unread': 'Unread',
  'notifications.category.messages': 'Messages',
  'notifications.category.reactions': 'Reactions',
  'notifications.category.mentions': 'Mentions',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contacts',
  'notifications.category.groups': 'Groups',
  'notifications.category.calls': 'Calls',
  'notifications.category.translations': 'Translations',
  'notifications.category.system': 'System',
  'notifications.categories': 'Notification categories',
  'notifications.markAllRead': 'Mark all read',
  'notifications.unreadCount.one': '{count} unread',
  'notifications.unreadCount.other': '{count} unread',
  'notifications.unread': 'Unread',
  'notifications.empty.all': 'No notifications',
  'notifications.empty.unread': 'No unread notifications',
  'notifications.empty.category': 'No notifications in “{category}”',
  'notifications.empty.subtitle': 'Your notifications will show up here',
  'notifications.loading': 'Loading notifications',
  'notifications.error.title': 'Couldn’t load notifications',
  'notifications.error.body': 'Try again in a moment.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Your notifications will show up once you’re back online.',
  'notifications.retry': 'Try again',
  'notifications.allLoaded': 'All notifications are loaded',
  'notifications.actions': 'Notification actions',
  'notifications.action.markRead': 'Mark as read',
  'notifications.action.delete': 'Delete',
  'notifications.failure': 'That didn’t go through. Try again.',

  'notFound.title': "This address doesn't exist.",

  'pending.back': 'Back to conversations',
  'pending.comingSoon': 'This screen is coming soon.',
  'pending.feed.promise': 'Posts from the people you follow.',
  'pending.links.promise': 'Links shared in your conversations will gather here.',
  'pending.notifications.promise': 'What is waiting for you — mentions, replies, invitations — will show up here.',
  'pending.calls.promise': 'Your call history, and a way to place a call.',
  'pending.discover.promise': 'People to meet, chosen by what you have in common.',
  'pending.communities.promise': 'The communities you belong to, and the ones that feel like you.',
  'pending.settings.promise': 'Your languages, your privacy, your notifications.',
  'pending.profile.promise': 'Your Meeshy identity — name, photo, languages, and what others see of it.',

  'profile.title': 'Profile',
  'profile.edit': 'Edit',
  'profile.cancel': 'Cancel',
  'profile.save': 'Save',
  'profile.saving': 'Saving…',
  'profile.saved': 'Profile saved',
  'profile.save.error': 'Error while saving',
  'profile.save.offline': 'Offline — the change was not sent.',
  'profile.save.invalid': 'Check the “{field}” field.',
  'profile.loading': 'Loading profile',
  'profile.error.title': "Couldn't load your profile",
  'profile.error.body': 'Try again in a moment.',
  'profile.retry': 'Try again',
  'profile.offline.title': 'Offline',
  'profile.offline.body': 'Your profile stays readable; editing comes back with the network.',
  'profile.avatar.edit': 'Edit profile photo',
  'profile.avatar.updated': 'Profile photo updated',
  'profile.avatar.error': "Couldn't update the profile photo",
  'profile.banner.edit': 'Edit banner',
  'profile.banner.updated': 'Banner updated',
  'profile.banner.error': "Couldn't update the banner",
  'profile.image.uploading': 'Uploading',
  'profile.image.cancel': 'Cancel upload',
  'profile.image.cancelled': 'Upload cancelled',
  'profile.image.unreadable': "This image can't be read.",
  'profile.section.identity': 'IDENTITY',
  'profile.section.contact': 'CONTACT',
  'profile.section.languages': 'LANGUAGES',
  'profile.section.stats': 'STATISTICS',
  'profile.section.requests': 'REQUESTS',
  'profile.section.member_since': 'MEMBER SINCE',
  'profile.first_name': 'First name',
  'profile.last_name': 'Last name',
  'profile.username': 'Username',
  'profile.display_name': 'Display name',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Tell us about yourself...',
  'profile.email': 'Email',
  'profile.phone': 'Phone',
  'profile.verified': 'Verified',
  'profile.not_verified': 'Not verified',
  'profile.language.primary': 'Primary language',
  'profile.language.primary.subtitle': 'Content will be translated into this language',
  'profile.language.regional': 'Regional language',
  'profile.language.custom': 'Custom language',
  'profile.language.none': 'None',
  'profile.language.choose': 'Choose',
  'profile.language.clear.regional': 'Remove regional language',
  'profile.language.clear.custom': 'Remove custom language',
  'profile.stats.messages': 'Messages',
  'profile.stats.translations': 'Translations',
  'profile.stats.languages': 'Languages',
  'profile.stats.days': 'Days',
  'profile.stats.loading': 'Loading statistics',
  'profile.progression.title': 'Progress',
  'profile.progression.subtitle': 'Badges, level and streak',
  'profile.friend_requests': 'Friend requests',
  'profile.friend_requests.count.one': '{count} pending request',
  'profile.friend_requests.count.other': '{count} pending requests',

  'settings.title': 'Settings',
  'settings.my_profile': 'My profile',
  'settings.section.account': 'Account',
  'settings.security.title': 'Security',
  'settings.delete_account': 'Delete account',
  'settings.privacy.title': 'Privacy',
  'settings.privacy.online_status': 'Online status',
  'settings.privacy.online_status.info':
    "The green dot on your avatar means you're active. Turned off, nobody sees it — but typing in a conversation still proves you're around.",
  'settings.privacy.last_seen': 'Last sign-in',
  'settings.privacy.read_receipts': 'Read receipts',
  'settings.privacy.read_receipts.info':
    "This works both ways: if you don't send read receipts, you won't see whether your own messages were read.",
  'settings.privacy.typing_indicator': 'Typing indicator',
  'settings.section.appearance': 'Appearance',
  'settings.theme': 'Theme',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.interface_language': 'Interface language',
  'settings.interface_language.automatic': 'Automatic',
  'settings.content_languages': 'Translation languages',
  'settings.section.notifications': 'Notifications',
  'settings.notifications.title': 'Notifications',
  'settings.notif.sounds': 'Sounds',
  'settings.notif.more_options': 'More options',
  'settings.section.data': 'Data',
  'settings.media': 'Media',
  'settings.messages': 'Messages',
  'settings.export_data': 'Export my data',
  'settings.section.tools': 'Tools',
  'settings.tools.progression': 'Progress',
  'settings.section.about': 'About',
  'settings.terms': 'Terms of Service',
  'settings.privacy_policy': 'Privacy Policy',
  'settings.version': 'Version',
  'settings.logout.title': 'Log out',
  'settings.logout.message': 'Are you sure you want to log out?',
  'settings.logout.inprogress': 'Logging out...',
  'settings.legacy': 'Classic version, new tab',
  'settings.legacy.unavailable': 'Unavailable in this environment',
  'settings.loading': 'Loading settings',
  'settings.error.title': 'Unable to load your settings',
  'settings.retry': 'Try again',
  'settings.offline.body': 'Offline — your settings stay readable; you can change them once the network is back.',
  'settings.save.error': 'The setting was not saved.',
  'settings.theme.sync_error': 'Theme applied on this device, not synced.',
  'common.cancel': 'Cancel',

  'media.video.play': 'Play video',
  'media.video.pause': 'Pause',
  'media.video.position': 'Playback position',
  'media.video.position.value': '{elapsed} of {total}',
  'media.video.mute': 'Mute',
  'media.video.unmute': 'Unmute',
  'media.video.more_options': 'More options',
  'media.video.speed': 'Speed',
  'media.video.pip.enter': 'Picture in Picture',
  'media.video.pip.exit': 'Exit Picture in Picture',

  'community.list.create.accessibilityLabel': 'Create a community',
  'community.list.search.placeholder': 'Search communities',
  'community.list.search.clear': 'Clear search',
  'community.list.search.empty': 'No community matches “{query}”.',
  'community.list.empty.title': 'No communities',
  'community.list.empty.subtitle': 'Join or create a community to talk together.',
  'community.list.loading': 'Loading communities',
  'community.error.title': 'Couldn’t load communities',
  'community.error.body': 'Check your connection, then try again.',
  'community.retry': 'Try again',
  'community.offline.title': 'Offline',
  'community.offline.body': 'Your communities stay readable; creating one needs a connection.',
  'community.privacy.private': 'Private',
  'community.privacy.public': 'Public',
  'community.members.one': '{count} member',
  'community.members.other': '{count} members',
  'community.conversations.one': '{count} conversation',
  'community.conversations.other': '{count} conversations',
  'community.detail.stats.members': 'Members',
  'community.detail.channels': 'Conversations',
  'community.detail.channels.empty': 'You’re not in any conversation of this community yet.',
  'community.detail.untitled': 'Untitled conversation',
  'community.detail.back': 'Back to communities',
  'community.detail.refused.title': 'Community not found',
  'community.detail.refused.body': 'It doesn’t exist, or it’s private and you’re not a member.',
  'community.detail.error.title': 'Couldn’t load this community',
  'community.detail.loading': 'Loading the community',
  'community.create.title': 'New community',
  'community.create.preview.placeholder': 'My community',
  'community.create.field.name': 'Name',
  'community.create.field.name.placeholder': 'Community name',
  'community.create.field.identifier': 'Identifier',
  'community.create.field.identifier.placeholder': 'my-group',
  'community.create.field.description': 'Description',
  'community.create.field.description.placeholder': 'What is this community about?',
  'community.create.privacy.title': 'Private community',
  'community.create.privacy.private.description': 'Only invited members can join',
  'community.create.privacy.public.description': 'Anyone can discover and join it',
  'community.create.button': 'Create community',
  'community.create.inprogress': 'Creating…',
  'community.create.error.name': 'Give it a name, 100 characters at most.',
  'community.create.error.identifier': 'Letters, digits, hyphens and underscores only, 50 at most.',
  'community.create.error.description': '500 characters at most.',
  'community.create.error.conflict': 'This identifier is already taken.',
  'community.create.error.offline': 'Offline — the community wasn’t sent.',
  'community.create.error.default': 'The community wasn’t created. Try again.',
  'calls.filters': 'Filter the call log',
  'calls.filter.all': 'All',
  'calls.filter.missed': 'Missed',
  'calls.direction.incoming': 'Received',
  'calls.direction.outgoing': 'Outgoing',
  'calls.direction.missed': 'Missed',
  'calls.a11y.incoming': 'incoming call',
  'calls.a11y.outgoing': 'outgoing call',
  'calls.a11y.missed': 'missed call',
  'calls.type.audio': 'voice call',
  'calls.type.video': 'video call',
  'calls.duration': 'duration {duration}',
  'calls.unknown': 'Unknown',
  'calls.empty.title': 'No recent calls',
  'calls.empty.subtitle': 'Your received, missed, cancelled and outgoing calls will appear here.',
  'calls.empty.missed.title': 'No missed calls',
  'calls.empty.missed.subtitle': 'Calls you didn’t answer will appear here.',
  'calls.error.title': 'The call log couldn’t be loaded',
  'calls.error.body': 'Check your connection, then try again.',
  'calls.offline.title': 'Offline',
  'calls.offline.body': 'You’re seeing the call log from the last load.',
  'calls.retry': 'Try again',
  'calls.loading': 'Loading the call log',
  'calls.allLoaded': 'All calls from the last three months are loaded',
} satisfies InterfaceCatalog;

export default en;
