import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const ar = {
  'announce.messageSent': 'تم إرسال الرسالة',
  'announce.messageCopied': 'تم نسخ الرسالة',
  'announce.messagesCopied': 'تم نسخ الرسائل',
  'announce.messageProtected': 'رسالة محمية',
  'announce.selectionCap': '{count} رسالة كحد أقصى',
  'announce.nothingToCopy': 'لا شيء للنسخ',

  'message.author.self': 'أنت',
  'message.excerpt.protected': 'محتوى محمي',
  'a11y.message.menu.subject': 'إجراءات رسالة {author}: {excerpt}',

  'typing.named': '{name} يكتب',
  'typing.double': '{first} و{second} يكتبان',
  'typing.several': 'عدة أشخاص يكتبون',

  'feed.header.reels': 'تشغيل الريلز',
  'reels.title': 'الريلز',
  'reels.back': 'رجوع',
  'reels.open': 'مشاهدة ريل {author}',
  'reels.item': 'ريل {author}، {index} من {count}',
  'reels.loading': 'جارٍ تحميل الريلز',
  'reels.empty': 'لا توجد ريلز حاليًا',
  'reels.empty.hint': 'ستظهر هنا ريلز جهات اتصالك.',
  'reels.error': 'تعذّر تحميل الريلز',
  'reels.error.hint': 'أعد المحاولة بعد لحظات.',
  'reels.retry': 'إعادة المحاولة',
  'reels.offline': 'غير متصل',
  'reels.offline.cold': 'سيتم تحميل الريلز عند عودة الاتصال.',
  'reels.action.like': 'إعجاب',
  'reels.action.bookmark': 'حفظ',
  'reels.action.share': 'مشاركة',
  'reels.sound.on': 'تشغيل الصوت',
  'reels.sound.off': 'كتم الصوت',
  'reels.play': 'تشغيل الريل',
  'reels.pause': 'إيقاف الريل مؤقتًا',
  'reels.media.error': 'تعذّر التشغيل — إعادة المحاولة',
  'reels.image': 'صورة {index} من {count}',

  'stories.title': 'القصص',
  'stories.loading': 'جاري تحميل القصص…',
  'stories.error': 'تعذّر تحميل القصص.',
  'stories.empty.title': 'لا توجد قصص حتى الآن',
  'stories.empty.subtitle': 'ستظهر هنا قصص جهات اتصالك لمدة أربع وعشرين ساعة.',
  'stories.create': 'إنشاء قصة',
  'stories.count.one': '{count} قصة',
  'stories.count.other': '{count} قصص',
  'stories.mine': 'قصتك',

  'feed.post.action.like': 'إعجاب',
  'feed.post.action.comment': 'تعليق',
  'feed.post.action.repost': 'إعادة النشر',
  'feed.post.action.bookmark': 'حفظ',
  'feed.post.action.share': 'مشاركة',
  'feed.post.media.video': 'فيديو',
  'feed.post.media.audio': 'صوت',
  'feed.post.media.previous': 'الوسائط السابقة',
  'feed.post.media.next': 'الوسائط التالية',
  'feed.post.media.mosaic': 'فسيفساء من {count} وسائط',
  'feed.post.see_more': 'عرض المزيد',
  'feed.post.see_less': 'عرض أقل',
  'feed.post.reel.chip': 'ريل',
  'feed.post.reel.of': 'ريل {author}',
  'feed.error.title': 'تعذّر تحميل التدفق',
  'feed.error.body': 'أعد المحاولة بعد لحظة.',
  'feed.offline.title': 'غير متصل',
  'feed.offline.body': 'سيظهر التدفق عند عودة الاتصال.',
  'feed.retry': 'إعادة المحاولة',
  'feed.empty.title': 'لا توجد منشورات بعد',
  'feed.empty.subtitle': 'ستظهر هنا منشورات جهات اتصالك.',
  'feed.loading': 'جارٍ تحميل التدفق',
  'feed.allLoaded': 'تم تحميل جميع المنشورات',
  'feed.like.error': 'تعذّر الإعجاب بالمنشور',
  'post.bookmark.error': 'تعذّر الحفظ',
  'feed.gesture.pending': 'لم يتم تأكيد الإجراء — غير متصل',
  'feed.share.error': 'تعذّرت مشاركة المنشور',
  'feed.share.copied': 'تم نسخ الرابط — لم يتبقَّ سوى لصقه.',
  'feed.share.text': 'منشور على Meeshy',

  'root.menu.feed': 'التدفق',
  'root.menu.links': 'روابطي',
  'root.menu.notifications': 'الإشعارات',
  'root.menu.calls': 'المكالمات',
  'root.menu.discover': 'اكتشاف',
  'root.menu.communities': 'المجتمعات',
  'root.menu.settings': 'الإعدادات',
  'root.menu.profile': 'الملف الشخصي',
  'root.menu.conversations': 'المحادثات',
  'a11y.floating.feed.hint': 'اضغط مطولًا لتشغيل الريلز',
  'a11y.floating.menu': 'القائمة',
  'a11y.floating.menu.ladder': 'التنقل في Meeshy',
  'a11y.floating.menu.unread.one': 'القائمة، {count} إشعار غير مقروء',
  'a11y.floating.menu.unread.other': 'القائمة، {count} إشعارات غير مقروءة',
  'a11y.floating.rung.notifications.unread.one': 'الإشعارات، {count} غير مقروء',
  'a11y.floating.rung.notifications.unread.other': 'الإشعارات، {count} غير مقروءة',

  'notifications.category.all': 'الكل',
  'notifications.category.unread': 'غير المقروءة',
  'notifications.category.messages': 'الرسائل',
  'notifications.category.reactions': 'التفاعلات',
  'notifications.category.mentions': 'الإشارات',
  'notifications.category.social': 'اجتماعي',
  'notifications.category.contacts': 'جهات الاتصال',
  'notifications.category.groups': 'المجموعات',
  'notifications.category.calls': 'المكالمات',
  'notifications.category.translations': 'الترجمات',
  'notifications.category.system': 'النظام',
  'notifications.categories': 'فئات الإشعارات',
  'notifications.markAllRead': 'قراءة الكل',
  'notifications.unreadCount.one': '{count} غير مقروء',
  'notifications.unreadCount.other': '{count} غير مقروءة',
  'notifications.unread': 'غير مقروء',
  'notifications.empty.all': 'لا توجد إشعارات',
  'notifications.empty.unread': 'لا توجد إشعارات غير مقروءة',
  'notifications.empty.category': 'لا توجد إشعارات في «{category}»',
  'notifications.empty.subtitle': 'ستظهر إشعاراتك هنا',
  'notifications.loading': 'جارٍ تحميل الإشعارات',
  'notifications.error.title': 'تعذّر تحميل الإشعارات',
  'notifications.error.body': 'أعد المحاولة بعد لحظة.',
  'notifications.offline.title': 'غير متصل',
  'notifications.offline.body': 'ستظهر إشعاراتك عند عودة الاتصال.',
  'notifications.retry': 'إعادة المحاولة',
  'notifications.allLoaded': 'تم تحميل جميع الإشعارات',
  'notifications.actions': 'إجراءات الإشعار',
  'notifications.action.markRead': 'وضع علامة كمقروء',
  'notifications.action.delete': 'حذف',
  'notifications.failure': 'لم يكتمل الإجراء. أعد المحاولة.',

  'notFound.title': 'هذا العنوان غير موجود.',

  'pending.back': 'العودة إلى المحادثات',

  'linkPage.home': 'العودة إلى Meeshy',
  'linkPage.retry': 'إعادة المحاولة',
  'linkPage.settings': 'فتح الإعدادات',
  'linkPage.signIn': 'تسجيل الدخول',
  'linkPage.offline.title': 'غير متصل',
  'linkPage.offline.body': 'أعد الاتصال بالإنترنت، ثم حاول مرة أخرى.',
  'linkPage.unavailable.title': 'Meeshy لا يستجيب',
  'linkPage.unavailable.body': 'الخدمة غير متاحة مؤقتًا. حاول مرة أخرى بعد لحظات.',
  'linkPage.rateLimited': 'محاولات كثيرة جدًا. انتظر قليلًا قبل المحاولة مرة أخرى.',
  'linkPage.signedOut.title': 'سجّل الدخول للمتابعة',
  'linkPage.signedOut.body': 'يؤثر هذا الرابط في حسابك. سجّل الدخول، ثم افتحه مرة أخرى من البريد الإلكتروني.',
  'linkPage.expired': 'انتهت صلاحية هذا الرابط. أعد تقديم الطلب من الإعدادات.',
  'trackingLink.opening': 'جارٍ فتح الرابط…',
  'trackingLink.dead.title': 'هذا الرابط لم يعد متاحًا',
  'trackingLink.dead.body': 'انتهت صلاحيته أو تم تعطيله أو لم يكن موجودًا قط.',
  'accountDeletion.incomplete.title': 'رابط غير مكتمل',
  'accountDeletion.incomplete.body': 'لا يحمل هذا الرابط المعلومات اللازمة. سجّل الدخول لطلب حذف حسابك.',
  'accountDeletion.confirm.title': 'تأكيد حذف حسابك',
  'accountDeletion.confirm.body': 'سيتم تعطيل حسابك بعد انتهاء فترة سماح مدتها 30 يومًا. وحتى ذلك الحين، يتيح لك رابط «إلغاء» في البريد الإلكتروني التراجع.',
  'accountDeletion.confirm.action': 'تأكيد الحذف',
  'accountDeletion.cancel.title': 'إلغاء حذف حسابك',
  'accountDeletion.cancel.body': 'يبقى حسابك نشطًا ويُلغى طلب الحذف. لن تفقد شيئًا.',
  'accountDeletion.cancel.action': 'إلغاء الحذف',
  'accountDeletion.purge.title': 'حذف حسابك الآن',
  'accountDeletion.purge.body': 'سيتم تعطيل حسابك فورًا وإغلاق جميع جلساتك. لا يمكن التراجع عن هذا الإجراء.',
  'accountDeletion.purge.action': 'حذف الآن',
  'accountDeletion.dismiss': 'عدم فعل أي شيء',
  'accountDeletion.working': 'لحظة…',
  'accountDeletion.done.title': 'تم',
  'accountDeletion.done.confirmed': 'تم تأكيد طلبك: سيتم تعطيل حسابك في {date}. يمكنك الإلغاء حتى ذلك الحين.',
  'accountDeletion.done.cancelled': 'يبقى حسابك نشطًا: تم إلغاء طلب الحذف.',
  'accountDeletion.done.completed': 'تم تعطيل حسابك وإغلاق جميع جلساتك.',
  'accountDeletion.done.purged': 'تم مسح بياناتك.',
  'accountDeletion.closed.title': 'هذا الرابط لم يعد صالحًا',
  'accountDeletion.invalid': 'هذا الرابط غير صالح أو سبق استخدامه.',
  'accountDeletion.request.title': 'حذف حسابك',
  'accountDeletion.request.body':
    'ستُحذف محادثاتك ورسائلك ووسائطك وجهات اتصالك وتفضيلاتك. ستطلب منك رسالة بريد إلكتروني التأكيد، ثم تتيح لك فترة سماح مدتها 30 يومًا التراجع.',
  'accountDeletion.request.phrase': 'اكتب {phrase} للتأكيد',
  'accountDeletion.request.password': 'كلمة المرور الحالية',
  'accountDeletion.request.action': 'طلب الحذف',
  'accountDeletion.request.sent.title': 'أرسلنا إليك رسالة تأكيد بالبريد الإلكتروني',
  'accountDeletion.request.sent.body': 'افتحها لتأكيد حذف حسابك.',
  'accountDeletion.request.wrongPassword': 'كلمة المرور غير صحيحة.',
  'accountDeletion.request.alreadyPending': 'يوجد طلب قيد التنفيذ بالفعل. افتح رسالة البريد الإلكتروني التي تلقيتها لتأكيده أو إلغائه.',
  'accountDeletion.request.noEmail': 'أضف عنوان بريد إلكتروني وتحقّق منه قبل طلب الحذف.',
  'emailChange.verifying': 'جارٍ تأكيد عنوانك الجديد…',
  'emailChange.done.title': 'تم تغيير عنوان البريد الإلكتروني',
  'emailChange.done.body': 'أصبحت تسجّل الدخول الآن باستخدام {email}.',
  'emailChange.done.generic': 'تم تأكيد عنوان بريدك الإلكتروني الجديد.',
  'emailChange.failed.title': 'لم يتم تغيير العنوان',
  'emailChange.missing': 'لا يحمل هذا الرابط رمز تأكيد. افتح الرابط الموجود في أحدث رسالة بريد إلكتروني.',
  'emailChange.invalid': 'لا يطابق هذا الرابط أي تغيير معلّق في هذا الحساب، أو سبق استخدامه.',
  'emailChange.taken': 'هذا العنوان يستخدمه الآن حساب آخر.',
  'emailNotifications.title': 'رسائل Meeshy الإلكترونية',
  'emailNotifications.loading': 'جارٍ قراءة تفضيلك…',
  'emailNotifications.on': 'تتلقى إعلانات Meeshy وملخصاته وإشعاراته عبر البريد الإلكتروني.',
  'emailNotifications.off': 'لم تعد تتلقى إعلانات Meeshy أو ملخصاته أو إشعاراته عبر البريد الإلكتروني.',
  'emailNotifications.security': 'تستمر رسائل الأمان الخاصة بحسابك في الوصول.',
  'emailNotifications.unsubscribe': 'إيقاف تلقي هذه الرسائل',
  'emailNotifications.resubscribe': 'تلقي هذه الرسائل مجددًا',
  'emailNotifications.failed': 'لم يتم تطبيق التغيير. حاول مرة أخرى.',

  'dataExport.title': 'تصدير بياناتي',
  'dataExport.info.body': 'وفقًا للائحة العامة لحماية البيانات (RGPD)، احصل على ملف يضم ملفك الشخصي ورسائلك وجهات اتصالك ومنشوراتك.',
  'dataExport.action.start': 'تصدير بياناتي',
  'dataExport.action.exporting': 'التصدير قيد التنفيذ…',
  'dataExport.action.again': 'تصدير مرة أخرى',
  'dataExport.done.title': 'اكتمل التصدير',
  'dataExport.done.body': 'تم تنزيل الملف على هذا الجهاز.',

  'profile.title': 'الملف الشخصي',
  'profile.edit': 'تعديل',
  'profile.cancel': 'إلغاء',
  'profile.save': 'حفظ',
  'profile.saving': 'جارٍ الحفظ…',
  'profile.saved': 'تم حفظ الملف الشخصي',
  'profile.save.error': 'خطأ أثناء الحفظ',
  'profile.save.offline': 'غير متصل — لم يُرسَل التعديل.',
  'profile.save.invalid': 'تحقّق من الحقل «{field}».',
  'profile.loading': 'جارٍ تحميل الملف الشخصي',
  'profile.error.title': 'تعذّر تحميل ملفك الشخصي',
  'profile.error.body': 'أعد المحاولة بعد قليل.',
  'profile.retry': 'إعادة المحاولة',
  'profile.offline.title': 'غير متصل',
  'profile.offline.body': 'يبقى ملفك الشخصي مقروءًا، ويعود التعديل مع عودة الشبكة.',
  'profile.avatar.edit': 'تعديل صورة الملف الشخصي',
  'profile.avatar.updated': 'تم تحديث صورة الملف الشخصي',
  'profile.avatar.error': 'تعذّر تحديث صورة الملف الشخصي',
  'profile.banner.edit': 'تعديل صورة الغلاف',
  'profile.banner.updated': 'تم تحديث صورة الغلاف',
  'profile.banner.error': 'تعذّر تحديث صورة الغلاف',
  'profile.image.uploading': 'جارٍ الإرسال',
  'profile.image.cancel': 'إلغاء الإرسال',
  'profile.image.cancelled': 'أُلغي الإرسال',
  'profile.image.unreadable': 'تعذّرت قراءة هذه الصورة.',
  'profile.section.identity': 'الهوية',
  'profile.section.contact': 'الاتصال',
  'profile.section.languages': 'اللغات',
  'profile.section.stats': 'الإحصائيات',
  'profile.section.requests': 'الطلبات',
  'profile.section.member_since': 'عضو منذ',
  'profile.first_name': 'الاسم الأول',
  'profile.last_name': 'اسم العائلة',
  'profile.username': 'اسم المستخدم',
  'profile.display_name': 'الاسم المعروض',
  'profile.bio': 'نبذة',
  'profile.bio.placeholder': 'عرّفنا بنفسك...',
  'profile.email': 'البريد الإلكتروني',
  'profile.phone': 'الهاتف',
  'profile.verified': 'موثّق',
  'profile.not_verified': 'غير موثّق',
  'profile.language.primary': 'اللغة الأساسية',
  'profile.language.primary.subtitle': 'ستُترجَم المحتويات إلى هذه اللغة',
  'profile.language.regional': 'اللغة الإقليمية',
  'profile.language.custom': 'لغة مخصّصة',
  'profile.language.none': 'لا شيء',
  'profile.language.choose': 'اختيار',
  'profile.language.clear.regional': 'إزالة اللغة الإقليمية',
  'profile.language.clear.custom': 'إزالة اللغة المخصّصة',

  'languageSheet.title.read': 'لغة القراءة',
  'languageSheet.title.write': 'لغة الكتابة',
  'languageSheet.search': 'البحث عن لغة',
  'languageSheet.empty': 'لا توجد لغة تطابق «{search}».',

  'profile.stats.messages': 'الرسائل',
  'profile.stats.translations': 'الترجمات',
  'profile.stats.languages': 'اللغات',
  'profile.stats.days': 'الأيام',
  'profile.stats.loading': 'جارٍ تحميل الإحصائيات',
  'profile.progression.title': 'التقدّم',
  'profile.progression.subtitle': 'الشارات والمستوى والسلسلة',
  'profile.friend_requests': 'طلبات الصداقة',
  'profile.friend_requests.count.one': '{count} طلب معلّق',
  'profile.friend_requests.count.other': '{count} طلبات معلّقة',

  'settings.title': 'الإعدادات',
  'settings.my_profile': 'ملفي الشخصي',
  'settings.section.account': 'الحساب',
  'settings.security.title': 'الأمان',
  'settings.delete_account': 'حذف الحساب',
  'settings.privacy.title': 'الخصوصية',
  'settings.privacy.online_status': 'حالة الاتصال',
  'settings.privacy.online_status.info':
    'النقطة الخضراء على صورتك تعني أنك نشط. عند إيقافها لا يراها أحد، لكن الكتابة في محادثة تظل دليلاً على نشاطك.',
  'settings.privacy.last_seen': 'آخر تسجيل دخول',
  'settings.privacy.read_receipts': 'إيصالات القراءة',
  'settings.privacy.read_receipts.info': 'الأمر متبادل: إن لم تُرسل إشعارات القراءة، فلن ترى أيضًا ما إذا قُرئت رسائلك.',
  'settings.privacy.typing_indicator': 'مؤشر الكتابة',
  'settings.section.appearance': 'المظهر',
  'settings.theme': 'السمة',
  'settings.theme.auto': 'تلقائي',
  'settings.theme.light': 'فاتح',
  'settings.theme.dark': 'داكن',
  'settings.interface_language': 'لغة الواجهة',
  'settings.interface_language.automatic': 'تلقائي',
  'settings.content_languages': 'لغات الترجمة',
  'settings.section.notifications': 'الإشعارات',
  'settings.notifications.title': 'الإشعارات',
  'settings.notif.sounds': 'الأصوات',
  'settings.notif.more_options': 'المزيد من الخيارات',
  'settings.section.data': 'البيانات',
  'settings.media': 'الوسائط',
  'settings.messages': 'الرسائل',
  'settings.export_data': 'تصدير بياناتي',
  'settings.section.tools': 'الأدوات',
  'settings.tools.progression': 'التقدّم',
  'settings.section.about': 'حول',
  'settings.terms': 'شروط الاستخدام',
  'settings.privacy_policy': 'سياسة الخصوصية',
  'settings.version': 'الإصدار',
  'settings.logout.title': 'تسجيل الخروج',
  'settings.logout.message': 'هل تريد فعلاً تسجيل الخروج؟',
  'settings.logout.inprogress': 'جارٍ تسجيل الخروج...',
  'settings.loading': 'جارٍ تحميل الإعدادات',
  'settings.error.title': 'تعذّر تحميل إعداداتك',
  'settings.retry': 'إعادة المحاولة',
  'settings.offline.body': 'غير متصل — تبقى إعداداتك مقروءة، ويمكنك تعديلها عند عودة الشبكة.',
  'settings.save.error': 'لم يُحفظ الإعداد.',
  'settings.theme.sync_error': 'طُبّق المظهر على هذا الجهاز دون مزامنة.',
  'common.cancel': 'إلغاء',

  'media.video.play': 'تشغيل الفيديو',
  'media.video.pause': 'إيقاف مؤقت',
  'media.video.position': 'موضع التشغيل',
  'media.audio.position': 'موضع التشغيل',
  'media.audio.speed': 'سرعة التشغيل',
  'media.video.position.value': '{elapsed} من {total}',
  'media.video.mute': 'كتم الصوت',
  'media.video.unmute': 'إلغاء كتم الصوت',
  'media.video.more_options': 'مزيد من الخيارات',
  'media.video.speed': 'السرعة',
  'media.video.pip.enter': 'صورة داخل صورة',
  'media.video.pip.exit': 'الخروج من صورة داخل صورة',

  'community.list.create.accessibilityLabel': 'إنشاء مجتمع',
  'community.list.search.placeholder': 'ابحث عن مجتمع',
  'community.list.search.clear': 'مسح البحث',
  'community.list.search.empty': 'لا يوجد مجتمع يطابق «{query}».',
  'community.list.empty.title': 'لا توجد مجتمعات',
  'community.list.empty.subtitle': 'انضم إلى مجتمع أو أنشئ واحدًا للتحدث معًا.',
  'community.list.loading': 'جارٍ تحميل المجتمعات',
  'community.error.title': 'تعذّر تحميل المجتمعات',
  'community.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'community.retry': 'إعادة المحاولة',
  'community.offline.title': 'غير متصل',
  'community.offline.body': 'تبقى مجتمعاتك قابلة للقراءة؛ يتطلب إنشاء مجتمع اتصالًا.',
  'community.privacy.private': 'خاص',
  'community.privacy.public': 'عام',
  'community.members.one': '{count} عضو',
  'community.members.other': '{count} أعضاء',
  'community.conversations.one': '{count} محادثة',
  'community.conversations.other': '{count} محادثات',
  'community.detail.stats.members': 'الأعضاء',
  'community.detail.channels': 'المحادثات',
  'community.detail.channels.empty': 'لم تنضم بعد إلى أي محادثة في هذا المجتمع.',
  'community.detail.untitled': 'محادثة بلا عنوان',
  'community.detail.back': 'العودة إلى المجتمعات',
  'community.detail.refused.title': 'المجتمع غير موجود',
  'community.detail.refused.body': 'إنه غير موجود، أو خاص ولست عضوًا فيه.',
  'community.detail.error.title': 'تعذّر تحميل هذا المجتمع',
  'community.detail.loading': 'جارٍ تحميل المجتمع',
  'community.create.title': 'مجتمع جديد',
  'community.create.preview.placeholder': 'مجتمعي',
  'community.create.field.name': 'الاسم',
  'community.create.field.name.placeholder': 'اسم المجتمع',
  'community.create.field.identifier': 'المعرّف',
  'community.create.field.identifier.placeholder': 'my-group',
  'community.create.field.description': 'الوصف',
  'community.create.field.description.placeholder': 'عمّ يدور هذا المجتمع؟',
  'community.create.privacy.title': 'مجتمع خاص',
  'community.create.privacy.private.description': 'يمكن للأعضاء المدعوين فقط الانضمام',
  'community.create.privacy.public.description': 'يمكن للجميع اكتشافه والانضمام إليه',
  'community.create.button': 'إنشاء المجتمع',
  'community.create.inprogress': 'جارٍ الإنشاء…',
  'community.create.error.name': 'أعطه اسمًا لا يتجاوز 100 حرف.',
  'community.create.error.identifier': 'أحرف وأرقام وشرطات وشرطات سفلية فقط، 50 على الأكثر.',
  'community.create.error.description': '500 حرف على الأكثر.',
  'community.create.error.conflict': 'هذا المعرّف مستخدم بالفعل.',
  'community.create.error.offline': 'غير متصل — لم يُرسَل المجتمع.',
  'community.create.error.default': 'لم يُنشأ المجتمع. أعد المحاولة.',
  'calls.filters': 'تصفية سجل المكالمات',
  'calls.filter.all': 'الكل',
  'calls.filter.missed': 'الفائتة',
  'calls.direction.incoming': 'واردة',
  'calls.direction.outgoing': 'صادرة',
  'calls.direction.missed': 'فائتة',
  'calls.a11y.incoming': 'مكالمة واردة',
  'calls.a11y.outgoing': 'مكالمة صادرة',
  'calls.a11y.missed': 'مكالمة فائتة',
  'calls.type.audio': 'مكالمة صوتية',
  'calls.type.video': 'مكالمة فيديو',
  'calls.duration': 'المدة {duration}',
  'calls.unknown': 'غير معروف',
  'calls.empty.title': 'لا مكالمات حديثة',
  'calls.empty.subtitle': 'ستظهر هنا مكالماتك الواردة والفائتة والملغاة والصادرة.',
  'calls.empty.missed.title': 'لا مكالمات فائتة',
  'calls.empty.missed.subtitle': 'ستظهر هنا المكالمات التي لم تُجب عليها.',
  'calls.error.title': 'تعذّر تحميل سجل المكالمات',
  'calls.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'calls.offline.title': 'غير متصل',
  'calls.offline.body': 'تعرض سجل آخر تحميل.',
  'calls.offline.cold.body': 'سيُحمَّل السجل فور عودة الاتصال.',
  'calls.retry': 'أعد المحاولة',
  'calls.loading': 'جارٍ تحميل سجل المكالمات',
  'calls.allLoaded': 'تم تحميل كل مكالمات الأشهر الثلاثة الأخيرة',

  'discover.tabs': 'أقسام الاكتشاف',
  'discover.tab.discover': 'اكتشاف',
  'discover.tab.requests': 'الطلبات',
  'discover.tab.blocked': 'المحظورون',
  'discover.tab.requests.count.one': 'الطلبات، {count} طلب وارد',
  'discover.tab.requests.count.other': 'الطلبات، {count} طلبات واردة',
  'discover.invite.title': 'دعوة عبر البريد الإلكتروني',
  'discover.invite.placeholder': 'عنوان البريد الإلكتروني',
  'discover.invite.send': 'إرسال',
  'discover.invite.sending': 'جارٍ الإرسال…',
  'discover.invite.sendLabel': 'إرسال الدعوة عبر البريد الإلكتروني',
  'discover.invite.sent': 'أُرسلت الدعوة إلى {email}',
  'discover.invite.invalid': 'عنوان البريد الإلكتروني هذا غير صالح.',
  'discover.invite.conflict': 'هذا الشخص موجود على Meeshy بالفعل: ابحث عنه أدناه.',
  'discover.invite.error': 'تعذّر إرسال الدعوة. أعد المحاولة.',
  'discover.invite.offline': 'غير متصل: اتصل لإرسال الدعوة.',
  'discover.search.label': 'ابحث عن مستخدم على Meeshy',
  'discover.search.clear': 'مسح البحث',
  'discover.search.searching': 'جارٍ البحث',
  'discover.search.empty': 'لم يُعثر على أي مستخدم لـ «{query}»',
  'discover.search.error': 'تعذّر البحث. تحقّق من اتصالك.',
  'discover.connection.add': 'إضافة',
  'discover.connection.addLabel': 'إضافة {name}',
  'discover.connection.pending': 'قيد الانتظار',
  'discover.connection.cancelLabel': 'إلغاء الطلب المرسل إلى {name}',
  'discover.connection.contact': 'جهة اتصال',
  'discover.connection.blocked': 'محظور',
  'discover.connection.acceptLabel': 'قبول طلب {name}',
  'discover.connection.rejectLabel': 'رفض طلب {name}',
  'discover.requests.filters': 'تصفية الطلبات',
  'discover.requests.received': 'الواردة',
  'discover.requests.sent': 'المرسلة',
  'discover.requests.intent': 'يرغب في التواصل معك',
  'discover.requests.cancel': 'إلغاء',
  'discover.requests.empty.received.title': 'لا توجد طلبات واردة',
  'discover.requests.empty.received.subtitle': 'ستظهر هنا طلبات التواصل التي تتلقاها.',
  'discover.requests.empty.sent.title': 'لا توجد طلبات مرسلة',
  'discover.requests.empty.sent.subtitle': 'ستظهر هنا الطلبات التي ترسلها.',
  'discover.blocked.unblock': 'إلغاء الحظر',
  'discover.blocked.unblockLabel': 'إلغاء حظر {name}',
  'discover.blocked.confirm.title': 'إلغاء الحظر؟',
  'discover.blocked.confirm.body': 'إلغاء حظر {name}؟',
  'discover.blocked.confirm.cancel': 'إلغاء',
  'discover.blocked.empty.title': 'لا يوجد مستخدمون محظورون',
  'discover.blocked.empty.subtitle': 'سيظهر هنا الأشخاص الذين تحظرهم.',
  'discover.unknown': 'مجهول',
  'discover.loading': 'جارٍ التحميل',
  'discover.allLoaded': 'تم تحميل القائمة كاملة',
  'discover.error.title': 'تعذّر تحميل هذه القائمة',
  'discover.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'discover.offline.title': 'غير متصل',
  'discover.offline.body': 'تعرض قائمة آخر تحميل.',
  'discover.offline.cold.body': 'ستُحمَّل القائمة فور عودة الاتصال.',
  'discover.retry': 'إعادة المحاولة',
  'discover.announce.accepted': 'تم قبول التواصل',
  'discover.announce.rejected': 'تم رفض الطلب',
  'discover.announce.cancelled': 'تم إلغاء الطلب',
  'discover.announce.sent': 'تم إرسال الطلب',
  'discover.announce.unblocked': 'تم إلغاء حظر المستخدم',
  'discover.announce.acceptFailed': 'تعذّر قبول هذا الطلب',
  'discover.announce.rejectFailed': 'تعذّر رفض هذا الطلب',
  'discover.announce.cancelFailed': 'تعذّر إلغاء هذا الطلب',
  'discover.announce.sendFailed': 'تعذّر إرسال الطلب',
  'discover.announce.unblockFailed': 'تعذّر إلغاء الحظر',
  'discover.announce.offline': 'غير متصل: لم يُرسَل شيء.',

  'a11y.floating.rung.discover.requests.one': 'اكتشاف، {count} طلب وارد',
  'a11y.floating.rung.discover.requests.other': 'اكتشاف، {count} طلبات واردة',

  'links.hub.banner.title': 'إدارة روابطك',
  'links.hub.banner.subtitle': 'ادعُ من تشاء إلى محادثاتك',
  'links.hub.share.title': 'روابط المشاركة',
  'links.hub.share.description': 'ادعُ جهات اتصالك للانضمام إلى محادثاتك',
  'links.hub.share.create': 'إنشاء رابط مشاركة',
  'links.share.back': 'العودة إلى روابطي',
  'links.share.stats.total': 'الروابط',
  'links.share.stats.active': 'النشطة',
  'links.share.stats.joined': 'المنضمّون',
  'links.share.joined.one': 'انضمّ {count}',
  'links.share.joined.other': 'انضمّ {count}',
  'links.share.copy': 'نسخ الرابط',
  'links.share.empty.title': 'لا توجد روابط مشاركة',
  'links.share.empty.subtitle': 'أنشئ رابطًا لدعوة أشخاص إلى محادثة',
  'links.share.loading': 'جارٍ تحميل الروابط',
  'links.share.allLoaded': 'تم تحميل كل روابطك',
  'links.status.active': 'نشط',
  'links.status.inactive': 'غير نشط',
  'links.unlimited': 'غير محدود',
  'links.error.title': 'تعذّر تحميل روابطك',
  'links.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'links.retry': 'إعادة المحاولة',
  'links.offline.title': 'غير متصل',
  'links.offline.body': 'تبقى روابطك قابلة للقراءة؛ يتطلب تعديلها اتصالًا.',
  'links.detail.back': 'العودة إلى روابط المشاركة',
  'links.detail.copy': 'نسخ',
  'links.detail.copied': 'تم النسخ',
  'links.detail.share': 'مشاركة',
  'links.detail.disable': 'تعطيل',
  'links.detail.activate': 'تفعيل',
  'links.detail.stats': 'الإحصاءات',
  'links.detail.stats.uses': 'مرات الاستخدام',
  'links.detail.stats.max': 'الحد الأقصى',
  'links.detail.info': 'المعلومات',
  'links.detail.identifier': 'المعرّف',
  'links.detail.createdAt': 'تاريخ الإنشاء',
  'links.detail.expiresAt': 'تاريخ الانتهاء',
  'links.detail.reason.closed': 'المحادثة مغلقة: لم يعد هذا الرابط يسمح بالدخول.',
  'links.detail.reason.expired': 'انتهت صلاحية هذا الرابط.',
  'links.detail.reason.revoked': 'لقد عطّلت هذا الرابط.',
  'links.detail.refused.title': 'الرابط غير موجود',
  'links.detail.refused.body': 'هذا الرابط غير موجود أو ليس من روابطك.',
  'links.detail.loading': 'جارٍ تحميل الرابط',
  'links.announce.copied': 'تم نسخ الرابط',
  'links.announce.copyFailed': 'تعذّر نسخ الرابط',
  'links.announce.shareUnavailable': 'المشاركة غير متاحة هنا',
  'links.announce.disabled': 'تم تعطيل الرابط',
  'links.announce.activated': 'تم تفعيل الرابط',
  'links.announce.toggleFailed': 'تعذّر تعديل هذا الرابط',
  'links.announce.offline': 'غير متصل: لم يُرسَل شيء.',
  'links.create.title': 'رابط مشاركة جديد',
  'links.create.section.conversation': 'المحادثة',
  'links.create.choose': 'اختر مجموعة أو مجتمعًا',
  'links.create.picker.title': 'اختر محادثة',
  'links.create.picker.empty': 'لا توجد محادثة يمكنها استقبال رابط حاليًا.',
  'links.create.section.identity': 'هوية الرابط',
  'links.create.name': 'اسم الرابط',
  'links.create.name.placeholder': 'مثال: مشاركة على تويتر',
  'links.create.description': 'الوصف (اختياري)',
  'links.create.description.placeholder': 'مثال: انضمّ إلى مجموعتنا…',
  'links.create.section.access': 'وصول الضيوف',
  'links.create.section.access.subtitle': 'ما يجب أن يقدّمه الزوار للانضمام',
  'links.create.access.account': 'الحساب مطلوب',
  'links.create.access.account.caption': 'لا ينضمّ إلا أعضاء Meeshy',
  'links.create.access.nickname': 'الاسم المستعار مطلوب',
  'links.create.access.nickname.caption': 'على الزائر اختيار اسم مستعار',
  'links.create.access.email': 'البريد الإلكتروني مطلوب',
  'links.create.access.email.caption': 'على الزائر تقديم بريده الإلكتروني',
  'links.create.access.birthday': 'تاريخ الميلاد مطلوب',
  'links.create.access.birthday.caption': 'يتيح التحقّق من العمر',
  'links.create.section.permissions': 'الأذونات',
  'links.create.section.permissions.subtitle': 'ما يمكن للضيوف المجهولين فعله',
  'links.create.permission.messages': 'إرسال الرسائل',
  'links.create.permission.messages.caption': 'يمكن للضيوف الكتابة في المحادثة',
  'links.create.permission.images': 'إرسال الصور',
  'links.create.permission.images.caption': 'يمكن للضيوف مشاركة الصور',
  'links.create.permission.files': 'إرسال الملفات',
  'links.create.permission.files.caption': 'يمكن للضيوف إرسال المستندات',
  'links.create.permission.history': 'عرض السجل',
  'links.create.permission.history.caption': 'يرى الضيوف الرسائل السابقة',
  'links.create.section.limits': 'الحدود',
  'links.create.section.limits.subtitle': 'تحكّم في جمهور الرابط ومدة صلاحيته',
  'links.create.limit.uses': 'تحديد عدد الاستخدامات',
  'links.create.limit.max.one': '{count} استخدام كحد أقصى',
  'links.create.limit.max.other': '{count} استخدامات كحد أقصى',
  'links.create.limit.count': 'عدد الاستخدامات',
  'links.create.limit.invalid': 'اختر عددًا صحيحًا بين 1 و{max}.',
  'links.create.expiration': 'انتهاء الصلاحية',
  'links.create.expiration.never': 'أبدًا',
  'links.create.expiration.h24': '24 ساعة',
  'links.create.expiration.d7': '7 أيام',
  'links.create.expiration.d30': '30 يومًا',
  'links.create.expiration.m3': '3 أشهر',
  'links.create.button': 'إنشاء رابط المشاركة',
  'links.create.inprogress': 'جارٍ الإنشاء…',
  'links.create.error.conversation': 'اختر محادثة أولًا.',
  'links.create.error.offline': 'غير متصل: لم يُنشأ الرابط.',
  'links.create.error.refused': 'لا يمكنك إنشاء رابط لهذه المحادثة.',
  'links.create.error.default': 'تعذّر إنشاء الرابط. أعد المحاولة.',

  /* L'ESPACE D'ADMINISTRATION (#6432) — les onze sections reprennent les
     libellés de la barre latérale du legacy (`AdminLayout.tsx`), pour qu'un
     administrateur retrouve ses repères d'une application à l'autre. */
  'admin.title': 'الإدارة',
  'admin.role': 'دورك: {role}',
  'admin.denied.title': 'منطقة محجوزة',
  'admin.denied.message': 'تتطلب هذه المنطقة صلاحية إدارية.',
  'admin.counters.title': 'لمحة سريعة',
  'admin.counters.unavailable': 'العدادات غير متاحة حاليًا.',
  'admin.counters.users': 'الحسابات',
  'admin.counters.activeUsers': 'الحسابات النشطة',
  'admin.counters.messages': 'الرسائل',
  'admin.counters.communities': 'المجتمعات',
  'admin.counters.reports': 'البلاغات',
  'admin.counters.newUsers': 'جديد (٢٤ ساعة)',
  'admin.sections.title': 'الأقسام',
  'admin.sections.legacy': 'الواجهة السابقة',
  'admin.nav.dashboard': 'لوحة المعلومات',
  'admin.nav.users': 'الحسابات',
  'admin.nav.moderation': 'الإشراف',
  'admin.nav.audit': 'سجلات التدقيق',
  'admin.nav.analytics': 'الإحصاءات',
  'admin.nav.trackingLinks': 'روابط التتبع',
  'admin.nav.ranking': 'الترتيب',
  'admin.nav.broadcasts': 'البثوث',
  'admin.nav.settings': 'الإعدادات',
  'admin.nav.agent': 'الوكيل',
  'admin.nav.monitoring': 'المراقبة',
  'admin.users.search': 'ابحث عن حساب',
  'admin.users.count': '{count} حساب',
  'admin.users.empty': 'لا يوجد حساب مطابق.',
  'admin.users.unavailable': 'القائمة غير متاحة حاليًا.',
  'admin.users.inactive': 'معطّل',
  'admin.users.previous': 'السابق',
  'admin.users.next': 'التالي',
  'admin.user.title': 'عضو',
  'admin.user.unavailable': 'البطاقة غير متاحة حاليًا.',
  'admin.user.identity': 'الهوية',
  'admin.user.account': 'الحساب',
  'admin.user.created': 'انضمّ في',
  'admin.user.lastActive': 'آخر نشاط',
  'admin.user.twoFactor': 'التحقق بخطوتين',
  'admin.user.enabled': 'مُفعّل',
  'admin.user.deleted': 'محذوف',
  'admin.user.role': 'الدور',
  'admin.edit.open': 'تعديل',
  'admin.edit.title': 'تعديل العضو',
  'admin.edit.displayName': 'الاسم المعروض',
  'admin.edit.email': 'البريد الإلكتروني',
  'admin.edit.bio': 'نبذة',
  'admin.edit.active': 'الحساب نشط',
  'admin.edit.save': 'حفظ',
  'admin.edit.reason': 'السبب (اختياري)',
  'admin.edit.warnRole': 'تغيير الدور يغيّر صلاحياته.',
  'admin.edit.warnDeactivate': 'التعطيل ينهي جلساته المفتوحة.',
  'admin.edit.confirm': 'تأكيد',
  'admin.edit.saved': 'تم حفظ التغييرات',
  'admin.edit.failed': 'تعذّر الحفظ',

} satisfies InterfaceCatalog;

export default ar;
