import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const ar = {
  'announce.messageSent': 'تم إرسال الرسالة',
  'announce.messageCopied': 'تم نسخ الرسالة',
  'announce.messagesCopied': 'تم نسخ الرسائل',
  'announce.messageProtected': 'رسالة محمية',
  'announce.selectionCap': '{count} رسالة كحد أقصى',
  'announce.nothingToCopy': 'لا شيء للنسخ',

  'message.author.self': 'أنت',
  'message.excerpt.protected': 'محتوى محمي',
  'a11y.message.menu.subject': 'إجراءات رسالة {author}: {excerpt}',

  'typing.named': '{name} يكتب',
  'typing.double': '{first} و{second} يكتبان',
  'typing.several': 'عدة أشخاص يكتبون',

  'root.menu.feed': 'التدفق',
  'root.menu.links': 'روابطي',
  'root.menu.notifications': 'الإشعارات',
  'root.menu.calls': 'المكالمات',
  'root.menu.discover': 'اكتشاف',
  'root.menu.communities': 'المجتمعات',
  'root.menu.settings': 'الإعدادات',
  'root.menu.profile': 'الملف الشخصي',
  'a11y.floating.menu': 'القائمة',
  'a11y.floating.menu.ladder': 'التنقل في Meeshy',
  'a11y.floating.menu.unread.one': 'القائمة، {count} إشعار غير مقروء',
  'a11y.floating.menu.unread.other': 'القائمة، {count} إشعارات غير مقروءة',
  'a11y.floating.rung.notifications.unread.one': 'الإشعارات، {count} غير مقروء',
  'a11y.floating.rung.notifications.unread.other': 'الإشعارات، {count} غير مقروءة',

  'notifications.category.all': 'الكل',
  'notifications.category.unread': 'غير المقروءة',
  'notifications.category.messages': 'الرسائل',
  'notifications.category.reactions': 'التفاعلات',
  'notifications.category.mentions': 'الإشارات',
  'notifications.category.social': 'اجتماعي',
  'notifications.category.contacts': 'جهات الاتصال',
  'notifications.category.groups': 'المجموعات',
  'notifications.category.calls': 'المكالمات',
  'notifications.category.translations': 'الترجمات',
  'notifications.category.system': 'النظام',
  'notifications.categories': 'فئات الإشعارات',
  'notifications.markAllRead': 'قراءة الكل',
  'notifications.unreadCount.one': '{count} غير مقروء',
  'notifications.unreadCount.other': '{count} غير مقروءة',
  'notifications.unread': 'غير مقروء',
  'notifications.empty.all': 'لا توجد إشعارات',
  'notifications.empty.unread': 'لا توجد إشعارات غير مقروءة',
  'notifications.empty.category': 'لا توجد إشعارات في «{category}»',
  'notifications.empty.subtitle': 'ستظهر إشعاراتك هنا',
  'notifications.loading': 'جارٍ تحميل الإشعارات',
  'notifications.error.title': 'تعذّر تحميل الإشعارات',
  'notifications.error.body': 'أعد المحاولة بعد لحظة.',
  'notifications.offline.title': 'غير متصل',
  'notifications.offline.body': 'ستظهر إشعاراتك عند عودة الاتصال.',
  'notifications.retry': 'إعادة المحاولة',
  'notifications.allLoaded': 'تم تحميل جميع الإشعارات',
  'notifications.actions': 'إجراءات الإشعار',
  'notifications.action.markRead': 'وضع علامة كمقروء',
  'notifications.action.delete': 'حذف',
  'notifications.failure': 'لم يكتمل الإجراء. أعد المحاولة.',

  'pending.back': 'العودة إلى المحادثات',
  'pending.comingSoon': 'هذه الشاشة قادمة قريبًا.',
  'pending.feed.promise': 'منشورات الأشخاص الذين تتابعهم.',
  'pending.links.promise': 'ستُجمع هنا الروابط التي تمت مشاركتها في محادثاتك.',
  'pending.notifications.promise': 'ما ينتظرك — الإشارات والردود والدعوات — ستقرؤه هنا.',
  'pending.calls.promise': 'سجل مكالماتك، وطريقة لإجراء مكالمة.',
  'pending.discover.promise': 'أشخاص للتعرف عليهم، يتم اختيارهم بحسب ما يجمعكم.',
  'pending.communities.promise': 'المجتمعات التي تنتمي إليها، وتلك التي تشبهك.',
  'pending.settings.promise': 'لغاتك وخصوصيتك وإشعاراتك.',
  'pending.profile.promise': 'هويتك على Meeshy — الاسم والصورة واللغات وما يراه الآخرون منها.',
} satisfies InterfaceCatalog;

export default ar;
