import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const es = {
  'announce.messageSent': 'Mensaje enviado',
  'announce.messageCopied': 'Mensaje copiado',
  'announce.messagesCopied': 'Mensajes copiados',
  'announce.messageProtected': 'Mensaje protegido',
  'announce.selectionCap': 'Máximo {count} mensajes',
  'announce.nothingToCopy': 'Nada que copiar',

  'message.author.self': 'Tú',
  'message.excerpt.protected': 'contenido protegido',
  'a11y.message.menu.subject': 'Acciones del mensaje de {author}: {excerpt}',

  'typing.named': '{name} está escribiendo',
  'typing.double': '{first} y {second} están escribiendo',
  'typing.several': 'Varias personas están escribiendo',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'Mis enlaces',
  'root.menu.notifications': 'Notificaciones',
  'root.menu.calls': 'Llamadas',
  'root.menu.discover': 'Descubrir',
  'root.menu.communities': 'Comunidades',
  'root.menu.settings': 'Ajustes',
  'root.menu.profile': 'Perfil',
  'a11y.floating.menu': 'Menú',
  'a11y.floating.menu.ladder': 'Navegación de Meeshy',
  'a11y.floating.menu.unread.one': 'Menú, {count} notificación no leída',
  'a11y.floating.menu.unread.other': 'Menú, {count} notificaciones no leídas',
  'a11y.floating.rung.notifications.unread.one': 'Notificaciones, {count} no leída',
  'a11y.floating.rung.notifications.unread.other': 'Notificaciones, {count} no leídas',

  'notifications.category.all': 'Todas',
  'notifications.category.unread': 'No leídas',
  'notifications.category.messages': 'Mensajes',
  'notifications.category.reactions': 'Reacciones',
  'notifications.category.mentions': 'Menciones',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contactos',
  'notifications.category.groups': 'Grupos',
  'notifications.category.calls': 'Llamadas',
  'notifications.category.translations': 'Traducciones',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorías de notificaciones',
  'notifications.markAllRead': 'Marcar todo como leído',
  'notifications.unreadCount.one': '{count} no leída',
  'notifications.unreadCount.other': '{count} no leídas',
  'notifications.unread': 'No leída',
  'notifications.empty.all': 'No hay notificaciones',
  'notifications.empty.unread': 'No hay notificaciones no leídas',
  'notifications.empty.category': 'No hay notificaciones en «{category}»',
  'notifications.empty.subtitle': 'Tus notificaciones aparecerán aquí',
  'notifications.loading': 'Cargando notificaciones',
  'notifications.error.title': 'No se pudieron cargar las notificaciones',
  'notifications.error.body': 'Inténtalo de nuevo en un momento.',
  'notifications.offline.title': 'Sin conexión',
  'notifications.offline.body': 'Tus notificaciones aparecerán cuando vuelvas a estar en línea.',
  'notifications.retry': 'Reintentar',
  'notifications.allLoaded': 'Todas las notificaciones están cargadas',
  'notifications.actions': 'Acciones de la notificación',
  'notifications.action.markRead': 'Marcar como leída',
  'notifications.action.delete': 'Eliminar',
  'notifications.failure': 'La acción no se completó. Inténtalo de nuevo.',

  'pending.back': 'Volver a las conversaciones',
  'pending.comingSoon': 'Esta pantalla llegará pronto.',
  'pending.feed.promise': 'Las publicaciones de las personas que sigues.',
  'pending.links.promise': 'Los enlaces compartidos en tus conversaciones se reunirán aquí.',
  'pending.notifications.promise': 'Lo que te espera — menciones, respuestas, invitaciones — se leerá aquí.',
  'pending.calls.promise': 'El historial de tus llamadas, y cómo hacer una.',
  'pending.discover.promise': 'Personas por conocer, elegidas por lo que tienen en común.',
  'pending.communities.promise': 'Las comunidades de las que formas parte, y las que se parecen a ti.',
  'pending.settings.promise': 'Tus idiomas, tu privacidad, tus notificaciones.',
  'pending.profile.promise': 'Tu identidad en Meeshy — nombre, foto, idiomas y lo que los demás ven de ella.',

  'profile.title': 'Perfil',
  'profile.edit': 'Editar',
  'profile.cancel': 'Cancelar',
  'profile.save': 'Guardar',
  'profile.saving': 'Guardando…',
  'profile.saved': 'Perfil guardado',
  'profile.save.error': 'Error al guardar',
  'profile.save.offline': 'Sin conexión — el cambio no se envió.',
  'profile.save.invalid': 'Revisa el campo «{field}».',
  'profile.loading': 'Cargando el perfil',
  'profile.error.title': 'No se pudo cargar tu perfil',
  'profile.error.body': 'Vuelve a intentarlo en un momento.',
  'profile.retry': 'Reintentar',
  'profile.offline.title': 'Sin conexión',
  'profile.offline.body': 'Tu perfil sigue visible; la edición vuelve con la red.',
  'profile.avatar.edit': 'Editar foto de perfil',
  'profile.avatar.updated': 'Foto de perfil actualizada',
  'profile.avatar.error': 'No se pudo actualizar la foto de perfil',
  'profile.banner.edit': 'Editar banner',
  'profile.banner.updated': 'Banner actualizado',
  'profile.banner.error': 'No se pudo actualizar el banner',
  'profile.image.uploading': 'Enviando',
  'profile.image.cancel': 'Cancelar el envío',
  'profile.image.cancelled': 'Envío cancelado',
  'profile.image.unreadable': 'Esta imagen no se puede leer.',
  'profile.section.identity': 'IDENTIDAD',
  'profile.section.contact': 'CONTACTO',
  'profile.section.languages': 'IDIOMAS',
  'profile.section.stats': 'ESTADÍSTICAS',
  'profile.section.requests': 'SOLICITUDES',
  'profile.section.member_since': 'MIEMBRO DESDE',
  'profile.first_name': 'Nombre',
  'profile.last_name': 'Apellido',
  'profile.username': 'Usuario',
  'profile.display_name': 'Nombre visible',
  'profile.bio': 'Biografía',
  'profile.bio.placeholder': 'Cuéntanos sobre ti...',
  'profile.email': 'Correo electrónico',
  'profile.phone': 'Teléfono',
  'profile.verified': 'Verificado',
  'profile.not_verified': 'No verificado',
  'profile.language.primary': 'Idioma principal',
  'profile.language.primary.subtitle': 'El contenido se traducirá a este idioma',
  'profile.language.regional': 'Idioma regional',
  'profile.language.custom': 'Idioma personalizado',
  'profile.language.none': 'Ninguno',
  'profile.language.choose': 'Elegir',
  'profile.language.clear.regional': 'Quitar el idioma regional',
  'profile.language.clear.custom': 'Quitar el idioma personalizado',
  'profile.stats.messages': 'Mensajes',
  'profile.stats.translations': 'Traducciones',
  'profile.stats.languages': 'Idiomas',
  'profile.stats.days': 'Días',
  'profile.stats.loading': 'Cargando las estadísticas',
  'profile.progression.title': 'Progreso',
  'profile.progression.subtitle': 'Insignias, nivel y racha',
  'profile.friend_requests': 'Solicitudes de amistad',
  'profile.friend_requests.count.one': '{count} solicitud pendiente',
  'profile.friend_requests.count.other': '{count} solicitudes pendientes',
} satisfies InterfaceCatalog;

export default es;
