/**
 * LE CATALOGUE D'INTERFACE FRANÇAIS (#6206) — la SOURCE DES CLÉS. Les six
 * autres langues portent exactement celles-ci : `satisfies InterfaceCatalog`
 * le vérifie à la compilation, `i18n-catalog.test.ts` le mesure à l'exécution.
 *
 * Les noms reprennent ceux d'iOS (`apps/ios/Meeshy/Localizable.xcstrings`)
 * partout où iOS en a un — `root.menu.*`, `a11y.floating.menu`, `typing.*` ;
 * les autres sont propres au web et le disent par leur préfixe (`pending.*`).
 * Un paramètre s'écrit `{nom}` et se place là où la LANGUE le veut, jamais là
 * où un site d'appel le concatène.
 */
const fr = {
  'announce.messageSent': 'Message envoyé',
  'announce.messageCopied': 'Message copié',
  'announce.messagesCopied': 'Messages copiés',
  'announce.messageProtected': 'Message protégé',
  'announce.selectionCap': 'Maximum {count} messages',
  'announce.nothingToCopy': 'Rien à copier',

  'message.author.self': 'Vous',
  'message.excerpt.protected': 'contenu protégé',
  'a11y.message.menu.subject': 'Actions du message de {author} : {excerpt}',

  'typing.named': '{name} écrit',
  'typing.double': '{first} et {second} écrivent',
  'typing.several': 'Plusieurs personnes écrivent',

  /* LES RÉELS (#6457) — le bouton de l'en-tête du Flux et le lecteur plein
     écran ; `feed.header.reels`, `reels.back`, `reels.empty` et
     `reels.action.*` reprennent les clés d'iOS. */
  'feed.header.reels': 'Lancer les Réels',
  'reels.title': 'Réels',
  'reels.back': 'Retour',
  'reels.open': 'Regarder le réel de {author}',
  'reels.item': 'Réel de {author}, {index} sur {count}',
  'reels.loading': 'Chargement des réels',
  'reels.empty': 'Aucun réel pour le moment',
  'reels.empty.hint': 'Les réels de vos contacts apparaîtront ici.',
  'reels.error': 'Impossible de charger les réels',
  'reels.error.hint': 'Réessayez dans un instant.',
  'reels.retry': 'Réessayer',
  'reels.offline': 'Hors ligne',
  'reels.offline.cold': 'Les réels se chargeront dès le retour du réseau.',
  'reels.action.like': 'J’aime',
  'reels.action.bookmark': 'Enregistrer',
  'reels.action.share': 'Partager',
  'reels.sound.on': 'Activer le son',
  'reels.sound.off': 'Couper le son',
  'reels.play': 'Lire le réel',
  'reels.pause': 'Mettre le réel en pause',
  'reels.media.error': 'Lecture impossible — Réessayer',
  'reels.image': 'Image {index} sur {count}',

  /* TOUTES LES STORIES (#6547) — `routes/stories.tsx`, même patron que le Flux. */
  'stories.title': 'Stories',
  'stories.loading': 'Chargement des stories…',
  'stories.error': "Les stories n'ont pas pu être chargées.",
  'stories.empty.title': "Aucune story pour l'instant",
  'stories.empty.subtitle': 'Les stories de vos contacts apparaîtront ici pendant vingt heures.',
  'stories.create': 'Créer une story',
  'stories.count.one': '{count} story',
  'stories.count.other': '{count} stories',
  /* LE LIBELLÉ DU GROUPE DU LECTEUR (#6550) — partagé par le rail
     (`components/story-rail.tsx`) et la liste « Toutes les stories »
     (`routes/stories.tsx`), via `storyAuthorLabel()`. */
  'stories.mine': 'Votre story',

  /* LES DEUX PORTES DE MA CELLULE (#6150) — le (+) haut-gauche et la pastille
     d'humeur bas-droite, miroir `LentilleRailSelfEntryView`
     (`StoriesVivantsRail.swift`) et de ses deux libellés `StoryTrayCopy`
     (`addStory`, `changeMood`). `{emoji}` est ANNONCÉ, jamais dessiné : sans
     lui, un lecteur d'écran entendrait deux fois le même bouton. */
  'stories.self.addStory': 'Ajouter une story',
  'stories.self.mood.add': 'Poser une humeur',
  'stories.self.mood.change': 'Changer mon humeur, {emoji}',

  /* MON HUMEUR (#6150) — l'écran de composition, `routes/status-compose.tsx`.
     MINIMAL, comme la directive porteur le demande : un emoji, un mot, on
     publie. Le composeur d'humeur complet d'iOS (`ComposerMoodSurface.swift`)
     reste hors tranche. */
  'status.compose.title': 'Mon humeur',
  'status.compose.pick': 'Choisir une humeur',
  'status.compose.note': 'Un mot, si vous voulez',
  'status.compose.publish': 'Publier',
  'status.compose.publishing': 'Publication…',
  'status.compose.error': "Votre humeur n'a pas pu être publiée.",
  'status.compose.offline': 'Hors ligne — votre humeur partira au retour du réseau.',

  /* LA CARTE DU FIL ET SES GESTES (#6488) — `FeedPostCard`, l'en-tête et les
     quatre états du Flux (`routes/feed.tsx`), et les échecs d'un geste
     (`lib/api/feed-gestures.ts`, `lib/feed/share-url.ts`) : tous écrits en
     dur en français jusqu'ici, alors qu'une coque branchée en anglais servait
     déjà `reels.open` sur la même carte. */
  'feed.post.action.like': 'Aimer',
  'feed.post.action.comment': 'Commenter',
  'feed.post.action.repost': 'Repartager',
  'feed.post.action.bookmark': 'Enregistrer',
  'feed.post.action.share': 'Partager',
  'feed.post.media.video': 'Vidéo',
  'feed.post.media.audio': 'Audio',
  'feed.post.media.previous': 'Média précédent',
  'feed.post.media.next': 'Média suivant',
  'feed.post.media.mosaic': 'Mosaïque de {count} médias',
  'media.unavailable': 'Média indisponible',
  'feed.post.see_more': 'voir plus',
  'feed.post.see_less': 'voir moins',
  'feed.post.reel.chip': 'Réel',
  'feed.post.reel.of': 'Réel de {author}',
  /* OUVRIR LA PUBLICATION (#7284) — le nom accessible DIT sa destination :
     « Ouvrir » seul laisserait le lecteur d'écran deviner de quelle carte
     il s'agit dans un fil qui en aligne vingt. */
  'feed.post.open': 'Ouvrir la publication de {author}',
  /* LES PUBLICATIONS ENREGISTRÉES (#7286) — l'écran `/me/bookmarks` et sa rangée de Réglages › Outils. */
  'bookmarks.title': 'Publications enregistrées',
  'bookmarks.back': 'Retour aux réglages',
  'bookmarks.loading': 'Chargement des publications enregistrées',
  'bookmarks.empty.title': 'Aucune publication enregistrée',
  'bookmarks.empty.subtitle': 'Touchez le signet sous une publication pour la garder ici et la relire quand vous voulez.',
  'bookmarks.empty.cta': 'Ouvrir le Flux',
  'bookmarks.error.title': 'Impossible de charger vos enregistrements',
  'bookmarks.error.body': 'Réessayez dans un instant.',
  'bookmarks.offline.body': 'Vos enregistrements s’afficheront à la reconnexion.',
  'bookmarks.allLoaded': 'Toutes vos publications enregistrées sont chargées',
  'bookmarks.filter.all': 'Tout',
  'bookmarks.filter.posts': 'Postes',
  'bookmarks.filter.reels': 'Réels',
  'bookmarks.filter.a11y': 'Filtrer les enregistrements',
  'settings.tools.bookmarks': 'Publications enregistrées',
  'feed.error.title': 'Impossible de charger le fil',
  'feed.error.body': 'Réessayez dans un instant.',
  'feed.offline.title': 'Hors ligne',
  'feed.offline.body': 'Le fil s’affichera à la reconnexion.',
  'feed.retry': 'Réessayer',
  'feed.empty.title': 'Aucune publication',
  'feed.empty.subtitle': 'Les publications de vos contacts apparaîtront ici.',
  'feed.loading': 'Chargement du fil',
  'feed.allLoaded': 'Toutes les publications sont chargées',
  'feed.newPosts.one': '{count} nouvelle publication',
  'feed.newPosts.other': '{count} nouvelles publications',
  'a11y.avatar.profile': 'Voir le profil de {name}',
  'a11y.avatar.story': 'Voir la story de {name}',
  'userProfile.self.edit': 'Modifier mon profil',
  'report.title': 'Signaler ce compte',
  'report.body': 'Choisissez ce qui motive votre signalement. Notre équipe de modération le recevra.',
  'report.action': 'Signaler',
  'report.done': 'Signalement envoyé',
  'report.throttled': 'Trop de signalements — réessayez dans un moment',
  'report.failed': 'Le signalement n’a pas pu être envoyé',
  'report.reason.spam': 'Spam',
  'report.reason.inappropriate': 'Contenu inapproprié',
  'report.reason.harassment': 'Harcèlement',
  'report.reason.violence': 'Violence',
  'report.reason.hate_speech': 'Discours haineux',
  'report.reason.fake_profile': 'Faux profil',
  'report.reason.impersonation': 'Usurpation d’identité',
  'report.reason.other': 'Autre',
  'feed.like.error': 'Impossible d’aimer la publication',
  'post.bookmark.error': 'Erreur lors de l’enregistrement',
  'feed.gesture.pending': 'Geste non confirmé — hors ligne',
  'feed.share.error': 'Impossible de partager la publication',
  'feed.share.copied': 'Lien copié — il ne reste qu’à le coller.',
  'feed.share.text': 'Une publication sur Meeshy',

  'root.menu.feed': 'Flux',
  'root.menu.links': 'Mes liens',
  'root.menu.notifications': 'Notifications',
  'root.menu.calls': 'Appels',
  'root.menu.discover': 'Découvrir',
  'root.menu.communities': 'Communautés',
  'root.menu.settings': 'Réglages',
  'root.menu.profile': 'Profil',
  'root.menu.conversations': 'Conversations',
  'a11y.floating.feed.hint': 'Appui long pour lancer les Réels',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Navigation Meeshy',
  'a11y.floating.menu.unread.one': 'Menu, {count} notification non lue',
  'a11y.floating.menu.unread.other': 'Menu, {count} notifications non lues',
  'a11y.floating.rung.notifications.unread.one': 'Notifications, {count} non lue',
  'a11y.floating.rung.notifications.unread.other': 'Notifications, {count} non lues',

  'notifications.category.all': 'Toutes',
  'notifications.category.unread': 'Non lues',
  'notifications.category.messages': 'Messages',
  'notifications.category.reactions': 'Réactions',
  'notifications.category.mentions': 'Mentions',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contacts',
  'notifications.category.groups': 'Groupes',
  'notifications.category.calls': 'Appels',
  'notifications.category.translations': 'Traductions',
  'notifications.category.system': 'Système',
  'notifications.categories': 'Catégories de notifications',
  'notifications.markAllRead': 'Tout lire',
  'notifications.unreadCount.one': '{count} non lue',
  'notifications.unreadCount.other': '{count} non lues',
  'notifications.unread': 'Non lue',
  'notifications.empty.all': 'Aucune notification',
  'notifications.empty.unread': 'Aucune notification non lue',
  'notifications.empty.category': 'Aucune notification dans « {category} »',
  'notifications.empty.subtitle': 'Vos notifications apparaîtront ici',
  'notifications.loading': 'Chargement des notifications',
  'notifications.error.title': 'Impossible de charger les notifications',
  'notifications.error.body': 'Réessayez dans un instant.',
  'notifications.offline.title': 'Hors ligne',
  'notifications.offline.body': 'Vos notifications s’afficheront à la reconnexion.',
  'notifications.retry': 'Réessayer',
  'notifications.allLoaded': 'Toutes les notifications sont chargées',
  'notifications.actions': 'Actions de la notification',
  'notifications.action.markRead': 'Marquer comme lue',
  'notifications.action.delete': 'Supprimer',
  'notifications.failure': 'L’action n’a pas abouti. Réessayez.',

  'notFound.title': "Cette adresse n'existe pas.",

  'pending.back': 'Revenir aux conversations',

  /* LES LIENS REÇUS (#6714, #6715) — les pages que visent les liens suivis
     `/l/:token` et les e-mails de compte (suppression, changement d'adresse,
     désabonnement). `linkPage.*` porte les états qu'elles partagent. */
  'linkPage.home': 'Retour à Meeshy',
  'linkPage.retry': 'Réessayer',
  'linkPage.settings': 'Ouvrir les réglages',
  'linkPage.signIn': 'Se connecter',
  'linkPage.offline.title': 'Hors ligne',
  'linkPage.offline.body': 'Reconnectez-vous à Internet, puis réessayez.',
  'linkPage.unavailable.title': 'Meeshy ne répond pas',
  'linkPage.unavailable.body': 'Le service est momentanément indisponible. Réessayez dans quelques instants.',
  'linkPage.rateLimited': 'Trop de tentatives. Patientez un moment avant de réessayer.',
  'linkPage.signedOut.title': 'Connectez-vous pour continuer',
  'linkPage.signedOut.body': 'Ce lien agit sur votre compte. Connectez-vous, puis rouvrez-le depuis l’e-mail.',
  'linkPage.expired': 'Ce lien a expiré. Refaites la demande depuis les réglages.',
  'trackingLink.opening': 'Ouverture du lien…',
  'trackingLink.dead.title': 'Ce lien n’est plus disponible',
  'trackingLink.dead.body': 'Il a expiré, a été désactivé ou n’a jamais existé.',
  'accountDeletion.incomplete.title': 'Lien incomplet',
  'accountDeletion.incomplete.body': 'Ce lien ne porte pas les informations nécessaires. Connectez-vous pour demander la suppression de votre compte.',
  'accountDeletion.confirm.title': 'Confirmer la suppression de votre compte',
  'accountDeletion.confirm.body':
    'Votre compte sera désactivé au terme d’une période de grâce de 30 jours. D’ici là, le lien « Annuler » de l’e-mail vous permet de revenir en arrière.',
  'accountDeletion.confirm.action': 'Confirmer la suppression',
  'accountDeletion.cancel.title': 'Annuler la suppression de votre compte',
  'accountDeletion.cancel.body': 'Votre compte reste actif et la demande de suppression est abandonnée. Rien n’est perdu.',
  'accountDeletion.cancel.action': 'Annuler la suppression',
  'accountDeletion.purge.title': 'Supprimer votre compte maintenant',
  'accountDeletion.purge.body': 'Votre compte sera désactivé sur-le-champ et toutes vos sessions seront fermées. Ce geste est définitif.',
  'accountDeletion.purge.action': 'Supprimer maintenant',
  'accountDeletion.dismiss': 'Ne rien faire',
  'accountDeletion.working': 'Un instant…',
  'accountDeletion.done.title': 'C’est fait',
  'accountDeletion.done.confirmed': 'Votre demande est confirmée : votre compte sera désactivé le {date}. Vous pouvez annuler d’ici là.',
  'accountDeletion.done.cancelled': 'Votre compte reste actif : la demande de suppression est abandonnée.',
  'accountDeletion.done.completed': 'Votre compte est désactivé et toutes vos sessions ont été fermées.',
  'accountDeletion.done.purged': 'Vos données ont été effacées.',
  'accountDeletion.closed.title': 'Ce lien ne sert plus',
  'accountDeletion.invalid': 'Ce lien est invalide ou a déjà servi.',
  'accountDeletion.request.title': 'Supprimer votre compte',
  'accountDeletion.request.body':
    'Vos conversations, messages, médias, contacts et préférences seront supprimés. Un e-mail vous demandera de confirmer, puis une période de grâce de 30 jours vous laissera revenir en arrière.',
  'accountDeletion.request.phrase': 'Tapez {phrase} pour confirmer',
  'accountDeletion.request.password': 'Mot de passe actuel',
  'accountDeletion.request.action': 'Demander la suppression',
  'accountDeletion.request.sent.title': 'Un e-mail de confirmation vous a été envoyé',
  'accountDeletion.request.sent.body': 'Ouvrez-le pour confirmer la suppression de votre compte.',
  'accountDeletion.request.wrongPassword': 'Mot de passe incorrect.',
  'accountDeletion.request.alreadyPending': 'Une demande est déjà en cours. Ouvrez l’e-mail reçu pour la confirmer ou l’annuler.',
  'accountDeletion.request.noEmail': 'Ajoutez et vérifiez une adresse e-mail avant de demander la suppression.',
  'emailChange.verifying': 'Confirmation de votre nouvelle adresse…',
  'emailChange.done.title': 'Adresse e-mail modifiée',
  'emailChange.done.body': 'Vous vous connectez désormais avec {email}.',
  'emailChange.done.generic': 'Votre nouvelle adresse e-mail est confirmée.',
  'emailChange.failed.title': 'Adresse non modifiée',
  'emailChange.missing': 'Ce lien ne porte pas de code de confirmation. Ouvrez celui de l’e-mail le plus récent.',
  'emailChange.invalid': 'Ce lien ne correspond à aucun changement en attente sur ce compte, ou il a déjà servi.',
  'emailChange.taken': 'Cette adresse est désormais utilisée par un autre compte.',
  'emailNotifications.title': 'E-mails de Meeshy',
  'emailNotifications.loading': 'Lecture de votre préférence…',
  'emailNotifications.on': 'Vous recevez les annonces, récapitulatifs et notifications de Meeshy par e-mail.',
  'emailNotifications.off': 'Vous ne recevez plus les annonces, récapitulatifs ni notifications de Meeshy par e-mail.',
  'emailNotifications.security': 'Les e-mails de sécurité de votre compte continuent d’arriver.',
  'emailNotifications.unsubscribe': 'Ne plus recevoir ces e-mails',
  'emailNotifications.resubscribe': 'Recevoir de nouveau ces e-mails',
  'emailNotifications.failed': 'Le changement n’a pas abouti. Réessayez.',

  'dataExport.title': 'Exporter mes données',
  'dataExport.info.body': 'Conformément au RGPD, recevez un fichier reprenant votre profil, vos messages, vos contacts et vos publications.',
  'dataExport.action.start': 'Exporter mes données',
  'dataExport.action.exporting': 'Export en cours…',
  'dataExport.action.again': 'Exporter à nouveau',
  'dataExport.done.title': 'Export terminé',
  'dataExport.done.body': 'Le fichier a été téléchargé sur cet appareil.',

  'profile.title': 'Profil',
  'profile.edit': 'Modifier',
  'profile.cancel': 'Annuler',
  'profile.save': 'Enregistrer',
  'profile.saving': 'Enregistrement…',
  'profile.saved': 'Profil enregistré',
  'profile.save.error': "Erreur lors de l'enregistrement",
  'profile.save.offline': 'Hors ligne — la modification n’est pas partie.',
  'profile.save.invalid': 'Vérifiez le champ « {field} ».',
  'profile.loading': 'Chargement du profil',
  'profile.error.title': 'Impossible de charger votre profil',
  'profile.error.body': 'Réessayez dans un instant.',
  'profile.retry': 'Réessayer',
  'profile.offline.title': 'Hors ligne',
  'profile.offline.body': 'Votre profil reste lisible ; la modification reviendra avec le réseau.',
  'profile.avatar.edit': 'Modifier la photo de profil',
  'profile.avatar.updated': 'Photo de profil mise à jour',
  'profile.avatar.error': 'Impossible de mettre à jour la photo de profil',
  'profile.banner.edit': 'Modifier la bannière',
  'profile.banner.updated': 'Bannière mise à jour',
  'profile.banner.error': 'Impossible de mettre à jour la bannière',
  'profile.image.uploading': 'Envoi en cours',
  'profile.image.cancel': 'Annuler l’envoi',
  'profile.image.cancelled': 'Envoi annulé',
  'profile.image.unreadable': 'Cette image ne peut pas être lue.',
  'profile.section.identity': 'IDENTITÉ',
  'profile.section.contact': 'CONTACT',
  'profile.section.languages': 'LANGUES',
  'profile.section.stats': 'STATISTIQUES',
  'profile.section.requests': 'DEMANDES',
  'profile.section.member_since': 'MEMBRE DEPUIS',
  'profile.first_name': 'Prénom',
  'profile.last_name': 'Nom',
  'profile.username': 'Pseudo',
  'profile.display_name': "Nom d'affichage",
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Parlez de vous...',
  'profile.email': 'Email',
  'profile.phone': 'Téléphone',
  'profile.verified': 'Vérifié',
  'profile.not_verified': 'Non vérifié',
  'profile.language.primary': 'Langue principale',
  'profile.language.primary.subtitle': 'Le contenu sera traduit dans cette langue',
  'profile.language.regional': 'Langue régionale',
  'profile.language.custom': 'Langue personnalisée',
  'profile.language.none': 'Aucune',
  'profile.language.choose': 'Choisir',
  'profile.language.clear.regional': 'Retirer la langue régionale',
  'profile.language.clear.custom': 'Retirer la langue personnalisée',

  /* LA FEUILLE DE CHOIX DE LANGUE, PARLÉE DANS LA LANGUE D'INTERFACE (#6328)
     — titre par défaut (inscription), titre du composeur, recherche et état
     vide de `language-sheet.tsx`. `title`/`selected` restent des props
     explicites (#5828) : ces clés ne servent qu'à défaut d'un `title` fourni
     par l'appelant, et toujours pour la recherche/l'état vide. */
  'languageSheet.title.read': 'Langue de lecture',
  'languageSheet.title.write': 'Langue d’écriture',
  'languageSheet.search': 'Rechercher une langue',
  'languageSheet.empty': 'Aucune langue ne correspond à « {search} ».',

  'profile.stats.messages': 'Messages',
  'profile.stats.translations': 'Traductions',
  'profile.stats.languages': 'Langues',
  'profile.stats.days': 'Jours',
  'profile.stats.loading': 'Chargement des statistiques',
  'profile.progression.title': 'Progression',
  'profile.progression.subtitle': 'Badges, niveau et série',
  'profile.friend_requests': "Demandes d'amis",
  'profile.friend_requests.count.one': '{count} demande en attente',
  'profile.friend_requests.count.other': '{count} demandes en attente',

  'settings.title': 'Réglages',
  'settings.my_profile': 'Mon profil',
  'settings.section.account': 'Compte',
  'settings.security.title': 'Sécurité',
  'settings.delete_account': 'Supprimer le compte',
  'settings.privacy.title': 'Confidentialité',
  'settings.privacy.online_status': 'Statut en ligne',
  'settings.privacy.online_status.info':
    "La pastille verte sur votre avatar indique que vous êtes actif. Désactivée, personne ne voit ce point — mais écrire dans une conversation reste une preuve d'activité pour vos interlocuteurs.",
  'settings.privacy.last_seen': 'Dernière connexion',
  'settings.privacy.read_receipts': 'Accusés de lecture',
  'settings.privacy.read_receipts.info':
    "Réciproque : si vous ne renvoyez pas d'accusé de lecture, vous ne verrez pas non plus si vos messages ont été lus.",
  'settings.privacy.typing_indicator': 'Indicateur de frappe',
  'settings.section.appearance': 'Apparence',
  'settings.theme': 'Thème',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Clair',
  'settings.theme.dark': 'Sombre',
  'settings.interface_language': "Langue de l'interface",
  'settings.interface_language.automatic': 'Automatique',
  'settings.content_languages': 'Langues de traduction',
  'settings.section.notifications': 'Notifications',
  'settings.notifications.title': 'Notifications',
  'settings.notif.sounds': 'Sons',
  'settings.notif.more_options': "Plus d'options",
  'settings.section.data': 'Données',
  'settings.media': 'Médias',
  'settings.messages': 'Messages',
  'settings.export_data': 'Exporter mes données',
  'settings.section.tools': 'Outils',
  'settings.tools.progression': 'Progression',
  'settings.section.about': 'À propos',
  'settings.terms': "Conditions d'utilisation",
  'settings.privacy_policy': 'Politique de confidentialité',
  'settings.version': 'Version',
  'settings.logout.title': 'Déconnexion',
  'settings.logout.message': 'Voulez-vous vraiment vous déconnecter ?',
  'settings.logout.inprogress': 'Déconnexion en cours...',
  'settings.loading': 'Chargement des réglages',
  'settings.error.title': 'Impossible de charger vos réglages',
  'settings.retry': 'Réessayer',
  'settings.offline.body': 'Hors ligne — vos réglages restent lisibles ; ils se modifieront avec le réseau.',
  'settings.save.error': "Le réglage n'a pas été enregistré.",
  'settings.theme.sync_error': 'Thème appliqué sur cet appareil, sans synchronisation.',
  'common.cancel': 'Annuler',

  'media.video.play': 'Lire la vidéo',
  'media.video.pause': 'Pause',
  'media.video.position': 'Position de lecture',
  'media.audio.position': 'Position de lecture',
  'media.audio.speed': 'Vitesse de lecture',
  'media.video.position.value': '{elapsed} sur {total}',
  'media.video.mute': 'Couper le son',
  'media.video.unmute': 'Réactiver le son',
  'media.video.more_options': "Plus d'options",
  'media.video.speed': 'Vitesse',
  'media.video.pip.enter': "Image dans l'image",
  'media.video.pip.exit': "Quitter l'image dans l'image",

  'community.list.create.accessibilityLabel': 'Créer une communauté',
  'community.list.search.placeholder': 'Rechercher une communauté',
  'community.list.search.clear': 'Effacer la recherche',
  'community.list.search.empty': 'Aucune communauté ne correspond à « {query} ».',
  'community.list.empty.title': 'Aucune communauté',
  'community.list.empty.subtitle': 'Rejoignez ou créez une communauté pour échanger à plusieurs.',
  'community.list.loading': 'Chargement des communautés',
  'community.error.title': 'Impossible de charger les communautés',
  'community.error.body': 'Vérifiez votre connexion, puis réessayez.',
  'community.retry': 'Réessayer',
  'community.offline.title': 'Hors ligne',
  'community.offline.body': 'Vos communautés restent lisibles ; en créer une demande le réseau.',
  'community.privacy.private': 'Privée',
  'community.privacy.public': 'Publique',
  'community.members.one': '{count} membre',
  'community.members.other': '{count} membres',
  'community.conversations.one': '{count} conversation',
  'community.conversations.other': '{count} conversations',
  'community.detail.stats.members': 'Membres',
  'community.detail.channels': 'Conversations',
  'community.detail.channels.empty': 'Vous ne participez encore à aucune conversation de cette communauté.',
  'community.detail.untitled': 'Conversation sans titre',
  'community.detail.back': 'Revenir aux communautés',
  'community.detail.refused.title': 'Communauté introuvable',
  'community.detail.refused.body': 'Elle n’existe pas, ou elle est privée et vous n’en êtes pas membre.',
  'community.detail.error.title': 'Impossible de charger cette communauté',
  'community.detail.loading': 'Chargement de la communauté',
  'community.create.title': 'Nouvelle communauté',
  'community.create.preview.placeholder': 'Ma communauté',
  'community.create.field.name': 'Nom',
  'community.create.field.name.placeholder': 'Nom de la communauté',
  'community.create.field.identifier': 'Identifiant',
  'community.create.field.identifier.placeholder': 'mon-groupe',
  'community.create.field.description': 'Description',
  'community.create.field.description.placeholder': 'De quoi parle cette communauté ?',
  'community.create.privacy.title': 'Communauté privée',
  'community.create.privacy.private.description': 'Seuls les membres invités peuvent rejoindre',
  'community.create.privacy.public.description': 'Tout le monde peut la découvrir et la rejoindre',
  'community.create.button': 'Créer la communauté',
  'community.create.inprogress': 'Création…',
  'community.create.error.name': 'Donnez-lui un nom, 100 caractères au plus.',
  'community.create.error.identifier': 'Lettres, chiffres, tirets et tirets bas seulement, 50 au plus.',
  'community.create.error.description': '500 caractères au plus.',
  'community.create.error.conflict': 'Cet identifiant est déjà pris.',
  'community.create.error.offline': 'Hors ligne — la communauté n’est pas partie.',
  'community.create.error.default': 'La communauté n’a pas été créée. Réessayez.',
  'calls.filters': 'Filtrer le journal d’appels',
  'calls.filter.all': 'Tous',
  'calls.filter.missed': 'Manqués',
  'calls.direction.incoming': 'Reçu',
  'calls.direction.outgoing': 'Émis',
  'calls.direction.missed': 'Manqué',
  'calls.a11y.incoming': 'appel reçu',
  'calls.a11y.outgoing': 'appel émis',
  'calls.a11y.missed': 'appel manqué',
  'calls.type.audio': 'appel vocal',
  'calls.type.video': 'appel vidéo',
  'calls.duration': 'durée {duration}',
  'calls.unknown': 'Inconnu',
  'calls.empty.title': 'Aucun appel récent',
  'calls.empty.subtitle': 'Vos appels reçus, manqués, annulés et émis apparaîtront ici.',
  'calls.empty.missed.title': 'Aucun appel manqué',
  'calls.empty.missed.subtitle': 'Les appels auxquels vous n’avez pas répondu apparaîtront ici.',
  'calls.error.title': 'Le journal d’appels n’a pas pu être chargé',
  'calls.error.body': 'Vérifiez votre connexion puis réessayez.',
  'calls.offline.title': 'Hors ligne',
  'calls.offline.body': 'Vous voyez le journal du dernier chargement.',
  'calls.offline.cold.body': 'Le journal se chargera dès le retour du réseau.',
  'calls.retry': 'Réessayer',
  'calls.loading': 'Chargement du journal d’appels',
  'calls.allLoaded': 'Les appels des trois derniers mois sont tous chargés',

  'discover.tabs': 'Rubriques de la découverte',
  'discover.tab.discover': 'Découvrir',
  'discover.tab.requests': 'Demandes',
  'discover.tab.blocked': 'Bloqués',
  'discover.tab.requests.count.one': 'Demandes, {count} reçue',
  'discover.tab.requests.count.other': 'Demandes, {count} reçues',
  'discover.invite.title': 'Inviter par e-mail',
  'discover.invite.placeholder': 'Adresse e-mail',
  'discover.invite.send': 'Envoyer',
  'discover.invite.sending': 'Envoi…',
  'discover.invite.sendLabel': 'Envoyer l’invitation par e-mail',
  'discover.invite.sent': 'Invitation envoyée à {email}',
  'discover.invite.invalid': 'Cette adresse e-mail n’est pas valide.',
  'discover.invite.conflict': 'Cette personne est déjà sur Meeshy : cherchez-la ci-dessous.',
  'discover.invite.error': 'L’invitation n’a pas pu partir. Réessayez.',
  'discover.invite.offline': 'Hors ligne : reconnectez-vous pour envoyer l’invitation.',
  'discover.search.label': 'Rechercher un utilisateur Meeshy',
  'discover.search.clear': 'Effacer la recherche',
  'discover.search.searching': 'Recherche en cours',
  'discover.search.empty': 'Aucun utilisateur trouvé pour « {query} »',
  'discover.search.error': 'La recherche n’a pas abouti. Vérifiez votre connexion.',
  'discover.connection.add': 'Ajouter',
  'discover.connection.addLabel': 'Ajouter {name}',
  'discover.connection.pending': 'En attente',
  'discover.connection.cancelLabel': 'Annuler la demande envoyée à {name}',
  'discover.connection.contact': 'Contact',
  'discover.connection.blocked': 'Bloqué',
  'discover.connection.acceptLabel': 'Accepter la demande de {name}',
  'discover.connection.rejectLabel': 'Refuser la demande de {name}',
  'discover.requests.filters': 'Filtrer les demandes',
  'discover.requests.received': 'Reçues',
  'discover.requests.sent': 'Envoyées',
  'discover.requests.intent': 'Souhaite entrer en contact avec vous',
  'discover.requests.cancel': 'Annuler',
  'discover.requests.empty.received.title': 'Aucune demande reçue',
  'discover.requests.empty.received.subtitle': 'Les demandes de contact reçues apparaîtront ici.',
  'discover.requests.empty.sent.title': 'Aucune demande envoyée',
  'discover.requests.empty.sent.subtitle': 'Les demandes que vous envoyez apparaîtront ici.',
  'discover.blocked.unblock': 'Débloquer',
  'discover.blocked.unblockLabel': 'Débloquer {name}',
  'discover.blocked.confirm.title': 'Débloquer ?',
  'discover.blocked.confirm.body': 'Débloquer {name} ?',
  'discover.blocked.confirm.cancel': 'Annuler',
  'discover.blocked.empty.title': 'Aucun utilisateur bloqué',
  'discover.blocked.empty.subtitle': 'Les personnes que vous bloquez apparaîtront ici.',
  'discover.unknown': 'Inconnu',
  'discover.loading': 'Chargement',
  'discover.allLoaded': 'Toute la liste est chargée',
  'discover.error.title': 'Cette liste n’a pas pu être chargée',
  'discover.error.body': 'Vérifiez votre connexion puis réessayez.',
  'discover.offline.title': 'Hors ligne',
  'discover.offline.body': 'Vous voyez la liste du dernier chargement.',
  'discover.offline.cold.body': 'La liste se chargera dès le retour du réseau.',
  'discover.retry': 'Réessayer',
  'discover.announce.accepted': 'Connexion acceptée',
  'discover.announce.rejected': 'Demande refusée',
  'discover.announce.cancelled': 'Demande annulée',
  'discover.announce.sent': 'Demande envoyée',
  'discover.announce.unblocked': 'Personne débloquée',
  'discover.announce.acceptFailed': 'Impossible d’accepter cette demande',
  'discover.announce.rejectFailed': 'Impossible de refuser cette demande',
  'discover.announce.cancelFailed': 'Impossible d’annuler cette demande',
  'discover.announce.sendFailed': 'Impossible d’envoyer la demande',
  'discover.announce.unblockFailed': 'Impossible de débloquer',
  'discover.announce.offline': 'Hors ligne : rien n’a été envoyé.',

  /* LE PROFIL PUBLIC DE QUELQU'UN (#7083) — préfixe `userProfile.*` : le
     préfixe `profile.*` appartient à /me, et deux écrans qui partageraient un
     préfixe partageraient ses retouches. Ce qui EXISTE déjà est réutilisé, pas
     redit : `discover.connection.*` et `discover.announce.*` (les mêmes
     gestes), `profile.stats.*`, `profile.section.stats`,
     `profile.section.member_since`, `profile.retry`, `profile.offline.title`. */
  'userProfile.title': 'Profil',
  'userProfile.loading': 'Chargement du profil',
  'userProfile.section.publications': 'PUBLICATIONS',
  'userProfile.section.relation': 'CONNEXION',
  'userProfile.section.conversations': 'CONVERSATIONS',
  'userProfile.conversations.empty': 'Aucune conversation en commun',
  'userProfile.conversations.emptyBody': 'Rien ne vous relie encore — « Écrire » ouvre la première.',
  'userProfile.conversations.error': 'Impossible de charger les conversations',
  'userProfile.conversations.loading': 'Chargement des conversations',
  'userProfile.refused.title': 'Ce profil n’est pas accessible',
  'userProfile.refused.body': 'Il n’existe pas, ou vous n’y avez pas accès.',
  'userProfile.throttled.title': 'Trop de demandes',
  'userProfile.throttled.body': 'Réessayez dans un instant.',
  'userProfile.error.title': 'Impossible de charger ce profil',
  'userProfile.error.body': 'Réessayez dans un instant.',
  'userProfile.offline.body': 'Le profil s’affichera à la reconnexion.',
  'userProfile.posts.empty': 'Aucune publication',
  'userProfile.posts.emptyBody': 'Rien de public à lire pour l’instant.',
  /* LE VIDE D'UN FILTRE N'EST PAS LE VIDE D'UN COMPTE (miroir de
     `filteredEmptyState`, `ProfileUserPostsList.swift:498-510`) : dire
     « Aucune publication » à qui vient de toucher « Réels » est FAUX — le
     compte publie, c'est le filtre qui ne trouve rien ICI. */
  'userProfile.posts.emptyPosts': 'Aucun poste',
  'userProfile.posts.emptyReels': 'Aucun réel',
  'userProfile.posts.emptyFilter': 'Touchez à nouveau la tuile pour tout revoir.',
  'userProfile.posts.error': 'Impossible de charger les publications',
  'userProfile.posts.loadMore': 'Charger plus',
  /* CE QUI EST ARRIVÉ SE DIT (revue #7083) : « Charger plus » était le seul
     geste de l'écran à changer la LONGUEUR de la liste, et le seul à ne rien
     annoncer. La forme « Publications ajoutées : {count} » évite l'accord de
     pluriel dans les sept langues — un seul libellé pour 1 comme pour 12. */
  'userProfile.posts.loaded': 'Publications ajoutées : {count}',
  'userProfile.posts.loadedNone': 'Aucune publication de plus à afficher',
  'userProfile.posts.loading': 'Chargement…',
  'userProfile.stat.posts': 'Postes',
  'userProfile.stat.reels': 'Réels',
  'userProfile.stat.stories': 'Stories',
  'userProfile.stat.filterLabel': 'Filtrer sur {name}',
  'userProfile.stat.filterClear': 'Tout afficher',
  'userProfile.context.received': '{name} souhaite entrer en contact avec vous. Acceptez pour échanger des messages.',
  'userProfile.context.sent': 'Vous avez envoyé une demande de connexion à {name}. En attente de sa réponse.',
  'userProfile.action.write': 'Écrire',
  'userProfile.action.writeLabel': 'Écrire à {name}',
  'userProfile.action.block': 'Bloquer',
  'userProfile.action.blockLabel': 'Bloquer {name}',
  'userProfile.blocked.title': 'Vous avez bloqué cette personne',
  'userProfile.blocked.body': 'Ses publications et ses statistiques restent masquées tant que le blocage dure.',
  'userProfile.signin.title': 'Connectez-vous pour entrer en contact',
  'userProfile.signin.body': 'Les demandes de connexion et les messages demandent un compte.',
  'userProfile.signin.cta': 'Se connecter',
  'userProfile.announce.blocked': 'Personne bloquée',
  'userProfile.announce.blockFailed': 'Impossible de bloquer',
  'userProfile.announce.writeFailed': 'Impossible d’ouvrir la conversation',

  'a11y.floating.rung.discover.requests.one': 'Découvrir, {count} demande reçue',
  'a11y.floating.rung.discover.requests.other': 'Découvrir, {count} demandes reçues',

  'links.hub.banner.title': 'Gérez vos liens',
  'links.hub.banner.subtitle': 'Invitez qui vous voulez dans vos conversations',
  'links.hub.share.title': 'Liens de partage',
  'links.hub.share.description': 'Invitez des contacts à rejoindre vos conversations',
  'links.hub.share.create': 'Créer un lien de partage',
  'links.share.back': 'Revenir à Mes liens',
  'links.share.stats.total': 'Liens',
  'links.share.stats.active': 'Actifs',
  'links.share.stats.joined': 'Rejoints',
  'links.share.joined.one': '{count} rejoint',
  'links.share.joined.other': '{count} rejoints',
  'links.share.copy': 'Copier le lien',
  'links.share.empty.title': 'Aucun lien de partage',
  'links.share.empty.subtitle': 'Créez un lien pour inviter des personnes dans une conversation',
  'links.share.loading': 'Chargement des liens',
  'links.share.allLoaded': 'Tous vos liens sont chargés',
  'links.status.active': 'Actif',
  'links.status.inactive': 'Inactif',
  'links.unlimited': 'Illimité',
  'links.error.title': 'Impossible de charger vos liens',
  'links.error.body': 'Vérifiez votre connexion, puis réessayez.',
  'links.retry': 'Réessayer',
  'links.offline.title': 'Hors ligne',
  'links.offline.body': 'Vos liens restent lisibles ; les modifier demande le réseau.',
  'links.detail.back': 'Revenir aux liens de partage',
  'links.detail.copy': 'Copier',
  'links.detail.copied': 'Copié',
  'links.detail.share': 'Partager',
  'links.detail.disable': 'Désactiver',
  'links.detail.activate': 'Activer',
  'links.detail.stats': 'Statistiques',
  'links.detail.stats.uses': 'Utilisations',
  'links.detail.stats.max': 'Maximum',
  'links.detail.info': 'Informations',
  'links.detail.identifier': 'Identifiant',
  'links.detail.createdAt': 'Créé le',
  'links.detail.expiresAt': 'Expire le',
  'links.detail.reason.closed': 'La conversation est fermée : ce lien ne permet plus d’entrer.',
  'links.detail.reason.expired': 'Ce lien a expiré.',
  'links.detail.reason.revoked': 'Vous avez désactivé ce lien.',
  'links.detail.refused.title': 'Lien introuvable',
  'links.detail.refused.body': 'Ce lien n’existe pas ou n’est pas l’un des vôtres.',
  'links.detail.loading': 'Chargement du lien',
  'links.announce.copied': 'Lien copié',
  'links.announce.copyFailed': 'Impossible de copier le lien',
  'links.announce.shareUnavailable': 'Le partage n’est pas disponible ici',
  'links.announce.disabled': 'Lien désactivé',
  'links.announce.activated': 'Lien activé',
  'links.announce.toggleFailed': 'Impossible de modifier ce lien',
  'links.announce.offline': 'Hors ligne : rien n’a été envoyé.',
  'links.create.title': 'Nouveau lien de partage',
  'links.create.section.conversation': 'Conversation',
  'links.create.choose': 'Choisir un groupe ou une communauté',
  'links.create.picker.title': 'Choisir une conversation',
  'links.create.picker.empty': 'Aucune conversation ne peut recevoir un lien pour l’instant.',
  'links.create.section.identity': 'Identité du lien',
  'links.create.name': 'Nom du lien',
  'links.create.name.placeholder': 'ex. : Partage Twitter',
  'links.create.description': 'Description (facultative)',
  'links.create.description.placeholder': 'ex. : Rejoins notre groupe…',
  'links.create.section.access': 'Accès invités',
  'links.create.section.access.subtitle': 'Ce que les visiteurs doivent fournir pour rejoindre',
  'links.create.access.account': 'Compte requis',
  'links.create.access.account.caption': 'Seuls les membres Meeshy peuvent rejoindre',
  'links.create.access.nickname': 'Pseudonyme requis',
  'links.create.access.nickname.caption': 'Le visiteur doit choisir un pseudo',
  'links.create.access.email': 'E-mail requis',
  'links.create.access.email.caption': 'Le visiteur doit fournir son e-mail',
  'links.create.access.birthday': 'Date de naissance requise',
  'links.create.access.birthday.caption': 'Permet le contrôle d’âge',
  'links.create.section.permissions': 'Permissions',
  'links.create.section.permissions.subtitle': 'Ce que les invités anonymes peuvent faire',
  'links.create.permission.messages': 'Envoyer des messages',
  'links.create.permission.messages.caption': 'Les invités peuvent écrire dans la conversation',
  'links.create.permission.images': 'Envoyer des images',
  'links.create.permission.images.caption': 'Les invités peuvent partager des photos',
  'links.create.permission.files': 'Envoyer des fichiers',
  'links.create.permission.files.caption': 'Les invités peuvent envoyer des documents',
  'links.create.permission.history': 'Voir l’historique',
  'links.create.permission.history.caption': 'Les invités voient les messages précédents',
  'links.create.section.limits': 'Limites',
  'links.create.section.limits.subtitle': 'Contrôlez l’audience et la durée de vie du lien',
  'links.create.limit.uses': 'Limiter les utilisations',
  'links.create.limit.max.one': '{count} utilisation au maximum',
  'links.create.limit.max.other': '{count} utilisations au maximum',
  'links.create.limit.count': 'Nombre d’utilisations',
  'links.create.limit.invalid': 'Choisissez un nombre entier entre 1 et {max}.',
  'links.create.expiration': 'Expiration',
  'links.create.expiration.never': 'Jamais',
  'links.create.expiration.h24': '24 heures',
  'links.create.expiration.d7': '7 jours',
  'links.create.expiration.d30': '30 jours',
  'links.create.expiration.m3': '3 mois',
  'links.create.button': 'Créer le lien de partage',
  'links.create.inprogress': 'Création en cours…',
  'links.create.error.conversation': 'Choisissez d’abord une conversation.',
  'links.create.error.offline': 'Hors ligne : le lien n’a pas été créé.',
  'links.create.error.refused': 'Vous ne pouvez pas créer de lien pour cette conversation.',
  'links.create.error.default': 'Le lien n’a pas pu être créé. Réessayez.',

  /* LES SCÈNES DU FIL (#6898) — carrousel, mosaïque et lecture d'une
     publication v:3. */
  'feed.scene.carousel.previous': 'Scène précédente',
  'feed.scene.carousel.next': 'Scène suivante',
  'feed.scene.mosaic.tile': 'Scène {index}',
  'feed.scene.mosaic.more': 'Scène {index}, et {count} de plus',
  'feed.scene.mosaic.video': 'Scène {index}, vidéo',
  'feed.scene.shared_by': 'Scène partagée par {author}',
  'feed.scene.open.fullscreen': 'Touche deux fois pour voir en plein écran',
  'feed.scene.open.post': 'Touche deux fois pour ouvrir la publication',
  'feed.scene.sound.muted': 'Son coupé',
  'feed.scene.count': '{count} scènes',
  'scene.fullscreen.play': 'Tout reprendre',
  'scene.fullscreen.pause': 'Tout mettre en pause',
  'scene.fullscreen.sound.on': 'Réactiver le son',
  'scene.fullscreen.sound.off': 'Couper le son',
  'scene.place.here': 'Ici',

  /* LE SON DE FOND DU LECTEUR DE STORY (T10, #6899) — bouton BASCULE dans la
     ligne auteur (rail droit hors tranche, #5817) : UN libellé constant et
     `aria-pressed`, jamais un libellé qui change avec l'état (« Son, non
     enfoncé » se lit comme un son coupé). */
  'story.sound.off': 'Muet',

  /* LE STUDIO DE STORY (#6900) — créer une story avec un fond, un son de
     fond et un texte, aperçu par le moteur partagé, publiée en CanvasV3
     comme iOS. */
  'story.studio.title': 'Nouvelle story',
  'story.studio.cancel': 'Annuler',
  'story.studio.publish': 'Publier',
  'story.studio.publishing': 'Publication…',
  'story.studio.publish.waiting': 'En attente du réseau…',
  'story.studio.offline': 'Hors ligne — la publication partira au retour du réseau.',
  'story.studio.stage': 'Aperçu de la story',
  'story.studio.background.add': 'Ajouter une photo ou une vidéo',
  'story.studio.background.label': 'Fond',
  'story.studio.background.remove': 'Retirer le fond',
  'story.studio.sound.add': 'Ajouter un son',
  'story.studio.sound.label': 'Son de fond',
  'story.studio.sound.remove': 'Retirer le son',
  'story.studio.sound.mute': 'Couper le son',
  'story.studio.sound.unmute': 'Écouter le son',
  'story.studio.upload.progress': 'Envoi… {percent} %',
  'story.studio.upload.ready': 'Prêt',
  'story.studio.upload.retry': 'Réessayer',
  'story.studio.text.label': 'Texte de la story',
  'story.studio.text.placeholder': 'Ajouter du texte',
  'story.studio.hint.duration': 'Une story reste visible vingt heures.',
  'story.studio.error.upload': 'Le fichier n’a pas pu être envoyé.',
  'story.studio.error.publish': 'La story n’a pas pu être publiée.',
  'story.studio.refusal.title': 'Un compte est nécessaire pour créer une story.',
  'story.studio.refusal.login': 'Se connecter',
  'story.studio.refusal.door.visual': 'Choisissez une image ou une vidéo.',
  'story.studio.refusal.door.sound': 'Choisissez un fichier audio.',
  'story.studio.failure.network': 'Réseau indisponible.',
  'story.studio.failure.timeout': 'La passerelle n’a pas répondu.',
  'story.studio.failure.session': 'Session expirée — reconnectez-vous.',
  'story.studio.failure.account': 'Un compte est nécessaire pour publier un média.',
  'story.studio.failure.forbidden': 'Action refusée pour ce compte.',
  'story.studio.failure.tooLarge': 'Fichier trop lourd.',
  'story.studio.failure.fileRefused': 'Fichier refusé : son type ne correspond pas à son contenu.',
  'story.studio.failure.rateLimited': 'Trop de publications d’un coup — réessayez dans un instant.',
  'story.studio.failure.refused': 'Publication refusée.',
  'story.studio.failure.unavailable': 'La passerelle est indisponible.',
  'story.studio.text.add': 'Ajouter un texte',
  'story.studio.text.remove': 'Retirer ce texte',
  'story.studio.object.text': 'Texte {index}',
  'story.studio.object.overlay': 'Calque',
  'story.studio.object.select': 'Sélectionner {name}',
  'story.studio.objects.label': 'Objets de la scène',
  'story.studio.overlay.add': 'Poser une image sur la scène',
  'story.studio.overlay.label': 'Calque',
  'story.studio.overlay.remove': 'Retirer le calque',
  'story.studio.caption.label': 'Légende de {media}',
  'story.studio.caption.placeholder': 'Ajouter une légende',
  'story.studio.sound.plane.label': 'Placement du son',
  'story.studio.sound.plane.background': 'En fond',
  'story.studio.sound.plane.foreground': 'Sur la scène',
  'story.studio.editor.label': 'Réglages de l’objet',
  'story.studio.editor.style': 'Police',
  'story.studio.editor.effect': 'Effet',
  'story.studio.editor.color': 'Couleur',
  'story.studio.editor.align': 'Alignement',
  'story.studio.editor.background': 'Fond du texte',
  'story.studio.editor.language': 'Langue du texte',
  'story.studio.editor.none': 'Aucun',
  'story.studio.editor.empty': 'Sélectionnez un objet pour le régler.',
  'story.studio.style.bold': 'Gras',
  'story.studio.style.neon': 'Néon',
  'story.studio.style.classic': 'Classique',
  'story.studio.style.italic': 'Italique',
  'story.studio.style.typewriter': 'Machine',
  'story.studio.style.handwriting': 'Manuscrit',
  'story.studio.style.calligraphy': 'Calligraphie',
  'story.studio.style.cartoon': 'Cartoon',
  'story.studio.style.futuristic': 'Futuriste',
  'story.studio.style.fantasy': 'Fantaisie',
  'story.studio.style.curve': 'Courbe',
  'story.studio.style.tag': 'Tag',
  'story.studio.style.retro': 'Rétro',
  'story.studio.style.elegant': 'Élégant',
  'story.studio.style.poster': 'Affiche',
  'story.studio.style.bubble': 'Bulle',
  'story.studio.style.note': 'Note',
  'story.studio.style.brush': 'Pinceau',
  'story.studio.effect.glow': 'Lueur',
  'story.studio.effect.neon': 'Néon',
  'story.studio.effect.outline': 'Contour',
  'story.studio.effect.shadow': 'Ombre',
  'story.studio.effect.longShadow': 'Ombre portée',
  'story.studio.effect.emboss': 'Relief',
  'story.studio.color.FFFFFF': 'Blanc',
  'story.studio.color.000000': 'Noir',
  'story.studio.color.FF2E63': 'Rose',
  'story.studio.color.08D9D6': 'Cyan',
  'story.studio.color.F8B500': 'Ambre',
  'story.studio.color.9B59B6': 'Violet',
  'story.studio.color.2ECC71': 'Vert',
  'story.studio.color.3498DB': 'Bleu',
  'story.studio.align.left': 'À gauche',
  'story.studio.align.center': 'Au centre',
  'story.studio.align.right': 'À droite',
  'story.studio.pose.label': 'Position et taille',
  'story.studio.pose.bigger': 'Agrandir',
  'story.studio.pose.smaller': 'Réduire',
  'story.studio.pose.rotateLeft': 'Tourner à gauche',
  'story.studio.pose.rotateRight': 'Tourner à droite',
  'story.studio.pose.reset': 'Recentrer',
  'story.studio.pose.handle': 'Déplacer {name} — flèches pour déplacer, + et − pour la taille, [ et ] pour tourner',
  'story.studio.pose.grip': 'Redimensionner et faire tourner {name}',

  /* LA BANNIÈRE DE MISE À JOUR (#6936) — les libellés du legacy
     (`updateAvailable`, `updateNow`, `wait`, dans les catalogues
     `apps/web/locales`), plus l'état du clic et le nom de la région annoncée,
     que le legacy n'avait pas. */
  'appUpdate.available': 'Une nouvelle version de Meeshy est disponible !',
  'appUpdate.hint': 'Rechargez pour avoir les dernières nouveautés.',
  'appUpdate.action': 'Mettre à jour',
  'appUpdate.dismiss': 'Attendre',
  'appUpdate.applying': 'Mise à jour…',
  'appUpdate.region': 'Mise à jour de l’application',

  /* L'ESPACE D'ADMINISTRATION (#6432) — SEUL `admin.title` reste ici : la
     rangée des Réglages et le barreau du menu flottant (#6458) le lisent
     SANS jamais entrer dans `/adm`, donc sans jamais charger le catalogue
     d'administration. Les 83 autres clés (`admin.nav.*`, `admin.users.*`,
     `admin.user.*`, `admin.edit.*`, `admin.password.*`, `admin.ban.*`,
     `admin.media.*`, `admin.conv.*`, `admin.counters.*`, `admin.sections.*`,
     `admin.denied.*`, `admin.role`) ont déménagé dans
     `catalog-admin-fr.ts` (#6871, #6834) : elles ne pesaient que pour un
     lecteur qui n'ouvre jamais l'administration. */
  /* LE RAIL D'ACTIONS DU LECTEUR DE STORIES et LE FIL DE COMMENTAIRES
     d'une publication — les libellés reprennent ceux d'iOS
     (`story.viewer.action.*`, `Localizable.xcstrings`) ; `comments.*`
     est propre au web, qui rend la liste là où iOS pose une couche. */
  'story.action.rail': 'Actions de la story',
  'story.action.react': 'Réagir',
  'story.action.reply': 'Répondre',
  'story.action.forward': 'Envoyer',
  'story.action.repost': 'Republier',
  'story.action.views': 'Vues',
  'story.action.share': 'Partager',
  'story.action.save': 'Enregistrer',
  'story.action.comments': 'Commentaires',
  'story.action.translations': 'Traductions',
  /* LA PASTILLE DU PRISME (#7141) — trois SUJETS, parce que « Afficher le
     message… » sur un commentaire serait traduit et faux. Neuf clés plates
     plutôt que trois à paramètre : l'accord (« traduit » / « traduite ») ne
     se paramètre pas d'une langue à l'autre. */
  'prism.translated.message': 'Message traduit',
  'prism.translated.comment': 'Commentaire traduit',
  'prism.translated.post': 'Publication traduite',
  'prism.original.show.message': 'Afficher le message dans sa langue d’origine',
  'prism.original.show.comment': 'Afficher le commentaire dans sa langue d’origine',
  'prism.original.show.post': 'Afficher la publication dans sa langue d’origine',
  'prism.original.hide.message': 'Masquer le message dans sa langue d’origine',
  'prism.original.hide.comment': 'Masquer le commentaire dans sa langue d’origine',
  'prism.original.hide.post': 'Masquer la publication dans sa langue d’origine',

  'comments.title': 'Commentaires',
  'comments.close': 'Fermer les commentaires',
  'comments.loading': 'Chargement des commentaires',
  'comments.empty': 'Aucun commentaire',
  'comments.empty.hint': 'Soyez la première personne à en écrire un.',
  'comments.error': 'Impossible de charger les commentaires',
  'comments.error.hint': 'Réessayez dans un instant.',
  'comments.retry': 'Réessayer',
  'comments.more': 'Voir plus de commentaires',
  'comments.offline': 'Hors ligne — seuls les commentaires déjà lus s’affichent.',
  'comments.placeholder': 'Écrire un commentaire…',
  'comments.send': 'Envoyer le commentaire',
  'comments.row.pending': 'Envoi en cours',
  'comments.signin': 'Connectez-vous pour commenter.',
  'comment.send.error': 'Le commentaire n’a pas pu être publié.',
  'comment.send.pending': 'Commentaire non confirmé — hors ligne',
  'comment.send.empty': 'Écrivez quelque chose avant d’envoyer.',
  'comments.action.like': 'J’aime',
  'comments.action.unlike': 'Je n’aime plus',
  'comments.action.edit': 'Modifier',
  'comments.action.delete': 'Supprimer',
  'comments.action.delete.confirm': 'Confirmer',
  'comments.edit.label': 'Modifier le commentaire',
  'comments.edit.save': 'Enregistrer',
  'comments.edit.cancel': 'Annuler',
  'comment.like.error': 'Le « j’aime » n’a pas été enregistré.',
  'comment.edit.error': 'La modification n’a pas été enregistrée.',
  'comment.delete.error': 'Le commentaire n’a pas pu être supprimé.',
  'comment.gesture.pending': 'Geste non confirmé — hors ligne',
  'comment.gesture.unconfirmed': 'Geste non confirmé — la passerelle n’a pas répondu.',
  'comment.refused.session': 'Session expirée — reconnectez-vous.',
  'comment.refused.right': 'Ce geste ne vous est pas ouvert.',
  'comment.like.limit': 'Cinq réactions au maximum par personne.',
  'feed.action.comment': 'Commenter',

  'admin.title': 'Administration',

  'thread.unread-separator.one': '{count} message non lu',
  'thread.unread-separator.other': '{count} messages non lus',
  'message-detail.info.title': 'Infos du message',
  'message-detail.received-by': 'Reçu par',
  'message-detail.read-by': 'Vu par',
  'message-detail.not-yet': 'Pas encore',
  'message-detail.received-by.empty': 'Aucune confirmation de distribution',
  'message-detail.read-by.empty': 'Personne n’a encore lu ce message',
  'message-detail.not-yet.empty': 'Tout le monde a reçu le message',
  'message-detail.open': 'Voir les détails du message',
  'message-detail.attachment.opens.one': '{count} ouverture',
  'message-detail.attachment.opens.other': '{count} ouvertures',
  'message-detail.attachment.downloads.one': '{count} téléchargement',
  'message-detail.attachment.downloads.other': '{count} téléchargements',
  'message-detail.attachment.listened-until': 'Écouté jusqu’à {time}',
  'message-detail.attachment.watched-until': 'Regardé jusqu’à {time}',
  'message-detail.attachment.complete': 'Terminé',
  'message-detail.attachment.listen.empty': 'Pas encore écouté',
  'message-detail.attachment.watch.empty': 'Pas encore regardé',
  'message-detail.loading': 'Chargement…',
  'message-detail.load-error': 'Impossible de charger ces informations',
  'message-detail.retry': 'Réessayer',

  /* `/download` — L'INVITATION REÇUE PAR SMS (#7297). Ce que la page PROMET
     est ce que le produit tient : la fiche App Store, qui existe, et le web,
     que meeshy.me sert aujourd'hui. Aucune mention du Play Store tant que la
     coque Android n'est pas publiée. */
  'download.title': 'Téléchargez Meeshy',
  'download.body': 'Écrivez dans votre langue, lisez dans la vôtre : Meeshy traduit chaque message au passage.',
  'download.appStore': 'Télécharger dans l’App Store',
  'download.web': 'Ouvrir Meeshy dans le navigateur',
  'download.otherPlatforms': 'Sur Android et sur ordinateur, Meeshy s’utilise directement dans le navigateur.',

  /* LES SOURCES DU COMPOSEUR (#7280) — le panneau de pièces jointes du fil.
     Les libellés et les gestes annoncés reprennent le catalogue d'iOS
     (`composer.attach.*`, `apps/ios/Meeshy/Localizable.xcstrings`), qui fait
     foi : même mot, même ordre, même icône (dimension 6). Les trois premiers
     (Photos / Fichier / Vocal) vivaient EN DUR dans `composer-tray.tsx` — ils
     sont remontés ici par le lot qui en ajoute quatre, plutôt que d'y répandre
     la dette (#6310). */
  'composer.attach.group': 'Types de pièces jointes',
  'composer.attach.handle': 'Poignée du panneau',
  'composer.attach.photo': 'Photos',
  'composer.attach.photo.action': 'Choisir des photos',
  'composer.attach.camera': 'Caméra',
  'composer.attach.camera.action': 'Prendre une photo',
  'composer.attach.file': 'Fichier',
  'composer.attach.file.action': 'Choisir un fichier',
  'composer.attach.location': 'Position',
  'composer.attach.location.action': 'Partager ma position',
  'composer.attach.voice': 'Vocal',
  'composer.attach.voice.action': 'Enregistrer un message vocal',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Insérer un emoji',
  'composer.emoji.title': 'Insérer un emoji',
  'composer.location.locating': 'Recherche de votre position…',
  'composer.location.denied': 'Position refusée — autorisez-la dans les réglages',
  'composer.location.unavailable': 'Position indisponible sur ce navigateur',
  'composer.location.failed': 'Position introuvable — réessayez',
  'composer.location.chip': 'LIEU',
  'composer.location.unknown': 'Lieu inconnu',
  'composer.location.remove': 'Retirer la position',

  /* LA BASCULE « VUE UNIQUE » DE LA RANGÉE HAUTE (#7354, V6) — même famille
     que `composer.attach.*` ci-dessus. Libellés repris du catalogue iOS
     (`composer.viewonce.activate`/`.active`/`.label`,
     `+Protections.swift:233-235`), la référence de cette bascule. */
  'composer.viewOnce.activate': 'Activer le mode vue unique',
  'composer.viewOnce.active': 'Mode vue unique actif',
  'composer.viewOnce.label': 'Vue unique',

  /* LA BULLE D'UN LIEU (#7328) — valeurs reprises du catalogue iOS
     (`MeeshyUI/Resources/Localizable.xcstrings` : `location.shared`,
     `location.fullscreen.openInMaps`, `location.a11y.label`), la référence de
     cette bulle. `{place}` reçoit le nom du lieu, ou `message.location.shared`
     quand il n'y en a pas — le cas NOMINAL du web, sans géocodeur inverse. */
  'message.location.shared': 'Position partagée',
  'message.location.open': 'Ouvrir dans Plans',
  'message.location.a11y': 'Position : {place}',

  /* LES LIBELLÉS D'ÉTAT DU FIL (#7337) — le transfert, l'échec d'envoi, les
     tombstones et les substituts de pièce protégée. Ils étaient EN DUR, en
     français, sur des surfaces servies en SEPT langues : un lecteur anglophone,
     arabophone ou lusophone lisait du français sur les états les plus
     anxiogènes de l'application. D-13 ne les couvre pas — elle EXCLUT
     explicitement « les textes affichés à l'utilisateur, qui relèvent de
     l'internationalisation, pas du nommage ».

     Valeurs reprises du catalogue iOS là où il en a une : `bubble.meta.forwarded`,
     `bubble.meta.forwarded.fromGroup`, `bubble.meta.forwarded.from`,
     `bubble.system.deleted`, `bubble.system.burned`, `bubble.system.burned.a11y`,
     `bubble.media.masked`, `bubble.media.viewOnce`, `common.retry`,
     `sync.pill.failed.message` (l'annonce au lecteur d'écran). */
  'message.forwarded': 'Transféré',
  'message.forwarded.fromGroup': 'Transféré depuis {name}',
  'message.forwarded.fromPerson': 'Transféré de {name}',
  'message.send.failed': 'Non envoyé',
  'message.send.failed.reason': 'Non envoyé — {reason}',
  'message.send.retry': 'Réessayer',
  'announce.messageNotSent': 'Message non envoyé',
  'announce.messageNotSent.reason': 'Message non envoyé — {reason}',
  'message.deleted': 'Message supprimé',
  'message.burned': 'Vu et supprimé',
  'message.burned.a11y': 'Message vu et supprimé',
  'message.expired.a11y': 'Message éphémère expiré',
  'message.withheld': 'Contenu retenu',
  'message.withheld.a11y': 'Contenu retenu : ce message existe et ne se montre pas',
  'message.veiled': 'Contenu masqué',
  'message.veiled.hint': 'Toucher pour révéler le contenu',
  'message.veiled.viewOnce': 'Voir une fois',
  'message.veiled.error': 'Révélation impossible pour l’instant',
  'message.ephemeral.a11y': 'Message éphémère, disparaît dans {remaining}',
  'message.ephemeral.awaiting': 'En attente de réception',
  'message.ephemeral.awaiting.a11y': 'Message éphémère de {duration}, en attente de réception',
  'message.viewOnce.a11y': 'Vue unique, ce message ne s’affiche qu’une fois',
  'attachment.protected.image': 'Photo protégée',
  'attachment.protected.video': 'Vidéo protégée',
  'attachment.protected.audio': 'Vocal protégé',
  'attachment.protected.file': 'Pièce protégée',

} as const;

export default fr;
