import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const de = {
  'announce.messageSent': 'Nachricht gesendet',
  'announce.messageCopied': 'Nachricht kopiert',
  'announce.messagesCopied': 'Nachrichten kopiert',
  'announce.messageProtected': 'Geschützte Nachricht',
  'announce.selectionCap': 'Maximal {count} Nachrichten',
  'announce.nothingToCopy': 'Nichts zu kopieren',

  'message.author.self': 'Du',
  'message.excerpt.protected': 'geschützter Inhalt',
  'a11y.message.menu.subject': 'Aktionen für die Nachricht von {author}: {excerpt}',

  'typing.named': '{name} schreibt',
  'typing.double': '{first} und {second} schreiben',
  'typing.several': 'Mehrere Personen schreiben',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'Meine Links',
  'root.menu.notifications': 'Mitteilungen',
  'root.menu.calls': 'Anrufe',
  'root.menu.discover': 'Entdecken',
  'root.menu.communities': 'Communitys',
  'root.menu.settings': 'Einstellungen',
  'root.menu.profile': 'Profil',
  'a11y.floating.menu': 'Menü',
  'a11y.floating.menu.ladder': 'Meeshy-Navigation',
  'a11y.floating.menu.unread.one': 'Menü, {count} ungelesene Mitteilung',
  'a11y.floating.menu.unread.other': 'Menü, {count} ungelesene Mitteilungen',
  'a11y.floating.rung.notifications.unread.one': 'Mitteilungen, {count} ungelesen',
  'a11y.floating.rung.notifications.unread.other': 'Mitteilungen, {count} ungelesen',

  'notifications.category.all': 'Alle',
  'notifications.category.unread': 'Ungelesen',
  'notifications.category.messages': 'Nachrichten',
  'notifications.category.reactions': 'Reaktionen',
  'notifications.category.mentions': 'Erwähnungen',
  'notifications.category.social': 'Soziales',
  'notifications.category.contacts': 'Kontakte',
  'notifications.category.groups': 'Gruppen',
  'notifications.category.calls': 'Anrufe',
  'notifications.category.translations': 'Übersetzungen',
  'notifications.category.system': 'System',
  'notifications.categories': 'Mitteilungskategorien',
  'notifications.markAllRead': 'Alle gelesen',
  'notifications.unreadCount.one': '{count} ungelesen',
  'notifications.unreadCount.other': '{count} ungelesen',
  'notifications.unread': 'Ungelesen',
  'notifications.empty.all': 'Keine Mitteilungen',
  'notifications.empty.unread': 'Keine ungelesenen Mitteilungen',
  'notifications.empty.category': 'Keine Mitteilungen in „{category}“',
  'notifications.empty.subtitle': 'Deine Mitteilungen erscheinen hier',
  'notifications.loading': 'Mitteilungen werden geladen',
  'notifications.error.title': 'Mitteilungen konnten nicht geladen werden',
  'notifications.error.body': 'Versuche es gleich noch einmal.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Deine Mitteilungen erscheinen, sobald du wieder online bist.',
  'notifications.retry': 'Erneut versuchen',
  'notifications.allLoaded': 'Alle Mitteilungen sind geladen',
  'notifications.actions': 'Aktionen für die Mitteilung',
  'notifications.action.markRead': 'Als gelesen markieren',
  'notifications.action.delete': 'Löschen',
  'notifications.failure': 'Das hat nicht geklappt. Versuche es erneut.',

  'pending.back': 'Zurück zu den Unterhaltungen',
  'pending.comingSoon': 'Dieser Bildschirm kommt bald.',
  'pending.feed.promise': 'Die Beiträge der Menschen, denen du folgst.',
  'pending.links.promise': 'Die in deinen Unterhaltungen geteilten Links werden hier gesammelt.',
  'pending.notifications.promise': 'Was auf dich wartet — Erwähnungen, Antworten, Einladungen — liest du hier.',
  'pending.calls.promise': 'Dein Anrufverlauf und die Möglichkeit, jemanden anzurufen.',
  'pending.discover.promise': 'Menschen zum Kennenlernen, ausgewählt nach euren Gemeinsamkeiten.',
  'pending.communities.promise': 'Die Communitys, zu denen du gehörst, und die, die zu dir passen.',
  'pending.settings.promise': 'Deine Sprachen, deine Privatsphäre, deine Mitteilungen.',
  'pending.profile.promise': 'Deine Meeshy-Identität — Name, Foto, Sprachen und was andere davon sehen.',

  'profile.title': 'Profil',
  'profile.edit': 'Bearbeiten',
  'profile.cancel': 'Abbrechen',
  'profile.save': 'Speichern',
  'profile.saving': 'Wird gespeichert…',
  'profile.saved': 'Profil gespeichert',
  'profile.save.error': 'Fehler beim Speichern',
  'profile.save.offline': 'Offline — die Änderung wurde nicht gesendet.',
  'profile.save.invalid': 'Prüfe das Feld „{field}“.',
  'profile.loading': 'Profil wird geladen',
  'profile.error.title': 'Dein Profil konnte nicht geladen werden',
  'profile.error.body': 'Versuche es gleich noch einmal.',
  'profile.retry': 'Erneut versuchen',
  'profile.offline.title': 'Offline',
  'profile.offline.body': 'Dein Profil bleibt lesbar; Bearbeiten ist wieder möglich, sobald du online bist.',
  'profile.avatar.edit': 'Profilfoto bearbeiten',
  'profile.avatar.updated': 'Profilfoto aktualisiert',
  'profile.avatar.error': 'Profilfoto konnte nicht aktualisiert werden',
  'profile.banner.edit': 'Banner bearbeiten',
  'profile.banner.updated': 'Banner aktualisiert',
  'profile.banner.error': 'Banner konnte nicht aktualisiert werden',
  'profile.image.uploading': 'Wird hochgeladen',
  'profile.image.cancel': 'Hochladen abbrechen',
  'profile.image.cancelled': 'Hochladen abgebrochen',
  'profile.image.unreadable': 'Dieses Bild kann nicht gelesen werden.',
  'profile.section.identity': 'IDENTITÄT',
  'profile.section.contact': 'KONTAKT',
  'profile.section.languages': 'SPRACHEN',
  'profile.section.stats': 'STATISTIKEN',
  'profile.section.requests': 'ANFRAGEN',
  'profile.section.member_since': 'MITGLIED SEIT',
  'profile.first_name': 'Vorname',
  'profile.last_name': 'Nachname',
  'profile.username': 'Benutzername',
  'profile.display_name': 'Anzeigename',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Erzähl etwas über dich...',
  'profile.email': 'E-Mail',
  'profile.phone': 'Telefon',
  'profile.verified': 'Verifiziert',
  'profile.not_verified': 'Nicht verifiziert',
  'profile.language.primary': 'Hauptsprache',
  'profile.language.primary.subtitle': 'Inhalte werden in diese Sprache übersetzt',
  'profile.language.regional': 'Regionalsprache',
  'profile.language.custom': 'Benutzerdefinierte Sprache',
  'profile.language.none': 'Keine',
  'profile.language.choose': 'Auswählen',
  'profile.language.clear.regional': 'Regionalsprache entfernen',
  'profile.language.clear.custom': 'Benutzerdefinierte Sprache entfernen',
  'profile.stats.messages': 'Nachrichten',
  'profile.stats.translations': 'Übersetzungen',
  'profile.stats.languages': 'Sprachen',
  'profile.stats.days': 'Tage',
  'profile.stats.loading': 'Statistiken werden geladen',
  'profile.progression.title': 'Fortschritt',
  'profile.progression.subtitle': 'Abzeichen, Level und Serie',
  'profile.friend_requests': 'Freundschaftsanfragen',
  'profile.friend_requests.count.one': '{count} offene Anfrage',
  'profile.friend_requests.count.other': '{count} offene Anfragen',
} satisfies InterfaceCatalog;

export default de;
