import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const it = {
  'announce.messageSent': 'Messaggio inviato',
  'announce.messageCopied': 'Messaggio copiato',
  'announce.messagesCopied': 'Messaggi copiati',
  'announce.messageProtected': 'Messaggio protetto',
  'announce.selectionCap': 'Massimo {count} messaggi',
  'announce.nothingToCopy': 'Niente da copiare',

  'message.author.self': 'Tu',
  'message.excerpt.protected': 'contenuto protetto',
  'a11y.message.menu.subject': 'Azioni del messaggio di {author}: {excerpt}',

  'typing.named': '{name} sta scrivendo',
  'typing.double': '{first} e {second} stanno scrivendo',
  'typing.several': 'Più persone stanno scrivendo',

  'feed.header.reels': 'Avvia i Reel',
  'reels.title': 'Reel',
  'reels.back': 'Indietro',
  'reels.open': 'Guarda il reel di {author}',
  'reels.item': 'Reel di {author}, {index} di {count}',
  'reels.loading': 'Caricamento dei reel',
  'reels.empty': 'Nessun reel per ora',
  'reels.empty.hint': 'I reel dei tuoi contatti appariranno qui.',
  'reels.error': 'Impossibile caricare i reel',
  'reels.error.hint': 'Riprova tra un momento.',
  'reels.retry': 'Riprova',
  'reels.offline': 'Offline',
  'reels.offline.cold': 'I reel si caricheranno al ritorno della connessione.',
  'reels.action.like': 'Mi piace',
  'reels.action.bookmark': 'Salva',
  'reels.action.share': 'Condividi',
  'reels.sound.on': 'Attiva l’audio',
  'reels.sound.off': 'Disattiva l’audio',
  'reels.play': 'Riproduci il reel',
  'reels.pause': 'Metti in pausa il reel',
  'reels.media.error': 'Riproduzione impossibile — Riprova',
  'reels.image': 'Immagine {index} di {count}',

  'stories.title': 'Storie',
  'stories.loading': 'Caricamento delle storie…',
  'stories.error': 'Non è stato possibile caricare le storie.',
  'stories.empty.title': 'Nessuna storia per ora',
  'stories.empty.subtitle': 'Le storie dei tuoi contatti appariranno qui per ventiquattro ore.',
  'stories.create': 'Crea una storia',
  'stories.count.one': '{count} storia',
  'stories.count.other': '{count} storie',
  'stories.mine': 'La tua storia',

  'feed.post.action.like': 'Mi piace',
  'feed.post.action.comment': 'Commenta',
  'feed.post.action.repost': 'Ripubblica',
  'feed.post.action.bookmark': 'Salva',
  'feed.post.action.share': 'Condividi',
  'feed.post.media.video': 'Video',
  'feed.post.media.audio': 'Audio',
  'feed.post.media.previous': 'Media precedente',
  'feed.post.media.next': 'Media successivo',
  'feed.post.media.mosaic': 'Mosaico di {count} media',
  'feed.post.see_more': 'mostra altro',
  'feed.post.see_less': 'mostra meno',
  'feed.post.reel.chip': 'Reel',
  'feed.post.reel.of': 'Reel di {author}',
  'feed.error.title': 'Impossibile caricare il feed',
  'feed.error.body': 'Riprova tra un momento.',
  'feed.offline.title': 'Offline',
  'feed.offline.body': 'Il feed apparirà quando tornerai online.',
  'feed.retry': 'Riprova',
  'feed.empty.title': 'Nessuna pubblicazione per ora',
  'feed.empty.subtitle': 'Le pubblicazioni dei tuoi contatti appariranno qui.',
  'feed.loading': 'Caricamento del feed',
  'feed.allLoaded': 'Tutte le pubblicazioni sono state caricate',
  'feed.like.error': 'Errore nel mettere Mi piace',
  'post.bookmark.error': 'Salvataggio non riuscito',
  'feed.gesture.pending': 'Azione non confermata — offline',
  'feed.share.error': 'Errore nella condivisione del post',
  'feed.share.copied': 'Link copiato — non resta che incollarlo.',
  'feed.share.text': 'Una pubblicazione su Meeshy',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'I miei link',
  'root.menu.notifications': 'Notifiche',
  'root.menu.calls': 'Chiamate',
  'root.menu.discover': 'Scopri',
  'root.menu.communities': 'Community',
  'root.menu.settings': 'Impostazioni',
  'root.menu.profile': 'Profilo',
  'root.menu.conversations': 'Conversazioni',
  'a11y.floating.feed.hint': 'Tieni premuto per avviare i Reel',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Navigazione Meeshy',
  'a11y.floating.menu.unread.one': 'Menu, {count} notifica non letta',
  'a11y.floating.menu.unread.other': 'Menu, {count} notifiche non lette',
  'a11y.floating.rung.notifications.unread.one': 'Notifiche, {count} non letta',
  'a11y.floating.rung.notifications.unread.other': 'Notifiche, {count} non lette',

  'notifications.category.all': 'Tutte',
  'notifications.category.unread': 'Non lette',
  'notifications.category.messages': 'Messaggi',
  'notifications.category.reactions': 'Reazioni',
  'notifications.category.mentions': 'Menzioni',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contatti',
  'notifications.category.groups': 'Gruppi',
  'notifications.category.calls': 'Chiamate',
  'notifications.category.translations': 'Traduzioni',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorie di notifiche',
  'notifications.markAllRead': 'Segna tutte come lette',
  'notifications.unreadCount.one': '{count} non letta',
  'notifications.unreadCount.other': '{count} non lette',
  'notifications.unread': 'Non letta',
  'notifications.empty.all': 'Nessuna notifica',
  'notifications.empty.unread': 'Nessuna notifica non letta',
  'notifications.empty.category': 'Nessuna notifica in «{category}»',
  'notifications.empty.subtitle': 'Le tue notifiche appariranno qui',
  'notifications.loading': 'Caricamento delle notifiche',
  'notifications.error.title': 'Impossibile caricare le notifiche',
  'notifications.error.body': 'Riprova tra un momento.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Le tue notifiche appariranno quando tornerai online.',
  'notifications.retry': 'Riprova',
  'notifications.allLoaded': 'Tutte le notifiche sono state caricate',
  'notifications.actions': 'Azioni della notifica',
  'notifications.action.markRead': 'Segna come letta',
  'notifications.action.delete': 'Elimina',
  'notifications.failure': 'L’azione non è andata a buon fine. Riprova.',

  'notFound.title': 'Questo indirizzo non esiste.',

  'pending.back': 'Torna alle conversazioni',

  'linkPage.home': 'Torna a Meeshy',
  'linkPage.retry': 'Riprova',
  'linkPage.settings': 'Apri le impostazioni',
  'linkPage.signIn': 'Accedi',
  'linkPage.offline.title': 'Offline',
  'linkPage.offline.body': 'Riconnettiti a Internet, poi riprova.',
  'linkPage.unavailable.title': 'Meeshy non risponde',
  'linkPage.unavailable.body': 'Il servizio è momentaneamente non disponibile. Riprova tra qualche istante.',
  'linkPage.rateLimited': 'Troppi tentativi. Attendi un momento prima di riprovare.',
  'linkPage.signedOut.title': 'Accedi per continuare',
  'linkPage.signedOut.body': 'Questo link agisce sul tuo account. Accedi, poi riaprilo dall’e-mail.',
  'linkPage.expired': 'Questo link è scaduto. Ripeti la richiesta dalle impostazioni.',
  'trackingLink.opening': 'Apertura del link…',
  'trackingLink.dead.title': 'Questo link non è più disponibile',
  'trackingLink.dead.body': 'È scaduto, è stato disattivato o non è mai esistito.',
  'accountDeletion.incomplete.title': 'Link incompleto',
  'accountDeletion.incomplete.body': 'A questo link mancano le informazioni necessarie. Accedi per richiedere l’eliminazione del tuo account.',
  'accountDeletion.confirm.title': 'Conferma l’eliminazione del tuo account',
  'accountDeletion.confirm.body':
    'Il tuo account sarà disattivato al termine di un periodo di tolleranza di 30 giorni. Fino ad allora, il link «Annulla» dell’e-mail ti permette di tornare indietro.',
  'accountDeletion.confirm.action': 'Conferma l’eliminazione',
  'accountDeletion.cancel.title': 'Annulla l’eliminazione del tuo account',
  'accountDeletion.cancel.body': 'Il tuo account resta attivo e la richiesta di eliminazione viene abbandonata. Non si perde nulla.',
  'accountDeletion.cancel.action': 'Annulla l’eliminazione',
  'accountDeletion.purge.title': 'Elimina il tuo account ora',
  'accountDeletion.purge.body': 'Il tuo account sarà disattivato subito e tutte le tue sessioni verranno chiuse. L’operazione è definitiva.',
  'accountDeletion.purge.action': 'Elimina ora',
  'accountDeletion.dismiss': 'Non fare nulla',
  'accountDeletion.working': 'Un istante…',
  'accountDeletion.done.title': 'Fatto',
  'accountDeletion.done.confirmed': 'La tua richiesta è confermata: il tuo account sarà disattivato il {date}. Puoi annullare fino ad allora.',
  'accountDeletion.done.cancelled': 'Il tuo account resta attivo: la richiesta di eliminazione è stata abbandonata.',
  'accountDeletion.done.completed': 'Il tuo account è disattivato e tutte le tue sessioni sono state chiuse.',
  'accountDeletion.done.purged': 'I tuoi dati sono stati cancellati.',
  'accountDeletion.closed.title': 'Questo link non è più valido',
  'accountDeletion.invalid': 'Questo link non è valido o è già stato usato.',
  'accountDeletion.request.title': 'Elimina il tuo account',
  'accountDeletion.request.body':
    'Le tue conversazioni, i messaggi, i contenuti multimediali, i contatti e le preferenze saranno eliminati. Un’e-mail ti chiederà di confermare, poi un periodo di tolleranza di 30 giorni ti permetterà di tornare indietro.',
  'accountDeletion.request.phrase': 'Digita {phrase} per confermare',
  'accountDeletion.request.password': 'Password attuale',
  'accountDeletion.request.action': 'Richiedi l’eliminazione',
  'accountDeletion.request.sent.title': 'Ti abbiamo inviato un’e-mail di conferma',
  'accountDeletion.request.sent.body': 'Aprila per confermare l’eliminazione del tuo account.',
  'accountDeletion.request.wrongPassword': 'Password errata.',
  'accountDeletion.request.alreadyPending': 'C’è già una richiesta in corso. Apri l’e-mail ricevuta per confermarla o annullarla.',
  'accountDeletion.request.noEmail': 'Aggiungi e verifica un indirizzo e-mail prima di richiedere l’eliminazione.',
  'emailChange.verifying': 'Conferma del nuovo indirizzo…',
  'emailChange.done.title': 'Indirizzo e-mail modificato',
  'emailChange.done.body': 'D’ora in poi accedi con {email}.',
  'emailChange.done.generic': 'Il tuo nuovo indirizzo e-mail è confermato.',
  'emailChange.failed.title': 'Indirizzo non modificato',
  'emailChange.missing': 'Questo link non contiene un codice di conferma. Apri quello dell’e-mail più recente.',
  'emailChange.invalid': 'Questo link non corrisponde a nessuna modifica in sospeso su questo account, oppure è già stato usato.',
  'emailChange.taken': 'Questo indirizzo è ora usato da un altro account.',
  'emailNotifications.title': 'E-mail di Meeshy',
  'emailNotifications.loading': 'Lettura della tua preferenza…',
  'emailNotifications.on': 'Ricevi via e-mail annunci, riepiloghi e notifiche di Meeshy.',
  'emailNotifications.off': 'Non ricevi più via e-mail annunci, riepiloghi né notifiche di Meeshy.',
  'emailNotifications.security': 'Le e-mail di sicurezza del tuo account continuano ad arrivare.',
  'emailNotifications.unsubscribe': 'Non ricevere più queste e-mail',
  'emailNotifications.resubscribe': 'Ricevi di nuovo queste e-mail',
  'emailNotifications.failed': 'La modifica non è andata a buon fine. Riprova.',

  'dataExport.title': 'Esporta i miei dati',
  'dataExport.info.body': 'In conformità al GDPR, ricevi un file con il tuo profilo, i tuoi messaggi, i tuoi contatti e le tue pubblicazioni.',
  'dataExport.action.start': 'Esporta i miei dati',
  'dataExport.action.exporting': 'Esportazione in corso…',
  'dataExport.action.again': 'Esporta di nuovo',
  'dataExport.done.title': 'Esportazione completata',
  'dataExport.done.body': 'Il file è stato scaricato su questo dispositivo.',

  'profile.title': 'Profilo',
  'profile.edit': 'Modifica',
  'profile.cancel': 'Annulla',
  'profile.save': 'Salva',
  'profile.saving': 'Salvataggio…',
  'profile.saved': 'Profilo salvato',
  'profile.save.error': 'Errore durante il salvataggio',
  'profile.save.offline': 'Offline — la modifica non è stata inviata.',
  'profile.save.invalid': 'Controlla il campo «{field}».',
  'profile.loading': 'Caricamento del profilo',
  'profile.error.title': 'Impossibile caricare il tuo profilo',
  'profile.error.body': 'Riprova tra un momento.',
  'profile.retry': 'Riprova',
  'profile.offline.title': 'Offline',
  'profile.offline.body': 'Il tuo profilo resta leggibile; la modifica torna con la rete.',
  'profile.avatar.edit': 'Modifica la foto del profilo',
  'profile.avatar.updated': 'Foto del profilo aggiornata',
  'profile.avatar.error': 'Impossibile aggiornare la foto del profilo',
  'profile.banner.edit': 'Modifica il banner',
  'profile.banner.updated': 'Banner aggiornato',
  'profile.banner.error': 'Impossibile aggiornare il banner',
  'profile.image.uploading': 'Invio in corso',
  'profile.image.cancel': 'Annulla l’invio',
  'profile.image.cancelled': 'Invio annullato',
  'profile.image.unreadable': 'Questa immagine non può essere letta.',
  'profile.section.identity': 'IDENTITÀ',
  'profile.section.contact': 'CONTATTO',
  'profile.section.languages': 'LINGUE',
  'profile.section.stats': 'STATISTICHE',
  'profile.section.requests': 'RICHIESTE',
  'profile.section.member_since': 'MEMBRO DAL',
  'profile.first_name': 'Nome',
  'profile.last_name': 'Cognome',
  'profile.username': 'Nome utente',
  'profile.display_name': 'Nome visualizzato',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Raccontaci di te...',
  'profile.email': 'Email',
  'profile.phone': 'Telefono',
  'profile.verified': 'Verificato',
  'profile.not_verified': 'Non verificato',
  'profile.language.primary': 'Lingua principale',
  'profile.language.primary.subtitle': 'I contenuti saranno tradotti in questa lingua',
  'profile.language.regional': 'Lingua regionale',
  'profile.language.custom': 'Lingua personalizzata',
  'profile.language.none': 'Nessuna',
  'profile.language.choose': 'Scegli',
  'profile.language.clear.regional': 'Rimuovi la lingua regionale',
  'profile.language.clear.custom': 'Rimuovi la lingua personalizzata',

  'languageSheet.title.read': 'Lingua di lettura',
  'languageSheet.title.write': 'Lingua di scrittura',
  'languageSheet.search': 'Cerca una lingua',
  'languageSheet.empty': 'Nessuna lingua corrisponde a «{search}».',

  'profile.stats.messages': 'Messaggi',
  'profile.stats.translations': 'Traduzioni',
  'profile.stats.languages': 'Lingue',
  'profile.stats.days': 'Giorni',
  'profile.stats.loading': 'Caricamento delle statistiche',
  'profile.progression.title': 'Progressi',
  'profile.progression.subtitle': 'Badge, livello e serie',
  'profile.friend_requests': 'Richieste di amicizia',
  'profile.friend_requests.count.one': '{count} richiesta in attesa',
  'profile.friend_requests.count.other': '{count} richieste in attesa',

  'settings.title': 'Impostazioni',
  'settings.my_profile': 'Il mio profilo',
  'settings.section.account': 'Account',
  'settings.security.title': 'Sicurezza',
  'settings.delete_account': "Elimina l'account",
  'settings.privacy.title': 'Privacy',
  'settings.privacy.online_status': 'Stato online',
  'settings.privacy.online_status.info':
    'Il punto verde sul tuo avatar indica che sei attivo. Disattivato, nessuno lo vede, ma scrivere in una conversazione rivela comunque la tua presenza.',
  'settings.privacy.last_seen': 'Ultimo accesso',
  'settings.privacy.read_receipts': 'Conferme di lettura',
  'settings.privacy.read_receipts.info':
    'È reciproco: se non invii conferme di lettura, non vedrai nemmeno se i tuoi messaggi sono stati letti.',
  'settings.privacy.typing_indicator': 'Indicatore di digitazione',
  'settings.section.appearance': 'Aspetto',
  'settings.theme': 'Tema',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Chiaro',
  'settings.theme.dark': 'Scuro',
  'settings.interface_language': "Lingua dell'interfaccia",
  'settings.interface_language.automatic': 'Automatico',
  'settings.content_languages': 'Lingue di traduzione',
  'settings.section.notifications': 'Notifiche',
  'settings.notifications.title': 'Notifiche',
  'settings.notif.sounds': 'Suoni',
  'settings.notif.more_options': 'Altre opzioni',
  'settings.section.data': 'Dati',
  'settings.media': 'Contenuti multimediali',
  'settings.messages': 'Messaggi',
  'settings.export_data': 'Esporta i miei dati',
  'settings.section.tools': 'Strumenti',
  'settings.tools.progression': 'Progressi',
  'settings.section.about': 'Informazioni',
  'settings.terms': "Condizioni d'uso",
  'settings.privacy_policy': 'Informativa sulla privacy',
  'settings.version': 'Versione',
  'settings.logout.title': 'Esci',
  'settings.logout.message': 'Vuoi davvero uscire?',
  'settings.logout.inprogress': 'Disconnessione in corso...',
  'settings.loading': 'Caricamento delle impostazioni',
  'settings.error.title': 'Impossibile caricare le impostazioni',
  'settings.retry': 'Riprova',
  'settings.offline.body': 'Offline: le impostazioni restano leggibili; potrai modificarle quando torna la rete.',
  'settings.save.error': "L'impostazione non è stata salvata.",
  'settings.theme.sync_error': 'Tema applicato su questo dispositivo, non sincronizzato.',
  'common.cancel': 'Annulla',

  'media.video.play': 'Riproduci video',
  'media.video.pause': 'Metti in pausa',
  'media.video.position': 'Posizione di riproduzione',
  'media.audio.position': 'Posizione di riproduzione',
  'media.audio.speed': 'Velocità di riproduzione',
  'media.video.position.value': '{elapsed} di {total}',
  'media.video.mute': 'Disattiva audio',
  'media.video.unmute': 'Riattiva audio',
  'media.video.more_options': 'Altre opzioni',
  'media.video.speed': 'Velocità',
  'media.video.pip.enter': 'Picture-in-Picture',
  'media.video.pip.exit': 'Esci da Picture-in-Picture',

  'community.list.create.accessibilityLabel': 'Crea una community',
  'community.list.search.placeholder': 'Cerca community',
  'community.list.search.clear': 'Cancella la ricerca',
  'community.list.search.empty': 'Nessuna community corrisponde a «{query}».',
  'community.list.empty.title': 'Nessuna community',
  'community.list.empty.subtitle': 'Unisciti a una community o creane una per parlare insieme.',
  'community.list.loading': 'Caricamento delle community',
  'community.error.title': 'Impossibile caricare le community',
  'community.error.body': 'Controlla la connessione e riprova.',
  'community.retry': 'Riprova',
  'community.offline.title': 'Offline',
  'community.offline.body': 'Le tue community restano leggibili; per crearne una serve la connessione.',
  'community.privacy.private': 'Privata',
  'community.privacy.public': 'Pubblica',
  'community.members.one': '{count} membro',
  'community.members.other': '{count} membri',
  'community.conversations.one': '{count} conversazione',
  'community.conversations.other': '{count} conversazioni',
  'community.detail.stats.members': 'Membri',
  'community.detail.channels': 'Conversazioni',
  'community.detail.channels.empty': 'Non partecipi ancora a nessuna conversazione di questa community.',
  'community.detail.untitled': 'Conversazione senza titolo',
  'community.detail.back': 'Torna alle community',
  'community.detail.refused.title': 'Community non trovata',
  'community.detail.refused.body': 'Non esiste, oppure è privata e non ne sei membro.',
  'community.detail.error.title': 'Impossibile caricare questa community',
  'community.detail.loading': 'Caricamento della community',
  'community.create.title': 'Nuova community',
  'community.create.preview.placeholder': 'La mia community',
  'community.create.field.name': 'Nome',
  'community.create.field.name.placeholder': 'Nome della community',
  'community.create.field.identifier': 'Identificativo',
  'community.create.field.identifier.placeholder': 'mio-gruppo',
  'community.create.field.description': 'Descrizione',
  'community.create.field.description.placeholder': 'Di cosa parla questa community?',
  'community.create.privacy.title': 'Community privata',
  'community.create.privacy.private.description': 'Solo i membri invitati possono unirsi',
  'community.create.privacy.public.description': 'Chiunque può scoprirla e unirsi',
  'community.create.button': 'Crea la community',
  'community.create.inprogress': 'Creazione…',
  'community.create.error.name': 'Dalle un nome di al massimo 100 caratteri.',
  'community.create.error.identifier': 'Solo lettere, cifre, trattini e trattini bassi, al massimo 50.',
  'community.create.error.description': 'Al massimo 500 caratteri.',
  'community.create.error.conflict': 'Questo identificativo è già in uso.',
  'community.create.error.offline': 'Offline: la community non è stata inviata.',
  'community.create.error.default': 'La community non è stata creata. Riprova.',
  'calls.filters': 'Filtra il registro chiamate',
  'calls.filter.all': 'Tutte',
  'calls.filter.missed': 'Perse',
  'calls.direction.incoming': 'Ricevuta',
  'calls.direction.outgoing': 'Effettuata',
  'calls.direction.missed': 'Persa',
  'calls.a11y.incoming': 'chiamata ricevuta',
  'calls.a11y.outgoing': 'chiamata effettuata',
  'calls.a11y.missed': 'chiamata persa',
  'calls.type.audio': 'chiamata vocale',
  'calls.type.video': 'videochiamata',
  'calls.duration': 'durata {duration}',
  'calls.unknown': 'Sconosciuto',
  'calls.empty.title': 'Nessuna chiamata recente',
  'calls.empty.subtitle': 'Qui appariranno le tue chiamate ricevute, perse, annullate ed effettuate.',
  'calls.empty.missed.title': 'Nessuna chiamata persa',
  'calls.empty.missed.subtitle': 'Qui appariranno le chiamate a cui non hai risposto.',
  'calls.error.title': 'Impossibile caricare il registro chiamate',
  'calls.error.body': 'Controlla la connessione e riprova.',
  'calls.offline.title': 'Offline',
  'calls.offline.body': 'Stai vedendo il registro dell’ultimo caricamento.',
  'calls.offline.cold.body': 'Il registro si caricherà appena torni online.',
  'calls.retry': 'Riprova',
  'calls.loading': 'Caricamento del registro chiamate',
  'calls.allLoaded': 'Tutte le chiamate degli ultimi tre mesi sono caricate',

  'discover.tabs': 'Sezioni di Scopri',
  'discover.tab.discover': 'Scopri',
  'discover.tab.requests': 'Richieste',
  'discover.tab.blocked': 'Bloccati',
  'discover.tab.requests.count.one': 'Richieste, {count} ricevuta',
  'discover.tab.requests.count.other': 'Richieste, {count} ricevute',
  'discover.invite.title': 'Invita via email',
  'discover.invite.placeholder': 'Indirizzo email',
  'discover.invite.send': 'Invia',
  'discover.invite.sending': 'Invio…',
  'discover.invite.sendLabel': 'Invia l’invito via email',
  'discover.invite.sent': 'Invito inviato a {email}',
  'discover.invite.invalid': 'Questo indirizzo email non è valido.',
  'discover.invite.conflict': 'Questa persona è già su Meeshy: cercala qui sotto.',
  'discover.invite.error': 'Impossibile inviare l’invito. Riprova.',
  'discover.invite.offline': 'Offline: riconnettiti per inviare l’invito.',
  'discover.search.label': 'Cerca un utente Meeshy',
  'discover.search.clear': 'Cancella la ricerca',
  'discover.search.searching': 'Ricerca in corso',
  'discover.search.empty': 'Nessun utente trovato per «{query}»',
  'discover.search.error': 'La ricerca non è riuscita. Controlla la connessione.',
  'discover.connection.add': 'Aggiungi',
  'discover.connection.addLabel': 'Aggiungi {name}',
  'discover.connection.pending': 'In attesa',
  'discover.connection.cancelLabel': 'Annulla la richiesta inviata a {name}',
  'discover.connection.contact': 'Contatto',
  'discover.connection.blocked': 'Bloccato',
  'discover.connection.acceptLabel': 'Accetta la richiesta di {name}',
  'discover.connection.rejectLabel': 'Rifiuta la richiesta di {name}',
  'discover.requests.filters': 'Filtra le richieste',
  'discover.requests.received': 'Ricevute',
  'discover.requests.sent': 'Inviate',
  'discover.requests.intent': 'Vorrebbe entrare in contatto con te',
  'discover.requests.cancel': 'Annulla',
  'discover.requests.empty.received.title': 'Nessuna richiesta ricevuta',
  'discover.requests.empty.received.subtitle': 'Le richieste di contatto ricevute appariranno qui.',
  'discover.requests.empty.sent.title': 'Nessuna richiesta inviata',
  'discover.requests.empty.sent.subtitle': 'Le richieste che invii appariranno qui.',
  'discover.blocked.unblock': 'Sblocca',
  'discover.blocked.unblockLabel': 'Sblocca {name}',
  'discover.blocked.confirm.title': 'Sbloccare?',
  'discover.blocked.confirm.body': 'Sbloccare {name}?',
  'discover.blocked.confirm.cancel': 'Annulla',
  'discover.blocked.empty.title': 'Nessun utente bloccato',
  'discover.blocked.empty.subtitle': 'Le persone che blocchi appariranno qui.',
  'discover.unknown': 'Sconosciuto',
  'discover.loading': 'Caricamento',
  'discover.allLoaded': 'L’elenco completo è caricato',
  'discover.error.title': 'Impossibile caricare questo elenco',
  'discover.error.body': 'Controlla la connessione e riprova.',
  'discover.offline.title': 'Offline',
  'discover.offline.body': 'Stai vedendo l’elenco dell’ultimo caricamento.',
  'discover.offline.cold.body': 'L’elenco si caricherà appena torni online.',
  'discover.retry': 'Riprova',
  'discover.announce.accepted': 'Connessione accettata',
  'discover.announce.rejected': 'Richiesta rifiutata',
  'discover.announce.cancelled': 'Richiesta annullata',
  'discover.announce.sent': 'Richiesta inviata',
  'discover.announce.unblocked': 'Utente sbloccato',
  'discover.announce.acceptFailed': 'Impossibile accettare questa richiesta',
  'discover.announce.rejectFailed': 'Impossibile rifiutare questa richiesta',
  'discover.announce.cancelFailed': 'Impossibile annullare questa richiesta',
  'discover.announce.sendFailed': 'Impossibile inviare la richiesta',
  'discover.announce.unblockFailed': 'Impossibile sbloccare',
  'discover.announce.offline': 'Offline: non è stato inviato nulla.',

  'a11y.floating.rung.discover.requests.one': 'Scopri, {count} richiesta ricevuta',
  'a11y.floating.rung.discover.requests.other': 'Scopri, {count} richieste ricevute',

  'links.hub.banner.title': 'Gestisci i tuoi link',
  'links.hub.banner.subtitle': 'Invita chi vuoi nelle tue conversazioni',
  'links.hub.share.title': 'Link di condivisione',
  'links.hub.share.description': 'Invita i contatti a unirsi alle tue conversazioni',
  'links.hub.share.create': 'Crea un link di condivisione',
  'links.share.back': 'Torna a I miei link',
  'links.share.stats.total': 'Link',
  'links.share.stats.active': 'Attivi',
  'links.share.stats.joined': 'Entrati',
  'links.share.joined.one': '{count} entrato',
  'links.share.joined.other': '{count} entrati',
  'links.share.copy': 'Copia il link',
  'links.share.empty.title': 'Nessun link di condivisione',
  'links.share.empty.subtitle': 'Crea un link per invitare persone in una conversazione',
  'links.share.loading': 'Caricamento dei link',
  'links.share.allLoaded': 'Tutti i tuoi link sono caricati',
  'links.status.active': 'Attivo',
  'links.status.inactive': 'Inattivo',
  'links.unlimited': 'Illimitato',
  'links.error.title': 'Impossibile caricare i tuoi link',
  'links.error.body': 'Controlla la connessione e riprova.',
  'links.retry': 'Riprova',
  'links.offline.title': 'Offline',
  'links.offline.body': 'I tuoi link restano leggibili; per modificarli serve la connessione.',
  'links.detail.back': 'Torna ai link di condivisione',
  'links.detail.copy': 'Copia',
  'links.detail.copied': 'Copiato',
  'links.detail.share': 'Condividi',
  'links.detail.disable': 'Disattiva',
  'links.detail.activate': 'Attiva',
  'links.detail.stats': 'Statistiche',
  'links.detail.stats.uses': 'Utilizzi',
  'links.detail.stats.max': 'Massimo',
  'links.detail.info': 'Informazioni',
  'links.detail.identifier': 'Identificativo',
  'links.detail.createdAt': 'Creato il',
  'links.detail.expiresAt': 'Scade il',
  'links.detail.reason.closed': 'La conversazione è chiusa: questo link non fa più entrare nessuno.',
  'links.detail.reason.expired': 'Questo link è scaduto.',
  'links.detail.reason.revoked': 'Hai disattivato questo link.',
  'links.detail.refused.title': 'Link non trovato',
  'links.detail.refused.body': 'Questo link non esiste o non è uno dei tuoi.',
  'links.detail.loading': 'Caricamento del link',
  'links.announce.copied': 'Link copiato',
  'links.announce.copyFailed': 'Impossibile copiare il link',
  'links.announce.shareUnavailable': 'La condivisione non è disponibile qui',
  'links.announce.disabled': 'Link disattivato',
  'links.announce.activated': 'Link attivato',
  'links.announce.toggleFailed': 'Impossibile modificare questo link',
  'links.announce.offline': 'Offline: non è stato inviato nulla.',
  'links.create.title': 'Nuovo link di condivisione',
  'links.create.section.conversation': 'Conversazione',
  'links.create.choose': 'Scegli un gruppo o una community',
  'links.create.picker.title': 'Scegli una conversazione',
  'links.create.picker.empty': 'Nessuna conversazione può ancora ricevere un link.',
  'links.create.section.identity': 'Identità del link',
  'links.create.name': 'Nome del link',
  'links.create.name.placeholder': 'es.: Condivisione su Twitter',
  'links.create.description': 'Descrizione (facoltativa)',
  'links.create.description.placeholder': 'es.: Unisciti al nostro gruppo…',
  'links.create.section.access': 'Accesso ospiti',
  'links.create.section.access.subtitle': 'Cosa devono fornire i visitatori per entrare',
  'links.create.access.account': 'Account obbligatorio',
  'links.create.access.account.caption': 'Solo i membri di Meeshy possono entrare',
  'links.create.access.nickname': 'Nickname obbligatorio',
  'links.create.access.nickname.caption': 'Il visitatore deve scegliere un nickname',
  'links.create.access.email': 'E-mail obbligatoria',
  'links.create.access.email.caption': 'Il visitatore deve fornire la sua e-mail',
  'links.create.access.birthday': 'Data di nascita obbligatoria',
  'links.create.access.birthday.caption': 'Consente il controllo dell’età',
  'links.create.section.permissions': 'Permessi',
  'links.create.section.permissions.subtitle': 'Cosa possono fare gli ospiti anonimi',
  'links.create.permission.messages': 'Inviare messaggi',
  'links.create.permission.messages.caption': 'Gli ospiti possono scrivere nella conversazione',
  'links.create.permission.images': 'Inviare immagini',
  'links.create.permission.images.caption': 'Gli ospiti possono condividere foto',
  'links.create.permission.files': 'Inviare file',
  'links.create.permission.files.caption': 'Gli ospiti possono inviare documenti',
  'links.create.permission.history': 'Vedere la cronologia',
  'links.create.permission.history.caption': 'Gli ospiti vedono i messaggi precedenti',
  'links.create.section.limits': 'Limiti',
  'links.create.section.limits.subtitle': 'Controlla il pubblico e la durata del link',
  'links.create.limit.uses': 'Limita gli utilizzi',
  'links.create.limit.max.one': 'Al massimo {count} utilizzo',
  'links.create.limit.max.other': 'Al massimo {count} utilizzi',
  'links.create.limit.count': 'Numero di utilizzi',
  'links.create.limit.invalid': 'Scegli un numero intero tra 1 e {max}.',
  'links.create.expiration': 'Scadenza',
  'links.create.expiration.never': 'Mai',
  'links.create.expiration.h24': '24 ore',
  'links.create.expiration.d7': '7 giorni',
  'links.create.expiration.d30': '30 giorni',
  'links.create.expiration.m3': '3 mesi',
  'links.create.button': 'Crea il link di condivisione',
  'links.create.inprogress': 'Creazione in corso…',
  'links.create.error.conversation': 'Scegli prima una conversazione.',
  'links.create.error.offline': 'Offline: il link non è stato creato.',
  'links.create.error.refused': 'Non puoi creare un link per questa conversazione.',
  'links.create.error.default': 'Impossibile creare il link. Riprova.',

  /* L'ESPACE D'ADMINISTRATION (#6432) — les onze sections reprennent les
     libellés de la barre latérale du legacy (`AdminLayout.tsx`), pour qu'un
     administrateur retrouve ses repères d'une application à l'autre. */
  'admin.title': 'Amministrazione',
  'admin.role': 'Il tuo ruolo: {role}',
  'admin.denied.title': 'Area riservata',
  'admin.denied.message': 'Quest\'area richiede un permesso di amministrazione.',
  'admin.counters.title': 'In sintesi',
  'admin.counters.unavailable': 'Contatori non disponibili al momento.',
  'admin.counters.users': 'Account',
  'admin.counters.activeUsers': 'Account attivi',
  'admin.counters.messages': 'Messaggi',
  'admin.counters.communities': 'Comunità',
  'admin.counters.reports': 'Segnalazioni',
  'admin.counters.newUsers': 'Nuovi (24 h)',
  'admin.sections.title': 'Sezioni',
  'admin.sections.legacy': 'interfaccia precedente',
  'admin.nav.dashboard': 'Cruscotto',
  'admin.nav.users': 'Account',
  'admin.nav.moderation': 'Moderazione',
  'admin.nav.audit': 'Registri di audit',
  'admin.nav.analytics': 'Statistiche',
  'admin.nav.trackingLinks': 'Link di tracciamento',
  'admin.nav.ranking': 'Classifica',
  'admin.nav.broadcasts': 'Trasmissioni',
  'admin.nav.settings': 'Impostazioni',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Monitoraggio',
  'admin.users.search': 'Cerca un account',
  'admin.users.count': '{count} account',
  'admin.users.empty': 'Nessun account corrisponde.',
  'admin.users.unavailable': 'Elenco non disponibile al momento.',
  'admin.users.inactive': 'disattivato',
  'admin.users.previous': 'Precedenti',
  'admin.users.next': 'Successivi',
  'admin.user.title': 'Membro',
  'admin.user.unavailable': 'Scheda non disponibile al momento.',
  'admin.user.identity': 'Identità',
  'admin.user.account': 'Account',
  'admin.user.created': 'Iscritto il',
  'admin.user.lastActive': 'Ultima attività',
  'admin.user.twoFactor': 'Due fattori',
  'admin.user.enabled': 'attivato',
  'admin.user.deleted': 'eliminato',
  'admin.user.role': 'Ruolo',

} satisfies InterfaceCatalog;

export default it;
