import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const it = {
  'announce.messageSent': 'Messaggio inviato',
  'announce.messageCopied': 'Messaggio copiato',
  'announce.messagesCopied': 'Messaggi copiati',
  'announce.messageProtected': 'Messaggio protetto',
  'announce.selectionCap': 'Massimo {count} messaggi',
  'announce.nothingToCopy': 'Niente da copiare',

  'message.author.self': 'Tu',
  'message.excerpt.protected': 'contenuto protetto',
  'a11y.message.menu.subject': 'Azioni del messaggio di {author}: {excerpt}',

  'typing.named': '{name} sta scrivendo',
  'typing.double': '{first} e {second} stanno scrivendo',
  'typing.several': 'Più persone stanno scrivendo',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'I miei link',
  'root.menu.notifications': 'Notifiche',
  'root.menu.calls': 'Chiamate',
  'root.menu.discover': 'Scopri',
  'root.menu.communities': 'Community',
  'root.menu.settings': 'Impostazioni',
  'root.menu.profile': 'Profilo',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Navigazione Meeshy',
  'a11y.floating.menu.unread.one': 'Menu, {count} notifica non letta',
  'a11y.floating.menu.unread.other': 'Menu, {count} notifiche non lette',
  'a11y.floating.rung.notifications.unread.one': 'Notifiche, {count} non letta',
  'a11y.floating.rung.notifications.unread.other': 'Notifiche, {count} non lette',

  'notifications.category.all': 'Tutte',
  'notifications.category.unread': 'Non lette',
  'notifications.category.messages': 'Messaggi',
  'notifications.category.reactions': 'Reazioni',
  'notifications.category.mentions': 'Menzioni',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contatti',
  'notifications.category.groups': 'Gruppi',
  'notifications.category.calls': 'Chiamate',
  'notifications.category.translations': 'Traduzioni',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorie di notifiche',
  'notifications.markAllRead': 'Segna tutte come lette',
  'notifications.unreadCount.one': '{count} non letta',
  'notifications.unreadCount.other': '{count} non lette',
  'notifications.unread': 'Non letta',
  'notifications.empty.all': 'Nessuna notifica',
  'notifications.empty.unread': 'Nessuna notifica non letta',
  'notifications.empty.category': 'Nessuna notifica in «{category}»',
  'notifications.empty.subtitle': 'Le tue notifiche appariranno qui',
  'notifications.loading': 'Caricamento delle notifiche',
  'notifications.error.title': 'Impossibile caricare le notifiche',
  'notifications.error.body': 'Riprova tra un momento.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Le tue notifiche appariranno quando tornerai online.',
  'notifications.retry': 'Riprova',
  'notifications.allLoaded': 'Tutte le notifiche sono state caricate',
  'notifications.actions': 'Azioni della notifica',
  'notifications.action.markRead': 'Segna come letta',
  'notifications.action.delete': 'Elimina',
  'notifications.failure': 'L’azione non è andata a buon fine. Riprova.',

  'pending.back': 'Torna alle conversazioni',
  'pending.comingSoon': 'Questa schermata arriverà presto.',
  'pending.feed.promise': 'I post delle persone che segui.',
  'pending.links.promise': 'I link condivisi nelle tue conversazioni si raccoglieranno qui.',
  'pending.notifications.promise': 'Ciò che ti aspetta — menzioni, risposte, inviti — si leggerà qui.',
  'pending.calls.promise': 'La cronologia delle tue chiamate, e il modo per farne una.',
  'pending.discover.promise': 'Persone da conoscere, scelte in base a ciò che avete in comune.',
  'pending.communities.promise': 'Le community di cui fai parte, e quelle che ti somigliano.',
  'pending.settings.promise': 'Le tue lingue, la tua privacy, le tue notifiche.',
  'pending.profile.promise': 'La tua identità Meeshy — nome, foto, lingue e ciò che gli altri ne vedono.',
} satisfies InterfaceCatalog;

export default it;
