/**
 * Le catalogue des libellés de la ligne d'aperçu d'une conversation (#7546),
 * dans les sept langues du produit.
 *
 * Il ne porte AUCUN contenu utilisateur : le texte d'un message passe par le
 * Prisme (`resolvePrismTranslation`) et n'est jamais une clé d'ici. Ce qui est
 * ici est le CADRAGE — dans quelle langue on adresse le lecteur.
 *
 * Les libellés sont sans pictogramme : l'icône voyage à part dans la valeur
 * rendue, pour que chaque client la dessine avec sa propre iconographie.
 */

import { normalizeLanguageForDedup } from './language-normalize.js';

export const CONVERSATION_PREVIEW_LANGUAGES = ['fr', 'en', 'es', 'pt', 'de', 'it', 'ar'] as const;
export type ConversationPreviewLanguage = (typeof CONVERSATION_PREVIEW_LANGUAGES)[number];

export const CONVERSATION_PREVIEW_STRING_KEYS = [
  'line.author',
  'message.author.self',
  'message.author.unknown',
  'conversation.empty',
  'typing.one',
  'typing.two',
  'typing.many',
  'draft',
  'reaction.member',
  'reaction.member.bare',
  'reaction.self',
  'reaction.self.bare',
  'call.active',
  'call.participants.one',
  'call.participants.other',
  'call.audio',
  'call.video',
  'call.missed',
  'call.declined',
  'call.cancelled',
  'call.unanswered',
  'call.failed',
  'attachment.voice',
  'attachment.audio',
  'attachment.video',
  'attachment.photo',
  'attachment.file',
  'attachment.location',
  'attachment.sticker',
  'attachment.voice.many',
  'attachment.audio.many',
  'attachment.video.many',
  'attachment.photo.many',
  'attachment.file.many',
  'attachment.mixed.many',
  'detail.pages.one',
  'detail.pages.other',
  'protection.viewOnce',
  'protection.viewOnce.opened',
  'protection.expired',
  'protection.hidden',
  'protection.hidden.hint',
  'protection.encrypted',
  'effect.count',
  'effect.shake',
  'effect.zoom',
  'effect.explode',
  'effect.confetti',
  'effect.fireworks',
  'effect.waoo',
  'effect.glow',
  'effect.pulse',
  'effect.rainbow',
  'effect.sparkle',
  'system.member.added',
  'system.member.removed',
  'system.member.left',
  'system.member.joined',
  'system.members.arrived.one',
  'system.members.arrived.two',
  'system.members.arrived.three',
  'system.members.arrived.many',
  'system.conversation.renamed',
  'system.conversation.image',
  'system.encryption.e2ee',
  'system.encryption.enabled',
  'system.generic',
  'unit.second',
  'unit.minute',
  'unit.hour',
  'unit.day',
] as const;
export type ConversationPreviewStringKey = (typeof CONVERSATION_PREVIEW_STRING_KEYS)[number];

type Catalog = Readonly<Record<ConversationPreviewStringKey, string>>;

const FR: Catalog = {
  'line.author': '{author} : {line}',
  'message.author.self': 'Vous',
  'message.author.unknown': 'Quelqu’un',
  'conversation.empty': 'Nouvelle conversation',
  'typing.one': '{name} écrit…',
  'typing.two': '{name} et {other} écrivent…',
  'typing.many': '{count} personnes écrivent…',
  'draft': 'Brouillon',
  'reaction.member': '{actor} a réagi {emoji} à « {excerpt} »',
  'reaction.member.bare': '{actor} a réagi {emoji}',
  'reaction.self': 'Vous avez réagi {emoji} à « {excerpt} »',
  'reaction.self.bare': 'Vous avez réagi {emoji}',
  'call.active': 'Appel en cours',
  'call.participants.one': '{count} participant',
  'call.participants.other': '{count} participants',
  'call.audio': 'Appel vocal',
  'call.video': 'Appel vidéo',
  'call.missed': 'Appel manqué',
  'call.declined': 'Appel refusé',
  'call.cancelled': 'Appel annulé',
  'call.unanswered': 'Appel sans réponse',
  'call.failed': 'Appel interrompu',
  'attachment.voice': 'Message vocal',
  'attachment.audio': 'Audio',
  'attachment.video': 'Vidéo',
  'attachment.photo': 'Photo',
  'attachment.file': 'Fichier',
  'attachment.location': 'Position',
  'attachment.sticker': 'Sticker',
  'attachment.voice.many': '{count} messages vocaux',
  'attachment.audio.many': '{count} audios',
  'attachment.video.many': '{count} vidéos',
  'attachment.photo.many': '{count} photos',
  'attachment.file.many': '{count} fichiers',
  'attachment.mixed.many': '{count} pièces jointes',
  'detail.pages.one': '{count} page',
  'detail.pages.other': '{count} pages',
  'protection.viewOnce': 'Vue unique',
  'protection.viewOnce.opened': 'Ouvert',
  'protection.expired': 'Message expiré',
  'protection.hidden': 'Message masqué',
  'protection.hidden.hint': 'ouvrir pour lire',
  'protection.encrypted': 'Message chiffré',
  'effect.count': '{count} effets',
  'effect.shake': 'Secousse',
  'effect.zoom': 'Zoom',
  'effect.explode': 'Explosion',
  'effect.confetti': 'Confettis',
  'effect.fireworks': 'Feu d’artifice',
  'effect.waoo': 'Waouh',
  'effect.glow': 'Lueur',
  'effect.pulse': 'Pulsation',
  'effect.rainbow': 'Arc-en-ciel',
  'effect.sparkle': 'Paillettes',
  'system.member.added': '{actor} a ajouté {target}',
  'system.member.removed': '{actor} a retiré {target}',
  'system.member.left': '{actor} a quitté la conversation',
  'system.member.joined': '{actor} a rejoint la conversation',
  'system.members.arrived.one': '{first} vient d’arriver — dis-lui salut',
  'system.members.arrived.two': '{first} et {second} viennent d’arriver — dis-leur salut',
  'system.members.arrived.three': '{first}, {second} et {third} viennent d’arriver — dis-leur salut',
  'system.members.arrived.many': '{first}, {second} et {others} autres viennent d’arriver — dis-leur salut',
  'system.conversation.renamed': 'Nom du groupe modifié',
  'system.conversation.image': 'Photo du groupe modifiée',
  'system.encryption.e2ee': 'Chiffrement de bout en bout activé',
  'system.encryption.enabled': 'Chiffrement activé',
  'system.generic': 'Conversation mise à jour',
  'unit.second': '{count} s',
  'unit.minute': '{count} min',
  'unit.hour': '{count} h',
  'unit.day': '{count} j',
};

const EN: Catalog = {
  'line.author': '{author}: {line}',
  'message.author.self': 'You',
  'message.author.unknown': 'Someone',
  'conversation.empty': 'New conversation',
  'typing.one': '{name} is typing…',
  'typing.two': '{name} and {other} are typing…',
  'typing.many': '{count} people are typing…',
  'draft': 'Draft',
  'reaction.member': '{actor} reacted {emoji} to “{excerpt}”',
  'reaction.member.bare': '{actor} reacted {emoji}',
  'reaction.self': 'You reacted {emoji} to “{excerpt}”',
  'reaction.self.bare': 'You reacted {emoji}',
  'call.active': 'Call in progress',
  'call.participants.one': '{count} participant',
  'call.participants.other': '{count} participants',
  'call.audio': 'Voice call',
  'call.video': 'Video call',
  'call.missed': 'Missed call',
  'call.declined': 'Declined call',
  'call.cancelled': 'Cancelled call',
  'call.unanswered': 'Unanswered call',
  'call.failed': 'Call interrupted',
  'attachment.voice': 'Voice message',
  'attachment.audio': 'Audio',
  'attachment.video': 'Video',
  'attachment.photo': 'Photo',
  'attachment.file': 'File',
  'attachment.location': 'Location',
  'attachment.sticker': 'Sticker',
  'attachment.voice.many': '{count} voice messages',
  'attachment.audio.many': '{count} audio files',
  'attachment.video.many': '{count} videos',
  'attachment.photo.many': '{count} photos',
  'attachment.file.many': '{count} files',
  'attachment.mixed.many': '{count} attachments',
  'detail.pages.one': '{count} page',
  'detail.pages.other': '{count} pages',
  'protection.viewOnce': 'View once',
  'protection.viewOnce.opened': 'Opened',
  'protection.expired': 'Message expired',
  'protection.hidden': 'Hidden message',
  'protection.hidden.hint': 'open to read',
  'protection.encrypted': 'Encrypted message',
  'effect.count': '{count} effects',
  'effect.shake': 'Shake',
  'effect.zoom': 'Zoom',
  'effect.explode': 'Explosion',
  'effect.confetti': 'Confetti',
  'effect.fireworks': 'Fireworks',
  'effect.waoo': 'Wow',
  'effect.glow': 'Glow',
  'effect.pulse': 'Pulse',
  'effect.rainbow': 'Rainbow',
  'effect.sparkle': 'Sparkle',
  'system.member.added': '{actor} added {target}',
  'system.member.removed': '{actor} removed {target}',
  'system.member.left': '{actor} left the conversation',
  'system.member.joined': '{actor} joined the conversation',
  'system.members.arrived.one': '{first} just arrived — say hi',
  'system.members.arrived.two': '{first} and {second} just arrived — say hi',
  'system.members.arrived.three': '{first}, {second} and {third} just arrived — say hi',
  'system.members.arrived.many': '{first}, {second} and {others} others just arrived — say hi',
  'system.conversation.renamed': 'Group name changed',
  'system.conversation.image': 'Group photo changed',
  'system.encryption.e2ee': 'End-to-end encryption enabled',
  'system.encryption.enabled': 'Encryption enabled',
  'system.generic': 'Conversation updated',
  'unit.second': '{count} s',
  'unit.minute': '{count} min',
  'unit.hour': '{count} h',
  'unit.day': '{count} d',
};

const ES: Catalog = {
  'line.author': '{author}: {line}',
  'message.author.self': 'Tú',
  'message.author.unknown': 'Alguien',
  'conversation.empty': 'Nueva conversación',
  'typing.one': '{name} está escribiendo…',
  'typing.two': '{name} y {other} están escribiendo…',
  'typing.many': '{count} personas están escribiendo…',
  'draft': 'Borrador',
  'reaction.member': '{actor} reaccionó {emoji} a «{excerpt}»',
  'reaction.member.bare': '{actor} reaccionó {emoji}',
  'reaction.self': 'Reaccionaste {emoji} a «{excerpt}»',
  'reaction.self.bare': 'Reaccionaste {emoji}',
  'call.active': 'Llamada en curso',
  'call.participants.one': '{count} participante',
  'call.participants.other': '{count} participantes',
  'call.audio': 'Llamada de voz',
  'call.video': 'Videollamada',
  'call.missed': 'Llamada perdida',
  'call.declined': 'Llamada rechazada',
  'call.cancelled': 'Llamada cancelada',
  'call.unanswered': 'Llamada sin respuesta',
  'call.failed': 'Llamada interrumpida',
  'attachment.voice': 'Mensaje de voz',
  'attachment.audio': 'Audio',
  'attachment.video': 'Vídeo',
  'attachment.photo': 'Foto',
  'attachment.file': 'Archivo',
  'attachment.location': 'Ubicación',
  'attachment.sticker': 'Sticker',
  'attachment.voice.many': '{count} mensajes de voz',
  'attachment.audio.many': '{count} audios',
  'attachment.video.many': '{count} vídeos',
  'attachment.photo.many': '{count} fotos',
  'attachment.file.many': '{count} archivos',
  'attachment.mixed.many': '{count} archivos adjuntos',
  'detail.pages.one': '{count} página',
  'detail.pages.other': '{count} páginas',
  'protection.viewOnce': 'Ver una vez',
  'protection.viewOnce.opened': 'Abierto',
  'protection.expired': 'Mensaje caducado',
  'protection.hidden': 'Mensaje oculto',
  'protection.hidden.hint': 'abrir para leer',
  'protection.encrypted': 'Mensaje cifrado',
  'effect.count': '{count} efectos',
  'effect.shake': 'Sacudida',
  'effect.zoom': 'Zoom',
  'effect.explode': 'Explosión',
  'effect.confetti': 'Confeti',
  'effect.fireworks': 'Fuegos artificiales',
  'effect.waoo': 'Guau',
  'effect.glow': 'Brillo',
  'effect.pulse': 'Pulso',
  'effect.rainbow': 'Arcoíris',
  'effect.sparkle': 'Destellos',
  'system.member.added': '{actor} añadió a {target}',
  'system.member.removed': '{actor} eliminó a {target}',
  'system.member.left': '{actor} salió de la conversación',
  'system.member.joined': '{actor} se unió a la conversación',
  'system.members.arrived.one': '{first} acaba de llegar — salúdale',
  'system.members.arrived.two': '{first} y {second} acaban de llegar — salúdalos',
  'system.members.arrived.three': '{first}, {second} y {third} acaban de llegar — salúdalos',
  'system.members.arrived.many': '{first}, {second} y {others} más acaban de llegar — salúdalos',
  'system.conversation.renamed': 'Nombre del grupo cambiado',
  'system.conversation.image': 'Foto del grupo cambiada',
  'system.encryption.e2ee': 'Cifrado de extremo a extremo activado',
  'system.encryption.enabled': 'Cifrado activado',
  'system.generic': 'Conversación actualizada',
  'unit.second': '{count} s',
  'unit.minute': '{count} min',
  'unit.hour': '{count} h',
  'unit.day': '{count} d',
};

const PT: Catalog = {
  'line.author': '{author}: {line}',
  'message.author.self': 'Você',
  'message.author.unknown': 'Alguém',
  'conversation.empty': 'Nova conversa',
  'typing.one': '{name} está digitando…',
  'typing.two': '{name} e {other} estão digitando…',
  'typing.many': '{count} pessoas estão digitando…',
  'draft': 'Rascunho',
  'reaction.member': '{actor} reagiu {emoji} a “{excerpt}”',
  'reaction.member.bare': '{actor} reagiu {emoji}',
  'reaction.self': 'Você reagiu {emoji} a “{excerpt}”',
  'reaction.self.bare': 'Você reagiu {emoji}',
  'call.active': 'Chamada em andamento',
  'call.participants.one': '{count} participante',
  'call.participants.other': '{count} participantes',
  'call.audio': 'Chamada de voz',
  'call.video': 'Chamada de vídeo',
  'call.missed': 'Chamada perdida',
  'call.declined': 'Chamada recusada',
  'call.cancelled': 'Chamada cancelada',
  'call.unanswered': 'Chamada não atendida',
  'call.failed': 'Chamada interrompida',
  'attachment.voice': 'Mensagem de voz',
  'attachment.audio': 'Áudio',
  'attachment.video': 'Vídeo',
  'attachment.photo': 'Foto',
  'attachment.file': 'Arquivo',
  'attachment.location': 'Localização',
  'attachment.sticker': 'Figurinha',
  'attachment.voice.many': '{count} mensagens de voz',
  'attachment.audio.many': '{count} áudios',
  'attachment.video.many': '{count} vídeos',
  'attachment.photo.many': '{count} fotos',
  'attachment.file.many': '{count} arquivos',
  'attachment.mixed.many': '{count} anexos',
  'detail.pages.one': '{count} página',
  'detail.pages.other': '{count} páginas',
  'protection.viewOnce': 'Visualização única',
  'protection.viewOnce.opened': 'Aberto',
  'protection.expired': 'Mensagem expirada',
  'protection.hidden': 'Mensagem oculta',
  'protection.hidden.hint': 'abrir para ler',
  'protection.encrypted': 'Mensagem criptografada',
  'effect.count': '{count} efeitos',
  'effect.shake': 'Tremor',
  'effect.zoom': 'Zoom',
  'effect.explode': 'Explosão',
  'effect.confetti': 'Confete',
  'effect.fireworks': 'Fogos de artifício',
  'effect.waoo': 'Uau',
  'effect.glow': 'Brilho',
  'effect.pulse': 'Pulsação',
  'effect.rainbow': 'Arco-íris',
  'effect.sparkle': 'Cintilar',
  'system.member.added': '{actor} adicionou {target}',
  'system.member.removed': '{actor} removeu {target}',
  'system.member.left': '{actor} saiu da conversa',
  'system.member.joined': '{actor} entrou na conversa',
  'system.members.arrived.one': '{first} acabou de chegar — diz olá',
  'system.members.arrived.two': '{first} e {second} acabaram de chegar — diz olá',
  'system.members.arrived.three': '{first}, {second} e {third} acabaram de chegar — diz olá',
  'system.members.arrived.many': '{first}, {second} e mais {others} acabaram de chegar — diz olá',
  'system.conversation.renamed': 'Nome do grupo alterado',
  'system.conversation.image': 'Foto do grupo alterada',
  'system.encryption.e2ee': 'Criptografia de ponta a ponta ativada',
  'system.encryption.enabled': 'Criptografia ativada',
  'system.generic': 'Conversa atualizada',
  'unit.second': '{count} s',
  'unit.minute': '{count} min',
  'unit.hour': '{count} h',
  'unit.day': '{count} d',
};

const DE: Catalog = {
  'line.author': '{author}: {line}',
  'message.author.self': 'Du',
  'message.author.unknown': 'Jemand',
  'conversation.empty': 'Neue Unterhaltung',
  'typing.one': '{name} schreibt…',
  'typing.two': '{name} und {other} schreiben…',
  'typing.many': '{count} Personen schreiben…',
  'draft': 'Entwurf',
  'reaction.member': '{actor} hat mit {emoji} auf „{excerpt}“ reagiert',
  'reaction.member.bare': '{actor} hat mit {emoji} reagiert',
  'reaction.self': 'Du hast mit {emoji} auf „{excerpt}“ reagiert',
  'reaction.self.bare': 'Du hast mit {emoji} reagiert',
  'call.active': 'Laufender Anruf',
  'call.participants.one': '{count} Teilnehmer',
  'call.participants.other': '{count} Teilnehmer',
  'call.audio': 'Sprachanruf',
  'call.video': 'Videoanruf',
  'call.missed': 'Verpasster Anruf',
  'call.declined': 'Abgelehnter Anruf',
  'call.cancelled': 'Abgebrochener Anruf',
  'call.unanswered': 'Unbeantworteter Anruf',
  'call.failed': 'Anruf unterbrochen',
  'attachment.voice': 'Sprachnachricht',
  'attachment.audio': 'Audio',
  'attachment.video': 'Video',
  'attachment.photo': 'Foto',
  'attachment.file': 'Datei',
  'attachment.location': 'Standort',
  'attachment.sticker': 'Sticker',
  'attachment.voice.many': '{count} Sprachnachrichten',
  'attachment.audio.many': '{count} Audiodateien',
  'attachment.video.many': '{count} Videos',
  'attachment.photo.many': '{count} Fotos',
  'attachment.file.many': '{count} Dateien',
  'attachment.mixed.many': '{count} Anhänge',
  'detail.pages.one': '{count} Seite',
  'detail.pages.other': '{count} Seiten',
  'protection.viewOnce': 'Einmalansicht',
  'protection.viewOnce.opened': 'Geöffnet',
  'protection.expired': 'Nachricht abgelaufen',
  'protection.hidden': 'Verborgene Nachricht',
  'protection.hidden.hint': 'zum Lesen öffnen',
  'protection.encrypted': 'Verschlüsselte Nachricht',
  'effect.count': '{count} Effekte',
  'effect.shake': 'Schütteln',
  'effect.zoom': 'Zoom',
  'effect.explode': 'Explosion',
  'effect.confetti': 'Konfetti',
  'effect.fireworks': 'Feuerwerk',
  'effect.waoo': 'Wow',
  'effect.glow': 'Leuchten',
  'effect.pulse': 'Puls',
  'effect.rainbow': 'Regenbogen',
  'effect.sparkle': 'Funkeln',
  'system.member.added': '{actor} hat {target} hinzugefügt',
  'system.member.removed': '{actor} hat {target} entfernt',
  'system.member.left': '{actor} hat die Unterhaltung verlassen',
  'system.member.joined': '{actor} ist der Unterhaltung beigetreten',
  'system.members.arrived.one': '{first} ist gerade angekommen — sag hallo',
  'system.members.arrived.two': '{first} und {second} sind gerade angekommen — sag hallo',
  'system.members.arrived.three': '{first}, {second} und {third} sind gerade angekommen — sag hallo',
  'system.members.arrived.many': '{first}, {second} und {others} weitere sind gerade angekommen — sag hallo',
  'system.conversation.renamed': 'Gruppenname geändert',
  'system.conversation.image': 'Gruppenfoto geändert',
  'system.encryption.e2ee': 'Ende-zu-Ende-Verschlüsselung aktiviert',
  'system.encryption.enabled': 'Verschlüsselung aktiviert',
  'system.generic': 'Unterhaltung aktualisiert',
  'unit.second': '{count} s',
  'unit.minute': '{count} Min.',
  'unit.hour': '{count} Std.',
  'unit.day': '{count} T.',
};

const IT: Catalog = {
  'line.author': '{author}: {line}',
  'message.author.self': 'Tu',
  'message.author.unknown': 'Qualcuno',
  'conversation.empty': 'Nuova conversazione',
  'typing.one': '{name} sta scrivendo…',
  'typing.two': '{name} e {other} stanno scrivendo…',
  'typing.many': '{count} persone stanno scrivendo…',
  'draft': 'Bozza',
  'reaction.member': '{actor} ha reagito {emoji} a «{excerpt}»',
  'reaction.member.bare': '{actor} ha reagito {emoji}',
  'reaction.self': 'Hai reagito {emoji} a «{excerpt}»',
  'reaction.self.bare': 'Hai reagito {emoji}',
  'call.active': 'Chiamata in corso',
  'call.participants.one': '{count} partecipante',
  'call.participants.other': '{count} partecipanti',
  'call.audio': 'Chiamata vocale',
  'call.video': 'Videochiamata',
  'call.missed': 'Chiamata persa',
  'call.declined': 'Chiamata rifiutata',
  'call.cancelled': 'Chiamata annullata',
  'call.unanswered': 'Chiamata senza risposta',
  'call.failed': 'Chiamata interrotta',
  'attachment.voice': 'Messaggio vocale',
  'attachment.audio': 'Audio',
  'attachment.video': 'Video',
  'attachment.photo': 'Foto',
  'attachment.file': 'File',
  'attachment.location': 'Posizione',
  'attachment.sticker': 'Sticker',
  'attachment.voice.many': '{count} messaggi vocali',
  'attachment.audio.many': '{count} audio',
  'attachment.video.many': '{count} video',
  'attachment.photo.many': '{count} foto',
  'attachment.file.many': '{count} file',
  'attachment.mixed.many': '{count} allegati',
  'detail.pages.one': '{count} pagina',
  'detail.pages.other': '{count} pagine',
  'protection.viewOnce': 'Visualizzazione singola',
  'protection.viewOnce.opened': 'Aperto',
  'protection.expired': 'Messaggio scaduto',
  'protection.hidden': 'Messaggio nascosto',
  'protection.hidden.hint': 'apri per leggere',
  'protection.encrypted': 'Messaggio cifrato',
  'effect.count': '{count} effetti',
  'effect.shake': 'Scossa',
  'effect.zoom': 'Zoom',
  'effect.explode': 'Esplosione',
  'effect.confetti': 'Coriandoli',
  'effect.fireworks': 'Fuochi d’artificio',
  'effect.waoo': 'Wow',
  'effect.glow': 'Bagliore',
  'effect.pulse': 'Pulsazione',
  'effect.rainbow': 'Arcobaleno',
  'effect.sparkle': 'Scintille',
  'system.member.added': '{actor} ha aggiunto {target}',
  'system.member.removed': '{actor} ha rimosso {target}',
  'system.member.left': '{actor} ha lasciato la conversazione',
  'system.member.joined': '{actor} si è unito alla conversazione',
  'system.members.arrived.one': 'Nuovo arrivo: {first} — fai un saluto',
  'system.members.arrived.two': 'Nuovi arrivi: {first} e {second} — fai un saluto',
  'system.members.arrived.three': 'Nuovi arrivi: {first}, {second} e {third} — fai un saluto',
  'system.members.arrived.many': 'Nuovi arrivi: {first}, {second} e altri {others} — fai un saluto',
  'system.conversation.renamed': 'Nome del gruppo modificato',
  'system.conversation.image': 'Foto del gruppo modificata',
  'system.encryption.e2ee': 'Crittografia end-to-end attivata',
  'system.encryption.enabled': 'Crittografia attivata',
  'system.generic': 'Conversazione aggiornata',
  'unit.second': '{count} s',
  'unit.minute': '{count} min',
  'unit.hour': '{count} h',
  'unit.day': '{count} g',
};

const AR: Catalog = {
  'line.author': '{author}: {line}',
  'message.author.self': 'أنت',
  'message.author.unknown': 'شخص ما',
  'conversation.empty': 'محادثة جديدة',
  'typing.one': '{name} يكتب…',
  'typing.two': '{name} و{other} يكتبان…',
  'typing.many': '{count} أشخاص يكتبون…',
  'draft': 'مسودة',
  'reaction.member': 'تفاعل {actor} بـ {emoji} مع «{excerpt}»',
  'reaction.member.bare': 'تفاعل {actor} بـ {emoji}',
  'reaction.self': 'تفاعلت بـ {emoji} مع «{excerpt}»',
  'reaction.self.bare': 'تفاعلت بـ {emoji}',
  'call.active': 'مكالمة جارية',
  'call.participants.one': '{count} مشارك',
  'call.participants.other': '{count} مشاركين',
  'call.audio': 'مكالمة صوتية',
  'call.video': 'مكالمة فيديو',
  'call.missed': 'مكالمة فائتة',
  'call.declined': 'مكالمة مرفوضة',
  'call.cancelled': 'مكالمة ملغاة',
  'call.unanswered': 'مكالمة بلا رد',
  'call.failed': 'مكالمة منقطعة',
  'attachment.voice': 'رسالة صوتية',
  'attachment.audio': 'صوت',
  'attachment.video': 'فيديو',
  'attachment.photo': 'صورة',
  'attachment.file': 'ملف',
  'attachment.location': 'موقع',
  'attachment.sticker': 'ملصق',
  'attachment.voice.many': '{count} رسائل صوتية',
  'attachment.audio.many': '{count} ملفات صوتية',
  'attachment.video.many': '{count} مقاطع فيديو',
  'attachment.photo.many': '{count} صور',
  'attachment.file.many': '{count} ملفات',
  'attachment.mixed.many': '{count} مرفقات',
  'detail.pages.one': '{count} صفحة',
  'detail.pages.other': '{count} صفحات',
  'protection.viewOnce': 'عرض لمرة واحدة',
  'protection.viewOnce.opened': 'تم الفتح',
  'protection.expired': 'انتهت صلاحية الرسالة',
  'protection.hidden': 'رسالة مخفية',
  'protection.hidden.hint': 'افتح للقراءة',
  'protection.encrypted': 'رسالة مشفرة',
  'effect.count': '{count} تأثيرات',
  'effect.shake': 'اهتزاز',
  'effect.zoom': 'تكبير',
  'effect.explode': 'انفجار',
  'effect.confetti': 'قصاصات',
  'effect.fireworks': 'ألعاب نارية',
  'effect.waoo': 'واو',
  'effect.glow': 'توهج',
  'effect.pulse': 'نبض',
  'effect.rainbow': 'قوس قزح',
  'effect.sparkle': 'بريق',
  'system.member.added': 'أضاف {actor} {target}',
  'system.member.removed': 'أزال {actor} {target}',
  'system.member.left': 'غادر {actor} المحادثة',
  'system.member.joined': 'انضم {actor} إلى المحادثة',
  'system.members.arrived.one': 'وصل {first} للتو — قل مرحبًا',
  'system.members.arrived.two': 'وصل {first} و{second} للتو — قل مرحبًا',
  'system.members.arrived.three': 'وصل {first} و{second} و{third} للتو — قل مرحبًا',
  'system.members.arrived.many': 'وصل {first} و{second} و{others} آخرون للتو — قل مرحبًا',
  'system.conversation.renamed': 'تم تغيير اسم المجموعة',
  'system.conversation.image': 'تم تغيير صورة المجموعة',
  'system.encryption.e2ee': 'تم تفعيل التشفير التام بين الطرفين',
  'system.encryption.enabled': 'تم تفعيل التشفير',
  'system.generic': 'تم تحديث المحادثة',
  'unit.second': '{count} ث',
  'unit.minute': '{count} د',
  'unit.hour': '{count} س',
  'unit.day': '{count} ي',
};

const CATALOGS: Readonly<Record<ConversationPreviewLanguage, Catalog>> = {
  fr: FR,
  en: EN,
  es: ES,
  pt: PT,
  de: DE,
  it: IT,
  ar: AR,
};

const SUPPORTED: ReadonlySet<string> = new Set(CONVERSATION_PREVIEW_LANGUAGES);

/** Une langue hors des sept retombe sur le français, comme `resolveUserLanguage`. */
export function normalizeConversationPreviewLanguage(code: string | null | undefined): ConversationPreviewLanguage {
  const base = code ? normalizeLanguageForDedup(code).split('-')[0] ?? '' : '';
  return SUPPORTED.has(base) ? (base as ConversationPreviewLanguage) : 'fr';
}

export type ConversationPreviewStringParams = Readonly<Record<string, string | number>>;

export function conversationPreviewString(
  lang: string | null | undefined,
  key: ConversationPreviewStringKey,
  params: ConversationPreviewStringParams = {},
): string {
  const template = CATALOGS[normalizeConversationPreviewLanguage(lang)][key];
  return template.replace(/\{(\w+)\}/g, (_match, token: string) => {
    const value = params[token];
    return value === undefined ? '' : String(value);
  });
}

const DECIMAL_SEPARATOR: Readonly<Record<ConversationPreviewLanguage, string>> = {
  fr: ',',
  en: '.',
  es: ',',
  pt: ',',
  de: ',',
  it: ',',
  ar: '.',
};

type ByteUnits = { readonly b: string; readonly kb: string; readonly mb: string; readonly gb: string };
const FRENCH_BYTE_UNITS: ByteUnits = { b: 'o', kb: 'Ko', mb: 'Mo', gb: 'Go' };
const DEFAULT_BYTE_UNITS: ByteUnits = { b: 'B', kb: 'KB', mb: 'MB', gb: 'GB' };

function formatOneDecimal(value: number, separator: string): string {
  if (value >= 10) return String(Math.round(value));
  const rounded = Math.round(value * 10) / 10;
  const [whole, fraction] = rounded.toFixed(1).split('.');
  return fraction === '0' ? `${whole}` : `${whole}${separator}${fraction}`;
}

/**
 * Poids d'un fichier, au format de la langue : « 48 Ko », « 4,2 Mo », « 12 Mo »
 * en français ; « 4.2 MB » en anglais. Une décimale sous dix unités, aucune
 * au-delà, et jamais de « ,0 ».
 */
export function formatPreviewFileSize(lang: string | null | undefined, bytes: number): string {
  const language = normalizeConversationPreviewLanguage(lang);
  const units = language === 'fr' ? FRENCH_BYTE_UNITS : DEFAULT_BYTE_UNITS;
  const separator = DECIMAL_SEPARATOR[language];
  if (bytes < 1024) return `${Math.max(0, Math.round(bytes))} ${units.b}`;
  const kb = bytes / 1024;
  if (Math.round(kb) < 1024) return `${Math.round(kb)} ${units.kb}`;
  const mb = kb / 1024;
  if (Math.round(mb * 10) / 10 < 1024) return `${formatOneDecimal(mb, separator)} ${units.mb}`;
  return `${formatOneDecimal(mb / 1024, separator)} ${units.gb}`;
}

/**
 * Temps restant d'un éphémère, arrondi à l'unité SUPÉRIEURE : il reste
 * « 4 min » de 3:01 à 4:00, jamais « 3 min » quand il en reste plus de trois.
 */
export function formatPreviewRemaining(lang: string | null | undefined, remainingMs: number): string {
  const seconds = Math.max(1, Math.ceil(remainingMs / 1000));
  if (seconds < 60) return conversationPreviewString(lang, 'unit.second', { count: seconds });
  const minutes = Math.ceil(seconds / 60);
  if (minutes < 60) return conversationPreviewString(lang, 'unit.minute', { count: minutes });
  const hours = Math.ceil(minutes / 60);
  if (hours < 24) return conversationPreviewString(lang, 'unit.hour', { count: hours });
  return conversationPreviewString(lang, 'unit.day', { count: Math.ceil(hours / 24) });
}
