/**
 * Les GABARITS de `notification-strings.ts`, langue par langue.
 *
 * Une table de données, extraite du catalogue qui la consomme pour qu'il tienne
 * dans son budget de taille (#4532) : la logique (interpolation, composition des
 * bannières) reste là-bas, seule la table vit ici.
 */

import type { NotificationLanguage, NotificationStringKey } from './notification-strings.js';

type Templates = Record<NotificationStringKey, string>;

export const TEMPLATES: Record<NotificationLanguage, Templates> = {
  fr: {
    'reaction.message': 'a réagi {emoji} à votre message',
    'reaction.comment': 'a réagi {emoji} à votre commentaire',
    'reaction.commentVerbose': '{actor} a réagi {emoji} à votre commentaire{context}',
    'reaction.post': 'a réagi {emoji} {reactObj}',
    'comment.your': 'a commenté {possObj}',
    'comment.generic': 'a commenté {indefObj}',
    'comment.repliedIn': 'a répondu {locObj}',
    'comment.reply': 'En réponse à votre commentaire',
    'comment.replyWithParent': 'En réponse à « {preview} »',
    'comment.repliedToYours': 'a répondu à votre commentaire',
    'comment.genericFrom': 'a commenté {indefObj} de {author}',
    'comment.repliedInFrom': 'a répondu {locObj} de {author}',
    'someone': 'Quelqu’un',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} de {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'vous a mentionné',
    'reference.post': 'vous a référencé dans sa publication',
    'reference.reel': 'vous a référencé dans son réel',
    'reference.story': 'vous a référencé dans sa story',
    'reference.status': 'vous a référencé dans son statut',
    'friend.story': 'a publié une nouvelle story',
    'friend.post': 'a publié un nouveau post',
    'friend.reel': 'a publié un nouveau réel',
    'friend.mood': 'a publié une nouvelle humeur',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} Appel {callLabel} manqué',
    'call.incoming.title': '{actor} vous appelle',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'Répondre', 'call.action.decline': 'Refuser',
    'contact.request': 'Nouvelle demande de contact',
    'contact.accepted': 'Demande de contact acceptée',
    'contact.requestAction': 'veut se connecter',
    'contact.acceptedAction': 'a accepté votre demande',
    'contact.joinedAction': 'est sur Meeshy !',
    'contact.joinedBody': 'Dites-lui bonjour 👋',
    'contact.joinedMany': '{actor} et {count} autres de vos contacts sont sur Meeshy !',
    'contact.joinedManyBody': 'Dites-leur bonjour 👋',
    'repost': 'a partagé {possObj}',
    'invitation.group': 'Invitation au groupe {title}',
    'invitation.direct': 'Nouvelle conversation avec {actor}',
    'group.added': 'Ajouté au groupe {title}',
    'group.newContact': 'Nouveau contact',
    'attachment.photo': '📷 Photo',
    'attachment.video': '🎬 Vidéo',
    'attachment.audio': '🎵 Audio',
    'attachment.document': '📎 Document',
    'attachment.files': '📎 {count} fichiers',
    'login.newDevice.title': 'Nouvelle connexion détectée',
    'push.private': 'Nouvelle notification',
    'engagement.badgeEarned': '🏅 Badge débloqué : {title} · palier {count}',
    'engagement.streakMilestone': '🔥 Série de {count} jours !',
    'engagement.levelUp': '⭐ Niveau {count} atteint !',
    'engagement.achievementUnlocked': '🏆 Succès débloqué : {title}',
  },
  en: {
    'reaction.message': 'reacted {emoji} to your message',
    'reaction.comment': 'reacted {emoji} to your comment',
    'reaction.commentVerbose': '{actor} reacted {emoji} to your comment{context}',
    'reaction.post': 'reacted {emoji} {reactObj}',
    'comment.your': 'commented on {possObj}',
    'comment.generic': 'commented on {indefObj}',
    'comment.repliedIn': 'replied {locObj}',
    'comment.reply': 'Replied to your comment',
    'comment.replyWithParent': 'Replying to “{preview}”',
    'comment.repliedToYours': 'replied to your comment',
    'comment.genericFrom': 'commented on {author}’s {bareObj}',
    'comment.repliedInFrom': 'replied in {author}’s {bareObj}',
    'someone': 'Someone',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} from {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'mentioned you',
    'reference.post': 'referenced you in their post',
    'reference.reel': 'referenced you in their reel',
    'reference.story': 'referenced you in their story',
    'reference.status': 'referenced you in their status',
    'friend.story': 'shared a new story',
    'friend.post': 'shared a new post',
    'friend.reel': 'shared a new reel',
    'friend.mood': 'shared a new mood',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} Missed {callLabel} call',
    'call.incoming.title': '{actor} is calling you',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'Answer', 'call.action.decline': 'Decline',
    'contact.request': 'New contact request',
    'contact.accepted': 'Contact request accepted',
    'contact.requestAction': 'wants to connect',
    'contact.acceptedAction': 'accepted your request',
    'contact.joinedAction': 'is on Meeshy!',
    'contact.joinedBody': 'Say hello 👋',
    'contact.joinedMany': '{actor} and {count} more of your contacts are on Meeshy!',
    'contact.joinedManyBody': 'Say hello 👋',
    'repost': 'shared {possObj}',
    'invitation.group': 'Invitation to group {title}',
    'invitation.direct': 'New conversation with {actor}',
    'group.added': 'Added to group {title}',
    'group.newContact': 'New contact',
    'attachment.photo': '📷 Photo',
    'attachment.video': '🎬 Video',
    'attachment.audio': '🎵 Audio',
    'attachment.document': '📎 Document',
    'attachment.files': '📎 {count} files',
    'login.newDevice.title': 'New login detected',
    'push.private': 'New notification',
    'engagement.badgeEarned': '🏅 Badge unlocked: {title} · milestone {count}',
    'engagement.streakMilestone': '🔥 {count}-day streak!',
    'engagement.levelUp': '⭐ Level {count} reached!',
    'engagement.achievementUnlocked': '🏆 Achievement unlocked: {title}',
  },
  es: {
    'reaction.message': 'reaccionó {emoji} a tu mensaje',
    'reaction.comment': 'reaccionó {emoji} a tu comentario',
    'reaction.commentVerbose': '{actor} reaccionó {emoji} a tu comentario{context}',
    'reaction.post': 'reaccionó {emoji} {reactObj}',
    'comment.your': 'comentó {possObj}',
    'comment.generic': 'comentó {indefObj}',
    'comment.repliedIn': 'respondió {locObj}',
    'comment.reply': 'Respondió a tu comentario',
    'comment.replyWithParent': 'Respondiendo a «{preview}»',
    'comment.repliedToYours': 'respondió a tu comentario',
    'comment.genericFrom': 'comentó {indefObj} de {author}',
    'comment.repliedInFrom': 'respondió {locObj} de {author}',
    'someone': 'Alguien',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} de {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'te mencionó',
    'reference.post': 'te referenció en su publicación',
    'reference.reel': 'te referenció en su reel',
    'reference.story': 'te referenció en su historia',
    'reference.status': 'te referenció en su estado',
    'friend.story': 'publicó una nueva historia',
    'friend.post': 'publicó una nueva publicación',
    'friend.reel': 'publicó un nuevo reel',
    'friend.mood': 'publicó un nuevo estado de ánimo',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} Llamada {callLabel} perdida',
    'call.incoming.title': '{actor} te está llamando',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'Responder', 'call.action.decline': 'Rechazar',
    'contact.request': 'Nueva solicitud de contacto',
    'contact.accepted': 'Solicitud de contacto aceptada',
    'contact.requestAction': 'quiere conectar contigo',
    'contact.acceptedAction': 'aceptó tu solicitud',
    'contact.joinedAction': 'ya está en Meeshy',
    'contact.joinedBody': '¡Salúdale! 👋',
    'contact.joinedMany': '¡{actor} y {count} contactos más ya están en Meeshy!',
    'contact.joinedManyBody': '¡Salúdales! 👋',
    'repost': 'compartió {possObj}',
    'invitation.group': 'Invitación al grupo {title}',
    'invitation.direct': 'Nueva conversación con {actor}',
    'group.added': 'Añadido al grupo {title}',
    'group.newContact': 'Nuevo contacto',
    'attachment.photo': '📷 Foto',
    'attachment.video': '🎬 Vídeo',
    'attachment.audio': '🎵 Audio',
    'attachment.document': '📎 Documento',
    'attachment.files': '📎 {count} archivos',
    'login.newDevice.title': 'Nuevo inicio de sesión detectado',
    'push.private': 'Nueva notificación',
    'engagement.badgeEarned': '🏅 Insignia desbloqueada: {title} · nivel {count}',
    'engagement.streakMilestone': '🔥 ¡Racha de {count} días!',
    'engagement.levelUp': '⭐ ¡Nivel {count} alcanzado!',
    'engagement.achievementUnlocked': '🏆 Logro desbloqueado: {title}',
  },
  pt: {
    'reaction.message': 'reagiu {emoji} à sua mensagem',
    'reaction.comment': 'reagiu {emoji} ao seu comentário',
    'reaction.commentVerbose': '{actor} reagiu {emoji} ao seu comentário{context}',
    'reaction.post': 'reagiu {emoji} {reactObj}',
    'comment.your': 'comentou {possObj}',
    'comment.generic': 'comentou {indefObj}',
    'comment.repliedIn': 'respondeu {locObj}',
    'comment.reply': 'Respondeu ao seu comentário',
    'comment.replyWithParent': 'Respondendo a “{preview}”',
    'comment.repliedToYours': 'respondeu ao seu comentário',
    'comment.genericFrom': 'comentou {indefObj} de {author}',
    'comment.repliedInFrom': 'respondeu {locObj} de {author}',
    'someone': 'Alguém',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} de {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'mencionou você',
    'reference.post': 'referenciou você na publicação dele(a)',
    'reference.reel': 'referenciou você no reel dele(a)',
    'reference.story': 'referenciou você na story dele(a)',
    'reference.status': 'referenciou você no status dele(a)',
    'friend.story': 'publicou uma nova story',
    'friend.post': 'publicou uma nova publicação',
    'friend.reel': 'publicou um novo reel',
    'friend.mood': 'publicou um novo humor',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} Chamada {callLabel} perdida',
    'call.incoming.title': '{actor} está ligando para você',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'Atender', 'call.action.decline': 'Recusar',
    'contact.request': 'Novo pedido de contato',
    'contact.accepted': 'Pedido de contato aceito',
    'contact.requestAction': 'quer se conectar',
    'contact.acceptedAction': 'aceitou o seu pedido',
    'contact.joinedAction': 'está no Meeshy!',
    'contact.joinedBody': 'Diga olá 👋',
    'contact.joinedMany': '{actor} e mais {count} contatos seus estão no Meeshy!',
    'contact.joinedManyBody': 'Diga olá 👋',
    'repost': 'compartilhou {possObj}',
    'invitation.group': 'Convite para o grupo {title}',
    'invitation.direct': 'Nova conversa com {actor}',
    'group.added': 'Adicionado ao grupo {title}',
    'group.newContact': 'Novo contato',
    'attachment.photo': '📷 Foto',
    'attachment.video': '🎬 Vídeo',
    'attachment.audio': '🎵 Áudio',
    'attachment.document': '📎 Documento',
    'attachment.files': '📎 {count} arquivos',
    'login.newDevice.title': 'Novo login detectado',
    'push.private': 'Nova notificação',
    'engagement.badgeEarned': '🏅 Emblema desbloqueado: {title} · nível {count}',
    'engagement.streakMilestone': '🔥 Sequência de {count} dias!',
    'engagement.levelUp': '⭐ Nível {count} alcançado!',
    'engagement.achievementUnlocked': '🏆 Conquista desbloqueada: {title}',
  },
  de: {
    'reaction.message': 'hat {emoji} auf deine Nachricht reagiert',
    'reaction.comment': 'hat {emoji} auf deinen Kommentar reagiert',
    'reaction.commentVerbose': '{actor} hat {emoji} auf deinen Kommentar reagiert{context}',
    'reaction.post': 'hat {emoji} {reactObj} reagiert',
    'comment.your': 'hat {possObj} kommentiert',
    'comment.generic': 'hat {indefObj} kommentiert',
    'comment.repliedIn': 'hat {locObj} geantwortet',
    'comment.reply': 'Hat auf deinen Kommentar geantwortet',
    'comment.replyWithParent': 'Antwort auf „{preview}“',
    'comment.repliedToYours': 'hat auf deinen Kommentar geantwortet',
    'comment.genericFrom': 'hat {indefObj} von {author} kommentiert',
    'comment.repliedInFrom': 'hat {locObj} von {author} geantwortet',
    'someone': 'Jemand',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} von {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'hat dich erwähnt',
    'reference.post': 'hat dich in einem Beitrag erwähnt',
    'reference.reel': 'hat dich in einem Reel erwähnt',
    'reference.story': 'hat dich in einer Story erwähnt',
    'reference.status': 'hat dich in einem Status erwähnt',
    'friend.story': 'hat eine neue Story geteilt',
    'friend.post': 'hat einen neuen Beitrag geteilt',
    'friend.reel': 'hat einen neuen Reel geteilt',
    'friend.mood': 'hat eine neue Stimmung geteilt',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} Verpasster {callLabel}',
    'call.incoming.title': '{actor} ruft dich an',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'Annehmen', 'call.action.decline': 'Ablehnen',
    'contact.request': 'Neue Kontaktanfrage',
    'contact.accepted': 'Kontaktanfrage angenommen',
    'contact.requestAction': 'möchte sich vernetzen',
    'contact.acceptedAction': 'hat deine Anfrage angenommen',
    'contact.joinedAction': 'ist auf Meeshy!',
    'contact.joinedBody': 'Sag Hallo 👋',
    'contact.joinedMany': '{actor} und {count} weitere Kontakte sind auf Meeshy!',
    'contact.joinedManyBody': 'Sag Hallo 👋',
    'repost': 'hat {possObj} geteilt',
    'invitation.group': 'Einladung zur Gruppe {title}',
    'invitation.direct': 'Neue Unterhaltung mit {actor}',
    'group.added': 'Zur Gruppe {title} hinzugefügt',
    'group.newContact': 'Neuer Kontakt',
    'attachment.photo': '📷 Foto',
    'attachment.video': '🎬 Video',
    'attachment.audio': '🎵 Audio',
    'attachment.document': '📎 Dokument',
    'attachment.files': '📎 {count} Dateien',
    'login.newDevice.title': 'Neue Anmeldung erkannt',
    'push.private': 'Neue Benachrichtigung',
    'engagement.badgeEarned': '🏅 Abzeichen freigeschaltet: {title} · Stufe {count}',
    'engagement.streakMilestone': '🔥 {count}-Tage-Serie!',
    'engagement.levelUp': '⭐ Stufe {count} erreicht!',
    'engagement.achievementUnlocked': '🏆 Erfolg freigeschaltet: {title}',
  },
  it: {
    'reaction.message': 'ha reagito {emoji} al tuo messaggio',
    'reaction.comment': 'ha reagito {emoji} al tuo commento',
    'reaction.commentVerbose': '{actor} ha reagito {emoji} al tuo commento{context}',
    'reaction.post': 'ha reagito {emoji} {reactObj}',
    'comment.your': 'ha commentato {possObj}',
    'comment.generic': 'ha commentato {indefObj}',
    'comment.repliedIn': 'ha risposto {locObj}',
    'comment.reply': 'Ha risposto al tuo commento',
    'comment.replyWithParent': 'In risposta a «{preview}»',
    'comment.repliedToYours': 'ha risposto al tuo commento',
    'comment.genericFrom': 'ha commentato {indefObj} di {author}',
    'comment.repliedInFrom': 'ha risposto {locObj} di {author}',
    'someone': 'Qualcuno',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} di {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'ti ha menzionato',
    'reference.post': 'ti ha menzionato nel suo post',
    'reference.reel': 'ti ha menzionato nel suo reel',
    'reference.story': 'ti ha menzionato nella sua storia',
    'reference.status': 'ti ha menzionato nel suo stato',
    'friend.story': 'ha pubblicato una nuova storia',
    'friend.post': 'ha pubblicato un nuovo post',
    'friend.reel': 'ha pubblicato un nuovo reel',
    'friend.mood': 'ha pubblicato un nuovo stato d’animo',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} Chiamata {callLabel} persa',
    'call.incoming.title': '{actor} ti sta chiamando',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'Rispondi', 'call.action.decline': 'Rifiuta',
    'contact.request': 'Nuova richiesta di contatto',
    'contact.accepted': 'Richiesta di contatto accettata',
    'contact.requestAction': 'vuole entrare in contatto',
    'contact.acceptedAction': 'ha accettato la tua richiesta',
    'contact.joinedAction': 'è su Meeshy!',
    'contact.joinedBody': 'Salutalo 👋',
    'contact.joinedMany': '{actor} e altri {count} tuoi contatti sono su Meeshy!',
    'contact.joinedManyBody': 'Salutali 👋',
    'repost': 'ha condiviso {possObj}',
    'invitation.group': 'Invito al gruppo {title}',
    'invitation.direct': 'Nuova conversazione con {actor}',
    'group.added': 'Aggiunto al gruppo {title}',
    'group.newContact': 'Nuovo contatto',
    'attachment.photo': '📷 Foto',
    'attachment.video': '🎬 Video',
    'attachment.audio': '🎵 Audio',
    'attachment.document': '📎 Documento',
    'attachment.files': '📎 {count} file',
    'login.newDevice.title': 'Nuovo accesso rilevato',
    'push.private': 'Nuova notifica',
    'engagement.badgeEarned': '🏅 Distintivo sbloccato: {title} · livello {count}',
    'engagement.streakMilestone': '🔥 Serie di {count} giorni!',
    'engagement.levelUp': '⭐ Livello {count} raggiunto!',
    'engagement.achievementUnlocked': '🏆 Obiettivo sbloccato: {title}',
  },
  ar: {
    'reaction.message': 'تفاعل {emoji} مع رسالتك',
    'reaction.comment': 'تفاعل {emoji} مع تعليقك',
    'reaction.commentVerbose': '{actor} تفاعل {emoji} مع تعليقك{context}',
    'reaction.post': 'تفاعل {emoji} {reactObj}',
    'comment.your': 'علّق على {possObj}',
    'comment.generic': 'علّق على {indefObj}',
    'comment.repliedIn': 'ردّ {locObj}',
    'comment.reply': 'ردّ على تعليقك',
    'comment.replyWithParent': 'ردًّا على «{preview}»',
    'comment.repliedToYours': 'ردّ على تعليقك',
    'comment.genericFrom': 'علّق على {indefObj} لـ{author}',
    'comment.repliedInFrom': 'ردّ {locObj} لـ{author}',
    'someone': 'شخص ما',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{nounCap} من {author}',
    'comment.subtitleBare': '{nounCap}',
    'mention': 'أشار إليك',
    'reference.post': 'أشار إليك في منشور',
    'reference.reel': 'أشار إليك في ريل',
    'reference.story': 'أشار إليك في قصة',
    'reference.status': 'أشار إليك في حالة',
    'friend.story': 'نشر قصة جديدة',
    'friend.post': 'نشر منشورًا جديدًا',
    'friend.reel': 'نشر ريلًا جديدًا',
    'friend.mood': 'شارك مزاجًا جديدًا',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} مكالمة {callLabel} فائتة',
    'call.incoming.title': '{actor} يتصل بك',
    'call.incoming.body': '{callBody}',
    'call.action.answer': 'رد', 'call.action.decline': 'رفض',
    'contact.request': 'طلب تواصل جديد',
    'contact.accepted': 'تم قبول طلب التواصل',
    'contact.requestAction': 'يريد التواصل معك',
    'contact.acceptedAction': 'قبِل طلبك',
    'contact.joinedAction': 'انضم إلى Meeshy!',
    'contact.joinedBody': 'قل مرحبًا 👋',
    'contact.joinedMany': '{actor} و{count} آخرون من جهات اتصالك على Meeshy!',
    'contact.joinedManyBody': 'قل مرحبًا 👋',
    'repost': 'شارك {possObj}',
    'invitation.group': 'دعوة إلى مجموعة {title}',
    'invitation.direct': 'محادثة جديدة مع {actor}',
    'group.added': 'تمت إضافتك إلى مجموعة {title}',
    'group.newContact': 'جهة اتصال جديدة',
    'attachment.photo': '📷 صورة',
    'attachment.video': '🎬 فيديو',
    'attachment.audio': '🎵 صوت',
    'attachment.document': '📎 مستند',
    'attachment.files': '📎 {count} ملفات',
    'login.newDevice.title': 'تم رصد تسجيل دخول جديد',
    'push.private': 'إشعار جديد',
    'engagement.badgeEarned': '🏅 تم فتح شارة: {title} · المستوى {count}',
    'engagement.streakMilestone': '🔥 سلسلة {count} يوم!',
    'engagement.levelUp': '⭐ تم الوصول إلى المستوى {count}!',
    'engagement.achievementUnlocked': '🏆 تم فتح الإنجاز: {title}',
  },
  'zh-Hans': {
    'reaction.message': '用 {emoji} 回应了你的消息',
    'reaction.comment': '用 {emoji} 回应了你的评论',
    'reaction.commentVerbose': '{actor} 用 {emoji} 回应了你的评论{context}',
    'reaction.post': '用 {emoji} 回应了{reactObj}',
    'comment.your': '评论了{possObj}',
    'comment.generic': '评论了{indefObj}',
    'comment.repliedIn': '{locObj}回复了',
    'comment.reply': '回复了你的评论',
    'comment.replyWithParent': '回复 “{preview}”',
    'comment.repliedToYours': '回复了你的评论',
    'comment.genericFrom': '评论了 {author} 的{bareObj}',
    'comment.repliedInFrom': '在 {author} 的{bareObj}中回复了',
    'someone': '有人',
    'comment.subtitleOwner': '{ownerSubtitle}',
    'comment.subtitleFrom': '{author} 的{nounCap}',
    'comment.subtitleBare': '{nounCap}',
    'mention': '提到了你',
    'reference.post': '在帖子中提到了你',
    'reference.reel': '在短视频中提到了你',
    'reference.story': '在快拍中提到了你',
    'reference.status': '在状态中提到了你',
    'friend.story': '发布了新快拍',
    'friend.post': '发布了新帖子',
    'friend.reel': '发布了新短视频',
    'friend.mood': '分享了新心情',
    'friend.subtitleNew': '{friendSubtitle}',
    'call.missed': '{callIcon} 未接{callLabel}',
    'call.incoming.title': '{actor} 来电',
    'call.incoming.body': '{callBody}',
    'call.action.answer': '接听', 'call.action.decline': '拒绝',
    'contact.request': '新的联系人请求',
    'contact.accepted': '联系人请求已接受',
    'contact.requestAction': '想与你建立联系',
    'contact.acceptedAction': '接受了你的请求',
    'contact.joinedAction': '已加入 Meeshy！',
    'contact.joinedBody': '打个招呼吧 👋',
    'contact.joinedMany': '{actor} 和另外 {count} 位联系人已加入 Meeshy！',
    'contact.joinedManyBody': '打个招呼吧 👋',
    'repost': '分享了{possObj}',
    'invitation.group': '邀请你加入群组 {title}',
    'invitation.direct': '与 {actor} 的新对话',
    'group.added': '已加入群组 {title}',
    'group.newContact': '新联系人',
    'attachment.photo': '📷 照片',
    'attachment.video': '🎬 视频',
    'attachment.audio': '🎵 音频',
    'attachment.document': '📎 文档',
    'attachment.files': '📎 {count} 个文件',
    'login.newDevice.title': '检测到新登录',
    'push.private': '新通知',
    'engagement.badgeEarned': '🏅 徽章解锁：{title} · 第 {count} 级',
    'engagement.streakMilestone': '🔥 连续 {count} 天！',
    'engagement.levelUp': '⭐ 达到第 {count} 级！',
    'engagement.achievementUnlocked': '🏆 成就解锁：{title}',
  },
};
