import type { CallControlsCatalog } from '@/lib/i18n-call-controls-catalog';

const es = {
  'callControls.invite': 'Añadir',
  'callControls.invite.label': 'Añadir personas a la llamada',
  'callControls.react': 'Reaccionar',
  'callControls.react.label': 'Enviar una reacción',
  'callControls.react.palette': 'Reacciones',
  'callControls.react.send': 'Reaccionar con {emoji}',
  'callControls.react.from': '{name} reaccionó {emoji}',
  'callControls.react.mine': 'Reaccionaste {emoji}',
  'callControls.people.title': 'Participantes',
  'callControls.people.inCall': 'En la llamada',
  'callControls.people.add': 'Añadir personas',
  'callControls.people.search': 'Buscar un contacto',
  'callControls.people.empty': 'Todos tus contactos ya están en la llamada',
  'callControls.people.none': 'Ningún contacto coincide',
  'callControls.people.invite': 'Invitar',
  'callControls.people.inviteNamed': 'Invitar a {name}',
  'callControls.people.loading': 'Cargando contactos…',
  'callControls.people.you': 'Tú',
  'callControls.close': 'Cerrar',
  'callControls.ringing': 'Sonando…',
  'callControls.invite.declined': '{name} rechazó la llamada',
  'callControls.invite.unanswered': '{name} no respondió',
  'callControls.moderate.menu': 'Opciones para {name}',
  'callControls.mute': 'Silenciar micrófono',
  'callControls.mute.done': 'Micrófono silenciado',
  'callControls.remove': 'Quitar de la llamada',
  'callControls.remove.confirm': '¿Quitar a {name} de la llamada?',
  'callControls.remove.detail': 'La llamada terminará enseguida para {name}.',
  'callControls.remove.do': 'Quitar',
  'callControls.cancel': 'Cancelar',
  'callControls.mutedBy': '{name} silenció tu micrófono',
  'callControls.someone': 'Un participante',
  'callControls.incomingInvite': '{name} te invita a una llamada de grupo',
  'callControls.error.invite': 'No se pudo invitar a {name}',
  'callControls.error.mute': 'No se pudo silenciar a {name}',
  'callControls.error.remove': 'No se pudo quitar a {name}',
  'callControls.error.notContact': '{name} no está en tus contactos',
  'callControls.error.alreadyIn': '{name} ya está en la llamada',
  'callControls.error.full': 'La llamada está completa',
  'callControls.error.rateLimited': 'Demasiados intentos: vuelve a intentarlo en un momento',
  'callControls.error.denied': 'No tienes este derecho en esta llamada',
  'callControls.error.notActive': 'La llamada ya no está activa',
  'callControls.error.gone': '{name} ya no está en la llamada',
  'callControls.record.title': '¿Qué quieres grabar?',
  'callControls.record.audio': 'Solo audio',
  'callControls.record.audioDetail': 'Las voces de todos',
  'callControls.record.video': 'Audio y vídeo',
  'callControls.record.videoDetail': 'Las imágenes visibles y las voces',
  'callControls.capture': 'Capturar',
  'callControls.capture.label': 'Capturar la llamada',
  'callControls.back': 'Atrás',
  'callControls.journal': 'Diario',
  'callControls.journal.label': 'Abrir el diario de la llamada',
  'callControls.journal.live': 'Volver al directo',
  'callControls.journal.empty': 'Aún no hay nada transcrito. Activa los subtítulos: cada frase dicha aparece aquí con su traducción, durante toda la llamada.',
  'callControls.journal.original': 'Original',
  'callControls.camera.denied': 'El acceso a la cámara está denegado',
  'callControls.camera.failed': 'No se pudo abrir la cámara',
  'callControls.cameraPicker': 'Cámara',
  'callControls.cameraPicker.label': 'Elegir la cámara',
  'callControls.cameraPicker.unnamed': 'Cámara {n}',
  'callControls.pip': 'PiP',
  'callControls.camera.options': 'Opciones de mi cámara',
  'callControls.selfTile.small': 'Mi miniatura: pequeña',
  'callControls.selfTile.medium': 'Mi miniatura: mediana',
  'callControls.selfTile.large': 'Mi miniatura: grande',
  'callControls.selfTile.hint': 'Toca para intercambiar los vídeos; arrástrala o usa las flechas para moverla',
  'callControls.selfTile.corner.top-left': 'Mi miniatura: arriba a la izquierda',
  'callControls.selfTile.corner.top-right': 'Mi miniatura: arriba a la derecha',
  'callControls.selfTile.corner.bottom-left': 'Mi miniatura: abajo a la izquierda',
  'callControls.selfTile.corner.bottom-right': 'Mi miniatura: abajo a la derecha',
} satisfies CallControlsCatalog;

export default es;
