import type { SessionsCatalog } from '@/lib/i18n-sessions-catalog';

const en = {
  'sessions.title': 'Security',
  'sessions.back': 'Back',
  'sessions.section': 'Sessions',
  'sessions.intro': 'The devices signed in to your account. Close any session you don’t recognize.',
  'sessions.current': 'This device',
  'sessions.trusted': 'Trusted device',
  'sessions.unknownDevice': 'Unknown device',
  'sessions.field.app': 'Meeshy',
  'sessions.field.platform': 'Platform',
  'sessions.field.device': 'Device',
  'sessions.field.system': 'System',
  'sessions.field.browser': 'Browser',
  'sessions.field.ip': 'IP address',
  'sessions.field.place': 'Location',
  'sessions.field.timezone': 'Time zone',
  'sessions.field.opened': 'Opened on',
  'sessions.field.lastActive': 'Last active',
  'sessions.field.method': 'Sign-in',
  'sessions.version': 'Version {version}',
  'sessions.versionBuild': 'Version {version} ({build})',
  'sessions.place.approximate': '{place} · approximate',
  'sessions.platform.web': 'Web browser',
  'sessions.platform.pwa': 'Installed web app',
  'sessions.platform.android-shell': 'Android app',
  'sessions.platform.ios': 'iOS app',
  'sessions.method.password': 'Password',
  'sessions.method.two_factor': 'Password and verification code',
  'sessions.method.magic_link': 'Email sign-in link',
  'sessions.method.registration': 'Sign-up',
  'sessions.method.email_verification': 'Email verification',
  'sessions.method.oauth': 'External account',
  'sessions.method.anonymous': 'Access without an account',
  'sessions.revoke': 'Close this session',
  'sessions.revoke.label': 'Close the session on {device}',
  'sessions.revoke.title': 'Close this session?',
  'sessions.revoke.body': '{device} will be signed out and will have to sign in again.',
  'sessions.revoke.done': 'Session closed',
  'sessions.revoke.error': 'The session couldn’t be closed. Try again.',
  'sessions.others': 'Sign out other devices',
  'sessions.others.title': 'Sign out other devices?',
  'sessions.others.body': 'Every session except this one will be closed.',
  'sessions.others.done.one': 'One session closed',
  'sessions.others.done.other': '{count} sessions closed',
  'sessions.others.none': 'No other device is signed in.',
  'sessions.others.error': 'The other sessions couldn’t be closed. Try again.',
  'sessions.cancel': 'Cancel',
  'sessions.empty.title': 'No active session',
  'sessions.empty.body': 'Your signed-in devices will appear here.',
  'sessions.loading': 'Loading sessions…',
  'sessions.error.title': 'Sessions couldn’t be loaded.',
  'sessions.error.retry': 'Try again',
  'sessions.offline': 'Offline: the list may be out of date, and no session can be closed.',
  'sessions.signedOut': 'Your session has expired. Sign in again to see your devices.',
  'sessions.attribution.note': 'Approximate locations, derived from the IP address.',
  'sessionEnd.title': 'Session closed',
  'sessionEnd.admin_revoke': 'Your session was closed by the Meeshy team.',
  'sessionEnd.admin_revoke.help': 'If you think this is a mistake, contact us.',
  'sessionEnd.user_revoke': 'This session was closed from another one of your devices.',
  'sessionEnd.password_changed': 'Your account password changed. Sign in with the new one.',
  'sessionEnd.logout': 'You were signed out of this device.',
  'sessionEnd.logout_all_devices': 'All sessions on your account were closed.',
  'sessionEnd.session_expired': 'Your session has expired. Sign in again.',
  'sessionEnd.contact': 'Contact the team',
  'sessionEnd.ok': 'Got it',
} satisfies SessionsCatalog;

export default en;
