import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const es = {
  'admin.role': 'Tu rol: {role}',
  'admin.denied.title': 'Zona reservada',
  'admin.denied.message': 'Esta zona requiere un permiso de administración.',
  'admin.counters.title': 'De un vistazo',
  'admin.counters.unavailable': 'Contadores no disponibles por ahora.',
  'admin.counters.users': 'Cuentas',
  'admin.counters.activeUsers': 'Cuentas activas',
  'admin.counters.messages': 'Mensajes',
  'admin.counters.communities': 'Comunidades',
  'admin.counters.reports': 'Denuncias',
  'admin.counters.newUsers': 'Nuevas (24 h)',
  'admin.sections.title': 'Secciones',
  'admin.nav.dashboard': 'Panel',
  'admin.nav.users': 'Cuentas',
  'admin.nav.moderation': 'Moderación',
  'admin.nav.audit': 'Registros de auditoría',
  'admin.nav.analytics': 'Estadísticas',
  'admin.nav.trackingLinks': 'Enlaces de seguimiento',
  'admin.nav.ranking': 'Clasificación',
  'admin.nav.broadcasts': 'Difusiones',
  'admin.nav.settings': 'Ajustes',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Supervisión',
  'admin.users.search': 'Buscar una cuenta',
  'admin.users.count': '{count} cuenta(s)',
  'admin.users.empty': 'Ninguna cuenta coincide.',
  'admin.users.unavailable': 'Lista no disponible por ahora.',
  'admin.users.inactive': 'desactivada',
  'admin.users.previous': 'Anteriores',
  'admin.users.next': 'Siguientes',
  'admin.user.title': 'Miembro',
  'admin.user.unavailable': 'Ficha no disponible por ahora.',
  'admin.user.identity': 'Identidad',
  'admin.user.account': 'Cuenta',
  'admin.user.created': 'Se unió el',
  'admin.user.lastActive': 'Última actividad',
  'admin.user.twoFactor': 'Doble factor',
  'admin.user.enabled': 'activado',
  'admin.user.deleted': 'eliminada',
  'admin.user.role': 'Rol',
  'admin.edit.open': 'Editar',
  'admin.edit.title': 'Editar miembro',
  'admin.edit.displayName': 'Nombre visible',
  'admin.edit.email': 'Correo',
  'admin.edit.bio': 'Biografía',
  'admin.edit.active': 'Cuenta activa',
  'admin.edit.save': 'Guardar',
  'admin.edit.reason': 'Motivo (opcional)',
  'admin.edit.warnRole': 'Cambiar el rol modifica sus permisos.',
  'admin.edit.warnDeactivate': 'Desactivar cierra sus sesiones abiertas.',
  'admin.edit.confirm': 'Confirmar',
  'admin.edit.saved': 'Cambios guardados',
  'admin.edit.failed': 'No se pudo guardar',
  'admin.password.title': 'Restablecer la contraseña',
  'admin.password.warn': 'Esto cierra todas sus sesiones abiertas.',
  'admin.password.generated': 'Cópiala ahora: no volverá a mostrarse.',
  'admin.password.copy': 'Copiar',
  'admin.password.copied': 'Copiada',
  'admin.password.apply': 'Restablecer',
  'admin.password.done': 'Contraseña restablecida',
  'admin.password.failed': 'No se pudo restablecer',
  'admin.ban.open': 'Bloquear',
  'admin.ban.title': 'Bloquear a este miembro',
  'admin.ban.reason': 'Motivo (obligatorio)',
  'admin.ban.permanent': 'Bloqueo permanente',
  'admin.ban.until': 'Hasta',
  'admin.ban.apply': 'Bloquear',
  'admin.ban.lift': 'Levantar',
  'admin.ban.active': 'vigente',
  'admin.ban.expired': 'caducado',
  'admin.ban.lifted': 'levantado',
  'admin.ban.none': 'Sin bloqueos',
  'admin.ban.done': 'Bloqueo registrado',
  'admin.ban.failed': 'No se pudo bloquear',
  'admin.media.title': 'Medios',
  'admin.media.empty': 'Sin medios',
  'admin.media.protected': 'protegido',
  'admin.media.fromPost': 'publicación',
  'admin.media.fromMessage': 'mensaje',
  'admin.conv.title': 'Conversaciones',
  'admin.conv.empty': 'Sin conversaciones',
  'admin.conv.members': '{count} miembros',
  'admin.nav.conversations': 'Conversaciones',
  'admin.convList.search': 'Buscar una conversación',
  'admin.convList.count': '{count} conversación(es)',
  'admin.convList.empty': 'Ninguna conversación coincide.',
  'admin.convList.unavailable': 'Lista no disponible por ahora.',
  'admin.convList.members': '{count} miembros',
  'admin.convList.sovereign': 'Reservado al rango de administración.',
  'admin.convDetail.title': 'Lectura de una conversación',
  'admin.convDetail.reasonLabel': 'Motivo de la lectura',
  'admin.convDetail.reasonHint': 'Diez caracteres mínimo, registrado con su nombre.',
  'admin.convDetail.read': 'Leer la conversación',
  'admin.convDetail.empty': 'Ningún mensaje',
  'admin.convDetail.memberPrism': 'Leído en el prisma del miembro: {languages}',
  'admin.agent.title': 'Control del agente',
  'admin.agent.denied': 'Este control exige un permiso propio.',
  'admin.agent.users': 'Miembros dirigidos',
  'admin.agent.tracked': 'Conversaciones seguidas',
  'admin.agent.empty': 'Nada que mostrar.',
  'admin.offline': 'Sin conexión.',
  'admin.agent.scan': 'Escaneo en curso: {node}',
  'admin.agent.relaunch': 'Volver a lanzar el agente',
  'admin.agent.effect': 'Rehace el estudio y puede publicar un mensaje.',
  'admin.agent.done': 'Lanzamiento solicitado',
  'admin.agent.failed': 'Rechazada',
  'admin.agent.stop': 'Detener el escaneo',
  'admin.agent.halted': 'Escaneo detenido',
  'admin.agent.down': 'Servicio del agente inaccesible.',
  'admin.agent.logs': 'Registro de escaneos',
  'admin.tab.profile': 'Perfil',
  'admin.tab.preferences': 'Preferencias',
  'admin.tab.conversations': 'Conversaciones',
  'admin.tab.media': 'Multimedia',
  'admin.tab.security': 'Seguridad',
  'admin.tab.activity': 'Actividad',
  'admin.carousel.title': 'Imágenes',
  'admin.carousel.empty': 'Sin imágenes',
  'admin.carousel.avatar': 'Foto de perfil',
  'admin.carousel.banner': 'Banner',
  'admin.carousel.previous': 'Imagen anterior',
  'admin.carousel.next': 'Imagen siguiente',
  'admin.carousel.position': '{index} de {count}',
  'admin.carousel.open': 'Ver la imagen completa',
  'admin.carousel.close': 'Cerrar la imagen',
  'admin.user.completion': 'Perfil completado al {percent} %',
  'admin.user.names': 'Nombre y apellidos',
  'admin.user.phone': 'Teléfono',
  'admin.user.timezone': 'Zona horaria',
  'admin.user.languages': 'Idiomas',
  'admin.user.systemLanguage': 'Idioma principal',
  'admin.user.regionalLanguage': 'Idioma secundario',
  'admin.user.customLanguage': 'Idioma personalizado',
  'admin.user.deviceLocale': 'Idioma del dispositivo',
  'admin.user.updated': 'Modificado el',
  'admin.user.birthDate': 'Fecha de nacimiento',
  'admin.user.verifications': 'Verificaciones',
  'admin.user.emailVerified': 'Correo verificado',
  'admin.user.phoneVerified': 'Teléfono verificado',
  'admin.user.ageVerified': 'Edad verificada',
  'admin.user.notVerified': 'no verificado',
  'admin.user.securityTitle': 'Seguridad de la cuenta',
  'admin.user.locked': 'Bloqueado hasta el {date}',
  'admin.user.failedLogins': 'Inicios de sesión fallidos',
  'admin.user.lastPasswordChange': 'Contraseña cambiada el',
  'admin.user.consents': 'Consentimientos',
  'admin.user.consent.voiceProfile': 'Perfil de voz',
  'admin.user.consent.voiceData': 'Datos de voz',
  'admin.user.consent.dataProcessing': 'Tratamiento de datos',
  'admin.user.consent.analytics': 'Analítica',
  'admin.user.consent.voiceCloning': 'Clonación de voz',
  'admin.user.terms': 'Condiciones aceptadas (v{version})',
  'admin.user.engagement': 'Participación',
  'admin.user.streak': 'Racha: {current} d (récord {longest} d)',
  'admin.user.pending': 'Pendiente de confirmación',
  'admin.user.blocked': 'Cuentas bloqueadas',
  'admin.user.metadata': 'Metadatos',
  'admin.user.none': '—',
  'admin.stats.title': 'Estadísticas',
  'admin.stats.messages': 'Mensajes enviados',
  'admin.stats.conversations': 'Conversaciones',
  'admin.stats.translations': 'Traducciones',
  'admin.stats.posts': 'Publicaciones',
  'admin.stats.stories': 'Historias',
  'admin.stats.reels': 'Reels',
  'admin.stats.comments': 'Comentarios',
  'admin.stats.reactions': 'Reacciones',
  'admin.stats.attachments': 'Archivos adjuntos',
  'admin.stats.friends': 'Amigos',
  'admin.stats.friendRequests': 'Solicitudes de amistad pendientes',
  'admin.stats.contacts': 'Contactos',
  'admin.stats.communities': 'Comunidades',
  'admin.stats.reportsReceived': 'Denuncias recibidas',
  'admin.stats.reportsMade': 'Denuncias realizadas',
  'admin.stats.sessions': 'Sesiones activas',
  'admin.stats.bans': 'Suspensiones',
  'admin.stats.memberDays': 'Días como miembro',
  'admin.stats.shareLinks': 'Enlaces para compartir',
  'admin.stats.trackingLinks': 'Enlaces de seguimiento',
  'admin.stats.affiliations': 'Referidos',
  'admin.stats.unavailable': 'Estadísticas no disponibles por ahora.',
  'admin.pref.title': 'Preferencias del miembro',
  'admin.pref.reason': 'Motivo (opcional)',
  'admin.pref.cat.privacy': 'Privacidad',
  'admin.pref.cat.audio': 'Audio',
  'admin.pref.cat.message': 'Mensajes',
  'admin.pref.cat.notification': 'Notificaciones',
  'admin.pref.cat.video': 'Vídeo',
  'admin.pref.cat.document': 'Documentos',
  'admin.pref.cat.application': 'Aplicación',
  'admin.pref.default': 'predeterminado',
  'admin.pref.custom': 'personalizado',
  'admin.pref.readOnly': 'solo lectura',
  'admin.pref.saved': 'Preferencia guardada',
  'admin.pref.failed': 'Preferencia no guardada',
  'admin.pref.consent': 'El miembro no ha dado este consentimiento',
  'admin.pref.unavailable': 'Preferencias no disponibles por ahora.',
  'admin.conv.sort': 'Ordenar por',
  'admin.conv.sort.lastMessageAt': 'Última actividad',
  'admin.conv.sort.createdAt': 'Creación',
  'admin.conv.sort.title': 'Título',
  'admin.conv.sort.joinedAt': 'Llegada del miembro',
  'admin.conv.order.asc': 'Ascendente',
  'admin.conv.order.desc': 'Descendente',
  'admin.conv.search': 'Buscar una conversación',
  'admin.conv.filterType': 'Tipo',
  'admin.conv.filterRole': 'Rol del miembro',
  'admin.conv.all': 'Todos',
  'admin.conv.messages': '{count} mensajes',
  'admin.conv.memberRole': 'Rol: {role}',
  'admin.conv.role.creator': 'Creador',
  'admin.conv.role.admin': 'Administrador',
  'admin.conv.role.moderator': 'Moderador',
  'admin.conv.role.member': 'Miembro',
  'admin.conv.closed': 'cerrada',
  'admin.conv.archived': 'archivada',
  'admin.conv.read': 'Leer',
  'admin.conv.configure': 'Configurar',
  'admin.convSettings.title': 'Configurar la conversación',
  'admin.convSettings.titleField': 'Título',
  'admin.convSettings.description': 'Descripción',
  'admin.convSettings.avatar': 'Imagen (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Quién puede escribir',
  'admin.convSettings.writeRole.everyone': 'Todos',
  'admin.convSettings.writeRole.member': 'Los miembros',
  'admin.convSettings.writeRole.moderator': 'Moderadores y superiores',
  'admin.convSettings.writeRole.admin': 'Administradores y superiores',
  'admin.convSettings.writeRole.creator': 'Solo el creador',
  'admin.convSettings.announcement': 'Canal de anuncios',
  'admin.convSettings.slowMode': 'Modo lento (segundos)',
  'admin.convSettings.autoTranslate': 'Traducción automática',
  'admin.convSettings.archive': 'Archivar',
  'admin.convSettings.restore': 'Restaurar',
  'admin.convSettings.close': 'Cerrar a la escritura',
  'admin.convSettings.reopen': 'Reabrir',
  'admin.convSettings.memberRole': 'Rol de este miembro',
  'admin.convSettings.remove': 'Quitar de la conversación',
  'admin.convSettings.reason': 'Motivo (mínimo 10 caracteres)',
  'admin.convSettings.confirm': 'Confirmar',
  'admin.convSettings.save': 'Guardar',
  'admin.convSettings.saved': 'Conversación actualizada',
  'admin.convSettings.removed': 'Miembro quitado',
  'admin.convSettings.failed': 'Cambio rechazado',
  'admin.convSettings.creatorProtected': 'El creador no puede ser degradado ni quitado',
  'admin.security.sessions': 'Sesiones',
  'admin.security.current': 'activa',
  'admin.security.revoked': 'revocada',
  'admin.security.revoke': 'Revocar',
  'admin.security.revoked.done': 'Sesión revocada',
  'admin.security.events': 'Eventos de seguridad',
  'admin.security.severity': 'Gravedad',
  'admin.security.empty': 'Sin eventos',
  'admin.security.bans': 'Historial de suspensiones',
  'admin.security.unavailable': 'Seguridad no disponible por ahora.',
  'admin.account.open': 'Seguridad y verificaciones',
  'admin.account.unlock': 'Desbloquear la cuenta',
  'admin.account.twoFactorOff': 'Desactivar la verificación en dos pasos',
  'admin.account.twoFactorOn': 'Activar la verificación en dos pasos',
  'admin.account.done': 'Cuenta actualizada',
  'admin.account.failed': 'Cambio de cuenta rechazado',
  'admin.activity.reportsMade': 'Denuncias realizadas',
  'admin.activity.reportedMessages': 'Mensajes denunciados',
  'admin.activity.hiddenContent': 'Contenido oculto',
  'admin.activity.links': 'Enlaces creados',
  'admin.activity.friendRequests': 'Solicitudes de amistad',
  'admin.activity.empty': 'Nada que mostrar',
  'admin.activity.unavailable': 'Actividad no disponible por ahora.',
  'admin.edit.firstName': 'Nombre',
  'admin.edit.lastName': 'Apellidos',
  'admin.edit.username': 'Nombre de usuario',
  'admin.edit.phone': 'Teléfono',
  'admin.edit.phoneCountryCode': 'Prefijo del país',
  'admin.edit.timezone': 'Zona horaria',
  'admin.edit.banner': 'Banner (URL)',
  'admin.user.id': 'Identificador',
  'admin.user.onboarding': 'Bienvenida completada',
  'admin.user.engagementScore': 'Puntuación de participación',
  'admin.user.meeshBalance': 'Saldo Meesh',
  'admin.user.meeshMinted': 'Meesh ganados en total',
  'admin.user.deviceCountry': 'País del dispositivo',
  'admin.user.participations': 'Participaciones',
  'admin.stats.more': 'Todas las estadísticas',
  'admin.pref.edit': 'Editar: {category}',
  'admin.carousel.unavailable': 'Imágenes no disponibles por ahora.',
  'admin.conv.type.direct': 'Directa',
  'admin.conv.type.group': 'Grupo',
  'admin.conv.type.public': 'Pública',
  'admin.conv.type.global': 'Global',
  'admin.conv.type.broadcast': 'Difusión',
  'admin.security.severity.low': 'Baja',
  'admin.security.severity.medium': 'Media',
  'admin.security.severity.high': 'Alta',
  'admin.security.severity.critical': 'Crítica',
  'admin.report.type.spam': 'Spam',
  'admin.report.type.inappropriate': 'Contenido inapropiado',
  'admin.report.type.harassment': 'Acoso',
  'admin.report.type.violence': 'Violencia',
  'admin.report.type.hateSpeech': 'Discurso de odio',
  'admin.report.type.fakeProfile': 'Perfil falso',
  'admin.report.type.impersonation': 'Suplantación de identidad',
  'admin.report.type.other': 'Otro',
  'admin.report.target.message': 'Mensaje',
  'admin.report.target.user': 'Cuenta',
  'admin.report.target.conversation': 'Conversación',
  'admin.report.target.community': 'Comunidad',
  'admin.status.pending': 'Pendiente',
  'admin.status.underReview': 'En revisión',
  'admin.status.resolved': 'Resuelto',
  'admin.status.rejected': 'Rechazado',
  'admin.status.dismissed': 'Desestimado',
  'admin.status.accepted': 'Aceptada',
  'admin.status.blocked': 'Bloqueado',
  'admin.status.success': 'Correcto',
  'admin.status.failed': 'Fallido',
  'admin.security.lastActiveOn': 'Última actividad: {date}',
  'admin.ban.untilDate': 'hasta el {date}',
  'admin.activity.sentTo': 'Enviada a {name}',
  'admin.activity.receivedFrom': 'Recibida de {name}',
  'admin.nav.anonymous': 'Anónimos',
  'admin.shell.menu': 'Menú de administración',
  'admin.shell.fold': 'Plegar el menú',
  'admin.shell.unfold': 'Desplegar el menú',
  'admin.shell.open': 'Abrir el menú',
  'admin.shell.close': 'Cerrar el menú',
  'admin.shell.backToApp': 'Volver a la aplicación',
  'admin.list.filters': 'Filtros',
  'admin.list.all': 'Todos',
  'admin.list.yes': 'Sí',
  'admin.list.no': 'No',
  'admin.list.reset': 'Restablecer',
  'admin.list.pageSize': 'Por página',
  'admin.list.range': '{from}–{to} de {total}',
  'admin.list.sortBy': 'Ordenar por {column}',
  'admin.col.member': 'Miembro',
  'admin.col.email': 'Correo',
  'admin.col.role': 'Rol',
  'admin.col.status': 'Estado',
  'admin.col.created': 'Registro',
  'admin.col.lastActive': 'Última actividad',
  'admin.col.joined': 'Llegada',
  'admin.col.language': 'Idioma',
  'admin.col.conversation': 'Conversación',
  'admin.col.messages': 'Mensajes',
  'admin.col.name': 'Nombre',
  'admin.filter.active': 'Activos',
  'admin.filter.inactive': 'Desactivados',
  'admin.filter.emailVerified': 'Correo verificado',
  'admin.filter.twoFactor': 'Doble factor',
  'admin.anonymous.search': 'Buscar un anónimo',
  'admin.anonymous.empty': 'Ningún anónimo coincide.',
  'admin.anonymous.unavailable': 'Lista no disponible por ahora.',
  'admin.anonymous.title': 'Participante anónimo',
  'admin.anonymous.left': 'Salió',
  'admin.anonymous.permissions': 'Permisos',
  'admin.anonymous.openConversation': 'Leer la conversación',
  'admin.col.type': 'Tipo',
  'admin.col.members': 'Miembros',
  'admin.col.createdOn': 'Creación',
  'admin.col.lastMessage': 'Último mensaje',
  'admin.tab.contacts': 'Contactos',
  'admin.tab.communities': 'Comunidades',
  'admin.tab.voice': 'Perfil de voz',
  'admin.tab.reports': 'Denuncias',
  'admin.tab.label': 'Secciones de la ficha',
  'admin.dossier.empty': 'Nada que mostrar.',
  'admin.dossier.restricted': 'Reservado a administradores habilitados para datos sensibles.',
  'admin.contacts.sent': 'Enviada',
  'admin.contacts.received': 'Recibida',
  'admin.contacts.direction': 'Solicitud',
  'admin.contacts.links': '{share} enlace(s) compartido(s) · {tracking} enlace(s) de seguimiento · {affiliate} token(s) de afiliación',
  'admin.communities.creator': 'Creador',
  'admin.communities.private': 'Privada',
  'admin.voice.none': 'Ningún perfil de voz registrado.',
  'admin.voice.samples': 'Muestras',
  'admin.voice.duration': 'Duración grabada',
  'admin.voice.model': 'Modelo',
  'admin.voice.consents': 'Consentimientos',
  'admin.voice.consentProfile': 'Perfil de voz',
  'admin.voice.consentData': 'Datos de voz',
  'admin.voice.consentCloning': 'Clonación de voz',
  'admin.voice.notGiven': 'no otorgado',
  'admin.voice.traced': 'Esta consulta queda registrada en el registro de auditoría.',
  'admin.security.device': 'Dispositivo',
  'admin.security.place': 'Lugar',
  'admin.security.ip': 'Dirección IP',
  'admin.security.valid': 'Abierta',
  'admin.security.closed': 'Cerrada',
  'admin.security.event': 'Evento',
  'admin.col.date': 'Fecha',
  'admin.reports.filed': 'Denuncias hechas por este miembro',
  'admin.reports.received': 'Sus mensajes denunciados',
  'admin.reports.subject': 'Objeto',
  'admin.reports.reporter': 'Denunciado por',
  'admin.reports.reason': 'Motivo',
  'admin.reports.message': 'Mensaje',
  'admin.reports.withheld': 'texto reservado a la moderación',
  'admin.anonymous.link': 'Entró por el enlace',
  'admin.gallery.title': 'Imágenes',
  'admin.gallery.empty': 'Ninguna imagen',
  'admin.gallery.previous': 'Imagen anterior',
  'admin.gallery.next': 'Imagen siguiente',
  'admin.gallery.avatar': 'Foto de perfil',
  'admin.gallery.banner': 'Portada',
  'admin.gallery.position': 'Imagen {n} de {total}',
  'admin.meta.title': 'Metadatos',
  'admin.meta.name': 'Nombre completo',
  'admin.meta.systemLanguage': 'Idioma principal',
  'admin.meta.regionalLanguage': 'Idioma secundario',
  'admin.meta.customLanguage': 'Idioma de destino',
  'admin.meta.timezone': 'Zona horaria',
  'admin.meta.emailVerified': 'Correo verificado el',
  'admin.meta.phoneVerified': 'Teléfono verificado el',
  'admin.meta.completion': 'Perfil completado',
  'admin.meta.passwordChanged': 'Contraseña cambiada el',
  'admin.meta.failedLogins': 'Inicios de sesión fallidos',
  'admin.meta.lockedUntil': 'Bloqueado hasta',
  'admin.meta.lockedReason': 'Motivo del bloqueo',
  'admin.meta.deactivated': 'Desactivado el',
  'admin.meta.updated': 'Actualizado el',
  'admin.stats.messagesSent': 'Mensajes enviados',
  'admin.stats.reactionsGiven': 'Reacciones dadas',
  'admin.stats.mediaUploaded': 'Medios subidos',
  'admin.stats.pendingIn': 'Solicitudes recibidas',
  'admin.stats.pendingOut': 'Solicitudes enviadas',
  'admin.stats.reportsFiled': 'Denuncias presentadas',
  'admin.stats.activeSessions': 'Sesiones activas',
  'admin.prefs.privacy': 'Privacidad',
  'admin.prefs.notification': 'Notificaciones',
  'admin.prefs.message': 'Mensajes',
  'admin.prefs.audio': 'Audio y voz',
  'admin.prefs.video': 'Vídeo',
  'admin.prefs.document': 'Documentos',
  'admin.prefs.application': 'Aplicación',
  'admin.prefs.notice': 'Cada cambio se aplica al miembro en todos sus dispositivos y queda registrado en el registro de auditoría.',
  'admin.prefs.readOnly': 'solo lectura',
  'admin.prefs.saved': 'Preferencia guardada',
  'admin.prefs.failed': 'No se pudo guardar la preferencia',
  'admin.prefs.consent': 'Rechazado: el miembro no ha dado el consentimiento que requiere esta opción',
  'admin.prefs.reserved': 'Rechazado: su rol no permite modificar a este miembro',
  'admin.prefs.invalid': 'Rechazado: valor no válido',
  'admin.list.sort': 'Orden',
  'admin.list.order': 'Sentido',
  'admin.list.newest': 'Más recientes primero',
  'admin.list.oldest': 'Más antiguas primero',
  'admin.conv.manage': 'Gestionar',
} satisfies AdminInterfaceCatalog;

export default es;
