/**
 * LE CATALOGUE D'INTERFACE D'ADMINISTRATION FRANÇAIS (#6871, #6834) — la
 * SOURCE DES CLÉS `admin.*`, sorties de `catalog-fr.ts` parce qu'un lecteur
 * qui n'ouvre jamais `/adm` les payait quand même : 84 clés sur 629, 13 % du
 * poids que TOUT lecteur téléchargeait. Chargé SEULEMENT à l'entrée d'un
 * écran d'administration (`i18n-admin-catalog.ts`), jamais au démarrage.
 *
 * Les six autres langues portent exactement ces clés : `satisfies
 * AdminInterfaceCatalog` le vérifie à la compilation,
 * `i18n-admin-catalog.test.ts` le mesure à l'exécution — même discipline que
 * `catalog-fr.ts` pour le catalogue commun. `admin.title` seul reste dans ce
 * dernier : la rangée des Réglages et le menu flottant le lisent sans jamais
 * entrer dans l'administration.
 */
const fr = {
  'admin.role': 'Votre rôle : {role}',
  'admin.denied.title': 'Espace réservé',
  'admin.denied.message': 'Cet espace demande un droit d\'administration.',
  'admin.counters.title': 'En un coup d\'œil',
  'admin.counters.unavailable': 'Compteurs indisponibles pour le moment.',
  'admin.counters.users': 'Comptes',
  'admin.counters.activeUsers': 'Comptes actifs',
  'admin.counters.messages': 'Messages',
  'admin.counters.communities': 'Communautés',
  'admin.counters.reports': 'Signalements',
  'admin.counters.newUsers': 'Nouveaux (24 h)',
  'admin.sections.title': 'Sections',
  'admin.nav.dashboard': 'Tableau de bord',
  'admin.nav.users': 'Comptes',
  'admin.nav.moderation': 'Modération',
  'admin.nav.audit': 'Journaux d\'audit',
  'admin.nav.analytics': 'Statistiques',
  'admin.nav.trackingLinks': 'Liens de suivi',
  'admin.nav.ranking': 'Classement',
  'admin.nav.broadcasts': 'Diffusions',
  'admin.nav.settings': 'Réglages',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Supervision',
  'admin.users.search': 'Rechercher un compte',
  'admin.users.count': '{count} compte(s)',
  'admin.users.empty': 'Aucun compte ne correspond.',
  'admin.users.unavailable': 'Liste indisponible pour le moment.',
  'admin.users.inactive': 'désactivé',
  'admin.users.previous': 'Précédents',
  'admin.users.next': 'Suivants',
  'admin.user.title': 'Membre',
  'admin.user.unavailable': 'Fiche indisponible pour le moment.',
  'admin.user.identity': 'Identité',
  'admin.user.account': 'Compte',
  'admin.user.created': 'Inscrit le',
  'admin.user.lastActive': 'Dernière activité',
  'admin.user.twoFactor': 'Second facteur',
  'admin.user.enabled': 'activé',
  'admin.user.deleted': 'supprimé',
  'admin.user.role': 'Rôle',
  'admin.edit.open': 'Modifier',
  'admin.edit.title': 'Modifier le membre',
  'admin.edit.displayName': 'Nom affiché',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Compte actif',
  'admin.edit.save': 'Enregistrer',
  'admin.edit.reason': 'Motif (facultatif)',
  'admin.edit.warnRole': 'Changer le rôle modifie ses droits.',
  'admin.edit.warnDeactivate': 'Désactiver ferme ses sessions ouvertes.',
  'admin.edit.confirm': 'Confirmer',
  'admin.edit.saved': 'Modifications enregistrées',
  'admin.edit.failed': 'Échec de l’enregistrement',
  'admin.password.title': 'Réinitialiser le mot de passe',
  'admin.password.warn': 'Cette action ferme toutes ses sessions ouvertes.',
  'admin.password.generated': 'Copiez-le maintenant : il ne sera plus affiché.',
  'admin.password.copy': 'Copier',
  'admin.password.copied': 'Copié',
  'admin.password.apply': 'Réinitialiser',
  'admin.password.done': 'Mot de passe réinitialisé',
  'admin.password.failed': 'Échec de la réinitialisation',
  'admin.ban.open': 'Bannir',
  'admin.ban.title': 'Bannir ce membre',
  'admin.ban.reason': 'Motif (obligatoire)',
  'admin.ban.permanent': 'Bannissement permanent',
  'admin.ban.until': 'Jusqu’au',
  'admin.ban.apply': 'Bannir',
  'admin.ban.lift': 'Lever',
  'admin.ban.active': 'en vigueur',
  'admin.ban.expired': 'expiré',
  'admin.ban.lifted': 'levé',
  'admin.ban.none': 'Aucun bannissement',
  'admin.ban.done': 'Bannissement enregistré',
  'admin.ban.failed': 'Échec du bannissement',
  'admin.media.title': 'Médias',
  'admin.media.empty': 'Aucun média',
  'admin.media.protected': 'protégé',
  'admin.media.fromPost': 'publication',
  'admin.media.fromMessage': 'message',
  'admin.conv.title': 'Conversations',
  'admin.conv.empty': 'Aucune conversation',
  'admin.conv.members': '{count} membres',
  'admin.nav.conversations': 'Conversations',
  'admin.convList.search': 'Rechercher une conversation',
  'admin.convList.count': '{count} conversation(s)',
  'admin.convList.empty': 'Aucune conversation ne correspond.',
  'admin.convList.unavailable': 'Liste indisponible pour le moment.',
  'admin.convList.members': '{count} membres',
  'admin.convList.sovereign': 'Réservé au rang d\'administration.',
  'admin.convDetail.title': "Lecture d'une conversation",
  'admin.convDetail.reasonLabel': 'Motif de la lecture',
  'admin.convDetail.reasonHint': 'Dix caractères minimum, consigné avec votre nom.',
  'admin.convDetail.read': 'Lire la conversation',
  'admin.convDetail.empty': 'Aucun message',
  'admin.convDetail.memberPrism': 'Lu dans le prisme du membre : {languages}',
  /* LE PILOTAGE DE L'AGENT (#6733). `admin.agent.effect` est la clé la plus
     importante du groupe : elle DIT ce que la relance fait vraiment — refaire
     l'analyse ET, par `strategist → generator → qualityGate`, publier un
     message dans la vraie conversation. Elle est rendue à côté du bouton, et
     les sept langues la portent (`admin-agent.test.tsx` vérifie que chacune
     nomme la publication, et qu'aucun libellé de bouton ne dit « analyse »).

     Les seconds segments sont COURTS (`effect`, `done`, `failed`, `down`) comme
     ceux de leurs voisins (`admin.ban.done`, `admin.password.failed`) : un nom
     de clé est payé SEPT fois dans le chunk des catalogues, et ce groupe a
     été ramené de 28 à 15 clés pour tenir sous `interface_catalogs_admin`
     (11 Ko). Ce qui manquait à l'appel a été EMPRUNTÉ plutôt que redit —
     `admin.counters.title`, `admin.counters.messages`,
     `admin.convList.unavailable`, `admin.user.enabled`,
     `admin.users.inactive`. */
  'admin.agent.title': 'Pilotage de l’agent',
  'admin.agent.denied': 'Ce pilotage demande un droit dédié.',
  'admin.agent.users': 'Membres pilotés',
  'admin.agent.tracked': 'Conversations suivies',
  'admin.agent.empty': 'Rien à afficher.',
  'admin.offline': 'Hors ligne.',
  'admin.agent.scan': 'Scan en cours : {node}',
  'admin.agent.relaunch': 'Relancer l’agent',
  'admin.agent.effect': 'Refait l’analyse et peut publier un message.',
  'admin.agent.done': 'Relance demandée',
  'admin.agent.failed': 'Refusé',
  'admin.agent.stop': 'Arrêter le scan',
  'admin.agent.halted': 'Scan arrêté',
  'admin.agent.down': 'Service agent injoignable.',
  'admin.agent.logs': 'Journal des scans',
  'admin.tab.profile': 'Profil',
  'admin.tab.preferences': 'Préférences',
  'admin.tab.conversations': 'Conversations',
  'admin.tab.media': 'Médias',
  'admin.tab.security': 'Sécurité',
  'admin.carousel.title': 'Images',
  'admin.carousel.empty': 'Aucune image',
  'admin.carousel.avatar': 'Photo de profil',
  'admin.carousel.banner': 'Bannière',
  'admin.carousel.previous': 'Image précédente',
  'admin.carousel.next': 'Image suivante',
  'admin.carousel.position': '{index} sur {count}',
  'admin.carousel.open': 'Voir l\'image en grand',
  'admin.carousel.close': 'Fermer l\'image',
  'admin.user.completion': 'Profil complété à {percent} %',
  'admin.user.names': 'Prénom et nom',
  'admin.user.phone': 'Téléphone',
  'admin.user.timezone': 'Fuseau horaire',
  'admin.user.languages': 'Langues',
  'admin.user.systemLanguage': 'Langue principale',
  'admin.user.regionalLanguage': 'Langue secondaire',
  'admin.user.customLanguage': 'Langue personnalisée',
  'admin.user.deviceLocale': 'Langue de l\'appareil',
  'admin.user.updated': 'Modifié le',
  'admin.user.birthDate': 'Date de naissance',
  'admin.user.verifications': 'Vérifications',
  'admin.user.emailVerified': 'E-mail vérifié',
  'admin.user.phoneVerified': 'Téléphone vérifié',
  'admin.user.ageVerified': 'Âge vérifié',
  'admin.user.notVerified': 'non vérifié',
  'admin.user.securityTitle': 'Sécurité du compte',
  'admin.user.locked': 'Verrouillé jusqu\'au {date}',
  'admin.user.failedLogins': 'Échecs de connexion',
  'admin.user.lastPasswordChange': 'Mot de passe changé le',
  'admin.user.consents': 'Consentements',
  'admin.user.consent.voiceProfile': 'Profil vocal',
  'admin.user.consent.voiceData': 'Données vocales',
  'admin.user.consent.dataProcessing': 'Traitement des données',
  'admin.user.consent.analytics': 'Mesure d\'audience',
  'admin.user.consent.voiceCloning': 'Clonage vocal',
  'admin.user.terms': 'CGU acceptées (v{version})',
  'admin.user.engagement': 'Engagement',
  'admin.user.streak': 'Série : {current} j (record {longest} j)',
  'admin.user.pending': 'En attente de confirmation',
  'admin.user.blocked': 'Comptes bloqués',
  'admin.user.metadata': 'Métadonnées',
  'admin.stats.title': 'Statistiques',
  'admin.stats.messages': 'Messages envoyés',
  'admin.stats.conversations': 'Conversations',
  'admin.stats.translations': 'Traductions',
  'admin.stats.posts': 'Publications',
  'admin.stats.stories': 'Stories',
  'admin.stats.reels': 'Reels',
  'admin.stats.comments': 'Commentaires',
  'admin.stats.reactions': 'Réactions',
  'admin.stats.attachments': 'Pièces jointes',
  'admin.stats.friends': 'Amis',
  'admin.stats.friendRequests': 'Demandes d\'amis en attente',
  'admin.stats.contacts': 'Contacts',
  'admin.stats.communities': 'Communautés',
  'admin.stats.reportsReceived': 'Signalements reçus',
  'admin.stats.reportsMade': 'Signalements émis',
  'admin.stats.sessions': 'Sessions actives',
  'admin.stats.bans': 'Bannissements',
  'admin.stats.memberDays': 'Jours d\'ancienneté',
  'admin.stats.shareLinks': 'Liens de partage',
  'admin.stats.trackingLinks': 'Liens de suivi',
  'admin.stats.affiliations': 'Parrainages',
  'admin.stats.unavailable': 'Statistiques indisponibles pour l\'instant.',
  'admin.pref.reason': 'Motif (facultatif)',
  'admin.pref.cat.privacy': 'Confidentialité',
  'admin.pref.cat.audio': 'Audio',
  'admin.pref.cat.message': 'Messages',
  'admin.pref.cat.notification': 'Notifications',
  'admin.pref.cat.video': 'Vidéo',
  'admin.pref.cat.document': 'Documents',
  'admin.pref.cat.application': 'Application',
  'admin.pref.default': 'par défaut',
  'admin.pref.custom': 'personnalisé',
  'admin.pref.readOnly': 'lecture seule',
  'admin.pref.saved': 'Préférence enregistrée',
  'admin.pref.failed': 'Préférence non enregistrée',
  'admin.pref.consent': 'Le membre n\'a pas donné ce consentement',
  'admin.pref.unavailable': 'Préférences indisponibles pour l\'instant.',
  'admin.conv.sort': 'Trier par',
  'admin.conv.sort.lastMessageAt': 'Dernière activité',
  'admin.conv.sort.createdAt': 'Création',
  'admin.conv.sort.title': 'Titre',
  'admin.conv.sort.joinedAt': 'Arrivée du membre',
  'admin.conv.order.asc': 'Croissant',
  'admin.conv.order.desc': 'Décroissant',
  'admin.conv.search': 'Rechercher une conversation',
  'admin.conv.filterType': 'Type',
  'admin.conv.filterRole': 'Rôle du membre',
  'admin.conv.all': 'Tous',
  'admin.conv.messages': '{count} messages',
  'admin.conv.memberRole': 'Rôle : {role}',
  'admin.conv.role.creator': 'Créateur',
  'admin.conv.role.admin': 'Administrateur',
  'admin.conv.role.moderator': 'Modérateur',
  'admin.conv.role.member': 'Membre',
  'admin.conv.closed': 'fermée',
  'admin.conv.archived': 'archivée',
  'admin.conv.read': 'Lire',
  'admin.conv.configure': 'Configurer',
  'admin.convSettings.title': 'Configurer la conversation',
  'admin.convSettings.titleField': 'Titre',
  'admin.convSettings.description': 'Description',
  'admin.convSettings.avatar': 'Image (URL)',
  'admin.convSettings.banner': 'Bannière (URL)',
  'admin.convSettings.writeRole': 'Qui peut écrire',
  'admin.convSettings.writeRole.everyone': 'Tout le monde',
  'admin.convSettings.writeRole.member': 'Les membres',
  'admin.convSettings.writeRole.moderator': 'Modérateurs et plus',
  'admin.convSettings.writeRole.admin': 'Administrateurs et plus',
  'admin.convSettings.writeRole.creator': 'Le créateur seul',
  'admin.convSettings.announcement': 'Canal d\'annonces',
  'admin.convSettings.slowMode': 'Mode lent (secondes)',
  'admin.convSettings.autoTranslate': 'Traduction automatique',
  'admin.convSettings.archive': 'Archiver',
  'admin.convSettings.restore': 'Restaurer',
  'admin.convSettings.close': 'Fermer à l\'écriture',
  'admin.convSettings.reopen': 'Rouvrir',
  'admin.convSettings.memberRole': 'Rôle de ce membre',
  'admin.convSettings.remove': 'Retirer de la conversation',
  'admin.convSettings.reason': 'Motif (10 caractères minimum)',
  'admin.convSettings.confirm': 'Confirmer',
  'admin.convSettings.save': 'Enregistrer',
  'admin.convSettings.saved': 'Conversation mise à jour',
  'admin.convSettings.removed': 'Membre retiré',
  'admin.convSettings.failed': 'Modification refusée',
  'admin.convSettings.creatorProtected': 'Le créateur ne peut être ni rétrogradé ni retiré',
  'admin.security.sessions': 'Sessions',
  'admin.security.current': 'active',
  'admin.security.revoked': 'révoquée',
  'admin.security.revoke': 'Révoquer',
  'admin.security.revoked.done': 'Session révoquée',
  'admin.security.events': 'Événements de sécurité',
  'admin.security.severity': 'Gravité',
  'admin.security.empty': 'Aucun événement',
  'admin.security.bans': 'Historique des bannissements',
  'admin.security.unavailable': 'Sécurité indisponible pour l\'instant.',
  'admin.account.open': 'Sécurité et vérifications',
  'admin.account.unlock': 'Déverrouiller le compte',
  'admin.account.twoFactorOff': 'Désactiver la double authentification',
  'admin.account.done': 'Compte mis à jour',
  'admin.account.failed': 'Modification du compte refusée',
  'admin.activity.reportsMade': 'Signalements émis',
  'admin.activity.reportedMessages': 'Messages signalés',
  'admin.activity.hiddenContent': 'Contenu masqué',
  'admin.activity.links': 'Liens créés',
  'admin.activity.friendRequests': 'Demandes d\'amis',
  'admin.activity.empty': 'Rien à afficher',
  'admin.activity.unavailable': 'Activité indisponible pour l\'instant.',
  'admin.edit.firstName': 'Prénom',
  'admin.edit.lastName': 'Nom',
  'admin.edit.username': 'Pseudo',
  'admin.edit.phone': 'Téléphone',
  'admin.edit.phoneCountryCode': 'Indicatif pays',
  'admin.edit.timezone': 'Fuseau horaire',
  'admin.edit.banner': 'Bannière (URL)',
  'admin.user.id': 'Identifiant',
  'admin.user.onboarding': 'Accueil terminé',
  'admin.user.engagementScore': 'Score d\'engagement',
  'admin.user.meeshBalance': 'Solde Meesh',
  'admin.user.meeshMinted': 'Meesh gagnés au total',
  'admin.user.deviceCountry': 'Pays de l\'appareil',
  'admin.user.participations': 'Participations',
  'admin.stats.more': 'Toutes les statistiques',
  'admin.stats.reportsOnMessages': 'Signalements sur ses messages',
  'admin.stats.withheld': 'Non communiqué',
  'admin.pref.edit': 'Modifier : {category}',
  'admin.carousel.unavailable': 'Images indisponibles pour l\'instant.',
  'admin.conv.type.direct': 'Tête-à-tête',
  'admin.conv.type.group': 'Groupe',
  'admin.conv.type.public': 'Publique',
  'admin.conv.type.global': 'Globale',
  'admin.conv.type.broadcast': 'Diffusion',
  'admin.security.severity.low': 'Faible',
  'admin.security.severity.medium': 'Moyenne',
  'admin.security.severity.high': 'Élevée',
  'admin.security.severity.critical': 'Critique',
  'admin.report.type.spam': 'Spam',
  'admin.report.type.inappropriate': 'Contenu inapproprié',
  'admin.report.type.harassment': 'Harcèlement',
  'admin.report.type.violence': 'Violence',
  'admin.report.type.hateSpeech': 'Discours haineux',
  'admin.report.type.fakeProfile': 'Faux profil',
  'admin.report.type.impersonation': 'Usurpation d\'identité',
  'admin.report.type.other': 'Autre',
  'admin.report.target.message': 'Message',
  'admin.report.target.user': 'Compte',
  'admin.report.target.conversation': 'Conversation',
  'admin.report.target.community': 'Communauté',
  'admin.status.pending': 'En attente',
  'admin.status.underReview': 'En cours d\'examen',
  'admin.status.resolved': 'Résolu',
  'admin.status.rejected': 'Refusé',
  'admin.status.dismissed': 'Classé sans suite',
  'admin.status.accepted': 'Acceptée',
  'admin.status.blocked': 'Bloqué',
  'admin.status.success': 'Réussi',
  'admin.status.failed': 'Échoué',
  'admin.security.lastActiveOn': 'Dernière activité : {date}',
  'admin.ban.untilDate': 'jusqu’au {date}',
  'admin.activity.sentTo': 'Envoyée à {name}',
  'admin.activity.receivedFrom': 'Reçue de {name}',
  'admin.nav.anonymous': 'Anonymes',
  'admin.shell.menu': 'Menu d\'administration',
  'admin.shell.fold': 'Replier le menu',
  'admin.shell.unfold': 'Déplier le menu',
  'admin.shell.open': 'Ouvrir le menu',
  'admin.shell.close': 'Fermer le menu',
  'admin.shell.backToApp': 'Retour à l\'application',
  'admin.list.all': 'Tous',
  'admin.list.yes': 'Oui',
  'admin.list.no': 'Non',
  'admin.list.reset': 'Réinitialiser',
  'admin.list.pageSize': 'Par page',
  'admin.list.range': '{from}–{to} sur {total}',
  'admin.list.sortBy': 'Trier par {column}',
  'admin.col.member': 'Membre',
  'admin.col.email': 'E-mail',
  'admin.col.role': 'Rôle',
  'admin.col.status': 'État',
  'admin.col.created': 'Inscription',
  'admin.col.lastActive': 'Dernière activité',
  'admin.col.joined': 'Arrivée',
  'admin.col.language': 'Langue',
  'admin.col.conversation': 'Conversation',
  'admin.col.messages': 'Messages',
  'admin.col.name': 'Nom',
  'admin.filter.active': 'Actifs',
  'admin.filter.inactive': 'Désactivés',
  'admin.filter.emailVerified': 'E-mail vérifié',
  'admin.filter.twoFactor': 'Double authentification',
  'admin.anonymous.search': 'Rechercher un anonyme',
  'admin.anonymous.empty': 'Aucun anonyme ne correspond.',
  'admin.anonymous.unavailable': 'Liste indisponible pour le moment.',
  'admin.anonymous.title': 'Participant anonyme',
  'admin.anonymous.left': 'Parti',
  'admin.anonymous.permissions': 'Permissions',
  'admin.anonymous.openConversation': 'Lire la conversation',
  'admin.col.type': 'Type',
  'admin.col.members': 'Membres',
  'admin.col.createdOn': 'Création',
  'admin.col.lastMessage': 'Dernier message',
  'admin.tab.contacts': 'Contacts',
  'admin.tab.communities': 'Communautés',
  'admin.tab.voice': 'Profil vocal',
  'admin.tab.reports': 'Signalements',
  'admin.tab.label': 'Sections de la fiche',
  'admin.dossier.empty': 'Rien à afficher.',
  'admin.dossier.restricted': 'Réservé aux administrateurs habilités aux données sensibles.',
  'admin.communities.creator': 'Créateur',
  'admin.communities.private': 'Privée',
  'admin.voice.none': 'Aucun profil vocal enregistré.',
  'admin.voice.samples': 'Échantillons',
  'admin.voice.duration': 'Durée enregistrée',
  'admin.voice.model': 'Modèle',
  'admin.voice.consents': 'Consentements',
  'admin.voice.consentProfile': 'Profil vocal',
  'admin.voice.consentData': 'Données vocales',
  'admin.voice.consentCloning': 'Clonage de voix',
  'admin.voice.notGiven': 'non donné',
  'admin.voice.traced': 'Cette consultation est tracée dans le journal d\'audit.',
  'admin.anonymous.link': 'Entré par le lien',
  'admin.user.deactivated': 'Désactivé le',
  'admin.stats.pendingOut': 'Demandes envoyées',
  'admin.conv.manage': 'Gérer',
} as const;

export default fr;
