import type { OnboardingCatalog } from '@/lib/i18n-onboarding-catalog';

const de = {
  'onboarding.title': 'Willkommen bei Meeshy',
  'onboarding.skipAll': 'Alles überspringen',
  'onboarding.later': 'Später',
  'onboarding.continue': 'Weiter',
  'onboarding.progress': 'Schritt {current} von {total}',
  'onboarding.offline': 'Verfügbar, sobald du online bist',
  'onboarding.points.gauge': '{points} / {target} Pkt. bis Level 1',
  'onboarding.points.level': 'Level 1 erreicht!',
  'onboarding.points.gained': '+{points}',
  'onboarding.points.announce': 'Du bekommst {points} Punkte.',

  'onboarding.languages.title': 'Deine Sprache, deine Welt',
  'onboarding.languages.body': 'Hier schreibt jeder in seiner Sprache. Du liest alles in deiner.',
  'onboarding.languages.demo.from': 'Hola, ¿qué tal?',
  'onboarding.languages.demo.fromCode': 'es',
  'onboarding.languages.demo.to': 'Hi, wie geht’s?',
  'onboarding.languages.primary': 'Deine Hauptsprache',
  'onboarding.languages.secondary': 'Eine zweite Sprache? (optional)',
  'onboarding.languages.change': 'Ändern',
  'onboarding.languages.pick': 'Wähle deine Hauptsprache',
  'onboarding.languages.confirm': 'Das ist meine Sprache',
  'onboarding.languages.failed': 'Deine Sprache wurde nicht gespeichert. Versuch es noch einmal.',

  'onboarding.global.title': 'Sag Hallo zur Welt',
  'onboarding.global.body': 'Meeshy Global ist der Treffpunkt für alle. Sag einfach Hallo, ganz ohne Druck.',
  'onboarding.global.field': 'Dein Hallo, bearbeitbar',
  'onboarding.global.shuffle': 'Andere Idee',
  'onboarding.global.send': 'Senden',
  'onboarding.global.sending': 'Wird gesendet…',
  'onboarding.global.sent': 'Hallo gesendet!',
  'onboarding.global.failed': 'Dein Hallo wurde nicht gesendet. Versuch es noch einmal.',
  'onboarding.global.unavailable': 'Meeshy Global ist gerade nicht erreichbar.',
  'onboarding.global.badge': 'Abzeichen „Erste Nachricht“',
  'onboarding.global.streak': 'Serie: 1 Tag 🔥',
  'onboarding.global.reward': '+14 Pkt. beim Senden',
  'onboarding.global.template.1': 'Hallo zusammen! Ich bin {name} und spreche {languages}. Wer wohnt hier in der Nähe [[vom Meer]]?',
  'onboarding.global.template.2': 'Hi! {name} hier 👋 Gerade höre ich [[Rap]] in Dauerschleife. Und ihr?',
  'onboarding.global.template.3': 'Hey! Ich heiße {name}. Mein Lieblingsessen: [[Pasta]]. Und eures?',
  'onboarding.global.template.4': 'Hallo! {name}, gerade angekommen. Ich suche Leute, die [[Fußball]] lieben!',
  'onboarding.global.template.5': 'Hey! Ich bin {name}. Mein kleines Glück des Tages: [[Sonnenuntergänge]].',
  'onboarding.global.template.6': 'Hallo! {name} hier, ich spreche {languages}. Ich würde gern [[Spanisch]] lernen, habt ihr Tipps?',
  'onboarding.global.template.7': 'Hallo Welt 🌍 Ich bin {name}. Meine Leidenschaft gerade: [[Fotografie]]. Wer noch?',
  'onboarding.global.template.8': 'Yo! {name} ist gerade angekommen. Bei mir ist heute [[strahlender Sonnenschein]]. Und bei euch?',

  'onboarding.story.title': 'Zeig dich',
  'onboarding.story.body': 'Freunde findest du, wenn du zeigst, wer du bist. Ein Foto, ein Satz: Das ist eine Story, nach 24 Std. ist sie weg.',
  'onboarding.story.create': 'Meine Story erstellen',
  'onboarding.story.audience.public': 'Für alle sichtbar. Du kannst das vor dem Posten ändern.',
  'onboarding.story.audience.friends': 'Für deine Freunde sichtbar. Du kannst das vor dem Posten ändern.',
  'onboarding.story.reward': '+10 Pkt. beim Posten',
  'onboarding.story.done': 'Story gepostet!',

  'onboarding.friends.title': 'Finde deine Leute',
  'onboarding.friends.body': 'Füge 3 Leute hinzu, die zu dir passen. Wenn sie annehmen, bekommt ihr beide\u00A0+7.',
  'onboarding.friends.add': 'Hinzufügen',
  'onboarding.friends.addNamed': '{name} hinzufügen',
  'onboarding.friends.added': 'Gesendet',
  'onboarding.friends.speaks': 'Spricht {languages}',
  'onboarding.friends.reward': '+7 für jeden, wenn angenommen',
  'onboarding.friends.count': '{count} / 3 Anfragen',
  'onboarding.friends.empty': 'Gerade niemand zum Vorschlagen. Der Tab Entdecken zeigt dir bald Leute.',
  'onboarding.friends.failed': 'Die Anfrage wurde nicht gesendet. Versuch es noch einmal.',

  'onboarding.notifications.title': 'Wir sagen dir Bescheid, wenn was passiert',
  'onboarding.notifications.body': 'Gleich antwortet dir jemand. Willst du es sofort wissen?',
  'onboarding.notifications.yes': 'Ja, sag mir Bescheid',
  'onboarding.notifications.no': 'Nicht jetzt',

  'onboarding.recap.title': 'Gut gemacht!',
  'onboarding.recap.calm': 'Alles bereit. Du kannst es jederzeit machen.',
  'onboarding.recap.points': '{points} Pkt.',
  'onboarding.recap.level': 'Level {level}',
  'onboarding.recap.streak.one': 'Serie: {days} Tag',
  'onboarding.recap.streak.other': 'Serie: {days} Tage',
  'onboarding.recap.badges': 'Abzeichen: {count}',
  'onboarding.recap.friends': 'Anfragen unterwegs: {count}',
  'onboarding.recap.tomorrow': 'Morgen kann deine Serie auf {next} steigen.',
  'onboarding.recap.explore': 'Weiter entdecken',
  'onboarding.recap.done': 'Genug für heute',
} satisfies OnboardingCatalog;

export default de;
