import type { OnboardingCatalog } from '@/lib/i18n-onboarding-catalog';

const it = {
  'onboarding.title': 'Benvenuto su Meeshy',
  'onboarding.skipAll': 'Salta tutto',
  'onboarding.later': 'Più tardi',
  'onboarding.continue': 'Continua',
  'onboarding.progress': 'Passo {current} di {total}',
  'onboarding.offline': 'Disponibile quando sei online',
  'onboarding.points.gauge': '{points} / {target} pt per il tuo livello 1',
  'onboarding.points.level': 'Livello 1 raggiunto!',
  'onboarding.points.gained': '+{points}',
  'onboarding.points.announce': 'Guadagni {points} punti.',

  'onboarding.languages.title': 'La tua lingua, il tuo mondo',
  'onboarding.languages.body': 'Qui ognuno scrive nella sua lingua. Tu leggi tutto nella tua.',
  'onboarding.languages.demo.from': 'Hola, ¿qué tal?',
  'onboarding.languages.demo.fromCode': 'es',
  'onboarding.languages.demo.to': 'Ciao, come va?',
  'onboarding.languages.primary': 'La tua lingua principale',
  'onboarding.languages.secondary': 'Una seconda lingua? (facoltativa)',
  'onboarding.languages.change': 'Cambia',
  'onboarding.languages.pick': 'Scegli la tua lingua principale',
  'onboarding.languages.confirm': 'È la mia lingua',
  'onboarding.languages.failed': 'La tua lingua non è stata salvata. Riprova.',

  'onboarding.global.title': 'Saluta il mondo',
  'onboarding.global.body': 'Meeshy Global è il salotto dove passano tutti. Lascia un saluto, senza pressione.',
  'onboarding.global.field': 'Il tuo saluto, modificabile',
  'onboarding.global.shuffle': 'Un’altra idea',
  'onboarding.global.send': 'Invia',
  'onboarding.global.sending': 'Invio…',
  'onboarding.global.sent': 'Saluto inviato!',
  'onboarding.global.failed': 'Il tuo saluto non è partito. Riprova.',
  'onboarding.global.unavailable': 'Meeshy Global non è raggiungibile al momento.',
  'onboarding.global.badge': 'Badge «Primo messaggio»',
  'onboarding.global.streak': 'Serie: 1 giorno 🔥',
  'onboarding.global.reward': '+14 pt all’invio',
  'onboarding.global.template.1': 'Ciao a tutti! Sono {name}, parlo {languages}. Chi vive vicino [[al mare]]?',
  'onboarding.global.template.2': 'Ciao! {name} qui 👋 In questo periodo ascolto [[rap]] a ripetizione. E voi?',
  'onboarding.global.template.3': 'Ehi! Mi chiamo {name}. Il mio piatto preferito: [[la pasta]]. Il vostro?',
  'onboarding.global.template.4': 'Ciao! {name}, appena arrivato. Cerco gente che ama [[il calcio]]!',
  'onboarding.global.template.5': 'Ehi! Sono {name}. La mia piccola gioia del giorno: [[i tramonti]].',
  'onboarding.global.template.6': 'Ciao! {name} qui, parlo {languages}. Vorrei imparare [[lo spagnolo]], qualche consiglio?',
  'onboarding.global.template.7': 'Ciao mondo 🌍 Sono {name}. La mia passione del momento: [[la fotografia]]. Chi altro?',
  'onboarding.global.template.8': 'Yo! {name} è appena arrivato. Da me oggi c’è [[un bel sole]]. E da voi?',

  'onboarding.story.title': 'Fatti vedere',
  'onboarding.story.body': 'Gli amici arrivano mostrando chi sei. Una foto, una frase: è una story, sparisce in 24 h.',
  'onboarding.story.create': 'Crea la mia story',
  'onboarding.story.audience.public': 'Visibile a tutti. Puoi cambiarlo prima di pubblicare.',
  'onboarding.story.audience.friends': 'Visibile ai tuoi amici. Puoi cambiarlo prima di pubblicare.',
  'onboarding.story.reward': '+10 pt alla pubblicazione',
  'onboarding.story.done': 'Story pubblicata!',

  'onboarding.friends.title': 'Trova la tua gente',
  'onboarding.friends.body': 'Aggiungi 3 persone simili a te. Quando accettano, guadagnate +7 entrambi.',
  'onboarding.friends.add': 'Aggiungi',
  'onboarding.friends.addNamed': 'Aggiungi {name}',
  'onboarding.friends.added': 'Inviata',
  'onboarding.friends.speaks': 'Parla {languages}',
  'onboarding.friends.reward': '+7 a testa quando accetta',
  'onboarding.friends.count': '{count} / 3 richieste',
  'onboarding.friends.empty': 'Nessuno da proporti per ora. La scheda Scopri te ne mostrerà presto.',
  'onboarding.friends.failed': 'La richiesta non è partita. Riprova.',

  'onboarding.notifications.title': 'Ti avvisiamo quando succede qualcosa',
  'onboarding.notifications.body': 'Qualcuno sta per risponderti. Vuoi saperlo subito?',
  'onboarding.notifications.yes': 'Sì, avvisami',
  'onboarding.notifications.no': 'Non ora',

  'onboarding.recap.title': 'Ben fatto!',
  'onboarding.recap.calm': 'È tutto pronto. Potrai farlo quando vuoi.',
  'onboarding.recap.points': '+{points} pt',
  'onboarding.recap.level': 'Livello 1',
  'onboarding.recap.streak': 'Serie 1 🔥',
  'onboarding.recap.badges': 'Badge: {count}',
  'onboarding.recap.friends': 'Richieste in arrivo: {count}',
  'onboarding.recap.tomorrow': 'Domani la tua serie può arrivare a 2.',
  'onboarding.recap.explore': 'Continua a esplorare',
  'onboarding.recap.done': 'Per oggi basta così',
} satisfies OnboardingCatalog;

export default it;
