import type { InterfaceCatalog } from '@/lib/i18n-catalog';
import itComposerAttach from './catalog-it-composer-attach';
import itIdentity from './catalog-it-identity';
import itVerifyEmail from './catalog-it-verify-email';
import itPassword from './catalog-it-password';
import itCall from './catalog-it-call';
import itCallJoin from './catalog-it-call-join';
import itCallShell from './catalog-it-call-shell';
import itSignup from './catalog-it-signup';

import itMentions from './catalog-it-mentions';
import itStoriesMine from './catalog-it-stories-mine';

const it = {
  'announce.messageSent': 'Messaggio inviato',
  'announce.messageCopied': 'Messaggio copiato',
  'announce.messagesCopied': 'Messaggi copiati',
  'announce.messageProtected': 'Messaggio protetto',
  'announce.selectionCap': 'Massimo {count} messaggi',
  'announce.nothingToCopy': 'Niente da copiare',

  'message.author.self': 'Tu',
  'message.excerpt.protected': 'contenuto protetto',
  'a11y.message.menu.subject': 'Azioni del messaggio di {author}: {excerpt}',

  'selection.toolbar': 'Selezione messaggi',
  'selection.cancel': 'Annulla',
  'selection.count': '{count} selezionati',
  'forward.title': 'Inoltra a…',
  'forward.empty': 'Nessuna conversazione',
  'forward.search.label': 'Cerca una conversazione',
  'forward.search.placeholder': 'Cerca',
  'forward.announce.sent': 'Messaggio inoltrato',
  'forward.announce.sentMany': '{count} messaggi inoltrati',
  'forward.announce.failed': 'Inoltro non riuscito',
  'forward.refusal.viewOnce': 'Un messaggio a visualizzazione singola non può essere inoltrato',
  'forward.refusal.unavailable': 'Il messaggio originale non è più disponibile: niente da inoltrare',

  'typing.named': '{name} sta scrivendo',
  'typing.double': '{first} e {second} stanno scrivendo',
  'typing.several': 'Più persone stanno scrivendo',

  'feed.header.reels': 'Avvia i Reel',
  'reels.title': 'Reel',
  'reels.back': 'Indietro',
  'reels.open': 'Guarda il reel di {author}',
  'reels.item': 'Reel di {author}, {index} di {count}',
  'reels.loading': 'Caricamento dei reel',
  'reels.empty': 'Nessun reel per ora',
  'reels.empty.hint': 'I reel dei tuoi contatti appariranno qui.',
  'reels.error': 'Impossibile caricare i reel',
  'reels.error.hint': 'Riprova tra un momento.',
  'reels.retry': 'Riprova',
  'reels.offline': 'Offline',
  'reels.offline.cold': 'I reel si caricheranno al ritorno della connessione.',
  'reels.action.like': 'Mi piace',
  'reels.action.bookmark': 'Salva',
  'reels.action.share': 'Condividi',
  'reels.sound.on': 'Attiva l’audio',
  'reels.sound.off': 'Disattiva l’audio',
  'reels.play': 'Riproduci il reel',
  'reels.pause': 'Metti in pausa il reel',
  'reels.media.error': 'Riproduzione impossibile — Riprova',
  'reels.image': 'Immagine {index} di {count}',

  'stories.title': 'Storie',
  'stories.loading': 'Caricamento delle storie…',
  'stories.error': 'Non è stato possibile caricare le storie.',
  'stories.empty.title': 'Nessuna storia per ora',
  'stories.empty.subtitle': 'Le storie dei tuoi contatti appariranno qui per venti ore.',
  'stories.create': 'Crea una storia',
  'stories.count.one': '{count} storia',
  'stories.count.other': '{count} storie',
  'stories.mine': 'La tua storia',

  /* #6150 — le due porte della mia cella nella barra. */
  'stories.self.addStory': 'Aggiungi una storia',
  'stories.self.mood.add': 'Imposta un umore',
  'stories.self.mood.change': 'Cambia il mio umore, {emoji}',

  'status.compose.title': 'Il mio umore',
  'status.compose.pick': 'Scegli un umore',
  'status.compose.note': 'Una parola, se vuoi',
  'status.compose.publish': 'Pubblica',
  'status.compose.publishing': 'Pubblicazione…',
  'status.compose.error': 'Non è stato possibile pubblicare il tuo umore.',
  'status.compose.offline': 'Offline — il tuo umore partirà al ritorno della rete.',

  'feed.header.create': 'Creare un post o un reel',
  'feed.create.post': 'Post',
  'feed.create.reel': 'Reel',

  'feed.post.action.like': 'Mi piace',
  'feed.post.action.comment': 'Commenta',
  'feed.post.action.repost': 'Ripubblica',
  'feed.post.action.bookmark': 'Salva',
  'feed.post.action.share': 'Condividi',
  'feed.post.media.video': 'Video',
  'feed.post.media.audio': 'Audio',
  'feed.post.media.previous': 'Media precedente',
  'feed.post.media.next': 'Media successivo',
  'feed.post.media.mosaic': 'Mosaico di {count} media',
  'media.unavailable': 'Contenuto non disponibile',
  'feed.post.see_more': 'mostra altro',
  'feed.post.see_less': 'mostra meno',
  'feed.post.more_options': 'Altre opzioni',
  'feed.post.menu.open': 'Apri',
  'feed.post.menu.copy_text': 'Copia il testo',
  'feed.post.menu.unsave': 'Rimuovi dai salvati',
  'feed.post.menu.pin': 'Fissa',
  'feed.post.menu.delete': 'Elimina',
  'feed.post.edit': 'Modifica',
  'feed.post.edit.title': 'Modifica post',
  'feed.post.edit.body.a11y': 'Contenuto del post',
  'feed.post.edit.remaining.a11y': '{count} caratteri rimanenti',
  'feed.post.edit.publish': 'Pubblica',
  'report.post.title': 'Segnala questo post',
  'feed.post.copied': 'Testo copiato',
  'feed.post.copy_failed': 'Impossibile copiare il testo',
  'feed.post.pinned': 'Post fissato',
  'feed.post.pin_failed': 'Impossibile fissare il post',
  'feed.post.edited': 'Post aggiornato',
  'feed.post.edit_failed': 'Impossibile aggiornare il post',
  'feed.post.edit_busy': 'È già in corso una modifica',
  'feed.post.deleted': 'Post eliminato',
  'feed.post.delete_failed': 'Errore durante l’eliminazione',
  'feed.post.repost.success': 'Ripubblicato',
  'feed.post.repost.error': 'Impossibile ripubblicare',
  'feed.post.repost.already': 'Già ripubblicato',
  'feed.post.repost.offline': 'Offline — la ripubblicazione non è partita.',
  'feed.post.repost.unconfirmed': 'Ripubblicazione non confermata — riprova',
  'feed.post.repost.audience': 'Questo pubblico amplierebbe la portata del post originale',
  'feed.post.repost.confirm.title': 'Ripubblicare questo post?',
  'feed.post.repost.confirm.body': 'Apparirà nel tuo feed, visibile ai tuoi follower. Questa azione non può essere annullata.',
  'feed.post.reel.chip': 'Reel',
  'feed.post.repost.embed.story': 'Story',
  'feed.post.reel.of': 'Reel di {author}',
  'feed.post.open': 'Apri il post di {author}',
  'feed.post.original.open': 'Post originale di {author}',
  /* LES PUBLICATIONS ENREGISTRÉES (#7286) — l'écran `/me/bookmarks` et sa rangée de Réglages › Outils. */
  'bookmarks.title': 'Post salvati',
  'bookmarks.back': 'Torna alle impostazioni',
  'bookmarks.loading': 'Caricamento dei post salvati',
  'bookmarks.empty.title': 'Nessun post salvato',
  'bookmarks.empty.subtitle': 'Tocca il segnalibro sotto un post per conservarlo qui e rileggerlo quando vuoi.',
  'bookmarks.empty.cta': 'Apri il Feed',
  'bookmarks.error.title': 'Impossibile caricare i post salvati',
  'bookmarks.error.body': 'Riprova tra un istante.',
  'bookmarks.offline.body': 'I tuoi post salvati compariranno alla riconnessione.',
  'bookmarks.allLoaded': 'Tutti i tuoi post salvati sono caricati',
  'bookmarks.filter.all': 'Tutto',
  'bookmarks.filter.posts': 'Post',
  'bookmarks.filter.reels': 'Reel',
  'bookmarks.filter.a11y': 'Filtra i post salvati',
  'settings.tools.bookmarks': 'Post salvati',
  'action.star': 'Aggiungi ai preferiti',
  'action.unstar': 'Rimuovi dai preferiti',
  'announce.messageStarred': 'Aggiunto ai preferiti',
  'announce.messageUnstarred': 'Rimosso dai preferiti',
  'starred.messages.pending': 'Preferito non confermato — offline',
  'starred.messages.error': 'Impossibile modificare il preferito',
  'starred.messages.notStarrable': 'Questo messaggio non può essere aggiunto ai preferiti',
  'settings.tools.starred': 'Messaggi preferiti',
  'starred.messages.title': 'Messaggi preferiti',
  'starred.messages.back': 'Torna alle impostazioni',
  'starred.messages.loading': 'Caricamento dei messaggi preferiti',
  'starred.messages.empty.title': 'Nessun messaggio preferito',
  'starred.messages.empty.subtitle': 'Tieni premuto un messaggio e scegli «Aggiungi ai preferiti» per ritrovarlo qui.',
  'starred.messages.empty.cta': 'Apri le conversazioni',
  'starred.messages.error.title': 'Impossibile caricare i tuoi messaggi preferiti',
  'starred.messages.error.body': 'Riprova tra un istante.',
  'starred.messages.offline.body': 'I tuoi messaggi preferiti compariranno alla riconnessione.',
  'starred.messages.allLoaded': 'Tutti i tuoi messaggi preferiti sono caricati',
  'starred.messages.row.hint': 'Apre la conversazione',
  'starred.messages.remove.a11y': 'Rimuovi il messaggio di {author} dai preferiti',
  'starred.messages.protected': 'Messaggio protetto',
  'starred.messages.noText': 'Messaggio senza testo',
  'starred.messages.media.image': 'Foto',
  'starred.messages.media.video': 'Video',
  'starred.messages.media.audio': 'Audio',
  'starred.messages.media.file': 'File',
  'common.unknown_user': 'Utente',
  'feed.error.title': 'Impossibile caricare il feed',
  'feed.error.body': 'Riprova tra un momento.',
  'feed.offline.title': 'Offline',
  'feed.offline.body': 'Il feed apparirà quando tornerai online.',
  'feed.retry': 'Riprova',
  'feed.empty.title': 'Nessuna pubblicazione per ora',
  'feed.empty.subtitle': 'Le pubblicazioni dei tuoi contatti appariranno qui.',
  'feed.loading': 'Caricamento del feed',
  'feed.allLoaded': 'Tutte le pubblicazioni sono state caricate',
  'feed.newPosts.one': '{count} nuova pubblicazione',
  'feed.newPosts.other': '{count} nuove pubblicazioni',
  ...itIdentity,
  ...itVerifyEmail,
  ...itPassword,
  ...itCall,
  ...itCallJoin,
  ...itCallShell,
  ...itSignup,
  'userProfile.self.edit': 'Modifica il mio profilo',
  'report.title': 'Segnala questo account',
  'report.body': 'Scegli il motivo della segnalazione. Il nostro team di moderazione la riceverà.',
  'report.action': 'Segnala',
  'report.done': 'Segnalazione inviata',
  'report.throttled': 'Troppe segnalazioni — riprova tra poco',
  'report.failed': 'Impossibile inviare la segnalazione',
  'report.reason.spam': 'Spam',
  'report.reason.inappropriate': 'Contenuto inappropriato',
  'report.reason.harassment': 'Molestie',
  'report.reason.violence': 'Violenza',
  'report.reason.hate_speech': 'Incitamento all’odio',
  'report.reason.fake_profile': 'Profilo falso',
  'report.reason.impersonation': 'Furto d’identità',
  'report.reason.other': 'Altro',
  'feed.like.error': 'Errore nel mettere Mi piace',
  'post.bookmark.error': 'Salvataggio non riuscito',
  'feed.gesture.pending': 'Azione non confermata — offline',
  'feed.share.error': 'Errore nella condivisione del post',
  'feed.share.copied': 'Link copiato — non resta che incollarlo.',
  'feed.share.text': 'Una pubblicazione su Meeshy',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'I miei link',
  'root.menu.notifications': 'Notifiche',
  'root.menu.calls': 'Chiamate',
  'root.menu.discover': 'Scopri',
  'root.menu.communities': 'Community',
  'root.menu.settings': 'Impostazioni',
  'root.menu.profile': 'Profilo',
  'root.menu.conversations': 'Conversazioni',
  'a11y.floating.feed.hint': 'Tieni premuto per avviare i Reel',
  'a11y.floating.menu': 'Menu',
  'a11y.floating.menu.ladder': 'Navigazione Meeshy',
  'a11y.floating.menu.unread.one': 'Menu, {count} notifica non letta',
  'a11y.floating.menu.unread.other': 'Menu, {count} notifiche non lette',
  'a11y.floating.rung.notifications.unread.one': 'Notifiche, {count} non letta',
  'a11y.floating.rung.notifications.unread.other': 'Notifiche, {count} non lette',

  'notifications.category.all': 'Tutte',
  'notifications.category.unread': 'Non lette',
  'notifications.category.messages': 'Messaggi',
  'notifications.category.reactions': 'Reazioni',
  'notifications.category.mentions': 'Menzioni',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contatti',
  'notifications.category.groups': 'Gruppi',
  'notifications.category.calls': 'Chiamate',
  'notifications.category.translations': 'Traduzioni',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorie di notifiche',
  'notifications.markAllRead': 'Segna tutte come lette',
  'notifications.unreadCount.one': '{count} non letta',
  'notifications.unreadCount.other': '{count} non lette',
  'notifications.unread': 'Non letta',
  'notifications.empty.all': 'Nessuna notifica',
  'notifications.empty.unread': 'Nessuna notifica non letta',
  'notifications.empty.category': 'Nessuna notifica in «{category}»',
  'notifications.empty.subtitle': 'Le tue notifiche appariranno qui',
  'notifications.loading': 'Caricamento delle notifiche',
  'notifications.error.title': 'Impossibile caricare le notifiche',
  'notifications.error.body': 'Riprova tra un momento.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Le tue notifiche appariranno quando tornerai online.',
  'notifications.retry': 'Riprova',
  'notifications.allLoaded': 'Tutte le notifiche sono state caricate',
  'notifications.actions': 'Azioni della notifica',
  'notifications.action.markRead': 'Segna come letta',
  'notifications.action.delete': 'Elimina',
  'notifications.failure': 'L’azione non è andata a buon fine. Riprova.',

  'notFound.title': 'Questo indirizzo non esiste.',

  'pending.back': 'Torna alle conversazioni',

  'linkPage.home': 'Torna a Meeshy',
  'linkPage.retry': 'Riprova',
  'linkPage.settings': 'Apri le impostazioni',
  'linkPage.signIn': 'Accedi',
  'linkPage.offline.title': 'Offline',
  'linkPage.offline.body': 'Riconnettiti a Internet, poi riprova.',
  'linkPage.unavailable.title': 'Meeshy non risponde',
  'linkPage.unavailable.body': 'Il servizio è momentaneamente non disponibile. Riprova tra qualche istante.',
  'linkPage.rateLimited': 'Troppi tentativi. Attendi un momento prima di riprovare.',
  'linkPage.signedOut.title': 'Accedi per continuare',
  'linkPage.signedOut.body': 'Questo link agisce sul tuo account. Accedi, poi riaprilo dall’e-mail.',
  'linkPage.expired': 'Questo link è scaduto. Ripeti la richiesta dalle impostazioni.',
  'trackingLink.opening': 'Apertura del link…',
  'trackingLink.dead.title': 'Questo link non è più disponibile',
  'trackingLink.dead.body': 'È scaduto, è stato disattivato o non è mai esistito.',
  'accountDeletion.incomplete.title': 'Link incompleto',
  'accountDeletion.incomplete.body': 'A questo link mancano le informazioni necessarie. Accedi per richiedere l’eliminazione del tuo account.',
  'accountDeletion.confirm.title': 'Conferma l’eliminazione del tuo account',
  'accountDeletion.confirm.body':
    'Il tuo account sarà disattivato al termine di un periodo di tolleranza di 30 giorni. Fino ad allora, il link «Annulla» dell’e-mail ti permette di tornare indietro.',
  'accountDeletion.confirm.action': 'Conferma l’eliminazione',
  'accountDeletion.cancel.title': 'Annulla l’eliminazione del tuo account',
  'accountDeletion.cancel.body': 'Il tuo account resta attivo e la richiesta di eliminazione viene abbandonata. Non si perde nulla.',
  'accountDeletion.cancel.action': 'Annulla l’eliminazione',
  'accountDeletion.purge.title': 'Elimina il tuo account ora',
  'accountDeletion.purge.body': 'Il tuo account sarà disattivato subito e tutte le tue sessioni verranno chiuse. L’operazione è definitiva.',
  'accountDeletion.purge.action': 'Elimina ora',
  'accountDeletion.dismiss': 'Non fare nulla',
  'accountDeletion.working': 'Un istante…',
  'accountDeletion.done.title': 'Fatto',
  'accountDeletion.done.confirmed': 'La tua richiesta è confermata: il tuo account sarà disattivato il {date}. Puoi annullare fino ad allora.',
  'accountDeletion.done.cancelled': 'Il tuo account resta attivo: la richiesta di eliminazione è stata abbandonata.',
  'accountDeletion.done.completed': 'Il tuo account è disattivato e tutte le tue sessioni sono state chiuse.',
  'accountDeletion.done.purged': 'I tuoi dati sono stati cancellati.',
  'accountDeletion.closed.title': 'Questo link non è più valido',
  'accountDeletion.invalid': 'Questo link non è valido o è già stato usato.',
  'accountDeletion.request.title': 'Elimina il tuo account',
  'accountDeletion.request.body':
    'Le tue conversazioni, i messaggi, i contenuti multimediali, i contatti e le preferenze saranno eliminati. Un’e-mail ti chiederà di confermare, poi un periodo di tolleranza di 30 giorni ti permetterà di tornare indietro.',
  'accountDeletion.request.phrase': 'Digita {phrase} per confermare',
  'accountDeletion.request.password': 'Password attuale',
  'accountDeletion.request.action': 'Richiedi l’eliminazione',
  'accountDeletion.request.sent.title': 'Ti abbiamo inviato un’e-mail di conferma',
  'accountDeletion.request.sent.body': 'Aprila per confermare l’eliminazione del tuo account.',
  'accountDeletion.request.wrongPassword': 'Password errata.',
  'accountDeletion.request.alreadyPending': 'C’è già una richiesta in corso. Apri l’e-mail ricevuta per confermarla o annullarla.',
  'accountDeletion.request.noEmail': 'Aggiungi e verifica un indirizzo e-mail prima di richiedere l’eliminazione.',
  'emailChange.verifying': 'Conferma del nuovo indirizzo…',
  'emailChange.done.title': 'Indirizzo e-mail modificato',
  'emailChange.done.body': 'D’ora in poi accedi con {email}.',
  'emailChange.done.generic': 'Il tuo nuovo indirizzo e-mail è confermato.',
  'emailChange.failed.title': 'Indirizzo non modificato',
  'emailChange.missing': 'Questo link non contiene un codice di conferma. Apri quello dell’e-mail più recente.',
  'emailChange.invalid': 'Questo link non corrisponde a nessuna modifica in sospeso su questo account, oppure è già stato usato.',
  'emailChange.taken': 'Questo indirizzo è ora usato da un altro account.',
  'emailNotifications.title': 'E-mail di Meeshy',
  'emailNotifications.loading': 'Lettura della tua preferenza…',
  'emailNotifications.on': 'Ricevi via e-mail annunci, riepiloghi e notifiche di Meeshy.',
  'emailNotifications.off': 'Non ricevi più via e-mail annunci, riepiloghi né notifiche di Meeshy.',
  'emailNotifications.security': 'Le e-mail di sicurezza del tuo account continuano ad arrivare.',
  'emailNotifications.unsubscribe': 'Non ricevere più queste e-mail',
  'emailNotifications.resubscribe': 'Ricevi di nuovo queste e-mail',
  'emailNotifications.failed': 'La modifica non è andata a buon fine. Riprova.',

  'dataExport.title': 'Esporta i miei dati',
  'dataExport.info.body': 'In conformità al GDPR, ricevi un file con il tuo profilo, i tuoi messaggi, i tuoi contatti e le tue pubblicazioni.',
  'dataExport.action.start': 'Esporta i miei dati',
  'dataExport.action.exporting': 'Esportazione in corso…',
  'dataExport.action.again': 'Esporta di nuovo',
  'dataExport.done.title': 'Esportazione completata',
  'dataExport.done.body': 'Il file è stato scaricato su questo dispositivo.',
  'dataExport.ready.title': 'Esportazione pronta',
  'dataExport.ready.body': 'Il file è pronto. Tocca per salvarlo su questo dispositivo.',
  'dataExport.action.deliver': 'Salva il file',
  'dataExport.undelivered.body': 'Questo dispositivo non ha potuto ricevere il file.',

  'profile.title': 'Profilo',
  'profile.edit': 'Modifica',
  'profile.cancel': 'Annulla',
  'profile.save': 'Salva',
  'profile.saving': 'Salvataggio…',
  'profile.saved': 'Profilo salvato',
  'profile.save.error': 'Errore durante il salvataggio',
  'profile.save.offline': 'Offline — la modifica non è stata inviata.',
  'profile.save.invalid': 'Controlla il campo «{field}».',
  'profile.loading': 'Caricamento del profilo',
  'profile.error.title': 'Impossibile caricare il tuo profilo',
  'profile.error.body': 'Riprova tra un momento.',
  'profile.retry': 'Riprova',
  'profile.offline.title': 'Offline',
  'profile.offline.body': 'Il tuo profilo resta leggibile; la modifica torna con la rete.',
  'profile.avatar.edit': 'Modifica la foto del profilo',
  'profile.avatar.updated': 'Foto del profilo aggiornata',
  'profile.avatar.error': 'Impossibile aggiornare la foto del profilo',
  'profile.banner.edit': 'Modifica il banner',
  'profile.banner.updated': 'Banner aggiornato',
  'profile.banner.error': 'Impossibile aggiornare il banner',
  'profile.image.uploading': 'Invio in corso',
  'profile.image.cancel': 'Annulla l’invio',
  'profile.image.cancelled': 'Invio annullato',
  'profile.image.unreadable': 'Questa immagine non può essere letta.',
  'profile.section.identity': 'IDENTITÀ',
  'profile.section.contact': 'CONTATTO',
  'profile.section.languages': 'LINGUE',
  'profile.section.stats': 'STATISTICHE',
  'profile.section.requests': 'RICHIESTE',
  'profile.section.member_since': 'MEMBRO DAL',
  'profile.first_name': 'Nome',
  'profile.last_name': 'Cognome',
  'profile.username': 'Nome utente',
  'profile.display_name': 'Nome visualizzato',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Raccontaci di te...',
  'profile.email': 'Email',
  'profile.phone': 'Telefono',
  'profile.verified': 'Verificato',
  'profile.not_verified': 'Non verificato',
  'profile.language.primary': 'Lingua principale',
  'profile.language.primary.subtitle': 'I contenuti saranno tradotti in questa lingua',
  'profile.language.regional': 'Lingua regionale',
  'profile.language.custom': 'Lingua personalizzata',
  'profile.language.none': 'Nessuna',
  'profile.language.choose': 'Scegli',
  'profile.language.clear.regional': 'Rimuovi la lingua regionale',
  'profile.language.clear.custom': 'Rimuovi la lingua personalizzata',

  'languageSheet.title.read': 'Lingua di lettura',
  'languageSheet.title.write': 'Lingua di scrittura',
  'languageSheet.search': 'Cerca una lingua',
  'languageSheet.empty': 'Nessuna lingua corrisponde a «{search}».',

  'profile.stats.messages': 'Messaggi',
  'profile.stats.translations': 'Traduzioni',
  'profile.stats.languages': 'Lingue',
  'profile.stats.days': 'Giorni',
  'profile.stats.loading': 'Caricamento delle statistiche',
  'profile.progression.title': 'Progressi',
  'profile.progression.subtitle': 'Badge, livello e serie',
  'profile.friend_requests': 'Richieste di amicizia',
  'profile.friend_requests.count.one': '{count} richiesta in attesa',
  'profile.friend_requests.count.other': '{count} richieste in attesa',

  'settings.title': 'Impostazioni',
  'settings.my_profile': 'Il mio profilo',
  'settings.section.account': 'Account',
  'settings.security.title': 'Sicurezza',
  'settings.delete_account': "Elimina l'account",
  'settings.privacy.title': 'Privacy',
  'settings.privacy.online_status': 'Stato online',
  'settings.privacy.online_status.info':
    'Il punto verde sul tuo avatar indica che sei attivo. Disattivato, nessuno lo vede, ma scrivere in una conversazione rivela comunque la tua presenza.',
  'settings.privacy.last_seen': 'Ultimo accesso',
  'settings.privacy.read_receipts': 'Conferme di lettura',
  'settings.privacy.read_receipts.info':
    'È reciproco: se non invii conferme di lettura, non vedrai nemmeno se i tuoi messaggi sono stati letti.',
  'settings.privacy.typing_indicator': 'Indicatore di digitazione',
  'settings.section.appearance': 'Aspetto',
  'settings.theme': 'Tema',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Chiaro',
  'settings.theme.dark': 'Scuro',
  'settings.interface_language': "Lingua dell'interfaccia",
  'settings.interface_language.automatic': 'Automatico',
  'settings.content_languages': 'Lingue di traduzione',
  'settings.section.notifications': 'Notifiche',
  'settings.notifications.title': 'Notifiche',
  'settings.notif.sounds': 'Suoni',
  'settings.notif.more_options': 'Altre opzioni',
  'settings.section.data': 'Dati',
  'settings.media': 'Contenuti multimediali',
  'settings.messages': 'Messaggi',
  'settings.export_data': 'Esporta i miei dati',
  'settings.section.tools': 'Strumenti',
  'settings.tools.progression': 'Progressi',
  'settings.section.about': 'Informazioni',
  'settings.terms': "Condizioni d'uso",
  'settings.privacy_policy': 'Informativa sulla privacy',
  'settings.version': 'Versione',
  'settings.logout.title': 'Esci',
  'settings.logout.message': 'Vuoi davvero uscire?',
  'settings.logout.inprogress': 'Disconnessione in corso...',
  'settings.loading': 'Caricamento delle impostazioni',
  'settings.error.title': 'Impossibile caricare le impostazioni',
  'settings.retry': 'Riprova',
  'settings.offline.body': 'Offline: le impostazioni restano leggibili; potrai modificarle quando torna la rete.',
  'settings.save.error': "L'impostazione non è stata salvata.",
  'settings.theme.sync_error': 'Tema applicato su questo dispositivo, non sincronizzato.',
  'common.cancel': 'Annulla',

  'media.video.play': 'Riproduci video',
  'media.video.pause': 'Metti in pausa',
  'media.video.position': 'Posizione di riproduzione',
  'media.audio.position': 'Posizione di riproduzione',
  'media.audio.speed': 'Velocità di riproduzione',
  'media.video.position.value': '{elapsed} di {total}',
  'media.video.mute': 'Disattiva audio',
  'media.video.unmute': 'Riattiva audio',
  'media.video.more_options': 'Altre opzioni',
  'media.video.speed': 'Velocità',
  'media.video.pip.enter': 'Picture-in-Picture',
  'media.video.pip.exit': 'Esci da Picture-in-Picture',

  'community.list.create.accessibilityLabel': 'Crea una community',
  'community.list.search.placeholder': 'Cerca community',
  'community.list.search.clear': 'Cancella la ricerca',
  'community.list.search.empty': 'Nessuna community corrisponde a «{query}».',
  'community.list.empty.title': 'Nessuna community',
  'community.list.empty.subtitle': 'Unisciti a una community o creane una per parlare insieme.',
  'community.list.loading': 'Caricamento delle community',
  'community.error.title': 'Impossibile caricare le community',
  'community.error.body': 'Controlla la connessione e riprova.',
  'community.retry': 'Riprova',
  'community.offline.title': 'Offline',
  'community.offline.body': 'Le tue community restano leggibili; per crearne una serve la connessione.',
  'community.privacy.private': 'Privata',
  'community.privacy.public': 'Pubblica',
  'community.members.one': '{count} membro',
  'community.members.other': '{count} membri',
  'community.conversations.one': '{count} conversazione',
  'community.conversations.other': '{count} conversazioni',
  'community.detail.stats.members': 'Membri',
  'community.detail.channels': 'Conversazioni',
  'community.detail.channels.empty': 'Non partecipi ancora a nessuna conversazione di questa community.',
  'community.detail.untitled': 'Conversazione senza titolo',
  'community.detail.back': 'Torna alle community',
  'community.detail.refused.title': 'Community non trovata',
  'community.detail.refused.body': 'Non esiste, oppure è privata e non ne sei membro.',
  'community.detail.error.title': 'Impossibile caricare questa community',
  'community.detail.loading': 'Caricamento della community',
  'community.create.title': 'Nuova community',
  'community.create.preview.placeholder': 'La mia community',
  'community.create.field.name': 'Nome',
  'community.create.field.name.placeholder': 'Nome della community',
  'community.create.field.identifier': 'Identificativo',
  'community.create.field.identifier.placeholder': 'mio-gruppo',
  'community.create.field.description': 'Descrizione',
  'community.create.field.description.placeholder': 'Di cosa parla questa community?',
  'community.create.privacy.title': 'Community privata',
  'community.create.privacy.private.description': 'Solo i membri invitati possono unirsi',
  'community.create.privacy.public.description': 'Chiunque può scoprirla e unirsi',
  'community.create.button': 'Crea la community',
  'community.create.inprogress': 'Creazione…',
  'community.create.error.name': 'Dalle un nome di al massimo 100 caratteri.',
  'community.create.error.identifier': 'Solo lettere, cifre, trattini e trattini bassi, al massimo 50.',
  'community.create.error.description': 'Al massimo 500 caratteri.',
  'community.create.error.conflict': 'Questo identificativo è già in uso.',
  'community.create.error.offline': 'Offline: la community non è stata inviata.',
  'community.create.error.default': 'La community non è stata creata. Riprova.',
  'calls.filters': 'Filtra il registro chiamate',
  'calls.filter.all': 'Tutte',
  'calls.filter.missed': 'Perse',
  'calls.direction.incoming': 'Ricevuta',
  'calls.direction.outgoing': 'Effettuata',
  'calls.direction.missed': 'Persa',
  'calls.a11y.incoming': 'chiamata ricevuta',
  'calls.a11y.outgoing': 'chiamata effettuata',
  'calls.a11y.missed': 'chiamata persa',
  'calls.type.audio': 'chiamata vocale',
  'calls.type.video': 'videochiamata',
  'calls.duration': 'durata {duration}',
  'calls.unknown': 'Sconosciuto',
  'calls.empty.title': 'Nessuna chiamata recente',
  'calls.empty.subtitle': 'Qui appariranno le tue chiamate ricevute, perse, annullate ed effettuate.',
  'calls.empty.missed.title': 'Nessuna chiamata persa',
  'calls.empty.missed.subtitle': 'Qui appariranno le chiamate a cui non hai risposto.',
  'calls.error.title': 'Impossibile caricare il registro chiamate',
  'calls.error.body': 'Controlla la connessione e riprova.',
  'calls.offline.title': 'Offline',
  'calls.offline.body': 'Stai vedendo il registro dell’ultimo caricamento.',
  'calls.offline.cold.body': 'Il registro si caricherà appena torni online.',
  'calls.retry': 'Riprova',
  'calls.loading': 'Caricamento del registro chiamate',
  'calls.allLoaded': 'Tutte le chiamate degli ultimi tre mesi sono caricate',

  'discover.tabs': 'Sezioni di Scopri',
  'discover.tab.discover': 'Scopri',
  'discover.tab.requests': 'Richieste',
  'discover.tab.blocked': 'Bloccati',
  'discover.tab.requests.count.one': 'Richieste, {count} ricevuta',
  'discover.tab.requests.count.other': 'Richieste, {count} ricevute',
  'discover.invite.title': 'Invita via email',
  'discover.invite.placeholder': 'Indirizzo email',
  'discover.invite.send': 'Invia',
  'discover.invite.sending': 'Invio…',
  'discover.invite.sendLabel': 'Invia l’invito via email',
  'discover.invite.sent': 'Invito inviato a {email}',
  'discover.invite.invalid': 'Questo indirizzo email non è valido.',
  'discover.invite.conflict': 'Questa persona è già su Meeshy: cercala qui sotto.',
  'discover.invite.error': 'Impossibile inviare l’invito. Riprova.',
  'discover.invite.offline': 'Offline: riconnettiti per inviare l’invito.',
  'discover.search.label': 'Cerca un utente Meeshy',
  'discover.search.clear': 'Cancella la ricerca',
  'discover.search.searching': 'Ricerca in corso',
  'discover.search.empty': 'Nessun utente trovato per «{query}»',
  'discover.search.error': 'La ricerca non è riuscita. Controlla la connessione.',
  'discover.connection.add': 'Aggiungi',
  'discover.connection.addLabel': 'Aggiungi {name}',
  'discover.connection.pending': 'In attesa',
  'discover.connection.cancelLabel': 'Annulla la richiesta inviata a {name}',
  'discover.connection.contact': 'Contatto',
  'discover.connection.blocked': 'Bloccato',
  'discover.connection.acceptLabel': 'Accetta la richiesta di {name}',
  'discover.connection.rejectLabel': 'Rifiuta la richiesta di {name}',
  'discover.requests.filters': 'Filtra le richieste',
  'discover.requests.received': 'Ricevute',
  'discover.requests.sent': 'Inviate',
  'discover.requests.intent': 'Vorrebbe entrare in contatto con te',
  'discover.requests.cancel': 'Annulla',
  'discover.requests.empty.received.title': 'Nessuna richiesta ricevuta',
  'discover.requests.empty.received.subtitle': 'Le richieste di contatto ricevute appariranno qui.',
  'discover.requests.empty.sent.title': 'Nessuna richiesta inviata',
  'discover.requests.empty.sent.subtitle': 'Le richieste che invii appariranno qui.',
  'discover.blocked.unblock': 'Sblocca',
  'discover.blocked.unblockLabel': 'Sblocca {name}',
  'discover.blocked.confirm.title': 'Sbloccare?',
  'discover.blocked.confirm.body': 'Sbloccare {name}?',
  'discover.blocked.confirm.cancel': 'Annulla',
  'discover.blocked.empty.title': 'Nessun utente bloccato',
  'discover.blocked.empty.subtitle': 'Le persone che blocchi appariranno qui.',
  'discover.unknown': 'Sconosciuto',
  'discover.loading': 'Caricamento',
  'discover.allLoaded': 'L’elenco completo è caricato',
  'discover.error.title': 'Impossibile caricare questo elenco',
  'discover.error.body': 'Controlla la connessione e riprova.',
  'discover.offline.title': 'Offline',
  'discover.offline.body': 'Stai vedendo l’elenco dell’ultimo caricamento.',
  'discover.offline.cold.body': 'L’elenco si caricherà appena torni online.',
  'discover.retry': 'Riprova',
  'discover.announce.accepted': 'Connessione accettata',
  'discover.announce.rejected': 'Richiesta rifiutata',
  'discover.announce.cancelled': 'Richiesta annullata',
  'discover.announce.sent': 'Richiesta inviata',
  'discover.announce.unblocked': 'Utente sbloccato',
  'discover.announce.acceptFailed': 'Impossibile accettare questa richiesta',
  'discover.announce.rejectFailed': 'Impossibile rifiutare questa richiesta',
  'discover.announce.cancelFailed': 'Impossibile annullare questa richiesta',
  'discover.announce.sendFailed': 'Impossibile inviare la richiesta',
  'discover.announce.unblockFailed': 'Impossibile sbloccare',
  'discover.announce.offline': 'Offline: non è stato inviato nulla.',

  'userProfile.title': 'Profilo',
  'userProfile.loading': 'Caricamento del profilo',
  'userProfile.section.publications': 'PUBBLICAZIONI',
  'userProfile.section.relation': 'CONNESSIONE',
  'userProfile.section.conversations': 'CONVERSAZIONI',
  'userProfile.conversations.empty': 'Nessuna conversazione in comune',
  'userProfile.conversations.emptyBody': 'Niente vi lega ancora: «Scrivi» apre la prima.',
  'userProfile.conversations.error': 'Impossibile caricare le conversazioni',
  'userProfile.conversations.loading': 'Caricamento delle conversazioni',
  'userProfile.refused.title': 'Questo profilo non è disponibile',
  'userProfile.refused.body': 'Non esiste, oppure non hai accesso.',
  'userProfile.throttled.title': 'Troppe richieste',
  'userProfile.throttled.body': 'Riprova tra un istante.',
  'userProfile.error.title': 'Impossibile caricare questo profilo',
  'userProfile.error.body': 'Riprova tra un istante.',
  'userProfile.offline.body': 'Il profilo apparirà al ritorno della connessione.',
  'userProfile.posts.empty': 'Nessuna pubblicazione',
  'userProfile.posts.emptyBody': 'Non c’è ancora nulla di pubblico da leggere.',
  'userProfile.posts.emptyPosts': 'Nessun post qui',
  'userProfile.posts.emptyReels': 'Nessun reel qui',
  'userProfile.posts.emptyFilter': 'Tocca di nuovo il riquadro per rivedere tutto.',
  'userProfile.posts.error': 'Impossibile caricare le pubblicazioni',
  'userProfile.posts.loadMore': 'Carica altro',
  'userProfile.posts.loaded': 'Pubblicazioni aggiunte: {count}',
  'userProfile.posts.loadedNone': 'Nessuna altra pubblicazione da mostrare',
  'userProfile.posts.loading': 'Caricamento…',
  'userProfile.stat.posts': 'Post',
  'userProfile.stat.reels': 'Reel',
  'userProfile.stat.stories': 'Storie',
  'userProfile.stat.filterLabel': 'Filtra su {name}',
  'userProfile.stat.filterClear': 'Mostra tutto',
  'userProfile.context.received': '{name} vuole entrare in contatto con te. Accetta per scambiare messaggi.',
  'userProfile.context.sent': 'Hai inviato una richiesta di connessione a {name}. In attesa di risposta.',
  'userProfile.action.write': 'Scrivere',
  'userProfile.action.writeLabel': 'Scrivere a {name}',
  'userProfile.action.block': 'Bloccare',
  'userProfile.action.blockLabel': 'Bloccare {name}',
  'userProfile.blocked.title': 'Hai bloccato questa persona',
  'userProfile.blocked.body': 'Le sue pubblicazioni e le sue statistiche restano nascoste finché dura il blocco.',
  'userProfile.signin.title': 'Accedi per entrare in contatto',
  'userProfile.signin.body': 'Le richieste di connessione e i messaggi richiedono un account.',
  'userProfile.signin.cta': 'Accedi',
  'userProfile.announce.blocked': 'Persona bloccata',
  'userProfile.announce.blockFailed': 'Impossibile bloccare',
  'userProfile.announce.writeFailed': 'Impossibile aprire la conversazione',

  'a11y.floating.rung.discover.requests.one': 'Scopri, {count} richiesta ricevuta',
  'a11y.floating.rung.discover.requests.other': 'Scopri, {count} richieste ricevute',

  'links.hub.banner.title': 'Gestisci i tuoi link',
  'links.hub.banner.subtitle': 'Invita chi vuoi nelle tue conversazioni',
  'links.hub.share.title': 'Link di condivisione',
  'links.hub.share.description': 'Invita i contatti a unirsi alle tue conversazioni',
  'links.hub.share.create': 'Crea un link di condivisione',
  'links.share.back': 'Torna a I miei link',
  'links.share.stats.total': 'Link',
  'links.share.stats.active': 'Attivi',
  'links.share.stats.joined': 'Entrati',
  'links.share.joined.one': '{count} entrato',
  'links.share.joined.other': '{count} entrati',
  'links.share.copy': 'Copia il link',
  'links.share.empty.title': 'Nessun link di condivisione',
  'links.share.empty.subtitle': 'Crea un link per invitare persone in una conversazione',
  'links.share.loading': 'Caricamento dei link',
  'links.share.allLoaded': 'Tutti i tuoi link sono caricati',
  'links.status.active': 'Attivo',
  'links.status.inactive': 'Inattivo',
  'links.unlimited': 'Illimitato',
  'links.error.title': 'Impossibile caricare i tuoi link',
  'links.error.body': 'Controlla la connessione e riprova.',
  'links.retry': 'Riprova',
  'links.offline.title': 'Offline',
  'links.offline.body': 'I tuoi link restano leggibili; per modificarli serve la connessione.',
  'links.detail.back': 'Torna ai link di condivisione',
  'links.detail.copy': 'Copia',
  'links.detail.copied': 'Copiato',
  'links.detail.share': 'Condividi',
  'links.detail.disable': 'Disattiva',
  'links.detail.activate': 'Attiva',
  'links.detail.stats': 'Statistiche',
  'links.detail.stats.uses': 'Utilizzi',
  'links.detail.stats.max': 'Massimo',
  'links.detail.info': 'Informazioni',
  'links.detail.identifier': 'Identificativo',
  'links.detail.createdAt': 'Creato il',
  'links.detail.expiresAt': 'Scade il',
  'links.detail.reason.closed': 'La conversazione è chiusa: questo link non fa più entrare nessuno.',
  'links.detail.reason.expired': 'Questo link è scaduto.',
  'links.detail.reason.revoked': 'Hai disattivato questo link.',
  'links.detail.refused.title': 'Link non trovato',
  'links.detail.refused.body': 'Questo link non esiste o non è uno dei tuoi.',
  'links.detail.loading': 'Caricamento del link',
  'links.announce.copied': 'Link copiato',
  'links.announce.copyFailed': 'Impossibile copiare il link',
  'links.announce.shareUnavailable': 'La condivisione non è disponibile qui',
  'links.announce.disabled': 'Link disattivato',
  'links.announce.activated': 'Link attivato',
  'links.announce.toggleFailed': 'Impossibile modificare questo link',
  'links.announce.offline': 'Offline: non è stato inviato nulla.',
  'links.create.title': 'Nuovo link di condivisione',
  'links.create.section.conversation': 'Conversazione',
  'links.create.choose': 'Scegli un gruppo o una community',
  'links.create.picker.title': 'Scegli una conversazione',
  'links.create.picker.empty': 'Nessuna conversazione può ancora ricevere un link.',
  'links.create.section.identity': 'Identità del link',
  'links.create.name': 'Nome del link',
  'links.create.name.placeholder': 'es.: Condivisione su Twitter',
  'links.create.description': 'Descrizione (facoltativa)',
  'links.create.description.placeholder': 'es.: Unisciti al nostro gruppo…',
  'links.create.section.access': 'Accesso ospiti',
  'links.create.section.access.subtitle': 'Cosa devono fornire i visitatori per entrare',
  'links.create.access.account': 'Account obbligatorio',
  'links.create.access.account.caption': 'Solo i membri di Meeshy possono entrare',
  'links.create.access.nickname': 'Nickname obbligatorio',
  'links.create.access.nickname.caption': 'Il visitatore deve scegliere un nickname',
  'links.create.access.email': 'E-mail obbligatoria',
  'links.create.access.email.caption': 'Il visitatore deve fornire la sua e-mail',
  'links.create.access.birthday': 'Data di nascita obbligatoria',
  'links.create.access.birthday.caption': 'Consente il controllo dell’età',
  'links.create.section.permissions': 'Permessi',
  'links.create.section.permissions.subtitle': 'Cosa possono fare gli ospiti anonimi',
  'links.create.permission.messages': 'Inviare messaggi',
  'links.create.permission.messages.caption': 'Gli ospiti possono scrivere nella conversazione',
  'links.create.permission.images': 'Inviare immagini',
  'links.create.permission.images.caption': 'Gli ospiti possono condividere foto',
  'links.create.permission.files': 'Inviare file',
  'links.create.permission.files.caption': 'Gli ospiti possono inviare documenti',
  'links.create.permission.history': 'Vedere la cronologia',
  'links.create.permission.history.caption': 'Gli ospiti vedono i messaggi precedenti',
  'links.create.section.limits': 'Limiti',
  'links.create.section.limits.subtitle': 'Controlla il pubblico e la durata del link',
  'links.create.limit.uses': 'Limita gli utilizzi',
  'links.create.limit.max.one': 'Al massimo {count} utilizzo',
  'links.create.limit.max.other': 'Al massimo {count} utilizzi',
  'links.create.limit.count': 'Numero di utilizzi',
  'links.create.limit.invalid': 'Scegli un numero intero tra 1 e {max}.',
  'links.create.expiration': 'Scadenza',
  'links.create.expiration.never': 'Mai',
  'links.create.expiration.h24': '24 ore',
  'links.create.expiration.d7': '7 giorni',
  'links.create.expiration.d30': '30 giorni',
  'links.create.expiration.m3': '3 mesi',
  'links.create.button': 'Crea il link di condivisione',
  'links.create.inprogress': 'Creazione in corso…',
  'links.create.error.conversation': 'Scegli prima una conversazione.',
  'links.create.error.offline': 'Offline: il link non è stato creato.',
  'links.create.error.refused': 'Non puoi creare un link per questa conversazione.',
  'links.create.error.default': 'Impossibile creare il link. Riprova.',

  'feed.scene.carousel.previous': 'Scena precedente',
  'feed.scene.carousel.next': 'Scena successiva',
  'feed.scene.mosaic.tile': 'Scena {index}',
  'feed.scene.mosaic.more': 'Scena {index} e altre {count}',
  'feed.scene.mosaic.video': 'Scena {index}, video',
  'feed.scene.shared_by': 'Scena condivisa da {author}',
  'feed.scene.open.fullscreen': 'Tocca due volte per vedere a schermo intero',
  'feed.scene.open.post': 'Tocca due volte per aprire il post',
  'feed.scene.sound.muted': 'Audio disattivato',
  'feed.scene.count': '{count} scene',
  'scene.fullscreen.play': 'Riprendi tutto',
  'scene.fullscreen.pause': 'Metti tutto in pausa',
  'scene.fullscreen.sound.on': "Attiva l'audio",
  'scene.fullscreen.sound.off': "Disattiva l'audio",
  'scene.place.here': 'Qui',

  'story.sound.off': 'Muto',

  /* LO STUDIO DELLE STORY (#6900) — creare una story con uno sfondo, un
     suono di sottofondo e un testo, anteprima tramite il motore condiviso,
     pubblicata in CanvasV3 come su iOS. */
  'story.studio.title': 'Nuova story',
  'story.studio.cancel': 'Annulla',
  'story.studio.publish': 'Pubblica',
  'story.studio.publishing': 'Pubblicazione…',
  'story.studio.publish.waiting': 'In attesa della rete…',
  'story.studio.publishing.progress': 'Pubblicazione {current}/{total}…',
  'story.studio.outcome.partial': '{published} su {total} pubblicate — le altre restano qui.',
  'story.studio.title.post': 'Nuovo post',
  'story.studio.title.reel': 'Nuovo reel',
  'story.studio.publish.as.story': 'Pubblica storia',
  'story.studio.publish.as.post': 'Pubblica post',
  'story.studio.publish.as.reel': 'Pubblica reel',
  'story.studio.publish.menu': 'Pubblica come',
  'story.studio.kind.story': 'Storia',
  'story.studio.kind.post': 'Post',
  'story.studio.kind.reel': 'Reel',
  'story.studio.refusal.reel': 'Un reel richiede un video o un suono di almeno 3 secondi, o almeno due immagini.',
  'story.studio.offline': 'Offline — la story verrà pubblicata al ritorno della rete.',
  'story.studio.stage': 'Anteprima della story',
  'story.studio.background.add': 'Aggiungi una foto o un video',
  'story.studio.background.label': 'Sfondo',
  'story.studio.background.remove': 'Rimuovi lo sfondo',
  'story.studio.sound.add': 'Aggiungi un suono',
  'story.studio.sound.label': 'Suono di sottofondo',
  'story.studio.sound.remove': 'Rimuovi il suono',
  'story.studio.sound.mute': 'Disattiva audio',
  'story.studio.sound.unmute': 'Attiva audio',
  'story.studio.upload.progress': 'Invio… {percent} %',
  'story.studio.upload.ready': 'Pronto',
  'story.studio.upload.retry': 'Riprova',
  'story.studio.text.label': 'Testo della story',
  'story.studio.text.placeholder': 'Aggiungi testo',
  'story.studio.hint.duration': 'Una story resta visibile per venti ore.',
  'story.studio.error.upload': 'Il file non è stato inviato.',
  'story.studio.error.publish': 'La story non è stata pubblicata.',
  'story.studio.refusal.title': 'Serve un account per creare una story.',
  'story.studio.refusal.login': 'Accedi',
  'story.studio.refusal.door.visual': 'Scegli un’immagine o un video.',
  'story.studio.refusal.door.sound': 'Scegli un file audio.',
  'story.studio.refusal.media-max': 'Questa pubblicazione porta già dieci contenuti multimediali — il limite della piattaforma.',
  'story.studio.failure.network': 'Rete non disponibile.',
  'story.studio.failure.timeout': 'Il server non ha risposto.',
  'story.studio.failure.session': 'Sessione scaduta — accedi di nuovo.',
  'story.studio.failure.account': 'Serve un account per pubblicare un contenuto multimediale.',
  'story.studio.failure.forbidden': 'Azione non consentita per questo account.',
  'story.studio.failure.tooLarge': 'File troppo pesante.',
  'story.studio.failure.fileRefused': 'File rifiutato: il tipo non corrisponde al contenuto.',
  'story.studio.failure.rateLimited': 'Troppe pubblicazioni in una volta — riprova tra un attimo.',
  'story.studio.failure.refused': 'Pubblicazione rifiutata.',
  'story.studio.failure.unavailable': 'Il server non è disponibile.',
  'story.studio.text.add': 'Aggiungi testo',
  'story.studio.text.remove': 'Rimuovi questo testo',
  'story.studio.object.text': 'Testo {index}',
  'story.studio.object.overlay': 'Livello',
  'story.studio.object.select': 'Seleziona {name}',
  'story.studio.objects.label': 'Oggetti della scena',
  'story.studio.overlay.add': 'Metti un’immagine sulla scena',
  'story.studio.overlay.label': 'Livello',
  'story.studio.overlay.remove': 'Rimuovi il livello',
  'story.studio.pages.label': 'Scene della pubblicazione',
  'story.studio.page.position': 'Scena {index} di {count}',
  'story.studio.page.add': 'Crea una scena',
  'story.studio.page.remove': 'Elimina la scena {index}',
  'story.studio.page.failed': 'un contenuto multimediale non è stato caricato',
  'story.studio.layout.title': 'Disposizione delle scene',
  'story.studio.layout.carousel': 'Una alla volta',
  'story.studio.layout.reel': 'Scorrimento continuo',
  'story.studio.layout.hero': 'Una grande, le altre a fianco',
  'story.studio.layout.wave': 'A onda',
  'story.studio.layout.sine': 'A zigzag',
  'story.studio.caption.label': 'Didascalia di {media}',
  'story.studio.caption.placeholder': 'Aggiungi una didascalia',
  'story.studio.sound.plane.label': 'Posizione del suono',
  'story.studio.sound.plane.background': 'In sottofondo',
  'story.studio.sound.plane.foreground': 'Sulla scena',
  'story.studio.editor.label': 'Impostazioni dell’oggetto',
  'story.studio.editor.style': 'Carattere',
  'story.studio.editor.effect': 'Effetto',
  'story.studio.editor.color': 'Colore',
  'story.studio.editor.align': 'Allineamento',
  'story.studio.editor.background': 'Sfondo del testo',
  'story.studio.editor.language': 'Lingua del testo',
  'story.studio.editor.none': 'Nessuno',
  'story.studio.editor.empty': 'Seleziona un oggetto per regolarlo.',
  'story.studio.style.bold': 'Grassetto',
  'story.studio.style.neon': 'Neon',
  'story.studio.style.classic': 'Classico',
  'story.studio.style.italic': 'Corsivo',
  'story.studio.style.typewriter': 'Macchina',
  'story.studio.style.handwriting': 'Manoscritto',
  'story.studio.style.calligraphy': 'Calligrafia',
  'story.studio.style.cartoon': 'Fumetto',
  'story.studio.style.futuristic': 'Futuristico',
  'story.studio.style.fantasy': 'Fantasia',
  'story.studio.style.curve': 'Curva',
  'story.studio.style.tag': 'Graffiti',
  'story.studio.style.retro': 'Retrò',
  'story.studio.style.elegant': 'Elegante',
  'story.studio.style.poster': 'Manifesto',
  'story.studio.style.bubble': 'Bolla',
  'story.studio.style.note': 'Nota',
  'story.studio.style.brush': 'Pennello',
  'story.studio.effect.glow': 'Bagliore',
  'story.studio.effect.neon': 'Neon',
  'story.studio.effect.outline': 'Contorno',
  'story.studio.effect.shadow': 'Ombra',
  'story.studio.effect.longShadow': 'Ombra lunga',
  'story.studio.effect.emboss': 'Rilievo',
  'story.studio.color.FFFFFF': 'Bianco',
  'story.studio.color.000000': 'Nero',
  'story.studio.color.FF2E63': 'Rosa',
  'story.studio.color.08D9D6': 'Ciano',
  'story.studio.color.F8B500': 'Ambra',
  'story.studio.color.9B59B6': 'Viola',
  'story.studio.color.2ECC71': 'Verde',
  'story.studio.color.3498DB': 'Blu',
  'story.studio.align.left': 'Sinistra',
  'story.studio.align.center': 'Centro',
  'story.studio.align.right': 'Destra',
  'story.studio.pose.label': 'Posizione e dimensione',
  'story.studio.pose.bigger': 'Ingrandisci',
  'story.studio.pose.smaller': 'Riduci',
  'story.studio.pose.rotateLeft': 'Ruota a sinistra',
  'story.studio.pose.rotateRight': 'Ruota a destra',
  'story.studio.pose.reset': 'Ricentra',
  'story.studio.pose.handle': 'Sposta {name} — frecce per spostare, + e − per la dimensione, [ e ] per ruotare',
  'story.studio.pose.grip': 'Ridimensiona e ruota {name}',

  /* IL FOGLIO DI DESTINATARI DELLO STUDIO (#7683) — i sei PostVisibility,
     specchio di PostVisibility.swift (packages/MeeshySDK). */
  'story.studio.audience.chip.label': 'Destinatari',
  'story.studio.audience.title': 'Destinatari',
  'story.studio.audience.public': 'Pubblico',
  'story.studio.audience.community': 'Community',
  'story.studio.audience.friends': 'Contatti',
  'story.studio.audience.except': 'Tranne…',
  'story.studio.audience.only': 'Solo…',
  'story.studio.audience.private': 'Privato',
  'story.studio.audience.subtitle.public': 'Tutti, compresi i non follower',
  'story.studio.audience.subtitle.community': 'I membri delle tue community',
  'story.studio.audience.subtitle.friends': 'I tuoi contatti accettati',
  'story.studio.audience.subtitle.private': 'Solo tu — non viene pubblicato nulla',
  'story.studio.audience.refusal.people': 'La scelta delle persone non è ancora disponibile sul web.',
  'story.studio.audience.scope': 'I destinatari scelti appartengono alla pubblicazione, mai a un formato: cambiare formato li conserva.',
  'story.studio.audience.defaultMark': 'predefinito',

  'appUpdate.available': 'È disponibile una nuova versione di Meeshy!',
  'appUpdate.hint': 'Ricarica per avere le ultime novità.',
  'appUpdate.storeHint': 'Installala dallo store delle app.',
  'appUpdate.action': 'Aggiorna',
  'appUpdate.dismiss': 'Attendi',
  'appUpdate.applying': 'Aggiornamento…',
  'appUpdate.region': 'Aggiornamento dell’app',

  'story.action.rail': 'Azioni della storia',
  'story.action.react': 'Reagisci',
  'story.action.reply': 'Rispondi',
  'story.action.forward': 'Invia',
  'story.action.repost': 'Ripubblica',
  'story.action.views': 'Visualizzazioni',
  'story.action.share': 'Condividi',
  'story.action.save': 'Salva',
  'story.action.comments': 'Commenti',
  'story.action.translations': 'Traduzioni',
  'story.language.bar': 'Lingue disponibili',
  'story.language.original': 'Originale',
  'story.language.more': 'Altre lingue',
  'story.views.empty.title': 'Ancora nessuna visualizzazione',
  'story.views.empty.subtitle': 'Le persone che guardano la tua storia appariranno qui.',
  'story.views.count.one': '{count} visualizzazione',
  'story.views.count.other': '{count} visualizzazioni',
  'story.save.progress': 'Salvataggio {percent}%',
  'story.save.cancel': 'Annulla salvataggio',
  'story.save.success': 'Storia salvata',
  'story.save.failed': 'Salvataggio non riuscito',
  'story.save.cancelled': 'Esportazione annullata',
  'story.views.loading': 'Caricamento delle visualizzazioni…',
  'story.views.offline': 'Offline — l’elenco apparirà al ritorno della rete.',
  'story.views.forbidden': 'Solo l’autore può vedere chi ha guardato questa storia.',
  'story.save.offline': 'Offline — riprova al ritorno della rete.',
  'story.save.refused': 'Accedi per salvare questa storia.',
  'story.save.missing': 'Questo contenuto non è più disponibile.',
  'story.save.retry': 'Riprova — tocca di nuovo Salva.',
  'prism.translated.message': 'Messaggio tradotto',
  'prism.translated.comment': 'Commento tradotto',
  'prism.translated.post': 'Post tradotto',
  'prism.original.show.message': 'Mostra il messaggio nella lingua originale',
  'prism.original.show.comment': 'Mostra il commento nella lingua originale',
  'prism.original.show.post': 'Mostra il post nella lingua originale',
  'prism.original.hide.message': 'Nascondi il messaggio nella lingua originale',
  'prism.original.hide.comment': 'Nascondi il commento nella lingua originale',
  'prism.original.hide.post': 'Nascondi il post nella lingua originale',

  'comments.title': 'Commenti',
  'comments.close': 'Chiudi i commenti',
  'comments.loading': 'Caricamento dei commenti',
  'comments.empty': 'Nessun commento',
  'comments.empty.hint': 'Scrivi tu il primo.',
  'comments.error': 'Impossibile caricare i commenti',
  'comments.error.hint': 'Riprova tra un istante.',
  'comments.retry': 'Riprova',
  'comments.more': 'Carica altri commenti',
  'comments.offline': 'Offline — vengono mostrati solo i commenti già caricati.',
  'comments.placeholder': 'Scrivi un commento…',
  'comments.send': 'Invia il commento',
  'comments.row.pending': 'Invio in corso',
  'comments.signin': 'Accedi per commentare.',
  'comment.send.error': 'Non è stato possibile pubblicare il commento.',
  'comment.send.pending': 'Commento non confermato — offline',
  'comment.send.empty': 'Scrivi qualcosa prima di inviare.',
  'comments.action.like': 'Mi piace',
  'comments.action.unlike': 'Non mi piace più',
  'comments.action.edit': 'Modifica',
  'comments.action.delete': 'Elimina',
  'comments.action.delete.confirm': 'Conferma',
  'comments.edit.label': 'Modifica commento',
  'comments.edit.save': 'Salva',
  'comments.edit.cancel': 'Annulla',
  'comment.like.error': 'Il «mi piace» non è stato salvato.',
  'comment.edit.error': 'La modifica non è stata salvata.',
  'comment.delete.error': 'Non è stato possibile eliminare il commento.',
  'comment.gesture.pending': 'Azione non confermata — offline',
  'comment.gesture.unconfirmed': 'Azione non confermata — il gateway non ha risposto.',
  'comment.refused.session': 'Sessione scaduta — accedi di nuovo.',
  'comment.refused.right': 'Questa azione non ti è consentita.',
  'comment.like.limit': 'Al massimo cinque reazioni a persona.',
  'feed.action.comment': 'Commenta',

  'admin.title': 'Amministrazione',

  'thread.unread-separator.one': '{count} messaggio non letto',
  'thread.unread-separator.other': '{count} messaggi non letti',
  'message-detail.info.title': 'Informazioni sul messaggio',
  'message-detail.received-by': 'Ricevuto da',
  'message-detail.read-by': 'Letto da',
  'message-detail.not-yet': 'Non ancora',
  'message-detail.received-by.empty': 'Nessuna conferma di consegna',
  'message-detail.read-by.empty': 'Nessuno ha ancora letto questo messaggio',
  'message-detail.not-yet.empty': 'Tutti hanno ricevuto il messaggio',
  'message-detail.open': 'Visualizza i dettagli del messaggio',
  'message-detail.attachment.opens.one': '{count} apertura',
  'message-detail.attachment.opens.other': '{count} aperture',
  'message-detail.attachment.downloads.one': '{count} download',
  'message-detail.attachment.downloads.other': '{count} download',
  'message-detail.attachment.listened-until': 'Ascoltato fino a {time}',
  'message-detail.attachment.watched-until': 'Guardato fino a {time}',
  'message-detail.attachment.complete': 'Completo',
  'message-detail.attachment.listen.empty': 'Non ancora ascoltato',
  'message-detail.attachment.watch.empty': 'Non ancora guardato',
  'message-detail.attachment.open': 'Apri {name}',
  'message-detail.attachment.opened.empty': 'Non ancora aperto',
  'message-detail.loading': 'Caricamento…',
  'message-detail.load-error': 'Impossibile caricare queste informazioni',
  'message-detail.retry': 'Riprova',

  'download.title': 'Scarica Meeshy',
  'download.body': 'Scrivi nella tua lingua e leggi nella tua: Meeshy traduce ogni messaggio lungo la strada.',
  'download.appStore': 'Scarica su App Store',
  'download.web': 'Apri Meeshy nel browser',
  'download.otherPlatforms': 'Su Android e su computer, Meeshy funziona direttamente nel browser.',

  /* LES SOURCES DU COMPOSEUR (#7280) — miroir de `composer.attach.*` d'iOS. */
  ...itComposerAttach,
  'composer.viewOnce.activate': 'Attiva la modalità visione unica',
  'composer.viewOnce.active': 'Modalità visione unica attiva',
  'composer.viewOnce.label': 'Visione unica',
  'composer.protection.ephemeral.state': 'Modalità effimera attiva',
  'composer.protection.blur.state': 'Modalità sfocatura attiva',
  'message.location.shared': 'Posizione condivisa',
  'message.location.open': 'Apri in Mappe',
  'message.location.a11y': 'Posizione: {place}',

  /* LES LIBELLÉS D'ÉTAT DU FIL (#7337) — voir `catalog-fr.ts` pour la règle. */
  'message.forwarded': 'Inoltrato',
  'message.forwarded.fromGroup': 'Inoltrato da {name}',
  'message.forwarded.fromPerson': 'Inoltrato da {name}',
  'message.send.failed': 'Non inviato',
  'message.send.failed.reason': 'Non inviato — {reason}',
  'message.send.retry': 'Riprova',
  'announce.messageNotSent': 'Messaggio non inviato',
  'announce.messageNotSent.reason': 'Messaggio non inviato — {reason}',
  'send.failure.offline': 'rete non disponibile',
  'send.failure.timeout': 'il server non ha risposto',
  'send.failure.uploadPartial': 'impossibile caricare un allegato',
  'send.failure.newcomerSlowMode': 'benvenuto! i nuovi account possono inviare un messaggio ogni 30 s — riprova tra {seconds} s',
  'send.failure.newcomerSlowMode.soon': 'benvenuto! i nuovi account possono inviare un messaggio ogni 30 s — riprova tra un istante',
  'send.failure.sessionExpired': 'sessione scaduta — accedi di nuovo',
  'send.failure.forbidden': 'invio non consentito in questa conversazione',
  'send.failure.tooMany': 'troppi messaggi in una volta — riprova tra un istante',
  'send.failure.rejected': 'messaggio rifiutato',
  'send.failure.gatewayUnavailable': 'il server non è disponibile',
  'message.deleted': 'Messaggio eliminato',
  'message.expired.a11y': 'Messaggio effimero scaduto',
  'message.story.reply': 'risposta alla sua storia',
  'message.story.label': 'Storia',
  'message.story.unavailable': 'Storia non disponibile',
  'message.mood.label': 'Umore',
  'message.withheld': 'Contenuto trattenuto',
  'message.withheld.a11y': 'Contenuto trattenuto: questo messaggio esiste e non viene mostrato',
  'message.veiled': 'Contenuto nascosto',
  'message.veiled.hint': 'Tocca per rivelare il contenuto',
  'message.veiled.error': 'Impossibile rivelare per ora',
  'message.ephemeral.a11y': 'Messaggio effimero, scompare tra {remaining}',
  'message.ephemeral.awaiting': 'In attesa della ricezione',
  'message.ephemeral.awaiting.a11y': 'Messaggio effimero di {duration}, in attesa della ricezione',
  'message.viewOnce.tap': 'Tocca per vedere',
  'message.viewOnce.opened': 'Già aperto',
  'message.viewOnce.sealed.a11y': 'Messaggio visualizzabile una volta, tocca per vedere',
  'message.viewOnce.opened.a11y': 'Messaggio visualizzabile una volta, già aperto',
  'message.viewOnce.close': 'Chiudi',
  'attachment.protected.image': 'Foto protetta',
  'attachment.protected.video': 'Video protetto',
  'attachment.protected.audio': 'Audio protetto',
  'attachment.protected.file': 'Allegato protetto',
  'attachment.protected.open.hint': 'tocca per vederlo a schermo intero',
  'media.reactions.badge.a11y': 'Reazioni',
  'media.reactions.badge.mine.a11y': 'compresa la tua',
  'attachment.kind.image': 'Foto',
  'attachment.kind.video': 'Video',
  'attachment.kind.audio': 'Audio',
  'attachment.kind.file': 'File',

  /* Le menu du message, sa barre de sélection et sa feuille « Plus… » (#7555). */
  'message.menu.select': 'Seleziona',
  'message.menu.translate': 'Traduci',
  'message.menu.copy': 'Copia',
  'message.menu.forward': 'Inoltra',
  'message.menu.reply': 'Rispondi',
  'message.menu.more': 'Altro…',
  'message.menu.react': 'Reagisci',
  'message.menu.addReaction': 'Aggiungi una reazione',
  'message.selection.toolbar': 'Selezione dei messaggi',
  'message.selection.count': '{count} selezionati',
  'message.detail.title': 'Dettagli del messaggio',
  'message.detail.languages': 'Lingue',
  'message.detail.reactions': 'Reazioni',
  'message.detail.sent': 'Inviato',
  'message.detail.language.original': '{language} (originale)',

  ...itMentions,
  ...itStoriesMine,
} satisfies InterfaceCatalog;

export default it;
