import type { ExportCardCatalog } from '@/lib/i18n-export-card-catalog';

const ar = {
  'export.card.title': 'Imagine',
  'export.card.popular': 'الأكثر استخدامًا',
  'export.card.random': 'عشوائي',
  'export.card.palette': 'الألوان',
  'export.card.typeface': 'الخط',
  'export.card.link': 'الربط',
  'export.card.typeface.rond': 'مستدير',
  'export.card.typeface.didone': 'ديدون',
  'export.card.typeface.plume': 'ريشة',
  'export.card.typeface.affiche': 'ملصق',
  'export.card.typeface.futur': 'مستقبلي',
  'export.card.typeface.machine': 'آلة كاتبة',
  'export.card.typeface.marqueur': 'قلم تحديد',
  'export.card.typeface.systeme': 'النظام',
  'export.card.link.orbite': 'مدار',
  'export.card.link.filet': 'خط فاصل',
  'export.card.link.guillemets': 'علامات اقتباس',
  'export.card.link.fleche': 'سهم',
  'export.card.link.bulles': 'فقاعات',
  'export.card.link.fil': 'خيط',
  'export.card.link.silence': 'صمت',
  'export.card.option.anonymizeQuoted': 'إخفاء هوية كاتب الرسالة المقتبسة',
  'export.card.option.anonymizeReply': 'إخفاء هوية كاتب الرد',
  'export.card.anonymous': 'مجهول',
  'export.card.preview': 'معاينة الصورة',
  'export.card.rendering': 'جارٍ تجهيز الصورة…',
  'export.card.save': 'حفظ',
  'export.card.share': 'مشاركة',
  'export.card.language': 'لغة الرسالة',
  'export.card.language.asRead': 'كما أقرؤها',
  'export.card.truncated': 'رسالة طويلة: نهايتها مقطوعة في الصورة.',
  'export.announce.gallery': 'حُفظت الصورة في المعرض',
  'export.announce.shared': 'الصورة جاهزة',
  'export.announce.cancelled': 'أُلغي التصدير',
  'export.announce.expired': 'اضغط مجددًا للحفظ',
  'export.announce.failed': 'تعذّر إنشاء الصورة',
  'export.announce.unavailable': 'لا يستطيع هذا الجهاز حفظ الصورة',
  'export.card.options': 'إظهار',
  'export.card.option.title': 'عنوان المحادثة',
  'export.card.option.authors': 'أسماء الكتّاب',
  'export.card.option.date': 'التاريخ',
  'export.card.default.save': 'استخدام كتنسيق افتراضي',
  'export.card.default.current': 'التنسيق الافتراضي',
  'export.announce.defaultSaved': 'حُفظ التنسيق الافتراضي',
  'export.card.tab.styles': 'الأنماط',
  'export.card.tab.palette': 'الخلفية',
  'export.card.tab.typeface': 'الخط',
  'export.card.tab.link': 'الربط',
  'export.card.tab.details': 'التفاصيل',
  'export.card.tab.language': 'اللغة',
  'export.card.part.header': 'الترويسة',
  'export.card.part.quote': 'الاقتباس',
  'export.card.part.link': 'الربط',
  'export.card.part.reply': 'الرد',
  'export.card.part.background': 'الخلفية',
  'export.card.hint': 'المس جزءًا من البطاقة لضبطه',
  'export.card.gallery.open': 'عرض الكل',
  'export.card.gallery.title': 'كل الأنماط',
  'export.card.gallery.count': '{count} نمطًا',
  'export.card.gallery.close': 'إغلاق المعرض',
  'export.card.gallery.search': 'ابحث عن نمط',
  'export.card.gallery.placeholder': 'ريشة، داكن، فقاعات…',
  'export.card.gallery.empty': 'لا يحمل أي نمط هذا الاسم. جرّب لونًا أو خطًا أو «داكن».',
  'export.card.tone.all': 'الكل',
  'export.card.tone.dark': 'داكن',
  'export.card.tone.light': 'فاتح',
  'export.card.typeface.pairs': 'الخط يكسو الاقتباس والرد',
  'export.card.tab.frame': 'الإطار',
  'export.card.tab.media': 'الوسائط',
  'export.card.part.media': 'الوسائط',
  'export.card.part.replies': 'الردود',
  'export.card.aspect': 'مقاس الصورة',
  'export.card.aspect.auto': 'مُلائم',
  'export.card.aspect.story': 'قصة 9:16',
  'export.card.aspect.portrait': 'عمودي 4:5',
  'export.card.aspect.square': 'مربع 1:1',
  'export.card.aspect.landscape': 'أفقي 16:9',
  'export.card.header': 'العنوان والتاريخ',
  'export.card.header.horizontal': 'في سطر',
  'export.card.header.letters': 'حرفًا حرفًا',
  'export.card.header.up': 'إلى الأعلى',
  'export.card.header.down': 'إلى الأسفل',
  'export.card.authorsAt': 'الأسماء',
  'export.card.authorsAt.top': 'فوق الرسالة',
  'export.card.authorsAt.end': 'في نهاية الرسالة',
  'export.card.tilt': 'تدوير الرسالة',
  'export.card.tilt.none': 'مستقيم',
  'export.card.tilt.left': 'مائل لليسار',
  'export.card.tilt.right': 'مائل لليمين',
  'export.card.option.times': 'أوقات الرسائل',
  'export.card.option.pseudonyms': 'اسم المستخدم بدل الاسم الظاهر',
  'export.card.anonymity': 'إخفاء الهوية',
  'export.card.media.style': 'ترتيب الصور',
  'export.card.media.mosaique': 'فسيفساء',
  'export.card.media.pleine': 'بعرض كامل',
  'export.card.media.bande': 'شريط',
  'export.card.audio.style': 'تمثيل الصوت',
  'export.card.audio.onde': 'موجة',
  'export.card.audio.spectre': 'طيف',
  'export.card.audio.pastille': 'كبسولة',
  'export.card.audio.etiquette': 'بطاقة',
  'export.card.media.loading': 'جارٍ تحميل الوسائط…',
  'export.card.media.failed.one': 'تعذّر تحميل وسيط واحد.',
  'export.card.media.failed.other': 'تعذّر تحميل {count} من الوسائط.',
  'export.card.media.retry': 'إعادة المحاولة',
  'export.card.output': 'حفظ بصيغة',
  'export.card.output.image': 'صورة',
  'export.card.output.gif': 'GIF',
  'export.card.output.video': 'فيديو',
  'export.card.motion.video': 'جارٍ إنشاء الفيديو…',
  'export.card.motion.gif': 'جارٍ إنشاء GIF…',
  'export.announce.motionUnavailable': 'لا يستطيع هذا المتصفح إنشاء هذه الحركة',
  'export.announce.galleryMotion': 'حُفظ في المعرض',
  'export.announce.sharedMotion': 'جاهز للمشاركة',
} satisfies ExportCardCatalog;

export default ar;
