import type { CallControlsCatalog } from '@/lib/i18n-call-controls-catalog';

const pt = {
  'callControls.invite': 'Adicionar',
  'callControls.invite.label': 'Adicionar pessoas à chamada',
  'callControls.react': 'Reagir',
  'callControls.react.label': 'Enviar uma reação',
  'callControls.react.palette': 'Reações',
  'callControls.react.send': 'Reagir com {emoji}',
  'callControls.react.from': '{name} reagiu {emoji}',
  'callControls.react.mine': 'Você reagiu {emoji}',
  'callControls.people.title': 'Participantes',
  'callControls.people.inCall': 'Na chamada',
  'callControls.people.add': 'Adicionar pessoas',
  'callControls.people.search': 'Pesquisar um contato',
  'callControls.people.empty': 'Todos os seus contatos já estão na chamada',
  'callControls.people.none': 'Nenhum contato corresponde',
  'callControls.people.invite': 'Convidar',
  'callControls.people.inviteNamed': 'Convidar {name}',
  'callControls.people.loading': 'Carregando contatos…',
  'callControls.people.you': 'Você',
  'callControls.close': 'Fechar',
  'callControls.ringing': 'Tocando…',
  'callControls.invite.declined': '{name} recusou',
  'callControls.invite.unanswered': '{name} não atendeu',
  'callControls.moderate.menu': 'Opções para {name}',
  'callControls.mute': 'Silenciar microfone',
  'callControls.mute.done': 'Microfone silenciado',
  'callControls.remove': 'Remover da chamada',
  'callControls.remove.confirm': 'Remover {name} da chamada?',
  'callControls.remove.detail': 'A chamada terminará imediatamente para {name}.',
  'callControls.remove.do': 'Remover',
  'callControls.cancel': 'Cancelar',
  'callControls.mutedBy': '{name} silenciou seu microfone',
  'callControls.someone': 'Um participante',
  'callControls.incomingInvite': '{name} convida você para uma chamada em grupo',
  'callControls.error.invite': 'Não foi possível convidar {name}',
  'callControls.error.mute': 'Não foi possível silenciar {name}',
  'callControls.error.remove': 'Não foi possível remover {name}',
  'callControls.error.notContact': '{name} não está nos seus contatos',
  'callControls.error.alreadyIn': '{name} já está na chamada',
  'callControls.error.full': 'A chamada está cheia',
  'callControls.error.rateLimited': 'Tentativas demais: tente novamente em instantes',
  'callControls.error.denied': 'Você não tem esse direito nesta chamada',
  'callControls.error.notActive': 'A chamada não está mais ativa',
  'callControls.error.gone': '{name} não está mais na chamada',
  'callControls.record.title': 'O que você quer gravar?',
  'callControls.record.audio': 'Só áudio',
  'callControls.record.audioDetail': 'As vozes de todos',
  'callControls.record.video': 'Áudio e vídeo',
  'callControls.record.videoDetail': 'As imagens visíveis e as vozes',
  'callControls.capture': 'Capturar',
  'callControls.capture.label': 'Capturar a chamada',
  'callControls.back': 'Voltar',
  'callControls.journal': 'Diário',
  'callControls.journal.label': 'Abrir o diário da chamada',
  'callControls.journal.live': 'Voltar ao direto',
  'callControls.journal.empty': 'Ainda nada foi transcrito. Ative as legendas: cada frase dita aparece aqui com a sua tradução, durante toda a chamada.',
  'callControls.journal.original': 'Original',
  'callControls.camera.denied': 'O acesso à câmara foi recusado',
  'callControls.camera.failed': 'Não foi possível abrir a câmara',
  'callControls.cameraPicker': 'Câmara',
  'callControls.cameraPicker.label': 'Escolher a câmara',
  'callControls.cameraPicker.unnamed': 'Câmara {n}',
  'callControls.pip': 'PiP',
  'callControls.camera.options': 'Opções da minha câmara',
  'callControls.selfTile.small': 'A minha miniatura: pequena',
  'callControls.selfTile.medium': 'A minha miniatura: média',
  'callControls.selfTile.large': 'A minha miniatura: grande',
  'callControls.selfTile.hint': 'Toque para trocar os vídeos; arraste-a ou use as setas para movê-la',
  'callControls.selfTile.corner.top-left': 'Minha miniatura: no alto à esquerda',
  'callControls.selfTile.corner.top-right': 'Minha miniatura: no alto à direita',
  'callControls.selfTile.corner.bottom-left': 'Minha miniatura: embaixo à esquerda',
  'callControls.selfTile.corner.bottom-right': 'Minha miniatura: embaixo à direita',
} satisfies CallControlsCatalog;

export default pt;
