import type { InviteCatalog } from '@/lib/i18n-invite-catalog';

const it = {
  'invite.brand': 'Meeshy',
  'invite.loading': 'Apertura dell’invito…',
  'invite.inviter.named': '{name} ti invita',
  'invite.inviter.unnamed': 'Sei invitato a unirti',
  'invite.inviter.message': 'Messaggio di {name}',
  'invite.group.fallbackTitle': 'Una conversazione Meeshy',
  'invite.group.created': 'creato il {date}',
  'invite.group.logo': 'Logo di {name}',
  'invite.kind.direct': 'Conversazione privata',
  'invite.kind.group': 'Gruppo',
  'invite.kind.public': 'Conversazione pubblica',
  'invite.kind.global': 'Aperta a tutti',
  'invite.kind.broadcast': 'Canale di trasmissione',
  'invite.link.label': 'Link della conversazione',
  'invite.link.copy': 'Copia',
  'invite.link.copied': 'Copiato',
  'invite.link.reshare': 'Condividi di nuovo',
  'invite.announce.copied': 'Link copiato.',
  'invite.announce.copyFailed': 'Impossibile copiare il link qui.',
  'invite.announce.shareUnavailable': 'La condivisione non è disponibile qui.',
  'invite.share.text': 'Unisciti a {name} su Meeshy — ognuno scrive nella propria lingua.',
  'invite.stats.people.one': 'persona',
  'invite.stats.people.other': 'persone',
  'invite.stats.languages.one': 'lingua parlata',
  'invite.stats.languages.other': 'lingue parlate',
  'invite.stats.spoken': 'Qui si parla',
  'invite.stats.share': '{language} {percent}',
  'invite.rights.title': 'Senza account, potrai',
  'invite.rights.messages': 'Scrivere messaggi',
  'invite.rights.images': 'Inviare immagini',
  'invite.rights.files': 'Inviare file',
  'invite.rights.history': 'Vedere i messaggi precedenti al tuo arrivo',
  'invite.rights.granted': 'consentito',
  'invite.rights.denied': 'non consentito',
  'invite.asked.label': 'Ti verrà chiesto:',
  'invite.asked.nickname': 'un nome',
  'invite.asked.email': 'un indirizzo e-mail',
  'invite.asked.birthday': 'la tua data di nascita',
  'invite.asked.nothing': 'nient’altro che la tua lingua',
  'invite.languages.label': 'Lingue accettate:',
  'invite.languages.all': 'tutte',
  'invite.validity.label': 'Link valido',
  'invite.validity.days.one': 'ancora {count} giorno',
  'invite.validity.days.other': 'ancora {count} giorni',
  'invite.validity.today': 'fino a oggi',
  'invite.validity.forever': 'senza limiti di tempo',
  'invite.places.unlimited': 'posti illimitati',
  'invite.places.one': '{count} posto rimasto',
  'invite.places.other': '{count} posti rimasti',
  'invite.join.title': 'Unisciti a {name}',
  'invite.join.account': 'Unisciti con il mio account',
  'invite.join.joining': 'Ingresso nella conversazione…',
  'invite.join.joined': 'Ti sei unito alla conversazione. Apertura del thread…',
  'invite.join.offline': 'Offline — l’ingresso attenderà il ritorno della rete.',
  'invite.guest.continue': 'Continua senza account',
  'invite.guest.nickname': 'Il tuo nome',
  'invite.guest.nickname.optional': 'Il tuo nome (facoltativo)',
  'invite.guest.nickname.placeholder': 'Come ti chiamiamo?',
  'invite.guest.nickname.placeholder.optional': 'Lascia vuoto per un nickname generato',
  'invite.guest.language': 'La tua lingua',
  'invite.guest.email': 'La tua e-mail',
  'invite.guest.email.placeholder': 'tu@esempio.com',
  'invite.guest.birthday': 'La tua data di nascita',
  'invite.exits.separator': 'oppure con il tuo account',
  'invite.exits.signIn': 'Accedi',
  'invite.exits.signUp': 'Crea un account',
  'invite.exits.accountRequired': 'Questa conversazione richiede un account Meeshy.',
  'invite.refusal.not-found': 'Invito non trovato. Il link potrebbe essere incompleto.',
  'invite.refusal.revoked': 'Questo link è stato disattivato dalla persona che l’ha condiviso.',
  'invite.refusal.expired': 'Questo link è scaduto o non è più attivo.',
  'invite.refusal.closed': 'Questa conversazione è terminata: non è più possibile unirsi.',
  'invite.refusal.full': 'Questo link ha raggiunto il limite di partecipanti.',
  'invite.refusal.language': 'Questo invito non accetta la tua lingua.',
  'invite.refusal.banned': 'Non puoi più unirti a questa conversazione.',
  'invite.refusal.region': 'Questo invito non è accessibile dalla tua rete.',
  'invite.refusal.account-required': 'Serve un account Meeshy per unirsi a questa conversazione.',
  'invite.refusal.session-expired': 'La tua sessione è scaduta. Accedi di nuovo per unirti.',
  'invite.refusal.rate-limited': 'Troppi tentativi. Riprova tra un attimo.',
  'invite.refusal.offline': 'Sei offline. L’invito comparirà al ritorno della rete.',
  'invite.refusal.unavailable': 'L’invito non è disponibile al momento.',
  'invite.missing.nickname': 'Scegli un nome per questa conversazione.',
  'invite.missing.email': 'Questo link richiede un indirizzo e-mail valido.',
  'invite.missing.birthday': 'Questo link richiede la tua data di nascita.',
  'invite.missing.language': 'Scegli una delle lingue accettate da questo link.',
  'invite.refused.nickname': 'Questo nome è già in uso in questa conversazione.',
  'invite.refused.email': 'Questo indirizzo e-mail è stato rifiutato.',
  'invite.refused.birthday': 'Questa data di nascita è stata rifiutata.',
  'invite.refused.language': 'Questo invito non accetta questa lingua.',
  'invite.refused.none': 'Un’informazione richiesta manca o è stata rifiutata.',
  'invite.refused.taken': 'Questo nome è già in uso — «{suggestion}» è libero.',
  'invite.retry': 'Riprova',
  'invite.home': 'Torna alla home',

  'linkDetail.title': 'Link di invito',
  'linkDetail.breadcrumb': 'Percorso di navigazione',
  'linkDetail.breadcrumb.links': 'Link',
  'linkDetail.breadcrumb.share': 'Link di conversazione',
  'linkDetail.card.created': 'Link creato il {date}',
  'linkDetail.card.share': 'Condividi',
  'linkDetail.card.copy': 'Copia il link',
  'linkDetail.card.copied': 'Link copiato',
  'linkDetail.stats.title': 'Statistiche',
  'linkDetail.stats.visits': 'Visite',
  'linkDetail.stats.arrivals': 'Arrivi',
  'linkDetail.stats.anonymous': 'Senza account',
  'linkDetail.stats.unknown': 'non ancora misurato',
  'linkDetail.stats.unavailable': 'Le statistiche di questo link non sono ancora disponibili.',
  'linkDetail.languages.title': 'Lingue dei nuovi arrivati',
  'linkDetail.languages.empty': 'Nessun arrivo per ora.',
  'linkDetail.recent.title': 'Arrivati di recente',
  'linkDetail.recent.anonymous': 'senza account',
  'linkDetail.recent.empty': 'Nessuno è ancora arrivato da questo link.',
  'linkDetail.config.title': 'Configurazione',
  'linkDetail.config.edit': 'Modifica',
  'linkDetail.config.rights': 'Permessi degli ospiti senza account',
  'linkDetail.config.entry': 'Condizioni di ingresso',
  'linkDetail.config.account': 'Account Meeshy',
  'linkDetail.config.account.required': 'Obbligatorio',
  'linkDetail.config.account.optional': 'Facoltativo',
  'linkDetail.config.asked': 'Richiesto all’arrivo',
  'linkDetail.config.asked.nickname': 'Nome',
  'linkDetail.config.asked.email': 'E-mail',
  'linkDetail.config.asked.birthday': 'Data di nascita',
  'linkDetail.config.asked.none': 'Niente',
  'linkDetail.config.limits': 'Limiti',
  'linkDetail.config.uses': 'Utilizzi',
  'linkDetail.config.uses.value': '{count} / {max}',
  'linkDetail.config.unlimited': 'illimitato',
  'linkDetail.config.concurrent': 'Contemporaneamente',
  'linkDetail.config.concurrent.value': '{count} max',
  'linkDetail.config.expires': 'Scade',
  'linkDetail.config.expires.value': 'il {date}',
  'linkDetail.config.expires.never': 'Mai',
  'linkDetail.config.languages': 'Lingue consentite',
  'linkDetail.config.languages.all': 'Tutte le lingue',
  'linkDetail.config.pending': 'Caricamento della configurazione di questo link…',
  'linkDetail.rights.messages': 'Scrivere messaggi',
  'linkDetail.rights.images': 'Inviare immagini',
  'linkDetail.rights.files': 'Inviare file',
  'linkDetail.rights.history': 'Vedere la cronologia',
  'linkDetail.edit.title': 'Modifica il link',
  'linkDetail.edit.name': 'Nome del link (visibile solo a te)',
  'linkDetail.edit.name.placeholder': 'Es. Invito del team',
  'linkDetail.edit.message': 'Messaggio di invito (mostrato agli ospiti)',
  'linkDetail.edit.message.placeholder': 'Di’ in una frase perché unirsi',
  'linkDetail.edit.limits': 'Limiti',
  'linkDetail.edit.expiration': 'Scadenza',
  'linkDetail.edit.expiration.keep': 'Invariata — {date}',
  'linkDetail.edit.maxUses': 'Limita gli utilizzi',
  'linkDetail.edit.maxUses.count': 'Utilizzi max',
  'linkDetail.edit.maxConcurrent': 'Limita le persone contemporanee',
  'linkDetail.edit.maxConcurrent.count': 'Persone contemporanee',
  'linkDetail.edit.number.invalid': 'Inserisci un numero intero tra 1 e {max}.',
  'linkDetail.edit.entry': 'Condizioni di ingresso',
  'linkDetail.edit.rights': 'Permessi degli ospiti senza account',
  'linkDetail.edit.languages': 'Lingue consentite',
  'linkDetail.edit.languages.all': 'Tutte le lingue',
  'linkDetail.edit.languages.hint': 'Disattiva «Tutte le lingue» per scegliere.',
  'linkDetail.edit.languages.invalid': 'Scegli almeno una lingua.',
  'linkDetail.edit.save': 'Salva',
  'linkDetail.edit.saving': 'Salvataggio…',
  'linkDetail.edit.unchanged': 'Nessuna modifica da salvare.',
  'linkDetail.edit.delete': 'Elimina',
  'linkDetail.delete.title': 'Eliminare questo link?',
  'linkDetail.delete.body': 'Il link smetterà di funzionare e gli ospiti senza account entrati tramite esso perderanno l’accesso.',
  'linkDetail.delete.confirm': 'Elimina il link',
  'linkDetail.delete.cancel': 'Annulla',
  'linkDetail.announce.saved': 'Modifiche salvate.',
  'linkDetail.announce.saveFailed': 'Le modifiche non sono state salvate.',
  'linkDetail.announce.deleted': 'Link eliminato.',
  'linkDetail.announce.deleteFailed': 'Il link non è stato eliminato.',
  'linkDetail.announce.offline': 'Offline: non è stato inviato nulla.',
} satisfies InviteCatalog;

export default it;
