import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page et les fiches (`game.concept.*`, `game.fiche.*`, `game.fact.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const en = {
  'game.progression.title': 'Progress',
  'game.concept.why_label': 'What it’s for',
  'game.concept.how_label': 'How it works',
  'game.fiche.what': 'What is it?',
  'game.fiche.where': 'Where I am',
  'game.fiche.earn': 'How to earn more',
  'game.fiche.more': 'Go further',
  'game.fiche.unknown': 'This page doesn’t exist, or your server doesn’t serve it yet.',
  'game.concept.level.name': 'Level',
  'game.concept.level.why': 'Your level shows how far you’ve come on Meeshy.',
  'game.concept.level.how': 'Your points fill the ring: when it’s full, you go up a level.',
  'game.concept.level.tip.1': 'Do the daily missions: they bring lots of points.',
  'game.concept.level.tip.2': 'Keep your Flame lit: it boosts your rewards.',
  'game.concept.points.name': 'Points',
  'game.concept.points.why': 'Points raise your level and let you mint Meeshes.',
  'game.concept.points.how': 'Every useful action earns some: writing, talking, posting, reacting.',
  'game.concept.points.tip.1': 'Post, comment, react: each family of actions has its own rate.',
  'game.concept.points.tip.2': 'Trigger a boost to multiply your points.',
  'game.concept.meesh.name': 'Meeshes',
  'game.concept.meesh.why': 'The Meesh is Meeshy’s rare coin: you keep it or you spend it.',
  'game.concept.meesh.how': 'You mint it with your points. Each mint makes the next one cost more.',
  'game.concept.meesh.tip.1': 'Keep your Meeshes to grow your treasury.',
  'game.concept.meesh.tip.2': 'Spend them to protect your Flame or swap a mission.',
  'game.concept.glory.name': 'Glory',
  'game.concept.glory.why': 'Glory gives you your rank, and your rank never goes down.',
  'game.concept.glory.how': 'Every mint, every record and every achievement adds some.',
  'game.concept.glory.tip.1': 'Mint a Meesh: each mint adds Glory.',
  'game.concept.glory.tip.2': 'Beat your records and unlock achievements.',
  'game.concept.flame.name': 'Flame',
  'game.concept.flame.why': 'Your Flame counts your days in a row and boosts your mission rewards.',
  'game.concept.flame.how': 'One action a day makes it grow. A freeze covers a missed day.',
  'game.concept.flame.tip.1': 'Do at least one action every day.',
  'game.concept.flame.tip.2': 'Keep a freeze in reserve for the days off.',
  'game.concept.missions.name': 'Daily missions',
  'game.concept.missions.why': 'Missions give you a goal every day, and extra points.',
  'game.concept.missions.how': 'Three missions a day. When they’re done, you open the chest.',
  'game.concept.missions.tip.1': 'Start with the easiest mission.',
  'game.concept.missions.tip.2': 'Don’t like a mission? Swap it, once a day.',
  'game.concept.league.name': 'League',
  'game.concept.league.why': 'The league pits you against 29 other players every week.',
  'game.concept.league.how': 'Your points this week set your rank. The top players move up a league.',
  'game.concept.league.tip.1': 'Play a little every day: the week’s points add up.',
  'game.concept.league.tip.2': 'Aim for the top spots before Sunday evening.',
  'game.concept.league.more': 'See the ranking',
  'game.concept.league.unplaced': 'Not placed yet',
  'game.concept.season.name': 'Season',
  'game.concept.season.why': 'A season is an eight-week path, with a cup at the end.',
  'game.concept.season.how': 'Missions and the duo give stars. Stars open the steps.',
  'game.concept.season.tip.1': 'Finish your daily missions to earn stars.',
  'game.concept.season.tip.2': 'Play as a duo with a friend: the reward is doubled.',
  'game.concept.season.more': 'See the path',
  'game.concept.season.none': 'None right now',
  'game.concept.prestige.name': 'Prestige',
  'game.concept.prestige.why': 'Prestige rewards those who reach level 100.',
  'game.concept.prestige.how': 'Your level goes back to 1. You earn a star, a trophy and Glory.',
  'game.concept.prestige.tip.1': 'Climb all the way to level 100.',
  'game.concept.prestige.tip.2': 'Go Prestige whenever you like: nothing forces you to.',
  'game.concept.prestige.more': 'Open Prestige',
  'game.concept.elans.name': 'Boosts',
  'game.concept.elans.why': 'A boost multiplies the points of your next actions.',
  'game.concept.elans.how': 'Do actions from several families these days to trigger it.',
  'game.concept.elans.tip.1': 'Mix it up: write, post, comment, react.',
  'game.concept.elans.tip.2': 'Come back several days in a row to keep it.',
  'game.concept.elans.families.one': '{count} active family',
  'game.concept.elans.families.other': '{count} active families',
  'game.concept.badges.name': 'Badges',
  'game.concept.badges.why': 'A badge shows what you do most on Meeshy.',
  'game.concept.badges.how': 'Repeat an action: its badge changes material, from copper to prism.',
  'game.concept.badges.tip.1': 'Pick an action you like and do it often.',
  'game.concept.badges.tip.2': 'A badge that went out can be relit: nothing is lost.',
  'game.concept.badges.more': 'See all my badges',
  'game.concept.defis.name': 'Challenges',
  'game.concept.defis.why': 'Challenges are tiers to clear, one after another.',
  'game.concept.defis.how': 'Each tier you reach opens the next one, a little higher.',
  'game.concept.defis.tip.1': 'Look at the next tier and work towards it.',
  'game.concept.defis.tip.2': 'Try new actions: each one has its challenges.',
  'game.concept.defis.more': 'See all my challenges',
  'game.concept.succes.name': 'Achievements',
  'game.concept.succes.why': 'An achievement marks a rare moment in your Meeshy story.',
  'game.concept.succes.how': 'You unlock it in one go, when you meet what it asks for.',
  'game.concept.succes.tip.1': 'Explore the app: some achievements are hidden.',
  'game.concept.succes.tip.2': 'The rarest ones add the most Glory.',
  'game.concept.succes.more': 'See all my achievements',
  'game.concept.showcase.name': 'Showcase',
  'game.concept.showcase.why': 'Your showcase displays the trophies you’ve won.',
  'game.concept.showcase.how': 'Each cup lands there by itself. You choose the order and who sees it.',
  'game.concept.showcase.tip.1': 'Finish at the top of your league to win a cup.',
  'game.concept.showcase.tip.2': 'Complete a season or go Prestige.',
  'game.concept.showcase.more': 'Open my showcase',
  'game.concept.atlas.name': 'Atlas',
  'game.concept.atlas.why': 'The Atlas keeps a stamp for every language you’ve chatted in.',
  'game.concept.atlas.how': 'Send a message and get one back in a language: the stamp lands.',
  'game.concept.atlas.tip.1': 'Write to someone in a language other than yours.',
  'game.concept.atlas.tip.2': 'Wait for the reply: it takes a message each way.',
  'game.concept.atlas.more': 'Open my Atlas',
  'game.concept.chip.next_price': 'Next: {price}',
  'game.concept.chip.next': 'Next: {name}',
  'game.concept.chip.record': 'Record: {value}',
  'game.concept.chip.freezes': 'Freezes: {count}',
  'game.concept.chip.chest.locked': 'Chest locked',
  'game.concept.chip.chest.ready': 'Chest ready',
  'game.concept.chip.chest.claimed': 'Chest opened',
  'game.concept.chip.can_mint': 'Ready to mint',
  'game.concept.chip.mint_covered': 'Enough for a Meesh',
  'game.concept.chip.left': 'Left: {count}',
  'game.concept.chip.week': 'Week {week}',
  'game.concept.chip.no_elan': 'No boost running',
  'game.concept.chip.factor': 'Points ×{factor}',
  'game.concept.chip.seen_by': 'Seen by: {who}',
  'game.fact.tier': 'Tier',
  'game.fact.to_next': 'Next level',
  'game.fact.record': 'Record',
  'game.fact.next_meesh': 'Next Meesh',
  'game.fact.missing': 'Missing',
  'game.fact.balance': 'In hand',
  'game.fact.next_tier': 'Next tier',
  'game.fact.minted': 'Minted so far',
  'game.fact.next_rank': 'Next rank',
  'game.fact.streak': 'Streak',
  'game.fact.form': 'Form',
  'game.fact.freezes': 'Freezes in reserve',
  'game.fact.state': 'Status',
  'game.fact.lit': 'Lit',
  'game.fact.done': 'Done',
  'game.fact.week_points': 'Points this week',
  'game.fact.closes': 'Closes',
  'game.fact.steps': 'Steps',
  'game.fact.stars': 'Stars',
  'game.fact.week': 'Week',
  'game.fact.factor': 'Multiplier',
  'game.fact.families': 'Active families',
  'game.fact.earned': 'Earned',
  'game.fact.trophies': 'Trophies',
  'game.fact.visibility': 'Visible to',
  'game.fact.stamps': 'Stamps',
  'game.fact.pending': 'In progress',
  'game.fact.group': 'Group',
  'game.fact.material': 'Material',
  'game.detail.obtain_label': 'How to get it',
  'game.detail.gives_label': 'What it gives',
  'game.detail.earned': 'Earned',
  'game.detail.earned_on': 'Earned on {date}',
  'game.detail.locked': 'Not earned yet',
  'game.detail.missing': 'Missing: {missing}',
  'game.detail.see_fiche': 'See the page',
  'game.detail.open': '{name}: see details',
  'game.detail.rarity': 'Rarity',
  'game.detail.header_group': 'My rank and my Meeshes',
  'game.detail.badge.what': 'A badge shows how many times you’ve done an action.',
  'game.detail.badge.how': 'Do it again: at each tier, the badge changes material.',
  'game.detail.succes.what': 'An achievement marks a rare moment in your Meeshy story.',
  'game.detail.succes.how': 'Meet what it asks for: it unlocks in one go.',
  'game.detail.defi.what': 'A challenge is a tier to clear in a family of actions.',
  'game.detail.defi.how': 'Reach the number it asks for: the next tier opens.',
  'game.detail.trophy.what': 'A trophy keeps the memory of a win. It earns nothing: it’s for show.',
  'game.detail.trophy.how': 'Finish at the top of your league, complete a season, go Prestige or keep your Flame.',
  'game.detail.stamp.what': 'A stamp proves you really chatted in this language.',
  'game.detail.stamp.how': 'Send a message in this language, and get one back.',
  'game.detail.step.what': 'A season step is a free reward along the path.',
  'game.detail.step.how': 'Earn stars with missions and the duo, then claim the step.',
  'game.detail.seal.what': 'The Seal is a collectible. It changes nothing in the game.',
  'game.detail.seal.how': 'Take it with your Meeshes during the season.',
  'game.detail.gem.what': 'The gem tells which league you’re playing in this week.',
  'game.detail.gem.how': 'Finish among the top players of your group to move up a league.',
  'game.detail.star.what': 'A Prestige star lands on your level ring, forever.',
  'game.detail.star.how': 'Reach level 100, then go Prestige.',
  'game.detail.rank.what': 'Your crest shows your rank. A rank never goes down.',
  'game.detail.rank.how': 'Earn Glory: mint Meeshes, beat your records, unlock achievements.',
  'game.detail.flame.what': 'The form of your Flame grows with your streak of days.',
  'game.detail.flame.how': 'The bigger it is, the more your mission rewards grow.',
  'game.detail.freeze.what': 'A freeze protects your Flame: it covers a day when you did nothing.',
  'game.detail.freeze.how': 'Buy it with your Meeshes, or find it in the daily chest.',
  'game.detail.mission.what': 'A mission is a small goal to reach today.',
  'game.detail.mission.how': 'It earns points and brings you closer to the daily chest.',
  'game.detail.chest.what': 'The daily chest opens when your missions are done.',
  'game.detail.chest.how': 'Points, and sometimes a Meesh fragment or a freeze.',
  'game.detail.coin.what': 'The Meesh is Meeshy’s rare coin. Each coin carries its number.',
  'game.detail.coin.how': 'Mint it with your points as soon as you have enough.',
  'game.detail.ring.what': 'The ring shows your level: it fills up with your points.',
  'game.detail.ring.how': 'Earn points: when the ring is full, you go up a level.',
  'game.detail.treasury.what': 'Your treasury grows with the Meeshes you keep.',
  'game.detail.treasury.how': 'Keep your Meeshes instead of spending them to reach the next tier.',
  'game.detail.elan.what': 'A family groups actions that are alike.',
  'game.detail.elan.how': 'Each action earns points. Several active families trigger a boost.',
  'game.detail.elan.active': 'Active these days',
  'game.detail.elan.idle': 'Not active these days',
  'game.detail.elan.points': '{points} per action',
  'game.detail.player.what': 'A player in your group. You only see their nickname and their points this week.',
  'game.detail.fact.tier': 'Ten levels make a tier. Each tier has its name and its colour.',
  'game.detail.fact.score': 'These are the points you hold. They make your level.',
  'game.detail.fact.level_next': 'These are the points you still need to go up a level.',
  'game.detail.fact.level_record': 'This is the highest level you’ve reached.',
  'game.detail.fact.tailwind': 'After a mint, your points count for more until your record level.',
  'game.detail.fact.mint_price': 'This is the price of your next Meesh. It rises with each mint.',
  'game.detail.fact.mint_missing': 'These are the points you still need to mint your next Meesh.',
  'game.detail.fact.can_mint': 'You have enough points: you can mint a Meesh on its page.',
  'game.detail.fact.factor': 'Your next actions earn this many times more points.',
  'game.detail.fact.mint_next': 'Each Meesh carries its number. One in a hundred is gold, one in a thousand prism.',
  'game.detail.fact.mint_glory': 'Each mint adds this Glory to your rank.',
  'game.detail.fact.minted': 'This is how many Meeshes you’ve minted since the start.',
  'game.detail.fact.glory': 'Glory adds up and never goes down. It gives you your rank.',
  'game.detail.fact.glory_missing': 'This is the Glory you still need for the next rank.',
  'game.detail.fact.streak': 'This is how many days in a row you’ve done at least one action.',
  'game.detail.fact.streak_record': 'This is your longest streak of days.',
  'game.detail.fact.flame_state': 'It tells whether your Flame is lit, at risk, protected or out.',
  'game.detail.fact.missions_done': 'Three missions a day. Once done, they open the chest.',
  'game.detail.fact.league_place': 'This is your place among the players of your group this week.',
  'game.detail.fact.week_points': 'These are the points earned since Monday. They start again from zero every week.',
  'game.detail.fact.league_zone': 'The top players move up, the bottom ones move down, the rest stay.',
  'game.detail.fact.league_missing': 'These are the points you still need to enter the promotion zone.',
  'game.detail.fact.league_closes': 'The league week closes on Sunday evening. The ranking is then frozen.',
  'game.detail.fact.league_friends': 'This is your place among your accepted friends this week.',
  'game.detail.fact.season': 'A season lasts eight weeks and has a number.',
  'game.detail.fact.season_week': 'This is the current week, out of the season’s eight.',
  'game.detail.fact.season_steps': 'These are the steps you’ve opened along the season path.',
  'game.detail.fact.season_stars': 'Stars are earned with missions and the duo. They open the steps.',
  'game.detail.fact.prestige_glory': 'This is the Glory you earn by going Prestige.',
  'game.detail.fact.elan_families': 'These are the families of actions you’ve been active in lately.',
  'game.detail.fact.badges_earned': 'This is how many badges you’ve earned, out of all that exist.',
  'game.detail.fact.defis_earned': 'These are the tiers you’ve cleared, out of those you can reach.',
  'game.detail.fact.succes_earned': 'These are the achievements you’ve unlocked, out of all that exist.',
  'game.detail.fact.trophies': 'This is how many trophies sit in your showcase.',
  'game.detail.fact.showcase_visibility': 'You choose who sees your showcase: everyone, your friends, or only you.',
  'game.detail.fact.atlas_stamps': 'These are the languages where you have a stamp, out of all in the Atlas.',
  'game.detail.fact.atlas_pending': 'These are the languages still missing a message, sent or received.',
} as const satisfies GameConceptCatalog;

export default en;
