/**
 * LA QUALITÉ D'UN APPEL (#8047) — tranche du catalogue, RÉPANDUE par
 * `catalog-ar.ts` comme `catalog-ar-call-screen.ts` : l'indicateur et le
 * détail de qualité, les pastilles de survie de la vidéo et les alertes d'un
 * pair (`call-quality-indicator.tsx`, `call-screen.tsx`).
 */
const arCallQuality = {
  'call.quality.indicator': 'جودة المكالمة: {level}',
  'call.quality.level.excellent': 'ممتازة',
  'call.quality.level.good': 'جيدة',
  'call.quality.level.fair': 'متوسطة',
  'call.quality.level.poor': 'ضعيفة',
  'call.quality.detail': 'جودة المكالمة',
  'call.quality.loss': 'فقدان الحزم',
  'call.quality.latency': 'زمن الاستجابة',
  'call.quality.jitter': 'التذبذب',
  'call.quality.audioRate': 'معدل الصوت',
  'call.quality.videoRate': 'معدل الفيديو',
  'call.quality.close': 'إغلاق تفاصيل الجودة',
  'call.quality.profile': 'الشبكة',
  'call.quality.profile.wifi': 'Wi-Fi',
  'call.quality.profile.cellular': 'بيانات الجوال',
  'call.quality.profile.economy': 'توفير البيانات',
  'call.quality.audioCap': 'حد الصوت',
  'call.quality.videoCap': 'حد الفيديو',
  'callJournal.title': 'الجودة والشبكة',
  'callJournal.chronology': 'التسلسل الزمني',
  'callJournal.summary.worstLevel': 'أدنى جودة',
  'callJournal.summary.maxLoss': 'أقصى فقدان للحزم',
  'callJournal.summary.maxRtt': 'أقصى تأخير',
  'callJournal.summary.reconnections': 'إعادات الاتصال',
  'callJournal.summary.path': 'مسار الوسائط',
  'callJournal.path.direct': 'مباشر',
  'callJournal.path.relay': 'عبر مُرحِّل',
  'callJournal.summary.end': 'النهاية',
  'callJournal.end.local': 'أُنهيت',
  'callJournal.end.remote': 'أنهاها الطرف الآخر',
  'callJournal.end.rejected': 'مرفوضة',
  'callJournal.end.missed': 'بلا رد',
  'callJournal.end.connectionLost': 'انقطع الاتصال',
  'callJournal.end.failed': 'فشل الاتصال',
  'callJournal.end.busy': 'مشغول',
  'callJournal.end.permission': 'رُفض الميكروفون أو الكاميرا',
  'callJournal.end.removed': 'أُزيل من المكالمة',
  'callJournal.event.connecting': 'جارٍ الاتصال',
  'callJournal.event.connected': 'متصل',
  'callJournal.event.reconnecting': 'إعادة الاتصال',
  'callJournal.event.ended': 'انتهت: {reason}',
  'callJournal.event.link': '{name}: {state}',
  'callJournal.link.connecting': 'يتصل',
  'callJournal.link.connected': 'متصل',
  'callJournal.link.reconnecting': 'يعيد الاتصال',
  'callJournal.event.quality': 'الجودة {level}',
  'callJournal.event.frozen': 'تباطأ الفيديو (شبكة ضعيفة)',
  'callJournal.event.suspended': 'الفيديو متوقف، الصوت مستمر',
  'callJournal.event.resumed': 'عاد الفيديو',
  'callJournal.event.profile': 'الشبكة: {profile} · الصوت {bitrate}',
  'callJournal.event.relay': 'مُرحَّل عبر الخادم',
  'callJournal.event.direct': 'اتصال مباشر',
  'call.video.frozen': 'شبكة ضعيفة: الفيديو الخاص بك أبطأ',
  'call.video.suspended': 'شبكة ضعيفة: الفيديو الخاص بك متوقف مؤقتًا، والصوت مستمر',
  'call.alert.weakNetwork': 'اتصال {name} غير مستقر',
  'call.alert.capturing': '{name} يلتقط شاشة المكالمة',
} as const;

export default arCallQuality;
