import type { InterfaceCatalog } from '@/lib/i18n-catalog';
import arIdentity from './catalog-ar-identity';

import arMentions from './catalog-ar-mentions';
import arStoriesMine from './catalog-ar-stories-mine';

const ar = {
  'announce.messageSent': 'تم إرسال الرسالة',
  'announce.messageCopied': 'تم نسخ الرسالة',
  'announce.messagesCopied': 'تم نسخ الرسائل',
  'announce.messageProtected': 'رسالة محمية',
  'announce.selectionCap': '{count} رسالة كحد أقصى',
  'announce.nothingToCopy': 'لا شيء للنسخ',

  'message.author.self': 'أنت',
  'message.excerpt.protected': 'محتوى محمي',
  'a11y.message.menu.subject': 'إجراءات رسالة {author}: {excerpt}',

  'selection.toolbar': 'تحديد الرسائل',
  'selection.cancel': 'إلغاء',
  'selection.count': 'تم تحديد {count}',
  'forward.title': 'إعادة التوجيه إلى…',
  'forward.empty': 'لا توجد محادثة',
  'forward.search.label': 'البحث عن محادثة',
  'forward.search.placeholder': 'بحث',
  'forward.announce.sent': 'تمت إعادة توجيه الرسالة',
  'forward.announce.sentMany': 'تمت إعادة توجيه {count} رسائل',
  'forward.announce.failed': 'تعذّرت إعادة التوجيه',
  'forward.refusal.viewOnce': 'لا يمكن إعادة توجيه رسالة تُعرض مرة واحدة',
  'forward.refusal.unavailable': 'الرسالة الأصلية لم تعد متاحة: لا شيء لإعادة توجيهه',

  'typing.named': '{name} يكتب',
  'typing.double': '{first} و{second} يكتبان',
  'typing.several': 'عدة أشخاص يكتبون',

  'feed.header.reels': 'تشغيل الريلز',
  'reels.title': 'الريلز',
  'reels.back': 'رجوع',
  'reels.open': 'مشاهدة ريل {author}',
  'reels.item': 'ريل {author}، {index} من {count}',
  'reels.loading': 'جارٍ تحميل الريلز',
  'reels.empty': 'لا توجد ريلز حاليًا',
  'reels.empty.hint': 'ستظهر هنا ريلز جهات اتصالك.',
  'reels.error': 'تعذّر تحميل الريلز',
  'reels.error.hint': 'أعد المحاولة بعد لحظات.',
  'reels.retry': 'إعادة المحاولة',
  'reels.offline': 'غير متصل',
  'reels.offline.cold': 'سيتم تحميل الريلز عند عودة الاتصال.',
  'reels.action.like': 'إعجاب',
  'reels.action.bookmark': 'حفظ',
  'reels.action.share': 'مشاركة',
  'reels.sound.on': 'تشغيل الصوت',
  'reels.sound.off': 'كتم الصوت',
  'reels.play': 'تشغيل الريل',
  'reels.pause': 'إيقاف الريل مؤقتًا',
  'reels.media.error': 'تعذّر التشغيل — إعادة المحاولة',
  'reels.image': 'صورة {index} من {count}',

  'stories.title': 'القصص',
  'stories.loading': 'جاري تحميل القصص…',
  'stories.error': 'تعذّر تحميل القصص.',
  'stories.empty.title': 'لا توجد قصص حتى الآن',
  'stories.empty.subtitle': 'ستظهر هنا قصص جهات اتصالك لمدة عشرين ساعة.',
  'stories.create': 'إنشاء قصة',
  'stories.count.one': '{count} قصة',
  'stories.count.other': '{count} قصص',
  'stories.mine': 'قصتك',

  /* #6150 — بابا خليتي في الشريط. */
  'stories.self.addStory': 'إضافة قصة',
  'stories.self.mood.add': 'تعيين مزاج',
  'stories.self.mood.change': 'تغيير مزاجي، {emoji}',

  'status.compose.title': 'مزاجي',
  'status.compose.pick': 'اختر مزاجًا',
  'status.compose.note': 'كلمة، إن أردت',
  'status.compose.publish': 'نشر',
  'status.compose.publishing': 'جارٍ النشر…',
  'status.compose.error': 'تعذّر نشر مزاجك.',
  'status.compose.offline': 'غير متصل — سيُنشر مزاجك عند عودة الشبكة.',

  'feed.header.create': 'إنشاء منشور أو ريل',
  'feed.create.post': 'منشور',
  'feed.create.reel': 'ريل',

  'feed.post.action.like': 'إعجاب',
  'feed.post.action.comment': 'تعليق',
  'feed.post.action.repost': 'إعادة النشر',
  'feed.post.action.bookmark': 'حفظ',
  'feed.post.action.share': 'مشاركة',
  'feed.post.media.video': 'فيديو',
  'feed.post.media.audio': 'صوت',
  'feed.post.media.previous': 'الوسائط السابقة',
  'feed.post.media.next': 'الوسائط التالية',
  'feed.post.media.mosaic': 'فسيفساء من {count} وسائط',
  'media.unavailable': 'الوسائط غير متوفرة',
  'feed.post.see_more': 'عرض المزيد',
  'feed.post.see_less': 'عرض أقل',
  'feed.post.more_options': 'خيارات إضافية',
  'feed.post.menu.open': 'فتح',
  'feed.post.menu.copy_text': 'نسخ النص',
  'feed.post.menu.unsave': 'إزالة من المحفوظات',
  'feed.post.menu.pin': 'تثبيت',
  'feed.post.menu.delete': 'حذف',
  'feed.post.edit': 'تعديل',
  'feed.post.edit.title': 'تعديل المنشور',
  'feed.post.edit.body.a11y': 'محتوى المنشور',
  'feed.post.edit.remaining.a11y': '{count} حرف متبقٍّ',
  'feed.post.edit.publish': 'نشر',
  'report.post.title': 'الإبلاغ عن هذا المنشور',
  'feed.post.copied': 'تم نسخ النص',
  'feed.post.copy_failed': 'تعذّر نسخ النص',
  'feed.post.pinned': 'تم تثبيت المنشور',
  'feed.post.pin_failed': 'تعذّر تثبيت المنشور',
  'feed.post.edited': 'تم تحديث المنشور',
  'feed.post.edit_failed': 'تعذّر تحديث المنشور',
  'feed.post.edit_busy': 'يوجد تعديل قيد التنفيذ بالفعل',
  'feed.post.deleted': 'تم حذف المنشور',
  'feed.post.delete_failed': 'حدث خطأ أثناء الحذف',
  'feed.post.repost.success': 'تمت إعادة النشر',
  'feed.post.repost.error': 'تعذّرت إعادة النشر',
  'feed.post.repost.already': 'أُعيد نشره بالفعل',
  'feed.post.repost.offline': 'غير متصل — تعذّر إرسال إعادة النشر.',
  'feed.post.repost.unconfirmed': 'لم تُؤكَّد إعادة النشر — أعد المحاولة',
  'feed.post.repost.audience': 'سيؤدي هذا الجمهور إلى توسيع نطاق المنشور الأصلي',
  'feed.post.reel.chip': 'ريل',
  'feed.post.reel.of': 'ريل {author}',
  'feed.post.open': 'فتح منشور {author}',
  /* LES PUBLICATIONS ENREGISTRÉES (#7286) — l'écran `/me/bookmarks` et sa rangée de Réglages › Outils. */
  'bookmarks.title': 'المنشورات المحفوظة',
  'bookmarks.back': 'العودة إلى الإعدادات',
  'bookmarks.loading': 'جارٍ تحميل منشوراتك المحفوظة',
  'bookmarks.empty.title': 'لا توجد منشورات محفوظة بعد',
  'bookmarks.empty.subtitle': 'انقر على أيقونة الحفظ أسفل أي منشور للاحتفاظ به هنا وقراءته متى شئت.',
  'bookmarks.empty.cta': 'فتح الموجز',
  'bookmarks.error.title': 'تعذّر تحميل منشوراتك المحفوظة',
  'bookmarks.error.body': 'حاول مرة أخرى بعد لحظات.',
  'bookmarks.offline.body': 'ستظهر منشوراتك المحفوظة عند عودة الاتصال.',
  'bookmarks.allLoaded': 'تم تحميل جميع منشوراتك المحفوظة',
  'bookmarks.filter.all': 'الكل',
  'bookmarks.filter.posts': 'المنشورات',
  'bookmarks.filter.reels': 'الريلز',
  'bookmarks.filter.a11y': 'تصفية المنشورات المحفوظة',
  'settings.tools.bookmarks': 'المنشورات المحفوظة',
  'action.star': 'إضافة إلى المفضلة',
  'action.unstar': 'إزالة من المفضلة',
  'announce.messageStarred': 'تمت الإضافة إلى المفضلة',
  'announce.messageUnstarred': 'تمت الإزالة من المفضلة',
  'starred.messages.pending': 'لم يتم تأكيد المفضلة — غير متصل',
  'starred.messages.error': 'تعذّر تعديل المفضلة',
  'starred.messages.notStarrable': 'لا يمكن إضافة هذه الرسالة إلى المفضلة',
  'settings.tools.starred': 'الرسائل المفضّلة',
  'starred.messages.title': 'الرسائل المفضلة',
  'starred.messages.back': 'العودة إلى الإعدادات',
  'starred.messages.loading': 'جارٍ تحميل رسائلك المفضلة',
  'starred.messages.empty.title': 'لا توجد رسائل مفضّلة',
  'starred.messages.empty.subtitle': 'اضغط مطوّلًا على رسالة واختر «إضافة إلى المفضّلة» لتجدها هنا.',
  'starred.messages.empty.cta': 'فتح المحادثات',
  'starred.messages.error.title': 'تعذّر تحميل رسائلك المفضلة',
  'starred.messages.error.body': 'حاول مرة أخرى بعد لحظات.',
  'starred.messages.offline.body': 'ستظهر رسائلك المفضلة عند عودة الاتصال.',
  'starred.messages.allLoaded': 'تم تحميل جميع رسائلك المفضلة',
  'starred.messages.row.hint': 'يفتح المحادثة',
  'starred.messages.remove.a11y': 'إزالة رسالة {author} من المفضلة',
  'starred.messages.protected': 'رسالة محمية',
  'starred.messages.noText': 'رسالة بلا نص',
  'starred.messages.media.image': 'صورة',
  'starred.messages.media.video': 'الفيديو',
  'starred.messages.media.audio': 'صوت',
  'starred.messages.media.file': 'ملف',
  'common.unknown_user': 'المستخدم',
  'feed.error.title': 'تعذّر تحميل التدفق',
  'feed.error.body': 'أعد المحاولة بعد لحظة.',
  'feed.offline.title': 'غير متصل',
  'feed.offline.body': 'سيظهر التدفق عند عودة الاتصال.',
  'feed.retry': 'إعادة المحاولة',
  'feed.empty.title': 'لا توجد منشورات بعد',
  'feed.empty.subtitle': 'ستظهر هنا منشورات جهات اتصالك.',
  'feed.loading': 'جارٍ تحميل التدفق',
  'feed.allLoaded': 'تم تحميل جميع المنشورات',
  'feed.newPosts.one': 'منشور جديد {count}',
  'feed.newPosts.other': 'منشورات جديدة {count}',
  ...arIdentity,
  'userProfile.self.edit': 'تعديل ملفي الشخصي',
  'report.title': 'الإبلاغ عن هذا الحساب',
  'report.body': 'اختر سبب البلاغ. سيصل إلى فريق الإشراف لدينا.',
  'report.action': 'إبلاغ',
  'report.done': 'تم إرسال البلاغ',
  'report.throttled': 'بلاغات كثيرة — أعد المحاولة بعد قليل',
  'report.failed': 'تعذّر إرسال البلاغ',
  'report.reason.spam': 'رسائل مزعجة',
  'report.reason.inappropriate': 'محتوى غير لائق',
  'report.reason.harassment': 'تحرّش',
  'report.reason.violence': 'عنف',
  'report.reason.hate_speech': 'خطاب كراهية',
  'report.reason.fake_profile': 'حساب مزيّف',
  'report.reason.impersonation': 'انتحال هوية',
  'report.reason.other': 'أخرى',
  'feed.like.error': 'تعذّر الإعجاب بالمنشور',
  'post.bookmark.error': 'تعذّر الحفظ',
  'feed.gesture.pending': 'لم يتم تأكيد الإجراء — غير متصل',
  'feed.share.error': 'تعذّرت مشاركة المنشور',
  'feed.share.copied': 'تم نسخ الرابط — لم يتبقَّ سوى لصقه.',
  'feed.share.text': 'منشور على Meeshy',

  'root.menu.feed': 'التدفق',
  'root.menu.links': 'روابطي',
  'root.menu.notifications': 'الإشعارات',
  'root.menu.calls': 'المكالمات',
  'root.menu.discover': 'اكتشاف',
  'root.menu.communities': 'المجتمعات',
  'root.menu.settings': 'الإعدادات',
  'root.menu.profile': 'الملف الشخصي',
  'root.menu.conversations': 'المحادثات',
  'a11y.floating.feed.hint': 'اضغط مطولًا لتشغيل الريلز',
  'a11y.floating.menu': 'القائمة',
  'a11y.floating.menu.ladder': 'التنقل في Meeshy',
  'a11y.floating.menu.unread.one': 'القائمة، {count} إشعار غير مقروء',
  'a11y.floating.menu.unread.other': 'القائمة، {count} إشعارات غير مقروءة',
  'a11y.floating.rung.notifications.unread.one': 'الإشعارات، {count} غير مقروء',
  'a11y.floating.rung.notifications.unread.other': 'الإشعارات، {count} غير مقروءة',

  'notifications.category.all': 'الكل',
  'notifications.category.unread': 'غير المقروءة',
  'notifications.category.messages': 'الرسائل',
  'notifications.category.reactions': 'التفاعلات',
  'notifications.category.mentions': 'الإشارات',
  'notifications.category.social': 'اجتماعي',
  'notifications.category.contacts': 'جهات الاتصال',
  'notifications.category.groups': 'المجموعات',
  'notifications.category.calls': 'المكالمات',
  'notifications.category.translations': 'الترجمات',
  'notifications.category.system': 'النظام',
  'notifications.categories': 'فئات الإشعارات',
  'notifications.markAllRead': 'قراءة الكل',
  'notifications.unreadCount.one': '{count} غير مقروء',
  'notifications.unreadCount.other': '{count} غير مقروءة',
  'notifications.unread': 'غير مقروء',
  'notifications.empty.all': 'لا توجد إشعارات',
  'notifications.empty.unread': 'لا توجد إشعارات غير مقروءة',
  'notifications.empty.category': 'لا توجد إشعارات في «{category}»',
  'notifications.empty.subtitle': 'ستظهر إشعاراتك هنا',
  'notifications.loading': 'جارٍ تحميل الإشعارات',
  'notifications.error.title': 'تعذّر تحميل الإشعارات',
  'notifications.error.body': 'أعد المحاولة بعد لحظة.',
  'notifications.offline.title': 'غير متصل',
  'notifications.offline.body': 'ستظهر إشعاراتك عند عودة الاتصال.',
  'notifications.retry': 'إعادة المحاولة',
  'notifications.allLoaded': 'تم تحميل جميع الإشعارات',
  'notifications.actions': 'إجراءات الإشعار',
  'notifications.action.markRead': 'وضع علامة كمقروء',
  'notifications.action.delete': 'حذف',
  'notifications.failure': 'لم يكتمل الإجراء. أعد المحاولة.',

  'notFound.title': 'هذا العنوان غير موجود.',

  'pending.back': 'العودة إلى المحادثات',

  'linkPage.home': 'العودة إلى Meeshy',
  'linkPage.retry': 'إعادة المحاولة',
  'linkPage.settings': 'فتح الإعدادات',
  'linkPage.signIn': 'تسجيل الدخول',
  'linkPage.offline.title': 'غير متصل',
  'linkPage.offline.body': 'أعد الاتصال بالإنترنت، ثم حاول مرة أخرى.',
  'linkPage.unavailable.title': 'Meeshy لا يستجيب',
  'linkPage.unavailable.body': 'الخدمة غير متاحة مؤقتًا. حاول مرة أخرى بعد لحظات.',
  'linkPage.rateLimited': 'محاولات كثيرة جدًا. انتظر قليلًا قبل المحاولة مرة أخرى.',
  'linkPage.signedOut.title': 'سجّل الدخول للمتابعة',
  'linkPage.signedOut.body': 'يؤثر هذا الرابط في حسابك. سجّل الدخول، ثم افتحه مرة أخرى من البريد الإلكتروني.',
  'linkPage.expired': 'انتهت صلاحية هذا الرابط. أعد تقديم الطلب من الإعدادات.',
  'trackingLink.opening': 'جارٍ فتح الرابط…',
  'trackingLink.dead.title': 'هذا الرابط لم يعد متاحًا',
  'trackingLink.dead.body': 'انتهت صلاحيته أو تم تعطيله أو لم يكن موجودًا قط.',
  'accountDeletion.incomplete.title': 'رابط غير مكتمل',
  'accountDeletion.incomplete.body': 'لا يحمل هذا الرابط المعلومات اللازمة. سجّل الدخول لطلب حذف حسابك.',
  'accountDeletion.confirm.title': 'تأكيد حذف حسابك',
  'accountDeletion.confirm.body': 'سيتم تعطيل حسابك بعد انتهاء فترة سماح مدتها 30 يومًا. وحتى ذلك الحين، يتيح لك رابط «إلغاء» في البريد الإلكتروني التراجع.',
  'accountDeletion.confirm.action': 'تأكيد الحذف',
  'accountDeletion.cancel.title': 'إلغاء حذف حسابك',
  'accountDeletion.cancel.body': 'يبقى حسابك نشطًا ويُلغى طلب الحذف. لن تفقد شيئًا.',
  'accountDeletion.cancel.action': 'إلغاء الحذف',
  'accountDeletion.purge.title': 'حذف حسابك الآن',
  'accountDeletion.purge.body': 'سيتم تعطيل حسابك فورًا وإغلاق جميع جلساتك. لا يمكن التراجع عن هذا الإجراء.',
  'accountDeletion.purge.action': 'حذف الآن',
  'accountDeletion.dismiss': 'عدم فعل أي شيء',
  'accountDeletion.working': 'لحظة…',
  'accountDeletion.done.title': 'تم',
  'accountDeletion.done.confirmed': 'تم تأكيد طلبك: سيتم تعطيل حسابك في {date}. يمكنك الإلغاء حتى ذلك الحين.',
  'accountDeletion.done.cancelled': 'يبقى حسابك نشطًا: تم إلغاء طلب الحذف.',
  'accountDeletion.done.completed': 'تم تعطيل حسابك وإغلاق جميع جلساتك.',
  'accountDeletion.done.purged': 'تم مسح بياناتك.',
  'accountDeletion.closed.title': 'هذا الرابط لم يعد صالحًا',
  'accountDeletion.invalid': 'هذا الرابط غير صالح أو سبق استخدامه.',
  'accountDeletion.request.title': 'حذف حسابك',
  'accountDeletion.request.body':
    'ستُحذف محادثاتك ورسائلك ووسائطك وجهات اتصالك وتفضيلاتك. ستطلب منك رسالة بريد إلكتروني التأكيد، ثم تتيح لك فترة سماح مدتها 30 يومًا التراجع.',
  'accountDeletion.request.phrase': 'اكتب {phrase} للتأكيد',
  'accountDeletion.request.password': 'كلمة المرور الحالية',
  'accountDeletion.request.action': 'طلب الحذف',
  'accountDeletion.request.sent.title': 'أرسلنا إليك رسالة تأكيد بالبريد الإلكتروني',
  'accountDeletion.request.sent.body': 'افتحها لتأكيد حذف حسابك.',
  'accountDeletion.request.wrongPassword': 'كلمة المرور غير صحيحة.',
  'accountDeletion.request.alreadyPending': 'يوجد طلب قيد التنفيذ بالفعل. افتح رسالة البريد الإلكتروني التي تلقيتها لتأكيده أو إلغائه.',
  'accountDeletion.request.noEmail': 'أضف عنوان بريد إلكتروني وتحقّق منه قبل طلب الحذف.',
  'emailChange.verifying': 'جارٍ تأكيد عنوانك الجديد…',
  'emailChange.done.title': 'تم تغيير عنوان البريد الإلكتروني',
  'emailChange.done.body': 'أصبحت تسجّل الدخول الآن باستخدام {email}.',
  'emailChange.done.generic': 'تم تأكيد عنوان بريدك الإلكتروني الجديد.',
  'emailChange.failed.title': 'لم يتم تغيير العنوان',
  'emailChange.missing': 'لا يحمل هذا الرابط رمز تأكيد. افتح الرابط الموجود في أحدث رسالة بريد إلكتروني.',
  'emailChange.invalid': 'لا يطابق هذا الرابط أي تغيير معلّق في هذا الحساب، أو سبق استخدامه.',
  'emailChange.taken': 'هذا العنوان يستخدمه الآن حساب آخر.',
  'emailNotifications.title': 'رسائل Meeshy الإلكترونية',
  'emailNotifications.loading': 'جارٍ قراءة تفضيلك…',
  'emailNotifications.on': 'تتلقى إعلانات Meeshy وملخصاته وإشعاراته عبر البريد الإلكتروني.',
  'emailNotifications.off': 'لم تعد تتلقى إعلانات Meeshy أو ملخصاته أو إشعاراته عبر البريد الإلكتروني.',
  'emailNotifications.security': 'تستمر رسائل الأمان الخاصة بحسابك في الوصول.',
  'emailNotifications.unsubscribe': 'إيقاف تلقي هذه الرسائل',
  'emailNotifications.resubscribe': 'تلقي هذه الرسائل مجددًا',
  'emailNotifications.failed': 'لم يتم تطبيق التغيير. حاول مرة أخرى.',

  'dataExport.title': 'تصدير بياناتي',
  'dataExport.info.body': 'وفقًا للائحة العامة لحماية البيانات (RGPD)، احصل على ملف يضم ملفك الشخصي ورسائلك وجهات اتصالك ومنشوراتك.',
  'dataExport.action.start': 'تصدير بياناتي',
  'dataExport.action.exporting': 'التصدير قيد التنفيذ…',
  'dataExport.action.again': 'تصدير مرة أخرى',
  'dataExport.done.title': 'اكتمل التصدير',
  'dataExport.done.body': 'تم تنزيل الملف على هذا الجهاز.',
  'dataExport.ready.title': 'التصدير جاهز',
  'dataExport.ready.body': 'الملف جاهز. اضغط لحفظه على هذا الجهاز.',
  'dataExport.action.deliver': 'حفظ الملف',
  'dataExport.undelivered.body': 'تعذّر على هذا الجهاز استلام الملف.',

  'profile.title': 'الملف الشخصي',
  'profile.edit': 'تعديل',
  'profile.cancel': 'إلغاء',
  'profile.save': 'حفظ',
  'profile.saving': 'جارٍ الحفظ…',
  'profile.saved': 'تم حفظ الملف الشخصي',
  'profile.save.error': 'خطأ أثناء الحفظ',
  'profile.save.offline': 'غير متصل — لم يُرسَل التعديل.',
  'profile.save.invalid': 'تحقّق من الحقل «{field}».',
  'profile.loading': 'جارٍ تحميل الملف الشخصي',
  'profile.error.title': 'تعذّر تحميل ملفك الشخصي',
  'profile.error.body': 'أعد المحاولة بعد قليل.',
  'profile.retry': 'إعادة المحاولة',
  'profile.offline.title': 'غير متصل',
  'profile.offline.body': 'يبقى ملفك الشخصي مقروءًا، ويعود التعديل مع عودة الشبكة.',
  'profile.avatar.edit': 'تعديل صورة الملف الشخصي',
  'profile.avatar.updated': 'تم تحديث صورة الملف الشخصي',
  'profile.avatar.error': 'تعذّر تحديث صورة الملف الشخصي',
  'profile.banner.edit': 'تعديل صورة الغلاف',
  'profile.banner.updated': 'تم تحديث صورة الغلاف',
  'profile.banner.error': 'تعذّر تحديث صورة الغلاف',
  'profile.image.uploading': 'جارٍ الإرسال',
  'profile.image.cancel': 'إلغاء الإرسال',
  'profile.image.cancelled': 'أُلغي الإرسال',
  'profile.image.unreadable': 'تعذّرت قراءة هذه الصورة.',
  'profile.section.identity': 'الهوية',
  'profile.section.contact': 'الاتصال',
  'profile.section.languages': 'اللغات',
  'profile.section.stats': 'الإحصائيات',
  'profile.section.requests': 'الطلبات',
  'profile.section.member_since': 'عضو منذ',
  'profile.first_name': 'الاسم الأول',
  'profile.last_name': 'اسم العائلة',
  'profile.username': 'اسم المستخدم',
  'profile.display_name': 'الاسم المعروض',
  'profile.bio': 'نبذة',
  'profile.bio.placeholder': 'عرّفنا بنفسك...',
  'profile.email': 'البريد الإلكتروني',
  'profile.phone': 'الهاتف',
  'profile.verified': 'موثّق',
  'profile.not_verified': 'غير موثّق',
  'profile.language.primary': 'اللغة الأساسية',
  'profile.language.primary.subtitle': 'ستُترجَم المحتويات إلى هذه اللغة',
  'profile.language.regional': 'اللغة الإقليمية',
  'profile.language.custom': 'لغة مخصّصة',
  'profile.language.none': 'لا شيء',
  'profile.language.choose': 'اختيار',
  'profile.language.clear.regional': 'إزالة اللغة الإقليمية',
  'profile.language.clear.custom': 'إزالة اللغة المخصّصة',

  'languageSheet.title.read': 'لغة القراءة',
  'languageSheet.title.write': 'لغة الكتابة',
  'languageSheet.search': 'البحث عن لغة',
  'languageSheet.empty': 'لا توجد لغة تطابق «{search}».',

  'profile.stats.messages': 'الرسائل',
  'profile.stats.translations': 'الترجمات',
  'profile.stats.languages': 'اللغات',
  'profile.stats.days': 'الأيام',
  'profile.stats.loading': 'جارٍ تحميل الإحصائيات',
  'profile.progression.title': 'التقدّم',
  'profile.progression.subtitle': 'الشارات والمستوى والسلسلة',
  'profile.friend_requests': 'طلبات الصداقة',
  'profile.friend_requests.count.one': '{count} طلب معلّق',
  'profile.friend_requests.count.other': '{count} طلبات معلّقة',

  'settings.title': 'الإعدادات',
  'settings.my_profile': 'ملفي الشخصي',
  'settings.section.account': 'الحساب',
  'settings.security.title': 'الأمان',
  'settings.delete_account': 'حذف الحساب',
  'settings.privacy.title': 'الخصوصية',
  'settings.privacy.online_status': 'حالة الاتصال',
  'settings.privacy.online_status.info':
    'النقطة الخضراء على صورتك تعني أنك نشط. عند إيقافها لا يراها أحد، لكن الكتابة في محادثة تظل دليلاً على نشاطك.',
  'settings.privacy.last_seen': 'آخر تسجيل دخول',
  'settings.privacy.read_receipts': 'إيصالات القراءة',
  'settings.privacy.read_receipts.info': 'الأمر متبادل: إن لم تُرسل إشعارات القراءة، فلن ترى أيضًا ما إذا قُرئت رسائلك.',
  'settings.privacy.typing_indicator': 'مؤشر الكتابة',
  'settings.section.appearance': 'المظهر',
  'settings.theme': 'السمة',
  'settings.theme.auto': 'تلقائي',
  'settings.theme.light': 'فاتح',
  'settings.theme.dark': 'داكن',
  'settings.interface_language': 'لغة الواجهة',
  'settings.interface_language.automatic': 'تلقائي',
  'settings.content_languages': 'لغات الترجمة',
  'settings.section.notifications': 'الإشعارات',
  'settings.notifications.title': 'الإشعارات',
  'settings.notif.sounds': 'الأصوات',
  'settings.notif.more_options': 'المزيد من الخيارات',
  'settings.section.data': 'البيانات',
  'settings.media': 'الوسائط',
  'settings.messages': 'الرسائل',
  'settings.export_data': 'تصدير بياناتي',
  'settings.section.tools': 'الأدوات',
  'settings.tools.progression': 'التقدّم',
  'settings.section.about': 'حول',
  'settings.terms': 'شروط الاستخدام',
  'settings.privacy_policy': 'سياسة الخصوصية',
  'settings.version': 'الإصدار',
  'settings.logout.title': 'تسجيل الخروج',
  'settings.logout.message': 'هل تريد فعلاً تسجيل الخروج؟',
  'settings.logout.inprogress': 'جارٍ تسجيل الخروج...',
  'settings.loading': 'جارٍ تحميل الإعدادات',
  'settings.error.title': 'تعذّر تحميل إعداداتك',
  'settings.retry': 'إعادة المحاولة',
  'settings.offline.body': 'غير متصل — تبقى إعداداتك مقروءة، ويمكنك تعديلها عند عودة الشبكة.',
  'settings.save.error': 'لم يُحفظ الإعداد.',
  'settings.theme.sync_error': 'طُبّق المظهر على هذا الجهاز دون مزامنة.',
  'common.cancel': 'إلغاء',

  'media.video.play': 'تشغيل الفيديو',
  'media.video.pause': 'إيقاف مؤقت',
  'media.video.position': 'موضع التشغيل',
  'media.audio.position': 'موضع التشغيل',
  'media.audio.speed': 'سرعة التشغيل',
  'media.video.position.value': '{elapsed} من {total}',
  'media.video.mute': 'كتم الصوت',
  'media.video.unmute': 'إلغاء كتم الصوت',
  'media.video.more_options': 'مزيد من الخيارات',
  'media.video.speed': 'السرعة',
  'media.video.pip.enter': 'صورة داخل صورة',
  'media.video.pip.exit': 'الخروج من صورة داخل صورة',

  'community.list.create.accessibilityLabel': 'إنشاء مجتمع',
  'community.list.search.placeholder': 'ابحث عن مجتمع',
  'community.list.search.clear': 'مسح البحث',
  'community.list.search.empty': 'لا يوجد مجتمع يطابق «{query}».',
  'community.list.empty.title': 'لا توجد مجتمعات',
  'community.list.empty.subtitle': 'انضم إلى مجتمع أو أنشئ واحدًا للتحدث معًا.',
  'community.list.loading': 'جارٍ تحميل المجتمعات',
  'community.error.title': 'تعذّر تحميل المجتمعات',
  'community.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'community.retry': 'إعادة المحاولة',
  'community.offline.title': 'غير متصل',
  'community.offline.body': 'تبقى مجتمعاتك قابلة للقراءة؛ يتطلب إنشاء مجتمع اتصالًا.',
  'community.privacy.private': 'خاص',
  'community.privacy.public': 'عام',
  'community.members.one': '{count} عضو',
  'community.members.other': '{count} أعضاء',
  'community.conversations.one': '{count} محادثة',
  'community.conversations.other': '{count} محادثات',
  'community.detail.stats.members': 'الأعضاء',
  'community.detail.channels': 'المحادثات',
  'community.detail.channels.empty': 'لم تنضم بعد إلى أي محادثة في هذا المجتمع.',
  'community.detail.untitled': 'محادثة بلا عنوان',
  'community.detail.back': 'العودة إلى المجتمعات',
  'community.detail.refused.title': 'المجتمع غير موجود',
  'community.detail.refused.body': 'إنه غير موجود، أو خاص ولست عضوًا فيه.',
  'community.detail.error.title': 'تعذّر تحميل هذا المجتمع',
  'community.detail.loading': 'جارٍ تحميل المجتمع',
  'community.create.title': 'مجتمع جديد',
  'community.create.preview.placeholder': 'مجتمعي',
  'community.create.field.name': 'الاسم',
  'community.create.field.name.placeholder': 'اسم المجتمع',
  'community.create.field.identifier': 'المعرّف',
  'community.create.field.identifier.placeholder': 'my-group',
  'community.create.field.description': 'الوصف',
  'community.create.field.description.placeholder': 'عمّ يدور هذا المجتمع؟',
  'community.create.privacy.title': 'مجتمع خاص',
  'community.create.privacy.private.description': 'يمكن للأعضاء المدعوين فقط الانضمام',
  'community.create.privacy.public.description': 'يمكن للجميع اكتشافه والانضمام إليه',
  'community.create.button': 'إنشاء المجتمع',
  'community.create.inprogress': 'جارٍ الإنشاء…',
  'community.create.error.name': 'أعطه اسمًا لا يتجاوز 100 حرف.',
  'community.create.error.identifier': 'أحرف وأرقام وشرطات وشرطات سفلية فقط، 50 على الأكثر.',
  'community.create.error.description': '500 حرف على الأكثر.',
  'community.create.error.conflict': 'هذا المعرّف مستخدم بالفعل.',
  'community.create.error.offline': 'غير متصل — لم يُرسَل المجتمع.',
  'community.create.error.default': 'لم يُنشأ المجتمع. أعد المحاولة.',
  'calls.filters': 'تصفية سجل المكالمات',
  'calls.filter.all': 'الكل',
  'calls.filter.missed': 'الفائتة',
  'calls.direction.incoming': 'واردة',
  'calls.direction.outgoing': 'صادرة',
  'calls.direction.missed': 'فائتة',
  'calls.a11y.incoming': 'مكالمة واردة',
  'calls.a11y.outgoing': 'مكالمة صادرة',
  'calls.a11y.missed': 'مكالمة فائتة',
  'calls.type.audio': 'مكالمة صوتية',
  'calls.type.video': 'مكالمة فيديو',
  'calls.duration': 'المدة {duration}',
  'calls.unknown': 'غير معروف',
  'calls.empty.title': 'لا مكالمات حديثة',
  'calls.empty.subtitle': 'ستظهر هنا مكالماتك الواردة والفائتة والملغاة والصادرة.',
  'calls.empty.missed.title': 'لا مكالمات فائتة',
  'calls.empty.missed.subtitle': 'ستظهر هنا المكالمات التي لم تُجب عليها.',
  'calls.error.title': 'تعذّر تحميل سجل المكالمات',
  'calls.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'calls.offline.title': 'غير متصل',
  'calls.offline.body': 'تعرض سجل آخر تحميل.',
  'calls.offline.cold.body': 'سيُحمَّل السجل فور عودة الاتصال.',
  'calls.retry': 'أعد المحاولة',
  'calls.loading': 'جارٍ تحميل سجل المكالمات',
  'calls.allLoaded': 'تم تحميل كل مكالمات الأشهر الثلاثة الأخيرة',

  'discover.tabs': 'أقسام الاكتشاف',
  'discover.tab.discover': 'اكتشاف',
  'discover.tab.requests': 'الطلبات',
  'discover.tab.blocked': 'المحظورون',
  'discover.tab.requests.count.one': 'الطلبات، {count} طلب وارد',
  'discover.tab.requests.count.other': 'الطلبات، {count} طلبات واردة',
  'discover.invite.title': 'دعوة عبر البريد الإلكتروني',
  'discover.invite.placeholder': 'عنوان البريد الإلكتروني',
  'discover.invite.send': 'إرسال',
  'discover.invite.sending': 'جارٍ الإرسال…',
  'discover.invite.sendLabel': 'إرسال الدعوة عبر البريد الإلكتروني',
  'discover.invite.sent': 'أُرسلت الدعوة إلى {email}',
  'discover.invite.invalid': 'عنوان البريد الإلكتروني هذا غير صالح.',
  'discover.invite.conflict': 'هذا الشخص موجود على Meeshy بالفعل: ابحث عنه أدناه.',
  'discover.invite.error': 'تعذّر إرسال الدعوة. أعد المحاولة.',
  'discover.invite.offline': 'غير متصل: اتصل لإرسال الدعوة.',
  'discover.search.label': 'ابحث عن مستخدم على Meeshy',
  'discover.search.clear': 'مسح البحث',
  'discover.search.searching': 'جارٍ البحث',
  'discover.search.empty': 'لم يُعثر على أي مستخدم لـ «{query}»',
  'discover.search.error': 'تعذّر البحث. تحقّق من اتصالك.',
  'discover.connection.add': 'إضافة',
  'discover.connection.addLabel': 'إضافة {name}',
  'discover.connection.pending': 'قيد الانتظار',
  'discover.connection.cancelLabel': 'إلغاء الطلب المرسل إلى {name}',
  'discover.connection.contact': 'جهة اتصال',
  'discover.connection.blocked': 'محظور',
  'discover.connection.acceptLabel': 'قبول طلب {name}',
  'discover.connection.rejectLabel': 'رفض طلب {name}',
  'discover.requests.filters': 'تصفية الطلبات',
  'discover.requests.received': 'الواردة',
  'discover.requests.sent': 'المرسلة',
  'discover.requests.intent': 'يرغب في التواصل معك',
  'discover.requests.cancel': 'إلغاء',
  'discover.requests.empty.received.title': 'لا توجد طلبات واردة',
  'discover.requests.empty.received.subtitle': 'ستظهر هنا طلبات التواصل التي تتلقاها.',
  'discover.requests.empty.sent.title': 'لا توجد طلبات مرسلة',
  'discover.requests.empty.sent.subtitle': 'ستظهر هنا الطلبات التي ترسلها.',
  'discover.blocked.unblock': 'إلغاء الحظر',
  'discover.blocked.unblockLabel': 'إلغاء حظر {name}',
  'discover.blocked.confirm.title': 'إلغاء الحظر؟',
  'discover.blocked.confirm.body': 'إلغاء حظر {name}؟',
  'discover.blocked.confirm.cancel': 'إلغاء',
  'discover.blocked.empty.title': 'لا يوجد مستخدمون محظورون',
  'discover.blocked.empty.subtitle': 'سيظهر هنا الأشخاص الذين تحظرهم.',
  'discover.unknown': 'مجهول',
  'discover.loading': 'جارٍ التحميل',
  'discover.allLoaded': 'تم تحميل القائمة كاملة',
  'discover.error.title': 'تعذّر تحميل هذه القائمة',
  'discover.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'discover.offline.title': 'غير متصل',
  'discover.offline.body': 'تعرض قائمة آخر تحميل.',
  'discover.offline.cold.body': 'ستُحمَّل القائمة فور عودة الاتصال.',
  'discover.retry': 'إعادة المحاولة',
  'discover.announce.accepted': 'تم قبول التواصل',
  'discover.announce.rejected': 'تم رفض الطلب',
  'discover.announce.cancelled': 'تم إلغاء الطلب',
  'discover.announce.sent': 'تم إرسال الطلب',
  'discover.announce.unblocked': 'تم إلغاء حظر المستخدم',
  'discover.announce.acceptFailed': 'تعذّر قبول هذا الطلب',
  'discover.announce.rejectFailed': 'تعذّر رفض هذا الطلب',
  'discover.announce.cancelFailed': 'تعذّر إلغاء هذا الطلب',
  'discover.announce.sendFailed': 'تعذّر إرسال الطلب',
  'discover.announce.unblockFailed': 'تعذّر إلغاء الحظر',
  'discover.announce.offline': 'غير متصل: لم يُرسَل شيء.',

  'userProfile.title': 'الملف الشخصي',
  'userProfile.loading': 'جارٍ تحميل الملف الشخصي',
  'userProfile.section.publications': 'المنشورات',
  'userProfile.section.relation': 'الاتصال',
  'userProfile.section.conversations': 'المحادثات',
  'userProfile.conversations.empty': 'لا توجد محادثة مشتركة',
  'userProfile.conversations.emptyBody': 'لا شيء يجمعكما بعد — «اكتب» يفتح المحادثة الأولى.',
  'userProfile.conversations.error': 'تعذّر تحميل المحادثات',
  'userProfile.conversations.loading': 'جارٍ تحميل المحادثات',
  'userProfile.refused.title': 'هذا الملف الشخصي غير متاح',
  'userProfile.refused.body': 'إما أنه غير موجود، أو لا تملك صلاحية الوصول إليه.',
  'userProfile.throttled.title': 'طلبات كثيرة جدًا',
  'userProfile.throttled.body': 'أعد المحاولة بعد لحظة.',
  'userProfile.error.title': 'تعذّر تحميل هذا الملف الشخصي',
  'userProfile.error.body': 'أعد المحاولة بعد لحظة.',
  'userProfile.offline.body': 'سيظهر الملف الشخصي عند عودة الاتصال.',
  'userProfile.posts.empty': 'لا توجد منشورات',
  'userProfile.posts.emptyBody': 'لا يوجد بعد محتوى عام للقراءة.',
  'userProfile.posts.emptyPosts': 'لا توجد منشورات هنا',
  'userProfile.posts.emptyReels': 'لا توجد ريلز هنا',
  'userProfile.posts.emptyFilter': 'انقر على البطاقة مرة أخرى لعرض كل شيء.',
  'userProfile.posts.error': 'تعذّر تحميل المنشورات',
  'userProfile.posts.loadMore': 'تحميل المزيد',
  'userProfile.posts.loaded': 'المنشورات المضافة: {count}',
  'userProfile.posts.loadedNone': 'لا مزيد من المنشورات للعرض',
  'userProfile.posts.loading': 'جارٍ التحميل…',
  'userProfile.stat.posts': 'منشورات',
  'userProfile.stat.reels': 'ريلز',
  'userProfile.stat.stories': 'قصص',
  'userProfile.stat.filterLabel': 'التصفية على {name}',
  'userProfile.stat.filterClear': 'عرض الكل',
  'userProfile.context.received': 'يريد {name} التواصل معك. اقبل لتبادل الرسائل.',
  'userProfile.context.sent': 'أرسلت طلب اتصال إلى {name}. في انتظار الرد.',
  'userProfile.action.write': 'مراسلة',
  'userProfile.action.writeLabel': 'مراسلة {name}',
  'userProfile.action.block': 'حظر',
  'userProfile.action.blockLabel': 'حظر {name}',
  'userProfile.blocked.title': 'لقد حظرت هذا الشخص',
  'userProfile.blocked.body': 'تبقى منشوراته وإحصاءاته مخفية ما دام الحظر قائمًا.',
  'userProfile.signin.title': 'سجّل الدخول للتواصل',
  'userProfile.signin.body': 'طلبات الاتصال والرسائل تتطلب حسابًا.',
  'userProfile.signin.cta': 'تسجيل الدخول',
  'userProfile.announce.blocked': 'تم حظر الشخص',
  'userProfile.announce.blockFailed': 'تعذّر الحظر',
  'userProfile.announce.writeFailed': 'تعذّر فتح المحادثة',

  'a11y.floating.rung.discover.requests.one': 'اكتشاف، {count} طلب وارد',
  'a11y.floating.rung.discover.requests.other': 'اكتشاف، {count} طلبات واردة',

  'links.hub.banner.title': 'إدارة روابطك',
  'links.hub.banner.subtitle': 'ادعُ من تشاء إلى محادثاتك',
  'links.hub.share.title': 'روابط المشاركة',
  'links.hub.share.description': 'ادعُ جهات اتصالك للانضمام إلى محادثاتك',
  'links.hub.share.create': 'إنشاء رابط مشاركة',
  'links.share.back': 'العودة إلى روابطي',
  'links.share.stats.total': 'الروابط',
  'links.share.stats.active': 'النشطة',
  'links.share.stats.joined': 'المنضمّون',
  'links.share.joined.one': 'انضمّ {count}',
  'links.share.joined.other': 'انضمّ {count}',
  'links.share.copy': 'نسخ الرابط',
  'links.share.empty.title': 'لا توجد روابط مشاركة',
  'links.share.empty.subtitle': 'أنشئ رابطًا لدعوة أشخاص إلى محادثة',
  'links.share.loading': 'جارٍ تحميل الروابط',
  'links.share.allLoaded': 'تم تحميل كل روابطك',
  'links.status.active': 'نشط',
  'links.status.inactive': 'غير نشط',
  'links.unlimited': 'غير محدود',
  'links.error.title': 'تعذّر تحميل روابطك',
  'links.error.body': 'تحقّق من اتصالك ثم أعد المحاولة.',
  'links.retry': 'إعادة المحاولة',
  'links.offline.title': 'غير متصل',
  'links.offline.body': 'تبقى روابطك قابلة للقراءة؛ يتطلب تعديلها اتصالًا.',
  'links.detail.back': 'العودة إلى روابط المشاركة',
  'links.detail.copy': 'نسخ',
  'links.detail.copied': 'تم النسخ',
  'links.detail.share': 'مشاركة',
  'links.detail.disable': 'تعطيل',
  'links.detail.activate': 'تفعيل',
  'links.detail.stats': 'الإحصاءات',
  'links.detail.stats.uses': 'مرات الاستخدام',
  'links.detail.stats.max': 'الحد الأقصى',
  'links.detail.info': 'المعلومات',
  'links.detail.identifier': 'المعرّف',
  'links.detail.createdAt': 'تاريخ الإنشاء',
  'links.detail.expiresAt': 'تاريخ الانتهاء',
  'links.detail.reason.closed': 'المحادثة مغلقة: لم يعد هذا الرابط يسمح بالدخول.',
  'links.detail.reason.expired': 'انتهت صلاحية هذا الرابط.',
  'links.detail.reason.revoked': 'لقد عطّلت هذا الرابط.',
  'links.detail.refused.title': 'الرابط غير موجود',
  'links.detail.refused.body': 'هذا الرابط غير موجود أو ليس من روابطك.',
  'links.detail.loading': 'جارٍ تحميل الرابط',
  'links.announce.copied': 'تم نسخ الرابط',
  'links.announce.copyFailed': 'تعذّر نسخ الرابط',
  'links.announce.shareUnavailable': 'المشاركة غير متاحة هنا',
  'links.announce.disabled': 'تم تعطيل الرابط',
  'links.announce.activated': 'تم تفعيل الرابط',
  'links.announce.toggleFailed': 'تعذّر تعديل هذا الرابط',
  'links.announce.offline': 'غير متصل: لم يُرسَل شيء.',
  'links.create.title': 'رابط مشاركة جديد',
  'links.create.section.conversation': 'المحادثة',
  'links.create.choose': 'اختر مجموعة أو مجتمعًا',
  'links.create.picker.title': 'اختر محادثة',
  'links.create.picker.empty': 'لا توجد محادثة يمكنها استقبال رابط حاليًا.',
  'links.create.section.identity': 'هوية الرابط',
  'links.create.name': 'اسم الرابط',
  'links.create.name.placeholder': 'مثال: مشاركة على تويتر',
  'links.create.description': 'الوصف (اختياري)',
  'links.create.description.placeholder': 'مثال: انضمّ إلى مجموعتنا…',
  'links.create.section.access': 'وصول الضيوف',
  'links.create.section.access.subtitle': 'ما يجب أن يقدّمه الزوار للانضمام',
  'links.create.access.account': 'الحساب مطلوب',
  'links.create.access.account.caption': 'لا ينضمّ إلا أعضاء Meeshy',
  'links.create.access.nickname': 'الاسم المستعار مطلوب',
  'links.create.access.nickname.caption': 'على الزائر اختيار اسم مستعار',
  'links.create.access.email': 'البريد الإلكتروني مطلوب',
  'links.create.access.email.caption': 'على الزائر تقديم بريده الإلكتروني',
  'links.create.access.birthday': 'تاريخ الميلاد مطلوب',
  'links.create.access.birthday.caption': 'يتيح التحقّق من العمر',
  'links.create.section.permissions': 'الأذونات',
  'links.create.section.permissions.subtitle': 'ما يمكن للضيوف المجهولين فعله',
  'links.create.permission.messages': 'إرسال الرسائل',
  'links.create.permission.messages.caption': 'يمكن للضيوف الكتابة في المحادثة',
  'links.create.permission.images': 'إرسال الصور',
  'links.create.permission.images.caption': 'يمكن للضيوف مشاركة الصور',
  'links.create.permission.files': 'إرسال الملفات',
  'links.create.permission.files.caption': 'يمكن للضيوف إرسال المستندات',
  'links.create.permission.history': 'عرض السجل',
  'links.create.permission.history.caption': 'يرى الضيوف الرسائل السابقة',
  'links.create.section.limits': 'الحدود',
  'links.create.section.limits.subtitle': 'تحكّم في جمهور الرابط ومدة صلاحيته',
  'links.create.limit.uses': 'تحديد عدد الاستخدامات',
  'links.create.limit.max.one': '{count} استخدام كحد أقصى',
  'links.create.limit.max.other': '{count} استخدامات كحد أقصى',
  'links.create.limit.count': 'عدد الاستخدامات',
  'links.create.limit.invalid': 'اختر عددًا صحيحًا بين 1 و{max}.',
  'links.create.expiration': 'انتهاء الصلاحية',
  'links.create.expiration.never': 'أبدًا',
  'links.create.expiration.h24': '24 ساعة',
  'links.create.expiration.d7': '7 أيام',
  'links.create.expiration.d30': '30 يومًا',
  'links.create.expiration.m3': '3 أشهر',
  'links.create.button': 'إنشاء رابط المشاركة',
  'links.create.inprogress': 'جارٍ الإنشاء…',
  'links.create.error.conversation': 'اختر محادثة أولًا.',
  'links.create.error.offline': 'غير متصل: لم يُنشأ الرابط.',
  'links.create.error.refused': 'لا يمكنك إنشاء رابط لهذه المحادثة.',
  'links.create.error.default': 'تعذّر إنشاء الرابط. أعد المحاولة.',

  'feed.scene.carousel.previous': 'المشهد السابق',
  'feed.scene.carousel.next': 'المشهد التالي',
  'feed.scene.mosaic.tile': 'المشهد {index}',
  'feed.scene.mosaic.more': 'المشهد {index}، و{count} أخرى',
  'feed.scene.mosaic.video': 'المشهد {index}، فيديو',
  'feed.scene.shared_by': 'مشهد شاركه {author}',
  'feed.scene.open.fullscreen': 'اضغط مرتين للعرض بملء الشاشة',
  'feed.scene.open.post': 'اضغط مرتين لفتح المنشور',
  'feed.scene.sound.muted': 'الصوت مكتوم',
  'feed.scene.count': '{count} مشاهد',
  'scene.fullscreen.play': 'استئناف الكل',
  'scene.fullscreen.pause': 'إيقاف الكل مؤقتًا',
  'scene.fullscreen.sound.on': 'تشغيل الصوت',
  'scene.fullscreen.sound.off': 'كتم الصوت',
  'scene.place.here': 'هنا',

  'story.sound.off': 'صامت',

  /* استوديو القصص (#6900) — إنشاء قصة بخلفية وصوت خلفية ونص، مع معاينة
     بواسطة المحرك المشترك، تُنشر بصيغة CanvasV3 مثل iOS. */
  'story.studio.title': 'قصة جديدة',
  'story.studio.cancel': 'إلغاء',
  'story.studio.publish': 'نشر',
  'story.studio.publishing': 'جارٍ النشر…',
  'story.studio.publish.waiting': 'في انتظار الشبكة…',
  'story.studio.publishing.progress': 'نشر {current}/{total}…',
  'story.studio.outcome.partial': 'تم نشر {published} من {total} — تبقى البقية هنا.',
  'story.studio.title.post': 'منشور جديد',
  'story.studio.title.reel': 'ريل جديد',
  'story.studio.publish.as.story': 'نشر القصة',
  'story.studio.publish.as.post': 'نشر المنشور',
  'story.studio.publish.as.reel': 'نشر الريل',
  'story.studio.publish.menu': 'النشر بصفة',
  'story.studio.kind.story': 'قصة',
  'story.studio.kind.post': 'منشور',
  'story.studio.kind.reel': 'ريل',
  'story.studio.refusal.reel': 'يحتاج الريل إلى فيديو أو صوت لا يقل عن 3 ثوانٍ، أو صورتين على الأقل.',
  'story.studio.offline': 'غير متصل — ستُنشر القصة عند عودة الشبكة.',
  'story.studio.stage': 'معاينة القصة',
  'story.studio.background.add': 'إضافة صورة أو فيديو',
  'story.studio.background.label': 'الخلفية',
  'story.studio.background.remove': 'إزالة الخلفية',
  'story.studio.sound.add': 'إضافة صوت',
  'story.studio.sound.label': 'صوت الخلفية',
  'story.studio.sound.remove': 'إزالة الصوت',
  'story.studio.sound.mute': 'كتم الصوت',
  'story.studio.sound.unmute': 'تشغيل الصوت',
  'story.studio.upload.progress': 'جارٍ الإرسال… {percent}٪',
  'story.studio.upload.ready': 'جاهز',
  'story.studio.upload.retry': 'إعادة المحاولة',
  'story.studio.text.label': 'نص القصة',
  'story.studio.text.placeholder': 'إضافة نص',
  'story.studio.hint.duration': 'تبقى القصة مرئية لمدة عشرين ساعة.',
  'story.studio.error.upload': 'تعذّر إرسال الملف.',
  'story.studio.error.publish': 'تعذّر نشر القصة.',
  'story.studio.refusal.title': 'يلزم حساب لإنشاء قصة.',
  'story.studio.refusal.login': 'تسجيل الدخول',
  'story.studio.refusal.door.visual': 'اختر صورة أو فيديو.',
  'story.studio.refusal.door.sound': 'اختر ملفًا صوتيًا.',
  'story.studio.refusal.media-max': 'هذا المنشور يحمل بالفعل عشرة عناصر وسائط — وهو الحد الأقصى للبوابة.',
  'story.studio.failure.network': 'الشبكة غير متاحة.',
  'story.studio.failure.timeout': 'لم يستجب الخادم.',
  'story.studio.failure.session': 'انتهت الجلسة — سجّل الدخول مجددًا.',
  'story.studio.failure.account': 'يلزم حساب لنشر وسائط.',
  'story.studio.failure.forbidden': 'الإجراء غير مسموح لهذا الحساب.',
  'story.studio.failure.tooLarge': 'الملف كبير جدًا.',
  'story.studio.failure.fileRefused': 'تم رفض الملف: نوعه لا يطابق محتواه.',
  'story.studio.failure.rateLimited': 'منشورات كثيرة دفعة واحدة — أعد المحاولة بعد لحظة.',
  'story.studio.failure.refused': 'تم رفض النشر.',
  'story.studio.failure.unavailable': 'الخادم غير متاح.',
  'story.studio.text.add': 'إضافة نص',
  'story.studio.text.remove': 'إزالة هذا النص',
  'story.studio.object.text': 'نص {index}',
  'story.studio.object.overlay': 'طبقة',
  'story.studio.object.select': 'تحديد {name}',
  'story.studio.objects.label': 'عناصر المشهد',
  'story.studio.overlay.add': 'ضع صورة على المشهد',
  'story.studio.overlay.label': 'طبقة',
  'story.studio.overlay.remove': 'إزالة الطبقة',
  'story.studio.pages.label': 'مشاهد المنشور',
  'story.studio.page.position': 'المشهد {index} من {count}',
  'story.studio.page.add': 'إنشاء مشهد',
  'story.studio.page.remove': 'حذف المشهد {index}',
  'story.studio.page.failed': 'تعذّر إرسال وسائط',
  'story.studio.layout.title': 'تخطيط المشاهد',
  'story.studio.layout.carousel': 'واحدة تلو الأخرى',
  'story.studio.layout.reel': 'تمرير متواصل',
  'story.studio.layout.hero': 'واحدة كبيرة والبقية بجانبها',
  'story.studio.layout.wave': 'على شكل موجة',
  'story.studio.layout.sine': 'متعرج',
  'story.studio.caption.label': 'تعليق {media}',
  'story.studio.caption.placeholder': 'إضافة تعليق',
  'story.studio.sound.plane.label': 'موضع الصوت',
  'story.studio.sound.plane.background': 'في الخلفية',
  'story.studio.sound.plane.foreground': 'على المشهد',
  'story.studio.editor.label': 'إعدادات العنصر',
  'story.studio.editor.style': 'الخط',
  'story.studio.editor.effect': 'التأثير',
  'story.studio.editor.color': 'اللون',
  'story.studio.editor.align': 'المحاذاة',
  'story.studio.editor.background': 'خلفية النص',
  'story.studio.editor.language': 'لغة النص',
  'story.studio.editor.none': 'بلا',
  'story.studio.editor.empty': 'حدد عنصراً لضبطه.',
  'story.studio.style.bold': 'عريض',
  'story.studio.style.neon': 'نيون',
  'story.studio.style.classic': 'كلاسيكي',
  'story.studio.style.italic': 'مائل',
  'story.studio.style.typewriter': 'آلة كاتبة',
  'story.studio.style.handwriting': 'خط اليد',
  'story.studio.style.calligraphy': 'خط منمق',
  'story.studio.style.cartoon': 'كرتوني',
  'story.studio.style.futuristic': 'مستقبلي',
  'story.studio.style.fantasy': 'خيالي',
  'story.studio.style.curve': 'منحني',
  'story.studio.style.tag': 'غرافيتي',
  'story.studio.style.retro': 'ريترو',
  'story.studio.style.elegant': 'أنيق',
  'story.studio.style.poster': 'ملصق',
  'story.studio.style.bubble': 'فقاعة',
  'story.studio.style.note': 'ملاحظة',
  'story.studio.style.brush': 'فرشاة',
  'story.studio.effect.glow': 'توهج',
  'story.studio.effect.neon': 'نيون',
  'story.studio.effect.outline': 'حد خارجي',
  'story.studio.effect.shadow': 'ظل',
  'story.studio.effect.longShadow': 'ظل ممتد',
  'story.studio.effect.emboss': 'نقش بارز',
  'story.studio.color.FFFFFF': 'أبيض',
  'story.studio.color.000000': 'أسود',
  'story.studio.color.FF2E63': 'وردي',
  'story.studio.color.08D9D6': 'سماوي',
  'story.studio.color.F8B500': 'كهرماني',
  'story.studio.color.9B59B6': 'بنفسجي',
  'story.studio.color.2ECC71': 'أخضر',
  'story.studio.color.3498DB': 'أزرق',
  'story.studio.align.left': 'يسار',
  'story.studio.align.center': 'وسط',
  'story.studio.align.right': 'يمين',
  'story.studio.pose.label': 'الموضع والحجم',
  'story.studio.pose.bigger': 'تكبير',
  'story.studio.pose.smaller': 'تصغير',
  'story.studio.pose.rotateLeft': 'تدوير لليسار',
  'story.studio.pose.rotateRight': 'تدوير لليمين',
  'story.studio.pose.reset': 'إعادة التوسيط',
  'story.studio.pose.handle': 'تحريك {name} — الأسهم للتحريك، + و − للحجم، [ و ] للتدوير',
  'story.studio.pose.grip': 'تغيير حجم {name} وتدويره',

  /* ورقة جمهور الاستوديو (#7683) — القيم الست لـ PostVisibility،
     مرآة PostVisibility.swift (packages/MeeshySDK). */
  'story.studio.audience.chip.label': 'الجمهور',
  'story.studio.audience.title': 'الجمهور',
  'story.studio.audience.public': 'عام',
  'story.studio.audience.community': 'المجتمعات',
  'story.studio.audience.friends': 'جهات الاتصال',
  'story.studio.audience.except': 'باستثناء…',
  'story.studio.audience.only': 'فقط…',
  'story.studio.audience.private': 'خاص',
  'story.studio.audience.subtitle.public': 'الجميع، بمن فيهم غير المتابعين',
  'story.studio.audience.subtitle.community': 'أعضاء مجتمعاتك',
  'story.studio.audience.subtitle.friends': 'جهات اتصالك المقبولة',
  'story.studio.audience.subtitle.private': 'أنت فقط — لا يُنشر شيء',
  'story.studio.audience.refusal.people': 'اختيار الأشخاص غير متاح بعد على الويب.',
  'story.studio.audience.scope': 'الجمهور المختار ملك للمنشور، وليس للتنسيق أبدًا: تغيير التنسيق يحافظ عليه.',
  'story.studio.audience.defaultMark': 'افتراضي',

  'appUpdate.available': 'يتوفر إصدار جديد من Meeshy!',
  'appUpdate.hint': 'أعد التحميل للحصول على أحدث المزايا.',
  'appUpdate.storeHint': 'ثبّتها من متجر التطبيقات.',
  'appUpdate.action': 'تحديث',
  'appUpdate.dismiss': 'انتظار',
  'appUpdate.applying': 'جارٍ التحديث…',
  'appUpdate.region': 'تحديث التطبيق',

  'story.action.rail': 'إجراءات القصة',
  'story.action.react': 'تفاعل',
  'story.action.reply': 'رد',
  'story.action.forward': 'إرسال',
  'story.action.repost': 'إعادة نشر',
  'story.action.views': 'المشاهدات',
  'story.action.share': 'مشاركة',
  'story.action.save': 'حفظ',
  'story.action.comments': 'التعليقات',
  'story.action.translations': 'الترجمات',
  'story.views.empty.title': 'لا مشاهدات بعد',
  'story.views.empty.subtitle': 'سيظهر هنا الأشخاص الذين يشاهدون قصتك.',
  'story.views.count.one': '{count} مشاهدة',
  'story.views.count.other': '{count} مشاهدات',
  'story.save.progress': 'جارٍ الحفظ {percent}%',
  'story.save.cancel': 'إلغاء الحفظ',
  'story.save.success': 'تم حفظ القصة',
  'story.save.failed': 'فشل الحفظ',
  'story.save.cancelled': 'تم إلغاء التصدير',
  'story.views.loading': 'جارٍ تحميل المشاهدات…',
  'story.views.offline': 'غير متصل — ستظهر القائمة عند عودة الشبكة.',
  'story.views.forbidden': 'صاحب القصة وحده يرى من شاهدها.',
  'story.save.offline': 'غير متصل — أعد المحاولة عند عودة الشبكة.',
  'story.save.refused': 'سجّل الدخول لحفظ هذه القصة.',
  'story.save.missing': 'لم تعد هذه الوسائط متاحة.',
  'story.save.retry': 'أعد المحاولة — اضغط على حفظ مرة أخرى.',
  'prism.translated.message': 'رسالة مترجمة',
  'prism.translated.comment': 'تعليق مترجم',
  'prism.translated.post': 'منشور مترجم',
  'prism.original.show.message': 'عرض الرسالة بلغتها الأصلية',
  'prism.original.show.comment': 'عرض التعليق بلغته الأصلية',
  'prism.original.show.post': 'عرض المنشور بلغته الأصلية',
  'prism.original.hide.message': 'إخفاء الرسالة بلغتها الأصلية',
  'prism.original.hide.comment': 'إخفاء التعليق بلغته الأصلية',
  'prism.original.hide.post': 'إخفاء المنشور بلغته الأصلية',

  'comments.title': 'التعليقات',
  'comments.close': 'إغلاق التعليقات',
  'comments.loading': 'جارٍ تحميل التعليقات',
  'comments.empty': 'لا توجد تعليقات',
  'comments.empty.hint': 'كن أول من يكتب تعليقًا.',
  'comments.error': 'تعذّر تحميل التعليقات',
  'comments.error.hint': 'حاول مرة أخرى بعد قليل.',
  'comments.retry': 'إعادة المحاولة',
  'comments.more': 'تحميل المزيد من التعليقات',
  'comments.offline': 'غير متصل — تُعرض التعليقات المحمَّلة فقط.',
  'comments.placeholder': 'اكتب تعليقًا…',
  'comments.send': 'إرسال التعليق',
  'comments.row.pending': 'جارٍ الإرسال',
  'comments.signin': 'سجّل الدخول للتعليق.',
  'comment.send.error': 'تعذّر نشر التعليق.',
  'comment.send.pending': 'لم يُؤكَّد التعليق — غير متصل',
  'comment.send.empty': 'اكتب شيئًا قبل الإرسال.',
  'comments.action.like': 'أعجبني',
  'comments.action.unlike': 'لم يعد يعجبني',
  'comments.action.edit': 'تعديل',
  'comments.action.delete': 'حذف',
  'comments.action.delete.confirm': 'تأكيد',
  'comments.edit.label': 'تعديل التعليق',
  'comments.edit.save': 'حفظ',
  'comments.edit.cancel': 'إلغاء',
  'comment.like.error': 'لم يُحفظ إعجابك.',
  'comment.edit.error': 'لم يُحفظ التعديل.',
  'comment.delete.error': 'تعذّر حذف التعليق.',
  'comment.gesture.pending': 'إجراء غير مؤكَّد — دون اتصال',
  'comment.gesture.unconfirmed': 'إجراء غير مؤكَّد — لم تستجب البوابة.',
  'comment.refused.session': 'انتهت الجلسة — سجّل الدخول من جديد.',
  'comment.refused.right': 'هذا الإجراء غير متاح لك.',
  'comment.like.limit': 'خمسة تفاعلات كحد أقصى لكل شخص.',
  'feed.action.comment': 'تعليق',

  'admin.title': 'الإدارة',

  'thread.unread-separator.one': '{count} رسالة غير مقروءة',
  'thread.unread-separator.other': '{count} رسائل غير مقروءة',
  'message-detail.info.title': 'معلومات الرسالة',
  'message-detail.received-by': 'استلمها',
  'message-detail.read-by': 'قرأها',
  'message-detail.not-yet': 'لم يصل بعد',
  'message-detail.received-by.empty': 'لا يوجد تأكيد تسليم بعد',
  'message-detail.read-by.empty': 'لم يقرأ أحد هذه الرسالة بعد',
  'message-detail.not-yet.empty': 'استلم الجميع الرسالة',
  'message-detail.open': 'عرض تفاصيل الرسالة',
  'message-detail.attachment.opens.one': '{count} فتحة',
  'message-detail.attachment.opens.other': '{count} فتحات',
  'message-detail.attachment.downloads.one': '{count} تنزيل',
  'message-detail.attachment.downloads.other': '{count} تنزيلات',
  'message-detail.attachment.listened-until': 'تم الاستماع حتى {time}',
  'message-detail.attachment.watched-until': 'تمت المشاهدة حتى {time}',
  'message-detail.attachment.complete': 'مكتمل',
  'message-detail.attachment.listen.empty': 'لم يُستمع بعد',
  'message-detail.attachment.watch.empty': 'لم تُشاهد بعد',
  'message-detail.attachment.open': 'فتح {name}',
  'message-detail.attachment.opened.empty': 'لم يُفتح بعد',
  'message-detail.loading': 'جارٍ التحميل…',
  'message-detail.load-error': 'تعذر تحميل هذه المعلومات',
  'message-detail.retry': 'إعادة المحاولة',

  'download.title': 'نزّل Meeshy',
  'download.body': 'اكتب بلغتك واقرأ بلغتك: يترجم Meeshy كل رسالة في الطريق.',
  'download.appStore': 'التنزيل من App Store',
  'download.web': 'افتح Meeshy في المتصفح',
  'download.otherPlatforms': 'على أندرويد وعلى الحاسوب، يعمل Meeshy مباشرة في المتصفح.',

  /* LES SOURCES DU COMPOSEUR (#7280) — miroir de `composer.attach.*` d'iOS. */
  'composer.attach.group': 'أنواع المرفقات',
  'composer.attach.handle': 'مقبض اللوحة',
  'composer.attach.photo': 'الصور',
  'composer.attach.photo.action': 'اختيار صور',
  'composer.attach.camera': 'الكاميرا',
  'composer.attach.camera.action': 'التقاط صورة',
  'composer.attach.file': 'ملف',
  'composer.attach.file.action': 'اختيار ملف',
  'composer.attach.location': 'الموقع',
  'composer.attach.location.action': 'مشاركة موقعي',
  'composer.attach.voice': 'صوت',
  'composer.attach.voice.action': 'تسجيل رسالة صوتية',
  'composer.attach.emoji': 'الرموز التعبيرية',
  'composer.attach.emoji.action': 'إدراج رمز تعبيري',
  'composer.emoji.title': 'إدراج رمز تعبيري',
  'composer.location.locating': 'جارٍ تحديد موقعك…',
  'composer.location.denied': 'تم رفض الموقع — اسمح به من الإعدادات',
  'composer.location.unavailable': 'الموقع غير متاح في هذا المتصفح',
  'composer.location.failed': 'تعذّر تحديد الموقع — أعد المحاولة',
  'composer.location.chip': 'موقع',
  'composer.location.unknown': 'مكان غير معروف',
  'composer.location.remove': 'إزالة الموقع',
  'composer.viewOnce.activate': 'تفعيل وضع المشاهدة لمرة واحدة',
  'composer.viewOnce.active': 'وضع المشاهدة لمرة واحدة نشط',
  'composer.viewOnce.label': 'مشاهدة لمرة واحدة',
  'composer.protection.ephemeral.state': 'الوضع المؤقت مفعّل',
  'composer.protection.blur.state': 'وضع التمويه مفعّل',
  'message.location.shared': 'موقع مشترك',
  'message.location.open': 'فتح في الخرائط',
  'message.location.a11y': 'الموقع: {place}',

  /* LES LIBELLÉS D'ÉTAT DU FIL (#7337) — voir `catalog-fr.ts` pour la règle. */
  'message.forwarded': 'تمت إعادة التوجيه',
  'message.forwarded.fromGroup': 'تمت إعادة التوجيه من {name}',
  'message.forwarded.fromPerson': 'موجّهة من {name}',
  'message.send.failed': 'لم يُرسَل',
  'message.send.failed.reason': 'لم يُرسَل — {reason}',
  'message.send.retry': 'إعادة المحاولة',
  'announce.messageNotSent': 'لم تُرسَل الرسالة',
  'announce.messageNotSent.reason': 'لم تُرسَل الرسالة — {reason}',
  'send.failure.offline': 'الشبكة غير متاحة',
  'send.failure.timeout': 'لم يستجب الخادم',
  'send.failure.uploadPartial': 'تعذّر رفع أحد المرفقات',
  'send.failure.newcomerSlowMode': 'مرحبًا! يمكن للحسابات الجديدة إرسال رسالة واحدة كل 30 ث — أعد المحاولة بعد {seconds} ث',
  'send.failure.newcomerSlowMode.soon': 'مرحبًا! يمكن للحسابات الجديدة إرسال رسالة واحدة كل 30 ث — أعد المحاولة بعد لحظات',
  'send.failure.sessionExpired': 'انتهت الجلسة — سجّل الدخول مجددًا',
  'send.failure.forbidden': 'الإرسال غير مسموح في هذه المحادثة',
  'send.failure.tooMany': 'رسائل كثيرة دفعة واحدة — أعد المحاولة بعد لحظات',
  'send.failure.rejected': 'رُفضت الرسالة',
  'send.failure.gatewayUnavailable': 'الخادم غير متاح',
  'message.deleted': 'تم حذف الرسالة',
  'message.expired.a11y': 'انتهت صلاحية الرسالة المؤقتة',
  'message.story.reply': 'رد على القصة',
  'message.story.label': 'قصة',
  'message.story.unavailable': 'القصة غير متاحة',
  'message.mood.label': 'المزاج',
  'message.withheld': 'محتوى محجوب',
  'message.withheld.a11y': 'محتوى محجوب: هذه الرسالة موجودة ولا تُعرض',
  'message.veiled': 'محتوى مخفي',
  'message.veiled.hint': 'اضغط لإظهار المحتوى',
  'message.veiled.error': 'يتعذّر الإظهار في الوقت الحالي',
  'message.ephemeral.a11y': 'رسالة مؤقتة، تختفي خلال {remaining}',
  'message.ephemeral.awaiting': 'في انتظار الاستلام',
  'message.ephemeral.awaiting.a11y': 'رسالة مؤقتة مدتها {duration}، في انتظار الاستلام',
  'message.viewOnce.tap': 'المس للعرض',
  'message.viewOnce.opened': 'تم فتحها',
  'message.viewOnce.sealed.a11y': 'رسالة تُعرض مرة واحدة، المس للعرض',
  'message.viewOnce.opened.a11y': 'رسالة تُعرض مرة واحدة، تم فتحها',
  'message.viewOnce.close': 'إغلاق',
  'attachment.protected.image': 'صورة محمية',
  'attachment.protected.video': 'فيديو محمي',
  'attachment.protected.audio': 'رسالة صوتية محمية',
  'attachment.protected.file': 'مرفق محمي',
  'media.reactions.badge.a11y': 'التفاعلات',
  'media.reactions.badge.mine.a11y': 'بما في ذلك تفاعلك',
  'attachment.kind.image': 'صورة',
  'attachment.kind.video': 'فيديو',
  'attachment.kind.audio': 'مقطع صوتي',
  'attachment.kind.file': 'ملف',

  /* Le menu du message, sa barre de sélection et sa feuille « Plus… » (#7555). */
  'message.menu.select': 'تحديد',
  'message.menu.translate': 'ترجمة',
  'message.menu.copy': 'نسخ',
  'message.menu.forward': 'إعادة توجيه',
  'message.menu.reply': 'رد',
  'message.menu.more': 'المزيد…',
  'message.menu.react': 'تفاعل',
  'message.menu.addReaction': 'إضافة تفاعل',
  'message.selection.toolbar': 'تحديد الرسائل',
  'message.selection.count': 'تم تحديد {count}',
  'message.detail.title': 'تفاصيل الرسالة',
  'message.detail.languages': 'اللغات',
  'message.detail.reactions': 'التفاعلات',
  'message.detail.sent': 'أُرسلت',
  'message.detail.language.original': '{language} (الأصل)',

  ...arMentions,
  ...arStoriesMine,
} satisfies InterfaceCatalog;

export default ar;
