import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const itStudioChrome = {
  'story.studio.more': 'Altre opzioni',
  'story.studio.preview': 'Anteprima',
  'story.studio.preview.close': 'Chiudi l’anteprima',
  'story.studio.page.remove.current': 'Elimina questa scena',
  'story.studio.postText': 'Testo del post',
  'story.studio.postText.placeholder': 'Scrivi il testo del post…',
  'story.studio.postText.done': 'Fine',
  'story.studio.tile.text': 'Testo',
  'story.studio.tile.time': 'Tempo',
  'story.studio.rail.scene': 'Strumenti della scena',
  'story.studio.timeline.unit': 's',
  'story.studio.tile.frame': 'Cornice',
  'story.studio.undo': 'Annulla',
  'story.studio.redo': 'Ripristina',
  'story.studio.frame': 'Cornice',
  'story.studio.frame.media': 'Il media',
  'story.studio.frame.around': 'Intorno al media',
  'story.studio.frame.fit': 'Adatta',
  'story.studio.frame.fill': 'Riempi',
  'story.studio.frame.fit.hint': 'Intero, dentro la cornice 9:16. Nulla viene ritagliato.',
  'story.studio.frame.fill.hint': 'Copre tutta la cornice 9:16, ritagliando i bordi se serve.',
  'story.studio.backdrop.blur': 'Sfocato',
  'story.studio.backdrop.black': 'Nero',
  'story.studio.backdrop.white': 'Bianco',
  'story.studio.backdrop.indigo': 'Indaco',
  'story.studio.backdrop.sand': 'Sabbia',
  'story.studio.animated': 'Animato',
  'story.studio.timeline': 'Timeline della scena',
  'story.studio.timeline.play': 'Riproduci',
  'story.studio.timeline.pause': 'Pausa',
  'story.studio.timeline.empty': 'Scrivi un testo o posa un livello: ogni oggetto ha la sua traccia.',
  'story.studio.timeline.overlay': 'Livello',
  'story.studio.retouch.title': 'Modifica l’immagine',
  'story.studio.retouch.done': 'Fine',
  'story.studio.retouch.cancel': 'Annulla la modifica',
  'composer.attachment.edit': 'Modifica {name}',
  'story.studio.retouch.failed': 'Impossibile generare il contenuto.',
  'story.studio.retouch.exporting': 'Esportazione in corso…',
  'story.studio.timeline.enter': 'Entra qui',
  'story.studio.timeline.exit': 'Esce qui',
  'story.studio.timeline.scrub': 'Sposta la testina',
  'story.studio.timeline.track': 'Traccia di {name}',
  'story.studio.timeline.earlier': 'Prima',
  'story.studio.timeline.later': 'Dopo',
  'story.studio.editor.filter': 'Filtro',
  'story.studio.filter.vintage': 'Vintage',
  'story.studio.filter.bw': 'B/N',
  'story.studio.filter.warm': 'Caldo',
  'story.studio.filter.cool': 'Freddo',
  'story.studio.filter.dramatic': 'Drammatico',
  'story.studio.filter.vivid': 'Vivace',
  'story.studio.filter.fade': 'Sbiadito',
  'story.studio.filter.chrome': 'Cromo',
  'story.studio.object.menu': 'Azioni per {name}',
  'story.studio.object.raise': 'Porta avanti',
  'story.studio.object.lower': 'Porta indietro',
  'story.studio.object.duplicate': 'Duplica',
  'story.studio.object.edit': 'Modifica',
  'story.studio.object.remove': 'Rimuovi',
  'story.studio.edit.done': 'OK',
  'story.studio.pose.left': 'A sinistra',
  'story.studio.pose.right': 'A destra',
  'story.studio.pose.up': 'In alto',
  'story.studio.pose.down': 'In basso',
  'story.studio.objects.edit': 'Modifica {name}',
  'story.studio.media.alt': 'Testo alternativo',
  'story.studio.media.alt.placeholder': 'Descrivi questo contenuto per i lettori di schermo',
  'composer.reelOffer.title': 'Pubblicare come reel?',
  'composer.reelOffer.body': 'Il tuo post contiene un solo video: come reel, si apre a schermo intero nei Reel.',
  'composer.reelOffer.reel': 'È un reel',
  'composer.reelOffer.post': 'È un post',
  'story.studio.tool.close': 'Chiudi lo strumento',
  'story.studio.camera.quick.holdFilm': 'Tieni premuto: filma',
  'story.studio.camera.quick.videoOnly': 'Tieni premuto per filmare',
  'story.studio.camera.quick.photo': 'Scatta una foto',
  'story.studio.camera.quick.video': 'Filma',
  'story.studio.camera.title': 'Fotocamera',
  'story.studio.camera.close': 'Torna alla scena',
  'story.studio.camera.flip': 'Cambia fotocamera',
  'story.studio.camera.flash': 'Flash',
  'story.studio.camera.shutter.photo': 'Scatta una foto',
  'story.studio.camera.shutter.start': 'Avvia la registrazione',
  'story.studio.camera.shutter.stop': 'Interrompi la registrazione',
  'story.studio.camera.hint.photo': 'Tocca lo schermo: foto · tienilo premuto: video',
  'story.studio.camera.hint.video': 'Tocca per filmare · tocca di nuovo per posare',
  'story.studio.camera.unavailable': 'La fotocamera non è disponibile. Consentila nelle impostazioni.',
  'story.studio.camera.openSettings': 'Impostazioni',
  'story.studio.camera.recording': 'Registrazione in corso',
  'story.studio.scene.empty.title': 'Questa è la tua scena',
  'story.studio.scene.empty.invite': 'Aggiungi un testo, un disegno, un’immagine o un video: rendila tua.',
  'story.studio.camera.locked': 'Registrazione bloccata',
  'story.studio.camera.hint.holding': 'Scorri fino al lucchetto per bloccare · verso l’alto per lo zoom',
  'story.studio.camera.hint.locked': 'Mani libere: scorri su o giù per lo zoom',
  'story.studio.camera.flash.intensity': 'Intensità del flash',
  'story.studio.camera.flash.intensityValue': '{percent}%',
  'story.studio.camera.quick.tapArm': 'Tocca: apri la fotocamera',
  'story.studio.camera.quick.tapAgain': 'Tocca di nuovo: foto',
  'story.studio.effect.column': 'Effetti della scena',
  'story.studio.effect.opening': 'Effetto di apertura',
  'story.studio.effect.visual': 'Effetto visivo',
  'story.studio.effect.close': 'Chiudi gli effetti',
  'story.studio.effect.row.opening': 'Apertura',
  'story.studio.effect.row.closing': 'Chiusura',
  'story.studio.transition.fade': 'Dissolvenza',
  'story.studio.transition.zoom': 'Zoom',
  'story.studio.transition.slide': 'Scorrimento',
  'story.studio.transition.reveal': 'Rivelazione',
  'story.studio.object.options': 'Opzioni di {name}',
  'story.studio.object.deselect': 'Deseleziona',
  'story.studio.object.setBackground': 'Imposta come sfondo',
  'story.studio.object.replaceBackground': 'Sostituisci lo sfondo',
  'story.studio.background.menu.title': 'Sfondo della scena',
  'story.studio.background.menu.edit': 'Modifica lo sfondo',
  'story.studio.background.menu.retake': 'Scatta di nuovo',
  'story.studio.background.menu.forward': 'Porta in primo piano',
  'story.studio.background.menu.remove': 'Rimuovi lo sfondo',
  'story.studio.background.tools': 'Strumenti dello sfondo',
  'story.studio.background.tools.describe': 'Descrivi',
  'story.studio.background.tools.leave': 'Torna alla scena',
  'story.studio.reelSwitch.announcement': 'Passato a reel',
} satisfies StudioChromeCatalogSlice;

export default itStudioChrome;
