/**
 * LE TIROIR DES PIÈCES JOINTES DU COMPOSEUR — tranche du catalogue, extraite
 * pour tenir le budget de taille (motif `catalog-fr-mentions.ts`) : ses
 * tuiles, la position partagée, et « Mes stickers » (#7938). Chaque langue
 * RÉPAND la sienne dans son catalogue.
 */
const frComposerAttach = {
  'composer.attach.group': 'Types de pièces jointes',
  'composer.attach.handle': 'Poignée du panneau',
  'composer.attach.photo': 'Photos',
  'composer.attach.photo.action': 'Choisir des photos',
  'composer.attach.camera': 'Caméra',
  'composer.attach.camera.action': 'Prendre une photo',
  'composer.attach.file': 'Fichier',
  'composer.attach.file.action': 'Choisir un fichier',
  'composer.attach.contact': 'Contact',
  'composer.attach.contact.action': 'Partager un contact',
  'composer.contact.failed': 'Ce contact ne peut pas être partagé',
  'composer.attach.location': 'Position',
  'composer.attach.location.action': 'Partager ma position',
  'composer.attach.voice': 'Vocal',
  'composer.attach.voice.action': 'Enregistrer un message vocal',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Insérer un emoji',
  'composer.emoji.title': 'Insérer un emoji',
  'composer.location.locating': 'Recherche de votre position…',
  'composer.location.denied': 'Position refusée — autorisez-la dans les réglages',
  'composer.location.unavailable': 'Position indisponible sur ce navigateur',
  'composer.location.failed': 'Position introuvable — réessayez',
  'composer.mic.refused': 'Micro refusé — autorisez-le dans les réglages',
  'composer.mic.unavailable': 'Micro indisponible sur cet appareil',
  'composer.openSettings': 'Réglages',
  'composer.location.chip': 'LIEU',
  'composer.location.unknown': 'Lieu inconnu',
  'composer.location.remove': 'Retirer la position',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Envoyer un sticker',
  'composer.sticker.title': 'Mes stickers',
  'composer.sticker.fromImage': 'Depuis une image',
  'composer.sticker.paste': 'Coller',
  'composer.sticker.pasteHint': 'Collez ou déposez une image ici pour en faire un sticker',
  'composer.sticker.nothingToPaste': 'Aucune image dans le presse-papier',
  'composer.sticker.empty': 'Aucun sticker pour l’instant — créez-en un depuis une image ou collez-en une',
  'composer.sticker.creating': 'Création du sticker…',
  'composer.sticker.manage': 'Gérer',
  'composer.sticker.done': 'Terminé',
  'composer.sticker.remove': 'Retirer ce sticker',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'Ce sticker n’a pas pu être relu — réessayez',
  'composer.sticker.error.notImage': 'Ce fichier n’est pas une image',
  'composer.sticker.error.tooLarge': 'Image trop lourde pour un sticker',
  'composer.sticker.error.full': 'Bibliothèque pleine — retirez un sticker pour en ajouter un',
  'composer.sticker.error.failed': 'Le sticker n’a pas pu être créé',
  'composer.sticker.tabs': 'Familles de stickers',
  'composer.sticker.tab.instants': 'Instants',
  'composer.sticker.tab.custom': 'Personnalisés',
  'composer.sticker.intent.bonjour.title': 'Bonjour, merci',
  'composer.sticker.intent.bonjour.hint': 'Pour saluer, remercier, dire oui, s’excuser ou souhaiter bonne nuit',
  'composer.sticker.intent.amour.title': 'Dire je t’aime',
  'composer.sticker.intent.amour.hint': 'Pour un mot doux, un bisou, un câlin ou une déclaration',
  'composer.sticker.intent.fete.title': 'Rire et fêter',
  'composer.sticker.intent.fete.hint': 'Pour une bonne nouvelle, un succès, un anniversaire ou un fou rire',
  'composer.sticker.intent.soutien.title': 'Consoler et soutenir',
  'composer.sticker.intent.soutien.hint': 'Pour encourager, réconforter ou dire « je suis là »',
  'composer.sticker.intent.rale.title': 'Râler et bouder',
  'composer.sticker.intent.rale.hint': 'Pour dire son agacement, sa colère, sa jalousie ou prendre ses distances',
  'composer.sticker.intent.coup-de-mou.title': 'Coup de mou',
  'composer.sticker.intent.coup-de-mou.hint': 'Pour la tristesse, le chagrin, la fatigue ou l’envie de dormir',
  'composer.sticker.intent.surprise.title': 'Surprise et frisson',
  'composer.sticker.intent.surprise.hint': 'Pour l’étonnement, la peur, la gêne ou un « oups »',
  'composer.sticker.intent.quotidien.title': 'Le quotidien',
  'composer.sticker.intent.quotidien.hint': 'Pour dire ce qu’on fait : un café, un repas, le travail, la route, un retard',
  'composer.sticker.intent.humour-noir.title': 'Humour noir',
  'composer.sticker.intent.humour-noir.hint': 'Pour rire de tout, même du pire : mort de rire, fantômes et pierres tombales',
  'composer.sticker.instants.hint': 'Ce que vous écrivez s’affiche sur le sticker',
  'composer.sticker.instants.message': 'Messages',
  'composer.sticker.instants.moment': 'Moments',
  'composer.sticker.instants.lieu': 'Lieux',
  'composer.sticker.instants.meteo': 'Météo',
  'composer.sticker.instants.field.message': 'Message',
  'composer.sticker.instants.field.place': 'Lieu',
  'composer.sticker.instants.field.weather': 'Météo',
  'composer.sticker.instants.field.time': 'Heure',
  'composer.quickEmoji.label': 'Envoyer directement',
  'composer.quickEmoji.group': 'Emojis rapides',
  'composer.effects.panel': 'Effets du message',
  'composer.effects.entrance': "Animation d'entrée",
  'composer.effects.permanent': 'Effet permanent',
  'composer.effects.clearAll': 'Tout effacer',
} as const;

export type ComposerAttachCatalogSlice = Readonly<Record<keyof typeof frComposerAttach, string>>;

export default frComposerAttach;
