import type { LinkFamiliesCatalog } from '@/lib/i18n-link-families-catalog';

const ar = {
  'links.hub.tracking.title': 'روابط التتبّع',
  'links.hub.tracking.description': 'تابع أداء روابط الإحالة الخاصة بك',
  'links.hub.tracking.create': 'إنشاء رابط تتبّع',
  'links.hub.community.title': 'روابط المجتمع',
  'links.hub.community.description': 'أدر روابط الدعوة إلى مجتمعاتك',
  'links.hub.affiliate.title': 'روابط الإحالة',
  'links.hub.affiliate.description': 'ادعُ شبكتك إلى Meeshy وتابع من يسجّل',
  'links.hub.affiliate.create': 'إنشاء رابط إحالة',

  'linkFamilies.delete': 'حذف',
  'linkFamilies.cancel': 'إلغاء',
  'linkFamilies.noData': 'لا توجد بيانات',
  'linkFamilies.announce.deleted': 'تم حذف الرابط',
  'linkFamilies.announce.deleteFailed': 'تعذّر حذف هذا الرابط',
  'linkFamilies.create.inprogress': 'جارٍ الإنشاء…',
  'linkFamilies.create.error.offline': 'غير متصل: لم يتم إنشاء الرابط.',
  'linkFamilies.create.error.default': 'تعذّر إنشاء الرابط. أعد المحاولة.',
  'linkFamilies.tracking.stats.links': 'الروابط',
  'linkFamilies.tracking.stats.clicks': 'النقرات',
  'linkFamilies.tracking.stats.uniques': 'الفريدة',
  'linkFamilies.tracking.stats.active': 'النشطة',
  'linkFamilies.tracking.clicks.one': '{count} نقرة',
  'linkFamilies.tracking.clicks.other': '{count} نقرات',
  'linkFamilies.tracking.uniques.one': '{count} فريدة',
  'linkFamilies.tracking.uniques.other': '{count} فريدة',
  'linkFamilies.tracking.copy': 'نسخ رابط التتبّع',
  'linkFamilies.tracking.empty.title': 'لا توجد روابط تتبّع',
  'linkFamilies.tracking.empty.subtitle': 'أنشئ رابطًا لتتبّع نقراتك وحملاتك',
  'linkFamilies.tracking.back': 'العودة إلى روابط التتبّع',
  'linkFamilies.tracking.totalClicks': 'إجمالي النقرات',
  'linkFamilies.tracking.uniqueClicks': 'النقرات الفريدة',
  'linkFamilies.tracking.lastClick': 'آخر نقرة: {date}',
  'linkFamilies.tracking.noClick': 'لا توجد نقرات بعد',
  'linkFamilies.tracking.countries': 'الدول',
  'linkFamilies.tracking.devices': 'الأجهزة',
  'linkFamilies.tracking.browsers': 'المتصفحات',
  'linkFamilies.tracking.social': 'المصادر الاجتماعية',
  'linkFamilies.tracking.recent': 'آخر النقرات',
  'linkFamilies.tracking.unknownPlace': 'موقع غير معروف',
  'linkFamilies.tracking.redirect.confirmed': 'تم تأكيد إعادة التوجيه',
  'linkFamilies.tracking.redirect.failed': 'فشلت إعادة التوجيه',
  'linkFamilies.tracking.redirect.pending': 'إعادة التوجيه قيد الانتظار',
  'linkFamilies.tracking.device.mobile': 'الجوال',
  'linkFamilies.tracking.device.desktop': 'الكمبيوتر',
  'linkFamilies.tracking.device.tablet': 'اللوحي',
  'linkFamilies.tracking.utm': 'إعدادات UTM',
  'linkFamilies.tracking.campaign': 'الحملة',
  'linkFamilies.tracking.source': 'المصدر',
  'linkFamilies.tracking.medium': 'الوسيط',
  'linkFamilies.tracking.destination': 'عنوان URL الوجهة',
  'linkFamilies.tracking.delete.title': 'حذف رابط التتبّع هذا؟',
  'linkFamilies.tracking.delete.body': 'سيتوقف الرابط عن إعادة التوجيه وستُفقد إحصاءاته.',
  'linkFamilies.tracking.create.title': 'رابط تتبّع جديد',
  'linkFamilies.tracking.create.section.destination': 'الوجهة',
  'linkFamilies.tracking.create.url': 'عنوان URL الوجهة',
  'linkFamilies.tracking.create.url.placeholder': 'https://example.com/page',
  'linkFamilies.tracking.create.url.invalid': 'أدخل عنوان ويب صالحًا.',
  'linkFamilies.tracking.create.name': 'الاسم الداخلي (اختياري)',
  'linkFamilies.tracking.create.name.placeholder': 'مثال: حملة العودة إلى المدارس',
  'linkFamilies.tracking.create.name.invalid': '32 حرفًا كحد أقصى.',
  'linkFamilies.tracking.create.section.utm': 'معلمات UTM',
  'linkFamilies.tracking.create.section.utm.subtitle': 'لمعرفة من أين تأتي نقراتك',
  'linkFamilies.tracking.create.campaign.placeholder': 'مثال: back-to-school',
  'linkFamilies.tracking.create.source.placeholder': 'مثال: instagram',
  'linkFamilies.tracking.create.medium.placeholder': 'مثال: social',
  'linkFamilies.tracking.create.section.token': 'رمز مخصّص',
  'linkFamilies.tracking.create.token': 'الرمز (اختياري)',
  'linkFamilies.tracking.create.token.placeholder': 'مثال: school26',
  'linkFamilies.tracking.create.token.help': 'اتركه فارغًا للحصول على رمز عشوائي.',
  'linkFamilies.tracking.create.token.invalid': 'من 5 إلى 50 حرفًا: أحرف أو أرقام أو «-» أو «_»، دون شرطة في البداية أو النهاية.',
  'linkFamilies.tracking.create.token.taken': 'هذا الرمز مستخدم بالفعل. اختر رمزًا آخر.',
  'linkFamilies.tracking.create.preview': 'رابطك: {url}',
  'linkFamilies.tracking.create.button': 'إنشاء رابط التتبّع',
  'linkFamilies.affiliate.title': 'الإحالة',
  'linkFamilies.affiliate.stats.links': 'الروابط',
  'linkFamilies.affiliate.stats.signups': 'المسجّلون',
  'linkFamilies.affiliate.stats.pending': 'قيد الانتظار',
  'linkFamilies.affiliate.section.referrals': 'المُحالون من طرفي',
  'linkFamilies.affiliate.signups.one': 'سجّل {count}',
  'linkFamilies.affiliate.signups.other': 'سجّل {count}',
  'linkFamilies.affiliate.uses': '{used} من {max}',
  'linkFamilies.affiliate.empty.title': 'لا توجد روابط إحالة',
  'linkFamilies.affiliate.empty.subtitle': 'أنشئ رابطًا لدعوة أصدقائك إلى Meeshy',
  'linkFamilies.affiliate.referrals.empty': 'لم يسجّل أحد بعد عبر روابطك.',
  'linkFamilies.affiliate.referral.completed': 'مسجّل',
  'linkFamilies.affiliate.referral.pending': 'قيد الانتظار',
  'linkFamilies.affiliate.referral.expired': 'منتهي الصلاحية',
  'linkFamilies.affiliate.copy': 'نسخ رابط الإحالة',
  'linkFamilies.affiliate.share': 'مشاركة رابط الإحالة',
  'linkFamilies.affiliate.delete': 'حذف رابط الإحالة',
  'linkFamilies.affiliate.delete.title': 'حذف رابط الإحالة هذا؟',
  'linkFamilies.affiliate.delete.body': 'لن يتيح بعد الآن التسجيل باسمك. يبقى المُحالون من طرفك لك.',
  'linkFamilies.affiliate.create.title': 'رابط إحالة جديد',
  'linkFamilies.affiliate.create.name': 'اسم الرابط',
  'linkFamilies.affiliate.create.name.placeholder': 'مثال: دعوة الأصدقاء',
  'linkFamilies.affiliate.create.name.invalid': 'امنح هذا الرابط اسمًا (100 حرف كحد أقصى).',
  'linkFamilies.affiliate.create.limit': 'تحديد عدد التسجيلات',
  'linkFamilies.affiliate.create.limit.caption': 'بعد ذلك، لا يسجّل الرابط أحدًا',
  'linkFamilies.affiliate.create.maxUses': 'الحد الأقصى لعدد التسجيلات',
  'linkFamilies.affiliate.create.maxUses.invalid': 'عدد صحيح بين 1 و100000.',
  'linkFamilies.affiliate.create.button': 'إنشاء رابط الإحالة',
  'linkFamilies.community.stats.communities': 'المجتمعات',
  'linkFamilies.community.stats.public': 'العامة',
  'linkFamilies.community.stats.members': 'الأعضاء',
  'linkFamilies.community.section': 'مجتمعاتي',
  'linkFamilies.community.role.admin': 'مسؤول',
  'linkFamilies.community.role.moderator': 'مشرف',
  'linkFamilies.community.private': 'خاص',
  'linkFamilies.community.public': 'عام',
  'linkFamilies.community.members.one': '{count} عضو',
  'linkFamilies.community.members.other': '{count} أعضاء',
  'linkFamilies.community.empty.title': 'لا يوجد مجتمع تديره',
  'linkFamilies.community.empty.subtitle': 'ستظهر هنا المجتمعات التي تديرها مع رابط المشاركة الخاص بها',
  'linkFamilies.community.empty.create': 'إنشاء مجتمع',
  'linkFamilies.community.back': 'العودة إلى روابط المجتمع',
  'linkFamilies.community.open': 'فتح المجتمع',
  'linkFamilies.community.fullLink': 'الرابط الكامل',
  'linkFamilies.community.role': 'دورك',
  'linkFamilies.community.visibility': 'الظهور',
} satisfies LinkFamiliesCatalog;

export default ar;
