import type { ExportCardCatalog } from '@/lib/i18n-export-card-catalog';

const pt = {
  'export.card.title': 'Exportar como imagem',
  'export.card.popular': 'Populares',
  'export.card.random': 'Aleatório',
  'export.card.palette': 'Cores',
  'export.card.typeface': 'Tipografia',
  'export.card.link': 'Ligação',
  'export.card.typeface.rond': 'Redonda',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Pena',
  'export.card.typeface.affiche': 'Cartaz',
  'export.card.typeface.futur': 'Futurista',
  'export.card.typeface.machine': 'Máquina de escrever',
  'export.card.typeface.marqueur': 'Marcador',
  'export.card.typeface.systeme': 'Sistema',
  'export.card.link.orbite': 'Órbita',
  'export.card.link.filet': 'Filete',
  'export.card.link.guillemets': 'Aspas',
  'export.card.link.fleche': 'Seta',
  'export.card.link.bulles': 'Balões',
  'export.card.link.fil': 'Fio',
  'export.card.link.silence': 'Silêncio',
  'export.card.option.anonymizeQuoted': 'Anonimizar a mensagem citada',
  'export.card.option.anonymizeReply': 'Anonimizar a resposta',
  'export.card.anonymous': 'Anónimo',
  'export.card.preview': 'Pré-visualização da imagem',
  'export.card.rendering': 'A preparar a imagem…',
  'export.card.save': 'Guardar',
  'export.card.share': 'Partilhar',
  'export.card.language': 'Idioma da mensagem',
  'export.card.language.asRead': 'Como eu leio',
  'export.card.truncated': 'Mensagem longa: o final é cortado na imagem.',
  'export.announce.gallery': 'Imagem guardada na galeria',
  'export.announce.shared': 'Imagem pronta',
  'export.announce.cancelled': 'Exportação cancelada',
  'export.announce.expired': 'Toque novamente para guardar',
  'export.announce.failed': 'Não foi possível criar a imagem',
  'export.announce.unavailable': 'Este dispositivo não consegue guardar a imagem',
  'export.card.options': 'Mostrar',
  'export.card.option.title': 'Título da conversa',
  'export.card.option.authors': 'Nomes dos autores',
  'export.card.option.date': 'Data',
  'export.card.default.save': 'Usar como formato predefinido',
  'export.card.default.current': 'Formato predefinido',
  'export.announce.defaultSaved': 'Formato predefinido guardado',
  'export.card.tab.styles': 'Estilos',
  'export.card.tab.palette': 'Fundo',
  'export.card.tab.typeface': 'Fonte',
  'export.card.tab.link': 'Ligação',
  'export.card.tab.details': 'Detalhes',
  'export.card.tab.language': 'Idioma',
  'export.card.part.header': 'Cabeçalho',
  'export.card.part.quote': 'Citação',
  'export.card.part.link': 'Ligação',
  'export.card.part.reply': 'Resposta',
  'export.card.part.background': 'Fundo',
  'export.card.hint': 'Toque numa parte do cartão para a ajustar',
  'export.card.gallery.open': 'Ver tudo',
  'export.card.gallery.title': 'Todos os estilos',
  'export.card.gallery.count': '{count} estilos',
  'export.card.gallery.close': 'Fechar a galeria',
  'export.card.gallery.search': 'Procurar um estilo',
  'export.card.gallery.placeholder': 'Pena, escuro, bolhas…',
  'export.card.gallery.empty': 'Nenhum estilo tem esse nome. Experimente uma cor, uma fonte ou «escuro».',
  'export.card.tone.all': 'Todos',
  'export.card.tone.dark': 'Escuro',
  'export.card.tone.light': 'Claro',
  'export.card.typeface.pairs': 'A fonte veste a citação e a resposta',
} satisfies ExportCardCatalog;

export default pt;
