import type { CallControlsCatalog } from '@/lib/i18n-call-controls-catalog';

const en = {
  'callControls.invite': 'Add',
  'callControls.invite.label': 'Add people to the call',
  'callControls.react': 'React',
  'callControls.react.label': 'Send a reaction',
  'callControls.react.palette': 'Reactions',
  'callControls.react.send': 'React with {emoji}',
  'callControls.react.from': '{name} reacted {emoji}',
  'callControls.react.mine': 'You reacted {emoji}',
  'callControls.people.title': 'Participants',
  'callControls.people.inCall': 'In the call',
  'callControls.people.add': 'Add people',
  'callControls.people.search': 'Search contacts',
  'callControls.people.empty': 'All your contacts are already in the call',
  'callControls.people.none': 'No contact matches',
  'callControls.people.invite': 'Invite',
  'callControls.people.inviteNamed': 'Invite {name}',
  'callControls.people.loading': 'Loading contacts…',
  'callControls.people.you': 'You',
  'callControls.close': 'Close',
  'callControls.ringing': 'Ringing…',
  'callControls.moderate.menu': 'Options for {name}',
  'callControls.mute': 'Mute microphone',
  'callControls.mute.done': 'Microphone muted',
  'callControls.remove': 'Remove from call',
  'callControls.remove.confirm': 'Remove {name} from the call?',
  'callControls.remove.detail': 'The call will end right away for {name}.',
  'callControls.remove.do': 'Remove',
  'callControls.cancel': 'Cancel',
  'callControls.mutedBy': '{name} muted your microphone',
  'callControls.someone': 'A participant',
  'callControls.incomingInvite': '{name} is inviting you to a group call',
  'callControls.error.invite': 'Couldn’t invite {name}',
  'callControls.error.mute': 'Couldn’t mute {name}',
  'callControls.error.remove': 'Couldn’t remove {name}',
  'callControls.error.notContact': '{name} is not in your contacts',
  'callControls.error.alreadyIn': '{name} is already in the call',
  'callControls.error.full': 'The call is full',
  'callControls.error.rateLimited': 'Too many attempts: try again in a moment',
  'callControls.error.denied': 'You don’t have this right in this call',
  'callControls.error.notActive': 'The call is no longer active',
  'callControls.error.gone': '{name} is no longer in the call',
  'callControls.record.title': 'What do you want to record?',
  'callControls.record.audio': 'Audio only',
  'callControls.record.audioDetail': 'Everyone’s voices',
  'callControls.record.video': 'Audio and video',
  'callControls.record.videoDetail': 'Visible video and voices',
  'callControls.capture': 'Capture',
  'callControls.capture.label': 'Capture the call',
  'callControls.back': 'Back',
  'callControls.journal': 'Transcript',
  'callControls.journal.label': 'Open the call transcript',
  'callControls.journal.live': 'Back to live',
  'callControls.journal.empty': 'Nothing transcribed yet. Turn on captions: every sentence spoken appears here with its translation, for the whole call.',
  'callControls.journal.original': 'Original',
  'callControls.camera.options': 'My camera options',
  'callControls.selfTile.small': 'My thumbnail: small',
  'callControls.selfTile.medium': 'My thumbnail: medium',
  'callControls.selfTile.large': 'My thumbnail: large',
} satisfies CallControlsCatalog;

export default en;
