/**
 * LA QUALITÉ D'UN APPEL (#8047) — tranche du catalogue, RÉPANDUE par
 * `catalog-de.ts` comme `catalog-de-call-screen.ts` : l'indicateur et le
 * détail de qualité, les pastilles de survie de la vidéo et les alertes d'un
 * pair (`call-quality-indicator.tsx`, `call-screen.tsx`).
 */
const deCallQuality = {
  'call.quality.indicator': 'Anrufqualität: {level}',
  'call.quality.level.excellent': 'ausgezeichnet',
  'call.quality.level.good': 'gut',
  'call.quality.level.fair': 'mittel',
  'call.quality.level.poor': 'schwach',
  'call.quality.detail': 'Anrufqualität',
  'call.quality.loss': 'Paketverlust',
  'call.quality.latency': 'Latenz',
  'call.quality.jitter': 'Jitter',
  'call.quality.audioRate': 'Audio-Bitrate',
  'call.quality.videoRate': 'Video-Bitrate',
  'call.quality.close': 'Details zur Anrufqualität schließen',
  'call.quality.profile': 'Netzwerk',
  'call.quality.profile.wifi': 'WLAN',
  'call.quality.profile.cellular': 'Mobile Daten',
  'call.quality.profile.economy': 'Datensparmodus',
  'call.quality.audioCap': 'Audio-Obergrenze',
  'call.quality.videoCap': 'Video-Obergrenze',
  'callJournal.title': 'Qualität und Netzwerk',
  'callJournal.chronology': 'Verlauf',
  'callJournal.summary.worstLevel': 'Niedrigste Qualität',
  'callJournal.summary.maxLoss': 'Maximaler Paketverlust',
  'callJournal.summary.maxRtt': 'Maximale Latenz',
  'callJournal.summary.reconnections': 'Neuverbindungen',
  'callJournal.summary.path': 'Medienweg',
  'callJournal.path.direct': 'Direkt',
  'callJournal.path.relay': 'Über ein Relay',
  'callJournal.summary.end': 'Ende',
  'callJournal.end.local': 'Aufgelegt',
  'callJournal.end.remote': 'Von der Gegenseite beendet',
  'callJournal.end.rejected': 'Abgelehnt',
  'callJournal.end.missed': 'Unbeantwortet',
  'callJournal.end.connectionLost': 'Verbindung verloren',
  'callJournal.end.failed': 'Verbindung fehlgeschlagen',
  'callJournal.end.busy': 'Besetzt',
  'callJournal.end.permission': 'Mikrofon oder Kamera verweigert',
  'callJournal.end.removed': 'Aus dem Anruf entfernt',
  'callJournal.event.connecting': 'Verbindung wird hergestellt',
  'callJournal.event.connected': 'Verbunden',
  'callJournal.event.reconnecting': 'Neuverbindung',
  'callJournal.event.ended': 'Ende: {reason}',
  'callJournal.event.link': '{name}: {state}',
  'callJournal.link.connecting': 'verbindet',
  'callJournal.link.connected': 'verbunden',
  'callJournal.link.reconnecting': 'verbindet neu',
  'callJournal.event.quality': 'Qualität {level}',
  'callJournal.event.frozen': 'Video verlangsamt (schwaches Netz)',
  'callJournal.event.suspended': 'Video pausiert, Audio läuft weiter',
  'callJournal.event.resumed': 'Video wiederhergestellt',
  'callJournal.event.profile': 'Netzwerk: {profile} · Stimme {bitrate}',
  'callJournal.event.relay': 'Über den Server weitergeleitet',
  'callJournal.event.direct': 'Direkte Verbindung',
  'call.video.frozen': 'Schwaches Netz: Ihr Video ist verlangsamt',
  'call.video.suspended': 'Schwaches Netz: Ihr Video ist pausiert, der Ton läuft weiter',
  'call.alert.weakNetwork': 'Die Verbindung von {name} ist instabil',
  'call.alert.capturing': '{name} nimmt den Anrufbildschirm auf',
} as const;

export default deCallQuality;
