/**
 * LE STUDIO D'UN APPEL VIDÉO, FRANÇAIS (#8551, #8552, #8625) — la SOURCE des clés :
 * les effets de visage, les montages, les ambiances des cadres (#8742 — les noms
 * de motif, eux, sont des noms propres et ne se traduisent pas), la photo et la
 * vidéo. Les six autres langues
 * portent exactement ces clés (`satisfies CallStudioCatalog`,
 * `i18n-call-studio-catalog.test.ts`).
 */
const fr = {
  'callStudio.effects.color': 'Couleur',
  'callStudio.effects.settings': 'Réglages',
  'callStudio.face.none': 'Aucun',
  'callStudio.face.smoothing': 'Lissage de peau',
  'callStudio.face.toad': 'Crapaud',
  'callStudio.face.angel': 'Ange',
  'callStudio.face.demon': 'Démon',
  'callStudio.face.volcano': 'Éruption',
  'callStudio.montage.screen': 'Plein écran',
  'callStudio.montage.grid': 'Mosaïque',
  'callStudio.montage.strip': 'Photomaton',
  'callStudio.montage.polaroid': 'Polaroïd',
  'callStudio.montage.magazine': 'Magazine',
  'callStudio.montage.comic': 'BD',
  'callStudio.montage.heart': 'Cœur',
  'callStudio.capture.preview': 'Aperçu du montage {style}',
  'callStudio.capture.faces': 'Chaque visage',
  'callStudio.capture.facesLabel': 'Enregistrer chaque visage séparément',
  'callStudio.capture.saved': 'Capture enregistrée',
  'callStudio.capture.faceSaved': '1 visage enregistré',
  'callStudio.capture.facesSaved': '{count} visages enregistrés',
  'callStudio.capture.failed': 'La capture n’a pas pu être enregistrée',
  'callStudio.capture.cancelled': 'Enregistrement annulé',
  'callStudio.capture.empty': 'Rien à capturer : aucune image n’est affichée',
  'callStudio.capture.busy': 'Capture en cours…',
  'callStudio.capture.bubble': 'Quel appel !',
  'callStudio.montage.cover': 'Couverture',
  'callStudio.montage.gold': 'Doré',
  'callStudio.montage.redcarpet': 'Tapis rouge',
  'callStudio.montage.film': 'Pellicule',
  'callStudio.montage.neon': 'Néon',
  'callStudio.montage.noir': 'Noir et blanc',
  'callStudio.cover.line1': 'L’appel de l’année',
  'callStudio.cover.line2': 'Tous réunis, enfin',
  'callStudio.cover.line3': 'Exclusif',
  'callStudio.mode.effects': 'Effets de ma vidéo',
  'callStudio.mode.montage': 'Capturer l’appel',
  'callStudio.mode.quit': 'Quitter',
  'callStudio.mode.quitEffects': 'Quitter sans garder ces changements',
  'callStudio.mode.validateLabel': 'Garder cet effet et revenir à l’appel',
  'callStudio.mode.face': 'Visage',
  'callStudio.mode.categories': 'Catégorie',
  'callStudio.mode.pickEffect': 'Choisir un effet',
  'callStudio.mode.pickMontage': 'Choisir un montage',
  'callStudio.mode.settingsLabel': 'Afficher les réglages (luminosité, flou)',
  'callStudio.capture.hint': 'Deux tapes : photo · Appui long : vidéo',
  'callStudio.capture.gestures': 'Deux tapes, ou Entrée : une photo. Appui long : une vidéo, avec le son.',
  'callStudio.record.start': 'Filmer, avec le son',
  'callStudio.record.stop': 'Arrêter la vidéo et l’enregistrer',
  'callStudio.record.saved': 'Vidéo enregistrée',
  'callStudio.record.failed': 'La vidéo n’a pas pu être enregistrée',
  'callStudio.record.unsupported': 'Ce navigateur ne sait pas filmer l’appel',
  'callStudio.record.clock': 'Vidéo en cours, {time}',
  'callStudio.companions.label': 'Participants à l’appel',
  'callStudio.companions.more': '{count} autres participants',
  'callStudio.companions.move': 'Changer de côté',
  'callStudio.frames.moods': 'Ambiances',
  'callStudio.frames.mood.classics': 'Classiques',
  'callStudio.frames.mood.signature': 'Signature',
  'callStudio.frames.mood.distingue': 'Distingué',
  'callStudio.frames.mood.elegant': 'Élégant',
  'callStudio.frames.mood.jovial': 'Jovial',
  'callStudio.frames.mood.deconnecte': 'Déconnecté',
  'callStudio.frames.mood.corporate': 'Corporate',
  'callStudio.frames.mood.fantastique': 'Fantastique',
  'callStudio.frames.mood.futuriste': 'Futuriste',
  'callStudio.frames.mood.glauque': 'Glauque',
  'callStudio.frames.mood.hors-norme': 'Hors norme',
  'callStudio.frames.mood.morbide': 'Morbide',
  'callStudio.frames.mood.feerique': 'Féerique',
  'callStudio.mode.pickFrame': 'Choisir un cadre',
  'callStudio.capture.framePreview': 'Aperçu du cadre {name}',
} as const;

export default fr;
