import type { OnboardingCatalog } from '@/lib/i18n-onboarding-catalog';

const ar = {
  'onboarding.title': 'مرحبًا بك في Meeshy',
  'onboarding.skipAll': 'تخطَّ الكل',
  'onboarding.later': 'لاحقًا',
  'onboarding.continue': 'متابعة',
  'onboarding.progress': 'الخطوة {current} من {total}',
  'onboarding.offline': 'متاح عندما تكون متصلًا',
  'onboarding.points.gauge': '{points} / {target} نقاط لمستواك الأول',
  'onboarding.points.level': 'بلغت المستوى 1!',
  'onboarding.points.gained': '+{points}',
  'onboarding.points.announce': 'ربحت {points} نقطة.',

  'onboarding.languages.title': 'لغتك، عالمك',
  'onboarding.languages.body': 'هنا يكتب كلٌّ بلغته، وأنت تقرأ كل شيء بلغتك.',
  'onboarding.languages.demo.from': 'Hola, ¿qué tal?',
  'onboarding.languages.demo.fromCode': 'es',
  'onboarding.languages.demo.to': 'مرحبًا، كيف الحال؟',
  'onboarding.languages.primary': 'لغتك الأساسية',
  'onboarding.languages.secondary': 'لغة ثانية؟ (اختياري)',
  'onboarding.languages.change': 'تغيير',
  'onboarding.languages.pick': 'اختر لغتك الأساسية',
  'onboarding.languages.confirm': 'هذه لغتي',
  'onboarding.languages.failed': 'لم تُحفَظ لغتك. حاول مجددًا.',

  'onboarding.global.title': 'قل مرحبًا للعالم',
  'onboarding.global.body': 'Meeshy Global هو الصالون الذي يلتقي فيه الجميع. ألقِ التحية بلا ضغط.',
  'onboarding.global.field': 'تحيتك، قابلة للتعديل',
  'onboarding.global.shuffle': 'فكرة أخرى',
  'onboarding.global.send': 'إرسال',
  'onboarding.global.sending': 'جارٍ الإرسال…',
  'onboarding.global.sent': 'أُرسلت التحية!',
  'onboarding.global.failed': 'لم تُرسَل تحيتك. حاول مجددًا.',
  'onboarding.global.unavailable': 'تعذّر الوصول إلى Meeshy Global حاليًا.',
  'onboarding.global.badge': 'شارة «الرسالة الأولى»',
  'onboarding.global.streak': 'السلسلة: يوم واحد 🔥',
  'onboarding.global.reward': '+14 نقطة عند الإرسال',
  'onboarding.global.template.1': 'مرحبًا بالجميع! أنا {name}، أتحدث {languages}. من يعيش هنا قرب [[البحر]]؟',
  'onboarding.global.template.2': 'أهلًا! {name} هنا 👋 أستمع هذه الأيام إلى [[الراب]] بلا توقف. وأنتم؟',
  'onboarding.global.template.3': 'مرحبًا! اسمي {name}. طبقي المفضل: [[المعكرونة]]. وأنتم؟',
  'onboarding.global.template.4': 'أهلًا! {name}، وصلت للتو. أبحث عن أشخاص يحبون [[كرة القدم]]!',
  'onboarding.global.template.5': 'هاي! أنا {name}. فرحتي الصغيرة اليوم: [[غروب الشمس]].',
  'onboarding.global.template.6': 'مرحبًا! {name} هنا، أتحدث {languages}. أودّ تعلّم [[الإسبانية]]، هل من نصائح؟',
  'onboarding.global.template.7': 'مرحبًا أيها العالم 🌍 أنا {name}. شغفي هذه الأيام: [[التصوير]]. من يشاركني؟',
  'onboarding.global.template.8': 'يو! وصل {name} للتو. الطقس عندي اليوم [[مشمس جدًا]]. وعندكم؟',

  'onboarding.story.title': 'أظهِر نفسك',
  'onboarding.story.body': 'الأصدقاء يأتون حين تُظهر من أنت. صورة وكلمة: هذه قصة، وتختفي بعد 24 ساعة.',
  'onboarding.story.create': 'أنشئ قصتي',
  'onboarding.story.audience.public': 'مرئية للجميع. يمكنك التغيير قبل النشر.',
  'onboarding.story.audience.friends': 'مرئية لأصدقائك. يمكنك التغيير قبل النشر.',
  'onboarding.story.reward': '+10 نقاط عند النشر',
  'onboarding.story.done': 'نُشرت القصة!',

  'onboarding.friends.title': 'اعثر على جماعتك',
  'onboarding.friends.body': 'أضف 3 أشخاص يشبهونك. حين يقبلون، يربح كلٌّ منكما +7.',
  'onboarding.friends.add': 'إضافة',
  'onboarding.friends.addNamed': 'إضافة {name}',
  'onboarding.friends.added': 'أُرسل',
  'onboarding.friends.speaks': 'يتحدث {languages}',
  'onboarding.friends.reward': '+7 لكل منكما عند القبول',
  'onboarding.friends.count': '{count} / 3 طلبات',
  'onboarding.friends.empty': 'لا أحد نقترحه عليك الآن. سيعرض لك تبويب «اكتشف» أشخاصًا قريبًا.',
  'onboarding.friends.failed': 'لم يُرسَل الطلب. حاول مجددًا.',

  'onboarding.notifications.title': 'نخبرك حين يحدث شيء',
  'onboarding.notifications.body': 'أحدهم على وشك الرد عليك. أتريد أن تعرف فورًا؟',
  'onboarding.notifications.yes': 'نعم، أخبرني',
  'onboarding.notifications.no': 'ليس الآن',

  'onboarding.recap.title': 'أحسنت!',
  'onboarding.recap.calm': 'كل شيء جاهز. يمكنك فعل ذلك متى شئت.',
  'onboarding.recap.points': '+{points} نقطة',
  'onboarding.recap.level': 'المستوى 1',
  'onboarding.recap.streak': 'السلسلة 1 🔥',
  'onboarding.recap.badges': 'الشارات: {count}',
  'onboarding.recap.friends': 'طلبات في الطريق: {count}',
  'onboarding.recap.tomorrow': 'غدًا يمكن أن تصل سلسلتك إلى 2.',
  'onboarding.recap.explore': 'تابع الاستكشاف',
  'onboarding.recap.done': 'يكفي لهذا اليوم',
} satisfies OnboardingCatalog;

export default ar;
