/**
 * LES TROIS AUTRES FAMILLES DE « MES LIENS », FRANÇAIS (#6408, #6409, #6410) —
 * la SOURCE des clés `linkFamilies.*` : listes, détails et créations des liens
 * de suivi, de parrainage et de communauté. Mots repris d'iOS
 * (`tracking.links.*`, `affiliate.*`, `community.links.*`). Chargé avec ces
 * écrans seulement (`i18n-link-families-catalog`), jamais au démarrage ; les
 * six autres langues portent exactement ces clés (`satisfies LinkFamiliesCatalog`).
 */
const fr = {
  'links.hub.tracking.title': 'Liens de suivi',
  'links.hub.tracking.description': 'Suivez les performances de vos liens de référence',
  'links.hub.tracking.create': 'Créer un lien de suivi',
  'links.hub.community.title': 'Liens communauté',
  'links.hub.community.description': 'Gérez les liens d’invitation vers vos communautés',
  'links.hub.affiliate.title': 'Liens de parrainage',
  'links.hub.affiliate.description': 'Invitez votre réseau sur Meeshy et suivez vos inscrits',
  'links.hub.affiliate.create': 'Créer un lien de parrainage',

  'linkFamilies.delete': 'Supprimer',
  'linkFamilies.cancel': 'Annuler',
  'linkFamilies.noData': 'Aucune donnée',
  'linkFamilies.announce.deleted': 'Lien supprimé',
  'linkFamilies.announce.deleteFailed': 'Impossible de supprimer ce lien',
  'linkFamilies.create.inprogress': 'Création en cours…',
  'linkFamilies.create.error.offline': 'Hors ligne : le lien n’a pas été créé.',
  'linkFamilies.create.error.default': 'Le lien n’a pas pu être créé. Réessayez.',
  'linkFamilies.tracking.stats.links': 'Liens',
  'linkFamilies.tracking.stats.clicks': 'Clics',
  'linkFamilies.tracking.stats.uniques': 'Uniques',
  'linkFamilies.tracking.stats.active': 'Actifs',
  'linkFamilies.tracking.clicks.one': '{count} clic',
  'linkFamilies.tracking.clicks.other': '{count} clics',
  'linkFamilies.tracking.uniques.one': '{count} unique',
  'linkFamilies.tracking.uniques.other': '{count} uniques',
  'linkFamilies.tracking.copy': 'Copier le lien de suivi',
  'linkFamilies.tracking.empty.title': 'Aucun lien de suivi',
  'linkFamilies.tracking.empty.subtitle': 'Créez un lien pour suivre vos clics et vos campagnes',
  'linkFamilies.tracking.back': 'Revenir aux liens de suivi',
  'linkFamilies.tracking.totalClicks': 'Total des clics',
  'linkFamilies.tracking.uniqueClicks': 'Clics uniques',
  'linkFamilies.tracking.lastClick': 'Dernier clic : {date}',
  'linkFamilies.tracking.noClick': 'Aucun clic pour l’instant',
  'linkFamilies.tracking.countries': 'Pays',
  'linkFamilies.tracking.devices': 'Appareils',
  'linkFamilies.tracking.browsers': 'Navigateurs',
  'linkFamilies.tracking.social': 'Sources sociales',
  'linkFamilies.tracking.recent': 'Derniers clics',
  'linkFamilies.tracking.unknownPlace': 'Lieu inconnu',
  'linkFamilies.tracking.redirect.confirmed': 'Redirection confirmée',
  'linkFamilies.tracking.redirect.failed': 'Redirection échouée',
  'linkFamilies.tracking.redirect.pending': 'Redirection en attente',
  'linkFamilies.tracking.device.mobile': 'Mobile',
  'linkFamilies.tracking.device.desktop': 'Ordinateur',
  'linkFamilies.tracking.device.tablet': 'Tablette',
  'linkFamilies.tracking.utm': 'Configuration UTM',
  'linkFamilies.tracking.campaign': 'Campagne',
  'linkFamilies.tracking.source': 'Source',
  'linkFamilies.tracking.medium': 'Moyen',
  'linkFamilies.tracking.destination': 'URL de destination',
  'linkFamilies.tracking.delete.title': 'Supprimer ce lien de suivi ?',
  'linkFamilies.tracking.delete.body': 'Le lien cessera de rediriger et ses statistiques seront perdues.',
  'linkFamilies.tracking.create.title': 'Nouveau lien de suivi',
  'linkFamilies.tracking.create.section.destination': 'Destination',
  'linkFamilies.tracking.create.url': 'URL de destination',
  'linkFamilies.tracking.create.url.placeholder': 'https://exemple.com/page',
  'linkFamilies.tracking.create.url.invalid': 'Saisissez une adresse web valide.',
  'linkFamilies.tracking.create.name': 'Nom interne (facultatif)',
  'linkFamilies.tracking.create.name.placeholder': 'ex. : Campagne de rentrée',
  'linkFamilies.tracking.create.name.invalid': '32 caractères au plus.',
  'linkFamilies.tracking.create.section.utm': 'Paramètres UTM',
  'linkFamilies.tracking.create.section.utm.subtitle': 'Pour savoir d’où viennent vos clics',
  'linkFamilies.tracking.create.campaign.placeholder': 'ex. : rentree',
  'linkFamilies.tracking.create.source.placeholder': 'ex. : instagram',
  'linkFamilies.tracking.create.medium.placeholder': 'ex. : social',
  'linkFamilies.tracking.create.section.token': 'Jeton personnalisé',
  'linkFamilies.tracking.create.token': 'Jeton (facultatif)',
  'linkFamilies.tracking.create.token.placeholder': 'ex. : rentree26',
  'linkFamilies.tracking.create.token.help': 'Laissez vide pour un jeton aléatoire.',
  'linkFamilies.tracking.create.token.invalid': '5 à 50 caractères : lettres, chiffres, « - » ou « _ », sans tiret au début ni à la fin.',
  'linkFamilies.tracking.create.token.taken': 'Ce jeton est déjà pris. Choisissez-en un autre.',
  'linkFamilies.tracking.create.preview': 'Votre lien : {url}',
  'linkFamilies.tracking.create.button': 'Créer le lien de suivi',
  'linkFamilies.affiliate.title': 'Parrainage',
  'linkFamilies.affiliate.stats.links': 'Liens',
  'linkFamilies.affiliate.stats.signups': 'Inscrits',
  'linkFamilies.affiliate.stats.pending': 'En attente',
  'linkFamilies.affiliate.section.referrals': 'Mes filleuls',
  'linkFamilies.affiliate.signups.one': '{count} inscrit',
  'linkFamilies.affiliate.signups.other': '{count} inscrits',
  'linkFamilies.affiliate.uses': '{used} sur {max}',
  'linkFamilies.affiliate.empty.title': 'Aucun lien de parrainage',
  'linkFamilies.affiliate.empty.subtitle': 'Créez un lien pour inviter vos amis sur Meeshy',
  'linkFamilies.affiliate.referrals.empty': 'Personne ne s’est encore inscrit avec vos liens.',
  'linkFamilies.affiliate.referral.completed': 'Inscrit',
  'linkFamilies.affiliate.referral.pending': 'En attente',
  'linkFamilies.affiliate.referral.expired': 'Expiré',
  'linkFamilies.affiliate.copy': 'Copier le lien de parrainage',
  'linkFamilies.affiliate.share': 'Partager le lien de parrainage',
  'linkFamilies.affiliate.delete': 'Supprimer le lien de parrainage',
  'linkFamilies.affiliate.delete.title': 'Supprimer ce lien de parrainage ?',
  'linkFamilies.affiliate.delete.body': 'Il ne permettra plus de s’inscrire en votre nom. Vos filleuls restent les vôtres.',
  'linkFamilies.affiliate.create.title': 'Nouveau lien de parrainage',
  'linkFamilies.affiliate.create.name': 'Nom du lien',
  'linkFamilies.affiliate.create.name.placeholder': 'ex. : Invitation amis',
  'linkFamilies.affiliate.create.name.invalid': 'Donnez un nom à ce lien (100 caractères au plus).',
  'linkFamilies.affiliate.create.limit': 'Limiter les inscriptions',
  'linkFamilies.affiliate.create.limit.caption': 'Au-delà, le lien n’inscrit plus personne',
  'linkFamilies.affiliate.create.maxUses': 'Nombre maximum d’inscriptions',
  'linkFamilies.affiliate.create.maxUses.invalid': 'Un nombre entier entre 1 et 100 000.',
  'linkFamilies.affiliate.create.button': 'Créer le lien de parrainage',
  'linkFamilies.community.stats.communities': 'Communautés',
  'linkFamilies.community.stats.public': 'Publiques',
  'linkFamilies.community.stats.members': 'Membres',
  'linkFamilies.community.section': 'Mes communautés',
  'linkFamilies.community.role.admin': 'Administrateur',
  'linkFamilies.community.role.moderator': 'Modérateur',
  'linkFamilies.community.private': 'Privée',
  'linkFamilies.community.public': 'Publique',
  'linkFamilies.community.members.one': '{count} membre',
  'linkFamilies.community.members.other': '{count} membres',
  'linkFamilies.community.empty.title': 'Aucune communauté administrée',
  'linkFamilies.community.empty.subtitle': 'Les communautés que vous gérez apparaîtront ici avec leur lien de partage',
  'linkFamilies.community.empty.create': 'Créer une communauté',
  'linkFamilies.community.back': 'Revenir aux liens communauté',
  'linkFamilies.community.open': 'Ouvrir la communauté',
  'linkFamilies.community.fullLink': 'Lien complet',
  'linkFamilies.community.role': 'Votre rôle',
  'linkFamilies.community.visibility': 'Visibilité',
} as const;

export default fr;
