import kitFr from './admin/kit-fr';
import dashboardFr from './admin/dashboard-fr';
import statistiquesFr from './admin/statistiques-fr';
import moderationFr from './admin/moderation-fr';
import contenusFr from './admin/contenus-fr';
import liensFr from './admin/liens-fr';
import diffusionsFr from './admin/diffusions-fr';
import classementSupervisionFr from './admin/classement-supervision-fr';
import auditReglagesFr from './admin/audit-reglages-fr';
import personnesFr from './admin/personnes-fr';
import conversationsAgentFr from './admin/conversations-agent-fr';

/**
 * LE CATALOGUE D'INTERFACE D'ADMINISTRATION FRANÇAIS (#6871, #6834) — la
 * SOURCE DES CLÉS `admin.*`, sorties de `catalog-fr.ts` parce qu'un lecteur
 * qui n'ouvre jamais `/adm` les payait quand même : 84 clés sur 629, 13 % du
 * poids que TOUT lecteur téléchargeait. Chargé SEULEMENT à l'entrée d'un
 * écran d'administration (`i18n-admin-catalog.ts`), jamais au démarrage.
 *
 * Les six autres langues portent exactement ces clés : `satisfies
 * AdminInterfaceCatalog` le vérifie à la compilation,
 * `i18n-admin-catalog.test.ts` le mesure à l'exécution — même discipline que
 * `catalog-fr.ts` pour le catalogue commun. `admin.title` seul reste dans ce
 * dernier : la rangée des Réglages et le menu flottant le lisent sans jamais
 * entrer dans l'administration.
 */
const fr = {
  'admin.role': 'Votre rôle : {role}',
  'admin.denied.title': 'Espace réservé',
  'admin.denied.message': 'Cet espace demande un droit d\'administration.',
  'admin.nav.dashboard': 'Tableau de bord',
  'admin.nav.users': 'Comptes',
  'admin.nav.audit': 'Journal d’audit',
  'admin.nav.analytics': 'Statistiques',
  'admin.nav.trackingLinks': 'Liens de suivi',
  'admin.nav.ranking': 'Classement',
  'admin.nav.broadcasts': 'Diffusions',
  'admin.nav.settings': 'Réglages',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Supervision',
  'admin.nav.invitations': 'Demandes de contact',
  'admin.nav.communities': 'Communautés',
  'admin.nav.shareLinks': 'Liens de partage',
  'admin.nav.posts': 'Publications',
  'admin.nav.reports': 'Signalements',
  'admin.nav.languages': 'Langues et traductions',
  'admin.nav.dashboard.hint': 'L’état de la plateforme en un coup d’œil',
  'admin.nav.users.hint': 'Tous les comptes, leurs droits et leur sécurité',
  'admin.nav.anonymous.hint': 'Les invités entrés par un lien, sans compte',
  'admin.nav.invitations.hint': 'Les demandes d’ami envoyées entre membres',
  'admin.nav.conversations.hint': 'Les conversations de la plateforme et leur lecture encadrée',
  'admin.nav.communities.hint': 'Les communautés, leurs équipes et leurs conversations',
  'admin.nav.shareLinks.hint': 'Les liens qui ouvrent une conversation',
  'admin.nav.posts.hint': 'Publications, stories, reels et statuts',
  'admin.nav.reports.hint': 'Les signalements à examiner et à traiter',
  'admin.nav.audit.hint': 'La trace de chaque geste d’administration',
  'admin.nav.analytics.hint': 'Activité, messages et appels dans le temps',
  'admin.nav.ranking.hint': 'Les membres, conversations et liens les plus actifs',
  'admin.nav.trackingLinks.hint': 'Les campagnes et leurs clics',
  'admin.nav.broadcasts.hint': 'Écrire à tous les comptes, par e-mail ou dans l’application',
  'admin.nav.monitoring.hint': 'La santé des services et l’usage des routes',
  'admin.nav.languages.hint': 'La santé du Prisme : langues et paires traduites',
  'admin.nav.agent.hint': 'Piloter l’agent de conversation',
  'admin.nav.settings.hint': 'Votre accès et les préférences de l’espace',
  'admin.users.search': 'Rechercher un compte',
  'admin.users.count': '{count} compte(s)',
  'admin.users.unavailable': 'Liste indisponible pour le moment.',
  'admin.users.previous': 'Précédents',
  'admin.users.next': 'Suivants',
  'admin.user.title': 'Membre',
  'admin.user.unavailable': 'Fiche indisponible pour le moment.',
  'admin.user.identity': 'Identité',
  'admin.user.created': 'Inscrit le',
  'admin.user.lastActive': 'Dernière activité',
  'admin.user.twoFactor': 'Second facteur',
  'admin.user.role': 'Rôle',
  'admin.edit.displayName': 'Nom affiché',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Compte actif',
  'admin.edit.save': 'Enregistrer',
  'admin.edit.reason': 'Motif (facultatif)',
  'admin.edit.warnRole': 'Changer le rôle modifie ses droits.',
  'admin.edit.warnDeactivate': 'Désactiver ferme ses sessions ouvertes.',
  'admin.edit.confirm': 'Confirmer',
  'admin.edit.saved': 'Modifications enregistrées',
  'admin.edit.failed': 'Échec de l’enregistrement',
  'admin.password.title': 'Réinitialiser le mot de passe',
  'admin.password.warn': 'Cette action ferme toutes ses sessions ouvertes.',
  'admin.password.generated': 'Copiez-le maintenant : il ne sera plus affiché.',
  'admin.password.copy': 'Copier',
  'admin.password.copied': 'Copié',
  'admin.password.apply': 'Réinitialiser',
  'admin.password.done': 'Mot de passe réinitialisé',
  'admin.password.failed': 'Échec de la réinitialisation',
  'admin.password.level': 'Niveau',
  'admin.password.level.simple': 'Simple',
  'admin.password.level.easy': 'Facile',
  'admin.password.level.medium': 'Moyen',
  'admin.password.level.hard': 'Difficile',
  'admin.password.field': 'Mot de passe',
  'admin.password.editable': 'Choisissez un niveau ou saisissez le vôtre : c’est ce qui est affiché qui sera appliqué.',
  'admin.password.loading': 'Préparation des propositions…',
  'admin.password.proposals.failed': 'Les propositions n’ont pas pu être chargées : saisissez un mot de passe.',
  'admin.password.regenerate': 'Autre proposition',
  'admin.password.refused': 'Refusé : {reason}',
  'admin.ban.open': 'Bannir',
  'admin.ban.title': 'Bannir ce membre',
  'admin.ban.reason': 'Motif (obligatoire)',
  'admin.ban.permanent': 'Bannissement permanent',
  'admin.ban.until': 'Jusqu’au',
  'admin.ban.apply': 'Bannir',
  'admin.ban.lift': 'Lever',
  'admin.ban.active': 'en vigueur',
  'admin.ban.expired': 'expiré',
  'admin.ban.lifted': 'levé',
  'admin.ban.none': 'Aucun bannissement',
  'admin.ban.done': 'Bannissement enregistré',
  'admin.ban.failed': 'Échec du bannissement',
  'admin.media.title': 'Médias',
  'admin.media.empty': 'Aucun média',
  'admin.media.protected': 'protégé',
  'admin.media.fromPost': 'publication',
  'admin.media.fromMessage': 'message',
  'admin.conv.title': 'Conversations',
  'admin.conv.empty': 'Aucune conversation',
  'admin.conv.members': '{count} membres',
  'admin.nav.conversations': 'Conversations',
  'admin.convList.unavailable': 'Liste indisponible pour le moment.',
  'admin.convDetail.title': "Lecture d'une conversation",
  'admin.convDetail.reasonLabel': 'Motif de la lecture',
  'admin.convDetail.reasonHint': 'Dix caractères minimum, consigné avec votre nom.',
  'admin.convDetail.read': 'Lire la conversation',
  'admin.convDetail.empty': 'Aucun message',
  'admin.convDetail.memberPrism': 'Lu dans le prisme du membre : {languages}',
  /* LE PILOTAGE DE L'AGENT (#6733). `admin.agent.effect` est la clé la plus
     importante du groupe : elle DIT ce que la relance fait vraiment — refaire
     l'analyse ET, par `strategist → generator → qualityGate`, publier un
     message dans la vraie conversation. Elle est rendue à côté du bouton, et
     les sept langues la portent (`admin-agent.test.tsx` vérifie que chacune
     nomme la publication, et qu'aucun libellé de bouton ne dit « analyse »).

     Les seconds segments sont COURTS (`effect`, `done`, `failed`, `down`) comme
     ceux de leurs voisins (`admin.ban.done`, `admin.password.failed`) : un nom
     de clé est payé SEPT fois dans le chunk des catalogues, et ce groupe a
     été ramené de 28 à 15 clés pour tenir sous `interface_catalogs_admin`
     (11 Ko). Ce qui manquait à l'appel a été EMPRUNTÉ plutôt que redit —
     `admin.counters.title`, `admin.counters.messages`,
     `admin.convList.unavailable`, `admin.user.enabled`,
     `admin.users.inactive`. */
  'admin.agent.title': 'Pilotage de l’agent',
  'admin.agent.denied': 'Ce pilotage demande un droit dédié.',
  'admin.agent.users': 'Membres pilotés',
  'admin.agent.tracked': 'Conversations suivies',
  'admin.offline': 'Hors ligne.',
  'admin.agent.scan': 'Scan en cours : {node}',
  'admin.agent.relaunch': 'Relancer l’agent',
  'admin.agent.effect': 'Refait l’analyse et peut publier un message.',
  'admin.agent.done': 'Relance demandée',
  'admin.agent.failed': 'Refusé',
  'admin.agent.stop': 'Arrêter le scan',
  'admin.agent.halted': 'Scan arrêté',
  'admin.agent.down': 'Service agent injoignable.',
  'admin.agent.logs': 'Journal des scans',
  'admin.nav.anonymous': 'Anonymes',
  'admin.shell.menu': 'Menu d\'administration',
  'admin.shell.fold': 'Replier le menu',
  'admin.shell.unfold': 'Déplier le menu',
  'admin.shell.open': 'Ouvrir le menu',
  'admin.shell.close': 'Fermer le menu',
  'admin.shell.backToApp': 'Retour à l\'application',
  'admin.list.all': 'Tous',
  'admin.list.yes': 'Oui',
  'admin.list.no': 'Non',
  'admin.list.reset': 'Réinitialiser',
  'admin.list.pageSize': 'Par page',
  'admin.list.range': '{from}–{to} sur {total}',
  'admin.list.sortBy': 'Trier par {column}',
  'admin.col.member': 'Membre',
  'admin.col.email': 'E-mail',
  'admin.col.role': 'Rôle',
  'admin.col.status': 'État',
  'admin.col.created': 'Inscription',
  'admin.col.lastActive': 'Dernière activité',
  'admin.col.joined': 'Arrivée',
  'admin.col.language': 'Langue',
  'admin.col.conversation': 'Conversation',
  'admin.col.messages': 'Messages',
  'admin.col.name': 'Nom',
  'admin.filter.active': 'Actifs',
  'admin.filter.inactive': 'Désactivés',
  'admin.filter.emailVerified': 'E-mail vérifié',
  'admin.filter.twoFactor': 'Double authentification',
  'admin.anonymous.search': 'Rechercher un anonyme',
  'admin.anonymous.title': 'Participant anonyme',
  'admin.col.type': 'Type',
  'admin.col.members': 'Membres',
  'admin.col.createdOn': 'Création',
  'admin.col.lastMessage': 'Dernier message',
  'admin.tab.profile': 'Profil',
  'admin.tab.conversations': 'Conversations',
  'admin.tab.media': 'Médias',
  'admin.tab.contacts': 'Contacts',
  'admin.tab.communities': 'Communautés',
  'admin.tab.voice': 'Profil vocal',
  'admin.tab.security': 'Sécurité',
  'admin.tab.reports': 'Signalements',
  'admin.tab.label': 'Sections de la fiche',
  'admin.dossier.empty': 'Rien à afficher.',
  'admin.dossier.restricted': 'Réservé aux administrateurs habilités aux données sensibles.',
  'admin.contacts.sent': 'Envoyée',
  'admin.contacts.received': 'Reçue',
  'admin.contacts.direction': 'Demande',
  'admin.contacts.links': '{share} lien(s) de partage · {tracking} lien(s) de suivi · {affiliate} jeton(s) d\'affiliation',
  'admin.communities.creator': 'Créateur',
  'admin.communities.private': 'Privée',
  'admin.voice.none': 'Aucun profil vocal enregistré.',
  'admin.voice.samples': 'Échantillons',
  'admin.voice.duration': 'Durée enregistrée',
  'admin.voice.model': 'Modèle',
  'admin.voice.consents': 'Consentements',
  'admin.voice.consentProfile': 'Profil vocal',
  'admin.voice.consentData': 'Données vocales',
  'admin.voice.consentCloning': 'Clonage de voix',
  'admin.voice.traced': 'Cette consultation est tracée dans le journal d\'audit.',
  'admin.security.sessions': 'Sessions',
  'admin.security.events': 'Événements de sécurité',
  'admin.security.device': 'Appareil',
  'admin.security.place': 'Lieu',
  'admin.security.ip': 'Adresse IP',
  'admin.security.valid': 'Ouverte',
  'admin.security.closed': 'Fermée',
  'admin.security.event': 'Événement',
  'admin.security.severity': 'Gravité',
  'admin.col.date': 'Date',
  'admin.reports.filed': 'Signalements faits par ce membre',
  'admin.reports.received': 'Ses messages signalés',
  'admin.reports.subject': 'Objet',
  'admin.reports.reporter': 'Signalé par',
  'admin.reports.reason': 'Motif',
  'admin.reports.message': 'Message',
  'admin.reports.withheld': 'texte réservé à la modération',
  'admin.gallery.title': 'Images',
  'admin.gallery.empty': 'Aucune image',
  'admin.gallery.previous': 'Image précédente',
  'admin.gallery.next': 'Image suivante',
  'admin.gallery.avatar': 'Photo de profil',
  'admin.gallery.banner': 'Bannière',
  'admin.gallery.position': 'Image {n} sur {total}',
  'admin.meta.name': 'Nom complet',
  'admin.meta.systemLanguage': 'Langue principale',
  'admin.meta.regionalLanguage': 'Langue secondaire',
  'admin.meta.customLanguage': 'Langue de destination',
  'admin.meta.timezone': 'Fuseau horaire',
  'admin.meta.completion': 'Profil complété',
  'admin.meta.failedLogins': 'Connexions échouées',
  'admin.meta.updated': 'Mis à jour le',
  'admin.tab.preferences': 'Préférences',
  'admin.stats.messagesSent': 'Messages envoyés',
  'admin.stats.conversations': 'Conversations',
  'admin.stats.posts': 'Publications',
  'admin.stats.reels': 'Reels',
  'admin.stats.stories': 'Stories',
  'admin.stats.comments': 'Commentaires',
  'admin.stats.reactionsGiven': 'Réactions données',
  'admin.stats.mediaUploaded': 'Médias envoyés',
  'admin.stats.friends': 'Amis',
  'admin.stats.pendingIn': 'Demandes reçues',
  'admin.stats.pendingOut': 'Demandes envoyées',
  'admin.stats.reportsFiled': 'Signalements déposés',
  'admin.stats.reportsReceived': 'Signalements reçus',
  'admin.stats.activeSessions': 'Sessions actives',
  'admin.stats.communities': 'Communautés',
  'admin.prefs.privacy': 'Confidentialité',
  'admin.prefs.notification': 'Notifications',
  'admin.prefs.message': 'Messages',
  'admin.prefs.audio': 'Audio et voix',
  'admin.prefs.video': 'Vidéo',
  'admin.prefs.document': 'Documents',
  'admin.prefs.application': 'Application',
  'admin.prefs.notice': 'Chaque modification s’applique au membre sur tous ses appareils et reste inscrite au journal d’audit.',
  'admin.prefs.readOnly': 'lecture seule',
  'admin.prefs.saved': 'Préférence enregistrée',
  'admin.prefs.failed': 'La préférence n’a pas pu être enregistrée',
  'admin.prefs.consent': 'Refusé : le membre n’a pas donné le consentement que cette option exige',
  'admin.prefs.reserved': 'Refusé : votre rôle ne permet pas de modifier ce membre',
  'admin.prefs.invalid': 'Refusé : valeur invalide',
  'admin.list.sort': 'Tri',
  'admin.list.order': 'Ordre',
  'admin.list.newest': 'Plus récentes d’abord',
  'admin.list.oldest': 'Plus anciennes d’abord',
  'admin.conv.manage': 'Gérer',
  'admin.conv.role.admin': 'Administrateur',
  'admin.conv.role.moderator': 'Modérateur',
  'admin.conv.role.member': 'Membre',
  'admin.conv.configure': 'Configurer',
  'admin.convSettings.title': 'Configurer la conversation',
  'admin.convSettings.titleField': 'Titre',
  'admin.convSettings.description': 'Description',
  'admin.convSettings.avatar': 'Image (URL)',
  'admin.convSettings.banner': 'Bannière (URL)',
  'admin.convSettings.writeRole': 'Qui peut écrire',
  'admin.convSettings.writeRole.everyone': 'Tout le monde',
  'admin.convSettings.writeRole.member': 'Les membres',
  'admin.convSettings.writeRole.moderator': 'Modérateurs et plus',
  'admin.convSettings.writeRole.admin': 'Administrateurs et plus',
  'admin.convSettings.writeRole.creator': 'Le créateur seul',
  'admin.convSettings.announcement': 'Canal d\'annonces',
  'admin.convSettings.slowMode': 'Mode lent (secondes)',
  'admin.convSettings.autoTranslate': 'Traduction automatique',
  'admin.convSettings.archive': 'Archiver',
  'admin.convSettings.restore': 'Restaurer',
  'admin.convSettings.close': 'Fermer à l\'écriture',
  'admin.convSettings.reopen': 'Rouvrir',
  'admin.convSettings.memberRole': 'Rôle de ce membre',
  'admin.convSettings.remove': 'Retirer de la conversation',
  'admin.convSettings.reason': 'Motif (10 caractères minimum)',
  'admin.convSettings.confirm': 'Confirmer',
  'admin.convSettings.save': 'Enregistrer',
  'admin.convSettings.saved': 'Conversation mise à jour',
  'admin.convSettings.removed': 'Membre retiré',
  'admin.convSettings.failed': 'Modification refusée',
  'admin.convSettings.creatorProtected': 'Le créateur ne peut être ni rétrogradé ni retiré',
  'admin.create.open': 'Créer un compte',
  'admin.create.title': 'Nouveau compte',
  'admin.create.username': 'Pseudonyme',
  'admin.create.firstName': 'Prénom',
  'admin.create.lastName': 'Nom',
  'admin.create.email': 'E-mail',
  'admin.create.password': 'Mot de passe',
  'admin.create.passwordHint': 'Long et difficile à deviner : un mot de passe trop faible est refusé.',
  'admin.create.language': 'Langue de l’interface',
  'admin.create.emailVerified': 'J’atteste cette adresse e-mail',
  'admin.create.emailVerifiedOn': 'Le compte pourra se connecter tout de suite.',
  'admin.create.emailVerifiedOff': 'Sans attestation, un code sera envoyé à cette adresse à la première connexion.',
  'admin.create.submit': 'Créer le compte',
  'admin.create.created': 'Compte créé',
  'admin.create.failed': 'Création refusée : {reason}',
  'admin.create.emailTaken': 'Cette adresse est déjà utilisée par un autre compte.',
  'admin.create.usernameTaken': 'Ce pseudonyme est déjà pris.',
  'admin.create.missing': 'Renseignez tous les champs.',
  'admin.images.avatarOpen': 'Changer la photo',
  'admin.images.bannerOpen': 'Changer la bannière',
  'admin.images.upload': 'Téléverser une image',
  'admin.images.uploading': 'Téléversement…',
  'admin.images.remove': 'Retirer',
  'admin.images.choose': 'Choisir parmi ses publications publiques',
  'admin.images.chooseHint': 'Seules les images qu’il a déjà publiées en public sont proposées.',
  'admin.images.noCandidate': 'Aucune image publique à proposer.',
  'admin.images.candidatesFailed': 'Ses images publiques n’ont pas pu être chargées.',
  'admin.images.useCandidate': 'Utiliser l’image {n} sur {total}',
  'admin.images.current': 'Image actuelle',
  'admin.images.saved': 'Image mise à jour',
  'admin.images.removed': 'Image retirée',
  'admin.images.failed': 'Échec de la mise à jour de l’image',
  'admin.images.offline': 'Hors ligne : réessayez une fois connecté.',
  'admin.images.unreadable': 'Cette image n’a pas pu être lue.',
  'admin.section.saving': 'Enregistrement…',
  'admin.contact.title': 'Contact',
  'admin.contact.phone': 'Téléphone',
  'admin.contact.verified': 'Vérifié',
  'admin.contact.unverified': 'Non vérifié',
  'admin.contact.resend': 'Renvoyer la vérification',
  'admin.contact.resent': 'Vérification envoyée',
  'admin.contact.resendFailed': 'La vérification n’a pas pu être envoyée',
  'admin.contact.markVerified': 'Marquer vérifié',
  'admin.contact.markUnverified': 'Retirer la vérification',
  'admin.security.twoFactorHint': 'Un code est demandé à chaque connexion.',
  'admin.security.sessionsOpen': 'Voir les sessions',
  'admin.roleStatus.title': 'Rôle et statut',
  'admin.identity.suggestions': 'Pseudonymes libres',
  'admin.identity.noLanguage': 'Aucune',
  'admin.security.twoFactorNotEnrolled': 'Le membre doit d’abord appairer une application d’authentification.',
  'admin.quick.title': 'Actions rapides',
  'admin.quick.activate': 'Activer le compte',
  'admin.quick.activated': 'Compte activé',
  'admin.quick.validateEmail': 'Valider l’e-mail',
  'admin.quick.validatePhone': 'Valider le téléphone',
  ...kitFr,
  ...dashboardFr,
  ...statistiquesFr,
  ...moderationFr,
  ...contenusFr,
  ...liensFr,
  ...diffusionsFr,
  ...classementSupervisionFr,
  ...auditReglagesFr,
  ...personnesFr,
  ...conversationsAgentFr,
} as const;

export default fr;
