import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const esComposerAttach = {
  'composer.attach.group': 'Tipos de adjuntos',
  'composer.attach.handle': 'Tirador del panel',
  'composer.attach.photo': 'Fotos',
  'composer.attach.photo.action': 'Elegir fotos',
  'composer.attach.camera': 'Cámara',
  'composer.attach.camera.action': 'Hacer una foto',
  'composer.attach.file': 'Archivo',
  'composer.attach.file.action': 'Elegir un archivo',
  'composer.attach.location': 'Ubicación',
  'composer.attach.location.action': 'Compartir mi ubicación',
  'composer.attach.voice': 'Voz',
  'composer.attach.voice.action': 'Grabar un mensaje de voz',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Insertar un emoji',
  'composer.emoji.title': 'Insertar un emoji',
  'composer.location.locating': 'Buscando tu ubicación…',
  'composer.location.denied': 'Ubicación denegada: permítela en los ajustes',
  'composer.location.unavailable': 'Ubicación no disponible en este navegador',
  'composer.location.failed': 'Ubicación no encontrada: inténtalo de nuevo',
  'composer.location.chip': 'LUGAR',
  'composer.location.unknown': 'Lugar desconocido',
  'composer.location.remove': 'Quitar la ubicación',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Enviar un sticker',
  'composer.sticker.title': 'Mis stickers',
  'composer.sticker.fromImage': 'Desde una imagen',
  'composer.sticker.paste': 'Pegar',
  'composer.sticker.pasteHint': 'Pega o suelta una imagen aquí para convertirla en sticker',
  'composer.sticker.nothingToPaste': 'No hay ninguna imagen en el portapapeles',
  'composer.sticker.empty': 'Aún no hay stickers — crea uno desde una imagen o pega uno',
  'composer.sticker.creating': 'Creando sticker…',
  'composer.sticker.manage': 'Gestionar',
  'composer.sticker.done': 'Listo',
  'composer.sticker.remove': 'Quitar este sticker',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'No se pudo cargar este sticker — inténtalo de nuevo',
  'composer.sticker.error.notImage': 'Este archivo no es una imagen',
  'composer.sticker.error.tooLarge': 'Imagen demasiado pesada para un sticker',
  'composer.sticker.error.full': 'Biblioteca llena — quita un sticker para añadir otro',
  'composer.sticker.error.failed': 'No se pudo crear el sticker',
} satisfies ComposerAttachCatalogSlice;

export default esComposerAttach;
