import type { CallControlsCatalog } from '@/lib/i18n-call-controls-catalog';

const de = {
  'callControls.invite': 'Hinzufügen',
  'callControls.invite.label': 'Personen zum Anruf hinzufügen',
  'callControls.react': 'Reagieren',
  'callControls.react.label': 'Reaktion senden',
  'callControls.react.palette': 'Reaktionen',
  'callControls.react.send': 'Mit {emoji} reagieren',
  'callControls.react.from': '{name} hat mit {emoji} reagiert',
  'callControls.react.mine': 'Sie haben mit {emoji} reagiert',
  'callControls.people.title': 'Teilnehmende',
  'callControls.people.inCall': 'Im Anruf',
  'callControls.people.add': 'Personen hinzufügen',
  'callControls.people.search': 'Kontakt suchen',
  'callControls.people.empty': 'Alle Ihre Kontakte sind bereits im Anruf',
  'callControls.people.none': 'Kein Kontakt passt',
  'callControls.people.invite': 'Einladen',
  'callControls.people.inviteNamed': '{name} einladen',
  'callControls.people.loading': 'Kontakte werden geladen…',
  'callControls.people.you': 'Sie',
  'callControls.close': 'Schließen',
  'callControls.ringing': 'Klingelt…',
  'callControls.moderate.menu': 'Optionen für {name}',
  'callControls.mute': 'Mikrofon stummschalten',
  'callControls.mute.done': 'Mikrofon stumm',
  'callControls.remove': 'Aus dem Anruf entfernen',
  'callControls.remove.confirm': '{name} aus dem Anruf entfernen?',
  'callControls.remove.detail': 'Der Anruf endet sofort für {name}.',
  'callControls.remove.do': 'Entfernen',
  'callControls.cancel': 'Abbrechen',
  'callControls.mutedBy': '{name} hat Ihr Mikrofon stummgeschaltet',
  'callControls.someone': 'Eine teilnehmende Person',
  'callControls.incomingInvite': '{name} lädt Sie zu einem Gruppenanruf ein',
  'callControls.error.invite': '{name} konnte nicht eingeladen werden',
  'callControls.error.mute': '{name} konnte nicht stummgeschaltet werden',
  'callControls.error.remove': '{name} konnte nicht entfernt werden',
  'callControls.error.notContact': '{name} ist nicht in Ihren Kontakten',
  'callControls.error.alreadyIn': '{name} ist bereits im Anruf',
  'callControls.error.full': 'Der Anruf ist voll',
  'callControls.error.rateLimited': 'Zu viele Versuche: Bitte gleich erneut versuchen',
  'callControls.error.denied': 'Dieses Recht haben Sie in diesem Anruf nicht',
  'callControls.error.notActive': 'Der Anruf ist nicht mehr aktiv',
  'callControls.error.gone': '{name} ist nicht mehr im Anruf',
  'callControls.record.title': 'Was möchten Sie aufnehmen?',
  'callControls.record.audio': 'Nur Audio',
  'callControls.record.audioDetail': 'Die Stimmen aller',
  'callControls.record.video': 'Audio und Video',
  'callControls.record.videoDetail': 'Die sichtbaren Bilder und die Stimmen',
} satisfies CallControlsCatalog;

export default de;
