import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page et les fiches (`game.concept.*`, `game.fiche.*`, `game.fact.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const ar = {
  'game.progression.title': 'التقدّم',
  'game.concept.why_label': 'ما فائدته',
  'game.concept.how_label': 'كيف يعمل',
  'game.fiche.what': 'ما هو؟',
  'game.fiche.where': 'أين وصلتُ',
  'game.fiche.earn': 'كيف تكسب المزيد',
  'game.fiche.more': 'للمزيد',
  'game.fiche.unknown': 'هذه الصفحة غير موجودة، أو أن خادمك لا يقدّمها بعد.',
  'game.concept.level.name': 'المستوى',
  'game.concept.level.why': 'مستواك يُظهر الطريق الذي قطعته على Meeshy.',
  'game.concept.level.how': 'نقاطك تملأ الحلقة: حين تمتلئ، تصعد مستوى.',
  'game.concept.level.tip.1': 'أنجز مهام اليوم: فهي تمنح نقاطًا كثيرة.',
  'game.concept.level.tip.2': 'أبقِ لهبك مشتعلًا: فهو يزيد مكافآتك.',
  'game.concept.points.name': 'النقاط',
  'game.concept.points.why': 'النقاط ترفع مستواك وتُستعمل لسكّ Meesh.',
  'game.concept.points.how': 'كل إجراء مفيد يمنحك نقاطًا: الكتابة، والكلام، والنشر، والتفاعل، والدعوة.',
  'game.concept.points.tip.1': 'انشر، علّق، تفاعل: لكل فئة من الإجراءات قيمتها.',
  'game.concept.points.tip.2': 'فعّل اندفاعًا لتضاعف نقاطك.',
  'game.concept.meesh.name': 'Meesh',
  'game.concept.meesh.why': '‏Meesh هي عملة Meeshy النادرة: تحتفظ بها أو تنفقها.',
  'game.concept.meesh.how': 'تسكّها بنقاطك. كلما زاد ما سُكّ، ارتفع ثمن التالية.',
  'game.concept.meesh.tip.1': 'احتفظ بـ Meesh ليكبر كنزك.',
  'game.concept.meesh.tip.2': 'أنفقها لتحمي لهبك أو لتبدّل مهمة.',
  'game.concept.glory.name': 'المجد',
  'game.concept.glory.why': 'المجد يمنحك رتبتك، ورتبتك لا تنخفض أبدًا.',
  'game.concept.glory.how': 'كل سكّ وكل رقم قياسي وكل إنجاز يضيف مجدًا.',
  'game.concept.glory.tip.1': 'اسكّ Meesh: كل سكّ يضيف مجدًا.',
  'game.concept.glory.tip.2': 'حطّم أرقامك القياسية وافتح الإنجازات.',
  'game.concept.flame.name': 'اللهب',
  'game.concept.flame.why': 'لهبك يعدّ أيامك المتتالية ويزيد مكافآت مهامك.',
  'game.concept.flame.how': 'إجراء واحد في اليوم يجعله يكبر. التجميد يغطّي يومًا فائتًا.',
  'game.concept.flame.tip.1': 'قم بإجراء واحد على الأقل كل يوم.',
  'game.concept.flame.tip.2': 'احتفظ بتجميد في الاحتياط لأيام الغياب.',
  'game.concept.missions.name': 'مهام اليوم',
  'game.concept.missions.why': 'المهام تمنحك هدفًا كل يوم، ونقاطًا إضافية.',
  'game.concept.missions.how': 'ثلاث مهام في اليوم. حين تُنجزها، تفتح الصندوق.',
  'game.concept.missions.tip.1': 'ابدأ بأسهل مهمة.',
  'game.concept.missions.tip.2': 'لم تعجبك مهمة؟ بدّلها، مرة واحدة في اليوم.',
  'game.concept.league.name': 'الدوري',
  'game.concept.league.why': 'الدوري يقيسك كل أسبوع بـ ⁦29⁩ لاعبًا آخر.',
  'game.concept.league.how': 'نقاط أسبوعك تحدّد مركزك. الأوائل يصعدون إلى الدوري الأعلى.',
  'game.concept.league.tip.1': 'العب قليلًا كل يوم: نقاط الأسبوع تتراكم.',
  'game.concept.league.tip.2': 'استهدف المراكز الأولى قبل مساء الأحد.',
  'game.concept.league.more': 'عرض الترتيب',
  'game.concept.league.unplaced': 'لم تُوضع في مجموعة بعد',
  'game.concept.season.name': 'الموسم',
  'game.concept.season.why': 'الموسم مسار من ثمانية أسابيع، وفي نهايته كأس.',
  'game.concept.season.how': 'المهام والثنائي يمنحان نجومًا. النجوم تفتح المراحل.',
  'game.concept.season.tip.1': 'أنهِ مهام اليوم لتكسب نجومًا.',
  'game.concept.season.tip.2': 'العب ثنائيًا مع صديق: المكافأة تتضاعف.',
  'game.concept.season.more': 'عرض المسار',
  'game.concept.season.none': 'لا موسم الآن',
  'game.concept.prestige.name': 'التميّز',
  'game.concept.prestige.why': 'التميّز يكافئ من يبلغ المستوى ⁦100⁩.',
  'game.concept.prestige.how': 'يعود مستواك إلى ⁦1⁩. تكسب نجمة وكأسًا ومجدًا.',
  'game.concept.prestige.tip.1': 'اصعد حتى المستوى ⁦100⁩.',
  'game.concept.prestige.tip.2': 'انتقل إلى التميّز متى شئت: لا شيء يُلزمك.',
  'game.concept.prestige.more': 'فتح التميّز',
  'game.concept.elans.name': 'الاندفاعات',
  'game.concept.elans.why': 'الاندفاع يضاعف نقاط إجراءاتك القادمة.',
  'game.concept.elans.how': 'قم بإجراءات من عدة فئات في هذه الأيام لتفعيله.',
  'game.concept.elans.tip.1': 'نوّع إجراءاتك: اكتب، انشر، علّق، تفاعل.',
  'game.concept.elans.tip.2': 'عُد عدة أيام متتالية لتحافظ عليه.',
  'game.concept.elans.families.one': 'فئة نشطة واحدة',
  'game.concept.elans.families.other': '⁦{count}⁩ فئات نشطة',
  'game.concept.badges.name': 'الأوسمة',
  'game.concept.badges.why': 'الوسام يُظهر أكثر ما تفعله على Meeshy.',
  'game.concept.badges.how': 'كرّر إجراءً: يتغيّر معدن وسامه، من النحاس إلى المنشور.',
  'game.concept.badges.tip.1': 'اختر إجراءً تحبه وكرّره كثيرًا.',
  'game.concept.badges.tip.2': 'الوسام المنطفئ يشتعل من جديد: لا شيء يضيع.',
  'game.concept.badges.more': 'عرض كل أوسمتي',
  'game.concept.defis.name': 'التحديات',
  'game.concept.defis.why': 'التحديات درجات تتجاوزها، واحدة بعد أخرى.',
  'game.concept.defis.how': 'كل درجة تبلغها تفتح التالية، أعلى قليلًا.',
  'game.concept.defis.tip.1': 'انظر إلى الدرجة التالية وتقدّم نحوها.',
  'game.concept.defis.tip.2': 'جرّب إجراءات جديدة: لكل منها تحدياته.',
  'game.concept.defis.more': 'عرض كل تحدياتي',
  'game.concept.succes.name': 'الإنجازات',
  'game.concept.succes.why': 'الإنجاز يسجّل لحظة نادرة من قصتك على Meeshy.',
  'game.concept.succes.how': 'يُفتح دفعة واحدة، حين تجمع ما يطلبه.',
  'game.concept.succes.tip.1': 'استكشف التطبيق: بعض الإنجازات مخفية.',
  'game.concept.succes.tip.2': 'الأندر منها يضيف أكثر مجد.',
  'game.concept.succes.more': 'عرض كل إنجازاتي',
  'game.concept.showcase.name': 'الواجهة',
  'game.concept.showcase.why': 'واجهتك تعرض الكؤوس التي فزت بها.',
  'game.concept.showcase.how': 'كل كأس يأخذ مكانه وحده. أنت تختار الترتيب ومن يراها.',
  'game.concept.showcase.tip.1': 'أنهِ في أعلى دوريك لتفوز بكأس.',
  'game.concept.showcase.tip.2': 'أكمل موسمًا أو انتقل إلى التميّز.',
  'game.concept.showcase.more': 'فتح واجهتي',
  'game.concept.atlas.name': 'الأطلس',
  'game.concept.atlas.why': 'الأطلس يحفظ ختمًا لكل لغة تبادلت بها الرسائل.',
  'game.concept.atlas.how': 'أرسل رسالة واستقبل أخرى بلغة ما: فيوضع الختم.',
  'game.concept.atlas.tip.1': 'اكتب لشخص بلغة غير لغتك.',
  'game.concept.atlas.tip.2': 'انتظر ردّه: لا بد من رسالة في كل اتجاه.',
  'game.concept.atlas.more': 'فتح أطلسي',
  'game.concept.chip.next_price': 'التالية: {price}',
  'game.concept.chip.next': 'بعدها: {name}',
  'game.concept.chip.record': 'الرقم القياسي: {value}',
  'game.concept.chip.freezes': 'التجميدات: {count}',
  'game.concept.chip.chest.locked': 'الصندوق مغلق',
  'game.concept.chip.chest.ready': 'الصندوق جاهز',
  'game.concept.chip.chest.claimed': 'الصندوق مفتوح',
  'game.concept.chip.can_mint': 'السكّ ممكن',
  'game.concept.chip.mint_covered': 'يكفي لسكّ Meesh',
  'game.concept.chip.left': 'الباقي: ⁦{count}⁩',
  'game.concept.chip.week': 'الأسبوع {week}',
  'game.concept.chip.no_elan': 'لا اندفاع الآن',
  'game.concept.chip.factor': 'النقاط ⁦×{factor}⁩',
  'game.concept.chip.seen_by': 'يراها: {who}',
  'game.fact.tier': 'المرحلة',
  'game.fact.to_next': 'المستوى التالي',
  'game.fact.record': 'الرقم القياسي',
  'game.fact.next_meesh': '‏Meesh التالية',
  'game.fact.missing': 'ينقص',
  'game.fact.balance': 'في حوزتك',
  'game.fact.next_tier': 'المرحلة التالية',
  'game.fact.minted': 'سُكّت منذ البداية',
  'game.fact.next_rank': 'الرتبة التالية',
  'game.fact.streak': 'السلسلة',
  'game.fact.form': 'الشكل',
  'game.fact.freezes': 'التجميدات في الاحتياط',
  'game.fact.state': 'الحالة',
  'game.fact.lit': 'مشتعل',
  'game.fact.done': 'المُنجزة',
  'game.fact.week_points': 'نقاط الأسبوع',
  'game.fact.closes': 'الإغلاق',
  'game.fact.steps': 'المراحل',
  'game.fact.stars': 'النجوم',
  'game.fact.week': 'الأسبوع',
  'game.fact.factor': 'المضاعِف',
  'game.fact.families': 'الفئات النشطة',
  'game.fact.earned': 'المكتسبة',
  'game.fact.trophies': 'الكؤوس',
  'game.fact.visibility': 'يراها',
  'game.fact.stamps': 'الأختام',
  'game.fact.pending': 'قيد الإنجاز',
  'game.fact.group': 'المجموعة',
  'game.fact.material': 'المعدن',
  'game.detail.obtain_label': 'كيف تحصل عليه',
  'game.detail.gives_label': 'ماذا يمنحك',
  'game.detail.earned': 'تم الحصول عليه',
  'game.detail.earned_on': 'تم الحصول عليه في {date}',
  'game.detail.locked': 'لم تحصل عليه بعد',
  'game.detail.missing': 'ينقص {missing}',
  'game.detail.see_fiche': 'عرض الصفحة',
  'game.detail.open': '{name}: عرض التفاصيل',
  'game.detail.rarity': 'الندرة',
  'game.detail.header_group': 'رتبتي وعملات Meesh',
  'game.detail.badge.what': 'الوسام يُظهر كم مرة قمت بإجراء ما.',
  'game.detail.badge.how': 'كرّر هذا الإجراء: عند كل درجة يتغيّر معدن الوسام.',
  'game.detail.succes.what': 'الإنجاز يسجّل لحظة نادرة من قصتك على Meeshy.',
  'game.detail.succes.how': 'اجمع ما يطلبه: يُفتح دفعة واحدة.',
  'game.detail.defi.what': 'التحدي درجة تتجاوزها في فئة من الإجراءات.',
  'game.detail.defi.how': 'ابلغ العدد المطلوب: تُفتح الدرجة التالية.',
  'game.detail.trophy.what': 'الكأس يحفظ ذكرى فوز. لا يمنح شيئًا: إنه للعرض.',
  'game.detail.trophy.how': 'أنهِ في أعلى دوريك، أكمل موسمًا، انتقل إلى التميّز أو حافظ على لهبك.',
  'game.detail.stamp.what': 'الختم يثبت أنك تبادلت الرسائل فعلًا بهذه اللغة.',
  'game.detail.stamp.how': 'أرسل رسالة بهذه اللغة، واستقبل واحدة.',
  'game.detail.step.what': 'مرحلة الموسم مكافأة مجانية على المسار.',
  'game.detail.step.how': 'اكسب نجومًا بالمهام والثنائي، ثم استلم المرحلة.',
  'game.detail.seal.what': 'الختم عنصر للجمع. لا يغيّر شيئًا في اللعبة.',
  'game.detail.seal.how': 'خذه بعملات Meesh خلال الموسم.',
  'game.detail.gem.what': 'الجوهرة تقول في أي دوري تلعب هذا الأسبوع.',
  'game.detail.gem.how': 'أنهِ بين أوائل مجموعتك لتصعد دوريًا.',
  'game.detail.star.what': 'نجمة التميّز تبقى على حلقة مستواك إلى الأبد.',
  'game.detail.star.how': 'ابلغ المستوى 100، ثم انتقل إلى التميّز.',
  'game.detail.rank.what': 'شعارك يُظهر رتبتك. الرتبة لا تنخفض أبدًا.',
  'game.detail.rank.how': 'اكسب المجد: اسكّ Meesh، حطّم أرقامك القياسية، افتح الإنجازات.',
  'game.detail.flame.what': 'شكل لهبك يكبر مع سلسلة أيامك.',
  'game.detail.flame.how': 'كلما كبر، زادت مكافآت مهامك.',
  'game.detail.freeze.what': 'التجميد يحمي لهبك: يغطّي يومًا لم تفعل فيه شيئًا.',
  'game.detail.freeze.how': 'اشترِه بعملات Meesh، أو اعثر عليه في صندوق اليوم.',
  'game.detail.mission.what': 'المهمة هدف صغير تبلغه اليوم.',
  'game.detail.mission.how': 'تمنح نقاطًا وتقرّبك من صندوق اليوم.',
  'game.detail.chest.what': 'صندوق اليوم يُفتح حين تُنجز مهامك.',
  'game.detail.chest.how': 'نقاط، وأحيانًا جزء من Meesh أو تجميد.',
  'game.detail.coin.what': '‏Meesh هي عملة Meeshy النادرة. كل عملة تحمل رقمها.',
  'game.detail.coin.how': 'اسكّها بنقاطك حين يصير لديك ما يكفي.',
  'game.detail.ring.what': 'الحلقة تُظهر مستواك: تمتلئ بنقاطك.',
  'game.detail.ring.how': 'اكسب نقاطًا: حين تمتلئ الحلقة، تصعد مستوى.',
  'game.detail.treasury.what': 'كنزك يكبر بعملات Meesh التي تحتفظ بها.',
  'game.detail.treasury.how': 'احتفظ بعملات Meesh بدل إنفاقها لتبلغ المرحلة التالية.',
  'game.detail.elan.what': 'الفئة تجمع إجراءات متشابهة.',
  'game.detail.elan.how': 'كل إجراء يمنح نقاطًا. عدة فئات نشطة تفعّل اندفاعًا.',
  'game.detail.elan.active': 'نشطة هذه الأيام',
  'game.detail.elan.idle': 'غير نشطة هذه الأيام',
  'game.detail.elan.points': 'حتى {points} لكل إجراء',
  'game.detail.player.what': 'لاعب من مجموعتك. لا ترى إلا اسمه المستعار ونقاط أسبوعه.',
  'game.detail.fact.tier': 'حتى المستوى 100، تكوّن عشرة مستويات مرحلة؛ وبعده مئة مستوى، ويبدأ التفرد عند 1000. لكل مرحلة اسمها ولونها.',
  'game.detail.fact.score': 'هذه نقاطك الحالية. منها يُحسب مستواك.',
  'game.detail.fact.level_next': 'هذه النقاط التي تنقصك لتصعد مستوى.',
  'game.detail.fact.level_record': 'هذا أعلى مستوى بلغته.',
  'game.detail.fact.tailwind': 'بعد السكّ، تُحسب نقاطك أكثر حتى مستواك القياسي.',
  'game.detail.fact.mint_price': 'هذا ثمن Meesh التالية. يرتفع مع كل سكّ.',
  'game.detail.fact.mint_missing': 'هذه النقاط التي تنقصك لسكّ Meesh التالية.',
  'game.detail.fact.can_mint': 'لديك نقاط كافية: يمكنك سكّ Meesh من صفحتها.',
  'game.detail.fact.factor': 'إجراءاتك القادمة تمنح هذا العدد من أضعاف النقاط.',
  'game.detail.fact.mint_next': 'كل Meesh تحمل رقمها. واحدة من كل مئة ذهبية، وواحدة من كل ألف من المنشور.',
  'game.detail.fact.mint_glory': 'كل سكّ يضيف هذا المجد إلى رتبتك.',
  'game.detail.fact.minted': 'هذا عدد عملات Meesh التي سككتها منذ البداية.',
  'game.detail.fact.glory': 'المجد يتراكم ولا ينخفض أبدًا. وهو يمنحك رتبتك.',
  'game.detail.fact.glory_missing': 'هذا المجد الذي ينقصك للرتبة التالية.',
  'game.detail.fact.streak': 'هذا عدد الأيام المتتالية التي قمت فيها بإجراء واحد على الأقل.',
  'game.detail.fact.streak_record': 'هذه أطول سلسلة أيام لك.',
  'game.detail.fact.flame_state': 'تقول إن كان لهبك مشتعلًا أو في خطر أو محميًا أو منطفئًا.',
  'game.detail.fact.missions_done': 'ثلاث مهام في اليوم. حين تُنجز، تفتح الصندوق.',
  'game.detail.fact.league_place': 'هذا مركزك بين لاعبي مجموعتك، هذا الأسبوع.',
  'game.detail.fact.week_points': 'هذه النقاط المكتسبة منذ الاثنين. تبدأ من الصفر كل أسبوع.',
  'game.detail.fact.league_zone': 'الأوائل يصعدون، والأخيرون يهبطون، والباقون يبقون.',
  'game.detail.fact.league_missing': 'هذه النقاط التي تنقصك لتدخل منطقة الصعود.',
  'game.detail.fact.league_closes': 'أسبوع الدوري يُغلق مساء الأحد. عندها يُثبَّت الترتيب.',
  'game.detail.fact.league_friends': 'هذا مركزك بين أصدقائك المقبولين، هذا الأسبوع.',
  'game.detail.fact.season': 'الموسم يدوم ثمانية أسابيع وله رقم.',
  'game.detail.fact.season_week': 'هذا الأسبوع الجاري، من أسابيع الموسم الثمانية.',
  'game.detail.fact.season_steps': 'هذه المراحل التي فتحتها على مسار الموسم.',
  'game.detail.fact.season_stars': 'النجوم تُكسب بالمهام والثنائي. وهي تفتح المراحل.',
  'game.detail.fact.prestige_glory': 'هذا المجد الذي تكسبه بالانتقال إلى التميّز.',
  'game.detail.fact.elan_families': 'هذه فئات الإجراءات التي نشطت فيها في الأيام الأخيرة.',
  'game.detail.fact.badges_earned': 'هذا عدد الأوسمة التي حصلت عليها، من كل الموجودة.',
  'game.detail.fact.defis_earned': 'هذه الدرجات التي تجاوزتها، من التي يمكنك بلوغها.',
  'game.detail.fact.succes_earned': 'هذه الإنجازات التي فتحتها، من كل الموجودة.',
  'game.detail.fact.trophies': 'هذا عدد الكؤوس في واجهتك.',
  'game.detail.fact.showcase_visibility': 'أنت تختار من يرى واجهتك: الجميع، أصدقاؤك، أو أنت فقط.',
  'game.detail.fact.atlas_stamps': 'هذه اللغات التي لك فيها ختم، من كل لغات الأطلس.',
  'game.detail.fact.atlas_pending': 'هذه اللغات التي ما زالت تنقصها رسالة، مُرسلة أو مُستقبلة.',
  'game.badge.counts_label': 'ما الذي يُحتسب',
  'game.badge.stars_label': 'النجوم',
  'game.badge.reason.none': 'لا نجمة بعد: أول خطوة منك تُضيء النحاس.',
  'game.badge.reason.crossed': '{material}، لأنك تجاوزت عتبة {threshold}: وصلت إلى {count}.',
  'game.badge.reason.served': '{material}، نلته حين تجاوزت عتبة {threshold}.',
  'game.badge.next': 'يتبقى {missing} للنجمة التالية: {material}، عند {threshold}.',
  'game.badge.complete': 'النجوم السبع مضاءة: هذه الشارة في المنشور.',
  'game.badge.ladder_title': 'المستويات السبعة',
  'game.badge.rung.upcoming': 'عند {threshold}',
  'game.badge.rung.next': 'النجمة التالية · يتبقى {missing}',
  'game.badge.upcoming_title': 'القادم',
  'game.badge.guide_link': 'فهم الشارات',
} as const satisfies GameConceptCatalog;

export default ar;
