import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page et les fiches (`game.concept.*`, `game.fiche.*`, `game.fact.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const es = {
  'game.progression.title': 'Progreso',
  'game.concept.why_label': 'Para qué sirve',
  'game.concept.how_label': 'Cómo funciona',
  'game.fiche.what': '¿Qué es?',
  'game.fiche.where': 'Dónde estoy',
  'game.fiche.earn': 'Cómo ganar más',
  'game.fiche.more': 'Ir más lejos',
  'game.fiche.unknown': 'Esta ficha no existe, o tu servidor todavía no la ofrece.',
  'game.concept.level.name': 'Nivel',
  'game.concept.level.why': 'Tu nivel muestra el camino que has recorrido en Meeshy.',
  'game.concept.level.how': 'Tus puntos llenan el anillo: cuando está lleno, subes un nivel.',
  'game.concept.level.tip.1': 'Haz las misiones del día: dan muchos puntos.',
  'game.concept.level.tip.2': 'Mantén tu Llama encendida: aumenta tus recompensas.',
  'game.concept.points.name': 'Puntos',
  'game.concept.points.why': 'Los puntos suben tu nivel y sirven para acuñar Meeshes.',
  'game.concept.points.how': 'Cada gesto útil da puntos: escribir, hablar, publicar, reaccionar.',
  'game.concept.points.tip.1': 'Publica, comenta, reacciona: cada familia de gestos tiene su baremo.',
  'game.concept.points.tip.2': 'Activa un impulso para multiplicar tus puntos.',
  'game.concept.meesh.name': 'Meeshes',
  'game.concept.meesh.why': 'La Meesh es la moneda rara de Meeshy: se guarda o se gasta.',
  'game.concept.meesh.how': 'La acuñas con tus puntos. Cada acuñación encarece la siguiente.',
  'game.concept.meesh.tip.1': 'Guarda tus Meeshes para hacer crecer tu tesoro.',
  'game.concept.meesh.tip.2': 'Gástalas para proteger tu Llama o cambiar una misión.',
  'game.concept.glory.name': 'Gloria',
  'game.concept.glory.why': 'La Gloria te da tu rango, y tu rango nunca baja.',
  'game.concept.glory.how': 'Cada acuñación, cada récord y cada logro suman Gloria.',
  'game.concept.glory.tip.1': 'Acuña una Meesh: cada acuñación suma Gloria.',
  'game.concept.glory.tip.2': 'Bate tus récords y consigue logros.',
  'game.concept.flame.name': 'Llama',
  'game.concept.flame.why': 'Tu Llama cuenta tus días seguidos y aumenta tus recompensas de misión.',
  'game.concept.flame.how': 'Un gesto al día la hace crecer. Una congelación cubre un día perdido.',
  'game.concept.flame.tip.1': 'Haz al menos un gesto cada día.',
  'game.concept.flame.tip.2': 'Guarda una congelación en reserva para los días sin jugar.',
  'game.concept.missions.name': 'Misiones del día',
  'game.concept.missions.why': 'Las misiones te dan una meta cada día, y puntos extra.',
  'game.concept.missions.how': 'Tres misiones al día. Cuando están hechas, abres el cofre.',
  'game.concept.missions.tip.1': 'Empieza por la misión más fácil.',
  'game.concept.missions.tip.2': '¿No te gusta una misión? Cámbiala, una vez al día.',
  'game.concept.league.name': 'Liga',
  'game.concept.league.why': 'La liga te mide cada semana con otros 29 jugadores.',
  'game.concept.league.how': 'Tus puntos de la semana marcan tu puesto. Los primeros suben de liga.',
  'game.concept.league.tip.1': 'Juega un poco cada día: los puntos de la semana se suman.',
  'game.concept.league.tip.2': 'Apunta a los primeros puestos antes del domingo por la noche.',
  'game.concept.league.more': 'Ver la clasificación',
  'game.concept.league.unplaced': 'Aún sin grupo',
  'game.concept.season.name': 'Temporada',
  'game.concept.season.why': 'La temporada es un recorrido de ocho semanas, con una copa al final.',
  'game.concept.season.how': 'Las misiones y el dúo dan estrellas. Las estrellas abren las etapas.',
  'game.concept.season.tip.1': 'Termina tus misiones del día para ganar estrellas.',
  'game.concept.season.tip.2': 'Juega en dúo con un amigo: la recompensa se duplica.',
  'game.concept.season.more': 'Ver el recorrido',
  'game.concept.season.none': 'Ninguna ahora',
  'game.concept.prestige.name': 'Prestigio',
  'game.concept.prestige.why': 'El Prestigio premia a quienes llegan al nivel 100.',
  'game.concept.prestige.how': 'Tu nivel vuelve a 1. Ganas una estrella, un trofeo y Gloria.',
  'game.concept.prestige.tip.1': 'Sube hasta el nivel 100.',
  'game.concept.prestige.tip.2': 'Pasa a Prestigio cuando quieras: nada te obliga.',
  'game.concept.prestige.more': 'Abrir el Prestigio',
  'game.concept.elans.name': 'Impulsos',
  'game.concept.elans.why': 'Un impulso multiplica los puntos de tus próximos gestos.',
  'game.concept.elans.how': 'Haz gestos de varias familias estos días para activarlo.',
  'game.concept.elans.tip.1': 'Varía tus gestos: escribe, publica, comenta, reacciona.',
  'game.concept.elans.tip.2': 'Vuelve varios días seguidos para mantenerlo.',
  'game.concept.elans.families.one': '{count} familia activa',
  'game.concept.elans.families.other': '{count} familias activas',
  'game.concept.badges.name': 'Insignias',
  'game.concept.badges.why': 'Una insignia muestra lo que más haces en Meeshy.',
  'game.concept.badges.how': 'Repite un gesto: su insignia cambia de material, del cobre al prisma.',
  'game.concept.badges.tip.1': 'Elige un gesto que te guste y repítelo a menudo.',
  'game.concept.badges.tip.2': 'Una insignia apagada se vuelve a encender: nada se pierde.',
  'game.concept.badges.more': 'Ver todas mis insignias',
  'game.concept.defis.name': 'Desafíos',
  'game.concept.defis.why': 'Los desafíos son escalones que superar, uno tras otro.',
  'game.concept.defis.how': 'Cada escalón alcanzado abre el siguiente, un poco más alto.',
  'game.concept.defis.tip.1': 'Mira el próximo escalón y avanza hacia él.',
  'game.concept.defis.tip.2': 'Prueba gestos nuevos: cada uno tiene sus desafíos.',
  'game.concept.defis.more': 'Ver todos mis desafíos',
  'game.concept.succes.name': 'Logros',
  'game.concept.succes.why': 'Un logro marca un momento raro de tu historia en Meeshy.',
  'game.concept.succes.how': 'Se consigue de una vez, cuando reúnes lo que pide.',
  'game.concept.succes.tip.1': 'Explora la aplicación: algunos logros están escondidos.',
  'game.concept.succes.tip.2': 'Los más raros son los que más Gloria suman.',
  'game.concept.succes.more': 'Ver todos mis logros',
  'game.concept.showcase.name': 'Vitrina',
  'game.concept.showcase.why': 'Tu vitrina expone los trofeos que has ganado.',
  'game.concept.showcase.how': 'Cada copa se coloca sola. Tú eliges el orden y quién la ve.',
  'game.concept.showcase.tip.1': 'Termina arriba en tu liga para ganar una copa.',
  'game.concept.showcase.tip.2': 'Completa una temporada o pasa a Prestigio.',
  'game.concept.showcase.more': 'Abrir mi vitrina',
  'game.concept.atlas.name': 'Atlas',
  'game.concept.atlas.why': 'El Atlas guarda un sello por cada idioma en el que has conversado.',
  'game.concept.atlas.how': 'Envía un mensaje y recibe otro en un idioma: el sello se estampa.',
  'game.concept.atlas.tip.1': 'Escribe a alguien en un idioma distinto del tuyo.',
  'game.concept.atlas.tip.2': 'Espera su respuesta: hace falta un mensaje en cada sentido.',
  'game.concept.atlas.more': 'Abrir mi Atlas',
  'game.concept.chip.next_price': 'Siguiente: {price}',
  'game.concept.chip.next': 'Después: {name}',
  'game.concept.chip.record': 'Récord: {value}',
  'game.concept.chip.freezes': 'Congelaciones: {count}',
  'game.concept.chip.chest.locked': 'Cofre cerrado',
  'game.concept.chip.chest.ready': 'Cofre listo',
  'game.concept.chip.chest.claimed': 'Cofre abierto',
  'game.concept.chip.can_mint': 'Puedes acuñar',
  'game.concept.chip.mint_covered': 'Suficiente para una Meesh',
  'game.concept.chip.left': 'Quedan: {count}',
  'game.concept.chip.week': 'Semana {week}',
  'game.concept.chip.no_elan': 'Sin impulso activo',
  'game.concept.chip.factor': 'Puntos ×{factor}',
  'game.concept.chip.seen_by': 'La ven: {who}',
  'game.fact.tier': 'Tramo',
  'game.fact.to_next': 'Próximo nivel',
  'game.fact.record': 'Récord',
  'game.fact.next_meesh': 'Próxima Meesh',
  'game.fact.missing': 'Falta',
  'game.fact.balance': 'En mano',
  'game.fact.next_tier': 'Tramo siguiente',
  'game.fact.minted': 'Acuñadas desde siempre',
  'game.fact.next_rank': 'Rango siguiente',
  'game.fact.streak': 'Racha',
  'game.fact.form': 'Forma',
  'game.fact.freezes': 'Congelaciones en reserva',
  'game.fact.state': 'Estado',
  'game.fact.lit': 'Encendida',
  'game.fact.done': 'Hechas',
  'game.fact.week_points': 'Puntos de la semana',
  'game.fact.closes': 'Cierre',
  'game.fact.steps': 'Etapas',
  'game.fact.stars': 'Estrellas',
  'game.fact.week': 'Semana',
  'game.fact.factor': 'Multiplicador',
  'game.fact.families': 'Familias activas',
  'game.fact.earned': 'Conseguidas',
  'game.fact.trophies': 'Trofeos',
  'game.fact.visibility': 'Visible para',
  'game.fact.stamps': 'Sellos',
  'game.fact.pending': 'En curso',
  'game.fact.group': 'Grupo',
  'game.fact.material': 'Material',
  'game.detail.obtain_label': 'Cómo conseguirlo',
  'game.detail.gives_label': 'Qué te da',
  'game.detail.earned': 'Conseguido',
  'game.detail.earned_on': 'Conseguido el {date}',
  'game.detail.locked': 'Aún no conseguido',
  'game.detail.missing': 'Falta {missing}',
  'game.detail.see_fiche': 'Ver la ficha',
  'game.detail.open': '{name}: ver los detalles',
  'game.detail.rarity': 'Rareza',
  'game.detail.header_group': 'Mi rango y mis Meeshes',
  'game.detail.badge.what': 'Una insignia muestra cuántas veces has hecho un gesto.',
  'game.detail.badge.how': 'Repite ese gesto: en cada escalón, la insignia cambia de material.',
  'game.detail.succes.what': 'Un logro marca un momento raro de tu historia en Meeshy.',
  'game.detail.succes.how': 'Reúne lo que pide: se consigue de una vez.',
  'game.detail.defi.what': 'Un desafío es un escalón que superar en una familia de gestos.',
  'game.detail.defi.how': 'Alcanza el número pedido: se abre el escalón siguiente.',
  'game.detail.trophy.what': 'Un trofeo guarda el recuerdo de una victoria. No da nada: se enseña.',
  'game.detail.trophy.how': 'Termina arriba en tu liga, completa una temporada, pasa a Prestigio o mantén tu Llama.',
  'game.detail.stamp.what': 'Un sello demuestra que has conversado de verdad en este idioma.',
  'game.detail.stamp.how': 'Envía un mensaje en este idioma y recibe otro.',
  'game.detail.step.what': 'Una etapa de temporada es una recompensa gratis en el recorrido.',
  'game.detail.step.how': 'Gana estrellas con las misiones y el dúo, y luego reclama la etapa.',
  'game.detail.seal.what': 'El Sello es un objeto de colección. No cambia nada del juego.',
  'game.detail.seal.how': 'Consíguelo con tus Meeshes durante la temporada.',
  'game.detail.gem.what': 'La gema dice en qué liga juegas esta semana.',
  'game.detail.gem.how': 'Termina entre los primeros de tu grupo para subir de liga.',
  'game.detail.star.what': 'Una estrella de Prestigio se queda en tu anillo de nivel, para siempre.',
  'game.detail.star.how': 'Llega al nivel 100 y pasa a Prestigio.',
  'game.detail.rank.what': 'Tu blasón muestra tu rango. Un rango nunca baja.',
  'game.detail.rank.how': 'Gana Gloria: acuña Meeshes, bate tus récords, consigue logros.',
  'game.detail.flame.what': 'La forma de tu Llama crece con tu racha de días.',
  'game.detail.flame.how': 'Cuanto más grande es, más crecen tus recompensas de misión.',
  'game.detail.freeze.what': 'Una congelación protege tu Llama: cubre un día en que no hiciste nada.',
  'game.detail.freeze.how': 'Cómprala con tus Meeshes, o encuéntrala en el cofre del día.',
  'game.detail.mission.what': 'Una misión es una pequeña meta para hoy.',
  'game.detail.mission.how': 'Da puntos y te acerca al cofre del día.',
  'game.detail.chest.what': 'El cofre del día se abre cuando tus misiones están hechas.',
  'game.detail.chest.how': 'Puntos, y a veces un fragmento de Meesh o una congelación.',
  'game.detail.coin.what': 'La Meesh es la moneda rara de Meeshy. Cada moneda lleva su número.',
  'game.detail.coin.how': 'Acúñala con tus puntos en cuanto tengas suficientes.',
  'game.detail.ring.what': 'El anillo muestra tu nivel: se llena con tus puntos.',
  'game.detail.ring.how': 'Gana puntos: cuando el anillo está lleno, subes un nivel.',
  'game.detail.treasury.what': 'Tu tesoro crece con las Meeshes que guardas.',
  'game.detail.treasury.how': 'Guarda tus Meeshes en vez de gastarlas para alcanzar el tramo siguiente.',
  'game.detail.elan.what': 'Una familia reúne gestos que se parecen.',
  'game.detail.elan.how': 'Cada gesto da puntos. Varias familias activas activan un impulso.',
  'game.detail.elan.active': 'Activa estos días',
  'game.detail.elan.idle': 'No activa estos días',
  'game.detail.elan.points': 'hasta {points} por gesto',
  'game.detail.player.what': 'Es un jugador de tu grupo. Solo ves su seudónimo y sus puntos de la semana.',
  'game.detail.fact.tier': 'Diez niveles forman un tramo. Cada tramo tiene su nombre y su color.',
  'game.detail.fact.score': 'Son los puntos que tienes. Con ellos se calcula tu nivel.',
  'game.detail.fact.level_next': 'Son los puntos que te faltan para subir un nivel.',
  'game.detail.fact.level_record': 'Es el nivel más alto que has alcanzado.',
  'game.detail.fact.tailwind': 'Tras una acuñación, tus puntos cuentan más hasta tu nivel récord.',
  'game.detail.fact.mint_price': 'Es el precio de tu próxima Meesh. Sube con cada acuñación.',
  'game.detail.fact.mint_missing': 'Son los puntos que te faltan para acuñar tu próxima Meesh.',
  'game.detail.fact.can_mint': 'Tienes puntos suficientes: puedes acuñar una Meesh en su ficha.',
  'game.detail.fact.factor': 'Tus próximos gestos dan este número de veces más puntos.',
  'game.detail.fact.mint_next': 'Cada Meesh lleva su número. Una de cada cien es de oro, una de cada mil de prisma.',
  'game.detail.fact.mint_glory': 'Cada acuñación suma esta Gloria a tu rango.',
  'game.detail.fact.minted': 'Es el número de Meeshes que has acuñado desde el principio.',
  'game.detail.fact.glory': 'La Gloria se suma y nunca baja. Te da tu rango.',
  'game.detail.fact.glory_missing': 'Es la Gloria que te falta para el rango siguiente.',
  'game.detail.fact.streak': 'Es el número de días seguidos en que has hecho al menos un gesto.',
  'game.detail.fact.streak_record': 'Es tu racha de días más larga.',
  'game.detail.fact.flame_state': 'Dice si tu Llama está encendida, en peligro, protegida o apagada.',
  'game.detail.fact.missions_done': 'Tres misiones al día. Una vez hechas, abren el cofre.',
  'game.detail.fact.league_place': 'Es tu puesto entre los jugadores de tu grupo, esta semana.',
  'game.detail.fact.week_points': 'Son los puntos ganados desde el lunes. Vuelven a cero cada semana.',
  'game.detail.fact.league_zone': 'Los primeros suben, los últimos bajan, los demás se quedan.',
  'game.detail.fact.league_missing': 'Son los puntos que te faltan para entrar en la zona de ascenso.',
  'game.detail.fact.league_closes': 'La semana de liga se cierra el domingo por la noche. La clasificación queda fija.',
  'game.detail.fact.league_friends': 'Es tu puesto entre tus amigos aceptados, esta semana.',
  'game.detail.fact.season': 'Una temporada dura ocho semanas y lleva un número.',
  'game.detail.fact.season_week': 'Es la semana en curso, de las ocho de la temporada.',
  'game.detail.fact.season_steps': 'Son las etapas que has abierto en el recorrido de la temporada.',
  'game.detail.fact.season_stars': 'Las estrellas se ganan con las misiones y el dúo. Abren las etapas.',
  'game.detail.fact.prestige_glory': 'Es la Gloria que ganas al pasar a Prestigio.',
  'game.detail.fact.elan_families': 'Son las familias de gestos en las que has estado activo estos días.',
  'game.detail.fact.badges_earned': 'Es el número de insignias conseguidas, de todas las que existen.',
  'game.detail.fact.defis_earned': 'Son los escalones superados, de los que puedes alcanzar.',
  'game.detail.fact.succes_earned': 'Son los logros conseguidos, de todos los que existen.',
  'game.detail.fact.trophies': 'Es el número de trofeos guardados en tu vitrina.',
  'game.detail.fact.showcase_visibility': 'Tú eliges quién ve tu vitrina: todos, tus amigos o solo tú.',
  'game.detail.fact.atlas_stamps': 'Son los idiomas en los que tienes un sello, de todos los del Atlas.',
  'game.detail.fact.atlas_pending': 'Son los idiomas en los que aún falta un mensaje, enviado o recibido.',
  'game.badge.counts_label': 'Lo que cuenta',
  'game.badge.stars_label': 'Estrellas',
  'game.badge.reason.none': 'Ninguna estrella por ahora: tu primer gesto enciende el cobre.',
  'game.badge.reason.crossed': '{material}, porque superaste el umbral de {threshold}: llevas {count}.',
  'game.badge.reason.served': '{material}, ganado al superar el umbral de {threshold}.',
  'game.badge.next': 'Faltan {missing} para la próxima estrella: {material}, en {threshold}.',
  'game.badge.complete': 'Las siete estrellas están encendidas: esta insignia está en Prisma.',
  'game.badge.ladder_title': 'Los siete niveles',
  'game.badge.rung.upcoming': 'En {threshold}',
  'game.badge.rung.next': 'Próxima estrella · faltan {missing}',
  'game.badge.upcoming_title': 'Lo que viene',
  'game.badge.guide_link': 'Entender las insignias',
} as const satisfies GameConceptCatalog;

export default es;
