import type { SessionsCatalog } from '@/lib/i18n-sessions-catalog';

const pt = {
  'sessions.title': 'Segurança',
  'sessions.back': 'Voltar',
  'sessions.section': 'Sessões',
  'sessions.intro': 'Os dispositivos conectados à sua conta. Encerre qualquer sessão que você não reconheça.',
  'sessions.current': 'Este dispositivo',
  'sessions.trusted': 'Dispositivo confiável',
  'sessions.unknownDevice': 'Dispositivo desconhecido',
  'sessions.field.app': 'Meeshy',
  'sessions.field.platform': 'Plataforma',
  'sessions.field.device': 'Dispositivo',
  'sessions.field.system': 'Sistema',
  'sessions.field.browser': 'Navegador',
  'sessions.field.ip': 'Endereço IP',
  'sessions.field.place': 'Local',
  'sessions.field.timezone': 'Fuso horário',
  'sessions.field.opened': 'Aberta em',
  'sessions.field.lastActive': 'Última atividade',
  'sessions.field.method': 'Login',
  'sessions.version': 'Versão {version}',
  'sessions.versionBuild': 'Versão {version} ({build})',
  'sessions.place.approximate': '{place} · aproximado',
  'sessions.platform.web': 'Navegador web',
  'sessions.platform.pwa': 'App web instalado',
  'sessions.platform.android-shell': 'App Android',
  'sessions.platform.ios': 'App iOS',
  'sessions.method.password': 'Senha',
  'sessions.method.two_factor': 'Senha e código de verificação',
  'sessions.method.magic_link': 'Link de acesso por e-mail',
  'sessions.method.registration': 'Cadastro',
  'sessions.method.email_verification': 'Verificação do e-mail',
  'sessions.method.oauth': 'Conta externa',
  'sessions.method.anonymous': 'Acesso sem conta',
  'sessions.revoke': 'Encerrar esta sessão',
  'sessions.revoke.label': 'Encerrar a sessão de {device}',
  'sessions.revoke.title': 'Encerrar esta sessão?',
  'sessions.revoke.body': '{device} será desconectado e precisará entrar novamente.',
  'sessions.revoke.done': 'Sessão encerrada',
  'sessions.revoke.error': 'Não foi possível encerrar a sessão. Tente novamente.',
  'sessions.others': 'Desconectar os outros dispositivos',
  'sessions.others.title': 'Desconectar os outros dispositivos?',
  'sessions.others.body': 'Todas as sessões, exceto esta, serão encerradas.',
  'sessions.others.done.one': 'Uma sessão encerrada',
  'sessions.others.done.other': '{count} sessões encerradas',
  'sessions.others.none': 'Nenhum outro dispositivo está conectado.',
  'sessions.others.error': 'Não foi possível encerrar as outras sessões. Tente novamente.',
  'sessions.cancel': 'Cancelar',
  'sessions.empty.title': 'Nenhuma sessão ativa',
  'sessions.empty.body': 'Seus dispositivos conectados aparecerão aqui.',
  'sessions.loading': 'Carregando sessões…',
  'sessions.error.title': 'Não foi possível carregar as sessões.',
  'sessions.error.retry': 'Tentar novamente',
  'sessions.offline': 'Offline: a lista pode estar desatualizada e nenhuma sessão pode ser encerrada.',
  'sessions.signedOut': 'Sua sessão expirou. Entre novamente para ver seus dispositivos.',
  'sessions.attribution.note': 'Locais aproximados, deduzidos do endereço IP.',
  'sessionEnd.title': 'Sessão encerrada',
  'sessionEnd.admin_revoke': 'Sua sessão foi encerrada pela equipe Meeshy.',
  'sessionEnd.admin_revoke.help': 'Se você acha que isso é um erro, fale conosco.',
  'sessionEnd.user_revoke': 'Esta sessão foi encerrada a partir de outro dos seus dispositivos.',
  'sessionEnd.password_changed': 'A senha da sua conta mudou. Entre com a nova.',
  'sessionEnd.logout': 'Você foi desconectado deste dispositivo.',
  'sessionEnd.logout_all_devices': 'Todas as sessões da sua conta foram encerradas.',
  'sessionEnd.session_expired': 'Sua sessão expirou. Entre novamente.',
  'sessionEnd.contact': 'Falar com a equipe',
  'sessionEnd.ok': 'Entendi',
} satisfies SessionsCatalog;

export default pt;
