/**
 * L'APPEL AUDIO ET VIDÉO (#6382) — tranche du catalogue `catalog-en.ts`,
 * extraite pour tenir le budget de taille (CLAUDE.md) : le catalogue la
 * RÉPAND. Libellés repris d'iOS (`CallView.swift`, `IncomingCallView.swift`).
 */
const enCall = {
  'call.action.menu': 'Call',
  'call.action.audio': 'Voice call',
  'call.action.video': 'Video call',
  'call.action.return': 'Return to call',
  'call.incoming.title.audio': 'Incoming call',
  'call.incoming.title.video': 'Incoming video call',
  'call.incoming.title.tab': '📞 Incoming call',
  'call.incoming.group': '{caller} is calling the group',
  'call.accept': 'Accept',
  'call.accept.audioOnly': 'Answer without video',
  'call.decline': 'Decline',
  'call.outgoing.ringing': 'Calling…',
  'call.outgoing.waiting': 'Waiting for the other person…',
  'call.connecting': 'Connecting…',
  'call.reconnecting': 'Reconnecting…',
  'call.mic.mute': 'Mute microphone',
  'call.mic.unmute': 'Unmute microphone',
  'call.mic.muted': 'Microphone off',
  'call.peer.muted': 'Contact muted',
  'call.camera.on': 'Turn camera on',
  'call.camera.off': 'Turn camera off',
  'call.camera.switch': 'Switch camera',
  'call.camera.peerOff': 'Camera off',
  'call.video.connecting': 'Connecting video…',
  'call.hangup': 'Hang up',
  'call.minimize': 'Minimize call',
  'call.expand': 'Return to call',
  'call.captions.on': 'Show captions',
  'call.captions.off': 'Hide captions',
  'call.quality.poor': 'Unstable connection',
  'call.ended.local': 'Call ended',
  'call.ended.remote': 'Call ended',
  'call.ended.rejected': 'Call declined',
  'call.ended.missed': 'No answer',
  'call.ended.busy': 'Line busy',
  'call.ended.connectionLost': 'Connection lost',
  'call.ended.failed': 'Call failed',
  'call.ended.permission': 'Allow the microphone to call',
  'call.retry': 'Try again',
  'call.close': 'Close',
  'call.waiting.from': '{caller} is calling you',
  'call.waiting.answer': 'Answer',
  'call.waiting.decline': 'Decline',
  'call.notice.alreadyInCall': 'A call is already in progress',
  'call.members': '{count} participants',
  'call.a11y.screen': 'Call with {name}',
  'call.bubble.callBack': 'Call back',
  'call.bubble.join': 'Join',
  'call.callBack.named': 'Call {name} back',
  'call.you': 'You',
} as const;

export default enCall;
