import type { GameRulesCatalog } from '@/lib/i18n-game-catalog';

/** LE CARNET DES RÈGLES ET SON ATLAS (#9542) — `game.rules.*`. Chargé avec la seule page « Comment ça marche ». Mêmes clés et mêmes paramètres que le français. */
const de = {
  'game.rules.1.title': 'Jede Aktion zählt',
  'game.rules.1.body': 'Schreiben, sprechen, veröffentlichen, reagieren, einladen: Jede nützliche Aktion bringt Punkte. Limits zählen deine Aktionen, nie deine Punkte: Boni, Flamme und Events erhöhen, was jede Aktion bringt.',
  'game.rules.2.title': 'Punkte machen das Level',
  'game.rules.2.body': '100 Level in 10 Stufen. Jedes Level verlangt etwas mehr als das vorherige.',
  'game.rules.3.title': 'Man prägt Meeshes',
  'game.rules.3.body': 'Ab 1.221 Punkten prägst du eine Meesh von Hand. Der Preis steigt mit der Zahl der bereits geprägten Meeshes.',
  'game.rules.4.title': 'Prägen lässt dich absteigen',
  'game.rules.4.body': 'Ausgegebene Punkte verlassen das Level. Die Abzeichen, die sie hielten, können erlöschen.',
  'game.rules.5.title': 'Dein Rang sinkt nie',
  'game.rules.5.body': 'Jede Prägung, jeder Rekord, jeder Erfolg bringt Ruhm. Ruhm bestimmt den Rang.',
  'game.rules.6.title': 'Der Schatz wird behalten oder ausgegeben',
  'game.rules.6.body': 'Deine Meeshes zu behalten lässt den Schatz wachsen. Sie auszugeben schützt die Flamme oder bringt Kosmetik.',
  'game.rules.7.title': 'Jeder Tag zählt',
  'game.rules.7.body': 'Drei Missionen, eine Truhe, eine Flamme, die wächst, solange du wiederkommst.',
  'game.rules.8.title': 'Wir halten es fest',
  'game.rules.8.body': 'Jeder große Moment wird mit Mee und Meo im Fortschrittsheft festgehalten.',
  'game.rules.page_title': 'So funktioniert es',
  'game.rules.intro': 'Acht Regeln, und das ganze Spiel passt hinein. Meo erklärt sie, Mee zeigt dir die Aktion.',
  'game.rules.section_rules': 'Die Regeln auf einer Seite',
  'game.rules.section_steps': 'Die sieben Schritte',
  'game.rules.atlas.title': 'Das Spiel in Bildern',
  'game.rules.atlas.meesh': 'Die Meesh',
  'game.rules.atlas.medals': 'Die Medaillen',
  'game.rules.atlas.trophies': 'Die Trophäen',
  'game.rules.atlas.rarities': 'Die Seltenheiten',
  'game.rules.atlas.obverse': 'Vorderseite',
  'game.rules.atlas.reverse': 'Rückseite',
  'game.rules.atlas.line.levels': 'Hundert Level in zehn Stufen: jede Stufe hat ihr eigenes Emblem und ihre Farbe.',
  'game.rules.atlas.line.meesh': 'Die Vorderseite trägt die Signatur; die Rückseite Mee und Meo, die Nummer und das Jahr. Gold bei jeder hundertsten, Prisma bei jeder tausendsten.',
  'game.rules.atlas.line.treasury': 'Wer seine Meeshes behält, füllt den Schatz: sechs Stufen zu erklimmen.',
  'game.rules.atlas.line.rank': 'Elf Ränge. Ruhm bringt sie, und ein Rang sinkt nie.',
  'game.rules.atlas.line.flame': 'Die Flamme wächst, solange du wiederkommst: fünf Formen.',
  'game.rules.atlas.line.league': 'Acht Edelsteine, einer pro Liga. Jede Woche misst du dich mit 29 anderen Spielern.',
  'game.rules.atlas.line.medals': 'Sieben Metalle, von Kupfer bis Prisma: das Metall zeigt, wie weit du gekommen bist. Ein erloschenes Abzeichen hinterlässt einen Abdruck.',
  'game.rules.atlas.line.trophies': 'Eine Trophäe erhält man in einem bestimmten Moment: Liga-Pokal, Saison-Pokal, Prestige, Flamme.',
  'game.rules.atlas.line.rarities': 'Fünf Seltenheitsstufen, jede Nacht gemessen. Keine bringt Punkte.',
  'game.rules.atlas.levels': 'Die zehn Stufen',
  'game.rules.atlas.treasury': 'Die Stufen des Schatzes',
  'game.rules.atlas.ranks': 'Die Wappen der Ränge',
  'game.rules.atlas.flames': 'Die fünf Flammen',
  'game.rules.atlas.leagues': 'Die acht Ligen',
  'game.rules.atlas.edition_gold': 'Goldausgabe · jede hundertste',
  'game.rules.atlas.edition_prism': 'Prismaausgabe · jede tausendste',
  'game.rules.atlas.shape_accumulation': 'Ansammlung',
  'game.rules.atlas.shape_record': 'Rekord',
  'game.rules.atlas.shape_collection': 'Sammlung',
  'game.rules.atlas.imprint': 'Abdruck',
  'game.rules.atlas.trophy_league': 'Ligapokal',
  'game.rules.atlas.trophy_season': 'Saisonpokal',
  'game.rules.atlas.trophy_prestige': 'Prestige-Trophäe',
  'game.rules.atlas.trophy_flame': 'Flammen-Trophäe',
  'game.rules.atlas.share_common': 'über 40 % der Konten',
  'game.rules.atlas.share_rare': '10 bis 40 % der Konten',
  'game.rules.atlas.share_epic': '2 bis 10 % der Konten',
  'game.rules.atlas.share_legendary': '0,2 bis 2 % der Konten',
  'game.rules.atlas.share_mythic': 'unter 0,2 % der Konten',
  'game.rules.atlas.rarity_glory': '+{glory} Ruhm',
  'game.rules.atlas.myth': 'Die ersten 100, die 1.000.000 Ruhm erreichen',
  'game.rules.badges.title': 'Die Abzeichen',
  'game.rules.badges.intro': 'Jedes Abzeichen zählt EINE bestimmte Geste: eine Sprachnachricht, eine Story, eine neue Freundschaft… Es gibt zwanzig, in fünf Familien geordnet.',
  'game.rules.badges.ladder': 'Jedes Abzeichen steigt über sieben Stufen. Bei jeder überschrittenen Schwelle wechselt es das Material und lässt einen Stern mehr leuchten.',
  'game.rules.badges.ribbon': 'Ab Gold trägt die Medaille ein Band; bei Prisma schillert ihr Email.',
  'game.rules.badges.imprint': 'Das Prägen einer Meesh kann ein Abzeichen erlöschen lassen: Es wird zu einem Abdruck, der zeigt, was zum Wiederentzünden fehlt.',
  'game.rules.badges.families': 'Die zwanzig Abzeichen nach Familie',
  'game.rules.badges.sheet': 'Tippe auf ein Abzeichen: Seine Karte sagt, was dafür zählt, sein Material und warum, und was bis zum nächsten Stern fehlt.',
} as const satisfies GameRulesCatalog;

export default de;
