import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const enStudioChrome = {
  'story.studio.more': 'More options',
  'story.studio.preview': 'Preview',
  'story.studio.preview.close': 'Close preview',
  'story.studio.page.remove.current': 'Delete this scene',
  'story.studio.postText': 'Post text',
  'story.studio.postText.placeholder': 'Write the post text…',
  'story.studio.postText.done': 'Done',
  'story.studio.tile.text': 'Text',
  'story.studio.tile.time': 'Time',
  'story.studio.rail.scene': 'Scene tools',
  'story.studio.timeline.unit': 's',
  'story.studio.tile.frame': 'Frame',
  'story.studio.undo': 'Undo',
  'story.studio.redo': 'Redo',
  'story.studio.frame': 'Frame',
  'story.studio.frame.media': 'The media',
  'story.studio.frame.around': 'Around the media',
  'story.studio.frame.fit': 'Fit',
  'story.studio.frame.fill': 'Fill',
  'story.studio.frame.fit.hint': 'Whole, placed in the 9:16 frame. Nothing is cropped.',
  'story.studio.frame.fill.hint': 'Covers the whole 9:16 frame, cropping the edges if needed.',
  'story.studio.backdrop.blur': 'Blur',
  'story.studio.backdrop.black': 'Black',
  'story.studio.backdrop.white': 'White',
  'story.studio.backdrop.indigo': 'Indigo',
  'story.studio.backdrop.sand': 'Sand',
  'story.studio.animated': 'Animated',
  'story.studio.timeline': 'Scene timeline',
  'story.studio.timeline.play': 'Play',
  'story.studio.timeline.pause': 'Pause',
  'story.studio.timeline.empty': 'Write a text or place a layer: each object gets its own track.',
  'story.studio.timeline.overlay': 'Layer',
  'story.studio.retouch.title': 'Edit the image',
  'story.studio.retouch.done': 'Done',
  'story.studio.retouch.cancel': 'Discard the edit',
  'composer.attachment.edit': 'Edit {name}',
  'story.studio.retouch.failed': 'The image could not be rendered.',
  'story.studio.timeline.enter': 'Enters here',
  'story.studio.timeline.exit': 'Leaves here',
  'story.studio.timeline.scrub': 'Move the playhead',
  'story.studio.timeline.track': 'Track of {name}',
  'story.studio.timeline.earlier': 'Earlier',
  'story.studio.timeline.later': 'Later',
  'story.studio.editor.filter': 'Filter',
  'story.studio.filter.vintage': 'Vintage',
  'story.studio.filter.bw': 'B&W',
  'story.studio.filter.warm': 'Warm',
  'story.studio.filter.cool': 'Cool',
  'story.studio.filter.dramatic': 'Dramatic',
  'story.studio.filter.vivid': 'Vivid',
  'story.studio.filter.fade': 'Fade',
  'story.studio.filter.chrome': 'Chrome',
  'story.studio.object.menu': 'Actions for {name}',
  'story.studio.object.raise': 'Bring forward',
  'story.studio.object.lower': 'Send backward',
  'story.studio.object.duplicate': 'Duplicate',
  'story.studio.object.edit': 'Edit',
  'story.studio.object.remove': 'Remove',
  'story.studio.edit.done': 'OK',
  'story.studio.pose.left': 'Move left',
  'story.studio.pose.right': 'Move right',
  'story.studio.pose.up': 'Move up',
  'story.studio.pose.down': 'Move down',
  'story.studio.objects.edit': 'Edit {name}',
  'story.studio.media.alt': 'Alt text',
  'story.studio.media.alt.placeholder': 'Describe this media for screen readers',
  'composer.reelOffer.title': 'Publish as a reel?',
  'composer.reelOffer.body': 'Your post has a single video: as a reel, it plays full screen in Reels.',
  'composer.reelOffer.reel': 'It’s a Reel',
  'composer.reelOffer.post': 'It’s a Post',
  'story.studio.tool.close': 'Close tool',
  'story.studio.camera.quick.holdFilm': 'Hold: film',
  'story.studio.camera.quick.videoOnly': 'Hold to film',
  'story.studio.camera.quick.photo': 'Take a photo',
  'story.studio.camera.quick.video': 'Film',
  'story.studio.camera.title': 'Camera',
  'story.studio.camera.close': 'Back to the scene',
  'story.studio.camera.flip': 'Switch camera',
  'story.studio.camera.flash': 'Flash',
  'story.studio.camera.shutter.photo': 'Take a photo',
  'story.studio.camera.shutter.start': 'Start recording',
  'story.studio.camera.shutter.stop': 'Stop recording',
  'story.studio.camera.hint.photo': 'Tap the screen: photo · hold the shutter: video',
  'story.studio.camera.hint.video': 'Tap to film · tap again to place',
  'story.studio.camera.unavailable': 'The camera isn’t available. Allow it in your browser settings.',
  'story.studio.camera.recording': 'Recording',
  'story.studio.scene.empty.title': 'This is your scene',
  'story.studio.scene.empty.invite': 'Drop in text, a drawing, a photo or a video — and make it yours.',
  'story.studio.camera.locked': 'Recording locked',
  'story.studio.camera.hint.holding': 'Slide to the lock to keep recording · up to zoom',
  'story.studio.camera.hint.locked': 'Hands-free — slide up or down to zoom',
  'story.studio.camera.flash.intensity': 'Flash intensity',
  'story.studio.camera.flash.intensityValue': '{percent}%',
  'story.studio.camera.quick.tapArm': 'Tap: open the camera',
  'story.studio.camera.quick.tapAgain': 'Tap again: photo',
  'story.studio.effect.column': 'Scene effects',
  'story.studio.effect.opening': 'Opening effect',
  'story.studio.effect.visual': 'Visual effect',
  'story.studio.effect.close': 'Close effects',
  'story.studio.effect.row.opening': 'Opening',
  'story.studio.effect.row.closing': 'Closing',
  'story.studio.transition.fade': 'Fade',
  'story.studio.transition.zoom': 'Zoom',
  'story.studio.transition.slide': 'Slide',
  'story.studio.transition.reveal': 'Reveal',
  'story.studio.object.options': 'Options for {name}',
  'story.studio.object.deselect': 'Deselect',
  'story.studio.object.setBackground': 'Set as background',
  'story.studio.object.replaceBackground': 'Replace background',
  'story.studio.background.menu.title': 'Scene background',
  'story.studio.background.menu.edit': 'Edit background',
  'story.studio.background.menu.retake': 'Retake a photo',
  'story.studio.background.menu.forward': 'Bring to foreground',
  'story.studio.background.menu.remove': 'Remove background',
  'story.studio.reelSwitch.announcement': 'Switched to a reel',
} satisfies StudioChromeCatalogSlice;

export default enStudioChrome;
