/**
 * L'EXPORT D'UN MESSAGE EN IMAGE, FRANÇAIS (#8667) — la SOURCE des clés du
 * composer d'export (`routes/thread-export-*.tsx`). Les six autres langues
 * portent exactement ces clés (`satisfies ExportCardCatalog`,
 * `i18n-export-card-catalog.test.ts`). Seules les deux entrées du menu du
 * message restent au catalogue d'interface (`catalog-fr-message-card.ts`) :
 * elles sont visibles avant que le composer ne soit chargé.
 */
const fr = {
  'export.card.title': 'Exporter en image',
  'export.card.popular': 'Populaires',
  'export.card.random': 'Au hasard',
  'export.card.palette': 'Couleurs',
  'export.card.typeface': 'Typographie',
  'export.card.link': 'Liaison',
  'export.card.typeface.rond': 'Ronde',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Plume',
  'export.card.typeface.affiche': 'Affiche',
  'export.card.typeface.futur': 'Futuriste',
  'export.card.typeface.machine': 'Machine à écrire',
  'export.card.typeface.marqueur': 'Marqueur',
  'export.card.typeface.systeme': 'Système',
  'export.card.link.orbite': 'Orbite',
  'export.card.link.filet': 'Filet',
  'export.card.link.guillemets': 'Guillemets',
  'export.card.link.fleche': 'Flèche',
  'export.card.link.bulles': 'Bulles',
  'export.card.link.fil': 'Fil',
  'export.card.link.silence': 'Silence',
  'export.card.option.anonymizeQuoted': 'Anonymiser le message cité',
  'export.card.option.anonymizeReply': 'Anonymiser la réponse',
  'export.card.anonymous': 'Anonyme',
  'export.card.preview': 'Aperçu de l’image',
  'export.card.rendering': 'Préparation de l’image…',
  'export.card.save': 'Sauvegarder',
  'export.card.share': 'Partager',
  'export.card.language': 'Langue du message',
  'export.card.language.asRead': 'Comme je le lis',
  'export.card.truncated': 'Message long : la fin est coupée sur l’image.',
  'export.announce.gallery': 'Image enregistrée dans la galerie',
  'export.announce.shared': 'Image prête',
  'export.announce.cancelled': 'Export annulé',
  'export.announce.expired': 'Touchez de nouveau pour enregistrer',
  'export.announce.failed': 'Impossible de créer l’image',
  'export.announce.unavailable': 'Cet appareil ne sait pas enregistrer l’image',
  'export.card.options': 'Afficher',
  'export.card.option.title': 'Titre de la conversation',
  'export.card.option.authors': 'Noms des auteurs',
  'export.card.option.date': 'Date',
  'export.card.default.save': 'Utiliser comme format par défaut',
  'export.card.default.current': 'Format par défaut',
  'export.announce.defaultSaved': 'Format par défaut enregistré',
  'export.card.tab.styles': 'Styles',
  'export.card.tab.palette': 'Fond',
  'export.card.tab.typeface': 'Police',
  'export.card.tab.link': 'Liaison',
  'export.card.tab.details': 'Détails',
  'export.card.tab.language': 'Langue',
  'export.card.part.header': 'En-tête',
  'export.card.part.quote': 'Citation',
  'export.card.part.link': 'Liaison',
  'export.card.part.reply': 'Réponse',
  'export.card.part.background': 'Fond',
  'export.card.hint': 'Touchez une partie de la carte pour la régler',
  'export.card.gallery.open': 'Tout voir',
  'export.card.gallery.title': 'Tous les styles',
  'export.card.gallery.count': '{count} styles',
  'export.card.gallery.close': 'Fermer la galerie',
  'export.card.gallery.search': 'Chercher un style',
  'export.card.gallery.placeholder': 'Plume, sombre, bulles…',
  'export.card.gallery.empty': 'Aucun style ne porte ce nom. Essayez une couleur, une police ou « sombre ».',
  'export.card.tone.all': 'Tous',
  'export.card.tone.dark': 'Sombre',
  'export.card.tone.light': 'Clair',
  'export.card.typeface.pairs': 'La police habille la citation et la réponse',
} as const;

export default fr;
