import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const arStudioChrome = {
  'story.studio.more': 'خيارات أخرى',
  'story.studio.preview': 'معاينة',
  'story.studio.preview.close': 'إغلاق المعاينة',
  'story.studio.page.remove.current': 'حذف هذا المشهد',
  'story.studio.postText': 'نص المنشور',
  'story.studio.postText.placeholder': 'اكتب نص المنشور…',
  'story.studio.postText.done': 'تم',
  'story.studio.tile.page': 'مشهد',
  'story.studio.tile.text': 'نص',
  'story.studio.tile.editor': 'الإعدادات',
  'story.studio.tile.frame': 'الإطار',
  'story.studio.undo': 'تراجع',
  'story.studio.redo': 'إعادة',
  'story.studio.frame': 'الإطار',
  'story.studio.frame.media': 'الوسائط',
  'story.studio.frame.around': 'حول الوسائط',
  'story.studio.frame.fit': 'ملاءمة',
  'story.studio.frame.fill': 'ملء',
  'story.studio.frame.fit.hint': 'كاملة داخل إطار 9:16. لا يُقصّ شيء.',
  'story.studio.frame.fill.hint': 'تغطي إطار 9:16 كله، مع قصّ الحواف عند الحاجة.',
  'story.studio.backdrop.blur': 'ضبابي',
  'story.studio.backdrop.black': 'أسود',
  'story.studio.backdrop.white': 'أبيض',
  'story.studio.backdrop.indigo': 'نيلي',
  'story.studio.backdrop.sand': 'رملي',
  'story.studio.animated': 'متحرك',
  'story.studio.timeline': 'الخط الزمني للمشهد',
  'story.studio.timeline.play': 'تشغيل',
  'story.studio.timeline.pause': 'إيقاف مؤقت',
  'story.studio.timeline.start': 'بداية {name}',
  'story.studio.timeline.end': 'نهاية {name}',
  'story.studio.timeline.empty': 'اكتب نصًا أو ضع طبقة: لكل عنصر مساره.',
  'story.studio.timeline.overlay': 'طبقة',
  'story.studio.retouch.title': 'تعديل الصورة',
  'story.studio.retouch.done': 'تم',
  'story.studio.retouch.cancel': 'تجاهل التعديل',
  'composer.attachment.edit': 'تعديل {name}',
  'story.studio.retouch.failed': 'تعذّر إنشاء الصورة.',
} satisfies StudioChromeCatalogSlice;

export default arStudioChrome;
