import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const de = {
  'admin.role': 'Deine Rolle: {role}',
  'admin.denied.title': 'Geschützter Bereich',
  'admin.denied.message': 'Dieser Bereich erfordert ein Verwaltungsrecht.',
  'admin.counters.title': 'Auf einen Blick',
  'admin.counters.unavailable': 'Zähler derzeit nicht verfügbar.',
  'admin.counters.users': 'Konten',
  'admin.counters.activeUsers': 'Aktive Konten',
  'admin.counters.messages': 'Nachrichten',
  'admin.counters.communities': 'Communities',
  'admin.counters.reports': 'Meldungen',
  'admin.counters.newUsers': 'Neu (24 Std.)',
  'admin.sections.title': 'Bereiche',
  'admin.nav.dashboard': 'Übersicht',
  'admin.nav.users': 'Konten',
  'admin.nav.moderation': 'Moderation',
  'admin.nav.audit': 'Audit-Protokolle',
  'admin.nav.analytics': 'Statistiken',
  'admin.nav.trackingLinks': 'Tracking-Links',
  'admin.nav.ranking': 'Rangliste',
  'admin.nav.broadcasts': 'Rundsendungen',
  'admin.nav.settings': 'Einstellungen',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Überwachung',
  'admin.users.search': 'Konto suchen',
  'admin.users.count': '{count} Konto/Konten',
  'admin.users.empty': 'Kein Konto passt.',
  'admin.users.unavailable': 'Liste derzeit nicht verfügbar.',
  'admin.users.inactive': 'deaktiviert',
  'admin.users.previous': 'Zurück',
  'admin.users.next': 'Weiter',
  'admin.user.title': 'Mitglied',
  'admin.user.unavailable': 'Profil derzeit nicht verfügbar.',
  'admin.user.identity': 'Identität',
  'admin.user.account': 'Konto',
  'admin.user.created': 'Beigetreten am',
  'admin.user.lastActive': 'Zuletzt aktiv',
  'admin.user.twoFactor': 'Zwei-Faktor',
  'admin.user.enabled': 'aktiviert',
  'admin.user.deleted': 'gelöscht',
  'admin.user.role': 'Rolle',
  'admin.edit.open': 'Bearbeiten',
  'admin.edit.title': 'Mitglied bearbeiten',
  'admin.edit.displayName': 'Anzeigename',
  'admin.edit.email': 'E-Mail',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Konto aktiv',
  'admin.edit.save': 'Speichern',
  'admin.edit.reason': 'Grund (optional)',
  'admin.edit.warnRole': 'Eine Rollenänderung ändert die Rechte.',
  'admin.edit.warnDeactivate': 'Deaktivieren beendet offene Sitzungen.',
  'admin.edit.confirm': 'Bestätigen',
  'admin.edit.saved': 'Änderungen gespeichert',
  'admin.edit.failed': 'Speichern fehlgeschlagen',
  'admin.password.title': 'Passwort zurücksetzen',
  'admin.password.warn': 'Damit enden alle offenen Sitzungen.',
  'admin.password.generated': 'Jetzt kopieren — es wird nicht erneut angezeigt.',
  'admin.password.copy': 'Kopieren',
  'admin.password.copied': 'Kopiert',
  'admin.password.apply': 'Zurücksetzen',
  'admin.password.done': 'Passwort zurückgesetzt',
  'admin.password.failed': 'Zurücksetzen fehlgeschlagen',
  'admin.password.level': 'Stufe',
  'admin.password.level.simple': 'Einfach',
  'admin.password.level.easy': 'Leicht',
  'admin.password.level.medium': 'Mittel',
  'admin.password.level.hard': 'Schwer',
  'admin.password.field': 'Passwort',
  'admin.password.editable': 'Stufe wählen oder eigenes eingeben: Was angezeigt wird, wird angewendet.',
  'admin.password.loading': 'Vorschläge werden vorbereitet…',
  'admin.password.proposals.failed': 'Vorschläge konnten nicht geladen werden: Passwort eingeben.',
  'admin.password.regenerate': 'Anderer Vorschlag',
  'admin.password.refused': 'Abgelehnt: {reason}',
  'admin.ban.open': 'Sperren',
  'admin.ban.title': 'Dieses Mitglied sperren',
  'admin.ban.reason': 'Grund (erforderlich)',
  'admin.ban.permanent': 'Dauerhafte Sperre',
  'admin.ban.until': 'Bis',
  'admin.ban.apply': 'Sperren',
  'admin.ban.lift': 'Aufheben',
  'admin.ban.active': 'aktiv',
  'admin.ban.expired': 'abgelaufen',
  'admin.ban.lifted': 'aufgehoben',
  'admin.ban.none': 'Keine Sperren',
  'admin.ban.done': 'Sperre gespeichert',
  'admin.ban.failed': 'Sperren fehlgeschlagen',
  'admin.media.title': 'Medien',
  'admin.media.empty': 'Keine Medien',
  'admin.media.protected': 'geschützt',
  'admin.media.fromPost': 'Beitrag',
  'admin.media.fromMessage': 'Nachricht',
  'admin.conv.title': 'Unterhaltungen',
  'admin.conv.empty': 'Keine Unterhaltungen',
  'admin.conv.members': '{count} Mitglieder',
  'admin.nav.conversations': 'Unterhaltungen',
  'admin.convList.search': 'Unterhaltung suchen',
  'admin.convList.count': '{count} Unterhaltung(en)',
  'admin.convList.empty': 'Keine Unterhaltung gefunden.',
  'admin.convList.unavailable': 'Liste derzeit nicht verfügbar.',
  'admin.convList.members': '{count} Mitglieder',
  'admin.convList.sovereign': 'Dem Admin-Rang vorbehalten.',
  'admin.convDetail.title': 'Eine Unterhaltung lesen',
  'admin.convDetail.reasonLabel': 'Grund des Lesens',
  'admin.convDetail.reasonHint': 'Mindestens zehn Zeichen, mit Ihrem Namen protokolliert.',
  'admin.convDetail.read': 'Unterhaltung lesen',
  'admin.convDetail.empty': 'Keine Nachricht',
  'admin.convDetail.memberPrism': 'Im Prisma des Mitglieds gelesen: {languages}',
  'admin.agent.title': 'Agentensteuerung',
  'admin.agent.denied': 'Diese Steuerung verlangt ein eigenes Recht.',
  'admin.agent.users': 'Geführte Mitglieder',
  'admin.agent.tracked': 'Begleitete Unterhaltungen',
  'admin.agent.empty': 'Nichts zu zeigen.',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Lauf aktiv: {node}',
  'admin.agent.relaunch': 'Agenten erneut starten',
  'admin.agent.effect': 'Wiederholt die Auswertung und kann eine Nachricht veröffentlichen.',
  'admin.agent.done': 'Start angefordert',
  'admin.agent.failed': 'Abgelehnt',
  'admin.agent.stop': 'Lauf anhalten',
  'admin.agent.halted': 'Lauf angehalten',
  'admin.agent.down': 'Agentendienst nicht erreichbar.',
  'admin.agent.logs': 'Lauf-Protokoll',
  'admin.nav.anonymous': 'Anonyme',
  'admin.shell.menu': 'Verwaltungsmenü',
  'admin.shell.fold': 'Menü einklappen',
  'admin.shell.unfold': 'Menü ausklappen',
  'admin.shell.open': 'Menü öffnen',
  'admin.shell.close': 'Menü schließen',
  'admin.shell.backToApp': 'Zurück zur App',
  'admin.list.filters': 'Filter',
  'admin.list.all': 'Alle',
  'admin.list.yes': 'Ja',
  'admin.list.no': 'Nein',
  'admin.list.reset': 'Zurücksetzen',
  'admin.list.pageSize': 'Pro Seite',
  'admin.list.range': '{from}–{to} von {total}',
  'admin.list.sortBy': 'Sortieren nach {column}',
  'admin.col.member': 'Mitglied',
  'admin.col.email': 'E-Mail',
  'admin.col.role': 'Rolle',
  'admin.col.status': 'Status',
  'admin.col.created': 'Registriert',
  'admin.col.lastActive': 'Zuletzt aktiv',
  'admin.col.joined': 'Beigetreten',
  'admin.col.language': 'Sprache',
  'admin.col.conversation': 'Unterhaltung',
  'admin.col.messages': 'Nachrichten',
  'admin.col.name': 'Name',
  'admin.filter.active': 'Aktiv',
  'admin.filter.inactive': 'Deaktiviert',
  'admin.filter.emailVerified': 'E-Mail bestätigt',
  'admin.filter.twoFactor': 'Zwei-Faktor',
  'admin.anonymous.search': 'Anonyme suchen',
  'admin.anonymous.empty': 'Kein Anonymer passt.',
  'admin.anonymous.unavailable': 'Liste derzeit nicht verfügbar.',
  'admin.anonymous.title': 'Anonymer Teilnehmer',
  'admin.anonymous.left': 'Verlassen',
  'admin.anonymous.permissions': 'Berechtigungen',
  'admin.anonymous.openConversation': 'Unterhaltung lesen',
  'admin.col.type': 'Typ',
  'admin.col.members': 'Mitglieder',
  'admin.col.createdOn': 'Erstellt',
  'admin.col.lastMessage': 'Letzte Nachricht',
  'admin.tab.profile': 'Profil',
  'admin.tab.conversations': 'Unterhaltungen',
  'admin.tab.media': 'Medien',
  'admin.tab.contacts': 'Kontakte',
  'admin.tab.communities': 'Communitys',
  'admin.tab.voice': 'Stimmprofil',
  'admin.tab.security': 'Sicherheit',
  'admin.tab.reports': 'Meldungen',
  'admin.tab.label': 'Abschnitte des Profils',
  'admin.dossier.empty': 'Nichts anzuzeigen.',
  'admin.dossier.restricted': 'Nur für Administratoren mit Zugriff auf sensible Daten.',
  'admin.contacts.sent': 'Gesendet',
  'admin.contacts.received': 'Empfangen',
  'admin.contacts.direction': 'Anfrage',
  'admin.contacts.links': '{share} Teilen-Link(s) · {tracking} Tracking-Link(s) · {affiliate} Partner-Token(s)',
  'admin.communities.creator': 'Ersteller',
  'admin.communities.private': 'Privat',
  'admin.voice.none': 'Kein Stimmprofil gespeichert.',
  'admin.voice.samples': 'Proben',
  'admin.voice.duration': 'Aufgenommene Dauer',
  'admin.voice.model': 'Modell',
  'admin.voice.consents': 'Einwilligungen',
  'admin.voice.consentProfile': 'Stimmprofil',
  'admin.voice.consentData': 'Stimmdaten',
  'admin.voice.consentCloning': 'Stimmklonen',
  'admin.voice.notGiven': 'nicht erteilt',
  'admin.voice.traced': 'Dieser Aufruf wird im Audit-Protokoll erfasst.',
  'admin.security.sessions': 'Sitzungen',
  'admin.security.events': 'Sicherheitsereignisse',
  'admin.security.device': 'Gerät',
  'admin.security.place': 'Ort',
  'admin.security.ip': 'IP-Adresse',
  'admin.security.valid': 'Offen',
  'admin.security.closed': 'Geschlossen',
  'admin.security.event': 'Ereignis',
  'admin.security.severity': 'Schwere',
  'admin.col.date': 'Datum',
  'admin.reports.filed': 'Meldungen dieses Mitglieds',
  'admin.reports.received': 'Gemeldete Nachrichten',
  'admin.reports.subject': 'Gegenstand',
  'admin.reports.reporter': 'Gemeldet von',
  'admin.reports.reason': 'Grund',
  'admin.reports.message': 'Nachricht',
  'admin.reports.withheld': 'Text nur für Moderation',
  'admin.anonymous.link': 'Beigetreten über Link',
  'admin.gallery.title': 'Bilder',
  'admin.gallery.empty': 'Keine Bilder',
  'admin.gallery.previous': 'Vorheriges Bild',
  'admin.gallery.next': 'Nächstes Bild',
  'admin.gallery.avatar': 'Profilbild',
  'admin.gallery.banner': 'Banner',
  'admin.gallery.position': 'Bild {n} von {total}',
  'admin.meta.title': 'Metadaten',
  'admin.meta.name': 'Vollständiger Name',
  'admin.meta.systemLanguage': 'Hauptsprache',
  'admin.meta.regionalLanguage': 'Zweitsprache',
  'admin.meta.customLanguage': 'Zielsprache',
  'admin.meta.timezone': 'Zeitzone',
  'admin.meta.emailVerified': 'E-Mail bestätigt am',
  'admin.meta.phoneVerified': 'Telefon bestätigt am',
  'admin.meta.completion': 'Profil vervollständigt',
  'admin.meta.passwordChanged': 'Passwort geändert am',
  'admin.meta.failedLogins': 'Fehlgeschlagene Anmeldungen',
  'admin.meta.lockedUntil': 'Gesperrt bis',
  'admin.meta.lockedReason': 'Sperrgrund',
  'admin.meta.deactivated': 'Deaktiviert am',
  'admin.meta.updated': 'Aktualisiert am',
  'admin.tab.preferences': 'Einstellungen',
  'admin.stats.title': 'In Zahlen',
  'admin.stats.messagesSent': 'Gesendete Nachrichten',
  'admin.stats.conversations': 'Unterhaltungen',
  'admin.stats.posts': 'Beiträge',
  'admin.stats.reels': 'Reels',
  'admin.stats.stories': 'Storys',
  'admin.stats.comments': 'Kommentare',
  'admin.stats.reactionsGiven': 'Reaktionen',
  'admin.stats.mediaUploaded': 'Hochgeladene Medien',
  'admin.stats.friends': 'Freunde',
  'admin.stats.pendingIn': 'Erhaltene Anfragen',
  'admin.stats.pendingOut': 'Gesendete Anfragen',
  'admin.stats.reportsFiled': 'Eingereichte Meldungen',
  'admin.stats.reportsReceived': 'Erhaltene Meldungen',
  'admin.stats.activeSessions': 'Aktive Sitzungen',
  'admin.stats.communities': 'Communitys',
  'admin.prefs.privacy': 'Datenschutz',
  'admin.prefs.notification': 'Benachrichtigungen',
  'admin.prefs.message': 'Nachrichten',
  'admin.prefs.audio': 'Audio und Stimme',
  'admin.prefs.video': 'Video',
  'admin.prefs.document': 'Dokumente',
  'admin.prefs.application': 'App',
  'admin.prefs.notice': 'Jede Änderung gilt auf allen Geräten des Mitglieds und wird im Audit-Protokoll festgehalten.',
  'admin.prefs.readOnly': 'schreibgeschützt',
  'admin.prefs.saved': 'Einstellung gespeichert',
  'admin.prefs.failed': 'Die Einstellung konnte nicht gespeichert werden',
  'admin.prefs.consent': 'Abgelehnt: Das Mitglied hat die für diese Option nötige Einwilligung nicht erteilt',
  'admin.prefs.reserved': 'Abgelehnt: Ihre Rolle darf dieses Mitglied nicht ändern',
  'admin.prefs.invalid': 'Abgelehnt: ungültiger Wert',
  'admin.list.sort': 'Sortierung',
  'admin.list.order': 'Reihenfolge',
  'admin.list.newest': 'Neueste zuerst',
  'admin.list.oldest': 'Älteste zuerst',
  'admin.conv.manage': 'Verwalten',
  'admin.conv.role.admin': 'Administrator',
  'admin.conv.role.moderator': 'Moderator',
  'admin.conv.role.member': 'Mitglied',
  'admin.conv.configure': 'Konfigurieren',
  'admin.convSettings.title': 'Unterhaltung konfigurieren',
  'admin.convSettings.titleField': 'Titel',
  'admin.convSettings.description': 'Beschreibung',
  'admin.convSettings.avatar': 'Bild (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Wer schreiben darf',
  'admin.convSettings.writeRole.everyone': 'Alle',
  'admin.convSettings.writeRole.member': 'Mitglieder',
  'admin.convSettings.writeRole.moderator': 'Moderatoren und höher',
  'admin.convSettings.writeRole.admin': 'Administratoren und höher',
  'admin.convSettings.writeRole.creator': 'Nur der Ersteller',
  'admin.convSettings.announcement': 'Ankündigungskanal',
  'admin.convSettings.slowMode': 'Langsamer Modus (Sekunden)',
  'admin.convSettings.autoTranslate': 'Automatische Übersetzung',
  'admin.convSettings.archive': 'Archivieren',
  'admin.convSettings.restore': 'Wiederherstellen',
  'admin.convSettings.close': 'Für Nachrichten schließen',
  'admin.convSettings.reopen': 'Wieder öffnen',
  'admin.convSettings.memberRole': 'Rolle dieses Mitglieds',
  'admin.convSettings.remove': 'Aus der Unterhaltung entfernen',
  'admin.convSettings.reason': 'Grund (mindestens 10 Zeichen)',
  'admin.convSettings.confirm': 'Bestätigen',
  'admin.convSettings.save': 'Speichern',
  'admin.convSettings.saved': 'Unterhaltung aktualisiert',
  'admin.convSettings.removed': 'Mitglied entfernt',
  'admin.convSettings.failed': 'Änderung abgelehnt',
  'admin.convSettings.creatorProtected': 'Der Ersteller kann weder herabgestuft noch entfernt werden',
} satisfies AdminInterfaceCatalog;

export default de;
