import type { ExportCardCatalog } from '@/lib/i18n-export-card-catalog';

const it = {
  'export.card.title': 'Imagine',
  'export.card.popular': 'Popolari',
  'export.card.random': 'A caso',
  'export.card.palette': 'Colori',
  'export.card.typeface': 'Carattere',
  'export.card.link': 'Collegamento',
  'export.card.typeface.rond': 'Tondo',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Piuma',
  'export.card.typeface.affiche': 'Manifesto',
  'export.card.typeface.futur': 'Futurista',
  'export.card.typeface.machine': 'Macchina da scrivere',
  'export.card.typeface.marqueur': 'Pennarello',
  'export.card.typeface.systeme': 'Sistema',
  'export.card.link.orbite': 'Orbita',
  'export.card.link.filet': 'Filetto',
  'export.card.link.guillemets': 'Virgolette',
  'export.card.link.fleche': 'Freccia',
  'export.card.link.bulles': 'Bolle',
  'export.card.link.fil': 'Filo',
  'export.card.link.silence': 'Silenzio',
  'export.card.option.anonymizeQuoted': 'Anonimizza il messaggio citato',
  'export.card.option.anonymizeReply': 'Anonimizza la risposta',
  'export.card.anonymous': 'Anonimo',
  'export.card.preview': 'Anteprima dell’immagine',
  'export.card.rendering': 'Preparazione dell’immagine…',
  'export.card.save': 'Salva',
  'export.card.share': 'Condividi',
  'export.card.language': 'Lingua del messaggio',
  'export.card.language.asRead': 'Come lo leggo',
  'export.card.truncated': 'Messaggio lungo: la fine è tagliata nell’immagine.',
  'export.announce.gallery': 'Immagine salvata nella galleria',
  'export.announce.shared': 'Immagine pronta',
  'export.announce.cancelled': 'Esportazione annullata',
  'export.announce.expired': 'Tocca di nuovo per salvare',
  'export.announce.failed': 'Impossibile creare l’immagine',
  'export.announce.unavailable': 'Questo dispositivo non può salvare l’immagine',
  'export.card.options': 'Mostra',
  'export.card.option.title': 'Titolo della conversazione',
  'export.card.option.authors': 'Nomi degli autori',
  'export.card.option.date': 'Data',
  'export.card.default.save': 'Usa come formato predefinito',
  'export.card.default.current': 'Formato predefinito',
  'export.announce.defaultSaved': 'Formato predefinito salvato',
  'export.card.tab.styles': 'Stili',
  'export.card.tab.palette': 'Sfondo',
  'export.card.tab.typeface': 'Carattere',
  'export.card.tab.link': 'Legame',
  'export.card.tab.details': 'Dettagli',
  'export.card.tab.language': 'Lingua',
  'export.card.part.header': 'Intestazione',
  'export.card.part.quote': 'Citazione',
  'export.card.part.link': 'Legame',
  'export.card.part.reply': 'Risposta',
  'export.card.part.background': 'Sfondo',
  'export.card.hint': 'Tocca una parte della scheda per regolarla',
  'export.card.gallery.open': 'Vedi tutti',
  'export.card.gallery.title': 'Tutti gli stili',
  'export.card.gallery.count': '{count} stili',
  'export.card.gallery.close': 'Chiudi la galleria',
  'export.card.gallery.search': 'Cerca uno stile',
  'export.card.gallery.placeholder': 'Piuma, scuro, bolle…',
  'export.card.gallery.empty': 'Nessuno stile ha questo nome. Prova un colore, un carattere o «scuro».',
  'export.card.tone.all': 'Tutti',
  'export.card.tone.dark': 'Scuro',
  'export.card.tone.light': 'Chiaro',
  'export.card.typeface.pairs': 'Il carattere veste la citazione e la risposta',
  'export.card.tab.frame': 'Cornice',
  'export.card.tab.media': 'Media',
  'export.card.part.media': 'Media',
  'export.card.part.replies': 'Risposte',
  'export.card.aspect': 'Formato immagine',
  'export.card.aspect.auto': 'Adattato',
  'export.card.aspect.story': 'Storia 9:16',
  'export.card.aspect.portrait': 'Verticale 4:5',
  'export.card.aspect.square': 'Quadrato 1:1',
  'export.card.aspect.landscape': 'Orizzontale 16:9',
  'export.card.header': 'Titolo e data',
  'export.card.header.horizontal': 'In linea',
  'export.card.header.letters': 'Lettera per lettera',
  'export.card.header.up': 'Verso l’alto',
  'export.card.header.down': 'Verso il basso',
  'export.card.authorsAt': 'Nomi',
  'export.card.authorsAt.top': 'Sopra il messaggio',
  'export.card.authorsAt.end': 'Alla fine del messaggio',
  'export.card.tilt': 'Rotazione del messaggio',
  'export.card.tilt.none': 'Dritto',
  'export.card.tilt.left': 'Inclinato a sinistra',
  'export.card.tilt.right': 'Inclinato a destra',
  'export.card.option.times': 'Orari dei messaggi',
  'export.card.option.pseudonyms': 'Nome utente invece del nome visualizzato',
  'export.card.anonymity': 'Anonimato',
  'export.card.media.style': 'Disposizione delle immagini',
  'export.card.media.mosaique': 'Mosaico',
  'export.card.media.pleine': 'Larghezza piena',
  'export.card.media.bande': 'Striscia',
  'export.card.audio.style': 'Rappresentazione dell’audio',
  'export.card.audio.onde': 'Onda',
  'export.card.audio.spectre': 'Spettro',
  'export.card.audio.pastille': 'Pastiglia',
  'export.card.audio.etiquette': 'Etichetta',
  'export.card.media.loading': 'Caricamento dei media…',
  'export.card.media.failed.one': 'Un contenuto multimediale non si è caricato.',
  'export.card.media.failed.other': '{count} contenuti multimediali non si sono caricati.',
  'export.card.media.retry': 'Riprova',
  'export.card.output': 'Salva come',
  'export.card.output.image': 'Immagine',
  'export.card.output.gif': 'GIF',
  'export.card.output.video': 'Video',
  'export.card.motion.video': 'Creazione del video…',
  'export.card.motion.gif': 'Creazione della GIF…',
  'export.announce.motionUnavailable': 'Questo browser non può creare questa animazione',
  'export.announce.galleryMotion': 'Salvato nella galleria',
  'export.announce.sharedMotion': 'Pronto da condividere',
} satisfies ExportCardCatalog;

export default it;
