import type { GameRulesCatalog } from '@/lib/i18n-game-catalog';

/** LE CARNET DES RÈGLES ET SON ATLAS (#9542) — `game.rules.*`. Chargé avec la seule page « Comment ça marche ». Mêmes clés et mêmes paramètres que le français. */
const es = {
  'game.rules.1.title': 'Cada gesto cuenta',
  'game.rules.1.body': 'Escribir, hablar, publicar, reaccionar, invitar: cada acción útil da puntos.',
  'game.rules.2.title': 'Los puntos hacen el nivel',
  'game.rules.2.body': '100 niveles en 10 tramos. Cada nivel pide un poco más que el anterior.',
  'game.rules.3.title': 'Se acuñan Meeshes',
  'game.rules.3.body': 'A partir de 1.221 puntos, se acuña una Meesh a mano. El precio sube con el número de Meeshes ya acuñadas.',
  'game.rules.4.title': 'Acuñar hace bajar',
  'game.rules.4.body': 'Los puntos gastados salen del nivel. Las insignias que sostenían pueden apagarse.',
  'game.rules.5.title': 'Tu rango nunca baja',
  'game.rules.5.body': 'Cada acuñación, cada récord, cada logro suma Gloria. La Gloria da el rango.',
  'game.rules.6.title': 'El tesoro se guarda o se gasta',
  'game.rules.6.body': 'Guardar tus Meeshes hace crecer el tesoro. Gastarlas protege la Llama u ofrece cosméticos.',
  'game.rules.7.title': 'Cada día cuenta',
  'game.rules.7.body': 'Tres misiones, un cofre, una Llama que crece mientras vuelvas.',
  'game.rules.8.title': 'Se guarda un recuerdo',
  'game.rules.8.body': 'Cada gran momento se fotografía con Mee y Meo en el cuaderno de progreso.',
  'game.rules.page_title': 'Cómo funciona',
  'game.rules.intro': 'Ocho reglas, y todo el juego cabe en ellas. Meo las explica, Mee te muestra el gesto.',
  'game.rules.section_rules': 'Las reglas en una página',
  'game.rules.section_steps': 'Los siete pasos',
  'game.rules.atlas.title': 'El juego en imágenes',
  'game.rules.atlas.meesh': 'La Meesh',
  'game.rules.atlas.medals': 'Las medallas',
  'game.rules.atlas.trophies': 'Los trofeos',
  'game.rules.atlas.rarities': 'Las rarezas',
  'game.rules.atlas.obverse': 'Anverso',
  'game.rules.atlas.reverse': 'Reverso',
  'game.rules.atlas.line.levels': 'Cien niveles en diez etapas: cada etapa tiene su emblema y su color.',
  'game.rules.atlas.line.meesh': 'El anverso lleva la Firma; el reverso, a Mee y Meo, el número y el año. De oro cada cien, de prisma cada mil.',
  'game.rules.atlas.line.treasury': 'Guardar tus Meeshes llena el tesoro: seis niveles por subir.',
  'game.rules.atlas.line.rank': 'Once rangos. La Gloria los da, y un rango nunca baja.',
  'game.rules.atlas.line.flame': 'La Llama crece mientras vuelves: cinco formas.',
  'game.rules.atlas.line.league': 'Ocho gemas, una por liga. Cada semana te mides con otros 29 jugadores.',
  'game.rules.atlas.line.medals': 'Siete metales, del cobre al prisma: el metal muestra hasta dónde llegaste. Una insignia que se apaga deja una huella.',
  'game.rules.atlas.line.trophies': 'Un trofeo se recibe en un momento preciso: copa de liga, de temporada, Prestigio, Llama.',
  'game.rules.atlas.line.rarities': 'Cinco rarezas, medidas cada noche. Ninguna da puntos.',
  'game.rules.atlas.levels': 'Los diez tramos',
  'game.rules.atlas.treasury': 'Los escalones del tesoro',
  'game.rules.atlas.ranks': 'Los escudos de los rangos',
  'game.rules.atlas.flames': 'Las cinco Llamas',
  'game.rules.atlas.leagues': 'Las ocho ligas',
  'game.rules.atlas.edition_gold': 'Edición oro · cada centésima',
  'game.rules.atlas.edition_prism': 'Edición prisma · cada milésima',
  'game.rules.atlas.shape_accumulation': 'Acumulación',
  'game.rules.atlas.shape_record': 'Récord',
  'game.rules.atlas.shape_collection': 'Colección',
  'game.rules.atlas.imprint': 'Huella',
  'game.rules.atlas.trophy_league': 'Copa de liga',
  'game.rules.atlas.trophy_season': 'Copa de temporada',
  'game.rules.atlas.trophy_prestige': 'Trofeo de Prestigio',
  'game.rules.atlas.trophy_flame': 'Trofeo de Llama',
  'game.rules.atlas.share_common': 'más del 40 % de las cuentas',
  'game.rules.atlas.share_rare': 'del 10 al 40 % de las cuentas',
  'game.rules.atlas.share_epic': 'del 2 al 10 % de las cuentas',
  'game.rules.atlas.share_legendary': 'del 0,2 al 2 % de las cuentas',
  'game.rules.atlas.share_mythic': 'menos del 0,2 % de las cuentas',
  'game.rules.atlas.rarity_glory': '+{glory} de Gloria',
  'game.rules.atlas.myth': 'Los 100 primeros en alcanzar 1 000 000 de Gloria',
  'game.rules.badges.title': 'Las insignias',
  'game.rules.badges.intro': 'Cada insignia cuenta UN gesto concreto: un mensaje de voz, una historia, una amistad nueva… Hay veinte, agrupadas en cinco familias.',
  'game.rules.badges.ladder': 'Cada insignia sube siete niveles. Cada vez que superas un umbral, cambia de material y enciende una estrella más.',
  'game.rules.badges.ribbon': 'Desde el Oro, la medalla lleva una cinta; en Prisma, su esmalte se vuelve iridiscente.',
  'game.rules.badges.imprint': 'Acuñar una Meesh puede apagar una insignia: se vuelve una huella que dice lo que falta para volver a encenderla.',
  'game.rules.badges.families': 'Las veinte insignias, por familia',
  'game.rules.badges.sheet': 'Toca una insignia: su ficha dice lo que cuenta para ella, su material y por qué, y lo que falta para la próxima estrella.',
} as const satisfies GameRulesCatalog;

export default es;
