import type { GameCoreCatalog } from '@/lib/i18n-game-catalog';

/** Le catalogue du jeu, it (#9379) — mêmes clés et mêmes paramètres que le français ; textes de l'app iOS quand elle les porte. */
const it = {
  'game.points.convertible.one': '{count} punto convertibile',
  'game.points.convertible.other': '{count} punti convertibili',
  'game.actions.one': '{count} azione',
  'game.actions.other': '{count} azioni',
  'game.levels.one': '{count} livello',
  'game.levels.other': '{count} livelli',
  'game.mint.badges.one': '{count} badge scende',
  'game.mint.badges.other': '{count} badge scendono',
  'game.mint.badges.none': 'Nessun badge si spegne',
  'game.treasury.bourse': 'Borsa',
  'game.treasury.escarcelle': 'Scarsella',
  'game.treasury.coffret': 'Scrigno',
  'game.treasury.coffre': 'Forziere',
  'game.treasury.tresor': 'Tesoro',
  'game.treasury.reserve': 'Riserva',
  'game.flame.form.braise': 'Brace',
  'game.flame.form.flamme': 'Fiamma',
  'game.flame.form.brasier': 'Falò',
  'game.flame.form.astre': 'Astro',
  'game.flame.form.soleil': 'Sole',
  'game.edition.silver': 'argento',
  'game.edition.gold': 'oro',
  'game.edition.prism': 'prisma',
  'game.difficulty.easy': 'Facile',
  'game.difficulty.medium': 'Media',
  'game.difficulty.hard': 'Difficile',
  'game.difficulty.gold': 'Oro',
  'game.mission.react_messages.one': 'Reagire a {count} messaggio in una conversazione',
  'game.mission.react_messages.other': 'Reagire a {count} messaggi nelle tue conversazioni',
  'game.mission.send_voice.one': 'Invia un messaggio vocale',
  'game.mission.send_voice.other': 'Invia {count} messaggi vocali',
  'game.mission.send_texts.one': 'Invia {count} messaggio',
  'game.mission.send_texts.other': 'Invia {count} messaggi',
  'game.mission.use_stickers.one': 'Invia uno sticker',
  'game.mission.use_stickers.other': 'Invia {count} sticker',
  'game.mission.send_attachments.one': 'Invia un allegato',
  'game.mission.send_attachments.other': 'Invia {count} allegati',
  'game.mission.comment_text.one': 'Commentare il post di qualcuno',
  'game.mission.comment_text.other': 'Commentare {count} post di altri',
  'game.mission.publish_story.one': 'Pubblica una storia',
  'game.mission.publish_story.other': 'Pubblica {count} storie',
  'game.mission.publish_post.one': 'Pubblica un post',
  'game.mission.publish_post.other': 'Pubblica {count} post',
  'game.mission.share_link.one': 'Condividere un post',
  'game.mission.share_link.other': 'Condividere {count} post',
  'game.mission.prism_foreign_messages.one': 'Scrivi un messaggio in una lingua diversa dalla tua',
  'game.mission.prism_foreign_messages.other': 'Scrivi {count} messaggi in una lingua diversa dalla tua',
  'game.mission.voice_comments.one': 'Lascia un commento vocale',
  'game.mission.voice_comments.other': 'Lascia {count} commenti vocali',
  'game.mission.publish_reel.one': 'Pubblica un reel',
  'game.mission.publish_reel.other': 'Pubblica {count} reel',
  'game.mission.reply_conversations': 'Rispondi in {count} conversazioni diverse',
  'game.mission.prism_foreign_exchange': 'Scrivi {count} messaggi in una lingua diversa dalla tua',
  'game.mission.long_chat': 'Invia {count} messaggi',
  'game.mission.gold_replies_received': 'Ricevi risposte da {count} persone diverse',
  'game.mission.react_posts.one': 'Reagire a un post',
  'game.mission.react_posts.other': 'Reagire a {count} post',
  'game.mission.reply_story.one': 'Rispondere a una storia',
  'game.mission.reply_story.other': 'Rispondere a {count} storie',
  'game.mission.join_community.one': 'Unirti a una community',
  'game.mission.join_community.other': 'Unirti a {count} community',
  'game.mission.write_conversations.one': 'Scrivere in una conversazione',
  'game.mission.write_conversations.other': 'Scrivere in {count} conversazioni diverse',
  'game.mission.write_someone_new.one': 'Scrivere a qualcuno per la prima volta',
  'game.mission.write_someone_new.other': 'Scrivere a {count} persone per la prima volta',
  'game.mission.start_conversation.one': 'Avviare una conversazione',
  'game.mission.start_conversation.other': 'Avviare {count} conversazioni',
  'game.mission.community_hello.one': 'Presentarti in una community',
  'game.mission.community_hello.other': 'Presentarti in {count} community',
  'game.mission.comment_stranger_post.one': 'Commentare il post pubblico di qualcuno che non conosci',
  'game.mission.comment_stranger_post.other': 'Commentare {count} post pubblici di persone che non conosci',
  'game.mission.cross_language_chat.one': 'Parlare con qualcuno che parla un’altra lingua',
  'game.mission.cross_language_chat.other': 'Parlare con {count} persone che parlano un’altra lingua',
  'game.mission.reply_their_language.one': 'Rispondere a qualcuno nella sua lingua',
  'game.mission.reply_their_language.other': 'Rispondere {count} volte a qualcuno nella sua lingua',
  'game.mission.create_invite_link.one': 'Creare il tuo link d’invito',
  'game.mission.create_invite_link.other': 'Creare {count} link d’invito',
  'game.mission.invite_contact.one': 'Invitare un contatto su Meeshy',
  'game.mission.invite_contact.other': 'Invitare {count} contatti su Meeshy',
  'game.mission.invite_joined.one': 'Far entrare in Meeshy una persona invitata',
  'game.mission.invite_joined.other': 'Far entrare in Meeshy {count} persone invitate',
  'game.mission.generic': 'Missione del giorno',
  'game.error.insufficient_points': 'Non hai abbastanza punti convertibili per coniare una Meesh.',
  'game.error.insufficient_meeshes': 'Per questo ti serve una Meesh in più.',
  'game.error.freeze_at_maximum': 'Hai già due congelamenti di riserva: è il massimo.',
  'game.error.relight_not_allowed': 'La Fiamma non può essere riaccesa adesso.',
  'game.error.mission_not_found': 'Questa missione non esiste più: la schermata si aggiorna.',
  'game.error.mission_reroll_exhausted': 'Hai già cambiato una missione oggi.',
  'game.error.mission_reroll_unavailable': 'Questa missione non può essere cambiata.',
  'game.error.missions_locked': 'Le missioni si aprono al livello 5.',
  'game.error.chest_not_ready': 'Completa prima le missioni del giorno per aprire il forziere.',
  'game.error.generic': 'Non è andata a buon fine: controlla la connessione e riprova.',
  'game.chest.chance': '1 possibilità su {odds}',
  'game.chest.reward.fragment': 'Un frammento di Meesh',
  'game.chest.reward.freeze': 'Un congelamento della Fiamma',
  'game.flame_panel.title': 'Proteggere la Fiamma',
  'game.flame_panel.bonus': '+{perDay} % per ogni giorno di serie sulle ricompense delle missioni, fino a\u00a0+{max} %.',
  'game.flame_panel.freezes': 'Congelamenti di riserva: {held} / {max}',
  'game.flame_panel.offline': 'Offline: congelamenti e riaccensione riprenderanno con la connessione.',
  'game.flame_panel.freeze_full': 'Riserva piena: un congelamento copre un giorno saltato, non te ne serve un altro.',
  'game.flame_panel.freeze_buy': 'Compra un congelamento · {price}',
  'game.flame_panel.relight_intro': 'La tua Fiamma si è spenta: riaccendila adesso, riparte da dove si era fermata.',
  'game.flame_panel.relight': 'Riaccendi la Fiamma · {price}',
  'game.flame_panel.relight_missing_window': 'Per riaccenderla ti serve {missing}, se si è spenta meno di 48 ore fa.',
  'game.flame_panel.relight_closed': 'Questa Fiamma non può più essere riaccesa. Una nuova Fiamma inizia con il tuo prossimo gesto.',
  'game.gauge.level': 'Livello',
  'game.level.title': 'Livello {level} · {tier}',
  'game.level.top': 'Sei in cima.',
  'game.level.capped': 'Tetto raggiunto: il grado {rank} apre il seguito.',
  'game.level.to_next': 'Ancora {points} al livello {level}',
  'game.level.record': 'Record: livello {level}',
  'game.level.tailwind': ' · Vento in poppa ×{factor}',
  'game.gauge.rank': 'Rango',
  'game.rank.glory': 'Gloria {glory}',
  'game.rank.top': 'Il rango più alto',
  'game.rank.next': 'Ancora {missing} di Gloria prima di {rank}',
  'game.gauge.treasury': 'Tesoro',
  'game.treasury.hint': 'Tieni le tue Meesh: riempiono il tuo tesoro',
  'game.treasury.next': 'Ancora {missing} per {tier}',
  'game.gauge.flame': 'Fiamma',
  'game.flame.no_streak': 'Nessuna serie',
  'game.flame.form_line': '{form} ·\u00a0+{bonus} % sulle missioni',
  'game.flame.out_line': 'Fiamma spenta',
  'game.flame.status.none': 'Un gesto oggi accende la tua Fiamma',
  'game.flame.status.at_risk': 'Fai un gesto prima di mezzanotte',
  'game.flame.status.covered': 'Un congelamento la protegge',
  'game.flame.status.out': 'Spenta',
  'game.guide.speaker.mee': 'Mee',
  'game.guide.speaker.meo': 'Meo',
  'game.guide.speaker.duo': 'Mee e Meo',
  'game.guide.step_of': 'Passo {index} di {total}',
  'game.guide.more': 'Vedi la spiegazione completa',
  'game.guide.dismiss': 'Più tardi',
  'game.guide.skip': 'Salta',
  'game.guide.photo': 'Immortala questo momento',
  'game.guide.skip_all': 'Salta l’introduzione',
  'game.guide.action.start_game': 'Inizia il gioco',
  'game.guide.action.earn_first_points': 'Fai il mio primo gesto',
  'game.guide.action.see_level': 'Vedi il mio livello',
  'game.guide.action.see_missions': 'Vedi le missioni',
  'game.guide.action.see_flame': 'Vedi la mia Fiamma',
  'game.guide.action.see_meeshes': 'Vedi le Meesh',
  'game.guide.action.see_rank': 'Vedi il mio rango',
  'game.guide.action.take_start_photo': 'Scatta la foto di partenza',
  'game.guide.action.see_progress': 'Vedi i miei progressi',
  'game.guide.action.see_next_tier': 'Vedi la fascia successiva',
  'game.guide.action.open_first_mission': 'Apri la mia prima missione',
  'game.guide.action.mint_or_climb': 'Vedi l’anteprima del conio',
  'game.guide.action.regain_levels': 'Riprendi i miei livelli',
  'game.guide.action.relight_badge': 'Vedi i miei badge',
  'game.guide.action.see_mint_preview': 'Vedi l’anteprima del conio',
  'game.guide.action.take_photo': 'Immortala questo momento',
  'game.guide.action.keep_or_spend': 'Vedi il mio tesoro',
  'game.guide.action.do_easy_mission_or_freeze': 'Vedi le mie missioni',
  'game.guide.action.relight_flame': 'Riaccendi la Fiamma',
  'game.guide.action.do_easiest_mission': 'Vedi la missione più facile',
  'game.guide.action.prestige_or_stay': 'Vedi il mio livello',
  'game.guide.moment.first_level.what': 'Il tuo primo livello è conquistato.',
  'game.guide.moment.first_level.means': 'I tuoi punti riempiono l’anello: quando è pieno, sali di livello.',
  'game.guide.moment.first_level.next': 'Ancora {points} per il livello {level}.',
  'game.guide.moment.first_level.short': 'Livello {level}: ancora {points} per il prossimo.',
  'game.guide.moment.new_tier.what': 'Entri in {tier}!',
  'game.guide.moment.new_tier.means': 'Le fasce segnano il tuo cammino: dieci livelli ciascuna.',
  'game.guide.moment.new_tier.next': 'La fascia successiva si apre al livello {level}.',
  'game.guide.moment.new_tier.next_last': 'Sei all’ultima fascia.',
  'game.guide.moment.new_tier.short': 'Fascia {tier} raggiunta.',
  'game.guide.moment.missions_unlocked.what': 'Le missioni sono sbloccate.',
  'game.guide.moment.missions_unlocked.means': 'Tre missioni al giorno e un forziere da aprire quando le completi.',
  'game.guide.moment.missions_unlocked.next': 'Apri la tua prima missione.',
  'game.guide.moment.missions_unlocked.short': 'Le tue missioni del giorno ti aspettano.',
  'game.guide.moment.first_mint_possible.what': 'Puoi coniare la tua prima Meesh.',
  'game.guide.moment.first_mint_possible.means_free': 'Coniare costa {price}, senza perdere alcun livello, e fa guadagnare\u00a0+{glory} di Gloria.',
  'game.guide.moment.first_mint_possible.means': 'Coniare costa {price}, cioè {levels}, e fa guadagnare\u00a0+{glory} di Gloria.',
  'game.guide.moment.first_mint_possible.next': 'Conia ora, o sali prima.',
  'game.guide.moment.first_mint_possible.short': 'Una Meesh si conia per {price}.',
  'game.guide.moment.first_mint.what': 'Clac! La tua prima Meesh è coniata.',
  'game.guide.moment.first_mint.means': 'Il tuo livello è passato da {from} a {to}: è la regola. Il Vento in poppa è attivo.',
  'game.guide.moment.first_mint.next': 'Riprendi i tuoi livelli più in fretta: i tuoi punti valgono il 25 % in più fino al livello {level}.',
  'game.guide.moment.first_mint.short': 'Livello {from} → {to}. Il Vento in poppa ti aiuta fino al livello {level}.',
  'game.guide.moment.badge_extinguished.what': 'Un badge si è spento.',
  'game.guide.moment.badge_extinguished.means': 'È diventato un’impronta: niente è perso per sempre.',
  'game.guide.moment.badge_extinguished.next': 'Ancora {actions} per riaccenderlo.',
  'game.guide.moment.badge_extinguished.short': 'Un badge si è spento: {actions} per riaccenderlo.',
  'game.guide.moment.price_rises.what': 'Le Meesh diventano più rare.',
  'game.guide.moment.price_rises.means': 'Più ne conii, più costa la successiva.',
  'game.guide.moment.price_rises.next': 'La prossima costa {price}.',
  'game.guide.moment.price_rises.short': 'La prossima Meesh costa {price}.',
  'game.guide.moment.new_rank.what': 'Nuovo rango: {rank}.',
  'game.guide.moment.new_rank.means': 'La tua Gloria ha superato una soglia e non scende mai.',
  'game.guide.moment.new_rank.next': 'Ancora {glory} di Gloria per la divisione successiva. Immortala questo momento.',
  'game.guide.moment.new_rank.next_top': 'È il rango più alto. Immortala questo momento.',
  'game.guide.moment.new_rank.short': 'Sei {rank}.',
  'game.guide.moment.treasury_tier.what': 'Il tuo tesoro raggiunge la fascia {tier}.',
  'game.guide.moment.treasury_tier.means': 'Il tuo tesoro è visibile sul tuo profilo.',
  'game.guide.moment.treasury_tier.next': 'Tieni {meeshes} in più per la fascia successiva, oppure spendi.',
  'game.guide.moment.treasury_tier.next_top': 'Tienilo, oppure spendi le tue Meesh.',
  'game.guide.moment.treasury_tier.short': 'Tesoro: fascia {tier}.',
  'game.guide.moment.flame_at_risk.what': 'La tua Fiamma è in pericolo.',
  'game.guide.moment.flame_at_risk.means': 'Si spegne a mezzanotte se non fai nulla: {days} di serie da salvare.',
  'game.guide.moment.flame_at_risk.next': 'Fai una missione facile, oppure compra un congelamento.',
  'game.guide.moment.flame_at_risk.short': 'La tua Fiamma si spegne a mezzanotte: basta un gesto.',
  'game.guide.moment.flame_out.what': 'La tua Fiamma si è spenta.',
  'game.guide.moment.flame_out.means': 'Il Bonus Fiamma riparte da zero.',
  'game.guide.moment.flame_out.next': 'Riaccendila entro 48 ore per {price}.',
  'game.guide.moment.flame_out.next_new': 'Il tuo prossimo gesto ne accende una nuova.',
  'game.guide.moment.flame_out.short': 'Fiamma spenta: riaccendila per {price}.',
  'game.guide.moment.flame_out.short_new': 'Fiamma spenta: un nuovo gesto la riaccende.',
  'game.guide.moment.return_after_absence.what': 'Che bello rivederti!',
  'game.guide.moment.return_after_absence.means': 'Sei stato via {days}: il tuo rango, il tuo tesoro e la tua Gloria sono rimasti dove li avevi lasciati.',
  'game.guide.moment.return_after_absence.next': 'Comincia dalla missione più facile del giorno.',
  'game.guide.moment.return_after_absence.short': 'Bentornato: comincia dalla missione più facile.',
  'game.guide.moment.level_100.what': 'Livello 100: si apre il Prestigio!',
  'game.guide.moment.level_100.means': 'Il Prestigio riporta il tuo livello a 1 e ti dà una stella e un trofeo.',
  'game.guide.moment.level_100.next': 'Passa al Prestigio, oppure continua a salire.',
  'game.guide.moment.level_100.next_stay': 'Continua a salire quanto vuoi.',
  'game.guide.moment.level_100.short': 'Il Prestigio è aperto.',
  'game.guide.step.welcome.what': 'Ciao, sono Mee! Con Meo ti spieghiamo il gioco in sette carte.',
  'game.guide.step.welcome.means': 'Ogni gesto utile fa guadagnare punti: scrivere, parlare, pubblicare, reagire, invitare.',
  'game.guide.step.welcome.next': 'Fai il tuo primo gesto, io conto i tuoi punti.',
  'game.guide.step.first_points.what': 'Bravo, i tuoi primi punti!',
  'game.guide.step.first_points.means': 'I punti fanno il livello: riempiono il tuo anello.',
  'game.guide.step.first_points.next': 'Guarda il tuo anello riempirsi.',
  'game.guide.step.levels.what': 'Cento livelli, dieci fasce.',
  'game.guide.step.levels.means': 'Ogni livello richiede un po’ più di punti del precedente.',
  'game.guide.step.levels.next': 'Le missioni si aprono al livello 5.',
  'game.guide.step.missions.what': 'Ogni giorno, tre missioni e un forziere.',
  'game.guide.step.missions.means': 'Completale per aprire il forziere e alimentare la tua Fiamma.',
  'game.guide.step.missions.next': 'Una Fiamma cresce finché torni.',
  'game.guide.step.flame.what': 'La tua Fiamma cresce ogni giorno in cui agisci.',
  'game.guide.step.flame.means': 'Ogni giorno di serie aggiunge il 2 % alle ricompense delle missioni, fino al 50 %. Un congelamento copre un giorno saltato.',
  'game.guide.step.flame.next': 'I tuoi punti possono diventare Meesh.',
  'game.guide.step.mint.what': 'A partire da 1.221 punti si conia una Meesh.',
  'game.guide.step.mint.means': 'I punti spesi escono dal tuo livello, ma il tuo rango non scende mai: ogni conio aggiunge Gloria.',
  'game.guide.step.mint.next': 'La Gloria dà il rango.',
  'game.guide.step.rank.what': 'Il tuo rango non scende mai.',
  'game.guide.step.rank.means': 'Coniare, battere record, ottenere traguardi: tutto aggiunge Gloria.',
  'game.guide.step.rank.next': 'Immortaliamo la tua partenza con una foto.',
  'game.page.back': 'Torna ai progressi',
  'game.door.rules': 'Come funziona',
  'game.door.notebook': 'Quaderno dei progressi',
  'game.mint.minted_line': 'Meesh n. {number} coniata, {edition}.',
  'game.mint.action': 'Conia con Mee e Meo',
  'game.mint.minting': 'Conio in corso…',
  'game.mint.offline': 'Offline: il conio riprenderà con la connessione.',
  'game.mint.missing': 'Ancora {missing} prima della prossima Meesh: costa {price}.',
  'game.mint.next_title': 'Prossima Meesh · n. {number}',
  'game.mint.next_subtitle': 'Edizione {edition} · {price}',
  'game.mint.row.price': 'Prezzo',
  'game.mint.row.level': 'Livello',
  'game.mint.row.treasury': 'Tesoro',
  'game.mint.row.glory': 'Gloria',
  'game.mint.row.badges': 'Badge',
  'game.mint.row.tailwind': 'Vento in poppa',
  'game.mint.tailwind_value': '+25 % sui tuoi punti fino al livello {level}',
  'game.missions.title': 'Missioni del giorno',
  'game.missions.locked': 'Le missioni si aprono al livello 5: tre al giorno e un forziere. Sei al livello {level}.',
  'game.missions.prism_day': 'Giorno del Prisma: una delle missioni si gioca in una lingua diversa dalla tua.',
  'game.missions.prism_hour': 'Ora del Prisma: {start} – {end} — le tue missioni contano doppio.',
  'game.missions.offline': 'Offline: cambiare una missione o aprire il forziere riprenderà con la connessione.',
  'game.mission.prism': 'Prisma',
  'game.mission.done': 'Fatta',
  'game.mission.personal.chip': 'Solo per te',
  'game.mission.personal.upcoming': 'Inizia tra {remaining}',
  'game.mission.personal.active': 'Finisce tra {remaining}',
  'game.mission.personal.completed': 'Completata',
  'game.mission.personal.missed': 'Mancata',
  'game.mission.reroll': 'Cambia · {price}',
  'game.mission.reroll.a11y': 'Cambia la missione «{title}» con {price}',
  'game.chest.title': 'Forziere del giorno',
  'game.chest.locked': 'Completa le missioni del giorno per aprirlo.',
  'game.chest.opening': 'Apertura in corso…',
  'game.chest.open': 'Apri il forziere',
  'game.chest.claimed': 'Torna domani per il prossimo.',
  'game.chest.odds': '{min} a {max} · {fragment} di un frammento · {freeze} di un congelamento',
  'game.notebook.page_title': 'Quaderno dei progressi',
  'game.notebook.empty': 'Il tuo quaderno è vuoto. I grandi momenti — un rango, una prima Meesh, una Fiamma di 7 giorni — si fotografano con Mee e Meo, e la foto resta sul tuo dispositivo.',
  'game.notebook.pending': 'In attesa',
  'game.notebook.kept': 'Foto conservate',
  'game.notebook.photo_a11y': 'Foto: {title}',
  'game.notebook.remove': 'Rimuovi',
  'game.photo.offer.start': 'Fotografa',
  'game.photo.offer.title': 'Lo immortaliamo?',
  'game.photo.share': 'Condividi',
  'game.photo.a11y': 'Foto: {title}',
  'game.photo.close': 'Chiudi',
  'game.photo.selfie': 'Selfie con noi',
  'game.photo.card_only': 'Solo la carta',
  'game.photo.later': 'Più tardi',
  'game.photo.gallery': 'Scegli una foto dalla galleria',
  'game.photo.shutter': 'Scatta la foto',
  'game.photo.camera.denied': 'La fotocamera è negata. Consentila nelle impostazioni del dispositivo, oppure scegli una foto dalla galleria.',
  'game.photo.camera.unsupported': 'Questo dispositivo non consente la fotocamera qui. Scegli una foto dalla galleria, oppure tieni solo la carta.',
  'game.photo.camera.unavailable': 'La fotocamera non è disponibile (la sta usando un’altra app?). Scegli una foto dalla galleria, oppure tieni solo la carta.',
  'game.photo.striking': 'Mee e Meo coniano il momento nella foto',
  'game.photo.preview': 'Anteprima: {title}',
  'game.photo.format.story': '9:16 · storia',
  'game.photo.format.square': '1:1 · profilo',
  'game.photo.save': 'Salva',
  'game.photo.kept': 'Conservata',
  'game.photo.keep': 'Conserva',
  'game.photo.kicker.start': 'Primi passi',
  'game.photo.title.start': 'La mia partenza su Meeshy',
  'game.photo.kicker.rank': 'Nuovo rango',
  'game.photo.kicker.tier': 'Livello {level}',
  'game.photo.title.tier': 'Fascia {tier}',
  'game.photo.kicker.summit': 'In cima',
  'game.photo.kicker.new_lap': 'Nuovo giro',
  'game.photo.title.level_100': 'Livello 100',
  'game.photo.title.prestige': 'Prestigio {count}',
  'game.photo.title.meesh_first': 'La mia prima Meesh',
  'game.photo.title.meesh_number': 'Meesh n. {number}',
  'game.photo.title.meesh_number_edition': 'Meesh n. {number} · {edition}',
  'game.photo.kicker.meesh': 'Meesh coniata',
  'game.photo.kicker.treasury': 'Tesoro',
  'game.photo.kicker.flame': 'Fiamma',
  'game.photo.kicker.achievement': 'Traguardo sbloccato',
  'game.photo.title.flame_days': '{count} giorni di Fiamma',
  'game.photo.notice.kept': 'Conservata nel quaderno dei progressi.',
  'game.photo.notice.keep_failed': 'Il quaderno non è disponibile su questo dispositivo: la foto non è stata conservata.',
  'game.photo.notice.save_failed': 'Il salvataggio non è andato a buon fine.',
  'game.photo.notice.shared': 'Immagine condivisa.',
  'game.mission.glory': '+{glory} di Gloria',
  'game.guide.collapse': 'Comprimi',
  'game.guide.collapse_a11y': 'Comprimi la spiegazione',
  'game.guide.awaiting.missions': 'Fai la missione più facile del giorno: ti aspetto per proseguire.',
  'game.guide.awaiting.flame': 'Torna domani e fai un gesto: la tua serie arriverà a 2 giorni.',
  'game.photo.private': 'La foto resta sul tuo dispositivo finché non la condividi.',
  'game.photo.camera.opening': 'Apertura della fotocamera…',
  'game.photo.gallery.unreadable': 'Impossibile leggere questa immagine.',
  'game.photo.format.group': 'Formato dell’immagine',
  'game.photo.notice.saved_file': 'Immagine salvata.',
  'game.photo.notice.share_failed': 'La condivisione non è riuscita.',
  'game.photo.compose_unsupported': 'Questo browser non sa comporre l’immagine. Il tuo momento resta nei tuoi progressi.',
  'game.notebook.pending_until': 'In attesa fino al {date}',
  'game.notebook.remove_confirm': 'Conferma la rimozione',
  'game.mint.number_label': 'n. {number}',
  'game.chest.contents': 'Contenuto del forziere',
  'game.fmt.signed': '+{value}',
  'game.fmt.minus': '−{value}',
  'game.fmt.fraction': '{done} / {total}',
  'game.fmt.from_to': '{from} → {to}',
  'game.error.request_id_conflict': 'Quell’identificativo della richiesta è già stato usato per un’altra azione: riprova, ne verrà inviato uno nuovo.',
  'game.level.ring_label': 'Livello {level}, fascia {tier}, {ordinal}',
  'game.tier.ordinal.1': 'prima fascia',
  'game.tier.ordinal.2': 'seconda fascia',
  'game.tier.ordinal.3': 'terza fascia',
  'game.tier.ordinal.4': 'quarta fascia',
  'game.tier.ordinal.5': 'quinta fascia',
  'game.tier.ordinal.6': 'sesta fascia',
  'game.tier.ordinal.7': 'settima fascia',
  'game.tier.ordinal.8': 'ottava fascia',
  'game.tier.ordinal.9': 'nona fascia',
  'game.tier.ordinal.10': 'decima fascia',
  'game.tier.ordinal.11': 'undicesima fascia',
  'game.tier.ordinal.12': 'dodicesima fascia',
  'game.tier.ordinal.13': 'tredicesima fascia',
  'game.tier.ordinal.14': 'quattordicesima fascia',
  'game.tier.ordinal.15': 'quindicesima fascia',
  'game.tier.ordinal.16': 'sedicesima fascia',
  'game.tier.ordinal.17': 'diciassettesima fascia',
  'game.tier.ordinal.18': 'diciottesima fascia',
  'game.tier.ordinal.19': 'diciannovesima fascia',
  'game.tier.ordinal.20': 'ventesima fascia',
  'game.material.copper': 'Rame',
  'game.material.bronze': 'Bronzo',
  'game.material.silver': 'Argento',
  'game.material.gold': 'Oro',
  'game.material.platinum': 'Platino',
  'game.material.obsidian': 'Ossidiana',
  'game.material.prism': 'Prisma',
  'game.medal.label': '{axis}, {material}, {value} su {next} verso {nextMaterial}',
  'game.medal.label_top': '{axis}, {material}, {value}',
  'game.medal.label_off': '{axis}, non ancora ottenuta, ne mancano {missing}',
  'game.family.content': 'Contenuti',
  'game.family.comment': 'Commenti',
  'game.family.conversation': 'Conversazioni',
  'game.family.tool': 'Strumenti',
  'game.family.social': 'Legami',
  'game.hero.earn_title': 'Come guadagnare punti',
  'game.hero.earn_chip': '{family} fino a +{points}',
  'game.hero.earn_chip_a11y': '{family}: fino a {points} per gesto. Vedi le regole.',
  'game.hero.mint_title': 'Come coniare',
  'game.hero.mint_price': '{price} → una Meesh',
  'game.hero.mint_cost': 'costa {levels}',
  'game.hero.mint_glory': '+{glory} Gloria',
  'game.hero.mee_idle': 'Una domanda? Toccami, ti spiego.',
  'game.photo.referral.headline': 'Unisciti a me su Meeshy',
  'game.photo.referral.share_text': 'Unisciti a me su Meeshy: {link}',
  'game.photo.referral.flame_days': '{days} g',
  'game.photo.referral.qr_label': 'Codice QR del tuo link d’invito',
  'game.duration.days_hours': '{days} g {hours} h',
  'game.duration.hours': '{hours} h',
  'game.duration.minutes': '{minutes} min',
  'game.visibility.everyone': 'Tutti',
  'game.visibility.friends': 'I miei amici',
  'game.visibility.me': 'Solo io',
  'game.door.league': 'Lega',
  'game.door.league.locked': 'Dal livello {level}',
  'game.door.league.rank': '{league} · posizione {rank} su {size}',
  'game.door.league.open': 'Classifica della settimana',
  'game.door.season': 'Stagione {number}',
  'game.door.season.steps': 'Tappa {steps} su {total}',
  'game.door.season.none': 'Nessuna stagione aperta al momento',
  'game.door.showcase': 'Vetrina dei trofei',
  'game.door.showcase.count.one': '{count} trofeo',
  'game.door.showcase.count.other': '{count} trofei',
  'game.door.showcase.empty': 'Ancora nessun trofeo',
  'game.door.atlas': 'Atlante delle lingue',
  'game.door.atlas.count': '{stamped} lingue su {total}',
  'game.door.prestige': 'Prestigio',
  'game.door.prestige.ready': 'Puoi passare a Prestigio',
  'game.door.prestige.stars': 'Stelle: {stars} su {max}',
  'game.door.prestige.locked': 'Al livello 100',
  'game.league.title': 'Lega',
  'game.league.tab.mine': 'La mia lega',
  'game.league.tab.friends': 'Amici',
  'game.league.closes': 'Chiude tra {remaining}',
  'game.league.week_points': '{points} questa settimana',
  'game.league.week': 'Settimana del {date}',
  'game.league.locked': 'La lega si apre al livello {level}: ogni settimana ti misuri con altri 29 giocatori di attività simile. Sei al livello {current}.',
  'game.league.minor': 'La lega pubblica non è aperta per il tuo account. La lega tra amici lo è sempre.',
  'game.league.consent.title': 'Entra nella lega pubblica',
  'game.league.consent.shown': 'Cosa vedono gli altri: il tuo pseudonimo, la tua lega e il tuo totale di punti della settimana, aggiornato una volta al giorno alle 4.',
  'game.league.consent.who': 'Chi lo vede: fino a 29 altri giocatori della tua lega, che non conosci. Nessun nome, nessuna foto, nessuna lingua.',
  'game.league.consent.how': 'Come vieni inserito: in base ai punti che guadagni, con giocatori di attività simile.',
  'game.league.consent.risk': 'Un rischio da conoscere: da un giorno all’altro, il tuo totale mostra che hai giocato quel giorno.',
  'game.league.consent.withdraw_info': 'Puoi ritirare il consenso in qualsiasi momento con un tocco, qui o nelle impostazioni. I tuoi dati di lega vengono eliminati entro 4 settimane al massimo.',
  'game.league.consent.accept': 'Accetto ed entro',
  'game.league.consent.leave': 'Esci dalla lega pubblica',
  'game.league.pseudonym.label': 'Pseudonimo di lega (facoltativo)',
  'game.league.pseudonym.hint': 'Da 3 a 20 caratteri. Né il tuo nome né il tuo nome utente. Lascia vuoto: ti viene assegnato un pseudonimo a sorte.',
  'game.league.pseudonym.drawn': 'Il tuo pseudonimo è estratto a sorte: né il tuo nome né il tuo nome utente. Cambia a ogni stagione.',
  'game.league.pseudonym.save': 'Cambia pseudonimo',
  'game.league.pseudonym.current': 'Giochi con il nome {name}.',
  'game.league.pseudonym.invalid': 'Questo pseudonimo non è valido: da 3 a 20 caratteri, lettere, cifre, punto, trattino, trattino basso.',
  'game.league.waiting': 'Fatto. Ti verrà assegnato un gruppo all’inizio della prossima settimana.',
  'game.league.rank_line': 'Posizione {rank} su {size}',
  'game.league.zone.promotion': 'Promozione',
  'game.league.zone.safe': 'Salvezza',
  'game.league.zone.relegation': 'Retrocessione',
  'game.league.to_promotion': 'Ancora {points} per salire',
  'game.league.in_promotion': 'Sali se mantieni la posizione.',
  'game.league.at_top': 'Sei al vertice delle leghe.',
  'game.league.cup.gold': 'Coppa d’oro',
  'game.league.cup.silver': 'Coppa d’argento',
  'game.league.cup.bronze': 'Coppa di bronzo',
  'game.league.snapshot': 'La classifica degli altri si congela ogni giorno alle 4: nessuno vede chi sta giocando ora. Solo la tua riga è in diretta.',
  'game.league.me': 'Tu',
  'game.league.empty': 'Il gruppo si sta riempiendo: la classifica compare appena arrivano i primi punti.',
  'game.league.friends.title': 'Lega tra amici',
  'game.league.friends.body': 'I punti della settimana, tra amici accettati. Sempre aperta, nessun consenso da dare.',
  'game.league.friends.empty': 'Aggiungi amici per confrontarti con loro ogni settimana.',
  'game.league.friends.unknown': 'Un amico',
  'game.duo.title': 'Missione in coppia',
  'game.duo.locked': 'La missione in coppia si apre al livello {level}, per entrambi. Sei al livello {current}.',
  'game.duo.none': 'Scegli un amico: se finite entrambi la vostra parte entro la settimana, la ricompensa raddoppia.',
  'game.duo.invite': 'Invita {name}',
  'game.duo.pick': 'Scegli un amico',
  'game.duo.search': 'Cerca un amico',
  'game.duo.search.none': 'Nessun amico corrisponde.',
  'game.duo.no_friends': 'Ti serve un amico accettato per giocare in coppia.',
  'game.duo.invited.inviter': 'Invito inviato a {name}. In attesa della risposta.',
  'game.duo.invited.invitee': '{name} ti invita alla missione in coppia della settimana.',
  'game.duo.accept': 'Accetta',
  'game.duo.decline': 'Rifiuta',
  'game.duo.cancel': 'Annulla l’invito',
  'game.duo.abandon': 'Lascia la coppia',
  'game.duo.progress.me': 'Tu: {done} su {target}',
  'game.duo.progress.partner': '{name}: {done} su {target}',
  'game.duo.progress.common': 'Insieme: {done} su {target}',
  'game.duo.reward': 'La tua parte: {points}',
  'game.duo.reward.doubled': 'Ricompensa raddoppiata: {points}',
  'game.duo.reward.hint': 'Raddoppia se finite entrambi la vostra parte.',
  'game.duo.completed': 'Coppia riuscita questa settimana.',
  'game.duo.abandoned': 'Coppia lasciata. Una nuova coppia si apre la prossima settimana.',
  'game.duo.expired': 'La coppia della settimana si è conclusa senza riuscire.',
  'game.error.league_locked': 'La lega si apre al livello 10.',
  'game.error.league_minor': 'La lega pubblica non è aperta per il tuo account.',
  'game.error.league_consent_required': 'Accetta prima di entrare nella lega pubblica.',
  'game.error.league_pseudonym_invalid': 'Questo pseudonimo non è valido: da 3 a 20 caratteri, lettere, cifre, punto, trattino, trattino basso.',
  'game.error.league_pseudonym_taken': 'Questo pseudonimo è già in uso.',
  'game.error.league_pseudonym_forbidden': 'Questo pseudonimo non è consentito: scegline uno che non ti identifichi.',
  'game.error.duo_locked': 'La missione in coppia si apre al livello 20, per entrambi.',
  'game.error.duo_not_friends': 'La coppia si gioca tra amici accettati.',
  'game.error.duo_already_active': 'Uno di voi ha già una coppia questa settimana.',
  'game.error.duo_not_found': 'Questa coppia non esiste più: la schermata si aggiorna.',
  'game.error.duo_transition_refused': 'Questo gesto non ha senso per questa coppia.',
  'game.error.season_not_open': 'Nessuna stagione è aperta.',
  'game.error.season_step_not_found': 'Questa tappa non esiste.',
  'game.error.season_step_locked': 'Questa tappa non è ancora stata raggiunta.',
  'game.error.season_step_already_claimed': 'Questa tappa è già stata riscattata.',
  'game.error.seal_already_owned': 'Hai già il Sigillo di questa stagione.',
  'game.error.prestige_level_too_low': 'Il Prestigio si apre al livello 100.',
  'game.error.prestige_at_maximum': 'Hai già tutte e cinque le stelle del Prestigio.',
  'game.offline.action': 'Offline: questo gesto riprenderà con la connessione.',
  'game.retry': 'Riprova',
  'game.unavailable': 'Questa parte del gioco non è ancora disponibile sul tuo server.',
  'game.season.title': 'Stagione',
  'game.season.heading': 'Stagione {number} · settimana {week} su {total}',
  'game.season.theme': 'Tema: {theme}',
  'game.season.stars.one': '{count} stella',
  'game.season.stars.other': '{count} stelle',
  'game.season.how': 'Le missioni del giorno e la coppia danno stelle: {per} stelle aprono una tappa. Tutto il percorso è gratuito.',
  'game.season.to_next': 'Ancora {stars} per la tappa successiva',
  'game.season.steps_line': 'Tappa {steps} su {total}',
  'game.season.path': 'Percorso gratuito',
  'game.season.step': 'Tappa {step}',
  'game.season.step.claimed': 'riscattata',
  'game.season.step.ready': 'da riscattare',
  'game.season.step.locked': 'in arrivo',
  'game.season.reward.fragment': 'Un frammento',
  'game.season.reward.freeze': 'Un gelo della Fiamma',
  'game.season.reward.season-cup': 'La coppa della stagione',
  'game.season.claim': 'Riscatta la tappa {step}',
  'game.season.completed': 'Percorso completato: una coppa, un badge datato e {glory} di Gloria.',
  'game.season.none': 'Nessuna stagione è aperta al momento. La prossima inizia presto.',
  'game.season.seal.title': 'Fila Sigillo',
  'game.season.seal.body': 'Il Sigillo è puramente decorativo: un oggetto da collezione ogni {every} tappe, senza effetto sul gioco.',
  'game.season.seal.buy': 'Prendi il Sigillo · {price}',
  'game.season.seal.owned': 'Hai il Sigillo di questa stagione.',
  'game.season.seal.cosmetic': 'Oggetto del Sigillo',
  'game.league.pseudonym.title': 'Il tuo pseudonimo',
  'game.league.pseudonym.new': 'Nuovo pseudonimo',
  'game.league.pseudonym.hint_change': 'Da 3 a 20 caratteri. Né il tuo nome né il tuo nome utente.',
  'game.doors.label': 'Il gioco',
  'game.trophy.league-cup': '{cup} — lega {league}, settimana del {date}',
  'game.trophy.season-cup': 'Coppa della stagione {number}',
  'game.trophy.prestige': 'Trofeo di Prestigio {number}',
  'game.trophy.flame': 'Trofeo della Fiamma, {days}',
  'game.trophy.plate.league': '{league} · S{week}',
  'game.trophy.league-cup-month': '{cup} — lega {league}, {month}',
  'game.trophy.plate.league-month': '{league} · {month}',
  'game.trophy.plate.season': 'STAGIONE {number}',
  'game.trophy.plate.prestige': 'PRESTIGIO {number}',
  'game.trophy.plate.flame': '{days} GIORNI',
  'game.showcase.title': 'Vetrina dei trofei',
  'game.showcase.empty': 'La tua vetrina è vuota. Le coppe di lega, di stagione, di Prestigio e della Fiamma vengono riposte qui man mano che le ottieni.',
  'game.showcase.order_hint': 'Riordina i tuoi trofei: sposta ciascuno su o giù di un posto.',
  'game.showcase.move_up': 'Sposta su: {name}',
  'game.showcase.move_down': 'Sposta giù: {name}',
  'game.showcase.awarded': 'Ottenuto il {date}',
  'game.showcase.awarded_month': 'Ottenuto a {month}',
  'game.showcase.awarded_month_count': 'Ottenuto a {month} · ×{count}',
  'game.showcase.visibility': 'Chi vede la tua vetrina',
  'game.showcase.visibility_hint': 'Un visitatore vede solo il mese di ottenimento, mai la data esatta. «Solo io» chiude la vetrina a tutti gli altri.',
  'game.visibility.field.showcase': 'Vetrina dei trofei',
  'game.visibility.field.rank': 'Rango e livello',
  'game.visibility.field.treasury': 'Tesoro e Fiamma',
  'game.visibility.field.atlas': 'Atlante delle lingue',
  'game.visibility.saving': 'Salvataggio…',
  'game.atlas.title': 'Atlante delle lingue',
  'game.atlas.intro': 'Ogni lingua con cui hai davvero scambiato messaggi — uno inviato e uno ricevuto con qualcuno che la scrive — mette un timbro nel tuo passaporto.',
  'game.atlas.count': '{stamped} lingue su {total}',
  'game.atlas.remaining': '{remaining} lingue da scoprire',
  'game.atlas.stamps': 'I tuoi timbri',
  'game.atlas.stamped_on': 'Timbro del {date}',
  'game.atlas.pending': 'Scambi a metà',
  'game.atlas.pending.sent': 'inviato — manca un messaggio ricevuto',
  'game.atlas.pending.received': 'ricevuto — manca un messaggio inviato',
  'game.atlas.empty': 'Ancora nessun timbro. Scrivi in un’altra lingua: appena qualcuno risponde, arriva il primo.',
  'game.atlas.privacy': 'Il tuo Atlante è privato per impostazione predefinita: una lingua può dire molto di te. Scegli tu chi lo vede. Il gioco conserva la lingua, i due sensi e la data — mai l’interlocutore né la conversazione.',
  'game.atlas.visibility': 'Chi vede il tuo Atlante',
  'game.prestige.title': 'Prestigio',
  'game.prestige.stars': 'Stelle: {stars} su {max}',
  'game.prestige.locked': 'Il Prestigio si apre al livello 100. Sei al livello {level}.',
  'game.prestige.max': 'Hai tutte e cinque le stelle: la vetta della vetta.',
  'game.prestige.mee': 'Hai raggiunto il livello 100: puoi passare a Prestigio, oppure continuare a salire.',
  'game.prestige.meo': 'Il tuo livello torna a 1 e i tuoi punti in tasca a 0. In cambio: una stella sul tuo anello, un trofeo numerato e {glory} di Gloria. Il tuo rango non scende mai.',
  'game.prestige.confirm.title': 'Passare a Prestigio {number}?',
  'game.prestige.confirm.resets': 'Cosa riparte: il tuo livello (a 1) e i tuoi punti in tasca (a 0).',
  'game.prestige.confirm.keeps': 'Cosa resta: il tuo rango, la tua Gloria, le tue Meesh, la tua Fiamma e i tuoi trofei.',
  'game.prestige.confirm.access': 'Attenzione: la tua lega (livello 10) e la tua coppia (livello 20) si chiudono finché il tuo livello record non ci torna.',
  'game.prestige.confirm.consent': 'Il tuo consenso alla lega pubblica resta registrato: ritrovi la tua lega al livello 10.',
  'game.prestige.go': 'Passa a Prestigio',
  'game.prestige.stay': 'Tenere il mio livello',
  'game.prestige.done': 'Prestigio {number}! Una stella in più sul tuo anello.',
  'game.rarity.common': 'Comune',
  'game.rarity.rare': 'Raro',
  'game.rarity.epic': 'Epico',
  'game.rarity.legendary': 'Leggendario',
  'game.rarity.mythic': 'Mitico',
  'game.rarity.share': '{percent} degli account',
  'game.rarity.aria': 'Rarità: {name}, {share}',
  'game.rarity.measuring': 'Rarità in corso di misurazione',
  'game.guide.action.see_league': 'Vedi la mia lega',
  'game.guide.action.see_season': 'Vedi la stagione',
  'game.guide.action.see_trophies': 'Vedi la mia vetrina',
  'game.guide.action.see_atlas': 'Vedi il mio Atlante',
  'game.guide.moment.league_first.what': 'Benvenuto nella lega {league}!',
  'game.guide.moment.league_first.means': 'Ogni settimana ti misuri con altri 29 giocatori. I primi 7 salgono, gli ultimi 5 scendono e i punti ripartono da zero.',
  'game.guide.moment.league_first.next': 'Ancora {points} per salire questa settimana.',
  'game.guide.moment.league_first.next_top': 'Sei già al vertice delle leghe.',
  'game.guide.moment.league_first.short': 'Lega {league}: {points} per salire.',
  'game.guide.moment.league_promoted.what': 'Sali nella lega {league}!',
  'game.guide.moment.league_promoted.means': 'Hai chiuso al posto {rank} della lega {from}: i primi 7 salgono.',
  'game.guide.moment.league_promoted.next': 'Inizia una nuova settimana: i punti ripartono da zero.',
  'game.guide.moment.league_promoted.short': 'Promozione: lega {league}.',
  'game.guide.moment.league_relegated.what': 'Scendi nella lega {league}.',
  'game.guide.moment.league_relegated.means': 'Gli ultimi 5 di ogni gruppo scendono. Nessun problema: i punti ripartono da zero e nient’altro cala.',
  'game.guide.moment.league_relegated.next': 'Risali già questa settimana: {points} per salire.',
  'game.guide.moment.league_relegated.next_far': 'Risali già questa settimana: ogni punto conta.',
  'game.guide.moment.league_relegated.short': 'Di nuovo nella lega {league}.',
  'game.guide.moment.season_start.what': 'Inizia la stagione {season}!',
  'game.guide.moment.season_start.means': 'Otto settimane, un tema: {theme}. Le missioni del giorno e la coppia danno stelle, e ogni tappa è gratuita.',
  'game.guide.moment.season_start.means_plain': 'Otto settimane e un tema. Le missioni del giorno e la coppia danno stelle, e ogni tappa è gratuita.',
  'game.guide.moment.season_start.next': 'Ti aspettano {steps} tappe, abbastanza per vincere una coppa di stagione.',
  'game.guide.moment.season_start.short': 'Stagione {season}: tappe gratuite.',
  'game.guide.moment.season_end.what_done': 'Stagione {season} finita: percorso completo!',
  'game.guide.moment.season_end.what': 'La stagione {season} sta per finire.',
  'game.guide.moment.season_end.means_done': 'Vinci la coppa di stagione, un badge datato e {glory} di Gloria.',
  'game.guide.moment.season_end.means': 'Sei arrivato alla tappa {steps} su 40. Non si perde nulla: livello e rango restano.',
  'game.guide.moment.season_end.next': 'La prossima stagione inizia presto.',
  'game.guide.moment.season_end.short': 'Fine della stagione {season}.',
  'game.guide.moment.trophy.what': 'Un nuovo trofeo!',
  'game.guide.moment.trophy.means': '{title} entra nella tua vetrina. Un trofeo non fa guadagnare nulla: si conserva e si mostra.',
  'game.guide.moment.trophy.next': 'Riordinala a modo tuo e scegli chi la vede.',
  'game.guide.moment.trophy.short': 'Nuovo trofeo: {title}.',
  'game.guide.moment.prestige.what': 'Prestigio {number}!',
  'game.guide.moment.prestige.means': 'Una stella sul tuo anello, un trofeo numerato e {glory} di Gloria. Il tuo rango non scende mai.',
  'game.guide.moment.prestige.next': 'Il tuo livello torna a 1: inizia un nuovo giro.',
  'game.guide.moment.prestige.short': 'Prestigio {number}.',
  'game.guide.moment.atlas_stamp.what': 'Nuovo timbro: {language}!',
  'game.guide.moment.atlas_stamp.means': 'Hai davvero scambiato messaggi in questa lingua: uno inviato, uno ricevuto.',
  'game.guide.moment.atlas_stamp.next': '{stamped} lingue su {total} nel tuo passaporto.',
  'game.guide.moment.atlas_stamp.short': 'Timbro: {language}.',
  'game.photo.kicker.trophy': 'Nuovo trofeo',
  'game.photo.kicker.league_up': 'Promozione di lega',
  'game.photo.kicker.season': 'Stagione completata',
  'game.photo.kicker.prestige': 'Nuovo Prestigio',
  'game.photo.title.league_up': 'Lega {league}',
  'game.door.settings': 'Impostazioni del gioco',
  'game.settings.title': 'Impostazioni del gioco',
  'game.settings.celebrations.title': 'Mee e Meo',
  'game.settings.celebrations.body': 'Le carte di Mee e Meo e i suggerimenti di foto che compaiono in Progressi. Questa impostazione vale solo per questo dispositivo.',
  'game.settings.celebrations.switch': 'Mostra le celebrazioni',
  'game.settings.hidden.title': 'Gioco nascosto',
  'game.settings.hidden.body': 'Nasconde il gioco ovunque su questo dispositivo, chiude la tua vetrina, il tuo rango, il tuo tesoro e il tuo Atlante a tutti gli altri e ti toglie dalla lega pubblica. I tuoi punti e i tuoi trofei restano.',
  'game.settings.hidden.switch': 'Nascondi il gioco',
  'game.settings.hidden.card': 'Il gioco è nascosto su questo dispositivo.',
  'game.settings.hidden.show': 'Mostra di nuovo il gioco',
  'game.settings.hidden.reopen_note': 'Le tue impostazioni di visibilità restano chiuse: riaprile qui quando vuoi.',
  'game.settings.visibility.title': 'Chi vede cosa',
  'game.settings.visibility.body': 'Fuori dagli amici accettati nessuno vede se sei online né quando giochi. Queste impostazioni dicono cosa vedono i tuoi amici, o tutti, del tuo gioco.',
  'game.settings.league.title': 'Lega pubblica',
  'game.settings.league.on': 'Sei nella lega pubblica con il nome {name}.',
  'game.settings.league.on_unnamed': 'Sei nella lega pubblica.',
  'game.settings.league.off': 'Non sei nella lega pubblica. La tua lega tra amici resta aperta.',
  'game.settings.league.manage': 'Gestisci la mia lega',
  'game.settings.help': 'Come funziona',
  'game.profile.title': 'Il mio gioco',
  'game.profile.level': 'Livello {level} · {tier}',
  'game.profile.glory': '{glory} di Gloria',
  'game.profile.treasury': '{meeshes} · {tier}',
  'game.profile.flame': 'Fiamma: {days}',
  'game.profile.showcase': 'Vetrina',
  'game.profile.medals': 'Medaglie',
  'game.profile.see_progress': 'Vedi i miei progressi',
  'game.profile.see_showcase': 'Vedi tutta la vetrina',
  'game.profile.visitor_title': 'Vetrina di {name}',
  'game.profile.no_trophy': 'Ancora nessun trofeo.',
  'game.photo.referral.with_link': 'Aggiungi il mio link d’invito',
  'game.photo.referral.with_flame': 'Aggiungi la mia Fiamma',
  'game.photo.referral.options': 'Cosa porta la carta',
  'game.photo.image_right': 'Meo: se nella foto ci sono altre persone, chiedi il loro consenso prima di condividerla.',
  'game.photo.kicker.achievement_rarity': 'Traguardo sbloccato · {rarity}',
  'game.standing.title': 'Il gioco di {name}',
  'game.standing.treasury': 'Tesoro: {tier}',
  'game.standing.flame': 'Fiamma: {form}',
  'game.settings.notifications.title': 'Notifiche del gioco',
  'game.settings.notifications.body': 'Un invito alla missione in coppia, un risultato di lega, una tappa della stagione: al massimo una notifica del gioco al giorno. Questa impostazione vale per il tuo account, su tutti i tuoi dispositivi.',
  'game.settings.notifications.switch': 'Ricevi le notifiche del gioco',
} as const satisfies GameCoreCatalog;

export default it;
