import type { CallStudioCatalog } from '@/lib/i18n-call-studio-catalog';

/** Le studio d'un appel vidéo — de (#8551, #8552). */
const de = {
  'callStudio.effects.color': 'Farbe',
  'callStudio.effects.settings': 'Einstellungen',
  'callStudio.face.none': 'Keiner',
  'callStudio.face.smoothing': 'Hautglättung',
  'callStudio.face.toad': 'Kröte',
  'callStudio.face.angel': 'Engel',
  'callStudio.face.demon': 'Dämon',
  'callStudio.face.volcano': 'Vulkanausbruch',
  'callStudio.montage.screen': 'Vollbild',
  'callStudio.montage.grid': 'Mosaik',
  'callStudio.montage.strip': 'Fotoautomat',
  'callStudio.montage.polaroid': 'Polaroid',
  'callStudio.montage.magazine': 'Magazin',
  'callStudio.montage.comic': 'Comic',
  'callStudio.montage.heart': 'Herz',
  'callStudio.capture.preview': 'Vorschau der Collage {style}',
  'callStudio.capture.faces': 'Jedes Gesicht',
  'callStudio.capture.facesLabel': 'Jedes Gesicht einzeln speichern',
  'callStudio.capture.saved': 'Schnappschuss gespeichert',
  'callStudio.capture.faceSaved': '1 Gesicht gespeichert',
  'callStudio.capture.facesSaved': '{count} Gesichter gespeichert',
  'callStudio.capture.failed': 'Der Schnappschuss konnte nicht gespeichert werden',
  'callStudio.capture.cancelled': 'Speichern abgebrochen',
  'callStudio.capture.empty': 'Nichts aufzunehmen: Es wird kein Bild angezeigt',
  'callStudio.capture.busy': 'Wird aufgenommen…',
  'callStudio.capture.bubble': 'Was für ein Anruf!',
  'callStudio.montage.cover': 'Titelseite',
  'callStudio.montage.gold': 'Gold',
  'callStudio.montage.redcarpet': 'Roter Teppich',
  'callStudio.montage.film': 'Film',
  'callStudio.montage.neon': 'Neon',
  'callStudio.montage.noir': 'Schwarzweiß',
  'callStudio.cover.line1': 'Der Anruf des Jahres',
  'callStudio.cover.line2': 'Endlich alle zusammen',
  'callStudio.cover.line3': 'Exklusiv',
  'callStudio.mode.effects': 'Effekte meines Videos',
  'callStudio.mode.montage': 'Anruf festhalten',
  'callStudio.mode.quit': 'Beenden',
  'callStudio.mode.quitEffects': 'Beenden, ohne diese Änderungen zu behalten',
  'callStudio.mode.validateLabel': 'Diesen Effekt behalten und zum Anruf zurückkehren',
  'callStudio.mode.face': 'Gesicht',
  'callStudio.mode.categories': 'Kategorie',
  'callStudio.mode.pickEffect': 'Effekt wählen',
  'callStudio.mode.pickMontage': 'Montage wählen',
  'callStudio.mode.settingsLabel': 'Einstellungen anzeigen (Helligkeit, Unschärfe)',
  'callStudio.capture.hint': 'Zweimal tippen: Foto · Lange drücken: Video',
  'callStudio.capture.gestures': 'Zweimal tippen oder Eingabe: ein Foto. Lange drücken: ein Video mit Ton.',
  'callStudio.record.start': 'Video mit Ton aufnehmen',
  'callStudio.record.stop': 'Video beenden und speichern',
  'callStudio.record.saved': 'Video gespeichert',
  'callStudio.record.failed': 'Das Video konnte nicht gespeichert werden',
  'callStudio.record.unsupported': 'Dieser Browser kann den Anruf nicht aufnehmen',
  'callStudio.record.clock': 'Aufnahme läuft, {time}',
  'callStudio.companions.label': 'Teilnehmende am Anruf',
  'callStudio.companions.more': '{count} weitere Teilnehmende',
  'callStudio.companions.move': 'Auf die andere Seite verschieben',
  'callStudio.frames.moods': 'Stimmungen',
  'callStudio.frames.mood.classics': 'Klassiker',
  'callStudio.frames.mood.signature': 'Signatur',
  'callStudio.frames.mood.distingue': 'Vornehm',
  'callStudio.frames.mood.elegant': 'Elegant',
  'callStudio.frames.mood.jovial': 'Fröhlich',
  'callStudio.frames.mood.deconnecte': 'Abgeschaltet',
  'callStudio.frames.mood.corporate': 'Business',
  'callStudio.frames.mood.fantastique': 'Fantastisch',
  'callStudio.frames.mood.futuriste': 'Futuristisch',
  'callStudio.frames.mood.glauque': 'Düster',
  'callStudio.frames.mood.hors-norme': 'Außergewöhnlich',
  'callStudio.frames.mood.morbide': 'Makaber',
  'callStudio.frames.mood.feerique': 'Märchenhaft',
  'callStudio.mode.pickFrame': 'Rahmen wählen',
  'callStudio.capture.framePreview': 'Vorschau des Rahmens {name}',
} satisfies CallStudioCatalog;

export default de;
