import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const enStudioChrome = {
  'story.studio.more': 'More options',
  'story.studio.preview': 'Preview',
  'story.studio.preview.close': 'Close preview',
  'story.studio.page.remove.current': 'Delete this scene',
  'story.studio.postText': 'Post text',
  'story.studio.postText.placeholder': 'Write the post text…',
  'story.studio.postText.done': 'Done',
  'story.studio.tile.page': 'Scene',
  'story.studio.tile.text': 'Text',
  'story.studio.tile.editor': 'Settings',
  'story.studio.tile.frame': 'Frame',
  'story.studio.undo': 'Undo',
  'story.studio.redo': 'Redo',
  'story.studio.frame': 'Frame',
  'story.studio.frame.media': 'The media',
  'story.studio.frame.around': 'Around the media',
  'story.studio.frame.fit': 'Fit',
  'story.studio.frame.fill': 'Fill',
  'story.studio.frame.fit.hint': 'Whole, placed in the 9:16 frame. Nothing is cropped.',
  'story.studio.frame.fill.hint': 'Covers the whole 9:16 frame, cropping the edges if needed.',
  'story.studio.backdrop.blur': 'Blur',
  'story.studio.backdrop.black': 'Black',
  'story.studio.backdrop.white': 'White',
  'story.studio.backdrop.indigo': 'Indigo',
  'story.studio.backdrop.sand': 'Sand',
  'story.studio.animated': 'Animated',
  'story.studio.timeline': 'Scene timeline',
  'story.studio.timeline.play': 'Play',
  'story.studio.timeline.pause': 'Pause',
  'story.studio.timeline.empty': 'Write a text or place a layer: each object gets its own track.',
  'story.studio.timeline.overlay': 'Layer',
  'story.studio.retouch.title': 'Edit the image',
  'story.studio.retouch.done': 'Done',
  'story.studio.retouch.cancel': 'Discard the edit',
  'composer.attachment.edit': 'Edit {name}',
  'story.studio.retouch.failed': 'The image could not be rendered.',
  'story.studio.timeline.enter': 'Enters here',
  'story.studio.timeline.exit': 'Leaves here',
  'story.studio.timeline.scrub': 'Move the playhead',
  'story.studio.timeline.track': 'Track of {name}',
  'story.studio.timeline.earlier': 'Earlier',
  'story.studio.timeline.later': 'Later',
  'story.studio.editor.filter': 'Filter',
  'story.studio.filter.vintage': 'Vintage',
  'story.studio.filter.bw': 'B&W',
  'story.studio.filter.warm': 'Warm',
  'story.studio.filter.cool': 'Cool',
  'story.studio.filter.dramatic': 'Dramatic',
  'story.studio.filter.vivid': 'Vivid',
  'story.studio.filter.fade': 'Fade',
  'story.studio.filter.chrome': 'Chrome',
  'story.studio.object.menu': 'Actions for {name}',
  'story.studio.object.raise': 'Bring forward',
  'story.studio.object.lower': 'Send backward',
  'story.studio.object.duplicate': 'Duplicate',
  'story.studio.object.edit': 'Edit',
  'story.studio.object.remove': 'Remove',
  'story.studio.object.leave': 'Take off the scene',
  'story.studio.edit.done': 'OK',
  'story.studio.pose.left': 'Move left',
  'story.studio.pose.right': 'Move right',
  'story.studio.pose.up': 'Move up',
  'story.studio.pose.down': 'Move down',
  'story.studio.objects.edit': 'Edit {name}',
  'story.studio.media.alt': 'Alt text',
  'story.studio.media.alt.placeholder': 'Describe this media for screen readers',
} satisfies StudioChromeCatalogSlice;

export default enStudioChrome;
