import type { GameCatalog } from '@/lib/i18n-game-catalog';

/** Le catalogue du jeu, ar (#9379) — mêmes clés et mêmes paramètres que le français ; textes de l'app iOS quand elle les porte. */
const ar = {
  'game.points.one': '{count} نقطة',
  'game.points.other': '{count} نقطة',
  'game.points.convertible.one': '{count} نقطة قابلة للتحويل',
  'game.points.convertible.other': '{count} نقطة قابلة للتحويل',
  'game.days.one': '{count} يوم',
  'game.days.other': '{count} يومًا',
  'game.actions.one': '{count} إجراء',
  'game.actions.other': '{count} إجراءً',
  'game.levels.one': '{count} مستوى',
  'game.levels.other': '{count} مستوى',
  'game.meeshes.none': 'لا Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meesh',
  'game.mint.badges.one': 'ينخفض {count} وسام',
  'game.mint.badges.other': 'ينخفض {count} وسامًا',
  'game.mint.badges.none': 'لن ينطفئ أي وسام',
  'game.tier.etincelle': 'شرارة',
  'game.tier.lueur': 'وميض',
  'game.tier.lumiere': 'نور',
  'game.tier.eclat': 'بريق',
  'game.tier.rayon': 'شعاع',
  'game.tier.aurore': 'فجر',
  'game.tier.comete': 'مذنّب',
  'game.tier.etoile': 'نجمة',
  'game.tier.constellation': 'كوكبة',
  'game.tier.galaxie': 'مجرّة',
  'game.rank.murmure': 'همس',
  'game.rank.echo': 'صدى',
  'game.rank.voix': 'صوت',
  'game.rank.conteur': 'حكّاء',
  'game.rank.passeur': 'جسّار',
  'game.rank.polyglotte': 'متعدّد اللغات',
  'game.rank.ambassadeur': 'سفير',
  'game.rank.orateur': 'خطيب',
  'game.rank.oracle': 'عرّاف',
  'game.rank.legende': 'أسطورة',
  'game.rank.mythe': 'خرافة',
  'game.treasury.bourse': 'كيس',
  'game.treasury.escarcelle': 'جراب',
  'game.treasury.coffret': 'صندوق صغير',
  'game.treasury.coffre': 'صندوق',
  'game.treasury.tresor': 'كنز',
  'game.treasury.reserve': 'احتياطي',
  'game.flame.form.braise': 'جمرة',
  'game.flame.form.flamme': 'لهب',
  'game.flame.form.brasier': 'نار مشتعلة',
  'game.flame.form.astre': 'نجم',
  'game.flame.form.soleil': 'شمس',
  'game.edition.silver': 'فضّية',
  'game.edition.gold': 'ذهبية',
  'game.edition.prism': 'منشورية',
  'game.difficulty.easy': 'سهلة',
  'game.difficulty.medium': 'متوسطة',
  'game.difficulty.hard': 'صعبة',
  'game.difficulty.gold': 'ذهبية',
  'game.mission.react_messages.one': 'تفاعل مع {count} رسالة',
  'game.mission.react_messages.other': 'تفاعل مع {count} رسائل',
  'game.mission.send_voice.one': 'أرسل رسالة صوتية',
  'game.mission.send_voice.other': 'أرسل {count} رسائل صوتية',
  'game.mission.send_texts.one': 'أرسل {count} رسالة',
  'game.mission.send_texts.other': 'أرسل {count} رسائل',
  'game.mission.use_stickers.one': 'أرسل ملصقًا',
  'game.mission.use_stickers.other': 'أرسل {count} ملصقات',
  'game.mission.send_attachments.one': 'أرسل مرفقًا',
  'game.mission.send_attachments.other': 'أرسل {count} مرفقات',
  'game.mission.comment_text.one': 'اكتب تعليقًا',
  'game.mission.comment_text.other': 'اكتب {count} تعليقات',
  'game.mission.publish_story.one': 'انشر ستوري',
  'game.mission.publish_story.other': 'انشر {count} ستوري',
  'game.mission.publish_post.one': 'انشر منشورًا',
  'game.mission.publish_post.other': 'انشر {count} منشورات',
  'game.mission.share_link.one': 'شارك رابطًا',
  'game.mission.share_link.other': 'شارك {count} روابط',
  'game.mission.prism_foreign_messages.one': 'اكتب رسالة بلغة غير لغتك',
  'game.mission.prism_foreign_messages.other': 'اكتب {count} رسائل بلغة غير لغتك',
  'game.mission.voice_comments.one': 'اترك تعليقًا صوتيًا',
  'game.mission.voice_comments.other': 'اترك {count} تعليقات صوتية',
  'game.mission.publish_reel.one': 'انشر ريلز',
  'game.mission.publish_reel.other': 'انشر {count} ريلز',
  'game.mission.reply_conversations': 'ردّ في {count} محادثات مختلفة',
  'game.mission.prism_foreign_exchange': 'اكتب {count} رسائل بلغة غير لغتك',
  'game.mission.long_chat': 'أرسل {count} رسائل',
  'game.mission.gold_replies_received': 'احصل على ردود من {count} أشخاص مختلفين',
  'game.mission.generic': 'مهمة اليوم',
  'game.error.insufficient_points': 'ليس لديك نقاط قابلة للتحويل تكفي لسك Meesh.',
  'game.error.insufficient_meeshes': 'تحتاج إلى Meesh إضافية لذلك.',
  'game.error.freeze_at_maximum': 'لديك بالفعل تجميدان في الاحتياط: هذا هو الحد الأقصى.',
  'game.error.relight_not_allowed': 'لا يمكن إعادة إشعال اللهب الآن.',
  'game.error.mission_not_found': 'هذه المهمة لم تعد موجودة: تتحدّث الشاشة.',
  'game.error.mission_reroll_exhausted': 'لقد غيّرت مهمة اليوم بالفعل.',
  'game.error.mission_reroll_unavailable': 'لا يمكن تغيير هذه المهمة.',
  'game.error.missions_locked': 'تُفتح المهام عند المستوى 5.',
  'game.error.chest_not_ready': 'أكمل مهام اليوم أولًا لفتح الصندوق.',
  'game.error.generic': 'لم تكتمل العملية — تحقّق من اتصالك وأعد المحاولة.',
  'game.chest.chance': 'فرصة واحدة من {odds}',
  'game.chest.reward.fragment': 'جزء من Meesh',
  'game.chest.reward.freeze': 'تجميد للّهب',
  'game.flame_panel.title': 'احمِ اللهب',
  'game.flame_panel.bonus': '\u2066+{perDay} %\u2069 لكل يوم متتالٍ على مكافآت المهام، حتى\u00a0\u2066+{max} %\u2069.',
  'game.flame_panel.freezes': 'التجميدات في الاحتياط: \u2066{held} / {max}\u2069',
  'game.flame_panel.offline': 'بلا اتصال: ستُستأنف التجميدات وإعادة الإشعال عند عودة الاتصال.',
  'game.flame_panel.freeze_full': 'الاحتياط ممتلئ: تجميد واحد يغطّي يومًا فائتًا، ولا تحتاج إلى المزيد.',
  'game.flame_panel.freeze_buy': 'اشترِ تجميدًا · {price}',
  'game.flame_panel.freeze_missing': 'تحتاج إلى {missing} لتجميد.',
  'game.flame_panel.relight_intro': 'انطفأ لهبك: أعد إشعاله الآن، فيستأنف من حيث توقّف.',
  'game.flame_panel.relight': 'أعد إشعال اللهب · {price}',
  'game.flame_panel.relight_missing': 'تحتاج إلى {missing} لإعادة إشعاله.',
  'game.flame_panel.relight_missing_window': 'تحتاج إلى {missing} لإعادة إشعاله إذا انطفأ قبل أقل من 48 ساعة.',
  'game.flame_panel.relight_closed': 'لا يمكن إعادة إشعال هذا اللهب بعد الآن. يبدأ لهب جديد مع إجرائك التالي.',
  'game.gauge.level': 'المستوى',
  'game.level.title': 'المستوى {level} · {tier}',
  'game.level.top': 'أنت في القمة.',
  'game.level.to_next': 'بقي {points} للوصول إلى المستوى {level}',
  'game.level.record': 'الرقم القياسي: المستوى {level}',
  'game.level.tailwind': ' · رياح مواتية ×{factor}',
  'game.gauge.rank': 'الرتبة',
  'game.rank.glory': 'المجد {glory}',
  'game.rank.top': 'أعلى رتبة',
  'game.rank.next': 'بقي {missing} من المجد قبل {rank}',
  'game.gauge.treasury': 'الكنز',
  'game.treasury.hint': 'احتفظ بـ Meesh: فهي تملأ كنزك',
  'game.treasury.next': 'بقي {missing} للوصول إلى {tier}',
  'game.gauge.flame': 'اللهب',
  'game.flame.no_streak': 'لا سلسلة',
  'game.flame.form_line': '{form} ·\u00a0\u2066+{bonus} %\u2069 على المهام',
  'game.flame.out_line': 'اللهب منطفئ',
  'game.flame.status.none': 'إجراء واحد اليوم يُشعل لهبك',
  'game.flame.status.at_risk': 'قم بإجراء قبل منتصف الليل',
  'game.flame.status.covered': 'تجميد يحميه',
  'game.flame.status.out': 'منطفئ',
  'game.guide.speaker.mee': 'مي',
  'game.guide.speaker.meo': 'ميو',
  'game.guide.speaker.duo': 'مي وميو',
  'game.guide.step_of': 'الخطوة {index} من {total}',
  'game.guide.more': 'عرض الشرح الكامل',
  'game.guide.dismiss': 'لاحقًا',
  'game.guide.skip': 'تخطَّ',
  'game.guide.photo': 'خلّد هذه اللحظة',
  'game.guide.skip_all': 'تخطَّ المقدمة',
  'game.guide.action.start_game': 'ابدأ اللعبة',
  'game.guide.action.earn_first_points': 'قم بأول إجراء لي',
  'game.guide.action.see_level': 'عرض مستواي',
  'game.guide.action.see_missions': 'عرض المهام',
  'game.guide.action.see_flame': 'عرض لهبي',
  'game.guide.action.see_meeshes': 'عرض Meesh',
  'game.guide.action.see_rank': 'عرض رتبتي',
  'game.guide.action.take_start_photo': 'التقط صورة البداية',
  'game.guide.action.see_progress': 'عرض تقدّمي',
  'game.guide.action.see_next_tier': 'عرض المرحلة التالية',
  'game.guide.action.open_first_mission': 'افتح مهمتي الأولى',
  'game.guide.action.mint_or_climb': 'عرض معاينة السك',
  'game.guide.action.regain_levels': 'استعد مستوياتي',
  'game.guide.action.relight_badge': 'عرض أوسمتي',
  'game.guide.action.see_mint_preview': 'عرض معاينة السك',
  'game.guide.action.take_photo': 'خلّد هذه اللحظة',
  'game.guide.action.keep_or_spend': 'عرض كنزي',
  'game.guide.action.do_easy_mission_or_freeze': 'عرض مهامي',
  'game.guide.action.relight_flame': 'أعد إشعال اللهب',
  'game.guide.action.do_easiest_mission': 'عرض أسهل مهمة',
  'game.guide.action.prestige_or_stay': 'عرض مستواي',
  'game.guide.moment.first_level.what': 'لقد ربحت مستواك الأول.',
  'game.guide.moment.first_level.means': 'تملأ نقاطك الحلقة: وعندما تمتلئ ترتقي مستوى.',
  'game.guide.moment.first_level.next': 'بقي {points} للوصول إلى المستوى {level}.',
  'game.guide.moment.first_level.short': 'المستوى {level}: بقي {points} للمستوى التالي.',
  'game.guide.moment.new_tier.what': 'لقد دخلت مرحلة {tier}!',
  'game.guide.moment.new_tier.means': 'تُميّز المراحل طريقك: عشرة مستويات لكل منها.',
  'game.guide.moment.new_tier.next': 'تُفتح المرحلة التالية عند المستوى {level}.',
  'game.guide.moment.new_tier.next_last': 'أنت في المرحلة الأخيرة.',
  'game.guide.moment.new_tier.short': 'تم بلوغ مرحلة {tier}.',
  'game.guide.moment.missions_unlocked.what': 'تم فتح المهام.',
  'game.guide.moment.missions_unlocked.means': 'ثلاث مهام يوميًا، وصندوق تفتحه عند إنجازها.',
  'game.guide.moment.missions_unlocked.next': 'افتح مهمتك الأولى.',
  'game.guide.moment.missions_unlocked.short': 'مهام اليوم في انتظارك.',
  'game.guide.moment.first_mint_possible.what': 'يمكنك الآن سك أول Meesh لك.',
  'game.guide.moment.first_mint_possible.means_free': 'يكلّف السك {price} دون أن تفقد أي مستوى، ويمنحك\u00a0\u2066+{glory}\u2069 من المجد.',
  'game.guide.moment.first_mint_possible.means': 'يكلّف السك {price}، أي {levels}، ويمنحك\u00a0\u2066+{glory}\u2069 من المجد.',
  'game.guide.moment.first_mint_possible.next': 'اسكّها الآن، أو اصعد أولًا.',
  'game.guide.moment.first_mint_possible.short': 'تُسَكّ Meesh مقابل {price}.',
  'game.guide.moment.first_mint.what': 'طَق! تم سك أول Meesh لك.',
  'game.guide.moment.first_mint.means': 'انتقل مستواك من {from} إلى {to}: هذه هي القاعدة. الرياح المواتية فعّالة.',
  'game.guide.moment.first_mint.next': 'استعد مستوياتك أسرع: تُحتسب نقاطك بزيادة \u206625 %\u2069 حتى المستوى {level}.',
  'game.guide.moment.first_mint.short': 'المستوى \u2066{from} → {to}\u2069. تساعدك الرياح المواتية حتى المستوى {level}.',
  'game.guide.moment.badge_extinguished.what': 'انطفأ وسام.',
  'game.guide.moment.badge_extinguished.means': 'تحوّل إلى أثر: لا شيء يضيع إلى الأبد.',
  'game.guide.moment.badge_extinguished.next': 'بقي {actions} لإعادة إشعاله.',
  'game.guide.moment.badge_extinguished.short': 'انطفأ وسام: {actions} لإعادة إشعاله.',
  'game.guide.moment.price_rises.what': 'تصبح Meesh أندر.',
  'game.guide.moment.price_rises.means': 'كلما سككت أكثر، ارتفعت كلفة التالية.',
  'game.guide.moment.price_rises.next': 'التالية تكلّف {price}.',
  'game.guide.moment.price_rises.short': 'تكلّف Meesh التالية {price}.',
  'game.guide.moment.new_rank.what': 'رتبة جديدة: {rank}.',
  'game.guide.moment.new_rank.means': 'تجاوز مجدك عتبة جديدة، ولا يتراجع أبدًا.',
  'game.guide.moment.new_rank.next': 'بقي {glory} من المجد للشريحة التالية. خلّد هذه اللحظة.',
  'game.guide.moment.new_rank.next_top': 'هذه أعلى رتبة. خلّد هذه اللحظة.',
  'game.guide.moment.new_rank.short': 'أنت {rank}.',
  'game.guide.moment.treasury_tier.what': 'يبلغ كنزك مرحلة {tier}.',
  'game.guide.moment.treasury_tier.means': 'كنزك ظاهر على ملفك الشخصي.',
  'game.guide.moment.treasury_tier.next': 'احتفظ بـ {meeshes} إضافية للمرحلة التالية، أو أنفق.',
  'game.guide.moment.treasury_tier.next_top': 'احتفظ به، أو أنفق Meesh.',
  'game.guide.moment.treasury_tier.short': 'الكنز: مرحلة {tier}.',
  'game.guide.moment.flame_at_risk.what': 'لهبك في خطر.',
  'game.guide.moment.flame_at_risk.means': 'ينطفئ عند منتصف الليل إن لم تفعل شيئًا: {days} من السلسلة لإنقاذها.',
  'game.guide.moment.flame_at_risk.next': 'أنجز مهمة سهلة، أو اشترِ تجميدًا.',
  'game.guide.moment.flame_at_risk.short': 'ينطفئ لهبك عند منتصف الليل: يكفي إجراء واحد.',
  'game.guide.moment.flame_out.what': 'انطفأ لهبك.',
  'game.guide.moment.flame_out.means': 'يعود مكافأة اللهب إلى الصفر.',
  'game.guide.moment.flame_out.next': 'أعد إشعاله خلال 48 ساعة مقابل {price}.',
  'game.guide.moment.flame_out.next_new': 'إجراؤك التالي يُشعل لهبًا جديدًا.',
  'game.guide.moment.flame_out.short': 'اللهب منطفئ: أعد إشعاله مقابل {price}.',
  'game.guide.moment.flame_out.short_new': 'اللهب منطفئ: إجراء جديد يُشعله.',
  'game.guide.moment.return_after_absence.what': 'سعيد برؤيتك مجددًا!',
  'game.guide.moment.return_after_absence.means': 'غبت {days}: بقيت رتبتك وكنزك ومجدك حيث تركتها.',
  'game.guide.moment.return_after_absence.next': 'ابدأ بأسهل مهمة اليوم.',
  'game.guide.moment.return_after_absence.short': 'مرحبًا بعودتك: ابدأ بأسهل مهمة.',
  'game.guide.moment.level_100.what': 'المستوى 100: أنت في القمة!',
  'game.guide.moment.level_100.means': 'يعيد التميّز مستواك إلى 1 ويمنحك نجمة وكأسًا.',
  'game.guide.moment.level_100.next': 'انتقل إلى التميّز، أو ابقَ في القمة.',
  'game.guide.moment.level_100.next_stay': 'ابقَ في القمة ما شئت.',
  'game.guide.moment.level_100.short': 'أنت في القمة.',
  'game.guide.step.welcome.what': 'مرحبًا، أنا مي! مع ميو سنشرح لك اللعبة في سبع بطاقات.',
  'game.guide.step.welcome.means': 'كل إجراء مفيد يمنحك نقاطًا: الكتابة، والكلام، والنشر، والتفاعل، والدعوة.',
  'game.guide.step.welcome.next': 'قم بأول إجراء، وأنا أحسب نقاطك.',
  'game.guide.step.first_points.what': 'أحسنت، هذه أولى نقاطك!',
  'game.guide.step.first_points.means': 'النقاط تصنع مستواك: إنها تملأ حلقتك.',
  'game.guide.step.first_points.next': 'شاهد حلقتك وهي تمتلئ.',
  'game.guide.step.levels.what': 'مئة مستوى، وعشر مراحل.',
  'game.guide.step.levels.means': 'يتطلّب كل مستوى نقاطًا أكثر قليلًا من الذي قبله.',
  'game.guide.step.levels.next': 'تُفتح المهام عند المستوى 5.',
  'game.guide.step.missions.what': 'كل يوم ثلاث مهام وصندوق.',
  'game.guide.step.missions.means': 'أنجزها لتفتح الصندوق وتغذّي لهبك.',
  'game.guide.step.missions.next': 'يكبر اللهب ما دمت تعود.',
  'game.guide.step.flame.what': 'يكبر لهبك كل يوم تتحرّك فيه.',
  'game.guide.step.flame.means': 'كل يوم متتالٍ يضيف \u20662 %\u2069 إلى مكافآت مهامك، حتى \u206650 %\u2069. التجميد يغطّي يومًا فائتًا.',
  'game.guide.step.flame.next': 'يمكن أن تتحوّل نقاطك إلى Meesh.',
  'game.guide.step.mint.what': 'ابتداءً من 1٬221 نقطة، تُسَكّ Meesh.',
  'game.guide.step.mint.means': 'تغادر النقاط المنفقة مستواك، لكن رتبتك لا تنخفض أبدًا: كل سكّ يضيف مجدًا.',
  'game.guide.step.mint.next': 'المجد يمنح الرتبة.',
  'game.guide.step.rank.what': 'رتبتك لا تنخفض أبدًا.',
  'game.guide.step.rank.means': 'السكّ وتحطيم الأرقام القياسية وكسب الإنجازات: كلها تضيف مجدًا.',
  'game.guide.step.rank.next': 'لنخلّد بدايتك بصورة.',
  'game.rules.1.title': 'كل إجراء له مكافأة',
  'game.rules.1.body': 'الكتابة والكلام والنشر والتفاعل والدعوة: كل إجراء مفيد يمنحك نقاطًا.',
  'game.rules.2.title': 'النقاط تصنع المستوى',
  'game.rules.2.body': '100 مستوى في 10 مراحل. يتطلّب كل مستوى أكثر قليلًا من الذي قبله.',
  'game.rules.3.title': 'نسكّ Meesh',
  'game.rules.3.body': 'ابتداءً من 1٬221 نقطة، تسكّ Meesh يدويًا. يرتفع السعر مع عدد الـ Meesh المسكوكة.',
  'game.rules.4.title': 'السكّ يُنزِلك',
  'game.rules.4.body': 'تغادر النقاط المنفقة المستوى. وقد تنطفئ الأوسمة التي كانت تدعمها.',
  'game.rules.5.title': 'رتبتك لا تنخفض أبدًا',
  'game.rules.5.body': 'كل سكّ وكل رقم قياسي وكل إنجاز يضيف مجدًا. والمجد يمنح الرتبة.',
  'game.rules.6.title': 'الكنز يُحفَظ أو يُنفَق',
  'game.rules.6.body': 'الاحتفاظ بـ Meesh يُنمّي الكنز. وإنفاقها يحمي اللهب أو يمنحك عناصر تجميلية.',
  'game.rules.7.title': 'كل يوم يُحتسب',
  'game.rules.7.body': 'ثلاث مهام، وصندوق، ولهب يكبر ما دمت تعود.',
  'game.rules.8.title': 'نحتفظ بأثر',
  'game.rules.8.body': 'كل لحظة كبيرة تُصوَّر مع مي وميو في دفتر التقدّم.',
  'game.rules.page_title': 'كيف تعمل اللعبة',
  'game.rules.intro': 'ثماني قواعد، واللعبة كلها بداخلها. ميو يشرحها، ومي تُريك الإجراء.',
  'game.rules.section_rules': 'القواعد في صفحة واحدة',
  'game.rules.section_steps': 'الخطوات السبع',
  'game.page.back': 'العودة إلى التقدّم',
  'game.door.rules': 'كيف تعمل اللعبة',
  'game.door.notebook': 'دفتر التقدّم',
  'game.mint.minted_line': 'تم سك Meesh رقم {number}، {edition}.',
  'game.mint.action': 'اسكّها مع مي وميو',
  'game.mint.minting': 'جارٍ السك…',
  'game.mint.offline': 'بلا اتصال: سيُستأنف السك عند عودة الاتصال.',
  'game.mint.missing': 'بقي {missing} قبل Meesh التالية: تكلّف {price}.',
  'game.mint.next_title': 'Meesh التالية · رقم {number}',
  'game.mint.next_subtitle': 'إصدار {edition} · {price}',
  'game.mint.row.price': 'السعر',
  'game.mint.row.level': 'المستوى',
  'game.mint.row.treasury': 'الكنز',
  'game.mint.row.glory': 'المجد',
  'game.mint.row.badges': 'الأوسمة',
  'game.mint.row.tailwind': 'رياح مواتية',
  'game.mint.tailwind_value': '\u2066+25 %\u2069 على نقاطك حتى المستوى {level}',
  'game.missions.title': 'مهام اليوم',
  'game.missions.locked': 'تُفتح المهام عند المستوى 5: ثلاث يوميًا وصندوق. أنت في المستوى {level}.',
  'game.missions.prism_day': 'يوم المنشور: إحدى المهام تُنجَز بلغة غير لغتك.',
  'game.missions.prism_hour': 'ساعة المنشور: {start} – {end} — تُحتسب مهامك مضاعفة.',
  'game.missions.offline': 'بلا اتصال: سيُستأنف تغيير المهمة وفتح الصندوق عند عودة الاتصال.',
  'game.mission.prism': 'المنشور',
  'game.mission.done': 'مُنجزة',
  'game.mission.reroll': 'غيّر · 1 Meesh',
  'game.mission.reroll.a11y': 'غيّر المهمة «{title}» مقابل 1 Meesh',
  'game.chest.title': 'صندوق اليوم',
  'game.chest.locked': 'أكمل مهام اليوم لفتحه.',
  'game.chest.opening': 'جارٍ الفتح…',
  'game.chest.open': 'افتح الصندوق',
  'game.chest.claimed': 'عُد غدًا للصندوق التالي.',
  'game.chest.odds': '{min} إلى {max} · {fragment} لجزء · {freeze} لتجميد',
  'game.notebook.page_title': 'دفتر التقدّم',
  'game.notebook.empty': 'دفترك فارغ. تُصوَّر اللحظات الكبيرة — رتبة، أو أول Meesh، أو لهب لسبعة أيام — مع مي وميو، وتبقى الصورة على جهازك.',
  'game.notebook.pending': 'قيد الانتظار',
  'game.notebook.kept': 'الصور المحفوظة',
  'game.notebook.photo_a11y': 'صورة: {title}',
  'game.notebook.remove': 'احذف',
  'game.photo.offer.start': 'صوّر',
  'game.photo.offer.title': 'هل نخلّدها؟',
  'game.photo.share': 'شارك',
  'game.photo.a11y': 'صورة: {title}',
  'game.photo.close': 'إغلاق',
  'game.photo.selfie': 'سيلفي معنا',
  'game.photo.card_only': 'البطاقة فقط',
  'game.photo.later': 'لاحقًا',
  'game.photo.gallery': 'اختر صورة من المعرض',
  'game.photo.shutter': 'التقط الصورة',
  'game.photo.camera.denied': 'تم رفض الكاميرا. اسمح بها من إعدادات جهازك، أو اختر صورة من المعرض.',
  'game.photo.camera.unsupported': 'لا يسمح هذا الجهاز بالكاميرا هنا. اختر صورة من المعرض، أو احتفظ بالبطاقة فقط.',
  'game.photo.camera.unavailable': 'الكاميرا غير متاحة (هل يستخدمها تطبيق آخر؟). اختر صورة من المعرض، أو احتفظ بالبطاقة فقط.',
  'game.photo.striking': 'مي وميو يسكّان اللحظة في الصورة',
  'game.photo.preview': 'معاينة: {title}',
  'game.photo.format.story': '9:16 · ستوري',
  'game.photo.format.square': '1:1 · الملف الشخصي',
  'game.photo.save': 'احفظ',
  'game.photo.kept': 'محفوظة',
  'game.photo.keep': 'احتفظ',
  'game.photo.kicker.start': 'الخطوات الأولى',
  'game.photo.title.start': 'بدايتي على Meeshy',
  'game.photo.kicker.rank': 'رتبة جديدة',
  'game.photo.kicker.tier': 'المستوى {level}',
  'game.photo.title.tier': 'مرحلة {tier}',
  'game.photo.kicker.summit': 'في القمة',
  'game.photo.kicker.new_lap': 'جولة جديدة',
  'game.photo.title.level_100': 'المستوى 100',
  'game.photo.title.prestige': 'التميّز {count}',
  'game.photo.title.meesh_first': 'أول Meesh لي',
  'game.photo.title.meesh_number': 'Meesh رقم {number}',
  'game.photo.title.meesh_number_edition': 'Meesh رقم {number} · {edition}',
  'game.photo.kicker.meesh': 'Meesh مسكوكة',
  'game.photo.kicker.treasury': 'الكنز',
  'game.photo.kicker.flame': 'اللهب',
  'game.photo.kicker.achievement': 'تم فتح إنجاز',
  'game.photo.title.flame_days': '{count} يومًا من اللهب',
  'game.photo.notice.kept': 'تم الاحتفاظ بها في دفتر التقدّم.',
  'game.photo.notice.keep_failed': 'الدفتر غير متاح على هذا الجهاز: لم يتم حفظ الصورة.',
  'game.photo.notice.save_failed': 'لم يتم الحفظ.',
  'game.photo.notice.shared': 'تمت مشاركة الصورة.',
  'game.mission.glory': '\u2066+{glory}\u2069 مجد',
  'game.guide.collapse': 'طيّ',
  'game.guide.collapse_a11y': 'طيّ الشرح',
  'game.guide.awaiting.missions': 'أنجز أسهل مهام اليوم: سأنتظرك لنكمل.',
  'game.guide.awaiting.flame': 'عُد غدًا وقم بأي إجراء: ستصل سلسلتك إلى يومين.',
  'game.photo.private': 'تبقى الصورة على جهازك ما لم تشاركها.',
  'game.photo.camera.opening': 'جارٍ فتح الكاميرا…',
  'game.photo.gallery.unreadable': 'تعذّرت قراءة هذه الصورة.',
  'game.photo.format.group': 'تنسيق الصورة',
  'game.photo.notice.saved_file': 'تم حفظ الصورة.',
  'game.photo.notice.share_failed': 'تعذّرت المشاركة.',
  'game.photo.compose_unsupported': 'لا يستطيع هذا المتصفح تركيب الصورة. تبقى لحظتك في تقدّمك.',
  'game.notebook.pending_until': 'في الانتظار حتى {date}',
  'game.notebook.remove_confirm': 'تأكيد الإزالة',
  'game.mint.number_label': 'رقم {number}',
  'game.chest.contents': 'محتوى الصندوق',
  'game.fmt.signed': '\u2066+{value}\u2069',
  'game.fmt.minus': '\u2066−{value}\u2069',
  'game.fmt.fraction': '\u2066{done} / {total}\u2069',
  'game.fmt.from_to': '\u2066{from} → {to}\u2069',
  'game.points.two': 'نقطتان',
  'game.points.few': '{count} نقاط',
  'game.points.convertible.two': 'نقطتان قابلتان للتحويل',
  'game.points.convertible.few': '{count} نقاط قابلة للتحويل',
  'game.days.two': 'يومان',
  'game.days.few': '{count} أيام',
  'game.actions.two': 'إجراءان',
  'game.actions.few': '{count} إجراءات',
  'game.levels.two': 'مستويان',
  'game.levels.few': '{count} مستويات',
  'game.mint.badges.two': 'ينخفض وسامان',
  'game.mint.badges.few': 'تنخفض {count} أوسمة',
  'game.error.request_id_conflict': 'سبق استخدام معرّف هذا الطلب في إجراء آخر: أعد المحاولة وسيُرسَل معرّف جديد.',
  'game.level.ring_label': 'المستوى {level}، مرحلة {tier}، {ordinal}',
  'game.banner.level': 'المستوى {level}',
  'game.banner.to_next': '{percent}٪ نحو المستوى {level}',
  'game.banner.top': 'في القمة',
  'game.banner.league': 'دوري {league} {place}',
  'game.banner.flame': 'اللهب {days}',
  'game.banner.place.one': 'المركز {count}',
  'game.banner.place.other': 'المركز {count}',
  'game.banner.points': '{points} نقطة',
  'game.banner.missing': 'باقٍ {points}',
  'game.banner.separator': '، ',
  'game.tier.ordinal.1': 'المرحلة الأولى',
  'game.tier.ordinal.2': 'المرحلة الثانية',
  'game.tier.ordinal.3': 'المرحلة الثالثة',
  'game.tier.ordinal.4': 'المرحلة الرابعة',
  'game.tier.ordinal.5': 'المرحلة الخامسة',
  'game.tier.ordinal.6': 'المرحلة السادسة',
  'game.tier.ordinal.7': 'المرحلة السابعة',
  'game.tier.ordinal.8': 'المرحلة الثامنة',
  'game.tier.ordinal.9': 'المرحلة التاسعة',
  'game.tier.ordinal.10': 'المرحلة العاشرة',
  'game.material.copper': 'نحاس',
  'game.material.bronze': 'برونز',
  'game.material.silver': 'فضة',
  'game.material.gold': 'ذهب',
  'game.material.platinum': 'بلاتين',
  'game.material.obsidian': 'سبج',
  'game.material.prism': 'منشور',
  'game.medal.label': '{axis}، {material}، {value} من {next} نحو {nextMaterial}',
  'game.medal.label_top': '{axis}، {material}، {value}',
  'game.medal.label_off': '{axis}، لم تُنَل بعد، يتبقّى {missing}',
  'game.family.content': 'المحتوى',
  'game.family.comment': 'التعليقات',
  'game.family.conversation': 'المحادثات',
  'game.family.tool': 'الأدوات',
  'game.family.social': 'الروابط',
  'game.hero.earn_title': 'كيف تكسب النقاط',
  'game.hero.earn_chip': '{family} ⁦+{points}⁩',
  'game.hero.earn_chip_a11y': '{family}: {points} لكل إجراء. عرض القواعد.',
  'game.hero.mint_title': 'كيف تسكّ',
  'game.hero.mint_price': 'Meesh واحدة مقابل {price}',
  'game.hero.mint_cost': 'تكلّف {levels}',
  'game.hero.mint_glory': '⁦+{glory}⁩ مجد',
  'game.hero.mint_missing': 'بقي {missing}',
  'game.hero.mee_idle': 'عندك سؤال؟ المسني وسأشرح لك.',
  'game.photo.referral.headline': 'انضم إليّ على Meeshy',
  'game.photo.referral.share_text': 'انضم إليّ على Meeshy: ⁦{link}⁩',
  'game.photo.referral.flame_days': '⁦{days}⁩ ي',
  'game.duration.days_hours': '⁦{days}⁩ ي ⁦{hours}⁩ س',
  'game.duration.hours': '⁦{hours}⁩ س',
  'game.duration.minutes': '⁦{minutes}⁩ د',
  'game.visibility.everyone': 'الجميع',
  'game.visibility.friends': 'أصدقائي',
  'game.visibility.me': 'أنا فقط',
  'game.door.league': 'الدوري',
  'game.door.league.locked': 'ابتداءً من المستوى ⁦{level}⁩',
  'game.door.league.rank': '{league} · المركز ⁦{rank}⁩ من ⁦{size}⁩',
  'game.door.league.open': 'ترتيب الأسبوع',
  'game.door.season': 'الموسم ⁦{number}⁩',
  'game.door.season.steps': 'المرحلة ⁦{steps}⁩ من ⁦{total}⁩',
  'game.door.season.none': 'لا يوجد موسم مفتوح حاليًا',
  'game.door.showcase': 'واجهة الكؤوس',
  'game.door.showcase.count.one': 'كأس واحدة',
  'game.door.showcase.count.other': '⁦{count}⁩ كؤوس',
  'game.door.showcase.empty': 'لا توجد كؤوس بعد',
  'game.door.atlas': 'أطلس اللغات',
  'game.door.atlas.count': '⁦{stamped}⁩ لغة من ⁦{total}⁩',
  'game.door.prestige': 'التميّز',
  'game.door.prestige.ready': 'يمكنك الانتقال إلى التميّز',
  'game.door.prestige.stars': 'النجوم: ⁦{stars}⁩ من ⁦{max}⁩',
  'game.door.prestige.locked': 'عند المستوى 100',
  'game.league.title': 'الدوري',
  'game.league.name.quartz': 'كوارتز',
  'game.league.name.ambre': 'عنبر',
  'game.league.name.jade': 'يشم',
  'game.league.name.saphir': 'ياقوت أزرق',
  'game.league.name.rubis': 'ياقوت أحمر',
  'game.league.name.amethyste': 'جمشت',
  'game.league.name.diamant': 'ألماس',
  'game.league.name.prisme': 'منشور',
  'game.league.tab.mine': 'دوريّ',
  'game.league.tab.friends': 'الأصدقاء',
  'game.league.closes': 'يُغلق بعد {remaining}',
  'game.league.week': 'أسبوع {date}',
  'game.league.locked': 'يفتح الدوري عند المستوى ⁦{level}⁩: كل أسبوع تنافس 29 لاعبًا آخر بنشاط مقارب. أنت في المستوى ⁦{current}⁩.',
  'game.league.minor': 'الدوري العام غير مفتوح لحسابك. أما دوري الأصدقاء فمفتوح دائمًا.',
  'game.league.consent.title': 'الانضمام إلى الدوري العام',
  'game.league.consent.shown': 'ما يراه الآخرون: اسمك المستعار ودوريك ومجموع نقاط الأسبوع، يُحدَّث مرة في اليوم عند الساعة 4 صباحًا.',
  'game.league.consent.who': 'من يراه: حتى 29 لاعبًا آخر في دوريك لا تعرفهم. لا اسم ولا صورة ولا لغة.',
  'game.league.consent.how': 'كيف يتم وضعك: بحسب النقاط التي تكسبها، مع لاعبين بنشاط مقارب.',
  'game.league.consent.risk': 'خطر يجب أن تعرفه: من يوم إلى آخر، يُظهر مجموعك أنك لعبت في ذلك اليوم.',
  'game.league.consent.withdraw_info': 'يمكنك سحب موافقتك في أي وقت بلمسة واحدة، هنا أو من الإعدادات. تُحذف بيانات دوريك بعد 4 أسابيع كحدٍّ أقصى.',
  'game.league.consent.accept': 'أوافق وأنضم',
  'game.league.consent.leave': 'مغادرة الدوري العام',
  'game.league.pseudonym.label': 'الاسم المستعار في الدوري (اختياري)',
  'game.league.pseudonym.hint': 'من 3 إلى 20 حرفًا. لا اسمك ولا معرّفك. اتركه فارغًا ليُسحب لك اسم مستعار.',
  'game.league.pseudonym.drawn': 'يُسحب اسمك المستعار عشوائيًا: لا اسمك ولا معرّفك. ويتغيّر في كل موسم.',
  'game.league.pseudonym.save': 'تغيير الاسم المستعار',
  'game.league.pseudonym.current': 'تلعب باسم {name}.',
  'game.league.pseudonym.invalid': 'هذا الاسم غير صالح: من 3 إلى 20 حرفًا، حروف وأرقام ونقطة وشرطة وشرطة سفلية.',
  'game.league.waiting': 'تم تسجيل ذلك. سيتم وضعك في مجموعة مع بداية الأسبوع القادم.',
  'game.league.rank_line': 'المركز ⁦{rank}⁩ من ⁦{size}⁩',
  'game.league.zone.promotion': 'صعود',
  'game.league.zone.safe': 'بقاء',
  'game.league.zone.relegation': 'هبوط',
  'game.league.to_promotion': 'تبقّى {points} للصعود',
  'game.league.in_promotion': 'ستصعد إن حافظت على مكانك.',
  'game.league.at_top': 'أنت في قمة الدوريات.',
  'game.league.cup.gold': 'كأس ذهبية',
  'game.league.cup.silver': 'كأس فضية',
  'game.league.cup.bronze': 'كأس برونزية',
  'game.league.snapshot': 'يُجمَّد ترتيب الآخرين كل يوم عند الساعة 4 صباحًا: لا أحد يرى من يلعب الآن. سطرك وحده مباشر.',
  'game.league.me': 'أنت',
  'game.league.empty': 'المجموعة تمتلئ: يظهر الترتيب بمجرد وصول النقاط الأولى.',
  'game.league.friends.title': 'دوري الأصدقاء',
  'game.league.friends.body': 'نقاط الأسبوع بين الأصدقاء المقبولين. مفتوح دائمًا، دون موافقة مطلوبة.',
  'game.league.friends.empty': 'أضف أصدقاء لتقارن نفسك بهم كل أسبوع.',
  'game.league.friends.unknown': 'صديق',
  'game.duo.title': 'مهمة الثنائي',
  'game.duo.locked': 'تفتح مهمة الثنائي عند المستوى ⁦{level}⁩ لكليكما. أنت في المستوى ⁦{current}⁩.',
  'game.duo.none': 'اختر صديقًا: إن أنهيتما كلٌّ حصته خلال الأسبوع تتضاعف المكافأة.',
  'game.duo.invite': 'دعوة {name}',
  'game.duo.pick': 'اختر صديقًا',
  'game.duo.no_friends': 'تحتاج إلى صديق مقبول للعب كثنائي.',
  'game.duo.invited.inviter': 'أُرسلت الدعوة إلى {name}. بانتظار الرد.',
  'game.duo.invited.invitee': 'يدعوك {name} إلى مهمة الثنائي لهذا الأسبوع.',
  'game.duo.accept': 'قبول',
  'game.duo.decline': 'رفض',
  'game.duo.cancel': 'إلغاء الدعوة',
  'game.duo.abandon': 'مغادرة الثنائي',
  'game.duo.progress.me': 'أنت: ⁦{done}⁩ من ⁦{target}⁩',
  'game.duo.progress.partner': '{name}: ⁦{done}⁩ من ⁦{target}⁩',
  'game.duo.progress.common': 'معًا: ⁦{done}⁩ من ⁦{target}⁩',
  'game.duo.reward': 'حصتك: {points}',
  'game.duo.reward.doubled': 'مكافأة مضاعفة: {points}',
  'game.duo.reward.hint': 'تتضاعف إن أنهيتما كلٌّ حصته.',
  'game.duo.completed': 'نجح الثنائي هذا الأسبوع.',
  'game.duo.abandoned': 'تمت مغادرة الثنائي. يفتح ثنائي جديد الأسبوع القادم.',
  'game.duo.expired': 'انتهى ثنائي الأسبوع دون إتمام.',
  'game.error.league_locked': 'يفتح الدوري عند المستوى 10.',
  'game.error.league_minor': 'الدوري العام غير مفتوح لحسابك.',
  'game.error.league_consent_required': 'وافق أولًا على الانضمام إلى الدوري العام.',
  'game.error.league_pseudonym_invalid': 'هذا الاسم غير صالح: من 3 إلى 20 حرفًا، حروف وأرقام ونقطة وشرطة وشرطة سفلية.',
  'game.error.league_pseudonym_taken': 'هذا الاسم المستعار مستخدم بالفعل.',
  'game.error.league_pseudonym_forbidden': 'هذا الاسم غير مسموح: اختر اسمًا لا يدل عليك.',
  'game.error.duo_locked': 'تفتح مهمة الثنائي عند المستوى 20 لكليكما.',
  'game.error.duo_not_friends': 'يُلعب الثنائي بين الأصدقاء المقبولين.',
  'game.error.duo_already_active': 'لدى أحدكما ثنائي هذا الأسبوع بالفعل.',
  'game.error.duo_not_found': 'هذا الثنائي لم يعد موجودًا: يتم تحديث الشاشة.',
  'game.error.duo_transition_refused': 'هذا الإجراء لا ينطبق على هذا الثنائي.',
  'game.error.season_not_open': 'لا يوجد موسم مفتوح.',
  'game.error.season_step_not_found': 'هذه المرحلة غير موجودة.',
  'game.error.season_step_locked': 'لم تصل إلى هذه المرحلة بعد.',
  'game.error.season_step_already_claimed': 'تم استلام هذه المرحلة بالفعل.',
  'game.error.seal_already_owned': 'لديك ختم هذا الموسم بالفعل.',
  'game.error.prestige_level_too_low': 'يفتح التميّز عند المستوى 100.',
  'game.error.prestige_at_maximum': 'لديك نجوم التميّز الخمس بالفعل.',
  'game.offline.action': 'غير متصل: سيُستأنف هذا الإجراء عند عودة الاتصال.',
  'game.retry': 'إعادة المحاولة',
  'game.unavailable': 'هذا الجزء من اللعبة غير متاح بعد على خادمك.',
  'game.season.title': 'الموسم',
  'game.season.heading': 'الموسم ⁦{number}⁩ · الأسبوع ⁦{week}⁩ من ⁦{total}⁩',
  'game.season.theme': 'الموضوع: {theme}',
  'game.season.stars.one': 'نجمة واحدة',
  'game.season.stars.other': '⁦{count}⁩ نجوم',
  'game.season.how': 'مهام اليوم والثنائي تمنح نجومًا: ⁦{per}⁩ نجوم تفتح مرحلة. المسار كله مجاني.',
  'game.season.to_next': 'تبقّى {stars} للمرحلة التالية',
  'game.season.steps_line': 'المرحلة ⁦{steps}⁩ من ⁦{total}⁩',
  'game.season.path': 'المسار المجاني',
  'game.season.step': 'المرحلة ⁦{step}⁩',
  'game.season.step.claimed': 'تم استلامها',
  'game.season.step.ready': 'جاهزة للاستلام',
  'game.season.step.locked': 'قادمة',
  'game.season.reward.fragment': 'شظية',
  'game.season.reward.freeze': 'تجميد للشعلة',
  'game.season.reward.season-cup': 'كأس الموسم',
  'game.season.claim': 'استلام المرحلة ⁦{step}⁩',
  'game.season.completed': 'اكتمل المسار: كأس وشارة مؤرخة و500 مجد.',
  'game.season.none': 'لا يوجد موسم مفتوح الآن. يبدأ الموسم القادم قريبًا.',
  'game.season.seal.title': 'صف الختم',
  'game.season.seal.body': 'الختم للزينة فقط: عنصر للجمع كل ⁦{every}⁩ مراحل، دون أي تأثير على اللعبة.',
  'game.season.seal.buy': 'احصل على الختم · {price}',
  'game.season.seal.owned': 'لديك ختم هذا الموسم.',
  'game.season.seal.missing': 'ينقصك بعض Meesh للحصول على الختم.',
  'game.season.seal.cosmetic': 'عنصر الختم',
  'game.league.pseudonym.title': 'اسمك المستعار',
  'game.league.pseudonym.new': 'اسم مستعار جديد',
  'game.league.pseudonym.hint_change': 'من 3 إلى 20 حرفًا. لا اسمك ولا معرّفك.',
  'game.doors.label': 'اللعبة',
  'game.trophy.league-cup': '{cup} — دوري {league}، أسبوع {date}',
  'game.trophy.season-cup': 'كأس الموسم ⁦{number}⁩',
  'game.trophy.prestige': 'كأس التميّز ⁦{number}⁩',
  'game.trophy.flame': 'كأس الشعلة، {days}',
  'game.trophy.plate.league': '{league} · ⁦{week}⁩',
  'game.trophy.league-cup-month': '{cup} — دوري {league}، {month}',
  'game.trophy.plate.league-month': '{league} · {month}',
  'game.trophy.plate.season': 'موسم ⁦{number}⁩',
  'game.trophy.plate.prestige': 'تميّز ⁦{number}⁩',
  'game.trophy.plate.flame': '⁦{days}⁩ يومًا',
  'game.showcase.title': 'واجهة الكؤوس',
  'game.showcase.empty': 'واجهتك فارغة. تُوضع هنا كؤوس الدوري والموسم والتميّز والشعلة كلما ربحتها.',
  'game.showcase.order_hint': 'رتّب كؤوسك: ارفع كل كأس أو اخفضها مرتبة واحدة.',
  'game.showcase.move_up': 'رفع: {name}',
  'game.showcase.move_down': 'خفض: {name}',
  'game.showcase.awarded': 'نُلت في {date}',
  'game.showcase.awarded_month': 'نُلت في {month}',
  'game.showcase.awarded_month_count': 'نُلت في {month} · ⁦×{count}⁩',
  'game.showcase.visibility': 'من يرى واجهتك',
  'game.showcase.visibility_hint': 'يرى الزائر شهر الحصول فقط، لا التاريخ الدقيق أبدًا. «أنا فقط» يغلق الواجهة أمام الجميع.',
  'game.visibility.field.showcase': 'واجهة الكؤوس',
  'game.visibility.field.rank': 'الرتبة والمستوى',
  'game.visibility.field.treasury': 'الكنز والشعلة',
  'game.visibility.field.atlas': 'أطلس اللغات',
  'game.visibility.saving': 'جارٍ الحفظ…',
  'game.atlas.title': 'أطلس اللغات',
  'game.atlas.intro': 'كل لغة تبادلت بها الرسائل فعلًا — رسالة مرسلة وأخرى مستلمة مع من يكتبها — تضع ختمًا في جواز سفرك.',
  'game.atlas.count': '⁦{stamped}⁩ لغة من ⁦{total}⁩',
  'game.atlas.remaining': '⁦{remaining}⁩ لغة لاكتشافها',
  'game.atlas.stamps': 'أختامك',
  'game.atlas.stamped_on': 'ختم بتاريخ {date}',
  'game.atlas.pending': 'تبادلات غير مكتملة',
  'game.atlas.pending.sent': 'مُرسل — تنقص رسالة مستلمة',
  'game.atlas.pending.received': 'مستلم — تنقص رسالة مرسلة',
  'game.atlas.empty': 'لا أختام بعد. اكتب بلغة أخرى: بمجرد أن يردّ أحدهم يصلك الأول.',
  'game.atlas.privacy': 'أطلسك خاص افتراضيًا: قد تكشف اللغة الكثير عنك. أنت تختار من يراه. تحتفظ اللعبة باللغة والاتجاهين والتاريخ فقط — لا بالطرف الآخر ولا بالمحادثة.',
  'game.atlas.visibility': 'من يرى أطلسك',
  'game.prestige.title': 'التميّز',
  'game.prestige.stars': 'النجوم: ⁦{stars}⁩ من ⁦{max}⁩',
  'game.prestige.locked': 'يفتح التميّز عند المستوى 100. أنت في المستوى ⁦{level}⁩.',
  'game.prestige.max': 'لديك النجوم الخمس: قمة القمم.',
  'game.prestige.mee': 'أنت في المستوى 100: القمة! يمكنك الانتقال إلى التميّز.',
  'game.prestige.meo': 'يعود مستواك إلى 1 ونقاطك إلى 0. مقابل ذلك: نجمة على حلقتك وكأس مرقّمة و{glory} من المجد. رتبتك لا تنخفض أبدًا.',
  'game.prestige.confirm.title': 'الانتقال إلى التميّز ⁦{number}⁩؟',
  'game.prestige.confirm.resets': 'ما يعود إلى البداية: مستواك (إلى 1) ونقاطك (إلى 0).',
  'game.prestige.confirm.keeps': 'ما يبقى: رتبتك ومجدك وMeesh ولهبك وكؤوسك.',
  'game.prestige.confirm.access': 'تنبيه: يُغلق دوريك (المستوى 10) وثنائيك (المستوى 20) إلى أن يعود مستواك القياسي إليهما.',
  'game.prestige.confirm.consent': 'تبقى موافقتك على الدوري العام مسجّلة: تستعيد دوريك عند المستوى 10.',
  'game.prestige.go': 'الانتقال إلى التميّز',
  'game.prestige.stay': 'البقاء في القمة',
  'game.prestige.done': 'التميّز ⁦{number}⁩! نجمة أخرى على حلقتك.',
  'game.rarity.common': 'شائع',
  'game.rarity.rare': 'نادر',
  'game.rarity.epic': 'ملحمي',
  'game.rarity.legendary': 'أسطوري',
  'game.rarity.mythic': 'خرافي',
  'game.rarity.share': '{percent} من الحسابات',
  'game.rarity.aria': 'الندرة: {name}، {share}',
  'game.rarity.measuring': 'جارٍ قياس الندرة',
  'game.guide.action.see_league': 'عرض دوريّ',
  'game.guide.action.see_season': 'عرض الموسم',
  'game.guide.action.see_trophies': 'عرض واجهتي',
  'game.guide.action.see_atlas': 'عرض أطلسي',
  'game.guide.moment.league_first.what': 'مرحبًا بك في دوري {league}!',
  'game.guide.moment.league_first.means': 'كل أسبوع تنافس 29 لاعبًا آخر. يصعد السبعة الأوائل ويهبط الخمسة الأخيرون، وتبدأ النقاط من الصفر.',
  'game.guide.moment.league_first.next': 'تبقّى {points} للصعود هذا الأسبوع.',
  'game.guide.moment.league_first.next_top': 'أنت بالفعل في قمة الدوريات.',
  'game.guide.moment.league_first.short': 'دوري {league}: {points} للصعود.',
  'game.guide.moment.league_promoted.what': 'صعدت إلى دوري {league}!',
  'game.guide.moment.league_promoted.means': 'أنهيت في المركز {rank} من دوري {from}: يصعد السبعة الأوائل.',
  'game.guide.moment.league_promoted.next': 'يبدأ أسبوع جديد: تبدأ النقاط من الصفر.',
  'game.guide.moment.league_promoted.short': 'صعود: دوري {league}.',
  'game.guide.moment.league_relegated.what': 'هبطت إلى دوري {league}.',
  'game.guide.moment.league_relegated.means': 'يهبط الخمسة الأخيرون في كل مجموعة. لا بأس: تبدأ النقاط من الصفر ولا ينخفض شيء آخر.',
  'game.guide.moment.league_relegated.next': 'اصعد من جديد هذا الأسبوع: {points} للصعود.',
  'game.guide.moment.league_relegated.next_far': 'اصعد من جديد هذا الأسبوع: كل نقطة مهمة.',
  'game.guide.moment.league_relegated.short': 'العودة إلى دوري {league}.',
  'game.guide.moment.season_start.what': 'يبدأ الموسم {season}!',
  'game.guide.moment.season_start.means': 'ثمانية أسابيع وموضوع واحد: {theme}. مهام اليوم والثنائي تمنح نجومًا، وكل مرحلة مجانية.',
  'game.guide.moment.season_start.means_plain': 'ثمانية أسابيع وموضوع واحد. مهام اليوم والثنائي تمنح نجومًا، وكل مرحلة مجانية.',
  'game.guide.moment.season_start.next': 'تنتظرك ⁦{steps}⁩ مرحلة، تكفي لربح كأس الموسم.',
  'game.guide.moment.season_start.short': 'الموسم {season}: مراحل مجانية.',
  'game.guide.moment.season_end.what_done': 'انتهى الموسم {season}: أكملت المسار كاملًا!',
  'game.guide.moment.season_end.what': 'ينتهي الموسم {season}.',
  'game.guide.moment.season_end.means_done': 'تربح كأس الموسم وشارة مؤرخة و{glory} من المجد.',
  'game.guide.moment.season_end.means': 'وصلت إلى المرحلة ⁦{steps}⁩ من 40. لم يضع شيء: مستواك ورتبتك كما هما.',
  'game.guide.moment.season_end.next': 'يبدأ الموسم القادم قريبًا.',
  'game.guide.moment.season_end.short': 'نهاية الموسم {season}.',
  'game.guide.moment.trophy.what': 'كأس جديدة!',
  'game.guide.moment.trophy.means': 'تنضم {title} إلى واجهتك. الكأس لا تمنح شيئًا: تُحفظ وتُعرض.',
  'game.guide.moment.trophy.next': 'رتّبها على طريقتك واختر من يراها.',
  'game.guide.moment.trophy.short': 'كأس جديدة: {title}.',
  'game.guide.moment.prestige.what': 'التميّز ⁦{number}⁩!',
  'game.guide.moment.prestige.means': 'نجمة على حلقتك وكأس مرقّمة و{glory} من المجد. رتبتك لا تنخفض أبدًا.',
  'game.guide.moment.prestige.next': 'يعود مستواك إلى 1: تبدأ دورة جديدة.',
  'game.guide.moment.prestige.short': 'التميّز ⁦{number}⁩.',
  'game.guide.moment.atlas_stamp.what': 'ختم جديد: {language}!',
  'game.guide.moment.atlas_stamp.means': 'لقد تبادلت الرسائل فعلًا بهذه اللغة: رسالة مرسلة وأخرى مستلمة.',
  'game.guide.moment.atlas_stamp.next': '⁦{stamped}⁩ لغة من ⁦{total}⁩ في جواز سفرك.',
  'game.guide.moment.atlas_stamp.short': 'ختم: {language}.',
  'game.photo.kicker.trophy': 'كأس جديدة',
  'game.photo.kicker.league_up': 'صعود في الدوري',
  'game.photo.kicker.season': 'اكتمل الموسم',
  'game.photo.kicker.prestige': 'تميّز جديد',
  'game.photo.title.league_up': 'دوري {league}',
  'game.door.settings': 'إعدادات اللعبة',
  'game.settings.title': 'إعدادات اللعبة',
  'game.settings.celebrations.title': 'مي وميو',
  'game.settings.celebrations.body': 'بطاقات مي وميو واقتراحات الصور التي تظهر في التقدّم. يسري هذا الإعداد على هذا الجهاز فقط.',
  'game.settings.celebrations.switch': 'عرض الاحتفالات',
  'game.settings.hidden.title': 'اللعبة مخفية',
  'game.settings.hidden.body': 'يخفي اللعبة في كل مكان على هذا الجهاز، ويغلق واجهتك ورتبتك وكنزك وأطلسك أمام الجميع، ويخرجك من الدوري العام. تبقى نقاطك وكؤوسك محفوظة.',
  'game.settings.hidden.switch': 'إخفاء اللعبة',
  'game.settings.hidden.card': 'اللعبة مخفية على هذا الجهاز.',
  'game.settings.hidden.show': 'إعادة عرض اللعبة',
  'game.settings.hidden.reopen_note': 'تبقى إعدادات الظهور مغلقة: أعد فتحها هنا متى شئت.',
  'game.settings.visibility.title': 'من يرى ماذا',
  'game.settings.visibility.body': 'خارج الأصدقاء المقبولين لا أحد يرى إن كنت متصلًا ولا متى تلعب. تحدد هذه الإعدادات ما يراه أصدقاؤك، أو الجميع، من لعبتك.',
  'game.settings.league.title': 'الدوري العام',
  'game.settings.league.on': 'أنت في الدوري العام باسم {name}.',
  'game.settings.league.on_unnamed': 'أنت في الدوري العام.',
  'game.settings.league.off': 'أنت لست في الدوري العام. يبقى دوري الأصدقاء مفتوحًا.',
  'game.settings.league.manage': 'إدارة دوريّ',
  'game.settings.help': 'كيف تعمل',
  'game.profile.title': 'لعبتي',
  'game.profile.level': 'المستوى ⁦{level}⁩ · {tier}',
  'game.profile.glory': '{glory} من المجد',
  'game.profile.treasury': '{meeshes} · {tier}',
  'game.profile.flame': 'الشعلة: {days}',
  'game.profile.showcase': 'الواجهة',
  'game.profile.medals': 'الميداليات',
  'game.profile.see_progress': 'عرض تقدّمي',
  'game.profile.see_showcase': 'عرض الواجهة كاملة',
  'game.profile.visitor_title': 'واجهة {name}',
  'game.profile.no_trophy': 'لا كؤوس بعد.',
  'game.photo.referral.with_link': 'إضافة رابط دعوتي',
  'game.photo.referral.with_flame': 'إضافة شعلتي',
  'game.photo.referral.options': 'ما تحمله البطاقة',
  'game.photo.image_right': 'ميو: إن ظهر أشخاص آخرون في الصورة فاطلب موافقتهم قبل مشاركتها.',
} as const satisfies GameCatalog;

export default ar;
