import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const en = {
  'admin.role': 'Your role: {role}',
  'admin.denied.title': 'Restricted area',
  'admin.denied.message': 'This area requires an administration right.',
  'admin.counters.title': 'At a glance',
  'admin.counters.unavailable': 'Counters unavailable right now.',
  'admin.counters.users': 'Accounts',
  'admin.counters.activeUsers': 'Active accounts',
  'admin.counters.messages': 'Messages',
  'admin.counters.communities': 'Communities',
  'admin.counters.reports': 'Reports',
  'admin.counters.newUsers': 'New (24 h)',
  'admin.sections.title': 'Sections',
  'admin.nav.dashboard': 'Dashboard',
  'admin.nav.users': 'Accounts',
  'admin.nav.moderation': 'Moderation',
  'admin.nav.audit': 'Audit logs',
  'admin.nav.analytics': 'Analytics',
  'admin.nav.trackingLinks': 'Tracking links',
  'admin.nav.ranking': 'Ranking',
  'admin.nav.broadcasts': 'Broadcasts',
  'admin.nav.settings': 'Settings',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Monitoring',
  'admin.users.search': 'Search an account',
  'admin.users.count': '{count} account(s)',
  'admin.users.empty': 'No account matches.',
  'admin.users.unavailable': 'List unavailable right now.',
  'admin.users.inactive': 'disabled',
  'admin.users.previous': 'Previous',
  'admin.users.next': 'Next',
  'admin.user.title': 'Member',
  'admin.user.unavailable': 'Profile unavailable right now.',
  'admin.user.identity': 'Identity',
  'admin.user.account': 'Account',
  'admin.user.created': 'Joined on',
  'admin.user.lastActive': 'Last active',
  'admin.user.twoFactor': 'Two-factor',
  'admin.user.enabled': 'enabled',
  'admin.user.deleted': 'deleted',
  'admin.user.role': 'Role',
  'admin.edit.open': 'Edit',
  'admin.edit.title': 'Edit member',
  'admin.edit.displayName': 'Display name',
  'admin.edit.email': 'Email',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Account active',
  'admin.edit.save': 'Save',
  'admin.edit.reason': 'Reason (optional)',
  'admin.edit.warnRole': 'Changing the role changes their permissions.',
  'admin.edit.warnDeactivate': 'Deactivating ends their open sessions.',
  'admin.edit.confirm': 'Confirm',
  'admin.edit.saved': 'Changes saved',
  'admin.edit.failed': 'Could not save',
  'admin.password.title': 'Reset password',
  'admin.password.warn': 'This ends all their open sessions.',
  'admin.password.generated': 'Copy it now — it will not be shown again.',
  'admin.password.copy': 'Copy',
  'admin.password.copied': 'Copied',
  'admin.password.apply': 'Reset',
  'admin.password.done': 'Password reset',
  'admin.password.failed': 'Reset failed',
  'admin.ban.open': 'Ban',
  'admin.ban.title': 'Ban this member',
  'admin.ban.reason': 'Reason (required)',
  'admin.ban.permanent': 'Permanent ban',
  'admin.ban.until': 'Until',
  'admin.ban.apply': 'Ban',
  'admin.ban.lift': 'Lift',
  'admin.ban.active': 'active',
  'admin.ban.expired': 'expired',
  'admin.ban.lifted': 'lifted',
  'admin.ban.none': 'No bans',
  'admin.ban.done': 'Ban recorded',
  'admin.ban.failed': 'Ban failed',
  'admin.media.title': 'Media',
  'admin.media.empty': 'No media',
  'admin.media.protected': 'protected',
  'admin.media.fromPost': 'post',
  'admin.media.fromMessage': 'message',
  'admin.conv.title': 'Conversations',
  'admin.conv.empty': 'No conversations',
  'admin.conv.members': '{count} members',
  'admin.nav.conversations': 'Conversations',
  'admin.convList.search': 'Search a conversation',
  'admin.convList.count': '{count} conversation(s)',
  'admin.convList.empty': 'No conversation matches.',
  'admin.convList.unavailable': 'List unavailable right now.',
  'admin.convList.members': '{count} members',
  'admin.convList.sovereign': 'Reserved to the admin rank.',
  'admin.convDetail.title': 'Reading a conversation',
  'admin.convDetail.reasonLabel': 'Reason for reading',
  'admin.convDetail.reasonHint': 'Ten characters minimum, logged with your name.',
  'admin.convDetail.read': 'Read the conversation',
  'admin.convDetail.empty': 'No message',
  'admin.convDetail.memberPrism': 'Read in the member’s prism: {languages}',
  'admin.agent.title': 'Agent control',
  'admin.agent.denied': 'This control needs a dedicated permission.',
  'admin.agent.users': 'Members driven',
  'admin.agent.tracked': 'Tracked conversations',
  'admin.agent.empty': 'Nothing to show.',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Scan running: {node}',
  'admin.agent.relaunch': 'Run the agent again',
  'admin.agent.effect': 'Re-runs the study and may publish a message.',
  'admin.agent.done': 'Run requested',
  'admin.agent.failed': 'Refused',
  'admin.agent.stop': 'Stop the scan',
  'admin.agent.halted': 'Scan stopped',
  'admin.agent.down': 'Agent service unreachable.',
  'admin.agent.logs': 'Scan log',
  'admin.nav.anonymous': 'Anonymous',
  'admin.shell.menu': 'Administration menu',
  'admin.shell.fold': 'Collapse menu',
  'admin.shell.unfold': 'Expand menu',
  'admin.shell.open': 'Open menu',
  'admin.shell.close': 'Close menu',
  'admin.shell.backToApp': 'Back to the app',
  'admin.list.filters': 'Filters',
  'admin.list.all': 'All',
  'admin.list.yes': 'Yes',
  'admin.list.no': 'No',
  'admin.list.reset': 'Reset',
  'admin.list.pageSize': 'Per page',
  'admin.list.range': '{from}–{to} of {total}',
  'admin.list.sortBy': 'Sort by {column}',
  'admin.col.member': 'Member',
  'admin.col.email': 'Email',
  'admin.col.role': 'Role',
  'admin.col.status': 'Status',
  'admin.col.created': 'Joined',
  'admin.col.lastActive': 'Last active',
  'admin.col.joined': 'Joined',
  'admin.col.language': 'Language',
  'admin.col.conversation': 'Conversation',
  'admin.col.messages': 'Messages',
  'admin.col.name': 'Name',
  'admin.filter.active': 'Active',
  'admin.filter.inactive': 'Deactivated',
  'admin.filter.emailVerified': 'Email verified',
  'admin.filter.twoFactor': 'Two-factor',
  'admin.anonymous.search': 'Search anonymous participants',
  'admin.anonymous.empty': 'No anonymous participant matches.',
  'admin.anonymous.unavailable': 'List unavailable for now.',
  'admin.anonymous.title': 'Anonymous participant',
  'admin.anonymous.left': 'Left',
  'admin.anonymous.permissions': 'Permissions',
  'admin.anonymous.openConversation': 'Read the conversation',
  'admin.col.type': 'Type',
  'admin.col.members': 'Members',
  'admin.col.createdOn': 'Created',
  'admin.col.lastMessage': 'Last message',
  'admin.tab.profile': 'Profile',
  'admin.tab.conversations': 'Conversations',
  'admin.tab.media': 'Media',
  'admin.tab.contacts': 'Contacts',
  'admin.tab.communities': 'Communities',
  'admin.tab.voice': 'Voice profile',
  'admin.tab.security': 'Security',
  'admin.tab.reports': 'Reports',
  'admin.tab.label': 'Profile sections',
  'admin.dossier.empty': 'Nothing to show.',
  'admin.dossier.restricted': 'Restricted to administrators cleared for sensitive data.',
  'admin.contacts.sent': 'Sent',
  'admin.contacts.received': 'Received',
  'admin.contacts.direction': 'Request',
  'admin.contacts.links': '{share} share link(s) · {tracking} tracking link(s) · {affiliate} affiliate token(s)',
  'admin.communities.creator': 'Creator',
  'admin.communities.private': 'Private',
  'admin.voice.none': 'No voice profile recorded.',
  'admin.voice.samples': 'Samples',
  'admin.voice.duration': 'Recorded duration',
  'admin.voice.model': 'Model',
  'admin.voice.consents': 'Consents',
  'admin.voice.consentProfile': 'Voice profile',
  'admin.voice.consentData': 'Voice data',
  'admin.voice.consentCloning': 'Voice cloning',
  'admin.voice.notGiven': 'not given',
  'admin.voice.traced': 'This view is recorded in the audit log.',
  'admin.security.sessions': 'Sessions',
  'admin.security.events': 'Security events',
  'admin.security.device': 'Device',
  'admin.security.place': 'Location',
  'admin.security.ip': 'IP address',
  'admin.security.valid': 'Open',
  'admin.security.closed': 'Closed',
  'admin.security.event': 'Event',
  'admin.security.severity': 'Severity',
  'admin.col.date': 'Date',
  'admin.reports.filed': 'Reports filed by this member',
  'admin.reports.received': 'Their reported messages',
  'admin.reports.subject': 'Subject',
  'admin.reports.reporter': 'Reported by',
  'admin.reports.reason': 'Reason',
  'admin.reports.message': 'Message',
  'admin.reports.withheld': 'text reserved for moderators',
  'admin.anonymous.link': 'Joined through link',
} satisfies AdminInterfaceCatalog;

export default en;
