import type { GameCatalog } from '@/lib/i18n-game-catalog';

/** Le catalogue du jeu, it (#9379) — mêmes clés et mêmes paramètres que le français ; textes de l'app iOS quand elle les porte. */
const it = {
  'game.points.one': '{count} punto',
  'game.points.other': '{count} punti',
  'game.points.convertible.one': '{count} punto convertibile',
  'game.points.convertible.other': '{count} punti convertibili',
  'game.days.one': '{count} giorno',
  'game.days.other': '{count} giorni',
  'game.actions.one': '{count} azione',
  'game.actions.other': '{count} azioni',
  'game.levels.one': '{count} livello',
  'game.levels.other': '{count} livelli',
  'game.meeshes.none': 'Nessuna Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meeshes',
  'game.mint.badges.one': '{count} badge scende',
  'game.mint.badges.other': '{count} badge scendono',
  'game.mint.badges.none': 'Nessun badge si spegne',
  'game.tier.etincelle': 'Scintilla',
  'game.tier.lueur': 'Barlume',
  'game.tier.lumiere': 'Luce',
  'game.tier.eclat': 'Splendore',
  'game.tier.rayon': 'Raggio',
  'game.tier.aurore': 'Aurora',
  'game.tier.comete': 'Cometa',
  'game.tier.etoile': 'Stella',
  'game.tier.constellation': 'Costellazione',
  'game.tier.galaxie': 'Galassia',
  'game.rank.murmure': 'Sussurro',
  'game.rank.echo': 'Eco',
  'game.rank.voix': 'Voce',
  'game.rank.conteur': 'Narratore',
  'game.rank.passeur': 'Traghettatore',
  'game.rank.polyglotte': 'Poliglotta',
  'game.rank.ambassadeur': 'Ambasciatore',
  'game.rank.orateur': 'Oratore',
  'game.rank.oracle': 'Oracolo',
  'game.rank.legende': 'Leggenda',
  'game.rank.mythe': 'Mito',
  'game.treasury.bourse': 'Borsa',
  'game.treasury.escarcelle': 'Scarsella',
  'game.treasury.coffret': 'Scrigno',
  'game.treasury.coffre': 'Forziere',
  'game.treasury.tresor': 'Tesoro',
  'game.treasury.reserve': 'Riserva',
  'game.flame.form.braise': 'Brace',
  'game.flame.form.flamme': 'Fiamma',
  'game.flame.form.brasier': 'Falò',
  'game.flame.form.astre': 'Astro',
  'game.flame.form.soleil': 'Sole',
  'game.edition.silver': 'argento',
  'game.edition.gold': 'oro',
  'game.edition.prism': 'prisma',
  'game.difficulty.easy': 'Facile',
  'game.difficulty.medium': 'Media',
  'game.difficulty.hard': 'Difficile',
  'game.difficulty.gold': 'Oro',
  'game.mission.react_messages.one': 'Reagire a {count} messaggio',
  'game.mission.react_messages.other': 'Reagire a {count} messaggi',
  'game.mission.send_voice.one': 'Invia un messaggio vocale',
  'game.mission.send_voice.other': 'Invia {count} messaggi vocali',
  'game.mission.send_texts.one': 'Invia {count} messaggio',
  'game.mission.send_texts.other': 'Invia {count} messaggi',
  'game.mission.use_stickers.one': 'Invia uno sticker',
  'game.mission.use_stickers.other': 'Invia {count} sticker',
  'game.mission.send_attachments.one': 'Invia un allegato',
  'game.mission.send_attachments.other': 'Invia {count} allegati',
  'game.mission.comment_text.one': 'Scrivi un commento',
  'game.mission.comment_text.other': 'Scrivi {count} commenti',
  'game.mission.publish_story.one': 'Pubblica una storia',
  'game.mission.publish_story.other': 'Pubblica {count} storie',
  'game.mission.publish_post.one': 'Pubblica un post',
  'game.mission.publish_post.other': 'Pubblica {count} post',
  'game.mission.share_link.one': 'Condividi un link',
  'game.mission.share_link.other': 'Condividi {count} link',
  'game.mission.prism_foreign_messages.one': 'Scrivi un messaggio in una lingua diversa dalla tua',
  'game.mission.prism_foreign_messages.other': 'Scrivi {count} messaggi in una lingua diversa dalla tua',
  'game.mission.voice_comments.one': 'Lascia un commento vocale',
  'game.mission.voice_comments.other': 'Lascia {count} commenti vocali',
  'game.mission.publish_reel.one': 'Pubblica un reel',
  'game.mission.publish_reel.other': 'Pubblica {count} reel',
  'game.mission.reply_conversations': 'Rispondi in {count} conversazioni diverse',
  'game.mission.prism_foreign_exchange': 'Scrivi {count} messaggi in una lingua diversa dalla tua',
  'game.mission.long_chat': 'Invia {count} messaggi',
  'game.mission.gold_replies_received': 'Ricevi risposte da {count} persone diverse',
  'game.mission.generic': 'Missione del giorno',
  'game.error.insufficient_points': 'Non hai abbastanza punti convertibili per coniare una Meesh.',
  'game.error.insufficient_meeshes': 'Per questo ti serve una Meesh in più.',
  'game.error.freeze_at_maximum': 'Hai già due congelamenti di riserva: è il massimo.',
  'game.error.relight_not_allowed': 'La Fiamma non può essere riaccesa adesso.',
  'game.error.mission_not_found': 'Questa missione non esiste più: la schermata si aggiorna.',
  'game.error.mission_reroll_exhausted': 'Hai già cambiato una missione oggi.',
  'game.error.mission_reroll_unavailable': 'Questa missione non può essere cambiata.',
  'game.error.missions_locked': 'Le missioni si aprono al livello 5.',
  'game.error.chest_not_ready': 'Completa prima le missioni del giorno per aprire il forziere.',
  'game.error.generic': 'Non è andata a buon fine: controlla la connessione e riprova.',
  'game.chest.chance': '1 possibilità su {odds}',
  'game.chest.reward.fragment': 'Un frammento di Meesh',
  'game.chest.reward.freeze': 'Un congelamento della Fiamma',
  'game.flame_panel.title': 'Proteggere la Fiamma',
  'game.flame_panel.bonus': '+{perDay} % per ogni giorno di serie sulle ricompense delle missioni, fino a\u00a0+{max} %.',
  'game.flame_panel.freezes': 'Congelamenti di riserva: {held} / {max}',
  'game.flame_panel.offline': 'Offline: congelamenti e riaccensione riprenderanno con la connessione.',
  'game.flame_panel.freeze_full': 'Riserva piena: un congelamento copre un giorno saltato, non te ne serve un altro.',
  'game.flame_panel.freeze_buy': 'Compra un congelamento · {price}',
  'game.flame_panel.freeze_missing': 'Per un congelamento ti serve {missing}.',
  'game.flame_panel.relight_intro': 'La tua Fiamma si è spenta: riaccendila adesso, riparte da dove si era fermata.',
  'game.flame_panel.relight': 'Riaccendi la Fiamma · {price}',
  'game.flame_panel.relight_missing': 'Per riaccenderla ti serve {missing}.',
  'game.flame_panel.relight_missing_window': 'Per riaccenderla ti serve {missing}, se si è spenta meno di 48 ore fa.',
  'game.flame_panel.relight_closed': 'Questa Fiamma non può più essere riaccesa. Una nuova Fiamma inizia con il tuo prossimo gesto.',
  'game.gauge.level': 'Livello',
  'game.level.title': 'Livello {level} · {tier}',
  'game.level.top': 'Sei in cima.',
  'game.level.to_next': 'Ancora {points} al livello {level}',
  'game.level.record': 'Record: livello {level}',
  'game.level.tailwind': ' · Vento in poppa ×{factor}',
  'game.gauge.rank': 'Rango',
  'game.rank.glory': 'Gloria {glory}',
  'game.rank.top': 'Il rango più alto',
  'game.rank.next': 'Ancora {missing} di Gloria prima di {rank}',
  'game.gauge.treasury': 'Tesoro',
  'game.treasury.hint': 'Tieni le tue Meesh: riempiono il tuo tesoro',
  'game.treasury.next': 'Ancora {missing} per {tier}',
  'game.gauge.flame': 'Fiamma',
  'game.flame.no_streak': 'Nessuna serie',
  'game.flame.form_line': '{form} ·\u00a0+{bonus} % sulle missioni',
  'game.flame.out_line': 'Fiamma spenta',
  'game.flame.status.none': 'Un gesto oggi accende la tua Fiamma',
  'game.flame.status.at_risk': 'Fai un gesto prima di mezzanotte',
  'game.flame.status.covered': 'Un congelamento la protegge',
  'game.flame.status.out': 'Spenta',
  'game.guide.speaker.mee': 'Mee',
  'game.guide.speaker.meo': 'Meo',
  'game.guide.speaker.duo': 'Mee e Meo',
  'game.guide.step_of': 'Passo {index} di {total}',
  'game.guide.more': 'Vedi la spiegazione completa',
  'game.guide.dismiss': 'Più tardi',
  'game.guide.skip': 'Salta',
  'game.guide.photo': 'Immortala questo momento',
  'game.guide.skip_all': 'Salta l’introduzione',
  'game.guide.action.start_game': 'Inizia il gioco',
  'game.guide.action.earn_first_points': 'Fai il mio primo gesto',
  'game.guide.action.see_level': 'Vedi il mio livello',
  'game.guide.action.see_missions': 'Vedi le missioni',
  'game.guide.action.see_flame': 'Vedi la mia Fiamma',
  'game.guide.action.see_meeshes': 'Vedi le Meesh',
  'game.guide.action.see_rank': 'Vedi il mio rango',
  'game.guide.action.take_start_photo': 'Scatta la foto di partenza',
  'game.guide.action.see_progress': 'Vedi i miei progressi',
  'game.guide.action.see_next_tier': 'Vedi la fascia successiva',
  'game.guide.action.open_first_mission': 'Apri la mia prima missione',
  'game.guide.action.mint_or_climb': 'Vedi l’anteprima del conio',
  'game.guide.action.regain_levels': 'Riprendi i miei livelli',
  'game.guide.action.relight_badge': 'Vedi i miei badge',
  'game.guide.action.see_mint_preview': 'Vedi l’anteprima del conio',
  'game.guide.action.take_photo': 'Immortala questo momento',
  'game.guide.action.keep_or_spend': 'Vedi il mio tesoro',
  'game.guide.action.do_easy_mission_or_freeze': 'Vedi le mie missioni',
  'game.guide.action.relight_flame': 'Riaccendi la Fiamma',
  'game.guide.action.do_easiest_mission': 'Vedi la missione più facile',
  'game.guide.action.prestige_or_stay': 'Vedi il mio livello',
  'game.guide.moment.first_level.what': 'Il tuo primo livello è conquistato.',
  'game.guide.moment.first_level.means': 'I tuoi punti riempiono l’anello: quando è pieno, sali di livello.',
  'game.guide.moment.first_level.next': 'Ancora {points} per il livello {level}.',
  'game.guide.moment.first_level.short': 'Livello {level}: ancora {points} per il prossimo.',
  'game.guide.moment.new_tier.what': 'Entri in {tier}!',
  'game.guide.moment.new_tier.means': 'Le fasce segnano il tuo cammino: dieci livelli ciascuna.',
  'game.guide.moment.new_tier.next': 'La fascia successiva si apre al livello {level}.',
  'game.guide.moment.new_tier.next_last': 'Sei all’ultima fascia.',
  'game.guide.moment.new_tier.short': 'Fascia {tier} raggiunta.',
  'game.guide.moment.missions_unlocked.what': 'Le missioni sono sbloccate.',
  'game.guide.moment.missions_unlocked.means': 'Tre missioni al giorno e un forziere da aprire quando le completi.',
  'game.guide.moment.missions_unlocked.next': 'Apri la tua prima missione.',
  'game.guide.moment.missions_unlocked.short': 'Le tue missioni del giorno ti aspettano.',
  'game.guide.moment.first_mint_possible.what': 'Puoi coniare la tua prima Meesh.',
  'game.guide.moment.first_mint_possible.means_free': 'Coniare costa {price}, senza perdere alcun livello, e fa guadagnare\u00a0+{glory} di Gloria.',
  'game.guide.moment.first_mint_possible.means': 'Coniare costa {price}, cioè {levels}, e fa guadagnare\u00a0+{glory} di Gloria.',
  'game.guide.moment.first_mint_possible.next': 'Conia ora, o sali prima.',
  'game.guide.moment.first_mint_possible.short': 'Una Meesh si conia per {price}.',
  'game.guide.moment.first_mint.what': 'Clac! La tua prima Meesh è coniata.',
  'game.guide.moment.first_mint.means': 'Il tuo livello è passato da {from} a {to}: è la regola. Il Vento in poppa è attivo.',
  'game.guide.moment.first_mint.next': 'Riprendi i tuoi livelli più in fretta: i tuoi punti valgono il 25 % in più fino al livello {level}.',
  'game.guide.moment.first_mint.short': 'Livello {from} → {to}. Il Vento in poppa ti aiuta fino al livello {level}.',
  'game.guide.moment.badge_extinguished.what': 'Un badge si è spento.',
  'game.guide.moment.badge_extinguished.means': 'È diventato un’impronta: niente è perso per sempre.',
  'game.guide.moment.badge_extinguished.next': 'Ancora {actions} per riaccenderlo.',
  'game.guide.moment.badge_extinguished.short': 'Un badge si è spento: {actions} per riaccenderlo.',
  'game.guide.moment.price_rises.what': 'Le Meesh diventano più rare.',
  'game.guide.moment.price_rises.means': 'Più ne conii, più costa la successiva.',
  'game.guide.moment.price_rises.next': 'La prossima costa {price}.',
  'game.guide.moment.price_rises.short': 'La prossima Meesh costa {price}.',
  'game.guide.moment.new_rank.what': 'Nuovo rango: {rank}.',
  'game.guide.moment.new_rank.means': 'La tua Gloria ha superato una soglia e non scende mai.',
  'game.guide.moment.new_rank.next': 'Ancora {glory} di Gloria per la divisione successiva. Immortala questo momento.',
  'game.guide.moment.new_rank.next_top': 'È il rango più alto. Immortala questo momento.',
  'game.guide.moment.new_rank.short': 'Sei {rank}.',
  'game.guide.moment.treasury_tier.what': 'Il tuo tesoro raggiunge la fascia {tier}.',
  'game.guide.moment.treasury_tier.means': 'Il tuo tesoro è visibile sul tuo profilo.',
  'game.guide.moment.treasury_tier.next': 'Tieni {meeshes} in più per la fascia successiva, oppure spendi.',
  'game.guide.moment.treasury_tier.next_top': 'Tienilo, oppure spendi le tue Meesh.',
  'game.guide.moment.treasury_tier.short': 'Tesoro: fascia {tier}.',
  'game.guide.moment.flame_at_risk.what': 'La tua Fiamma è in pericolo.',
  'game.guide.moment.flame_at_risk.means': 'Si spegne a mezzanotte se non fai nulla: {days} di serie da salvare.',
  'game.guide.moment.flame_at_risk.next': 'Fai una missione facile, oppure compra un congelamento.',
  'game.guide.moment.flame_at_risk.short': 'La tua Fiamma si spegne a mezzanotte: basta un gesto.',
  'game.guide.moment.flame_out.what': 'La tua Fiamma si è spenta.',
  'game.guide.moment.flame_out.means': 'Il Bonus Fiamma riparte da zero.',
  'game.guide.moment.flame_out.next': 'Riaccendila entro 48 ore per {price}.',
  'game.guide.moment.flame_out.next_new': 'Il tuo prossimo gesto ne accende una nuova.',
  'game.guide.moment.flame_out.short': 'Fiamma spenta: riaccendila per {price}.',
  'game.guide.moment.flame_out.short_new': 'Fiamma spenta: un nuovo gesto la riaccende.',
  'game.guide.moment.return_after_absence.what': 'Che bello rivederti!',
  'game.guide.moment.return_after_absence.means': 'Sei stato via {days}: il tuo rango, il tuo tesoro e la tua Gloria sono rimasti dove li avevi lasciati.',
  'game.guide.moment.return_after_absence.next': 'Comincia dalla missione più facile del giorno.',
  'game.guide.moment.return_after_absence.short': 'Bentornato: comincia dalla missione più facile.',
  'game.guide.moment.level_100.what': 'Livello 100: sei in cima!',
  'game.guide.moment.level_100.means': 'Il Prestigio riporta il tuo livello a 1 e ti dà una stella e un trofeo.',
  'game.guide.moment.level_100.next': 'Passa al Prestigio, oppure resta in cima.',
  'game.guide.moment.level_100.next_stay': 'Resta in cima quanto vuoi.',
  'game.guide.moment.level_100.short': 'Sei in cima.',
  'game.guide.step.welcome.what': 'Ciao, sono Mee! Con Meo ti spieghiamo il gioco in sette carte.',
  'game.guide.step.welcome.means': 'Ogni gesto utile fa guadagnare punti: scrivere, parlare, pubblicare, reagire, invitare.',
  'game.guide.step.welcome.next': 'Fai il tuo primo gesto, io conto i tuoi punti.',
  'game.guide.step.first_points.what': 'Bravo, i tuoi primi punti!',
  'game.guide.step.first_points.means': 'I punti fanno il livello: riempiono il tuo anello.',
  'game.guide.step.first_points.next': 'Guarda il tuo anello riempirsi.',
  'game.guide.step.levels.what': 'Cento livelli, dieci fasce.',
  'game.guide.step.levels.means': 'Ogni livello richiede un po’ più di punti del precedente.',
  'game.guide.step.levels.next': 'Le missioni si aprono al livello 5.',
  'game.guide.step.missions.what': 'Ogni giorno, tre missioni e un forziere.',
  'game.guide.step.missions.means': 'Completale per aprire il forziere e alimentare la tua Fiamma.',
  'game.guide.step.missions.next': 'Una Fiamma cresce finché torni.',
  'game.guide.step.flame.what': 'La tua Fiamma cresce ogni giorno in cui agisci.',
  'game.guide.step.flame.means': 'Ogni giorno di serie aggiunge il 2 % alle ricompense delle missioni, fino al 50 %. Un congelamento copre un giorno saltato.',
  'game.guide.step.flame.next': 'I tuoi punti possono diventare Meesh.',
  'game.guide.step.mint.what': 'A partire da 1.221 punti si conia una Meesh.',
  'game.guide.step.mint.means': 'I punti spesi escono dal tuo livello, ma il tuo rango non scende mai: ogni conio aggiunge Gloria.',
  'game.guide.step.mint.next': 'La Gloria dà il rango.',
  'game.guide.step.rank.what': 'Il tuo rango non scende mai.',
  'game.guide.step.rank.means': 'Coniare, battere record, ottenere traguardi: tutto aggiunge Gloria.',
  'game.guide.step.rank.next': 'Immortaliamo la tua partenza con una foto.',
  'game.rules.1.title': 'Ogni gesto conta',
  'game.rules.1.body': 'Scrivere, parlare, pubblicare, reagire, invitare: ogni azione utile fa guadagnare punti.',
  'game.rules.2.title': 'I punti fanno il livello',
  'game.rules.2.body': '100 livelli in 10 fasce. Ogni livello richiede un po’ più del precedente.',
  'game.rules.3.title': 'Si coniano Meesh',
  'game.rules.3.body': 'A partire da 1.221 punti si conia una Meesh a mano. Il prezzo sale con il numero di Meesh già coniate.',
  'game.rules.4.title': 'Coniare fa scendere',
  'game.rules.4.body': 'I punti spesi escono dal livello. I badge che sostenevano possono spegnersi.',
  'game.rules.5.title': 'Il tuo rango non scende mai',
  'game.rules.5.body': 'Ogni conio, ogni record, ogni traguardo aggiunge Gloria. La Gloria dà il rango.',
  'game.rules.6.title': 'Il tesoro si tiene o si spende',
  'game.rules.6.body': 'Tenere le tue Meesh fa crescere il tesoro. Spenderle protegge la Fiamma o regala cosmetici.',
  'game.rules.7.title': 'Ogni giorno conta',
  'game.rules.7.body': 'Tre missioni, un forziere, una Fiamma che cresce finché si torna.',
  'game.rules.8.title': 'Si conserva una traccia',
  'game.rules.8.body': 'Ogni grande momento si fotografa con Mee e Meo nel quaderno dei progressi.',
  'game.rules.page_title': 'Come funziona',
  'game.rules.intro': 'Otto regole, e tutto il gioco ci sta dentro. Meo le spiega, Mee ti mostra il gesto.',
  'game.rules.section_rules': 'Le regole in una pagina',
  'game.rules.section_steps': 'I sette passi',
  'game.page.back': 'Torna ai progressi',
  'game.door.rules': 'Come funziona',
  'game.door.notebook': 'Quaderno dei progressi',
  'game.mint.minted_line': 'Meesh n. {number} coniata, {edition}.',
  'game.mint.action': 'Conia con Mee e Meo',
  'game.mint.minting': 'Conio in corso…',
  'game.mint.offline': 'Offline: il conio riprenderà con la connessione.',
  'game.mint.missing': 'Ancora {missing} prima della prossima Meesh: costa {price}.',
  'game.mint.next_title': 'Prossima Meesh · n. {number}',
  'game.mint.next_subtitle': 'Edizione {edition} · {price}',
  'game.mint.row.price': 'Prezzo',
  'game.mint.row.level': 'Livello',
  'game.mint.row.treasury': 'Tesoro',
  'game.mint.row.glory': 'Gloria',
  'game.mint.row.badges': 'Badge',
  'game.mint.row.tailwind': 'Vento in poppa',
  'game.mint.tailwind_value': '+25 % sui tuoi punti fino al livello {level}',
  'game.missions.title': 'Missioni del giorno',
  'game.missions.locked': 'Le missioni si aprono al livello 5: tre al giorno e un forziere. Sei al livello {level}.',
  'game.missions.prism_day': 'Giorno del Prisma: una delle missioni si gioca in una lingua diversa dalla tua.',
  'game.missions.prism_hour': 'Ora del Prisma: {start} – {end} — le tue missioni contano doppio.',
  'game.missions.offline': 'Offline: cambiare una missione o aprire il forziere riprenderà con la connessione.',
  'game.mission.prism': 'Prisma',
  'game.mission.done': 'Fatta',
  'game.mission.reroll': 'Cambia · 1 Meesh',
  'game.mission.reroll.a11y': 'Cambia la missione «{title}» con 1 Meesh',
  'game.chest.title': 'Forziere del giorno',
  'game.chest.locked': 'Completa le missioni del giorno per aprirlo.',
  'game.chest.opening': 'Apertura in corso…',
  'game.chest.open': 'Apri il forziere',
  'game.chest.claimed': 'Torna domani per il prossimo.',
  'game.chest.odds': '{min} a {max} · {fragment} di un frammento · {freeze} di un congelamento',
  'game.notebook.page_title': 'Quaderno dei progressi',
  'game.notebook.empty': 'Il tuo quaderno è vuoto. I grandi momenti — un rango, una prima Meesh, una Fiamma di 7 giorni — si fotografano con Mee e Meo, e la foto resta sul tuo dispositivo.',
  'game.notebook.pending': 'In attesa',
  'game.notebook.kept': 'Foto conservate',
  'game.notebook.photo_a11y': 'Foto: {title}',
  'game.notebook.remove': 'Rimuovi',
  'game.photo.offer.start': 'Fotografa',
  'game.photo.offer.title': 'Lo immortaliamo?',
  'game.photo.share': 'Condividi',
  'game.photo.a11y': 'Foto: {title}',
  'game.photo.close': 'Chiudi',
  'game.photo.selfie': 'Selfie con noi',
  'game.photo.card_only': 'Solo la carta',
  'game.photo.later': 'Più tardi',
  'game.photo.gallery': 'Scegli una foto dalla galleria',
  'game.photo.shutter': 'Scatta la foto',
  'game.photo.camera.denied': 'La fotocamera è negata. Consentila nelle impostazioni del dispositivo, oppure scegli una foto dalla galleria.',
  'game.photo.camera.unsupported': 'Questo dispositivo non consente la fotocamera qui. Scegli una foto dalla galleria, oppure tieni solo la carta.',
  'game.photo.camera.unavailable': 'La fotocamera non è disponibile (la sta usando un’altra app?). Scegli una foto dalla galleria, oppure tieni solo la carta.',
  'game.photo.striking': 'Mee e Meo coniano il momento nella foto',
  'game.photo.preview': 'Anteprima: {title}',
  'game.photo.format.story': '9:16 · storia',
  'game.photo.format.square': '1:1 · profilo',
  'game.photo.save': 'Salva',
  'game.photo.kept': 'Conservata',
  'game.photo.keep': 'Conserva',
  'game.photo.kicker.start': 'Primi passi',
  'game.photo.title.start': 'La mia partenza su Meeshy',
  'game.photo.kicker.rank': 'Nuovo rango',
  'game.photo.kicker.tier': 'Livello {level}',
  'game.photo.title.tier': 'Fascia {tier}',
  'game.photo.kicker.summit': 'In cima',
  'game.photo.kicker.new_lap': 'Nuovo giro',
  'game.photo.title.level_100': 'Livello 100',
  'game.photo.title.prestige': 'Prestigio {count}',
  'game.photo.title.meesh_first': 'La mia prima Meesh',
  'game.photo.title.meesh_number': 'Meesh n. {number}',
  'game.photo.title.meesh_number_edition': 'Meesh n. {number} · {edition}',
  'game.photo.kicker.meesh': 'Meesh coniata',
  'game.photo.kicker.treasury': 'Tesoro',
  'game.photo.kicker.flame': 'Fiamma',
  'game.photo.title.flame_days': '{count} giorni di Fiamma',
  'game.photo.notice.kept': 'Conservata nel quaderno dei progressi.',
  'game.photo.notice.keep_failed': 'Il quaderno non è disponibile su questo dispositivo: la foto non è stata conservata.',
  'game.photo.notice.save_failed': 'Il salvataggio non è andato a buon fine.',
  'game.photo.notice.shared': 'Immagine condivisa.',
  'game.mission.glory': '+{glory} di Gloria',
  'game.guide.collapse': 'Comprimi',
  'game.guide.collapse_a11y': 'Comprimi la spiegazione',
  'game.guide.awaiting.missions': 'Fai la missione più facile del giorno: ti aspetto per proseguire.',
  'game.guide.awaiting.flame': 'Torna domani e fai un gesto: la tua serie arriverà a 2 giorni.',
  'game.photo.private': 'La foto resta sul tuo dispositivo finché non la condividi.',
  'game.photo.camera.opening': 'Apertura della fotocamera…',
  'game.photo.gallery.unreadable': 'Impossibile leggere questa immagine.',
  'game.photo.format.group': 'Formato dell’immagine',
  'game.photo.notice.saved_file': 'Immagine salvata.',
  'game.photo.notice.share_failed': 'La condivisione non è riuscita.',
  'game.photo.compose_unsupported': 'Questo browser non sa comporre l’immagine. Il tuo momento resta nei tuoi progressi.',
  'game.notebook.pending_until': 'In attesa fino al {date}',
  'game.notebook.remove_confirm': 'Conferma la rimozione',
  'game.mint.number_label': 'n. {number}',
  'game.chest.contents': 'Contenuto del forziere',
  'game.fmt.signed': '+{value}',
  'game.fmt.minus': '−{value}',
  'game.fmt.fraction': '{done} / {total}',
  'game.fmt.from_to': '{from} → {to}',
  'game.error.request_id_conflict': 'Quell’identificativo della richiesta è già stato usato per un’altra azione: riprova, ne verrà inviato uno nuovo.',
  'game.level.ring_label': 'Livello {level}, fascia {tier}, {ordinal}',
  'game.tier.ordinal.1': 'prima fascia',
  'game.tier.ordinal.2': 'seconda fascia',
  'game.tier.ordinal.3': 'terza fascia',
  'game.tier.ordinal.4': 'quarta fascia',
  'game.tier.ordinal.5': 'quinta fascia',
  'game.tier.ordinal.6': 'sesta fascia',
  'game.tier.ordinal.7': 'settima fascia',
  'game.tier.ordinal.8': 'ottava fascia',
  'game.tier.ordinal.9': 'nona fascia',
  'game.tier.ordinal.10': 'decima fascia',
  'game.material.copper': 'Rame',
  'game.material.bronze': 'Bronzo',
  'game.material.silver': 'Argento',
  'game.material.gold': 'Oro',
  'game.material.platinum': 'Platino',
  'game.material.obsidian': 'Ossidiana',
  'game.material.prism': 'Prisma',
  'game.medal.label': '{axis}, {material}, {value} su {next} verso {nextMaterial}',
  'game.medal.label_top': '{axis}, {material}, {value}',
  'game.medal.label_off': '{axis}, non ancora ottenuta, ne mancano {missing}',
  'game.family.content': 'Contenuti',
  'game.family.comment': 'Commenti',
  'game.family.conversation': 'Conversazioni',
  'game.family.tool': 'Strumenti',
  'game.family.social': 'Legami',
  'game.hero.earn_title': 'Come guadagnare punti',
  'game.hero.earn_chip': '{family} +{points}',
  'game.hero.earn_chip_a11y': '{family}: {points} per gesto. Vedi le regole.',
  'game.hero.mint_title': 'Come coniare',
  'game.hero.mint_price': '{price} → una Meesh',
  'game.hero.mint_cost': 'costa {levels}',
  'game.hero.mint_glory': '+{glory} Gloria',
  'game.hero.mint_missing': 'Ancora {missing}',
  'game.hero.mee_idle': 'Una domanda? Toccami, ti spiego.',
  'game.photo.referral.headline': 'Unisciti a me su Meeshy',
  'game.photo.referral.share_text': 'Unisciti a me su Meeshy: {link}',
  'game.photo.referral.flame_days': '{days} g',
} as const satisfies GameCatalog;

export default it;
