/**
 * LES PACKS DE STICKERS (#9141) — tranche du catalogue `catalog-pt.ts` :
 * onglets de pack, boutique, proposition d'un pack par un tiers et ses refus
 * motivés. Le catalogue la RÉPAND.
 */
const ptStickerPacks = {
  'stickerPacks.by': 'Por {author}',
  'stickerPacks.cancel': 'Cancelar',
  'stickerPacks.send': 'Enviar',
  'stickerPacks.count': '{count} figurinhas',
  'stickerPacks.install': 'Instalar',
  'stickerPacks.uninstall': 'Remover',
  'stickerPacks.tab.shop': 'Loja',
  'stickerPacks.shop.hint': 'Instale os pacotes que quer ver nas suas figurinhas e remova os outros. As figurinhas já enviadas continuam legíveis.',
  'stickerPacks.error.install': 'Não foi possível alterar o pacote — tente novamente',
  'stickerPacks.error.load': 'Não foi possível carregar os pacotes',
  'stickerPacks.kind.static': 'Estáticas',
  'stickerPacks.kind.cinematic': 'Animadas',
  'stickerPacks.kind.instant': 'Instantes',
  'stickerPacks.status.pending': 'Pendente',
  'stickerPacks.status.approved': 'Publicado',
  'stickerPacks.status.rejected': 'Recusado',
  'stickerPacks.mine.title': 'Minhas propostas',
  'stickerPacks.submit.open': 'Propor um pacote',
  'stickerPacks.submit.title': 'Propor um pacote',
  'stickerPacks.submit.back': 'Voltar',
  'stickerPacks.submit.hint': 'Adicione pelo menos três imagens (PNG, WebP, GIF ou JPEG). Uma imagem animada vira uma figurinha animada; marque «Instante» para que uma figurinha escreva o texto de quem a envia. Cada pacote é revisado antes da publicação.',
  'stickerPacks.submit.name': 'Nome do pacote',
  'stickerPacks.submit.description': 'Descrição',
  'stickerPacks.submit.author': 'Assinatura',
  'stickerPacks.submit.add': 'Adicionar imagens',
  'stickerPacks.submit.itemTitle': 'Título',
  'stickerPacks.submit.emoji': 'Emoji',
  'stickerPacks.submit.instant': 'Instante',
  'stickerPacks.submit.removeItem': 'Remover esta figurinha',
  'stickerPacks.submit.zoneHint': 'Desenhe na imagem a área onde o texto será escrito. A pré-visualização mostra o texto mais longo permitido.',
  'stickerPacks.submit.zoneDefault': 'Texto padrão',
  'stickerPacks.submit.zoneLength': 'Comprimento máximo',
  'stickerPacks.submit.send': 'Enviar para revisão',
  'stickerPacks.submit.sending': 'Enviando…',
  'stickerPacks.submit.failed': 'Não foi possível enviar o pacote — tente novamente',
  'stickerPacks.submit.slugTaken': 'Este nome já está em uso — escolha outro',
  'stickerPacks.submit.tooMany': 'Três dos seus pacotes já aguardam revisão',
  'stickerPacks.submit.assetRefused': 'Não foi possível ler uma imagem — substitua-a',
  'stickerPacks.submit.tooLarge': 'O pacote está pesado demais — remova algumas imagens',
  'stickerPacks.problem.invalid': 'Um campo não é válido',
  'stickerPacks.problem.reservedSlug': 'Este nome é reservado — escolha outro',
  'stickerPacks.problem.duplicate': 'Duas figurinhas têm o mesmo nome',
  'stickerPacks.problem.duplicateSlot': 'Duas áreas têm o mesmo nome',
  'stickerPacks.problem.zonesRequired': 'Um Instante precisa de uma área de texto',
  'stickerPacks.problem.zoneOutside': 'A área sai da imagem',
  'stickerPacks.problem.zonesOverlap': 'Duas áreas se sobrepõem',
  'stickerPacks.problem.defaultTooLong': 'O texto padrão é mais longo do que a área permite',
  'stickerPacks.problem.defaultOverflows': 'O texto padrão transborda da área',
  'stickerPacks.problem.longestOverflows': 'Um texto de comprimento máximo transbordaria: aumente a área ou reduza o comprimento',
  'stickerPacks.problem.count': 'Um pacote tem entre 3 e 120 figurinhas',
  'stickerPacks.problem.packField': 'Dê ao pacote um nome, uma descrição e uma assinatura',
};

export default ptStickerPacks;
