import type { GameCatalog } from '@/lib/i18n-game-catalog';

/** Le catalogue du jeu, en (#9379) — mêmes clés et mêmes paramètres que le français ; textes de l'app iOS quand elle les porte. */
const en = {
  'game.points.one': '{count} point',
  'game.points.other': '{count} points',
  'game.points.convertible.one': '{count} convertible point',
  'game.points.convertible.other': '{count} convertible points',
  'game.days.one': '{count} day',
  'game.days.other': '{count} days',
  'game.actions.one': '{count} action',
  'game.actions.other': '{count} actions',
  'game.levels.one': '{count} level',
  'game.levels.other': '{count} levels',
  'game.meeshes.none': 'No Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meeshes',
  'game.mint.badges.one': '{count} badge goes down',
  'game.mint.badges.other': '{count} badges go down',
  'game.mint.badges.none': 'No badge goes out',
  'game.tier.etincelle': 'Spark',
  'game.tier.lueur': 'Glimmer',
  'game.tier.lumiere': 'Light',
  'game.tier.eclat': 'Radiance',
  'game.tier.rayon': 'Ray',
  'game.tier.aurore': 'Dawn',
  'game.tier.comete': 'Comet',
  'game.tier.etoile': 'Star',
  'game.tier.constellation': 'Constellation',
  'game.tier.galaxie': 'Galaxy',
  'game.rank.murmure': 'Whisper',
  'game.rank.echo': 'Echo',
  'game.rank.voix': 'Voice',
  'game.rank.conteur': 'Storyteller',
  'game.rank.passeur': 'Bridge-builder',
  'game.rank.polyglotte': 'Polyglot',
  'game.rank.ambassadeur': 'Ambassador',
  'game.rank.orateur': 'Orator',
  'game.rank.oracle': 'Oracle',
  'game.rank.legende': 'Legend',
  'game.rank.mythe': 'Myth',
  'game.treasury.bourse': 'Purse',
  'game.treasury.escarcelle': 'Pouch',
  'game.treasury.coffret': 'Casket',
  'game.treasury.coffre': 'Chest',
  'game.treasury.tresor': 'Treasure',
  'game.treasury.reserve': 'Reserve',
  'game.flame.form.braise': 'Ember',
  'game.flame.form.flamme': 'Flame',
  'game.flame.form.brasier': 'Blaze',
  'game.flame.form.astre': 'Luminary',
  'game.flame.form.soleil': 'Sun',
  'game.edition.silver': 'silver',
  'game.edition.gold': 'gold',
  'game.edition.prism': 'prism',
  'game.difficulty.easy': 'Easy',
  'game.difficulty.medium': 'Medium',
  'game.difficulty.hard': 'Hard',
  'game.difficulty.gold': 'Gold',
  'game.mission.react_messages.one': 'React to {count} message',
  'game.mission.react_messages.other': 'React to {count} messages',
  'game.mission.send_voice.one': 'Send a voice message',
  'game.mission.send_voice.other': 'Send {count} voice messages',
  'game.mission.send_texts.one': 'Send {count} message',
  'game.mission.send_texts.other': 'Send {count} messages',
  'game.mission.use_stickers.one': 'Send a sticker',
  'game.mission.use_stickers.other': 'Send {count} stickers',
  'game.mission.send_attachments.one': 'Send an attachment',
  'game.mission.send_attachments.other': 'Send {count} attachments',
  'game.mission.comment_text.one': 'Write a comment',
  'game.mission.comment_text.other': 'Write {count} comments',
  'game.mission.publish_story.one': 'Publish a story',
  'game.mission.publish_story.other': 'Publish {count} stories',
  'game.mission.publish_post.one': 'Publish a post',
  'game.mission.publish_post.other': 'Publish {count} posts',
  'game.mission.share_link.one': 'Share a link',
  'game.mission.share_link.other': 'Share {count} links',
  'game.mission.prism_foreign_messages.one': 'Write a message in a language other than yours',
  'game.mission.prism_foreign_messages.other': 'Write {count} messages in a language other than yours',
  'game.mission.voice_comments.one': 'Leave a voice comment',
  'game.mission.voice_comments.other': 'Leave {count} voice comments',
  'game.mission.publish_reel.one': 'Publish a reel',
  'game.mission.publish_reel.other': 'Publish {count} reels',
  'game.mission.reply_conversations': 'Reply in {count} different conversations',
  'game.mission.prism_foreign_exchange': 'Write {count} messages in a language other than yours',
  'game.mission.long_chat': 'Send {count} messages',
  'game.mission.gold_replies_received': 'Get replies from {count} different people',
  'game.mission.generic': 'Mission of the day',
  'game.error.insufficient_points': 'Not enough convertible points to mint a Meesh.',
  'game.error.insufficient_meeshes': 'You need one more Meesh for that.',
  'game.error.freeze_at_maximum': 'You already have two freezes in reserve: that is the maximum.',
  'game.error.relight_not_allowed': 'The Flame cannot be relit right now.',
  'game.error.mission_not_found': 'This mission no longer exists: the screen is refreshing.',
  'game.error.mission_reroll_exhausted': 'You already changed a mission today.',
  'game.error.mission_reroll_unavailable': 'This mission cannot be changed.',
  'game.error.missions_locked': 'Missions open at level 5.',
  'game.error.chest_not_ready': 'Finish the day’s missions first to open the chest.',
  'game.error.generic': 'That did not go through — check your connection and try again.',
  'game.chest.chance': '1 chance in {odds}',
  'game.chest.reward.fragment': 'A Meesh fragment',
  'game.chest.reward.freeze': 'A Flame freeze',
  'game.flame_panel.title': 'Protect the Flame',
  'game.flame_panel.bonus': '+{perDay} % per streak day on mission rewards, up to\u00a0+{max} %.',
  'game.flame_panel.freezes': 'Freezes in reserve: {held} / {max}',
  'game.flame_panel.offline': 'Offline: freezes and relighting will resume when you are back online.',
  'game.flame_panel.freeze_full': 'Reserve full: a freeze covers one missed day, you do not need another.',
  'game.flame_panel.freeze_buy': 'Buy a freeze · {price}',
  'game.flame_panel.freeze_missing': 'You need {missing} for a freeze.',
  'game.flame_panel.relight_intro': 'Your Flame went out: relight it now, it picks up where it stopped.',
  'game.flame_panel.relight': 'Relight the Flame · {price}',
  'game.flame_panel.relight_missing': 'You need {missing} to relight it.',
  'game.flame_panel.relight_missing_window': 'You need {missing} to relight it, if it went out less than 48 h ago.',
  'game.flame_panel.relight_closed': 'This Flame can no longer be relit. A new Flame starts with your next action.',
  'game.gauge.level': 'Level',
  'game.level.title': 'Level {level} · {tier}',
  'game.level.top': 'You are at the top.',
  'game.level.to_next': '{points} more before level {level}',
  'game.level.record': 'Record: level {level}',
  'game.level.tailwind': ' · Tailwind ×{factor}',
  'game.gauge.rank': 'Rank',
  'game.rank.glory': 'Glory {glory}',
  'game.rank.top': 'The highest rank',
  'game.rank.next': '{missing} more Glory before {rank}',
  'game.gauge.treasury': 'Treasury',
  'game.treasury.hint': 'Keep your Meeshes: they fill your treasury',
  'game.treasury.next': '{missing} more for {tier}',
  'game.gauge.flame': 'Flame',
  'game.flame.no_streak': 'No streak',
  'game.flame.form_line': '{form} ·\u00a0+{bonus} % on missions',
  'game.flame.out_line': 'Flame out',
  'game.flame.status.none': 'An action today lights your Flame',
  'game.flame.status.at_risk': 'Do something before midnight',
  'game.flame.status.covered': 'A freeze protects it',
  'game.flame.status.out': 'Out',
  'game.guide.speaker.mee': 'Mee',
  'game.guide.speaker.meo': 'Meo',
  'game.guide.speaker.duo': 'Mee and Meo',
  'game.guide.step_of': 'Step {index} of {total}',
  'game.guide.more': 'See the full explanation',
  'game.guide.dismiss': 'Later',
  'game.guide.skip': 'Skip',
  'game.guide.photo': 'Capture this moment',
  'game.guide.skip_all': 'Skip the walkthrough',
  'game.guide.action.start_game': 'Start the game',
  'game.guide.action.earn_first_points': 'Make my first move',
  'game.guide.action.see_level': 'See my level',
  'game.guide.action.see_missions': 'See the missions',
  'game.guide.action.see_flame': 'See my Flame',
  'game.guide.action.see_meeshes': 'See the Meeshes',
  'game.guide.action.see_rank': 'See my rank',
  'game.guide.action.take_start_photo': 'Take the starting photo',
  'game.guide.action.see_progress': 'See my progress',
  'game.guide.action.see_next_tier': 'See the next tier',
  'game.guide.action.open_first_mission': 'Open my first mission',
  'game.guide.action.mint_or_climb': 'See the mint preview',
  'game.guide.action.regain_levels': 'Win my levels back',
  'game.guide.action.relight_badge': 'See my badges',
  'game.guide.action.see_mint_preview': 'See the mint preview',
  'game.guide.action.take_photo': 'Capture this moment',
  'game.guide.action.keep_or_spend': 'See my treasury',
  'game.guide.action.do_easy_mission_or_freeze': 'See my missions',
  'game.guide.action.relight_flame': 'Relight the Flame',
  'game.guide.action.do_easiest_mission': 'See the easiest mission',
  'game.guide.action.prestige_or_stay': 'See my level',
  'game.guide.moment.first_level.what': 'Your first level is won.',
  'game.guide.moment.first_level.means': 'Your points fill the ring: when it is full, you go up a level.',
  'game.guide.moment.first_level.next': '{points} more for level {level}.',
  'game.guide.moment.first_level.short': 'Level {level}: {points} more for the next one.',
  'game.guide.moment.new_tier.what': 'You are entering {tier}!',
  'game.guide.moment.new_tier.means': 'Tiers mark your road: ten levels each.',
  'game.guide.moment.new_tier.next': 'The next tier opens at level {level}.',
  'game.guide.moment.new_tier.next_last': 'You are on the last tier.',
  'game.guide.moment.new_tier.short': 'Tier {tier} reached.',
  'game.guide.moment.missions_unlocked.what': 'Missions are unlocked.',
  'game.guide.moment.missions_unlocked.means': 'Three missions a day, and a chest to open when they are done.',
  'game.guide.moment.missions_unlocked.next': 'Open your first mission.',
  'game.guide.moment.missions_unlocked.short': 'Your missions of the day are waiting.',
  'game.guide.moment.first_mint_possible.what': 'You can mint your first Meesh.',
  'game.guide.moment.first_mint_possible.means_free': 'Minting costs {price}, without losing a level, and earns\u00a0+{glory} Glory.',
  'game.guide.moment.first_mint_possible.means': 'Minting costs {price}, that is {levels}, and earns\u00a0+{glory} Glory.',
  'game.guide.moment.first_mint_possible.next': 'Mint now, or climb first.',
  'game.guide.moment.first_mint_possible.short': 'A Meesh is minted for {price}.',
  'game.guide.moment.first_mint.what': 'Clack! Your first Meesh is minted.',
  'game.guide.moment.first_mint.means': 'Your level went from {from} to {to}: that is the rule. The Tailwind is on.',
  'game.guide.moment.first_mint.next': 'Win your levels back faster: your points count 25 % more up to level {level}.',
  'game.guide.moment.first_mint.short': 'Level {from} → {to}. The Tailwind helps you up to level {level}.',
  'game.guide.moment.badge_extinguished.what': 'A badge went out.',
  'game.guide.moment.badge_extinguished.means': 'It became an imprint: nothing is lost for good.',
  'game.guide.moment.badge_extinguished.next': '{actions} more to relight it.',
  'game.guide.moment.badge_extinguished.short': 'A badge went out: {actions} to relight it.',
  'game.guide.moment.price_rises.what': 'Meeshes are getting rarer.',
  'game.guide.moment.price_rises.means': 'The more you mint, the more the next one costs.',
  'game.guide.moment.price_rises.next': 'The next one costs {price}.',
  'game.guide.moment.price_rises.short': 'The next Meesh costs {price}.',
  'game.guide.moment.new_rank.what': 'New rank: {rank}.',
  'game.guide.moment.new_rank.means': 'Your Glory passed a threshold, and it never goes back down.',
  'game.guide.moment.new_rank.next': '{glory} more Glory for the next division. Capture this moment.',
  'game.guide.moment.new_rank.next_top': 'This is the highest rank. Capture this moment.',
  'game.guide.moment.new_rank.short': 'You are {rank}.',
  'game.guide.moment.treasury_tier.what': 'Your treasury reaches the {tier} tier.',
  'game.guide.moment.treasury_tier.means': 'Your treasury is visible on your profile.',
  'game.guide.moment.treasury_tier.next': 'Keep {meeshes} more for the next tier, or spend.',
  'game.guide.moment.treasury_tier.next_top': 'Keep it, or spend your Meeshes.',
  'game.guide.moment.treasury_tier.short': 'Treasury: {tier} tier.',
  'game.guide.moment.flame_at_risk.what': 'Your Flame is in danger.',
  'game.guide.moment.flame_at_risk.means': 'It goes out at midnight if you do nothing: {days} of streak to save.',
  'game.guide.moment.flame_at_risk.next': 'Do an easy mission, or buy a freeze.',
  'game.guide.moment.flame_at_risk.short': 'Your Flame goes out at midnight: one action is enough.',
  'game.guide.moment.flame_out.what': 'Your Flame went out.',
  'game.guide.moment.flame_out.means': 'The Flame Bonus starts again from zero.',
  'game.guide.moment.flame_out.next': 'Relight it within 48 h for {price}.',
  'game.guide.moment.flame_out.next_new': 'Your next action lights a new one.',
  'game.guide.moment.flame_out.short': 'Flame out: relight it for {price}.',
  'game.guide.moment.flame_out.short_new': 'Flame out: a new action relights it.',
  'game.guide.moment.return_after_absence.what': 'Good to see you again!',
  'game.guide.moment.return_after_absence.means': 'You were away {days}: your rank, treasury and Glory stayed where you left them.',
  'game.guide.moment.return_after_absence.next': 'Start with the easiest mission of the day.',
  'game.guide.moment.return_after_absence.short': 'Welcome back: start with the easiest mission.',
  'game.guide.moment.level_100.what': 'Level 100: you are at the top!',
  'game.guide.moment.level_100.means': 'Prestige resets your level to 1 and gives you a star and a trophy.',
  'game.guide.moment.level_100.next': 'Go Prestige, or stay at the top.',
  'game.guide.moment.level_100.next_stay': 'Stay at the top as long as you like.',
  'game.guide.moment.level_100.short': 'You are at the top.',
  'game.guide.step.welcome.what': 'Hi, I am Mee! With Meo, we will explain the game in seven cards.',
  'game.guide.step.welcome.means': 'Every useful action earns points: writing, talking, publishing, reacting, inviting.',
  'game.guide.step.welcome.next': 'Make your first move, I will count your points.',
  'game.guide.step.first_points.what': 'Well done, your first points!',
  'game.guide.step.first_points.means': 'Points make your level: they fill your ring.',
  'game.guide.step.first_points.next': 'Watch your ring fill up.',
  'game.guide.step.levels.what': 'A hundred levels, ten tiers.',
  'game.guide.step.levels.means': 'Each level asks for a little more points than the one before.',
  'game.guide.step.levels.next': 'Missions open at level 5.',
  'game.guide.step.missions.what': 'Every day, three missions and a chest.',
  'game.guide.step.missions.means': 'Do them to open the chest and feed your Flame.',
  'game.guide.step.missions.next': 'A Flame grows as long as you come back.',
  'game.guide.step.flame.what': 'Your Flame grows every day you act.',
  'game.guide.step.flame.means': 'Each streak day adds 2 % to your mission rewards, up to 50 %. A freeze covers a missed day.',
  'game.guide.step.flame.next': 'Your points can become Meeshes.',
  'game.guide.step.mint.what': 'From 1,221 points, you mint a Meesh.',
  'game.guide.step.mint.means': 'Spent points leave your level, but your rank never drops: every mint adds Glory.',
  'game.guide.step.mint.next': 'Glory gives the rank.',
  'game.guide.step.rank.what': 'Your rank never drops.',
  'game.guide.step.rank.means': 'Minting, beating records, earning achievements: everything adds Glory.',
  'game.guide.step.rank.next': 'Let us capture your start in a photo.',
  'game.rules.1.title': 'Every action pays',
  'game.rules.1.body': 'Writing, talking, publishing, reacting, inviting: every useful action earns points.',
  'game.rules.2.title': 'Points make the level',
  'game.rules.2.body': '100 levels in 10 tiers. Each level asks for a little more than the one before.',
  'game.rules.3.title': 'We mint Meeshes',
  'game.rules.3.body': 'From 1,221 points, you mint a Meesh by hand. The price rises with the number of Meeshes already minted.',
  'game.rules.4.title': 'Minting brings you down',
  'game.rules.4.body': 'Spent points leave the level. The badges they held may go out.',
  'game.rules.5.title': 'Your rank never drops',
  'game.rules.5.body': 'Every mint, every record, every achievement adds Glory. Glory gives the rank.',
  'game.rules.6.title': 'The treasury is kept or spent',
  'game.rules.6.body': 'Keeping your Meeshes grows the treasury. Spending them protects the Flame or buys cosmetics.',
  'game.rules.7.title': 'Every day counts',
  'game.rules.7.body': 'Three missions, a chest, a Flame that grows as long as you come back.',
  'game.rules.8.title': 'We keep a trace',
  'game.rules.8.body': 'Every big moment is photographed with Mee and Meo in the progress notebook.',
  'game.rules.page_title': 'How it works',
  'game.rules.intro': 'Eight rules, and the whole game fits inside. Meo explains them, Mee shows you the move.',
  'game.rules.section_rules': 'The rules on one page',
  'game.rules.section_steps': 'The seven steps',
  'game.page.back': 'Back to progress',
  'game.door.rules': 'How it works',
  'game.door.notebook': 'Progress notebook',
  'game.mint.minted_line': 'Meesh no. {number} minted, {edition}.',
  'game.mint.action': 'Mint with Mee and Meo',
  'game.mint.minting': 'Minting…',
  'game.mint.offline': 'Offline: minting will resume when you are back online.',
  'game.mint.missing': '{missing} more before the next Meesh: it costs {price}.',
  'game.mint.next_title': 'Next Meesh · no. {number}',
  'game.mint.next_subtitle': '{edition} edition · {price}',
  'game.mint.row.price': 'Price',
  'game.mint.row.level': 'Level',
  'game.mint.row.treasury': 'Treasury',
  'game.mint.row.glory': 'Glory',
  'game.mint.row.badges': 'Badges',
  'game.mint.row.tailwind': 'Tailwind',
  'game.mint.tailwind_value': '+25 % on your points up to level {level}',
  'game.missions.title': 'Missions of the day',
  'game.missions.locked': 'Missions open at level 5: three a day, and a chest. You are at level {level}.',
  'game.missions.prism_day': 'Prism day: one of the missions is played in a language other than yours.',
  'game.missions.prism_hour': 'Prism hour: {start} – {end} — your missions count double.',
  'game.missions.offline': 'Offline: changing a mission or opening the chest will resume online.',
  'game.mission.prism': 'Prism',
  'game.mission.done': 'Done',
  'game.mission.reroll': 'Change · 1 Meesh',
  'game.mission.reroll.a11y': 'Change the mission “{title}” for 1 Meesh',
  'game.chest.title': 'Chest of the day',
  'game.chest.locked': 'Finish the day’s missions to open it.',
  'game.chest.opening': 'Opening…',
  'game.chest.open': 'Open the chest',
  'game.chest.claimed': 'Come back tomorrow for the next one.',
  'game.chest.odds': '{min} to {max} · {fragment} of a fragment · {freeze} of a freeze',
  'game.notebook.page_title': 'Progress notebook',
  'game.notebook.empty': 'Your notebook is empty. Big moments — a rank, a first Meesh, a 7-day Flame — are photographed with Mee and Meo, and the photo stays on your device.',
  'game.notebook.pending': 'Pending',
  'game.notebook.kept': 'Kept photos',
  'game.notebook.photo_a11y': 'Photo: {title}',
  'game.notebook.remove': 'Remove',
  'game.photo.offer.start': 'Take the photo',
  'game.photo.offer.title': 'Shall we capture it?',
  'game.photo.share': 'Share',
  'game.photo.a11y': 'Photo: {title}',
  'game.photo.close': 'Close',
  'game.photo.selfie': 'Selfie with us',
  'game.photo.card_only': 'Card only',
  'game.photo.later': 'Later',
  'game.photo.gallery': 'Choose a photo from the gallery',
  'game.photo.shutter': 'Take the photo',
  'game.photo.camera.denied': 'The camera is denied. Allow it in your device settings, or pick a photo from your gallery.',
  'game.photo.camera.unsupported': 'This device does not allow the camera here. Pick a photo from your gallery, or keep the card only.',
  'game.photo.camera.unavailable': 'The camera is not available (is another app using it?). Pick a photo from your gallery, or keep the card only.',
  'game.photo.striking': 'Mee and Meo are striking the moment into the photo',
  'game.photo.preview': 'Preview: {title}',
  'game.photo.format.story': '9:16 · story',
  'game.photo.format.square': '1:1 · profile',
  'game.photo.save': 'Save',
  'game.photo.kept': 'Kept',
  'game.photo.keep': 'Keep',
  'game.photo.kicker.start': 'First steps',
  'game.photo.title.start': 'My start on Meeshy',
  'game.photo.kicker.rank': 'New rank',
  'game.photo.kicker.tier': 'Level {level}',
  'game.photo.title.tier': '{tier} tier',
  'game.photo.kicker.summit': 'At the top',
  'game.photo.kicker.new_lap': 'New lap',
  'game.photo.title.level_100': 'Level 100',
  'game.photo.title.prestige': 'Prestige {count}',
  'game.photo.title.meesh_first': 'My first Meesh',
  'game.photo.title.meesh_number': 'Meesh no. {number}',
  'game.photo.title.meesh_number_edition': 'Meesh no. {number} · {edition}',
  'game.photo.kicker.meesh': 'Meesh minted',
  'game.photo.kicker.treasury': 'Treasury',
  'game.photo.kicker.flame': 'Flame',
  'game.photo.kicker.achievement': 'Achievement unlocked',
  'game.photo.title.flame_days': '{count} days of Flame',
  'game.photo.notice.kept': 'Kept in the progress notebook.',
  'game.photo.notice.keep_failed': 'The notebook is not available on this device: the photo was not kept.',
  'game.photo.notice.save_failed': 'Saving did not go through.',
  'game.photo.notice.shared': 'Image shared.',
  'game.mission.glory': '+{glory} Glory',
  'game.guide.collapse': 'Collapse',
  'game.guide.collapse_a11y': 'Collapse the explanation',
  'game.guide.awaiting.missions': 'Do today’s easiest mission: I will wait for you before the next step.',
  'game.guide.awaiting.flame': 'Come back tomorrow and make a move: your streak will reach 2 days.',
  'game.photo.private': 'The photo stays on your device until you share it.',
  'game.photo.camera.opening': 'Opening the camera…',
  'game.photo.gallery.unreadable': 'This image could not be read.',
  'game.photo.format.group': 'Image format',
  'game.photo.notice.saved_file': 'Image saved.',
  'game.photo.notice.share_failed': 'Sharing did not go through.',
  'game.photo.compose_unsupported': 'This browser cannot compose the image. Your moment stays in your progress.',
  'game.notebook.pending_until': 'Waiting until {date}',
  'game.notebook.remove_confirm': 'Confirm removal',
  'game.mint.number_label': 'No. {number}',
  'game.chest.contents': 'Chest contents',
  'game.fmt.signed': '+{value}',
  'game.fmt.minus': '−{value}',
  'game.fmt.fraction': '{done} / {total}',
  'game.fmt.from_to': '{from} → {to}',
  'game.error.request_id_conflict': 'That request identifier was already used by another action: try again, a new one will be sent.',
  'game.level.ring_label': 'Level {level}, {tier} tier, {ordinal}',
  'game.banner.level': 'Level {level}',
  'game.banner.to_next': '{percent}% to {level}',
  'game.banner.top': 'at the top',
  'game.banner.league': '{league} league {place}',
  'game.banner.flame': 'Flame {days}',
  'game.banner.place.one': '{count}st',
  'game.banner.place.two': '{count}nd',
  'game.banner.place.few': '{count}rd',
  'game.banner.place.other': '{count}th',
  'game.banner.points': '{points} pts',
  'game.banner.missing': '{points} to go',
  'game.banner.separator': ', ',
  'game.tier.ordinal.1': 'first tier',
  'game.tier.ordinal.2': 'second tier',
  'game.tier.ordinal.3': 'third tier',
  'game.tier.ordinal.4': 'fourth tier',
  'game.tier.ordinal.5': 'fifth tier',
  'game.tier.ordinal.6': 'sixth tier',
  'game.tier.ordinal.7': 'seventh tier',
  'game.tier.ordinal.8': 'eighth tier',
  'game.tier.ordinal.9': 'ninth tier',
  'game.tier.ordinal.10': 'tenth tier',
  'game.material.copper': 'Copper',
  'game.material.bronze': 'Bronze',
  'game.material.silver': 'Silver',
  'game.material.gold': 'Gold',
  'game.material.platinum': 'Platinum',
  'game.material.obsidian': 'Obsidian',
  'game.material.prism': 'Prism',
  'game.medal.label': '{axis}, {material}, {value} of {next} toward {nextMaterial}',
  'game.medal.label_top': '{axis}, {material}, {value}',
  'game.medal.label_off': '{axis}, not earned yet, {missing} to go',
  'game.family.content': 'Content',
  'game.family.comment': 'Comments',
  'game.family.conversation': 'Conversations',
  'game.family.tool': 'Tools',
  'game.family.social': 'Social ties',
  'game.hero.earn_title': 'How to earn points',
  'game.hero.earn_chip': '{family} +{points}',
  'game.hero.earn_chip_a11y': '{family}: {points} per action. See the rules.',
  'game.hero.mint_title': 'How to mint',
  'game.hero.mint_price': '{price} → one Meesh',
  'game.hero.mint_cost': 'costs {levels}',
  'game.hero.mint_glory': '+{glory} Glory',
  'game.hero.mint_missing': '{missing} more',
  'game.hero.mee_idle': 'A question? Tap me, I’ll explain.',
  'game.photo.referral.headline': 'Join me on Meeshy',
  'game.photo.referral.share_text': 'Join me on Meeshy: {link}',
  'game.photo.referral.flame_days': '{days} d',
  'game.duration.days_hours': '{days} d {hours} h',
  'game.duration.hours': '{hours} h',
  'game.duration.minutes': '{minutes} min',
  'game.visibility.everyone': 'Everyone',
  'game.visibility.friends': 'My friends',
  'game.visibility.me': 'Only me',
  'game.door.league': 'League',
  'game.door.league.locked': 'From level {level}',
  'game.door.league.rank': '{league} · rank {rank} of {size}',
  'game.door.league.open': 'This week’s ranking',
  'game.door.season': 'Season {number}',
  'game.door.season.steps': 'Step {steps} of {total}',
  'game.door.season.none': 'No season open right now',
  'game.door.showcase': 'Trophy showcase',
  'game.door.showcase.count.one': '{count} trophy',
  'game.door.showcase.count.other': '{count} trophies',
  'game.door.showcase.empty': 'No trophy yet',
  'game.door.atlas': 'Language Atlas',
  'game.door.atlas.count': '{stamped} of {total} languages',
  'game.door.prestige': 'Prestige',
  'game.door.prestige.ready': 'You can go Prestige',
  'game.door.prestige.stars': 'Stars: {stars} of {max}',
  'game.door.prestige.locked': 'At level 100',
  'game.league.title': 'League',
  'game.league.name.quartz': 'Quartz',
  'game.league.name.ambre': 'Amber',
  'game.league.name.jade': 'Jade',
  'game.league.name.saphir': 'Sapphire',
  'game.league.name.rubis': 'Ruby',
  'game.league.name.amethyste': 'Amethyst',
  'game.league.name.diamant': 'Diamond',
  'game.league.name.prisme': 'Prism',
  'game.league.tab.mine': 'My league',
  'game.league.tab.friends': 'Friends',
  'game.league.closes': 'Closes in {remaining}',
  'game.league.week': 'Week of {date}',
  'game.league.locked': 'The league opens at level {level}: every week you compete against 29 other players with a similar level of activity. You are at level {current}.',
  'game.league.minor': 'The public league is not open for your account. The friends league always is.',
  'game.league.consent.title': 'Join the public league',
  'game.league.consent.shown': 'What others see: your pseudonym, your league and your points total for the week, updated once a day at 4 a.m.',
  'game.league.consent.who': 'Who sees it: up to 29 other players in your league, whom you don’t know. No name, no photo, no language.',
  'game.league.consent.how': 'How you are placed: according to the points you earn, with players of similar activity.',
  'game.league.consent.risk': 'A risk to be aware of: from one day to the next, your total shows that you played that day.',
  'game.league.consent.withdraw_info': 'You can withdraw your consent at any time with one tap, here or in settings. Your league data is deleted within 4 weeks at the latest.',
  'game.league.consent.accept': 'I agree and join',
  'game.league.consent.leave': 'Leave the public league',
  'game.league.pseudonym.label': 'League pseudonym (optional)',
  'game.league.pseudonym.hint': '3 to 20 characters. Not your name or your username. Leave empty: a pseudonym is drawn for you.',
  'game.league.pseudonym.drawn': 'Your pseudonym is drawn at random: not your name, not your username. It changes every season.',
  'game.league.pseudonym.save': 'Change pseudonym',
  'game.league.pseudonym.current': 'You play under the name {name}.',
  'game.league.pseudonym.invalid': 'This pseudonym isn’t valid: 3 to 20 characters, letters, digits, dot, dash, underscore.',
  'game.league.waiting': 'Noted. You will be placed in a group at the start of next week.',
  'game.league.rank_line': 'Rank {rank} of {size}',
  'game.league.zone.promotion': 'Promotion',
  'game.league.zone.safe': 'Safe',
  'game.league.zone.relegation': 'Relegation',
  'game.league.to_promotion': '{points} more to move up',
  'game.league.in_promotion': 'You move up if you keep your place.',
  'game.league.at_top': 'You are at the top of the leagues.',
  'game.league.cup.gold': 'Gold cup',
  'game.league.cup.silver': 'Silver cup',
  'game.league.cup.bronze': 'Bronze cup',
  'game.league.snapshot': 'The others’ ranking is frozen every day at 4 a.m.: nobody sees who is playing right now. Only your own row is live.',
  'game.league.me': 'You',
  'game.league.empty': 'The group is filling up: the ranking appears as soon as the first points come in.',
  'game.league.friends.title': 'Friends league',
  'game.league.friends.body': 'This week’s points, among accepted friends. Always open, no consent to give.',
  'game.league.friends.empty': 'Add friends to compare yourself with them every week.',
  'game.league.friends.unknown': 'A friend',
  'game.duo.title': 'Duo mission',
  'game.duo.locked': 'The duo mission opens at level {level}, for both of you. You are at level {current}.',
  'game.duo.none': 'Pick a friend: if you each finish your part within the week, the reward is doubled.',
  'game.duo.invite': 'Invite {name}',
  'game.duo.pick': 'Choose a friend',
  'game.duo.no_friends': 'You need an accepted friend to play a duo.',
  'game.duo.invited.inviter': 'Invitation sent to {name}. Waiting for the answer.',
  'game.duo.invited.invitee': '{name} invites you to this week’s duo mission.',
  'game.duo.accept': 'Accept',
  'game.duo.decline': 'Decline',
  'game.duo.cancel': 'Cancel the invitation',
  'game.duo.abandon': 'Leave the duo',
  'game.duo.progress.me': 'You: {done} of {target}',
  'game.duo.progress.partner': '{name}: {done} of {target}',
  'game.duo.progress.common': 'Together: {done} of {target}',
  'game.duo.reward': 'Your share: {points}',
  'game.duo.reward.doubled': 'Doubled reward: {points}',
  'game.duo.reward.hint': 'Doubled if you each finish your part.',
  'game.duo.completed': 'Duo completed this week.',
  'game.duo.abandoned': 'Duo left. A new duo opens next week.',
  'game.duo.expired': 'This week’s duo ended without completing.',
  'game.error.league_locked': 'The league opens at level 10.',
  'game.error.league_minor': 'The public league is not open for your account.',
  'game.error.league_consent_required': 'Agree to join the public league first.',
  'game.error.league_pseudonym_invalid': 'This pseudonym isn’t valid: 3 to 20 characters, letters, digits, dot, dash, underscore.',
  'game.error.league_pseudonym_taken': 'This pseudonym is already taken.',
  'game.error.league_pseudonym_forbidden': 'This pseudonym isn’t allowed: choose one that doesn’t identify you.',
  'game.error.duo_locked': 'The duo mission opens at level 20, for both of you.',
  'game.error.duo_not_friends': 'A duo is played between accepted friends.',
  'game.error.duo_already_active': 'One of you already has a duo this week.',
  'game.error.duo_not_found': 'This duo no longer exists: the screen is refreshing.',
  'game.error.duo_transition_refused': 'This action doesn’t apply to this duo.',
  'game.error.season_not_open': 'No season is open.',
  'game.error.season_step_not_found': 'This step doesn’t exist.',
  'game.error.season_step_locked': 'This step hasn’t been reached yet.',
  'game.error.season_step_already_claimed': 'This step has already been claimed.',
  'game.error.seal_already_owned': 'You already have this season’s Seal.',
  'game.error.prestige_level_too_low': 'Prestige opens at level 100.',
  'game.error.prestige_at_maximum': 'You already have all five Prestige stars.',
  'game.offline.action': 'Offline: this action will resume when you are back online.',
  'game.retry': 'Try again',
  'game.unavailable': 'This part of the game is not available on your server yet.',
  'game.season.title': 'Season',
  'game.season.heading': 'Season {number} · week {week} of {total}',
  'game.season.theme': 'Theme: {theme}',
  'game.season.stars.one': '{count} star',
  'game.season.stars.other': '{count} stars',
  'game.season.how': 'Daily missions and the duo give stars: {per} stars open a step. The whole path is free.',
  'game.season.to_next': '{stars} more for the next step',
  'game.season.steps_line': 'Step {steps} of {total}',
  'game.season.path': 'Free path',
  'game.season.step': 'Step {step}',
  'game.season.step.claimed': 'claimed',
  'game.season.step.ready': 'ready to claim',
  'game.season.step.locked': 'upcoming',
  'game.season.reward.fragment': 'A fragment',
  'game.season.reward.freeze': 'A Flame freeze',
  'game.season.reward.season-cup': 'The season cup',
  'game.season.claim': 'Claim step {step}',
  'game.season.completed': 'Path completed: a cup, a dated badge and 500 Glory.',
  'game.season.none': 'No season is open right now. The next one starts soon.',
  'game.season.seal.title': 'Seal row',
  'game.season.seal.body': 'The Seal is purely cosmetic: a collectible every {every} steps, with no effect on the game.',
  'game.season.seal.buy': 'Get the Seal · {price}',
  'game.season.seal.owned': 'You have this season’s Seal.',
  'game.season.seal.missing': 'You need more Meeshes for the Seal.',
  'game.season.seal.cosmetic': 'Seal item',
  'game.league.pseudonym.title': 'Your pseudonym',
  'game.league.pseudonym.new': 'New pseudonym',
  'game.league.pseudonym.hint_change': '3 to 20 characters. Not your name or your username.',
  'game.doors.label': 'The game',
  'game.trophy.league-cup': '{cup} — {league} league, week of {date}',
  'game.trophy.season-cup': 'Season {number} cup',
  'game.trophy.prestige': 'Prestige {number} trophy',
  'game.trophy.flame': 'Flame trophy, {days}',
  'game.trophy.plate.league': '{league} · W{week}',
  'game.trophy.league-cup-month': '{cup} — {league} league, {month}',
  'game.trophy.plate.league-month': '{league} · {month}',
  'game.trophy.plate.season': 'SEASON {number}',
  'game.trophy.plate.prestige': 'PRESTIGE {number}',
  'game.trophy.plate.flame': '{days} DAYS',
  'game.showcase.title': 'Trophy showcase',
  'game.showcase.empty': 'Your showcase is empty. League, season, Prestige and Flame cups are added as you earn them.',
  'game.showcase.order_hint': 'Arrange your trophies: move each one up or down a notch.',
  'game.showcase.move_up': 'Move up: {name}',
  'game.showcase.move_down': 'Move down: {name}',
  'game.showcase.awarded': 'Earned on {date}',
  'game.showcase.awarded_month': 'Earned in {month}',
  'game.showcase.awarded_month_count': 'Earned in {month} · ×{count}',
  'game.showcase.visibility': 'Who sees your showcase',
  'game.showcase.visibility_hint': 'A visitor only sees the month you earned a trophy, never the exact date. “Only me” closes the showcase to everyone else.',
  'game.visibility.field.showcase': 'Trophy showcase',
  'game.visibility.field.rank': 'Rank and level',
  'game.visibility.field.treasury': 'Treasury and Flame',
  'game.visibility.field.atlas': 'Language Atlas',
  'game.visibility.saving': 'Saving…',
  'game.atlas.title': 'Language Atlas',
  'game.atlas.intro': 'Every language you have really exchanged in — one message sent and one received with someone who writes it — adds a stamp to your passport.',
  'game.atlas.count': '{stamped} of {total} languages',
  'game.atlas.remaining': '{remaining} languages to discover',
  'game.atlas.stamps': 'Your stamps',
  'game.atlas.stamped_on': 'Stamped on {date}',
  'game.atlas.pending': 'Half-finished exchanges',
  'game.atlas.pending.sent': 'sent — a received message is missing',
  'game.atlas.pending.received': 'received — a sent message is missing',
  'game.atlas.empty': 'No stamp yet. Write in another language: as soon as someone replies, the first one arrives.',
  'game.atlas.privacy': 'Your Atlas is private by default: a language can say a lot about you. You choose who sees it. The game keeps the language, both directions and the date — never the other person or the conversation.',
  'game.atlas.visibility': 'Who sees your Atlas',
  'game.prestige.title': 'Prestige',
  'game.prestige.stars': 'Stars: {stars} of {max}',
  'game.prestige.locked': 'Prestige opens at level 100. You are at level {level}.',
  'game.prestige.max': 'You have all five stars: the top of the top.',
  'game.prestige.mee': 'You are at level 100: the top! You can go Prestige.',
  'game.prestige.meo': 'Your level goes back to 1 and your points in hand to 0. In return: a star on your ring, a numbered trophy and {glory} Glory. Your rank never drops.',
  'game.prestige.confirm.title': 'Go Prestige {number}?',
  'game.prestige.confirm.resets': 'What resets: your level (to 1) and your points in hand (to 0).',
  'game.prestige.confirm.keeps': 'What stays: your rank, your Glory, your Meeshes, your Flame and your trophies.',
  'game.prestige.confirm.access': 'Heads up: your league (level 10) and your duo (level 20) close until your record level gets back there.',
  'game.prestige.confirm.consent': 'Your consent to the public league stays on record: you get your league back at level 10.',
  'game.prestige.go': 'Go Prestige',
  'game.prestige.stay': 'Stay at the top',
  'game.prestige.done': 'Prestige {number}! One more star on your ring.',
  'game.rarity.common': 'Common',
  'game.rarity.rare': 'Rare',
  'game.rarity.epic': 'Epic',
  'game.rarity.legendary': 'Legendary',
  'game.rarity.mythic': 'Mythic',
  'game.rarity.share': '{percent} of accounts',
  'game.rarity.aria': 'Rarity: {name}, {share}',
  'game.rarity.measuring': 'Rarity being measured',
  'game.guide.action.see_league': 'See my league',
  'game.guide.action.see_season': 'See the season',
  'game.guide.action.see_trophies': 'See my showcase',
  'game.guide.action.see_atlas': 'See my Atlas',
  'game.guide.moment.league_first.what': 'Welcome to the {league} league!',
  'game.guide.moment.league_first.means': 'Every week you compete against 29 other players. The top 7 move up, the bottom 5 move down, and points start again from zero.',
  'game.guide.moment.league_first.next': '{points} more to move up this week.',
  'game.guide.moment.league_first.next_top': 'You are already at the top of the leagues.',
  'game.guide.moment.league_first.short': '{league} league: {points} to move up.',
  'game.guide.moment.league_promoted.what': 'You move up to the {league} league!',
  'game.guide.moment.league_promoted.means': 'You finished in place {rank} of the {from} league: the top 7 move up.',
  'game.guide.moment.league_promoted.next': 'A new week starts: points begin again from zero.',
  'game.guide.moment.league_promoted.short': 'Promoted: {league} league.',
  'game.guide.moment.league_relegated.what': 'You drop back to the {league} league.',
  'game.guide.moment.league_relegated.means': 'The bottom 5 of each group move down. No big deal: points start again from zero and nothing else drops.',
  'game.guide.moment.league_relegated.next': 'Climb back this week: {points} to move up.',
  'game.guide.moment.league_relegated.next_far': 'Climb back this week: every point counts.',
  'game.guide.moment.league_relegated.short': 'Back in the {league} league.',
  'game.guide.moment.season_start.what': 'Season {season} begins!',
  'game.guide.moment.season_start.means': 'Eight weeks, one theme: {theme}. Daily missions and the duo give stars, and every step is free.',
  'game.guide.moment.season_start.means_plain': 'Eight weeks and one theme. Daily missions and the duo give stars, and every step is free.',
  'game.guide.moment.season_start.next': '{steps} steps are waiting for you, enough to win a season cup.',
  'game.guide.moment.season_start.short': 'Season {season}: free steps.',
  'game.guide.moment.season_end.what_done': 'Season {season} over: full path completed!',
  'game.guide.moment.season_end.what': 'Season {season} is ending.',
  'game.guide.moment.season_end.means_done': 'You win the season cup, a dated badge and {glory} Glory.',
  'game.guide.moment.season_end.means': 'You got as far as step {steps} of 40. Nothing is lost: your level and rank stay as they are.',
  'game.guide.moment.season_end.next': 'The next season starts soon.',
  'game.guide.moment.season_end.short': 'Season {season} is over.',
  'game.guide.moment.trophy.what': 'A new trophy!',
  'game.guide.moment.trophy.means': '{title} joins your showcase. A trophy earns nothing: it is kept and shown.',
  'game.guide.moment.trophy.next': 'Arrange it your way, and choose who sees it.',
  'game.guide.moment.trophy.short': 'New trophy: {title}.',
  'game.guide.moment.prestige.what': 'Prestige {number}!',
  'game.guide.moment.prestige.means': 'A star on your ring, a numbered trophy and {glory} Glory. Your rank never drops.',
  'game.guide.moment.prestige.next': 'Your level goes back to 1: a new lap begins.',
  'game.guide.moment.prestige.short': 'Prestige {number}.',
  'game.guide.moment.atlas_stamp.what': 'New stamp: {language}!',
  'game.guide.moment.atlas_stamp.means': 'You really exchanged in this language: one message sent, one received.',
  'game.guide.moment.atlas_stamp.next': '{stamped} of {total} languages in your passport.',
  'game.guide.moment.atlas_stamp.short': 'Stamp: {language}.',
  'game.photo.kicker.trophy': 'New trophy',
  'game.photo.kicker.league_up': 'League promotion',
  'game.photo.kicker.season': 'Season completed',
  'game.photo.kicker.prestige': 'New Prestige',
  'game.photo.title.league_up': '{league} league',
  'game.door.settings': 'Game settings',
  'game.settings.title': 'Game settings',
  'game.settings.celebrations.title': 'Mee and Meo',
  'game.settings.celebrations.body': 'The Mee and Meo cards and the photo suggestions that appear on Progress. This setting applies to this device only.',
  'game.settings.celebrations.switch': 'Show celebrations',
  'game.settings.hidden.title': 'Hidden game',
  'game.settings.hidden.body': 'Hides the game everywhere on this device, closes your showcase, rank, treasury and Atlas to everyone else, and removes you from the public league. Your points and trophies are kept.',
  'game.settings.hidden.switch': 'Hide the game',
  'game.settings.hidden.card': 'The game is hidden on this device.',
  'game.settings.hidden.show': 'Show the game again',
  'game.settings.hidden.reopen_note': 'Your visibility settings stay closed: reopen them here whenever you like.',
  'game.settings.visibility.title': 'Who sees what',
  'game.settings.visibility.body': 'Outside accepted friends, nobody sees whether you are online or when you play. These settings say what your friends, or everyone, can see of your game.',
  'game.settings.league.title': 'Public league',
  'game.settings.league.on': 'You are in the public league under the name {name}.',
  'game.settings.league.on_unnamed': 'You are in the public league.',
  'game.settings.league.off': 'You are not in the public league. Your friends league stays open.',
  'game.settings.league.manage': 'Manage my league',
  'game.settings.help': 'How it works',
  'game.profile.title': 'My game',
  'game.profile.level': 'Level {level} · {tier}',
  'game.profile.glory': '{glory} Glory',
  'game.profile.treasury': '{meeshes} · {tier}',
  'game.profile.flame': 'Flame: {days}',
  'game.profile.showcase': 'Showcase',
  'game.profile.medals': 'Medals',
  'game.profile.see_progress': 'See my progress',
  'game.profile.see_showcase': 'See the whole showcase',
  'game.profile.visitor_title': '{name}’s showcase',
  'game.profile.no_trophy': 'No trophy yet.',
  'game.photo.referral.with_link': 'Add my invitation link',
  'game.photo.referral.with_flame': 'Add my Flame',
  'game.photo.referral.options': 'What the card carries',
  'game.photo.image_right': 'Meo: if other people are in the photo, ask for their agreement before sharing it.',
} as const satisfies GameCatalog;

export default en;
