/**
 * L'APPEL AUDIO ET VIDÉO (#6382) — tranche du catalogue `catalog-fr.ts`,
 * extraite pour tenir le budget de taille (CLAUDE.md) : le catalogue la
 * RÉPAND. Libellés repris d'iOS (`CallView.swift`, `IncomingCallView.swift`).
 */
const frCall = {
  'call.action.menu': 'Appeler',
  'call.action.audio': 'Appel vocal',
  'call.action.video': 'Appel vidéo',
  'call.action.return': 'Revenir à l’appel',
  'call.incoming.title.audio': 'Appel entrant',
  'call.incoming.title.video': 'Appel vidéo entrant',
  'call.incoming.title.tab': '📞 Appel entrant',
  'call.incoming.group': '{caller} appelle le groupe',
  'call.accept': 'Accepter',
  'call.accept.audioOnly': 'Répondre sans vidéo',
  'call.decline': 'Refuser',
  'call.outgoing.ringing': 'Appel en cours…',
  'call.outgoing.waiting': 'En attente du correspondant…',
  'call.connecting': 'Connexion…',
  'call.reconnecting': 'Reconnexion…',
  'call.mic.mute': 'Couper le micro',
  'call.mic.unmute': 'Activer le micro',
  'call.mic.muted': 'Micro coupé',
  'call.peer.muted': 'Contact en sourdine',
  'call.camera.on': 'Activer la caméra',
  'call.camera.off': 'Couper la caméra',
  'call.camera.switch': 'Changer de caméra',
  'call.video.swap': 'Inverser les vidéos',
  'call.camera.peerOff': 'Caméra désactivée',
  'call.video.connecting': 'Connexion vidéo…',
  'call.hangup': 'Raccrocher',
  'call.minimize': 'Réduire l’appel',
  'call.expand': 'Revenir à l’appel',
  'call.captions.on': 'Afficher les sous-titres',
  'call.captions.off': 'Masquer les sous-titres',
  'call.quality.poor': 'Connexion instable',
  'call.ended.local': 'Appel terminé',
  'call.ended.remote': 'Appel terminé',
  'call.ended.rejected': 'Appel refusé',
  'call.ended.missed': 'Pas de réponse',
  'call.ended.busy': 'Correspondant occupé',
  'call.ended.connectionLost': 'Connexion perdue',
  'call.ended.failed': 'Échec de l’appel',
  'call.ended.permission': 'Autorisez le micro pour appeler',
  'call.retry': 'Réessayer',
  'call.close': 'Fermer',
  'call.waiting.from': '{caller} vous appelle',
  'call.waiting.answer': 'Répondre',
  'call.waiting.decline': 'Refuser',
  'call.notice.alreadyInCall': 'Un appel est déjà en cours',
  'call.members': '{count} participants',
  'call.a11y.screen': 'Appel avec {name}',
  'call.bubble.callBack': 'Rappeler',
  'call.bubble.join': 'Rejoindre',
  'call.callBack.named': 'Rappeler {name}',
  'call.you': 'Vous',
  'call.ended.removed': 'Vous avez été retiré de l’appel',
  'call.spotlight.show': 'Mettre {name} en avant',
  'call.spotlight.back': 'Revenir à la grille',
  'call.remove.named': 'Retirer {name} de l’appel',
  'call.remove.failed': 'Impossible de retirer ce participant',
} as const;

export default frCall;
