/**
 * LES SESSIONS ET LA FIN D'UNE SESSION, FRANÇAIS (#6720, #9613) — la SOURCE
 * des clés de l'écran Sécurité > Sessions (`routes/settings-security.tsx`) et
 * de l'explication d'une session fermée (`components/session-end-notice.tsx`).
 * Les six autres langues portent exactement ces clés (`satisfies
 * SessionsCatalog`, `i18n-sessions-catalog.test.ts`).
 */
const fr = {
  'sessions.title': 'Sécurité',
  'sessions.back': 'Retour',
  'sessions.section': 'Sessions',
  'sessions.intro': 'Les appareils connectés à votre compte. Fermez toute session que vous ne reconnaissez pas.',
  'sessions.current': 'Cet appareil',
  'sessions.trusted': 'Appareil de confiance',
  'sessions.unknownDevice': 'Appareil inconnu',
  'sessions.field.app': 'Meeshy',
  'sessions.field.platform': 'Plateforme',
  'sessions.field.device': 'Appareil',
  'sessions.field.system': 'Système',
  'sessions.field.browser': 'Navigateur',
  'sessions.field.ip': 'Adresse IP',
  'sessions.field.place': 'Lieu',
  'sessions.field.timezone': 'Fuseau horaire',
  'sessions.field.opened': 'Ouverte le',
  'sessions.field.lastActive': 'Dernière activité',
  'sessions.field.method': 'Connexion',
  'sessions.version': 'Version {version}',
  'sessions.versionBuild': 'Version {version} ({build})',
  'sessions.place.approximate': '{place} · approximatif',
  'sessions.platform.web': 'Navigateur web',
  'sessions.platform.pwa': 'Application web installée',
  'sessions.platform.android-shell': 'Application Android',
  'sessions.platform.ios': 'Application iOS',
  'sessions.method.password': 'Mot de passe',
  'sessions.method.two_factor': 'Mot de passe et code de vérification',
  'sessions.method.magic_link': 'Lien de connexion par e-mail',
  'sessions.method.registration': 'Inscription',
  'sessions.method.email_verification': 'Vérification de l’e-mail',
  'sessions.method.oauth': 'Compte externe',
  'sessions.method.anonymous': 'Accès sans compte',
  'sessions.revoke': 'Fermer cette session',
  'sessions.revoke.label': 'Fermer la session {device}',
  'sessions.revoke.title': 'Fermer cette session ?',
  'sessions.revoke.body': '{device} sera déconnecté et devra se reconnecter.',
  'sessions.revoke.done': 'Session fermée',
  'sessions.revoke.error': 'La session n’a pas pu être fermée. Réessayez.',
  'sessions.others': 'Déconnecter les autres appareils',
  'sessions.others.title': 'Déconnecter les autres appareils ?',
  'sessions.others.body': 'Toutes les sessions sauf celle-ci seront fermées.',
  'sessions.others.done.one': 'Une session fermée',
  'sessions.others.done.other': '{count} sessions fermées',
  'sessions.others.none': 'Aucun autre appareil n’est connecté.',
  'sessions.others.error': 'Les autres sessions n’ont pas pu être fermées. Réessayez.',
  'sessions.cancel': 'Annuler',
  'sessions.empty.title': 'Aucune session active',
  'sessions.empty.body': 'Vos appareils connectés apparaîtront ici.',
  'sessions.loading': 'Chargement des sessions…',
  'sessions.error.title': 'Les sessions n’ont pas pu être chargées.',
  'sessions.error.retry': 'Réessayer',
  'sessions.offline': 'Hors ligne : la liste peut ne plus être à jour, et aucune session ne peut être fermée.',
  'sessions.signedOut': 'Votre session a expiré. Reconnectez-vous pour voir vos appareils.',
  'sessions.attribution.note': 'Lieux approximatifs, déduits de l’adresse IP.',
  'sessionEnd.title': 'Session fermée',
  'sessionEnd.admin_revoke': 'Votre session a été fermée par l’équipe Meeshy.',
  'sessionEnd.admin_revoke.help': 'Si vous pensez qu’il s’agit d’une erreur, contactez-nous.',
  'sessionEnd.user_revoke': 'Cette session a été fermée depuis un autre de vos appareils.',
  'sessionEnd.password_changed': 'Le mot de passe de votre compte a changé. Reconnectez-vous avec le nouveau.',
  'sessionEnd.logout': 'Vous avez été déconnecté de cet appareil.',
  'sessionEnd.logout_all_devices': 'Toutes les sessions de votre compte ont été fermées.',
  'sessionEnd.session_expired': 'Votre session a expiré. Reconnectez-vous.',
  'sessionEnd.contact': 'Contacter l’équipe',
  'sessionEnd.ok': 'Compris',
} as const;

export default fr;
