import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const itComposerAttach = {
  'composer.attach.group': 'Tipi di allegato',
  'composer.attach.handle': 'Maniglia del pannello',
  'composer.attach.photo': 'Foto',
  'composer.attach.photo.action': 'Scegli foto',
  'composer.attach.camera': 'Fotocamera',
  'composer.attach.camera.action': 'Scatta una foto',
  'composer.attach.file': 'File',
  'composer.attach.file.action': 'Scegli un file',
  'composer.attach.contact': 'Contatto',
  'composer.attach.contact.action': 'Condividi un contatto',
  'composer.contact.failed': 'Questo contatto non può essere condiviso',
  'composer.attach.location': 'Posizione',
  'composer.attach.location.action': 'Condividi la mia posizione',
  'composer.attach.voice': 'Voce',
  'composer.attach.voice.action': 'Registra un messaggio vocale',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Inserisci un emoji',
  'composer.emoji.title': 'Inserisci un emoji',
  'composer.location.locating': 'Ricerca della tua posizione…',
  'composer.location.denied': 'Posizione negata — consentila nelle impostazioni',
  'composer.location.unavailable': 'Posizione non disponibile su questo browser',
  'composer.location.failed': 'Posizione non trovata — riprova',
  'composer.mic.refused': 'Microfono negato — consentilo nelle impostazioni',
  'composer.mic.unavailable': 'Microfono non disponibile su questo dispositivo',
  'composer.openSettings': 'Impostazioni',
  'composer.location.chip': 'LUOGO',
  'composer.location.unknown': 'Luogo sconosciuto',
  'composer.location.remove': 'Rimuovi la posizione',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Invia uno sticker',
  'composer.sticker.title': 'I miei sticker',
  'composer.sticker.fromImage': 'Da un’immagine',
  'composer.sticker.paste': 'Incolla',
  'composer.sticker.pasteHint': 'Incolla o trascina qui un’immagine per farne uno sticker',
  'composer.sticker.nothingToPaste': 'Nessuna immagine negli appunti',
  'composer.sticker.empty': 'Ancora nessuno sticker — creane uno da un’immagine o incollane uno',
  'composer.sticker.creating': 'Creazione dello sticker…',
  'composer.sticker.manage': 'Gestisci',
  'composer.sticker.done': 'Fine',
  'composer.sticker.remove': 'Rimuovi questo sticker',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'Impossibile caricare questo sticker — riprova',
  'composer.sticker.error.notImage': 'Questo file non è un’immagine',
  'composer.sticker.error.tooLarge': 'Immagine troppo pesante per uno sticker',
  'composer.sticker.error.full': 'Libreria piena — rimuovi uno sticker per aggiungerne un altro',
  'composer.sticker.error.failed': 'Impossibile creare lo sticker',
  'composer.sticker.tabs': 'Famiglie di sticker',
  'composer.sticker.tab.instants': 'Istanti',
  'composer.sticker.mee.solo': 'Mee da sola',
  'composer.sticker.mee.duo': 'In due — Mee fa il gesto',
  'composer.sticker.meo.solo': 'Meo da solo',
  'composer.sticker.meo.duo': 'In due — Meo fa il gesto',
  'composer.sticker.instants.hint': 'Ciò che scrivi appare sullo sticker',
  'composer.sticker.instants.message': 'Messaggi',
  'composer.sticker.instants.moment': 'Momenti',
  'composer.sticker.instants.lieu': 'Luoghi',
  'composer.sticker.instants.meteo': 'Meteo',
  'composer.sticker.instants.field.message': 'Messaggio',
  'composer.sticker.instants.field.place': 'Luogo',
  'composer.sticker.instants.field.weather': 'Meteo',
  'composer.sticker.instants.field.time': 'Ora',
  'composer.quickEmoji.label': 'Invia direttamente',
  'composer.quickEmoji.group': 'Emoji rapide',
  'composer.effects.panel': 'Effetti del messaggio',
  'composer.effects.entrance': 'Animazione di ingresso',
  'composer.effects.permanent': 'Effetto permanente',
  'composer.effects.clearAll': 'Cancella tutto',
} satisfies ComposerAttachCatalogSlice;

export default itComposerAttach;
