import type { SessionsCatalog } from '@/lib/i18n-sessions-catalog';

const ar = {
  'sessions.title': 'الأمان',
  'sessions.back': 'رجوع',
  'sessions.section': 'الجلسات',
  'sessions.intro': 'الأجهزة المتصلة بحسابك. أغلق أي جلسة لا تتعرف عليها.',
  'sessions.current': 'هذا الجهاز',
  'sessions.trusted': 'جهاز موثوق',
  'sessions.unknownDevice': 'جهاز غير معروف',
  'sessions.field.app': 'Meeshy',
  'sessions.field.platform': 'المنصة',
  'sessions.field.device': 'الجهاز',
  'sessions.field.system': 'النظام',
  'sessions.field.browser': 'المتصفح',
  'sessions.field.ip': 'عنوان IP',
  'sessions.field.place': 'الموقع',
  'sessions.field.timezone': 'المنطقة الزمنية',
  'sessions.field.opened': 'فُتحت في',
  'sessions.field.lastActive': 'آخر نشاط',
  'sessions.field.method': 'تسجيل الدخول',
  'sessions.version': 'الإصدار {version}',
  'sessions.versionBuild': 'الإصدار {version} ({build})',
  'sessions.place.approximate': '{place} · تقريبي',
  'sessions.platform.web': 'متصفح الويب',
  'sessions.platform.pwa': 'تطبيق ويب مثبّت',
  'sessions.platform.android-shell': 'تطبيق Android',
  'sessions.platform.ios': 'تطبيق iOS',
  'sessions.method.password': 'كلمة المرور',
  'sessions.method.two_factor': 'كلمة المرور ورمز التحقق',
  'sessions.method.magic_link': 'رابط الدخول عبر البريد الإلكتروني',
  'sessions.method.registration': 'التسجيل',
  'sessions.method.email_verification': 'التحقق من البريد الإلكتروني',
  'sessions.method.oauth': 'حساب خارجي',
  'sessions.method.anonymous': 'دخول بدون حساب',
  'sessions.revoke': 'إغلاق هذه الجلسة',
  'sessions.revoke.label': 'إغلاق الجلسة على {device}',
  'sessions.revoke.title': 'إغلاق هذه الجلسة؟',
  'sessions.revoke.body': 'سيتم تسجيل خروج {device} وسيتعيّن تسجيل الدخول مجددًا.',
  'sessions.revoke.done': 'أُغلقت الجلسة',
  'sessions.revoke.error': 'تعذّر إغلاق الجلسة. حاول مرة أخرى.',
  'sessions.others': 'تسجيل الخروج من الأجهزة الأخرى',
  'sessions.others.title': 'تسجيل الخروج من الأجهزة الأخرى؟',
  'sessions.others.body': 'ستُغلق جميع الجلسات ما عدا هذه الجلسة.',
  'sessions.others.done.one': 'أُغلقت جلسة واحدة',
  'sessions.others.done.other': 'أُغلقت {count} جلسات',
  'sessions.others.none': 'لا يوجد جهاز آخر متصل.',
  'sessions.others.error': 'تعذّر إغلاق الجلسات الأخرى. حاول مرة أخرى.',
  'sessions.cancel': 'إلغاء',
  'sessions.empty.title': 'لا توجد جلسة نشطة',
  'sessions.empty.body': 'ستظهر هنا أجهزتك المتصلة.',
  'sessions.loading': 'جارٍ تحميل الجلسات…',
  'sessions.error.title': 'تعذّر تحميل الجلسات.',
  'sessions.error.retry': 'إعادة المحاولة',
  'sessions.offline': 'غير متصل: قد لا تكون القائمة محدّثة، ولا يمكن إغلاق أي جلسة.',
  'sessions.signedOut': 'انتهت صلاحية جلستك. سجّل الدخول مجددًا لرؤية أجهزتك.',
  'sessions.attribution.note': 'مواقع تقريبية مستنتجة من عنوان IP.',
  'sessionEnd.title': 'أُغلقت الجلسة',
  'sessionEnd.admin_revoke': 'أغلق فريق Meeshy جلستك.',
  'sessionEnd.admin_revoke.help': 'إذا كنت تعتقد أن هذا خطأ، فتواصل معنا.',
  'sessionEnd.user_revoke': 'أُغلقت هذه الجلسة من جهاز آخر من أجهزتك.',
  'sessionEnd.password_changed': 'تغيّرت كلمة مرور حسابك. سجّل الدخول بكلمة المرور الجديدة.',
  'sessionEnd.logout': 'تم تسجيل خروجك من هذا الجهاز.',
  'sessionEnd.logout_all_devices': 'أُغلقت جميع جلسات حسابك.',
  'sessionEnd.session_expired': 'انتهت صلاحية جلستك. سجّل الدخول مجددًا.',
  'sessionEnd.contact': 'التواصل مع الفريق',
  'sessionEnd.ok': 'حسنًا',
} satisfies SessionsCatalog;

export default ar;
