import type { GameRulesCatalog } from '@/lib/i18n-game-catalog';

/** LE CARNET DES RÈGLES ET SON ATLAS (#9542) — `game.rules.*`. Chargé avec la seule page « Comment ça marche ». Mêmes clés et mêmes paramètres que le français. */
const en = {
  'game.rules.1.title': 'Every action pays',
  'game.rules.1.body': 'Writing, talking, publishing, reacting, inviting: every useful action earns points. A post earns according to who can see it: public, community or friends. Limits count your actions, never your points: bonuses, the Flame and events raise what each action earns.',
  'game.rules.2.title': 'Points make the level',
  'game.rules.2.body': 'Levels keep climbing: up to 499 below Ambassador, up to 1000 from Ambassador, with no limit from Oracle. Twenty tiers, and each level asks for a little more than the one before. Prestige opens at level 100 but never forces you: you can keep climbing. Beyond 100, every ten levels crossed for the first time earn 1,000 Glory.',
  'game.rules.3.title': 'We mint Meeshes',
  'game.rules.3.body': 'From 1,221 points, you mint a Meesh by hand. The price rises with the number of Meeshes already minted.',
  'game.rules.4.title': 'Minting brings you down',
  'game.rules.4.body': 'Spent points leave the level. The badges they held may go out.',
  'game.rules.5.title': 'Your rank never drops',
  'game.rules.5.body': 'Every mint, every record, every achievement adds Glory. Glory gives the rank.',
  'game.rules.6.title': 'The treasury is kept or spent',
  'game.rules.6.body': 'Keeping your Meeshes grows the treasury. Spending them protects the Flame or buys cosmetics.',
  'game.rules.7.title': 'Every day counts',
  'game.rules.7.body': 'Three missions, a chest, a Flame that grows as long as you come back.',
  'game.rules.8.title': 'We keep a trace',
  'game.rules.8.body': 'Every big moment is photographed with Mee and Meo in the progress notebook.',
  'game.rules.page_title': 'How it works',
  'game.rules.intro': 'Eight rules, and the whole game fits inside. Meo explains them, Mee shows you the move.',
  'game.rules.section_rules': 'The rules on one page',
  'game.rules.section_steps': 'The seven steps',
  'game.rules.atlas.title': 'The game in pictures',
  'game.rules.atlas.meesh': 'The Meesh',
  'game.rules.atlas.medals': 'Medals',
  'game.rules.atlas.trophies': 'Trophies',
  'game.rules.atlas.rarities': 'Rarities',
  'game.rules.atlas.obverse': 'Obverse',
  'game.rules.atlas.reverse': 'Reverse',
  'game.rules.atlas.line.levels': 'Twenty tiers: ten for the first hundred levels, nine of a hundred levels each after that, then Singularity from 1000. Each tier has its own emblem and colour.',
  'game.rules.atlas.line.meesh': 'The obverse bears the Signature; the reverse, Mee and Meo, the number and the year. Gold every hundredth, prism every thousandth.',
  'game.rules.atlas.line.treasury': 'Keeping your Meeshes fills the treasury: six tiers to climb.',
  'game.rules.atlas.line.rank': 'Eleven ranks. Glory earns them, and a rank never goes down.',
  'game.rules.atlas.line.flame': 'The Flame grows as long as you come back: five forms.',
  'game.rules.atlas.line.league': 'Eight gems, one per league. Every week you compete with 29 other players.',
  'game.rules.atlas.line.medals': 'Seven metals, from copper to prism: the metal shows how far you got. A badge that goes out leaves an imprint.',
  'game.rules.atlas.line.trophies': 'A trophy is received at one precise moment: league cup, season cup, Prestige, Flame.',
  'game.rules.atlas.line.rarities': 'Five rarities, measured every night. None of them earns points.',
  'game.rules.atlas.levels': 'The twenty tiers',
  'game.rules.atlas.treasury': 'The treasury tiers',
  'game.rules.atlas.ranks': 'The rank crests',
  'game.rules.atlas.flames': 'The five Flames',
  'game.rules.atlas.leagues': 'The eight leagues',
  'game.rules.atlas.edition_gold': 'Gold edition · every hundredth',
  'game.rules.atlas.edition_prism': 'Prism edition · every thousandth',
  'game.rules.atlas.shape_accumulation': 'Accumulation',
  'game.rules.atlas.shape_record': 'Record',
  'game.rules.atlas.shape_collection': 'Collection',
  'game.rules.atlas.imprint': 'Imprint',
  'game.rules.atlas.trophy_league': 'League cup',
  'game.rules.atlas.trophy_season': 'Season cup',
  'game.rules.atlas.trophy_prestige': 'Prestige trophy',
  'game.rules.atlas.trophy_flame': 'Flame trophy',
  'game.rules.atlas.share_common': 'over 40% of accounts',
  'game.rules.atlas.share_rare': '10 to 40% of accounts',
  'game.rules.atlas.share_epic': '2 to 10% of accounts',
  'game.rules.atlas.share_legendary': '0.2 to 2% of accounts',
  'game.rules.atlas.share_mythic': 'under 0.2% of accounts',
  'game.rules.atlas.rarity_glory': '+{glory} Glory',
  'game.rules.atlas.myth': 'The first 100 to reach 1,000,000 Glory',
  'game.rules.badges.title': 'Badges',
  'game.rules.badges.intro': 'Each badge counts ONE specific move: a voice message, a story, a new friendship… There are twenty, grouped into five families.',
  'game.rules.badges.ladder': 'Each badge climbs seven tiers. Every time you pass a mark, it changes material and lights one more star.',
  'game.rules.badges.ribbon': 'From Gold on, the medal wears a ribbon; at Prism, its enamel turns iridescent.',
  'game.rules.badges.imprint': 'Minting a Meesh can put a badge out: it becomes an imprint showing what is missing to light it again.',
  'game.rules.badges.families': 'The twenty badges, by family',
  'game.rules.badges.sheet': 'Tap a badge: its card says what counts for it, its material and why, and what is missing for the next star.',
} as const satisfies GameRulesCatalog;

export default en;
