import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const deComposerAttach = {
  'composer.attach.group': 'Anhangstypen',
  'composer.attach.handle': 'Bedienleiste',
  'composer.attach.photo': 'Fotos',
  'composer.attach.photo.action': 'Fotos auswählen',
  'composer.attach.camera': 'Kamera',
  'composer.attach.camera.action': 'Foto aufnehmen',
  'composer.attach.file': 'Datei',
  'composer.attach.file.action': 'Datei auswählen',
  'composer.attach.location': 'Standort',
  'composer.attach.location.action': 'Meinen Standort teilen',
  'composer.attach.voice': 'Sprache',
  'composer.attach.voice.action': 'Sprachnachricht aufnehmen',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Emoji einfügen',
  'composer.emoji.title': 'Emoji einfügen',
  'composer.location.locating': 'Standort wird gesucht…',
  'composer.location.denied': 'Standort verweigert — in den Einstellungen erlauben',
  'composer.location.unavailable': 'Standort in diesem Browser nicht verfügbar',
  'composer.location.failed': 'Standort nicht gefunden — erneut versuchen',
  'composer.location.chip': 'ORT',
  'composer.location.unknown': 'Unbekannter Ort',
  'composer.location.remove': 'Standort entfernen',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Sticker senden',
  'composer.sticker.title': 'Meine Sticker',
  'composer.sticker.fromImage': 'Aus einem Bild',
  'composer.sticker.paste': 'Einfügen',
  'composer.sticker.pasteHint': 'Füge hier ein Bild ein oder lege es ab, um einen Sticker daraus zu machen',
  'composer.sticker.nothingToPaste': 'Kein Bild in der Zwischenablage',
  'composer.sticker.empty': 'Noch keine Sticker — erstelle einen aus einem Bild oder füge eines ein',
  'composer.sticker.creating': 'Sticker wird erstellt…',
  'composer.sticker.manage': 'Verwalten',
  'composer.sticker.done': 'Fertig',
  'composer.sticker.remove': 'Diesen Sticker entfernen',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'Dieser Sticker konnte nicht geladen werden — versuche es erneut',
  'composer.sticker.error.notImage': 'Diese Datei ist kein Bild',
  'composer.sticker.error.tooLarge': 'Bild zu groß für einen Sticker',
  'composer.sticker.error.full': 'Bibliothek voll — entferne einen Sticker, um einen neuen hinzuzufügen',
  'composer.sticker.error.failed': 'Der Sticker konnte nicht erstellt werden',
  'composer.quickEmoji.label': 'Direkt senden',
  'composer.quickEmoji.group': 'Schnell-Emojis',
  'composer.effects.panel': 'Nachrichteneffekte',
  'composer.effects.entrance': 'Eingangsanimation',
  'composer.effects.permanent': 'Dauerhafter Effekt',
  'composer.effects.clearAll': 'Alles löschen',
} satisfies ComposerAttachCatalogSlice;

export default deComposerAttach;
