import type { GameBannerCatalog } from '@/lib/i18n-game-catalog';

/** LE BANDEAU DU JOUEUR (#9542) — les seules clés que le bandeau des hubs lit (`player-banner.tsx`, `lib/view/player-banner.ts`) : ses phrases, les noms de palier, de rang et de ligue, les accords de points, de jours et de Meeshes. Chargé SEUL par le bandeau, et avec chaque écran du jeu. Mêmes clés et mêmes paramètres que le français. */
const de = {
  'game.points.one': '{count} Punkt',
  'game.points.other': '{count} Punkte',
  'game.days.one': '{count} Tag',
  'game.days.other': '{count} Tage',
  'game.meeshes.none': 'Keine Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meeshes',
  'game.tier.etincelle': 'Funke',
  'game.tier.lueur': 'Schimmer',
  'game.tier.lumiere': 'Licht',
  'game.tier.eclat': 'Glanz',
  'game.tier.rayon': 'Strahl',
  'game.tier.aurore': 'Morgenrot',
  'game.tier.comete': 'Komet',
  'game.tier.etoile': 'Stern',
  'game.tier.constellation': 'Sternbild',
  'game.tier.galaxie': 'Galaxie',
  'game.rank.murmure': 'Flüstern',
  'game.rank.echo': 'Echo',
  'game.rank.voix': 'Stimme',
  'game.rank.conteur': 'Erzähler',
  'game.rank.passeur': 'Brückenbauer',
  'game.rank.polyglotte': 'Polyglott',
  'game.rank.ambassadeur': 'Botschafter',
  'game.rank.orateur': 'Redner',
  'game.rank.oracle': 'Orakel',
  'game.rank.legende': 'Legende',
  'game.rank.mythe': 'Mythos',
  'game.rank.mythe_seat': 'Mythos Nr. {number}',
  'game.banner.level': 'Level {level}',
  'game.banner.to_next': '{percent} % bis Level {level}',
  'game.banner.top': 'ganz oben',
  'game.banner.league': 'Liga {league} {place}',
  'game.banner.flame': 'Flamme {days}',
  'game.banner.place.one': '{count}.',
  'game.banner.place.other': '{count}.',
  'game.banner.points': '{points} P.',
  'game.banner.missing': 'noch {points}',
  'game.banner.separator': ', ',
  'game.league.name.quartz': 'Quarz',
  'game.league.name.ambre': 'Bernstein',
  'game.league.name.jade': 'Jade',
  'game.league.name.saphir': 'Saphir',
  'game.league.name.rubis': 'Rubin',
  'game.league.name.amethyste': 'Amethyst',
  'game.league.name.diamant': 'Diamant',
  'game.league.name.prisme': 'Prisma',
} as const satisfies GameBannerCatalog;

export default de;
