/**
 * L'APPEL AUDIO ET VIDÉO (#6382) — tranche du catalogue `catalog-de.ts`,
 * extraite pour tenir le budget de taille (CLAUDE.md) : le catalogue la
 * RÉPAND. Libellés repris d'iOS (`CallView.swift`, `IncomingCallView.swift`).
 */
const deCall = {
  'call.action.menu': 'Anrufen',
  'call.action.audio': 'Sprachanruf',
  'call.action.video': 'Videoanruf',
  'call.action.return': 'Zurück zum Anruf',
  'call.incoming.title.audio': 'Eingehender Anruf',
  'call.incoming.title.video': 'Eingehender Videoanruf',
  'call.incoming.title.tab': '📞 Eingehender Anruf',
  'call.incoming.group': '{caller} ruft die Gruppe an',
  'call.accept': 'Annehmen',
  'call.accept.audioOnly': 'Ohne Video annehmen',
  'call.decline': 'Ablehnen',
  'call.outgoing.ringing': 'Anruf läuft…',
  'call.outgoing.waiting': 'Warten auf die andere Person…',
  'call.connecting': 'Verbinden…',
  'call.reconnecting': 'Neu verbinden…',
  'call.mic.mute': 'Mikrofon stummschalten',
  'call.mic.unmute': 'Mikrofon einschalten',
  'call.mic.muted': 'Mikrofon aus',
  'call.peer.muted': 'Kontakt stumm',
  'call.camera.on': 'Kamera einschalten',
  'call.camera.off': 'Kamera ausschalten',
  'call.camera.switch': 'Kamera wechseln',
  'call.camera.peerOff': 'Kamera aus',
  'call.video.connecting': 'Video wird verbunden…',
  'call.hangup': 'Auflegen',
  'call.minimize': 'Anruf minimieren',
  'call.expand': 'Zurück zum Anruf',
  'call.captions.on': 'Untertitel anzeigen',
  'call.captions.off': 'Untertitel ausblenden',
  'call.quality.poor': 'Instabile Verbindung',
  'call.ended.local': 'Anruf beendet',
  'call.ended.remote': 'Anruf beendet',
  'call.ended.rejected': 'Anruf abgelehnt',
  'call.ended.missed': 'Keine Antwort',
  'call.ended.busy': 'Besetzt',
  'call.ended.connectionLost': 'Verbindung verloren',
  'call.ended.failed': 'Anruf fehlgeschlagen',
  'call.ended.permission': 'Erlaube das Mikrofon, um anzurufen',
  'call.retry': 'Erneut versuchen',
  'call.close': 'Schließen',
  'call.waiting.from': '{caller} ruft dich an',
  'call.waiting.answer': 'Annehmen',
  'call.waiting.decline': 'Ablehnen',
  'call.notice.alreadyInCall': 'Es läuft bereits ein Anruf',
  'call.members': '{count} Teilnehmende',
  'call.a11y.screen': 'Anruf mit {name}',
  'call.bubble.callBack': 'Zurückrufen',
  'call.bubble.join': 'Beitreten',
  'call.callBack.named': '{name} zurückrufen',
  'call.you': 'Du',
} as const;

export default deCall;
