import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const arComposerAttach = {
  'composer.attach.group': 'أنواع المرفقات',
  'composer.attach.handle': 'مقبض اللوحة',
  'composer.attach.photo': 'الصور',
  'composer.attach.photo.action': 'اختيار صور',
  'composer.attach.camera': 'الكاميرا',
  'composer.attach.camera.action': 'التقاط صورة',
  'composer.attach.file': 'ملف',
  'composer.attach.file.action': 'اختيار ملف',
  'composer.attach.contact': 'جهة اتصال',
  'composer.attach.contact.action': 'مشاركة جهة اتصال',
  'composer.contact.failed': 'لا يمكن مشاركة جهة الاتصال هذه',
  'composer.attach.location': 'الموقع',
  'composer.attach.location.action': 'مشاركة موقعي',
  'composer.attach.voice': 'صوت',
  'composer.attach.voice.action': 'تسجيل رسالة صوتية',
  'composer.attach.emoji': 'الرموز التعبيرية',
  'composer.attach.emoji.action': 'إدراج رمز تعبيري',
  'composer.emoji.title': 'إدراج رمز تعبيري',
  'composer.location.locating': 'جارٍ تحديد موقعك…',
  'composer.location.denied': 'تم رفض الموقع — اسمح به من الإعدادات',
  'composer.location.unavailable': 'الموقع غير متاح في هذا المتصفح',
  'composer.location.failed': 'تعذّر تحديد الموقع — أعد المحاولة',
  'composer.mic.refused': 'تم رفض الميكروفون — اسمح به من الإعدادات',
  'composer.mic.unavailable': 'الميكروفون غير متاح على هذا الجهاز',
  'composer.openSettings': 'الإعدادات',
  'composer.location.chip': 'موقع',
  'composer.location.unknown': 'مكان غير معروف',
  'composer.location.remove': 'إزالة الموقع',
  'composer.attach.sticker': 'ملصق',
  'composer.attach.sticker.action': 'إرسال ملصق',
  'composer.sticker.title': 'ملصقاتي',
  'composer.sticker.fromImage': 'من صورة',
  'composer.sticker.paste': 'لصق',
  'composer.sticker.pasteHint': 'الصق صورة أو أفلتها هنا لتحويلها إلى ملصق',
  'composer.sticker.nothingToPaste': 'لا توجد صورة في الحافظة',
  'composer.sticker.empty': 'لا توجد ملصقات بعد — أنشئ واحدًا من صورة أو الصق واحدًا',
  'composer.sticker.creating': 'جارٍ إنشاء الملصق…',
  'composer.sticker.manage': 'إدارة',
  'composer.sticker.done': 'تم',
  'composer.sticker.remove': 'إزالة هذا الملصق',
  'composer.sticker.item': 'ملصق',
  'composer.sticker.unavailable': 'تعذّر تحميل هذا الملصق — أعد المحاولة',
  'composer.sticker.error.notImage': 'هذا الملف ليس صورة',
  'composer.sticker.error.tooLarge': 'الصورة كبيرة جدًا لملصق',
  'composer.sticker.error.full': 'المكتبة ممتلئة — أزل ملصقًا لإضافة آخر',
  'composer.sticker.error.failed': 'تعذّر إنشاء الملصق',
  'composer.sticker.tabs': 'مجموعات الملصقات',
  'composer.sticker.tab.instants': 'لحظات',
  'composer.sticker.tab.custom': 'مخصّص',
  'composer.sticker.intent.bonjour.title': 'مرحبًا، شكرًا',
  'composer.sticker.intent.bonjour.hint': 'للتحية والشكر والموافقة والاعتذار أو لتمنّي ليلة سعيدة',
  'composer.sticker.intent.amour.title': 'قل أحبك',
  'composer.sticker.intent.amour.hint': 'لكلمة لطيفة أو قبلة أو عناق أو اعتراف بالحب',
  'composer.sticker.intent.fete.title': 'اضحك واحتفل',
  'composer.sticker.intent.fete.hint': 'لخبر سار أو نجاح أو عيد ميلاد أو نوبة ضحك',
  'composer.sticker.intent.soutien.title': 'واسِ وادعم',
  'composer.sticker.intent.soutien.hint': 'للتشجيع أو المواساة أو لتقول «أنا هنا»',
  'composer.sticker.intent.rale.title': 'تذمّر وزعل',
  'composer.sticker.intent.rale.hint': 'للتعبير عن الضيق أو الغضب أو الغيرة أو للابتعاد قليلًا',
  'composer.sticker.intent.coup-de-mou.title': 'إحباط وتعب',
  'composer.sticker.intent.coup-de-mou.hint': 'للحزن أو الأسى أو التعب أو الرغبة في النوم',
  'composer.sticker.intent.surprise.title': 'مفاجأة وقشعريرة',
  'composer.sticker.intent.surprise.hint': 'للدهشة أو الخوف أو الإحراج أو «أوبس»',
  'composer.sticker.intent.quotidien.title': 'الحياة اليومية',
  'composer.sticker.intent.quotidien.hint': 'لتقول ما تفعله: قهوة، وجبة، عمل، طريق، تأخير',
  'composer.sticker.intent.humour-noir.title': 'كوميديا سوداء',
  'composer.sticker.intent.humour-noir.hint': 'للضحك على كل شيء حتى الأسوأ: الموت من الضحك والأشباح وشواهد القبور',
  'composer.sticker.instants.hint': 'ما تكتبه يظهر على الملصق',
  'composer.sticker.instants.message': 'رسائل',
  'composer.sticker.instants.moment': 'أوقات اليوم',
  'composer.sticker.instants.lieu': 'أماكن',
  'composer.sticker.instants.meteo': 'الطقس',
  'composer.sticker.instants.field.message': 'رسالة',
  'composer.sticker.instants.field.place': 'المكان',
  'composer.sticker.instants.field.weather': 'الطقس',
  'composer.sticker.instants.field.time': 'الساعة',
  'composer.quickEmoji.label': 'إرسال مباشرة',
  'composer.quickEmoji.group': 'رموز تعبيرية سريعة',
  'composer.effects.panel': 'تأثيرات الرسالة',
  'composer.effects.entrance': 'حركة الدخول',
  'composer.effects.permanent': 'تأثير دائم',
  'composer.effects.clearAll': 'مسح الكل',
} satisfies ComposerAttachCatalogSlice;

export default arComposerAttach;
