import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page, les fiches et le tableau de bord (`game.concept.*`, `game.fiche.*`, `game.fact.*`, `game.dashboard.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const it = {
  'game.progression.title': 'Progressi',
  'game.dashboard.title': 'Riepilogo',
  'game.dashboard.hint': 'Tutti i tuoi dati, concetto per concetto.',
  'game.concept.why_label': 'A cosa serve',
  'game.concept.how_label': 'Come funziona',
  'game.fiche.what': 'Che cos’è?',
  'game.fiche.where': 'A che punto sono',
  'game.fiche.earn': 'Come guadagnarne',
  'game.fiche.more': 'Per saperne di più',
  'game.fiche.unknown': 'Questa scheda non esiste, o il tuo server non la offre ancora.',
  'game.concept.level.name': 'Livello',
  'game.concept.level.why': 'Il tuo livello mostra la strada che hai fatto su Meeshy.',
  'game.concept.level.how': 'I tuoi punti riempiono l’anello: quando è pieno, sali di un livello.',
  'game.concept.level.tip.1': 'Fai le missioni del giorno: danno molti punti.',
  'game.concept.level.tip.2': 'Tieni accesa la tua Fiamma: aumenta le tue ricompense.',
  'game.concept.points.name': 'Punti',
  'game.concept.points.why': 'I punti fanno salire il tuo livello e servono a coniare le Meesh.',
  'game.concept.points.how': 'Ogni gesto utile ne dà: scrivere, parlare, pubblicare, reagire.',
  'game.concept.points.tip.1': 'Pubblica, commenta, reagisci: ogni famiglia di gesti ha il suo valore.',
  'game.concept.points.tip.2': 'Attiva uno slancio per moltiplicare i tuoi punti.',
  'game.concept.meesh.name': 'Meesh',
  'game.concept.meesh.why': 'La Meesh è la moneta rara di Meeshy: la tieni o la spendi.',
  'game.concept.meesh.how': 'La conii con i tuoi punti. Più se ne coniano, più costa la prossima.',
  'game.concept.meesh.tip.1': 'Tieni le tue Meesh per far crescere il tuo tesoro.',
  'game.concept.meesh.tip.2': 'Spendile per proteggere la tua Fiamma o cambiare una missione.',
  'game.concept.glory.name': 'Gloria',
  'game.concept.glory.why': 'La Gloria ti dà il rango, e il tuo rango non scende mai.',
  'game.concept.glory.how': 'Ogni conio, ogni record e ogni traguardo ne aggiunge.',
  'game.concept.glory.tip.1': 'Conia una Meesh: ogni conio aggiunge Gloria.',
  'game.concept.glory.tip.2': 'Batti i tuoi record e sblocca traguardi.',
  'game.concept.flame.name': 'Fiamma',
  'game.concept.flame.why': 'La tua Fiamma conta i giorni di fila e aumenta i premi delle missioni.',
  'game.concept.flame.how': 'Un gesto al giorno la fa crescere. Un congelamento copre un giorno.',
  'game.concept.flame.tip.1': 'Fai almeno un gesto ogni giorno.',
  'game.concept.flame.tip.2': 'Tieni un congelamento di riserva per i giorni di pausa.',
  'game.concept.missions.name': 'Missioni del giorno',
  'game.concept.missions.why': 'Le missioni ti danno un obiettivo ogni giorno, e punti in più.',
  'game.concept.missions.how': 'Tre missioni al giorno. Quando sono fatte, apri il forziere.',
  'game.concept.missions.tip.1': 'Comincia dalla missione più facile.',
  'game.concept.missions.tip.2': 'Una missione non ti piace? Cambiala, una volta al giorno.',
  'game.concept.league.name': 'Lega',
  'game.concept.league.why': 'La lega ti misura ogni settimana con altri 29 giocatori.',
  'game.concept.league.how': 'I punti della settimana fanno la tua posizione. I primi salgono di lega.',
  'game.concept.league.tip.1': 'Gioca un po’ ogni giorno: i punti della settimana si sommano.',
  'game.concept.league.tip.2': 'Punta ai primi posti prima di domenica sera.',
  'game.concept.league.more': 'Vedi la classifica',
  'game.concept.league.value': '{league} · posto {rank}',
  'game.concept.league.unplaced': 'Ancora senza gruppo',
  'game.concept.season.name': 'Stagione',
  'game.concept.season.why': 'La stagione è un percorso di otto settimane, con una coppa alla fine.',
  'game.concept.season.how': 'Le missioni e la coppia danno stelle. Le stelle aprono le tappe.',
  'game.concept.season.tip.1': 'Finisci le missioni del giorno per guadagnare stelle.',
  'game.concept.season.tip.2': 'Gioca in coppia con un amico: la ricompensa raddoppia.',
  'game.concept.season.more': 'Vedi il percorso',
  'game.concept.season.none': 'Nessuna ora',
  'game.concept.prestige.name': 'Prestigio',
  'game.concept.prestige.why': 'Il Prestigio premia chi raggiunge il livello 100.',
  'game.concept.prestige.how': 'Il tuo livello riparte da 1. Guadagni una stella, un trofeo e Gloria.',
  'game.concept.prestige.tip.1': 'Sali fino al livello 100.',
  'game.concept.prestige.tip.2': 'Passa al Prestigio quando vuoi: niente ti obbliga.',
  'game.concept.prestige.more': 'Apri il Prestigio',
  'game.concept.elans.name': 'Slanci',
  'game.concept.elans.why': 'Uno slancio moltiplica i punti dei tuoi prossimi gesti.',
  'game.concept.elans.how': 'Fai gesti di più famiglie in questi giorni per attivarlo.',
  'game.concept.elans.tip.1': 'Varia i tuoi gesti: scrivi, pubblica, commenta, reagisci.',
  'game.concept.elans.tip.2': 'Torna più giorni di fila per mantenerlo.',
  'game.concept.elans.families.one': '{count} famiglia attiva',
  'game.concept.elans.families.other': '{count} famiglie attive',
  'game.concept.badges.name': 'Badge',
  'game.concept.badges.why': 'Un badge mostra ciò che fai di più su Meeshy.',
  'game.concept.badges.how': 'Ripeti un gesto: il suo badge cambia materiale, dal rame al prisma.',
  'game.concept.badges.tip.1': 'Scegli un gesto che ti piace e ripetilo spesso.',
  'game.concept.badges.tip.2': 'Un badge spento si riaccende: niente è perduto.',
  'game.concept.badges.more': 'Vedi tutti i miei badge',
  'game.concept.defis.name': 'Sfide',
  'game.concept.defis.why': 'Le sfide sono gradini da superare, uno dopo l’altro.',
  'game.concept.defis.how': 'Ogni gradino raggiunto apre il successivo, un po’ più in alto.',
  'game.concept.defis.tip.1': 'Guarda il prossimo gradino e avanza verso di lui.',
  'game.concept.defis.tip.2': 'Prova gesti nuovi: ognuno ha le sue sfide.',
  'game.concept.defis.more': 'Vedi tutte le mie sfide',
  'game.concept.succes.name': 'Traguardi',
  'game.concept.succes.why': 'Un traguardo segna un momento raro della tua storia su Meeshy.',
  'game.concept.succes.how': 'Si sblocca in un colpo solo, quando riunisci ciò che chiede.',
  'game.concept.succes.tip.1': 'Esplora l’app: alcuni traguardi sono nascosti.',
  'game.concept.succes.tip.2': 'I più rari aggiungono più Gloria.',
  'game.concept.succes.more': 'Vedi tutti i miei traguardi',
  'game.concept.showcase.name': 'Vetrina',
  'game.concept.showcase.why': 'La tua vetrina espone i trofei che hai vinto.',
  'game.concept.showcase.how': 'Ogni coppa ci arriva da sola. Tu scegli l’ordine e chi la vede.',
  'game.concept.showcase.tip.1': 'Arriva in cima alla tua lega per vincere una coppa.',
  'game.concept.showcase.tip.2': 'Completa una stagione o passa al Prestigio.',
  'game.concept.showcase.more': 'Apri la mia vetrina',
  'game.concept.atlas.name': 'Atlante',
  'game.concept.atlas.why': 'L’Atlante conserva un timbro per ogni lingua in cui hai conversato.',
  'game.concept.atlas.how': 'Invia un messaggio e ricevine uno in una lingua: il timbro si posa.',
  'game.concept.atlas.tip.1': 'Scrivi a qualcuno in una lingua diversa dalla tua.',
  'game.concept.atlas.tip.2': 'Aspetta la risposta: serve un messaggio in ogni direzione.',
  'game.concept.atlas.more': 'Apri il mio Atlante',
  'game.concept.chip.next_price': 'Prossima: {price}',
  'game.concept.chip.next': 'Poi: {name}',
  'game.concept.chip.record': 'Record: {value}',
  'game.concept.chip.freezes': 'Congelamenti: {count}',
  'game.concept.chip.chest.locked': 'Forziere chiuso',
  'game.concept.chip.chest.ready': 'Forziere pronto',
  'game.concept.chip.chest.claimed': 'Forziere aperto',
  'game.concept.chip.can_mint': 'Puoi coniare',
  'game.concept.chip.left': 'Restano: {count}',
  'game.concept.chip.week': 'Settimana {week}',
  'game.concept.chip.no_elan': 'Nessuno slancio attivo',
  'game.concept.chip.factor': 'Punti ×{factor}',
  'game.concept.chip.seen_by': 'Vista da: {who}',
  'game.fact.tier': 'Fascia',
  'game.fact.to_next': 'Prossimo livello',
  'game.fact.record': 'Primato',
  'game.fact.next_meesh': 'Prossima Meesh',
  'game.fact.missing': 'Mancano',
  'game.fact.balance': 'In tasca',
  'game.fact.next_tier': 'Fascia successiva',
  'game.fact.minted': 'Coniate da sempre',
  'game.fact.next_rank': 'Rango successivo',
  'game.fact.streak': 'Serie',
  'game.fact.form': 'Forma',
  'game.fact.freezes': 'Congelamenti di riserva',
  'game.fact.state': 'Stato',
  'game.fact.lit': 'Accesa',
  'game.fact.done': 'Fatte',
  'game.fact.week_points': 'Punti della settimana',
  'game.fact.closes': 'Chiusura',
  'game.fact.steps': 'Tappe',
  'game.fact.stars': 'Stelle',
  'game.fact.week': 'Settimana',
  'game.fact.factor': 'Moltiplicatore',
  'game.fact.families': 'Famiglie attive',
  'game.fact.earned': 'Ottenuti',
  'game.fact.trophies': 'Trofei',
  'game.fact.visibility': 'Visibile a',
  'game.fact.stamps': 'Timbri',
  'game.fact.pending': 'In corso',
  'game.fact.group': 'Gruppo',
} as const satisfies GameConceptCatalog;

export default it;
