import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const esComposerAttach = {
  'composer.attach.group': 'Tipos de adjuntos',
  'composer.attach.handle': 'Tirador del panel',
  'composer.attach.photo': 'Fotos',
  'composer.attach.photo.action': 'Elegir fotos',
  'composer.attach.camera': 'Cámara',
  'composer.attach.camera.action': 'Hacer una foto',
  'composer.attach.file': 'Archivo',
  'composer.attach.file.action': 'Elegir un archivo',
  'composer.attach.contact': 'Contacto',
  'composer.attach.contact.action': 'Compartir un contacto',
  'composer.contact.failed': 'Este contacto no se puede compartir',
  'composer.attach.location': 'Ubicación',
  'composer.attach.location.action': 'Compartir mi ubicación',
  'composer.attach.voice': 'Voz',
  'composer.attach.voice.action': 'Grabar un mensaje de voz',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Insertar un emoji',
  'composer.emoji.title': 'Insertar un emoji',
  'composer.location.locating': 'Buscando tu ubicación…',
  'composer.location.denied': 'Ubicación denegada: permítela en los ajustes',
  'composer.location.unavailable': 'Ubicación no disponible en este navegador',
  'composer.location.failed': 'Ubicación no encontrada: inténtalo de nuevo',
  'composer.mic.refused': 'Micrófono denegado — permítelo en los ajustes',
  'composer.mic.unavailable': 'Micrófono no disponible en este dispositivo',
  'composer.openSettings': 'Ajustes',
  'composer.location.chip': 'LUGAR',
  'composer.location.unknown': 'Lugar desconocido',
  'composer.location.remove': 'Quitar la ubicación',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Enviar un sticker',
  'composer.sticker.title': 'Mis stickers',
  'composer.sticker.fromImage': 'Desde una imagen',
  'composer.sticker.paste': 'Pegar',
  'composer.sticker.pasteHint': 'Pega o suelta una imagen aquí para convertirla en sticker',
  'composer.sticker.nothingToPaste': 'No hay ninguna imagen en el portapapeles',
  'composer.sticker.empty': 'Aún no hay stickers — crea uno desde una imagen o pega uno',
  'composer.sticker.creating': 'Creando sticker…',
  'composer.sticker.manage': 'Gestionar',
  'composer.sticker.done': 'Listo',
  'composer.sticker.remove': 'Quitar este sticker',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'No se pudo cargar este sticker — inténtalo de nuevo',
  'composer.sticker.error.notImage': 'Este archivo no es una imagen',
  'composer.sticker.error.tooLarge': 'Imagen demasiado pesada para un sticker',
  'composer.sticker.error.full': 'Biblioteca llena — quita un sticker para añadir otro',
  'composer.sticker.error.failed': 'No se pudo crear el sticker',
  'composer.sticker.tabs': 'Familias de stickers',
  'composer.sticker.tab.instants': 'Instantes',
  'composer.sticker.intent.bonjour.title': 'Hola, gracias',
  'composer.sticker.intent.bonjour.hint': 'Para saludar, dar las gracias, decir que sí, disculparse o desear buenas noches',
  'composer.sticker.intent.amour.title': 'Decir te quiero',
  'composer.sticker.intent.amour.hint': 'Para una palabra dulce, un beso, un abrazo o una declaración',
  'composer.sticker.intent.fete.title': 'Reír y celebrar',
  'composer.sticker.intent.fete.hint': 'Para una buena noticia, un éxito, un cumpleaños o un ataque de risa',
  'composer.sticker.intent.soutien.title': 'Consolar y apoyar',
  'composer.sticker.intent.soutien.hint': 'Para animar, reconfortar o decir «estoy aquí»',
  'composer.sticker.intent.rale.title': 'Quejarse y enfadarse',
  'composer.sticker.intent.rale.hint': 'Para mostrar fastidio, enfado, celos o tomar distancia',
  'composer.sticker.intent.coup-de-mou.title': 'Bajón',
  'composer.sticker.intent.coup-de-mou.hint': 'Para la tristeza, la pena, el cansancio o las ganas de dormir',
  'composer.sticker.intent.surprise.title': 'Sorpresa y escalofríos',
  'composer.sticker.intent.surprise.hint': 'Para el asombro, el miedo, la vergüenza o un «ups»',
  'composer.sticker.intent.quotidien.title': 'El día a día',
  'composer.sticker.intent.quotidien.hint': 'Para contar lo que haces: un café, una comida, el trabajo, el camino, un retraso',
  'composer.sticker.intent.humour-noir.title': 'Humor negro',
  'composer.sticker.intent.humour-noir.hint': 'Para reírse de todo, incluso de lo peor: morirse de risa, fantasmas y lápidas',
  'composer.sticker.instants.hint': 'Lo que escribes aparece en el sticker',
  'composer.sticker.instants.message': 'Mensajes',
  'composer.sticker.instants.moment': 'Momentos',
  'composer.sticker.instants.lieu': 'Lugares',
  'composer.sticker.instants.meteo': 'Tiempo',
  'composer.sticker.instants.field.message': 'Mensaje',
  'composer.sticker.instants.field.place': 'Lugar',
  'composer.sticker.instants.field.weather': 'Tiempo',
  'composer.sticker.instants.field.time': 'Hora',
  'composer.quickEmoji.label': 'Enviar directamente',
  'composer.quickEmoji.group': 'Emojis rápidos',
  'composer.effects.panel': 'Efectos del mensaje',
  'composer.effects.entrance': 'Animación de entrada',
  'composer.effects.permanent': 'Efecto permanente',
  'composer.effects.clearAll': 'Borrar todo',
} satisfies ComposerAttachCatalogSlice;

export default esComposerAttach;
