import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const de = {
  'admin.role': 'Deine Rolle: {role}',
  'admin.denied.title': 'Geschützter Bereich',
  'admin.denied.message': 'Dieser Bereich erfordert ein Verwaltungsrecht.',
  'admin.counters.title': 'Auf einen Blick',
  'admin.counters.unavailable': 'Zähler derzeit nicht verfügbar.',
  'admin.counters.users': 'Konten',
  'admin.counters.activeUsers': 'Aktive Konten',
  'admin.counters.messages': 'Nachrichten',
  'admin.counters.communities': 'Communities',
  'admin.counters.reports': 'Meldungen',
  'admin.counters.newUsers': 'Neu (24 Std.)',
  'admin.sections.title': 'Bereiche',
  'admin.nav.dashboard': 'Übersicht',
  'admin.nav.users': 'Konten',
  'admin.nav.moderation': 'Moderation',
  'admin.nav.audit': 'Audit-Protokolle',
  'admin.nav.analytics': 'Statistiken',
  'admin.nav.trackingLinks': 'Tracking-Links',
  'admin.nav.ranking': 'Rangliste',
  'admin.nav.broadcasts': 'Rundsendungen',
  'admin.nav.settings': 'Einstellungen',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Überwachung',
  'admin.users.search': 'Konto suchen',
  'admin.users.count': '{count} Konto/Konten',
  'admin.users.empty': 'Kein Konto passt.',
  'admin.users.unavailable': 'Liste derzeit nicht verfügbar.',
  'admin.users.inactive': 'deaktiviert',
  'admin.users.previous': 'Zurück',
  'admin.users.next': 'Weiter',
  'admin.user.title': 'Mitglied',
  'admin.user.unavailable': 'Profil derzeit nicht verfügbar.',
  'admin.user.identity': 'Identität',
  'admin.user.account': 'Konto',
  'admin.user.created': 'Beigetreten am',
  'admin.user.lastActive': 'Zuletzt aktiv',
  'admin.user.twoFactor': 'Zwei-Faktor',
  'admin.user.enabled': 'aktiviert',
  'admin.user.deleted': 'gelöscht',
  'admin.user.role': 'Rolle',
  'admin.edit.open': 'Bearbeiten',
  'admin.edit.title': 'Mitglied bearbeiten',
  'admin.edit.displayName': 'Anzeigename',
  'admin.edit.email': 'E-Mail',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Konto aktiv',
  'admin.edit.save': 'Speichern',
  'admin.edit.reason': 'Grund (optional)',
  'admin.edit.warnRole': 'Eine Rollenänderung ändert die Rechte.',
  'admin.edit.warnDeactivate': 'Deaktivieren beendet offene Sitzungen.',
  'admin.edit.confirm': 'Bestätigen',
  'admin.edit.saved': 'Änderungen gespeichert',
  'admin.edit.failed': 'Speichern fehlgeschlagen',
  'admin.password.title': 'Passwort zurücksetzen',
  'admin.password.warn': 'Damit enden alle offenen Sitzungen.',
  'admin.password.generated': 'Jetzt kopieren — es wird nicht erneut angezeigt.',
  'admin.password.copy': 'Kopieren',
  'admin.password.copied': 'Kopiert',
  'admin.password.apply': 'Zurücksetzen',
  'admin.password.done': 'Passwort zurückgesetzt',
  'admin.password.failed': 'Zurücksetzen fehlgeschlagen',
  'admin.ban.open': 'Sperren',
  'admin.ban.title': 'Dieses Mitglied sperren',
  'admin.ban.reason': 'Grund (erforderlich)',
  'admin.ban.permanent': 'Dauerhafte Sperre',
  'admin.ban.until': 'Bis',
  'admin.ban.apply': 'Sperren',
  'admin.ban.lift': 'Aufheben',
  'admin.ban.active': 'aktiv',
  'admin.ban.expired': 'abgelaufen',
  'admin.ban.lifted': 'aufgehoben',
  'admin.ban.none': 'Keine Sperren',
  'admin.ban.done': 'Sperre gespeichert',
  'admin.ban.failed': 'Sperren fehlgeschlagen',
  'admin.media.title': 'Medien',
  'admin.media.empty': 'Keine Medien',
  'admin.media.protected': 'geschützt',
  'admin.media.fromPost': 'Beitrag',
  'admin.media.fromMessage': 'Nachricht',
  'admin.conv.title': 'Unterhaltungen',
  'admin.conv.empty': 'Keine Unterhaltungen',
  'admin.conv.members': '{count} Mitglieder',
  'admin.nav.conversations': 'Unterhaltungen',
  'admin.convList.search': 'Unterhaltung suchen',
  'admin.convList.count': '{count} Unterhaltung(en)',
  'admin.convList.empty': 'Keine Unterhaltung gefunden.',
  'admin.convList.unavailable': 'Liste derzeit nicht verfügbar.',
  'admin.convList.members': '{count} Mitglieder',
  'admin.convList.sovereign': 'Dem Admin-Rang vorbehalten.',
  'admin.convDetail.title': 'Eine Unterhaltung lesen',
  'admin.convDetail.reasonLabel': 'Grund des Lesens',
  'admin.convDetail.reasonHint': 'Mindestens zehn Zeichen, mit Ihrem Namen protokolliert.',
  'admin.convDetail.read': 'Unterhaltung lesen',
  'admin.convDetail.empty': 'Keine Nachricht',
  'admin.convDetail.memberPrism': 'Im Prisma des Mitglieds gelesen: {languages}',
  'admin.agent.title': 'Agentensteuerung',
  'admin.agent.denied': 'Diese Steuerung verlangt ein eigenes Recht.',
  'admin.agent.users': 'Geführte Mitglieder',
  'admin.agent.tracked': 'Begleitete Unterhaltungen',
  'admin.agent.empty': 'Nichts zu zeigen.',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Lauf aktiv: {node}',
  'admin.agent.relaunch': 'Agenten erneut starten',
  'admin.agent.effect': 'Wiederholt die Auswertung und kann eine Nachricht veröffentlichen.',
  'admin.agent.done': 'Start angefordert',
  'admin.agent.failed': 'Abgelehnt',
  'admin.agent.stop': 'Lauf anhalten',
  'admin.agent.halted': 'Lauf angehalten',
  'admin.agent.down': 'Agentendienst nicht erreichbar.',
  'admin.agent.logs': 'Lauf-Protokoll',
  'admin.tab.profile': 'Profil',
  'admin.tab.preferences': 'Einstellungen',
  'admin.tab.conversations': 'Unterhaltungen',
  'admin.tab.media': 'Medien',
  'admin.tab.security': 'Sicherheit',
  'admin.tab.activity': 'Aktivität',
  'admin.carousel.title': 'Bilder',
  'admin.carousel.empty': 'Keine Bilder',
  'admin.carousel.avatar': 'Profilbild',
  'admin.carousel.banner': 'Banner',
  'admin.carousel.previous': 'Vorheriges Bild',
  'admin.carousel.next': 'Nächstes Bild',
  'admin.carousel.position': '{index} von {count}',
  'admin.carousel.open': 'Bild vergrößern',
  'admin.carousel.close': 'Bild schließen',
  'admin.user.completion': 'Profil zu {percent} % vollständig',
  'admin.user.names': 'Vor- und Nachname',
  'admin.user.phone': 'Telefon',
  'admin.user.timezone': 'Zeitzone',
  'admin.user.languages': 'Sprachen',
  'admin.user.systemLanguage': 'Hauptsprache',
  'admin.user.regionalLanguage': 'Zweitsprache',
  'admin.user.customLanguage': 'Eigene Sprache',
  'admin.user.deviceLocale': 'Gerätesprache',
  'admin.user.updated': 'Geändert am',
  'admin.user.birthDate': 'Geburtsdatum',
  'admin.user.verifications': 'Verifizierungen',
  'admin.user.emailVerified': 'E-Mail bestätigt',
  'admin.user.phoneVerified': 'Telefon bestätigt',
  'admin.user.ageVerified': 'Alter bestätigt',
  'admin.user.notVerified': 'nicht bestätigt',
  'admin.user.securityTitle': 'Kontosicherheit',
  'admin.user.locked': 'Gesperrt bis {date}',
  'admin.user.failedLogins': 'Fehlgeschlagene Anmeldungen',
  'admin.user.lastPasswordChange': 'Passwort geändert am',
  'admin.user.consents': 'Einwilligungen',
  'admin.user.consent.voiceProfile': 'Stimmprofil',
  'admin.user.consent.voiceData': 'Sprachdaten',
  'admin.user.consent.dataProcessing': 'Datenverarbeitung',
  'admin.user.consent.analytics': 'Nutzungsanalyse',
  'admin.user.consent.voiceCloning': 'Stimmklonen',
  'admin.user.terms': 'AGB akzeptiert (v{version})',
  'admin.user.engagement': 'Engagement',
  'admin.user.streak': 'Serie: {current} T (Rekord {longest} T)',
  'admin.user.pending': 'Bestätigung ausstehend',
  'admin.user.blocked': 'Blockierte Konten',
  'admin.user.metadata': 'Metadaten',
  'admin.user.none': '—',
  'admin.stats.title': 'Statistiken',
  'admin.stats.messages': 'Gesendete Nachrichten',
  'admin.stats.conversations': 'Unterhaltungen',
  'admin.stats.translations': 'Übersetzungen',
  'admin.stats.posts': 'Beiträge',
  'admin.stats.stories': 'Storys',
  'admin.stats.reels': 'Reels',
  'admin.stats.comments': 'Kommentare',
  'admin.stats.reactions': 'Reaktionen',
  'admin.stats.attachments': 'Anhänge',
  'admin.stats.friends': 'Freunde',
  'admin.stats.friendRequests': 'Offene Freundschaftsanfragen',
  'admin.stats.contacts': 'Kontakte',
  'admin.stats.communities': 'Communitys',
  'admin.stats.reportsReceived': 'Erhaltene Meldungen',
  'admin.stats.reportsMade': 'Abgegebene Meldungen',
  'admin.stats.sessions': 'Aktive Sitzungen',
  'admin.stats.bans': 'Sperren',
  'admin.stats.memberDays': 'Tage als Mitglied',
  'admin.stats.shareLinks': 'Freigabelinks',
  'admin.stats.trackingLinks': 'Tracking-Links',
  'admin.stats.affiliations': 'Empfehlungen',
  'admin.stats.unavailable': 'Statistiken derzeit nicht verfügbar.',
  'admin.pref.title': 'Einstellungen des Mitglieds',
  'admin.pref.reason': 'Grund (optional)',
  'admin.pref.cat.privacy': 'Datenschutz',
  'admin.pref.cat.audio': 'Audio',
  'admin.pref.cat.message': 'Nachrichten',
  'admin.pref.cat.notification': 'Benachrichtigungen',
  'admin.pref.cat.video': 'Video',
  'admin.pref.cat.document': 'Dokumente',
  'admin.pref.cat.application': 'App',
  'admin.pref.default': 'Standard',
  'admin.pref.custom': 'angepasst',
  'admin.pref.readOnly': 'schreibgeschützt',
  'admin.pref.saved': 'Einstellung gespeichert',
  'admin.pref.failed': 'Einstellung nicht gespeichert',
  'admin.pref.consent': 'Das Mitglied hat diese Einwilligung nicht erteilt',
  'admin.pref.unavailable': 'Einstellungen derzeit nicht verfügbar.',
  'admin.conv.sort': 'Sortieren nach',
  'admin.conv.sort.lastMessageAt': 'Letzte Aktivität',
  'admin.conv.sort.createdAt': 'Erstellung',
  'admin.conv.sort.title': 'Titel',
  'admin.conv.sort.joinedAt': 'Beitritt des Mitglieds',
  'admin.conv.order.asc': 'Aufsteigend',
  'admin.conv.order.desc': 'Absteigend',
  'admin.conv.search': 'Unterhaltung suchen',
  'admin.conv.filterType': 'Typ',
  'admin.conv.filterRole': 'Rolle des Mitglieds',
  'admin.conv.all': 'Alle',
  'admin.conv.messages': '{count} Nachrichten',
  'admin.conv.memberRole': 'Rolle: {role}',
  'admin.conv.role.creator': 'Ersteller',
  'admin.conv.role.admin': 'Administrator',
  'admin.conv.role.moderator': 'Moderator',
  'admin.conv.role.member': 'Mitglied',
  'admin.conv.closed': 'geschlossen',
  'admin.conv.archived': 'archiviert',
  'admin.conv.read': 'Lesen',
  'admin.conv.configure': 'Konfigurieren',
  'admin.convSettings.title': 'Unterhaltung konfigurieren',
  'admin.convSettings.titleField': 'Titel',
  'admin.convSettings.description': 'Beschreibung',
  'admin.convSettings.avatar': 'Bild (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Wer schreiben darf',
  'admin.convSettings.writeRole.everyone': 'Alle',
  'admin.convSettings.writeRole.member': 'Mitglieder',
  'admin.convSettings.writeRole.moderator': 'Moderatoren und höher',
  'admin.convSettings.writeRole.admin': 'Administratoren und höher',
  'admin.convSettings.writeRole.creator': 'Nur der Ersteller',
  'admin.convSettings.announcement': 'Ankündigungskanal',
  'admin.convSettings.slowMode': 'Langsamer Modus (Sekunden)',
  'admin.convSettings.autoTranslate': 'Automatische Übersetzung',
  'admin.convSettings.archive': 'Archivieren',
  'admin.convSettings.restore': 'Wiederherstellen',
  'admin.convSettings.close': 'Für Nachrichten schließen',
  'admin.convSettings.reopen': 'Wieder öffnen',
  'admin.convSettings.memberRole': 'Rolle dieses Mitglieds',
  'admin.convSettings.remove': 'Aus der Unterhaltung entfernen',
  'admin.convSettings.reason': 'Grund (mindestens 10 Zeichen)',
  'admin.convSettings.confirm': 'Bestätigen',
  'admin.convSettings.save': 'Speichern',
  'admin.convSettings.saved': 'Unterhaltung aktualisiert',
  'admin.convSettings.removed': 'Mitglied entfernt',
  'admin.convSettings.failed': 'Änderung abgelehnt',
  'admin.convSettings.creatorProtected': 'Der Ersteller kann weder herabgestuft noch entfernt werden',
  'admin.security.sessions': 'Sitzungen',
  'admin.security.current': 'aktiv',
  'admin.security.revoked': 'widerrufen',
  'admin.security.revoke': 'Widerrufen',
  'admin.security.revoked.done': 'Sitzung widerrufen',
  'admin.security.events': 'Sicherheitsereignisse',
  'admin.security.severity': 'Schweregrad',
  'admin.security.empty': 'Keine Ereignisse',
  'admin.security.bans': 'Sperrverlauf',
  'admin.security.unavailable': 'Sicherheit derzeit nicht verfügbar.',
  'admin.account.open': 'Sicherheit und Verifizierungen',
  'admin.account.unlock': 'Konto entsperren',
  'admin.account.twoFactorOff': 'Zwei-Faktor deaktivieren',
  'admin.account.twoFactorOn': 'Zwei-Faktor aktivieren',
  'admin.account.done': 'Konto aktualisiert',
  'admin.account.failed': 'Kontoänderung abgelehnt',
  'admin.activity.reportsMade': 'Abgegebene Meldungen',
  'admin.activity.reportedMessages': 'Gemeldete Nachrichten',
  'admin.activity.hiddenContent': 'Inhalt ausgeblendet',
  'admin.activity.links': 'Erstellte Links',
  'admin.activity.friendRequests': 'Freundschaftsanfragen',
  'admin.activity.empty': 'Nichts anzuzeigen',
  'admin.activity.unavailable': 'Aktivität derzeit nicht verfügbar.',
  'admin.edit.firstName': 'Vorname',
  'admin.edit.lastName': 'Nachname',
  'admin.edit.username': 'Benutzername',
  'admin.edit.phone': 'Telefon',
  'admin.edit.phoneCountryCode': 'Ländervorwahl',
  'admin.edit.timezone': 'Zeitzone',
  'admin.edit.banner': 'Banner (URL)',
  'admin.user.id': 'Kennung',
  'admin.user.onboarding': 'Einführung abgeschlossen',
  'admin.user.engagementScore': 'Engagement-Wert',
  'admin.user.meeshBalance': 'Meesh-Guthaben',
  'admin.user.meeshMinted': 'Insgesamt verdiente Meesh',
  'admin.user.deviceCountry': 'Land des Geräts',
  'admin.user.participations': 'Mitgliedschaften',
  'admin.stats.more': 'Alle Statistiken',
  'admin.pref.edit': 'Bearbeiten: {category}',
  'admin.carousel.unavailable': 'Bilder derzeit nicht verfügbar.',
  'admin.conv.type.direct': 'Direkt',
  'admin.conv.type.group': 'Gruppe',
  'admin.conv.type.public': 'Öffentlich',
  'admin.conv.type.global': 'Global',
  'admin.conv.type.broadcast': 'Übertragung',
  'admin.security.severity.low': 'Niedrig',
  'admin.security.severity.medium': 'Mittel',
  'admin.security.severity.high': 'Hoch',
  'admin.security.severity.critical': 'Kritisch',
  'admin.report.type.spam': 'Spam',
  'admin.report.type.inappropriate': 'Unangemessener Inhalt',
  'admin.report.type.harassment': 'Belästigung',
  'admin.report.type.violence': 'Gewalt',
  'admin.report.type.hateSpeech': 'Hassrede',
  'admin.report.type.fakeProfile': 'Gefälschtes Profil',
  'admin.report.type.impersonation': 'Identitätsdiebstahl',
  'admin.report.type.other': 'Sonstiges',
  'admin.report.target.message': 'Nachricht',
  'admin.report.target.user': 'Konto',
  'admin.report.target.conversation': 'Unterhaltung',
  'admin.report.target.community': 'Community',
  'admin.status.pending': 'Ausstehend',
  'admin.status.underReview': 'In Prüfung',
  'admin.status.resolved': 'Gelöst',
  'admin.status.rejected': 'Abgelehnt',
  'admin.status.dismissed': 'Eingestellt',
  'admin.status.accepted': 'Angenommen',
  'admin.status.blocked': 'Blockiert',
  'admin.status.success': 'Erfolgreich',
  'admin.status.failed': 'Fehlgeschlagen',
  'admin.security.lastActiveOn': 'Zuletzt aktiv: {date}',
  'admin.ban.untilDate': 'bis {date}',
  'admin.activity.sentTo': 'Gesendet an {name}',
  'admin.activity.receivedFrom': 'Empfangen von {name}',
} satisfies AdminInterfaceCatalog;

export default de;
