import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';
import kitAr from './admin/kit-ar';
import dashboardAr from './admin/dashboard-ar';
import statistiquesAr from './admin/statistiques-ar';
import moderationAr from './admin/moderation-ar';
import contenusAr from './admin/contenus-ar';
import liensAr from './admin/liens-ar';
import diffusionsAr from './admin/diffusions-ar';
import classementSupervisionAr from './admin/classement-supervision-ar';
import auditReglagesAr from './admin/audit-reglages-ar';
import personnesAr from './admin/personnes-ar';
import conversationsAgentAr from './admin/conversations-agent-ar';

const ar = {
  'admin.role': 'دورك: {role}',
  'admin.denied.title': 'منطقة محجوزة',
  'admin.denied.message': 'تتطلب هذه المنطقة صلاحية إدارية.',
  'admin.nav.dashboard': 'لوحة المعلومات',
  'admin.nav.users': 'الحسابات',
  'admin.nav.audit': 'سجل التدقيق',
  'admin.nav.analytics': 'الإحصاءات',
  'admin.nav.trackingLinks': 'روابط التتبع',
  'admin.nav.ranking': 'الترتيب',
  'admin.nav.broadcasts': 'البثوث',
  'admin.nav.settings': 'الإعدادات',
  'admin.nav.agent': 'الوكيل',
  'admin.nav.monitoring': 'المراقبة',
  'admin.nav.invitations': 'طلبات التواصل',
  'admin.nav.communities': 'المجتمعات',
  'admin.nav.shareLinks': 'روابط المشاركة',
  'admin.nav.posts': 'المنشورات',
  'admin.nav.reports': 'البلاغات',
  'admin.nav.languages': 'اللغات والترجمات',
  'admin.nav.dashboard.hint': 'حالة المنصة في لمحة',
  'admin.nav.users.hint': 'كل الحسابات وصلاحياتها وأمانها',
  'admin.nav.anonymous.hint': 'الضيوف الذين دخلوا عبر رابط دون حساب',
  'admin.nav.invitations.hint': 'طلبات الصداقة المرسلة بين الأعضاء',
  'admin.nav.conversations.hint': 'محادثات المنصة وقراءتها الخاضعة للرقابة',
  'admin.nav.communities.hint': 'المجتمعات وفرقها ومحادثاتها',
  'admin.nav.shareLinks.hint': 'الروابط التي تفتح محادثة',
  'admin.nav.posts.hint': 'المنشورات والستوري والريلز والحالات',
  'admin.nav.reports.hint': 'البلاغات التي تنتظر الفحص والمعالجة',
  'admin.nav.audit.hint': 'أثر كل إجراء إداري',
  'admin.nav.analytics.hint': 'النشاط والرسائل والمكالمات عبر الزمن',
  'admin.nav.ranking.hint': 'أنشط الأعضاء والمحادثات والروابط',
  'admin.nav.trackingLinks.hint': 'الحملات ونقراتها',
  'admin.nav.broadcasts.hint': 'المراسلة إلى كل الحسابات، بالبريد أو داخل التطبيق',
  'admin.nav.monitoring.hint': 'صحة الخدمات واستخدام المسارات',
  'admin.nav.languages.hint': 'صحة المنشور اللغوي: اللغات والأزواج المترجمة',
  'admin.nav.agent.hint': 'قيادة وكيل المحادثة',
  'admin.nav.settings.hint': 'وصولك وتفضيلات هذا الفضاء',
  'admin.users.search': 'ابحث عن حساب',
  'admin.users.count': '{count} حساب',
  'admin.users.unavailable': 'القائمة غير متاحة حاليًا.',
  'admin.users.previous': 'السابق',
  'admin.users.next': 'التالي',
  'admin.user.title': 'عضو',
  'admin.user.unavailable': 'البطاقة غير متاحة حاليًا.',
  'admin.user.identity': 'الهوية',
  'admin.user.created': 'انضمّ في',
  'admin.user.lastActive': 'آخر نشاط',
  'admin.user.twoFactor': 'التحقق بخطوتين',
  'admin.user.role': 'الدور',
  'admin.edit.displayName': 'الاسم المعروض',
  'admin.edit.email': 'البريد الإلكتروني',
  'admin.edit.bio': 'نبذة',
  'admin.edit.active': 'الحساب نشط',
  'admin.edit.save': 'حفظ',
  'admin.edit.reason': 'السبب (اختياري)',
  'admin.edit.warnRole': 'تغيير الدور يغيّر صلاحياته.',
  'admin.edit.warnDeactivate': 'التعطيل ينهي جلساته المفتوحة.',
  'admin.edit.confirm': 'تأكيد',
  'admin.edit.saved': 'تم حفظ التغييرات',
  'admin.edit.failed': 'تعذّر الحفظ',
  'admin.password.title': 'إعادة تعيين كلمة المرور',
  'admin.password.warn': 'هذا ينهي جميع جلساته المفتوحة.',
  'admin.password.generated': 'انسخها الآن: لن تُعرض مرة أخرى.',
  'admin.password.copy': 'نسخ',
  'admin.password.copied': 'تم النسخ',
  'admin.password.apply': 'إعادة التعيين',
  'admin.password.done': 'تم إعادة تعيين كلمة المرور',
  'admin.password.failed': 'تعذّرت إعادة التعيين',
  'admin.password.level': 'المستوى',
  'admin.password.level.simple': 'بسيط',
  'admin.password.level.easy': 'سهل',
  'admin.password.level.medium': 'متوسط',
  'admin.password.level.hard': 'صعب',
  'admin.password.field': 'كلمة المرور',
  'admin.password.editable': 'اختر مستوى أو اكتب كلمتك: ما يُعرض هو ما سيُطبَّق.',
  'admin.password.loading': 'جارٍ تحضير الاقتراحات…',
  'admin.password.proposals.failed': 'تعذّر تحميل الاقتراحات: اكتب كلمة مرور.',
  'admin.password.regenerate': 'اقتراح آخر',
  'admin.password.refused': 'مرفوضة: {reason}',
  'admin.ban.open': 'حظر',
  'admin.ban.title': 'حظر هذا العضو',
  'admin.ban.reason': 'السبب (إلزامي)',
  'admin.ban.permanent': 'حظر دائم',
  'admin.ban.until': 'حتى',
  'admin.ban.apply': 'حظر',
  'admin.ban.lift': 'رفع الحظر',
  'admin.ban.active': 'ساري',
  'admin.ban.expired': 'منتهٍ',
  'admin.ban.lifted': 'مرفوع',
  'admin.ban.none': 'لا توجد حالات حظر',
  'admin.ban.done': 'تم تسجيل الحظر',
  'admin.ban.failed': 'تعذّر الحظر',
  'admin.media.title': 'الوسائط',
  'admin.media.empty': 'لا توجد وسائط',
  'admin.media.protected': 'محمي',
  'admin.media.fromPost': 'منشور',
  'admin.media.fromMessage': 'رسالة',
  'admin.conv.title': 'المحادثات',
  'admin.conv.empty': 'لا توجد محادثات',
  'admin.conv.members': '{count} عضوًا',
  'admin.nav.conversations': 'المحادثات',
  'admin.convList.unavailable': 'القائمة غير متاحة حالياً.',
  'admin.convDetail.title': 'قراءة محادثة',
  'admin.convDetail.reasonLabel': 'سبب القراءة',
  'admin.convDetail.reasonHint': 'عشرة أحرف على الأقل، يُسجَّل مع اسمك.',
  'admin.convDetail.read': 'قراءة المحادثة',
  'admin.convDetail.empty': 'لا توجد رسائل',
  'admin.convDetail.memberPrism': 'مقروء وفق منشور لغات العضو: {languages}',
  'admin.agent.title': 'قيادة الوكيل',
  'admin.agent.denied': 'هذه القيادة تتطلّب صلاحية خاصة.',
  'admin.agent.users': 'أعضاء موجَّهون',
  'admin.agent.tracked': 'محادثات متابَعة',
  'admin.offline': 'غير متصل.',
  'admin.agent.scan': 'مسح جارٍ: {node}',
  'admin.agent.relaunch': 'إعادة تشغيل الوكيل',
  'admin.agent.effect': 'يعيد الدراسة وقد ينشر رسالة.',
  'admin.agent.done': 'طُلب التشغيل',
  'admin.agent.failed': 'رُفض',
  'admin.agent.stop': 'إيقاف المسح',
  'admin.agent.halted': 'أُوقف المسح',
  'admin.agent.down': 'خدمة الوكيل غير متاحة.',
  'admin.agent.logs': 'سجلّ المسوح',
  'admin.nav.anonymous': 'المجهولون',
  'admin.shell.menu': 'قائمة الإدارة',
  'admin.shell.fold': 'طي القائمة',
  'admin.shell.unfold': 'توسيع القائمة',
  'admin.shell.open': 'فتح القائمة',
  'admin.shell.close': 'إغلاق القائمة',
  'admin.shell.backToApp': 'العودة إلى التطبيق',
  'admin.list.all': 'الكل',
  'admin.list.yes': 'نعم',
  'admin.list.no': 'لا',
  'admin.list.reset': 'إعادة التعيين',
  'admin.list.pageSize': 'لكل صفحة',
  'admin.list.range': '{from}–{to} من {total}',
  'admin.list.sortBy': 'الترتيب حسب {column}',
  'admin.col.member': 'العضو',
  'admin.col.email': 'البريد',
  'admin.col.role': 'الدور',
  'admin.col.status': 'الحالة',
  'admin.col.created': 'التسجيل',
  'admin.col.lastActive': 'آخر نشاط',
  'admin.col.joined': 'الانضمام',
  'admin.col.language': 'اللغة',
  'admin.col.conversation': 'المحادثة',
  'admin.col.messages': 'الرسائل',
  'admin.col.name': 'الاسم',
  'admin.filter.active': 'نشطون',
  'admin.filter.inactive': 'معطّلون',
  'admin.filter.emailVerified': 'البريد موثّق',
  'admin.filter.twoFactor': 'المصادقة الثنائية',
  'admin.anonymous.search': 'البحث عن مجهول',
  'admin.anonymous.title': 'مشارك مجهول',
  'admin.col.type': 'النوع',
  'admin.col.members': 'الأعضاء',
  'admin.col.createdOn': 'الإنشاء',
  'admin.col.lastMessage': 'آخر رسالة',
  'admin.tab.profile': 'الملف',
  'admin.tab.conversations': 'المحادثات',
  'admin.tab.media': 'الوسائط',
  'admin.tab.contacts': 'جهات الاتصال',
  'admin.tab.communities': 'المجتمعات',
  'admin.tab.voice': 'الملف الصوتي',
  'admin.tab.security': 'الأمان',
  'admin.tab.reports': 'البلاغات',
  'admin.tab.label': 'أقسام الملف',
  'admin.dossier.empty': 'لا شيء لعرضه.',
  'admin.dossier.restricted': 'مخصص للمسؤولين المخولين بالبيانات الحساسة.',
  'admin.contacts.sent': 'مرسلة',
  'admin.contacts.received': 'مستلمة',
  'admin.contacts.direction': 'الطلب',
  'admin.contacts.links': '{share} رابط مشاركة · {tracking} رابط تتبع · {affiliate} رمز إحالة',
  'admin.communities.creator': 'المنشئ',
  'admin.communities.private': 'خاصة',
  'admin.voice.none': 'لا يوجد ملف صوتي مسجل.',
  'admin.voice.samples': 'العينات',
  'admin.voice.duration': 'المدة المسجلة',
  'admin.voice.model': 'النموذج',
  'admin.voice.consents': 'الموافقات',
  'admin.voice.consentProfile': 'الملف الصوتي',
  'admin.voice.consentData': 'البيانات الصوتية',
  'admin.voice.consentCloning': 'استنساخ الصوت',
  'admin.voice.traced': 'تُسجَّل هذه المعاينة في سجل التدقيق.',
  'admin.security.sessions': 'الجلسات',
  'admin.security.events': 'أحداث الأمان',
  'admin.security.device': 'الجهاز',
  'admin.security.place': 'الموقع',
  'admin.security.ip': 'عنوان IP',
  'admin.security.valid': 'مفتوحة',
  'admin.security.closed': 'مغلقة',
  'admin.security.event': 'الحدث',
  'admin.security.severity': 'الخطورة',
  'admin.col.date': 'التاريخ',
  'admin.reports.filed': 'بلاغات قدمها هذا العضو',
  'admin.reports.received': 'رسائله المبلغ عنها',
  'admin.reports.subject': 'الموضوع',
  'admin.reports.reporter': 'أبلغ عنه',
  'admin.reports.reason': 'السبب',
  'admin.reports.message': 'الرسالة',
  'admin.reports.withheld': 'النص مخصص للإشراف',
  'admin.gallery.title': 'الصور',
  'admin.gallery.empty': 'لا توجد صور',
  'admin.gallery.previous': 'الصورة السابقة',
  'admin.gallery.next': 'الصورة التالية',
  'admin.gallery.avatar': 'صورة الملف الشخصي',
  'admin.gallery.banner': 'صورة الغلاف',
  'admin.gallery.position': 'الصورة {n} من {total}',
  'admin.meta.name': 'الاسم الكامل',
  'admin.meta.systemLanguage': 'اللغة الرئيسية',
  'admin.meta.regionalLanguage': 'اللغة الثانوية',
  'admin.meta.customLanguage': 'لغة الوجهة',
  'admin.meta.timezone': 'المنطقة الزمنية',
  'admin.meta.completion': 'اكتمال الملف الشخصي',
  'admin.meta.failedLogins': 'محاولات دخول فاشلة',
  'admin.meta.updated': 'تم التحديث في',
  'admin.tab.preferences': 'التفضيلات',
  'admin.stats.messagesSent': 'الرسائل المرسلة',
  'admin.stats.conversations': 'المحادثات',
  'admin.stats.posts': 'المنشورات',
  'admin.stats.reels': 'المقاطع',
  'admin.stats.stories': 'القصص',
  'admin.stats.comments': 'التعليقات',
  'admin.stats.reactionsGiven': 'التفاعلات',
  'admin.stats.mediaUploaded': 'الوسائط المرفوعة',
  'admin.stats.friends': 'الأصدقاء',
  'admin.stats.pendingIn': 'طلبات مستلمة',
  'admin.stats.pendingOut': 'طلبات مرسلة',
  'admin.stats.reportsFiled': 'البلاغات المقدمة',
  'admin.stats.reportsReceived': 'البلاغات المستلمة',
  'admin.stats.activeSessions': 'الجلسات النشطة',
  'admin.stats.communities': 'المجتمعات',
  'admin.prefs.privacy': 'الخصوصية',
  'admin.prefs.notification': 'الإشعارات',
  'admin.prefs.message': 'الرسائل',
  'admin.prefs.audio': 'الصوت',
  'admin.prefs.video': 'الفيديو',
  'admin.prefs.document': 'المستندات',
  'admin.prefs.application': 'التطبيق',
  'admin.prefs.notice': 'يُطبَّق كل تغيير على العضو في جميع أجهزته ويُسجَّل في سجل التدقيق.',
  'admin.prefs.readOnly': 'للقراءة فقط',
  'admin.prefs.saved': 'تم حفظ التفضيل',
  'admin.prefs.failed': 'تعذّر حفظ التفضيل',
  'admin.prefs.consent': 'مرفوض: لم يمنح العضو الموافقة التي يتطلبها هذا الخيار',
  'admin.prefs.reserved': 'مرفوض: دورك لا يسمح بتعديل هذا العضو',
  'admin.prefs.invalid': 'مرفوض: قيمة غير صالحة',
  'admin.list.sort': 'الترتيب',
  'admin.list.order': 'الاتجاه',
  'admin.list.newest': 'الأحدث أولاً',
  'admin.list.oldest': 'الأقدم أولاً',
  'admin.conv.manage': 'إدارة',
  'admin.conv.role.admin': 'مسؤول',
  'admin.conv.role.moderator': 'مشرف',
  'admin.conv.role.member': 'عضو',
  'admin.conv.configure': 'ضبط',
  'admin.convSettings.title': 'ضبط المحادثة',
  'admin.convSettings.titleField': 'العنوان',
  'admin.convSettings.description': 'الوصف',
  'admin.convSettings.avatar': 'الصورة (رابط)',
  'admin.convSettings.banner': 'اللافتة (رابط)',
  'admin.convSettings.writeRole': 'من يمكنه الكتابة',
  'admin.convSettings.writeRole.everyone': 'الجميع',
  'admin.convSettings.writeRole.member': 'الأعضاء',
  'admin.convSettings.writeRole.moderator': 'المشرفون فما فوق',
  'admin.convSettings.writeRole.admin': 'المسؤولون فما فوق',
  'admin.convSettings.writeRole.creator': 'المُنشئ فقط',
  'admin.convSettings.announcement': 'قناة إعلانات',
  'admin.convSettings.slowMode': 'الوضع البطيء (بالثواني)',
  'admin.convSettings.autoTranslate': 'الترجمة التلقائية',
  'admin.convSettings.archive': 'أرشفة',
  'admin.convSettings.restore': 'استعادة',
  'admin.convSettings.close': 'إغلاق الكتابة',
  'admin.convSettings.reopen': 'إعادة الفتح',
  'admin.convSettings.memberRole': 'دور هذا العضو',
  'admin.convSettings.remove': 'إزالة من المحادثة',
  'admin.convSettings.reason': 'السبب (10 أحرف على الأقل)',
  'admin.convSettings.confirm': 'تأكيد',
  'admin.convSettings.save': 'حفظ',
  'admin.convSettings.saved': 'تم تحديث المحادثة',
  'admin.convSettings.removed': 'تمت إزالة العضو',
  'admin.convSettings.failed': 'رُفض التعديل',
  'admin.convSettings.creatorProtected': 'لا يمكن خفض رتبة المُنشئ أو إزالته',
  'admin.create.open': 'إنشاء حساب',
  'admin.create.title': 'حساب جديد',
  'admin.create.username': 'اسم المستخدم',
  'admin.create.firstName': 'الاسم الأول',
  'admin.create.lastName': 'اسم العائلة',
  'admin.create.email': 'البريد الإلكتروني',
  'admin.create.password': 'كلمة المرور',
  'admin.create.passwordHint': 'طويلة ويصعب تخمينها: تُرفض كلمة المرور الضعيفة.',
  'admin.create.language': 'لغة الواجهة',
  'admin.create.emailVerified': 'أشهد بصحة عنوان البريد هذا',
  'admin.create.emailVerifiedOn': 'سيتمكن الحساب من تسجيل الدخول فورًا.',
  'admin.create.emailVerifiedOff': 'بدون ذلك، سيُرسل رمز إلى هذا العنوان عند أول تسجيل دخول.',
  'admin.create.submit': 'إنشاء الحساب',
  'admin.create.created': 'تم إنشاء الحساب',
  'admin.create.failed': 'رُفض الإنشاء: {reason}',
  'admin.create.emailTaken': 'هذا العنوان مستخدم بالفعل من حساب آخر.',
  'admin.create.usernameTaken': 'اسم المستخدم هذا مأخوذ بالفعل.',
  'admin.create.missing': 'املأ جميع الحقول.',
  'admin.images.avatarOpen': 'تغيير الصورة',
  'admin.images.bannerOpen': 'تغيير الغلاف',
  'admin.images.upload': 'رفع صورة',
  'admin.images.uploading': 'جارٍ الرفع…',
  'admin.images.remove': 'إزالة',
  'admin.images.choose': 'الاختيار من منشوراته العامة',
  'admin.images.chooseHint': 'تُعرض فقط الصور التي نشرها للعموم.',
  'admin.images.noCandidate': 'لا توجد صورة عامة لعرضها.',
  'admin.images.candidatesFailed': 'تعذّر تحميل صوره العامة.',
  'admin.images.useCandidate': 'استخدام الصورة {n} من {total}',
  'admin.images.current': 'الصورة الحالية',
  'admin.images.saved': 'تم تحديث الصورة',
  'admin.images.removed': 'تمت إزالة الصورة',
  'admin.images.failed': 'فشل تحديث الصورة',
  'admin.images.offline': 'غير متصل: أعد المحاولة عند الاتصال.',
  'admin.images.unreadable': 'تعذّرت قراءة هذه الصورة.',
  'admin.section.saving': 'جارٍ الحفظ…',
  'admin.contact.title': 'التواصل',
  'admin.contact.phone': 'الهاتف',
  'admin.contact.verified': 'مُتحقَّق منه',
  'admin.contact.unverified': 'غير مُتحقَّق منه',
  'admin.contact.resend': 'إعادة إرسال التحقق',
  'admin.contact.resent': 'تم إرسال التحقق',
  'admin.contact.resendFailed': 'تعذّر إرسال التحقق',
  'admin.contact.markVerified': 'وضع علامة «مُتحقَّق منه»',
  'admin.contact.markUnverified': 'إزالة التحقق',
  'admin.security.twoFactorHint': 'يُطلب رمز عند كل تسجيل دخول.',
  'admin.security.sessionsOpen': 'عرض الجلسات',
  'admin.roleStatus.title': 'الدور والحالة',
  'admin.identity.suggestions': 'أسماء مستخدم متاحة',
  'admin.identity.noLanguage': 'لا شيء',
  'admin.security.twoFactorNotEnrolled': 'يجب على العضو أولًا ربط تطبيق مصادقة.',
  'admin.quick.title': 'إجراءات سريعة',
  'admin.quick.activate': 'تفعيل الحساب',
  'admin.quick.activated': 'تم تفعيل الحساب',
  'admin.quick.validateEmail': 'تأكيد البريد الإلكتروني',
  'admin.quick.validatePhone': 'تأكيد الهاتف',
  ...kitAr,
  ...dashboardAr,
  ...statistiquesAr,
  ...moderationAr,
  ...contenusAr,
  ...liensAr,
  ...diffusionsAr,
  ...classementSupervisionAr,
  ...auditReglagesAr,
  ...personnesAr,
  ...conversationsAgentAr,
} satisfies AdminInterfaceCatalog;

export default ar;
