import type { SendSheetCatalog } from '@/lib/i18n-send-sheet-catalog';

const de = {
  'sendSheet.title.forward': 'Weiterleiten',
  'sendSheet.title.share': 'Teilen',
  'sendSheet.title.sendTo': 'Senden an…',
  'sendSheet.cancel': 'Abbrechen',
  'sendSheet.caption.label': 'Nachricht',
  'sendSheet.caption.placeholder': 'Nachricht hinzufügen…',
  'sendSheet.search.label': 'Person oder Unterhaltung suchen',
  'sendSheet.search.placeholder': 'Person oder Unterhaltung suchen',
  'sendSheet.empty': 'Keine Ergebnisse',
  'sendSheet.section.recent': 'Zuletzt',
  'sendSheet.section.people': 'Personen',
  'sendSheet.section.conversations': 'Unterhaltungen',
  'sendSheet.section.publish': 'Veröffentlichen',
  'sendSheet.publish.story': 'Meine Story',
  'sendSheet.publish.post': 'Beitrag',
  'sendSheet.publish.reel': 'Reel',
  'sendSheet.send': 'Senden',
  'sendSheet.sendCount': 'Senden ({count})',
  'sendSheet.row.select': '{name} auswählen',
  'sendSheet.selectedCount': '{count} ausgewählt',
  'sendSheet.state.sending': 'Wird gesendet…',
  'sendSheet.state.sent': 'Gesendet',
  'sendSheet.state.failed': 'Fehlgeschlagen',
  'sendSheet.state.retry': 'Erneut versuchen',
  'sendSheet.state.waitingNetwork': 'Warten auf Netzwerk',
  'sendSheet.failure.download': 'Die Datei konnte nicht abgerufen werden',
  'sendSheet.failure.refused': 'Das Senden wurde abgelehnt',
  'sendSheet.limit.recipients': 'Höchstens {count} Empfänger',
  'sendSheet.error.captionTooLong': 'Diese Nachricht ist zu lang für eine Veröffentlichung (höchstens {count} Zeichen)',
  'sendSheet.error.tooManyFiles': 'Höchstens {count} Dateien pro Veröffentlichung',
  'sendSheet.moreOptions': 'Weitere Optionen…',
  'sendSheet.copyLink': 'Link kopieren',
  'sendSheet.linkCopied': 'Link kopiert',
  'sendSheet.announce.sent': 'An {count} gesendet',
  'sendSheet.preview.messages': '{count} Nachrichten',
  'sendSheet.preview.photo': 'Foto',
  'sendSheet.preview.video': 'Video',
  'sendSheet.preview.voice': 'Sprachnachricht',
  'sendSheet.preview.file': 'Datei',
  'sendSheet.preview.publication': 'Veröffentlichung',
  'sendSheet.protected': 'Geschützter Inhalt: Er kann nicht veröffentlicht werden',
  'shareLinkSheet.title': 'Freigabelink erstellen',
  'shareLinkSheet.empty': 'Im Moment kann keine Unterhaltung einen Link erhalten.',
  'shareLinkSheet.createFailed': 'Der Link konnte nicht erstellt werden — versuche es gleich noch einmal.',
  'shareLinkSheet.copied': 'Link kopiert — du musst ihn nur noch einfügen.',
  'shareLinkSheet.unavailable': 'Hier kann nicht geteilt werden. Kopiere die Adresse dieser Seite.',
} satisfies SendSheetCatalog;

export default de;
