import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';
import kitEn from './admin/kit-en';
import dashboardEn from './admin/dashboard-en';
import statistiquesEn from './admin/statistiques-en';
import moderationEn from './admin/moderation-en';
import contenusEn from './admin/contenus-en';
import liensEn from './admin/liens-en';
import diffusionsEn from './admin/diffusions-en';
import classementSupervisionEn from './admin/classement-supervision-en';
import auditReglagesEn from './admin/audit-reglages-en';
import personnesEn from './admin/personnes-en';
import conversationsAgentEn from './admin/conversations-agent-en';

const en = {
  'admin.role': 'Your role: {role}',
  'admin.denied.title': 'Restricted area',
  'admin.denied.message': 'This area requires an administration right.',
  'admin.nav.dashboard': 'Dashboard',
  'admin.nav.users': 'Accounts',
  'admin.nav.audit': 'Audit log',
  'admin.nav.analytics': 'Analytics',
  'admin.nav.trackingLinks': 'Tracking links',
  'admin.nav.ranking': 'Ranking',
  'admin.nav.broadcasts': 'Broadcasts',
  'admin.nav.settings': 'Settings',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Monitoring',
  'admin.nav.invitations': 'Contact requests',
  'admin.nav.communities': 'Communities',
  'admin.nav.shareLinks': 'Share links',
  'admin.nav.posts': 'Posts',
  'admin.nav.reports': 'Reports',
  'admin.nav.languages': 'Languages and translations',
  'admin.nav.dashboard.hint': 'The state of the platform at a glance',
  'admin.nav.users.hint': 'Every account, its rights and its security',
  'admin.nav.anonymous.hint': 'Guests who came in through a link, without an account',
  'admin.nav.invitations.hint': 'Friend requests sent between members',
  'admin.nav.conversations.hint': 'The platform’s conversations and their supervised reading',
  'admin.nav.communities.hint': 'Communities, their teams and their conversations',
  'admin.nav.shareLinks.hint': 'Links that open a conversation',
  'admin.nav.posts.hint': 'Posts, stories, reels and statuses',
  'admin.nav.reports.hint': 'Reports to review and handle',
  'admin.nav.audit.hint': 'The trace of every administration action',
  'admin.nav.analytics.hint': 'Activity, messages and calls over time',
  'admin.nav.ranking.hint': 'The most active members, conversations and links',
  'admin.nav.trackingLinks.hint': 'Campaigns and their clicks',
  'admin.nav.broadcasts.hint': 'Write to every account, by email or in the app',
  'admin.nav.monitoring.hint': 'Service health and route usage',
  'admin.nav.languages.hint': 'The health of the Prism: languages and translated pairs',
  'admin.nav.agent.hint': 'Drive the conversation agent',
  'admin.nav.settings.hint': 'Your access and the space preferences',
  'admin.users.search': 'Search an account',
  'admin.users.count': '{count} account(s)',
  'admin.users.unavailable': 'List unavailable right now.',
  'admin.users.previous': 'Previous',
  'admin.users.next': 'Next',
  'admin.user.title': 'Member',
  'admin.user.unavailable': 'Profile unavailable right now.',
  'admin.user.identity': 'Identity',
  'admin.user.created': 'Joined on',
  'admin.user.lastActive': 'Last active',
  'admin.user.twoFactor': 'Two-factor',
  'admin.user.role': 'Role',
  'admin.edit.displayName': 'Display name',
  'admin.edit.email': 'Email',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Account active',
  'admin.edit.save': 'Save',
  'admin.edit.reason': 'Reason (optional)',
  'admin.edit.warnRole': 'Changing the role changes their permissions.',
  'admin.edit.warnDeactivate': 'Deactivating ends their open sessions.',
  'admin.edit.confirm': 'Confirm',
  'admin.edit.saved': 'Changes saved',
  'admin.edit.failed': 'Could not save',
  'admin.password.title': 'Reset password',
  'admin.password.warn': 'This ends all their open sessions.',
  'admin.password.generated': 'Copy it now — it will not be shown again.',
  'admin.password.copy': 'Copy',
  'admin.password.copied': 'Copied',
  'admin.password.apply': 'Reset',
  'admin.password.done': 'Password reset',
  'admin.password.failed': 'Reset failed',
  'admin.password.level': 'Level',
  'admin.password.level.simple': 'Simple',
  'admin.password.level.easy': 'Easy',
  'admin.password.level.medium': 'Medium',
  'admin.password.level.hard': 'Hard',
  'admin.password.field': 'Password',
  'admin.password.editable': 'Pick a level or type your own: what is shown is what will be applied.',
  'admin.password.loading': 'Preparing proposals…',
  'admin.password.proposals.failed': 'Proposals could not be loaded: type a password.',
  'admin.password.regenerate': 'Another proposal',
  'admin.password.refused': 'Refused: {reason}',
  'admin.ban.open': 'Ban',
  'admin.ban.title': 'Ban this member',
  'admin.ban.reason': 'Reason (required)',
  'admin.ban.permanent': 'Permanent ban',
  'admin.ban.until': 'Until',
  'admin.ban.apply': 'Ban',
  'admin.ban.lift': 'Lift',
  'admin.ban.active': 'active',
  'admin.ban.expired': 'expired',
  'admin.ban.lifted': 'lifted',
  'admin.ban.none': 'No bans',
  'admin.ban.done': 'Ban recorded',
  'admin.ban.failed': 'Ban failed',
  'admin.media.title': 'Media',
  'admin.media.empty': 'No media',
  'admin.media.protected': 'protected',
  'admin.media.fromPost': 'post',
  'admin.media.fromMessage': 'message',
  'admin.conv.title': 'Conversations',
  'admin.conv.empty': 'No conversations',
  'admin.conv.members': '{count} members',
  'admin.nav.conversations': 'Conversations',
  'admin.convList.unavailable': 'List unavailable right now.',
  'admin.convDetail.title': 'Reading a conversation',
  'admin.convDetail.reasonLabel': 'Reason for reading',
  'admin.convDetail.reasonHint': 'Ten characters minimum, logged with your name.',
  'admin.convDetail.read': 'Read the conversation',
  'admin.convDetail.empty': 'No message',
  'admin.convDetail.memberPrism': 'Read in the member’s prism: {languages}',
  'admin.agent.title': 'Agent control',
  'admin.agent.denied': 'This control needs a dedicated permission.',
  'admin.agent.users': 'Members driven',
  'admin.agent.tracked': 'Tracked conversations',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Scan running: {node}',
  'admin.agent.relaunch': 'Run the agent again',
  'admin.agent.effect': 'Re-runs the study and may publish a message.',
  'admin.agent.done': 'Run requested',
  'admin.agent.failed': 'Refused',
  'admin.agent.stop': 'Stop the scan',
  'admin.agent.halted': 'Scan stopped',
  'admin.agent.down': 'Agent service unreachable.',
  'admin.agent.logs': 'Scan log',
  'admin.nav.anonymous': 'Anonymous',
  'admin.shell.menu': 'Administration menu',
  'admin.shell.fold': 'Collapse menu',
  'admin.shell.unfold': 'Expand menu',
  'admin.shell.open': 'Open menu',
  'admin.shell.close': 'Close menu',
  'admin.shell.backToApp': 'Back to the app',
  'admin.list.all': 'All',
  'admin.list.yes': 'Yes',
  'admin.list.no': 'No',
  'admin.list.reset': 'Reset',
  'admin.list.pageSize': 'Per page',
  'admin.list.range': '{from}–{to} of {total}',
  'admin.list.sortBy': 'Sort by {column}',
  'admin.col.member': 'Member',
  'admin.col.email': 'Email',
  'admin.col.role': 'Role',
  'admin.col.status': 'Status',
  'admin.col.created': 'Joined',
  'admin.col.lastActive': 'Last active',
  'admin.col.joined': 'Joined',
  'admin.col.language': 'Language',
  'admin.col.conversation': 'Conversation',
  'admin.col.messages': 'Messages',
  'admin.col.name': 'Name',
  'admin.filter.active': 'Active',
  'admin.filter.inactive': 'Deactivated',
  'admin.filter.emailVerified': 'Email verified',
  'admin.filter.twoFactor': 'Two-factor',
  'admin.anonymous.search': 'Search anonymous participants',
  'admin.anonymous.title': 'Anonymous participant',
  'admin.col.type': 'Type',
  'admin.col.members': 'Members',
  'admin.col.createdOn': 'Created',
  'admin.col.lastMessage': 'Last message',
  'admin.tab.profile': 'Profile',
  'admin.tab.conversations': 'Conversations',
  'admin.tab.media': 'Media',
  'admin.tab.contacts': 'Contacts',
  'admin.tab.communities': 'Communities',
  'admin.tab.voice': 'Voice profile',
  'admin.tab.security': 'Security',
  'admin.tab.reports': 'Reports',
  'admin.tab.label': 'Profile sections',
  'admin.dossier.empty': 'Nothing to show.',
  'admin.dossier.restricted': 'Restricted to administrators cleared for sensitive data.',
  'admin.contacts.sent': 'Sent',
  'admin.contacts.received': 'Received',
  'admin.contacts.direction': 'Request',
  'admin.contacts.links': '{share} share link(s) · {tracking} tracking link(s) · {affiliate} affiliate token(s)',
  'admin.communities.creator': 'Creator',
  'admin.communities.private': 'Private',
  'admin.voice.none': 'No voice profile recorded.',
  'admin.voice.samples': 'Samples',
  'admin.voice.duration': 'Recorded duration',
  'admin.voice.model': 'Model',
  'admin.voice.consents': 'Consents',
  'admin.voice.consentProfile': 'Voice profile',
  'admin.voice.consentData': 'Voice data',
  'admin.voice.consentCloning': 'Voice cloning',
  'admin.voice.traced': 'This view is recorded in the audit log.',
  'admin.security.sessions': 'Sessions',
  'admin.security.events': 'Security events',
  'admin.security.device': 'Device',
  'admin.security.place': 'Location',
  'admin.security.ip': 'IP address',
  'admin.security.valid': 'Open',
  'admin.security.closed': 'Closed',
  'admin.security.event': 'Event',
  'admin.security.severity': 'Severity',
  'admin.col.date': 'Date',
  'admin.reports.filed': 'Reports filed by this member',
  'admin.reports.received': 'Their reported messages',
  'admin.reports.subject': 'Subject',
  'admin.reports.reporter': 'Reported by',
  'admin.reports.reason': 'Reason',
  'admin.reports.message': 'Message',
  'admin.reports.withheld': 'text reserved for moderators',
  'admin.gallery.title': 'Images',
  'admin.gallery.empty': 'No images',
  'admin.gallery.previous': 'Previous image',
  'admin.gallery.next': 'Next image',
  'admin.gallery.avatar': 'Profile photo',
  'admin.gallery.banner': 'Banner',
  'admin.gallery.position': 'Image {n} of {total}',
  'admin.meta.name': 'Full name',
  'admin.meta.systemLanguage': 'Main language',
  'admin.meta.regionalLanguage': 'Secondary language',
  'admin.meta.customLanguage': 'Destination language',
  'admin.meta.timezone': 'Time zone',
  'admin.meta.completion': 'Profile completion',
  'admin.meta.failedLogins': 'Failed sign-ins',
  'admin.meta.updated': 'Updated on',
  'admin.tab.preferences': 'Preferences',
  'admin.stats.messagesSent': 'Messages sent',
  'admin.stats.conversations': 'Conversations',
  'admin.stats.posts': 'Posts',
  'admin.stats.reels': 'Reels',
  'admin.stats.stories': 'Stories',
  'admin.stats.comments': 'Comments',
  'admin.stats.reactionsGiven': 'Reactions given',
  'admin.stats.mediaUploaded': 'Media uploaded',
  'admin.stats.friends': 'Friends',
  'admin.stats.pendingIn': 'Requests received',
  'admin.stats.pendingOut': 'Requests sent',
  'admin.stats.reportsFiled': 'Reports filed',
  'admin.stats.reportsReceived': 'Reports received',
  'admin.stats.activeSessions': 'Active sessions',
  'admin.stats.communities': 'Communities',
  'admin.prefs.privacy': 'Privacy',
  'admin.prefs.notification': 'Notifications',
  'admin.prefs.message': 'Messages',
  'admin.prefs.audio': 'Audio and voice',
  'admin.prefs.video': 'Video',
  'admin.prefs.document': 'Documents',
  'admin.prefs.application': 'App',
  'admin.prefs.notice': 'Each change applies to the member on all their devices and is recorded in the audit log.',
  'admin.prefs.readOnly': 'read-only',
  'admin.prefs.saved': 'Preference saved',
  'admin.prefs.failed': 'The preference could not be saved',
  'admin.prefs.consent': 'Refused: the member hasn’t given the consent this option requires',
  'admin.prefs.reserved': 'Refused: your role can’t modify this member',
  'admin.prefs.invalid': 'Refused: invalid value',
  'admin.list.sort': 'Sort',
  'admin.list.order': 'Order',
  'admin.list.newest': 'Newest first',
  'admin.list.oldest': 'Oldest first',
  'admin.conv.manage': 'Manage',
  'admin.conv.role.admin': 'Administrator',
  'admin.conv.role.moderator': 'Moderator',
  'admin.conv.role.member': 'Member',
  'admin.conv.configure': 'Configure',
  'admin.convSettings.title': 'Configure conversation',
  'admin.convSettings.titleField': 'Title',
  'admin.convSettings.description': 'Description',
  'admin.convSettings.avatar': 'Image (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Who can write',
  'admin.convSettings.writeRole.everyone': 'Everyone',
  'admin.convSettings.writeRole.member': 'Members',
  'admin.convSettings.writeRole.moderator': 'Moderators and above',
  'admin.convSettings.writeRole.admin': 'Administrators and above',
  'admin.convSettings.writeRole.creator': 'Creator only',
  'admin.convSettings.announcement': 'Announcement channel',
  'admin.convSettings.slowMode': 'Slow mode (seconds)',
  'admin.convSettings.autoTranslate': 'Auto-translation',
  'admin.convSettings.archive': 'Archive',
  'admin.convSettings.restore': 'Restore',
  'admin.convSettings.close': 'Close to writing',
  'admin.convSettings.reopen': 'Reopen',
  'admin.convSettings.memberRole': 'This member\'s role',
  'admin.convSettings.remove': 'Remove from conversation',
  'admin.convSettings.reason': 'Reason (10 characters minimum)',
  'admin.convSettings.confirm': 'Confirm',
  'admin.convSettings.save': 'Save',
  'admin.convSettings.saved': 'Conversation updated',
  'admin.convSettings.removed': 'Member removed',
  'admin.convSettings.failed': 'Change refused',
  'admin.convSettings.creatorProtected': 'The creator cannot be demoted or removed',
  'admin.create.open': 'Create an account',
  'admin.create.title': 'New account',
  'admin.create.username': 'Username',
  'admin.create.firstName': 'First name',
  'admin.create.lastName': 'Last name',
  'admin.create.email': 'Email',
  'admin.create.password': 'Password',
  'admin.create.passwordHint': 'Long and hard to guess: a weak password is refused.',
  'admin.create.language': 'Interface language',
  'admin.create.emailVerified': 'I vouch for this email address',
  'admin.create.emailVerifiedOn': 'The account can sign in right away.',
  'admin.create.emailVerifiedOff': 'Without it, a code will be sent to this address at first sign-in.',
  'admin.create.submit': 'Create account',
  'admin.create.created': 'Account created',
  'admin.create.failed': 'Creation refused: {reason}',
  'admin.create.emailTaken': 'This address is already used by another account.',
  'admin.create.usernameTaken': 'This username is already taken.',
  'admin.create.missing': 'Fill in every field.',
  'admin.images.avatarOpen': 'Change photo',
  'admin.images.bannerOpen': 'Change banner',
  'admin.images.upload': 'Upload an image',
  'admin.images.uploading': 'Uploading…',
  'admin.images.remove': 'Remove',
  'admin.images.choose': 'Choose from their public posts',
  'admin.images.chooseHint': 'Only images they already published publicly are offered.',
  'admin.images.noCandidate': 'No public image to offer.',
  'admin.images.candidatesFailed': 'Their public images could not be loaded.',
  'admin.images.useCandidate': 'Use image {n} of {total}',
  'admin.images.current': 'Current image',
  'admin.images.saved': 'Image updated',
  'admin.images.removed': 'Image removed',
  'admin.images.failed': 'Image update failed',
  'admin.images.offline': 'Offline: try again once connected.',
  'admin.images.unreadable': 'This image could not be read.',
  'admin.section.saving': 'Saving…',
  'admin.contact.title': 'Contact',
  'admin.contact.phone': 'Phone',
  'admin.contact.verified': 'Verified',
  'admin.contact.unverified': 'Not verified',
  'admin.contact.resend': 'Resend verification',
  'admin.contact.resent': 'Verification sent',
  'admin.contact.resendFailed': 'The verification could not be sent',
  'admin.contact.markVerified': 'Mark as verified',
  'admin.contact.markUnverified': 'Remove verification',
  'admin.security.twoFactorHint': 'A code is asked at every sign-in.',
  'admin.security.sessionsOpen': 'View sessions',
  'admin.roleStatus.title': 'Role and status',
  'admin.identity.suggestions': 'Available usernames',
  'admin.identity.noLanguage': 'None',
  'admin.security.twoFactorNotEnrolled': 'The member must first pair an authenticator app.',
  'admin.quick.title': 'Quick actions',
  'admin.quick.activate': 'Activate the account',
  'admin.quick.activated': 'Account activated',
  'admin.quick.validateEmail': 'Validate the email',
  'admin.quick.validatePhone': 'Validate the phone',
  ...kitEn,
  ...dashboardEn,
  ...statistiquesEn,
  ...moderationEn,
  ...contenusEn,
  ...liensEn,
  ...diffusionsEn,
  ...classementSupervisionEn,
  ...auditReglagesEn,
  ...personnesEn,
  ...conversationsAgentEn,
} satisfies AdminInterfaceCatalog;

export default en;
