import type { ExportCardCatalog } from '@/lib/i18n-export-card-catalog';

const pt = {
  'export.card.title': 'Imagine',
  'export.card.popular': 'Populares',
  'export.card.random': 'Aleatório',
  'export.card.palette': 'Cores',
  'export.card.typeface': 'Tipografia',
  'export.card.link': 'Ligação',
  'export.card.typeface.rond': 'Redonda',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Pena',
  'export.card.typeface.affiche': 'Cartaz',
  'export.card.typeface.futur': 'Futurista',
  'export.card.typeface.machine': 'Máquina de escrever',
  'export.card.typeface.marqueur': 'Marcador',
  'export.card.typeface.systeme': 'Sistema',
  'export.card.link.orbite': 'Órbita',
  'export.card.link.filet': 'Filete',
  'export.card.link.guillemets': 'Aspas',
  'export.card.link.fleche': 'Seta',
  'export.card.link.bulles': 'Balões',
  'export.card.link.fil': 'Fio',
  'export.card.link.silence': 'Silêncio',
  'export.card.option.anonymizeQuoted': 'Anonimizar a mensagem citada',
  'export.card.option.anonymizeReply': 'Anonimizar a resposta',
  'export.card.anonymous': 'Anónimo',
  'export.card.preview': 'Pré-visualização da imagem',
  'export.card.rendering': 'A preparar a imagem…',
  'export.card.save': 'Guardar',
  'export.card.share': 'Partilhar',
  'export.card.language': 'Idioma da mensagem',
  'export.card.language.asRead': 'Como eu leio',
  'export.card.truncated': 'Mensagem longa: o final é cortado na imagem.',
  'export.announce.gallery': 'Imagem guardada na galeria',
  'export.announce.shared': 'Imagem pronta',
  'export.announce.cancelled': 'Exportação cancelada',
  'export.announce.expired': 'Toque novamente para guardar',
  'export.announce.failed': 'Não foi possível criar a imagem',
  'export.announce.unavailable': 'Este dispositivo não consegue guardar a imagem',
  'export.card.options': 'Mostrar',
  'export.card.option.title': 'Título da conversa',
  'export.card.option.authors': 'Nomes dos autores',
  'export.card.option.date': 'Data',
  'export.card.default.save': 'Usar como formato predefinido',
  'export.card.default.current': 'Formato predefinido',
  'export.announce.defaultSaved': 'Formato predefinido guardado',
  'export.card.tab.styles': 'Estilos',
  'export.card.tab.palette': 'Fundo',
  'export.card.tab.typeface': 'Fonte',
  'export.card.tab.link': 'Ligação',
  'export.card.tab.details': 'Detalhes',
  'export.card.tab.language': 'Idioma',
  'export.card.part.header': 'Cabeçalho',
  'export.card.part.quote': 'Citação',
  'export.card.part.link': 'Ligação',
  'export.card.part.reply': 'Resposta',
  'export.card.part.background': 'Fundo',
  'export.card.hint': 'Toque numa parte do cartão para a ajustar',
  'export.card.gallery.open': 'Ver tudo',
  'export.card.gallery.title': 'Todos os estilos',
  'export.card.gallery.count': '{count} estilos',
  'export.card.gallery.close': 'Fechar a galeria',
  'export.card.gallery.search': 'Procurar um estilo',
  'export.card.gallery.placeholder': 'Pena, escuro, bolhas…',
  'export.card.gallery.empty': 'Nenhum estilo tem esse nome. Experimente uma cor, uma fonte ou «escuro».',
  'export.card.tone.all': 'Todos',
  'export.card.tone.dark': 'Escuro',
  'export.card.tone.light': 'Claro',
  'export.card.typeface.pairs': 'A fonte veste a citação e a resposta',
  'export.card.tab.frame': 'Moldura',
  'export.card.tab.media': 'Mídia',
  'export.card.part.media': 'Mídia',
  'export.card.aspect': 'Formato da imagem',
  'export.card.aspect.auto': 'Ajustado',
  'export.card.aspect.story': 'Story 9:16',
  'export.card.aspect.portrait': 'Retrato 4:5',
  'export.card.aspect.square': 'Quadrado 1:1',
  'export.card.aspect.landscape': 'Paisagem 16:9',
  'export.card.header': 'Título e data',
  'export.card.header.horizontal': 'Em linha',
  'export.card.header.letters': 'Letra a letra',
  'export.card.header.up': 'Para cima',
  'export.card.header.down': 'Para baixo',
  'export.card.authorsAt': 'Nomes',
  'export.card.authorsAt.top': 'Acima da mensagem',
  'export.card.authorsAt.end': 'No fim da mensagem',
  'export.card.tilt': 'Rotação da mensagem',
  'export.card.tilt.none': 'Direito',
  'export.card.tilt.left': 'Inclinado à esquerda',
  'export.card.tilt.right': 'Inclinado à direita',
  'export.card.option.times': 'Horas das mensagens',
  'export.card.option.pseudonyms': 'Nome de utilizador em vez do nome exibido',
  'export.card.anonymity': 'Anonimato',
  'export.card.media.style': 'Disposição das imagens',
  'export.card.media.mosaique': 'Mosaico',
  'export.card.media.pleine': 'Largura total',
  'export.card.media.bande': 'Faixa',
  'export.card.audio.style': 'Representação do áudio',
  'export.card.audio.onde': 'Onda',
  'export.card.audio.spectre': 'Espectro',
  'export.card.audio.pastille': 'Pastilha',
  'export.card.audio.etiquette': 'Etiqueta',
  'export.card.media.loading': 'A carregar a mídia…',
  'export.card.output': 'Guardar como',
  'export.card.output.image': 'Imagem',
  'export.card.output.gif': 'GIF',
  'export.card.output.video': 'Vídeo',
  'export.card.motion.video': 'A criar o vídeo…',
  'export.card.motion.gif': 'A criar o GIF…',
  'export.announce.motionUnavailable': 'Este navegador não consegue criar esta animação',
  'export.announce.galleryMotion': 'Guardado na galeria',
  'export.announce.sharedMotion': 'Pronto a partilhar',
} satisfies ExportCardCatalog;

export default pt;
