import type { InviteCatalog } from '@/lib/i18n-invite-catalog';

const de = {
  'invite.brand': 'Meeshy',
  'invite.loading': 'Einladung wird geöffnet…',
  'invite.inviter.named': '{name} lädt dich ein',
  'invite.inviter.unnamed': 'Du bist eingeladen, beizutreten',
  'invite.inviter.message': 'Nachricht von {name}',
  'invite.group.fallbackTitle': 'Eine Meeshy-Unterhaltung',
  'invite.group.created': 'erstellt am {date}',
  'invite.group.logo': 'Logo von {name}',
  'invite.kind.direct': 'Private Unterhaltung',
  'invite.kind.group': 'Gruppe',
  'invite.kind.public': 'Öffentliche Unterhaltung',
  'invite.kind.global': 'Offen für alle',
  'invite.kind.broadcast': 'Broadcast-Kanal',
  'invite.link.label': 'Link zur Unterhaltung',
  'invite.link.copy': 'Kopieren',
  'invite.link.copied': 'Kopiert',
  'invite.link.reshare': 'Erneut teilen',
  'invite.announce.copied': 'Link kopiert.',
  'invite.announce.copyFailed': 'Der Link kann hier nicht kopiert werden.',
  'invite.announce.shareUnavailable': 'Teilen ist hier nicht verfügbar.',
  'invite.share.text': 'Tritt {name} auf Meeshy bei — alle schreiben in ihrer eigenen Sprache.',
  'invite.stats.people.one': 'Person',
  'invite.stats.people.other': 'Personen',
  'invite.stats.languages.one': 'gesprochene Sprache',
  'invite.stats.languages.other': 'gesprochene Sprachen',
  'invite.stats.spoken': 'Hier wird gesprochen',
  'invite.stats.share': '{language} {percent}',
  'invite.rights.title': 'Ohne Konto kannst du',
  'invite.rights.messages': 'Nachrichten schreiben',
  'invite.rights.images': 'Bilder senden',
  'invite.rights.files': 'Dateien senden',
  'invite.rights.history': 'Nachrichten von vor deinem Beitritt sehen',
  'invite.rights.granted': 'erlaubt',
  'invite.rights.denied': 'nicht erlaubt',
  'invite.asked.label': 'Du wirst gefragt nach:',
  'invite.asked.nickname': 'einem Vornamen',
  'invite.asked.email': 'einer E-Mail-Adresse',
  'invite.asked.birthday': 'deinem Geburtsdatum',
  'invite.asked.nothing': 'nichts außer deiner Sprache',
  'invite.languages.label': 'Akzeptierte Sprachen:',
  'invite.languages.all': 'alle',
  'invite.validity.label': 'Link gültig',
  'invite.validity.days.one': 'noch {count} Tag',
  'invite.validity.days.other': 'noch {count} Tage',
  'invite.validity.today': 'bis heute',
  'invite.validity.forever': 'ohne zeitliche Begrenzung',
  'invite.places.unlimited': 'unbegrenzte Plätze',
  'invite.places.one': 'noch {count} Platz frei',
  'invite.places.other': 'noch {count} Plätze frei',
  'invite.join.title': '{name} beitreten',
  'invite.join.account': 'Mit meinem Konto beitreten',
  'invite.join.joining': 'Unterhaltung wird betreten…',
  'invite.join.joined': 'Du bist der Unterhaltung beigetreten. Verlauf wird geöffnet…',
  'invite.join.offline': 'Offline — der Beitritt wartet, bis das Netz zurück ist.',
  'invite.guest.continue': 'Ohne Konto fortfahren',
  'invite.guest.nickname': 'Dein Vorname',
  'invite.guest.nickname.optional': 'Dein Vorname (optional)',
  'invite.guest.nickname.placeholder': 'Wie sollen wir dich nennen?',
  'invite.guest.nickname.placeholder.optional': 'Leer lassen für einen generierten Spitznamen',
  'invite.guest.language': 'Deine Sprache',
  'invite.guest.email': 'Deine E-Mail',
  'invite.guest.email.placeholder': 'du@beispiel.de',
  'invite.guest.birthday': 'Dein Geburtsdatum',
  'invite.exits.separator': 'oder mit deinem Konto',
  'invite.exits.signIn': 'Anmelden',
  'invite.exits.signUp': 'Konto erstellen',
  'invite.exits.accountRequired': 'Für diese Unterhaltung ist ein Meeshy-Konto nötig.',
  'invite.refusal.not-found': 'Diese Einladung wurde nicht gefunden. Der Link ist vielleicht unvollständig.',
  'invite.refusal.revoked': 'Dieser Link wurde von der Person deaktiviert, die ihn geteilt hat.',
  'invite.refusal.expired': 'Dieser Link ist abgelaufen oder nicht mehr aktiv.',
  'invite.refusal.closed': 'Diese Unterhaltung ist beendet: Ein Beitritt ist nicht mehr möglich.',
  'invite.refusal.full': 'Dieser Link hat seine Teilnehmergrenze erreicht.',
  'invite.refusal.language': 'Diese Einladung akzeptiert deine Sprache nicht.',
  'invite.refusal.banned': 'Du kannst dieser Unterhaltung nicht mehr beitreten.',
  'invite.refusal.region': 'Diese Einladung ist aus deinem Netzwerk nicht erreichbar.',
  'invite.refusal.account-required': 'Für den Beitritt zu dieser Unterhaltung ist ein Meeshy-Konto nötig.',
  'invite.refusal.session-expired': 'Deine Sitzung ist abgelaufen. Melde dich erneut an, um beizutreten.',
  'invite.refusal.rate-limited': 'Zu viele Versuche. Versuch es gleich noch einmal.',
  'invite.refusal.offline': 'Du bist offline. Die Einladung erscheint, sobald das Netz zurück ist.',
  'invite.refusal.unavailable': 'Die Einladung ist gerade nicht verfügbar.',
  'invite.missing.nickname': 'Wähle einen Vornamen für diese Unterhaltung.',
  'invite.missing.email': 'Dieser Link verlangt eine gültige E-Mail-Adresse.',
  'invite.missing.birthday': 'Dieser Link verlangt dein Geburtsdatum.',
  'invite.missing.language': 'Wähle eine der Sprachen, die dieser Link akzeptiert.',
  'invite.refused.nickname': 'Dieser Vorname ist in dieser Unterhaltung schon vergeben.',
  'invite.refused.email': 'Diese E-Mail-Adresse wurde abgelehnt.',
  'invite.refused.birthday': 'Dieses Geburtsdatum wurde abgelehnt.',
  'invite.refused.language': 'Diese Einladung akzeptiert diese Sprache nicht.',
  'invite.refused.none': 'Eine angeforderte Angabe fehlt oder wurde abgelehnt.',
  'invite.refused.taken': 'Dieser Vorname ist vergeben — „{suggestion}“ ist frei.',
  'invite.retry': 'Erneut versuchen',
  'invite.home': 'Zurück zur Startseite',

  'linkDetail.title': 'Einladungslink',
  'linkDetail.breadcrumb': 'Brotkrümelnavigation',
  'linkDetail.breadcrumb.links': 'Links',
  'linkDetail.breadcrumb.share': 'Unterhaltungslinks',
  'linkDetail.card.created': 'Link erstellt am {date}',
  'linkDetail.card.share': 'Teilen',
  'linkDetail.card.copy': 'Link kopieren',
  'linkDetail.card.copied': 'Link kopiert',
  'linkDetail.stats.title': 'Statistiken',
  'linkDetail.stats.visits': 'Besuche',
  'linkDetail.stats.arrivals': 'Beitritte',
  'linkDetail.stats.anonymous': 'Ohne Konto',
  'linkDetail.stats.unknown': 'noch nicht gemessen',
  'linkDetail.stats.unavailable': 'Die Statistiken dieses Links sind noch nicht verfügbar.',
  'linkDetail.languages.title': 'Sprachen der Neuen',
  'linkDetail.languages.empty': 'Noch keine Beitritte.',
  'linkDetail.recent.title': 'Kürzlich beigetreten',
  'linkDetail.recent.anonymous': 'ohne Konto',
  'linkDetail.recent.empty': 'Über diesen Link ist noch niemand beigetreten.',
  'linkDetail.config.title': 'Konfiguration',
  'linkDetail.config.edit': 'Bearbeiten',
  'linkDetail.config.rights': 'Rechte der Gäste ohne Konto',
  'linkDetail.config.entry': 'Beitrittsbedingungen',
  'linkDetail.config.account': 'Meeshy-Konto',
  'linkDetail.config.account.required': 'Erforderlich',
  'linkDetail.config.account.optional': 'Optional',
  'linkDetail.config.asked': 'Beim Beitritt abgefragt',
  'linkDetail.config.asked.nickname': 'Vorname',
  'linkDetail.config.asked.email': 'E-Mail',
  'linkDetail.config.asked.birthday': 'Geburtsdatum',
  'linkDetail.config.asked.none': 'Nichts',
  'linkDetail.config.limits': 'Grenzen',
  'linkDetail.config.uses': 'Nutzungen',
  'linkDetail.config.uses.value': '{count} / {max}',
  'linkDetail.config.unlimited': 'unbegrenzt',
  'linkDetail.config.concurrent': 'Gleichzeitig',
  'linkDetail.config.concurrent.value': 'max. {count}',
  'linkDetail.config.expires': 'Läuft ab',
  'linkDetail.config.expires.value': 'am {date}',
  'linkDetail.config.expires.never': 'Nie',
  'linkDetail.config.languages': 'Erlaubte Sprachen',
  'linkDetail.config.languages.all': 'Alle Sprachen',
  'linkDetail.config.pending': 'Die Konfiguration dieses Links wird geladen…',
  'linkDetail.rights.messages': 'Nachrichten schreiben',
  'linkDetail.rights.images': 'Bilder senden',
  'linkDetail.rights.files': 'Dateien senden',
  'linkDetail.rights.history': 'Verlauf sehen',
  'linkDetail.edit.title': 'Link bearbeiten',
  'linkDetail.edit.name': 'Name des Links (nur für dich sichtbar)',
  'linkDetail.edit.name.placeholder': 'Z. B. Team-Einladung',
  'linkDetail.edit.message': 'Einladungsnachricht (wird Gästen angezeigt)',
  'linkDetail.edit.message.placeholder': 'Sag in einem Satz, warum man beitreten sollte',
  'linkDetail.edit.limits': 'Grenzen',
  'linkDetail.edit.expiration': 'Ablauf',
  'linkDetail.edit.expiration.keep': 'Unverändert — {date}',
  'linkDetail.edit.maxUses': 'Nutzungen begrenzen',
  'linkDetail.edit.maxUses.count': 'Max. Nutzungen',
  'linkDetail.edit.maxConcurrent': 'Gleichzeitige Personen begrenzen',
  'linkDetail.edit.maxConcurrent.count': 'Personen gleichzeitig',
  'linkDetail.edit.number.invalid': 'Gib eine ganze Zahl zwischen 1 und {max} ein.',
  'linkDetail.edit.entry': 'Beitrittsbedingungen',
  'linkDetail.edit.rights': 'Rechte der Gäste ohne Konto',
  'linkDetail.edit.languages': 'Erlaubte Sprachen',
  'linkDetail.edit.languages.all': 'Alle Sprachen',
  'linkDetail.edit.languages.hint': 'Deaktiviere „Alle Sprachen“, um auszuwählen.',
  'linkDetail.edit.languages.invalid': 'Wähle mindestens eine Sprache.',
  'linkDetail.edit.save': 'Speichern',
  'linkDetail.edit.saving': 'Wird gespeichert…',
  'linkDetail.edit.unchanged': 'Keine Änderungen zu speichern.',
  'linkDetail.edit.delete': 'Löschen',
  'linkDetail.delete.title': 'Diesen Link löschen?',
  'linkDetail.delete.body': 'Der Link funktioniert dann nicht mehr, und Gäste ohne Konto, die über ihn beigetreten sind, verlieren den Zugang.',
  'linkDetail.delete.confirm': 'Link löschen',
  'linkDetail.delete.cancel': 'Abbrechen',
  'linkDetail.announce.saved': 'Änderungen gespeichert.',
  'linkDetail.announce.saveFailed': 'Die Änderungen wurden nicht gespeichert.',
  'linkDetail.announce.deleted': 'Link gelöscht.',
  'linkDetail.announce.deleteFailed': 'Der Link wurde nicht gelöscht.',
  'linkDetail.announce.offline': 'Offline: Es wurde nichts gesendet.',
} satisfies InviteCatalog;

export default de;
