import type { ContactCardCatalogSlice } from './catalog-fr-contact-card';

/** La carte de visite partagée (#8101) — voir `catalog-fr-contact-card.ts`. */
const deContactCard = {
  'contactCard.a11y.card': 'Visitenkarte: {name}',
  'contactCard.open': 'Alle Details zu {name} anzeigen',
  'contactCard.loading': 'Visitenkarte wird gelesen…',
  'contactCard.unreadable': 'Unlesbare Visitenkarte',
  'contactCard.failed': 'Die Visitenkarte konnte nicht gelesen werden',
  'contactCard.retry': 'Erneut versuchen',
  'contactCard.download': 'Karte herunterladen',
  'contactCard.onMeeshy': 'Auf Meeshy',
  'contactCard.connect': 'Verbinden',
  'contactCard.write': 'Schreiben',
  'contactCard.state.self': 'Das bist du',
  'contactCard.state.requestSent': 'Anfrage gesendet',
  'contactCard.state.requestReceived': 'Hat dir eine Anfrage gesendet',
  'contactCard.sheet.title': 'Visitenkarte',
  'contactCard.close': 'Schließen',
  'contactCard.copy': 'Kopieren: {field}',
  'contactCard.copied': 'In die Zwischenablage kopiert',
  'contactCard.copyFailed': 'Kopieren nicht möglich',
  'contactCard.copyHint': 'Lange drücken oder rechtsklicken, um ein Feld zu kopieren',
  'contactCard.avatar': 'Foto von {name}',
  'contactCard.banner': 'Banner von {name}',
  'contactCard.field.phone': 'Telefon',
  'contactCard.field.email': 'E-Mail',
  'contactCard.field.url': 'Website',
  'contactCard.field.address': 'Adresse',
  'contactCard.field.birthday': 'Geburtstag',
  'contactCard.field.note': 'Notiz',
  'contactCard.field.organization': 'Organisation',
  'contactCard.field.title': 'Position',
  'contactCard.label.mobile': 'mobil',
  'contactCard.label.home': 'privat',
  'contactCard.label.work': 'geschäftlich',
  'contactCard.label.main': 'Hauptnummer',
  'contactCard.label.iphone': 'iPhone',
  'contactCard.label.fax': 'Fax',
  'contactCard.label.pager': 'Pager',
  'contactCard.label.other': 'sonstige',
} satisfies ContactCardCatalogSlice;

export default deContactCard;
