import type { InviteCatalog } from '@/lib/i18n-invite-catalog';

const ar = {
  'invite.brand': 'Meeshy',
  'invite.loading': 'جارٍ فتح الدعوة…',
  'invite.inviter.named': 'يدعوك {name}',
  'invite.inviter.unnamed': 'أنت مدعو للانضمام',
  'invite.inviter.message': 'رسالة من {name}',
  'invite.group.fallbackTitle': 'محادثة على Meeshy',
  'invite.group.created': 'أُنشئت في {date}',
  'invite.group.logo': 'شعار {name}',
  'invite.kind.direct': 'محادثة خاصة',
  'invite.kind.group': 'مجموعة',
  'invite.kind.public': 'محادثة عامة',
  'invite.kind.global': 'مفتوحة للجميع',
  'invite.kind.broadcast': 'قناة بث',
  'invite.link.label': 'رابط المحادثة',
  'invite.link.copy': 'نسخ',
  'invite.link.copied': 'تم النسخ',
  'invite.link.reshare': 'إعادة المشاركة',
  'invite.announce.copied': 'تم نسخ الرابط.',
  'invite.announce.copyFailed': 'تعذّر نسخ الرابط هنا.',
  'invite.announce.shareUnavailable': 'المشاركة غير متاحة هنا.',
  'invite.share.text': 'انضم إلى {name} على Meeshy — كلٌّ يكتب بلغته.',
  'invite.stats.people.one': 'شخص',
  'invite.stats.people.other': 'أشخاص',
  'invite.stats.languages.one': 'لغة محكية',
  'invite.stats.languages.other': 'لغات محكية',
  'invite.stats.spoken': 'اللغات المحكية هنا',
  'invite.stats.share': '{language} {percent}',
  'invite.rights.title': 'بدون حساب، يمكنك',
  'invite.rights.messages': 'كتابة الرسائل',
  'invite.rights.images': 'إرسال الصور',
  'invite.rights.files': 'إرسال الملفات',
  'invite.rights.history': 'رؤية الرسائل السابقة لانضمامك',
  'invite.rights.granted': 'مسموح',
  'invite.rights.denied': 'غير مسموح',
  'invite.asked.label': 'سيُطلب منك:',
  'invite.asked.nickname': 'اسم أول',
  'invite.asked.email': 'عنوان بريد إلكتروني',
  'invite.asked.birthday': 'تاريخ ميلادك',
  'invite.asked.nothing': 'لا شيء سوى لغتك',
  'invite.languages.label': 'اللغات المقبولة:',
  'invite.languages.all': 'الكل',
  'invite.validity.label': 'الرابط صالح',
  'invite.validity.days.one': 'لمدة {count} يوم إضافي',
  'invite.validity.days.other': 'لمدة {count} أيام إضافية',
  'invite.validity.today': 'حتى اليوم',
  'invite.validity.forever': 'بلا حدّ زمني',
  'invite.places.unlimited': 'أماكن غير محدودة',
  'invite.places.one': 'يتبقى {count} مكان',
  'invite.places.other': 'تتبقى {count} أماكن',
  'invite.join.title': 'انضم إلى {name}',
  'invite.join.account': 'الانضمام بحسابي',
  'invite.join.joining': 'جارٍ الدخول إلى المحادثة…',
  'invite.join.joined': 'انضممت إلى المحادثة. جارٍ فتح السلسلة…',
  'invite.join.offline': 'غير متصل — سينتظر الانضمام عودة الشبكة.',
  'invite.guest.continue': 'المتابعة بدون حساب',
  'invite.guest.nickname': 'اسمك الأول',
  'invite.guest.nickname.optional': 'اسمك الأول (اختياري)',
  'invite.guest.nickname.placeholder': 'بماذا نناديك؟',
  'invite.guest.nickname.placeholder.optional': 'اتركه فارغًا لاسم مستعار مُولَّد',
  'invite.guest.language': 'لغتك',
  'invite.guest.email': 'بريدك الإلكتروني',
  'invite.guest.email.placeholder': 'you@example.com',
  'invite.guest.birthday': 'تاريخ ميلادك',
  'invite.exits.separator': 'أو بحسابك',
  'invite.exits.signIn': 'تسجيل الدخول',
  'invite.exits.signUp': 'إنشاء حساب',
  'invite.exits.accountRequired': 'تتطلب هذه المحادثة حسابًا على Meeshy.',
  'invite.refusal.not-found': 'لم يتم العثور على هذه الدعوة. ربما الرابط غير مكتمل.',
  'invite.refusal.revoked': 'عطّل الشخص الذي شارك هذا الرابط الرابطَ.',
  'invite.refusal.expired': 'انتهت صلاحية هذا الرابط أو لم يعد نشطًا.',
  'invite.refusal.closed': 'انتهت هذه المحادثة: لم يعد بالإمكان الانضمام إليها.',
  'invite.refusal.full': 'بلغ هذا الرابط الحدّ الأقصى للمشاركين.',
  'invite.refusal.language': 'هذه الدعوة لا تقبل لغتك.',
  'invite.refusal.banned': 'لم يعد بإمكانك الانضمام إلى هذه المحادثة.',
  'invite.refusal.region': 'هذه الدعوة غير متاحة من شبكتك.',
  'invite.refusal.account-required': 'يلزم حساب على Meeshy للانضمام إلى هذه المحادثة.',
  'invite.refusal.session-expired': 'انتهت جلستك. سجّل الدخول مجددًا للانضمام.',
  'invite.refusal.rate-limited': 'محاولات كثيرة جدًا. أعد المحاولة بعد قليل.',
  'invite.refusal.offline': 'أنت غير متصل. ستظهر الدعوة عند عودة الشبكة.',
  'invite.refusal.unavailable': 'الدعوة غير متاحة حاليًا.',
  'invite.missing.nickname': 'اختر اسمًا أول لهذه المحادثة.',
  'invite.missing.email': 'يتطلب هذا الرابط عنوان بريد إلكتروني صالحًا.',
  'invite.missing.birthday': 'يتطلب هذا الرابط تاريخ ميلادك.',
  'invite.missing.language': 'اختر إحدى اللغات التي يقبلها هذا الرابط.',
  'invite.refused.nickname': 'هذا الاسم مستخدم بالفعل في هذه المحادثة.',
  'invite.refused.email': 'تم رفض عنوان البريد الإلكتروني هذا.',
  'invite.refused.birthday': 'تم رفض تاريخ الميلاد هذا.',
  'invite.refused.language': 'هذه الدعوة لا تقبل هذه اللغة.',
  'invite.refused.none': 'معلومة مطلوبة مفقودة أو مرفوضة.',
  'invite.refused.taken': 'هذا الاسم مستخدم — «{suggestion}» متاح.',
  'invite.retry': 'إعادة المحاولة',
  'invite.home': 'العودة إلى الرئيسية',

  'linkDetail.title': 'رابط الدعوة',
  'linkDetail.breadcrumb': 'مسار التنقل',
  'linkDetail.breadcrumb.links': 'الروابط',
  'linkDetail.breadcrumb.share': 'روابط المحادثات',
  'linkDetail.card.created': 'أُنشئ الرابط في {date}',
  'linkDetail.card.share': 'مشاركة',
  'linkDetail.card.copy': 'نسخ الرابط',
  'linkDetail.card.copied': 'تم نسخ الرابط',
  'linkDetail.stats.title': 'الإحصاءات',
  'linkDetail.stats.visits': 'الزيارات',
  'linkDetail.stats.arrivals': 'المنضمّون',
  'linkDetail.stats.anonymous': 'بدون حساب',
  'linkDetail.stats.unknown': 'لم يُقَس بعد',
  'linkDetail.stats.unavailable': 'إحصاءات هذا الرابط غير متاحة بعد.',
  'linkDetail.languages.title': 'لغات المنضمّين',
  'linkDetail.languages.empty': 'لا منضمّين حتى الآن.',
  'linkDetail.recent.title': 'انضموا مؤخرًا',
  'linkDetail.recent.anonymous': 'بدون حساب',
  'linkDetail.recent.empty': 'لم ينضم أحد عبر هذا الرابط بعد.',
  'linkDetail.config.title': 'الإعدادات',
  'linkDetail.config.edit': 'تعديل',
  'linkDetail.config.rights': 'صلاحيات الضيوف بدون حساب',
  'linkDetail.config.entry': 'شروط الدخول',
  'linkDetail.config.account': 'حساب Meeshy',
  'linkDetail.config.account.required': 'إلزامي',
  'linkDetail.config.account.optional': 'اختياري',
  'linkDetail.config.asked': 'يُطلب عند الانضمام',
  'linkDetail.config.asked.nickname': 'الاسم الأول',
  'linkDetail.config.asked.email': 'البريد الإلكتروني',
  'linkDetail.config.asked.birthday': 'تاريخ الميلاد',
  'linkDetail.config.asked.none': 'لا شيء',
  'linkDetail.config.limits': 'الحدود',
  'linkDetail.config.uses': 'مرات الاستخدام',
  'linkDetail.config.uses.value': '⁦{count} / {max}⁩',
  'linkDetail.config.unlimited': 'غير محدود',
  'linkDetail.config.concurrent': 'في الوقت نفسه',
  'linkDetail.config.concurrent.value': '{count} كحدّ أقصى',
  'linkDetail.config.expires': 'ينتهي',
  'linkDetail.config.expires.value': 'في {date}',
  'linkDetail.config.expires.never': 'أبدًا',
  'linkDetail.config.languages': 'اللغات المسموح بها',
  'linkDetail.config.languages.all': 'كل اللغات',
  'linkDetail.config.pending': 'جارٍ تحميل إعدادات هذا الرابط…',
  'linkDetail.rights.messages': 'كتابة الرسائل',
  'linkDetail.rights.images': 'إرسال الصور',
  'linkDetail.rights.files': 'إرسال الملفات',
  'linkDetail.rights.history': 'رؤية السجل',
  'linkDetail.edit.title': 'تعديل الرابط',
  'linkDetail.edit.name': 'اسم الرابط (مرئي لك وحدك)',
  'linkDetail.edit.name.placeholder': 'مثلًا: دعوة الفريق',
  'linkDetail.edit.message': 'رسالة الدعوة (تظهر للضيوف)',
  'linkDetail.edit.message.placeholder': 'قل في جملة واحدة لماذا ينضمون',
  'linkDetail.edit.limits': 'الحدود',
  'linkDetail.edit.expiration': 'انتهاء الصلاحية',
  'linkDetail.edit.expiration.keep': 'دون تغيير — {date}',
  'linkDetail.edit.maxUses': 'تحديد مرات الاستخدام',
  'linkDetail.edit.maxUses.count': 'الحدّ الأقصى للاستخدام',
  'linkDetail.edit.maxConcurrent': 'تحديد عدد الأشخاص في الوقت نفسه',
  'linkDetail.edit.maxConcurrent.count': 'الأشخاص في الوقت نفسه',
  'linkDetail.edit.number.invalid': 'أدخل عددًا صحيحًا بين 1 و{max}.',
  'linkDetail.edit.entry': 'شروط الدخول',
  'linkDetail.edit.rights': 'صلاحيات الضيوف بدون حساب',
  'linkDetail.edit.languages': 'اللغات المسموح بها',
  'linkDetail.edit.languages.all': 'كل اللغات',
  'linkDetail.edit.languages.hint': 'عطّل «كل اللغات» لتختار.',
  'linkDetail.edit.languages.invalid': 'اختر لغة واحدة على الأقل.',
  'linkDetail.edit.save': 'حفظ',
  'linkDetail.edit.saving': 'جارٍ الحفظ…',
  'linkDetail.edit.unchanged': 'لا توجد تغييرات لحفظها.',
  'linkDetail.edit.delete': 'حذف',
  'linkDetail.delete.title': 'حذف هذا الرابط؟',
  'linkDetail.delete.body': 'سيتوقف الرابط عن العمل، وسيفقد الضيوف بدون حساب الذين دخلوا عبره إمكانية الوصول.',
  'linkDetail.delete.confirm': 'حذف الرابط',
  'linkDetail.delete.cancel': 'إلغاء',
  'linkDetail.announce.saved': 'تم حفظ التغييرات.',
  'linkDetail.announce.saveFailed': 'لم يتم حفظ التغييرات.',
  'linkDetail.announce.deleted': 'تم حذف الرابط.',
  'linkDetail.announce.deleteFailed': 'لم يتم حذف الرابط.',
  'linkDetail.announce.offline': 'غير متصل: لم يُرسَل شيء.',
} satisfies InviteCatalog;

export default ar;
