import type { OnboardingCatalog } from '@/lib/i18n-onboarding-catalog';

const es = {
  'onboarding.title': 'Bienvenido a Meeshy',
  'onboarding.skipAll': 'Saltar todo',
  'onboarding.later': 'Más tarde',
  'onboarding.continue': 'Continuar',
  'onboarding.progress': 'Paso {current} de {total}',
  'onboarding.offline': 'Disponible cuando estés en línea',
  'onboarding.points.gauge': '{points} / {target} pts para tu nivel 1',
  'onboarding.points.level': '¡Nivel 1 alcanzado!',
  'onboarding.points.gained': '+{points}',
  'onboarding.points.announce': 'Ganas {points} puntos.',

  'onboarding.languages.title': 'Tu idioma, tu mundo',
  'onboarding.languages.body': 'Aquí cada uno escribe en su idioma. Tú lo lees todo en el tuyo.',
  'onboarding.languages.demo.from': 'Salut, ça va ?',
  'onboarding.languages.demo.fromCode': 'fr',
  'onboarding.languages.demo.to': 'Hola, ¿qué tal?',
  'onboarding.languages.primary': 'Tu idioma principal',
  'onboarding.languages.secondary': '¿Un segundo idioma? (opcional)',
  'onboarding.languages.change': 'Cambiar',
  'onboarding.languages.pick': 'Elige tu idioma principal',
  'onboarding.languages.confirm': 'Es mi idioma',
  'onboarding.languages.failed': 'Tu idioma no se guardó. Inténtalo de nuevo.',

  'onboarding.email.title': 'Confirma tu correo electrónico',
  'onboarding.email.body': 'Te espera un enlace en tu bandeja. Un toque y podrás publicar e invitar a tus amigos.',
  'onboarding.email.resend': 'Reenviar el enlace',
  'onboarding.email.sending': 'Enviando…',
  'onboarding.email.sent': 'Enlace enviado. Ábrelo y vuelve aquí.',
  'onboarding.email.failed': 'El enlace no se envió. Inténtalo de nuevo.',

  'onboarding.global.title': 'Saluda al mundo',
  'onboarding.global.body': 'Meeshy Global es el salón donde está todo el mundo. Suelta un saludo, sin presión.',
  'onboarding.global.field': 'Tu saludo, editable',
  'onboarding.global.shuffle': 'Otra idea',
  'onboarding.global.send': 'Enviar',
  'onboarding.global.sending': 'Enviando…',
  'onboarding.global.sent': '¡Saludo enviado!',
  'onboarding.global.failed': 'Tu saludo no se envió. Inténtalo de nuevo.',
  'onboarding.global.unavailable': 'Meeshy Global no está disponible por ahora.',
  'onboarding.global.badge': 'Insignia «Primer mensaje»',
  'onboarding.global.streak': 'Racha: 1 día 🔥',
  'onboarding.global.reward': '+{points} pts al enviar',
  'onboarding.global.template.1': '¡Hola a todos! Soy {name}, hablo {languages}. ¿Quién vive cerca de [[el mar]]?',
  'onboarding.global.template.2': '¡Hola! {name} por aquí 👋 Ahora mismo escucho [[rap]] sin parar. ¿Y vosotros?',
  'onboarding.global.template.3': '¡Buenas! Me llamo {name}. Mi plato favorito: [[la pasta]]. ¿Y el tuyo?',
  'onboarding.global.template.4': '¡Hola! {name}, recién llegado. ¡Busco gente a la que le guste [[el fútbol]]!',
  'onboarding.global.template.5': '¡Hey! Soy {name}. Mi pequeña alegría del día: [[los atardeceres]].',
  'onboarding.global.template.6': '¡Hola! {name} aquí, hablo {languages}. Me encantaría aprender [[francés]], ¿algún consejo?',
  'onboarding.global.template.7': 'Hola mundo 🌍 Soy {name}. Mi pasión del momento: [[la fotografía]]. ¿Quién más?',
  'onboarding.global.template.8': '¡Ey! {name} acaba de llegar. Donde vivo hoy hace [[mucho sol]]. ¿Y donde estáis?',

  'onboarding.story.title': 'Muéstrate',
  'onboarding.story.body': 'Los amigos llegan mostrando quién eres. Una foto, una frase: es una story y desaparece en 24 h.',
  'onboarding.story.create': 'Crear mi story',
  'onboarding.story.audience.public': 'Visible para todos. Puedes cambiarlo antes de publicar.',
  'onboarding.story.audience.friends': 'Visible para tus amigos. Puedes cambiarlo antes de publicar.',
  'onboarding.story.reward': '+{points} pts al publicar',
  'onboarding.story.done': '¡Story publicada!',
  'onboarding.story.verify': 'Para publicar tu story, confirma primero tu correo electrónico.',

  'onboarding.friends.title': 'Encuentra a tu gente',
  'onboarding.friends.body': 'Añade a 3 personas que se parezcan a ti. Cuando acepten, ganáis al menos\u00A0+{points} los dos.',
  'onboarding.friends.add': 'Añadir',
  'onboarding.friends.addNamed': 'Añadir a {name}',
  'onboarding.friends.added': 'Enviada',
  'onboarding.friends.speaks': 'Habla {languages}',
  'onboarding.friends.reward': 'Al menos\u00A0+{points} cada uno cuando acepte',
  'onboarding.friends.count': '{count} / 3 solicitudes',
  'onboarding.friends.empty': 'Nadie que proponerte por ahora. La pestaña Descubrir te mostrará gente pronto.',
  'onboarding.friends.failed': 'La solicitud no se envió. Inténtalo de nuevo.',

  'onboarding.notifications.title': 'Te avisamos cuando pase algo',
  'onboarding.notifications.body': 'Alguien va a responderte. ¿Quieres saberlo enseguida?',
  'onboarding.notifications.yes': 'Sí, avísame',
  'onboarding.notifications.no': 'Ahora no',

  'onboarding.recap.title': '¡Bien hecho!',
  'onboarding.recap.loading': 'Tu progreso está llegando…',
  'onboarding.recap.calm': 'Todo listo. Podrás hacerlo cuando quieras.',
  'onboarding.recap.points': '{points} pts',
  'onboarding.recap.level': 'Nivel {level}',
  'onboarding.recap.streak.one': 'Racha: {days} día',
  'onboarding.recap.streak.other': 'Racha: {days} días',
  'onboarding.recap.badges': 'Insignias: {count}',
  'onboarding.recap.friends': 'Solicitudes en camino: {count}',
  'onboarding.recap.tomorrow': 'Mañana tu racha puede llegar a {next}.',
  'onboarding.recap.explore': 'Seguir explorando',
  'onboarding.recap.done': 'Suficiente por hoy',
} satisfies OnboardingCatalog;

export default es;
