import type { LinkFamiliesCatalog } from '@/lib/i18n-link-families-catalog';

const pt = {
  'links.hub.tracking.title': 'Links de rastreamento',
  'links.hub.tracking.description': 'Acompanhe o desempenho dos seus links de indicação',
  'links.hub.tracking.create': 'Criar um link de rastreamento',
  'links.hub.community.title': 'Links de comunidade',
  'links.hub.community.description': 'Gerencie os links de convite para suas comunidades',
  'links.hub.affiliate.title': 'Links de indicação',
  'links.hub.affiliate.description': 'Convide sua rede para o Meeshy e acompanhe quem se cadastra',
  'links.hub.affiliate.create': 'Criar um link de indicação',

  'linkFamilies.delete': 'Excluir',
  'linkFamilies.cancel': 'Cancelar',
  'linkFamilies.noData': 'Nenhum dado',
  'linkFamilies.announce.deleted': 'Link excluído',
  'linkFamilies.announce.deleteFailed': 'Não foi possível excluir este link',
  'linkFamilies.create.inprogress': 'Criando…',
  'linkFamilies.create.error.offline': 'Sem conexão: o link não foi criado.',
  'linkFamilies.create.error.default': 'Não foi possível criar o link. Tente novamente.',
  'linkFamilies.tracking.stats.links': 'Links',
  'linkFamilies.tracking.stats.clicks': 'Cliques',
  'linkFamilies.tracking.stats.uniques': 'Únicos',
  'linkFamilies.tracking.stats.active': 'Ativos',
  'linkFamilies.tracking.clicks.one': '{count} clique',
  'linkFamilies.tracking.clicks.other': '{count} cliques',
  'linkFamilies.tracking.uniques.one': '{count} único',
  'linkFamilies.tracking.uniques.other': '{count} únicos',
  'linkFamilies.tracking.copy': 'Copiar o link de rastreamento',
  'linkFamilies.tracking.empty.title': 'Nenhum link de rastreamento',
  'linkFamilies.tracking.empty.subtitle': 'Crie um link para acompanhar seus cliques e suas campanhas',
  'linkFamilies.tracking.back': 'Voltar para os links de rastreamento',
  'linkFamilies.tracking.totalClicks': 'Total de cliques',
  'linkFamilies.tracking.uniqueClicks': 'Cliques únicos',
  'linkFamilies.tracking.lastClick': 'Último clique: {date}',
  'linkFamilies.tracking.noClick': 'Ainda não há cliques',
  'linkFamilies.tracking.countries': 'Países',
  'linkFamilies.tracking.devices': 'Dispositivos',
  'linkFamilies.tracking.browsers': 'Navegadores',
  'linkFamilies.tracking.social': 'Fontes sociais',
  'linkFamilies.tracking.recent': 'Últimos cliques',
  'linkFamilies.tracking.unknownPlace': 'Local desconhecido',
  'linkFamilies.tracking.redirect.confirmed': 'Redirecionamento confirmado',
  'linkFamilies.tracking.redirect.failed': 'Redirecionamento falhou',
  'linkFamilies.tracking.redirect.pending': 'Redirecionamento pendente',
  'linkFamilies.tracking.device.mobile': 'Celular',
  'linkFamilies.tracking.device.desktop': 'Computador',
  'linkFamilies.tracking.device.tablet': 'Tablet',
  'linkFamilies.tracking.utm': 'Configuração UTM',
  'linkFamilies.tracking.campaign': 'Campanha',
  'linkFamilies.tracking.source': 'Origem',
  'linkFamilies.tracking.medium': 'Mídia',
  'linkFamilies.tracking.destination': 'URL de destino',
  'linkFamilies.tracking.delete.title': 'Excluir este link de rastreamento?',
  'linkFamilies.tracking.delete.body': 'O link deixará de redirecionar e suas estatísticas serão perdidas.',
  'linkFamilies.tracking.create.title': 'Novo link de rastreamento',
  'linkFamilies.tracking.create.section.destination': 'Destino',
  'linkFamilies.tracking.create.url': 'URL de destino',
  'linkFamilies.tracking.create.url.placeholder': 'https://exemplo.com/pagina',
  'linkFamilies.tracking.create.url.invalid': 'Digite um endereço web válido.',
  'linkFamilies.tracking.create.name': 'Nome interno (opcional)',
  'linkFamilies.tracking.create.name.placeholder': 'ex.: Campanha de volta às aulas',
  'linkFamilies.tracking.create.name.invalid': 'No máximo 32 caracteres.',
  'linkFamilies.tracking.create.section.utm': 'Parâmetros UTM',
  'linkFamilies.tracking.create.section.utm.subtitle': 'Para saber de onde vêm seus cliques',
  'linkFamilies.tracking.create.campaign.placeholder': 'ex.: volta-as-aulas',
  'linkFamilies.tracking.create.source.placeholder': 'ex.: instagram',
  'linkFamilies.tracking.create.medium.placeholder': 'ex.: social',
  'linkFamilies.tracking.create.section.token': 'Token personalizado',
  'linkFamilies.tracking.create.token': 'Token (opcional)',
  'linkFamilies.tracking.create.token.placeholder': 'ex.: aulas26',
  'linkFamilies.tracking.create.token.help': 'Deixe vazio para um token aleatório.',
  'linkFamilies.tracking.create.token.invalid': 'De 5 a 50 caracteres: letras, dígitos, “-” ou “_”, sem hífen no início ou no fim.',
  'linkFamilies.tracking.create.token.taken': 'Este token já está em uso. Escolha outro.',
  'linkFamilies.tracking.create.preview': 'Seu link: {url}',
  'linkFamilies.tracking.create.button': 'Criar o link de rastreamento',
  'linkFamilies.affiliate.title': 'Indicações',
  'linkFamilies.affiliate.stats.links': 'Links',
  'linkFamilies.affiliate.stats.signups': 'Cadastrados',
  'linkFamilies.affiliate.stats.pending': 'Pendentes',
  'linkFamilies.affiliate.section.referrals': 'Meus indicados',
  'linkFamilies.affiliate.signups.one': '{count} cadastrado',
  'linkFamilies.affiliate.signups.other': '{count} cadastrados',
  'linkFamilies.affiliate.uses': '{used} de {max}',
  'linkFamilies.affiliate.empty.title': 'Nenhum link de indicação',
  'linkFamilies.affiliate.empty.subtitle': 'Crie um link para convidar seus amigos para o Meeshy',
  'linkFamilies.affiliate.referrals.empty': 'Ninguém se cadastrou com seus links ainda.',
  'linkFamilies.affiliate.referral.completed': 'Cadastrado',
  'linkFamilies.affiliate.referral.pending': 'Pendente',
  'linkFamilies.affiliate.referral.expired': 'Expirado',
  'linkFamilies.affiliate.copy': 'Copiar o link de indicação',
  'linkFamilies.affiliate.share': 'Compartilhar o link de indicação',
  'linkFamilies.affiliate.delete': 'Excluir o link de indicação',
  'linkFamilies.affiliate.delete.title': 'Excluir este link de indicação?',
  'linkFamilies.affiliate.delete.body': 'Ele não permitirá mais cadastros em seu nome. Seus indicados continuam sendo seus.',
  'linkFamilies.affiliate.create.title': 'Novo link de indicação',
  'linkFamilies.affiliate.create.name': 'Nome do link',
  'linkFamilies.affiliate.create.name.placeholder': 'ex.: Convite para amigos',
  'linkFamilies.affiliate.create.name.invalid': 'Dê um nome a este link (no máximo 100 caracteres).',
  'linkFamilies.affiliate.create.limit': 'Limitar os cadastros',
  'linkFamilies.affiliate.create.limit.caption': 'Depois disso, o link não cadastra mais ninguém',
  'linkFamilies.affiliate.create.maxUses': 'Número máximo de cadastros',
  'linkFamilies.affiliate.create.maxUses.invalid': 'Um número inteiro entre 1 e 100.000.',
  'linkFamilies.affiliate.create.button': 'Criar o link de indicação',
  'linkFamilies.community.stats.communities': 'Comunidades',
  'linkFamilies.community.stats.public': 'Públicas',
  'linkFamilies.community.stats.members': 'Membros',
  'linkFamilies.community.section': 'Minhas comunidades',
  'linkFamilies.community.role.admin': 'Administrador',
  'linkFamilies.community.role.moderator': 'Moderador',
  'linkFamilies.community.private': 'Privada',
  'linkFamilies.community.public': 'Pública',
  'linkFamilies.community.members.one': '{count} membro',
  'linkFamilies.community.members.other': '{count} membros',
  'linkFamilies.community.empty.title': 'Nenhuma comunidade administrada',
  'linkFamilies.community.empty.subtitle': 'As comunidades que você gerencia aparecerão aqui com seu link de compartilhamento',
  'linkFamilies.community.empty.create': 'Criar uma comunidade',
  'linkFamilies.community.back': 'Voltar para os links de comunidade',
  'linkFamilies.community.open': 'Abrir a comunidade',
  'linkFamilies.community.fullLink': 'Link completo',
  'linkFamilies.community.role': 'Seu papel',
  'linkFamilies.community.visibility': 'Visibilidade',
} satisfies LinkFamiliesCatalog;

export default pt;
