import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const esStudioChrome = {
  'story.studio.more': 'Más opciones',
  'story.studio.preview': 'Vista previa',
  'story.studio.preview.close': 'Cerrar la vista previa',
  'story.studio.page.remove.current': 'Eliminar esta escena',
  'story.studio.postText': 'Texto de la publicación',
  'story.studio.postText.placeholder': 'Escribe el texto de la publicación…',
  'story.studio.postText.done': 'Listo',
  'story.studio.tile.text': 'Texto',
  'story.studio.tile.time': 'Tiempo',
  'story.studio.rail.scene': 'Herramientas de la escena',
  'story.studio.timeline.unit': 's',
  'story.studio.tile.frame': 'Marco',
  'story.studio.undo': 'Deshacer',
  'story.studio.redo': 'Rehacer',
  'story.studio.frame': 'Marco',
  'story.studio.frame.media': 'El medio',
  'story.studio.frame.around': 'Alrededor del medio',
  'story.studio.frame.fit': 'Ajustar',
  'story.studio.frame.fill': 'Rellenar',
  'story.studio.frame.fit.hint': 'Entero, dentro del marco 9:16. No se recorta nada.',
  'story.studio.frame.fill.hint': 'Cubre todo el marco 9:16, recortando los bordes si hace falta.',
  'story.studio.backdrop.blur': 'Desenfoque',
  'story.studio.backdrop.black': 'Negro',
  'story.studio.backdrop.white': 'Blanco',
  'story.studio.backdrop.indigo': 'Índigo',
  'story.studio.backdrop.sand': 'Arena',
  'story.studio.animated': 'Animado',
  'story.studio.timeline': 'Línea de tiempo de la escena',
  'story.studio.timeline.play': 'Reproducir',
  'story.studio.timeline.pause': 'Pausa',
  'story.studio.timeline.empty': 'Escribe un texto o coloca una capa: cada objeto tiene su pista.',
  'story.studio.timeline.overlay': 'Capa',
  'story.studio.retouch.title': 'Editar la imagen',
  'story.studio.retouch.done': 'Listo',
  'story.studio.retouch.cancel': 'Descartar la edición',
  'composer.attachment.edit': 'Editar {name}',
  'story.studio.retouch.failed': 'No se pudo generar el contenido.',
  'story.studio.retouch.exporting': 'Exportando…',
  'story.studio.timeline.enter': 'Entra aquí',
  'story.studio.timeline.exit': 'Sale aquí',
  'story.studio.timeline.scrub': 'Mover el cabezal',
  'story.studio.timeline.track': 'Pista de {name}',
  'story.studio.timeline.earlier': 'Antes',
  'story.studio.timeline.later': 'Después',
  'story.studio.editor.filter': 'Filtro',
  'story.studio.filter.vintage': 'Vintage',
  'story.studio.filter.bw': 'B/N',
  'story.studio.filter.warm': 'Cálido',
  'story.studio.filter.cool': 'Frío',
  'story.studio.filter.dramatic': 'Dramático',
  'story.studio.filter.vivid': 'Vívido',
  'story.studio.filter.fade': 'Desvaído',
  'story.studio.filter.chrome': 'Cromo',
  'story.studio.object.menu': 'Acciones de {name}',
  'story.studio.object.raise': 'Subir',
  'story.studio.object.lower': 'Bajar',
  'story.studio.object.duplicate': 'Duplicar',
  'story.studio.object.edit': 'Editar',
  'story.studio.object.remove': 'Quitar',
  'story.studio.edit.done': 'OK',
  'story.studio.pose.left': 'Hacia la izquierda',
  'story.studio.pose.right': 'Hacia la derecha',
  'story.studio.pose.up': 'Hacia arriba',
  'story.studio.pose.down': 'Hacia abajo',
  'story.studio.objects.edit': 'Editar {name}',
  'story.studio.media.alt': 'Texto alternativo',
  'story.studio.media.alt.placeholder': 'Describe este contenido para los lectores de pantalla',
  'composer.reelOffer.title': '¿Publicar como reel?',
  'composer.reelOffer.body': 'Tu publicación tiene un solo vídeo: como reel, se abre a pantalla completa en Reels.',
  'composer.reelOffer.reel': 'Es un reel',
  'composer.reelOffer.post': 'Es una publicación',
  'story.studio.tool.close': 'Cerrar la herramienta',
  'story.studio.camera.quick.holdFilm': 'Mantener: grabar',
  'story.studio.camera.quick.videoOnly': 'Mantén para grabar',
  'story.studio.camera.quick.photo': 'Hacer una foto',
  'story.studio.camera.quick.video': 'Grabar',
  'story.studio.camera.title': 'Cámara',
  'story.studio.camera.close': 'Volver a la escena',
  'story.studio.camera.flip': 'Cambiar de cámara',
  'story.studio.camera.flash': 'Flash',
  'story.studio.camera.shutter.photo': 'Hacer una foto',
  'story.studio.camera.shutter.start': 'Empezar a grabar',
  'story.studio.camera.shutter.stop': 'Detener la grabación',
  'story.studio.camera.hint.photo': 'Tocar la pantalla: foto · mantenerla pulsada: vídeo',
  'story.studio.camera.hint.video': 'Toca para grabar · toca de nuevo para colocar',
  'story.studio.camera.unavailable': 'La cámara no está disponible. Permítela en los ajustes.',
  'story.studio.camera.openSettings': 'Ajustes',
  'story.studio.camera.recording': 'Grabando',
  'story.studio.scene.empty.title': 'Esta es tu escena',
  'story.studio.scene.empty.invite': 'Añade texto, un dibujo, una imagen o un vídeo, y hazla tuya.',
  'story.studio.camera.locked': 'Grabación bloqueada',
  'story.studio.camera.hint.holding': 'Desliza hasta el candado para bloquear · hacia arriba para hacer zoom',
  'story.studio.camera.hint.locked': 'Manos libres: desliza arriba o abajo para hacer zoom',
  'story.studio.camera.flash.intensity': 'Intensidad del flash',
  'story.studio.camera.flash.intensityValue': '{percent} %',
  'story.studio.camera.quick.tapArm': 'Tocar: abrir la cámara',
  'story.studio.camera.quick.tapAgain': 'Tocar de nuevo: foto',
  'story.studio.effect.column': 'Efectos de la escena',
  'story.studio.effect.opening': 'Efecto de apertura',
  'story.studio.effect.visual': 'Efecto visual',
  'story.studio.effect.close': 'Cerrar los efectos',
  'story.studio.effect.row.opening': 'Apertura',
  'story.studio.effect.row.closing': 'Cierre',
  'story.studio.transition.fade': 'Fundido',
  'story.studio.transition.zoom': 'Zoom',
  'story.studio.transition.slide': 'Deslizamiento',
  'story.studio.transition.reveal': 'Revelación',
  'story.studio.object.options': 'Opciones de {name}',
  'story.studio.object.deselect': 'Quitar la selección',
  'story.studio.object.setBackground': 'Poner de fondo',
  'story.studio.object.replaceBackground': 'Reemplazar el fondo',
  'story.studio.background.menu.title': 'Fondo de la escena',
  'story.studio.background.menu.edit': 'Editar el fondo',
  'story.studio.background.menu.retake': 'Volver a hacer una foto',
  'story.studio.background.menu.forward': 'Pasar a primer plano',
  'story.studio.background.menu.remove': 'Quitar el fondo',
  'story.studio.background.tools': 'Herramientas del fondo',
  'story.studio.background.tools.describe': 'Describir',
  'story.studio.background.tools.trim': 'Acortar',
  'story.studio.background.tools.sound': 'Sonido',
  'story.studio.background.tools.crop': 'Recortar',
  'story.studio.trim.start': 'Inicio',
  'story.studio.trim.end': 'Fin',
  'story.studio.trim.kept': '{kept} de {total}',
  'story.studio.crop.original': 'Original',
  'story.studio.crop.ratio': 'Proporción',
  'story.studio.audioTrim.title': 'Acortar el audio',
  'story.studio.background.tools.leave': 'Volver a la escena',
  'story.studio.reelSwitch.announcement': 'Cambiado a reel',
} satisfies StudioChromeCatalogSlice;

export default esStudioChrome;
