import type { OnboardingCatalog } from '@/lib/i18n-onboarding-catalog';

const en = {
  'onboarding.title': 'Welcome to Meeshy',
  'onboarding.skipAll': 'Skip all',
  'onboarding.later': 'Later',
  'onboarding.continue': 'Continue',
  'onboarding.progress': 'Step {current} of {total}',
  'onboarding.offline': 'Available when you’re online',
  'onboarding.points.gauge': '{points} / {target} pts to your level 1',
  'onboarding.points.level': 'Level 1 reached!',
  'onboarding.points.gained': '+{points}',
  'onboarding.points.announce': 'You earn {points} points.',

  'onboarding.languages.title': 'Your language, your world',
  'onboarding.languages.body': 'Everyone writes in their own language. You read it all in yours.',
  'onboarding.languages.demo.from': 'Salut, ça va ?',
  'onboarding.languages.demo.fromCode': 'fr',
  'onboarding.languages.demo.to': 'Hey, how’s it going?',
  'onboarding.languages.primary': 'Your main language',
  'onboarding.languages.secondary': 'A second language? (optional)',
  'onboarding.languages.change': 'Change',
  'onboarding.languages.pick': 'Choose your main language',
  'onboarding.languages.confirm': 'That’s my language',
  'onboarding.languages.failed': 'Your language wasn’t saved. Try again.',

  'onboarding.global.title': 'Say hi to the world',
  'onboarding.global.body': 'Meeshy Global is where everyone hangs out. Drop a hi, no pressure.',
  'onboarding.global.field': 'Your hi, editable',
  'onboarding.global.shuffle': 'Another idea',
  'onboarding.global.send': 'Send',
  'onboarding.global.sending': 'Sending…',
  'onboarding.global.sent': 'Hi sent!',
  'onboarding.global.failed': 'Your hi didn’t go through. Try again.',
  'onboarding.global.unavailable': 'Meeshy Global can’t be reached right now.',
  'onboarding.global.badge': '“First message” badge',
  'onboarding.global.streak': 'Streak: 1 day 🔥',
  'onboarding.global.reward': '+14 pts when sent',
  'onboarding.global.template.1': 'Hi everyone! I’m {name}, I speak {languages}. Who here lives near [[the sea]]?',
  'onboarding.global.template.2': 'Hello! {name} here 👋 Right now I’m listening to [[rap]] on repeat. You?',
  'onboarding.global.template.3': 'Hey! My name is {name}. My favourite dish: [[pasta]]. Yours?',
  'onboarding.global.template.4': 'Hi! {name}, just arrived. Looking for people who love [[football]]!',
  'onboarding.global.template.5': 'Hey! I’m {name}. My little joy of the day: [[sunsets]].',
  'onboarding.global.template.6': 'Hello! {name} here, I speak {languages}. I’d love to learn [[Spanish]], any tips?',
  'onboarding.global.template.7': 'Hi world 🌍 I’m {name}. My passion right now: [[photography]]. Who else?',
  'onboarding.global.template.8': 'Yo! {name} just got here. Where I live, it’s [[sunny]] today. How about you?',

  'onboarding.story.title': 'Show yourself',
  'onboarding.story.body': 'Friends come from showing who you are. One pic, one line: it’s a story, gone in 24 h.',
  'onboarding.story.create': 'Create my story',
  'onboarding.story.audience.public': 'Visible to everyone. You can change it before posting.',
  'onboarding.story.audience.friends': 'Visible to your friends. You can change it before posting.',
  'onboarding.story.reward': '+10 pts when posted',
  'onboarding.story.done': 'Story posted!',

  'onboarding.friends.title': 'Find your crew',
  'onboarding.friends.body': 'Add 3 people who vibe like you. When they accept, you both get\u00A0+7.',
  'onboarding.friends.add': 'Add',
  'onboarding.friends.addNamed': 'Add {name}',
  'onboarding.friends.added': 'Sent',
  'onboarding.friends.speaks': 'Speaks {languages}',
  'onboarding.friends.reward': '+7 each when they accept',
  'onboarding.friends.count': '{count} / 3 requests',
  'onboarding.friends.empty': 'Nobody to suggest just yet. The Discover tab will show you people soon.',
  'onboarding.friends.failed': 'The request didn’t go through. Try again.',

  'onboarding.notifications.title': 'We’ll tell you when things happen',
  'onboarding.notifications.body': 'Someone’s about to reply. Want to know right away?',
  'onboarding.notifications.yes': 'Yes, let me know',
  'onboarding.notifications.no': 'Not now',

  'onboarding.recap.title': 'Nice one!',
  'onboarding.recap.calm': 'You’re all set. You can do it whenever you like.',
  'onboarding.recap.points': '{points} pts',
  'onboarding.recap.level': 'Level {level}',
  'onboarding.recap.streak.one': 'Streak: {days} day',
  'onboarding.recap.streak.other': 'Streak: {days} days',
  'onboarding.recap.badges': 'Badges: {count}',
  'onboarding.recap.friends': 'Requests on their way: {count}',
  'onboarding.recap.tomorrow': 'Tomorrow, your streak can reach {next}.',
  'onboarding.recap.explore': 'Keep exploring',
  'onboarding.recap.done': 'That’s it for today',
} satisfies OnboardingCatalog;

export default en;
