import type { InviteCatalog } from '@/lib/i18n-invite-catalog';

const es = {
  'invite.brand': 'Meeshy',
  'invite.loading': 'Abriendo la invitación…',
  'invite.inviter.named': '{name} te invita',
  'invite.inviter.unnamed': 'Te invitan a unirte',
  'invite.inviter.message': 'Mensaje de {name}',
  'invite.group.fallbackTitle': 'Una conversación de Meeshy',
  'invite.group.created': 'creado el {date}',
  'invite.group.logo': 'Logo de {name}',
  'invite.kind.direct': 'Conversación privada',
  'invite.kind.group': 'Grupo',
  'invite.kind.public': 'Conversación pública',
  'invite.kind.global': 'Abierta a todos',
  'invite.kind.broadcast': 'Canal de difusión',
  'invite.link.label': 'Enlace de la conversación',
  'invite.link.copy': 'Copiar',
  'invite.link.copied': 'Copiado',
  'invite.link.reshare': 'Volver a compartir',
  'invite.announce.copied': 'Enlace copiado.',
  'invite.announce.copyFailed': 'No se puede copiar el enlace aquí.',
  'invite.announce.shareUnavailable': 'Compartir no está disponible aquí.',
  'invite.share.text': 'Únete a {name} en Meeshy: cada uno escribe en su idioma.',
  'invite.stats.people.one': 'persona',
  'invite.stats.people.other': 'personas',
  'invite.stats.languages.one': 'idioma hablado',
  'invite.stats.languages.other': 'idiomas hablados',
  'invite.stats.spoken': 'Aquí se habla',
  'invite.stats.share': '{language} {percent}',
  'invite.rights.title': 'Sin cuenta, podrás',
  'invite.rights.messages': 'Escribir mensajes',
  'invite.rights.images': 'Enviar imágenes',
  'invite.rights.files': 'Enviar archivos',
  'invite.rights.history': 'Ver los mensajes anteriores a tu llegada',
  'invite.rights.granted': 'permitido',
  'invite.rights.denied': 'no permitido',
  'invite.asked.label': 'Se te pedirá:',
  'invite.asked.nickname': 'un nombre',
  'invite.asked.email': 'un correo electrónico',
  'invite.asked.birthday': 'tu fecha de nacimiento',
  'invite.asked.nothing': 'nada más que tu idioma',
  'invite.languages.label': 'Idiomas aceptados:',
  'invite.languages.all': 'todos',
  'invite.validity.label': 'Enlace válido',
  'invite.validity.days.one': '{count} día más',
  'invite.validity.days.other': '{count} días más',
  'invite.validity.today': 'hasta hoy',
  'invite.validity.forever': 'sin límite de tiempo',
  'invite.places.unlimited': 'plazas ilimitadas',
  'invite.places.one': 'Queda {count} plaza',
  'invite.places.other': 'Quedan {count} plazas',
  'invite.join.title': 'Unirse a {name}',
  'invite.join.account': 'Unirme con mi cuenta',
  'invite.join.joining': 'Entrando en la conversación…',
  'invite.join.joined': 'Te has unido a la conversación. Abriendo el hilo…',
  'invite.join.offline': 'Sin conexión: unirse esperará a que vuelva la red.',
  'invite.guest.continue': 'Continuar sin cuenta',
  'invite.guest.nickname': 'Tu nombre',
  'invite.guest.nickname.optional': 'Tu nombre (opcional)',
  'invite.guest.nickname.placeholder': '¿Cómo te llamamos?',
  'invite.guest.nickname.placeholder.optional': 'Déjalo vacío para un apodo generado',
  'invite.guest.language': 'Tu idioma',
  'invite.guest.email': 'Tu correo',
  'invite.guest.email.placeholder': 'tu@ejemplo.com',
  'invite.guest.birthday': 'Tu fecha de nacimiento',
  'invite.exits.separator': 'o con tu cuenta',
  'invite.exits.signIn': 'Iniciar sesión',
  'invite.exits.signUp': 'Crear una cuenta',
  'invite.exits.accountRequired': 'Esta conversación requiere una cuenta de Meeshy.',
  'invite.refusal.not-found': 'No se encuentra esta invitación. Puede que el enlace esté incompleto.',
  'invite.refusal.revoked': 'La persona que compartió este enlace lo ha desactivado.',
  'invite.refusal.expired': 'Este enlace ha caducado o ya no está activo.',
  'invite.refusal.closed': 'Esta conversación ha terminado: ya no es posible unirse.',
  'invite.refusal.full': 'Este enlace ha alcanzado su límite de participantes.',
  'invite.refusal.language': 'Esta invitación no acepta tu idioma.',
  'invite.refusal.banned': 'Ya no puedes unirte a esta conversación.',
  'invite.refusal.region': 'Esta invitación no está disponible desde tu red.',
  'invite.refusal.account-required': 'Se necesita una cuenta de Meeshy para unirse a esta conversación.',
  'invite.refusal.session-expired': 'Tu sesión ha caducado. Vuelve a iniciar sesión para unirte.',
  'invite.refusal.rate-limited': 'Demasiados intentos. Vuelve a intentarlo en un momento.',
  'invite.refusal.offline': 'Estás sin conexión. La invitación aparecerá cuando vuelva la red.',
  'invite.refusal.unavailable': 'La invitación no está disponible por ahora.',
  'invite.missing.nickname': 'Elige un nombre para esta conversación.',
  'invite.missing.email': 'Este enlace requiere un correo electrónico válido.',
  'invite.missing.birthday': 'Este enlace requiere tu fecha de nacimiento.',
  'invite.missing.language': 'Elige uno de los idiomas que acepta este enlace.',
  'invite.refused.nickname': 'Este nombre ya está en uso en esta conversación.',
  'invite.refused.email': 'Este correo electrónico ha sido rechazado.',
  'invite.refused.birthday': 'Esta fecha de nacimiento ha sido rechazada.',
  'invite.refused.language': 'Esta invitación no acepta este idioma.',
  'invite.refused.none': 'Falta un dato solicitado o ha sido rechazado.',
  'invite.refused.taken': 'Este nombre ya está en uso: «{suggestion}» está libre.',
  'invite.retry': 'Reintentar',
  'invite.home': 'Volver al inicio',

  'linkDetail.title': 'Enlace de invitación',
  'linkDetail.breadcrumb': 'Ruta de navegación',
  'linkDetail.breadcrumb.links': 'Enlaces',
  'linkDetail.breadcrumb.share': 'Enlaces de conversación',
  'linkDetail.card.created': 'Enlace creado el {date}',
  'linkDetail.card.share': 'Compartir',
  'linkDetail.card.copy': 'Copiar el enlace',
  'linkDetail.card.copied': 'Enlace copiado',
  'linkDetail.stats.title': 'Estadísticas',
  'linkDetail.stats.visits': 'Visitas',
  'linkDetail.stats.arrivals': 'Llegadas',
  'linkDetail.stats.anonymous': 'Sin cuenta',
  'linkDetail.stats.unknown': 'aún sin medir',
  'linkDetail.stats.unavailable': 'Las estadísticas de este enlace aún no están disponibles.',
  'linkDetail.languages.title': 'Idiomas de los recién llegados',
  'linkDetail.languages.empty': 'Aún no hay llegadas.',
  'linkDetail.recent.title': 'Llegados recientemente',
  'linkDetail.recent.anonymous': 'sin cuenta',
  'linkDetail.recent.empty': 'Nadie ha llegado todavía por este enlace.',
  'linkDetail.config.title': 'Configuración',
  'linkDetail.config.edit': 'Editar',
  'linkDetail.config.rights': 'Permisos de los invitados sin cuenta',
  'linkDetail.config.entry': 'Condiciones de entrada',
  'linkDetail.config.account': 'Cuenta de Meeshy',
  'linkDetail.config.account.required': 'Obligatoria',
  'linkDetail.config.account.optional': 'Opcional',
  'linkDetail.config.asked': 'Solicitado al llegar',
  'linkDetail.config.asked.nickname': 'Nombre',
  'linkDetail.config.asked.email': 'Correo',
  'linkDetail.config.asked.birthday': 'Fecha de nacimiento',
  'linkDetail.config.asked.none': 'Nada',
  'linkDetail.config.limits': 'Límites',
  'linkDetail.config.uses': 'Usos',
  'linkDetail.config.uses.value': '{count} / {max}',
  'linkDetail.config.unlimited': 'ilimitado',
  'linkDetail.config.concurrent': 'A la vez',
  'linkDetail.config.concurrent.value': '{count} máx.',
  'linkDetail.config.expires': 'Caduca',
  'linkDetail.config.expires.value': 'el {date}',
  'linkDetail.config.expires.never': 'Nunca',
  'linkDetail.config.languages': 'Idiomas permitidos',
  'linkDetail.config.languages.all': 'Todos los idiomas',
  'linkDetail.config.pending': 'Cargando la configuración de este enlace…',
  'linkDetail.rights.messages': 'Escribir mensajes',
  'linkDetail.rights.images': 'Enviar imágenes',
  'linkDetail.rights.files': 'Enviar archivos',
  'linkDetail.rights.history': 'Ver el historial',
  'linkDetail.edit.title': 'Editar el enlace',
  'linkDetail.edit.name': 'Nombre del enlace (solo visible para ti)',
  'linkDetail.edit.name.placeholder': 'Ej. Invitación del equipo',
  'linkDetail.edit.message': 'Mensaje de invitación (visible para los invitados)',
  'linkDetail.edit.message.placeholder': 'Di en una frase por qué unirse',
  'linkDetail.edit.limits': 'Límites',
  'linkDetail.edit.expiration': 'Caducidad',
  'linkDetail.edit.expiration.keep': 'Sin cambios — {date}',
  'linkDetail.edit.maxUses': 'Limitar los usos',
  'linkDetail.edit.maxUses.count': 'Usos máx.',
  'linkDetail.edit.maxConcurrent': 'Limitar las personas a la vez',
  'linkDetail.edit.maxConcurrent.count': 'Personas a la vez',
  'linkDetail.edit.number.invalid': 'Introduce un número entero entre 1 y {max}.',
  'linkDetail.edit.entry': 'Condiciones de entrada',
  'linkDetail.edit.rights': 'Permisos de los invitados sin cuenta',
  'linkDetail.edit.languages': 'Idiomas permitidos',
  'linkDetail.edit.languages.all': 'Todos los idiomas',
  'linkDetail.edit.languages.hint': 'Desactiva «Todos los idiomas» para elegir.',
  'linkDetail.edit.languages.invalid': 'Elige al menos un idioma.',
  'linkDetail.edit.save': 'Guardar',
  'linkDetail.edit.saving': 'Guardando…',
  'linkDetail.edit.unchanged': 'No hay cambios que guardar.',
  'linkDetail.edit.delete': 'Eliminar',
  'linkDetail.delete.title': '¿Eliminar este enlace?',
  'linkDetail.delete.body': 'El enlace dejará de funcionar y los invitados sin cuenta que entraron por él perderán el acceso.',
  'linkDetail.delete.confirm': 'Eliminar el enlace',
  'linkDetail.delete.cancel': 'Cancelar',
  'linkDetail.announce.saved': 'Cambios guardados.',
  'linkDetail.announce.saveFailed': 'No se guardaron los cambios.',
  'linkDetail.announce.deleted': 'Enlace eliminado.',
  'linkDetail.announce.deleteFailed': 'No se eliminó el enlace.',
  'linkDetail.announce.offline': 'Sin conexión: no se envió nada.',
} satisfies InviteCatalog;

export default es;
