/**
 * LE STUDIO D'UN APPEL VIDÉO, FRANÇAIS (#8551, #8552) — la SOURCE des clés :
 * les effets de visage, les montages et la capture. Les six autres langues
 * portent exactement ces clés (`satisfies CallStudioCatalog`,
 * `i18n-call-studio-catalog.test.ts`).
 */
const fr = {
  'callStudio.effects.color': 'Couleur',
  'callStudio.effects.settings': 'Réglages',
  'callStudio.face.none': 'Aucun',
  'callStudio.face.smoothing': 'Lissage de peau',
  'callStudio.face.toad': 'Crapaud',
  'callStudio.face.angel': 'Ange',
  'callStudio.face.demon': 'Démon',
  'callStudio.face.volcano': 'Éruption',
  'callStudio.montage.screen': 'Plein écran',
  'callStudio.montage.grid': 'Mosaïque',
  'callStudio.montage.strip': 'Photomaton',
  'callStudio.montage.polaroid': 'Polaroïd',
  'callStudio.montage.magazine': 'Magazine',
  'callStudio.montage.comic': 'BD',
  'callStudio.montage.heart': 'Cœur',
  'callStudio.capture.preview': 'Aperçu du montage {style}',
  'callStudio.capture.shoot': 'Capturer',
  'callStudio.capture.shootLabel': 'Capturer le montage {style}',
  'callStudio.capture.faces': 'Chaque visage',
  'callStudio.capture.facesLabel': 'Enregistrer chaque visage séparément',
  'callStudio.capture.saved': 'Capture enregistrée',
  'callStudio.capture.faceSaved': '1 visage enregistré',
  'callStudio.capture.facesSaved': '{count} visages enregistrés',
  'callStudio.capture.failed': 'La capture n’a pas pu être enregistrée',
  'callStudio.capture.cancelled': 'Enregistrement annulé',
  'callStudio.capture.empty': 'Rien à capturer : aucune image n’est affichée',
  'callStudio.capture.busy': 'Capture en cours…',
  'callStudio.capture.bubble': 'Quel appel !',
  'callStudio.montage.cover': 'Couverture',
  'callStudio.montage.gold': 'Doré',
  'callStudio.montage.redcarpet': 'Tapis rouge',
  'callStudio.montage.film': 'Pellicule',
  'callStudio.montage.neon': 'Néon',
  'callStudio.montage.noir': 'Noir et blanc',
  'callStudio.cover.line1': 'L’appel de l’année',
  'callStudio.cover.line2': 'Tous réunis, enfin',
  'callStudio.cover.line3': 'Exclusif',
  'callStudio.mode.effects': 'Effets de ma vidéo',
  'callStudio.mode.montage': 'Capturer l’appel',
  'callStudio.mode.quit': 'Quitter',
  'callStudio.mode.quitEffects': 'Quitter sans garder ces changements',
  'callStudio.mode.validate': 'Valider',
  'callStudio.mode.validateLabel': 'Garder cet effet et revenir à l’appel',
  'callStudio.mode.face': 'Visage',
  'callStudio.mode.categories': 'Catégorie',
  'callStudio.mode.pickEffect': 'Choisir un effet',
  'callStudio.mode.pickMontage': 'Choisir un montage',
  'callStudio.mode.settingsLabel': 'Afficher les réglages (luminosité, flou)',
} as const;

export default fr;
