import type { InterfaceCatalog } from '@/lib/i18n-catalog';

const de = {
  'announce.messageSent': 'Nachricht gesendet',
  'announce.messageCopied': 'Nachricht kopiert',
  'announce.messagesCopied': 'Nachrichten kopiert',
  'announce.messageProtected': 'Geschützte Nachricht',
  'announce.selectionCap': 'Maximal {count} Nachrichten',
  'announce.nothingToCopy': 'Nichts zu kopieren',

  'message.author.self': 'Du',
  'message.excerpt.protected': 'geschützter Inhalt',
  'a11y.message.menu.subject': 'Aktionen für die Nachricht von {author}: {excerpt}',

  'selection.toolbar': 'Nachrichtenauswahl',
  'selection.cancel': 'Abbrechen',
  'selection.count': '{count} ausgewählt',
  'forward.title': 'Weiterleiten an…',
  'forward.empty': 'Keine Unterhaltung',
  'forward.search.label': 'Unterhaltung suchen',
  'forward.search.placeholder': 'Suchen',
  'forward.announce.sent': 'Nachricht weitergeleitet',
  'forward.announce.sentMany': '{count} Nachrichten weitergeleitet',
  'forward.announce.failed': 'Weiterleiten fehlgeschlagen',
  'forward.refusal.viewOnce': 'Eine Einmal-Nachricht kann nicht weitergeleitet werden',
  'forward.refusal.unavailable': 'Die ursprüngliche Nachricht ist nicht mehr verfügbar: nichts zum Weiterleiten',

  'typing.named': '{name} schreibt',
  'typing.double': '{first} und {second} schreiben',
  'typing.several': 'Mehrere Personen schreiben',

  'feed.header.reels': 'Reels starten',
  'reels.title': 'Reels',
  'reels.back': 'Zurück',
  'reels.open': 'Reel von {author} ansehen',
  'reels.item': 'Reel von {author}, {index} von {count}',
  'reels.loading': 'Reels werden geladen',
  'reels.empty': 'Noch keine Reels',
  'reels.empty.hint': 'Reels deiner Kontakte erscheinen hier.',
  'reels.error': 'Reels konnten nicht geladen werden',
  'reels.error.hint': 'Versuche es gleich noch einmal.',
  'reels.retry': 'Erneut versuchen',
  'reels.offline': 'Offline',
  'reels.offline.cold': 'Reels werden geladen, sobald du wieder online bist.',
  'reels.action.like': 'Gefällt mir',
  'reels.action.bookmark': 'Speichern',
  'reels.action.share': 'Teilen',
  'reels.sound.on': 'Ton einschalten',
  'reels.sound.off': 'Stummschalten',
  'reels.play': 'Reel abspielen',
  'reels.pause': 'Reel pausieren',
  'reels.media.error': 'Wiedergabe nicht möglich — Erneut versuchen',
  'reels.image': 'Bild {index} von {count}',

  'stories.title': 'Storys',
  'stories.loading': 'Storys werden geladen…',
  'stories.error': 'Storys konnten nicht geladen werden.',
  'stories.empty.title': 'Noch keine Storys',
  'stories.empty.subtitle': 'Storys deiner Kontakte werden hier zwanzig Stunden lang angezeigt.',
  'stories.create': 'Story erstellen',
  'stories.count.one': '{count} Story',
  'stories.count.other': '{count} Storys',
  'stories.mine': 'Deine Story',

  /* #6150 — die beiden Türen meiner eigenen Zelle in der Leiste. */
  'stories.self.addStory': 'Story hinzufügen',
  'stories.self.mood.add': 'Stimmung setzen',
  'stories.self.mood.change': 'Meine Stimmung ändern, {emoji}',

  'status.compose.title': 'Meine Stimmung',
  'status.compose.pick': 'Stimmung wählen',
  'status.compose.note': 'Ein Wort, wenn du magst',
  'status.compose.publish': 'Veröffentlichen',
  'status.compose.publishing': 'Wird veröffentlicht…',
  'status.compose.error': 'Deine Stimmung konnte nicht veröffentlicht werden.',
  'status.compose.offline': 'Offline — deine Stimmung geht raus, sobald das Netz zurück ist.',

  'feed.header.create': 'Beitrag oder Reel erstellen',
  'feed.create.post': 'Beitrag',
  'feed.create.reel': 'Reel',

  'feed.post.action.like': 'Gefällt mir',
  'feed.post.action.comment': 'Kommentieren',
  'feed.post.action.repost': 'Erneut teilen',
  'feed.post.action.bookmark': 'Speichern',
  'feed.post.action.share': 'Teilen',
  'feed.post.media.video': 'Video',
  'feed.post.media.audio': 'Audio',
  'feed.post.media.previous': 'Vorheriges Medium',
  'feed.post.media.next': 'Nächstes Medium',
  'feed.post.media.mosaic': 'Mosaik aus {count} Medien',
  'media.unavailable': 'Medium nicht verfügbar',
  'feed.post.see_more': 'mehr anzeigen',
  'feed.post.see_less': 'weniger anzeigen',
  'feed.post.more_options': 'Weitere Optionen',
  'feed.post.menu.open': 'Öffnen',
  'feed.post.menu.copy_text': 'Text kopieren',
  'feed.post.menu.unsave': 'Aus Gespeichertem entfernen',
  'feed.post.menu.pin': 'Anheften',
  'feed.post.menu.delete': 'Löschen',
  'report.post.title': 'Diesen Beitrag melden',
  'feed.post.copied': 'Text kopiert',
  'feed.post.copy_failed': 'Text konnte nicht kopiert werden',
  'feed.post.pinned': 'Beitrag angeheftet',
  'feed.post.pin_failed': 'Beitrag konnte nicht angeheftet werden',
  'feed.post.deleted': 'Beitrag gelöscht',
  'feed.post.delete_failed': 'Fehler beim Löschen',
  'feed.post.repost.success': 'Repostet',
  'feed.post.repost.error': 'Repost fehlgeschlagen',
  'feed.post.repost.already': 'Bereits repostet',
  'feed.post.repost.offline': 'Offline — der Repost konnte nicht gesendet werden.',
  'feed.post.repost.unconfirmed': 'Repost nicht bestätigt — bitte erneut versuchen',
  'feed.post.repost.audience': 'Diese Zielgruppe würde die Reichweite des Originalbeitrags erweitern',
  'feed.post.reel.chip': 'Reel',
  'feed.post.reel.of': 'Reel von {author}',
  'feed.post.open': 'Beitrag von {author} öffnen',
  /* LES PUBLICATIONS ENREGISTRÉES (#7286) — l'écran `/me/bookmarks` et sa rangée de Réglages › Outils. */
  'bookmarks.title': 'Gespeicherte Beiträge',
  'bookmarks.back': 'Zurück zu den Einstellungen',
  'bookmarks.loading': 'Gespeicherte Beiträge werden geladen',
  'bookmarks.empty.title': 'Noch keine gespeicherten Beiträge',
  'bookmarks.empty.subtitle': 'Tippe auf das Lesezeichen unter einem Beitrag, um ihn hier zu behalten und jederzeit wieder zu lesen.',
  'bookmarks.empty.cta': 'Feed öffnen',
  'bookmarks.error.title': 'Gespeicherte Beiträge konnten nicht geladen werden',
  'bookmarks.error.body': 'Versuche es gleich noch einmal.',
  'bookmarks.offline.body': 'Deine gespeicherten Beiträge erscheinen, sobald du wieder online bist.',
  'bookmarks.allLoaded': 'Alle gespeicherten Beiträge sind geladen',
  'bookmarks.filter.all': 'Alle',
  'bookmarks.filter.posts': 'Beiträge',
  'bookmarks.filter.reels': 'Reels',
  'bookmarks.filter.a11y': 'Gespeicherte Beiträge filtern',
  'settings.tools.bookmarks': 'Gespeicherte Beiträge',
  'action.star': 'Zu Favoriten hinzufügen',
  'action.unstar': 'Aus Favoriten entfernen',
  'announce.messageStarred': 'Zu Favoriten hinzugefügt',
  'announce.messageUnstarred': 'Aus Favoriten entfernt',
  'starred.messages.pending': 'Favorit nicht bestätigt – offline',
  'starred.messages.error': 'Favorit konnte nicht geändert werden',
  'starred.messages.notStarrable': 'Diese Nachricht kann nicht zu den Favoriten hinzugefügt werden',
  'settings.tools.starred': 'Markierte Nachrichten',
  'starred.messages.title': 'Markierte Nachrichten',
  'starred.messages.back': 'Zurück zu den Einstellungen',
  'starred.messages.loading': 'Markierte Nachrichten werden geladen',
  'starred.messages.empty.title': 'Keine favorisierten Nachrichten',
  'starred.messages.empty.subtitle': 'Halte eine Nachricht gedrückt und wähle „Zu Favoriten hinzufügen“, um sie hier wiederzufinden.',
  'starred.messages.empty.cta': 'Unterhaltungen öffnen',
  'starred.messages.error.title': 'Deine markierten Nachrichten konnten nicht geladen werden',
  'starred.messages.error.body': 'Versuche es gleich noch einmal.',
  'starred.messages.offline.body': 'Deine markierten Nachrichten erscheinen, sobald du wieder online bist.',
  'starred.messages.allLoaded': 'Alle markierten Nachrichten sind geladen',
  'starred.messages.row.hint': 'Öffnet die Unterhaltung',
  'starred.messages.remove.a11y': 'Nachricht von {author} aus den Favoriten entfernen',
  'starred.messages.protected': 'Geschützte Nachricht',
  'starred.messages.noText': 'Nachricht ohne Text',
  'starred.messages.media.image': 'Foto',
  'starred.messages.media.video': 'Video',
  'starred.messages.media.audio': 'Audio',
  'starred.messages.media.file': 'Datei',
  'common.unknown_user': 'Nutzer',
  'feed.error.title': 'Feed konnte nicht geladen werden',
  'feed.error.body': 'Versuche es gleich noch einmal.',
  'feed.offline.title': 'Offline',
  'feed.offline.body': 'Der Feed erscheint, sobald du wieder online bist.',
  'feed.retry': 'Erneut versuchen',
  'feed.empty.title': 'Noch keine Beiträge',
  'feed.empty.subtitle': 'Beiträge deiner Kontakte erscheinen hier.',
  'feed.loading': 'Feed wird geladen',
  'feed.allLoaded': 'Alle Beiträge sind geladen',
  'feed.newPosts.one': '{count} neuer Beitrag',
  'feed.newPosts.other': '{count} neue Beiträge',
  'a11y.avatar.profile': 'Profil von {name} ansehen',
  'a11y.avatar.story': 'Story von {name} ansehen',
  'userProfile.self.edit': 'Mein Profil bearbeiten',
  'report.title': 'Dieses Konto melden',
  'report.body': 'Wählen Sie den Grund für Ihre Meldung. Unser Moderationsteam erhält sie.',
  'report.action': 'Melden',
  'report.done': 'Meldung gesendet',
  'report.throttled': 'Zu viele Meldungen — versuchen Sie es gleich erneut',
  'report.failed': 'Die Meldung konnte nicht gesendet werden',
  'report.reason.spam': 'Spam',
  'report.reason.inappropriate': 'Unangemessener Inhalt',
  'report.reason.harassment': 'Belästigung',
  'report.reason.violence': 'Gewalt',
  'report.reason.hate_speech': 'Hassrede',
  'report.reason.fake_profile': 'Gefälschtes Profil',
  'report.reason.impersonation': 'Identitätsdiebstahl',
  'report.reason.other': 'Sonstiges',
  'feed.like.error': 'Fehler beim Liken des Beitrags',
  'post.bookmark.error': 'Speichern fehlgeschlagen',
  'feed.gesture.pending': 'Aktion nicht bestätigt — offline',
  'feed.share.error': 'Fehler beim Teilen des Beitrags',
  'feed.share.copied': 'Link kopiert — einfach einfügen.',
  'feed.share.text': 'Ein Beitrag auf Meeshy',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'Meine Links',
  'root.menu.notifications': 'Mitteilungen',
  'root.menu.calls': 'Anrufe',
  'root.menu.discover': 'Entdecken',
  'root.menu.communities': 'Communitys',
  'root.menu.settings': 'Einstellungen',
  'root.menu.profile': 'Profil',
  'root.menu.conversations': 'Unterhaltungen',
  'a11y.floating.feed.hint': 'Lange drücken, um Reels zu starten',
  'a11y.floating.menu': 'Menü',
  'a11y.floating.menu.ladder': 'Meeshy-Navigation',
  'a11y.floating.menu.unread.one': 'Menü, {count} ungelesene Mitteilung',
  'a11y.floating.menu.unread.other': 'Menü, {count} ungelesene Mitteilungen',
  'a11y.floating.rung.notifications.unread.one': 'Mitteilungen, {count} ungelesen',
  'a11y.floating.rung.notifications.unread.other': 'Mitteilungen, {count} ungelesen',

  'notifications.category.all': 'Alle',
  'notifications.category.unread': 'Ungelesen',
  'notifications.category.messages': 'Nachrichten',
  'notifications.category.reactions': 'Reaktionen',
  'notifications.category.mentions': 'Erwähnungen',
  'notifications.category.social': 'Soziales',
  'notifications.category.contacts': 'Kontakte',
  'notifications.category.groups': 'Gruppen',
  'notifications.category.calls': 'Anrufe',
  'notifications.category.translations': 'Übersetzungen',
  'notifications.category.system': 'System',
  'notifications.categories': 'Mitteilungskategorien',
  'notifications.markAllRead': 'Alle gelesen',
  'notifications.unreadCount.one': '{count} ungelesen',
  'notifications.unreadCount.other': '{count} ungelesen',
  'notifications.unread': 'Ungelesen',
  'notifications.empty.all': 'Keine Mitteilungen',
  'notifications.empty.unread': 'Keine ungelesenen Mitteilungen',
  'notifications.empty.category': 'Keine Mitteilungen in „{category}“',
  'notifications.empty.subtitle': 'Deine Mitteilungen erscheinen hier',
  'notifications.loading': 'Mitteilungen werden geladen',
  'notifications.error.title': 'Mitteilungen konnten nicht geladen werden',
  'notifications.error.body': 'Versuche es gleich noch einmal.',
  'notifications.offline.title': 'Offline',
  'notifications.offline.body': 'Deine Mitteilungen erscheinen, sobald du wieder online bist.',
  'notifications.retry': 'Erneut versuchen',
  'notifications.allLoaded': 'Alle Mitteilungen sind geladen',
  'notifications.actions': 'Aktionen für die Mitteilung',
  'notifications.action.markRead': 'Als gelesen markieren',
  'notifications.action.delete': 'Löschen',
  'notifications.failure': 'Das hat nicht geklappt. Versuche es erneut.',

  'notFound.title': 'Diese Adresse gibt es nicht.',

  'pending.back': 'Zurück zu den Unterhaltungen',

  'linkPage.home': 'Zurück zu Meeshy',
  'linkPage.retry': 'Erneut versuchen',
  'linkPage.settings': 'Einstellungen öffnen',
  'linkPage.signIn': 'Anmelden',
  'linkPage.offline.title': 'Offline',
  'linkPage.offline.body': 'Verbinde dich wieder mit dem Internet und versuche es erneut.',
  'linkPage.unavailable.title': 'Meeshy antwortet nicht',
  'linkPage.unavailable.body': 'Der Dienst ist vorübergehend nicht verfügbar. Versuche es in einigen Augenblicken erneut.',
  'linkPage.rateLimited': 'Zu viele Versuche. Warte einen Moment, bevor du es erneut versuchst.',
  'linkPage.signedOut.title': 'Melde dich an, um fortzufahren',
  'linkPage.signedOut.body': 'Dieser Link wirkt auf dein Konto. Melde dich an und öffne ihn dann erneut aus der E-Mail.',
  'linkPage.expired': 'Dieser Link ist abgelaufen. Stelle die Anfrage erneut in den Einstellungen.',
  'trackingLink.opening': 'Link wird geöffnet…',
  'trackingLink.dead.title': 'Dieser Link ist nicht mehr verfügbar',
  'trackingLink.dead.body': 'Er ist abgelaufen, wurde deaktiviert oder hat nie existiert.',
  'accountDeletion.incomplete.title': 'Unvollständiger Link',
  'accountDeletion.incomplete.body': 'Diesem Link fehlen die nötigen Angaben. Melde dich an, um die Löschung deines Kontos zu beantragen.',
  'accountDeletion.confirm.title': 'Löschung deines Kontos bestätigen',
  'accountDeletion.confirm.body':
    'Dein Konto wird nach einer Karenzzeit von 30 Tagen deaktiviert. Bis dahin kannst du es dir über den Link „Abbrechen“ in der E-Mail anders überlegen.',
  'accountDeletion.confirm.action': 'Löschung bestätigen',
  'accountDeletion.cancel.title': 'Löschung deines Kontos abbrechen',
  'accountDeletion.cancel.body': 'Dein Konto bleibt aktiv und der Löschantrag wird verworfen. Nichts geht verloren.',
  'accountDeletion.cancel.action': 'Löschung abbrechen',
  'accountDeletion.purge.title': 'Konto jetzt löschen',
  'accountDeletion.purge.body': 'Dein Konto wird sofort deaktiviert und alle deine Sitzungen werden beendet. Dieser Schritt ist endgültig.',
  'accountDeletion.purge.action': 'Jetzt löschen',
  'accountDeletion.dismiss': 'Nichts tun',
  'accountDeletion.working': 'Einen Moment…',
  'accountDeletion.done.title': 'Erledigt',
  'accountDeletion.done.confirmed': 'Dein Antrag ist bestätigt: Dein Konto wird am {date} deaktiviert. Bis dahin kannst du abbrechen.',
  'accountDeletion.done.cancelled': 'Dein Konto bleibt aktiv: Der Löschantrag wurde verworfen.',
  'accountDeletion.done.completed': 'Dein Konto ist deaktiviert und alle deine Sitzungen wurden beendet.',
  'accountDeletion.done.purged': 'Deine Daten wurden gelöscht.',
  'accountDeletion.closed.title': 'Dieser Link gilt nicht mehr',
  'accountDeletion.invalid': 'Dieser Link ist ungültig oder wurde bereits verwendet.',
  'accountDeletion.request.title': 'Konto löschen',
  'accountDeletion.request.body':
    'Deine Unterhaltungen, Nachrichten, Medien, Kontakte und Einstellungen werden gelöscht. Eine E-Mail bittet dich um Bestätigung, danach kannst du es dir während einer Karenzzeit von 30 Tagen anders überlegen.',
  'accountDeletion.request.phrase': 'Gib {phrase} ein, um zu bestätigen',
  'accountDeletion.request.password': 'Aktuelles Passwort',
  'accountDeletion.request.action': 'Löschung beantragen',
  'accountDeletion.request.sent.title': 'Wir haben dir eine Bestätigungs-E-Mail gesendet',
  'accountDeletion.request.sent.body': 'Öffne sie, um die Löschung deines Kontos zu bestätigen.',
  'accountDeletion.request.wrongPassword': 'Falsches Passwort.',
  'accountDeletion.request.alreadyPending': 'Es läuft bereits ein Antrag. Öffne die erhaltene E-Mail, um ihn zu bestätigen oder abzubrechen.',
  'accountDeletion.request.noEmail': 'Füge eine E-Mail-Adresse hinzu und bestätige sie, bevor du die Löschung beantragst.',
  'emailChange.verifying': 'Deine neue Adresse wird bestätigt…',
  'emailChange.done.title': 'E-Mail-Adresse geändert',
  'emailChange.done.body': 'Du meldest dich ab jetzt mit {email} an.',
  'emailChange.done.generic': 'Deine neue E-Mail-Adresse ist bestätigt.',
  'emailChange.failed.title': 'Adresse nicht geändert',
  'emailChange.missing': 'Dieser Link enthält keinen Bestätigungscode. Öffne den Link aus der neuesten E-Mail.',
  'emailChange.invalid': 'Dieser Link passt zu keiner ausstehenden Änderung dieses Kontos oder wurde bereits verwendet.',
  'emailChange.taken': 'Diese Adresse wird inzwischen von einem anderen Konto verwendet.',
  'emailNotifications.title': 'E-Mails von Meeshy',
  'emailNotifications.loading': 'Deine Einstellung wird gelesen…',
  'emailNotifications.on': 'Du erhältst Ankündigungen, Zusammenfassungen und Benachrichtigungen von Meeshy per E-Mail.',
  'emailNotifications.off': 'Du erhältst keine Ankündigungen, Zusammenfassungen oder Benachrichtigungen von Meeshy mehr per E-Mail.',
  'emailNotifications.security': 'Sicherheits-E-Mails zu deinem Konto kommen weiterhin an.',
  'emailNotifications.unsubscribe': 'Diese E-Mails nicht mehr erhalten',
  'emailNotifications.resubscribe': 'Diese E-Mails wieder erhalten',
  'emailNotifications.failed': 'Die Änderung ist nicht durchgegangen. Versuche es erneut.',

  'dataExport.title': 'Meine Daten exportieren',
  'dataExport.info.body': 'Gemäß der DSGVO erhältst du eine Datei mit deinem Profil, deinen Nachrichten, deinen Kontakten und deinen Beiträgen.',
  'dataExport.action.start': 'Meine Daten exportieren',
  'dataExport.action.exporting': 'Export läuft…',
  'dataExport.action.again': 'Erneut exportieren',
  'dataExport.done.title': 'Export abgeschlossen',
  'dataExport.done.body': 'Die Datei wurde auf dieses Gerät heruntergeladen.',

  'profile.title': 'Profil',
  'profile.edit': 'Bearbeiten',
  'profile.cancel': 'Abbrechen',
  'profile.save': 'Speichern',
  'profile.saving': 'Wird gespeichert…',
  'profile.saved': 'Profil gespeichert',
  'profile.save.error': 'Fehler beim Speichern',
  'profile.save.offline': 'Offline — die Änderung wurde nicht gesendet.',
  'profile.save.invalid': 'Prüfe das Feld „{field}“.',
  'profile.loading': 'Profil wird geladen',
  'profile.error.title': 'Dein Profil konnte nicht geladen werden',
  'profile.error.body': 'Versuche es gleich noch einmal.',
  'profile.retry': 'Erneut versuchen',
  'profile.offline.title': 'Offline',
  'profile.offline.body': 'Dein Profil bleibt lesbar; Bearbeiten ist wieder möglich, sobald du online bist.',
  'profile.avatar.edit': 'Profilfoto bearbeiten',
  'profile.avatar.updated': 'Profilfoto aktualisiert',
  'profile.avatar.error': 'Profilfoto konnte nicht aktualisiert werden',
  'profile.banner.edit': 'Banner bearbeiten',
  'profile.banner.updated': 'Banner aktualisiert',
  'profile.banner.error': 'Banner konnte nicht aktualisiert werden',
  'profile.image.uploading': 'Wird hochgeladen',
  'profile.image.cancel': 'Hochladen abbrechen',
  'profile.image.cancelled': 'Hochladen abgebrochen',
  'profile.image.unreadable': 'Dieses Bild kann nicht gelesen werden.',
  'profile.section.identity': 'IDENTITÄT',
  'profile.section.contact': 'KONTAKT',
  'profile.section.languages': 'SPRACHEN',
  'profile.section.stats': 'STATISTIKEN',
  'profile.section.requests': 'ANFRAGEN',
  'profile.section.member_since': 'MITGLIED SEIT',
  'profile.first_name': 'Vorname',
  'profile.last_name': 'Nachname',
  'profile.username': 'Benutzername',
  'profile.display_name': 'Anzeigename',
  'profile.bio': 'Bio',
  'profile.bio.placeholder': 'Erzähl etwas über dich...',
  'profile.email': 'E-Mail',
  'profile.phone': 'Telefon',
  'profile.verified': 'Verifiziert',
  'profile.not_verified': 'Nicht verifiziert',
  'profile.language.primary': 'Hauptsprache',
  'profile.language.primary.subtitle': 'Inhalte werden in diese Sprache übersetzt',
  'profile.language.regional': 'Regionalsprache',
  'profile.language.custom': 'Benutzerdefinierte Sprache',
  'profile.language.none': 'Keine',
  'profile.language.choose': 'Auswählen',
  'profile.language.clear.regional': 'Regionalsprache entfernen',
  'profile.language.clear.custom': 'Benutzerdefinierte Sprache entfernen',

  'languageSheet.title.read': 'Lesesprache',
  'languageSheet.title.write': 'Schreibsprache',
  'languageSheet.search': 'Sprache suchen',
  'languageSheet.empty': 'Keine Sprache passt zu „{search}“.',

  'profile.stats.messages': 'Nachrichten',
  'profile.stats.translations': 'Übersetzungen',
  'profile.stats.languages': 'Sprachen',
  'profile.stats.days': 'Tage',
  'profile.stats.loading': 'Statistiken werden geladen',
  'profile.progression.title': 'Fortschritt',
  'profile.progression.subtitle': 'Abzeichen, Level und Serie',
  'profile.friend_requests': 'Freundschaftsanfragen',
  'profile.friend_requests.count.one': '{count} offene Anfrage',
  'profile.friend_requests.count.other': '{count} offene Anfragen',

  'settings.title': 'Einstellungen',
  'settings.my_profile': 'Mein Profil',
  'settings.section.account': 'Konto',
  'settings.security.title': 'Sicherheit',
  'settings.delete_account': 'Konto löschen',
  'settings.privacy.title': 'Datenschutz',
  'settings.privacy.online_status': 'Online-Status',
  'settings.privacy.online_status.info':
    'Der grüne Punkt auf deinem Avatar zeigt, dass du aktiv bist. Deaktiviert sieht ihn niemand — wer aber in einer Unterhaltung schreibt, verrät seine Aktivität trotzdem.',
  'settings.privacy.last_seen': 'Letzte Anmeldung',
  'settings.privacy.read_receipts': 'Lesebestätigungen',
  'settings.privacy.read_receipts.info':
    'Gilt in beide Richtungen: Wer keine Lesebestätigungen sendet, sieht auch nicht, ob die eigenen Nachrichten gelesen wurden.',
  'settings.privacy.typing_indicator': 'Schreibanzeige',
  'settings.section.appearance': 'Erscheinungsbild',
  'settings.theme': 'Design',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Hell',
  'settings.theme.dark': 'Dunkel',
  'settings.interface_language': 'Sprache der Benutzeroberfläche',
  'settings.interface_language.automatic': 'Automatisch',
  'settings.content_languages': 'Übersetzungssprachen',
  'settings.section.notifications': 'Mitteilungen',
  'settings.notifications.title': 'Mitteilungen',
  'settings.notif.sounds': 'Töne',
  'settings.notif.more_options': 'Weitere Optionen',
  'settings.section.data': 'Daten',
  'settings.media': 'Medien',
  'settings.messages': 'Nachrichten',
  'settings.export_data': 'Meine Daten exportieren',
  'settings.section.tools': 'Werkzeuge',
  'settings.tools.progression': 'Fortschritt',
  'settings.section.about': 'Über',
  'settings.terms': 'Nutzungsbedingungen',
  'settings.privacy_policy': 'Datenschutzrichtlinie',
  'settings.version': 'Version',
  'settings.logout.title': 'Abmelden',
  'settings.logout.message': 'Möchtest du dich wirklich abmelden?',
  'settings.logout.inprogress': 'Abmeldung läuft...',
  'settings.loading': 'Einstellungen werden geladen',
  'settings.error.title': 'Deine Einstellungen konnten nicht geladen werden',
  'settings.retry': 'Erneut versuchen',
  'settings.offline.body': 'Offline – deine Einstellungen bleiben lesbar; ändern kannst du sie, sobald das Netz zurück ist.',
  'settings.save.error': 'Die Einstellung wurde nicht gespeichert.',
  'settings.theme.sync_error': 'Design auf diesem Gerät übernommen, nicht synchronisiert.',
  'common.cancel': 'Abbrechen',

  'media.video.play': 'Video abspielen',
  'media.video.pause': 'Pausieren',
  'media.video.position': 'Wiedergabeposition',
  'media.audio.position': 'Wiedergabeposition',
  'media.audio.speed': 'Wiedergabegeschwindigkeit',
  'media.video.position.value': '{elapsed} von {total}',
  'media.video.mute': 'Stummschalten',
  'media.video.unmute': 'Ton einschalten',
  'media.video.more_options': 'Weitere Optionen',
  'media.video.speed': 'Geschwindigkeit',
  'media.video.pip.enter': 'Bild-in-Bild',
  'media.video.pip.exit': 'Bild-in-Bild beenden',

  'community.list.create.accessibilityLabel': 'Community erstellen',
  'community.list.search.placeholder': 'Communitys suchen',
  'community.list.search.clear': 'Suche löschen',
  'community.list.search.empty': 'Keine Community passt zu „{query}“.',
  'community.list.empty.title': 'Keine Communitys',
  'community.list.empty.subtitle': 'Tritt einer Community bei oder erstelle eine, um gemeinsam zu schreiben.',
  'community.list.loading': 'Communitys werden geladen',
  'community.error.title': 'Communitys konnten nicht geladen werden',
  'community.error.body': 'Prüfe deine Verbindung und versuche es erneut.',
  'community.retry': 'Erneut versuchen',
  'community.offline.title': 'Offline',
  'community.offline.body': 'Deine Communitys bleiben lesbar; zum Erstellen brauchst du eine Verbindung.',
  'community.privacy.private': 'Privat',
  'community.privacy.public': 'Öffentlich',
  'community.members.one': '{count} Mitglied',
  'community.members.other': '{count} Mitglieder',
  'community.conversations.one': '{count} Unterhaltung',
  'community.conversations.other': '{count} Unterhaltungen',
  'community.detail.stats.members': 'Mitglieder',
  'community.detail.channels': 'Unterhaltungen',
  'community.detail.channels.empty': 'Du bist noch in keiner Unterhaltung dieser Community.',
  'community.detail.untitled': 'Unbenannte Unterhaltung',
  'community.detail.back': 'Zurück zu den Communitys',
  'community.detail.refused.title': 'Community nicht gefunden',
  'community.detail.refused.body': 'Sie existiert nicht oder ist privat, und du bist kein Mitglied.',
  'community.detail.error.title': 'Diese Community konnte nicht geladen werden',
  'community.detail.loading': 'Community wird geladen',
  'community.create.title': 'Neue Community',
  'community.create.preview.placeholder': 'Meine Community',
  'community.create.field.name': 'Name',
  'community.create.field.name.placeholder': 'Name der Community',
  'community.create.field.identifier': 'Kennung',
  'community.create.field.identifier.placeholder': 'meine-gruppe',
  'community.create.field.description': 'Beschreibung',
  'community.create.field.description.placeholder': 'Worum geht es in dieser Community?',
  'community.create.privacy.title': 'Private Community',
  'community.create.privacy.private.description': 'Nur eingeladene Mitglieder können beitreten',
  'community.create.privacy.public.description': 'Alle können sie entdecken und beitreten',
  'community.create.button': 'Community anlegen',
  'community.create.inprogress': 'Wird erstellt…',
  'community.create.error.name': 'Gib ihr einen Namen mit höchstens 100 Zeichen.',
  'community.create.error.identifier': 'Nur Buchstaben, Ziffern, Binde- und Unterstriche, höchstens 50.',
  'community.create.error.description': 'Höchstens 500 Zeichen.',
  'community.create.error.conflict': 'Diese Kennung ist bereits vergeben.',
  'community.create.error.offline': 'Offline – die Community wurde nicht gesendet.',
  'community.create.error.default': 'Die Community wurde nicht erstellt. Versuche es erneut.',
  'calls.filters': 'Anrufliste filtern',
  'calls.filter.all': 'Alle',
  'calls.filter.missed': 'Verpasst',
  'calls.direction.incoming': 'Eingegangen',
  'calls.direction.outgoing': 'Ausgehend',
  'calls.direction.missed': 'Verpasst',
  'calls.a11y.incoming': 'eingegangener Anruf',
  'calls.a11y.outgoing': 'ausgehender Anruf',
  'calls.a11y.missed': 'verpasster Anruf',
  'calls.type.audio': 'Sprachanruf',
  'calls.type.video': 'Videoanruf',
  'calls.duration': 'Dauer {duration}',
  'calls.unknown': 'Unbekannt',
  'calls.empty.title': 'Keine kürzlichen Anrufe',
  'calls.empty.subtitle': 'Deine eingegangenen, verpassten, abgebrochenen und ausgehenden Anrufe erscheinen hier.',
  'calls.empty.missed.title': 'Keine verpassten Anrufe',
  'calls.empty.missed.subtitle': 'Anrufe, die du nicht angenommen hast, erscheinen hier.',
  'calls.error.title': 'Die Anrufliste konnte nicht geladen werden',
  'calls.error.body': 'Prüfe deine Verbindung und versuche es erneut.',
  'calls.offline.title': 'Offline',
  'calls.offline.body': 'Du siehst die Anrufliste vom letzten Laden.',
  'calls.offline.cold.body': 'Die Anrufliste lädt, sobald du wieder online bist.',
  'calls.retry': 'Erneut versuchen',
  'calls.loading': 'Anrufliste wird geladen',
  'calls.allLoaded': 'Alle Anrufe der letzten drei Monate sind geladen',

  'discover.tabs': 'Bereiche von Entdecken',
  'discover.tab.discover': 'Entdecken',
  'discover.tab.requests': 'Anfragen',
  'discover.tab.blocked': 'Blockiert',
  'discover.tab.requests.count.one': 'Anfragen, {count} erhalten',
  'discover.tab.requests.count.other': 'Anfragen, {count} erhalten',
  'discover.invite.title': 'Per E-Mail einladen',
  'discover.invite.placeholder': 'E-Mail-Adresse',
  'discover.invite.send': 'Senden',
  'discover.invite.sending': 'Wird gesendet…',
  'discover.invite.sendLabel': 'Einladung per E-Mail senden',
  'discover.invite.sent': 'Einladung an {email} gesendet',
  'discover.invite.invalid': 'Diese E-Mail-Adresse ist ungültig.',
  'discover.invite.conflict': 'Diese Person ist bereits bei Meeshy: Suche sie unten.',
  'discover.invite.error': 'Die Einladung konnte nicht gesendet werden. Versuche es erneut.',
  'discover.invite.offline': 'Offline: Verbinde dich, um die Einladung zu senden.',
  'discover.search.label': 'Meeshy-Nutzer suchen',
  'discover.search.clear': 'Suche löschen',
  'discover.search.searching': 'Suche läuft',
  'discover.search.empty': 'Kein Nutzer für „{query}“ gefunden',
  'discover.search.error': 'Die Suche ist fehlgeschlagen. Prüfe deine Verbindung.',
  'discover.connection.add': 'Hinzufügen',
  'discover.connection.addLabel': '{name} hinzufügen',
  'discover.connection.pending': 'Ausstehend',
  'discover.connection.cancelLabel': 'An {name} gesendete Anfrage zurückziehen',
  'discover.connection.contact': 'Kontakt',
  'discover.connection.blocked': 'Blockiert',
  'discover.connection.acceptLabel': 'Anfrage von {name} annehmen',
  'discover.connection.rejectLabel': 'Anfrage von {name} ablehnen',
  'discover.requests.filters': 'Anfragen filtern',
  'discover.requests.received': 'Erhalten',
  'discover.requests.sent': 'Gesendet',
  'discover.requests.intent': 'Möchte sich mit dir vernetzen',
  'discover.requests.cancel': 'Zurückziehen',
  'discover.requests.empty.received.title': 'Keine Anfragen erhalten',
  'discover.requests.empty.received.subtitle': 'Kontaktanfragen, die du erhältst, erscheinen hier.',
  'discover.requests.empty.sent.title': 'Keine Anfragen gesendet',
  'discover.requests.empty.sent.subtitle': 'Anfragen, die du sendest, erscheinen hier.',
  'discover.blocked.unblock': 'Entsperren',
  'discover.blocked.unblockLabel': '{name} entsperren',
  'discover.blocked.confirm.title': 'Entsperren?',
  'discover.blocked.confirm.body': '{name} entsperren?',
  'discover.blocked.confirm.cancel': 'Abbrechen',
  'discover.blocked.empty.title': 'Keine blockierten Nutzer',
  'discover.blocked.empty.subtitle': 'Personen, die du blockierst, erscheinen hier.',
  'discover.unknown': 'Unbekannt',
  'discover.loading': 'Wird geladen',
  'discover.allLoaded': 'Die ganze Liste ist geladen',
  'discover.error.title': 'Diese Liste konnte nicht geladen werden',
  'discover.error.body': 'Prüfe deine Verbindung und versuche es erneut.',
  'discover.offline.title': 'Offline',
  'discover.offline.body': 'Du siehst die Liste vom letzten Laden.',
  'discover.offline.cold.body': 'Die Liste lädt, sobald du wieder online bist.',
  'discover.retry': 'Erneut versuchen',
  'discover.announce.accepted': 'Verbindung angenommen',
  'discover.announce.rejected': 'Anfrage abgelehnt',
  'discover.announce.cancelled': 'Anfrage zurückgezogen',
  'discover.announce.sent': 'Anfrage gesendet',
  'discover.announce.unblocked': 'Nutzer entsperrt',
  'discover.announce.acceptFailed': 'Anfrage konnte nicht angenommen werden',
  'discover.announce.rejectFailed': 'Anfrage konnte nicht abgelehnt werden',
  'discover.announce.cancelFailed': 'Anfrage konnte nicht zurückgezogen werden',
  'discover.announce.sendFailed': 'Anfrage konnte nicht gesendet werden',
  'discover.announce.unblockFailed': 'Entsperren fehlgeschlagen',
  'discover.announce.offline': 'Offline: Es wurde nichts gesendet.',

  'userProfile.title': 'Profil',
  'userProfile.loading': 'Profil wird geladen',
  'userProfile.section.publications': 'BEITRÄGE',
  'userProfile.section.relation': 'VERBINDUNG',
  'userProfile.section.conversations': 'UNTERHALTUNGEN',
  'userProfile.conversations.empty': 'Keine gemeinsame Unterhaltung',
  'userProfile.conversations.emptyBody': 'Noch verbindet euch nichts – „Schreiben“ eröffnet die erste.',
  'userProfile.conversations.error': 'Unterhaltungen konnten nicht geladen werden',
  'userProfile.conversations.loading': 'Unterhaltungen werden geladen',
  'userProfile.refused.title': 'Dieses Profil ist nicht verfügbar',
  'userProfile.refused.body': 'Es existiert nicht, oder Sie haben keinen Zugriff darauf.',
  'userProfile.throttled.title': 'Zu viele Anfragen',
  'userProfile.throttled.body': 'Versuchen Sie es gleich noch einmal.',
  'userProfile.error.title': 'Dieses Profil konnte nicht geladen werden',
  'userProfile.error.body': 'Versuchen Sie es gleich noch einmal.',
  'userProfile.offline.body': 'Das Profil erscheint, sobald Sie wieder online sind.',
  'userProfile.posts.empty': 'Keine Beiträge',
  'userProfile.posts.emptyBody': 'Noch nichts Öffentliches zu lesen.',
  'userProfile.posts.emptyPosts': 'Hier keine Beiträge',
  'userProfile.posts.emptyReels': 'Hier keine Reels',
  'userProfile.posts.emptyFilter': 'Tippe erneut auf die Kachel, um alles zu sehen.',
  'userProfile.posts.error': 'Die Beiträge konnten nicht geladen werden',
  'userProfile.posts.loadMore': 'Mehr laden',
  'userProfile.posts.loaded': 'Hinzugefügte Beiträge: {count}',
  'userProfile.posts.loadedNone': 'Keine weiteren Beiträge vorhanden',
  'userProfile.posts.loading': 'Wird geladen…',
  'userProfile.stat.posts': 'Beiträge',
  'userProfile.stat.reels': 'Reels',
  'userProfile.stat.stories': 'Storys',
  'userProfile.stat.filterLabel': 'Nach {name} filtern',
  'userProfile.stat.filterClear': 'Alle anzeigen',
  'userProfile.context.received': '{name} möchte sich mit Ihnen verbinden. Nehmen Sie an, um Nachrichten auszutauschen.',
  'userProfile.context.sent': 'Sie haben {name} eine Verbindungsanfrage gesendet. Warten auf Antwort.',
  'userProfile.action.write': 'Schreiben',
  'userProfile.action.writeLabel': '{name} schreiben',
  'userProfile.action.block': 'Blockieren',
  'userProfile.action.blockLabel': '{name} blockieren',
  'userProfile.blocked.title': 'Sie haben diese Person blockiert',
  'userProfile.blocked.body': 'Ihre Beiträge und Statistiken bleiben verborgen, solange die Blockierung besteht.',
  'userProfile.signin.title': 'Melden Sie sich an, um sich zu verbinden',
  'userProfile.signin.body': 'Verbindungsanfragen und Nachrichten erfordern ein Konto.',
  'userProfile.signin.cta': 'Anmelden',
  'userProfile.announce.blocked': 'Person blockiert',
  'userProfile.announce.blockFailed': 'Blockieren nicht möglich',
  'userProfile.announce.writeFailed': 'Die Unterhaltung konnte nicht geöffnet werden',

  'a11y.floating.rung.discover.requests.one': 'Entdecken, {count} Anfrage erhalten',
  'a11y.floating.rung.discover.requests.other': 'Entdecken, {count} Anfragen erhalten',

  'links.hub.banner.title': 'Deine Links verwalten',
  'links.hub.banner.subtitle': 'Lade ein, wen du willst, in deine Unterhaltungen',
  'links.hub.share.title': 'Freigabelinks',
  'links.hub.share.description': 'Lade Kontakte in deine Unterhaltungen ein',
  'links.hub.share.create': 'Freigabelink erstellen',
  'links.share.back': 'Zurück zu Meine Links',
  'links.share.stats.total': 'Links',
  'links.share.stats.active': 'Aktiv',
  'links.share.stats.joined': 'Beigetreten',
  'links.share.joined.one': '{count} beigetreten',
  'links.share.joined.other': '{count} beigetreten',
  'links.share.copy': 'Link kopieren',
  'links.share.empty.title': 'Keine Freigabelinks',
  'links.share.empty.subtitle': 'Erstelle einen Link, um Personen in eine Unterhaltung einzuladen',
  'links.share.loading': 'Links werden geladen',
  'links.share.allLoaded': 'Alle deine Links sind geladen',
  'links.status.active': 'Aktiv',
  'links.status.inactive': 'Inaktiv',
  'links.unlimited': 'Unbegrenzt',
  'links.error.title': 'Deine Links konnten nicht geladen werden',
  'links.error.body': 'Prüfe deine Verbindung und versuche es erneut.',
  'links.retry': 'Erneut versuchen',
  'links.offline.title': 'Offline',
  'links.offline.body': 'Deine Links bleiben lesbar; zum Ändern brauchst du eine Verbindung.',
  'links.detail.back': 'Zurück zu den Freigabelinks',
  'links.detail.copy': 'Kopieren',
  'links.detail.copied': 'Kopiert',
  'links.detail.share': 'Teilen',
  'links.detail.disable': 'Deaktivieren',
  'links.detail.activate': 'Aktivieren',
  'links.detail.stats': 'Statistiken',
  'links.detail.stats.uses': 'Nutzungen',
  'links.detail.stats.max': 'Maximum',
  'links.detail.info': 'Informationen',
  'links.detail.identifier': 'Kennung',
  'links.detail.createdAt': 'Erstellt am',
  'links.detail.expiresAt': 'Läuft ab am',
  'links.detail.reason.closed': 'Die Unterhaltung ist geschlossen: Über diesen Link kommt niemand mehr herein.',
  'links.detail.reason.expired': 'Dieser Link ist abgelaufen.',
  'links.detail.reason.revoked': 'Du hast diesen Link deaktiviert.',
  'links.detail.refused.title': 'Link nicht gefunden',
  'links.detail.refused.body': 'Dieser Link existiert nicht oder gehört nicht dir.',
  'links.detail.loading': 'Link wird geladen',
  'links.announce.copied': 'Link kopiert',
  'links.announce.copyFailed': 'Link konnte nicht kopiert werden',
  'links.announce.shareUnavailable': 'Teilen ist hier nicht verfügbar',
  'links.announce.disabled': 'Link deaktiviert',
  'links.announce.activated': 'Link aktiviert',
  'links.announce.toggleFailed': 'Dieser Link konnte nicht geändert werden',
  'links.announce.offline': 'Offline: Es wurde nichts gesendet.',
  'links.create.title': 'Neuer Freigabelink',
  'links.create.section.conversation': 'Unterhaltung',
  'links.create.choose': 'Gruppe oder Community wählen',
  'links.create.picker.title': 'Unterhaltung wählen',
  'links.create.picker.empty': 'Noch kann keine Unterhaltung einen Link erhalten.',
  'links.create.section.identity': 'Link-Identität',
  'links.create.name': 'Name des Links',
  'links.create.name.placeholder': 'z. B. Twitter-Freigabe',
  'links.create.description': 'Beschreibung (optional)',
  'links.create.description.placeholder': 'z. B. Tritt unserer Gruppe bei…',
  'links.create.section.access': 'Gastzugang',
  'links.create.section.access.subtitle': 'Was Besucher zum Beitreten angeben müssen',
  'links.create.access.account': 'Konto erforderlich',
  'links.create.access.account.caption': 'Nur Meeshy-Mitglieder können beitreten',
  'links.create.access.nickname': 'Spitzname erforderlich',
  'links.create.access.nickname.caption': 'Besucher müssen einen Spitznamen wählen',
  'links.create.access.email': 'E-Mail erforderlich',
  'links.create.access.email.caption': 'Besucher müssen ihre E-Mail-Adresse angeben',
  'links.create.access.birthday': 'Geburtsdatum erforderlich',
  'links.create.access.birthday.caption': 'Ermöglicht eine Altersprüfung',
  'links.create.section.permissions': 'Berechtigungen',
  'links.create.section.permissions.subtitle': 'Was anonyme Gäste tun dürfen',
  'links.create.permission.messages': 'Nachrichten senden',
  'links.create.permission.messages.caption': 'Gäste können in der Unterhaltung schreiben',
  'links.create.permission.images': 'Bilder senden',
  'links.create.permission.images.caption': 'Gäste können Fotos teilen',
  'links.create.permission.files': 'Dateien senden',
  'links.create.permission.files.caption': 'Gäste können Dokumente senden',
  'links.create.permission.history': 'Verlauf sehen',
  'links.create.permission.history.caption': 'Gäste sehen frühere Nachrichten',
  'links.create.section.limits': 'Grenzen',
  'links.create.section.limits.subtitle': 'Steuere Publikum und Gültigkeitsdauer des Links',
  'links.create.limit.uses': 'Nutzungen begrenzen',
  'links.create.limit.max.one': 'Höchstens {count} Nutzung',
  'links.create.limit.max.other': 'Höchstens {count} Nutzungen',
  'links.create.limit.count': 'Anzahl der Nutzungen',
  'links.create.limit.invalid': 'Wähle eine ganze Zahl zwischen 1 und {max}.',
  'links.create.expiration': 'Ablauf',
  'links.create.expiration.never': 'Nie',
  'links.create.expiration.h24': '24 Stunden',
  'links.create.expiration.d7': '7 Tage',
  'links.create.expiration.d30': '30 Tage',
  'links.create.expiration.m3': '3 Monate',
  'links.create.button': 'Freigabelink erstellen',
  'links.create.inprogress': 'Wird erstellt…',
  'links.create.error.conversation': 'Wähle zuerst eine Unterhaltung.',
  'links.create.error.offline': 'Offline: Der Link wurde nicht erstellt.',
  'links.create.error.refused': 'Du kannst für diese Unterhaltung keinen Link erstellen.',
  'links.create.error.default': 'Der Link konnte nicht erstellt werden. Versuche es erneut.',

  'feed.scene.carousel.previous': 'Vorherige Szene',
  'feed.scene.carousel.next': 'Nächste Szene',
  'feed.scene.mosaic.tile': 'Szene {index}',
  'feed.scene.mosaic.more': 'Szene {index}, und {count} weitere',
  'feed.scene.mosaic.video': 'Szene {index}, Video',
  'feed.scene.shared_by': 'Szene geteilt von {author}',
  'feed.scene.open.fullscreen': 'Doppelt tippen für Vollbild',
  'feed.scene.open.post': 'Doppelt tippen, um den Beitrag zu öffnen',
  'feed.scene.sound.muted': 'Ton stumm',
  'feed.scene.count': '{count} Szenen',
  'scene.fullscreen.play': 'Alles fortsetzen',
  'scene.fullscreen.pause': 'Alles anhalten',
  'scene.fullscreen.sound.on': 'Ton einschalten',
  'scene.fullscreen.sound.off': 'Ton ausschalten',
  'scene.place.here': 'Hier',

  'story.sound.off': 'Stumm',

  /* DAS STORY-STUDIO (#6900) — eine Story mit Hintergrund, Hintergrundton
     und Text erstellen, Vorschau über die gemeinsame Engine, veröffentlicht
     als CanvasV3 wie unter iOS. */
  'story.studio.title': 'Neue Story',
  'story.studio.cancel': 'Abbrechen',
  'story.studio.publish': 'Veröffentlichen',
  'story.studio.publishing': 'Wird veröffentlicht…',
  'story.studio.publish.waiting': 'Warte auf Netzwerk…',
  'story.studio.title.post': 'Neuer Beitrag',
  'story.studio.title.reel': 'Neues Reel',
  'story.studio.publish.as.story': 'Story veröffentlichen',
  'story.studio.publish.as.post': 'Beitrag veröffentlichen',
  'story.studio.publish.as.reel': 'Reel veröffentlichen',
  'story.studio.publish.menu': 'Veröffentlichen als',
  'story.studio.kind.story': 'Story',
  'story.studio.kind.post': 'Beitrag',
  'story.studio.kind.reel': 'Reel',
  'story.studio.refusal.reel': 'Ein Reel braucht ein Video oder einen Ton von mindestens 3 Sekunden oder mindestens zwei Bilder.',
  'story.studio.refusal.story-pages': 'Eine Story trägt nur eine Szene: Veröffentliche sie als Beitrag oder entferne die anderen Szenen.',
  'story.studio.offline': 'Offline — die Story wird veröffentlicht, sobald das Netzwerk zurück ist.',
  'story.studio.stage': 'Story-Vorschau',
  'story.studio.background.add': 'Foto oder Video hinzufügen',
  'story.studio.background.label': 'Hintergrund',
  'story.studio.background.remove': 'Hintergrund entfernen',
  'story.studio.sound.add': 'Ton hinzufügen',
  'story.studio.sound.label': 'Hintergrundton',
  'story.studio.sound.remove': 'Ton entfernen',
  'story.studio.sound.mute': 'Ton stummschalten',
  'story.studio.sound.unmute': 'Ton aktivieren',
  'story.studio.upload.progress': 'Wird gesendet… {percent} %',
  'story.studio.upload.ready': 'Bereit',
  'story.studio.upload.retry': 'Erneut versuchen',
  'story.studio.text.label': 'Story-Text',
  'story.studio.text.placeholder': 'Text hinzufügen',
  'story.studio.hint.duration': 'Eine Story bleibt zwanzig Stunden sichtbar.',
  'story.studio.error.upload': 'Die Datei konnte nicht gesendet werden.',
  'story.studio.error.publish': 'Die Story konnte nicht veröffentlicht werden.',
  'story.studio.refusal.title': 'Zum Erstellen einer Story ist ein Konto erforderlich.',
  'story.studio.refusal.login': 'Anmelden',
  'story.studio.refusal.door.visual': 'Wähle ein Bild oder ein Video.',
  'story.studio.refusal.door.sound': 'Wähle eine Audiodatei.',
  'story.studio.refusal.media-max': 'Diese Veröffentlichung trägt bereits zehn Medien – die Obergrenze der Plattform.',
  'story.studio.failure.network': 'Netzwerk nicht verfügbar.',
  'story.studio.failure.timeout': 'Der Server hat nicht geantwortet.',
  'story.studio.failure.session': 'Sitzung abgelaufen — bitte erneut anmelden.',
  'story.studio.failure.account': 'Zum Veröffentlichen von Medien ist ein Konto erforderlich.',
  'story.studio.failure.forbidden': 'Aktion für dieses Konto nicht erlaubt.',
  'story.studio.failure.tooLarge': 'Datei zu groß.',
  'story.studio.failure.fileRefused': 'Datei abgelehnt: Ihr Typ entspricht nicht ihrem Inhalt.',
  'story.studio.failure.rateLimited': 'Zu viele Beiträge auf einmal — versuche es gleich noch einmal.',
  'story.studio.failure.refused': 'Veröffentlichung abgelehnt.',
  'story.studio.failure.unavailable': 'Der Server ist nicht verfügbar.',
  'story.studio.text.add': 'Text hinzufügen',
  'story.studio.text.remove': 'Diesen Text entfernen',
  'story.studio.object.text': 'Text {index}',
  'story.studio.object.overlay': 'Ebene',
  'story.studio.object.select': '{name} auswählen',
  'story.studio.objects.label': 'Objekte der Szene',
  'story.studio.overlay.add': 'Ein Bild auf die Szene legen',
  'story.studio.overlay.label': 'Ebene',
  'story.studio.overlay.remove': 'Ebene entfernen',
  'story.studio.pages.label': 'Szenen der Veröffentlichung',
  'story.studio.page.position': 'Szene {index} von {count}',
  'story.studio.page.add': 'Szene erstellen',
  'story.studio.page.remove': 'Szene {index} löschen',
  'story.studio.page.failed': 'ein Medium konnte nicht hochgeladen werden',
  'story.studio.layout.title': 'Anordnung der Szenen',
  'story.studio.layout.carousel': 'Einzeln nacheinander',
  'story.studio.layout.reel': 'Fortlaufendes Scrollen',
  'story.studio.layout.hero': 'Eine groß, die anderen daneben',
  'story.studio.layout.wave': 'Wellenförmig',
  'story.studio.layout.sine': 'Zickzack',
  'story.studio.caption.label': 'Bildunterschrift für {media}',
  'story.studio.caption.placeholder': 'Bildunterschrift hinzufügen',
  'story.studio.sound.plane.label': 'Platzierung des Tons',
  'story.studio.sound.plane.background': 'Im Hintergrund',
  'story.studio.sound.plane.foreground': 'Auf der Szene',
  'story.studio.editor.label': 'Objekteinstellungen',
  'story.studio.editor.style': 'Schrift',
  'story.studio.editor.effect': 'Effekt',
  'story.studio.editor.color': 'Farbe',
  'story.studio.editor.align': 'Ausrichtung',
  'story.studio.editor.background': 'Texthintergrund',
  'story.studio.editor.language': 'Sprache des Textes',
  'story.studio.editor.none': 'Keiner',
  'story.studio.editor.empty': 'Wählen Sie ein Objekt aus, um es anzupassen.',
  'story.studio.style.bold': 'Fett',
  'story.studio.style.neon': 'Neon',
  'story.studio.style.classic': 'Klassisch',
  'story.studio.style.italic': 'Kursiv',
  'story.studio.style.typewriter': 'Schreibmaschine',
  'story.studio.style.handwriting': 'Handschrift',
  'story.studio.style.calligraphy': 'Kalligrafie',
  'story.studio.style.cartoon': 'Comic',
  'story.studio.style.futuristic': 'Futuristisch',
  'story.studio.style.fantasy': 'Fantasy',
  'story.studio.style.curve': 'Schwung',
  'story.studio.style.tag': 'Graffiti',
  'story.studio.style.retro': 'Retro',
  'story.studio.style.elegant': 'Elegant',
  'story.studio.style.poster': 'Plakat',
  'story.studio.style.bubble': 'Blase',
  'story.studio.style.note': 'Notiz',
  'story.studio.style.brush': 'Pinsel',
  'story.studio.effect.glow': 'Leuchten',
  'story.studio.effect.neon': 'Neon',
  'story.studio.effect.outline': 'Kontur',
  'story.studio.effect.shadow': 'Schatten',
  'story.studio.effect.longShadow': 'Langer Schatten',
  'story.studio.effect.emboss': 'Relief',
  'story.studio.color.FFFFFF': 'Weiß',
  'story.studio.color.000000': 'Schwarz',
  'story.studio.color.FF2E63': 'Pink',
  'story.studio.color.08D9D6': 'Türkis',
  'story.studio.color.F8B500': 'Bernstein',
  'story.studio.color.9B59B6': 'Violett',
  'story.studio.color.2ECC71': 'Grün',
  'story.studio.color.3498DB': 'Blau',
  'story.studio.align.left': 'Links',
  'story.studio.align.center': 'Mitte',
  'story.studio.align.right': 'Rechts',
  'story.studio.pose.label': 'Position und Größe',
  'story.studio.pose.bigger': 'Vergrößern',
  'story.studio.pose.smaller': 'Verkleinern',
  'story.studio.pose.rotateLeft': 'Nach links drehen',
  'story.studio.pose.rotateRight': 'Nach rechts drehen',
  'story.studio.pose.reset': 'Zentrieren',
  'story.studio.pose.handle': '{name} verschieben — Pfeile zum Verschieben, + und − für die Größe, [ und ] zum Drehen',
  'story.studio.pose.grip': '{name} skalieren und drehen',

  /* DIE ZIELGRUPPEN-AUSWAHL DES STUDIOS (#7683) — die sechs PostVisibility,
     Spiegel von PostVisibility.swift (packages/MeeshySDK). */
  'story.studio.audience.chip.label': 'Zielgruppe',
  'story.studio.audience.title': 'Zielgruppe',
  'story.studio.audience.public': 'Öffentlich',
  'story.studio.audience.community': 'Communitys',
  'story.studio.audience.friends': 'Kontakte',
  'story.studio.audience.except': 'Außer…',
  'story.studio.audience.only': 'Nur…',
  'story.studio.audience.private': 'Privat',
  'story.studio.audience.subtitle.public': 'Alle, auch Nicht-Follower',
  'story.studio.audience.subtitle.community': 'Mitglieder deiner Communitys',
  'story.studio.audience.subtitle.friends': 'Deine akzeptierten Kontakte',
  'story.studio.audience.subtitle.private': 'Nur du — nichts wird veröffentlicht',
  'story.studio.audience.refusal.people': 'Die Personenauswahl ist im Web noch nicht verfügbar.',
  'story.studio.audience.scope': 'Die gewählte Zielgruppe gehört zur Veröffentlichung, nie zu einem Format: ein Formatwechsel behält sie bei.',
  'story.studio.audience.defaultMark': 'Standard',

  'appUpdate.available': 'Eine neue Version von Meeshy ist verfügbar!',
  'appUpdate.hint': 'Neu laden, um die neuesten Funktionen zu erhalten.',
  'appUpdate.action': 'Aktualisieren',
  'appUpdate.dismiss': 'Warten',
  'appUpdate.applying': 'Wird aktualisiert…',
  'appUpdate.region': 'App-Aktualisierung',

  'story.action.rail': 'Story-Aktionen',
  'story.action.react': 'Reagieren',
  'story.action.reply': 'Antworten',
  'story.action.forward': 'Senden',
  'story.action.repost': 'Reposten',
  'story.action.views': 'Aufrufe',
  'story.action.share': 'Teilen',
  'story.action.save': 'Speichern',
  'story.action.comments': 'Kommentare',
  'story.action.translations': 'Übersetzungen',
  'story.views.empty.title': 'Noch keine Aufrufe',
  'story.views.empty.subtitle': 'Personen, die deine Story ansehen, erscheinen hier.',
  'story.views.count.one': '{count} Aufruf',
  'story.views.count.other': '{count} Aufrufe',
  'story.save.progress': 'Speichern {percent} %',
  'story.save.cancel': 'Speichern abbrechen',
  'story.save.success': 'Story gespeichert',
  'story.save.failed': 'Speichern fehlgeschlagen',
  'story.save.cancelled': 'Export abgebrochen',
  'prism.translated.message': 'Übersetzte Nachricht',
  'prism.translated.comment': 'Übersetzter Kommentar',
  'prism.translated.post': 'Übersetzter Beitrag',
  'prism.original.show.message': 'Nachricht in der Originalsprache anzeigen',
  'prism.original.show.comment': 'Kommentar in der Originalsprache anzeigen',
  'prism.original.show.post': 'Beitrag in der Originalsprache anzeigen',
  'prism.original.hide.message': 'Nachricht in der Originalsprache ausblenden',
  'prism.original.hide.comment': 'Kommentar in der Originalsprache ausblenden',
  'prism.original.hide.post': 'Beitrag in der Originalsprache ausblenden',

  'comments.title': 'Kommentare',
  'comments.close': 'Kommentare schließen',
  'comments.loading': 'Kommentare werden geladen',
  'comments.empty': 'Noch keine Kommentare',
  'comments.empty.hint': 'Schreiben Sie den ersten Kommentar.',
  'comments.error': 'Kommentare konnten nicht geladen werden',
  'comments.error.hint': 'Versuchen Sie es gleich noch einmal.',
  'comments.retry': 'Erneut versuchen',
  'comments.more': 'Mehr Kommentare laden',
  'comments.offline': 'Offline — es werden nur bereits geladene Kommentare angezeigt.',
  'comments.placeholder': 'Kommentar schreiben…',
  'comments.send': 'Kommentar senden',
  'comments.row.pending': 'Wird gesendet',
  'comments.signin': 'Melden Sie sich an, um zu kommentieren.',
  'comment.send.error': 'Der Kommentar konnte nicht veröffentlicht werden.',
  'comment.send.pending': 'Kommentar nicht bestätigt — offline',
  'comment.send.empty': 'Schreiben Sie etwas, bevor Sie senden.',
  'comments.action.like': 'Gefällt mir',
  'comments.action.unlike': 'Gefällt mir nicht mehr',
  'comments.action.edit': 'Bearbeiten',
  'comments.action.delete': 'Löschen',
  'comments.action.delete.confirm': 'Bestätigen',
  'comments.edit.label': 'Kommentar bearbeiten',
  'comments.edit.save': 'Speichern',
  'comments.edit.cancel': 'Abbrechen',
  'comment.like.error': 'Ihr „Gefällt mir“ wurde nicht gespeichert.',
  'comment.edit.error': 'Die Änderung wurde nicht gespeichert.',
  'comment.delete.error': 'Der Kommentar konnte nicht gelöscht werden.',
  'comment.gesture.pending': 'Aktion nicht bestätigt — offline',
  'comment.gesture.unconfirmed': 'Aktion nicht bestätigt — das Gateway hat nicht geantwortet.',
  'comment.refused.session': 'Sitzung abgelaufen — bitte neu anmelden.',
  'comment.refused.right': 'Diese Aktion steht dir nicht offen.',
  'comment.like.limit': 'Höchstens fünf Reaktionen pro Person.',
  'feed.action.comment': 'Kommentieren',

  'admin.title': 'Verwaltung',

  'thread.unread-separator.one': '{count} ungelesene Nachricht',
  'thread.unread-separator.other': '{count} ungelesene Nachrichten',
  'message-detail.info.title': 'Nachrichteninfo',
  'message-detail.received-by': 'Erhalten von',
  'message-detail.read-by': 'Gelesen von',
  'message-detail.not-yet': 'Noch nicht',
  'message-detail.received-by.empty': 'Noch keine Zustellbestätigung',
  'message-detail.read-by.empty': 'Diese Nachricht wurde noch von niemandem gelesen',
  'message-detail.not-yet.empty': 'Alle haben die Nachricht erhalten',
  'message-detail.open': 'Nachrichtendetails anzeigen',
  'message-detail.attachment.opens.one': '{count} Öffnung',
  'message-detail.attachment.opens.other': '{count} Öffnungen',
  'message-detail.attachment.downloads.one': '{count} Download',
  'message-detail.attachment.downloads.other': '{count} Downloads',
  'message-detail.attachment.listened-until': 'Angehört bis {time}',
  'message-detail.attachment.watched-until': 'Angesehen bis {time}',
  'message-detail.attachment.complete': 'Vollständig',
  'message-detail.attachment.listen.empty': 'Noch nicht angehört',
  'message-detail.attachment.watch.empty': 'Noch nicht angesehen',
  'message-detail.attachment.open': '{name} öffnen',
  'message-detail.attachment.opened.empty': 'Noch nicht geöffnet',
  'message-detail.loading': 'Wird geladen…',
  'message-detail.load-error': 'Diese Informationen konnten nicht geladen werden',
  'message-detail.retry': 'Erneut versuchen',

  'download.title': 'Meeshy holen',
  'download.body': 'Schreibe in deiner Sprache und lies in deiner: Meeshy übersetzt jede Nachricht unterwegs.',
  'download.appStore': 'Laden im App Store',
  'download.web': 'Meeshy im Browser öffnen',
  'download.otherPlatforms': 'Auf Android und am Computer läuft Meeshy direkt im Browser.',

  /* LES SOURCES DU COMPOSEUR (#7280) — miroir de `composer.attach.*` d'iOS. */
  'composer.attach.group': 'Anhangstypen',
  'composer.attach.handle': 'Bedienleiste',
  'composer.attach.photo': 'Fotos',
  'composer.attach.photo.action': 'Fotos auswählen',
  'composer.attach.camera': 'Kamera',
  'composer.attach.camera.action': 'Foto aufnehmen',
  'composer.attach.file': 'Datei',
  'composer.attach.file.action': 'Datei auswählen',
  'composer.attach.location': 'Standort',
  'composer.attach.location.action': 'Meinen Standort teilen',
  'composer.attach.voice': 'Sprache',
  'composer.attach.voice.action': 'Sprachnachricht aufnehmen',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Emoji einfügen',
  'composer.emoji.title': 'Emoji einfügen',
  'composer.location.locating': 'Standort wird gesucht…',
  'composer.location.denied': 'Standort verweigert — in den Einstellungen erlauben',
  'composer.location.unavailable': 'Standort in diesem Browser nicht verfügbar',
  'composer.location.failed': 'Standort nicht gefunden — erneut versuchen',
  'composer.location.chip': 'ORT',
  'composer.location.unknown': 'Unbekannter Ort',
  'composer.location.remove': 'Standort entfernen',
  'composer.viewOnce.activate': 'Einmalansicht aktivieren',
  'composer.viewOnce.active': 'Einmalansicht aktiv',
  'composer.viewOnce.label': 'Einmalansicht',
  'composer.protection.ephemeral.state': 'Ephemerer Modus aktiv',
  'composer.protection.blur.state': 'Unschärfemodus aktiv',
  'message.location.shared': 'Geteilter Standort',
  'message.location.open': 'In Karten öffnen',
  'message.location.a11y': 'Standort: {place}',

  /* LES LIBELLÉS D'ÉTAT DU FIL (#7337) — voir `catalog-fr.ts` pour la règle. */
  'message.forwarded': 'Weitergeleitet',
  'message.forwarded.fromGroup': 'Weitergeleitet aus {name}',
  'message.forwarded.fromPerson': 'Weitergeleitet von {name}',
  'message.send.failed': 'Nicht gesendet',
  'message.send.failed.reason': 'Nicht gesendet — {reason}',
  'message.send.retry': 'Erneut versuchen',
  'announce.messageNotSent': 'Nachricht nicht gesendet',
  'announce.messageNotSent.reason': 'Nachricht nicht gesendet — {reason}',
  'message.deleted': 'Nachricht gelöscht',
  'message.expired.a11y': 'Flüchtige Nachricht abgelaufen',
  'message.withheld': 'Inhalt zurückgehalten',
  'message.withheld.a11y': 'Inhalt zurückgehalten: Diese Nachricht existiert und wird nicht angezeigt',
  'message.veiled': 'Ausgeblendeter Inhalt',
  'message.veiled.hint': 'Tippen, um den Inhalt anzuzeigen',
  'message.veiled.error': 'Anzeigen derzeit nicht möglich',
  'message.ephemeral.a11y': 'Selbstlöschende Nachricht, verschwindet in {remaining}',
  'message.ephemeral.awaiting': 'Wartet auf den Empfang',
  'message.ephemeral.awaiting.a11y': 'Selbstlöschende Nachricht von {duration}, wartet auf den Empfang',
  'message.viewOnce.tap': 'Zum Anzeigen tippen',
  'message.viewOnce.opened': 'Bereits geöffnet',
  'message.viewOnce.sealed.a11y': 'Einmal-Nachricht, zum Anzeigen tippen',
  'message.viewOnce.opened.a11y': 'Einmal-Nachricht, bereits geöffnet',
  'message.viewOnce.close': 'Schließen',
  'attachment.protected.image': 'Geschütztes Foto',
  'attachment.protected.video': 'Geschütztes Video',
  'attachment.protected.audio': 'Geschützte Sprachnachricht',
  'attachment.protected.file': 'Geschützter Anhang',
  'attachment.kind.image': 'Foto',
  'attachment.kind.video': 'Video',
  'attachment.kind.audio': 'Audio',
  'attachment.kind.file': 'Datei',

  /* Le menu du message, sa barre de sélection et sa feuille « Plus… » (#7555). */
  'message.menu.select': 'Auswählen',
  'message.menu.translate': 'Übersetzen',
  'message.menu.copy': 'Kopieren',
  'message.menu.forward': 'Weiterleiten',
  'message.menu.reply': 'Antworten',
  'message.menu.more': 'Mehr…',
  'message.menu.react': 'Reagieren',
  'message.menu.addReaction': 'Reaktion hinzufügen',
  'message.selection.toolbar': 'Nachrichtenauswahl',
  'message.selection.count': '{count} ausgewählt',
  'message.detail.title': 'Nachrichtendetails',
  'message.detail.languages': 'Sprachen',
  'message.detail.reactions': 'Reaktionen',
  'message.detail.sent': 'Gesendet',
  'message.detail.language.original': '{language} (Original)',

} satisfies InterfaceCatalog;

export default de;
