import type { InterfaceCatalog } from '@/lib/i18n-catalog';
import esComposerAttach from './catalog-es-composer-attach';
import esIdentity from './catalog-es-identity';
import esVerifyEmail from './catalog-es-verify-email';
import esPassword from './catalog-es-password';
import esCall from './catalog-es-call';
import esCallJoin from './catalog-es-call-join';
import esCallShell from './catalog-es-call-shell';
import esCallDevices from './catalog-es-call-devices';
import esSignup from './catalog-es-signup';

import esMentions from './catalog-es-mentions';
import esStoriesMine from './catalog-es-stories-mine';

const es = {
  'announce.messageSent': 'Mensaje enviado',
  'announce.messageCopied': 'Mensaje copiado',
  'announce.messagesCopied': 'Mensajes copiados',
  'announce.messageProtected': 'Mensaje protegido',
  'announce.selectionCap': 'Máximo {count} mensajes',
  'announce.nothingToCopy': 'Nada que copiar',

  'message.author.self': 'Tú',
  'message.excerpt.protected': 'contenido protegido',
  'a11y.message.menu.subject': 'Acciones del mensaje de {author}: {excerpt}',

  'selection.toolbar': 'Selección de mensajes',
  'selection.cancel': 'Cancelar',
  'selection.count': '{count} seleccionados',
  'forward.title': 'Reenviar a…',
  'forward.empty': 'Ninguna conversación',
  'forward.search.label': 'Buscar una conversación',
  'forward.search.placeholder': 'Buscar',
  'forward.announce.sent': 'Mensaje reenviado',
  'forward.announce.sentMany': '{count} mensajes reenviados',
  'forward.announce.failed': 'No se pudo reenviar',
  'forward.refusal.viewOnce': 'Un mensaje de visualización única no se puede reenviar',
  'forward.refusal.unavailable': 'El mensaje original ya no está disponible: nada que reenviar',

  'typing.named': '{name} está escribiendo',
  'typing.double': '{first} y {second} están escribiendo',
  'typing.several': 'Varias personas están escribiendo',

  'feed.header.reels': 'Ver Reels',
  'reels.title': 'Reels',
  'reels.back': 'Atrás',
  'reels.open': 'Ver el reel de {author}',
  'reels.item': 'Reel de {author}, {index} de {count}',
  'reels.loading': 'Cargando reels',
  'reels.empty': 'Aún no hay reels',
  'reels.empty.hint': 'Los reels de tus contactos aparecerán aquí.',
  'reels.error': 'No se pudieron cargar los reels',
  'reels.error.hint': 'Inténtalo de nuevo en un momento.',
  'reels.retry': 'Reintentar',
  'reels.offline': 'Sin conexión',
  'reels.offline.cold': 'Los reels se cargarán cuando vuelva la conexión.',
  'reels.action.like': 'Me gusta',
  'reels.action.bookmark': 'Guardar',
  'reels.action.share': 'Compartir',
  'reels.sound.on': 'Activar el sonido',
  'reels.sound.off': 'Silenciar',
  'reels.play': 'Reproducir el reel',
  'reels.pause': 'Pausar el reel',
  'reels.media.error': 'No se puede reproducir — Reintentar',
  'reels.image': 'Imagen {index} de {count}',

  'stories.title': 'Historias',
  'stories.loading': 'Cargando historias…',
  'stories.error': 'No se pudieron cargar las historias.',
  'stories.empty.title': 'Aún no hay historias',
  'stories.empty.subtitle': 'Las historias de tus contactos aparecerán aquí durante veinte horas.',
  'stories.create': 'Crear una historia',
  'stories.count.one': '{count} historia',
  'stories.count.other': '{count} historias',
  'stories.mine': 'Tu historia',

  /* #6150 — las dos puertas de mi propia celda del carril. */
  'stories.self.addStory': 'Añadir una historia',
  'stories.self.mood.add': 'Poner un estado de ánimo',
  'stories.self.mood.change': 'Cambiar mi estado de ánimo, {emoji}',

  'status.compose.title': 'Mi estado de ánimo',
  'status.compose.pick': 'Elegir un estado de ánimo',
  'status.compose.note': 'Una palabra, si quieres',
  'status.compose.publish': 'Publicar',
  'status.compose.publishing': 'Publicando…',
  'status.compose.error': 'No se pudo publicar tu estado de ánimo.',
  'status.compose.offline': 'Sin conexión — tu estado de ánimo saldrá cuando vuelva la red.',

  'feed.header.create': 'Crear una publicación o un reel',
  'feed.create.post': 'Publicación',
  'feed.create.reel': 'Reel',

  'feed.post.action.like': 'Me gusta',
  'feed.post.action.comment': 'Comentar',
  'feed.post.action.repost': 'Republicar',
  'feed.post.action.bookmark': 'Guardar',
  'feed.post.action.share': 'Compartir',
  'feed.post.media.video': 'Vídeo',
  'feed.post.media.audio': 'Audio',
  'feed.post.media.previous': 'Media anterior',
  'feed.post.media.next': 'Media siguiente',
  'feed.post.media.mosaic': 'Mosaico de {count} medios',
  'media.unavailable': 'Medio no disponible',
  'feed.post.see_more': 'ver más',
  'feed.post.see_less': 'ver menos',
  'feed.post.more_options': 'Más opciones',
  'feed.post.menu.open': 'Abrir',
  'feed.post.menu.copy_text': 'Copiar el texto',
  'feed.post.menu.unsave': 'Quitar de guardados',
  'feed.post.menu.pin': 'Fijar',
  'feed.post.menu.delete': 'Eliminar',
  'feed.post.edit': 'Editar',
  'feed.post.edit.title': 'Editar publicación',
  'feed.post.edit.body.a11y': 'Contenido de la publicación',
  'feed.post.edit.remaining.a11y': '{count} caracteres restantes',
  'feed.post.edit.publish': 'Publicar',
  'report.post.title': 'Denunciar esta publicación',
  'feed.post.copied': 'Texto copiado',
  'feed.post.copy_failed': 'No se pudo copiar el texto',
  'feed.post.pinned': 'Publicación fijada',
  'feed.post.pin_failed': 'No se pudo fijar la publicación',
  'feed.post.edited': 'Publicación actualizada',
  'feed.post.edit_failed': 'No se pudo actualizar la publicación',
  'feed.post.edit_busy': 'Ya hay una edición en curso',
  'feed.post.deleted': 'Publicación eliminada',
  'feed.post.delete_failed': 'Error al eliminar',
  'feed.post.repost.success': 'Republicado',
  'feed.post.repost.error': 'No se pudo republicar',
  'feed.post.repost.already': 'Ya republicado',
  'feed.post.repost.offline': 'Sin conexión — la republicación no pudo salir.',
  'feed.post.repost.unconfirmed': 'Republicación no confirmada — inténtalo de nuevo',
  'feed.post.repost.audience': 'Esa audiencia ampliaría el alcance de la publicación original',
  'feed.post.repost.confirm.title': '¿Republicar esta publicación?',
  'feed.post.repost.confirm.body': 'Aparecerá en tu feed, visible para tus seguidores. Esta acción no se puede deshacer.',
  'feed.post.reel.chip': 'Reel',
  'feed.post.repost.embed.story': 'Historia',
  'feed.post.reel.of': 'Reel de {author}',
  'feed.post.open': 'Abrir la publicación de {author}',
  'feed.post.original.open': 'Publicación original de {author}',
  /* LES PUBLICATIONS ENREGISTRÉES (#7286) — l'écran `/me/bookmarks` et sa rangée de Réglages › Outils. */
  'bookmarks.title': 'Publicaciones guardadas',
  'bookmarks.back': 'Volver a los ajustes',
  'bookmarks.loading': 'Cargando tus publicaciones guardadas',
  'bookmarks.empty.title': 'Aún no hay publicaciones guardadas',
  'bookmarks.empty.subtitle': 'Toca el marcador debajo de una publicación para guardarla aquí y volver a leerla cuando quieras.',
  'bookmarks.empty.cta': 'Abrir el Feed',
  'bookmarks.error.title': 'No se pudieron cargar tus publicaciones guardadas',
  'bookmarks.error.body': 'Inténtalo de nuevo en un momento.',
  'bookmarks.offline.body': 'Tus publicaciones guardadas aparecerán al reconectarte.',
  'bookmarks.allLoaded': 'Todas tus publicaciones guardadas están cargadas',
  'bookmarks.filter.all': 'Todo',
  'bookmarks.filter.posts': 'Publicaciones',
  'bookmarks.filter.reels': 'Reels',
  'bookmarks.filter.a11y': 'Filtrar publicaciones guardadas',
  'settings.tools.bookmarks': 'Publicaciones guardadas',
  'action.star': 'Añadir a favoritos',
  'action.unstar': 'Quitar de favoritos',
  'announce.messageStarred': 'Añadido a favoritos',
  'announce.messageUnstarred': 'Quitado de favoritos',
  'starred.messages.pending': 'Favorito sin confirmar — sin conexión',
  'starred.messages.error': 'No se pudo modificar el favorito',
  'starred.messages.notStarrable': 'Este mensaje no se puede añadir a favoritos',
  'settings.tools.starred': 'Mensajes destacados',
  'starred.messages.title': 'Mensajes favoritos',
  'starred.messages.back': 'Volver a los ajustes',
  'starred.messages.loading': 'Cargando tus mensajes favoritos',
  'starred.messages.empty.title': 'No hay mensajes favoritos',
  'starred.messages.empty.subtitle': 'Mantén pulsado un mensaje y elige «Añadir a favoritos» para encontrarlo aquí.',
  'starred.messages.empty.cta': 'Abrir las conversaciones',
  'starred.messages.error.title': 'No se pudieron cargar tus mensajes favoritos',
  'starred.messages.error.body': 'Inténtalo de nuevo en un momento.',
  'starred.messages.offline.body': 'Tus mensajes favoritos aparecerán al reconectarte.',
  'starred.messages.allLoaded': 'Todos tus mensajes favoritos están cargados',
  'starred.messages.row.hint': 'Abre la conversación',
  'starred.messages.remove.a11y': 'Quitar el mensaje de {author} de favoritos',
  'starred.messages.protected': 'Mensaje protegido',
  'starred.messages.noText': 'Mensaje sin texto',
  'starred.messages.media.image': 'Foto',
  'starred.messages.media.video': 'Vídeo',
  'starred.messages.media.audio': 'Audio',
  'starred.messages.media.file': 'Archivo',
  'common.unknown_user': 'Usuario',
  'feed.error.title': 'No se pudo cargar el feed',
  'feed.error.body': 'Inténtalo de nuevo en un momento.',
  'feed.offline.title': 'Sin conexión',
  'feed.offline.body': 'El feed aparecerá cuando vuelvas a estar en línea.',
  'feed.retry': 'Reintentar',
  'feed.empty.title': 'Aún no hay publicaciones',
  'feed.empty.subtitle': 'Las publicaciones de tus contactos aparecerán aquí.',
  'feed.loading': 'Cargando el feed',
  'feed.allLoaded': 'Todas las publicaciones están cargadas',
  'feed.newPosts.one': '{count} publicación nueva',
  'feed.newPosts.other': '{count} publicaciones nuevas',
  ...esIdentity,
  ...esVerifyEmail,
  ...esPassword,
  ...esCall,
  ...esCallJoin,
  ...esCallShell,
  ...esCallDevices,
  ...esSignup,
  'userProfile.self.edit': 'Editar mi perfil',
  'report.title': 'Denunciar esta cuenta',
  'report.body': 'Elija el motivo de su denuncia. Nuestro equipo de moderación la recibirá.',
  'report.action': 'Denunciar',
  'report.done': 'Denuncia enviada',
  'report.throttled': 'Demasiadas denuncias — inténtelo de nuevo en un momento',
  'report.failed': 'No se pudo enviar la denuncia',
  'report.reason.spam': 'Spam',
  'report.reason.inappropriate': 'Contenido inapropiado',
  'report.reason.harassment': 'Acoso',
  'report.reason.violence': 'Violencia',
  'report.reason.hate_speech': 'Discurso de odio',
  'report.reason.fake_profile': 'Perfil falso',
  'report.reason.impersonation': 'Suplantación de identidad',
  'report.reason.other': 'Otro',
  'feed.like.error': 'Error al dar me gusta',
  'post.bookmark.error': 'No se pudo guardar',
  'feed.gesture.pending': 'Acción no confirmada — sin conexión',
  'feed.share.error': 'Error al compartir la publicación',
  'feed.share.copied': 'Enlace copiado — ya solo queda pegarlo.',
  'feed.share.text': 'Una publicación en Meeshy',

  'root.menu.feed': 'Feed',
  'root.menu.links': 'Mis enlaces',
  'root.menu.notifications': 'Notificaciones',
  'root.menu.calls': 'Llamadas',
  'root.menu.discover': 'Descubrir',
  'root.menu.communities': 'Comunidades',
  'root.menu.settings': 'Ajustes',
  'root.menu.profile': 'Perfil',
  'root.menu.conversations': 'Conversaciones',
  'a11y.floating.feed.hint': 'Mantén pulsado para abrir los Reels',
  'a11y.floating.menu': 'Menú',
  'a11y.floating.menu.ladder': 'Navegación de Meeshy',
  'a11y.floating.menu.unread.one': 'Menú, {count} notificación no leída',
  'a11y.floating.menu.unread.other': 'Menú, {count} notificaciones no leídas',
  'a11y.floating.rung.notifications.unread.one': 'Notificaciones, {count} no leída',
  'a11y.floating.rung.notifications.unread.other': 'Notificaciones, {count} no leídas',

  'notifications.category.all': 'Todas',
  'notifications.category.unread': 'No leídas',
  'notifications.category.messages': 'Mensajes',
  'notifications.category.reactions': 'Reacciones',
  'notifications.category.mentions': 'Menciones',
  'notifications.category.social': 'Social',
  'notifications.category.contacts': 'Contactos',
  'notifications.category.groups': 'Grupos',
  'notifications.category.calls': 'Llamadas',
  'notifications.category.translations': 'Traducciones',
  'notifications.category.system': 'Sistema',
  'notifications.categories': 'Categorías de notificaciones',
  'notifications.markAllRead': 'Marcar todo como leído',
  'notifications.unreadCount.one': '{count} no leída',
  'notifications.unreadCount.other': '{count} no leídas',
  'notifications.unread': 'No leída',
  'notifications.empty.all': 'No hay notificaciones',
  'notifications.empty.unread': 'No hay notificaciones no leídas',
  'notifications.empty.category': 'No hay notificaciones en «{category}»',
  'notifications.empty.subtitle': 'Tus notificaciones aparecerán aquí',
  'notifications.loading': 'Cargando notificaciones',
  'notifications.error.title': 'No se pudieron cargar las notificaciones',
  'notifications.error.body': 'Inténtalo de nuevo en un momento.',
  'notifications.offline.title': 'Sin conexión',
  'notifications.offline.body': 'Tus notificaciones aparecerán cuando vuelvas a estar en línea.',
  'notifications.retry': 'Reintentar',
  'notifications.allLoaded': 'Todas las notificaciones están cargadas',
  'notifications.actions': 'Acciones de la notificación',
  'notifications.action.markRead': 'Marcar como leída',
  'notifications.action.delete': 'Eliminar',
  'notifications.failure': 'La acción no se completó. Inténtalo de nuevo.',

  'notFound.title': 'Esta dirección no existe.',

  'pending.back': 'Volver a las conversaciones',

  'linkPage.home': 'Volver a Meeshy',
  'linkPage.retry': 'Reintentar',
  'linkPage.settings': 'Abrir los ajustes',
  'linkPage.signIn': 'Iniciar sesión',
  'linkPage.offline.title': 'Sin conexión',
  'linkPage.offline.body': 'Vuelve a conectarte a Internet y reinténtalo.',
  'linkPage.unavailable.title': 'Meeshy no responde',
  'linkPage.unavailable.body': 'El servicio no está disponible por el momento. Reinténtalo en unos instantes.',
  'linkPage.rateLimited': 'Demasiados intentos. Espera un momento antes de reintentarlo.',
  'linkPage.signedOut.title': 'Inicia sesión para continuar',
  'linkPage.signedOut.body': 'Este enlace actúa sobre tu cuenta. Inicia sesión y vuelve a abrirlo desde el correo.',
  'linkPage.expired': 'Este enlace ha caducado. Vuelve a hacer la solicitud desde los ajustes.',
  'trackingLink.opening': 'Abriendo el enlace…',
  'trackingLink.dead.title': 'Este enlace ya no está disponible',
  'trackingLink.dead.body': 'Ha caducado, se ha desactivado o nunca ha existido.',
  'accountDeletion.incomplete.title': 'Enlace incompleto',
  'accountDeletion.incomplete.body': 'A este enlace le falta la información necesaria. Inicia sesión para solicitar la eliminación de tu cuenta.',
  'accountDeletion.confirm.title': 'Confirmar la eliminación de tu cuenta',
  'accountDeletion.confirm.body':
    'Tu cuenta se desactivará al final de un periodo de gracia de 30 días. Hasta entonces, el enlace «Cancelar» del correo te permite dar marcha atrás.',
  'accountDeletion.confirm.action': 'Confirmar la eliminación',
  'accountDeletion.cancel.title': 'Cancelar la eliminación de tu cuenta',
  'accountDeletion.cancel.body': 'Tu cuenta sigue activa y la solicitud de eliminación se abandona. No se pierde nada.',
  'accountDeletion.cancel.action': 'Cancelar la eliminación',
  'accountDeletion.purge.title': 'Eliminar tu cuenta ahora',
  'accountDeletion.purge.body': 'Tu cuenta se desactivará de inmediato y se cerrarán todas tus sesiones. Esta acción es definitiva.',
  'accountDeletion.purge.action': 'Eliminar ahora',
  'accountDeletion.dismiss': 'No hacer nada',
  'accountDeletion.working': 'Un momento…',
  'accountDeletion.done.title': 'Listo',
  'accountDeletion.done.confirmed': 'Tu solicitud está confirmada: tu cuenta se desactivará el {date}. Puedes cancelarla hasta entonces.',
  'accountDeletion.done.cancelled': 'Tu cuenta sigue activa: la solicitud de eliminación se ha abandonado.',
  'accountDeletion.done.completed': 'Tu cuenta está desactivada y se han cerrado todas tus sesiones.',
  'accountDeletion.done.purged': 'Tus datos se han borrado.',
  'accountDeletion.closed.title': 'Este enlace ya no sirve',
  'accountDeletion.invalid': 'Este enlace no es válido o ya se ha usado.',
  'accountDeletion.request.title': 'Eliminar tu cuenta',
  'accountDeletion.request.body':
    'Se eliminarán tus conversaciones, mensajes, archivos multimedia, contactos y preferencias. Un correo te pedirá que lo confirmes y después un periodo de gracia de 30 días te permitirá dar marcha atrás.',
  'accountDeletion.request.phrase': 'Escribe {phrase} para confirmar',
  'accountDeletion.request.password': 'Contraseña actual',
  'accountDeletion.request.action': 'Solicitar la eliminación',
  'accountDeletion.request.sent.title': 'Te hemos enviado un correo de confirmación',
  'accountDeletion.request.sent.body': 'Ábrelo para confirmar la eliminación de tu cuenta.',
  'accountDeletion.request.wrongPassword': 'Contraseña incorrecta.',
  'accountDeletion.request.alreadyPending': 'Ya hay una solicitud en curso. Abre el correo recibido para confirmarla o cancelarla.',
  'accountDeletion.request.noEmail': 'Añade y verifica una dirección de correo antes de solicitar la eliminación.',
  'emailChange.verifying': 'Confirmando tu nueva dirección…',
  'emailChange.done.title': 'Dirección de correo cambiada',
  'emailChange.done.body': 'A partir de ahora inicias sesión con {email}.',
  'emailChange.done.generic': 'Tu nueva dirección de correo está confirmada.',
  'emailChange.failed.title': 'Dirección no cambiada',
  'emailChange.missing': 'Este enlace no incluye un código de confirmación. Abre el del correo más reciente.',
  'emailChange.invalid': 'Este enlace no corresponde a ningún cambio pendiente en esta cuenta, o ya se ha usado.',
  'emailChange.taken': 'Esta dirección ya la usa otra cuenta.',
  'emailNotifications.title': 'Correos de Meeshy',
  'emailNotifications.loading': 'Leyendo tu preferencia…',
  'emailNotifications.on': 'Recibes por correo los anuncios, resúmenes y notificaciones de Meeshy.',
  'emailNotifications.off': 'Ya no recibes por correo los anuncios, resúmenes ni notificaciones de Meeshy.',
  'emailNotifications.security': 'Los correos de seguridad de tu cuenta siguen llegando.',
  'emailNotifications.unsubscribe': 'Dejar de recibir estos correos',
  'emailNotifications.resubscribe': 'Volver a recibir estos correos',
  'emailNotifications.failed': 'El cambio no se ha aplicado. Reinténtalo.',

  'dataExport.title': 'Exportar mis datos',
  'dataExport.info.body': 'De conformidad con el RGPD, recibe un archivo con tu perfil, tus mensajes, tus contactos y tus publicaciones.',
  'dataExport.action.start': 'Exportar mis datos',
  'dataExport.action.exporting': 'Exportando…',
  'dataExport.action.again': 'Exportar de nuevo',
  'dataExport.done.title': 'Exportación completada',
  'dataExport.done.body': 'El archivo se ha descargado en este dispositivo.',
  'dataExport.ready.title': 'Exportación lista',
  'dataExport.ready.body': 'El archivo está listo. Toca para guardarlo en este dispositivo.',
  'dataExport.action.deliver': 'Guardar el archivo',
  'dataExport.undelivered.body': 'Este dispositivo no pudo recibir el archivo.',

  'profile.title': 'Perfil',
  'profile.edit': 'Editar',
  'profile.cancel': 'Cancelar',
  'profile.save': 'Guardar',
  'profile.saving': 'Guardando…',
  'profile.saved': 'Perfil guardado',
  'profile.save.error': 'Error al guardar',
  'profile.save.offline': 'Sin conexión — el cambio no se envió.',
  'profile.save.invalid': 'Revisa el campo «{field}».',
  'profile.loading': 'Cargando el perfil',
  'profile.error.title': 'No se pudo cargar tu perfil',
  'profile.error.body': 'Vuelve a intentarlo en un momento.',
  'profile.retry': 'Reintentar',
  'profile.offline.title': 'Sin conexión',
  'profile.offline.body': 'Tu perfil sigue visible; la edición vuelve con la red.',
  'profile.avatar.edit': 'Editar foto de perfil',
  'profile.avatar.updated': 'Foto de perfil actualizada',
  'profile.avatar.error': 'No se pudo actualizar la foto de perfil',
  'profile.banner.edit': 'Editar banner',
  'profile.banner.updated': 'Banner actualizado',
  'profile.banner.error': 'No se pudo actualizar el banner',
  'profile.image.uploading': 'Enviando',
  'profile.image.cancel': 'Cancelar el envío',
  'profile.image.cancelled': 'Envío cancelado',
  'profile.image.unreadable': 'Esta imagen no se puede leer.',
  'profile.section.identity': 'IDENTIDAD',
  'profile.section.contact': 'CONTACTO',
  'profile.section.languages': 'IDIOMAS',
  'profile.section.stats': 'ESTADÍSTICAS',
  'profile.section.requests': 'SOLICITUDES',
  'profile.section.member_since': 'MIEMBRO DESDE',
  'profile.first_name': 'Nombre',
  'profile.last_name': 'Apellido',
  'profile.username': 'Usuario',
  'profile.display_name': 'Nombre visible',
  'profile.bio': 'Biografía',
  'profile.bio.placeholder': 'Cuéntanos sobre ti...',
  'profile.email': 'Correo electrónico',
  'profile.phone': 'Teléfono',
  'profile.verified': 'Verificado',
  'profile.not_verified': 'No verificado',
  'profile.language.primary': 'Idioma principal',
  'profile.language.primary.subtitle': 'El contenido se traducirá a este idioma',
  'profile.language.regional': 'Idioma regional',
  'profile.language.custom': 'Idioma personalizado',
  'profile.language.none': 'Ninguno',
  'profile.language.choose': 'Elegir',
  'profile.language.clear.regional': 'Quitar el idioma regional',
  'profile.language.clear.custom': 'Quitar el idioma personalizado',

  'languageSheet.title.read': 'Idioma de lectura',
  'languageSheet.title.write': 'Idioma de escritura',
  'languageSheet.search': 'Buscar un idioma',
  'languageSheet.empty': 'Ningún idioma coincide con «{search}».',

  'profile.stats.messages': 'Mensajes',
  'profile.stats.translations': 'Traducciones',
  'profile.stats.languages': 'Idiomas',
  'profile.stats.days': 'Días',
  'profile.stats.loading': 'Cargando las estadísticas',
  'profile.progression.title': 'Progreso',
  'profile.progression.subtitle': 'Insignias, nivel y racha',
  'profile.friend_requests': 'Solicitudes de amistad',
  'profile.friend_requests.count.one': '{count} solicitud pendiente',
  'profile.friend_requests.count.other': '{count} solicitudes pendientes',

  'settings.title': 'Ajustes',
  'settings.my_profile': 'Mi perfil',
  'settings.section.account': 'Cuenta',
  'settings.security.title': 'Seguridad',
  'settings.delete_account': 'Eliminar cuenta',
  'settings.privacy.title': 'Privacidad',
  'settings.privacy.online_status': 'Estado en línea',
  'settings.privacy.online_status.info':
    'El punto verde en tu avatar indica que estás activo. Desactivado, nadie lo ve, pero escribir en una conversación sigue delatando tu actividad.',
  'settings.privacy.last_seen': 'Último inicio de sesión',
  'settings.privacy.read_receipts': 'Confirmaciones de lectura',
  'settings.privacy.read_receipts.info':
    'Es recíproco: si no envías confirmaciones de lectura, tampoco verás si han leído tus mensajes.',
  'settings.privacy.typing_indicator': 'Indicador de escritura',
  'settings.section.appearance': 'Apariencia',
  'settings.theme': 'Tema',
  'settings.theme.auto': 'Auto',
  'settings.theme.light': 'Claro',
  'settings.theme.dark': 'Oscuro',
  'settings.interface_language': 'Idioma de la interfaz',
  'settings.interface_language.automatic': 'Automático',
  'settings.content_languages': 'Idiomas de traducción',
  'settings.section.notifications': 'Notificaciones',
  'settings.notifications.title': 'Notificaciones',
  'settings.notif.sounds': 'Sonidos',
  'settings.notif.more_options': 'Más opciones',
  'settings.section.data': 'Datos',
  'settings.media': 'Multimedia',
  'settings.messages': 'Mensajes',
  'settings.export_data': 'Exportar mis datos',
  'settings.section.tools': 'Herramientas',
  'settings.tools.progression': 'Progreso',
  'settings.section.about': 'Acerca de',
  'settings.terms': 'Términos de servicio',
  'settings.privacy_policy': 'Política de privacidad',
  'settings.version': 'Versión',
  'settings.logout.title': 'Cerrar sesión',
  'settings.logout.message': '¿Seguro que quieres cerrar sesión?',
  'settings.logout.inprogress': 'Cerrando sesión...',
  'settings.loading': 'Cargando los ajustes',
  'settings.error.title': 'No se pudieron cargar tus ajustes',
  'settings.retry': 'Reintentar',
  'settings.offline.body': 'Sin conexión: tus ajustes siguen visibles; podrás cambiarlos cuando vuelva la red.',
  'settings.save.error': 'El ajuste no se guardó.',
  'settings.theme.sync_error': 'Tema aplicado en este dispositivo, sin sincronizar.',
  'common.cancel': 'Cancelar',

  'media.video.play': 'Reproducir vídeo',
  'media.video.pause': 'Pausa',
  'media.video.position': 'Posición de reproducción',
  'media.audio.position': 'Posición de reproducción',
  'media.audio.speed': 'Velocidad de reproducción',
  'media.video.position.value': '{elapsed} de {total}',
  'media.video.mute': 'Silenciar',
  'media.video.unmute': 'Activar sonido',
  'media.video.more_options': 'Más opciones',
  'media.video.speed': 'Velocidad',
  'media.video.pip.enter': 'Imagen en imagen',
  'media.video.pip.exit': 'Salir de imagen en imagen',

  'community.list.create.accessibilityLabel': 'Crear una comunidad',
  'community.list.search.placeholder': 'Buscar comunidades',
  'community.list.search.clear': 'Borrar la búsqueda',
  'community.list.search.empty': 'Ninguna comunidad coincide con «{query}».',
  'community.list.empty.title': 'Ninguna comunidad',
  'community.list.empty.subtitle': 'Únete a una comunidad o crea una para conversar en grupo.',
  'community.list.loading': 'Cargando comunidades',
  'community.error.title': 'No se pudieron cargar las comunidades',
  'community.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'community.retry': 'Reintentar',
  'community.offline.title': 'Sin conexión',
  'community.offline.body': 'Tus comunidades siguen visibles; crear una requiere conexión.',
  'community.privacy.private': 'Privada',
  'community.privacy.public': 'Pública',
  'community.members.one': '{count} miembro',
  'community.members.other': '{count} miembros',
  'community.conversations.one': '{count} conversación',
  'community.conversations.other': '{count} conversaciones',
  'community.detail.stats.members': 'Miembros',
  'community.detail.channels': 'Conversaciones',
  'community.detail.channels.empty': 'Aún no participas en ninguna conversación de esta comunidad.',
  'community.detail.untitled': 'Conversación sin título',
  'community.detail.back': 'Volver a las comunidades',
  'community.detail.refused.title': 'Comunidad no encontrada',
  'community.detail.refused.body': 'No existe, o es privada y no eres miembro.',
  'community.detail.error.title': 'No se pudo cargar esta comunidad',
  'community.detail.loading': 'Cargando la comunidad',
  'community.create.title': 'Nueva comunidad',
  'community.create.preview.placeholder': 'Mi comunidad',
  'community.create.field.name': 'Nombre',
  'community.create.field.name.placeholder': 'Nombre de la comunidad',
  'community.create.field.identifier': 'Identificador',
  'community.create.field.identifier.placeholder': 'mi-grupo',
  'community.create.field.description': 'Descripción',
  'community.create.field.description.placeholder': '¿De qué trata esta comunidad?',
  'community.create.privacy.title': 'Comunidad privada',
  'community.create.privacy.private.description': 'Solo los miembros invitados pueden unirse',
  'community.create.privacy.public.description': 'Cualquiera puede descubrirla y unirse',
  'community.create.button': 'Crear la comunidad',
  'community.create.inprogress': 'Creando…',
  'community.create.error.name': 'Ponle un nombre de 100 caracteres como máximo.',
  'community.create.error.identifier': 'Solo letras, números, guiones y guiones bajos, 50 como máximo.',
  'community.create.error.description': '500 caracteres como máximo.',
  'community.create.error.conflict': 'Este identificador ya está en uso.',
  'community.create.error.offline': 'Sin conexión: la comunidad no se envió.',
  'community.create.error.default': 'No se creó la comunidad. Vuelve a intentarlo.',
  'calls.filters': 'Filtrar el registro de llamadas',
  'calls.filter.all': 'Todas',
  'calls.filter.missed': 'Perdidas',
  'calls.direction.incoming': 'Recibida',
  'calls.direction.outgoing': 'Realizada',
  'calls.direction.missed': 'Perdida',
  'calls.a11y.incoming': 'llamada recibida',
  'calls.a11y.outgoing': 'llamada realizada',
  'calls.a11y.missed': 'llamada perdida',
  'calls.type.audio': 'llamada de voz',
  'calls.type.video': 'videollamada',
  'calls.duration': 'duración {duration}',
  'calls.unknown': 'Desconocido',
  'calls.empty.title': 'No hay llamadas recientes',
  'calls.empty.subtitle': 'Aquí aparecerán tus llamadas recibidas, perdidas, canceladas y realizadas.',
  'calls.empty.missed.title': 'No hay llamadas perdidas',
  'calls.empty.missed.subtitle': 'Aquí aparecerán las llamadas que no respondiste.',
  'calls.error.title': 'No se pudo cargar el registro de llamadas',
  'calls.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'calls.offline.title': 'Sin conexión',
  'calls.offline.body': 'Ves el registro de la última carga.',
  'calls.offline.cold.body': 'El registro se cargará en cuanto vuelva la conexión.',
  'calls.retry': 'Reintentar',
  'calls.loading': 'Cargando el registro de llamadas',
  'calls.allLoaded': 'Todas las llamadas de los últimos tres meses están cargadas',

  'discover.tabs': 'Secciones de descubrir',
  'discover.tab.discover': 'Descubrir',
  'discover.tab.requests': 'Solicitudes',
  'discover.tab.blocked': 'Bloqueados',
  'discover.tab.requests.count.one': 'Solicitudes, {count} recibida',
  'discover.tab.requests.count.other': 'Solicitudes, {count} recibidas',
  'discover.invite.title': 'Invitar por correo',
  'discover.invite.placeholder': 'Correo electrónico',
  'discover.invite.send': 'Enviar',
  'discover.invite.sending': 'Enviando…',
  'discover.invite.sendLabel': 'Enviar la invitación por correo',
  'discover.invite.sent': 'Invitación enviada a {email}',
  'discover.invite.invalid': 'Este correo electrónico no es válido.',
  'discover.invite.conflict': 'Esta persona ya está en Meeshy: búscala abajo.',
  'discover.invite.error': 'No se pudo enviar la invitación. Inténtalo de nuevo.',
  'discover.invite.offline': 'Sin conexión: vuelve a conectarte para enviar la invitación.',
  'discover.search.label': 'Buscar un usuario de Meeshy',
  'discover.search.clear': 'Borrar la búsqueda',
  'discover.search.searching': 'Buscando',
  'discover.search.empty': 'Ningún usuario encontrado para «{query}»',
  'discover.search.error': 'La búsqueda falló. Comprueba tu conexión.',
  'discover.connection.add': 'Añadir',
  'discover.connection.addLabel': 'Añadir a {name}',
  'discover.connection.pending': 'Pendiente',
  'discover.connection.cancelLabel': 'Cancelar la solicitud enviada a {name}',
  'discover.connection.contact': 'Contacto',
  'discover.connection.blocked': 'Bloqueado',
  'discover.connection.acceptLabel': 'Aceptar la solicitud de {name}',
  'discover.connection.rejectLabel': 'Rechazar la solicitud de {name}',
  'discover.requests.filters': 'Filtrar las solicitudes',
  'discover.requests.received': 'Recibidas',
  'discover.requests.sent': 'Enviadas',
  'discover.requests.intent': 'Quiere conectar contigo',
  'discover.requests.cancel': 'Cancelar',
  'discover.requests.empty.received.title': 'Ninguna solicitud recibida',
  'discover.requests.empty.received.subtitle': 'Las solicitudes de contacto que recibas aparecerán aquí.',
  'discover.requests.empty.sent.title': 'Ninguna solicitud enviada',
  'discover.requests.empty.sent.subtitle': 'Las solicitudes que envíes aparecerán aquí.',
  'discover.blocked.unblock': 'Desbloquear',
  'discover.blocked.unblockLabel': 'Desbloquear a {name}',
  'discover.blocked.confirm.title': '¿Desbloquear?',
  'discover.blocked.confirm.body': '¿Desbloquear a {name}?',
  'discover.blocked.confirm.cancel': 'Cancelar',
  'discover.blocked.empty.title': 'Ningún usuario bloqueado',
  'discover.blocked.empty.subtitle': 'Las personas que bloquees aparecerán aquí.',
  'discover.unknown': 'Desconocido',
  'discover.loading': 'Cargando',
  'discover.allLoaded': 'La lista completa está cargada',
  'discover.error.title': 'No se pudo cargar esta lista',
  'discover.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'discover.offline.title': 'Sin conexión',
  'discover.offline.body': 'Ves la lista de la última carga.',
  'discover.offline.cold.body': 'La lista se cargará en cuanto vuelva la conexión.',
  'discover.retry': 'Reintentar',
  'discover.announce.accepted': 'Conexión aceptada',
  'discover.announce.rejected': 'Solicitud rechazada',
  'discover.announce.cancelled': 'Solicitud cancelada',
  'discover.announce.sent': 'Solicitud enviada',
  'discover.announce.unblocked': 'Usuario desbloqueado',
  'discover.announce.acceptFailed': 'No se pudo aceptar esta solicitud',
  'discover.announce.rejectFailed': 'No se pudo rechazar esta solicitud',
  'discover.announce.cancelFailed': 'No se pudo cancelar esta solicitud',
  'discover.announce.sendFailed': 'No se pudo enviar la solicitud',
  'discover.announce.unblockFailed': 'No se pudo desbloquear',
  'discover.announce.offline': 'Sin conexión: no se envió nada.',

  'userProfile.title': 'Perfil',
  'userProfile.loading': 'Cargando el perfil',
  'userProfile.section.publications': 'PUBLICACIONES',
  'userProfile.section.relation': 'CONEXIÓN',
  'userProfile.section.conversations': 'CONVERSACIONES',
  'userProfile.conversations.empty': 'Ninguna conversación en común',
  'userProfile.conversations.emptyBody': 'Todavía nada os une: «Escribir» abre la primera.',
  'userProfile.conversations.error': 'No se pudieron cargar las conversaciones',
  'userProfile.conversations.loading': 'Cargando las conversaciones',
  'userProfile.refused.title': 'Este perfil no está disponible',
  'userProfile.refused.body': 'No existe, o no tienes acceso.',
  'userProfile.throttled.title': 'Demasiadas solicitudes',
  'userProfile.throttled.body': 'Inténtalo de nuevo en un momento.',
  'userProfile.error.title': 'No se pudo cargar este perfil',
  'userProfile.error.body': 'Inténtalo de nuevo en un momento.',
  'userProfile.offline.body': 'El perfil aparecerá al volver a conectarte.',
  'userProfile.posts.empty': 'Sin publicaciones',
  'userProfile.posts.emptyBody': 'Todavía no hay nada público que leer.',
  'userProfile.posts.emptyPosts': 'Ninguna publicación aquí',
  'userProfile.posts.emptyReels': 'Ningún reel aquí',
  'userProfile.posts.emptyFilter': 'Toca de nuevo la casilla para volver a verlo todo.',
  'userProfile.posts.error': 'No se pudieron cargar las publicaciones',
  'userProfile.posts.loadMore': 'Cargar más',
  'userProfile.posts.loaded': 'Publicaciones añadidas: {count}',
  'userProfile.posts.loadedNone': 'No hay más publicaciones que mostrar',
  'userProfile.posts.loading': 'Cargando…',
  'userProfile.stat.posts': 'Publicaciones',
  'userProfile.stat.reels': 'Reels',
  'userProfile.stat.stories': 'Historias',
  'userProfile.stat.filterLabel': 'Filtrar por {name}',
  'userProfile.stat.filterClear': 'Mostrar todo',
  'userProfile.context.received': '{name} quiere conectar contigo. Acepta para intercambiar mensajes.',
  'userProfile.context.sent': 'Enviaste una solicitud de conexión a {name}. A la espera de su respuesta.',
  'userProfile.action.write': 'Escribir',
  'userProfile.action.writeLabel': 'Escribir a {name}',
  'userProfile.action.block': 'Bloquear',
  'userProfile.action.blockLabel': 'Bloquear a {name}',
  'userProfile.blocked.title': 'Has bloqueado a esta persona',
  'userProfile.blocked.body': 'Sus publicaciones y estadísticas quedan ocultas mientras dure el bloqueo.',
  'userProfile.signin.title': 'Inicia sesión para conectar',
  'userProfile.signin.body': 'Las solicitudes de conexión y los mensajes requieren una cuenta.',
  'userProfile.signin.cta': 'Iniciar sesión',
  'userProfile.announce.blocked': 'Persona bloqueada',
  'userProfile.announce.blockFailed': 'No se pudo bloquear',
  'userProfile.announce.writeFailed': 'No se pudo abrir la conversación',

  'a11y.floating.rung.discover.requests.one': 'Descubrir, {count} solicitud recibida',
  'a11y.floating.rung.discover.requests.other': 'Descubrir, {count} solicitudes recibidas',

  'links.hub.banner.title': 'Gestiona tus enlaces',
  'links.hub.banner.subtitle': 'Invita a quien quieras a tus conversaciones',
  'links.hub.share.title': 'Enlaces para compartir',
  'links.hub.share.description': 'Invita a tus contactos a unirse a tus conversaciones',
  'links.hub.share.create': 'Crear un enlace para compartir',
  'links.share.back': 'Volver a Mis enlaces',
  'links.share.stats.total': 'Enlaces',
  'links.share.stats.active': 'Activos',
  'links.share.stats.joined': 'Unidos',
  'links.share.joined.one': '{count} unido',
  'links.share.joined.other': '{count} unidos',
  'links.share.copy': 'Copiar el enlace',
  'links.share.empty.title': 'Ningún enlace para compartir',
  'links.share.empty.subtitle': 'Crea un enlace para invitar a personas a una conversación',
  'links.share.loading': 'Cargando enlaces',
  'links.share.allLoaded': 'Todos tus enlaces están cargados',
  'links.status.active': 'Activo',
  'links.status.inactive': 'Inactivo',
  'links.unlimited': 'Ilimitado',
  'links.error.title': 'No se pudieron cargar tus enlaces',
  'links.error.body': 'Comprueba tu conexión y vuelve a intentarlo.',
  'links.retry': 'Reintentar',
  'links.offline.title': 'Sin conexión',
  'links.offline.body': 'Tus enlaces siguen visibles; para modificarlos se necesita la red.',
  'links.detail.back': 'Volver a los enlaces para compartir',
  'links.detail.copy': 'Copiar',
  'links.detail.copied': 'Copiado',
  'links.detail.share': 'Compartir',
  'links.detail.disable': 'Desactivar',
  'links.detail.activate': 'Activar',
  'links.detail.stats': 'Estadísticas',
  'links.detail.stats.uses': 'Usos',
  'links.detail.stats.max': 'Máximo',
  'links.detail.info': 'Información',
  'links.detail.identifier': 'Identificador',
  'links.detail.createdAt': 'Creado el',
  'links.detail.expiresAt': 'Caduca el',
  'links.detail.reason.closed': 'La conversación está cerrada: este enlace ya no permite entrar.',
  'links.detail.reason.expired': 'Este enlace ha caducado.',
  'links.detail.reason.revoked': 'Desactivaste este enlace.',
  'links.detail.refused.title': 'Enlace no encontrado',
  'links.detail.refused.body': 'Este enlace no existe o no es uno de los tuyos.',
  'links.detail.loading': 'Cargando el enlace',
  'links.announce.copied': 'Enlace copiado',
  'links.announce.copyFailed': 'No se pudo copiar el enlace',
  'links.announce.shareUnavailable': 'Compartir no está disponible aquí',
  'links.announce.disabled': 'Enlace desactivado',
  'links.announce.activated': 'Enlace activado',
  'links.announce.toggleFailed': 'No se pudo modificar este enlace',
  'links.announce.offline': 'Sin conexión: no se envió nada.',
  'links.create.title': 'Nuevo enlace para compartir',
  'links.create.section.conversation': 'Conversación',
  'links.create.choose': 'Elegir un grupo o una comunidad',
  'links.create.picker.title': 'Elegir una conversación',
  'links.create.picker.empty': 'Ninguna conversación puede recibir un enlace por ahora.',
  'links.create.section.identity': 'Identidad del enlace',
  'links.create.name': 'Nombre del enlace',
  'links.create.name.placeholder': 'p. ej.: Compartir en Twitter',
  'links.create.description': 'Descripción (opcional)',
  'links.create.description.placeholder': 'p. ej.: Únete a nuestro grupo…',
  'links.create.section.access': 'Acceso de invitados',
  'links.create.section.access.subtitle': 'Lo que los visitantes deben aportar para unirse',
  'links.create.access.account': 'Cuenta obligatoria',
  'links.create.access.account.caption': 'Solo los miembros de Meeshy pueden unirse',
  'links.create.access.nickname': 'Seudónimo obligatorio',
  'links.create.access.nickname.caption': 'El visitante debe elegir un seudónimo',
  'links.create.access.email': 'Correo electrónico obligatorio',
  'links.create.access.email.caption': 'El visitante debe indicar su correo electrónico',
  'links.create.access.birthday': 'Fecha de nacimiento obligatoria',
  'links.create.access.birthday.caption': 'Permite el control de edad',
  'links.create.section.permissions': 'Permisos',
  'links.create.section.permissions.subtitle': 'Lo que pueden hacer los invitados anónimos',
  'links.create.permission.messages': 'Enviar mensajes',
  'links.create.permission.messages.caption': 'Los invitados pueden escribir en la conversación',
  'links.create.permission.images': 'Enviar imágenes',
  'links.create.permission.images.caption': 'Los invitados pueden compartir fotos',
  'links.create.permission.files': 'Enviar archivos',
  'links.create.permission.files.caption': 'Los invitados pueden enviar documentos',
  'links.create.permission.history': 'Ver el historial',
  'links.create.permission.history.caption': 'Los invitados ven los mensajes anteriores',
  'links.create.section.limits': 'Límites',
  'links.create.section.limits.subtitle': 'Controla la audiencia y la duración del enlace',
  'links.create.limit.uses': 'Limitar los usos',
  'links.create.limit.max.one': 'Como máximo {count} uso',
  'links.create.limit.max.other': 'Como máximo {count} usos',
  'links.create.limit.count': 'Número de usos',
  'links.create.limit.invalid': 'Elige un número entero entre 1 y {max}.',
  'links.create.expiration': 'Caducidad',
  'links.create.expiration.never': 'Nunca',
  'links.create.expiration.h24': '24 horas',
  'links.create.expiration.d7': '7 días',
  'links.create.expiration.d30': '30 días',
  'links.create.expiration.m3': '3 meses',
  'links.create.button': 'Crear el enlace para compartir',
  'links.create.inprogress': 'Creando…',
  'links.create.error.conversation': 'Elige primero una conversación.',
  'links.create.error.offline': 'Sin conexión: el enlace no se creó.',
  'links.create.error.refused': 'No puedes crear un enlace para esta conversación.',
  'links.create.error.default': 'No se pudo crear el enlace. Vuelve a intentarlo.',

  'feed.scene.carousel.previous': 'Escena anterior',
  'feed.scene.carousel.next': 'Escena siguiente',
  'feed.scene.mosaic.tile': 'Escena {index}',
  'feed.scene.mosaic.more': 'Escena {index}, y {count} más',
  'feed.scene.mosaic.video': 'Escena {index}, vídeo',
  'feed.scene.shared_by': 'Escena compartida por {author}',
  'feed.scene.open.fullscreen': 'Toca dos veces para ver en pantalla completa',
  'feed.scene.open.post': 'Toca dos veces para abrir la publicación',
  'feed.scene.sound.muted': 'Sonido silenciado',
  'feed.scene.count': '{count} escenas',
  'scene.fullscreen.play': 'Reanudar todo',
  'scene.fullscreen.pause': 'Pausar todo',
  'scene.fullscreen.sound.on': 'Activar el sonido',
  'scene.fullscreen.sound.off': 'Silenciar el sonido',
  'scene.place.here': 'Aquí',

  'story.sound.off': 'Silenciado',

  /* EL ESTUDIO DE HISTORIAS (#6900) — crear una historia con un fondo, un
     sonido de fondo y texto, previsualizada por el motor compartido,
     publicada en CanvasV3 como en iOS. */
  'story.studio.title': 'Nueva historia',
  'story.studio.cancel': 'Cancelar',
  'story.studio.publish': 'Publicar',
  'story.studio.publishing': 'Publicando…',
  'story.studio.publish.waiting': 'Esperando la red…',
  'story.studio.publishing.progress': 'Publicando {current}/{total}…',
  'story.studio.outcome.partial': '{published} de {total} publicadas — las demás siguen aquí.',
  'story.studio.title.post': 'Nueva publicación',
  'story.studio.title.reel': 'Nuevo reel',
  'story.studio.publish.as.story': 'Publicar historia',
  'story.studio.publish.as.post': 'Publicar publicación',
  'story.studio.publish.as.reel': 'Publicar reel',
  'story.studio.publish.menu': 'Publicar como',
  'story.studio.kind.story': 'Historia',
  'story.studio.kind.post': 'Publicación',
  'story.studio.kind.reel': 'Reel',
  'story.studio.refusal.reel': 'Un reel necesita un vídeo o un sonido de al menos 3 segundos, o al menos dos imágenes.',
  'story.studio.offline': 'Sin conexión — la historia se publicará cuando vuelva la red.',
  'story.studio.stage': 'Vista previa de la historia',
  'story.studio.background.add': 'Añadir una foto o un vídeo',
  'story.studio.background.label': 'Fondo',
  'story.studio.background.remove': 'Quitar el fondo',
  'story.studio.sound.add': 'Añadir un sonido',
  'story.studio.sound.label': 'Sonido de fondo',
  'story.studio.sound.remove': 'Quitar el sonido',
  'story.studio.sound.mute': 'Silenciar el sonido',
  'story.studio.sound.unmute': 'Activar el sonido',
  'story.studio.upload.progress': 'Enviando… {percent} %',
  'story.studio.upload.ready': 'Listo',
  'story.studio.upload.retry': 'Reintentar',
  'story.studio.text.label': 'Texto de la historia',
  'story.studio.text.placeholder': 'Añadir texto',
  'story.studio.hint.duration': 'Una historia permanece visible veinte horas.',
  'story.studio.error.upload': 'No se pudo enviar el archivo.',
  'story.studio.error.publish': 'No se pudo publicar la historia.',
  'story.studio.refusal.title': 'Se necesita una cuenta para crear una historia.',
  'story.studio.refusal.login': 'Iniciar sesión',
  'story.studio.refusal.door.visual': 'Elige una imagen o un vídeo.',
  'story.studio.refusal.door.sound': 'Elige un archivo de audio.',
  'story.studio.refusal.media-max': 'Esta publicación ya lleva diez medios: el límite de la pasarela.',
  'story.studio.failure.network': 'Red no disponible.',
  'story.studio.failure.timeout': 'El servidor no respondió.',
  'story.studio.failure.session': 'Sesión caducada — vuelve a iniciar sesión.',
  'story.studio.failure.account': 'Se necesita una cuenta para publicar un archivo multimedia.',
  'story.studio.failure.forbidden': 'Acción no permitida para esta cuenta.',
  'story.studio.failure.tooLarge': 'Archivo demasiado pesado.',
  'story.studio.failure.fileRefused': 'Archivo rechazado: su tipo no coincide con su contenido.',
  'story.studio.failure.rateLimited': 'Demasiadas publicaciones a la vez — inténtalo de nuevo en un momento.',
  'story.studio.failure.refused': 'Publicación rechazada.',
  'story.studio.failure.unavailable': 'El servidor no está disponible.',
  'story.studio.text.add': 'Añadir texto',
  'story.studio.text.remove': 'Quitar este texto',
  'story.studio.object.text': 'Texto {index}',
  'story.studio.object.overlay': 'Capa',
  'story.studio.object.select': 'Seleccionar {name}',
  'story.studio.objects.label': 'Objetos de la escena',
  'story.studio.overlay.add': 'Colocar una imagen en la escena',
  'story.studio.overlay.label': 'Capa',
  'story.studio.overlay.remove': 'Quitar la capa',
  'story.studio.pages.label': 'Escenas de la publicación',
  'story.studio.page.position': 'Escena {index} de {count}',
  'story.studio.page.add': 'Crear una escena',
  'story.studio.page.remove': 'Eliminar la escena {index}',
  'story.studio.page.failed': 'un medio no se pudo enviar',
  'story.studio.layout.title': 'Disposición de las escenas',
  'story.studio.layout.carousel': 'Una por una',
  'story.studio.layout.reel': 'Desplazamiento continuo',
  'story.studio.layout.hero': 'Una grande, las demás al lado',
  'story.studio.layout.wave': 'En ola',
  'story.studio.layout.sine': 'En zigzag',
  'story.studio.caption.label': 'Leyenda de {media}',
  'story.studio.caption.placeholder': 'Añadir una leyenda',
  'story.studio.sound.plane.label': 'Colocación del sonido',
  'story.studio.sound.plane.background': 'De fondo',
  'story.studio.sound.plane.foreground': 'En la escena',
  'story.studio.editor.label': 'Ajustes del objeto',
  'story.studio.editor.style': 'Tipografía',
  'story.studio.editor.effect': 'Efecto',
  'story.studio.editor.color': 'Color',
  'story.studio.editor.align': 'Alineación',
  'story.studio.editor.background': 'Fondo del texto',
  'story.studio.editor.language': 'Idioma del texto',
  'story.studio.editor.none': 'Ninguno',
  'story.studio.editor.empty': 'Selecciona un objeto para ajustarlo.',
  'story.studio.style.bold': 'Negrita',
  'story.studio.style.neon': 'Neón',
  'story.studio.style.classic': 'Clásico',
  'story.studio.style.italic': 'Cursiva',
  'story.studio.style.typewriter': 'Máquina',
  'story.studio.style.handwriting': 'Manuscrita',
  'story.studio.style.calligraphy': 'Caligrafía',
  'story.studio.style.cartoon': 'Cómic',
  'story.studio.style.futuristic': 'Futurista',
  'story.studio.style.fantasy': 'Fantasía',
  'story.studio.style.curve': 'Curva',
  'story.studio.style.tag': 'Grafiti',
  'story.studio.style.retro': 'Retro',
  'story.studio.style.elegant': 'Elegante',
  'story.studio.style.poster': 'Cartel',
  'story.studio.style.bubble': 'Burbuja',
  'story.studio.style.note': 'Nota',
  'story.studio.style.brush': 'Pincel',
  'story.studio.effect.glow': 'Resplandor',
  'story.studio.effect.neon': 'Neón',
  'story.studio.effect.outline': 'Contorno',
  'story.studio.effect.shadow': 'Sombra',
  'story.studio.effect.longShadow': 'Sombra larga',
  'story.studio.effect.emboss': 'Relieve',
  'story.studio.color.FFFFFF': 'Blanco',
  'story.studio.color.000000': 'Negro',
  'story.studio.color.FF2E63': 'Rosa',
  'story.studio.color.08D9D6': 'Cian',
  'story.studio.color.F8B500': 'Ámbar',
  'story.studio.color.9B59B6': 'Morado',
  'story.studio.color.2ECC71': 'Verde',
  'story.studio.color.3498DB': 'Azul',
  'story.studio.align.left': 'Izquierda',
  'story.studio.align.center': 'Centro',
  'story.studio.align.right': 'Derecha',
  'story.studio.pose.label': 'Posición y tamaño',
  'story.studio.pose.bigger': 'Ampliar',
  'story.studio.pose.smaller': 'Reducir',
  'story.studio.pose.rotateLeft': 'Girar a la izquierda',
  'story.studio.pose.rotateRight': 'Girar a la derecha',
  'story.studio.pose.reset': 'Recentrar',
  'story.studio.pose.handle': 'Mover {name} — flechas para mover, + y − para el tamaño, [ y ] para girar',
  'story.studio.pose.grip': 'Redimensionar y girar {name}',

  /* LA HOJA DE AUDIENCIA DEL ESTUDIO (#7683) — los seis PostVisibility,
     reflejo de PostVisibility.swift (packages/MeeshySDK). */
  'story.studio.audience.chip.label': 'Audiencia',
  'story.studio.audience.title': 'Audiencia',
  'story.studio.audience.public': 'Público',
  'story.studio.audience.community': 'Comunidades',
  'story.studio.audience.friends': 'Contactos',
  'story.studio.audience.except': 'Excepto…',
  'story.studio.audience.only': 'Solo…',
  'story.studio.audience.private': 'Privado',
  'story.studio.audience.subtitle.public': 'Todo el mundo, incluidos quienes no te siguen',
  'story.studio.audience.subtitle.community': 'Los miembros de tus comunidades',
  'story.studio.audience.subtitle.friends': 'Tus contactos aceptados',
  'story.studio.audience.subtitle.private': 'Solo tú — no se publica nada',
  'story.studio.audience.refusal.people': 'Elegir personas aún no está disponible en la web.',
  'story.studio.audience.scope': 'La audiencia elegida pertenece a la publicación, nunca a un formato: cambiar de formato la conserva.',
  'story.studio.audience.defaultMark': 'predeterminada',

  'appUpdate.available': '¡Hay una nueva versión de Meeshy disponible!',
  'appUpdate.hint': 'Recarga para tener las últimas novedades.',
  'appUpdate.storeHint': 'Instálala desde la tienda de aplicaciones.',
  'appUpdate.action': 'Actualizar',
  'appUpdate.dismiss': 'Esperar',
  'appUpdate.applying': 'Actualizando…',
  'appUpdate.region': 'Actualización de la aplicación',

  'story.action.rail': 'Acciones de la historia',
  'story.action.react': 'Reaccionar',
  'story.action.reply': 'Responder',
  'story.action.forward': 'Enviar',
  'story.action.repost': 'Republicar',
  'story.action.views': 'Vistas',
  'story.action.share': 'Compartir',
  'story.action.save': 'Guardar',
  'story.action.comments': 'Comentarios',
  'story.action.translations': 'Traducciones',
  'story.language.bar': 'Idiomas disponibles',
  'story.language.original': 'Original',
  'story.language.more': 'Más idiomas',
  'story.views.empty.title': 'Aún no hay vistas',
  'story.views.empty.subtitle': 'Las personas que vean tu historia aparecerán aquí.',
  'story.views.count.one': '{count} vista',
  'story.views.count.other': '{count} vistas',
  'story.save.progress': 'Guardando {percent} %',
  'story.save.cancel': 'Cancelar guardado',
  'story.save.success': 'Historia guardada',
  'story.save.failed': 'Error al guardar',
  'story.save.cancelled': 'Exportación cancelada',
  'story.views.loading': 'Cargando vistas…',
  'story.views.offline': 'Sin conexión — la lista aparecerá cuando vuelva la red.',
  'story.views.forbidden': 'Solo el autor puede ver quién vio esta historia.',
  'story.save.offline': 'Sin conexión — inténtalo de nuevo cuando vuelva la red.',
  'story.save.refused': 'Inicia sesión para guardar esta historia.',
  'story.save.missing': 'Este contenido ya no está disponible.',
  'story.save.retry': 'Inténtalo de nuevo — toca Guardar otra vez.',
  'prism.translated.message': 'Mensaje traducido',
  'prism.translated.comment': 'Comentario traducido',
  'prism.translated.post': 'Publicación traducida',
  'prism.original.show.message': 'Mostrar el mensaje en su idioma original',
  'prism.original.show.comment': 'Mostrar el comentario en su idioma original',
  'prism.original.show.post': 'Mostrar la publicación en su idioma original',
  'prism.original.hide.message': 'Ocultar el mensaje en su idioma original',
  'prism.original.hide.comment': 'Ocultar el comentario en su idioma original',
  'prism.original.hide.post': 'Ocultar la publicación en su idioma original',

  'comments.title': 'Comentarios',
  'comments.close': 'Cerrar comentarios',
  'comments.loading': 'Cargando comentarios',
  'comments.empty': 'Sin comentarios',
  'comments.empty.hint': 'Sé la primera persona en escribir uno.',
  'comments.error': 'No se pudieron cargar los comentarios',
  'comments.error.hint': 'Inténtalo de nuevo en un momento.',
  'comments.retry': 'Reintentar',
  'comments.more': 'Ver más comentarios',
  'comments.offline': 'Sin conexión: solo se muestran los comentarios ya cargados.',
  'comments.placeholder': 'Escribe un comentario…',
  'comments.send': 'Enviar comentario',
  'comments.row.pending': 'Enviando',
  'comments.signin': 'Inicia sesión para comentar.',
  'comment.send.error': 'No se pudo publicar el comentario.',
  'comment.send.pending': 'Comentario sin confirmar: sin conexión',
  'comment.send.empty': 'Escribe algo antes de enviar.',
  'comments.action.like': 'Me gusta',
  'comments.action.unlike': 'Ya no me gusta',
  'comments.action.edit': 'Editar',
  'comments.action.delete': 'Eliminar',
  'comments.action.delete.confirm': 'Confirmar',
  'comments.edit.label': 'Editar comentario',
  'comments.edit.save': 'Guardar',
  'comments.edit.cancel': 'Cancelar',
  'comment.like.error': 'No se ha guardado tu «me gusta».',
  'comment.edit.error': 'No se ha guardado la modificación.',
  'comment.delete.error': 'No se ha podido eliminar el comentario.',
  'comment.gesture.pending': 'Acción sin confirmar — sin conexión',
  'comment.gesture.unconfirmed': 'Acción sin confirmar: la pasarela no respondió.',
  'comment.refused.session': 'Sesión caducada: vuelve a iniciar sesión.',
  'comment.refused.right': 'Esta acción no está disponible para ti.',
  'comment.like.limit': 'Cinco reacciones como máximo por persona.',
  'feed.action.comment': 'Comentar',

  'admin.title': 'Administración',

  'thread.unread-separator.one': '{count} mensaje no leído',
  'thread.unread-separator.other': '{count} mensajes no leídos',
  'message-detail.info.title': 'Información del mensaje',
  'message-detail.received-by': 'Recibido por',
  'message-detail.read-by': 'Leído por',
  'message-detail.not-yet': 'Aún no',
  'message-detail.received-by.empty': 'Aún no hay confirmación de entrega',
  'message-detail.read-by.empty': 'Nadie ha leído este mensaje todavía',
  'message-detail.not-yet.empty': 'Todos han recibido el mensaje',
  'message-detail.open': 'Ver detalles del mensaje',
  'message-detail.attachment.opens.one': '{count} apertura',
  'message-detail.attachment.opens.other': '{count} aperturas',
  'message-detail.attachment.downloads.one': '{count} descarga',
  'message-detail.attachment.downloads.other': '{count} descargas',
  'message-detail.attachment.listened-until': 'Escuchado hasta {time}',
  'message-detail.attachment.watched-until': 'Visto hasta {time}',
  'message-detail.attachment.complete': 'Completo',
  'message-detail.attachment.listen.empty': 'Aún no escuchado',
  'message-detail.attachment.watch.empty': 'Aún no visto',
  'message-detail.attachment.open': 'Abrir {name}',
  'message-detail.attachment.opened.empty': 'Aún no abierto',
  'message-detail.loading': 'Cargando…',
  'message-detail.load-error': 'No se pudo cargar esta información',
  'message-detail.retry': 'Reintentar',

  'download.title': 'Descarga Meeshy',
  'download.body': 'Escribe en tu idioma y lee en el tuyo: Meeshy traduce cada mensaje por el camino.',
  'download.appStore': 'Descargar en el App Store',
  'download.web': 'Abrir Meeshy en el navegador',
  'download.otherPlatforms': 'En Android y en el ordenador, Meeshy funciona directamente en el navegador.',

  /* LES SOURCES DU COMPOSEUR (#7280) — miroir de `composer.attach.*` d'iOS. */
  ...esComposerAttach,
  'composer.viewOnce.activate': 'Activar el modo de vista única',
  'composer.viewOnce.active': 'Modo de vista única activo',
  'composer.viewOnce.label': 'Vista única',
  'composer.protection.ephemeral.state': 'Modo efímero activo',
  'composer.protection.blur.state': 'Modo desenfoque activo',
  'message.location.shared': 'Ubicación compartida',
  'message.location.open': 'Abrir en Mapas',
  'message.location.a11y': 'Ubicación: {place}',

  /* LES LIBELLÉS D'ÉTAT DU FIL (#7337) — voir `catalog-fr.ts` pour la règle. */
  'message.forwarded': 'Reenviado',
  'message.forwarded.fromGroup': 'Reenviado desde {name}',
  'message.forwarded.fromPerson': 'Reenviado de {name}',
  'message.send.failed': 'No enviado',
  'message.send.failed.reason': 'No enviado — {reason}',
  'message.send.retry': 'Reintentar',
  'announce.messageNotSent': 'Mensaje no enviado',
  'announce.messageNotSent.reason': 'Mensaje no enviado — {reason}',
  'send.failure.offline': 'red no disponible',
  'send.failure.timeout': 'el servidor no respondió',
  'send.failure.uploadPartial': 'no se pudo subir un archivo adjunto',
  'send.failure.newcomerSlowMode': '¡bienvenido! las cuentas nuevas pueden enviar un mensaje cada 30 s — inténtalo de nuevo en {seconds} s',
  'send.failure.newcomerSlowMode.soon': '¡bienvenido! las cuentas nuevas pueden enviar un mensaje cada 30 s — inténtalo de nuevo en un momento',
  'send.failure.sessionExpired': 'sesión caducada — vuelve a iniciar sesión',
  'send.failure.forbidden': 'envío no permitido en esta conversación',
  'send.failure.tooMany': 'demasiados mensajes a la vez — inténtalo de nuevo en un momento',
  'send.failure.rejected': 'mensaje rechazado',
  'send.failure.gatewayUnavailable': 'el servidor no está disponible',
  'message.deleted': 'Mensaje eliminado',
  'message.expired.a11y': 'Mensaje efímero caducado',
  'message.story.reply': 'respuesta a su historia',
  'message.story.label': 'Historia',
  'message.story.unavailable': 'Historia no disponible',
  'message.mood.label': 'Estado de ánimo',
  'message.withheld': 'Contenido retenido',
  'message.withheld.a11y': 'Contenido retenido: este mensaje existe y no se muestra',
  'message.veiled': 'Contenido oculto',
  'message.veiled.hint': 'Toca para revelar el contenido',
  'message.veiled.error': 'No se puede revelar por ahora',
  'message.ephemeral.a11y': 'Mensaje efímero, desaparece en {remaining}',
  'message.ephemeral.awaiting': 'Esperando la recepción',
  'message.ephemeral.awaiting.a11y': 'Mensaje efímero de {duration}, esperando la recepción',
  'message.viewOnce.tap': 'Toca para ver',
  'message.viewOnce.opened': 'Ya abierto',
  'message.viewOnce.sealed.a11y': 'Mensaje de visualización única, toca para ver',
  'message.viewOnce.opened.a11y': 'Mensaje de visualización única, ya abierto',
  'message.viewOnce.close': 'Cerrar',
  'attachment.protected.image': 'Foto protegida',
  'attachment.protected.video': 'Vídeo protegido',
  'attachment.protected.audio': 'Audio protegido',
  'attachment.protected.file': 'Archivo protegido',
  'attachment.protected.open.hint': 'toca para verlo a pantalla completa',
  'media.reactions.badge.a11y': 'Reacciones',
  'media.reactions.badge.mine.a11y': 'incluida la suya',
  'attachment.kind.image': 'Foto',
  'attachment.kind.video': 'Vídeo',
  'attachment.kind.audio': 'Audio',
  'attachment.kind.file': 'Archivo',

  /* Le menu du message, sa barre de sélection et sa feuille « Plus… » (#7555). */
  'message.menu.select': 'Seleccionar',
  'message.menu.translate': 'Traducir',
  'message.menu.copy': 'Copiar',
  'message.menu.forward': 'Reenviar',
  'message.menu.reply': 'Responder',
  'message.menu.more': 'Más…',
  'message.menu.react': 'Reaccionar',
  'message.menu.addReaction': 'Añadir una reacción',
  'message.selection.toolbar': 'Selección de mensajes',
  'message.selection.count': '{count} seleccionados',
  'message.detail.title': 'Detalles del mensaje',
  'message.detail.languages': 'Idiomas',
  'message.detail.reactions': 'Reacciones',
  'message.detail.sent': 'Enviado',
  'message.detail.language.original': '{language} (original)',

  ...esMentions,
  ...esStoriesMine,
} satisfies InterfaceCatalog;

export default es;
