import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const itComposerAttach = {
  'composer.attach.group': 'Tipi di allegato',
  'composer.attach.handle': 'Maniglia del pannello',
  'composer.attach.photo': 'Foto',
  'composer.attach.photo.action': 'Scegli foto',
  'composer.attach.camera': 'Fotocamera',
  'composer.attach.camera.action': 'Scatta una foto',
  'composer.attach.file': 'File',
  'composer.attach.file.action': 'Scegli un file',
  'composer.attach.contact': 'Contatto',
  'composer.attach.contact.action': 'Condividi un contatto',
  'composer.contact.failed': 'Questo contatto non può essere condiviso',
  'composer.attach.location': 'Posizione',
  'composer.attach.location.action': 'Condividi la mia posizione',
  'composer.attach.voice': 'Voce',
  'composer.attach.voice.action': 'Registra un messaggio vocale',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Inserisci un emoji',
  'composer.emoji.title': 'Inserisci un emoji',
  'composer.location.locating': 'Ricerca della tua posizione…',
  'composer.location.denied': 'Posizione negata — consentila nelle impostazioni',
  'composer.location.unavailable': 'Posizione non disponibile su questo browser',
  'composer.location.failed': 'Posizione non trovata — riprova',
  'composer.mic.refused': 'Microfono negato — consentilo nelle impostazioni',
  'composer.mic.unavailable': 'Microfono non disponibile su questo dispositivo',
  'composer.openSettings': 'Impostazioni',
  'composer.location.chip': 'LUOGO',
  'composer.location.unknown': 'Luogo sconosciuto',
  'composer.location.remove': 'Rimuovi la posizione',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Invia uno sticker',
  'composer.sticker.title': 'I miei sticker',
  'composer.sticker.fromImage': 'Da un’immagine',
  'composer.sticker.paste': 'Incolla',
  'composer.sticker.pasteHint': 'Incolla o trascina qui un’immagine per farne uno sticker',
  'composer.sticker.nothingToPaste': 'Nessuna immagine negli appunti',
  'composer.sticker.empty': 'Ancora nessuno sticker — creane uno da un’immagine o incollane uno',
  'composer.sticker.creating': 'Creazione dello sticker…',
  'composer.sticker.manage': 'Gestisci',
  'composer.sticker.done': 'Fine',
  'composer.sticker.remove': 'Rimuovi questo sticker',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'Impossibile caricare questo sticker — riprova',
  'composer.sticker.error.notImage': 'Questo file non è un’immagine',
  'composer.sticker.error.tooLarge': 'Immagine troppo pesante per uno sticker',
  'composer.sticker.error.full': 'Libreria piena — rimuovi uno sticker per aggiungerne un altro',
  'composer.sticker.error.failed': 'Impossibile creare lo sticker',
  'composer.sticker.tabs': 'Famiglie di sticker',
  'composer.sticker.tab.instants': 'Istanti',
  'composer.sticker.tab.custom': 'Personalizzati',
  'composer.sticker.tab.favorites': 'Preferiti',
  'composer.sticker.favorites.empty': 'Tieni premuto o fai clic destro su uno sticker per fissarlo qui.',
  'composer.sticker.favorites.pinned': 'Fissato nei preferiti',
  'composer.sticker.favorites.unpinned': 'Rimosso dai preferiti',
  'composer.sticker.intent.bonjour.title': 'Ciao, grazie',
  'composer.sticker.intent.bonjour.hint': 'Per salutare, ringraziare, dire di sì, scusarsi o augurare la buonanotte',
  'composer.sticker.intent.amour.title': 'Dire ti amo',
  'composer.sticker.intent.amour.hint': 'Per una parola dolce, un bacio, un abbraccio o una dichiarazione',
  'composer.sticker.intent.fete.title': 'Ridere e festeggiare',
  'composer.sticker.intent.fete.hint': 'Per una bella notizia, un successo, un compleanno o una risata a crepapelle',
  'composer.sticker.intent.soutien.title': 'Consolare e sostenere',
  'composer.sticker.intent.soutien.hint': 'Per incoraggiare, confortare o dire «ci sono io»',
  'composer.sticker.intent.rale.title': 'Brontolare e tenere il muso',
  'composer.sticker.intent.rale.hint': 'Per esprimere fastidio, rabbia, gelosia o prendere le distanze',
  'composer.sticker.intent.coup-de-mou.title': 'Giù di morale',
  'composer.sticker.intent.coup-de-mou.hint': 'Per la tristezza, il dispiacere, la stanchezza o la voglia di dormire',
  'composer.sticker.intent.surprise.title': 'Sorpresa e brividi',
  'composer.sticker.intent.surprise.hint': 'Per lo stupore, la paura, l’imbarazzo o un «ops»',
  'composer.sticker.intent.quotidien.title': 'La vita di tutti i giorni',
  'composer.sticker.intent.quotidien.hint': 'Per dire cosa stai facendo: un caffè, un pasto, il lavoro, il viaggio, un ritardo',
  'composer.sticker.intent.humour-noir.title': 'Umorismo nero',
  'composer.sticker.intent.humour-noir.hint': 'Per ridere di tutto, anche del peggio: morire dal ridere, fantasmi e lapidi',
  'composer.sticker.instants.hint': 'Ciò che scrivi appare sullo sticker',
  'composer.sticker.instants.message': 'Messaggi',
  'composer.sticker.instants.moment': 'Momenti',
  'composer.sticker.instants.lieu': 'Luoghi',
  'composer.sticker.instants.meteo': 'Meteo',
  'composer.sticker.instants.field.message': 'Messaggio',
  'composer.sticker.instants.field.place': 'Luogo',
  'composer.sticker.instants.field.weather': 'Meteo',
  'composer.sticker.instants.field.time': 'Ora',
  'composer.quickEmoji.label': 'Invia direttamente',
  'composer.quickEmoji.group': 'Emoji rapide',
  'composer.effects.panel': 'Effetti del messaggio',
  'composer.effects.entrance': 'Animazione di ingresso',
  'composer.effects.permanent': 'Effetto permanente',
  'composer.effects.clearAll': 'Cancella tutto',
} satisfies ComposerAttachCatalogSlice;

export default itComposerAttach;
