/**
 * LES PACKS DE STICKERS (#9141) — tranche du catalogue `catalog-fr.ts` :
 * onglets de pack, boutique, proposition d'un pack par un tiers et ses refus
 * motivés. Le catalogue la RÉPAND.
 */
const frStickerPacks = {
  'stickerPacks.by': 'Par {author}',
  'stickerPacks.cancel': 'Annuler',
  'stickerPacks.send': 'Envoyer',
  'stickerPacks.count': '{count} stickers',
  'stickerPacks.install': 'Installer',
  'stickerPacks.uninstall': 'Retirer',
  'stickerPacks.tab.shop': 'Boutique',
  'stickerPacks.shop.hint': 'Installez les packs que vous voulez retrouver dans vos stickers, retirez les autres. Les stickers déjà envoyés restent lisibles.',
  'stickerPacks.error.install': 'Le pack n’a pas pu être modifié — réessayez',
  'stickerPacks.error.load': 'Les packs n’ont pas pu être chargés',
  'stickerPacks.kind.static': 'Fixes',
  'stickerPacks.kind.cinematic': 'Animés',
  'stickerPacks.kind.instant': 'Instants',
  'stickerPacks.status.pending': 'En attente',
  'stickerPacks.status.approved': 'Publié',
  'stickerPacks.status.rejected': 'Refusé',
  'stickerPacks.mine.title': 'Mes propositions',
  'stickerPacks.submit.open': 'Proposer un pack',
  'stickerPacks.submit.title': 'Proposer un pack',
  'stickerPacks.submit.back': 'Retour',
  'stickerPacks.submit.hint': 'Ajoutez au moins trois images (PNG, WebP, GIF ou JPEG). Une image animée devient un sticker animé ; cochez « Instant » pour qu’un sticker écrive le texte de celui qui l’envoie. Chaque pack est relu avant publication.',
  'stickerPacks.submit.name': 'Nom du pack',
  'stickerPacks.submit.description': 'Description',
  'stickerPacks.submit.author': 'Signature',
  'stickerPacks.submit.add': 'Ajouter des images',
  'stickerPacks.submit.itemTitle': 'Titre',
  'stickerPacks.submit.emoji': 'Emoji',
  'stickerPacks.submit.instant': 'Instant',
  'stickerPacks.submit.removeItem': 'Retirer ce sticker',
  'stickerPacks.submit.zoneHint': 'Tracez sur l’image la zone où le texte s’écrira. L’aperçu montre le texte le plus long admis.',
  'stickerPacks.submit.zoneDefault': 'Texte par défaut',
  'stickerPacks.submit.zoneLength': 'Longueur maximale',
  'stickerPacks.submit.send': 'Envoyer à la relecture',
  'stickerPacks.submit.sending': 'Envoi…',
  'stickerPacks.submit.failed': 'Le pack n’a pas pu être envoyé — réessayez',
  'stickerPacks.submit.slugTaken': 'Ce nom est déjà pris — choisissez-en un autre',
  'stickerPacks.submit.tooMany': 'Trois de vos packs attendent déjà leur relecture',
  'stickerPacks.submit.assetRefused': 'Une image n’a pas pu être lue — remplacez-la',
  'stickerPacks.submit.tooLarge': 'Le pack est trop lourd — retirez quelques images',
  'stickerPacks.problem.invalid': 'Un champ n’est pas valide',
  'stickerPacks.problem.reservedSlug': 'Ce nom est réservé — choisissez-en un autre',
  'stickerPacks.problem.duplicate': 'Deux stickers portent le même nom',
  'stickerPacks.problem.duplicateSlot': 'Deux zones portent le même nom',
  'stickerPacks.problem.zonesRequired': 'Un Instant a besoin d’une zone de texte',
  'stickerPacks.problem.zoneOutside': 'La zone sort de l’image',
  'stickerPacks.problem.zonesOverlap': 'Deux zones se chevauchent',
  'stickerPacks.problem.defaultTooLong': 'Le texte par défaut est plus long que la zone ne l’admet',
  'stickerPacks.problem.defaultOverflows': 'Le texte par défaut déborde de la zone',
  'stickerPacks.problem.longestOverflows': 'Un texte de la longueur maximale déborderait : agrandissez la zone ou réduisez la longueur',
  'stickerPacks.problem.count': 'Un pack compte entre 3 et 120 stickers',
  'stickerPacks.problem.packField': 'Donnez au pack un nom, une description et une signature',
} as const;

export default frStickerPacks;
