import type { ExportCardCatalog } from '@/lib/i18n-export-card-catalog';

const de = {
  'export.card.title': 'Imagine',
  'export.card.popular': 'Beliebt',
  'export.card.random': 'Zufällig',
  'export.card.palette': 'Farben',
  'export.card.typeface': 'Schrift',
  'export.card.link': 'Verbindung',
  'export.card.typeface.rond': 'Rund',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Feder',
  'export.card.typeface.affiche': 'Plakat',
  'export.card.typeface.futur': 'Futuristisch',
  'export.card.typeface.machine': 'Schreibmaschine',
  'export.card.typeface.marqueur': 'Marker',
  'export.card.typeface.systeme': 'System',
  'export.card.link.orbite': 'Orbit',
  'export.card.link.filet': 'Linie',
  'export.card.link.guillemets': 'Anführungszeichen',
  'export.card.link.fleche': 'Pfeil',
  'export.card.link.bulles': 'Blasen',
  'export.card.link.fil': 'Faden',
  'export.card.link.silence': 'Stille',
  'export.card.option.anonymizeQuoted': 'Zitierte Nachricht anonymisieren',
  'export.card.option.anonymizeReply': 'Antwort anonymisieren',
  'export.card.anonymous': 'Anonym',
  'export.card.preview': 'Bildvorschau',
  'export.card.rendering': 'Bild wird vorbereitet…',
  'export.card.save': 'Speichern',
  'export.card.share': 'Teilen',
  'export.card.language': 'Sprache der Nachricht',
  'export.card.language.asRead': 'Wie ich sie lese',
  'export.card.truncated': 'Lange Nachricht: Das Ende wird im Bild abgeschnitten.',
  'export.announce.gallery': 'Bild in der Galerie gesichert',
  'export.announce.shared': 'Bild bereit',
  'export.announce.cancelled': 'Export abgebrochen',
  'export.announce.expired': 'Zum Sichern erneut tippen',
  'export.announce.failed': 'Bild konnte nicht erstellt werden',
  'export.announce.unavailable': 'Dieses Gerät kann das Bild nicht sichern',
  'export.card.options': 'Anzeigen',
  'export.card.option.title': 'Titel der Unterhaltung',
  'export.card.option.authors': 'Namen der Verfasser',
  'export.card.option.date': 'Datum',
  'export.card.default.save': 'Als Standardformat verwenden',
  'export.card.default.current': 'Standardformat',
  'export.announce.defaultSaved': 'Standardformat gesichert',
  'export.card.tab.styles': 'Stile',
  'export.card.tab.palette': 'Hintergrund',
  'export.card.tab.typeface': 'Schrift',
  'export.card.tab.link': 'Verbindung',
  'export.card.tab.details': 'Details',
  'export.card.tab.language': 'Sprache',
  'export.card.part.header': 'Kopfzeile',
  'export.card.part.quote': 'Zitat',
  'export.card.part.link': 'Verbindung',
  'export.card.part.reply': 'Antwort',
  'export.card.part.background': 'Hintergrund',
  'export.card.hint': 'Tippe auf einen Teil der Karte, um ihn anzupassen',
  'export.card.gallery.open': 'Alle ansehen',
  'export.card.gallery.title': 'Alle Stile',
  'export.card.gallery.count': '{count} Stile',
  'export.card.gallery.close': 'Galerie schließen',
  'export.card.gallery.search': 'Stil suchen',
  'export.card.gallery.placeholder': 'Feder, dunkel, Blasen …',
  'export.card.gallery.empty': 'Kein Stil heißt so. Versuche eine Farbe, eine Schrift oder „dunkel“.',
  'export.card.tone.all': 'Alle',
  'export.card.tone.dark': 'Dunkel',
  'export.card.tone.light': 'Hell',
  'export.card.typeface.pairs': 'Die Schrift gilt für Zitat und Antwort',
  'export.card.tab.frame': 'Rahmen',
  'export.card.tab.media': 'Medien',
  'export.card.part.media': 'Medien',
  'export.card.part.replies': 'Antworten',
  'export.card.aspect': 'Bildformat',
  'export.card.aspect.auto': 'Angepasst',
  'export.card.aspect.story': 'Story 9:16',
  'export.card.aspect.portrait': 'Hochformat 4:5',
  'export.card.aspect.square': 'Quadrat 1:1',
  'export.card.aspect.landscape': 'Querformat 16:9',
  'export.card.header': 'Titel und Datum',
  'export.card.header.horizontal': 'In einer Zeile',
  'export.card.header.letters': 'Buchstabe für Buchstabe',
  'export.card.header.up': 'Nach oben',
  'export.card.header.down': 'Nach unten',
  'export.card.authorsAt': 'Namen',
  'export.card.authorsAt.top': 'Über der Nachricht',
  'export.card.authorsAt.end': 'Am Ende der Nachricht',
  'export.card.tilt': 'Drehung der Nachricht',
  'export.card.tilt.none': 'Gerade',
  'export.card.tilt.left': 'Nach links geneigt',
  'export.card.tilt.right': 'Nach rechts geneigt',
  'export.card.option.times': 'Uhrzeiten der Nachrichten',
  'export.card.option.pseudonyms': 'Benutzername statt Anzeigename',
  'export.card.anonymity': 'Anonymität',
  'export.card.media.style': 'Bildanordnung',
  'export.card.media.mosaique': 'Mosaik',
  'export.card.media.pleine': 'Volle Breite',
  'export.card.media.bande': 'Streifen',
  'export.card.audio.style': 'Audio-Darstellung',
  'export.card.audio.onde': 'Welle',
  'export.card.audio.spectre': 'Spektrum',
  'export.card.audio.pastille': 'Pille',
  'export.card.audio.etiquette': 'Etikett',
  'export.card.media.loading': 'Medien werden geladen…',
  'export.card.output': 'Speichern als',
  'export.card.output.image': 'Bild',
  'export.card.output.gif': 'GIF',
  'export.card.output.video': 'Video',
  'export.card.motion.video': 'Video wird erstellt…',
  'export.card.motion.gif': 'GIF wird erstellt…',
  'export.announce.motionUnavailable': 'Dieser Browser kann diese Animation nicht erstellen',
  'export.announce.galleryMotion': 'In der Galerie gesichert',
  'export.announce.sharedMotion': 'Bereit zum Teilen',
} satisfies ExportCardCatalog;

export default de;
