import type { StickerPacksCatalog } from '@/lib/i18n-sticker-packs-catalog';

/** LE CATALOGUE DES PACKS DE STICKERS (#9141), langue `it` — mêmes clés que le français. */
const itStickerPacks = {
  'stickerPacks.by': 'Di {author}',
  'stickerPacks.cancel': 'Annulla',
  'stickerPacks.send': 'Invia',
  'stickerPacks.count': '{count} sticker',
  'stickerPacks.tab.shop': 'Negozio',
  'stickerPacks.install': 'Installa',
  'stickerPacks.uninstall': 'Rimuovi',
  'stickerPacks.shop.hint': 'Installa i pacchetti che vuoi ritrovare nei tuoi sticker e rimuovi gli altri. Gli sticker già inviati restano leggibili.',
  'stickerPacks.error.install': 'Impossibile modificare il pacchetto — riprova',
  'stickerPacks.error.load': 'Impossibile caricare i pacchetti',
  'stickerPacks.kind.static': 'Fissi',
  'stickerPacks.kind.cinematic': 'Animati',
  'stickerPacks.kind.instant': 'Instant',
  'stickerPacks.status.pending': 'In attesa',
  'stickerPacks.status.approved': 'Pubblicato',
  'stickerPacks.status.rejected': 'Rifiutato',
  'stickerPacks.mine.title': 'Le mie proposte',
  'stickerPacks.submit.open': 'Proponi un pacchetto',
  'stickerPacks.submit.title': 'Proponi un pacchetto',
  'stickerPacks.submit.back': 'Indietro',
  'stickerPacks.submit.hint': 'Aggiungi almeno tre immagini (PNG, WebP, GIF o JPEG). Un’immagine animata diventa uno sticker animato; seleziona «Instant» perché uno sticker scriva il testo di chi lo invia. Ogni pacchetto viene revisionato prima della pubblicazione.',
  'stickerPacks.submit.name': 'Nome del pacchetto',
  'stickerPacks.submit.description': 'Descrizione',
  'stickerPacks.submit.author': 'Firma',
  'stickerPacks.submit.add': 'Aggiungi immagini',
  'stickerPacks.submit.itemTitle': 'Titolo',
  'stickerPacks.submit.emoji': 'Emoji',
  'stickerPacks.submit.instant': 'Instant',
  'stickerPacks.submit.removeItem': 'Rimuovi questo sticker',
  'stickerPacks.submit.zoneHint': 'Disegna sull’immagine la zona in cui verrà scritto il testo. L’anteprima mostra il testo più lungo consentito.',
  'stickerPacks.submit.zoneDefault': 'Testo predefinito',
  'stickerPacks.submit.zoneLength': 'Lunghezza massima',
  'stickerPacks.submit.send': 'Invia in revisione',
  'stickerPacks.submit.sending': 'Invio…',
  'stickerPacks.submit.failed': 'Impossibile inviare il pacchetto — riprova',
  'stickerPacks.submit.slugTaken': 'Questo nome è già usato — scegline un altro',
  'stickerPacks.submit.tooMany': 'Tre dei tuoi pacchetti attendono già la revisione',
  'stickerPacks.submit.assetRefused': 'Impossibile leggere un’immagine — sostituiscila',
  'stickerPacks.submit.tooLarge': 'Il pacchetto è troppo pesante — rimuovi qualche immagine',
  'stickerPacks.problem.invalid': 'Un campo non è valido',
  'stickerPacks.problem.reservedSlug': 'Questo nome è riservato — scegline un altro',
  'stickerPacks.problem.duplicate': 'Due sticker hanno lo stesso nome',
  'stickerPacks.problem.duplicateSlot': 'Due zone hanno lo stesso nome',
  'stickerPacks.problem.zonesRequired': 'Un Instant ha bisogno di una zona di testo',
  'stickerPacks.problem.zoneOutside': 'La zona esce dall’immagine',
  'stickerPacks.problem.zonesOverlap': 'Due zone si sovrappongono',
  'stickerPacks.problem.defaultTooLong': 'Il testo predefinito è più lungo di quanto la zona consente',
  'stickerPacks.problem.defaultOverflows': 'Il testo predefinito esce dalla zona',
  'stickerPacks.problem.longestOverflows': 'Un testo di lunghezza massima uscirebbe: allarga la zona o riduci la lunghezza',
  'stickerPacks.problem.count': 'Un pacchetto ha da 3 a 120 sticker',
  'stickerPacks.problem.packField': 'Dai al pacchetto un nome, una descrizione e una firma',
} satisfies StickerPacksCatalog;

export default itStickerPacks;
