/**
 * L'EXPORT D'UN MESSAGE EN IMAGE, FRANÇAIS (#8667) — la SOURCE des clés du
 * composer d'export (`routes/thread-export-*.tsx`). Les six autres langues
 * portent exactement ces clés (`satisfies ExportCardCatalog`,
 * `i18n-export-card-catalog.test.ts`). Seules les deux entrées du menu du
 * message restent au catalogue d'interface (`catalog-fr-message-card.ts`) :
 * elles sont visibles avant que le composer ne soit chargé.
 */
const fr = {
  'export.card.title': 'Imagine',
  'export.card.popular': 'Populaires',
  'export.card.random': 'Au hasard',
  'export.card.palette': 'Couleurs',
  'export.card.typeface': 'Typographie',
  'export.card.link': 'Liaison',
  'export.card.typeface.rond': 'Ronde',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Plume',
  'export.card.typeface.affiche': 'Affiche',
  'export.card.typeface.futur': 'Futuriste',
  'export.card.typeface.machine': 'Machine à écrire',
  'export.card.typeface.marqueur': 'Marqueur',
  'export.card.typeface.systeme': 'Système',
  'export.card.link.orbite': 'Orbite',
  'export.card.link.filet': 'Filet',
  'export.card.link.guillemets': 'Guillemets',
  'export.card.link.fleche': 'Flèche',
  'export.card.link.bulles': 'Bulles',
  'export.card.link.fil': 'Fil',
  'export.card.link.silence': 'Silence',
  'export.card.option.anonymizeQuoted': 'Anonymiser le message cité',
  'export.card.option.anonymizeReply': 'Anonymiser la réponse',
  'export.card.anonymous': 'Anonyme',
  'export.card.preview': 'Aperçu de l’image',
  'export.card.rendering': 'Préparation de l’image…',
  'export.card.save': 'Sauvegarder',
  'export.card.share': 'Partager',
  'export.card.language': 'Langue du message',
  'export.card.language.asRead': 'Comme je le lis',
  'export.card.truncated': 'Message long : la fin est coupée sur l’image.',
  'export.announce.gallery': 'Image enregistrée dans la galerie',
  'export.announce.shared': 'Image prête',
  'export.announce.cancelled': 'Export annulé',
  'export.announce.expired': 'Touchez de nouveau pour enregistrer',
  'export.announce.failed': 'Impossible de créer l’image',
  'export.announce.unavailable': 'Cet appareil ne sait pas enregistrer l’image',
  'export.card.options': 'Afficher',
  'export.card.option.title': 'Titre de la conversation',
  'export.card.option.authors': 'Noms des auteurs',
  'export.card.option.date': 'Date',
  'export.card.default.save': 'Utiliser comme format par défaut',
  'export.card.default.current': 'Format par défaut',
  'export.announce.defaultSaved': 'Format par défaut enregistré',
  'export.card.tab.styles': 'Styles',
  'export.card.tab.palette': 'Fond',
  'export.card.tab.typeface': 'Police',
  'export.card.tab.link': 'Liaison',
  'export.card.tab.details': 'Détails',
  'export.card.tab.language': 'Langue',
  'export.card.part.header': 'En-tête',
  'export.card.part.quote': 'Citation',
  'export.card.part.link': 'Liaison',
  'export.card.part.reply': 'Réponse',
  'export.card.part.background': 'Fond',
  'export.card.hint': 'Touchez une partie de la carte pour la régler',
  'export.card.gallery.open': 'Tout voir',
  'export.card.gallery.title': 'Tous les styles',
  'export.card.gallery.count': '{count} styles',
  'export.card.gallery.close': 'Fermer la galerie',
  'export.card.gallery.search': 'Chercher un style',
  'export.card.gallery.placeholder': 'Plume, sombre, bulles…',
  'export.card.gallery.empty': 'Aucun style ne porte ce nom. Essayez une couleur, une police ou « sombre ».',
  'export.card.tone.all': 'Tous',
  'export.card.tone.dark': 'Sombre',
  'export.card.tone.light': 'Clair',
  'export.card.typeface.pairs': 'La police habille la citation et la réponse',
  'export.card.tab.frame': 'Frame',
  'export.card.tab.media': 'Médias',
  'export.card.part.media': 'Médias',
  'export.card.aspect': 'Format de l’image',
  'export.card.aspect.auto': 'Ajusté',
  'export.card.aspect.story': 'Story 9:16',
  'export.card.aspect.portrait': 'Portrait 4:5',
  'export.card.aspect.square': 'Carré 1:1',
  'export.card.aspect.landscape': 'Paysage 16:9',
  'export.card.header': 'Titre et date',
  'export.card.header.horizontal': 'En ligne',
  'export.card.header.letters': 'Lettre à lettre',
  'export.card.header.up': 'Vers le haut',
  'export.card.header.down': 'Vers le bas',
  'export.card.authorsAt': 'Noms',
  'export.card.authorsAt.top': 'Au-dessus du message',
  'export.card.authorsAt.end': 'À la fin du message',
  'export.card.tilt': 'Rotation du message',
  'export.card.tilt.none': 'Droit',
  'export.card.tilt.left': 'Penché à gauche',
  'export.card.tilt.right': 'Penché à droite',
  'export.card.option.times': 'Heures des messages',
  'export.card.option.pseudonyms': 'Pseudo au lieu du nom affiché',
  'export.card.anonymity': 'Anonymat',
  'export.card.media.style': 'Disposition des images',
  'export.card.media.mosaique': 'Mosaïque',
  'export.card.media.pleine': 'Pleine largeur',
  'export.card.media.bande': 'Bande',
  'export.card.audio.style': 'Représentation de l’audio',
  'export.card.audio.onde': 'Onde',
  'export.card.audio.spectre': 'Spectre',
  'export.card.audio.pastille': 'Pastille',
  'export.card.audio.etiquette': 'Étiquette',
  'export.card.media.loading': 'Chargement des médias…',
  'export.card.output': 'Enregistrer en',
  'export.card.output.image': 'Image',
  'export.card.output.gif': 'GIF',
  'export.card.output.video': 'Vidéo',
  'export.card.motion.video': 'Création de la vidéo…',
  'export.card.motion.gif': 'Création du GIF…',
  'export.announce.motionUnavailable': 'Ce navigateur ne sait pas créer cette animation',
  'export.announce.galleryMotion': 'Enregistré dans la galerie',
  'export.announce.sharedMotion': 'Prêt à partager',
} as const;

export default fr;
