import type { CallStudioCatalog } from '@/lib/i18n-call-studio-catalog';

/** Le studio d'un appel vidéo — it (#8551, #8552). */
const it = {
  'callStudio.effects.color': 'Colore',
  'callStudio.effects.settings': 'Regolazioni',
  'callStudio.face.none': 'Nessuno',
  'callStudio.face.smoothing': 'Levigatura della pelle',
  'callStudio.face.toad': 'Rospo',
  'callStudio.face.angel': 'Angelo',
  'callStudio.face.demon': 'Demone',
  'callStudio.face.volcano': 'Eruzione',
  'callStudio.montage.screen': 'Schermo intero',
  'callStudio.montage.grid': 'Mosaico',
  'callStudio.montage.strip': 'Cabina fototessere',
  'callStudio.montage.polaroid': 'Polaroid',
  'callStudio.montage.magazine': 'Rivista',
  'callStudio.montage.comic': 'Fumetto',
  'callStudio.montage.heart': 'Cuore',
  'callStudio.capture.preview': 'Anteprima del montaggio {style}',
  'callStudio.capture.faces': 'Ogni volto',
  'callStudio.capture.facesLabel': 'Salva ogni volto separatamente',
  'callStudio.capture.saved': 'Cattura salvata',
  'callStudio.capture.faceSaved': '1 volto salvato',
  'callStudio.capture.facesSaved': '{count} volti salvati',
  'callStudio.capture.failed': 'Impossibile salvare la cattura',
  'callStudio.capture.cancelled': 'Salvataggio annullato',
  'callStudio.capture.empty': 'Niente da catturare: nessuna immagine visualizzata',
  'callStudio.capture.busy': 'Cattura in corso…',
  'callStudio.capture.bubble': 'Che chiamata!',
  'callStudio.montage.cover': 'Copertina',
  'callStudio.montage.gold': 'Oro',
  'callStudio.montage.redcarpet': 'Tappeto rosso',
  'callStudio.montage.film': 'Pellicola',
  'callStudio.montage.neon': 'Neon',
  'callStudio.montage.noir': 'Bianco e nero',
  'callStudio.cover.line1': 'La chiamata dell’anno',
  'callStudio.cover.line2': 'Finalmente tutti insieme',
  'callStudio.cover.line3': 'Esclusiva',
  'callStudio.mode.effects': 'Effetti del mio video',
  'callStudio.mode.montage': 'Cattura la chiamata',
  'callStudio.mode.quit': 'Esci',
  'callStudio.mode.quitEffects': 'Esci senza mantenere queste modifiche',
  'callStudio.mode.validateLabel': 'Mantieni questo effetto e torna alla chiamata',
  'callStudio.mode.face': 'Viso',
  'callStudio.mode.categories': 'Categoria',
  'callStudio.mode.pickEffect': 'Scegli un effetto',
  'callStudio.mode.pickMontage': 'Scegli un montaggio',
  'callStudio.mode.settingsLabel': 'Mostra le impostazioni (luminosità, sfocatura)',
  'callStudio.capture.hint': 'Doppio tocco: foto · Pressione lunga: video',
  'callStudio.capture.gestures': 'Doppio tocco, o Invio: una foto. Pressione lunga: un video, con audio.',
  'callStudio.record.start': 'Registra un video, con audio',
  'callStudio.record.stop': 'Ferma il video e salvalo',
  'callStudio.record.saved': 'Video salvato',
  'callStudio.record.failed': 'Impossibile salvare il video',
  'callStudio.record.unsupported': 'Questo browser non può registrare la chiamata',
  'callStudio.record.clock': 'Registrazione in corso, {time}',
  'callStudio.companions.label': 'Partecipanti alla chiamata',
  'callStudio.companions.more': 'Altri {count} partecipanti',
  'callStudio.companions.move': 'Sposta sull’altro lato',
  'callStudio.frames.moods': 'Atmosfere',
  'callStudio.frames.mood.classics': 'Classici',
  'callStudio.frames.mood.signature': 'Firma',
  'callStudio.frames.mood.distingue': 'Distinto',
  'callStudio.frames.mood.elegant': 'Elegante',
  'callStudio.frames.mood.jovial': 'Allegro',
  'callStudio.frames.mood.deconnecte': 'Disconnesso',
  'callStudio.frames.mood.corporate': 'Aziendale',
  'callStudio.frames.mood.fantastique': 'Fantastico',
  'callStudio.frames.mood.futuriste': 'Futuristico',
  'callStudio.frames.mood.glauque': 'Cupo',
  'callStudio.frames.mood.hors-norme': 'Fuori dal comune',
  'callStudio.frames.mood.morbide': 'Macabro',
  'callStudio.frames.mood.feerique': 'Fiabesco',
  'callStudio.mode.pickFrame': 'Scegli una cornice',
  'callStudio.capture.framePreview': 'Anteprima della cornice {name}',
} satisfies CallStudioCatalog;

export default it;
