import type { SendSheetCatalog } from '@/lib/i18n-send-sheet-catalog';

const ar = {
  'sendSheet.title.forward': 'إعادة توجيه',
  'sendSheet.title.share': 'مشاركة',
  'sendSheet.title.sendTo': 'إرسال إلى…',
  'sendSheet.cancel': 'إلغاء',
  'sendSheet.caption.label': 'رسالة',
  'sendSheet.caption.placeholder': 'أضف رسالة…',
  'sendSheet.search.label': 'ابحث عن شخص أو محادثة',
  'sendSheet.search.placeholder': 'ابحث عن شخص أو محادثة',
  'sendSheet.empty': 'لا توجد نتائج',
  'sendSheet.section.recent': 'الأحدث',
  'sendSheet.section.people': 'الأشخاص',
  'sendSheet.section.conversations': 'المحادثات',
  'sendSheet.section.publish': 'نشر',
  'sendSheet.publish.story': 'قصتي',
  'sendSheet.publish.post': 'منشور',
  'sendSheet.publish.reel': 'ريل',
  'sendSheet.send': 'إرسال',
  'sendSheet.sendCount': 'إرسال ({count})',
  'sendSheet.row.select': 'تحديد {name}',
  'sendSheet.selectedCount': 'تم تحديد {count}',
  'sendSheet.state.sending': 'جارٍ الإرسال…',
  'sendSheet.state.sent': 'تم الإرسال',
  'sendSheet.state.failed': 'فشل',
  'sendSheet.state.retry': 'إعادة المحاولة',
  'sendSheet.state.waitingNetwork': 'في انتظار الشبكة',
  'sendSheet.failure.download': 'تعذّر الحصول على الملف',
  'sendSheet.failure.refused': 'تم رفض الإرسال',
  'sendSheet.limit.recipients': 'بحد أقصى {count} مستلمين',
  'sendSheet.error.captionTooLong': 'هذه الرسالة أطول من أن تُنشر (بحد أقصى {count} حرفًا)',
  'sendSheet.error.tooManyFiles': 'بحد أقصى {count} ملفات لكل منشور',
  'sendSheet.moreOptions': 'المزيد من الخيارات…',
  'sendSheet.copyLink': 'نسخ الرابط',
  'sendSheet.linkCopied': 'تم نسخ الرابط',
  'sendSheet.announce.sent': 'تم الإرسال إلى {count}',
  'sendSheet.preview.messages': '{count} رسالة',
  'sendSheet.preview.photo': 'صورة',
  'sendSheet.preview.video': 'فيديو',
  'sendSheet.preview.voice': 'رسالة صوتية',
  'sendSheet.preview.file': 'ملف',
  'sendSheet.preview.publication': 'منشور',
  'sendSheet.protected': 'محتوى محمي: لا يمكن نشره',
  'shareLinkSheet.title': 'إنشاء رابط مشاركة',
  'shareLinkSheet.empty': 'لا يمكن لأي محادثة استقبال رابط في الوقت الحالي.',
  'shareLinkSheet.createFailed': 'تعذّر إنشاء الرابط — حاول مرة أخرى بعد قليل.',
  'shareLinkSheet.copied': 'تم نسخ الرابط — يكفي لصقه.',
  'shareLinkSheet.unavailable': 'تعذّرت المشاركة هنا. انسخ عنوان هذه الصفحة.',
} satisfies SendSheetCatalog;

export default ar;
