import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const enComposerAttach = {
  'composer.attach.group': 'Attachment types',
  'composer.attach.handle': 'Panel handle',
  'composer.attach.photo': 'Photos',
  'composer.attach.photo.action': 'Choose photos',
  'composer.attach.camera': 'Camera',
  'composer.attach.camera.action': 'Take a photo',
  'composer.attach.file': 'File',
  'composer.attach.file.action': 'Choose a file',
  'composer.attach.contact': 'Contact',
  'composer.attach.contact.action': 'Share a contact',
  'composer.contact.failed': "This contact can't be shared",
  'composer.attach.location': 'Location',
  'composer.attach.location.action': 'Share my location',
  'composer.attach.voice': 'Voice',
  'composer.attach.voice.action': 'Record a voice message',
  'composer.attach.emoji': 'Emoji',
  'composer.attach.emoji.action': 'Insert an emoji',
  'composer.emoji.title': 'Insert an emoji',
  'composer.location.locating': 'Finding your location…',
  'composer.location.denied': 'Location denied — allow it in settings',
  'composer.location.unavailable': 'Location unavailable in this browser',
  'composer.location.failed': 'Location not found — try again',
  'composer.mic.refused': 'Microphone denied — allow it in settings',
  'composer.mic.unavailable': 'Microphone unavailable on this device',
  'composer.openSettings': 'Settings',
  'composer.location.chip': 'PLACE',
  'composer.location.unknown': 'Unknown place',
  'composer.location.remove': 'Remove the location',
  'composer.attach.sticker': 'Sticker',
  'composer.attach.sticker.action': 'Send a sticker',
  'composer.sticker.title': 'My stickers',
  'composer.sticker.fromImage': 'From an image',
  'composer.sticker.paste': 'Paste',
  'composer.sticker.pasteHint': 'Paste or drop an image here to make it a sticker',
  'composer.sticker.nothingToPaste': 'No image on the clipboard',
  'composer.sticker.empty': 'No stickers yet — create one from an image or paste one',
  'composer.sticker.creating': 'Creating sticker…',
  'composer.sticker.manage': 'Manage',
  'composer.sticker.done': 'Done',
  'composer.sticker.remove': 'Remove this sticker',
  'composer.sticker.item': 'Sticker',
  'composer.sticker.unavailable': 'This sticker could not be loaded — try again',
  'composer.sticker.error.notImage': 'This file is not an image',
  'composer.sticker.error.tooLarge': 'Image too large for a sticker',
  'composer.sticker.error.full': 'Library full — remove a sticker to add another',
  'composer.sticker.error.failed': 'The sticker could not be created',
  'composer.sticker.tabs': 'Sticker families',
  'composer.sticker.tab.mine': 'My stickers',
  'composer.sticker.tab.instants': 'Moments',
  'composer.sticker.mee.solo': 'Mee alone',
  'composer.sticker.mee.duo': 'Together — Mee makes the move',
  'composer.sticker.meo.solo': 'Meo alone',
  'composer.sticker.meo.duo': 'Together — Meo makes the move',
  'composer.sticker.mee.hint': 'Mee, the Meeshy mascot, in motion',
  'composer.sticker.meo.hint': 'Meo, her twin, in motion',
  'composer.sticker.instants.hint': 'What you type appears on the sticker',
  'composer.sticker.instants.message': 'Messages',
  'composer.sticker.instants.moment': 'Times of day',
  'composer.sticker.instants.lieu': 'Places',
  'composer.sticker.instants.meteo': 'Weather',
  'composer.sticker.instants.field.message': 'Message',
  'composer.sticker.instants.field.place': 'Place',
  'composer.sticker.instants.field.weather': 'Weather',
  'composer.sticker.instants.field.time': 'Time',
  'composer.sticker.instants.placeholder.message': 'Thinking of you',
  'composer.sticker.instants.placeholder.place': 'At the beach',
  'composer.sticker.instants.placeholder.weather': 'Sunny, 75°',
  'composer.sticker.instants.placeholder.time': 'Now',
  'composer.quickEmoji.label': 'Send directly',
  'composer.quickEmoji.group': 'Quick emojis',
  'composer.effects.panel': 'Message effects',
  'composer.effects.entrance': 'Entrance animation',
  'composer.effects.permanent': 'Permanent effect',
  'composer.effects.clearAll': 'Clear all',
} satisfies ComposerAttachCatalogSlice;

export default enComposerAttach;
