import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const arStudioChrome = {
  'story.studio.more': 'خيارات أخرى',
  'story.studio.preview': 'معاينة',
  'story.studio.preview.close': 'إغلاق المعاينة',
  'story.studio.page.remove.current': 'حذف هذا المشهد',
  'story.studio.postText': 'نص المنشور',
  'story.studio.postText.placeholder': 'اكتب نص المنشور…',
  'story.studio.postText.done': 'تم',
  'story.studio.tile.page': 'مشهد',
  'story.studio.tile.text': 'نص',
  'story.studio.tile.time': 'الوقت',
  'story.studio.rail.scene': 'أدوات المشهد',
  'story.studio.timeline.unit': 'ث',
  'story.studio.tile.frame': 'الإطار',
  'story.studio.undo': 'تراجع',
  'story.studio.redo': 'إعادة',
  'story.studio.frame': 'الإطار',
  'story.studio.frame.media': 'الوسائط',
  'story.studio.frame.around': 'حول الوسائط',
  'story.studio.frame.fit': 'ملاءمة',
  'story.studio.frame.fill': 'ملء',
  'story.studio.frame.fit.hint': 'كاملة داخل إطار 9:16. لا يُقصّ شيء.',
  'story.studio.frame.fill.hint': 'تغطي إطار 9:16 كله، مع قصّ الحواف عند الحاجة.',
  'story.studio.backdrop.blur': 'ضبابي',
  'story.studio.backdrop.black': 'أسود',
  'story.studio.backdrop.white': 'أبيض',
  'story.studio.backdrop.indigo': 'نيلي',
  'story.studio.backdrop.sand': 'رملي',
  'story.studio.animated': 'متحرك',
  'story.studio.timeline': 'الخط الزمني للمشهد',
  'story.studio.timeline.play': 'تشغيل',
  'story.studio.timeline.pause': 'إيقاف مؤقت',
  'story.studio.timeline.empty': 'اكتب نصًا أو ضع طبقة: لكل عنصر مساره.',
  'story.studio.timeline.overlay': 'طبقة',
  'story.studio.retouch.title': 'تعديل الصورة',
  'story.studio.retouch.done': 'تم',
  'story.studio.retouch.cancel': 'تجاهل التعديل',
  'composer.attachment.edit': 'تعديل {name}',
  'story.studio.retouch.failed': 'تعذّر إنشاء الصورة.',
  'story.studio.timeline.enter': 'يدخل هنا',
  'story.studio.timeline.exit': 'يخرج هنا',
  'story.studio.timeline.scrub': 'تحريك رأس التشغيل',
  'story.studio.timeline.track': 'مسار {name}',
  'story.studio.timeline.earlier': 'أبكر',
  'story.studio.timeline.later': 'لاحقًا',
  'story.studio.editor.filter': 'مرشّح',
  'story.studio.filter.vintage': 'عتيق',
  'story.studio.filter.bw': 'أبيض وأسود',
  'story.studio.filter.warm': 'دافئ',
  'story.studio.filter.cool': 'بارد',
  'story.studio.filter.dramatic': 'درامي',
  'story.studio.filter.vivid': 'زاهٍ',
  'story.studio.filter.fade': 'باهت',
  'story.studio.filter.chrome': 'كروم',
  'story.studio.object.menu': 'إجراءات {name}',
  'story.studio.object.raise': 'تقديم',
  'story.studio.object.lower': 'إرجاع',
  'story.studio.object.duplicate': 'تكرار',
  'story.studio.object.edit': 'تعديل',
  'story.studio.object.remove': 'إزالة',
  'story.studio.edit.done': 'حسنًا',
  'story.studio.pose.left': 'إلى اليسار',
  'story.studio.pose.right': 'إلى اليمين',
  'story.studio.pose.up': 'إلى الأعلى',
  'story.studio.pose.down': 'إلى الأسفل',
  'story.studio.objects.edit': 'تعديل {name}',
  'story.studio.media.alt': 'النص البديل',
  'story.studio.media.alt.placeholder': 'صِف هذه الوسائط لقارئات الشاشة',
  'composer.reelOffer.title': 'النشر كريل؟',
  'composer.reelOffer.body': 'منشورك يحتوي على فيديو واحد فقط: كريل، يُعرض بملء الشاشة في الريلز.',
  'composer.reelOffer.reel': 'إنه ريل',
  'composer.reelOffer.post': 'إنه منشور',
  'story.studio.tool.close': 'إغلاق الأداة',
  'story.studio.camera.quick.tapPhoto': 'المس: صورة',
  'story.studio.camera.quick.holdFilm': 'اضغط مطولًا: تصوير',
  'story.studio.camera.quick.videoOnly': 'اضغط مطولًا للتصوير',
  'story.studio.camera.quick.photo': 'التقاط صورة',
  'story.studio.camera.quick.video': 'تصوير',
  'story.studio.camera.title': 'الكاميرا',
  'story.studio.camera.close': 'العودة إلى المشهد',
  'story.studio.camera.flip': 'تبديل الكاميرا',
  'story.studio.camera.flash': 'الفلاش',
  'story.studio.camera.shutter.photo': 'التقاط صورة',
  'story.studio.camera.shutter.start': 'بدء التسجيل',
  'story.studio.camera.shutter.stop': 'إيقاف التسجيل',
  'story.studio.camera.hint.photo': 'المس: صورة · اضغط مطولًا: فيديو',
  'story.studio.camera.hint.video': 'المس للتصوير · المس مجددًا للوضع',
  'story.studio.camera.unavailable': 'الكاميرا غير متاحة. اسمح بها في إعدادات المتصفح.',
  'story.studio.camera.recording': 'جارٍ التسجيل',
  'story.studio.scene.empty.title': 'هذا مشهدك',
  'story.studio.scene.empty.invite': 'أضِف نصًا أو رسمًا أو صورة أو فيديو، واجعله على طريقتك.',
  'story.studio.camera.locked': 'تم تثبيت التسجيل',
  'story.studio.camera.hint.holding': 'اسحب نحو القفل لتثبيت التسجيل · إلى الأعلى للتكبير',
  'story.studio.camera.hint.locked': 'بدون يدين — اسحب للأعلى أو للأسفل للتكبير',
  'story.studio.camera.flash.intensity': 'شدة الفلاش',
  'story.studio.camera.flash.intensityValue': '{percent}٪',
} satisfies StudioChromeCatalogSlice;

export default arStudioChrome;
