import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const en = {
  'admin.role': 'Your role: {role}',
  'admin.denied.title': 'Restricted area',
  'admin.denied.message': 'This area requires an administration right.',
  'admin.counters.title': 'At a glance',
  'admin.counters.unavailable': 'Counters unavailable right now.',
  'admin.counters.users': 'Accounts',
  'admin.counters.activeUsers': 'Active accounts',
  'admin.counters.messages': 'Messages',
  'admin.counters.communities': 'Communities',
  'admin.counters.reports': 'Reports',
  'admin.counters.newUsers': 'New (24 h)',
  'admin.sections.title': 'Sections',
  'admin.nav.dashboard': 'Dashboard',
  'admin.nav.users': 'Accounts',
  'admin.nav.moderation': 'Moderation',
  'admin.nav.audit': 'Audit logs',
  'admin.nav.analytics': 'Analytics',
  'admin.nav.trackingLinks': 'Tracking links',
  'admin.nav.ranking': 'Ranking',
  'admin.nav.broadcasts': 'Broadcasts',
  'admin.nav.settings': 'Settings',
  'admin.nav.agent': 'Agent',
  'admin.nav.monitoring': 'Monitoring',
  'admin.users.search': 'Search an account',
  'admin.users.count': '{count} account(s)',
  'admin.users.empty': 'No account matches.',
  'admin.users.unavailable': 'List unavailable right now.',
  'admin.users.inactive': 'disabled',
  'admin.users.previous': 'Previous',
  'admin.users.next': 'Next',
  'admin.user.title': 'Member',
  'admin.user.unavailable': 'Profile unavailable right now.',
  'admin.user.identity': 'Identity',
  'admin.user.account': 'Account',
  'admin.user.created': 'Joined on',
  'admin.user.lastActive': 'Last active',
  'admin.user.twoFactor': 'Two-factor',
  'admin.user.enabled': 'enabled',
  'admin.user.deleted': 'deleted',
  'admin.user.role': 'Role',
  'admin.edit.open': 'Edit',
  'admin.edit.title': 'Edit member',
  'admin.edit.displayName': 'Display name',
  'admin.edit.email': 'Email',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Account active',
  'admin.edit.save': 'Save',
  'admin.edit.reason': 'Reason (optional)',
  'admin.edit.warnRole': 'Changing the role changes their permissions.',
  'admin.edit.warnDeactivate': 'Deactivating ends their open sessions.',
  'admin.edit.confirm': 'Confirm',
  'admin.edit.saved': 'Changes saved',
  'admin.edit.failed': 'Could not save',
  'admin.password.title': 'Reset password',
  'admin.password.warn': 'This ends all their open sessions.',
  'admin.password.generated': 'Copy it now — it will not be shown again.',
  'admin.password.copy': 'Copy',
  'admin.password.copied': 'Copied',
  'admin.password.apply': 'Reset',
  'admin.password.done': 'Password reset',
  'admin.password.failed': 'Reset failed',
  'admin.ban.open': 'Ban',
  'admin.ban.title': 'Ban this member',
  'admin.ban.reason': 'Reason (required)',
  'admin.ban.permanent': 'Permanent ban',
  'admin.ban.until': 'Until',
  'admin.ban.apply': 'Ban',
  'admin.ban.lift': 'Lift',
  'admin.ban.active': 'active',
  'admin.ban.expired': 'expired',
  'admin.ban.lifted': 'lifted',
  'admin.ban.none': 'No bans',
  'admin.ban.done': 'Ban recorded',
  'admin.ban.failed': 'Ban failed',
  'admin.media.title': 'Media',
  'admin.media.empty': 'No media',
  'admin.media.protected': 'protected',
  'admin.media.fromPost': 'post',
  'admin.media.fromMessage': 'message',
  'admin.conv.title': 'Conversations',
  'admin.conv.empty': 'No conversations',
  'admin.conv.members': '{count} members',
  'admin.nav.conversations': 'Conversations',
  'admin.convList.search': 'Search a conversation',
  'admin.convList.count': '{count} conversation(s)',
  'admin.convList.empty': 'No conversation matches.',
  'admin.convList.unavailable': 'List unavailable right now.',
  'admin.convList.members': '{count} members',
  'admin.convList.sovereign': 'Reserved to the admin rank.',
  'admin.convDetail.title': 'Reading a conversation',
  'admin.convDetail.reasonLabel': 'Reason for reading',
  'admin.convDetail.reasonHint': 'Ten characters minimum, logged with your name.',
  'admin.convDetail.read': 'Read the conversation',
  'admin.convDetail.empty': 'No message',
  'admin.convDetail.memberPrism': 'Read in the member’s prism: {languages}',
  'admin.agent.title': 'Agent control',
  'admin.agent.denied': 'This control needs a dedicated permission.',
  'admin.agent.users': 'Members driven',
  'admin.agent.tracked': 'Tracked conversations',
  'admin.agent.empty': 'Nothing to show.',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Scan running: {node}',
  'admin.agent.relaunch': 'Run the agent again',
  'admin.agent.effect': 'Re-runs the study and may publish a message.',
  'admin.agent.done': 'Run requested',
  'admin.agent.failed': 'Refused',
  'admin.agent.stop': 'Stop the scan',
  'admin.agent.halted': 'Scan stopped',
  'admin.agent.down': 'Agent service unreachable.',
  'admin.agent.logs': 'Scan log',
  'admin.tab.profile': 'Profile',
  'admin.tab.preferences': 'Preferences',
  'admin.tab.conversations': 'Conversations',
  'admin.tab.media': 'Media',
  'admin.tab.security': 'Security',
  'admin.tab.activity': 'Activity',
  'admin.carousel.title': 'Images',
  'admin.carousel.empty': 'No images',
  'admin.carousel.avatar': 'Profile photo',
  'admin.carousel.banner': 'Banner',
  'admin.carousel.previous': 'Previous image',
  'admin.carousel.next': 'Next image',
  'admin.carousel.position': '{index} of {count}',
  'admin.carousel.open': 'View full image',
  'admin.carousel.close': 'Close image',
  'admin.user.completion': 'Profile {percent}% complete',
  'admin.user.names': 'First and last name',
  'admin.user.phone': 'Phone',
  'admin.user.timezone': 'Time zone',
  'admin.user.languages': 'Languages',
  'admin.user.systemLanguage': 'Main language',
  'admin.user.regionalLanguage': 'Secondary language',
  'admin.user.customLanguage': 'Custom language',
  'admin.user.deviceLocale': 'Device language',
  'admin.user.updated': 'Updated on',
  'admin.user.birthDate': 'Date of birth',
  'admin.user.verifications': 'Verifications',
  'admin.user.emailVerified': 'Email verified',
  'admin.user.phoneVerified': 'Phone verified',
  'admin.user.ageVerified': 'Age verified',
  'admin.user.notVerified': 'not verified',
  'admin.user.securityTitle': 'Account security',
  'admin.user.locked': 'Locked until {date}',
  'admin.user.failedLogins': 'Failed sign-ins',
  'admin.user.lastPasswordChange': 'Password changed on',
  'admin.user.consents': 'Consents',
  'admin.user.consent.voiceProfile': 'Voice profile',
  'admin.user.consent.voiceData': 'Voice data',
  'admin.user.consent.dataProcessing': 'Data processing',
  'admin.user.consent.analytics': 'Analytics',
  'admin.user.consent.voiceCloning': 'Voice cloning',
  'admin.user.terms': 'Terms accepted (v{version})',
  'admin.user.engagement': 'Engagement',
  'admin.user.streak': 'Streak: {current} d (best {longest} d)',
  'admin.user.pending': 'Awaiting confirmation',
  'admin.user.blocked': 'Blocked accounts',
  'admin.user.metadata': 'Metadata',
  'admin.user.none': '—',
  'admin.stats.title': 'Statistics',
  'admin.stats.messages': 'Messages sent',
  'admin.stats.conversations': 'Conversations',
  'admin.stats.translations': 'Translations',
  'admin.stats.posts': 'Posts',
  'admin.stats.stories': 'Stories',
  'admin.stats.reels': 'Reels',
  'admin.stats.comments': 'Comments',
  'admin.stats.reactions': 'Reactions',
  'admin.stats.attachments': 'Attachments',
  'admin.stats.friends': 'Friends',
  'admin.stats.friendRequests': 'Pending friend requests',
  'admin.stats.contacts': 'Contacts',
  'admin.stats.communities': 'Communities',
  'admin.stats.reportsReceived': 'Reports received',
  'admin.stats.reportsMade': 'Reports made',
  'admin.stats.sessions': 'Active sessions',
  'admin.stats.bans': 'Bans',
  'admin.stats.memberDays': 'Days as member',
  'admin.stats.shareLinks': 'Share links',
  'admin.stats.trackingLinks': 'Tracking links',
  'admin.stats.affiliations': 'Referrals',
  'admin.stats.unavailable': 'Statistics unavailable right now.',
  'admin.pref.title': 'Member\'s preferences',
  'admin.pref.reason': 'Reason (optional)',
  'admin.pref.cat.privacy': 'Privacy',
  'admin.pref.cat.audio': 'Audio',
  'admin.pref.cat.message': 'Messages',
  'admin.pref.cat.notification': 'Notifications',
  'admin.pref.cat.video': 'Video',
  'admin.pref.cat.document': 'Documents',
  'admin.pref.cat.application': 'Application',
  'admin.pref.default': 'default',
  'admin.pref.custom': 'custom',
  'admin.pref.readOnly': 'read-only',
  'admin.pref.saved': 'Preference saved',
  'admin.pref.failed': 'Preference not saved',
  'admin.pref.consent': 'The member has not given this consent',
  'admin.pref.unavailable': 'Preferences unavailable right now.',
  'admin.conv.sort': 'Sort by',
  'admin.conv.sort.lastMessageAt': 'Last activity',
  'admin.conv.sort.createdAt': 'Creation',
  'admin.conv.sort.title': 'Title',
  'admin.conv.sort.joinedAt': 'Member joined',
  'admin.conv.order.asc': 'Ascending',
  'admin.conv.order.desc': 'Descending',
  'admin.conv.search': 'Search a conversation',
  'admin.conv.filterType': 'Type',
  'admin.conv.filterRole': 'Member\'s role',
  'admin.conv.all': 'All',
  'admin.conv.messages': '{count} messages',
  'admin.conv.memberRole': 'Role: {role}',
  'admin.conv.role.creator': 'Creator',
  'admin.conv.role.admin': 'Administrator',
  'admin.conv.role.moderator': 'Moderator',
  'admin.conv.role.member': 'Member',
  'admin.conv.closed': 'closed',
  'admin.conv.archived': 'archived',
  'admin.conv.read': 'Read',
  'admin.conv.configure': 'Configure',
  'admin.convSettings.title': 'Configure conversation',
  'admin.convSettings.titleField': 'Title',
  'admin.convSettings.description': 'Description',
  'admin.convSettings.avatar': 'Image (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Who can write',
  'admin.convSettings.writeRole.everyone': 'Everyone',
  'admin.convSettings.writeRole.member': 'Members',
  'admin.convSettings.writeRole.moderator': 'Moderators and above',
  'admin.convSettings.writeRole.admin': 'Administrators and above',
  'admin.convSettings.writeRole.creator': 'Creator only',
  'admin.convSettings.announcement': 'Announcement channel',
  'admin.convSettings.slowMode': 'Slow mode (seconds)',
  'admin.convSettings.autoTranslate': 'Auto-translation',
  'admin.convSettings.archive': 'Archive',
  'admin.convSettings.restore': 'Restore',
  'admin.convSettings.close': 'Close to writing',
  'admin.convSettings.reopen': 'Reopen',
  'admin.convSettings.memberRole': 'This member\'s role',
  'admin.convSettings.remove': 'Remove from conversation',
  'admin.convSettings.reason': 'Reason (10 characters minimum)',
  'admin.convSettings.confirm': 'Confirm',
  'admin.convSettings.save': 'Save',
  'admin.convSettings.saved': 'Conversation updated',
  'admin.convSettings.removed': 'Member removed',
  'admin.convSettings.failed': 'Change refused',
  'admin.convSettings.creatorProtected': 'The creator cannot be demoted or removed',
  'admin.security.sessions': 'Sessions',
  'admin.security.current': 'active',
  'admin.security.revoked': 'revoked',
  'admin.security.revoke': 'Revoke',
  'admin.security.revoked.done': 'Session revoked',
  'admin.security.events': 'Security events',
  'admin.security.severity': 'Severity',
  'admin.security.empty': 'No events',
  'admin.security.bans': 'Ban history',
  'admin.security.unavailable': 'Security unavailable right now.',
  'admin.account.open': 'Security and verifications',
  'admin.account.unlock': 'Unlock account',
  'admin.account.twoFactorOff': 'Disable two-factor',
  'admin.account.twoFactorOn': 'Enable two-factor',
  'admin.account.done': 'Account updated',
  'admin.account.failed': 'Account change refused',
  'admin.activity.reportsMade': 'Reports made',
  'admin.activity.reportedMessages': 'Reported messages',
  'admin.activity.hiddenContent': 'Content hidden',
  'admin.activity.links': 'Links created',
  'admin.activity.friendRequests': 'Friend requests',
  'admin.activity.empty': 'Nothing to show',
  'admin.activity.unavailable': 'Activity unavailable right now.',
  'admin.edit.firstName': 'First name',
  'admin.edit.lastName': 'Last name',
  'admin.edit.username': 'Username',
  'admin.edit.phone': 'Phone',
  'admin.edit.phoneCountryCode': 'Country code',
  'admin.edit.timezone': 'Time zone',
  'admin.edit.banner': 'Banner (URL)',
  'admin.user.id': 'Identifier',
  'admin.user.onboarding': 'Onboarding completed',
  'admin.user.engagementScore': 'Engagement score',
  'admin.user.meeshBalance': 'Meesh balance',
  'admin.user.meeshMinted': 'Meesh earned in total',
  'admin.user.deviceCountry': 'Device country',
  'admin.user.participations': 'Memberships',
  'admin.stats.more': 'All statistics',
  'admin.pref.edit': 'Edit: {category}',
  'admin.carousel.unavailable': 'Images unavailable for now.',
  'admin.conv.type.direct': 'Direct',
  'admin.conv.type.group': 'Group',
  'admin.conv.type.public': 'Public',
  'admin.conv.type.global': 'Global',
  'admin.conv.type.broadcast': 'Broadcast',
  'admin.security.severity.low': 'Low',
  'admin.security.severity.medium': 'Medium',
  'admin.security.severity.high': 'High',
  'admin.security.severity.critical': 'Critical',
  'admin.report.type.spam': 'Spam',
  'admin.report.type.inappropriate': 'Inappropriate content',
  'admin.report.type.harassment': 'Harassment',
  'admin.report.type.violence': 'Violence',
  'admin.report.type.hateSpeech': 'Hate speech',
  'admin.report.type.fakeProfile': 'Fake profile',
  'admin.report.type.impersonation': 'Impersonation',
  'admin.report.type.other': 'Other',
  'admin.report.target.message': 'Message',
  'admin.report.target.user': 'Account',
  'admin.report.target.conversation': 'Conversation',
  'admin.report.target.community': 'Community',
  'admin.status.pending': 'Pending',
  'admin.status.underReview': 'Under review',
  'admin.status.resolved': 'Resolved',
  'admin.status.rejected': 'Rejected',
  'admin.status.dismissed': 'Dismissed',
  'admin.status.accepted': 'Accepted',
  'admin.status.blocked': 'Blocked',
  'admin.status.success': 'Succeeded',
  'admin.status.failed': 'Failed',
  'admin.security.lastActiveOn': 'Last active: {date}',
  'admin.ban.untilDate': 'until {date}',
  'admin.activity.sentTo': 'Sent to {name}',
  'admin.activity.receivedFrom': 'Received from {name}',
  'admin.nav.anonymous': 'Anonymous',
  'admin.shell.menu': 'Administration menu',
  'admin.shell.fold': 'Collapse menu',
  'admin.shell.unfold': 'Expand menu',
  'admin.shell.open': 'Open menu',
  'admin.shell.close': 'Close menu',
  'admin.shell.backToApp': 'Back to the app',
  'admin.list.filters': 'Filters',
  'admin.list.all': 'All',
  'admin.list.yes': 'Yes',
  'admin.list.no': 'No',
  'admin.list.reset': 'Reset',
  'admin.list.pageSize': 'Per page',
  'admin.list.range': '{from}–{to} of {total}',
  'admin.list.sortBy': 'Sort by {column}',
  'admin.col.member': 'Member',
  'admin.col.email': 'Email',
  'admin.col.role': 'Role',
  'admin.col.status': 'Status',
  'admin.col.created': 'Joined',
  'admin.col.lastActive': 'Last active',
  'admin.col.joined': 'Joined',
  'admin.col.language': 'Language',
  'admin.col.conversation': 'Conversation',
  'admin.col.messages': 'Messages',
  'admin.col.name': 'Name',
  'admin.filter.active': 'Active',
  'admin.filter.inactive': 'Deactivated',
  'admin.filter.emailVerified': 'Email verified',
  'admin.filter.twoFactor': 'Two-factor',
  'admin.anonymous.search': 'Search anonymous participants',
  'admin.anonymous.empty': 'No anonymous participant matches.',
  'admin.anonymous.unavailable': 'List unavailable for now.',
  'admin.anonymous.title': 'Anonymous participant',
  'admin.anonymous.left': 'Left',
  'admin.anonymous.permissions': 'Permissions',
  'admin.anonymous.openConversation': 'Read the conversation',
  'admin.col.type': 'Type',
  'admin.col.members': 'Members',
  'admin.col.createdOn': 'Created',
  'admin.col.lastMessage': 'Last message',
  'admin.tab.contacts': 'Contacts',
  'admin.tab.communities': 'Communities',
  'admin.tab.voice': 'Voice profile',
  'admin.tab.reports': 'Reports',
  'admin.tab.label': 'Profile sections',
  'admin.dossier.empty': 'Nothing to show.',
  'admin.dossier.restricted': 'Restricted to administrators cleared for sensitive data.',
  'admin.contacts.sent': 'Sent',
  'admin.contacts.received': 'Received',
  'admin.contacts.direction': 'Request',
  'admin.contacts.links': '{share} share link(s) · {tracking} tracking link(s) · {affiliate} affiliate token(s)',
  'admin.communities.creator': 'Creator',
  'admin.communities.private': 'Private',
  'admin.voice.none': 'No voice profile recorded.',
  'admin.voice.samples': 'Samples',
  'admin.voice.duration': 'Recorded duration',
  'admin.voice.model': 'Model',
  'admin.voice.consents': 'Consents',
  'admin.voice.consentProfile': 'Voice profile',
  'admin.voice.consentData': 'Voice data',
  'admin.voice.consentCloning': 'Voice cloning',
  'admin.voice.notGiven': 'not given',
  'admin.voice.traced': 'This view is recorded in the audit log.',
  'admin.security.device': 'Device',
  'admin.security.place': 'Location',
  'admin.security.ip': 'IP address',
  'admin.security.valid': 'Open',
  'admin.security.closed': 'Closed',
  'admin.security.event': 'Event',
  'admin.col.date': 'Date',
  'admin.reports.filed': 'Reports filed by this member',
  'admin.reports.received': 'Their reported messages',
  'admin.reports.subject': 'Subject',
  'admin.reports.reporter': 'Reported by',
  'admin.reports.reason': 'Reason',
  'admin.reports.message': 'Message',
  'admin.reports.withheld': 'text reserved for moderators',
  'admin.anonymous.link': 'Joined through link',
  'admin.gallery.title': 'Images',
  'admin.gallery.empty': 'No images',
  'admin.gallery.previous': 'Previous image',
  'admin.gallery.next': 'Next image',
  'admin.gallery.avatar': 'Profile photo',
  'admin.gallery.banner': 'Banner',
  'admin.gallery.position': 'Image {n} of {total}',
  'admin.meta.title': 'Metadata',
  'admin.meta.name': 'Full name',
  'admin.meta.systemLanguage': 'Main language',
  'admin.meta.regionalLanguage': 'Secondary language',
  'admin.meta.customLanguage': 'Destination language',
  'admin.meta.timezone': 'Time zone',
  'admin.meta.emailVerified': 'Email verified on',
  'admin.meta.phoneVerified': 'Phone verified on',
  'admin.meta.completion': 'Profile completion',
  'admin.meta.passwordChanged': 'Password changed on',
  'admin.meta.failedLogins': 'Failed sign-ins',
  'admin.meta.lockedUntil': 'Locked until',
  'admin.meta.lockedReason': 'Lock reason',
  'admin.meta.deactivated': 'Deactivated on',
  'admin.meta.updated': 'Updated on',
  'admin.stats.messagesSent': 'Messages sent',
  'admin.stats.reactionsGiven': 'Reactions given',
  'admin.stats.mediaUploaded': 'Media uploaded',
  'admin.stats.pendingIn': 'Requests received',
  'admin.stats.pendingOut': 'Requests sent',
  'admin.stats.reportsFiled': 'Reports filed',
  'admin.stats.activeSessions': 'Active sessions',
  'admin.prefs.privacy': 'Privacy',
  'admin.prefs.notification': 'Notifications',
  'admin.prefs.message': 'Messages',
  'admin.prefs.audio': 'Audio and voice',
  'admin.prefs.video': 'Video',
  'admin.prefs.document': 'Documents',
  'admin.prefs.application': 'App',
  'admin.prefs.notice': 'Each change applies to the member on all their devices and is recorded in the audit log.',
  'admin.prefs.readOnly': 'read-only',
  'admin.prefs.saved': 'Preference saved',
  'admin.prefs.failed': 'The preference could not be saved',
  'admin.prefs.consent': 'Refused: the member hasn’t given the consent this option requires',
  'admin.prefs.reserved': 'Refused: your role can’t modify this member',
  'admin.prefs.invalid': 'Refused: invalid value',
  'admin.list.sort': 'Sort',
  'admin.list.order': 'Order',
  'admin.list.newest': 'Newest first',
  'admin.list.oldest': 'Oldest first',
  'admin.conv.manage': 'Manage',
} satisfies AdminInterfaceCatalog;

export default en;
