/**
 * LA QUALITÉ D'UN APPEL (#8047) — tranche du catalogue, RÉPANDUE par
 * `catalog-pt.ts` comme `catalog-pt-call-screen.ts` : l'indicateur et le
 * détail de qualité, les pastilles de survie de la vidéo et les alertes d'un
 * pair (`call-quality-indicator.tsx`, `call-screen.tsx`).
 */
const ptCallQuality = {
  'call.quality.indicator': 'Qualidade da chamada: {level}',
  'call.quality.level.excellent': 'excelente',
  'call.quality.level.good': 'boa',
  'call.quality.level.fair': 'razoável',
  'call.quality.level.poor': 'fraca',
  'call.quality.detail': 'Qualidade da chamada',
  'call.quality.loss': 'Perda de pacotes',
  'call.quality.latency': 'Latência',
  'call.quality.jitter': 'Jitter',
  'call.quality.audioRate': 'Débito de áudio',
  'call.quality.videoRate': 'Débito de vídeo',
  'call.quality.close': 'Fechar o detalhe da qualidade',
  'call.quality.profile': 'Rede',
  'call.quality.profile.wifi': 'Wi-Fi',
  'call.quality.profile.cellular': 'Dados móveis',
  'call.quality.profile.economy': 'Economia de dados',
  'call.quality.audioCap': 'Limite de áudio',
  'call.quality.videoCap': 'Limite de vídeo',
  'callJournal.title': 'Qualidade e rede',
  'callJournal.chronology': 'Cronologia',
  'callJournal.summary.worstLevel': 'Qualidade mais baixa',
  'callJournal.summary.maxLoss': 'Perda máxima',
  'callJournal.summary.maxRtt': 'Latência máxima',
  'callJournal.summary.reconnections': 'Reconexões',
  'callJournal.summary.path': 'Caminho da mídia',
  'callJournal.path.direct': 'Direto',
  'callJournal.path.relay': 'Por um relé',
  'callJournal.summary.end': 'Fim',
  'callJournal.end.local': 'Desligada',
  'callJournal.end.remote': 'Desligada pelo outro lado',
  'callJournal.end.rejected': 'Recusada',
  'callJournal.end.missed': 'Sem resposta',
  'callJournal.end.connectionLost': 'Conexão perdida',
  'callJournal.end.failed': 'Falha na conexão',
  'callJournal.end.busy': 'Ocupado',
  'callJournal.end.permission': 'Microfone ou câmera negados',
  'callJournal.end.removed': 'Removido da chamada',
  'callJournal.event.connecting': 'Conectando',
  'callJournal.event.connected': 'Conectado',
  'callJournal.event.reconnecting': 'Reconectando',
  'callJournal.event.ended': 'Fim: {reason}',
  'callJournal.event.link': '{name}: {state}',
  'callJournal.link.connecting': 'conectando',
  'callJournal.link.connected': 'conectado',
  'callJournal.link.reconnecting': 'reconectando',
  'callJournal.event.quality': 'Qualidade {level}',
  'callJournal.event.frozen': 'Vídeo desacelerado (rede fraca)',
  'callJournal.event.suspended': 'Vídeo em pausa, o áudio continua',
  'callJournal.event.resumed': 'Vídeo restabelecido',
  'callJournal.event.profile': 'Rede: {profile} · voz {bitrate}',
  'callJournal.event.relay': 'Retransmitido pelo servidor',
  'callJournal.event.direct': 'Conexão direta',
  'call.video.frozen': 'Rede fraca: o seu vídeo está mais lento',
  'call.video.suspended': 'Rede fraca: o seu vídeo está em pausa, o áudio continua',
  'call.alert.weakNetwork': 'A ligação de {name} está instável',
  'call.alert.capturing': '{name} está a capturar o ecrã da chamada',
} as const;

export default ptCallQuality;
