import type { StickerPacksCatalog } from '@/lib/i18n-sticker-packs-catalog';

/** LE CATALOGUE DES PACKS DE STICKERS (#9141), langue `es` — mêmes clés que le français. */
const esStickerPacks = {
  'stickerPacks.by': 'Por {author}',
  'stickerPacks.cancel': 'Cancelar',
  'stickerPacks.send': 'Enviar',
  'stickerPacks.count': '{count} stickers',
  'stickerPacks.tab.shop': 'Tienda',
  'stickerPacks.install': 'Instalar',
  'stickerPacks.uninstall': 'Quitar',
  'stickerPacks.shop.hint': 'Instala los paquetes que quieras tener en tus stickers y quita los demás. Los stickers ya enviados siguen siendo legibles.',
  'stickerPacks.error.install': 'No se pudo cambiar el paquete — inténtalo de nuevo',
  'stickerPacks.error.load': 'No se pudieron cargar los paquetes',
  'stickerPacks.kind.static': 'Fijos',
  'stickerPacks.kind.cinematic': 'Animados',
  'stickerPacks.kind.instant': 'Instantes',
  'stickerPacks.status.pending': 'Pendiente',
  'stickerPacks.status.approved': 'Publicado',
  'stickerPacks.status.rejected': 'Rechazado',
  'stickerPacks.mine.title': 'Mis propuestas',
  'stickerPacks.submit.open': 'Proponer un paquete',
  'stickerPacks.submit.title': 'Proponer un paquete',
  'stickerPacks.submit.back': 'Volver',
  'stickerPacks.submit.hint': 'Añade al menos tres imágenes (PNG, WebP, GIF o JPEG). Una imagen animada se convierte en un sticker animado; marca «Instante» para que un sticker escriba el texto de quien lo envía. Cada paquete se revisa antes de publicarse.',
  'stickerPacks.submit.name': 'Nombre del paquete',
  'stickerPacks.submit.description': 'Descripción',
  'stickerPacks.submit.author': 'Firma',
  'stickerPacks.submit.add': 'Añadir imágenes',
  'stickerPacks.submit.itemTitle': 'Título',
  'stickerPacks.submit.emoji': 'Emoji',
  'stickerPacks.submit.instant': 'Instante',
  'stickerPacks.submit.removeItem': 'Quitar este sticker',
  'stickerPacks.submit.zoneHint': 'Dibuja en la imagen la zona donde se escribirá el texto. La vista previa muestra el texto más largo permitido.',
  'stickerPacks.submit.zoneDefault': 'Texto predeterminado',
  'stickerPacks.submit.zoneLength': 'Longitud máxima',
  'stickerPacks.submit.send': 'Enviar a revisión',
  'stickerPacks.submit.sending': 'Enviando…',
  'stickerPacks.submit.failed': 'No se pudo enviar el paquete — inténtalo de nuevo',
  'stickerPacks.submit.slugTaken': 'Este nombre ya está en uso — elige otro',
  'stickerPacks.submit.tooMany': 'Tres de tus paquetes ya esperan revisión',
  'stickerPacks.submit.assetRefused': 'No se pudo leer una imagen — sustitúyela',
  'stickerPacks.submit.tooLarge': 'El paquete pesa demasiado — quita algunas imágenes',
  'stickerPacks.problem.invalid': 'Un campo no es válido',
  'stickerPacks.problem.reservedSlug': 'Este nombre está reservado — elige otro',
  'stickerPacks.problem.duplicate': 'Dos stickers tienen el mismo nombre',
  'stickerPacks.problem.duplicateSlot': 'Dos zonas tienen el mismo nombre',
  'stickerPacks.problem.zonesRequired': 'Un Instante necesita una zona de texto',
  'stickerPacks.problem.zoneOutside': 'La zona sale de la imagen',
  'stickerPacks.problem.zonesOverlap': 'Dos zonas se superponen',
  'stickerPacks.problem.defaultTooLong': 'El texto predeterminado es más largo de lo que admite la zona',
  'stickerPacks.problem.defaultOverflows': 'El texto predeterminado desborda la zona',
  'stickerPacks.problem.longestOverflows': 'Un texto de longitud máxima desbordaría: amplía la zona o reduce la longitud',
  'stickerPacks.problem.count': 'Un paquete tiene entre 3 y 120 stickers',
  'stickerPacks.problem.packField': 'Dale al paquete un nombre, una descripción y una firma',
} satisfies StickerPacksCatalog;

export default esStickerPacks;
