import type { SendSheetCatalog } from '@/lib/i18n-send-sheet-catalog';

const es = {
  'sendSheet.title.forward': 'Reenviar',
  'sendSheet.title.share': 'Compartir',
  'sendSheet.title.sendTo': 'Enviar a…',
  'sendSheet.cancel': 'Cancelar',
  'sendSheet.caption.label': 'Mensaje',
  'sendSheet.caption.placeholder': 'Añadir un mensaje…',
  'sendSheet.search.label': 'Buscar a una persona o una conversación',
  'sendSheet.search.placeholder': 'Buscar a una persona o una conversación',
  'sendSheet.empty': 'Sin resultados',
  'sendSheet.section.recent': 'Recientes',
  'sendSheet.section.people': 'Personas',
  'sendSheet.section.conversations': 'Conversaciones',
  'sendSheet.section.publish': 'Publicar',
  'sendSheet.publish.story': 'Mi historia',
  'sendSheet.publish.post': 'Publicación',
  'sendSheet.publish.reel': 'Reel',
  'sendSheet.send': 'Enviar',
  'sendSheet.sendCount': 'Enviar ({count})',
  'sendSheet.row.select': 'Seleccionar a {name}',
  'sendSheet.selectedCount': '{count} seleccionados',
  'sendSheet.state.sending': 'Enviando…',
  'sendSheet.state.sent': 'Enviado',
  'sendSheet.state.failed': 'Error',
  'sendSheet.state.retry': 'Reintentar',
  'sendSheet.state.waitingNetwork': 'Esperando la red',
  'sendSheet.failure.download': 'No se pudo obtener el archivo',
  'sendSheet.failure.refused': 'Se rechazó el envío',
  'sendSheet.limit.recipients': 'Máximo {count} destinatarios',
  'sendSheet.error.captionTooLong': 'Este mensaje es demasiado largo para publicarlo (máximo {count} caracteres)',
  'sendSheet.error.tooManyFiles': 'Máximo {count} archivos por publicación',
  'sendSheet.moreOptions': 'Más opciones…',
  'sendSheet.copyLink': 'Copiar enlace',
  'sendSheet.linkCopied': 'Enlace copiado',
  'sendSheet.announce.sent': 'Enviado a {count}',
  'sendSheet.preview.messages': '{count} mensajes',
  'sendSheet.preview.photo': 'Foto',
  'sendSheet.preview.video': 'Vídeo',
  'sendSheet.preview.voice': 'Mensaje de voz',
  'sendSheet.preview.file': 'Archivo',
  'sendSheet.preview.publication': 'Publicación',
  'sendSheet.protected': 'Contenido protegido: no se puede publicar',
  'shareLinkSheet.title': 'Crear un enlace para compartir',
  'shareLinkSheet.empty': 'Ninguna conversación puede recibir un enlace por ahora.',
  'shareLinkSheet.createFailed': 'No se pudo crear el enlace — inténtalo de nuevo en un momento.',
  'shareLinkSheet.copied': 'Enlace copiado — solo falta pegarlo.',
  'shareLinkSheet.unavailable': 'No se puede compartir aquí. Copia la dirección de esta página.',
} satisfies SendSheetCatalog;

export default es;
