/**
 * LE CHROME DU COMPOSER PLEIN ÉCRAN (#8413) ET LE PANNEAU CADRE (#8414) —
 * tranche du catalogue, extraite pour tenir le budget de taille (motif
 * `catalog-fr-mentions.ts`) : chaque langue RÉPAND la sienne dans son
 * catalogue.
 */
const frStudioChrome = {
  'story.studio.more': 'Plus d’options',
  'story.studio.preview': 'Aperçu',
  'story.studio.preview.close': 'Fermer l’aperçu',
  'story.studio.page.remove.current': 'Supprimer cette scène',
  'story.studio.postText': 'Texte du post',
  'story.studio.postText.placeholder': 'Écrivez le texte du post…',
  'story.studio.postText.done': 'Terminé',
  'story.studio.tile.text': 'Texte',
  'story.studio.tile.time': 'Temps',
  'story.studio.rail.scene': 'Outils de la scène',
  'story.studio.timeline.unit': 's',
  'story.studio.tile.frame': 'Cadre',
  'story.studio.undo': 'Annuler',
  'story.studio.redo': 'Rétablir',
  'story.studio.frame': 'Cadre',
  'story.studio.frame.media': 'Le média',
  'story.studio.frame.around': 'Autour du média',
  'story.studio.frame.fit': 'Ajuster',
  'story.studio.frame.fill': 'Remplir',
  'story.studio.frame.fit.hint': 'Entier, posé dans le cadre 9:16. Rien n’est rogné.',
  'story.studio.frame.fill.hint': 'Couvre tout le cadre 9:16, quitte à rogner les bords.',
  'story.studio.backdrop.blur': 'Flou',
  'story.studio.backdrop.black': 'Noir',
  'story.studio.backdrop.white': 'Blanc',
  'story.studio.backdrop.indigo': 'Indigo',
  'story.studio.backdrop.sand': 'Sable',
  'story.studio.animated': 'Animé',
  'story.studio.timeline': 'Frise de la scène',
  'story.studio.timeline.play': 'Lire',
  'story.studio.timeline.pause': 'Pause',
  'story.studio.timeline.empty': 'Écrivez un texte ou posez un calque : chaque objet y prend sa piste.',
  'story.studio.timeline.overlay': 'Calque',
  'story.studio.retouch.title': 'Retoucher l’image',
  'story.studio.retouch.done': 'Terminé',
  'story.studio.retouch.cancel': 'Abandonner la retouche',
  'composer.attachment.edit': 'Éditer {name}',
  'story.studio.retouch.failed': 'Le média n’a pas pu être rendu.',
  'story.studio.retouch.exporting': 'Export en cours…',
  'story.studio.timeline.enter': 'Entre ici',
  'story.studio.timeline.exit': 'Sort ici',
  'story.studio.timeline.scrub': 'Déplacer la tête de lecture',
  'story.studio.timeline.track': 'Piste de {name}',
  'story.studio.timeline.earlier': 'Plus tôt',
  'story.studio.timeline.later': 'Plus tard',
  'story.studio.editor.filter': 'Filtre',
  'story.studio.filter.vintage': 'Vintage',
  'story.studio.filter.bw': 'N&B',
  'story.studio.filter.warm': 'Chaud',
  'story.studio.filter.cool': 'Froid',
  'story.studio.filter.dramatic': 'Dramatique',
  'story.studio.filter.vivid': 'Vif',
  'story.studio.filter.fade': 'Délavé',
  'story.studio.filter.chrome': 'Chrome',
  'story.studio.object.menu': 'Actions de {name}',
  'story.studio.object.raise': 'Monter',
  'story.studio.object.lower': 'Reculer',
  'story.studio.object.duplicate': 'Dupliquer',
  'story.studio.object.edit': 'Modifier',
  'story.studio.object.remove': 'Retirer',
  'story.studio.edit.done': 'OK',
  'story.studio.pose.left': 'Vers la gauche',
  'story.studio.pose.right': 'Vers la droite',
  'story.studio.pose.up': 'Vers le haut',
  'story.studio.pose.down': 'Vers le bas',
  'story.studio.objects.edit': 'Modifier {name}',
  'story.studio.media.alt': 'Texte alternatif',
  'story.studio.media.alt.placeholder': 'Décrivez ce média pour les lecteurs d’écran',
  'composer.reelOffer.title': 'Publier en réel ?',
  'composer.reelOffer.body': 'Votre post n’a qu’une vidéo : en réel, elle s’ouvre en plein écran dans les Réels.',
  'composer.reelOffer.reel': 'C’est un Réel',
  'composer.reelOffer.post': 'C’est un Post',
  // L'outil ouvert et la capture rapide (#8654).
  'story.studio.tool.close': 'Fermer l’outil',
  'story.studio.camera.quick.holdFilm': 'Maintenir : filmer',
  'story.studio.camera.quick.videoOnly': 'Maintenir pour filmer',
  'story.studio.camera.quick.photo': 'Prendre une photo',
  'story.studio.camera.quick.video': 'Filmer',
  'story.studio.camera.title': 'Caméra',
  'story.studio.camera.close': 'Revenir à la scène',
  'story.studio.camera.flip': 'Changer d’objectif',
  'story.studio.camera.flash': 'Flash',
  'story.studio.camera.shutter.photo': 'Prendre une photo',
  'story.studio.camera.shutter.start': 'Démarrer l’enregistrement',
  'story.studio.camera.shutter.stop': 'Arrêter l’enregistrement',
  'story.studio.camera.hint.photo': 'Toucher l’écran : photo · le maintenir : vidéo',
  'story.studio.camera.hint.video': 'Toucher pour filmer · toucher encore pour poser',
  'story.studio.camera.unavailable': 'La caméra n’est pas disponible. Autorisez-la dans les réglages.',
  'story.studio.camera.openSettings': 'Réglages',
  'story.studio.camera.recording': 'Enregistrement en cours',
  'story.studio.scene.empty.title': 'Ceci est votre scène',
  'story.studio.scene.empty.invite': 'Ajoutez-y un texte, un dessin, une image ou une vidéo — et faites-la vôtre.',
  'story.studio.camera.locked': 'Enregistrement verrouillé',
  'story.studio.camera.hint.holding': 'Glisser vers le cadenas pour verrouiller · vers le haut pour zoomer',
  'story.studio.camera.hint.locked': 'Mains libres — glisser vers le haut ou le bas pour zoomer',
  'story.studio.camera.flash.intensity': 'Intensité du flash',
  'story.studio.camera.flash.intensityValue': '{percent} %',
  'story.studio.camera.quick.tapArm': 'Toucher : ouvrir l’objectif',
  'story.studio.camera.quick.tapAgain': 'Toucher encore : photo',
  'story.studio.effect.column': 'Effets de la scène',
  'story.studio.effect.opening': 'Effet d’ouverture',
  'story.studio.effect.visual': 'Effet visuel',
  'story.studio.effect.close': 'Fermer les effets',
  'story.studio.effect.row.opening': 'Ouverture',
  'story.studio.effect.row.closing': 'Fermeture',
  'story.studio.transition.fade': 'Fondu',
  'story.studio.transition.zoom': 'Zoom',
  'story.studio.transition.slide': 'Glissement',
  'story.studio.transition.reveal': 'Révélation',
  'story.studio.object.options': 'Options de {name}',
  'story.studio.object.deselect': 'Quitter la sélection',
  'story.studio.object.setBackground': 'Mettre en fond',
  'story.studio.object.replaceBackground': 'Remplacer le fond',
  'story.studio.background.menu.title': 'Fond de la scène',
  'story.studio.background.menu.edit': 'Modifier le fond',
  'story.studio.background.menu.retake': 'Reprendre une photo',
  'story.studio.background.menu.forward': 'Passer au premier plan',
  'story.studio.background.menu.remove': 'Retirer le fond',
  'story.studio.background.tools': 'Outils du fond',
  'story.studio.background.tools.describe': 'Décrire',
  'story.studio.background.tools.leave': 'Retour à la scène',
  'story.studio.reelSwitch.announcement': 'Publication passée en réel',
} as const;

export type StudioChromeCatalogSlice = Readonly<Record<keyof typeof frStudioChrome, string>>;

export default frStudioChrome;
