import type { GameCatalog } from '@/lib/i18n-game-catalog';

/** Le catalogue du jeu, ar (#9379) — mêmes clés et mêmes paramètres que le français ; textes de l'app iOS quand elle les porte. */
const ar = {
  'game.points.one': '{count} نقطة',
  'game.points.other': '{count} نقطة',
  'game.points.convertible.one': '{count} نقطة قابلة للتحويل',
  'game.points.convertible.other': '{count} نقطة قابلة للتحويل',
  'game.days.one': '{count} يوم',
  'game.days.other': '{count} يومًا',
  'game.actions.one': '{count} إجراء',
  'game.actions.other': '{count} إجراءً',
  'game.levels.one': '{count} مستوى',
  'game.levels.other': '{count} مستوى',
  'game.meeshes.none': 'لا Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meesh',
  'game.mint.badges.one': 'ينخفض {count} وسام',
  'game.mint.badges.other': 'ينخفض {count} وسامًا',
  'game.mint.badges.none': 'لن ينطفئ أي وسام',
  'game.tier.etincelle': 'شرارة',
  'game.tier.lueur': 'وميض',
  'game.tier.lumiere': 'نور',
  'game.tier.eclat': 'بريق',
  'game.tier.rayon': 'شعاع',
  'game.tier.aurore': 'فجر',
  'game.tier.comete': 'مذنّب',
  'game.tier.etoile': 'نجمة',
  'game.tier.constellation': 'كوكبة',
  'game.tier.galaxie': 'مجرّة',
  'game.rank.murmure': 'همس',
  'game.rank.echo': 'صدى',
  'game.rank.voix': 'صوت',
  'game.rank.conteur': 'حكّاء',
  'game.rank.passeur': 'جسّار',
  'game.rank.polyglotte': 'متعدّد اللغات',
  'game.rank.ambassadeur': 'سفير',
  'game.rank.orateur': 'خطيب',
  'game.rank.oracle': 'عرّاف',
  'game.rank.legende': 'أسطورة',
  'game.rank.mythe': 'خرافة',
  'game.treasury.bourse': 'كيس',
  'game.treasury.escarcelle': 'جراب',
  'game.treasury.coffret': 'صندوق صغير',
  'game.treasury.coffre': 'صندوق',
  'game.treasury.tresor': 'كنز',
  'game.treasury.reserve': 'احتياطي',
  'game.flame.form.braise': 'جمرة',
  'game.flame.form.flamme': 'لهب',
  'game.flame.form.brasier': 'نار مشتعلة',
  'game.flame.form.astre': 'نجم',
  'game.flame.form.soleil': 'شمس',
  'game.edition.silver': 'فضّية',
  'game.edition.gold': 'ذهبية',
  'game.edition.prism': 'منشورية',
  'game.difficulty.easy': 'سهلة',
  'game.difficulty.medium': 'متوسطة',
  'game.difficulty.hard': 'صعبة',
  'game.difficulty.gold': 'ذهبية',
  'game.mission.react_messages.one': 'تفاعل مع {count} رسالة',
  'game.mission.react_messages.other': 'تفاعل مع {count} رسائل',
  'game.mission.send_voice.one': 'أرسل رسالة صوتية',
  'game.mission.send_voice.other': 'أرسل {count} رسائل صوتية',
  'game.mission.send_texts.one': 'أرسل {count} رسالة',
  'game.mission.send_texts.other': 'أرسل {count} رسائل',
  'game.mission.use_stickers.one': 'أرسل ملصقًا',
  'game.mission.use_stickers.other': 'أرسل {count} ملصقات',
  'game.mission.send_attachments.one': 'أرسل مرفقًا',
  'game.mission.send_attachments.other': 'أرسل {count} مرفقات',
  'game.mission.comment_text.one': 'اكتب تعليقًا',
  'game.mission.comment_text.other': 'اكتب {count} تعليقات',
  'game.mission.publish_story.one': 'انشر ستوري',
  'game.mission.publish_story.other': 'انشر {count} ستوري',
  'game.mission.publish_post.one': 'انشر منشورًا',
  'game.mission.publish_post.other': 'انشر {count} منشورات',
  'game.mission.share_link.one': 'شارك رابطًا',
  'game.mission.share_link.other': 'شارك {count} روابط',
  'game.mission.prism_foreign_messages.one': 'اكتب رسالة بلغة غير لغتك',
  'game.mission.prism_foreign_messages.other': 'اكتب {count} رسائل بلغة غير لغتك',
  'game.mission.voice_comments.one': 'اترك تعليقًا صوتيًا',
  'game.mission.voice_comments.other': 'اترك {count} تعليقات صوتية',
  'game.mission.publish_reel.one': 'انشر ريلز',
  'game.mission.publish_reel.other': 'انشر {count} ريلز',
  'game.mission.reply_conversations': 'ردّ في {count} محادثات مختلفة',
  'game.mission.prism_foreign_exchange': 'اكتب {count} رسائل بلغة غير لغتك',
  'game.mission.long_chat': 'أرسل {count} رسائل',
  'game.mission.gold_replies_received': 'احصل على ردود من {count} أشخاص مختلفين',
  'game.mission.generic': 'مهمة اليوم',
  'game.error.insufficient_points': 'ليس لديك نقاط قابلة للتحويل تكفي لسك Meesh.',
  'game.error.insufficient_meeshes': 'تحتاج إلى Meesh إضافية لذلك.',
  'game.error.freeze_at_maximum': 'لديك بالفعل تجميدان في الاحتياط: هذا هو الحد الأقصى.',
  'game.error.relight_not_allowed': 'لا يمكن إعادة إشعال اللهب الآن.',
  'game.error.mission_not_found': 'هذه المهمة لم تعد موجودة: تتحدّث الشاشة.',
  'game.error.mission_reroll_exhausted': 'لقد غيّرت مهمة اليوم بالفعل.',
  'game.error.mission_reroll_unavailable': 'لا يمكن تغيير هذه المهمة.',
  'game.error.missions_locked': 'تُفتح المهام عند المستوى 5.',
  'game.error.chest_not_ready': 'أكمل مهام اليوم أولًا لفتح الصندوق.',
  'game.error.generic': 'لم تكتمل العملية — تحقّق من اتصالك وأعد المحاولة.',
  'game.chest.chance': 'فرصة واحدة من {odds}',
  'game.chest.reward.fragment': 'جزء من Meesh',
  'game.chest.reward.freeze': 'تجميد للّهب',
  'game.flame_panel.title': 'احمِ اللهب',
  'game.flame_panel.bonus': '\u2066+{perDay} %\u2069 لكل يوم متتالٍ على مكافآت المهام، حتى\u00a0\u2066+{max} %\u2069.',
  'game.flame_panel.freezes': 'التجميدات في الاحتياط: \u2066{held} / {max}\u2069',
  'game.flame_panel.offline': 'بلا اتصال: ستُستأنف التجميدات وإعادة الإشعال عند عودة الاتصال.',
  'game.flame_panel.freeze_full': 'الاحتياط ممتلئ: تجميد واحد يغطّي يومًا فائتًا، ولا تحتاج إلى المزيد.',
  'game.flame_panel.freeze_buy': 'اشترِ تجميدًا · {price}',
  'game.flame_panel.freeze_missing': 'تحتاج إلى {missing} لتجميد.',
  'game.flame_panel.relight_intro': 'انطفأ لهبك: أعد إشعاله الآن، فيستأنف من حيث توقّف.',
  'game.flame_panel.relight': 'أعد إشعال اللهب · {price}',
  'game.flame_panel.relight_missing': 'تحتاج إلى {missing} لإعادة إشعاله.',
  'game.flame_panel.relight_missing_window': 'تحتاج إلى {missing} لإعادة إشعاله إذا انطفأ قبل أقل من 48 ساعة.',
  'game.flame_panel.relight_closed': 'لا يمكن إعادة إشعال هذا اللهب بعد الآن. يبدأ لهب جديد مع إجرائك التالي.',
  'game.gauge.level': 'المستوى',
  'game.level.title': 'المستوى {level} · {tier}',
  'game.level.top': 'أنت في القمة.',
  'game.level.to_next': 'بقي {points} للوصول إلى المستوى {level}',
  'game.level.record': 'الرقم القياسي: المستوى {level}',
  'game.level.tailwind': ' · رياح مواتية ×{factor}',
  'game.gauge.rank': 'الرتبة',
  'game.rank.glory': 'المجد {glory}',
  'game.rank.top': 'أعلى رتبة',
  'game.rank.next': 'بقي {missing} من المجد قبل {rank}',
  'game.gauge.treasury': 'الكنز',
  'game.treasury.hint': 'احتفظ بـ Meesh: فهي تملأ كنزك',
  'game.treasury.next': 'بقي {missing} للوصول إلى {tier}',
  'game.gauge.flame': 'اللهب',
  'game.flame.no_streak': 'لا سلسلة',
  'game.flame.form_line': '{form} ·\u00a0\u2066+{bonus} %\u2069 على المهام',
  'game.flame.out_line': 'اللهب منطفئ',
  'game.flame.status.none': 'إجراء واحد اليوم يُشعل لهبك',
  'game.flame.status.at_risk': 'قم بإجراء قبل منتصف الليل',
  'game.flame.status.covered': 'تجميد يحميه',
  'game.flame.status.out': 'منطفئ',
  'game.guide.speaker.mee': 'مي',
  'game.guide.speaker.meo': 'ميو',
  'game.guide.speaker.duo': 'مي وميو',
  'game.guide.step_of': 'الخطوة {index} من {total}',
  'game.guide.more': 'عرض الشرح الكامل',
  'game.guide.dismiss': 'لاحقًا',
  'game.guide.skip': 'تخطَّ',
  'game.guide.photo': 'خلّد هذه اللحظة',
  'game.guide.skip_all': 'تخطَّ المقدمة',
  'game.guide.action.start_game': 'ابدأ اللعبة',
  'game.guide.action.earn_first_points': 'قم بأول إجراء لي',
  'game.guide.action.see_level': 'عرض مستواي',
  'game.guide.action.see_missions': 'عرض المهام',
  'game.guide.action.see_flame': 'عرض لهبي',
  'game.guide.action.see_meeshes': 'عرض Meesh',
  'game.guide.action.see_rank': 'عرض رتبتي',
  'game.guide.action.take_start_photo': 'التقط صورة البداية',
  'game.guide.action.see_progress': 'عرض تقدّمي',
  'game.guide.action.see_next_tier': 'عرض المرحلة التالية',
  'game.guide.action.open_first_mission': 'افتح مهمتي الأولى',
  'game.guide.action.mint_or_climb': 'عرض معاينة السك',
  'game.guide.action.regain_levels': 'استعد مستوياتي',
  'game.guide.action.relight_badge': 'عرض أوسمتي',
  'game.guide.action.see_mint_preview': 'عرض معاينة السك',
  'game.guide.action.take_photo': 'خلّد هذه اللحظة',
  'game.guide.action.keep_or_spend': 'عرض كنزي',
  'game.guide.action.do_easy_mission_or_freeze': 'عرض مهامي',
  'game.guide.action.relight_flame': 'أعد إشعال اللهب',
  'game.guide.action.do_easiest_mission': 'عرض أسهل مهمة',
  'game.guide.action.prestige_or_stay': 'عرض مستواي',
  'game.guide.moment.first_level.what': 'لقد ربحت مستواك الأول.',
  'game.guide.moment.first_level.means': 'تملأ نقاطك الحلقة: وعندما تمتلئ ترتقي مستوى.',
  'game.guide.moment.first_level.next': 'بقي {points} للوصول إلى المستوى {level}.',
  'game.guide.moment.first_level.short': 'المستوى {level}: بقي {points} للمستوى التالي.',
  'game.guide.moment.new_tier.what': 'لقد دخلت مرحلة {tier}!',
  'game.guide.moment.new_tier.means': 'تُميّز المراحل طريقك: عشرة مستويات لكل منها.',
  'game.guide.moment.new_tier.next': 'تُفتح المرحلة التالية عند المستوى {level}.',
  'game.guide.moment.new_tier.next_last': 'أنت في المرحلة الأخيرة.',
  'game.guide.moment.new_tier.short': 'تم بلوغ مرحلة {tier}.',
  'game.guide.moment.missions_unlocked.what': 'تم فتح المهام.',
  'game.guide.moment.missions_unlocked.means': 'ثلاث مهام يوميًا، وصندوق تفتحه عند إنجازها.',
  'game.guide.moment.missions_unlocked.next': 'افتح مهمتك الأولى.',
  'game.guide.moment.missions_unlocked.short': 'مهام اليوم في انتظارك.',
  'game.guide.moment.first_mint_possible.what': 'يمكنك الآن سك أول Meesh لك.',
  'game.guide.moment.first_mint_possible.means_free': 'يكلّف السك {price} دون أن تفقد أي مستوى، ويمنحك\u00a0\u2066+{glory}\u2069 من المجد.',
  'game.guide.moment.first_mint_possible.means': 'يكلّف السك {price}، أي {levels}، ويمنحك\u00a0\u2066+{glory}\u2069 من المجد.',
  'game.guide.moment.first_mint_possible.next': 'اسكّها الآن، أو اصعد أولًا.',
  'game.guide.moment.first_mint_possible.short': 'تُسَكّ Meesh مقابل {price}.',
  'game.guide.moment.first_mint.what': 'طَق! تم سك أول Meesh لك.',
  'game.guide.moment.first_mint.means': 'انتقل مستواك من {from} إلى {to}: هذه هي القاعدة. الرياح المواتية فعّالة.',
  'game.guide.moment.first_mint.next': 'استعد مستوياتك أسرع: تُحتسب نقاطك بزيادة \u206625 %\u2069 حتى المستوى {level}.',
  'game.guide.moment.first_mint.short': 'المستوى \u2066{from} → {to}\u2069. تساعدك الرياح المواتية حتى المستوى {level}.',
  'game.guide.moment.badge_extinguished.what': 'انطفأ وسام.',
  'game.guide.moment.badge_extinguished.means': 'تحوّل إلى أثر: لا شيء يضيع إلى الأبد.',
  'game.guide.moment.badge_extinguished.next': 'بقي {actions} لإعادة إشعاله.',
  'game.guide.moment.badge_extinguished.short': 'انطفأ وسام: {actions} لإعادة إشعاله.',
  'game.guide.moment.price_rises.what': 'تصبح Meesh أندر.',
  'game.guide.moment.price_rises.means': 'كلما سككت أكثر، ارتفعت كلفة التالية.',
  'game.guide.moment.price_rises.next': 'التالية تكلّف {price}.',
  'game.guide.moment.price_rises.short': 'تكلّف Meesh التالية {price}.',
  'game.guide.moment.new_rank.what': 'رتبة جديدة: {rank}.',
  'game.guide.moment.new_rank.means': 'تجاوز مجدك عتبة جديدة، ولا يتراجع أبدًا.',
  'game.guide.moment.new_rank.next': 'بقي {glory} من المجد للشريحة التالية. خلّد هذه اللحظة.',
  'game.guide.moment.new_rank.next_top': 'هذه أعلى رتبة. خلّد هذه اللحظة.',
  'game.guide.moment.new_rank.short': 'أنت {rank}.',
  'game.guide.moment.treasury_tier.what': 'يبلغ كنزك مرحلة {tier}.',
  'game.guide.moment.treasury_tier.means': 'كنزك ظاهر على ملفك الشخصي.',
  'game.guide.moment.treasury_tier.next': 'احتفظ بـ {meeshes} إضافية للمرحلة التالية، أو أنفق.',
  'game.guide.moment.treasury_tier.next_top': 'احتفظ به، أو أنفق Meesh.',
  'game.guide.moment.treasury_tier.short': 'الكنز: مرحلة {tier}.',
  'game.guide.moment.flame_at_risk.what': 'لهبك في خطر.',
  'game.guide.moment.flame_at_risk.means': 'ينطفئ عند منتصف الليل إن لم تفعل شيئًا: {days} من السلسلة لإنقاذها.',
  'game.guide.moment.flame_at_risk.next': 'أنجز مهمة سهلة، أو اشترِ تجميدًا.',
  'game.guide.moment.flame_at_risk.short': 'ينطفئ لهبك عند منتصف الليل: يكفي إجراء واحد.',
  'game.guide.moment.flame_out.what': 'انطفأ لهبك.',
  'game.guide.moment.flame_out.means': 'يعود مكافأة اللهب إلى الصفر.',
  'game.guide.moment.flame_out.next': 'أعد إشعاله خلال 48 ساعة مقابل {price}.',
  'game.guide.moment.flame_out.next_new': 'إجراؤك التالي يُشعل لهبًا جديدًا.',
  'game.guide.moment.flame_out.short': 'اللهب منطفئ: أعد إشعاله مقابل {price}.',
  'game.guide.moment.flame_out.short_new': 'اللهب منطفئ: إجراء جديد يُشعله.',
  'game.guide.moment.return_after_absence.what': 'سعيد برؤيتك مجددًا!',
  'game.guide.moment.return_after_absence.means': 'غبت {days}: بقيت رتبتك وكنزك ومجدك حيث تركتها.',
  'game.guide.moment.return_after_absence.next': 'ابدأ بأسهل مهمة اليوم.',
  'game.guide.moment.return_after_absence.short': 'مرحبًا بعودتك: ابدأ بأسهل مهمة.',
  'game.guide.moment.level_100.what': 'المستوى 100: أنت في القمة!',
  'game.guide.moment.level_100.means': 'يعيد التميّز مستواك إلى 1 ويمنحك نجمة وكأسًا.',
  'game.guide.moment.level_100.next': 'انتقل إلى التميّز، أو ابقَ في القمة.',
  'game.guide.moment.level_100.next_stay': 'ابقَ في القمة ما شئت.',
  'game.guide.moment.level_100.short': 'أنت في القمة.',
  'game.guide.step.welcome.what': 'مرحبًا، أنا مي! مع ميو سنشرح لك اللعبة في سبع بطاقات.',
  'game.guide.step.welcome.means': 'كل إجراء مفيد يمنحك نقاطًا: الكتابة، والكلام، والنشر، والتفاعل، والدعوة.',
  'game.guide.step.welcome.next': 'قم بأول إجراء، وأنا أحسب نقاطك.',
  'game.guide.step.first_points.what': 'أحسنت، هذه أولى نقاطك!',
  'game.guide.step.first_points.means': 'النقاط تصنع مستواك: إنها تملأ حلقتك.',
  'game.guide.step.first_points.next': 'شاهد حلقتك وهي تمتلئ.',
  'game.guide.step.levels.what': 'مئة مستوى، وعشر مراحل.',
  'game.guide.step.levels.means': 'يتطلّب كل مستوى نقاطًا أكثر قليلًا من الذي قبله.',
  'game.guide.step.levels.next': 'تُفتح المهام عند المستوى 5.',
  'game.guide.step.missions.what': 'كل يوم ثلاث مهام وصندوق.',
  'game.guide.step.missions.means': 'أنجزها لتفتح الصندوق وتغذّي لهبك.',
  'game.guide.step.missions.next': 'يكبر اللهب ما دمت تعود.',
  'game.guide.step.flame.what': 'يكبر لهبك كل يوم تتحرّك فيه.',
  'game.guide.step.flame.means': 'كل يوم متتالٍ يضيف \u20662 %\u2069 إلى مكافآت مهامك، حتى \u206650 %\u2069. التجميد يغطّي يومًا فائتًا.',
  'game.guide.step.flame.next': 'يمكن أن تتحوّل نقاطك إلى Meesh.',
  'game.guide.step.mint.what': 'ابتداءً من 1٬221 نقطة، تُسَكّ Meesh.',
  'game.guide.step.mint.means': 'تغادر النقاط المنفقة مستواك، لكن رتبتك لا تنخفض أبدًا: كل سكّ يضيف مجدًا.',
  'game.guide.step.mint.next': 'المجد يمنح الرتبة.',
  'game.guide.step.rank.what': 'رتبتك لا تنخفض أبدًا.',
  'game.guide.step.rank.means': 'السكّ وتحطيم الأرقام القياسية وكسب الإنجازات: كلها تضيف مجدًا.',
  'game.guide.step.rank.next': 'لنخلّد بدايتك بصورة.',
  'game.rules.1.title': 'كل إجراء له مكافأة',
  'game.rules.1.body': 'الكتابة والكلام والنشر والتفاعل والدعوة: كل إجراء مفيد يمنحك نقاطًا.',
  'game.rules.2.title': 'النقاط تصنع المستوى',
  'game.rules.2.body': '100 مستوى في 10 مراحل. يتطلّب كل مستوى أكثر قليلًا من الذي قبله.',
  'game.rules.3.title': 'نسكّ Meesh',
  'game.rules.3.body': 'ابتداءً من 1٬221 نقطة، تسكّ Meesh يدويًا. يرتفع السعر مع عدد الـ Meesh المسكوكة.',
  'game.rules.4.title': 'السكّ يُنزِلك',
  'game.rules.4.body': 'تغادر النقاط المنفقة المستوى. وقد تنطفئ الأوسمة التي كانت تدعمها.',
  'game.rules.5.title': 'رتبتك لا تنخفض أبدًا',
  'game.rules.5.body': 'كل سكّ وكل رقم قياسي وكل إنجاز يضيف مجدًا. والمجد يمنح الرتبة.',
  'game.rules.6.title': 'الكنز يُحفَظ أو يُنفَق',
  'game.rules.6.body': 'الاحتفاظ بـ Meesh يُنمّي الكنز. وإنفاقها يحمي اللهب أو يمنحك عناصر تجميلية.',
  'game.rules.7.title': 'كل يوم يُحتسب',
  'game.rules.7.body': 'ثلاث مهام، وصندوق، ولهب يكبر ما دمت تعود.',
  'game.rules.8.title': 'نحتفظ بأثر',
  'game.rules.8.body': 'كل لحظة كبيرة تُصوَّر مع مي وميو في دفتر التقدّم.',
  'game.rules.page_title': 'كيف تعمل اللعبة',
  'game.rules.intro': 'ثماني قواعد، واللعبة كلها بداخلها. ميو يشرحها، ومي تُريك الإجراء.',
  'game.rules.section_rules': 'القواعد في صفحة واحدة',
  'game.rules.section_steps': 'الخطوات السبع',
  'game.page.back': 'العودة إلى التقدّم',
  'game.door.rules': 'كيف تعمل اللعبة',
  'game.door.notebook': 'دفتر التقدّم',
  'game.mint.minted_line': 'تم سك Meesh رقم {number}، {edition}.',
  'game.mint.action': 'اسكّها مع مي وميو',
  'game.mint.minting': 'جارٍ السك…',
  'game.mint.offline': 'بلا اتصال: سيُستأنف السك عند عودة الاتصال.',
  'game.mint.missing': 'بقي {missing} قبل Meesh التالية: تكلّف {price}.',
  'game.mint.next_title': 'Meesh التالية · رقم {number}',
  'game.mint.next_subtitle': 'إصدار {edition} · {price}',
  'game.mint.row.price': 'السعر',
  'game.mint.row.level': 'المستوى',
  'game.mint.row.treasury': 'الكنز',
  'game.mint.row.glory': 'المجد',
  'game.mint.row.badges': 'الأوسمة',
  'game.mint.row.tailwind': 'رياح مواتية',
  'game.mint.tailwind_value': '\u2066+25 %\u2069 على نقاطك حتى المستوى {level}',
  'game.missions.title': 'مهام اليوم',
  'game.missions.locked': 'تُفتح المهام عند المستوى 5: ثلاث يوميًا وصندوق. أنت في المستوى {level}.',
  'game.missions.prism_day': 'يوم المنشور: إحدى المهام تُنجَز بلغة غير لغتك.',
  'game.missions.prism_hour': 'ساعة المنشور: {start} – {end} — تُحتسب مهامك مضاعفة.',
  'game.missions.offline': 'بلا اتصال: سيُستأنف تغيير المهمة وفتح الصندوق عند عودة الاتصال.',
  'game.mission.prism': 'المنشور',
  'game.mission.done': 'مُنجزة',
  'game.mission.reroll': 'غيّر · 1 Meesh',
  'game.mission.reroll.a11y': 'غيّر المهمة «{title}» مقابل 1 Meesh',
  'game.chest.title': 'صندوق اليوم',
  'game.chest.locked': 'أكمل مهام اليوم لفتحه.',
  'game.chest.opening': 'جارٍ الفتح…',
  'game.chest.open': 'افتح الصندوق',
  'game.chest.claimed': 'عُد غدًا للصندوق التالي.',
  'game.chest.odds': '{min} إلى {max} · {fragment} لجزء · {freeze} لتجميد',
  'game.notebook.page_title': 'دفتر التقدّم',
  'game.notebook.empty': 'دفترك فارغ. تُصوَّر اللحظات الكبيرة — رتبة، أو أول Meesh، أو لهب لسبعة أيام — مع مي وميو، وتبقى الصورة على جهازك.',
  'game.notebook.pending': 'قيد الانتظار',
  'game.notebook.kept': 'الصور المحفوظة',
  'game.notebook.photo_a11y': 'صورة: {title}',
  'game.notebook.remove': 'احذف',
  'game.photo.offer.start': 'صوّر',
  'game.photo.offer.title': 'هل نخلّدها؟',
  'game.photo.share': 'شارك',
  'game.photo.a11y': 'صورة: {title}',
  'game.photo.close': 'إغلاق',
  'game.photo.selfie': 'سيلفي معنا',
  'game.photo.card_only': 'البطاقة فقط',
  'game.photo.later': 'لاحقًا',
  'game.photo.gallery': 'اختر صورة من المعرض',
  'game.photo.shutter': 'التقط الصورة',
  'game.photo.camera.denied': 'تم رفض الكاميرا. اسمح بها من إعدادات جهازك، أو اختر صورة من المعرض.',
  'game.photo.camera.unsupported': 'لا يسمح هذا الجهاز بالكاميرا هنا. اختر صورة من المعرض، أو احتفظ بالبطاقة فقط.',
  'game.photo.camera.unavailable': 'الكاميرا غير متاحة (هل يستخدمها تطبيق آخر؟). اختر صورة من المعرض، أو احتفظ بالبطاقة فقط.',
  'game.photo.striking': 'مي وميو يسكّان اللحظة في الصورة',
  'game.photo.preview': 'معاينة: {title}',
  'game.photo.format.story': '9:16 · ستوري',
  'game.photo.format.square': '1:1 · الملف الشخصي',
  'game.photo.save': 'احفظ',
  'game.photo.kept': 'محفوظة',
  'game.photo.keep': 'احتفظ',
  'game.photo.kicker.start': 'الخطوات الأولى',
  'game.photo.title.start': 'بدايتي على Meeshy',
  'game.photo.kicker.rank': 'رتبة جديدة',
  'game.photo.kicker.tier': 'المستوى {level}',
  'game.photo.title.tier': 'مرحلة {tier}',
  'game.photo.kicker.summit': 'في القمة',
  'game.photo.kicker.new_lap': 'جولة جديدة',
  'game.photo.title.level_100': 'المستوى 100',
  'game.photo.title.prestige': 'التميّز {count}',
  'game.photo.title.meesh_first': 'أول Meesh لي',
  'game.photo.title.meesh_number': 'Meesh رقم {number}',
  'game.photo.title.meesh_number_edition': 'Meesh رقم {number} · {edition}',
  'game.photo.kicker.meesh': 'Meesh مسكوكة',
  'game.photo.kicker.treasury': 'الكنز',
  'game.photo.kicker.flame': 'اللهب',
  'game.photo.kicker.achievement': 'تم فتح إنجاز',
  'game.photo.title.flame_days': '{count} يومًا من اللهب',
  'game.photo.notice.kept': 'تم الاحتفاظ بها في دفتر التقدّم.',
  'game.photo.notice.keep_failed': 'الدفتر غير متاح على هذا الجهاز: لم يتم حفظ الصورة.',
  'game.photo.notice.save_failed': 'لم يتم الحفظ.',
  'game.photo.notice.shared': 'تمت مشاركة الصورة.',
  'game.mission.glory': '\u2066+{glory}\u2069 مجد',
  'game.guide.collapse': 'طيّ',
  'game.guide.collapse_a11y': 'طيّ الشرح',
  'game.guide.awaiting.missions': 'أنجز أسهل مهام اليوم: سأنتظرك لنكمل.',
  'game.guide.awaiting.flame': 'عُد غدًا وقم بأي إجراء: ستصل سلسلتك إلى يومين.',
  'game.photo.private': 'تبقى الصورة على جهازك ما لم تشاركها.',
  'game.photo.camera.opening': 'جارٍ فتح الكاميرا…',
  'game.photo.gallery.unreadable': 'تعذّرت قراءة هذه الصورة.',
  'game.photo.format.group': 'تنسيق الصورة',
  'game.photo.notice.saved_file': 'تم حفظ الصورة.',
  'game.photo.notice.share_failed': 'تعذّرت المشاركة.',
  'game.photo.compose_unsupported': 'لا يستطيع هذا المتصفح تركيب الصورة. تبقى لحظتك في تقدّمك.',
  'game.notebook.pending_until': 'في الانتظار حتى {date}',
  'game.notebook.remove_confirm': 'تأكيد الإزالة',
  'game.mint.number_label': 'رقم {number}',
  'game.chest.contents': 'محتوى الصندوق',
  'game.fmt.signed': '\u2066+{value}\u2069',
  'game.fmt.minus': '\u2066−{value}\u2069',
  'game.fmt.fraction': '\u2066{done} / {total}\u2069',
  'game.fmt.from_to': '\u2066{from} → {to}\u2069',
  'game.points.two': 'نقطتان',
  'game.points.few': '{count} نقاط',
  'game.points.convertible.two': 'نقطتان قابلتان للتحويل',
  'game.points.convertible.few': '{count} نقاط قابلة للتحويل',
  'game.days.two': 'يومان',
  'game.days.few': '{count} أيام',
  'game.actions.two': 'إجراءان',
  'game.actions.few': '{count} إجراءات',
  'game.levels.two': 'مستويان',
  'game.levels.few': '{count} مستويات',
  'game.mint.badges.two': 'ينخفض وسامان',
  'game.mint.badges.few': 'تنخفض {count} أوسمة',
  'game.error.request_id_conflict': 'سبق استخدام معرّف هذا الطلب في إجراء آخر: أعد المحاولة وسيُرسَل معرّف جديد.',
  'game.level.ring_label': 'المستوى {level}، مرحلة {tier}، {ordinal}',
  'game.tier.ordinal.1': 'المرحلة الأولى',
  'game.tier.ordinal.2': 'المرحلة الثانية',
  'game.tier.ordinal.3': 'المرحلة الثالثة',
  'game.tier.ordinal.4': 'المرحلة الرابعة',
  'game.tier.ordinal.5': 'المرحلة الخامسة',
  'game.tier.ordinal.6': 'المرحلة السادسة',
  'game.tier.ordinal.7': 'المرحلة السابعة',
  'game.tier.ordinal.8': 'المرحلة الثامنة',
  'game.tier.ordinal.9': 'المرحلة التاسعة',
  'game.tier.ordinal.10': 'المرحلة العاشرة',
  'game.material.copper': 'نحاس',
  'game.material.bronze': 'برونز',
  'game.material.silver': 'فضة',
  'game.material.gold': 'ذهب',
  'game.material.platinum': 'بلاتين',
  'game.material.obsidian': 'سبج',
  'game.material.prism': 'منشور',
  'game.medal.label': '{axis}، {material}، {value} من {next} نحو {nextMaterial}',
  'game.medal.label_top': '{axis}، {material}، {value}',
  'game.medal.label_off': '{axis}، لم تُنَل بعد، يتبقّى {missing}',
  'game.family.content': 'المحتوى',
  'game.family.comment': 'التعليقات',
  'game.family.conversation': 'المحادثات',
  'game.family.tool': 'الأدوات',
  'game.family.social': 'الروابط',
  'game.hero.earn_title': 'كيف تكسب النقاط',
  'game.hero.earn_chip': '{family} ⁦+{points}⁩',
  'game.hero.earn_chip_a11y': '{family}: {points} لكل إجراء. عرض القواعد.',
  'game.hero.mint_title': 'كيف تسكّ',
  'game.hero.mint_price': 'Meesh واحدة مقابل {price}',
  'game.hero.mint_cost': 'تكلّف {levels}',
  'game.hero.mint_glory': '⁦+{glory}⁩ مجد',
  'game.hero.mint_missing': 'بقي {missing}',
  'game.hero.mee_idle': 'عندك سؤال؟ المسني وسأشرح لك.',
  'game.photo.referral.headline': 'انضم إليّ على Meeshy',
  'game.photo.referral.share_text': 'انضم إليّ على Meeshy: ⁦{link}⁩',
  'game.photo.referral.flame_days': '⁦{days}⁩ ي',
} as const satisfies GameCatalog;

export default ar;
