import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const it = {
  'admin.role': 'Il tuo ruolo: {role}',
  'admin.denied.title': 'Area riservata',
  'admin.denied.message': 'Quest\'area richiede un permesso di amministrazione.',
  'admin.counters.title': 'In sintesi',
  'admin.counters.unavailable': 'Contatori non disponibili al momento.',
  'admin.counters.users': 'Account',
  'admin.counters.activeUsers': 'Account attivi',
  'admin.counters.messages': 'Messaggi',
  'admin.counters.communities': 'Comunità',
  'admin.counters.reports': 'Segnalazioni',
  'admin.counters.newUsers': 'Nuovi (24 h)',
  'admin.sections.title': 'Sezioni',
  'admin.nav.dashboard': 'Cruscotto',
  'admin.nav.users': 'Account',
  'admin.nav.moderation': 'Moderazione',
  'admin.nav.audit': 'Registri di audit',
  'admin.nav.analytics': 'Statistiche',
  'admin.nav.trackingLinks': 'Link di tracciamento',
  'admin.nav.ranking': 'Classifica',
  'admin.nav.broadcasts': 'Trasmissioni',
  'admin.nav.settings': 'Impostazioni',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Monitoraggio',
  'admin.users.search': 'Cerca un account',
  'admin.users.count': '{count} account',
  'admin.users.empty': 'Nessun account corrisponde.',
  'admin.users.unavailable': 'Elenco non disponibile al momento.',
  'admin.users.inactive': 'disattivato',
  'admin.users.previous': 'Precedenti',
  'admin.users.next': 'Successivi',
  'admin.user.title': 'Membro',
  'admin.user.unavailable': 'Scheda non disponibile al momento.',
  'admin.user.identity': 'Identità',
  'admin.user.account': 'Account',
  'admin.user.created': 'Iscritto il',
  'admin.user.lastActive': 'Ultima attività',
  'admin.user.twoFactor': 'Due fattori',
  'admin.user.enabled': 'attivato',
  'admin.user.deleted': 'eliminato',
  'admin.user.role': 'Ruolo',
  'admin.edit.open': 'Modifica',
  'admin.edit.title': 'Modifica membro',
  'admin.edit.displayName': 'Nome visualizzato',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Bio',
  'admin.edit.active': 'Account attivo',
  'admin.edit.save': 'Salva',
  'admin.edit.reason': 'Motivo (facoltativo)',
  'admin.edit.warnRole': 'Cambiare il ruolo modifica i permessi.',
  'admin.edit.warnDeactivate': 'Disattivare chiude le sessioni aperte.',
  'admin.edit.confirm': 'Conferma',
  'admin.edit.saved': 'Modifiche salvate',
  'admin.edit.failed': 'Salvataggio non riuscito',
  'admin.password.title': 'Reimposta la password',
  'admin.password.warn': 'Questo chiude tutte le sessioni aperte.',
  'admin.password.generated': 'Copiala ora: non verrà più mostrata.',
  'admin.password.copy': 'Copia',
  'admin.password.copied': 'Copiata',
  'admin.password.apply': 'Reimposta',
  'admin.password.done': 'Password reimpostata',
  'admin.password.failed': 'Reimpostazione non riuscita',
  'admin.ban.open': 'Blocca',
  'admin.ban.title': 'Blocca questo membro',
  'admin.ban.reason': 'Motivo (obbligatorio)',
  'admin.ban.permanent': 'Blocco permanente',
  'admin.ban.until': 'Fino al',
  'admin.ban.apply': 'Blocca',
  'admin.ban.lift': 'Revoca',
  'admin.ban.active': 'in vigore',
  'admin.ban.expired': 'scaduto',
  'admin.ban.lifted': 'revocato',
  'admin.ban.none': 'Nessun blocco',
  'admin.ban.done': 'Blocco registrato',
  'admin.ban.failed': 'Blocco non riuscito',
  'admin.media.title': 'Media',
  'admin.media.empty': 'Nessun media',
  'admin.media.protected': 'protetto',
  'admin.media.fromPost': 'post',
  'admin.media.fromMessage': 'messaggio',
  'admin.conv.title': 'Conversazioni',
  'admin.conv.empty': 'Nessuna conversazione',
  'admin.conv.members': '{count} membri',
  'admin.nav.conversations': 'Conversazioni',
  'admin.convList.search': 'Cerca una conversazione',
  'admin.convList.count': '{count} conversazione/i',
  'admin.convList.empty': 'Nessuna conversazione corrisponde.',
  'admin.convList.unavailable': 'Elenco non disponibile al momento.',
  'admin.convList.members': '{count} membri',
  'admin.convList.sovereign': 'Riservato al rango di amministrazione.',
  'admin.convDetail.title': 'Lettura di una conversazione',
  'admin.convDetail.reasonLabel': 'Motivo della lettura',
  'admin.convDetail.reasonHint': 'Almeno dieci caratteri, registrato con il suo nome.',
  'admin.convDetail.read': 'Leggere la conversazione',
  'admin.convDetail.empty': 'Nessun messaggio',
  'admin.convDetail.memberPrism': 'Letto nel prisma del membro: {languages}',
  'admin.agent.title': 'Governo dell’agente',
  'admin.agent.denied': 'Questo governo richiede un diritto dedicato.',
  'admin.agent.users': 'Membri guidati',
  'admin.agent.tracked': 'Conversazioni seguite',
  'admin.agent.empty': 'Nulla da mostrare.',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Scansione in corso: {node}',
  'admin.agent.relaunch': 'Rilanciare l’agente',
  'admin.agent.effect': 'Rifà lo studio e può pubblicare un messaggio.',
  'admin.agent.done': 'Rilancio richiesto',
  'admin.agent.failed': 'Rifiutata',
  'admin.agent.stop': 'Fermare la scansione',
  'admin.agent.halted': 'Scansione fermata',
  'admin.agent.down': 'Servizio agente irraggiungibile.',
  'admin.agent.logs': 'Registro delle scansioni',
  'admin.tab.profile': 'Profilo',
  'admin.tab.preferences': 'Preferenze',
  'admin.tab.conversations': 'Conversazioni',
  'admin.tab.media': 'Media',
  'admin.tab.security': 'Sicurezza',
  'admin.carousel.title': 'Immagini',
  'admin.carousel.empty': 'Nessuna immagine',
  'admin.carousel.avatar': 'Foto profilo',
  'admin.carousel.banner': 'Banner',
  'admin.carousel.previous': 'Immagine precedente',
  'admin.carousel.next': 'Immagine successiva',
  'admin.carousel.position': '{index} di {count}',
  'admin.carousel.open': 'Vedi l\'immagine intera',
  'admin.carousel.close': 'Chiudi l\'immagine',
  'admin.user.completion': 'Profilo completato al {percent}%',
  'admin.user.names': 'Nome e cognome',
  'admin.user.phone': 'Telefono',
  'admin.user.timezone': 'Fuso orario',
  'admin.user.languages': 'Lingue',
  'admin.user.systemLanguage': 'Lingua principale',
  'admin.user.regionalLanguage': 'Lingua secondaria',
  'admin.user.customLanguage': 'Lingua personalizzata',
  'admin.user.deviceLocale': 'Lingua del dispositivo',
  'admin.user.updated': 'Modificato il',
  'admin.user.birthDate': 'Data di nascita',
  'admin.user.verifications': 'Verifiche',
  'admin.user.emailVerified': 'E-mail verificata',
  'admin.user.phoneVerified': 'Telefono verificato',
  'admin.user.ageVerified': 'Età verificata',
  'admin.user.notVerified': 'non verificato',
  'admin.user.securityTitle': 'Sicurezza dell\'account',
  'admin.user.locked': 'Bloccato fino al {date}',
  'admin.user.failedLogins': 'Accessi non riusciti',
  'admin.user.lastPasswordChange': 'Password cambiata il',
  'admin.user.consents': 'Consensi',
  'admin.user.consent.voiceProfile': 'Profilo vocale',
  'admin.user.consent.voiceData': 'Dati vocali',
  'admin.user.consent.dataProcessing': 'Trattamento dei dati',
  'admin.user.consent.analytics': 'Statistiche di utilizzo',
  'admin.user.consent.voiceCloning': 'Clonazione vocale',
  'admin.user.terms': 'Termini accettati (v{version})',
  'admin.user.engagement': 'Coinvolgimento',
  'admin.user.streak': 'Serie: {current} g (record {longest} g)',
  'admin.user.pending': 'In attesa di conferma',
  'admin.user.blocked': 'Account bloccati',
  'admin.user.metadata': 'Metadati',
  'admin.stats.title': 'Statistiche',
  'admin.stats.messages': 'Messaggi inviati',
  'admin.stats.conversations': 'Conversazioni',
  'admin.stats.translations': 'Traduzioni',
  'admin.stats.posts': 'Post',
  'admin.stats.stories': 'Storie',
  'admin.stats.reels': 'Reel',
  'admin.stats.comments': 'Commenti',
  'admin.stats.reactions': 'Reazioni',
  'admin.stats.attachments': 'Allegati',
  'admin.stats.friends': 'Amici',
  'admin.stats.friendRequests': 'Richieste di amicizia in attesa',
  'admin.stats.contacts': 'Contatti',
  'admin.stats.communities': 'Community',
  'admin.stats.reportsReceived': 'Segnalazioni ricevute',
  'admin.stats.reportsMade': 'Segnalazioni effettuate',
  'admin.stats.sessions': 'Sessioni attive',
  'admin.stats.bans': 'Ban',
  'admin.stats.memberDays': 'Giorni da membro',
  'admin.stats.shareLinks': 'Link di condivisione',
  'admin.stats.trackingLinks': 'Link di tracciamento',
  'admin.stats.affiliations': 'Inviti',
  'admin.stats.unavailable': 'Statistiche non disponibili al momento.',
  'admin.pref.reason': 'Motivo (facoltativo)',
  'admin.pref.cat.privacy': 'Privacy',
  'admin.pref.cat.audio': 'Audio',
  'admin.pref.cat.message': 'Messaggi',
  'admin.pref.cat.notification': 'Notifiche',
  'admin.pref.cat.video': 'Video',
  'admin.pref.cat.document': 'Documenti',
  'admin.pref.cat.application': 'Applicazione',
  'admin.pref.default': 'predefinito',
  'admin.pref.custom': 'personalizzato',
  'admin.pref.readOnly': 'sola lettura',
  'admin.pref.saved': 'Preferenza salvata',
  'admin.pref.failed': 'Preferenza non salvata',
  'admin.pref.consent': 'Il membro non ha dato questo consenso',
  'admin.pref.unavailable': 'Preferenze non disponibili al momento.',
  'admin.conv.sort': 'Ordina per',
  'admin.conv.sort.lastMessageAt': 'Ultima attività',
  'admin.conv.sort.createdAt': 'Creazione',
  'admin.conv.sort.title': 'Titolo',
  'admin.conv.sort.joinedAt': 'Ingresso del membro',
  'admin.conv.order.asc': 'Crescente',
  'admin.conv.order.desc': 'Decrescente',
  'admin.conv.search': 'Cerca una conversazione',
  'admin.conv.filterType': 'Tipo',
  'admin.conv.filterRole': 'Ruolo del membro',
  'admin.conv.all': 'Tutti',
  'admin.conv.messages': '{count} messaggi',
  'admin.conv.memberRole': 'Ruolo: {role}',
  'admin.conv.role.creator': 'Creatore',
  'admin.conv.role.admin': 'Amministratore',
  'admin.conv.role.moderator': 'Moderatore',
  'admin.conv.role.member': 'Membro',
  'admin.conv.closed': 'chiusa',
  'admin.conv.archived': 'archiviata',
  'admin.conv.read': 'Leggi',
  'admin.conv.configure': 'Configura',
  'admin.convSettings.title': 'Configura la conversazione',
  'admin.convSettings.titleField': 'Titolo',
  'admin.convSettings.description': 'Descrizione',
  'admin.convSettings.avatar': 'Immagine (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Chi può scrivere',
  'admin.convSettings.writeRole.everyone': 'Tutti',
  'admin.convSettings.writeRole.member': 'I membri',
  'admin.convSettings.writeRole.moderator': 'Moderatori e superiori',
  'admin.convSettings.writeRole.admin': 'Amministratori e superiori',
  'admin.convSettings.writeRole.creator': 'Solo il creatore',
  'admin.convSettings.announcement': 'Canale annunci',
  'admin.convSettings.slowMode': 'Modalità lenta (secondi)',
  'admin.convSettings.autoTranslate': 'Traduzione automatica',
  'admin.convSettings.archive': 'Archivia',
  'admin.convSettings.restore': 'Ripristina',
  'admin.convSettings.close': 'Chiudi alla scrittura',
  'admin.convSettings.reopen': 'Riapri',
  'admin.convSettings.memberRole': 'Ruolo di questo membro',
  'admin.convSettings.remove': 'Rimuovi dalla conversazione',
  'admin.convSettings.reason': 'Motivo (minimo 10 caratteri)',
  'admin.convSettings.confirm': 'Conferma',
  'admin.convSettings.save': 'Salva',
  'admin.convSettings.saved': 'Conversazione aggiornata',
  'admin.convSettings.removed': 'Membro rimosso',
  'admin.convSettings.failed': 'Modifica rifiutata',
  'admin.convSettings.creatorProtected': 'Il creatore non può essere declassato né rimosso',
  'admin.security.sessions': 'Sessioni',
  'admin.security.current': 'attiva',
  'admin.security.revoked': 'revocata',
  'admin.security.revoke': 'Revoca',
  'admin.security.revoked.done': 'Sessione revocata',
  'admin.security.events': 'Eventi di sicurezza',
  'admin.security.severity': 'Gravità',
  'admin.security.empty': 'Nessun evento',
  'admin.security.bans': 'Cronologia dei ban',
  'admin.security.unavailable': 'Sicurezza non disponibile al momento.',
  'admin.account.open': 'Sicurezza e verifiche',
  'admin.account.unlock': 'Sblocca l\'account',
  'admin.account.twoFactorOff': 'Disattiva l\'autenticazione a due fattori',
  'admin.account.done': 'Account aggiornato',
  'admin.account.failed': 'Modifica dell\'account rifiutata',
  'admin.activity.reportsMade': 'Segnalazioni effettuate',
  'admin.activity.reportedMessages': 'Messaggi segnalati',
  'admin.activity.hiddenContent': 'Contenuto nascosto',
  'admin.activity.links': 'Link creati',
  'admin.activity.friendRequests': 'Richieste di amicizia',
  'admin.activity.empty': 'Niente da mostrare',
  'admin.activity.unavailable': 'Attività non disponibile al momento.',
  'admin.edit.firstName': 'Nome',
  'admin.edit.lastName': 'Cognome',
  'admin.edit.username': 'Nome utente',
  'admin.edit.phone': 'Telefono',
  'admin.edit.phoneCountryCode': 'Prefisso internazionale',
  'admin.edit.timezone': 'Fuso orario',
  'admin.edit.banner': 'Banner (URL)',
  'admin.user.id': 'Identificativo',
  'admin.user.onboarding': 'Benvenuto completato',
  'admin.user.engagementScore': 'Punteggio di coinvolgimento',
  'admin.user.meeshBalance': 'Saldo Meesh',
  'admin.user.meeshMinted': 'Meesh guadagnati in totale',
  'admin.user.deviceCountry': 'Paese del dispositivo',
  'admin.user.participations': 'Partecipazioni',
  'admin.stats.more': 'Tutte le statistiche',
  'admin.stats.reportsOnMessages': 'Segnalazioni sui suoi messaggi',
  'admin.stats.withheld': 'Non comunicato',
  'admin.pref.edit': 'Modifica: {category}',
  'admin.carousel.unavailable': 'Immagini non disponibili per ora.',
  'admin.conv.type.direct': 'Diretta',
  'admin.conv.type.group': 'Gruppo',
  'admin.conv.type.public': 'Pubblica',
  'admin.conv.type.global': 'Globale',
  'admin.conv.type.broadcast': 'Trasmissione',
  'admin.security.severity.low': 'Bassa',
  'admin.security.severity.medium': 'Media',
  'admin.security.severity.high': 'Alta',
  'admin.security.severity.critical': 'Critica',
  'admin.report.type.spam': 'Spam',
  'admin.report.type.inappropriate': 'Contenuto inappropriato',
  'admin.report.type.harassment': 'Molestie',
  'admin.report.type.violence': 'Violenza',
  'admin.report.type.hateSpeech': 'Incitamento all\'odio',
  'admin.report.type.fakeProfile': 'Profilo falso',
  'admin.report.type.impersonation': 'Furto d\'identità',
  'admin.report.type.other': 'Altro',
  'admin.report.target.message': 'Messaggio',
  'admin.report.target.user': 'Account',
  'admin.report.target.conversation': 'Conversazione',
  'admin.report.target.community': 'Comunità',
  'admin.status.pending': 'In attesa',
  'admin.status.underReview': 'In revisione',
  'admin.status.resolved': 'Risolto',
  'admin.status.rejected': 'Rifiutato',
  'admin.status.dismissed': 'Archiviato',
  'admin.status.accepted': 'Accettata',
  'admin.status.blocked': 'Bloccato',
  'admin.status.success': 'Riuscito',
  'admin.status.failed': 'Fallito',
  'admin.security.lastActiveOn': 'Ultima attività: {date}',
  'admin.ban.untilDate': 'fino al {date}',
  'admin.activity.sentTo': 'Inviata a {name}',
  'admin.activity.receivedFrom': 'Ricevuta da {name}',
  'admin.nav.anonymous': 'Anonimi',
  'admin.shell.menu': 'Menu di amministrazione',
  'admin.shell.fold': 'Comprimi il menu',
  'admin.shell.unfold': 'Espandi il menu',
  'admin.shell.open': 'Apri il menu',
  'admin.shell.close': 'Chiudi il menu',
  'admin.shell.backToApp': 'Torna all\'app',
  'admin.list.all': 'Tutti',
  'admin.list.yes': 'Sì',
  'admin.list.no': 'No',
  'admin.list.reset': 'Reimposta',
  'admin.list.pageSize': 'Per pagina',
  'admin.list.range': '{from}–{to} di {total}',
  'admin.list.sortBy': 'Ordina per {column}',
  'admin.col.member': 'Membro',
  'admin.col.email': 'E-mail',
  'admin.col.role': 'Ruolo',
  'admin.col.status': 'Stato',
  'admin.col.created': 'Iscrizione',
  'admin.col.lastActive': 'Ultima attività',
  'admin.col.joined': 'Ingresso',
  'admin.col.language': 'Lingua',
  'admin.col.conversation': 'Conversazione',
  'admin.col.messages': 'Messaggi',
  'admin.col.name': 'Nome',
  'admin.filter.active': 'Attivi',
  'admin.filter.inactive': 'Disattivati',
  'admin.filter.emailVerified': 'E-mail verificata',
  'admin.filter.twoFactor': 'Due fattori',
  'admin.anonymous.search': 'Cerca un anonimo',
  'admin.anonymous.empty': 'Nessun anonimo corrisponde.',
  'admin.anonymous.unavailable': 'Elenco non disponibile al momento.',
  'admin.anonymous.title': 'Partecipante anonimo',
  'admin.anonymous.left': 'Uscito',
  'admin.anonymous.permissions': 'Permessi',
  'admin.anonymous.openConversation': 'Leggi la conversazione',
  'admin.col.type': 'Tipo',
  'admin.col.members': 'Membri',
  'admin.col.createdOn': 'Creazione',
  'admin.col.lastMessage': 'Ultimo messaggio',
  'admin.tab.contacts': 'Contatti',
  'admin.tab.communities': 'Community',
  'admin.tab.voice': 'Profilo vocale',
  'admin.tab.reports': 'Segnalazioni',
  'admin.tab.label': 'Sezioni della scheda',
  'admin.dossier.empty': 'Niente da mostrare.',
  'admin.dossier.restricted': 'Riservato agli amministratori abilitati ai dati sensibili.',
  'admin.communities.creator': 'Creatore',
  'admin.communities.private': 'Privata',
  'admin.voice.none': 'Nessun profilo vocale registrato.',
  'admin.voice.samples': 'Campioni',
  'admin.voice.duration': 'Durata registrata',
  'admin.voice.model': 'Modello',
  'admin.voice.consents': 'Consensi',
  'admin.voice.consentProfile': 'Profilo vocale',
  'admin.voice.consentData': 'Dati vocali',
  'admin.voice.consentCloning': 'Clonazione vocale',
  'admin.voice.notGiven': 'non dato',
  'admin.voice.traced': 'Questa consultazione è registrata nel registro di audit.',
  'admin.anonymous.link': 'Entrato dal link',
  'admin.user.deactivated': 'Disattivato il',
  'admin.stats.pendingOut': 'Richieste inviate',
  'admin.conv.manage': 'Gestisci',
} satisfies AdminInterfaceCatalog;

export default it;
