import type { ContactCardCatalogSlice } from './catalog-fr-contact-card';

/** La carte de visite partagée (#8101) — voir `catalog-fr-contact-card.ts`. */
const ptContactCard = {
  'contactCard.a11y.card': 'Cartão de contato: {name}',
  'contactCard.open': 'Ver todos os detalhes de {name}',
  'contactCard.loading': 'Lendo o cartão de contato…',
  'contactCard.unreadable': 'Cartão de contato ilegível',
  'contactCard.failed': 'Não foi possível ler o cartão de contato',
  'contactCard.retry': 'Tentar novamente',
  'contactCard.download': 'Baixar o cartão',
  'contactCard.onMeeshy': 'No Meeshy',
  'contactCard.connect': 'Conectar',
  'contactCard.write': 'Escrever',
  'contactCard.state.self': 'É você',
  'contactCard.state.requestSent': 'Pedido enviado',
  'contactCard.state.requestReceived': 'Enviou-lhe um pedido',
  'contactCard.sheet.title': 'Cartão de contato',
  'contactCard.close': 'Fechar',
  'contactCard.copy': 'Copiar: {field}',
  'contactCard.copied': 'Copiado para a área de transferência',
  'contactCard.copyFailed': 'Não foi possível copiar',
  'contactCard.copyHint': 'Toque longo ou clique direito num campo para copiá-lo',
  'contactCard.avatar': 'Foto de {name}',
  'contactCard.banner': 'Capa de {name}',
  'contactCard.field.phone': 'Telefone',
  'contactCard.field.email': 'E-mail',
  'contactCard.field.url': 'Site',
  'contactCard.field.address': 'Endereço',
  'contactCard.field.birthday': 'Aniversário',
  'contactCard.field.note': 'Nota',
  'contactCard.field.organization': 'Organização',
  'contactCard.field.title': 'Cargo',
  'contactCard.label.mobile': 'celular',
  'contactCard.label.home': 'casa',
  'contactCard.label.work': 'trabalho',
  'contactCard.label.main': 'principal',
  'contactCard.label.iphone': 'iPhone',
  'contactCard.label.fax': 'fax',
  'contactCard.label.pager': 'pager',
  'contactCard.label.other': 'outro',
} satisfies ContactCardCatalogSlice;

export default ptContactCard;
