import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page et les fiches (`game.concept.*`, `game.fiche.*`, `game.fact.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const de = {
  'game.progression.title': 'Fortschritt',
  'game.concept.why_label': 'Wozu es dient',
  'game.concept.how_label': 'Wie es funktioniert',
  'game.fiche.what': 'Was ist das?',
  'game.fiche.where': 'Wo ich stehe',
  'game.fiche.earn': 'So bekommst du mehr',
  'game.fiche.more': 'Mehr entdecken',
  'game.fiche.unknown': 'Diese Seite gibt es nicht, oder dein Server liefert sie noch nicht.',
  'game.concept.level.name': 'Level',
  'game.concept.level.why': 'Dein Level zeigt, wie weit du auf Meeshy gekommen bist.',
  'game.concept.level.how': 'Deine Punkte füllen den Ring: Ist er voll, steigst du ein Level auf.',
  'game.concept.level.tip.1': 'Mach die Missionen des Tages: Sie bringen viele Punkte.',
  'game.concept.level.tip.2': 'Halte deine Flamme am Brennen: Sie erhöht deine Belohnungen.',
  'game.concept.points.name': 'Punkte',
  'game.concept.points.why': 'Punkte heben dein Level und dienen zum Prägen von Meeshes.',
  'game.concept.points.how': 'Jede nützliche Aktion bringt welche: schreiben, posten, reagieren.',
  'game.concept.points.tip.1': 'Poste, kommentiere, reagiere: Jede Aktionsfamilie hat ihren Wert.',
  'game.concept.points.tip.2': 'Löse einen Schwung aus, um deine Punkte zu vervielfachen.',
  'game.concept.meesh.name': 'Meeshes',
  'game.concept.meesh.why': 'Die Meesh ist die seltene Münze von Meeshy: behalten oder ausgeben.',
  'game.concept.meesh.how': 'Du prägst sie mit Punkten. Jede Prägung macht die nächste teurer.',
  'game.concept.meesh.tip.1': 'Behalte deine Meeshes, damit dein Schatz wächst.',
  'game.concept.meesh.tip.2': 'Gib sie aus, um deine Flamme zu schützen oder eine Mission zu tauschen.',
  'game.concept.glory.name': 'Ruhm',
  'game.concept.glory.why': 'Der Ruhm bestimmt deinen Rang, und dein Rang sinkt nie.',
  'game.concept.glory.how': 'Jede Prägung, jeder Rekord und jeder Erfolg bringt Ruhm.',
  'game.concept.glory.tip.1': 'Präge eine Meesh: Jede Prägung bringt Ruhm.',
  'game.concept.glory.tip.2': 'Brich deine Rekorde und schalte Erfolge frei.',
  'game.concept.flame.name': 'Flamme',
  'game.concept.flame.why': 'Deine Flamme zählt deine Tage in Folge und erhöht Missionsbelohnungen.',
  'game.concept.flame.how': 'Eine Aktion pro Tag lässt sie wachsen. Ein Eis deckt einen Tag ab.',
  'game.concept.flame.tip.1': 'Mach jeden Tag mindestens eine Aktion.',
  'game.concept.flame.tip.2': 'Halte ein Eis in Reserve für freie Tage.',
  'game.concept.missions.name': 'Missionen des Tages',
  'game.concept.missions.why': 'Missionen geben dir jeden Tag ein Ziel und Extrapunkte.',
  'game.concept.missions.how': 'Drei Missionen pro Tag. Sind sie erledigt, öffnest du die Truhe.',
  'game.concept.missions.tip.1': 'Fang mit der leichtesten Mission an.',
  'game.concept.missions.tip.2': 'Eine Mission gefällt dir nicht? Tausche sie, einmal pro Tag.',
  'game.concept.league.name': 'Liga',
  'game.concept.league.why': 'Die Liga misst dich jede Woche mit 29 anderen Spielern.',
  'game.concept.league.how': 'Deine Wochenpunkte bestimmen deinen Platz. Die Ersten steigen auf.',
  'game.concept.league.tip.1': 'Spiel jeden Tag ein wenig: Die Wochenpunkte summieren sich.',
  'game.concept.league.tip.2': 'Ziele vor Sonntagabend auf die ersten Plätze.',
  'game.concept.league.more': 'Rangliste ansehen',
  'game.concept.league.unplaced': 'Noch keine Gruppe',
  'game.concept.season.name': 'Saison',
  'game.concept.season.why': 'Die Saison ist ein Weg über acht Wochen, mit einem Pokal am Ende.',
  'game.concept.season.how': 'Missionen und das Duo bringen Sterne. Sterne öffnen die Etappen.',
  'game.concept.season.tip.1': 'Erledige deine Tagesmissionen, um Sterne zu sammeln.',
  'game.concept.season.tip.2': 'Spiel im Duo mit einem Freund: Die Belohnung wird verdoppelt.',
  'game.concept.season.more': 'Weg ansehen',
  'game.concept.season.none': 'Gerade keine',
  'game.concept.prestige.name': 'Prestige',
  'game.concept.prestige.why': 'Das Prestige belohnt alle, die Level 100 erreichen.',
  'game.concept.prestige.how': 'Dein Level beginnt wieder bei 1. Du bekommst Stern, Trophäe und Ruhm.',
  'game.concept.prestige.tip.1': 'Steig bis Level 100 auf.',
  'game.concept.prestige.tip.2': 'Wechsle ins Prestige, wann du willst: Nichts zwingt dich.',
  'game.concept.prestige.more': 'Prestige öffnen',
  'game.concept.elans.name': 'Schwung',
  'game.concept.elans.why': 'Ein Schwung vervielfacht die Punkte deiner nächsten Aktionen.',
  'game.concept.elans.how': 'Mach in diesen Tagen Aktionen aus mehreren Familien, um ihn auszulösen.',
  'game.concept.elans.tip.1': 'Wechsle ab: schreiben, posten, kommentieren, reagieren.',
  'game.concept.elans.tip.2': 'Komm mehrere Tage in Folge wieder, um ihn zu halten.',
  'game.concept.elans.families.one': '{count} aktive Familie',
  'game.concept.elans.families.other': '{count} aktive Familien',
  'game.concept.badges.name': 'Abzeichen',
  'game.concept.badges.why': 'Ein Abzeichen zeigt, was du auf Meeshy am meisten machst.',
  'game.concept.badges.how': 'Wiederhole eine Aktion: Ihr Abzeichen wechselt das Material.',
  'game.concept.badges.tip.1': 'Such dir eine Aktion aus, die du magst, und mach sie oft.',
  'game.concept.badges.tip.2': 'Ein erloschenes Abzeichen lässt sich neu entzünden: Nichts geht verloren.',
  'game.concept.badges.more': 'Alle meine Abzeichen ansehen',
  'game.concept.defis.name': 'Herausforderungen',
  'game.concept.defis.why': 'Herausforderungen sind Stufen, die du eine nach der anderen nimmst.',
  'game.concept.defis.how': 'Jede erreichte Stufe öffnet die nächste, ein Stück höher.',
  'game.concept.defis.tip.1': 'Sieh dir die nächste Stufe an und arbeite darauf hin.',
  'game.concept.defis.tip.2': 'Probier neue Aktionen aus: Jede hat ihre Herausforderungen.',
  'game.concept.defis.more': 'Alle meine Herausforderungen ansehen',
  'game.concept.succes.name': 'Erfolge',
  'game.concept.succes.why': 'Ein Erfolg hält einen seltenen Moment deiner Meeshy-Geschichte fest.',
  'game.concept.succes.how': 'Du schaltest ihn auf einmal frei, wenn du erfüllst, was er verlangt.',
  'game.concept.succes.tip.1': 'Erkunde die App: Manche Erfolge sind versteckt.',
  'game.concept.succes.tip.2': 'Die seltensten bringen den meisten Ruhm.',
  'game.concept.succes.more': 'Alle meine Erfolge ansehen',
  'game.concept.showcase.name': 'Vitrine',
  'game.concept.showcase.why': 'Deine Vitrine zeigt die Trophäen, die du gewonnen hast.',
  'game.concept.showcase.how': 'Jeder Pokal landet von selbst dort. Du bestimmst, wer sie sieht.',
  'game.concept.showcase.tip.1': 'Lande in deiner Liga ganz oben, um einen Pokal zu gewinnen.',
  'game.concept.showcase.tip.2': 'Schließe eine Saison ab oder wechsle ins Prestige.',
  'game.concept.showcase.more': 'Meine Vitrine öffnen',
  'game.concept.atlas.name': 'Atlas',
  'game.concept.atlas.why': 'Der Atlas bewahrt einen Stempel für jede Sprache deiner Gespräche.',
  'game.concept.atlas.how': 'Sende und erhalte eine Nachricht in einer Sprache: Der Stempel sitzt.',
  'game.concept.atlas.tip.1': 'Schreib jemandem in einer anderen Sprache als deiner.',
  'game.concept.atlas.tip.2': 'Warte auf die Antwort: Es braucht eine Nachricht in jede Richtung.',
  'game.concept.atlas.more': 'Meinen Atlas öffnen',
  'game.concept.chip.next_price': 'Nächste: {price}',
  'game.concept.chip.next': 'Danach: {name}',
  'game.concept.chip.record': 'Rekord: {value}',
  'game.concept.chip.freezes': 'Eis: {count}',
  'game.concept.chip.chest.locked': 'Truhe zu',
  'game.concept.chip.chest.ready': 'Truhe bereit',
  'game.concept.chip.chest.claimed': 'Truhe geöffnet',
  'game.concept.chip.can_mint': 'Prägen möglich',
  'game.concept.chip.mint_covered': 'Genug für eine Meesh',
  'game.concept.chip.left': 'Übrig: {count}',
  'game.concept.chip.week': 'Woche {week}',
  'game.concept.chip.no_elan': 'Kein Schwung aktiv',
  'game.concept.chip.factor': 'Punkte ×{factor}',
  'game.concept.chip.seen_by': 'Sichtbar für: {who}',
  'game.fact.tier': 'Stufe',
  'game.fact.to_next': 'Nächstes Level',
  'game.fact.record': 'Rekord',
  'game.fact.next_meesh': 'Nächste Meesh',
  'game.fact.missing': 'Es fehlen',
  'game.fact.balance': 'Im Besitz',
  'game.fact.next_tier': 'Nächste Stufe',
  'game.fact.minted': 'Bisher geprägt',
  'game.fact.next_rank': 'Nächster Rang',
  'game.fact.streak': 'Serie',
  'game.fact.form': 'Form',
  'game.fact.freezes': 'Eis in Reserve',
  'game.fact.state': 'Zustand',
  'game.fact.lit': 'Brennt',
  'game.fact.done': 'Erledigt',
  'game.fact.week_points': 'Wochenpunkte',
  'game.fact.closes': 'Schluss',
  'game.fact.steps': 'Etappen',
  'game.fact.stars': 'Sterne',
  'game.fact.week': 'Woche',
  'game.fact.factor': 'Multiplikator',
  'game.fact.families': 'Aktive Familien',
  'game.fact.earned': 'Erhalten',
  'game.fact.trophies': 'Trophäen',
  'game.fact.visibility': 'Sichtbar für',
  'game.fact.stamps': 'Stempel',
  'game.fact.pending': 'Läuft',
  'game.fact.group': 'Gruppe',
  'game.fact.material': 'Material',
  'game.detail.obtain_label': 'So bekommst du es',
  'game.detail.gives_label': 'Was es bringt',
  'game.detail.earned': 'Erhalten',
  'game.detail.earned_on': 'Erhalten am {date}',
  'game.detail.locked': 'Noch nicht erhalten',
  'game.detail.missing': 'Es fehlt: {missing}',
  'game.detail.see_fiche': 'Zur Seite',
  'game.detail.open': '{name}: Details ansehen',
  'game.detail.rarity': 'Seltenheit',
  'game.detail.header_group': 'Mein Rang und meine Meeshes',
  'game.detail.badge.what': 'Ein Abzeichen zeigt, wie oft du eine Aktion gemacht hast.',
  'game.detail.badge.how': 'Mach sie wieder: Bei jeder Stufe wechselt das Abzeichen das Material.',
  'game.detail.succes.what': 'Ein Erfolg hält einen seltenen Moment deiner Meeshy-Geschichte fest.',
  'game.detail.succes.how': 'Erfülle, was er verlangt: Er wird auf einmal freigeschaltet.',
  'game.detail.defi.what': 'Eine Herausforderung ist eine Stufe in einer Familie von Aktionen.',
  'game.detail.defi.how': 'Erreiche die verlangte Zahl: Die nächste Stufe öffnet sich.',
  'game.detail.trophy.what': 'Eine Trophäe bewahrt die Erinnerung an einen Sieg. Sie bringt nichts: Man zeigt sie.',
  'game.detail.trophy.how': 'Lande ganz oben in deiner Liga, schließe eine Saison ab, wechsle ins Prestige oder halte deine Flamme.',
  'game.detail.stamp.what': 'Ein Stempel beweist, dass du dich in dieser Sprache wirklich ausgetauscht hast.',
  'game.detail.stamp.how': 'Sende eine Nachricht in dieser Sprache und erhalte eine zurück.',
  'game.detail.step.what': 'Eine Saison-Etappe ist eine kostenlose Belohnung auf dem Weg.',
  'game.detail.step.how': 'Sammle Sterne mit Missionen und dem Duo, dann hol dir die Etappe.',
  'game.detail.seal.what': 'Das Siegel ist ein Sammelobjekt. Es ändert nichts am Spiel.',
  'game.detail.seal.how': 'Hol es dir während der Saison mit deinen Meeshes.',
  'game.detail.gem.what': 'Der Edelstein zeigt, in welcher Liga du diese Woche spielst.',
  'game.detail.gem.how': 'Lande unter den Ersten deiner Gruppe, um eine Liga aufzusteigen.',
  'game.detail.star.what': 'Ein Prestige-Stern bleibt für immer an deinem Level-Ring.',
  'game.detail.star.how': 'Erreiche Level 100 und wechsle dann ins Prestige.',
  'game.detail.rank.what': 'Dein Wappen zeigt deinen Rang. Ein Rang sinkt nie.',
  'game.detail.rank.how': 'Sammle Ruhm: Präge Meeshes, brich deine Rekorde, schalte Erfolge frei.',
  'game.detail.flame.what': 'Die Form deiner Flamme wächst mit deiner Serie von Tagen.',
  'game.detail.flame.how': 'Je größer sie ist, desto höher sind deine Missionsbelohnungen.',
  'game.detail.freeze.what': 'Ein Eis schützt deine Flamme: Es deckt einen Tag ab, an dem du nichts gemacht hast.',
  'game.detail.freeze.how': 'Kauf es mit deinen Meeshes oder finde es in der Truhe des Tages.',
  'game.detail.mission.what': 'Eine Mission ist ein kleines Ziel für heute.',
  'game.detail.mission.how': 'Sie bringt Punkte und bringt dich der Truhe des Tages näher.',
  'game.detail.chest.what': 'Die Truhe des Tages öffnet sich, wenn deine Missionen erledigt sind.',
  'game.detail.chest.how': 'Punkte und manchmal ein Meesh-Fragment oder ein Eis.',
  'game.detail.coin.what': 'Die Meesh ist die seltene Münze von Meeshy. Jede Münze trägt ihre Nummer.',
  'game.detail.coin.how': 'Präge sie mit deinen Punkten, sobald du genug hast.',
  'game.detail.ring.what': 'Der Ring zeigt dein Level: Er füllt sich mit deinen Punkten.',
  'game.detail.ring.how': 'Sammle Punkte: Ist der Ring voll, steigst du ein Level auf.',
  'game.detail.treasury.what': 'Dein Schatz wächst mit den Meeshes, die du behältst.',
  'game.detail.treasury.how': 'Behalte deine Meeshes, statt sie auszugeben, um die nächste Stufe zu erreichen.',
  'game.detail.elan.what': 'Eine Familie fasst ähnliche Aktionen zusammen.',
  'game.detail.elan.how': 'Jede Aktion bringt Punkte. Mehrere aktive Familien lösen einen Schwung aus.',
  'game.detail.elan.active': 'In diesen Tagen aktiv',
  'game.detail.elan.idle': 'In diesen Tagen nicht aktiv',
  'game.detail.elan.points': '{points} pro Aktion',
  'game.detail.player.what': 'Ein Spieler deiner Gruppe. Du siehst nur sein Pseudonym und seine Wochenpunkte.',
  'game.detail.fact.tier': 'Zehn Level bilden eine Stufe. Jede Stufe hat ihren Namen und ihre Farbe.',
  'game.detail.fact.score': 'Das sind die Punkte, die du hast. Sie bestimmen dein Level.',
  'game.detail.fact.level_next': 'Das sind die Punkte, die dir zum nächsten Level fehlen.',
  'game.detail.fact.level_record': 'Das ist das höchste Level, das du erreicht hast.',
  'game.detail.fact.tailwind': 'Nach einer Prägung zählen deine Punkte mehr, bis zu deinem Rekord-Level.',
  'game.detail.fact.mint_price': 'Das ist der Preis deiner nächsten Meesh. Er steigt mit jeder Prägung.',
  'game.detail.fact.mint_missing': 'Das sind die Punkte, die dir fehlen, um deine nächste Meesh zu prägen.',
  'game.detail.fact.can_mint': 'Du hast genug Punkte: Du kannst auf ihrer Seite eine Meesh prägen.',
  'game.detail.fact.factor': 'Deine nächsten Aktionen bringen so viel Mal mehr Punkte.',
  'game.detail.fact.mint_next': 'Jede Meesh trägt ihre Nummer. Jede hundertste ist aus Gold, jede tausendste aus Prisma.',
  'game.detail.fact.mint_glory': 'Jede Prägung fügt deinem Rang diesen Ruhm hinzu.',
  'game.detail.fact.minted': 'So viele Meeshes hast du seit dem Anfang geprägt.',
  'game.detail.fact.glory': 'Ruhm summiert sich und sinkt nie. Er bestimmt deinen Rang.',
  'game.detail.fact.glory_missing': 'Das ist der Ruhm, der dir zum nächsten Rang fehlt.',
  'game.detail.fact.streak': 'So viele Tage in Folge hast du mindestens eine Aktion gemacht.',
  'game.detail.fact.streak_record': 'Das ist deine längste Serie von Tagen.',
  'game.detail.fact.flame_state': 'Er sagt, ob deine Flamme brennt, in Gefahr, geschützt oder erloschen ist.',
  'game.detail.fact.missions_done': 'Drei Missionen pro Tag. Sind sie erledigt, öffnen sie die Truhe.',
  'game.detail.fact.league_place': 'Das ist dein Platz unter den Spielern deiner Gruppe in dieser Woche.',
  'game.detail.fact.week_points': 'Das sind die Punkte seit Montag. Jede Woche beginnen sie wieder bei null.',
  'game.detail.fact.league_zone': 'Die Ersten steigen auf, die Letzten steigen ab, die anderen bleiben.',
  'game.detail.fact.league_missing': 'Das sind die Punkte, die dir für die Aufstiegszone fehlen.',
  'game.detail.fact.league_closes': 'Die Ligawoche endet am Sonntagabend. Dann steht die Rangliste fest.',
  'game.detail.fact.league_friends': 'Das ist dein Platz unter deinen angenommenen Freunden in dieser Woche.',
  'game.detail.fact.season': 'Eine Saison dauert acht Wochen und hat eine Nummer.',
  'game.detail.fact.season_week': 'Das ist die laufende Woche von den acht der Saison.',
  'game.detail.fact.season_steps': 'Das sind die Etappen, die du auf dem Saisonweg geöffnet hast.',
  'game.detail.fact.season_stars': 'Sterne sammelst du mit Missionen und dem Duo. Sie öffnen die Etappen.',
  'game.detail.fact.prestige_glory': 'Das ist der Ruhm, den du beim Wechsel ins Prestige bekommst.',
  'game.detail.fact.elan_families': 'Das sind die Aktionsfamilien, in denen du zuletzt aktiv warst.',
  'game.detail.fact.badges_earned': 'So viele Abzeichen hast du erhalten, von allen, die es gibt.',
  'game.detail.fact.defis_earned': 'Das sind die genommenen Stufen, von denen, die du erreichen kannst.',
  'game.detail.fact.succes_earned': 'Das sind die freigeschalteten Erfolge, von allen, die es gibt.',
  'game.detail.fact.trophies': 'So viele Trophäen stehen in deiner Vitrine.',
  'game.detail.fact.showcase_visibility': 'Du bestimmst, wer deine Vitrine sieht: alle, deine Freunde oder nur du.',
  'game.detail.fact.atlas_stamps': 'Das sind die Sprachen, in denen du einen Stempel hast, von allen im Atlas.',
  'game.detail.fact.atlas_pending': 'Das sind die Sprachen, in denen noch eine Nachricht fehlt, gesendet oder erhalten.',
} as const satisfies GameConceptCatalog;

export default de;
