import type { SendSheetCatalog } from '@/lib/i18n-send-sheet-catalog';

const en = {
  'sendSheet.title.forward': 'Forward',
  'sendSheet.title.share': 'Share',
  'sendSheet.title.sendTo': 'Send to…',
  'sendSheet.cancel': 'Cancel',
  'sendSheet.caption.label': 'Message',
  'sendSheet.caption.placeholder': 'Add a message…',
  'sendSheet.search.label': 'Search for a person or a conversation',
  'sendSheet.search.placeholder': 'Search for a person or a conversation',
  'sendSheet.empty': 'No results',
  'sendSheet.section.recent': 'Recent',
  'sendSheet.section.people': 'People',
  'sendSheet.section.conversations': 'Conversations',
  'sendSheet.section.publish': 'Publish',
  'sendSheet.publish.story': 'My story',
  'sendSheet.publish.post': 'Post',
  'sendSheet.publish.reel': 'Reel',
  'sendSheet.send': 'Send',
  'sendSheet.sendCount': 'Send ({count})',
  'sendSheet.row.select': 'Select {name}',
  'sendSheet.selectedCount': '{count} selected',
  'sendSheet.state.sending': 'Sending…',
  'sendSheet.state.sent': 'Sent',
  'sendSheet.state.failed': 'Failed',
  'sendSheet.state.retry': 'Try again',
  'sendSheet.state.waitingNetwork': 'Waiting for network',
  'sendSheet.failure.download': 'Couldn’t get the file',
  'sendSheet.failure.refused': 'The send was declined',
  'sendSheet.limit.recipients': 'Up to {count} recipients',
  'sendSheet.error.captionTooLong': 'This message is too long to publish (up to {count} characters)',
  'sendSheet.error.tooManyFiles': 'Up to {count} files per publication',
  'sendSheet.moreOptions': 'More options…',
  'sendSheet.copyLink': 'Copy link',
  'sendSheet.linkCopied': 'Link copied',
  'sendSheet.announce.sent': 'Sent to {count}',
  'sendSheet.preview.messages': '{count} messages',
  'sendSheet.preview.photo': 'Photo',
  'sendSheet.preview.video': 'Video',
  'sendSheet.preview.voice': 'Voice message',
  'sendSheet.preview.file': 'File',
  'sendSheet.preview.publication': 'Publication',
  'sendSheet.protected': 'Protected content: it can’t be published',
  'shareLinkSheet.title': 'Create a share link',
  'shareLinkSheet.empty': 'No conversation can receive a link right now.',
  'shareLinkSheet.createFailed': 'Couldn’t create the link — try again in a moment.',
  'shareLinkSheet.copied': 'Link copied — just paste it.',
  'shareLinkSheet.unavailable': 'Can’t share here. Copy this page’s address.',
} satisfies SendSheetCatalog;

export default en;
