import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page, les fiches et le tableau de bord (`game.concept.*`, `game.fiche.*`, `game.fact.*`, `game.dashboard.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const es = {
  'game.progression.title': 'Progreso',
  'game.dashboard.title': 'Panel',
  'game.dashboard.hint': 'Todos tus datos, concepto por concepto.',
  'game.concept.why_label': 'Para qué sirve',
  'game.concept.how_label': 'Cómo funciona',
  'game.fiche.what': '¿Qué es?',
  'game.fiche.where': 'Dónde estoy',
  'game.fiche.earn': 'Cómo ganar más',
  'game.fiche.more': 'Ir más lejos',
  'game.fiche.unknown': 'Esta ficha no existe, o tu servidor todavía no la ofrece.',
  'game.concept.level.name': 'Nivel',
  'game.concept.level.why': 'Tu nivel muestra el camino que has recorrido en Meeshy.',
  'game.concept.level.how': 'Tus puntos llenan el anillo: cuando está lleno, subes un nivel.',
  'game.concept.level.tip.1': 'Haz las misiones del día: dan muchos puntos.',
  'game.concept.level.tip.2': 'Mantén tu Llama encendida: aumenta tus recompensas.',
  'game.concept.points.name': 'Puntos',
  'game.concept.points.why': 'Los puntos suben tu nivel y sirven para acuñar Meeshes.',
  'game.concept.points.how': 'Cada gesto útil da puntos: escribir, hablar, publicar, reaccionar.',
  'game.concept.points.tip.1': 'Publica, comenta, reacciona: cada familia de gestos tiene su baremo.',
  'game.concept.points.tip.2': 'Activa un impulso para multiplicar tus puntos.',
  'game.concept.meesh.name': 'Meeshes',
  'game.concept.meesh.why': 'La Meesh es la moneda rara de Meeshy: se guarda o se gasta.',
  'game.concept.meesh.how': 'La acuñas con tus puntos. Cada acuñación encarece la siguiente.',
  'game.concept.meesh.tip.1': 'Guarda tus Meeshes para hacer crecer tu tesoro.',
  'game.concept.meesh.tip.2': 'Gástalas para proteger tu Llama o cambiar una misión.',
  'game.concept.glory.name': 'Gloria',
  'game.concept.glory.why': 'La Gloria te da tu rango, y tu rango nunca baja.',
  'game.concept.glory.how': 'Cada acuñación, cada récord y cada logro suman Gloria.',
  'game.concept.glory.tip.1': 'Acuña una Meesh: cada acuñación suma Gloria.',
  'game.concept.glory.tip.2': 'Bate tus récords y consigue logros.',
  'game.concept.flame.name': 'Llama',
  'game.concept.flame.why': 'Tu Llama cuenta tus días seguidos y aumenta tus recompensas de misión.',
  'game.concept.flame.how': 'Un gesto al día la hace crecer. Una congelación cubre un día perdido.',
  'game.concept.flame.tip.1': 'Haz al menos un gesto cada día.',
  'game.concept.flame.tip.2': 'Guarda una congelación en reserva para los días sin jugar.',
  'game.concept.missions.name': 'Misiones del día',
  'game.concept.missions.why': 'Las misiones te dan una meta cada día, y puntos extra.',
  'game.concept.missions.how': 'Tres misiones al día. Cuando están hechas, abres el cofre.',
  'game.concept.missions.tip.1': 'Empieza por la misión más fácil.',
  'game.concept.missions.tip.2': '¿No te gusta una misión? Cámbiala, una vez al día.',
  'game.concept.league.name': 'Liga',
  'game.concept.league.why': 'La liga te mide cada semana con otros 29 jugadores.',
  'game.concept.league.how': 'Tus puntos de la semana marcan tu puesto. Los primeros suben de liga.',
  'game.concept.league.tip.1': 'Juega un poco cada día: los puntos de la semana se suman.',
  'game.concept.league.tip.2': 'Apunta a los primeros puestos antes del domingo por la noche.',
  'game.concept.league.more': 'Ver la clasificación',
  'game.concept.league.value': '{league} · puesto {rank}',
  'game.concept.league.unplaced': 'Aún sin grupo',
  'game.concept.season.name': 'Temporada',
  'game.concept.season.why': 'La temporada es un recorrido de ocho semanas, con una copa al final.',
  'game.concept.season.how': 'Las misiones y el dúo dan estrellas. Las estrellas abren las etapas.',
  'game.concept.season.tip.1': 'Termina tus misiones del día para ganar estrellas.',
  'game.concept.season.tip.2': 'Juega en dúo con un amigo: la recompensa se duplica.',
  'game.concept.season.more': 'Ver el recorrido',
  'game.concept.season.none': 'Ninguna ahora',
  'game.concept.prestige.name': 'Prestigio',
  'game.concept.prestige.why': 'El Prestigio premia a quienes llegan al nivel 100.',
  'game.concept.prestige.how': 'Tu nivel vuelve a 1. Ganas una estrella, un trofeo y Gloria.',
  'game.concept.prestige.tip.1': 'Sube hasta el nivel 100.',
  'game.concept.prestige.tip.2': 'Pasa a Prestigio cuando quieras: nada te obliga.',
  'game.concept.prestige.more': 'Abrir el Prestigio',
  'game.concept.elans.name': 'Impulsos',
  'game.concept.elans.why': 'Un impulso multiplica los puntos de tus próximos gestos.',
  'game.concept.elans.how': 'Haz gestos de varias familias estos días para activarlo.',
  'game.concept.elans.tip.1': 'Varía tus gestos: escribe, publica, comenta, reacciona.',
  'game.concept.elans.tip.2': 'Vuelve varios días seguidos para mantenerlo.',
  'game.concept.elans.families.one': '{count} familia activa',
  'game.concept.elans.families.other': '{count} familias activas',
  'game.concept.badges.name': 'Insignias',
  'game.concept.badges.why': 'Una insignia muestra lo que más haces en Meeshy.',
  'game.concept.badges.how': 'Repite un gesto: su insignia cambia de material, del cobre al prisma.',
  'game.concept.badges.tip.1': 'Elige un gesto que te guste y repítelo a menudo.',
  'game.concept.badges.tip.2': 'Una insignia apagada se vuelve a encender: nada se pierde.',
  'game.concept.badges.more': 'Ver todas mis insignias',
  'game.concept.defis.name': 'Desafíos',
  'game.concept.defis.why': 'Los desafíos son escalones que superar, uno tras otro.',
  'game.concept.defis.how': 'Cada escalón alcanzado abre el siguiente, un poco más alto.',
  'game.concept.defis.tip.1': 'Mira el próximo escalón y avanza hacia él.',
  'game.concept.defis.tip.2': 'Prueba gestos nuevos: cada uno tiene sus desafíos.',
  'game.concept.defis.more': 'Ver todos mis desafíos',
  'game.concept.succes.name': 'Logros',
  'game.concept.succes.why': 'Un logro marca un momento raro de tu historia en Meeshy.',
  'game.concept.succes.how': 'Se consigue de una vez, cuando reúnes lo que pide.',
  'game.concept.succes.tip.1': 'Explora la aplicación: algunos logros están escondidos.',
  'game.concept.succes.tip.2': 'Los más raros son los que más Gloria suman.',
  'game.concept.succes.more': 'Ver todos mis logros',
  'game.concept.showcase.name': 'Vitrina',
  'game.concept.showcase.why': 'Tu vitrina expone los trofeos que has ganado.',
  'game.concept.showcase.how': 'Cada copa se coloca sola. Tú eliges el orden y quién la ve.',
  'game.concept.showcase.tip.1': 'Termina arriba en tu liga para ganar una copa.',
  'game.concept.showcase.tip.2': 'Completa una temporada o pasa a Prestigio.',
  'game.concept.showcase.more': 'Abrir mi vitrina',
  'game.concept.atlas.name': 'Atlas',
  'game.concept.atlas.why': 'El Atlas guarda un sello por cada idioma en el que has conversado.',
  'game.concept.atlas.how': 'Envía un mensaje y recibe otro en un idioma: el sello se estampa.',
  'game.concept.atlas.tip.1': 'Escribe a alguien en un idioma distinto del tuyo.',
  'game.concept.atlas.tip.2': 'Espera su respuesta: hace falta un mensaje en cada sentido.',
  'game.concept.atlas.more': 'Abrir mi Atlas',
  'game.concept.chip.next_price': 'Siguiente: {price}',
  'game.concept.chip.next': 'Después: {name}',
  'game.concept.chip.record': 'Récord: {value}',
  'game.concept.chip.freezes': 'Congelaciones: {count}',
  'game.concept.chip.chest.locked': 'Cofre cerrado',
  'game.concept.chip.chest.ready': 'Cofre listo',
  'game.concept.chip.chest.claimed': 'Cofre abierto',
  'game.concept.chip.can_mint': 'Puedes acuñar',
  'game.concept.chip.left': 'Quedan: {count}',
  'game.concept.chip.week': 'Semana {week}',
  'game.concept.chip.no_elan': 'Sin impulso activo',
  'game.concept.chip.factor': 'Puntos ×{factor}',
  'game.concept.chip.seen_by': 'La ven: {who}',
  'game.fact.tier': 'Tramo',
  'game.fact.to_next': 'Próximo nivel',
  'game.fact.record': 'Récord',
  'game.fact.next_meesh': 'Próxima Meesh',
  'game.fact.missing': 'Falta',
  'game.fact.balance': 'En mano',
  'game.fact.next_tier': 'Tramo siguiente',
  'game.fact.minted': 'Acuñadas desde siempre',
  'game.fact.next_rank': 'Rango siguiente',
  'game.fact.streak': 'Racha',
  'game.fact.form': 'Forma',
  'game.fact.freezes': 'Congelaciones en reserva',
  'game.fact.state': 'Estado',
  'game.fact.lit': 'Encendida',
  'game.fact.done': 'Hechas',
  'game.fact.week_points': 'Puntos de la semana',
  'game.fact.closes': 'Cierre',
  'game.fact.steps': 'Etapas',
  'game.fact.stars': 'Estrellas',
  'game.fact.week': 'Semana',
  'game.fact.factor': 'Multiplicador',
  'game.fact.families': 'Familias activas',
  'game.fact.earned': 'Conseguidas',
  'game.fact.trophies': 'Trofeos',
  'game.fact.visibility': 'Visible para',
  'game.fact.stamps': 'Sellos',
  'game.fact.pending': 'En curso',
  'game.fact.group': 'Grupo',
} as const satisfies GameConceptCatalog;

export default es;
