import type { ComposerAttachCatalogSlice } from './catalog-fr-composer-attach';

/** The composer's attachment drawer and « Mes stickers » (#7938) — see `catalog-fr-composer-attach.ts`. */
const arComposerAttach = {
  'composer.attach.group': 'أنواع المرفقات',
  'composer.attach.handle': 'مقبض اللوحة',
  'composer.attach.photo': 'الصور',
  'composer.attach.photo.action': 'اختيار صور',
  'composer.attach.camera': 'الكاميرا',
  'composer.attach.camera.action': 'التقاط صورة',
  'composer.attach.file': 'ملف',
  'composer.attach.file.action': 'اختيار ملف',
  'composer.attach.location': 'الموقع',
  'composer.attach.location.action': 'مشاركة موقعي',
  'composer.attach.voice': 'صوت',
  'composer.attach.voice.action': 'تسجيل رسالة صوتية',
  'composer.attach.emoji': 'الرموز التعبيرية',
  'composer.attach.emoji.action': 'إدراج رمز تعبيري',
  'composer.emoji.title': 'إدراج رمز تعبيري',
  'composer.location.locating': 'جارٍ تحديد موقعك…',
  'composer.location.denied': 'تم رفض الموقع — اسمح به من الإعدادات',
  'composer.location.unavailable': 'الموقع غير متاح في هذا المتصفح',
  'composer.location.failed': 'تعذّر تحديد الموقع — أعد المحاولة',
  'composer.location.chip': 'موقع',
  'composer.location.unknown': 'مكان غير معروف',
  'composer.location.remove': 'إزالة الموقع',
  'composer.attach.sticker': 'ملصق',
  'composer.attach.sticker.action': 'إرسال ملصق',
  'composer.sticker.title': 'ملصقاتي',
  'composer.sticker.fromImage': 'من صورة',
  'composer.sticker.paste': 'لصق',
  'composer.sticker.pasteHint': 'الصق صورة أو أفلتها هنا لتحويلها إلى ملصق',
  'composer.sticker.nothingToPaste': 'لا توجد صورة في الحافظة',
  'composer.sticker.empty': 'لا توجد ملصقات بعد — أنشئ واحدًا من صورة أو الصق واحدًا',
  'composer.sticker.creating': 'جارٍ إنشاء الملصق…',
  'composer.sticker.manage': 'إدارة',
  'composer.sticker.done': 'تم',
  'composer.sticker.remove': 'إزالة هذا الملصق',
  'composer.sticker.item': 'ملصق',
  'composer.sticker.unavailable': 'تعذّر تحميل هذا الملصق — أعد المحاولة',
  'composer.sticker.error.notImage': 'هذا الملف ليس صورة',
  'composer.sticker.error.tooLarge': 'الصورة كبيرة جدًا لملصق',
  'composer.sticker.error.full': 'المكتبة ممتلئة — أزل ملصقًا لإضافة آخر',
  'composer.sticker.error.failed': 'تعذّر إنشاء الملصق',
  'composer.quickEmoji.label': 'إرسال مباشرة',
  'composer.quickEmoji.group': 'رموز تعبيرية سريعة',
  'composer.effects.panel': 'تأثيرات الرسالة',
  'composer.effects.entrance': 'حركة الدخول',
  'composer.effects.permanent': 'تأثير دائم',
  'composer.effects.clearAll': 'مسح الكل',
} satisfies ComposerAttachCatalogSlice;

export default arComposerAttach;
