import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page, les fiches et le tableau de bord (`game.concept.*`, `game.fiche.*`, `game.fact.*`, `game.dashboard.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const pt = {
  'game.progression.title': 'Progresso',
  'game.dashboard.title': 'Painel',
  'game.dashboard.hint': 'Todos os seus dados, conceito por conceito.',
  'game.concept.why_label': 'Para que serve',
  'game.concept.how_label': 'Como funciona',
  'game.fiche.what': 'O que é?',
  'game.fiche.where': 'Onde estou',
  'game.fiche.earn': 'Como ganhar mais',
  'game.fiche.more': 'Ir mais longe',
  'game.fiche.unknown': 'Esta ficha não existe, ou o seu servidor ainda não a oferece.',
  'game.concept.level.name': 'Nível',
  'game.concept.level.why': 'Seu nível mostra o caminho que você percorreu no Meeshy.',
  'game.concept.level.how': 'Seus pontos enchem o anel: quando ele fica cheio, você sobe um nível.',
  'game.concept.level.tip.1': 'Faça as missões do dia: elas dão muitos pontos.',
  'game.concept.level.tip.2': 'Mantenha sua Chama acesa: ela aumenta suas recompensas.',
  'game.concept.points.name': 'Pontos',
  'game.concept.points.why': 'Os pontos sobem seu nível e servem para cunhar Meeshes.',
  'game.concept.points.how': 'Cada gesto útil dá pontos: escrever, falar, publicar, reagir, convidar.',
  'game.concept.points.tip.1': 'Publique, comente, reaja: cada família de gestos tem sua tabela.',
  'game.concept.points.tip.2': 'Ative um impulso para multiplicar seus pontos.',
  'game.concept.meesh.name': 'Meeshes',
  'game.concept.meesh.why': 'A Meesh é a moeda rara do Meeshy: você guarda ou gasta.',
  'game.concept.meesh.how': 'Você a cunha com seus pontos. Cada cunhagem encarece a próxima.',
  'game.concept.meesh.tip.1': 'Guarde suas Meeshes para fazer seu tesouro crescer.',
  'game.concept.meesh.tip.2': 'Gaste-as para proteger sua Chama ou trocar uma missão.',
  'game.concept.glory.name': 'Glória',
  'game.concept.glory.why': 'A Glória dá o seu rank, e o seu rank nunca cai.',
  'game.concept.glory.how': 'Cada cunhagem, cada recorde e cada conquista somam Glória.',
  'game.concept.glory.tip.1': 'Cunhe uma Meesh: cada cunhagem soma Glória.',
  'game.concept.glory.tip.2': 'Bata seus recordes e desbloqueie conquistas.',
  'game.concept.flame.name': 'Chama',
  'game.concept.flame.why': 'Sua Chama conta seus dias seguidos e aumenta suas recompensas de missão.',
  'game.concept.flame.how': 'Um gesto por dia a faz crescer. Um congelamento cobre um dia perdido.',
  'game.concept.flame.tip.1': 'Faça pelo menos um gesto todos os dias.',
  'game.concept.flame.tip.2': 'Guarde um congelamento de reserva para os dias sem jogar.',
  'game.concept.missions.name': 'Missões do dia',
  'game.concept.missions.why': 'As missões dão um objetivo a cada dia, e pontos a mais.',
  'game.concept.missions.how': 'Três missões por dia. Quando estão feitas, você abre o baú.',
  'game.concept.missions.tip.1': 'Comece pela missão mais fácil.',
  'game.concept.missions.tip.2': 'Não gostou de uma missão? Troque-a, uma vez por dia.',
  'game.concept.league.name': 'Liga',
  'game.concept.league.why': 'A liga compara você, toda semana, com outros 29 jogadores.',
  'game.concept.league.how': 'Seus pontos da semana definem sua posição. Os primeiros sobem de liga.',
  'game.concept.league.tip.1': 'Jogue um pouco todo dia: os pontos da semana se somam.',
  'game.concept.league.tip.2': 'Mire nas primeiras posições antes de domingo à noite.',
  'game.concept.league.more': 'Ver a classificação',
  'game.concept.league.value': '{league} · posição {rank}',
  'game.concept.league.unplaced': 'Ainda sem grupo',
  'game.concept.season.name': 'Temporada',
  'game.concept.season.why': 'A temporada é um percurso de oito semanas, com uma taça no fim.',
  'game.concept.season.how': 'As missões e a dupla dão estrelas. As estrelas abrem as etapas.',
  'game.concept.season.tip.1': 'Termine suas missões do dia para ganhar estrelas.',
  'game.concept.season.tip.2': 'Jogue em dupla com um amigo: a recompensa é dobrada.',
  'game.concept.season.more': 'Ver o percurso',
  'game.concept.season.none': 'Nenhuma agora',
  'game.concept.prestige.name': 'Prestígio',
  'game.concept.prestige.why': 'O Prestígio recompensa quem chega ao nível 100.',
  'game.concept.prestige.how': 'Seu nível volta a 1. Você ganha uma estrela, um troféu e Glória.',
  'game.concept.prestige.tip.1': 'Suba até o nível 100.',
  'game.concept.prestige.tip.2': 'Passe ao Prestígio quando quiser: nada obriga você.',
  'game.concept.prestige.more': 'Abrir o Prestígio',
  'game.concept.elans.name': 'Impulsos',
  'game.concept.elans.why': 'Um impulso multiplica os pontos dos seus próximos gestos.',
  'game.concept.elans.how': 'Faça gestos de várias famílias nestes dias para ativá-lo.',
  'game.concept.elans.tip.1': 'Varie seus gestos: escreva, publique, comente, reaja.',
  'game.concept.elans.tip.2': 'Volte vários dias seguidos para mantê-lo.',
  'game.concept.elans.families.one': '{count} família ativa',
  'game.concept.elans.families.other': '{count} famílias ativas',
  'game.concept.badges.name': 'Selos',
  'game.concept.badges.why': 'Um selo mostra o que você mais faz no Meeshy.',
  'game.concept.badges.how': 'Repita um gesto: o selo dele muda de material, do cobre ao prisma.',
  'game.concept.badges.tip.1': 'Escolha um gesto de que você gosta e repita-o sempre.',
  'game.concept.badges.tip.2': 'Um selo apagado volta a acender: nada se perde.',
  'game.concept.badges.more': 'Ver todos os meus selos',
  'game.concept.defis.name': 'Desafios',
  'game.concept.defis.why': 'Os desafios são degraus a vencer, um depois do outro.',
  'game.concept.defis.how': 'Cada degrau alcançado abre o próximo, um pouco mais alto.',
  'game.concept.defis.tip.1': 'Olhe o próximo degrau e avance até ele.',
  'game.concept.defis.tip.2': 'Experimente gestos novos: cada um tem seus desafios.',
  'game.concept.defis.more': 'Ver todos os meus desafios',
  'game.concept.succes.name': 'Conquistas',
  'game.concept.succes.why': 'Uma conquista marca um momento raro da sua história no Meeshy.',
  'game.concept.succes.how': 'Ela se desbloqueia de uma vez, quando você reúne o que ela pede.',
  'game.concept.succes.tip.1': 'Explore o aplicativo: algumas conquistas estão escondidas.',
  'game.concept.succes.tip.2': 'As mais raras são as que mais somam Glória.',
  'game.concept.succes.more': 'Ver todas as minhas conquistas',
  'game.concept.showcase.name': 'Vitrine',
  'game.concept.showcase.why': 'Sua vitrine expõe os troféus que você ganhou.',
  'game.concept.showcase.how': 'Cada taça vai para lá sozinha. Você escolhe a ordem e quem a vê.',
  'game.concept.showcase.tip.1': 'Termine no topo da sua liga para ganhar uma taça.',
  'game.concept.showcase.tip.2': 'Complete uma temporada ou passe ao Prestígio.',
  'game.concept.showcase.more': 'Abrir minha vitrine',
  'game.concept.atlas.name': 'Atlas',
  'game.concept.atlas.why': 'O Atlas guarda um carimbo para cada idioma em que você conversou.',
  'game.concept.atlas.how': 'Envie uma mensagem e receba outra em um idioma: o carimbo aparece.',
  'game.concept.atlas.tip.1': 'Escreva para alguém em um idioma diferente do seu.',
  'game.concept.atlas.tip.2': 'Espere a resposta: é preciso uma mensagem em cada sentido.',
  'game.concept.atlas.more': 'Abrir meu Atlas',
  'game.concept.chip.next_price': 'Próxima: {price}',
  'game.concept.chip.next': 'Depois: {name}',
  'game.concept.chip.record': 'Recorde: {value}',
  'game.concept.chip.freezes': 'Congelamentos: {count}',
  'game.concept.chip.chest.locked': 'Baú fechado',
  'game.concept.chip.chest.ready': 'Baú pronto',
  'game.concept.chip.chest.claimed': 'Baú aberto',
  'game.concept.chip.can_mint': 'Dá para cunhar',
  'game.concept.chip.left': 'Faltam: {count}',
  'game.concept.chip.week': 'Semana {week}',
  'game.concept.chip.no_elan': 'Nenhum impulso ativo',
  'game.concept.chip.factor': 'Pontos ×{factor}',
  'game.concept.chip.seen_by': 'Vista por: {who}',
  'game.fact.tier': 'Faixa',
  'game.fact.to_next': 'Próximo nível',
  'game.fact.record': 'Recorde',
  'game.fact.next_meesh': 'Próxima Meesh',
  'game.fact.missing': 'Falta',
  'game.fact.balance': 'Em mãos',
  'game.fact.next_tier': 'Próxima faixa',
  'game.fact.minted': 'Cunhadas desde sempre',
  'game.fact.next_rank': 'Próximo rank',
  'game.fact.streak': 'Sequência',
  'game.fact.form': 'Forma',
  'game.fact.freezes': 'Congelamentos de reserva',
  'game.fact.state': 'Estado',
  'game.fact.lit': 'Acesa',
  'game.fact.done': 'Feitas',
  'game.fact.week_points': 'Pontos da semana',
  'game.fact.closes': 'Fechamento',
  'game.fact.steps': 'Etapas',
  'game.fact.stars': 'Estrelas',
  'game.fact.week': 'Semana',
  'game.fact.factor': 'Multiplicador',
  'game.fact.families': 'Famílias ativas',
  'game.fact.earned': 'Obtidos',
  'game.fact.trophies': 'Troféus',
  'game.fact.visibility': 'Visível para',
  'game.fact.stamps': 'Carimbos',
  'game.fact.pending': 'Em andamento',
  'game.fact.group': 'Grupo',
} as const satisfies GameConceptCatalog;

export default pt;
