import type { CallControlsCatalog } from '@/lib/i18n-call-controls-catalog';

const it = {
  'callControls.invite': 'Aggiungi',
  'callControls.invite.label': 'Aggiungi persone alla chiamata',
  'callControls.react': 'Reagisci',
  'callControls.react.label': 'Invia una reazione',
  'callControls.react.palette': 'Reazioni',
  'callControls.react.send': 'Reagisci con {emoji}',
  'callControls.react.from': '{name} ha reagito {emoji}',
  'callControls.react.mine': 'Hai reagito {emoji}',
  'callControls.people.title': 'Partecipanti',
  'callControls.people.inCall': 'Nella chiamata',
  'callControls.people.add': 'Aggiungi persone',
  'callControls.people.search': 'Cerca un contatto',
  'callControls.people.empty': 'Tutti i tuoi contatti sono già nella chiamata',
  'callControls.people.none': 'Nessun contatto corrisponde',
  'callControls.people.invite': 'Invita',
  'callControls.people.inviteNamed': 'Invita {name}',
  'callControls.people.loading': 'Caricamento dei contatti…',
  'callControls.people.you': 'Tu',
  'callControls.close': 'Chiudi',
  'callControls.ringing': 'Sta squillando…',
  'callControls.invite.declined': '{name} ha rifiutato',
  'callControls.invite.unanswered': '{name} non ha risposto',
  'callControls.moderate.menu': 'Opzioni per {name}',
  'callControls.mute': 'Disattiva microfono',
  'callControls.mute.done': 'Microfono disattivato',
  'callControls.remove': 'Rimuovi dalla chiamata',
  'callControls.remove.confirm': 'Rimuovere {name} dalla chiamata?',
  'callControls.remove.detail': 'La chiamata terminerà subito per {name}.',
  'callControls.remove.do': 'Rimuovi',
  'callControls.cancel': 'Annulla',
  'callControls.mutedBy': '{name} ha disattivato il tuo microfono',
  'callControls.someone': 'Un partecipante',
  'callControls.incomingInvite': '{name} ti invita a una chiamata di gruppo',
  'callControls.error.invite': 'Impossibile invitare {name}',
  'callControls.error.mute': 'Impossibile disattivare il microfono di {name}',
  'callControls.error.remove': 'Impossibile rimuovere {name}',
  'callControls.error.notContact': '{name} non è tra i tuoi contatti',
  'callControls.error.alreadyIn': '{name} è già nella chiamata',
  'callControls.error.full': 'La chiamata è al completo',
  'callControls.error.rateLimited': 'Troppi tentativi: riprova tra un attimo',
  'callControls.error.denied': 'Non hai questo diritto in questa chiamata',
  'callControls.error.notActive': 'La chiamata non è più attiva',
  'callControls.error.gone': '{name} non è più nella chiamata',
  'callControls.record.title': 'Cosa vuoi registrare?',
  'callControls.record.audio': 'Solo audio',
  'callControls.record.audioDetail': 'Le voci di tutti',
  'callControls.record.video': 'Audio e video',
  'callControls.record.videoDetail': 'Le immagini visibili e le voci',
  'callControls.capture': 'Cattura',
  'callControls.capture.label': 'Cattura la chiamata',
  'callControls.back': 'Indietro',
  'callControls.journal': 'Diario',
  'callControls.journal.label': 'Apri il diario della chiamata',
  'callControls.journal.live': 'Torna alla diretta',
  'callControls.journal.empty': 'Ancora nulla di trascritto. Attiva i sottotitoli: ogni frase detta compare qui con la sua traduzione, per tutta la chiamata.',
  'callControls.journal.original': 'Originale',
  'callControls.camera.options': 'Opzioni della mia fotocamera',
  'callControls.selfTile.small': 'La mia miniatura: piccola',
  'callControls.selfTile.medium': 'La mia miniatura: media',
  'callControls.selfTile.large': 'La mia miniatura: grande',
  'callControls.selfTile.hint': 'Tocca per scambiare i video; trascinala o usa le frecce per spostarla',
  'callControls.selfTile.corner.top-left': 'La mia miniatura: in alto a sinistra',
  'callControls.selfTile.corner.top-right': 'La mia miniatura: in alto a destra',
  'callControls.selfTile.corner.bottom-left': 'La mia miniatura: in basso a sinistra',
  'callControls.selfTile.corner.bottom-right': 'La mia miniatura: in basso a destra',
} satisfies CallControlsCatalog;

export default it;
