import type { CallStudioCatalog } from '@/lib/i18n-call-studio-catalog';

/** Le studio d'un appel vidéo — pt (#8551, #8552). */
const pt = {
  'callStudio.effects.color': 'Cor',
  'callStudio.effects.settings': 'Ajustes',
  'callStudio.face.none': 'Nenhum',
  'callStudio.face.smoothing': 'Suavização da pele',
  'callStudio.face.toad': 'Sapo',
  'callStudio.face.angel': 'Anjo',
  'callStudio.face.demon': 'Demônio',
  'callStudio.face.volcano': 'Erupção',
  'callStudio.montage.screen': 'Tela cheia',
  'callStudio.montage.grid': 'Mosaico',
  'callStudio.montage.strip': 'Cabine de fotos',
  'callStudio.montage.polaroid': 'Polaroide',
  'callStudio.montage.magazine': 'Revista',
  'callStudio.montage.comic': 'Quadrinhos',
  'callStudio.montage.heart': 'Coração',
  'callStudio.capture.preview': 'Prévia da montagem {style}',
  'callStudio.capture.shoot': 'Capturar',
  'callStudio.capture.shootLabel': 'Capturar a montagem {style}',
  'callStudio.capture.faces': 'Cada rosto',
  'callStudio.capture.facesLabel': 'Salvar cada rosto separadamente',
  'callStudio.capture.saved': 'Captura salva',
  'callStudio.capture.faceSaved': '1 rosto salvo',
  'callStudio.capture.facesSaved': '{count} rostos salvos',
  'callStudio.capture.failed': 'Não foi possível salvar a captura',
  'callStudio.capture.cancelled': 'Salvamento cancelado',
  'callStudio.capture.empty': 'Nada para capturar: nenhuma imagem está sendo exibida',
  'callStudio.capture.busy': 'Capturando…',
  'callStudio.capture.bubble': 'Que chamada!',
  'callStudio.montage.cover': 'Capa',
  'callStudio.montage.gold': 'Dourado',
  'callStudio.montage.redcarpet': 'Tapete vermelho',
  'callStudio.montage.film': 'Película',
  'callStudio.montage.neon': 'Néon',
  'callStudio.montage.noir': 'Preto e branco',
  'callStudio.cover.line1': 'A chamada do ano',
  'callStudio.cover.line2': 'Finalmente todos juntos',
  'callStudio.cover.line3': 'Exclusivo',
  'callStudio.mode.effects': 'Efeitos do meu vídeo',
  'callStudio.mode.montage': 'Capturar a chamada',
  'callStudio.mode.quit': 'Sair',
  'callStudio.mode.quitEffects': 'Sair sem manter estas alterações',
  'callStudio.mode.validate': 'Concluir',
  'callStudio.mode.validateLabel': 'Manter este efeito e voltar à chamada',
  'callStudio.mode.face': 'Rosto',
  'callStudio.mode.categories': 'Categoria',
  'callStudio.mode.pickEffect': 'Escolher um efeito',
  'callStudio.mode.pickMontage': 'Escolher uma montagem',
  'callStudio.mode.settingsLabel': 'Mostrar ajustes (brilho, desfoque)',
} satisfies CallStudioCatalog;

export default pt;
