/**
 * L'APPEL AUDIO ET VIDÉO (#6382) — tranche du catalogue `catalog-it.ts`,
 * extraite pour tenir le budget de taille (CLAUDE.md) : le catalogue la
 * RÉPAND. Libellés repris d'iOS (`CallView.swift`, `IncomingCallView.swift`).
 */
const itCall = {
  'call.action.menu': 'Chiama',
  'call.action.audio': 'Chiamata vocale',
  'call.action.video': 'Videochiamata',
  'call.action.return': 'Torna alla chiamata',
  'call.incoming.title.audio': 'Chiamata in arrivo',
  'call.incoming.title.video': 'Videochiamata in arrivo',
  'call.incoming.title.tab': '📞 Chiamata in arrivo',
  'call.incoming.group': '{caller} sta chiamando il gruppo',
  'call.accept': 'Accetta',
  'call.accept.audioOnly': 'Rispondi senza video',
  'call.decline': 'Rifiuta',
  'call.outgoing.ringing': 'Chiamata in corso…',
  'call.outgoing.waiting': 'In attesa dell’altra persona…',
  'call.connecting': 'Connessione…',
  'call.reconnecting': 'Riconnessione…',
  'call.mic.mute': 'Disattiva microfono',
  'call.mic.unmute': 'Attiva microfono',
  'call.mic.muted': 'Microfono disattivato',
  'call.peer.muted': 'Contatto silenziato',
  'call.camera.on': 'Attiva fotocamera',
  'call.camera.off': 'Disattiva fotocamera',
  'call.camera.switch': 'Cambia fotocamera',
  'call.video.swap': 'Scambia i video',
  'call.camera.peerOff': 'Fotocamera disattivata',
  'call.video.connecting': 'Connessione video…',
  'call.hangup': 'Riaggancia',
  'call.minimize': 'Riduci chiamata',
  'call.expand': 'Torna alla chiamata',
  'call.captions.on': 'Mostra sottotitoli tradotti',
  'call.captions.off': 'Nascondi sottotitoli',
  'call.quality.poor': 'Connessione instabile',
  'call.ended.local': 'Chiamata terminata',
  'call.ended.remote': 'Chiamata terminata',
  'call.ended.rejected': 'Chiamata rifiutata',
  'call.ended.missed': 'Nessuna risposta',
  'call.ended.busy': 'Linea occupata',
  'call.ended.connectionLost': 'Connessione persa',
  'call.ended.failed': 'Chiamata non riuscita',
  'call.ended.refusedNonContacts': 'Questa persona accetta solo chiamate dai suoi contatti',
  'settings.privacy.calls_non_contacts': 'Chiamate da non contatti',
  'settings.privacy.calls_non_contacts.info': 'Se disattivato, solo i tuoi amici possono farti squillare. Gli altri vedono che accetti solo chiamate dai tuoi contatti.',
  'call.ended.permission': 'Consenti il microfono per chiamare',
  'call.retry': 'Riprova',
  'call.close': 'Chiudi',
  'call.waiting.from': '{caller} ti sta chiamando',
  'call.waiting.answer': 'Rispondi',
  'call.waiting.decline': 'Rifiuta',
  'call.notice.alreadyInCall': 'Una chiamata è già in corso',
  'callBackPrompt.audio': 'Richiamare {name}?',
  'callBackPrompt.video': 'Richiamare {name} in video?',
  'callBackPrompt.call': 'Chiama',
  'callBackPrompt.cancel': 'Annulla',
  'call.members': '{count} partecipanti',
  'call.a11y.screen': 'Chiamata con {name}',
  'call.bubble.callBack': 'Richiama',
  'call.bubble.join': 'Partecipa',
  'call.callBack.named': 'Richiama {name}',
  'call.you': 'Tu',
  'call.ended.removed': 'Sei stato rimosso dalla chiamata',
  'call.spotlight.show': 'Metti in evidenza {name}',
  'call.spotlight.back': 'Torna alla griglia',
  'call.remove.named': 'Rimuovi {name} dalla chiamata',
  'call.remove.failed': 'Impossibile rimuovere questo partecipante',
  'call.preview.soundOn': 'Attiva l’audio',
  'call.preview.soundOff': 'Disattiva l’audio',
  'call.preview.seenBy': '{name} ti vede prima di rispondere',
  'call.preview.heardBy': '{name} può sentirti prima di rispondere',
} as const;

export default itCall;
