import type { MessageCardCatalogSlice } from './catalog-fr-message-card';

/** Message export as image — see `catalog-fr-message-card.ts`. */
const esMessageCard = {
  'message.menu.export': 'Exportar como imagen',
  'export.card.title': 'Exportar como imagen',
  'export.card.popular': 'Populares',
  'export.card.random': 'Al azar',
  'export.card.palette': 'Colores',
  'export.card.typeface': 'Tipografía',
  'export.card.link': 'Enlace',
  'export.card.typeface.rond': 'Redonda',
  'export.card.typeface.didone': 'Didona',
  'export.card.typeface.plume': 'Pluma',
  'export.card.typeface.affiche': 'Cartel',
  'export.card.typeface.futur': 'Futurista',
  'export.card.typeface.machine': 'Máquina de escribir',
  'export.card.typeface.marqueur': 'Rotulador',
  'export.card.typeface.systeme': 'Sistema',
  'export.card.link.orbite': 'Órbita',
  'export.card.link.filet': 'Filete',
  'export.card.link.guillemets': 'Comillas',
  'export.card.link.fleche': 'Flecha',
  'export.card.link.bulles': 'Burbujas',
  'export.card.link.fil': 'Hilo',
  'export.card.link.silence': 'Silencio',
  'export.card.option.anonymizeQuoted': 'Anonimizar el mensaje citado',
  'export.card.option.anonymizeReply': 'Anonimizar la respuesta',
  'export.card.anonymous': 'Anónimo',
  'export.card.preview': 'Vista previa de la imagen',
  'export.card.rendering': 'Preparando la imagen…',
  'export.card.save': 'Guardar',
  'export.card.share': 'Compartir',
  'export.card.language': 'Idioma del mensaje',
  'export.card.language.asRead': 'Como lo leo',
  'export.card.truncated': 'Mensaje largo: el final se corta en la imagen.',
  'export.announce.gallery': 'Imagen guardada en la galería',
  'export.announce.shared': 'Imagen lista',
  'export.announce.cancelled': 'Exportación cancelada',
  'export.announce.expired': 'Toca de nuevo para guardar',
  'export.announce.failed': 'No se pudo crear la imagen',
  'export.announce.unavailable': 'Este dispositivo no puede guardar la imagen',
  'message.menu.exportQuick': 'Exportación rápida',
  'export.card.options': 'Mostrar',
  'export.card.option.title': 'Título de la conversación',
  'export.card.option.authors': 'Nombres de los autores',
  'export.card.option.date': 'Fecha',
  'export.card.default.save': 'Usar como formato predeterminado',
  'export.card.default.current': 'Formato predeterminado',
  'export.announce.defaultSaved': 'Formato predeterminado guardado',
} satisfies MessageCardCatalogSlice;

export default esMessageCard;
