import type { UserProfileCatalogSlice } from './catalog-fr-user-profile';

/** Le profil public de quelqu'un (#7083, #9063) — voir `catalog-fr-user-profile.ts`. */
const esUserProfile = {
  'userProfile.self.edit': 'Editar mi perfil',
  'userProfile.title': 'Perfil',
  'userProfile.loading': 'Cargando el perfil',
  'userProfile.section.publications': 'PUBLICACIONES',
  'userProfile.section.relation': 'CONEXIÓN',
  'userProfile.section.conversations': 'CONVERSACIONES',
  'userProfile.conversations.empty': 'Ninguna conversación en común',
  'userProfile.conversations.emptyBody': 'Todavía nada os une: «Escribir» abre la primera.',
  'userProfile.conversations.error': 'No se pudieron cargar las conversaciones',
  'userProfile.conversations.loading': 'Cargando las conversaciones',
  'userProfile.refused.title': 'Este perfil no está disponible',
  'userProfile.refused.body': 'No existe, o no tienes acceso.',
  'userProfile.throttled.title': 'Demasiadas solicitudes',
  'userProfile.throttled.body': 'Inténtalo de nuevo en un momento.',
  'userProfile.error.title': 'No se pudo cargar este perfil',
  'userProfile.error.body': 'Inténtalo de nuevo en un momento.',
  'userProfile.offline.body': 'El perfil aparecerá al volver a conectarte.',
  'userProfile.posts.empty': 'Sin publicaciones',
  'userProfile.posts.emptyBody': 'Todavía no hay nada público que leer.',
  'userProfile.posts.emptyPosts': 'Ninguna publicación aquí',
  'userProfile.posts.emptyReels': 'Ningún reel aquí',
  'userProfile.posts.emptyFilter': 'Toca de nuevo la casilla para volver a verlo todo.',
  'userProfile.posts.error': 'No se pudieron cargar las publicaciones',
  'userProfile.posts.loadMore': 'Cargar más',
  'userProfile.posts.loaded': 'Publicaciones añadidas: {count}',
  'userProfile.posts.loadedNone': 'No hay más publicaciones que mostrar',
  'userProfile.posts.loading': 'Cargando…',
  'userProfile.stat.posts': 'Publicaciones',
  'userProfile.stat.reels': 'Reels',
  'userProfile.stat.stories': 'Historias',
  'userProfile.stat.filterLabel': 'Filtrar por {name}',
  'userProfile.stat.filterClear': 'Mostrar todo',
  'userProfile.context.received': '{name} quiere conectar contigo. Acepta para intercambiar mensajes.',
  'userProfile.context.sent': 'Enviaste una solicitud de conexión a {name}. A la espera de su respuesta.',
  'userProfile.action.write': 'Escribir',
  'userProfile.action.writeLabel': 'Escribir a {name}',
  'userProfile.action.block': 'Bloquear',
  'userProfile.action.blockLabel': 'Bloquear a {name}',
  'userProfile.blocked.title': 'Has bloqueado a esta persona',
  'userProfile.blocked.body': 'Sus publicaciones y estadísticas quedan ocultas mientras dure el bloqueo.',
  'userProfile.signin.title': 'Inicia sesión para conectar',
  'userProfile.signin.body': 'Las solicitudes de conexión y los mensajes requieren una cuenta.',
  'userProfile.signin.cta': 'Iniciar sesión',
  'userProfile.announce.blocked': 'Persona bloqueada',
  'userProfile.announce.blockFailed': 'No se pudo bloquear',
  'userProfile.announce.writeFailed': 'No se pudo abrir la conversación',
  'userProfile.presence.online': 'En línea',
  'userProfile.presence.seen': 'Visto {ago}',
  'userProfile.presence.yesterdayAt': 'Visto ayer a las {time}',
  'userProfile.presence.beforeYesterdayAt': 'Visto anteayer a las {time}',
  'userProfile.presence.dateAt': 'Visto el {date} a las {time}',
} satisfies UserProfileCatalogSlice;

export default esUserProfile;
