import type { GameBannerCatalog } from '@/lib/i18n-game-catalog';

/** LE BANDEAU DU JOUEUR (#9542) — les seules clés que le bandeau des hubs lit (`player-banner.tsx`, `lib/view/player-banner.ts`) : ses phrases, les noms de palier, de rang et de ligue, les accords de points, de jours et de Meeshes. Chargé SEUL par le bandeau, et avec chaque écran du jeu. Mêmes clés et mêmes paramètres que le français. */
const ar = {
  'game.points.one': '{count} نقطة',
  'game.points.other': '{count} نقطة',
  'game.days.one': '{count} يوم',
  'game.days.other': '{count} يومًا',
  'game.meeshes.none': 'لا Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meesh',
  'game.tier.etincelle': 'شرارة',
  'game.tier.lueur': 'وميض',
  'game.tier.lumiere': 'نور',
  'game.tier.eclat': 'بريق',
  'game.tier.rayon': 'شعاع',
  'game.tier.aurore': 'فجر',
  'game.tier.comete': 'مذنّب',
  'game.tier.etoile': 'نجمة',
  'game.tier.constellation': 'كوكبة',
  'game.tier.galaxie': 'مجرّة',
  'game.tier.nebuleuse': 'سديم',
  'game.tier.pulsar': 'نجم نابض',
  'game.tier.quasar': 'كوازار',
  'game.tier.supernova': 'مستعر أعظم',
  'game.tier.magnetar': 'ماغنيتار',
  'game.tier.amas': 'عنقود',
  'game.tier.superamas': 'عنقود فائق',
  'game.tier.cosmos': 'الكون',
  'game.tier.infini': 'اللانهاية',
  'game.tier.singularite': 'التفرد',
  'game.rank.murmure': 'همس',
  'game.rank.echo': 'صدى',
  'game.rank.voix': 'صوت',
  'game.rank.conteur': 'حكّاء',
  'game.rank.passeur': 'جسّار',
  'game.rank.polyglotte': 'متعدّد اللغات',
  'game.rank.ambassadeur': 'سفير',
  'game.rank.orateur': 'خطيب',
  'game.rank.oracle': 'عرّاف',
  'game.rank.legende': 'أسطورة',
  'game.rank.mythe': 'خرافة',
  'game.rank.mythe_seat': 'خرافة رقم {number}',
  'game.points.two': 'نقطتان',
  'game.points.few': '{count} نقاط',
  'game.days.two': 'يومان',
  'game.days.few': '{count} أيام',
  'game.banner.level': 'المستوى {level}',
  'game.banner.to_next': '{percent}٪ نحو المستوى {level}',
  'game.banner.top': 'في القمة',
  'game.banner.capped': '{rank} تفتح المزيد',
  'game.banner.league': 'دوري {league} {place}',
  'game.banner.flame': 'اللهب {days}',
  'game.banner.place.one': 'المركز {count}',
  'game.banner.place.other': 'المركز {count}',
  'game.banner.points': '{points} نقطة',
  'game.banner.missing': 'باقٍ {points}',
  'game.banner.separator': '، ',
  'game.league.name.quartz': 'كوارتز',
  'game.league.name.ambre': 'عنبر',
  'game.league.name.jade': 'يشم',
  'game.league.name.saphir': 'ياقوت أزرق',
  'game.league.name.rubis': 'ياقوت أحمر',
  'game.league.name.amethyste': 'جمشت',
  'game.league.name.diamant': 'ألماس',
  'game.league.name.prisme': 'منشور',
} as const satisfies GameBannerCatalog;

export default ar;
