import type { GameCatalog } from '@/lib/i18n-game-catalog';

/** Le catalogue du jeu, es (#9379) — mêmes clés et mêmes paramètres que le français ; textes de l'app iOS quand elle les porte. */
const es = {
  'game.points.one': '{count} punto',
  'game.points.other': '{count} puntos',
  'game.points.convertible.one': '{count} punto convertible',
  'game.points.convertible.other': '{count} puntos convertibles',
  'game.days.one': '{count} día',
  'game.days.other': '{count} días',
  'game.actions.one': '{count} acción',
  'game.actions.other': '{count} acciones',
  'game.levels.one': '{count} nivel',
  'game.levels.other': '{count} niveles',
  'game.meeshes.none': 'Ninguna Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meeshes',
  'game.mint.badges.one': '{count} insignia baja',
  'game.mint.badges.other': '{count} insignias bajan',
  'game.mint.badges.none': 'Ninguna insignia se apaga',
  'game.tier.etincelle': 'Chispa',
  'game.tier.lueur': 'Destello',
  'game.tier.lumiere': 'Luz',
  'game.tier.eclat': 'Brillo',
  'game.tier.rayon': 'Rayo',
  'game.tier.aurore': 'Aurora',
  'game.tier.comete': 'Cometa',
  'game.tier.etoile': 'Estrella',
  'game.tier.constellation': 'Constelación',
  'game.tier.galaxie': 'Galaxia',
  'game.rank.murmure': 'Murmullo',
  'game.rank.echo': 'Eco',
  'game.rank.voix': 'Voz',
  'game.rank.conteur': 'Narrador',
  'game.rank.passeur': 'Pasador',
  'game.rank.polyglotte': 'Políglota',
  'game.rank.ambassadeur': 'Embajador',
  'game.rank.orateur': 'Orador',
  'game.rank.oracle': 'Oráculo',
  'game.rank.legende': 'Leyenda',
  'game.rank.mythe': 'Mito',
  'game.treasury.bourse': 'Monedero',
  'game.treasury.escarcelle': 'Escarcela',
  'game.treasury.coffret': 'Cofrecillo',
  'game.treasury.coffre': 'Cofre',
  'game.treasury.tresor': 'Tesoro',
  'game.treasury.reserve': 'Reserva',
  'game.flame.form.braise': 'Brasa',
  'game.flame.form.flamme': 'Llama',
  'game.flame.form.brasier': 'Hoguera',
  'game.flame.form.astre': 'Astro',
  'game.flame.form.soleil': 'Sol',
  'game.edition.silver': 'plata',
  'game.edition.gold': 'oro',
  'game.edition.prism': 'prisma',
  'game.difficulty.easy': 'Fácil',
  'game.difficulty.medium': 'Media',
  'game.difficulty.hard': 'Difícil',
  'game.difficulty.gold': 'Oro',
  'game.mission.react_messages.one': 'Reaccionar a {count} mensaje',
  'game.mission.react_messages.other': 'Reaccionar a {count} mensajes',
  'game.mission.send_voice.one': 'Enviar un mensaje de voz',
  'game.mission.send_voice.other': 'Enviar {count} mensajes de voz',
  'game.mission.send_texts.one': 'Enviar {count} mensaje',
  'game.mission.send_texts.other': 'Enviar {count} mensajes',
  'game.mission.use_stickers.one': 'Enviar un sticker',
  'game.mission.use_stickers.other': 'Enviar {count} stickers',
  'game.mission.send_attachments.one': 'Enviar un archivo adjunto',
  'game.mission.send_attachments.other': 'Enviar {count} archivos adjuntos',
  'game.mission.comment_text.one': 'Escribir un comentario',
  'game.mission.comment_text.other': 'Escribir {count} comentarios',
  'game.mission.publish_story.one': 'Publicar una story',
  'game.mission.publish_story.other': 'Publicar {count} stories',
  'game.mission.publish_post.one': 'Publicar un post',
  'game.mission.publish_post.other': 'Publicar {count} posts',
  'game.mission.share_link.one': 'Compartir un enlace',
  'game.mission.share_link.other': 'Compartir {count} enlaces',
  'game.mission.prism_foreign_messages.one': 'Escribir un mensaje en un idioma distinto al tuyo',
  'game.mission.prism_foreign_messages.other': 'Escribir {count} mensajes en un idioma distinto al tuyo',
  'game.mission.voice_comments.one': 'Dejar un comentario de voz',
  'game.mission.voice_comments.other': 'Dejar {count} comentarios de voz',
  'game.mission.publish_reel.one': 'Publicar un reel',
  'game.mission.publish_reel.other': 'Publicar {count} reels',
  'game.mission.reply_conversations': 'Responder en {count} conversaciones distintas',
  'game.mission.prism_foreign_exchange': 'Escribir {count} mensajes en un idioma distinto al tuyo',
  'game.mission.long_chat': 'Enviar {count} mensajes',
  'game.mission.gold_replies_received': 'Recibir respuestas de {count} personas distintas',
  'game.mission.generic': 'Misión del día',
  'game.error.insufficient_points': 'No tienes puntos convertibles suficientes para acuñar una Meesh.',
  'game.error.insufficient_meeshes': 'Necesitas una Meesh más para eso.',
  'game.error.freeze_at_maximum': 'Ya tienes dos congelaciones en reserva: es el máximo.',
  'game.error.relight_not_allowed': 'La Llama no se puede volver a encender ahora.',
  'game.error.mission_not_found': 'Esta misión ya no existe: la pantalla se actualiza.',
  'game.error.mission_reroll_exhausted': 'Ya has cambiado una misión hoy.',
  'game.error.mission_reroll_unavailable': 'Esta misión no se puede cambiar.',
  'game.error.missions_locked': 'Las misiones se abren en el nivel 5.',
  'game.error.chest_not_ready': 'Termina primero las misiones del día para abrir el cofre.',
  'game.error.generic': 'No ha salido bien: revisa tu conexión e inténtalo de nuevo.',
  'game.chest.chance': '1 posibilidad entre {odds}',
  'game.chest.reward.fragment': 'Un fragmento de Meesh',
  'game.chest.reward.freeze': 'Una congelación de Llama',
  'game.flame_panel.title': 'Proteger la Llama',
  'game.flame_panel.bonus': '+{perDay} % por día de racha en las recompensas de misión, hasta\u00a0+{max} %.',
  'game.flame_panel.freezes': 'Congelaciones en reserva: {held} / {max}',
  'game.flame_panel.offline': 'Sin conexión: las congelaciones y el reencendido se reanudarán con la conexión.',
  'game.flame_panel.freeze_full': 'Reserva llena: una congelación cubre un día perdido, no necesitas otra.',
  'game.flame_panel.freeze_buy': 'Comprar una congelación · {price}',
  'game.flame_panel.freeze_missing': 'Necesitas {missing} para una congelación.',
  'game.flame_panel.relight_intro': 'Tu Llama se apagó: vuelve a encenderla ahora, continúa donde se quedó.',
  'game.flame_panel.relight': 'Volver a encender la Llama · {price}',
  'game.flame_panel.relight_missing': 'Necesitas {missing} para volver a encenderla.',
  'game.flame_panel.relight_missing_window': 'Necesitas {missing} para volver a encenderla, si se apagó hace menos de 48 h.',
  'game.flame_panel.relight_closed': 'Esta Llama ya no se puede volver a encender. Una nueva Llama empieza con tu próximo gesto.',
  'game.gauge.level': 'Nivel',
  'game.level.title': 'Nivel {level} · {tier}',
  'game.level.top': 'Estás en la cima.',
  'game.level.to_next': 'Faltan {points} para el nivel {level}',
  'game.level.record': 'Récord: nivel {level}',
  'game.level.tailwind': ' · Viento de cola ×{factor}',
  'game.gauge.rank': 'Rango',
  'game.rank.glory': 'Gloria {glory}',
  'game.rank.top': 'El rango más alto',
  'game.rank.next': 'Faltan {missing} de Gloria para {rank}',
  'game.gauge.treasury': 'Tesoro',
  'game.treasury.hint': 'Guarda tus Meeshes: llenan tu tesoro',
  'game.treasury.next': 'Faltan {missing} para {tier}',
  'game.gauge.flame': 'Llama',
  'game.flame.no_streak': 'Sin racha',
  'game.flame.form_line': '{form} ·\u00a0+{bonus} % en misiones',
  'game.flame.out_line': 'Llama apagada',
  'game.flame.status.none': 'Un gesto hoy enciende tu Llama',
  'game.flame.status.at_risk': 'Haz un gesto antes de medianoche',
  'game.flame.status.covered': 'Una congelación la protege',
  'game.flame.status.out': 'Apagada',
  'game.guide.speaker.mee': 'Mee',
  'game.guide.speaker.meo': 'Meo',
  'game.guide.speaker.duo': 'Mee y Meo',
  'game.guide.step_of': 'Paso {index} de {total}',
  'game.guide.more': 'Ver la explicación completa',
  'game.guide.dismiss': 'Más tarde',
  'game.guide.skip': 'Saltar',
  'game.guide.photo': 'Inmortalizar este momento',
  'game.guide.skip_all': 'Saltar la introducción',
  'game.guide.action.start_game': 'Empezar el juego',
  'game.guide.action.earn_first_points': 'Hacer mi primer gesto',
  'game.guide.action.see_level': 'Ver mi nivel',
  'game.guide.action.see_missions': 'Ver las misiones',
  'game.guide.action.see_flame': 'Ver mi Llama',
  'game.guide.action.see_meeshes': 'Ver las Meeshes',
  'game.guide.action.see_rank': 'Ver mi rango',
  'game.guide.action.take_start_photo': 'Hacer la foto de inicio',
  'game.guide.action.see_progress': 'Ver mi progreso',
  'game.guide.action.see_next_tier': 'Ver el siguiente tramo',
  'game.guide.action.open_first_mission': 'Abrir mi primera misión',
  'game.guide.action.mint_or_climb': 'Ver la vista previa de acuñación',
  'game.guide.action.regain_levels': 'Recuperar mis niveles',
  'game.guide.action.relight_badge': 'Ver mis insignias',
  'game.guide.action.see_mint_preview': 'Ver la vista previa de acuñación',
  'game.guide.action.take_photo': 'Inmortalizar este momento',
  'game.guide.action.keep_or_spend': 'Ver mi tesoro',
  'game.guide.action.do_easy_mission_or_freeze': 'Ver mis misiones',
  'game.guide.action.relight_flame': 'Volver a encender la Llama',
  'game.guide.action.do_easiest_mission': 'Ver la misión más fácil',
  'game.guide.action.prestige_or_stay': 'Ver mi nivel',
  'game.guide.moment.first_level.what': 'Has ganado tu primer nivel.',
  'game.guide.moment.first_level.means': 'Tus puntos llenan el anillo: cuando está lleno, subes de nivel.',
  'game.guide.moment.first_level.next': 'Faltan {points} para el nivel {level}.',
  'game.guide.moment.first_level.short': 'Nivel {level}: faltan {points} para el siguiente.',
  'game.guide.moment.new_tier.what': '¡Entras en {tier}!',
  'game.guide.moment.new_tier.means': 'Los tramos jalonan tu camino: diez niveles cada uno.',
  'game.guide.moment.new_tier.next': 'El siguiente tramo se abre en el nivel {level}.',
  'game.guide.moment.new_tier.next_last': 'Estás en el último tramo.',
  'game.guide.moment.new_tier.short': 'Tramo {tier} alcanzado.',
  'game.guide.moment.missions_unlocked.what': 'Las misiones están desbloqueadas.',
  'game.guide.moment.missions_unlocked.means': 'Tres misiones al día, y un cofre que abrir cuando las completes.',
  'game.guide.moment.missions_unlocked.next': 'Abre tu primera misión.',
  'game.guide.moment.missions_unlocked.short': 'Tus misiones del día te esperan.',
  'game.guide.moment.first_mint_possible.what': 'Puedes acuñar tu primera Meesh.',
  'game.guide.moment.first_mint_possible.means_free': 'Acuñar cuesta {price}, sin perder ningún nivel, y da\u00a0+{glory} de Gloria.',
  'game.guide.moment.first_mint_possible.means': 'Acuñar cuesta {price}, es decir {levels}, y da\u00a0+{glory} de Gloria.',
  'game.guide.moment.first_mint_possible.next': 'Acuña ahora, o sube primero.',
  'game.guide.moment.first_mint_possible.short': 'Una Meesh se acuña por {price}.',
  'game.guide.moment.first_mint.what': '¡Clac! Tu primera Meesh está acuñada.',
  'game.guide.moment.first_mint.means': 'Tu nivel pasó de {from} a {to}: es la regla. El Viento de cola está activo.',
  'game.guide.moment.first_mint.next': 'Recupera tus niveles más rápido: tus puntos valen un 25 % más hasta el nivel {level}.',
  'game.guide.moment.first_mint.short': 'Nivel {from} → {to}. El Viento de cola te ayuda hasta el nivel {level}.',
  'game.guide.moment.badge_extinguished.what': 'Una insignia se ha apagado.',
  'game.guide.moment.badge_extinguished.means': 'Se ha convertido en una huella: nada se pierde para siempre.',
  'game.guide.moment.badge_extinguished.next': 'Faltan {actions} para volver a encenderla.',
  'game.guide.moment.badge_extinguished.short': 'Una insignia se apagó: {actions} para volver a encenderla.',
  'game.guide.moment.price_rises.what': 'Las Meeshes se vuelven más escasas.',
  'game.guide.moment.price_rises.means': 'Cuantas más acuñas, más cuesta la siguiente.',
  'game.guide.moment.price_rises.next': 'La siguiente cuesta {price}.',
  'game.guide.moment.price_rises.short': 'La siguiente Meesh cuesta {price}.',
  'game.guide.moment.new_rank.what': 'Nuevo rango: {rank}.',
  'game.guide.moment.new_rank.means': 'Tu Gloria ha pasado un umbral, y nunca baja.',
  'game.guide.moment.new_rank.next': 'Faltan {glory} de Gloria para la siguiente división. Inmortaliza este momento.',
  'game.guide.moment.new_rank.next_top': 'Es el rango más alto. Inmortaliza este momento.',
  'game.guide.moment.new_rank.short': 'Eres {rank}.',
  'game.guide.moment.treasury_tier.what': 'Tu tesoro alcanza el nivel {tier}.',
  'game.guide.moment.treasury_tier.means': 'Tu tesoro es visible en tu perfil.',
  'game.guide.moment.treasury_tier.next': 'Guarda {meeshes} más para el siguiente tramo, o gasta.',
  'game.guide.moment.treasury_tier.next_top': 'Guárdalo, o gasta tus Meeshes.',
  'game.guide.moment.treasury_tier.short': 'Tesoro: tramo {tier}.',
  'game.guide.moment.flame_at_risk.what': 'Tu Llama está en peligro.',
  'game.guide.moment.flame_at_risk.means': 'Se apaga a medianoche si no haces nada: {days} de racha que salvar.',
  'game.guide.moment.flame_at_risk.next': 'Haz una misión fácil, o compra una congelación.',
  'game.guide.moment.flame_at_risk.short': 'Tu Llama se apaga a medianoche: basta un gesto.',
  'game.guide.moment.flame_out.what': 'Tu Llama se ha apagado.',
  'game.guide.moment.flame_out.means': 'El Bonus de Llama vuelve a cero.',
  'game.guide.moment.flame_out.next': 'Vuelve a encenderla en 48 h por {price}.',
  'game.guide.moment.flame_out.next_new': 'Tu próximo gesto enciende una nueva.',
  'game.guide.moment.flame_out.short': 'Llama apagada: vuelve a encenderla por {price}.',
  'game.guide.moment.flame_out.short_new': 'Llama apagada: un nuevo gesto la enciende.',
  'game.guide.moment.return_after_absence.what': '¡Qué bueno verte de nuevo!',
  'game.guide.moment.return_after_absence.means': 'Estuviste fuera {days}: tu rango, tu tesoro y tu Gloria siguen donde los dejaste.',
  'game.guide.moment.return_after_absence.next': 'Empieza por la misión más fácil del día.',
  'game.guide.moment.return_after_absence.short': 'Bienvenido de nuevo: empieza por la misión más fácil.',
  'game.guide.moment.level_100.what': 'Nivel 100: ¡estás en la cima!',
  'game.guide.moment.level_100.means': 'El Prestigio devuelve tu nivel a 1 y te da una estrella y un trofeo.',
  'game.guide.moment.level_100.next': 'Pasa a Prestigio, o quédate en la cima.',
  'game.guide.moment.level_100.next_stay': 'Quédate en la cima el tiempo que quieras.',
  'game.guide.moment.level_100.short': 'Estás en la cima.',
  'game.guide.step.welcome.what': '¡Hola, soy Mee! Con Meo te explicamos el juego en siete tarjetas.',
  'game.guide.step.welcome.means': 'Cada gesto útil da puntos: escribir, hablar, publicar, reaccionar, invitar.',
  'game.guide.step.welcome.next': 'Haz tu primer gesto, yo cuento tus puntos.',
  'game.guide.step.first_points.what': '¡Bravo, tus primeros puntos!',
  'game.guide.step.first_points.means': 'Los puntos hacen el nivel: llenan tu anillo.',
  'game.guide.step.first_points.next': 'Mira cómo se llena tu anillo.',
  'game.guide.step.levels.what': 'Cien niveles, diez tramos.',
  'game.guide.step.levels.means': 'Cada nivel pide un poco más de puntos que el anterior.',
  'game.guide.step.levels.next': 'Las misiones se abren en el nivel 5.',
  'game.guide.step.missions.what': 'Cada día, tres misiones y un cofre.',
  'game.guide.step.missions.means': 'Hazlas para abrir el cofre y alimentar tu Llama.',
  'game.guide.step.missions.next': 'Una Llama crece mientras vuelvas.',
  'game.guide.step.flame.what': 'Tu Llama crece cada día que actúas.',
  'game.guide.step.flame.means': 'Cada día de racha suma un 2 % a tus recompensas de misión, hasta un 50 %. Una congelación cubre un día perdido.',
  'game.guide.step.flame.next': 'Tus puntos pueden convertirse en Meeshes.',
  'game.guide.step.mint.what': 'A partir de 1.221 puntos, se acuña una Meesh.',
  'game.guide.step.mint.means': 'Los puntos gastados salen de tu nivel, pero tu rango nunca baja: cada acuñación suma Gloria.',
  'game.guide.step.mint.next': 'La Gloria da el rango.',
  'game.guide.step.rank.what': 'Tu rango nunca baja.',
  'game.guide.step.rank.means': 'Acuñar, batir récords, conseguir logros: todo suma Gloria.',
  'game.guide.step.rank.next': 'Inmortalicemos tu inicio con una foto.',
  'game.rules.1.title': 'Cada gesto cuenta',
  'game.rules.1.body': 'Escribir, hablar, publicar, reaccionar, invitar: cada acción útil da puntos.',
  'game.rules.2.title': 'Los puntos hacen el nivel',
  'game.rules.2.body': '100 niveles en 10 tramos. Cada nivel pide un poco más que el anterior.',
  'game.rules.3.title': 'Se acuñan Meeshes',
  'game.rules.3.body': 'A partir de 1.221 puntos, se acuña una Meesh a mano. El precio sube con el número de Meeshes ya acuñadas.',
  'game.rules.4.title': 'Acuñar hace bajar',
  'game.rules.4.body': 'Los puntos gastados salen del nivel. Las insignias que sostenían pueden apagarse.',
  'game.rules.5.title': 'Tu rango nunca baja',
  'game.rules.5.body': 'Cada acuñación, cada récord, cada logro suma Gloria. La Gloria da el rango.',
  'game.rules.6.title': 'El tesoro se guarda o se gasta',
  'game.rules.6.body': 'Guardar tus Meeshes hace crecer el tesoro. Gastarlas protege la Llama u ofrece cosméticos.',
  'game.rules.7.title': 'Cada día cuenta',
  'game.rules.7.body': 'Tres misiones, un cofre, una Llama que crece mientras vuelvas.',
  'game.rules.8.title': 'Se guarda un recuerdo',
  'game.rules.8.body': 'Cada gran momento se fotografía con Mee y Meo en el cuaderno de progreso.',
  'game.rules.page_title': 'Cómo funciona',
  'game.rules.intro': 'Ocho reglas, y todo el juego cabe en ellas. Meo las explica, Mee te muestra el gesto.',
  'game.rules.section_rules': 'Las reglas en una página',
  'game.rules.section_steps': 'Los siete pasos',
  'game.page.back': 'Volver al progreso',
  'game.door.rules': 'Cómo funciona',
  'game.door.notebook': 'Cuaderno de progreso',
  'game.mint.minted_line': 'Meesh n.º {number} acuñada, {edition}.',
  'game.mint.action': 'Acuñar con Mee y Meo',
  'game.mint.minting': 'Acuñando…',
  'game.mint.offline': 'Sin conexión: la acuñación se reanudará con la conexión.',
  'game.mint.missing': 'Faltan {missing} para la próxima Meesh: cuesta {price}.',
  'game.mint.next_title': 'Próxima Meesh · n.º {number}',
  'game.mint.next_subtitle': 'Edición {edition} · {price}',
  'game.mint.row.price': 'Precio',
  'game.mint.row.level': 'Nivel',
  'game.mint.row.treasury': 'Tesoro',
  'game.mint.row.glory': 'Gloria',
  'game.mint.row.badges': 'Insignias',
  'game.mint.row.tailwind': 'Viento de cola',
  'game.mint.tailwind_value': '+25 % en tus puntos hasta el nivel {level}',
  'game.missions.title': 'Misiones del día',
  'game.missions.locked': 'Las misiones se abren en el nivel 5: tres al día, y un cofre. Estás en el nivel {level}.',
  'game.missions.prism_day': 'Día del Prisma: una de las misiones se juega en un idioma distinto al tuyo.',
  'game.missions.prism_hour': 'Hora del Prisma: {start} – {end} — tus misiones cuentan doble.',
  'game.missions.offline': 'Sin conexión: cambiar una misión o abrir el cofre se reanudará con la conexión.',
  'game.mission.prism': 'Prisma',
  'game.mission.done': 'Hecha',
  'game.mission.reroll': 'Cambiar · 1 Meesh',
  'game.mission.reroll.a11y': 'Cambiar la misión «{title}» por 1 Meesh',
  'game.chest.title': 'Cofre del día',
  'game.chest.locked': 'Termina las misiones del día para abrirlo.',
  'game.chest.opening': 'Abriendo…',
  'game.chest.open': 'Abrir el cofre',
  'game.chest.claimed': 'Vuelve mañana para el siguiente.',
  'game.chest.odds': '{min} a {max} · {fragment} de un fragmento · {freeze} de una congelación',
  'game.notebook.page_title': 'Cuaderno de progreso',
  'game.notebook.empty': 'Tu cuaderno está vacío. Los grandes momentos —un rango, una primera Meesh, una Llama de 7 días— se fotografían con Mee y Meo, y la foto se queda en tu dispositivo.',
  'game.notebook.pending': 'Pendientes',
  'game.notebook.kept': 'Fotos guardadas',
  'game.notebook.photo_a11y': 'Foto: {title}',
  'game.notebook.remove': 'Quitar',
  'game.photo.offer.start': 'Fotografiar',
  'game.photo.offer.title': '¿Lo inmortalizamos?',
  'game.photo.share': 'Compartir',
  'game.photo.a11y': 'Foto: {title}',
  'game.photo.close': 'Cerrar',
  'game.photo.selfie': 'Selfie con nosotros',
  'game.photo.card_only': 'Solo la tarjeta',
  'game.photo.later': 'Más tarde',
  'game.photo.gallery': 'Elegir una foto de la galería',
  'game.photo.shutter': 'Hacer la foto',
  'game.photo.camera.denied': 'La cámara está denegada. Permítela en los ajustes de tu dispositivo, o elige una foto de tu galería.',
  'game.photo.camera.unsupported': 'Este dispositivo no permite la cámara aquí. Elige una foto de tu galería, o quédate solo con la tarjeta.',
  'game.photo.camera.unavailable': 'La cámara no está disponible (¿la usa otra aplicación?). Elige una foto de tu galería, o quédate solo con la tarjeta.',
  'game.photo.striking': 'Mee y Meo acuñan el momento en la foto',
  'game.photo.preview': 'Vista previa: {title}',
  'game.photo.format.story': '9:16 · story',
  'game.photo.format.square': '1:1 · perfil',
  'game.photo.save': 'Guardar',
  'game.photo.kept': 'Guardada',
  'game.photo.keep': 'Guardar en el cuaderno',
  'game.photo.kicker.start': 'Primeros pasos',
  'game.photo.title.start': 'Mi comienzo en Meeshy',
  'game.photo.kicker.rank': 'Nuevo rango',
  'game.photo.kicker.tier': 'Nivel {level}',
  'game.photo.title.tier': 'Tramo {tier}',
  'game.photo.kicker.summit': 'En la cima',
  'game.photo.kicker.new_lap': 'Nueva vuelta',
  'game.photo.title.level_100': 'Nivel 100',
  'game.photo.title.prestige': 'Prestigio {count}',
  'game.photo.title.meesh_first': 'Mi primera Meesh',
  'game.photo.title.meesh_number': 'Meesh n.º {number}',
  'game.photo.title.meesh_number_edition': 'Meesh n.º {number} · {edition}',
  'game.photo.kicker.meesh': 'Meesh acuñada',
  'game.photo.kicker.treasury': 'Tesoro',
  'game.photo.kicker.flame': 'Llama',
  'game.photo.kicker.achievement': 'Logro desbloqueado',
  'game.photo.title.flame_days': '{count} días de Llama',
  'game.photo.notice.kept': 'Guardada en el cuaderno de progreso.',
  'game.photo.notice.keep_failed': 'El cuaderno no está disponible en este dispositivo: la foto no se guardó.',
  'game.photo.notice.save_failed': 'No se pudo guardar.',
  'game.photo.notice.shared': 'Imagen compartida.',
  'game.mission.glory': '+{glory} de Gloria',
  'game.guide.collapse': 'Replegar',
  'game.guide.collapse_a11y': 'Replegar la explicación',
  'game.guide.awaiting.missions': 'Haz la misión más fácil del día: te espero para seguir.',
  'game.guide.awaiting.flame': 'Vuelve mañana y haz un gesto: tu racha llegará a 2 días.',
  'game.photo.private': 'La foto se queda en tu dispositivo mientras no la compartas.',
  'game.photo.camera.opening': 'Abriendo la cámara…',
  'game.photo.gallery.unreadable': 'No se pudo leer esta imagen.',
  'game.photo.format.group': 'Formato de la imagen',
  'game.photo.notice.saved_file': 'Imagen guardada.',
  'game.photo.notice.share_failed': 'No se pudo compartir.',
  'game.photo.compose_unsupported': 'Este navegador no sabe componer la imagen. Tu momento sigue en tu progreso.',
  'game.notebook.pending_until': 'En espera hasta el {date}',
  'game.notebook.remove_confirm': 'Confirmar la retirada',
  'game.mint.number_label': 'N.º {number}',
  'game.chest.contents': 'Contenido del cofre',
  'game.fmt.signed': '+{value}',
  'game.fmt.minus': '−{value}',
  'game.fmt.fraction': '{done} / {total}',
  'game.fmt.from_to': '{from} → {to}',
  'game.error.request_id_conflict': 'Ese identificador de solicitud ya se usó en otra acción: inténtalo de nuevo, se enviará uno nuevo.',
  'game.level.ring_label': 'Nivel {level}, tramo {tier}, {ordinal}',
  'game.tier.ordinal.1': 'primer tramo',
  'game.tier.ordinal.2': 'segundo tramo',
  'game.tier.ordinal.3': 'tercer tramo',
  'game.tier.ordinal.4': 'cuarto tramo',
  'game.tier.ordinal.5': 'quinto tramo',
  'game.tier.ordinal.6': 'sexto tramo',
  'game.tier.ordinal.7': 'séptimo tramo',
  'game.tier.ordinal.8': 'octavo tramo',
  'game.tier.ordinal.9': 'noveno tramo',
  'game.tier.ordinal.10': 'décimo tramo',
  'game.material.copper': 'Cobre',
  'game.material.bronze': 'Bronce',
  'game.material.silver': 'Plata',
  'game.material.gold': 'Oro',
  'game.material.platinum': 'Platino',
  'game.material.obsidian': 'Obsidiana',
  'game.material.prism': 'Prisma',
  'game.medal.label': '{axis}, {material}, {value} de {next} hacia {nextMaterial}',
  'game.medal.label_top': '{axis}, {material}, {value}',
  'game.medal.label_off': '{axis}, aún sin conseguir, faltan {missing}',
  'game.family.content': 'Contenido',
  'game.family.comment': 'Comentarios',
  'game.family.conversation': 'Conversaciones',
  'game.family.tool': 'Herramientas',
  'game.family.social': 'Vínculos',
  'game.hero.earn_title': 'Cómo ganar puntos',
  'game.hero.earn_chip': '{family} +{points}',
  'game.hero.earn_chip_a11y': '{family}: {points} por gesto. Ver las reglas.',
  'game.hero.mint_title': 'Cómo acuñar',
  'game.hero.mint_price': '{price} → una Meesh',
  'game.hero.mint_cost': 'cuesta {levels}',
  'game.hero.mint_glory': '+{glory} de Gloria',
  'game.hero.mint_missing': 'Faltan {missing}',
  'game.hero.mee_idle': '¿Una duda? Tócame, te lo explico.',
  'game.photo.referral.headline': 'Únete a mí en Meeshy',
  'game.photo.referral.share_text': 'Únete a mí en Meeshy: {link}',
  'game.photo.referral.flame_days': '{days} d',
} as const satisfies GameCatalog;

export default es;
