/**
 * L'APPEL AUDIO ET VIDÉO (#6382) — tranche du catalogue `catalog-es.ts`,
 * extraite pour tenir le budget de taille (CLAUDE.md) : le catalogue la
 * RÉPAND. Libellés repris d'iOS (`CallView.swift`, `IncomingCallView.swift`).
 */
const esCall = {
  'call.action.menu': 'Llamar',
  'call.action.audio': 'Llamada de voz',
  'call.action.video': 'Videollamada',
  'call.action.return': 'Volver a la llamada',
  'call.incoming.title.audio': 'Llamada entrante',
  'call.incoming.title.video': 'Videollamada entrante',
  'call.incoming.title.tab': '📞 Llamada entrante',
  'call.incoming.group': '{caller} está llamando al grupo',
  'call.accept': 'Aceptar',
  'call.accept.audioOnly': 'Responder sin vídeo',
  'call.decline': 'Rechazar',
  'call.outgoing.ringing': 'Llamando…',
  'call.outgoing.waiting': 'Esperando a la otra persona…',
  'call.connecting': 'Conectando…',
  'call.reconnecting': 'Reconectando…',
  'call.mic.mute': 'Silenciar micrófono',
  'call.mic.unmute': 'Activar micrófono',
  'call.mic.muted': 'Micrófono silenciado',
  'call.peer.muted': 'Contacto silenciado',
  'call.camera.on': 'Activar cámara',
  'call.camera.off': 'Desactivar cámara',
  'call.camera.switch': 'Cambiar de cámara',
  'call.video.swap': 'Intercambiar vídeos',
  'call.camera.peerOff': 'Cámara desactivada',
  'call.video.connecting': 'Conectando vídeo…',
  'call.hangup': 'Colgar',
  'call.minimize': 'Minimizar llamada',
  'call.expand': 'Volver a la llamada',
  'call.captions.on': 'Mostrar subtítulos',
  'call.captions.off': 'Ocultar subtítulos',
  'call.quality.poor': 'Conexión inestable',
  'call.ended.local': 'Llamada finalizada',
  'call.ended.remote': 'Llamada finalizada',
  'call.ended.rejected': 'Llamada rechazada',
  'call.ended.missed': 'Sin respuesta',
  'call.ended.busy': 'Línea ocupada',
  'call.ended.connectionLost': 'Conexión perdida',
  'call.ended.failed': 'La llamada falló',
  'call.ended.permission': 'Permite el micrófono para llamar',
  'call.retry': 'Reintentar',
  'call.close': 'Cerrar',
  'call.waiting.from': '{caller} te está llamando',
  'call.waiting.answer': 'Responder',
  'call.waiting.decline': 'Rechazar',
  'call.notice.alreadyInCall': 'Ya hay una llamada en curso',
  'call.members': '{count} participantes',
  'call.a11y.screen': 'Llamada con {name}',
  'call.bubble.callBack': 'Devolver llamada',
  'call.bubble.join': 'Unirse',
  'call.callBack.named': 'Devolver la llamada a {name}',
  'call.you': 'Tú',
} as const;

export default esCall;
