import type { AdminInterfaceCatalog } from '@/lib/i18n-admin-catalog';

const pt = {
  'admin.role': 'O seu papel: {role}',
  'admin.denied.title': 'Área reservada',
  'admin.denied.message': 'Esta área exige uma permissão de administração.',
  'admin.counters.title': 'Num relance',
  'admin.counters.unavailable': 'Contadores indisponíveis de momento.',
  'admin.counters.users': 'Contas',
  'admin.counters.activeUsers': 'Contas ativas',
  'admin.counters.messages': 'Mensagens',
  'admin.counters.communities': 'Comunidades',
  'admin.counters.reports': 'Denúncias',
  'admin.counters.newUsers': 'Novas (24 h)',
  'admin.sections.title': 'Secções',
  'admin.nav.dashboard': 'Painel',
  'admin.nav.users': 'Contas',
  'admin.nav.moderation': 'Moderação',
  'admin.nav.audit': 'Registos de auditoria',
  'admin.nav.analytics': 'Estatísticas',
  'admin.nav.trackingLinks': 'Ligações de seguimento',
  'admin.nav.ranking': 'Classificação',
  'admin.nav.broadcasts': 'Difusões',
  'admin.nav.settings': 'Definições',
  'admin.nav.agent': 'Agente',
  'admin.nav.monitoring': 'Supervisão',
  'admin.nav.engagementScale': 'Tabela de pontos',
  'admin.scale.title': 'Tabela de pontos',
  'admin.scale.denied': 'Esta configuração é reservada aos administradores.',
  'admin.scale.loadFailed': 'Não foi possível carregar a tabela.',
  'admin.scale.retry': 'Tentar novamente',
  'admin.scale.updated': 'Definida em {date} por {by}',
  'admin.scale.defaults': 'Tabela padrão — nunca definida.',
  'admin.scale.operations.title': 'Operações',
  'admin.scale.col.operation': 'Operação',
  'admin.scale.col.points': 'Pontos',
  'admin.scale.col.multiplied': 'Multiplicado',
  'admin.scale.col.cap': 'Limite',
  'admin.scale.col.frequency': 'Frequência',
  'admin.scale.cap.none': 'Nenhum',
  'admin.scale.pointsFor': 'Pontos — {operation}',
  'admin.scale.multipliedFor': 'Multiplicado pelo impulso — {operation}',
  'admin.scale.capFor': 'Limite — {operation}',
  'admin.scale.variantFor': 'Pontos ({variant}) — {operation}',
  'admin.scale.multiplier.title': 'Multiplicador',
  'admin.scale.field.windowDays': 'Janela móvel (dias)',
  'admin.scale.field.stepPerExtraFamily': 'Passo por família adicional',
  'admin.scale.field.standingBonus': 'Bônus de estabilidade',
  'admin.scale.field.achievementsForStanding': 'Conquistas para a estabilidade',
  'admin.scale.field.highBadgeThreshold': 'Limiar de medalha alta',
  'admin.scale.field.highBadgesForStanding': 'Medalhas altas para a estabilidade',
  'admin.scale.field.maxFactor': 'Multiplicador máximo',
  'admin.scale.levels.title': 'Limite por nível',
  'admin.scale.col.minLevel': 'A partir do nível',
  'admin.scale.col.maxFactor': 'Multiplicador máximo',
  'admin.scale.levels.empty': 'Sem limite por nível: o multiplicador máximo vale para todos.',
  'admin.scale.levels.add': 'Adicionar um nível',
  'admin.scale.levels.remove': 'Remover o nível {level}',
  'admin.scale.minLevelFor': 'Nível mínimo — linha {row}',
  'admin.scale.maxFactorFor': 'Multiplicador máximo — linha {row}',
  'admin.scale.reset': 'Voltar aos padrões',
  'admin.scale.save': 'Salvar',
  'admin.scale.saving': 'Salvando…',
  'admin.scale.saved': 'Tabela salva.',
  'admin.scale.invalid': 'Tabela inválida: um valor está fora dos limites, um nível ou um patamar de sequência está duplicado, ou um limite de nível excede o multiplicador máximo.',
  'admin.scale.saveFailed': 'Falha ao salvar: {error}',
  'admin.scale.resetDone': 'Padrões restaurados — salve para aplicá-los.',
  'admin.scale.domain.messaging': 'Mensagens',
  'admin.scale.domain.calls': 'Chamadas',
  'admin.scale.domain.conversations': 'Conversas',
  'admin.scale.domain.communities': 'Comunidades',
  'admin.scale.domain.publishing': 'Publicação',
  'admin.scale.domain.feed': 'Feed social',
  'admin.scale.domain.links': 'Links e afiliação',
  'admin.scale.domain.friends': 'Amigos e contatos',
  'admin.scale.domain.profile': 'Perfil e voz',
  'admin.scale.domain.tools': 'Ferramentas',
  'admin.scale.freq.repeatable': 'Repetível',
  'admin.scale.freq.per-target': 'Única por alvo',
  'admin.scale.freq.per-account': 'Uma vez por conta',
  'admin.scale.freq.progressive': 'Progressivo',
  'admin.scale.scope.conversation-day': 'por dia e por conversa',
  'admin.scale.scope.day': 'por dia',
  'admin.scale.scope.target': 'por alvo',
  'admin.scale.cap.perTarget': '1 por alvo',
  'admin.scale.cap.perAccount': '1 por conta',
  'admin.scale.cap.linkRule': 'Regra dos links',
  'admin.scale.variant.public': 'pública',
  'admin.scale.variant.community': 'comunidade',
  'admin.scale.variant.friends': 'amigos',
  'admin.scale.variant.other': 'outra',
  'admin.scale.variant.live': 'ao vivo',
  'admin.scale.variant.static': 'estática',
  'admin.scale.op.content.text_message': 'Enviar uma mensagem de texto',
  'admin.scale.op.content.audio_message': 'Enviar uma mensagem de voz',
  'admin.scale.op.tool.attachment': 'Anexar um arquivo, uma foto ou um vídeo',
  'admin.scale.op.tool.sticker': 'Enviar um sticker',
  'admin.scale.op.tool.reaction': 'Reagir a uma mensagem',
  'admin.scale.op.tool.quote_reply': 'Responder citando uma mensagem',
  'admin.scale.op.tool.forward': 'Encaminhar uma mensagem',
  'admin.scale.op.tool.pin': 'Fixar uma mensagem',
  'admin.scale.op.tool.voice_listened': 'Ouvir uma mensagem de voz até o fim',
  'admin.scale.op.tool.translation_request': 'Pedir uma tradução ou uma transcrição',
  'admin.scale.op.tool.location': 'Compartilhar sua localização',
  'admin.scale.op.conversation.call_started': 'Fazer uma chamada (≥ 30 s)',
  'admin.scale.op.conversation.call_joined': 'Entrar em uma chamada (≥ 30 s)',
  'admin.scale.op.conversation.call_minutes': 'Bloco de 5 minutos de chamada',
  'admin.scale.op.conversation.call_participant_added': 'Adicionar alguém a uma chamada em andamento',
  'admin.scale.op.conversation.private': 'Primeira mensagem em uma conversa privada',
  'admin.scale.op.conversation.public': 'Primeira mensagem em uma conversa pública',
  'admin.scale.op.conversation.community': 'Primeira mensagem em uma conversa de comunidade',
  'admin.scale.op.conversation.group_created': 'Criar um grupo (por conjunto de membros)',
  'admin.scale.op.social.conversation_invite': 'Convidar alguém para uma conversa',
  'admin.scale.op.social.conversation_link_joined': 'Alguém entra pelo meu link de conversa',
  'admin.scale.op.social.community_created': 'Criar uma comunidade',
  'admin.scale.op.social.community_joined': 'Entrar em uma comunidade',
  'admin.scale.op.content.post': 'Publicar um post',
  'admin.scale.op.content.story': 'Publicar um story',
  'admin.scale.op.content.reel': 'Publicar um reel',
  'admin.scale.op.content.status': 'Publicar um humor',
  'admin.scale.op.tool.in_app_edit': 'Criar no editor do Meeshy',
  'admin.scale.op.tool.direct_publish': 'Publicar uma mídia diretamente',
  'admin.scale.op.comment.text': 'Comentar por escrito',
  'admin.scale.op.comment.audio': 'Comentar com uma mensagem de voz',
  'admin.scale.op.tool.post_reaction': 'Reagir a um post',
  'admin.scale.op.tool.comment_like': 'Curtir um comentário',
  'admin.scale.op.social.repost': 'Republicar um post',
  'admin.scale.op.social.share': 'Compartilhar um post (link rastreado)',
  'admin.scale.op.tool.post_bookmark': 'Salvar um post',
  'admin.scale.op.tool.story_viewed': 'Ver um story até o fim',
  'admin.scale.op.tool.poll_answered': 'Responder a uma enquete',
  'admin.scale.op.social.tracked_link': 'Criar um link rastreado',
  'admin.scale.op.social.affiliate_link_created': 'Criar um link de afiliado',
  'admin.scale.op.social.conversation_link_created': 'Criar um link de conversa',
  'admin.scale.op.social.link_visit': 'Visita única a um dos meus links',
  'admin.scale.op.social.invite_joined': 'Um indicado se cadastra pelo meu link',
  'admin.scale.op.social.friendship': 'Amizade aceita (os dois ganham)',
  'admin.scale.op.social.email_invite': 'Convidar por e-mail',
  'admin.scale.op.social.contacts_synced': 'Sincronizar seus contatos',
  'admin.scale.op.profile.avatar': 'Adicionar uma foto de perfil',
  'admin.scale.op.profile.bio': 'Escrever sua bio',
  'admin.scale.op.profile.second_language': 'Configurar um segundo idioma',
  'admin.scale.op.profile.email_verified': 'Verificar seu e-mail',
  'admin.scale.op.profile.phone_verified': 'Verificar seu telefone',
  'admin.scale.op.profile.two_factor': 'Ativar a autenticação em dois fatores',
  'admin.scale.op.profile.voice_profile': 'Gravar sua voz (com consentimento)',
  'admin.scale.op.tool.sticker_created': 'Criar um sticker a partir de uma imagem',
  'admin.scale.op.streak.bonus': 'Bônus de sequência',
  'admin.scale.links.title': 'Regra dos links (visita única)',
  'admin.scale.links.intro': 'Uma visita conta uma vez por visitante, por link e por janela, nunca a do criador. Seu valor sobe a cada vez que as visitas dobram além do primeiro patamar.',
  'admin.scale.links.basePoints': 'Valor inicial de uma visita',
  'admin.scale.links.firstTier': 'Tamanho do primeiro patamar (visitas)',
  'admin.scale.links.stepPerDoubling': 'Aumento a cada dobra',
  'admin.scale.links.maxPoints': 'Valor máximo de uma visita',
  'admin.scale.links.dedupHours': 'Janela de uma visita única (horas)',
  'admin.scale.links.dailyCapPerCreator': 'Visitas creditadas por criador e por dia',
  'admin.scale.streak.title': 'Bônus de sequência',
  'admin.scale.streak.empty': 'Nenhum bônus de sequência.',
  'admin.scale.streak.col.days': 'Dias ativos seguidos',
  'admin.scale.streak.col.points': 'Pontos',
  'admin.scale.streak.daysFor': 'Dias — patamar {row}',
  'admin.scale.streak.pointsFor': 'Pontos — patamar {row}',
  'admin.scale.streak.add': 'Adicionar um patamar',
  'admin.scale.streak.remove': 'Remover o patamar de {days} dias',
  'admin.scale.abuse.title': 'Proteções dos pesos altos',
  'admin.scale.abuse.intro': 'Uma operação que vale pelo menos o limiar só credita uma vez por conteúdo, devolve seus pontos se o conteúdo for excluído dentro da janela e fica limitada para uma conta sem e-mail nem telefone verificado. Interagir com o próprio conteúdo nunca rende nada.',
  'admin.scale.abuse.heavyPoints': 'Limiar de peso alto (pontos)',
  'admin.scale.abuse.clawbackHours': 'Estorno se excluído em até (horas)',
  'admin.scale.abuse.unverifiedMaxPoints': 'Máximo para uma conta não verificada',
  'admin.users.search': 'Procurar uma conta',
  'admin.users.count': '{count} conta(s)',
  'admin.users.empty': 'Nenhuma conta corresponde.',
  'admin.users.unavailable': 'Lista indisponível de momento.',
  'admin.users.inactive': 'desativada',
  'admin.users.previous': 'Anteriores',
  'admin.users.next': 'Seguintes',
  'admin.user.title': 'Membro',
  'admin.user.unavailable': 'Ficha indisponível de momento.',
  'admin.user.identity': 'Identidade',
  'admin.user.account': 'Conta',
  'admin.user.created': 'Aderiu em',
  'admin.user.lastActive': 'Última atividade',
  'admin.user.twoFactor': 'Duplo fator',
  'admin.user.enabled': 'ativado',
  'admin.user.deleted': 'eliminada',
  'admin.user.role': 'Função',
  'admin.edit.displayName': 'Nome visível',
  'admin.edit.email': 'E-mail',
  'admin.edit.bio': 'Biografia',
  'admin.edit.active': 'Conta ativa',
  'admin.edit.save': 'Guardar',
  'admin.edit.reason': 'Motivo (opcional)',
  'admin.edit.warnRole': 'Alterar a função muda as suas permissões.',
  'admin.edit.warnDeactivate': 'Desativar encerra as sessões abertas.',
  'admin.edit.confirm': 'Confirmar',
  'admin.edit.saved': 'Alterações guardadas',
  'admin.edit.failed': 'Não foi possível guardar',
  'admin.password.title': 'Repor a palavra-passe',
  'admin.password.warn': 'Isto encerra todas as sessões abertas.',
  'admin.password.generated': 'Copie-a agora: não será mostrada novamente.',
  'admin.password.copy': 'Copiar',
  'admin.password.copied': 'Copiada',
  'admin.password.apply': 'Repor',
  'admin.password.done': 'Palavra-passe reposta',
  'admin.password.failed': 'Não foi possível repor',
  'admin.password.level': 'Nível',
  'admin.password.level.simple': 'Simples',
  'admin.password.level.easy': 'Fácil',
  'admin.password.level.medium': 'Médio',
  'admin.password.level.hard': 'Difícil',
  'admin.password.field': 'Palavra-passe',
  'admin.password.editable': 'Escolha um nível ou escreva a sua: o que é mostrado é o que será aplicado.',
  'admin.password.loading': 'A preparar propostas…',
  'admin.password.proposals.failed': 'Não foi possível carregar as propostas: escreva uma palavra-passe.',
  'admin.password.regenerate': 'Outra proposta',
  'admin.password.refused': 'Recusada: {reason}',
  'admin.ban.open': 'Banir',
  'admin.ban.title': 'Banir este membro',
  'admin.ban.reason': 'Motivo (obrigatório)',
  'admin.ban.permanent': 'Banimento permanente',
  'admin.ban.until': 'Até',
  'admin.ban.apply': 'Banir',
  'admin.ban.lift': 'Levantar',
  'admin.ban.active': 'em vigor',
  'admin.ban.expired': 'expirado',
  'admin.ban.lifted': 'levantado',
  'admin.ban.none': 'Sem banimentos',
  'admin.ban.done': 'Banimento registado',
  'admin.ban.failed': 'Não foi possível banir',
  'admin.media.title': 'Média',
  'admin.media.empty': 'Sem média',
  'admin.media.protected': 'protegido',
  'admin.media.fromPost': 'publicação',
  'admin.media.fromMessage': 'mensagem',
  'admin.conv.title': 'Conversas',
  'admin.conv.empty': 'Sem conversas',
  'admin.conv.members': '{count} membros',
  'admin.nav.conversations': 'Conversas',
  'admin.convList.search': 'Procurar uma conversa',
  'admin.convList.count': '{count} conversa(s)',
  'admin.convList.empty': 'Nenhuma conversa corresponde.',
  'admin.convList.unavailable': 'Lista indisponível no momento.',
  'admin.convList.members': '{count} membros',
  'admin.convList.sovereign': 'Reservado ao nível de administração.',
  'admin.convDetail.title': 'Leitura de uma conversa',
  'admin.convDetail.reasonLabel': 'Motivo da leitura',
  'admin.convDetail.reasonHint': 'Dez caracteres mínimo, registado com o seu nome.',
  'admin.convDetail.read': 'Ler a conversa',
  'admin.convDetail.empty': 'Nenhuma mensagem',
  'admin.convDetail.memberPrism': 'Lido no prisma do membro: {languages}',
  'admin.agent.title': 'Controlo do agente',
  'admin.agent.denied': 'Este controlo exige uma permissão própria.',
  'admin.agent.users': 'Membros conduzidos',
  'admin.agent.tracked': 'Conversas acompanhadas',
  'admin.agent.empty': 'Nada a mostrar.',
  'admin.offline': 'Offline.',
  'admin.agent.scan': 'Análise em curso: {node}',
  'admin.agent.relaunch': 'Voltar a lançar o agente',
  'admin.agent.effect': 'Refaz o estudo e pode publicar uma mensagem.',
  'admin.agent.done': 'Lançamento pedido',
  'admin.agent.failed': 'Recusada',
  'admin.agent.stop': 'Parar a análise',
  'admin.agent.halted': 'Análise parada',
  'admin.agent.down': 'Serviço do agente inacessível.',
  'admin.agent.logs': 'Registo de análises',
  'admin.nav.anonymous': 'Anônimos',
  'admin.shell.menu': 'Menu de administração',
  'admin.shell.fold': 'Recolher o menu',
  'admin.shell.unfold': 'Expandir o menu',
  'admin.shell.open': 'Abrir o menu',
  'admin.shell.close': 'Fechar o menu',
  'admin.shell.backToApp': 'Voltar ao aplicativo',
  'admin.list.filters': 'Filtros',
  'admin.list.all': 'Todos',
  'admin.list.yes': 'Sim',
  'admin.list.no': 'Não',
  'admin.list.reset': 'Redefinir',
  'admin.list.pageSize': 'Por página',
  'admin.list.range': '{from}–{to} de {total}',
  'admin.list.sortBy': 'Ordenar por {column}',
  'admin.col.member': 'Membro',
  'admin.col.email': 'E-mail',
  'admin.col.role': 'Função',
  'admin.col.status': 'Estado',
  'admin.col.created': 'Cadastro',
  'admin.col.lastActive': 'Última atividade',
  'admin.col.joined': 'Entrada',
  'admin.col.language': 'Idioma',
  'admin.col.conversation': 'Conversa',
  'admin.col.messages': 'Mensagens',
  'admin.col.name': 'Nome',
  'admin.filter.active': 'Ativos',
  'admin.filter.inactive': 'Desativados',
  'admin.filter.emailVerified': 'E-mail verificado',
  'admin.filter.twoFactor': 'Dois fatores',
  'admin.anonymous.search': 'Pesquisar um anônimo',
  'admin.anonymous.empty': 'Nenhum anônimo corresponde.',
  'admin.anonymous.unavailable': 'Lista indisponível no momento.',
  'admin.anonymous.title': 'Participante anônimo',
  'admin.anonymous.left': 'Saiu',
  'admin.anonymous.permissions': 'Permissões',
  'admin.anonymous.openConversation': 'Ler a conversa',
  'admin.col.type': 'Tipo',
  'admin.col.members': 'Membros',
  'admin.col.createdOn': 'Criação',
  'admin.col.lastMessage': 'Última mensagem',
  'admin.tab.profile': 'Perfil',
  'admin.tab.conversations': 'Conversas',
  'admin.tab.media': 'Mídia',
  'admin.tab.contacts': 'Contatos',
  'admin.tab.communities': 'Comunidades',
  'admin.tab.voice': 'Perfil de voz',
  'admin.tab.security': 'Segurança',
  'admin.tab.reports': 'Denúncias',
  'admin.tab.label': 'Seções da ficha',
  'admin.dossier.empty': 'Nada a exibir.',
  'admin.dossier.restricted': 'Restrito a administradores autorizados para dados sensíveis.',
  'admin.contacts.sent': 'Enviada',
  'admin.contacts.received': 'Recebida',
  'admin.contacts.direction': 'Pedido',
  'admin.contacts.links': '{share} link(s) de compartilhamento · {tracking} link(s) de rastreamento · {affiliate} token(s) de afiliação',
  'admin.communities.creator': 'Criador',
  'admin.communities.private': 'Privada',
  'admin.voice.none': 'Nenhum perfil de voz registrado.',
  'admin.voice.samples': 'Amostras',
  'admin.voice.duration': 'Duração gravada',
  'admin.voice.model': 'Modelo',
  'admin.voice.consents': 'Consentimentos',
  'admin.voice.consentProfile': 'Perfil de voz',
  'admin.voice.consentData': 'Dados de voz',
  'admin.voice.consentCloning': 'Clonagem de voz',
  'admin.voice.notGiven': 'não concedido',
  'admin.voice.traced': 'Esta consulta é registrada no log de auditoria.',
  'admin.security.sessions': 'Sessões',
  'admin.security.events': 'Eventos de segurança',
  'admin.security.device': 'Dispositivo',
  'admin.security.place': 'Local',
  'admin.security.ip': 'Endereço IP',
  'admin.security.valid': 'Aberta',
  'admin.security.closed': 'Fechada',
  'admin.security.event': 'Evento',
  'admin.security.severity': 'Gravidade',
  'admin.col.date': 'Data',
  'admin.reports.filed': 'Denúncias feitas por este membro',
  'admin.reports.received': 'Mensagens denunciadas',
  'admin.reports.subject': 'Objeto',
  'admin.reports.reporter': 'Denunciado por',
  'admin.reports.reason': 'Motivo',
  'admin.reports.message': 'Mensagem',
  'admin.reports.withheld': 'texto reservado à moderação',
  'admin.anonymous.link': 'Entrou pelo link',
  'admin.gallery.title': 'Imagens',
  'admin.gallery.empty': 'Nenhuma imagem',
  'admin.gallery.previous': 'Imagem anterior',
  'admin.gallery.next': 'Próxima imagem',
  'admin.gallery.avatar': 'Foto de perfil',
  'admin.gallery.banner': 'Capa',
  'admin.gallery.position': 'Imagem {n} de {total}',
  'admin.meta.title': 'Metadados',
  'admin.meta.name': 'Nome completo',
  'admin.meta.systemLanguage': 'Idioma principal',
  'admin.meta.regionalLanguage': 'Idioma secundário',
  'admin.meta.customLanguage': 'Idioma de destino',
  'admin.meta.timezone': 'Fuso horário',
  'admin.meta.emailVerified': 'E-mail verificado em',
  'admin.meta.phoneVerified': 'Telefone verificado em',
  'admin.meta.completion': 'Perfil concluído',
  'admin.meta.passwordChanged': 'Senha alterada em',
  'admin.meta.failedLogins': 'Logins falhados',
  'admin.meta.lockedUntil': 'Bloqueado até',
  'admin.meta.lockedReason': 'Motivo do bloqueio',
  'admin.meta.deactivated': 'Desativado em',
  'admin.meta.updated': 'Atualizado em',
  'admin.tab.preferences': 'Preferências',
  'admin.stats.title': 'Em números',
  'admin.stats.messagesSent': 'Mensagens enviadas',
  'admin.stats.conversations': 'Conversas',
  'admin.stats.posts': 'Publicações',
  'admin.stats.reels': 'Reels',
  'admin.stats.stories': 'Stories',
  'admin.stats.comments': 'Comentários',
  'admin.stats.reactionsGiven': 'Reações dadas',
  'admin.stats.mediaUploaded': 'Mídias enviadas',
  'admin.stats.friends': 'Amigos',
  'admin.stats.pendingIn': 'Pedidos recebidos',
  'admin.stats.pendingOut': 'Pedidos enviados',
  'admin.stats.reportsFiled': 'Denúncias feitas',
  'admin.stats.reportsReceived': 'Denúncias recebidas',
  'admin.stats.activeSessions': 'Sessões ativas',
  'admin.stats.communities': 'Comunidades',
  'admin.prefs.privacy': 'Privacidade',
  'admin.prefs.notification': 'Notificações',
  'admin.prefs.message': 'Mensagens',
  'admin.prefs.audio': 'Áudio e voz',
  'admin.prefs.video': 'Vídeo',
  'admin.prefs.document': 'Documentos',
  'admin.prefs.application': 'Aplicativo',
  'admin.prefs.notice': 'Cada alteração se aplica ao membro em todos os seus dispositivos e fica registrada no log de auditoria.',
  'admin.prefs.readOnly': 'somente leitura',
  'admin.prefs.saved': 'Preferência salva',
  'admin.prefs.failed': 'Não foi possível salvar a preferência',
  'admin.prefs.consent': 'Recusado: o membro não deu o consentimento que esta opção exige',
  'admin.prefs.reserved': 'Recusado: sua função não permite modificar este membro',
  'admin.prefs.invalid': 'Recusado: valor inválido',
  'admin.list.sort': 'Ordenar',
  'admin.list.order': 'Sentido',
  'admin.list.newest': 'Mais recentes primeiro',
  'admin.list.oldest': 'Mais antigas primeiro',
  'admin.conv.manage': 'Gerenciar',
  'admin.conv.role.admin': 'Administrador',
  'admin.conv.role.moderator': 'Moderador',
  'admin.conv.role.member': 'Membro',
  'admin.conv.configure': 'Configurar',
  'admin.convSettings.title': 'Configurar a conversa',
  'admin.convSettings.titleField': 'Título',
  'admin.convSettings.description': 'Descrição',
  'admin.convSettings.avatar': 'Imagem (URL)',
  'admin.convSettings.banner': 'Banner (URL)',
  'admin.convSettings.writeRole': 'Quem pode escrever',
  'admin.convSettings.writeRole.everyone': 'Todos',
  'admin.convSettings.writeRole.member': 'Os membros',
  'admin.convSettings.writeRole.moderator': 'Moderadores e acima',
  'admin.convSettings.writeRole.admin': 'Administradores e acima',
  'admin.convSettings.writeRole.creator': 'Apenas o criador',
  'admin.convSettings.announcement': 'Canal de anúncios',
  'admin.convSettings.slowMode': 'Modo lento (segundos)',
  'admin.convSettings.autoTranslate': 'Tradução automática',
  'admin.convSettings.archive': 'Arquivar',
  'admin.convSettings.restore': 'Restaurar',
  'admin.convSettings.close': 'Fechar à escrita',
  'admin.convSettings.reopen': 'Reabrir',
  'admin.convSettings.memberRole': 'Função deste membro',
  'admin.convSettings.remove': 'Remover da conversa',
  'admin.convSettings.reason': 'Motivo (mínimo 10 caracteres)',
  'admin.convSettings.confirm': 'Confirmar',
  'admin.convSettings.save': 'Guardar',
  'admin.convSettings.saved': 'Conversa atualizada',
  'admin.convSettings.removed': 'Membro removido',
  'admin.convSettings.failed': 'Alteração recusada',
  'admin.convSettings.creatorProtected': 'O criador não pode ser despromovido nem removido',
  'admin.create.open': 'Criar uma conta',
  'admin.create.title': 'Nova conta',
  'admin.create.username': 'Nome de utilizador',
  'admin.create.firstName': 'Nome',
  'admin.create.lastName': 'Apelido',
  'admin.create.email': 'E-mail',
  'admin.create.password': 'Palavra-passe',
  'admin.create.passwordHint': 'Longa e difícil de adivinhar: uma palavra-passe fraca é recusada.',
  'admin.create.language': 'Idioma da interface',
  'admin.create.emailVerified': 'Atesto este endereço de e-mail',
  'admin.create.emailVerifiedOn': 'A conta poderá iniciar sessão de imediato.',
  'admin.create.emailVerifiedOff': 'Sem isso, um código será enviado para este endereço no primeiro início de sessão.',
  'admin.create.submit': 'Criar a conta',
  'admin.create.created': 'Conta criada',
  'admin.create.failed': 'Criação recusada: {reason}',
  'admin.create.emailTaken': 'Este endereço já é usado por outra conta.',
  'admin.create.usernameTaken': 'Este nome de utilizador já está em uso.',
  'admin.create.missing': 'Preencha todos os campos.',
  'admin.images.avatarOpen': 'Alterar a foto',
  'admin.images.bannerOpen': 'Alterar o banner',
  'admin.images.upload': 'Carregar uma imagem',
  'admin.images.uploading': 'A carregar…',
  'admin.images.remove': 'Remover',
  'admin.images.choose': 'Escolher entre as suas publicações públicas',
  'admin.images.chooseHint': 'Só são propostas as imagens que já publicou em público.',
  'admin.images.noCandidate': 'Nenhuma imagem pública a propor.',
  'admin.images.candidatesFailed': 'Não foi possível carregar as suas imagens públicas.',
  'admin.images.useCandidate': 'Usar a imagem {n} de {total}',
  'admin.images.current': 'Imagem atual',
  'admin.images.saved': 'Imagem atualizada',
  'admin.images.removed': 'Imagem removida',
  'admin.images.failed': 'Falha ao atualizar a imagem',
  'admin.images.offline': 'Sem ligação: tente novamente quando estiver ligado.',
  'admin.images.unreadable': 'Não foi possível ler esta imagem.',
  'admin.section.saving': 'A guardar…',
  'admin.contact.title': 'Contacto',
  'admin.contact.phone': 'Telefone',
  'admin.contact.verified': 'Verificado',
  'admin.contact.unverified': 'Não verificado',
  'admin.contact.resend': 'Reenviar a verificação',
  'admin.contact.resent': 'Verificação enviada',
  'admin.contact.resendFailed': 'Não foi possível enviar a verificação',
  'admin.contact.markVerified': 'Marcar como verificado',
  'admin.contact.markUnverified': 'Remover a verificação',
  'admin.security.twoFactorHint': 'É pedido um código em cada início de sessão.',
  'admin.security.twoFactorNeedsPhone': 'Adicione um telefone para ativar o segundo fator.',
  'admin.security.sessionsOpen': 'Ver as sessões',
  'admin.roleStatus.title': 'Função e estado',
  'admin.identity.suggestions': 'Nomes de utilizador livres',
  'admin.identity.noLanguage': 'Nenhuma',
  'admin.security.twoFactorNotEnrolled': 'O membro tem primeiro de associar uma aplicação de autenticação.',
  'admin.quick.title': 'Ações rápidas',
  'admin.quick.activate': 'Ativar a conta',
  'admin.quick.activated': 'Conta ativada',
  'admin.quick.validateEmail': 'Validar o e-mail',
  'admin.quick.validatePhone': 'Validar o telefone',
} satisfies AdminInterfaceCatalog;

export default pt;
