import type { StudioChromeCatalogSlice } from './catalog-fr-studio-chrome';

/** Composer plein écran (#8413) et panneau Cadre (#8414) — voir `catalog-fr-studio-chrome.ts`. */
const itStudioChrome = {
  'story.studio.more': 'Altre opzioni',
  'story.studio.preview': 'Anteprima',
  'story.studio.preview.close': 'Chiudi l’anteprima',
  'story.studio.page.remove.current': 'Elimina questa scena',
  'story.studio.postText': 'Testo del post',
  'story.studio.postText.placeholder': 'Scrivi il testo del post…',
  'story.studio.postText.done': 'Fine',
  'story.studio.tile.page': 'Scena',
  'story.studio.tile.text': 'Testo',
  'story.studio.tile.time': 'Tempo',
  'story.studio.rail.scene': 'Strumenti della scena',
  'story.studio.timeline.unit': 's',
  'story.studio.tile.frame': 'Cornice',
  'story.studio.undo': 'Annulla',
  'story.studio.redo': 'Ripristina',
  'story.studio.frame': 'Cornice',
  'story.studio.frame.media': 'Il media',
  'story.studio.frame.around': 'Intorno al media',
  'story.studio.frame.fit': 'Adatta',
  'story.studio.frame.fill': 'Riempi',
  'story.studio.frame.fit.hint': 'Intero, dentro la cornice 9:16. Nulla viene ritagliato.',
  'story.studio.frame.fill.hint': 'Copre tutta la cornice 9:16, ritagliando i bordi se serve.',
  'story.studio.backdrop.blur': 'Sfocato',
  'story.studio.backdrop.black': 'Nero',
  'story.studio.backdrop.white': 'Bianco',
  'story.studio.backdrop.indigo': 'Indaco',
  'story.studio.backdrop.sand': 'Sabbia',
  'story.studio.animated': 'Animato',
  'story.studio.timeline': 'Timeline della scena',
  'story.studio.timeline.play': 'Riproduci',
  'story.studio.timeline.pause': 'Pausa',
  'story.studio.timeline.empty': 'Scrivi un testo o posa un livello: ogni oggetto ha la sua traccia.',
  'story.studio.timeline.overlay': 'Livello',
  'story.studio.retouch.title': 'Modifica l’immagine',
  'story.studio.retouch.done': 'Fine',
  'story.studio.retouch.cancel': 'Annulla la modifica',
  'composer.attachment.edit': 'Modifica {name}',
  'story.studio.retouch.failed': 'Impossibile generare l’immagine.',
  'story.studio.timeline.enter': 'Entra qui',
  'story.studio.timeline.exit': 'Esce qui',
  'story.studio.timeline.scrub': 'Sposta la testina',
  'story.studio.timeline.track': 'Traccia di {name}',
  'story.studio.timeline.earlier': 'Prima',
  'story.studio.timeline.later': 'Dopo',
  'story.studio.editor.filter': 'Filtro',
  'story.studio.filter.vintage': 'Vintage',
  'story.studio.filter.bw': 'B/N',
  'story.studio.filter.warm': 'Caldo',
  'story.studio.filter.cool': 'Freddo',
  'story.studio.filter.dramatic': 'Drammatico',
  'story.studio.filter.vivid': 'Vivace',
  'story.studio.filter.fade': 'Sbiadito',
  'story.studio.filter.chrome': 'Cromo',
  'story.studio.object.menu': 'Azioni per {name}',
  'story.studio.object.raise': 'Porta avanti',
  'story.studio.object.lower': 'Porta indietro',
  'story.studio.object.duplicate': 'Duplica',
  'story.studio.object.edit': 'Modifica',
  'story.studio.object.remove': 'Rimuovi',
  'story.studio.edit.done': 'OK',
  'story.studio.pose.left': 'A sinistra',
  'story.studio.pose.right': 'A destra',
  'story.studio.pose.up': 'In alto',
  'story.studio.pose.down': 'In basso',
  'story.studio.objects.edit': 'Modifica {name}',
} satisfies StudioChromeCatalogSlice;

export default itStudioChrome;
