import type { MessageCardCatalogSlice } from './catalog-fr-message-card';

/** Message export as image — see `catalog-fr-message-card.ts`. */
const itMessageCard = {
  'message.menu.export': 'Esporta come immagine',
  'export.card.title': 'Esporta come immagine',
  'export.card.popular': 'Popolari',
  'export.card.random': 'A caso',
  'export.card.palette': 'Colori',
  'export.card.typeface': 'Carattere',
  'export.card.link': 'Collegamento',
  'export.card.typeface.rond': 'Tondo',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Piuma',
  'export.card.typeface.affiche': 'Manifesto',
  'export.card.typeface.futur': 'Futurista',
  'export.card.typeface.machine': 'Macchina da scrivere',
  'export.card.typeface.marqueur': 'Pennarello',
  'export.card.typeface.systeme': 'Sistema',
  'export.card.link.orbite': 'Orbita',
  'export.card.link.filet': 'Filetto',
  'export.card.link.guillemets': 'Virgolette',
  'export.card.link.fleche': 'Freccia',
  'export.card.link.bulles': 'Bolle',
  'export.card.link.fil': 'Filo',
  'export.card.link.silence': 'Silenzio',
  'export.card.option.anonymizeQuoted': 'Anonimizza il messaggio citato',
  'export.card.option.anonymizeReply': 'Anonimizza la risposta',
  'export.card.anonymous': 'Anonimo',
  'export.card.preview': 'Anteprima dell’immagine',
  'export.card.rendering': 'Preparazione dell’immagine…',
  'export.card.save': 'Salva',
  'export.card.share': 'Condividi',
  'export.card.language': 'Lingua del messaggio',
  'export.card.language.asRead': 'Come lo leggo',
  'export.card.truncated': 'Messaggio lungo: la fine è tagliata nell’immagine.',
  'export.announce.gallery': 'Immagine salvata nella galleria',
  'export.announce.shared': 'Immagine pronta',
  'export.announce.cancelled': 'Esportazione annullata',
  'export.announce.expired': 'Tocca di nuovo per salvare',
  'export.announce.failed': 'Impossibile creare l’immagine',
  'export.announce.unavailable': 'Questo dispositivo non può salvare l’immagine',
  'message.menu.exportQuick': 'Esportazione rapida',
  'export.card.options': 'Mostra',
  'export.card.option.title': 'Titolo della conversazione',
  'export.card.option.authors': 'Nomi degli autori',
  'export.card.option.date': 'Data',
  'export.card.default.save': 'Usa come formato predefinito',
  'export.card.default.current': 'Formato predefinito',
  'export.announce.defaultSaved': 'Formato predefinito salvato',
} satisfies MessageCardCatalogSlice;

export default itMessageCard;
