import type { ExportCardCatalog } from '@/lib/i18n-export-card-catalog';

const en = {
  'export.card.title': 'Imagine',
  'export.card.popular': 'Popular',
  'export.card.random': 'Surprise me',
  'export.card.palette': 'Colors',
  'export.card.typeface': 'Typeface',
  'export.card.link': 'Link',
  'export.card.typeface.rond': 'Rounded',
  'export.card.typeface.didone': 'Didone',
  'export.card.typeface.plume': 'Quill',
  'export.card.typeface.affiche': 'Poster',
  'export.card.typeface.futur': 'Futuristic',
  'export.card.typeface.machine': 'Typewriter',
  'export.card.typeface.marqueur': 'Marker',
  'export.card.typeface.systeme': 'System',
  'export.card.link.orbite': 'Orbit',
  'export.card.link.filet': 'Rule',
  'export.card.link.guillemets': 'Quotes',
  'export.card.link.fleche': 'Arrow',
  'export.card.link.bulles': 'Bubbles',
  'export.card.link.fil': 'Thread',
  'export.card.link.silence': 'Silence',
  'export.card.option.anonymizeQuoted': 'Anonymize quoted message',
  'export.card.option.anonymizeReply': 'Anonymize reply',
  'export.card.anonymous': 'Anonymous',
  'export.card.preview': 'Image preview',
  'export.card.rendering': 'Preparing image…',
  'export.card.save': 'Save',
  'export.card.share': 'Share',
  'export.card.language': 'Message language',
  'export.card.language.asRead': 'As I read it',
  'export.card.truncated': 'Long message: the end is cut off in the image.',
  'export.announce.gallery': 'Image saved to your gallery',
  'export.announce.shared': 'Image ready',
  'export.announce.cancelled': 'Export cancelled',
  'export.announce.expired': 'Tap again to save',
  'export.announce.failed': 'Couldn’t create the image',
  'export.announce.unavailable': 'This device can’t save the image',
  'export.card.options': 'Show',
  'export.card.option.title': 'Conversation title',
  'export.card.option.authors': 'Author names',
  'export.card.option.date': 'Date',
  'export.card.default.save': 'Use as default format',
  'export.card.default.current': 'Default format',
  'export.announce.defaultSaved': 'Default format saved',
  'export.card.tab.styles': 'Styles',
  'export.card.tab.palette': 'Background',
  'export.card.tab.typeface': 'Font',
  'export.card.tab.link': 'Link',
  'export.card.tab.details': 'Details',
  'export.card.tab.language': 'Language',
  'export.card.part.header': 'Header',
  'export.card.part.quote': 'Quote',
  'export.card.part.link': 'Link',
  'export.card.part.reply': 'Reply',
  'export.card.part.background': 'Background',
  'export.card.hint': 'Tap a part of the card to style it',
  'export.card.gallery.open': 'See all',
  'export.card.gallery.title': 'All styles',
  'export.card.gallery.count': '{count} styles',
  'export.card.gallery.close': 'Close the gallery',
  'export.card.gallery.search': 'Search styles',
  'export.card.gallery.placeholder': 'Quill, dark, bubbles…',
  'export.card.gallery.empty': 'No style has that name. Try a color, a font or “dark”.',
  'export.card.tone.all': 'All',
  'export.card.tone.dark': 'Dark',
  'export.card.tone.light': 'Light',
  'export.card.typeface.pairs': 'The font dresses both the quote and the reply',
  'export.card.tab.frame': 'Frame',
  'export.card.tab.media': 'Media',
  'export.card.part.media': 'Media',
  'export.card.part.replies': 'Replies',
  'export.card.aspect': 'Image format',
  'export.card.aspect.auto': 'Fitted',
  'export.card.aspect.story': 'Story 9:16',
  'export.card.aspect.portrait': 'Portrait 4:5',
  'export.card.aspect.square': 'Square 1:1',
  'export.card.aspect.landscape': 'Landscape 16:9',
  'export.card.header': 'Title and date',
  'export.card.header.horizontal': 'Inline',
  'export.card.header.letters': 'Letter by letter',
  'export.card.header.up': 'Upward',
  'export.card.header.down': 'Downward',
  'export.card.authorsAt': 'Names',
  'export.card.authorsAt.top': 'Above the message',
  'export.card.authorsAt.end': 'At the end of the message',
  'export.card.tilt': 'Message rotation',
  'export.card.tilt.none': 'Straight',
  'export.card.tilt.left': 'Tilted left',
  'export.card.tilt.right': 'Tilted right',
  'export.card.option.times': 'Message times',
  'export.card.option.pseudonyms': 'Username instead of display name',
  'export.card.anonymity': 'Anonymity',
  'export.card.media.style': 'Image layout',
  'export.card.media.mosaique': 'Mosaic',
  'export.card.media.pleine': 'Full width',
  'export.card.media.bande': 'Strip',
  'export.card.audio.style': 'Audio display',
  'export.card.audio.onde': 'Waveform',
  'export.card.audio.spectre': 'Spectrum',
  'export.card.audio.pastille': 'Pill',
  'export.card.audio.etiquette': 'Label',
  'export.card.media.loading': 'Loading media…',
  'export.card.output': 'Save as',
  'export.card.output.image': 'Image',
  'export.card.output.gif': 'GIF',
  'export.card.output.video': 'Video',
  'export.card.motion.video': 'Creating the video…',
  'export.card.motion.gif': 'Creating the GIF…',
  'export.announce.motionUnavailable': 'This browser can’t create this animation',
  'export.announce.galleryMotion': 'Saved to your gallery',
  'export.announce.sharedMotion': 'Ready to share',
} satisfies ExportCardCatalog;

export default en;
