import type { GameBannerCatalog } from '@/lib/i18n-game-catalog';

/** LE BANDEAU DU JOUEUR (#9542) — les seules clés que le bandeau des hubs lit (`player-banner.tsx`, `lib/view/player-banner.ts`) : ses phrases, les noms de palier, de rang et de ligue, les accords de points, de jours et de Meeshes. Chargé SEUL par le bandeau, et avec chaque écran du jeu. Mêmes clés et mêmes paramètres que le français. */
const pt = {
  'game.points.one': '{count} ponto',
  'game.points.other': '{count} pontos',
  'game.days.one': '{count} dia',
  'game.days.other': '{count} dias',
  'game.meeshes.none': 'Nenhuma Meesh',
  'game.meeshes.one': '{count} Meesh',
  'game.meeshes.other': '{count} Meeshes',
  'game.tier.etincelle': 'Faísca',
  'game.tier.lueur': 'Lampejo',
  'game.tier.lumiere': 'Luz',
  'game.tier.eclat': 'Brilho',
  'game.tier.rayon': 'Raio',
  'game.tier.aurore': 'Aurora',
  'game.tier.comete': 'Cometa',
  'game.tier.etoile': 'Estrela',
  'game.tier.constellation': 'Constelação',
  'game.tier.galaxie': 'Galáxia',
  'game.tier.nebuleuse': 'Nebulosa',
  'game.tier.pulsar': 'Pulsar',
  'game.tier.quasar': 'Quasar',
  'game.tier.supernova': 'Supernova',
  'game.tier.magnetar': 'Magnetar',
  'game.tier.amas': 'Aglomerado',
  'game.tier.superamas': 'Superaglomerado',
  'game.tier.cosmos': 'Cosmos',
  'game.tier.infini': 'Infinito',
  'game.tier.singularite': 'Singularidade',
  'game.rank.murmure': 'Sussurro',
  'game.rank.echo': 'Eco',
  'game.rank.voix': 'Voz',
  'game.rank.conteur': 'Contador',
  'game.rank.passeur': 'Passador',
  'game.rank.polyglotte': 'Poliglota',
  'game.rank.ambassadeur': 'Embaixador',
  'game.rank.orateur': 'Orador',
  'game.rank.oracle': 'Oráculo',
  'game.rank.legende': 'Lenda',
  'game.rank.mythe': 'Mito',
  'game.rank.mythe_seat': 'Mito n.º {number}',
  'game.banner.level': 'Nível {level}',
  'game.banner.to_next': '{percent}% rumo ao {level}',
  'game.banner.top': 'no topo',
  'game.banner.capped': '{rank} abre mais',
  'game.banner.league': 'liga {league} {place}',
  'game.banner.flame': 'Chama {days}',
  'game.banner.place.one': '{count}º',
  'game.banner.place.other': '{count}º',
  'game.banner.points': '{points} pts',
  'game.banner.missing': 'faltam {points}',
  'game.banner.separator': ', ',
  'game.league.name.quartz': 'Quartzo',
  'game.league.name.ambre': 'Âmbar',
  'game.league.name.jade': 'Jade',
  'game.league.name.saphir': 'Safira',
  'game.league.name.rubis': 'Rubi',
  'game.league.name.amethyste': 'Ametista',
  'game.league.name.diamant': 'Diamante',
  'game.league.name.prisme': 'Prisma',
} as const satisfies GameBannerCatalog;

export default pt;
