import type { GameConceptCatalog } from '@/lib/i18n-game-catalog';

/** LES CONCEPTS DE « PROGRESSION » (#9542, #9563) — ce que disent la première page et les fiches (`game.concept.*`, `game.fiche.*`, `game.fact.*`). Chargé avec les routes de Progression, jamais avec le bandeau ni le carnet des règles. Mêmes clés et mêmes paramètres que le français. */
const pt = {
  'game.progression.title': 'Progresso',
  'game.concept.why_label': 'Para que serve',
  'game.concept.how_label': 'Como funciona',
  'game.fiche.what': 'O que é?',
  'game.fiche.where': 'Onde estou',
  'game.fiche.earn': 'Como ganhar mais',
  'game.fiche.more': 'Ir mais longe',
  'game.fiche.unknown': 'Esta ficha não existe, ou o seu servidor ainda não a oferece.',
  'game.concept.level.name': 'Nível',
  'game.concept.level.why': 'Seu nível mostra o caminho que você percorreu no Meeshy.',
  'game.concept.level.how': 'Seus pontos enchem o anel: quando ele fica cheio, você sobe um nível.',
  'game.concept.level.tip.1': 'Faça as missões do dia: elas dão muitos pontos.',
  'game.concept.level.tip.2': 'Mantenha sua Chama acesa: ela aumenta suas recompensas.',
  'game.concept.points.name': 'Pontos',
  'game.concept.points.why': 'Os pontos sobem seu nível e servem para cunhar Meeshes.',
  'game.concept.points.how': 'Cada gesto útil dá pontos: escrever, falar, publicar, reagir, convidar.',
  'game.concept.points.tip.1': 'Publique, comente, reaja: cada família de gestos tem sua tabela.',
  'game.concept.points.tip.2': 'Ative um impulso para multiplicar seus pontos.',
  'game.concept.meesh.name': 'Meeshes',
  'game.concept.meesh.why': 'A Meesh é a moeda rara do Meeshy: você guarda ou gasta.',
  'game.concept.meesh.how': 'Você a cunha com seus pontos. Cada cunhagem encarece a próxima.',
  'game.concept.meesh.tip.1': 'Guarde suas Meeshes para fazer seu tesouro crescer.',
  'game.concept.meesh.tip.2': 'Gaste-as para proteger sua Chama ou trocar uma missão.',
  'game.concept.glory.name': 'Glória',
  'game.concept.glory.why': 'A Glória dá o seu rank, e o seu rank nunca cai.',
  'game.concept.glory.how': 'Cada cunhagem, cada recorde e cada conquista somam Glória.',
  'game.concept.glory.tip.1': 'Cunhe uma Meesh: cada cunhagem soma Glória.',
  'game.concept.glory.tip.2': 'Bata seus recordes e desbloqueie conquistas.',
  'game.concept.flame.name': 'Chama',
  'game.concept.flame.why': 'Sua Chama conta seus dias seguidos e aumenta suas recompensas de missão.',
  'game.concept.flame.how': 'Um gesto por dia a faz crescer. Um congelamento cobre um dia perdido.',
  'game.concept.flame.tip.1': 'Faça pelo menos um gesto todos os dias.',
  'game.concept.flame.tip.2': 'Guarde um congelamento de reserva para os dias sem jogar.',
  'game.concept.missions.name': 'Missões do dia',
  'game.concept.missions.why': 'As missões dão um objetivo a cada dia, e pontos a mais.',
  'game.concept.missions.how': 'Três missões por dia. Quando estão feitas, você abre o baú.',
  'game.concept.missions.tip.1': 'Comece pela missão mais fácil.',
  'game.concept.missions.tip.2': 'Não gostou de uma missão? Troque-a, uma vez por dia.',
  'game.concept.league.name': 'Liga',
  'game.concept.league.why': 'A liga compara você, toda semana, com outros 29 jogadores.',
  'game.concept.league.how': 'Seus pontos da semana definem sua posição. Os primeiros sobem de liga.',
  'game.concept.league.tip.1': 'Jogue um pouco todo dia: os pontos da semana se somam.',
  'game.concept.league.tip.2': 'Mire nas primeiras posições antes de domingo à noite.',
  'game.concept.league.more': 'Ver a classificação',
  'game.concept.league.unplaced': 'Ainda sem grupo',
  'game.concept.season.name': 'Temporada',
  'game.concept.season.why': 'A temporada é um percurso de oito semanas, com uma taça no fim.',
  'game.concept.season.how': 'As missões e a dupla dão estrelas. As estrelas abrem as etapas.',
  'game.concept.season.tip.1': 'Termine suas missões do dia para ganhar estrelas.',
  'game.concept.season.tip.2': 'Jogue em dupla com um amigo: a recompensa é dobrada.',
  'game.concept.season.more': 'Ver o percurso',
  'game.concept.season.none': 'Nenhuma agora',
  'game.concept.prestige.name': 'Prestígio',
  'game.concept.prestige.why': 'O Prestígio recompensa quem chega ao nível 100.',
  'game.concept.prestige.how': 'Seu nível volta a 1. Você ganha uma estrela, um troféu e Glória.',
  'game.concept.prestige.tip.1': 'Suba até o nível 100.',
  'game.concept.prestige.tip.2': 'Passe ao Prestígio quando quiser: nada obriga você.',
  'game.concept.prestige.more': 'Abrir o Prestígio',
  'game.concept.elans.name': 'Impulsos',
  'game.concept.elans.why': 'Um impulso multiplica os pontos dos seus próximos gestos.',
  'game.concept.elans.how': 'Faça gestos de várias famílias nestes dias para ativá-lo.',
  'game.concept.elans.tip.1': 'Varie seus gestos: escreva, publique, comente, reaja.',
  'game.concept.elans.tip.2': 'Volte vários dias seguidos para mantê-lo.',
  'game.concept.elans.families.one': '{count} família ativa',
  'game.concept.elans.families.other': '{count} famílias ativas',
  'game.concept.badges.name': 'Selos',
  'game.concept.badges.why': 'Um selo mostra o que você mais faz no Meeshy.',
  'game.concept.badges.how': 'Repita um gesto: o selo dele muda de material, do cobre ao prisma.',
  'game.concept.badges.tip.1': 'Escolha um gesto de que você gosta e repita-o sempre.',
  'game.concept.badges.tip.2': 'Um selo apagado volta a acender: nada se perde.',
  'game.concept.badges.more': 'Ver todos os meus selos',
  'game.concept.defis.name': 'Desafios',
  'game.concept.defis.why': 'Os desafios são degraus a vencer, um depois do outro.',
  'game.concept.defis.how': 'Cada degrau alcançado abre o próximo, um pouco mais alto.',
  'game.concept.defis.tip.1': 'Olhe o próximo degrau e avance até ele.',
  'game.concept.defis.tip.2': 'Experimente gestos novos: cada um tem seus desafios.',
  'game.concept.defis.more': 'Ver todos os meus desafios',
  'game.concept.succes.name': 'Conquistas',
  'game.concept.succes.why': 'Uma conquista marca um momento raro da sua história no Meeshy.',
  'game.concept.succes.how': 'Ela se desbloqueia de uma vez, quando você reúne o que ela pede.',
  'game.concept.succes.tip.1': 'Explore o aplicativo: algumas conquistas estão escondidas.',
  'game.concept.succes.tip.2': 'As mais raras são as que mais somam Glória.',
  'game.concept.succes.more': 'Ver todas as minhas conquistas',
  'game.concept.showcase.name': 'Vitrine',
  'game.concept.showcase.why': 'Sua vitrine expõe os troféus que você ganhou.',
  'game.concept.showcase.how': 'Cada taça vai para lá sozinha. Você escolhe a ordem e quem a vê.',
  'game.concept.showcase.tip.1': 'Termine no topo da sua liga para ganhar uma taça.',
  'game.concept.showcase.tip.2': 'Complete uma temporada ou passe ao Prestígio.',
  'game.concept.showcase.more': 'Abrir minha vitrine',
  'game.concept.atlas.name': 'Atlas',
  'game.concept.atlas.why': 'O Atlas guarda um carimbo para cada idioma em que você conversou.',
  'game.concept.atlas.how': 'Envie uma mensagem e receba outra em um idioma: o carimbo aparece.',
  'game.concept.atlas.tip.1': 'Escreva para alguém em um idioma diferente do seu.',
  'game.concept.atlas.tip.2': 'Espere a resposta: é preciso uma mensagem em cada sentido.',
  'game.concept.atlas.more': 'Abrir meu Atlas',
  'game.concept.chip.next_price': 'Próxima: {price}',
  'game.concept.chip.next': 'Depois: {name}',
  'game.concept.chip.record': 'Recorde: {value}',
  'game.concept.chip.freezes': 'Congelamentos: {count}',
  'game.concept.chip.chest.locked': 'Baú fechado',
  'game.concept.chip.chest.ready': 'Baú pronto',
  'game.concept.chip.chest.claimed': 'Baú aberto',
  'game.concept.chip.can_mint': 'Dá para cunhar',
  'game.concept.chip.mint_covered': 'Suficiente para uma Meesh',
  'game.concept.chip.left': 'Faltam: {count}',
  'game.concept.chip.week': 'Semana {week}',
  'game.concept.chip.no_elan': 'Nenhum impulso ativo',
  'game.concept.chip.factor': 'Pontos ×{factor}',
  'game.concept.chip.seen_by': 'Vista por: {who}',
  'game.fact.tier': 'Faixa',
  'game.fact.to_next': 'Próximo nível',
  'game.fact.record': 'Recorde',
  'game.fact.next_meesh': 'Próxima Meesh',
  'game.fact.missing': 'Falta',
  'game.fact.balance': 'Em mãos',
  'game.fact.next_tier': 'Próxima faixa',
  'game.fact.minted': 'Cunhadas desde sempre',
  'game.fact.next_rank': 'Próximo rank',
  'game.fact.streak': 'Sequência',
  'game.fact.form': 'Forma',
  'game.fact.freezes': 'Congelamentos de reserva',
  'game.fact.state': 'Estado',
  'game.fact.lit': 'Acesa',
  'game.fact.done': 'Feitas',
  'game.fact.week_points': 'Pontos da semana',
  'game.fact.closes': 'Fechamento',
  'game.fact.steps': 'Etapas',
  'game.fact.stars': 'Estrelas',
  'game.fact.week': 'Semana',
  'game.fact.factor': 'Multiplicador',
  'game.fact.families': 'Famílias ativas',
  'game.fact.earned': 'Obtidos',
  'game.fact.trophies': 'Troféus',
  'game.fact.visibility': 'Visível para',
  'game.fact.stamps': 'Carimbos',
  'game.fact.pending': 'Em andamento',
  'game.fact.group': 'Grupo',
  'game.fact.material': 'Material',
  'game.detail.obtain_label': 'Como conseguir',
  'game.detail.gives_label': 'O que isso dá',
  'game.detail.earned': 'Obtido',
  'game.detail.earned_on': 'Obtido em {date}',
  'game.detail.locked': 'Ainda não obtido',
  'game.detail.missing': 'Falta {missing}',
  'game.detail.see_fiche': 'Ver a ficha',
  'game.detail.open': '{name}: ver os detalhes',
  'game.detail.rarity': 'Raridade',
  'game.detail.header_group': 'Meu rank e minhas Meeshes',
  'game.detail.badge.what': 'Um selo mostra quantas vezes você fez um gesto.',
  'game.detail.badge.how': 'Repita esse gesto: a cada degrau, o selo muda de material.',
  'game.detail.succes.what': 'Uma conquista marca um momento raro da sua história no Meeshy.',
  'game.detail.succes.how': 'Reúna o que ela pede: ela se desbloqueia de uma vez.',
  'game.detail.defi.what': 'Um desafio é um degrau a vencer em uma família de gestos.',
  'game.detail.defi.how': 'Alcance o número pedido: o próximo degrau se abre.',
  'game.detail.trophy.what': 'Um troféu guarda a lembrança de uma vitória. Não rende nada: é para mostrar.',
  'game.detail.trophy.how': 'Termine no topo da sua liga, complete uma temporada, passe ao Prestígio ou mantenha sua Chama.',
  'game.detail.stamp.what': 'Um carimbo prova que você conversou de verdade neste idioma.',
  'game.detail.stamp.how': 'Envie uma mensagem neste idioma e receba outra.',
  'game.detail.step.what': 'Uma etapa da temporada é uma recompensa gratuita no percurso.',
  'game.detail.step.how': 'Ganhe estrelas com as missões e a dupla, depois resgate a etapa.',
  'game.detail.seal.what': 'O Selo é um item de coleção. Não muda nada no jogo.',
  'game.detail.seal.how': 'Pegue-o com suas Meeshes durante a temporada.',
  'game.detail.gem.what': 'A gema diz em que liga você joga nesta semana.',
  'game.detail.gem.how': 'Termine entre os primeiros do seu grupo para subir de liga.',
  'game.detail.star.what': 'Uma estrela de Prestígio fica no seu anel de nível, para sempre.',
  'game.detail.star.how': 'Chegue ao nível 100 e passe ao Prestígio.',
  'game.detail.rank.what': 'Seu brasão mostra o seu rank. Um rank nunca cai.',
  'game.detail.rank.how': 'Ganhe Glória: cunhe Meeshes, bata seus recordes, desbloqueie conquistas.',
  'game.detail.flame.what': 'A forma da sua Chama cresce com a sua sequência de dias.',
  'game.detail.flame.how': 'Quanto maior ela é, mais crescem suas recompensas de missão.',
  'game.detail.freeze.what': 'Um congelamento protege sua Chama: ele cobre um dia em que você não fez nada.',
  'game.detail.freeze.how': 'Compre-o com suas Meeshes, ou encontre-o no baú do dia.',
  'game.detail.mission.what': 'Uma missão é um pequeno objetivo para hoje.',
  'game.detail.mission.how': 'Ela rende pontos e deixa você mais perto do baú do dia.',
  'game.detail.chest.what': 'O baú do dia se abre quando suas missões estão feitas.',
  'game.detail.chest.how': 'Pontos e, às vezes, um fragmento de Meesh ou um congelamento.',
  'game.detail.coin.what': 'A Meesh é a moeda rara do Meeshy. Cada moeda tem o seu número.',
  'game.detail.coin.how': 'Cunhe-a com seus pontos assim que tiver o bastante.',
  'game.detail.ring.what': 'O anel mostra o seu nível: ele se enche com seus pontos.',
  'game.detail.ring.how': 'Ganhe pontos: quando o anel fica cheio, você sobe um nível.',
  'game.detail.treasury.what': 'Seu tesouro cresce com as Meeshes que você guarda.',
  'game.detail.treasury.how': 'Guarde suas Meeshes em vez de gastá-las para chegar à próxima faixa.',
  'game.detail.elan.what': 'Uma família reúne gestos parecidos.',
  'game.detail.elan.how': 'Cada gesto rende pontos. Várias famílias ativas ativam um impulso.',
  'game.detail.elan.active': 'Ativa nestes dias',
  'game.detail.elan.idle': 'Não ativa nestes dias',
  'game.detail.elan.points': '{points} por gesto',
  'game.detail.player.what': 'É um jogador do seu grupo. Você só vê o pseudônimo e os pontos da semana dele.',
  'game.detail.fact.tier': 'Dez níveis formam uma faixa. Cada faixa tem seu nome e sua cor.',
  'game.detail.fact.score': 'São os pontos que você tem. Eles formam o seu nível.',
  'game.detail.fact.level_next': 'São os pontos que faltam para você subir um nível.',
  'game.detail.fact.level_record': 'É o nível mais alto que você alcançou.',
  'game.detail.fact.tailwind': 'Depois de uma cunhagem, seus pontos valem mais até o seu nível recorde.',
  'game.detail.fact.mint_price': 'É o preço da sua próxima Meesh. Ele sobe a cada cunhagem.',
  'game.detail.fact.mint_missing': 'São os pontos que faltam para cunhar sua próxima Meesh.',
  'game.detail.fact.can_mint': 'Você tem pontos suficientes: pode cunhar uma Meesh na ficha dela.',
  'game.detail.fact.factor': 'Seus próximos gestos rendem este número de vezes mais pontos.',
  'game.detail.fact.mint_next': 'Cada Meesh tem o seu número. Uma em cem é de ouro, uma em mil de prisma.',
  'game.detail.fact.mint_glory': 'Cada cunhagem soma esta Glória ao seu rank.',
  'game.detail.fact.minted': 'É o número de Meeshes que você cunhou desde o início.',
  'game.detail.fact.glory': 'A Glória se soma e nunca cai. Ela dá o seu rank.',
  'game.detail.fact.glory_missing': 'É a Glória que falta para o próximo rank.',
  'game.detail.fact.streak': 'É o número de dias seguidos em que você fez pelo menos um gesto.',
  'game.detail.fact.streak_record': 'É a sua sequência de dias mais longa.',
  'game.detail.fact.flame_state': 'Diz se a sua Chama está acesa, em perigo, protegida ou apagada.',
  'game.detail.fact.missions_done': 'Três missões por dia. Depois de feitas, elas abrem o baú.',
  'game.detail.fact.league_place': 'É a sua posição entre os jogadores do seu grupo, nesta semana.',
  'game.detail.fact.week_points': 'São os pontos ganhos desde segunda-feira. Eles voltam a zero toda semana.',
  'game.detail.fact.league_zone': 'Os primeiros sobem, os últimos descem, os outros ficam.',
  'game.detail.fact.league_missing': 'São os pontos que faltam para entrar na zona de promoção.',
  'game.detail.fact.league_closes': 'A semana da liga fecha no domingo à noite. A classificação fica congelada.',
  'game.detail.fact.league_friends': 'É a sua posição entre seus amigos aceitos, nesta semana.',
  'game.detail.fact.season': 'Uma temporada dura oito semanas e tem um número.',
  'game.detail.fact.season_week': 'É a semana atual, das oito da temporada.',
  'game.detail.fact.season_steps': 'São as etapas que você abriu no percurso da temporada.',
  'game.detail.fact.season_stars': 'As estrelas se ganham com as missões e a dupla. Elas abrem as etapas.',
  'game.detail.fact.prestige_glory': 'É a Glória que você ganha ao passar ao Prestígio.',
  'game.detail.fact.elan_families': 'São as famílias de gestos em que você esteve ativo nestes dias.',
  'game.detail.fact.badges_earned': 'É o número de selos obtidos, de todos os que existem.',
  'game.detail.fact.defis_earned': 'São os degraus vencidos, dos que você pode alcançar.',
  'game.detail.fact.succes_earned': 'São as conquistas desbloqueadas, de todas as que existem.',
  'game.detail.fact.trophies': 'É o número de troféus guardados na sua vitrine.',
  'game.detail.fact.showcase_visibility': 'Você escolhe quem vê sua vitrine: todos, seus amigos ou só você.',
  'game.detail.fact.atlas_stamps': 'São os idiomas em que você tem um carimbo, de todos os do Atlas.',
  'game.detail.fact.atlas_pending': 'São os idiomas em que ainda falta uma mensagem, enviada ou recebida.',
  'game.badge.counts_label': 'O que conta',
  'game.badge.stars_label': 'Estrelas',
  'game.badge.reason.none': 'Nenhuma estrela por enquanto: seu primeiro gesto acende o cobre.',
  'game.badge.reason.crossed': '{material}, porque você passou do limite de {threshold}: você está em {count}.',
  'game.badge.reason.served': '{material}, conquistado ao passar do limite de {threshold}.',
  'game.badge.next': 'Faltam {missing} para a próxima estrela: {material}, em {threshold}.',
  'game.badge.complete': 'As sete estrelas estão acesas: este emblema está no Prisma.',
  'game.badge.ladder_title': 'Os sete níveis',
  'game.badge.rung.upcoming': 'Em {threshold}',
  'game.badge.rung.next': 'Próxima estrela · faltam {missing}',
  'game.badge.upcoming_title': 'A seguir',
  'game.badge.guide_link': 'Entender os emblemas',
} as const satisfies GameConceptCatalog;

export default pt;
