import type { ContactCardCatalogSlice } from './catalog-fr-contact-card';

/** La carte de visite partagée (#8101) — voir `catalog-fr-contact-card.ts`. */
const arContactCard = {
  'contactCard.a11y.card': 'بطاقة جهة اتصال: {name}',
  'contactCard.open': 'عرض كل تفاصيل {name}',
  'contactCard.loading': 'جارٍ قراءة بطاقة جهة الاتصال…',
  'contactCard.unreadable': 'بطاقة جهة اتصال غير مقروءة',
  'contactCard.failed': 'تعذّرت قراءة بطاقة جهة الاتصال',
  'contactCard.retry': 'إعادة المحاولة',
  'contactCard.download': 'تنزيل البطاقة',
  'contactCard.onMeeshy': 'على Meeshy',
  'contactCard.connect': 'تواصل',
  'contactCard.write': 'راسِل',
  'contactCard.state.self': 'هذا أنت',
  'contactCard.state.requestSent': 'تم إرسال الطلب',
  'contactCard.state.requestReceived': 'أرسل إليك طلبًا',
  'contactCard.sheet.title': 'بطاقة جهة اتصال',
  'contactCard.close': 'إغلاق',
  'contactCard.copy': 'نسخ: {field}',
  'contactCard.copied': 'تم النسخ إلى الحافظة',
  'contactCard.copyFailed': 'تعذّر النسخ',
  'contactCard.copyHint': 'اضغط مطولًا أو انقر بزر الفأرة الأيمن على حقل لنسخه',
  'contactCard.avatar': 'صورة {name}',
  'contactCard.banner': 'غلاف {name}',
  'contactCard.field.phone': 'الهاتف',
  'contactCard.field.email': 'البريد الإلكتروني',
  'contactCard.field.url': 'الموقع',
  'contactCard.field.address': 'العنوان',
  'contactCard.field.birthday': 'تاريخ الميلاد',
  'contactCard.field.note': 'ملاحظة',
  'contactCard.field.organization': 'المؤسسة',
  'contactCard.field.title': 'المسمى الوظيفي',
  'contactCard.label.mobile': 'جوال',
  'contactCard.label.home': 'المنزل',
  'contactCard.label.work': 'العمل',
  'contactCard.label.main': 'رئيسي',
  'contactCard.label.iphone': 'iPhone',
  'contactCard.label.fax': 'فاكس',
  'contactCard.label.pager': 'جهاز نداء',
  'contactCard.label.other': 'آخر',
} satisfies ContactCardCatalogSlice;

export default arContactCard;
