import type { SessionsCatalog } from '@/lib/i18n-sessions-catalog';

const es = {
  'sessions.title': 'Seguridad',
  'sessions.back': 'Atrás',
  'sessions.section': 'Sesiones',
  'sessions.intro': 'Los dispositivos conectados a tu cuenta. Cierra cualquier sesión que no reconozcas.',
  'sessions.current': 'Este dispositivo',
  'sessions.trusted': 'Dispositivo de confianza',
  'sessions.unknownDevice': 'Dispositivo desconocido',
  'sessions.field.app': 'Meeshy',
  'sessions.field.platform': 'Plataforma',
  'sessions.field.device': 'Dispositivo',
  'sessions.field.system': 'Sistema',
  'sessions.field.browser': 'Navegador',
  'sessions.field.ip': 'Dirección IP',
  'sessions.field.place': 'Ubicación',
  'sessions.field.timezone': 'Zona horaria',
  'sessions.field.opened': 'Abierta el',
  'sessions.field.lastActive': 'Última actividad',
  'sessions.field.method': 'Inicio de sesión',
  'sessions.version': 'Versión {version}',
  'sessions.versionBuild': 'Versión {version} ({build})',
  'sessions.place.approximate': '{place} · aproximada',
  'sessions.platform.web': 'Navegador web',
  'sessions.platform.pwa': 'Aplicación web instalada',
  'sessions.platform.android-shell': 'Aplicación Android',
  'sessions.platform.ios': 'Aplicación iOS',
  'sessions.method.password': 'Contraseña',
  'sessions.method.two_factor': 'Contraseña y código de verificación',
  'sessions.method.magic_link': 'Enlace de acceso por correo',
  'sessions.method.registration': 'Registro',
  'sessions.method.email_verification': 'Verificación del correo',
  'sessions.method.oauth': 'Cuenta externa',
  'sessions.method.anonymous': 'Acceso sin cuenta',
  'sessions.revoke': 'Cerrar esta sesión',
  'sessions.revoke.label': 'Cerrar la sesión de {device}',
  'sessions.revoke.title': '¿Cerrar esta sesión?',
  'sessions.revoke.body': '{device} se desconectará y tendrá que volver a iniciar sesión.',
  'sessions.revoke.done': 'Sesión cerrada',
  'sessions.revoke.error': 'No se pudo cerrar la sesión. Inténtalo de nuevo.',
  'sessions.others': 'Desconectar los demás dispositivos',
  'sessions.others.title': '¿Desconectar los demás dispositivos?',
  'sessions.others.body': 'Se cerrarán todas las sesiones excepto esta.',
  'sessions.others.done.one': 'Una sesión cerrada',
  'sessions.others.done.other': '{count} sesiones cerradas',
  'sessions.others.none': 'Ningún otro dispositivo está conectado.',
  'sessions.others.error': 'No se pudieron cerrar las demás sesiones. Inténtalo de nuevo.',
  'sessions.cancel': 'Cancelar',
  'sessions.empty.title': 'Ninguna sesión activa',
  'sessions.empty.body': 'Tus dispositivos conectados aparecerán aquí.',
  'sessions.loading': 'Cargando sesiones…',
  'sessions.error.title': 'No se pudieron cargar las sesiones.',
  'sessions.error.retry': 'Reintentar',
  'sessions.offline': 'Sin conexión: la lista puede no estar actualizada y no se puede cerrar ninguna sesión.',
  'sessions.signedOut': 'Tu sesión ha caducado. Vuelve a iniciar sesión para ver tus dispositivos.',
  'sessions.attribution.note': 'Ubicaciones aproximadas, deducidas de la dirección IP.',
  'sessionEnd.title': 'Sesión cerrada',
  'sessionEnd.admin_revoke': 'El equipo de Meeshy cerró tu sesión.',
  'sessionEnd.admin_revoke.help': 'Si crees que se trata de un error, contáctanos.',
  'sessionEnd.user_revoke': 'Esta sesión se cerró desde otro de tus dispositivos.',
  'sessionEnd.password_changed': 'La contraseña de tu cuenta cambió. Inicia sesión con la nueva.',
  'sessionEnd.logout': 'Se cerró la sesión en este dispositivo.',
  'sessionEnd.logout_all_devices': 'Se cerraron todas las sesiones de tu cuenta.',
  'sessionEnd.session_expired': 'Tu sesión ha caducado. Vuelve a iniciar sesión.',
  'sessionEnd.contact': 'Contactar con el equipo',
  'sessionEnd.ok': 'Entendido',
} satisfies SessionsCatalog;

export default es;
