/**
 * LA QUALITÉ D'UN APPEL (#8047) — tranche du catalogue, RÉPANDUE par
 * `catalog-en.ts` comme `catalog-en-call-screen.ts` : l'indicateur et le
 * détail de qualité, les pastilles de survie de la vidéo et les alertes d'un
 * pair (`call-quality-indicator.tsx`, `call-screen.tsx`).
 */
const enCallQuality = {
  'call.quality.indicator': 'Call quality: {level}',
  'call.quality.level.excellent': 'excellent',
  'call.quality.level.good': 'good',
  'call.quality.level.fair': 'fair',
  'call.quality.level.poor': 'poor',
  'call.quality.detail': 'Call quality',
  'call.quality.loss': 'Packet loss',
  'call.quality.latency': 'Latency',
  'call.quality.jitter': 'Jitter',
  'call.quality.audioRate': 'Audio bitrate',
  'call.quality.videoRate': 'Video bitrate',
  'call.quality.close': 'Close call quality details',
  'call.quality.profile': 'Network',
  'call.quality.profile.wifi': 'Wi-Fi',
  'call.quality.profile.cellular': 'Mobile data',
  'call.quality.profile.economy': 'Data saver',
  'call.quality.audioCap': 'Audio cap',
  'call.quality.videoCap': 'Video cap',
  'callJournal.title': 'Quality and network',
  'callJournal.chronology': 'Timeline',
  'callJournal.summary.worstLevel': 'Lowest quality',
  'callJournal.summary.maxLoss': 'Peak packet loss',
  'callJournal.summary.maxRtt': 'Peak latency',
  'callJournal.summary.reconnections': 'Reconnections',
  'callJournal.summary.path': 'Media path',
  'callJournal.path.direct': 'Direct',
  'callJournal.path.relay': 'Through a relay',
  'callJournal.summary.end': 'End',
  'callJournal.end.local': 'Hung up',
  'callJournal.end.remote': 'Ended by the other side',
  'callJournal.end.rejected': 'Declined',
  'callJournal.end.missed': 'Unanswered',
  'callJournal.end.connectionLost': 'Connection lost',
  'callJournal.end.failed': 'Connection failed',
  'callJournal.end.busy': 'Busy',
  'callJournal.end.permission': 'Microphone or camera denied',
  'callJournal.end.removed': 'Removed from the call',
  'callJournal.event.connecting': 'Connecting',
  'callJournal.event.connected': 'Connected',
  'callJournal.event.reconnecting': 'Reconnecting',
  'callJournal.event.ended': 'Ended: {reason}',
  'callJournal.event.link': '{name}: {state}',
  'callJournal.link.connecting': 'connecting',
  'callJournal.link.connected': 'connected',
  'callJournal.link.reconnecting': 'reconnecting',
  'callJournal.event.quality': 'Quality {level}',
  'callJournal.event.frozen': 'Video slowed down (weak network)',
  'callJournal.event.suspended': 'Video paused, audio continues',
  'callJournal.event.resumed': 'Video restored',
  'callJournal.event.profile': 'Network: {profile} · voice {bitrate}',
  'callJournal.event.relay': 'Relayed through the server',
  'callJournal.event.direct': 'Direct connection',
  'call.video.frozen': 'Weak network: your video is slowed down',
  'call.video.suspended': 'Weak network: your video is paused, audio continues',
  'call.alert.weakNetwork': '{name}’s connection is unstable',
  'call.alert.capturing': '{name} is capturing the call screen',
} as const;

export default enCallQuality;
