import type { CallStudioCatalog } from '@/lib/i18n-call-studio-catalog';

/** Le studio d'un appel vidéo — en (#8551, #8552). */
const en = {
  'callStudio.effects.color': 'Color',
  'callStudio.effects.settings': 'Settings',
  'callStudio.face.none': 'None',
  'callStudio.face.smoothing': 'Skin smoothing',
  'callStudio.face.toad': 'Toad',
  'callStudio.face.angel': 'Angel',
  'callStudio.face.demon': 'Demon',
  'callStudio.face.volcano': 'Eruption',
  'callStudio.montage.screen': 'Full screen',
  'callStudio.montage.grid': 'Mosaic',
  'callStudio.montage.strip': 'Photo booth',
  'callStudio.montage.polaroid': 'Polaroid',
  'callStudio.montage.magazine': 'Magazine',
  'callStudio.montage.comic': 'Comic',
  'callStudio.montage.heart': 'Heart',
  'callStudio.capture.preview': 'Preview of the {style} layout',
  'callStudio.capture.faces': 'Each face',
  'callStudio.capture.facesLabel': 'Save each face separately',
  'callStudio.capture.saved': 'Capture saved',
  'callStudio.capture.faceSaved': '1 face saved',
  'callStudio.capture.facesSaved': '{count} faces saved',
  'callStudio.capture.failed': 'The capture could not be saved',
  'callStudio.capture.cancelled': 'Saving cancelled',
  'callStudio.capture.empty': 'Nothing to capture: no picture is showing',
  'callStudio.capture.busy': 'Capturing…',
  'callStudio.capture.bubble': 'What a call!',
  'callStudio.montage.cover': 'Cover',
  'callStudio.montage.gold': 'Gold',
  'callStudio.montage.redcarpet': 'Red carpet',
  'callStudio.montage.film': 'Film',
  'callStudio.montage.neon': 'Neon',
  'callStudio.montage.noir': 'Black & white',
  'callStudio.cover.line1': 'Call of the year',
  'callStudio.cover.line2': 'Together at last',
  'callStudio.cover.line3': 'Exclusive',
  'callStudio.mode.effects': 'My video effects',
  'callStudio.mode.montage': 'Capture the call',
  'callStudio.mode.quit': 'Exit',
  'callStudio.mode.quitEffects': 'Exit without keeping these changes',
  'callStudio.mode.validateLabel': 'Keep this effect and return to the call',
  'callStudio.mode.face': 'Face',
  'callStudio.mode.categories': 'Category',
  'callStudio.mode.pickEffect': 'Choose an effect',
  'callStudio.mode.pickMontage': 'Choose a montage',
  'callStudio.mode.settingsLabel': 'Show settings (brightness, blur)',
  'callStudio.capture.hint': 'Double tap: photo · Long press: video',
  'callStudio.capture.gestures': 'Double tap, or Enter: a photo. Long press: a video, with sound.',
  'callStudio.record.start': 'Record a video, with sound',
  'callStudio.record.stop': 'Stop the video and save it',
  'callStudio.record.saved': 'Video saved',
  'callStudio.record.failed': 'The video could not be saved',
  'callStudio.record.unsupported': 'This browser cannot record the call',
  'callStudio.record.clock': 'Recording, {time}',
  'callStudio.companions.label': 'Call participants',
  'callStudio.companions.more': '{count} more participants',
  'callStudio.companions.move': 'Move to the other side',
  'callStudio.frames.moods': 'Moods',
  'callStudio.frames.mood.classics': 'Classics',
  'callStudio.frames.mood.signature': 'Signature',
  'callStudio.frames.mood.distingue': 'Distinguished',
  'callStudio.frames.mood.elegant': 'Elegant',
  'callStudio.frames.mood.jovial': 'Cheerful',
  'callStudio.frames.mood.deconnecte': 'Unplugged',
  'callStudio.frames.mood.corporate': 'Corporate',
  'callStudio.frames.mood.fantastique': 'Fantasy',
  'callStudio.frames.mood.futuriste': 'Futuristic',
  'callStudio.frames.mood.glauque': 'Eerie',
  'callStudio.frames.mood.hors-norme': 'Offbeat',
  'callStudio.frames.mood.morbide': 'Macabre',
  'callStudio.frames.mood.feerique': 'Enchanted',
  'callStudio.mode.pickFrame': 'Choose a frame',
  'callStudio.capture.framePreview': 'Preview of the {name} frame',
} satisfies CallStudioCatalog;

export default en;
