import type { SendSheetCatalog } from '@/lib/i18n-send-sheet-catalog';

const it = {
  'sendSheet.title.forward': 'Inoltra',
  'sendSheet.title.share': 'Condividi',
  'sendSheet.title.sendTo': 'Invia a…',
  'sendSheet.cancel': 'Annulla',
  'sendSheet.caption.label': 'Messaggio',
  'sendSheet.caption.placeholder': 'Aggiungi un messaggio…',
  'sendSheet.search.label': 'Cerca una persona o una conversazione',
  'sendSheet.search.placeholder': 'Cerca una persona o una conversazione',
  'sendSheet.empty': 'Nessun risultato',
  'sendSheet.section.recent': 'Recenti',
  'sendSheet.section.people': 'Persone',
  'sendSheet.section.conversations': 'Conversazioni',
  'sendSheet.section.publish': 'Pubblica',
  'sendSheet.publish.story': 'La mia storia',
  'sendSheet.publish.post': 'Post',
  'sendSheet.publish.reel': 'Reel',
  'sendSheet.send': 'Invia',
  'sendSheet.sendCount': 'Invia ({count})',
  'sendSheet.row.select': 'Seleziona {name}',
  'sendSheet.selectedCount': '{count} selezionati',
  'sendSheet.state.sending': 'Invio…',
  'sendSheet.state.sent': 'Inviato',
  'sendSheet.state.failed': 'Non riuscito',
  'sendSheet.state.retry': 'Riprova',
  'sendSheet.state.waitingNetwork': 'In attesa di rete',
  'sendSheet.failure.download': 'Impossibile recuperare il file',
  'sendSheet.failure.refused': 'L’invio è stato rifiutato',
  'sendSheet.limit.recipients': 'Al massimo {count} destinatari',
  'sendSheet.error.captionTooLong': 'Questo messaggio è troppo lungo per essere pubblicato (al massimo {count} caratteri)',
  'sendSheet.error.tooManyFiles': 'Al massimo {count} file per pubblicazione',
  'sendSheet.moreOptions': 'Altre opzioni…',
  'sendSheet.copyLink': 'Copia link',
  'sendSheet.linkCopied': 'Link copiato',
  'sendSheet.announce.sent': 'Inviato a {count}',
  'sendSheet.preview.messages': '{count} messaggi',
  'sendSheet.preview.photo': 'Foto',
  'sendSheet.preview.video': 'Video',
  'sendSheet.preview.voice': 'Messaggio vocale',
  'sendSheet.preview.file': 'File',
  'sendSheet.preview.publication': 'Pubblicazione',
  'sendSheet.protected': 'Contenuto protetto: non può essere pubblicato',
  'shareLinkSheet.title': 'Crea un link di condivisione',
  'shareLinkSheet.empty': 'Al momento nessuna conversazione può ricevere un link.',
  'shareLinkSheet.createFailed': 'Impossibile creare il link — riprova tra un momento.',
  'shareLinkSheet.copied': 'Link copiato — non resta che incollarlo.',
  'shareLinkSheet.unavailable': 'Impossibile condividere qui. Copia l’indirizzo di questa pagina.',
} satisfies SendSheetCatalog;

export default it;
