import type { OnboardingCatalog } from '@/lib/i18n-onboarding-catalog';

const pt = {
  'onboarding.title': 'Bem-vindo ao Meeshy',
  'onboarding.skipAll': 'Saltar tudo',
  'onboarding.later': 'Mais tarde',
  'onboarding.continue': 'Continuar',
  'onboarding.progress': 'Passo {current} de {total}',
  'onboarding.offline': 'Disponível quando estiveres online',
  'onboarding.points.gauge': '{points} / {target} pts para o teu nível 1',
  'onboarding.points.level': 'Nível 1 alcançado!',
  'onboarding.points.gained': '+{points}',
  'onboarding.points.announce': 'Ganhas {points} pontos.',

  'onboarding.languages.title': 'A tua língua, o teu mundo',
  'onboarding.languages.body': 'Aqui cada um escreve na sua língua. Tu lês tudo na tua.',
  'onboarding.languages.demo.from': 'Hola, ¿qué tal?',
  'onboarding.languages.demo.fromCode': 'es',
  'onboarding.languages.demo.to': 'Olá, tudo bem?',
  'onboarding.languages.primary': 'A tua língua principal',
  'onboarding.languages.secondary': 'Uma segunda língua? (opcional)',
  'onboarding.languages.change': 'Mudar',
  'onboarding.languages.pick': 'Escolhe a tua língua principal',
  'onboarding.languages.confirm': 'É a minha língua',
  'onboarding.languages.failed': 'A tua língua não foi guardada. Tenta outra vez.',

  'onboarding.global.title': 'Diz olá ao mundo',
  'onboarding.global.body': 'O Meeshy Global é a sala onde toda a gente anda. Manda um olá, sem pressão.',
  'onboarding.global.field': 'O teu olá, editável',
  'onboarding.global.shuffle': 'Outra ideia',
  'onboarding.global.send': 'Enviar',
  'onboarding.global.sending': 'A enviar…',
  'onboarding.global.sent': 'Olá enviado!',
  'onboarding.global.failed': 'O teu olá não foi enviado. Tenta outra vez.',
  'onboarding.global.unavailable': 'O Meeshy Global não está acessível de momento.',
  'onboarding.global.badge': 'Emblema «Primeira mensagem»',
  'onboarding.global.streak': 'Sequência: 1 dia 🔥',
  'onboarding.global.reward': '+14 pts ao enviar',
  'onboarding.global.template.1': 'Olá a todos! Sou {name}, falo {languages}. Quem vive perto [[do mar]]?',
  'onboarding.global.template.2': 'Olá! {name} aqui 👋 Neste momento ouço [[rap]] sem parar. E vocês?',
  'onboarding.global.template.3': 'Oi! Chamo-me {name}. O meu prato preferido: [[massa]]. E o vosso?',
  'onboarding.global.template.4': 'Olá! {name}, acabei de chegar. Procuro pessoas que gostem de [[futebol]]!',
  'onboarding.global.template.5': 'Hey! Sou {name}. A minha pequena alegria do dia: [[o pôr do sol]].',
  'onboarding.global.template.6': 'Olá! {name} aqui, falo {languages}. Gostava de aprender [[espanhol]], alguma dica?',
  'onboarding.global.template.7': 'Olá mundo 🌍 Sou {name}. A minha paixão do momento: [[a fotografia]]. Quem mais?',
  'onboarding.global.template.8': 'Yo! {name} acabou de chegar. Onde vivo, hoje está [[um sol lindo]]. E aí?',

  'onboarding.story.title': 'Mostra-te',
  'onboarding.story.body': 'Os amigos chegam quando mostras quem és. Uma foto, uma frase: é uma story e desaparece em 24 h.',
  'onboarding.story.create': 'Criar a minha story',
  'onboarding.story.audience.public': 'Visível para todos. Podes mudar antes de publicar.',
  'onboarding.story.audience.friends': 'Visível para os teus amigos. Podes mudar antes de publicar.',
  'onboarding.story.reward': '+10 pts ao publicar',
  'onboarding.story.done': 'Story publicada!',

  'onboarding.friends.title': 'Encontra a tua malta',
  'onboarding.friends.body': 'Adiciona 3 pessoas parecidas contigo. Quando aceitarem, ganham +7 os dois.',
  'onboarding.friends.add': 'Adicionar',
  'onboarding.friends.addNamed': 'Adicionar {name}',
  'onboarding.friends.added': 'Enviado',
  'onboarding.friends.speaks': 'Fala {languages}',
  'onboarding.friends.reward': '+7 cada um quando aceitar',
  'onboarding.friends.count': '{count} / 3 pedidos',
  'onboarding.friends.empty': 'Ninguém para te sugerir por agora. O separador Descobrir vai mostrar-te pessoas em breve.',
  'onboarding.friends.failed': 'O pedido não foi enviado. Tenta outra vez.',

  'onboarding.notifications.title': 'Avisamos-te quando algo acontecer',
  'onboarding.notifications.body': 'Alguém vai responder-te. Queres saber logo?',
  'onboarding.notifications.yes': 'Sim, avisa-me',
  'onboarding.notifications.no': 'Agora não',

  'onboarding.recap.title': 'Muito bem!',
  'onboarding.recap.calm': 'Está tudo pronto. Podes fazê-lo quando quiseres.',
  'onboarding.recap.points': '+{points} pts',
  'onboarding.recap.level': 'Nível 1',
  'onboarding.recap.streak': 'Sequência 1 🔥',
  'onboarding.recap.badges': 'Emblemas: {count}',
  'onboarding.recap.friends': 'Pedidos a caminho: {count}',
  'onboarding.recap.tomorrow': 'Amanhã a tua sequência pode chegar a 2.',
  'onboarding.recap.explore': 'Continuar a explorar',
  'onboarding.recap.done': 'Chega por hoje',
} satisfies OnboardingCatalog;

export default pt;
