source "https://rubygems.org"

gem "fastlane", "~> 2.219"
gem "cocoapods", "~> 1.14"

# Ruby 4 : kconv et ostruct ont quitté la stdlib ; CFPropertyList 3.0.8 et
# fastlane 2.229 les requirent en dur.
gem "nkf"
gem "ostruct"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
