name: Meeshy
options:
  bundleIdPrefix: com.meeshy
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en

settings:
  SWIFT_VERSION: "5.0"
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"
  PRODUCT_NAME: Meeshy
  TARGETED_DEVICE_FAMILY: "1,2"

targets:
  Meeshy:
    type: application
    platform: iOS
    deploymentTarget: "16.0"

    sources:
      - path: Meeshy
        excludes:
          - "**/*.md"

    settings:
      INFOPLIST_FILE: Meeshy/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.meeshy.app
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ENABLE_PREVIEWS: YES
      CODE_SIGN_STYLE: Automatic

    scheme:
      testTargets: []
