import Foundation

/// Un son de la bibliothèque, tel que le gateway le projette.
///
/// Miroir EXACT de `toDTO` (`services/gateway/src/routes/posts/sounds.ts`) :
/// `contentHash` n'en fait pas partie et ne doit jamais y entrer — c'est un
/// oracle de possession de fichier.
public struct APISound: Codable, Identifiable, Sendable, Equatable {
    public let id: String
    /// Vide pour un son CAPTURÉ que son auteur n'a pas encore nommé. Le libellé
    /// affiché se compose alors côté client (« Son original »), jamais en base :
    /// l'y écrire graverait du français qui ressortirait dans les sept langues.
    public let title: String
    public let fileUrl: String
    public let durationMs: Int?
    public let waveform: [Float]
    /// Compte des PISTES, pas des publications : une story qui pose le son sur
    /// trois diapositives en vaut trois. Sert au classement « Tendances » côté
    /// serveur ; ne JAMAIS l'afficher tel quel — voir `postCount`.
    public let usageCount: Int
    /// Publications distinctes et visibles qui utilisent ce son. C'est ce
    /// nombre-là qui s'affiche.
    public let postCount: Int
    /// Somme des vues de ces mêmes publications. Les deux compteurs décrivent le
    /// même ensemble que la page du son, donc l'utilisateur peut les recompter.
    public let playCount: Int
    public let isPublic: Bool
    /// Capturé automatiquement à la publication, par opposition à un envoi manuel.
    public let isAutoGenerated: Bool
    /// Vignette du contenu source. Cascade d'affichage : `coverUrl`, sinon
    /// `coverThumbHash`, sinon l'avatar de l'uploadeur.
    public let coverUrl: String?
    public let coverThumbHash: String?
    public let createdAt: Date?
    /// Crédit, résolu à la LECTURE par le serveur — jamais figé dans la ligne.
    public let uploader: APISoundUploader?

    public init(id: String, title: String, fileUrl: String, durationMs: Int? = nil,
                waveform: [Float] = [], usageCount: Int = 0,
                postCount: Int = 0, playCount: Int = 0, isPublic: Bool = true,
                isAutoGenerated: Bool = false, coverUrl: String? = nil,
                coverThumbHash: String? = nil, createdAt: Date? = nil,
                uploader: APISoundUploader? = nil) {
        self.id = id; self.title = title; self.fileUrl = fileUrl
        self.durationMs = durationMs; self.waveform = waveform
        self.usageCount = usageCount
        self.postCount = postCount; self.playCount = playCount
        self.isPublic = isPublic
        self.isAutoGenerated = isAutoGenerated
        self.coverUrl = coverUrl; self.coverThumbHash = coverThumbHash
        self.createdAt = createdAt; self.uploader = uploader
    }

    /// ⚠ `CodingKeys` EXPLICITE : ajouter une propriété sans ajouter son `case`
    /// ici compile sans le moindre avertissement, et le champ ne voyage plus.
    /// `SoundModelsDecodingTests.test_decode_couvreTousLesChamps` échoue si ça
    /// arrive — c'est le seul garde-fou, ne le supprimez pas.
    enum CodingKeys: String, CodingKey {
        case id, title, fileUrl, durationMs, waveform
        case usageCount, postCount, playCount
        case isPublic, isAutoGenerated
        case coverUrl, coverThumbHash, createdAt, uploader
    }

    /// Décodage TOLÉRANT à l'absence des champs numériques et de collection.
    ///
    /// `postCount` et `playCount` sont arrivés après le reste : une app plus
    /// récente que sa gateway les recevrait absents, et le décodage synthétisé
    /// aurait fait échouer la LISTE ENTIÈRE sur deux compteurs décoratifs.
    /// Un son sans compteur s'affiche à 0, il ne disparaît pas.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        title = try c.decodeIfPresent(String.self, forKey: .title) ?? ""
        fileUrl = try c.decode(String.self, forKey: .fileUrl)
        durationMs = try c.decodeIfPresent(Int.self, forKey: .durationMs)
        waveform = try c.decodeIfPresent([Float].self, forKey: .waveform) ?? []
        usageCount = try c.decodeIfPresent(Int.self, forKey: .usageCount) ?? 0
        postCount = try c.decodeIfPresent(Int.self, forKey: .postCount) ?? 0
        playCount = try c.decodeIfPresent(Int.self, forKey: .playCount) ?? 0
        isPublic = try c.decodeIfPresent(Bool.self, forKey: .isPublic) ?? true
        isAutoGenerated = try c.decodeIfPresent(Bool.self, forKey: .isAutoGenerated) ?? false
        coverUrl = try c.decodeIfPresent(String.self, forKey: .coverUrl)
        coverThumbHash = try c.decodeIfPresent(String.self, forKey: .coverThumbHash)
        createdAt = try c.decodeIfPresent(Date.self, forKey: .createdAt)
        uploader = try c.decodeIfPresent(APISoundUploader.self, forKey: .uploader)
    }
}

public struct APISoundUploader: Codable, Identifiable, Sendable, Equatable {
    public let id: String
    public let username: String
    public let displayName: String?
    public let avatar: String?

    public init(id: String, username: String, displayName: String? = nil, avatar: String? = nil) {
        self.id = id; self.username = username
        self.displayName = displayName; self.avatar = avatar
    }
}

public extension APISound {
    /// Nom à afficher pour l'auteur — `displayName` s'il existe, sinon `@pseudo`.
    var authorLabel: String? {
        guard let uploader else { return nil }
        if let name = uploader.displayName, !name.isEmpty { return name }
        return "@\(uploader.username)"
    }

    /// Le son porte-t-il un titre donné par son auteur ?
    ///
    /// C'est cette question, et non `isAutoGenerated`, qui décide de l'affichage :
    /// un son capturé PUIS nommé doit montrer son titre, et un envoi manuel dont
    /// le titre a été vidé doit retomber sur le libellé par défaut.
    var hasAuthoredTitle: Bool {
        !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var durationSeconds: TimeInterval? {
        guard let durationMs else { return nil }
        return TimeInterval(durationMs) / 1000
    }
}
