import Foundation

/// Un son de la bibliothèque, tel que le gateway le projette.
///
/// Miroir EXACT de `toDTO` (`services/gateway/src/routes/posts/sounds.ts`) :
/// `contentHash` n'en fait pas partie et ne doit jamais y entrer — c'est un
/// oracle de possession de fichier.
public struct APISound: Codable, Identifiable, Sendable, Equatable {
    public let id: String
    /// Vide pour un son CAPTURÉ que son auteur n'a pas encore nommé. Le libellé
    /// affiché se compose alors côté client (« Son original »), jamais en base :
    /// l'y écrire graverait du français qui ressortirait dans les sept langues.
    public let title: String
    public let fileUrl: String
    public let durationMs: Int?
    public let waveform: [Float]
    public let usageCount: Int
    public let isPublic: Bool
    /// Capturé automatiquement à la publication, par opposition à un envoi manuel.
    public let isAutoGenerated: Bool
    /// Vignette du contenu source. Cascade d'affichage : `coverUrl`, sinon
    /// `coverThumbHash`, sinon l'avatar de l'uploadeur.
    public let coverUrl: String?
    public let coverThumbHash: String?
    public let createdAt: Date?
    /// Crédit, résolu à la LECTURE par le serveur — jamais figé dans la ligne.
    public let uploader: APISoundUploader?

    public init(id: String, title: String, fileUrl: String, durationMs: Int? = nil,
                waveform: [Float] = [], usageCount: Int = 0, isPublic: Bool = true,
                isAutoGenerated: Bool = false, coverUrl: String? = nil,
                coverThumbHash: String? = nil, createdAt: Date? = nil,
                uploader: APISoundUploader? = nil) {
        self.id = id; self.title = title; self.fileUrl = fileUrl
        self.durationMs = durationMs; self.waveform = waveform
        self.usageCount = usageCount; self.isPublic = isPublic
        self.isAutoGenerated = isAutoGenerated
        self.coverUrl = coverUrl; self.coverThumbHash = coverThumbHash
        self.createdAt = createdAt; self.uploader = uploader
    }
}

public struct APISoundUploader: Codable, Identifiable, Sendable, Equatable {
    public let id: String
    public let username: String
    public let displayName: String?
    public let avatar: String?

    public init(id: String, username: String, displayName: String? = nil, avatar: String? = nil) {
        self.id = id; self.username = username
        self.displayName = displayName; self.avatar = avatar
    }
}

public extension APISound {
    /// Nom à afficher pour l'auteur — `displayName` s'il existe, sinon `@pseudo`.
    var authorLabel: String? {
        guard let uploader else { return nil }
        if let name = uploader.displayName, !name.isEmpty { return name }
        return "@\(uploader.username)"
    }

    /// Le son porte-t-il un titre donné par son auteur ?
    ///
    /// C'est cette question, et non `isAutoGenerated`, qui décide de l'affichage :
    /// un son capturé PUIS nommé doit montrer son titre, et un envoi manuel dont
    /// le titre a été vidé doit retomber sur le libellé par défaut.
    var hasAuthoredTitle: Bool {
        !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var durationSeconds: TimeInterval? {
        guard let durationMs else { return nil }
        return TimeInterval(durationMs) / 1000
    }
}
