import type { AdminCatalogFragment } from './fragment';
import type fr from './audit-reglages-fr';

/* TEXTE PROVISOIRE (#8876) : le texte anglais tient lieu de traduction en attendant la passe de
   traduction du lot « audit-reglages ». Les clés sont celles du fragment français, ni plus ni moins. */
const f = {
  // ── Audit log: the screen ──────────────────────────────────────────────────
  'admin.audit.subtitle': 'Quem fez o quê, a quem e por quê: cada gesto de administração e cada leitura de conteúdo privado deixa um rastro aqui.',
  'admin.audit.list.caption': 'Registro de auditoria',
  'admin.audit.list.count': '{count} entradas',
  'admin.audit.list.empty': 'Nenhum rastro por enquanto',
  'admin.audit.list.emptyHint': 'Os gestos de administração e as leituras de conteúdo privado aparecerão aqui assim que houver.',
  'admin.audit.list.filteredEmpty': 'Nenhum rastro corresponde a esses filtros',
  'admin.audit.list.onAdmin': 'Ações de {name}',
  'admin.audit.list.onAdminGeneric': 'Ações de um único administrador',
  'admin.audit.list.onSubject': 'Ações relativas a {name}',
  'admin.audit.list.onSubjectGeneric': 'Ações relativas a um único membro',
  'admin.audit.list.onReset': 'Ver todo o rastro',
  'admin.audit.filter.family': 'Família de ações',
  'admin.audit.filter.entity': 'Item envolvido',
  'admin.audit.filter.period': 'Período',
  'admin.audit.filter.anyPeriod': 'Qualquer momento',
  'admin.audit.filter.gap': 'Este filtro ainda não lista: {actions}. Escolha «Todos» para as ver.',
  'admin.audit.col.when': 'Quando',
  'admin.audit.col.admin': 'Administrador',
  'admin.audit.col.action': 'Ação',
  'admin.audit.col.target': 'Item envolvido',
  'admin.audit.col.reason': 'Motivo',
  'admin.audit.row.open': 'Ver os detalhes: {action}',
  'admin.audit.actor.unknown': 'Sistema ou conta apagada',
  'admin.audit.badge.sovereign': 'Leitura soberana',
  'admin.audit.badge.sovereign.explain': 'Esta leitura abre conteúdo privado: é rastreada e seu motivo é mantido quando obrigatório.',

  // ── Audit log: action families ─────────────────────────────────────────────
  'admin.audit.family.sovereign': 'Leituras soberanas',
  'admin.audit.family.accounts': 'Contas',
  'admin.audit.family.security': 'Segurança e acesso',
  'admin.audit.family.roles': 'Papéis',
  'admin.audit.family.bans': 'Banimentos',
  'admin.audit.family.conversations': 'Conversas',
  'admin.audit.family.links': 'Links',
  'admin.audit.family.posts': 'Publicações',
  'admin.audit.family.broadcasts': 'Difusões',
  'admin.audit.family.agent': 'Agente',
  'admin.audit.family.reports': 'Denúncias',
  'admin.audit.family.communities': 'Comunidades',
  'admin.audit.family.settings': 'Configurações',

  // ── Audit log: kinds of item ───────────────────────────────────────────────
  'admin.audit.target.User': 'Conta',
  'admin.audit.target.Conversation': 'Conversa',
  'admin.audit.target.ConversationShareLink': 'Link de compartilhamento',
  'admin.audit.target.Community': 'Comunidade',
  'admin.audit.target.Report': 'Denúncia',
  'admin.audit.target.Post': 'Publicação',
  'admin.audit.target.Broadcast': 'Difusão',
  'admin.audit.target.TrackingLink': 'Link de rastreamento',
  'admin.audit.target.FriendRequest': 'Pedido de contato',
  'admin.audit.target.AgentLlmConfig': 'Modelo do agente',
  'admin.audit.target.Agent': 'Agente',
  'admin.audit.target.unknown': 'Elemento',

  // ── Audit log: action vocabulary ───────────────────────────────────────────
  'admin.audit.action.unknown': 'Ação não listada',
  'admin.audit.action.unknown.explain': 'Esta ação foi registrada por uma versão de gateway que este console ainda não conhece.',
  'admin.audit.action.VIEW_USER': 'Perfil de membro visualizado',
  'admin.audit.action.VIEW_USER.explain': 'Um administrador abriu a ficha de um membro. Esta leitura fica registrada.',
  'admin.audit.action.VIEW_USER_LIST': 'Lista de contas visualizada',
  'admin.audit.action.VIEW_USER_LIST.explain': 'Um administrador percorreu a lista de contas da plataforma.',
  'admin.audit.action.VIEW_AUDIT_LOG': 'Registro de auditoria visualizado',
  'admin.audit.action.VIEW_AUDIT_LOG.explain': 'Um administrador leu o registro de auditoria.',
  'admin.audit.action.CREATE_USER': 'Conta criada',
  'admin.audit.action.CREATE_USER.explain': 'Um administrador criou uma conta para um membro.',
  'admin.audit.action.UPDATE_PROFILE': 'Perfil editado',
  'admin.audit.action.UPDATE_PROFILE.explain': 'Algumas informações do perfil de um membro foram alteradas por um administrador.',
  'admin.audit.action.UPDATE_EMAIL': 'Endereço de e-mail alterado',
  'admin.audit.action.UPDATE_EMAIL.explain': 'O endereço de e-mail de uma conta foi alterado por um administrador.',
  'admin.audit.action.UPDATE_PHONE': 'Número de telefone alterado',
  'admin.audit.action.UPDATE_PHONE.explain': 'O número de telefone de uma conta foi alterado por um administrador.',
  'admin.audit.action.UPDATE_ROLE': 'Papel alterado',
  'admin.audit.action.UPDATE_ROLE.explain': 'O papel de um membro mudou e, com ele, os seus direitos de administração.',
  'admin.audit.action.UPDATE_STATUS': 'Estado da conta alterado',
  'admin.audit.action.UPDATE_STATUS.explain': 'A conta foi ativada ou desativada por um administrador.',
  'admin.audit.action.UPDATE_PREFERENCES': 'Preferências alteradas',
  'admin.audit.action.UPDATE_PREFERENCES.explain': 'Um administrador alterou uma categoria das preferências de um membro; cada valor consta nas alterações.',
  'admin.audit.action.UPLOAD_AVATAR': 'Imagem de perfil substituída',
  'admin.audit.action.UPLOAD_AVATAR.explain': 'A foto ou o banner de um membro foi substituído por um administrador.',
  'admin.audit.action.DELETE_AVATAR': 'Imagem de perfil removida',
  'admin.audit.action.DELETE_AVATAR.explain': 'A foto ou o banner de um membro foi retirado por um administrador.',
  'admin.audit.action.DEACTIVATE_USER': 'Conta desativada',
  'admin.audit.action.DEACTIVATE_USER.explain': 'O membro não pode mais entrar; seus dados são mantidos.',
  'admin.audit.action.ACTIVATE_USER': 'Conta reativada',
  'admin.audit.action.ACTIVATE_USER.explain': 'O membro pode entrar novamente.',
  'admin.audit.action.DELETE_USER': 'Conta apagada',
  'admin.audit.action.DELETE_USER.explain': 'Exclusão lógica: a conta pode ser restaurada.',
  'admin.audit.action.RESTORE_USER': 'Conta restaurada',
  'admin.audit.action.RESTORE_USER.explain': 'Uma conta excluída foi colocada de volta em serviço.',
  'admin.audit.action.BAN_USER': 'Membro banido',
  'admin.audit.action.BAN_USER.explain': 'A conta é suspensa, com um motivo e, se definido, uma data de término.',
  'admin.audit.action.UNBAN_USER': 'Banimento levantado',
  'admin.audit.action.UNBAN_USER.explain': 'A conta retoma o acesso, manualmente ou automaticamente quando o banimento expira.',
  'admin.audit.action.CHANGE_PASSWORD': 'Senha alterada',
  'admin.audit.action.CHANGE_PASSWORD.explain': 'A senha de uma conta foi alterada.',
  'admin.audit.action.RESET_PASSWORD': 'Senha redefinida',
  'admin.audit.action.RESET_PASSWORD.explain': 'Um administrador impôs uma nova senha; as sessões abertas do membro foram encerradas.',
  'admin.audit.action.ENABLE_2FA': 'Autenticação de dois fatores ativada',
  'admin.audit.action.ENABLE_2FA.explain': 'A conta agora pede um segundo fator no login.',
  'admin.audit.action.DISABLE_2FA': 'Autenticação de dois fatores desativada',
  'admin.audit.action.DISABLE_2FA.explain': 'A conta não pede mais um segundo fator no login.',
  'admin.audit.action.UNLOCK_ACCOUNT': 'Conta desbloqueada',
  'admin.audit.action.UNLOCK_ACCOUNT.explain': 'O bloqueio causado por muitas tentativas de login foi levantado.',
  'admin.audit.action.REVOKE_SESSION': 'Sessão encerrada',
  'admin.audit.action.REVOKE_SESSION.explain': 'Uma das sessões abertas do membro foi revogada: ele precisará entrar de novo nesse dispositivo.',
  'admin.audit.action.VERIFY_EMAIL': 'E-mail marcado como verificado',
  'admin.audit.action.VERIFY_EMAIL.explain': 'Um administrador registrou a prova de que o endereço de e-mail do membro está verificado.',
  'admin.audit.action.VERIFY_PHONE': 'Telefone marcado como verificado',
  'admin.audit.action.VERIFY_PHONE.explain': 'Um administrador registrou a prova de que o número de telefone do membro está verificado.',
  'admin.audit.action.VERIFY_AGE': 'Idade marcada como verificada',
  'admin.audit.action.VERIFY_AGE.explain': 'Um administrador registrou a prova de que a idade do membro está verificada.',
  'admin.audit.action.REQUEST_VERIFICATION': 'Verificação reenviada',
  'admin.audit.action.REQUEST_VERIFICATION.explain': 'Um código de verificação foi reenviado ao membro, por e-mail ou SMS; nenhuma prova é registrada.',
  'admin.audit.action.UPDATE_CONSENT': 'Consentimento alterado',
  'admin.audit.action.UPDATE_CONSENT.explain': 'Um administrador soberano registrou ou retirou, em nome do membro, a prova de um consentimento (voz, dados).',
  'admin.audit.action.ADMIN_INVITATION_STATUS_SET': 'Pedido de contato alterado',
  'admin.audit.action.ADMIN_INVITATION_STATUS_SET.explain': 'O estado de um pedido de contato entre dois membros foi alterado por um administrador.',
  'admin.audit.action.ADMIN_CONVERSATION_MESSAGES_VIEWED': 'Mensagens de conversa lidas',
  'admin.audit.action.ADMIN_CONVERSATION_MESSAGES_VIEWED.explain': 'Leitura soberana do conteúdo de uma conversa, com motivo escrito.',
  'admin.audit.action.ADMIN_CONVERSATION_UPDATED': 'Conversa editada',
  'admin.audit.action.ADMIN_CONVERSATION_UPDATED.explain': 'As configurações de uma conversa foram editadas por um administrador.',
  'admin.audit.action.ADMIN_CONVERSATION_MEMBER_ROLE_CHANGED': 'Papel do participante alterado',
  'admin.audit.action.ADMIN_CONVERSATION_MEMBER_ROLE_CHANGED.explain': 'Um administrador alterou o papel de um participante em uma conversa.',
  'admin.audit.action.ADMIN_CONVERSATION_MEMBER_REMOVED': 'Participante removido',
  'admin.audit.action.ADMIN_CONVERSATION_MEMBER_REMOVED.explain': 'Um participante foi removido de uma conversa por um administrador.',
  'admin.audit.action.ADMIN_SHARE_LINK_REVEALED': 'Link de compartilhamento revelado',
  'admin.audit.action.ADMIN_SHARE_LINK_REVEALED.explain': 'O endereço secreto de um link de compartilhamento foi exibido: ele abre a conversa.',
  'admin.audit.action.ADMIN_SHARE_LINK_CLOSED': 'Link de compartilhamento fechado',
  'admin.audit.action.ADMIN_SHARE_LINK_CLOSED.explain': 'O link não admite mais novos convidados, e os convidados que já haviam entrado foram revogados.',
  'admin.audit.action.ADMIN_SHARE_LINK_REOPENED': 'Link de compartilhamento reaberto',
  'admin.audit.action.ADMIN_SHARE_LINK_REOPENED.explain': 'O link admite convidados novamente.',
  'admin.audit.action.ADMIN_TRACKING_LINK_DEACTIVATED': 'Link de rastreamento desativado',
  'admin.audit.action.ADMIN_TRACKING_LINK_DEACTIVATED.explain': 'Os visitantes não são mais redirecionados; as estatísticas são mantidas.',
  'admin.audit.action.ADMIN_TRACKING_LINK_REACTIVATED': 'Link de rastreamento reativado',
  'admin.audit.action.ADMIN_TRACKING_LINK_REACTIVATED.explain': 'Os visitantes são redirecionados novamente.',
  'admin.audit.action.ADMIN_COMMUNITY_UPDATED': 'Comunidade editada',
  'admin.audit.action.ADMIN_COMMUNITY_UPDATED.explain': 'A ativação ou a visibilidade de uma comunidade foi alterada por um administrador.',
  'admin.audit.action.DELETE_POST': 'Publicação removida',
  'admin.audit.action.DELETE_POST.explain': 'Um conteúdo foi removido por um terceiro autorizado, não pelo seu autor: é um gesto de moderação.',
  'admin.audit.action.CREATE_BROADCAST': 'Difusão criada',
  'admin.audit.action.CREATE_BROADCAST.explain': 'Um rascunho de difusão foi criado.',
  'admin.audit.action.SEND_BROADCAST': 'Difusão enviada por email',
  'admin.audit.action.SEND_BROADCAST.explain': 'A difusão foi enviada por e-mail aos seus destinatários.',
  'admin.audit.action.SEND_BROADCAST_INAPP': 'Difusão publicada no aplicativo',
  'admin.audit.action.SEND_BROADCAST_INAPP.explain': 'A difusão foi enviada como notificação no aplicativo.',
  'admin.audit.action.DELETE_BROADCAST': 'Difusão excluída',
  'admin.audit.action.DELETE_BROADCAST.explain': 'Uma difusão foi excluída.',
  'admin.audit.action.AGENT_LLM_CONFIG_UPDATED': 'Modelo de agente alterado',
  'admin.audit.action.AGENT_LLM_CONFIG_UPDATED.explain': 'O provedor do modelo de linguagem do agente foi alterado. Gesto soberano, com motivo escrito.',
  'admin.audit.action.AGENT_FULL_RESET': 'Agente redefinido',
  'admin.audit.action.AGENT_FULL_RESET.explain': 'Todas as configurações, papéis e resumos do agente foram apagados. Gesto soberano, com motivo escrito.',
  'admin.audit.action.ADMIN_REPORT_UPDATED': 'Denúncia tratada',
  'admin.audit.action.ADMIN_REPORT_UPDATED.explain': 'O estado ou a decisão registrada de uma denúncia mudou.',
  'admin.audit.action.ADMIN_REPORT_DELETED': 'Denúncia excluída',
  'admin.audit.action.ADMIN_REPORT_DELETED.explain': 'Uma denúncia foi removida da fila de moderação.',
  'admin.audit.action.ADMIN_REPORT_ASSIGNED': 'Denúncia assumida',
  'admin.audit.action.ADMIN_REPORT_ASSIGNED.explain': 'Uma denúncia foi atribuída a um moderador.',
  'admin.audit.action.UPDATE_ENGAGEMENT_SCALE': 'Tabela de pontos alterada',
  'admin.audit.action.UPDATE_ENGAGEMENT_SCALE.explain': 'Um administrador alterou a tabela de pontos de engajamento: pontos por operação, multiplicador e limites.',

  // ── Audit log: the detail sheet ────────────────────────────────────────────
  'admin.audit.detail.action': 'Ação',
  'admin.audit.detail.when': 'Quando',
  'admin.audit.detail.admin': 'Administrador',
  'admin.audit.detail.adminAll': 'Todas as suas ações',
  'admin.audit.detail.subject': 'Membro envolvido',
  'admin.audit.detail.subjectAll': 'Todas as ações que o envolvem',
  'admin.audit.detail.target': 'Item envolvido',
  'admin.audit.detail.reason': 'Motivo',
  'admin.audit.detail.reasonNone': 'Nenhum motivo registrado para este gesto.',
  'admin.audit.detail.changes': 'Alterações',
  'admin.audit.detail.changesNone': 'Este gesto não registrou nenhuma alteração.',
  'admin.audit.detail.changesCaption': 'Alterações registradas para esta entrada',
  'admin.audit.detail.colField': 'Campo',
  'admin.audit.detail.colBefore': 'Antes',
  'admin.audit.detail.colAfter': 'Depois',
  'admin.audit.detail.network': 'Conexão do administrador',
  'admin.audit.detail.ip': 'Endereço IP',
  'admin.audit.detail.agent': 'Navegador e dispositivo',
  'admin.audit.detail.entryId': 'Identificador de entrada',
  'admin.audit.detail.targetId': 'Identificador de item',
  'admin.audit.change.none': 'Sem valor',
  'admin.audit.change.masked': 'Valor mascarado',
  'admin.audit.ua.on': '{browser} em {os}',
  'admin.audit.ua.unrecognized': 'Navegador não reconhecido',

  // ── Audit log: changed fields ──────────────────────────────────────────────
  'admin.audit.field.firstName': 'Primeiro nome',
  'admin.audit.field.lastName': 'Sobrenome',
  'admin.audit.field.displayName': 'Nome de exibição',
  'admin.audit.field.username': 'Nome de usuário',
  'admin.audit.field.bio': 'Biografia',
  'admin.audit.field.email': 'Endereço de e-mail',
  'admin.audit.field.phoneNumber': 'Número de telefone',
  'admin.audit.field.role': 'Papel',
  'admin.audit.field.isActive': 'Ativo',
  'admin.audit.field.twoFactorEnabled': 'Autenticação de dois fatores',
  'admin.audit.field.emailVerified': 'E-mail verificado',
  'admin.audit.field.phoneVerified': 'Telefone verificado',
  'admin.audit.field.ageVerified': 'Idade verificada',
  'admin.audit.field.unlock': 'Bloqueio',
  'admin.audit.field.verificationRequested': 'Verificação reenviada',
  'admin.audit.field.voiceProfile': 'Consentimento do perfil de voz',
  'admin.audit.field.voiceData': 'Consentimento de dados de voz',
  'admin.audit.field.dataProcessing': 'Consentimento de processamento de dados',
  'admin.audit.field.avatar': 'Foto de perfil',
  'admin.audit.field.banner': 'Banner',
  'admin.audit.field.systemLanguage': 'Idioma principal',
  'admin.audit.field.regionalLanguage': 'Idioma regional',
  'admin.audit.field.customDestinationLanguage': 'Idioma de destino',
  'admin.audit.field.timezone': 'Fuso horário',
  'admin.audit.field.status': 'Estado',
  'admin.audit.field.isPrivate': 'Privado',
  'admin.audit.field.closed': 'Fechado para escrita',
  'admin.audit.field.title': 'Título',
  'admin.audit.field.name': 'Nome',
  'admin.audit.field.description': 'Descrição',
  'admin.audit.field.type': 'Tipo',
  'admin.audit.field.reportType': 'Motivo da denúncia',
  'admin.audit.field.reportedType': 'Tipo de item denunciado',
  'admin.audit.field.configs': 'Configurações apagadas',
  'admin.audit.field.roles': 'Papéis apagados',
  'admin.audit.field.summaries': 'Resumos apagados',
  'admin.audit.field.analytics': 'Análises apagadas',
  'admin.audit.field.globalProfiles': 'Perfis globais apagados',
  'admin.audit.field.redisKeys': 'Chaves de cache apagadas',
  'admin.audit.field.value': 'Valor',

  // ── Settings ───────────────────────────────────────────────────────────────
  'admin.settings.subtitle': 'Seu acesso, recalculando os contadores do painel e suas preferências de exibição.',
  'admin.settings.access.title': 'Seu acesso',
  'admin.settings.access.intro': 'O que o seu papel permite que você faça na administração. Os direitos são decididos pela plataforma, não por esta tela.',
  'admin.settings.access.role': 'Seu papel',
  'admin.settings.access.granted': 'Concedido',
  'admin.settings.access.denied': 'Não concedido',
  'admin.settings.access.opens': 'Abre: {sections}',
  'admin.settings.access.wouldOpen': 'Abriria: {sections}',
  'admin.settings.access.opensNothing': 'Não abre nenhuma seção por conta própria.',
  'admin.settings.access.list': 'Seus direitos, um a um',
  'admin.settings.cap.canAccessAdmin.label': 'Entrar na administração',
  'admin.settings.cap.canAccessAdmin.explain': 'A porta de entrada: sem ela, nenhuma seção abre.',
  'admin.settings.cap.canManageUsers.label': 'Gerenciar contas',
  'admin.settings.cap.canManageUsers.explain': 'Ler perfis de membros, editar suas informações, bani-los ou desbloqueá-los.',
  'admin.settings.cap.canManageGroups.label': 'Gerenciar comunidades',
  'admin.settings.cap.canManageGroups.explain': 'Explorar as comunidades e seus membros, ativá-las ou desativá-las.',
  'admin.settings.cap.canManageConversations.label': 'Gerenciar conversas',
  'admin.settings.cap.canManageConversations.explain': 'Explorar as conversas e os links de compartilhamento, editar suas configurações e remover participantes.',
  'admin.settings.cap.canViewAnalytics.label': 'Ler estatísticas',
  'admin.settings.cap.canViewAnalytics.explain': 'Ver a atividade da plataforma, as classificações, as campanhas e a saúde dos serviços.',
  'admin.settings.cap.canModerateContent.label': 'Moderar conteúdo',
  'admin.settings.cap.canModerateContent.explain': 'Tratar denúncias e remover publicações.',
  'admin.settings.cap.canViewAuditLogs.label': 'Ler o registro de auditoria',
  'admin.settings.cap.canViewAuditLogs.explain': 'Ver quem fez o quê, a quem e por quê na administração.',
  'admin.settings.cap.canManageNotifications.label': 'Gerenciar difusões',
  'admin.settings.cap.canManageNotifications.explain': 'Preparar e enviar difusões e recalcular os contadores do painel.',
  'admin.settings.cap.canManageTranslations.label': 'Gerenciar traduções',
  'admin.settings.cap.canManageTranslations.explain': 'Reservado à gestão das traduções; hoje nenhuma seção da administração depende dele.',
  'admin.settings.cap.canManageAgent.label': 'Conduzir o agente',
  'admin.settings.cap.canManageAgent.explain': 'Configurar e observar o agente conversacional.',
  'admin.settings.sovereign.title': 'Gestos reservados ao criador',
  'admin.settings.sovereign.intro': 'Estes gestos abrem conteúdo privado ou afetam toda a plataforma: exigem o nível de criador, quase sempre um motivo escrito, e deixam um rastro no registro de auditoria.',
  'admin.settings.sovereign.readMessages': 'Ler as mensagens de uma conversa privada',
  'admin.settings.sovereign.listConversations': 'Explorar todas as conversas da plataforma',
  'admin.settings.sovereign.revealLink': 'Revelar o endereço secreto de um link de compartilhamento',
  'admin.settings.sovereign.consents': 'Registrar ou retirar um consentimento em nome de um membro',
  'admin.settings.sovereign.agentModel': 'Alterar o modelo do agente',
  'admin.settings.sovereign.agentReset': 'Redefinir todo o agente',
  'admin.settings.dash.title': 'Contadores do painel',
  'admin.settings.dash.body': 'A plataforma guarda em memória os contadores do painel por dez minutos. Recalcule-os para ver números atualizados imediatamente.',
  'admin.settings.dash.action': 'Recalcular agora',
  'admin.settings.dash.busy': 'Recalculando…',
  'admin.settings.dash.done': 'Contadores recalculados',
  'admin.settings.space.title': 'Espaço de administração',
  'admin.settings.space.folded': 'Menu lateral dobrado por padrão',
  'admin.settings.space.foldedHint': 'Em telas grandes, o menu lateral começa reduzido aos seus ícones. Esta configuração é própria deste navegador e se aplica na próxima vez que você abrir a administração.',
  'admin.settings.space.foldedOn': 'O menu começará recolhido',
  'admin.settings.space.foldedOff': 'O menu começará expandido',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
