/**
 * LE FRAGMENT « classement-supervision » DU CATALOGUE D’ADMINISTRATION (#8876) — le
 * classement (`admin.ranking.`) et la supervision de la plateforme
 * (`admin.monitoring.`). Les libellés de critères disent ce que la passerelle COMPTE,
 * pas ce que son nom technique laisse croire : `communities_created` compte des
 * conversations de groupe, jamais des communautés.
 */
const f = {
  'admin.ranking.subtitle': 'Les plus actifs de la plateforme : membres, conversations, messages et liens, sur la période choisie.',

  'admin.ranking.entity.label': 'Ce qu’on classe',
  'admin.ranking.entity.users': 'Membres',
  'admin.ranking.entity.conversations': 'Conversations',
  'admin.ranking.entity.messages': 'Messages',
  'admin.ranking.entity.links': 'Liens',

  'admin.ranking.criterion.label': 'Critère',
  'admin.ranking.criterion.users.messages_sent': 'Messages envoyés',
  'admin.ranking.criterion.users.reactions_given': 'Réactions données',
  'admin.ranking.criterion.users.reactions_received': 'Réactions reçues',
  'admin.ranking.criterion.users.replies_received': 'Réponses reçues',
  'admin.ranking.criterion.users.mentions_received': 'Mentions reçues',
  'admin.ranking.criterion.users.mentions_sent': 'Mentions envoyées',
  'admin.ranking.criterion.users.conversations_joined': 'Conversations rejointes',
  'admin.ranking.criterion.users.communities_created': 'Conversations de groupe créées',
  'admin.ranking.criterion.users.share_links_created': 'Liens de partage créés',
  'admin.ranking.criterion.users.files_shared': 'Fichiers partagés',
  'admin.ranking.criterion.users.reports_sent': 'Signalements envoyés',
  'admin.ranking.criterion.users.reports_received': 'Signalements reçus',
  'admin.ranking.criterion.users.friend_requests_sent': 'Demandes de contact envoyées',
  'admin.ranking.criterion.users.friend_requests_received': 'Demandes de contact reçues',
  'admin.ranking.criterion.users.calls_initiated': 'Appels lancés',
  'admin.ranking.criterion.users.call_participations': 'Participations à un appel',
  'admin.ranking.criterion.users.most_referrals_via_affiliate': 'Parrainages par affiliation',
  'admin.ranking.criterion.users.most_referrals_via_sharelinks': 'Arrivées par ses liens de partage',
  'admin.ranking.criterion.users.most_contacts': 'Contacts (amis acceptés)',
  'admin.ranking.criterion.users.most_tracking_links_created': 'Liens de suivi créés',
  'admin.ranking.criterion.users.most_tracking_link_clicks': 'Clics sur ses liens de suivi',
  'admin.ranking.criterion.conversations.message_count': 'Messages échangés',
  'admin.ranking.criterion.conversations.member_count': 'Membres actifs',
  'admin.ranking.criterion.conversations.reaction_count': 'Réactions',
  'admin.ranking.criterion.conversations.files_shared': 'Fichiers partagés',
  'admin.ranking.criterion.conversations.call_count': 'Appels',
  'admin.ranking.criterion.conversations.recent_activity': 'Activité la plus récente',
  'admin.ranking.criterion.messages.most_reactions': 'Les plus réagis',
  'admin.ranking.criterion.messages.most_replies': 'Les plus commentés',
  'admin.ranking.criterion.messages.most_mentions': 'Les plus mentionnés',
  'admin.ranking.criterion.links.tracking_links_most_visited': 'Liens de suivi les plus cliqués',
  'admin.ranking.criterion.links.tracking_links_most_unique': 'Liens de suivi aux plus de visiteurs distincts',
  'admin.ranking.criterion.links.share_links_most_used': 'Liens de partage les plus utilisés',
  'admin.ranking.criterion.links.share_links_most_unique_sessions': 'Liens de partage aux plus de sessions distinctes',

  'admin.ranking.period.label': 'Période',
  'admin.ranking.period.1d': 'Dernières 24 heures',
  'admin.ranking.period.7d': '7 derniers jours',
  'admin.ranking.period.30d': '30 derniers jours',
  'admin.ranking.period.60d': '60 derniers jours',
  'admin.ranking.period.90d': '90 derniers jours',
  'admin.ranking.period.180d': '6 derniers mois',
  'admin.ranking.period.365d': '12 derniers mois',
  'admin.ranking.period.all': 'Depuis toujours',
  'admin.ranking.periodNone': 'Ce critère porte sur tout l’historique : la période ne s’applique pas.',
  'admin.ranking.periodCreation': 'La période retient les liens créés pendant cette durée, quelle que soit la date des clics.',

  'admin.ranking.limit.label': 'Nombre de lignes',
  'admin.ranking.limit.option': 'Top {count}',
  'admin.ranking.count': '{count} dans ce classement',

  'admin.ranking.podium.title': 'Les trois premiers',
  'admin.ranking.table.title': 'Classement',
  'admin.ranking.table.titleRest': 'Du 4e rang au dernier',
  'admin.ranking.table.caption': 'Classement : {criterion}, {period}',
  'admin.ranking.rank': 'Rang {rank}',

  'admin.ranking.col.rank': 'Rang',
  'admin.ranking.col.entity.users': 'Membre',
  'admin.ranking.col.entity.conversations': 'Conversation',
  'admin.ranking.col.entity.messages': 'Message',
  'admin.ranking.col.entity.trackingLinks': 'Lien de suivi',
  'admin.ranking.col.entity.shareLinks': 'Lien de partage',
  'admin.ranking.col.creator': 'Créé par',
  'admin.ranking.col.lastActivity': 'Dernière activité',
  'admin.ranking.col.created': 'Créé',

  'admin.ranking.message.label': 'Message de {sender} dans {conversation}',
  'admin.ranking.message.meta': '{date} · {type}',
  'admin.ranking.trackingLink.to': 'Lien vers {host}',

  'admin.ranking.empty': 'Aucun résultat pour ce classement',
  'admin.ranking.empty.hint.period': 'Aucune activité n’a été comptée sur cette période.',
  'admin.ranking.empty.hint.all': 'Rien n’a encore été compté pour ce critère.',
  'admin.ranking.widen': 'Voir toute la période',

  'admin.monitoring.subtitle': 'La santé de la plateforme en un coup d’œil, et l’usage réel des adresses de l’API.',
  'admin.monitoring.tabs.label': 'Sections de la supervision',
  'admin.monitoring.tab.health': 'Santé',
  'admin.monitoring.tab.routes': 'Usage des routes',
  'admin.monitoring.refresh': 'Actualiser',
  'admin.monitoring.refreshing': 'Actualisation…',

  'admin.monitoring.health.measured': 'Dernière mesure',
  'admin.monitoring.health.auto': 'Actualisation automatique toutes les 30 secondes tant que l’écran est visible.',
  'admin.monitoring.health.allGood': 'Tous les services répondent normalement.',
  'admin.monitoring.health.issue.database': 'La base de données ne répond pas.',
  'admin.monitoring.health.issue.redis': 'Redis ne répond pas : le cache et les limites de débit sont dégradés.',
  'admin.monitoring.health.issue.translator': 'Le service de traduction est injoignable.',
  'admin.monitoring.health.issue.breakersOpen': 'Coupe-circuits ouverts : {count}. Les appels vers ces services sont refusés.',
  'admin.monitoring.health.issue.breakersHalfOpen': 'Coupe-circuits en essai : {count}. Ils laissent passer quelques appels pour vérifier que le service est rétabli.',

  'admin.monitoring.gateway.title': 'Passerelle',
  'admin.monitoring.gateway.uptime': 'Temps de fonctionnement',
  'admin.monitoring.gateway.uptime.caption': 'Depuis le dernier démarrage de la passerelle.',
  'admin.monitoring.gateway.heap': 'Mémoire utilisée',
  'admin.monitoring.gateway.heap.caption': 'sur {total} alloués au processus',
  'admin.monitoring.gateway.rss': 'Mémoire occupée',
  'admin.monitoring.gateway.rss.caption': 'Ce que le système réserve au processus.',

  'admin.monitoring.data.title': 'Données',
  'admin.monitoring.database.title': 'Base de données',
  'admin.monitoring.redis.title': 'Redis (cache)',
  'admin.monitoring.dependency.latency': 'Temps de réponse',
  'admin.monitoring.dependency.noAnswer': 'Aucune réponse',

  'admin.monitoring.realtime.title': 'Temps réel',
  'admin.monitoring.realtime.connections': 'Connexions ouvertes',
  'admin.monitoring.realtime.connections.caption': 'Une personne peut avoir plusieurs appareils connectés.',
  'admin.monitoring.realtime.users': 'Comptes connectés',
  'admin.monitoring.realtime.messages': 'Messages traités',
  'admin.monitoring.realtime.messages.caption': 'Depuis le démarrage de la passerelle.',
  'admin.monitoring.realtime.translations': 'Traductions envoyées',
  'admin.monitoring.realtime.errors': 'Erreurs',

  'admin.monitoring.translator.title': 'Traduction',
  'admin.monitoring.translator.unreachable': 'Service de traduction injoignable',
  'admin.monitoring.translator.unreachable.hint': 'Aucune statistique de traduction n’est disponible pour le moment.',
  'admin.monitoring.translator.sent': 'Demandes envoyées',
  'admin.monitoring.translator.received': 'Réponses reçues',
  'admin.monitoring.translator.errors': 'Erreurs',
  'admin.monitoring.translator.poolFull': 'Refus, file pleine',
  'admin.monitoring.translator.poolFull.caption': 'Demandes refusées faute de place dans la file.',
  'admin.monitoring.translator.avgTime': 'Temps de traitement moyen',
  'admin.monitoring.translator.cacheHit': 'Réponses tirées du cache',
  'admin.monitoring.translator.cacheHit.caption': 'Part des traductions déjà connues.',
  'admin.monitoring.translator.memory': 'Mémoire côté passerelle',
  'admin.monitoring.translator.memory.caption': 'Mesurée dans la passerelle, qui pilote les demandes de traduction.',
  'admin.monitoring.translator.uptime': 'Durée de suivi',
  'admin.monitoring.translator.uptime.caption': 'Depuis quand ces statistiques sont comptées.',

  'admin.monitoring.breakers.title': 'Coupe-circuits',
  'admin.monitoring.breakers.intro': 'Un coupe-circuit protège la plateforme d’un service en panne : ouvert, il refuse les appels le temps que le service se rétablisse.',
  'admin.monitoring.breakers.failures': 'Échecs',
  'admin.monitoring.breakers.successes': 'Succès',
  'admin.monitoring.breakers.lastFailure': 'Dernier échec',
  'admin.monitoring.breakers.never': 'Aucun échec',
  'admin.monitoring.breakers.empty': 'Aucun coupe-circuit enregistré',
  'admin.monitoring.breakers.emptyHint': 'Ils apparaissent dès qu’un service protégé est appelé.',

  'admin.monitoring.presence.title': 'Présence',
  'admin.monitoring.presence.total': 'Mises à jour demandées',
  'admin.monitoring.presence.throttled': 'Écrêtées',
  'admin.monitoring.presence.throttled.caption': 'Ignorées parce qu’elles arrivaient trop vite.',
  'admin.monitoring.presence.rate': 'Taux d’écrêtage',

  'admin.monitoring.routes.scope.label': 'Portée',
  'admin.monitoring.routes.scope.watched': 'Routes surveillées',
  'admin.monitoring.routes.scope.all': 'Toutes les routes',
  'admin.monitoring.routes.search': 'Filtrer par route',
  'admin.monitoring.routes.limit.label': 'Lignes du détail',
  'admin.monitoring.routes.limit.option': '{count} lignes',
  'admin.monitoring.routes.notInstrumented': 'La mesure n’est pas installée sur cette instance : les zéros ci-dessous ne prouvent rien.',
  'admin.monitoring.routes.saturated': 'La mesure est saturée : {count} échantillons n’ont pas été ventilés par plateforme et version. Les totaux des routes surveillées restent exacts.',
  'admin.monitoring.routes.truncated': '{shown} lignes affichées sur {total}. Affinez le filtre pour voir les autres.',
  'admin.monitoring.routes.observingSince': 'Observation depuis',
  'admin.monitoring.routes.observedFor': 'Durée observée',
  'admin.monitoring.routes.window': 'Fenêtre de mesure',
  'admin.monitoring.routes.window.caption': 'Les comptes portent sur cette fenêtre glissante.',

  'admin.monitoring.routes.watched.title': 'Routes surveillées',
  'admin.monitoring.routes.watched.intro': 'Adresses en voie de retrait : zéro appel observé autorise le retrait, à condition de lire les angles morts plus bas.',
  'admin.monitoring.routes.watched.caption': 'Routes surveillées et leur trafic',
  'admin.monitoring.routes.watched.empty': 'Aucune route surveillée ne correspond',
  'admin.monitoring.routes.col.method': 'Méthode',
  'admin.monitoring.routes.col.route': 'Route',
  'admin.monitoring.routes.col.issue': 'Issue liée',
  'admin.monitoring.routes.col.verdict': 'Verdict',
  'admin.monitoring.routes.col.calls': 'Appels',
  'admin.monitoring.routes.col.lastSeen': 'Dernier appel',
  'admin.monitoring.routes.col.platform': 'Plateforme',
  'admin.monitoring.routes.col.version': 'Version',
  'admin.monitoring.routes.issue': 'Issue n° {issue}',
  'admin.monitoring.routes.neverSeen': 'Jamais',

  'admin.monitoring.routes.verdict.unmounted': 'Adresse introuvable',
  'admin.monitoring.routes.verdict.unmounted.explain': 'Cette adresse n’est plus montée : son zéro ne prouve rien sur ses appelants.',
  'admin.monitoring.routes.verdict.unchecked': 'Non vérifiée',
  'admin.monitoring.routes.verdict.unchecked.explain': 'La table de routage n’a pas encore été confrontée à cette adresse.',
  'admin.monitoring.routes.verdict.unused': 'Jamais appelée',
  'admin.monitoring.routes.verdict.unused.explain': 'Observée sans aucun appel depuis le début de l’observation.',
  'admin.monitoring.routes.verdict.used': 'Encore appelée',
  'admin.monitoring.routes.verdict.used.explain': 'Au moins un appel a été observé : ne la retirez pas encore.',

  'admin.monitoring.routes.entries.title': 'Détail par plateforme et version',
  'admin.monitoring.routes.entries.caption': 'Usage des routes par plateforme et version',
  'admin.monitoring.routes.entries.empty': 'Aucun appel observé pour ce filtre',
  'admin.monitoring.routes.platform.all': 'Toutes plateformes',
  'admin.monitoring.routes.platform.absent': 'Non déclarée',
  'admin.monitoring.routes.platform.bot': 'Robot d’indexation',
  'admin.monitoring.routes.platform.script': 'Script ou outil en ligne de commande',
  'admin.monitoring.routes.platform.other': 'Autre',
  'admin.monitoring.routes.version.all': 'Toutes versions',
  'admin.monitoring.routes.version.absent': 'Non communiquée',
  'admin.monitoring.routes.version.invalid': 'Illisible',

  'admin.monitoring.routes.blind.title': 'Angles morts de la mesure',
  'admin.monitoring.routes.blind.intro': 'Ce que ce compteur ne voit pas : un zéro se lit avec ces limites.',
  'admin.monitoring.routes.blind.noVersion': 'Web et Android n’envoient pas leur version',
  'admin.monitoring.routes.blind.noVersion.explain': 'Seul iOS annonce sa version : tout le trafic web et Android arrive « version non communiquée ». Un zéro prouve l’absence d’une plateforme, jamais l’extinction d’une version.',
  'admin.monitoring.routes.blind.instanceMemory': 'Mesure en mémoire, par instance',
  'admin.monitoring.routes.blind.instanceMemory.explain': 'Elle repart de zéro au redémarrage et ne totalise pas les répliques : un zéro ne vaut que pour cette instance depuis le début de l’observation.',
  'admin.monitoring.routes.blind.clientCache': 'Réponses servies depuis un cache',
  'admin.monitoring.routes.blind.clientCache.explain': 'Une réponse servie par le navigateur ou par le service worker n’atteint jamais la passerelle et n’est donc pas comptée ; une requête conditionnelle, elle, l’est.',
  'admin.monitoring.routes.blind.socket': 'Temps réel non mesuré',
  'admin.monitoring.routes.blind.socket.explain': 'Les trames WebSocket ne produisent pas de réponse HTTP : un événement déprécié ne se mesure pas ici.',
  'admin.monitoring.routes.blind.retired': 'Routes déjà retirées',
  'admin.monitoring.routes.blind.retired.explain': 'Une requête qui ne correspond à aucune route est comptée à part, sans son adresse : on ne sait pas quelle route retirée est encore appelée.',
  'admin.monitoring.routes.blind.saturation': 'Ventilation limitée sous saturation',
  'admin.monitoring.routes.blind.saturation.explain': 'Au-delà d’un plafond, les nouvelles ventilations par plateforme et version sont refusées ; les totaux des routes surveillées, eux, restent exacts.',
  'admin.monitoring.routes.blind.other': 'Autre limite signalée',
} as const;

export default f;
