import type { AdminCatalogFragment } from './fragment';
import type fr from './classement-supervision-fr';

const f = {
  'admin.ranking.subtitle': 'The most active on the platform: members, conversations, messages and links, over the chosen period.',

  'admin.ranking.entity.label': 'What to rank',
  'admin.ranking.entity.users': 'Members',
  'admin.ranking.entity.conversations': 'Conversations',
  'admin.ranking.entity.messages': 'Messages',
  'admin.ranking.entity.links': 'Links',

  'admin.ranking.criterion.label': 'Criterion',
  'admin.ranking.criterion.users.messages_sent': 'Messages sent',
  'admin.ranking.criterion.users.reactions_given': 'Reactions given',
  'admin.ranking.criterion.users.reactions_received': 'Reactions received',
  'admin.ranking.criterion.users.replies_received': 'Replies received',
  'admin.ranking.criterion.users.mentions_received': 'Mentions received',
  'admin.ranking.criterion.users.mentions_sent': 'Mentions sent',
  'admin.ranking.criterion.users.conversations_joined': 'Conversations joined',
  'admin.ranking.criterion.users.communities_created': 'Group conversations created',
  'admin.ranking.criterion.users.share_links_created': 'Share links created',
  'admin.ranking.criterion.users.files_shared': 'Files shared',
  'admin.ranking.criterion.users.reports_sent': 'Reports sent',
  'admin.ranking.criterion.users.reports_received': 'Reports received',
  'admin.ranking.criterion.users.friend_requests_sent': 'Contact requests sent',
  'admin.ranking.criterion.users.friend_requests_received': 'Contact requests received',
  'admin.ranking.criterion.users.calls_initiated': 'Calls started',
  'admin.ranking.criterion.users.call_participations': 'Call participations',
  'admin.ranking.criterion.users.most_referrals_via_affiliate': 'Affiliate referrals',
  'admin.ranking.criterion.users.most_referrals_via_sharelinks': 'Arrivals through their share links',
  'admin.ranking.criterion.users.most_contacts': 'Contacts (accepted friends)',
  'admin.ranking.criterion.users.most_tracking_links_created': 'Tracking links created',
  'admin.ranking.criterion.users.most_tracking_link_clicks': 'Clicks on their tracking links',
  'admin.ranking.criterion.conversations.message_count': 'Messages exchanged',
  'admin.ranking.criterion.conversations.member_count': 'Active members',
  'admin.ranking.criterion.conversations.reaction_count': 'Reactions',
  'admin.ranking.criterion.conversations.files_shared': 'Files shared',
  'admin.ranking.criterion.conversations.call_count': 'Calls',
  'admin.ranking.criterion.conversations.recent_activity': 'Most recent activity',
  'admin.ranking.criterion.messages.most_reactions': 'Most reacted to',
  'admin.ranking.criterion.messages.most_replies': 'Most replied to',
  'admin.ranking.criterion.messages.most_mentions': 'Most mentioned',
  'admin.ranking.criterion.links.tracking_links_most_visited': 'Most clicked tracking links',
  'admin.ranking.criterion.links.tracking_links_most_unique': 'Tracking links with the most distinct visitors',
  'admin.ranking.criterion.links.share_links_most_used': 'Most used share links',
  'admin.ranking.criterion.links.share_links_most_unique_sessions': 'Share links with the most distinct sessions',

  'admin.ranking.period.label': 'Period',
  'admin.ranking.period.1d': 'Last 24 hours',
  'admin.ranking.period.7d': 'Last 7 days',
  'admin.ranking.period.30d': 'Last 30 days',
  'admin.ranking.period.60d': 'Last 60 days',
  'admin.ranking.period.90d': 'Last 90 days',
  'admin.ranking.period.180d': 'Last 6 months',
  'admin.ranking.period.365d': 'Last 12 months',
  'admin.ranking.period.all': 'All time',
  'admin.ranking.periodNone': 'This criterion covers the whole history: the period does not apply.',
  'admin.ranking.periodCreation': 'The period keeps the links created during it, whatever the date of the clicks.',

  'admin.ranking.limit.label': 'Number of rows',
  'admin.ranking.limit.option': 'Top {count}',
  'admin.ranking.count': '{count} in this ranking',

  'admin.ranking.podium.title': 'The top three',
  'admin.ranking.table.title': 'Ranking',
  'admin.ranking.table.titleRest': 'From 4th place to the last',
  'admin.ranking.table.caption': 'Ranking: {criterion}, {period}',
  'admin.ranking.rank': 'Rank {rank}',

  'admin.ranking.col.rank': 'Rank',
  'admin.ranking.col.entity.users': 'Member',
  'admin.ranking.col.entity.conversations': 'Conversation',
  'admin.ranking.col.entity.messages': 'Message',
  'admin.ranking.col.entity.trackingLinks': 'Tracking link',
  'admin.ranking.col.entity.shareLinks': 'Share link',
  'admin.ranking.col.creator': 'Created by',
  'admin.ranking.col.lastActivity': 'Last activity',
  'admin.ranking.col.created': 'Created',

  'admin.ranking.message.label': 'Message from {sender} in {conversation}',
  'admin.ranking.message.meta': '{date} · {type}',
  'admin.ranking.trackingLink.to': 'Link to {host}',

  'admin.ranking.empty': 'No result for this ranking',
  'admin.ranking.empty.hint.period': 'No activity was counted over this period.',
  'admin.ranking.empty.hint.all': 'Nothing has been counted yet for this criterion.',
  'admin.ranking.widen': 'See all time',

  'admin.monitoring.subtitle': 'The health of the platform at a glance, and the real usage of the API addresses.',
  'admin.monitoring.tabs.label': 'Monitoring sections',
  'admin.monitoring.tab.health': 'Health',
  'admin.monitoring.tab.routes': 'Route usage',
  'admin.monitoring.refresh': 'Refresh',
  'admin.monitoring.refreshing': 'Refreshing…',

  'admin.monitoring.health.measured': 'Last measured',
  'admin.monitoring.health.auto': 'Refreshes automatically every 30 seconds while the screen is visible.',
  'admin.monitoring.health.allGood': 'All services are responding normally.',
  'admin.monitoring.health.issue.database': 'The database is not responding.',
  'admin.monitoring.health.issue.redis': 'Redis is not responding: the cache and the rate limits are degraded.',
  'admin.monitoring.health.issue.translator': 'The translation service is unreachable.',
  'admin.monitoring.health.issue.breakersOpen': 'Open circuit breakers: {count}. Calls to these services are refused.',
  'admin.monitoring.health.issue.breakersHalfOpen': 'Circuit breakers on trial: {count}. They let a few calls through to check that the service has recovered.',

  'admin.monitoring.gateway.title': 'Gateway',
  'admin.monitoring.gateway.uptime': 'Uptime',
  'admin.monitoring.gateway.uptime.caption': 'Since the gateway last started.',
  'admin.monitoring.gateway.heap': 'Memory in use',
  'admin.monitoring.gateway.heap.caption': 'out of {total} allocated to the process',
  'admin.monitoring.gateway.rss': 'Memory held',
  'admin.monitoring.gateway.rss.caption': 'What the system reserves for the process.',

  'admin.monitoring.data.title': 'Data',
  'admin.monitoring.database.title': 'Database',
  'admin.monitoring.redis.title': 'Redis (cache)',
  'admin.monitoring.dependency.latency': 'Response time',
  'admin.monitoring.dependency.noAnswer': 'No answer',

  'admin.monitoring.realtime.title': 'Real time',
  'admin.monitoring.realtime.connections': 'Open connections',
  'admin.monitoring.realtime.connections.caption': 'A person can have several connected devices.',
  'admin.monitoring.realtime.users': 'Connected accounts',
  'admin.monitoring.realtime.messages': 'Messages processed',
  'admin.monitoring.realtime.messages.caption': 'Since the gateway started.',
  'admin.monitoring.realtime.translations': 'Translations sent',
  'admin.monitoring.realtime.errors': 'Errors',

  'admin.monitoring.translator.title': 'Translation',
  'admin.monitoring.translator.unreachable': 'Translation service unreachable',
  'admin.monitoring.translator.unreachable.hint': 'No translation statistics are available right now.',
  'admin.monitoring.translator.sent': 'Requests sent',
  'admin.monitoring.translator.received': 'Responses received',
  'admin.monitoring.translator.errors': 'Errors',
  'admin.monitoring.translator.poolFull': 'Refusals, queue full',
  'admin.monitoring.translator.poolFull.caption': 'Requests refused for lack of room in the queue.',
  'admin.monitoring.translator.avgTime': 'Average processing time',
  'admin.monitoring.translator.cacheHit': 'Answers served from cache',
  'admin.monitoring.translator.cacheHit.caption': 'Share of translations already known.',
  'admin.monitoring.translator.memory': 'Memory on the gateway side',
  'admin.monitoring.translator.memory.caption': 'Measured in the gateway, which drives the translation requests.',
  'admin.monitoring.translator.uptime': 'Tracking time',
  'admin.monitoring.translator.uptime.caption': 'How long these statistics have been counted.',

  'admin.monitoring.breakers.title': 'Circuit breakers',
  'admin.monitoring.breakers.intro': 'A circuit breaker protects the platform from a failing service: when open, it refuses calls while the service recovers.',
  'admin.monitoring.breakers.failures': 'Failures',
  'admin.monitoring.breakers.successes': 'Successes',
  'admin.monitoring.breakers.lastFailure': 'Last failure',
  'admin.monitoring.breakers.never': 'No failure',
  'admin.monitoring.breakers.empty': 'No circuit breaker registered',
  'admin.monitoring.breakers.emptyHint': 'They appear as soon as a protected service is called.',

  'admin.monitoring.presence.title': 'Presence',
  'admin.monitoring.presence.total': 'Updates requested',
  'admin.monitoring.presence.throttled': 'Throttled',
  'admin.monitoring.presence.throttled.caption': 'Ignored because they came in too fast.',
  'admin.monitoring.presence.rate': 'Throttle rate',

  'admin.monitoring.routes.scope.label': 'Scope',
  'admin.monitoring.routes.scope.watched': 'Watched routes',
  'admin.monitoring.routes.scope.all': 'All routes',
  'admin.monitoring.routes.search': 'Filter by route',
  'admin.monitoring.routes.limit.label': 'Detail rows',
  'admin.monitoring.routes.limit.option': '{count} rows',
  'admin.monitoring.routes.notInstrumented': 'Measurement is not installed on this instance: the zeros below prove nothing.',
  'admin.monitoring.routes.saturated': 'Measurement is saturated: {count} samples were not broken down by platform and version. Totals of the watched routes stay exact.',
  'admin.monitoring.routes.truncated': '{shown} rows shown out of {total}. Narrow the filter to see the others.',
  'admin.monitoring.routes.observingSince': 'Observing since',
  'admin.monitoring.routes.observedFor': 'Time observed',
  'admin.monitoring.routes.window': 'Measurement window',
  'admin.monitoring.routes.window.caption': 'Counts cover this sliding window.',

  'admin.monitoring.routes.watched.title': 'Watched routes',
  'admin.monitoring.routes.watched.intro': 'Addresses being retired: zero observed calls allows removal, provided you read the blind spots below.',
  'admin.monitoring.routes.watched.caption': 'Watched routes and their traffic',
  'admin.monitoring.routes.watched.empty': 'No watched route matches',
  'admin.monitoring.routes.col.method': 'Method',
  'admin.monitoring.routes.col.route': 'Route',
  'admin.monitoring.routes.col.issue': 'Linked issue',
  'admin.monitoring.routes.col.verdict': 'Verdict',
  'admin.monitoring.routes.col.calls': 'Calls',
  'admin.monitoring.routes.col.lastSeen': 'Last call',
  'admin.monitoring.routes.col.platform': 'Platform',
  'admin.monitoring.routes.col.version': 'Version',
  'admin.monitoring.routes.issue': 'Issue #{issue}',
  'admin.monitoring.routes.neverSeen': 'Never',

  'admin.monitoring.routes.verdict.unmounted': 'Address not found',
  'admin.monitoring.routes.verdict.unmounted.explain': 'This address is no longer mounted: its zero proves nothing about its callers.',
  'admin.monitoring.routes.verdict.unchecked': 'Not checked',
  'admin.monitoring.routes.verdict.unchecked.explain': 'The routing table has not been matched against this address yet.',
  'admin.monitoring.routes.verdict.unused': 'Never called',
  'admin.monitoring.routes.verdict.unused.explain': 'Observed with no call at all since observation began.',
  'admin.monitoring.routes.verdict.used': 'Still called',
  'admin.monitoring.routes.verdict.used.explain': 'At least one call was observed: do not remove it yet.',

  'admin.monitoring.routes.entries.title': 'Breakdown by platform and version',
  'admin.monitoring.routes.entries.caption': 'Route usage by platform and version',
  'admin.monitoring.routes.entries.empty': 'No call observed for this filter',
  'admin.monitoring.routes.platform.all': 'All platforms',
  'admin.monitoring.routes.platform.absent': 'Not declared',
  'admin.monitoring.routes.platform.bot': 'Crawler',
  'admin.monitoring.routes.platform.script': 'Script or command-line tool',
  'admin.monitoring.routes.platform.other': 'Other',
  'admin.monitoring.routes.version.all': 'All versions',
  'admin.monitoring.routes.version.absent': 'Not provided',
  'admin.monitoring.routes.version.invalid': 'Unreadable',

  'admin.monitoring.routes.blind.title': 'Blind spots of the measurement',
  'admin.monitoring.routes.blind.intro': 'What this counter does not see: read a zero with these limits.',
  'admin.monitoring.routes.blind.noVersion': 'Web and Android do not send their version',
  'admin.monitoring.routes.blind.noVersion.explain': 'Only iOS announces its version: all web and Android traffic arrives as “version not provided”. A zero proves the absence of a platform, never that a version is gone.',
  'admin.monitoring.routes.blind.instanceMemory': 'In-memory measurement, per instance',
  'admin.monitoring.routes.blind.instanceMemory.explain': 'It restarts from zero on redeploy and does not add up the replicas: a zero only holds for this instance since observation began.',
  'admin.monitoring.routes.blind.clientCache': 'Responses served from a cache',
  'admin.monitoring.routes.blind.clientCache.explain': 'A response served by the browser or the service worker never reaches the gateway and is not counted; a conditional request is.',
  'admin.monitoring.routes.blind.socket': 'Real time not measured',
  'admin.monitoring.routes.blind.socket.explain': 'WebSocket frames produce no HTTP response: a deprecated event cannot be measured here.',
  'admin.monitoring.routes.blind.retired': 'Routes already retired',
  'admin.monitoring.routes.blind.retired.explain': 'A request that matches no route is counted apart, without its address: we cannot tell which retired route is still being called.',
  'admin.monitoring.routes.blind.saturation': 'Breakdown limited under saturation',
  'admin.monitoring.routes.blind.saturation.explain': 'Beyond a ceiling, new platform and version breakdowns are refused; totals of the watched routes stay exact.',
  'admin.monitoring.routes.blind.other': 'Other limit reported',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
