import type { AdminCatalogFragment } from './fragment';
import type fr from './classement-supervision-fr';

const f = {
  'admin.ranking.subtitle': 'Lo más activo de la plataforma: miembros, conversaciones, mensajes y enlaces, durante el período elegido.',

  'admin.ranking.entity.label': 'Qué clasificar',
  'admin.ranking.entity.users': 'Miembros',
  'admin.ranking.entity.conversations': 'Conversaciones',
  'admin.ranking.entity.messages': 'Mensajes',
  'admin.ranking.entity.links': 'Enlaces',

  'admin.ranking.criterion.label': 'Criterio',
  'admin.ranking.criterion.users.messages_sent': 'Mensajes enviados',
  'admin.ranking.criterion.users.reactions_given': 'Reacciones dadas',
  'admin.ranking.criterion.users.reactions_received': 'Reacciones recibidas',
  'admin.ranking.criterion.users.replies_received': 'Respuestas recibidas',
  'admin.ranking.criterion.users.mentions_received': 'Menciones recibidas',
  'admin.ranking.criterion.users.mentions_sent': 'Menciones enviadas',
  'admin.ranking.criterion.users.conversations_joined': 'Conversaciones a las que se unió',
  'admin.ranking.criterion.users.communities_created': 'Conversaciones de grupo creadas',
  'admin.ranking.criterion.users.share_links_created': 'Enlaces para compartir creados',
  'admin.ranking.criterion.users.files_shared': 'Archivos compartidos',
  'admin.ranking.criterion.users.reports_sent': 'Denuncias enviadas',
  'admin.ranking.criterion.users.reports_received': 'Denuncias recibidas',
  'admin.ranking.criterion.users.friend_requests_sent': 'Solicitudes de contacto enviadas',
  'admin.ranking.criterion.users.friend_requests_received': 'Solicitudes de contacto recibidas',
  'admin.ranking.criterion.users.calls_initiated': 'Llamadas iniciadas',
  'admin.ranking.criterion.users.call_participations': 'Participaciones en llamadas',
  'admin.ranking.criterion.users.most_referrals_via_affiliate': 'Referidos por afiliación',
  'admin.ranking.criterion.users.most_referrals_via_sharelinks': 'Llegadas por sus enlaces para compartir',
  'admin.ranking.criterion.users.most_contacts': 'Contactos (amigos aceptados)',
  'admin.ranking.criterion.users.most_tracking_links_created': 'Enlaces de seguimiento creados',
  'admin.ranking.criterion.users.most_tracking_link_clicks': 'Clics en sus enlaces de seguimiento',
  'admin.ranking.criterion.conversations.message_count': 'Mensajes intercambiados',
  'admin.ranking.criterion.conversations.member_count': 'Miembros activos',
  'admin.ranking.criterion.conversations.reaction_count': 'Reacciones',
  'admin.ranking.criterion.conversations.files_shared': 'Archivos compartidos',
  'admin.ranking.criterion.conversations.call_count': 'Llamadas',
  'admin.ranking.criterion.conversations.recent_activity': 'Actividad más reciente',
  'admin.ranking.criterion.messages.most_reactions': 'Con más reacciones',
  'admin.ranking.criterion.messages.most_replies': 'Con más respuestas',
  'admin.ranking.criterion.messages.most_mentions': 'Con más menciones',
  'admin.ranking.criterion.links.tracking_links_most_visited': 'Enlaces de seguimiento con más clics',
  'admin.ranking.criterion.links.tracking_links_most_unique': 'Enlaces de seguimiento con más visitantes distintos',
  'admin.ranking.criterion.links.share_links_most_used': 'Enlaces para compartir más usados',
  'admin.ranking.criterion.links.share_links_most_unique_sessions': 'Enlaces para compartir con más sesiones distintas',

  'admin.ranking.period.label': 'Período',
  'admin.ranking.period.1d': 'Últimas 24 horas',
  'admin.ranking.period.7d': 'Últimos 7 días',
  'admin.ranking.period.30d': 'Últimos 30 días',
  'admin.ranking.period.60d': 'Últimos 60 días',
  'admin.ranking.period.90d': 'Últimos 90 días',
  'admin.ranking.period.180d': 'Últimos 6 meses',
  'admin.ranking.period.365d': 'Últimos 12 meses',
  'admin.ranking.period.all': 'Desde siempre',
  'admin.ranking.periodNone': 'Este criterio cubre todo el historial: el período no se aplica.',
  'admin.ranking.periodCreation': 'El período conserva los enlaces creados durante él, sea cual sea la fecha de los clics.',

  'admin.ranking.limit.label': 'Número de filas',
  'admin.ranking.limit.option': 'Top {count}',
  'admin.ranking.count': '{count} en esta clasificación',

  'admin.ranking.podium.title': 'Los tres primeros',
  'admin.ranking.table.title': 'Clasificación',
  'admin.ranking.table.titleRest': 'Del 4.º puesto al último',
  'admin.ranking.table.caption': 'Clasificación: {criterion}, {period}',
  'admin.ranking.rank': 'Puesto {rank}',

  'admin.ranking.col.rank': 'Puesto',
  'admin.ranking.col.entity.users': 'Miembro',
  'admin.ranking.col.entity.conversations': 'Conversación',
  'admin.ranking.col.entity.messages': 'Mensaje',
  'admin.ranking.col.entity.trackingLinks': 'Enlace de seguimiento',
  'admin.ranking.col.entity.shareLinks': 'Enlace para compartir',
  'admin.ranking.col.creator': 'Creado por',
  'admin.ranking.col.lastActivity': 'Última actividad',
  'admin.ranking.col.created': 'Creado',

  'admin.ranking.message.label': 'Mensaje de {sender} en {conversation}',
  'admin.ranking.message.meta': '{date} · {type}',
  'admin.ranking.trackingLink.to': 'Enlace hacia {host}',

  'admin.ranking.empty': 'Ningún resultado para esta clasificación',
  'admin.ranking.empty.hint.period': 'No se contó ninguna actividad en este período.',
  'admin.ranking.empty.hint.all': 'Todavía no se ha contado nada para este criterio.',
  'admin.ranking.widen': 'Ver desde siempre',

  'admin.monitoring.subtitle': 'La salud de la plataforma de un vistazo y el uso real de las direcciones de la API.',
  'admin.monitoring.tabs.label': 'Secciones de supervisión',
  'admin.monitoring.tab.health': 'Salud',
  'admin.monitoring.tab.routes': 'Uso de las rutas',
  'admin.monitoring.refresh': 'Actualizar',
  'admin.monitoring.refreshing': 'Actualizando…',

  'admin.monitoring.health.measured': 'Última medición',
  'admin.monitoring.health.auto': 'Se actualiza automáticamente cada 30 segundos mientras la pantalla está visible.',
  'admin.monitoring.health.allGood': 'Todos los servicios responden con normalidad.',
  'admin.monitoring.health.issue.database': 'La base de datos no responde.',
  'admin.monitoring.health.issue.redis': 'Redis no responde: la caché y los límites de frecuencia están degradados.',
  'admin.monitoring.health.issue.translator': 'El servicio de traducción es inalcanzable.',
  'admin.monitoring.health.issue.breakersOpen': 'Cortacircuitos abiertos: {count}. Las llamadas a estos servicios se rechazan.',
  'admin.monitoring.health.issue.breakersHalfOpen': 'Cortacircuitos a prueba: {count}. Dejan pasar algunas llamadas para comprobar que el servicio se ha recuperado.',

  'admin.monitoring.gateway.title': 'Pasarela',
  'admin.monitoring.gateway.uptime': 'Tiempo en marcha',
  'admin.monitoring.gateway.uptime.caption': 'Desde el último arranque de la pasarela.',
  'admin.monitoring.gateway.heap': 'Memoria en uso',
  'admin.monitoring.gateway.heap.caption': 'de {total} asignados al proceso',
  'admin.monitoring.gateway.rss': 'Memoria retenida',
  'admin.monitoring.gateway.rss.caption': 'Lo que el sistema reserva para el proceso.',

  'admin.monitoring.data.title': 'Datos',
  'admin.monitoring.database.title': 'Base de datos',
  'admin.monitoring.redis.title': 'Redis (caché)',
  'admin.monitoring.dependency.latency': 'Tiempo de respuesta',
  'admin.monitoring.dependency.noAnswer': 'Sin respuesta',

  'admin.monitoring.realtime.title': 'Tiempo real',
  'admin.monitoring.realtime.connections': 'Conexiones abiertas',
  'admin.monitoring.realtime.connections.caption': 'Una persona puede tener varios dispositivos conectados.',
  'admin.monitoring.realtime.users': 'Cuentas conectadas',
  'admin.monitoring.realtime.messages': 'Mensajes procesados',
  'admin.monitoring.realtime.messages.caption': 'Desde el arranque de la pasarela.',
  'admin.monitoring.realtime.translations': 'Traducciones enviadas',
  'admin.monitoring.realtime.errors': 'Errores',

  'admin.monitoring.translator.title': 'Traducción',
  'admin.monitoring.translator.unreachable': 'Servicio de traducción inalcanzable',
  'admin.monitoring.translator.unreachable.hint': 'Por ahora no hay ninguna estadística de traducción disponible.',
  'admin.monitoring.translator.sent': 'Solicitudes enviadas',
  'admin.monitoring.translator.received': 'Respuestas recibidas',
  'admin.monitoring.translator.errors': 'Errores',
  'admin.monitoring.translator.poolFull': 'Rechazos, cola llena',
  'admin.monitoring.translator.poolFull.caption': 'Solicitudes rechazadas por falta de sitio en la cola.',
  'admin.monitoring.translator.avgTime': 'Tiempo medio de procesamiento',
  'admin.monitoring.translator.cacheHit': 'Respuestas servidas desde la caché',
  'admin.monitoring.translator.cacheHit.caption': 'Proporción de traducciones ya conocidas.',
  'admin.monitoring.translator.memory': 'Memoria en el lado de la pasarela',
  'admin.monitoring.translator.memory.caption': 'Medida en la pasarela, que dirige las solicitudes de traducción.',
  'admin.monitoring.translator.uptime': 'Tiempo de seguimiento',
  'admin.monitoring.translator.uptime.caption': 'Desde hace cuánto se cuentan estas estadísticas.',

  'admin.monitoring.breakers.title': 'Cortacircuitos',
  'admin.monitoring.breakers.intro': 'Un cortacircuitos protege la plataforma de un servicio averiado: cuando está abierto, rechaza las llamadas mientras el servicio se recupera.',
  'admin.monitoring.breakers.failures': 'Fallos',
  'admin.monitoring.breakers.successes': 'Aciertos',
  'admin.monitoring.breakers.lastFailure': 'Último fallo',
  'admin.monitoring.breakers.never': 'Ningún fallo',
  'admin.monitoring.breakers.empty': 'Ningún cortacircuitos registrado',
  'admin.monitoring.breakers.emptyHint': 'Aparecen en cuanto se llama a un servicio protegido.',

  'admin.monitoring.presence.title': 'Presencia',
  'admin.monitoring.presence.total': 'Actualizaciones solicitadas',
  'admin.monitoring.presence.throttled': 'Limitadas',
  'admin.monitoring.presence.throttled.caption': 'Ignoradas por llegar demasiado deprisa.',
  'admin.monitoring.presence.rate': 'Tasa de limitación',

  'admin.monitoring.routes.scope.label': 'Alcance',
  'admin.monitoring.routes.scope.watched': 'Rutas vigiladas',
  'admin.monitoring.routes.scope.all': 'Todas las rutas',
  'admin.monitoring.routes.search': 'Filtrar por ruta',
  'admin.monitoring.routes.limit.label': 'Filas de detalle',
  'admin.monitoring.routes.limit.option': '{count} filas',
  'admin.monitoring.routes.notInstrumented': 'La medición no está instalada en esta instancia: los ceros de abajo no demuestran nada.',
  'admin.monitoring.routes.saturated': 'La medición está saturada: {count} muestras no se desglosaron por plataforma ni versión. Los totales de las rutas vigiladas siguen siendo exactos.',
  'admin.monitoring.routes.truncated': '{shown} filas mostradas de {total}. Acota el filtro para ver las demás.',
  'admin.monitoring.routes.observingSince': 'Observando desde',
  'admin.monitoring.routes.observedFor': 'Tiempo observado',
  'admin.monitoring.routes.window': 'Ventana de medición',
  'admin.monitoring.routes.window.caption': 'Los recuentos cubren esta ventana deslizante.',

  'admin.monitoring.routes.watched.title': 'Rutas vigiladas',
  'admin.monitoring.routes.watched.intro': 'Direcciones en proceso de retirada: cero llamadas observadas permite eliminarlas, siempre que leas los puntos ciegos de abajo.',
  'admin.monitoring.routes.watched.caption': 'Rutas vigiladas y su tráfico',
  'admin.monitoring.routes.watched.empty': 'Ninguna ruta vigilada coincide',
  'admin.monitoring.routes.col.method': 'Método',
  'admin.monitoring.routes.col.route': 'Ruta',
  'admin.monitoring.routes.col.issue': 'Issue enlazado',
  'admin.monitoring.routes.col.verdict': 'Veredicto',
  'admin.monitoring.routes.col.calls': 'Llamadas',
  'admin.monitoring.routes.col.lastSeen': 'Última llamada',
  'admin.monitoring.routes.col.platform': 'Plataforma',
  'admin.monitoring.routes.col.version': 'Versión',
  'admin.monitoring.routes.issue': 'Issue #{issue}',
  'admin.monitoring.routes.neverSeen': 'Nunca',

  'admin.monitoring.routes.verdict.unmounted': 'Dirección no encontrada',
  'admin.monitoring.routes.verdict.unmounted.explain': 'Esta dirección ya no está montada: su cero no demuestra nada sobre quienes la llaman.',
  'admin.monitoring.routes.verdict.unchecked': 'Sin comprobar',
  'admin.monitoring.routes.verdict.unchecked.explain': 'La tabla de rutas todavía no se ha contrastado con esta dirección.',
  'admin.monitoring.routes.verdict.unused': 'Nunca llamada',
  'admin.monitoring.routes.verdict.unused.explain': 'Observada sin ninguna llamada desde que empezó la observación.',
  'admin.monitoring.routes.verdict.used': 'Todavía se llama',
  'admin.monitoring.routes.verdict.used.explain': 'Se observó al menos una llamada: todavía no la retire.',

  'admin.monitoring.routes.entries.title': 'Desglose por plataforma y versión',
  'admin.monitoring.routes.entries.caption': 'Uso de las rutas por plataforma y versión',
  'admin.monitoring.routes.entries.empty': 'Ninguna llamada observada con este filtro',
  'admin.monitoring.routes.platform.all': 'Todas las plataformas',
  'admin.monitoring.routes.platform.absent': 'No declarada',
  'admin.monitoring.routes.platform.bot': 'Rastreador',
  'admin.monitoring.routes.platform.script': 'Script o herramienta de línea de comandos',
  'admin.monitoring.routes.platform.other': 'Otra',
  'admin.monitoring.routes.version.all': 'Todas las versiones',
  'admin.monitoring.routes.version.absent': 'No indicada',
  'admin.monitoring.routes.version.invalid': 'Ilegible',

  'admin.monitoring.routes.blind.title': 'Puntos ciegos de la medición',
  'admin.monitoring.routes.blind.intro': 'Lo que este contador no ve: lee un cero con estos límites.',
  'admin.monitoring.routes.blind.noVersion': 'La web y Android no envían su versión',
  'admin.monitoring.routes.blind.noVersion.explain': 'Solo iOS anuncia su versión: todo el tráfico web y Android llega como «versión no indicada». Un cero demuestra la ausencia de una plataforma, nunca que una versión haya desaparecido.',
  'admin.monitoring.routes.blind.instanceMemory': 'Medición en memoria, por instancia',
  'admin.monitoring.routes.blind.instanceMemory.explain': 'Vuelve a cero con cada redespliegue y no suma las réplicas: un cero solo vale para esta instancia desde que empezó la observación.',
  'admin.monitoring.routes.blind.clientCache': 'Respuestas servidas desde una caché',
  'admin.monitoring.routes.blind.clientCache.explain': 'Una respuesta servida por el navegador o por el service worker nunca llega a la pasarela y no se cuenta; una petición condicional sí.',
  'admin.monitoring.routes.blind.socket': 'Tiempo real no medido',
  'admin.monitoring.routes.blind.socket.explain': 'Las tramas WebSocket no producen respuesta HTTP: aquí no se puede medir un evento obsoleto.',
  'admin.monitoring.routes.blind.retired': 'Rutas ya retiradas',
  'admin.monitoring.routes.blind.retired.explain': 'Una petición que no corresponde a ninguna ruta se cuenta aparte, sin su dirección: no podemos saber qué ruta retirada se sigue llamando.',
  'admin.monitoring.routes.blind.saturation': 'Desglose limitado por saturación',
  'admin.monitoring.routes.blind.saturation.explain': 'Pasado un tope, se rechazan los nuevos desgloses por plataforma y versión; los totales de las rutas vigiladas siguen siendo exactos.',
  'admin.monitoring.routes.blind.other': 'Otro límite señalado',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
