/**
 * Fragment « contenus » — espagnol (#8876). TEXTE ANGLAIS PROVISOIRE : les clés sont
 * celles du français, la passe de traduction suit.
 */
import type { AdminCatalogFragment } from './fragment';
import type fr from './contenus-fr';

const f = {
  /* ─── Posts: the list ─── */
  'admin.posts.subtitle': 'Publicaciones, stories, reels y estados de toda la plataforma: detecte, entienda y retire lo que deba retirarse.',
  'admin.posts.caption': 'Publicaciones de la plataforma',
  'admin.posts.tabs.label': 'Tipo de publicación',
  'admin.posts.tab.all': 'Todas',
  'admin.posts.tab.POST': 'Publicaciones',
  'admin.posts.tab.STORY': 'Stories',
  'admin.posts.tab.REEL': 'Reels',
  'admin.posts.tab.STATUS': 'Estados',
  'admin.posts.search': 'Buscar en el texto',
  'admin.posts.count': 'Resultados: {count}',
  'admin.posts.filter.visibility': 'Visibilidad',
  'admin.posts.filter.deleted': 'Retirada',
  'admin.posts.filter.deleted.no': 'No retiradas',
  'admin.posts.filter.deleted.yes': 'Retiradas',
  'admin.posts.filter.pinned': 'Fijado',
  'admin.posts.filter.pinned.yes': 'Fijadas',
  'admin.posts.filter.pinned.no': 'No fijadas',
  'admin.posts.filter.period': 'Período',
  'admin.posts.filter.author': 'Publicaciones de {name}',
  'admin.posts.filter.authorUnknown': 'Publicaciones de un único autor',
  'admin.posts.filter.authorClear': 'Quitar este filtro',
  'admin.posts.period.all': 'Desde el principio',
  'admin.posts.period.today': 'Hoy',
  'admin.posts.period.week': 'Últimos 7 días',
  'admin.posts.period.month': 'Últimos 30 días',
  'admin.posts.col.author': 'Autor',
  'admin.posts.col.excerpt': 'Extracto',
  'admin.posts.col.type': 'Tipo',
  'admin.posts.col.visibility': 'Visibilidad',
  'admin.posts.col.likes': 'Reacciones',
  'admin.posts.col.comments': 'Comentarios',
  'admin.posts.col.views': 'Vistas',
  'admin.posts.col.state': 'Estado',
  'admin.posts.col.published': 'Publicada',
  'admin.posts.empty': 'Ninguna publicación',
  'admin.posts.empty.hint': 'Las publicaciones, stories, reels y estados aparecerán aquí en cuanto se publiquen.',
  'admin.posts.filtered': 'Ninguna publicación coincide con estos filtros',
  'admin.posts.restricted': 'Contenido de audiencia restringida',
  'admin.posts.noText': 'Sin texto',
  'admin.posts.mediaOnly.one': '{type} · {count} archivo multimedia',
  'admin.posts.mediaOnly.other': '{type} · {count} archivos multimedia',
  'admin.posts.pinned': 'Fijada',
  'admin.posts.edited': 'Editada',

  /* ─── Posts: the figures band ─── */
  'admin.posts.stats.title': 'Actividad de publicación',
  'admin.posts.stats.scope': 'Estas cifras siguen el período elegido; los demás filtros no las modifican.',
  'admin.posts.stats.total': 'Publicaciones en línea',
  'admin.posts.stats.deleted': 'Retiradas',
  'admin.posts.stats.deletedShare': 'es decir, el {share} de todo lo publicado',
  'admin.posts.stats.byType': 'Reparto por tipo',
  'admin.posts.stats.byType.summary': 'El más frecuente: {type}, {count}',
  'admin.posts.stats.authors': 'Autores más activos',
  'admin.posts.stats.authorPosts': 'Publicaciones: {count}',
  'admin.posts.stats.trending': 'Tendencias',
  'admin.posts.stats.engagement': 'Me gusta: {likes} · Comentarios: {comments}',
  'admin.posts.stats.none': 'Nada que señalar en este período.',

  /* ─── Posts: the record ─── */
  'admin.posts.notFound': 'No se encuentra esta publicación',
  'admin.posts.notFound.hint': 'Ya no existe, o la dirección es incorrecta.',
  'admin.posts.publishedOn': 'Publicada el {date}',
  'admin.posts.stat.likes': 'Me gusta',
  'admin.posts.stat.comments': 'Comentarios',
  'admin.posts.stat.shares': 'Compartidos',
  'admin.posts.stat.views': 'Vistas',
  'admin.posts.stat.bookmarks': 'Guardados',
  'admin.posts.stat.reposts': 'Republicaciones',
  'admin.posts.section.content': 'Contenido',
  'admin.posts.content.restricted': 'Esta publicación tiene una audiencia restringida: su texto solo aparece en esta ficha, para la moderación, nunca en la lista.',
  'admin.posts.content.empty': 'Esta publicación no tiene texto.',
  'admin.posts.content.language': 'Idioma original',
  'admin.posts.content.languageUnknown': 'Idioma no detectado',
  'admin.posts.content.translations.none': 'Todavía sin traducir',
  'admin.posts.content.translations.one': 'Traducida a {count} idioma',
  'admin.posts.content.translations.other': 'Traducida a {count} idiomas',
  'admin.posts.content.mood': 'Estado de ánimo',
  'admin.posts.section.media': 'Archivos multimedia',
  'admin.posts.media.open': 'Abrir el archivo multimedia {index}',
  'admin.posts.media.kind.image': 'Imagen',
  'admin.posts.media.kind.video': 'Vídeo',
  'admin.posts.media.kind.audio': 'Audio',
  'admin.posts.media.kind.file': 'Archivo',
  'admin.posts.media.caption': 'Pie de foto: {text}',
  'admin.posts.media.alt': 'Texto alternativo: {text}',
  'admin.posts.section.context': 'Autor y contexto',
  'admin.posts.context.author': 'Autor',
  'admin.posts.context.authorPosts': 'Ver sus publicaciones',
  'admin.posts.context.community': 'Comunidad',
  'admin.posts.context.repost': 'Republicación de',
  'admin.posts.context.repostQuote': 'Republicación con comentario',
  'admin.posts.context.repostSimple': 'Republicación simple',
  'admin.posts.section.comments': 'Últimos comentarios',
  'admin.posts.comments.caption': 'Últimos comentarios: {shown} de {total}',
  'admin.posts.comments.empty': 'Todavía no hay comentarios.',
  'admin.posts.comments.noText': 'Comentario sin texto',
  'admin.posts.section.viewers': 'Últimos espectadores',
  'admin.posts.viewers.caption': 'Últimos espectadores: {shown} de {total}',
  'admin.posts.viewers.empty': 'Nadie ha visto todavía esta publicación.',
  'admin.posts.meta.type': 'Tipo',
  'admin.posts.meta.visibility': 'Visibilidad',
  'admin.posts.meta.state': 'Estado',
  'admin.posts.meta.pinned': 'Fijado',
  'admin.posts.meta.pinned.yes': 'Fijada',
  'admin.posts.meta.pinned.no': 'No fijada',
  'admin.posts.meta.edited': 'Edición',
  'admin.posts.meta.edited.yes': 'Editada el {date}',
  'admin.posts.meta.edited.no': 'Nunca editada',
  'admin.posts.meta.expires': 'Fin de vida',
  'admin.posts.meta.expires.future': 'La publicación desaparecerá sola en esta fecha.',
  'admin.posts.meta.created': 'Publicada',
  'admin.posts.meta.updated': 'Actualizada',
  'admin.posts.meta.updated.explain': 'También cambia cada vez que se mueve un contador de vistas o de reacciones.',
  'admin.posts.audience.only.one': 'Visible para {count} persona elegida',
  'admin.posts.audience.only.other': 'Visible para {count} personas elegidas',
  'admin.posts.audience.except.one': 'Oculta para {count} persona',
  'admin.posts.audience.except.other': 'Oculta para {count} personas',

  /* ─── Posts: removal ─── */
  'admin.posts.remove.action': 'Retirar la publicación',
  'admin.posts.remove.title': '¿Retirar esta publicación?',
  'admin.posts.remove.body': 'La publicación desaparece del feed de todos los lectores, incluido su autor, y se cortan los enlaces que llevaban a ella. No se borra, pero esta consola no puede restaurarla.',
  'admin.posts.remove.motive': 'Motivo de la retirada (queda registrado en el registro)',
  'admin.posts.remove.confirm': 'Retirar la publicación',
  'admin.posts.remove.done': 'Publicación retirada',
  'admin.posts.remove.already': 'Esta publicación ya había sido retirada.',

  /* ─── Communities: the list ─── */
  'admin.community.subtitle': 'Las comunidades de la plataforma: quién las dirige, cuántas personas siguen dentro y qué contienen.',
  'admin.community.caption': 'Comunidades de la plataforma',
  'admin.community.search': 'Buscar (nombre, identificador, descripción)',
  'admin.community.count': 'Resultados: {count}',
  'admin.community.unnamed': 'Comunidad sin nombre',
  'admin.community.filter.visibility': 'Visibilidad',
  'admin.community.filter.visibility.private': 'Privada',
  'admin.community.filter.visibility.public': 'Pública',
  'admin.community.filter.state': 'Estado',
  'admin.community.filter.state.active': 'Activa',
  'admin.community.filter.state.inactive': 'Desactivada',
  'admin.community.col.community': 'Comunidad',
  'admin.community.col.visibility': 'Visibilidad',
  'admin.community.col.members': 'Miembros activos',
  'admin.community.col.conversations': 'Conversaciones',
  'admin.community.col.creator': 'Creada por',
  'admin.community.col.state': 'Estado',
  'admin.community.col.created': 'Creada',
  'admin.community.empty': 'Ninguna comunidad',
  'admin.community.empty.hint': 'Las comunidades aparecerán aquí en cuanto alguien cree una.',
  'admin.community.filtered': 'Ninguna comunidad coincide con estos filtros',
  'admin.community.visibility.private': 'Privada',
  'admin.community.visibility.private.explain': 'Fuera de la búsqueda: solo se puede entrar por invitación y solo sus miembros pueden leer su página.',
  'admin.community.visibility.public': 'Pública',
  'admin.community.visibility.public.explain': 'En la búsqueda: cualquiera puede unirse y leer su página.',
  'admin.community.state.active': 'Activa',
  'admin.community.state.inactive': 'Desactivada',
  'admin.community.state.inactive.explain': 'Retirada de las listas y de la búsqueda, nadie puede unirse ya. Sus conversaciones y sus miembros siguen en su sitio.',

  /* ─── Communities: the record ─── */
  'admin.community.notFound': 'No se encuentra esta comunidad',
  'admin.community.notFound.hint': 'Ya no existe, o la dirección es incorrecta.',
  'admin.community.banner': 'Banner de la comunidad',
  'admin.community.stat.members': 'Miembros activos',
  'admin.community.stat.left': 'Bajas',
  'admin.community.stat.conversations': 'Conversaciones',
  'admin.community.stat.posts': 'Publicaciones',
  'admin.community.tabs.label': 'Secciones de la comunidad',
  'admin.community.tab.overview': 'Resumen',
  'admin.community.tab.members': 'Miembros',
  'admin.community.section.description': 'Descripción',
  'admin.community.description.empty': 'Esta comunidad no tiene descripción.',
  'admin.community.section.staff': 'Equipo',
  'admin.community.staff.empty': 'Ningún administrador ni moderador activo.',
  'admin.community.section.conversations': 'Conversaciones',
  'admin.community.conversations.empty': 'Esta comunidad todavía no tiene ninguna conversación.',
  'admin.community.conversations.meta': '{type} · Miembros: {count}',
  'admin.community.conversations.metaInactive': '{type} · Miembros: {count} · Inactiva',
  'admin.community.conversations.more': 'Las 20 conversaciones activas más recientemente, de un total de {total}.',
  'admin.community.conversations.restricted': 'Esta comunidad tiene {count} conversación(es). Su lista está reservada al rango de administración.',
  'admin.community.conversations.seeAll': 'Ver todas las conversaciones de esta comunidad',
  'admin.community.meta.visibility': 'Visibilidad',
  'admin.community.meta.state': 'Estado',
  'admin.community.meta.identifier': 'Identificador público',
  'admin.community.meta.creator': 'Creador',
  'admin.community.meta.created': 'Creada',
  'admin.community.meta.updated': 'Actualizada',
  'admin.community.meta.deactivated': 'Desactivada el',

  /* ─── Communities: members ─── */
  'admin.community.members.caption': 'Miembros de la comunidad',
  'admin.community.members.search': 'Buscar un miembro',
  'admin.community.members.count': 'Resultados: {count}',
  'admin.community.members.filter.role': 'Rol',
  'admin.community.members.filter.active': 'Presencia',
  'admin.community.members.active.yes': 'Presente',
  'admin.community.members.active.no': 'Salió',
  'admin.community.members.col.member': 'Miembro',
  'admin.community.members.col.role': 'Rol',
  'admin.community.members.col.state': 'Estado',
  'admin.community.members.col.joined': 'Se unió',
  'admin.community.members.col.left': 'Salió',
  'admin.community.members.state.present': 'Presente',
  'admin.community.members.state.left': 'Salió',
  'admin.community.members.empty': 'Ningún miembro',
  'admin.community.members.empty.hint': 'Todavía nadie se ha unido a esta comunidad.',
  'admin.community.members.filtered': 'Ningún miembro coincide con estos filtros',

  /* ─── Communities: actions ─── */
  'admin.community.action.deactivate': 'Desactivar la comunidad',
  'admin.community.action.reactivate': 'Reactivar la comunidad',
  'admin.community.action.makePrivate': 'Hacer privada',
  'admin.community.action.makePublic': 'Hacer pública',
  'admin.community.motive': 'Motivo (queda registrado en el registro de auditoría)',
  'admin.community.deactivate.title': '¿Desactivar esta comunidad?',
  'admin.community.deactivate.body': 'Desaparece de las listas y de la búsqueda, nadie puede unirse ya, y su página responde «no encontrada» a los lectores. Sus conversaciones y sus miembros siguen en su sitio: las personas que hablan allí no pierden su conversación.',
  'admin.community.reactivate.title': '¿Reactivar esta comunidad?',
  'admin.community.reactivate.body': 'Vuelve a aparecer en las listas y en la búsqueda, y se puede volver a entrar en ella.',
  'admin.community.makePrivate.title': '¿Hacer privada esta comunidad?',
  'admin.community.makePrivate.body': 'Sale de la búsqueda, ya no se puede entrar sin invitación y solo sus miembros pueden leer su página. Los miembros actuales se quedan.',
  'admin.community.makePublic.title': '¿Hacer pública esta comunidad?',
  'admin.community.makePublic.body': 'Aparece en la búsqueda, cualquiera puede unirse sin invitación y su página pasa a ser legible por todos.',
  'admin.community.done.deactivated': 'Comunidad desactivada',
  'admin.community.done.reactivated': 'Comunidad reactivada',
  'admin.community.done.private': 'Comunidad hecha privada',
  'admin.community.done.public': 'Comunidad hecha pública',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
