/**
 * Fragment « contenus » — espagnol (#8876). TEXTE ANGLAIS PROVISOIRE : les clés sont
 * celles du français, la passe de traduction suit.
 */
import type { AdminCatalogFragment } from './fragment';
import type fr from './contenus-fr';

const f = {
  /* ─── Posts: the list ─── */
  'admin.posts.subtitle': 'Posts, stories, reels and statuses from the whole platform: spot, understand and remove what has to go.',
  'admin.posts.caption': 'Platform posts',
  'admin.posts.tabs.label': 'Post type',
  'admin.posts.tab.all': 'All',
  'admin.posts.tab.POST': 'Posts',
  'admin.posts.tab.STORY': 'Stories',
  'admin.posts.tab.REEL': 'Reels',
  'admin.posts.tab.STATUS': 'Statuses',
  'admin.posts.search': 'Search the text',
  'admin.posts.count': 'Results: {count}',
  'admin.posts.filter.visibility': 'Visibility',
  'admin.posts.filter.deleted': 'Removal',
  'admin.posts.filter.deleted.no': 'Not removed',
  'admin.posts.filter.deleted.yes': 'Removed',
  'admin.posts.filter.pinned': 'Pinning',
  'admin.posts.filter.pinned.yes': 'Pinned',
  'admin.posts.filter.pinned.no': 'Not pinned',
  'admin.posts.filter.period': 'Period',
  'admin.posts.filter.author': 'Posts by {name}',
  'admin.posts.filter.authorUnknown': 'Posts by a single author',
  'admin.posts.filter.authorClear': 'Remove this filter',
  'admin.posts.period.all': 'Since the beginning',
  'admin.posts.period.today': 'Today',
  'admin.posts.period.week': 'Last 7 days',
  'admin.posts.period.month': 'Last 30 days',
  'admin.posts.col.author': 'Author',
  'admin.posts.col.excerpt': 'Excerpt',
  'admin.posts.col.type': 'Type',
  'admin.posts.col.visibility': 'Visibility',
  'admin.posts.col.likes': 'Reactions',
  'admin.posts.col.comments': 'Comments',
  'admin.posts.col.views': 'Views',
  'admin.posts.col.state': 'State',
  'admin.posts.col.published': 'Published',
  'admin.posts.empty': 'No posts',
  'admin.posts.empty.hint': 'Posts, stories, reels and statuses will appear here as soon as they are published.',
  'admin.posts.filtered': 'No posts match these filters',
  'admin.posts.restricted': 'Restricted-audience content',
  'admin.posts.noText': 'No text',
  'admin.posts.mediaOnly.one': '{type} · {count} media item',
  'admin.posts.mediaOnly.other': '{type} · {count} media items',
  'admin.posts.pinned': 'Pinned',
  'admin.posts.edited': 'Edited',

  /* ─── Posts: the figures band ─── */
  'admin.posts.stats.title': 'Publishing activity',
  'admin.posts.stats.scope': 'These figures follow the chosen period; the other filters do not change them.',
  'admin.posts.stats.total': 'Posts online',
  'admin.posts.stats.deleted': 'Removed',
  'admin.posts.stats.deletedShare': 'that is {share} of everything published',
  'admin.posts.stats.byType': 'Breakdown by type',
  'admin.posts.stats.byType.summary': 'Most frequent: {type}, {count}',
  'admin.posts.stats.authors': 'Most active authors',
  'admin.posts.stats.authorPosts': 'Posts: {count}',
  'admin.posts.stats.trending': 'Trending',
  'admin.posts.stats.engagement': 'Likes: {likes} · Comments: {comments}',
  'admin.posts.stats.none': 'Nothing to report for this period.',

  /* ─── Posts: the record ─── */
  'admin.posts.notFound': 'This post cannot be found',
  'admin.posts.notFound.hint': 'It no longer exists, or the address is wrong.',
  'admin.posts.publishedOn': 'Published on {date}',
  'admin.posts.stat.likes': 'Likes',
  'admin.posts.stat.comments': 'Comments',
  'admin.posts.stat.shares': 'Shares',
  'admin.posts.stat.views': 'Views',
  'admin.posts.stat.bookmarks': 'Bookmarks',
  'admin.posts.stat.reposts': 'Reposts',
  'admin.posts.section.content': 'Content',
  'admin.posts.content.restricted': 'This post has a restricted audience: its text appears only in this record, for moderation — never in the list.',
  'admin.posts.content.empty': 'This post has no text.',
  'admin.posts.content.language': 'Original language',
  'admin.posts.content.languageUnknown': 'Language not detected',
  'admin.posts.content.translations.none': 'Not translated yet',
  'admin.posts.content.translations.one': 'Translated into {count} language',
  'admin.posts.content.translations.other': 'Translated into {count} languages',
  'admin.posts.content.mood': 'Mood',
  'admin.posts.section.media': 'Media',
  'admin.posts.media.open': 'Open media item {index}',
  'admin.posts.media.kind.image': 'Image',
  'admin.posts.media.kind.video': 'Video',
  'admin.posts.media.kind.audio': 'Audio',
  'admin.posts.media.kind.file': 'File',
  'admin.posts.media.caption': 'Caption: {text}',
  'admin.posts.media.alt': 'Alternative text: {text}',
  'admin.posts.section.context': 'Author and context',
  'admin.posts.context.author': 'Author',
  'admin.posts.context.authorPosts': 'See their posts',
  'admin.posts.context.community': 'Community',
  'admin.posts.context.repost': 'Repost of',
  'admin.posts.context.repostQuote': 'Repost with a comment',
  'admin.posts.context.repostSimple': 'Plain repost',
  'admin.posts.section.comments': 'Latest comments',
  'admin.posts.comments.caption': 'Latest comments: {shown} of {total}',
  'admin.posts.comments.empty': 'No comments yet.',
  'admin.posts.comments.noText': 'Comment without text',
  'admin.posts.section.viewers': 'Latest viewers',
  'admin.posts.viewers.caption': 'Latest viewers: {shown} of {total}',
  'admin.posts.viewers.empty': 'Nobody has seen this post yet.',
  'admin.posts.meta.type': 'Type',
  'admin.posts.meta.visibility': 'Visibility',
  'admin.posts.meta.state': 'State',
  'admin.posts.meta.pinned': 'Pinning',
  'admin.posts.meta.pinned.yes': 'Pinned',
  'admin.posts.meta.pinned.no': 'Not pinned',
  'admin.posts.meta.edited': 'Editing',
  'admin.posts.meta.edited.yes': 'Edited on {date}',
  'admin.posts.meta.edited.no': 'Never edited',
  'admin.posts.meta.expires': 'End of life',
  'admin.posts.meta.expires.future': 'The post will disappear by itself on this date.',
  'admin.posts.meta.created': 'Published',
  'admin.posts.meta.updated': 'Updated',
  'admin.posts.meta.updated.explain': 'Also changes whenever a view or reaction counter moves.',
  'admin.posts.audience.only.one': 'Visible to {count} chosen person',
  'admin.posts.audience.only.other': 'Visible to {count} chosen people',
  'admin.posts.audience.except.one': 'Hidden from {count} person',
  'admin.posts.audience.except.other': 'Hidden from {count} people',

  /* ─── Posts: removal ─── */
  'admin.posts.remove.action': 'Remove the post',
  'admin.posts.remove.title': 'Remove this post?',
  'admin.posts.remove.body': 'The post disappears from every reader’s feed, its author included, and the links that led to it are cut. It is not erased, but this console cannot restore it.',
  'admin.posts.remove.motive': 'Reason for removal (recorded in the log)',
  'admin.posts.remove.confirm': 'Remove the post',
  'admin.posts.remove.done': 'Post removed',
  'admin.posts.remove.already': 'This post had already been removed.',

  /* ─── Communities: the list ─── */
  'admin.community.subtitle': 'The platform’s communities: who runs them, how many people are still in, and what they contain.',
  'admin.community.caption': 'Platform communities',
  'admin.community.search': 'Search (name, identifier, description)',
  'admin.community.count': 'Results: {count}',
  'admin.community.unnamed': 'Unnamed community',
  'admin.community.filter.visibility': 'Visibility',
  'admin.community.filter.visibility.private': 'Private',
  'admin.community.filter.visibility.public': 'Public',
  'admin.community.filter.state': 'State',
  'admin.community.filter.state.active': 'Active',
  'admin.community.filter.state.inactive': 'Deactivated',
  'admin.community.col.community': 'Community',
  'admin.community.col.visibility': 'Visibility',
  'admin.community.col.members': 'Active members',
  'admin.community.col.conversations': 'Conversations',
  'admin.community.col.creator': 'Created by',
  'admin.community.col.state': 'State',
  'admin.community.col.created': 'Created',
  'admin.community.empty': 'No communities',
  'admin.community.empty.hint': 'Communities will appear here as soon as someone creates one.',
  'admin.community.filtered': 'No communities match these filters',
  'admin.community.visibility.private': 'Private',
  'admin.community.visibility.private.explain': 'Out of search: it can only be joined by invitation, and its page is readable by its members only.',
  'admin.community.visibility.public': 'Public',
  'admin.community.visibility.public.explain': 'In search: anyone can join it and read its page.',
  'admin.community.state.active': 'Active',
  'admin.community.state.inactive': 'Deactivated',
  'admin.community.state.inactive.explain': 'Removed from lists and search, nobody can join it any more. Its conversations and members stay in place.',

  /* ─── Communities: the record ─── */
  'admin.community.notFound': 'This community cannot be found',
  'admin.community.notFound.hint': 'It no longer exists, or the address is wrong.',
  'admin.community.banner': 'Community banner',
  'admin.community.stat.members': 'Active members',
  'admin.community.stat.left': 'Departures',
  'admin.community.stat.conversations': 'Conversations',
  'admin.community.stat.posts': 'Posts',
  'admin.community.tabs.label': 'Community sections',
  'admin.community.tab.overview': 'Overview',
  'admin.community.tab.members': 'Members',
  'admin.community.section.description': 'Description',
  'admin.community.description.empty': 'This community has no description.',
  'admin.community.section.staff': 'Team',
  'admin.community.staff.empty': 'No active administrator or moderator.',
  'admin.community.section.conversations': 'Conversations',
  'admin.community.conversations.empty': 'This community has no conversation yet.',
  'admin.community.conversations.meta': '{type} · Members: {count}',
  'admin.community.conversations.metaInactive': '{type} · Members: {count} · Inactive',
  'admin.community.conversations.more': 'The 20 most recently active conversations, out of {total}.',
  'admin.community.meta.visibility': 'Visibility',
  'admin.community.meta.state': 'State',
  'admin.community.meta.identifier': 'Public identifier',
  'admin.community.meta.creator': 'Creator',
  'admin.community.meta.created': 'Created',
  'admin.community.meta.updated': 'Updated',
  'admin.community.meta.deactivated': 'Deactivated on',

  /* ─── Communities: members ─── */
  'admin.community.members.caption': 'Community members',
  'admin.community.members.search': 'Search a member',
  'admin.community.members.count': 'Results: {count}',
  'admin.community.members.filter.role': 'Role',
  'admin.community.members.filter.active': 'Presence',
  'admin.community.members.active.yes': 'Present',
  'admin.community.members.active.no': 'Left',
  'admin.community.members.col.member': 'Member',
  'admin.community.members.col.role': 'Role',
  'admin.community.members.col.state': 'State',
  'admin.community.members.col.joined': 'Joined',
  'admin.community.members.col.left': 'Left',
  'admin.community.members.state.present': 'Present',
  'admin.community.members.state.left': 'Left',
  'admin.community.members.empty': 'No members',
  'admin.community.members.empty.hint': 'Nobody has joined this community yet.',
  'admin.community.members.filtered': 'No members match these filters',

  /* ─── Communities: actions ─── */
  'admin.community.action.deactivate': 'Deactivate the community',
  'admin.community.action.reactivate': 'Reactivate the community',
  'admin.community.action.makePrivate': 'Make private',
  'admin.community.action.makePublic': 'Make public',
  'admin.community.motive': 'Reason (recorded in the audit log)',
  'admin.community.deactivate.title': 'Deactivate this community?',
  'admin.community.deactivate.body': 'It disappears from lists and search, nobody can join it any more, and its page answers “not found” to readers. Its conversations and members stay in place: the people talking there do not lose their conversation.',
  'admin.community.reactivate.title': 'Reactivate this community?',
  'admin.community.reactivate.body': 'It reappears in lists and search, and can be joined again.',
  'admin.community.makePrivate.title': 'Make this community private?',
  'admin.community.makePrivate.body': 'It leaves search, it can no longer be joined without an invitation, and its page is readable by its members only. Current members stay.',
  'admin.community.makePublic.title': 'Make this community public?',
  'admin.community.makePublic.body': 'It appears in search, anyone can join it without an invitation, and its page becomes readable by everyone.',
  'admin.community.done.deactivated': 'Community deactivated',
  'admin.community.done.reactivated': 'Community reactivated',
  'admin.community.done.private': 'Community made private',
  'admin.community.done.public': 'Community made public',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
