/**
 * Fragment « contenus » — portugais (#8876). TEXTE ANGLAIS PROVISOIRE : les clés sont
 * celles du français, la passe de traduction suit.
 */
import type { AdminCatalogFragment } from './fragment';
import type fr from './contenus-fr';

const f = {
  /* ─── Posts: the list ─── */
  'admin.posts.subtitle': 'Publicações, stories, reels e estados de toda a plataforma: identifique, compreenda e retire o que deve ser retirado.',
  'admin.posts.caption': 'Publicações',
  'admin.posts.tabs.label': 'Tipo de publicação',
  'admin.posts.tab.all': 'Todos',
  'admin.posts.tab.POST': 'Postagens',
  'admin.posts.tab.STORY': 'Stories',
  'admin.posts.tab.REEL': 'Reels',
  'admin.posts.tab.STATUS': 'Statuses',
  'admin.posts.search': 'Search o/a text',
  'admin.posts.count': 'Resultados: {count}',
  'admin.posts.filter.visibility': 'Visibilidade',
  'admin.posts.filter.deleted': 'Removal',
  'admin.posts.filter.deleted.no': 'Not removed',
  'admin.posts.filter.deleted.yes': 'Removido',
  'admin.posts.filter.pinned': 'Fixação',
  'admin.posts.filter.pinned.yes': 'Fixado',
  'admin.posts.filter.pinned.no': 'Não fixado',
  'admin.posts.filter.period': 'Período',
  'admin.posts.filter.author': 'Publicações de {name}',
  'admin.posts.filter.authorUnknown': 'Publicações de um único autor',
  'admin.posts.filter.authorClear': 'Remove this filter',
  'admin.posts.period.all': 'Since o/a beginning',
  'admin.posts.period.today': 'Hoje',
  'admin.posts.period.week': 'Últimos 7 dias',
  'admin.posts.period.month': 'Últimos 30 dias',
  'admin.posts.col.author': 'Autor',
  'admin.posts.col.excerpt': 'Excerpt',
  'admin.posts.col.type': 'Tipo',
  'admin.posts.col.visibility': 'Visibilidade',
  'admin.posts.col.likes': 'Reações',
  'admin.posts.col.comments': 'Comentários',
  'admin.posts.col.views': 'Visualizações',
  'admin.posts.col.state': 'Estado',
  'admin.posts.col.published': 'Publicado',
  'admin.posts.empty': 'Aucune publicação',
  'admin.posts.empty.hint': 'Les publicaçãos, stories, reels et statuts apparaîtront ici dès qu’ils seront publiés.',
  'admin.posts.filtered': 'Aucune publicação pour ces filtres',
  'admin.posts.restricted': 'Restricted-audience content',
  'admin.posts.noText': 'No text',
  'admin.posts.mediaOnly.one': '{type} · {count} média',
  'admin.posts.mediaOnly.other': '{type} · {count} médias',
  'admin.posts.pinned': 'Fixado',
  'admin.posts.edited': 'Edited',

  /* ─── Posts: the figures band ─── */
  'admin.posts.stats.title': 'Activité de publicação',
  'admin.posts.stats.scope': 'These figures follow o/a chosen period; o/a other filters do not change them.',
  'admin.posts.stats.total': 'Publicações',
  'admin.posts.stats.deleted': 'Removido',
  'admin.posts.stats.deletedShare': 'that is {share} de everything published',
  'admin.posts.stats.byType': 'Breakdown por type',
  'admin.posts.stats.byType.summary': 'Mais frequente: {type}, {count}',
  'admin.posts.stats.authors': 'Most active authors',
  'admin.posts.stats.authorPosts': 'Publicações: {count}',
  'admin.posts.stats.trending': 'Tendência',
  'admin.posts.stats.engagement': 'Likes: {likes} · Comments: {comments}',
  'admin.posts.stats.none': 'Nothing para report for this period.',

  /* ─── Posts: the record ─── */
  'admin.posts.notFound': 'Cette publicação est introuvable',
  'admin.posts.notFound.hint': 'Ele não existe mais ou o endereço está errado.',
  'admin.posts.publishedOn': 'Published on {date}',
  'admin.posts.stat.likes': 'Likes',
  'admin.posts.stat.comments': 'Comentários',
  'admin.posts.stat.shares': 'Shares',
  'admin.posts.stat.views': 'Visualizações',
  'admin.posts.stat.bookmarks': 'Bookmarks',
  'admin.posts.stat.reposts': 'Reposts',
  'admin.posts.section.content': 'Conteúdo',
  'admin.posts.content.restricted': 'This post has a restricted audience: its text appears only em this record, for moderation — never in the list.',
  'admin.posts.content.empty': 'Cette publicação n’a pas de texte.',
  'admin.posts.content.language': 'Original language',
  'admin.posts.content.languageUnknown': 'Language not detected',
  'admin.posts.content.translations.none': 'Not translated yet',
  'admin.posts.content.translations.one': 'Translated into {count} language',
  'admin.posts.content.translations.other': 'Translated into {count} languages',
  'admin.posts.content.mood': 'Mood',
  'admin.posts.section.media': 'Mídia',
  'admin.posts.media.open': 'Open media item {index}',
  'admin.posts.media.kind.image': 'Imagem',
  'admin.posts.media.kind.video': 'Vídeo',
  'admin.posts.media.kind.audio': 'Áudio',
  'admin.posts.media.kind.file': 'Arquivo',
  'admin.posts.media.caption': 'Caption: {text}',
  'admin.posts.media.alt': 'Alternative text: {text}',
  'admin.posts.section.context': 'Author and context',
  'admin.posts.context.author': 'Autor',
  'admin.posts.context.authorPosts': 'Voir ses publicaçãos',
  'admin.posts.context.community': 'Comunidade',
  'admin.posts.context.repost': 'Repost of',
  'admin.posts.context.repostQuote': 'Repost with a comment',
  'admin.posts.context.repostSimple': 'Plain repost',
  'admin.posts.section.comments': 'Latest comments',
  'admin.posts.comments.caption': 'Latest comments: {shown} de {total}',
  'admin.posts.comments.empty': 'No comments yet.',
  'admin.posts.comments.noText': 'Comment without text',
  'admin.posts.section.viewers': 'Latest viewers',
  'admin.posts.viewers.caption': 'Latest viewers: {shown} de {total}',
  'admin.posts.viewers.empty': 'Personne n’a encore vu cette publicação.',
  'admin.posts.meta.type': 'Tipo',
  'admin.posts.meta.visibility': 'Visibilidade',
  'admin.posts.meta.state': 'Estado',
  'admin.posts.meta.pinned': 'Fixação',
  'admin.posts.meta.pinned.yes': 'Fixado',
  'admin.posts.meta.pinned.no': 'Não fixado',
  'admin.posts.meta.edited': 'Editing',
  'admin.posts.meta.edited.yes': 'Edited on {date}',
  'admin.posts.meta.edited.no': 'Never edited',
  'admin.posts.meta.expires': 'End de life',
  'admin.posts.meta.expires.future': 'o post will disappear por itself on this date.',
  'admin.posts.meta.created': 'Publicado',
  'admin.posts.meta.updated': 'Atualizado',
  'admin.posts.meta.updated.explain': 'Change aussi quand un compteur de vues ou de reações bouge.',
  'admin.posts.audience.only.one': 'Visible para {count} chosen person',
  'admin.posts.audience.only.other': 'Visible para {count} chosen people',
  'admin.posts.audience.except.one': 'Hidden de {count} person',
  'admin.posts.audience.except.other': 'Hidden de {count} people',

  /* ─── Posts: removal ─── */
  'admin.posts.remove.action': 'Remover o post',
  'admin.posts.remove.title': 'Retirer cette publicação ?',
  'admin.posts.remove.body': 'The post disappears from every reader’s feed, its author included, and the links that led para it are cut. It is not erased, but this console cannot restore it.',
  'admin.posts.remove.motive': 'Motivo da remoção (registado no registo)',
  'admin.posts.remove.confirm': 'Remover o post',
  'admin.posts.remove.done': 'Publicação removida',
  'admin.posts.remove.already': 'Cette publicação était déjà retirée.',

  /* ─── Communities: the list ─── */
  'admin.community.subtitle': 'o platform’s communities: who runs them, how many people are still in, and what they contain.',
  'admin.community.caption': 'Comunidades',
  'admin.community.search': 'Search (name, identifier, description)',
  'admin.community.count': 'Resultados: {count}',
  'admin.community.unnamed': 'Comunidade',
  'admin.community.filter.visibility': 'Visibilidade',
  'admin.community.filter.visibility.private': 'Privado',
  'admin.community.filter.visibility.public': 'Público',
  'admin.community.filter.state': 'Estado',
  'admin.community.filter.state.active': 'Ativo',
  'admin.community.filter.state.inactive': 'Desativado',
  'admin.community.col.community': 'Comunidade',
  'admin.community.col.visibility': 'Visibilidade',
  'admin.community.col.members': 'Membros ativos',
  'admin.community.col.conversations': 'Conversas',
  'admin.community.col.creator': 'Criado por',
  'admin.community.col.state': 'Estado',
  'admin.community.col.created': 'Criado',
  'admin.community.empty': 'No communities',
  'admin.community.empty.hint': 'Communities will appear here as soon as someone creates one.',
  'admin.community.filtered': 'No communities match these filters',
  'admin.community.visibility.private': 'Privado',
  'admin.community.visibility.private.explain': 'Out de search: it can only be joined by invitation, and its page is readable by its members only.',
  'admin.community.visibility.public': 'Público',
  'admin.community.visibility.public.explain': 'In search: anyone can join it and read its page.',
  'admin.community.state.active': 'Ativo',
  'admin.community.state.inactive': 'Desativado',
  'admin.community.state.inactive.explain': 'Removed from lists and search, nobody can join it any more. Its conversations and members stay em place.',

  /* ─── Communities: the record ─── */
  'admin.community.notFound': 'This community cannot be found',
  'admin.community.notFound.hint': 'Ele não existe mais ou o endereço está errado.',
  'admin.community.banner': 'Community banner',
  'admin.community.stat.members': 'Membros ativos',
  'admin.community.stat.left': 'Departures',
  'admin.community.stat.conversations': 'Conversas',
  'admin.community.stat.posts': 'Postagens',
  'admin.community.tabs.label': 'Community sections',
  'admin.community.tab.overview': 'Overview',
  'admin.community.tab.members': 'Membros',
  'admin.community.section.description': 'Descrição',
  'admin.community.description.empty': 'This community has no description.',
  'admin.community.section.staff': 'Equipa',
  'admin.community.staff.empty': 'No active administrator or moderator.',
  'admin.community.section.conversations': 'Conversas',
  'admin.community.conversations.empty': 'This community has no conversation yet.',
  'admin.community.conversations.meta': '{type} · Membros: {count}',
  'admin.community.conversations.metaInactive': '{type} · Membros: {count} · Inativa',
  'admin.community.conversations.more': 'As 20 conversas ativas mais recentemente, num total de {total}.',
  'admin.community.meta.visibility': 'Visibilidade',
  'admin.community.meta.state': 'Estado',
  'admin.community.meta.identifier': 'Public identifier',
  'admin.community.meta.creator': 'Criador',
  'admin.community.meta.created': 'Criado',
  'admin.community.meta.updated': 'Atualizado',
  'admin.community.meta.deactivated': 'Deactivated on',

  /* ─── Communities: members ─── */
  'admin.community.members.caption': 'Community members',
  'admin.community.members.search': 'Search a member',
  'admin.community.members.count': 'Resultados: {count}',
  'admin.community.members.filter.role': 'Papel',
  'admin.community.members.filter.active': 'Presença',
  'admin.community.members.active.yes': 'Presente',
  'admin.community.members.active.no': 'Saiu',
  'admin.community.members.col.member': 'Membro',
  'admin.community.members.col.role': 'Papel',
  'admin.community.members.col.state': 'Estado',
  'admin.community.members.col.joined': 'Joined',
  'admin.community.members.col.left': 'Saiu',
  'admin.community.members.state.present': 'Presente',
  'admin.community.members.state.left': 'Saiu',
  'admin.community.members.empty': 'No members',
  'admin.community.members.empty.hint': 'Nobody has joined this community yet.',
  'admin.community.members.filtered': 'No members match these filters',

  /* ─── Communities: actions ─── */
  'admin.community.action.deactivate': 'Deactivate o/a community',
  'admin.community.action.reactivate': 'Reactivate o/a community',
  'admin.community.action.makePrivate': 'Make private',
  'admin.community.action.makePublic': 'Make public',
  'admin.community.motive': 'Motivo (registado no registo de auditoria)',
  'admin.community.deactivate.title': 'Deactivate this community?',
  'admin.community.deactivate.body': 'It disappears from lists and search, nobody can join it any more, and its page answers “not found” to readers. Its conversations and members stay em place: the people talking there do not lose their conversation.',
  'admin.community.reactivate.title': 'Reactivate this community?',
  'admin.community.reactivate.body': 'It reappears em lists and search, and can be joined again.',
  'admin.community.makePrivate.title': 'Make this community private?',
  'admin.community.makePrivate.body': 'It leaves search, it can no longer be joined without an invitation, and its page is readable por its members only. Current members stay.',
  'admin.community.makePublic.title': 'Make this community public?',
  'admin.community.makePublic.body': 'It appears em search, anyone can join it without an invitation, and its page becomes readable by everyone.',
  'admin.community.done.deactivated': 'Comunidade',
  'admin.community.done.reactivated': 'Comunidade',
  'admin.community.done.private': 'Comunidade',
  'admin.community.done.public': 'Comunidade',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
