/**
 * LE FRAGMENT « conversations-agent » DU CATALOGUE D’ADMINISTRATION (#8876) — la
 * liste et la fiche des conversations, la lecture souveraine, et le pilotage de
 * l’agent. Préfixes exclusifs : `admin.conversation.` et `admin.agentPanel.`.
 *
 * Les libellés de types, d’états, de rôles, de chiffrement et de présence ne sont
 * PAS ici : ils vivent dans le fragment du kit (`admin.enum.*`), source unique de
 * leur interprétation. Les clés `admin.conv*` et `admin.agent.*` du catalogue de
 * base (lecture souveraine, feuille « Configurer », relance de l’agent) restent
 * celles des écrans qui les portent déjà.
 */
const f = {
  'admin.conversation.subtitle':
    'Toutes les conversations de la plateforme : qui les compose, où elles en sont, à quelle communauté elles appartiennent. Le contenu des messages ne se lit que sous motif écrit, depuis la fiche.',
  'admin.conversation.search': 'Rechercher par titre ou identifiant',
  'admin.conversation.list.caption': 'Liste des conversations',
  'admin.conversation.list.count': '{count} conversation(s)',
  'admin.conversation.list.empty': 'Aucune conversation',
  'admin.conversation.list.emptyHint': 'Les conversations créées sur la plateforme apparaissent ici.',
  'admin.conversation.list.filteredEmpty': 'Aucune conversation pour ces filtres',
  'admin.conversation.list.onCommunity': 'Conversations d’une seule communauté : retirez le filtre pour revoir toutes les conversations.',
  'admin.conversation.list.onCommunityNamed': 'Conversations de la communauté « {name} » : retirez le filtre pour revoir toutes les conversations.',
  'admin.conversation.list.onCommunityReset': 'Voir toutes les conversations',

  'admin.conversation.filter.type': 'Type',
  'admin.conversation.filter.state': 'État',
  'admin.conversation.filter.state.active': 'Actives',
  'admin.conversation.filter.state.archived': 'Archivées',
  'admin.conversation.filter.period': 'Créées sur',
  'admin.conversation.filter.period.all': 'Toute la période',

  'admin.conversation.col.conversation': 'Conversation',
  'admin.conversation.col.type': 'Type',
  'admin.conversation.col.community': 'Communauté',
  'admin.conversation.col.members': 'Membres',
  'admin.conversation.col.state': 'État',
  'admin.conversation.col.created': 'Création',
  'admin.conversation.col.lastMessage': 'Dernier message',

  'admin.conversation.fiche.loading': 'Chargement de la conversation',
  'admin.conversation.fiche.notFound': 'Cette conversation n’existe plus',
  'admin.conversation.fiche.notFoundHint': 'Elle a été supprimée, ou l’adresse est incorrecte.',
  'admin.conversation.fiche.back': 'Retour aux conversations',
  'admin.conversation.fiche.configure': 'Configurer',

  'admin.conversation.stat.members': 'Membres actifs',
  'admin.conversation.stat.messages': 'Messages',
  'admin.conversation.stat.shareLinks': 'Liens de partage',
  'admin.conversation.stat.agent': 'Agent',
  'admin.conversation.stat.agent.on': 'Actif',
  'admin.conversation.stat.agent.off': 'Inactif',
  'admin.conversation.badge.agent': 'Agent actif',

  'admin.conversation.meta.type': 'Type',
  'admin.conversation.meta.identifier': 'Identifiant public',
  'admin.conversation.meta.identifierExplain': 'Son adresse lisible, distincte de l’identifiant technique.',
  'admin.conversation.meta.description': 'Description',
  'admin.conversation.meta.community': 'Communauté',
  'admin.conversation.meta.state': 'État',
  'admin.conversation.meta.archivedExplain': 'Archivée : plus personne n’y écrit tant qu’elle n’est pas restaurée.',
  'admin.conversation.meta.closedOn': 'Fermée le',
  'admin.conversation.meta.closedBy': 'Fermée par',
  'admin.conversation.meta.writeRole': 'Qui peut écrire',
  'admin.conversation.meta.writeRoleExplain': 'Le rang minimal exigé pour envoyer un message.',
  'admin.conversation.meta.announcement': 'Canal d’annonces',
  'admin.conversation.meta.announcement.yes': 'Oui : seuls les administrateurs y écrivent',
  'admin.conversation.meta.announcement.no': 'Non : conversation ordinaire',
  'admin.conversation.meta.slowMode': 'Mode lent',
  'admin.conversation.meta.slowMode.off': 'Désactivé',
  'admin.conversation.meta.slowMode.on': 'Un message toutes les {duration} par membre',
  'admin.conversation.meta.slowModeExplain': 'Les modérateurs et les rangs au-dessus en sont dispensés.',
  'admin.conversation.meta.autoTranslate': 'Traduction automatique',
  'admin.conversation.meta.autoTranslate.yes': 'Activée : chaque lecteur voit les messages dans sa langue',
  'admin.conversation.meta.autoTranslate.no': 'Désactivée : les messages restent dans leur langue d’origine',
  'admin.conversation.meta.autoTranslate.unknown': 'Non précisée',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inactive : le serveur ne peut pas lire les messages chiffrés de bout en bout',
  'admin.conversation.meta.encryption': 'Chiffrement',
  'admin.conversation.meta.created': 'Créée',
  'admin.conversation.meta.updated': 'Dernière modification',
  'admin.conversation.meta.lastMessage': 'Dernier message',
  'admin.conversation.meta.noMessage': 'Aucun message pour le moment',

  'admin.conversation.members.title': 'Membres',
  'admin.conversation.members.caption': 'Participants de la conversation',
  'admin.conversation.members.count': '{count} participant(s)',
  'admin.conversation.members.empty': 'Aucun participant',
  'admin.conversation.members.col.member': 'Membre',
  'admin.conversation.members.col.role': 'Rôle',
  'admin.conversation.members.col.presence': 'Présence',
  'admin.conversation.members.col.state': 'État',
  'admin.conversation.members.col.joined': 'Arrivée',
  'admin.conversation.members.col.actions': 'Gestes',
  'admin.conversation.members.state.active': 'Actif',
  'admin.conversation.members.state.left': 'A quitté la conversation',
  'admin.conversation.members.roleOf': 'Rôle de {name}',
  'admin.conversation.members.remove': 'Retirer',
  'admin.conversation.members.removeOf': 'Retirer {name} de la conversation',
  'admin.conversation.members.creatorProtected': 'Protégé : le créateur ne peut être ni rétrogradé ni retiré',
  'admin.conversation.members.creatorRefused': 'Le créateur de la conversation est protégé : il ne peut être ni rétrogradé ni retiré.',
  'admin.conversation.members.motive': 'Motif (10 caractères minimum)',
  'admin.conversation.members.role.confirmTitle': 'Changer le rôle',
  'admin.conversation.members.role.confirmBody': '{name} passera de « {from} » à « {to} ». Le changement est consigné dans le journal d’audit avec votre motif.',
  'admin.conversation.members.role.confirm': 'Changer le rôle',
  'admin.conversation.members.role.done': 'Rôle modifié',
  'admin.conversation.members.remove.confirmTitle': 'Retirer de la conversation',
  'admin.conversation.members.remove.confirmBody': '{name} sera retiré de la conversation et n’y aura plus accès. Le retrait est consigné dans le journal d’audit avec votre motif.',
  'admin.conversation.members.remove.confirm': 'Retirer',
  'admin.conversation.members.remove.done': 'Membre retiré',

  'admin.conversation.reading.title': 'Lire la conversation',
  'admin.conversation.reading.hint':
    'Le contenu des messages ne se lit que sous un motif écrit, consigné avec votre nom dans le journal d’audit. Le fil s’affiche dans vos langues de lecture, comme dans l’application.',

  'admin.agentPanel.subtitle': 'Les conversations où l’agent intervient : suivez son activité, relancez-le ou arrêtez un scan en cours.',
  'admin.agentPanel.stat.tracked': 'Conversations pilotées',
  'admin.agentPanel.stat.trackedCaption': 'sur {total} suivies',
  'admin.agentPanel.stat.users': 'Membres pilotés',
  'admin.agentPanel.stat.messages': 'Messages publiés',

  'admin.agentPanel.tracked.caption': 'Conversations suivies par l’agent',
  'admin.agentPanel.tracked.search': 'Rechercher une conversation',
  'admin.agentPanel.tracked.count': '{count} conversation(s)',
  'admin.agentPanel.tracked.empty': 'Aucune conversation suivie',
  'admin.agentPanel.tracked.emptyHint': 'Quand l’agent est configuré pour une conversation, elle apparaît ici.',
  'admin.agentPanel.tracked.filteredEmpty': 'Aucune conversation pour cette recherche',
  'admin.agentPanel.tracked.col.conversation': 'Conversation',
  'admin.agentPanel.tracked.col.state': 'État',
  'admin.agentPanel.tracked.col.users': 'Membres pilotés',
  'admin.agentPanel.tracked.col.messages': 'Messages publiés',
  'admin.agentPanel.tracked.col.lastResponse': 'Dernière réponse',
  'admin.agentPanel.tracked.col.control': 'Pilotage',
  'admin.agentPanel.state.on': 'Activé',
  'admin.agentPanel.state.off': 'Désactivé',
  'admin.agentPanel.state.scanning': 'Scan en cours',
  'admin.agentPanel.lastResponse.never': 'Aucune réponse',

  'admin.agentPanel.logs.caption': 'Journal des scans de l’agent',
  'admin.agentPanel.logs.count': '{count} scan(s)',
  'admin.agentPanel.logs.empty': 'Aucun scan enregistré',
  'admin.agentPanel.logs.emptyHint': 'Chaque passage de l’agent sur une conversation laisse une ligne ici.',
  'admin.agentPanel.logs.filteredEmpty': 'Aucun scan pour ces filtres',
  'admin.agentPanel.logs.filter.outcome': 'Issue',
  'admin.agentPanel.logs.filter.trigger': 'Déclencheur',
  'admin.agentPanel.logs.col.conversation': 'Conversation',
  'admin.agentPanel.logs.col.trigger': 'Déclencheur',
  'admin.agentPanel.logs.col.outcome': 'Issue',
  'admin.agentPanel.logs.col.messages': 'Messages publiés',
  'admin.agentPanel.logs.col.duration': 'Durée',
  'admin.agentPanel.logs.col.started': 'Démarré',
  'admin.agentPanel.logs.open': 'Ouvrir le détail du scan de {name}',

  'admin.agentPanel.outcome.messages_sent': 'Message publié',
  'admin.agentPanel.outcome.messages_sent.explain': 'L’agent a écrit dans la conversation.',
  'admin.agentPanel.outcome.reactions_only': 'Réactions seules',
  'admin.agentPanel.outcome.reactions_only.explain': 'L’agent a réagi à des messages sans en publier.',
  'admin.agentPanel.outcome.skipped': 'Aucune action',
  'admin.agentPanel.outcome.skipped.explain': 'Le cycle s’est terminé sans rien publier.',
  'admin.agentPanel.outcome.error': 'Erreur',
  'admin.agentPanel.outcome.error.explain': 'Le cycle a échoué avant de finir.',
  'admin.agentPanel.trigger.auto': 'Automatique',
  'admin.agentPanel.trigger.auto.explain': 'Lancé par le planificateur de l’agent.',
  'admin.agentPanel.trigger.manual': 'Manuel',
  'admin.agentPanel.trigger.manual.explain': 'Lancé depuis l’administration.',
  'admin.agentPanel.node.observer': 'observe la conversation',
  'admin.agentPanel.node.strategist': 'choisit quoi dire',
  'admin.agentPanel.node.generator': 'rédige un message',
  'admin.agentPanel.node.qualityGate': 'contrôle la qualité',
  'admin.agentPanel.node.unknown': 'étape en cours',

  'admin.agentPanel.detail.title': 'Détail du scan',
  'admin.agentPanel.detail.conversation': 'Conversation',
  'admin.agentPanel.detail.started': 'Démarré',
  'admin.agentPanel.detail.reactions': 'Réactions envoyées',
  'admin.agentPanel.detail.rejected': 'Messages écartés',
  'admin.agentPanel.detail.rejectedExplain': 'Rédigés par l’agent puis refusés par son contrôle de qualité.',
  'admin.agentPanel.detail.users': 'Membres joués',
  'admin.agentPanel.detail.tokens': 'Jetons (entrée / sortie)',
  'admin.agentPanel.detail.cost': 'Coût estimé',

  'admin.agentPanel.conversation.title': 'Agent dans cette conversation',
  'admin.agentPanel.conversation.usersNone': 'Aucun membre piloté pour le moment',
  'admin.agentPanel.conversation.messages': 'Messages publiés',
  'admin.agentPanel.conversation.lastResponse': 'Dernière réponse',
} as const;

export default f;
