import type { AdminCatalogFragment } from './fragment';
import type fr from './conversations-agent-fr';

/**
 * THE “conversations-agent” FRAGMENT OF THE ADMINISTRATION CATALOG (#8876) —
 * Italian text for the conversation list and sheet, the sovereign reading,
 * and the agent control. Same keys as the French source, which stays the
 * reference for meaning; the `admin.enum.*` labels it relies on live in the kit.
 */
const f = {
  'admin.conversation.subtitle':
    'Tutte le conversazioni della piattaforma: chi le compone, a che punto sono e a quale community appartengono. Il contenuto dei messaggi si legge solo con un motivo scritto, dalla scheda.',
  'admin.conversation.search': 'Cerca per titolo o identificativo',
  'admin.conversation.list.caption': 'Elenco delle conversazioni',
  'admin.conversation.list.count': '{count} conversazione/i',
  'admin.conversation.list.empty': 'Nessuna conversazione',
  'admin.conversation.list.emptyHint': 'Le conversazioni create sulla piattaforma compaiono qui.',
  'admin.conversation.list.filteredEmpty': 'Nessuna conversazione per questi filtri',
  'admin.conversation.list.onCommunity': 'Conversazioni di una sola community: rimuovi il filtro per rivedere tutte le conversazioni.',
  'admin.conversation.list.onCommunityNamed':
    'Conversazioni della community «{name}»: rimuovi il filtro per rivedere tutte le conversazioni.',
  'admin.conversation.list.onCommunityReset': 'Vedi tutte le conversazioni',

  'admin.conversation.filter.type': 'Tipo',
  'admin.conversation.filter.state': 'Stato',
  'admin.conversation.filter.state.active': 'Attive',
  'admin.conversation.filter.state.archived': 'Archiviate',
  'admin.conversation.filter.period': 'Create negli ultimi',
  'admin.conversation.filter.period.all': 'Tutto il periodo',

  'admin.conversation.col.conversation': 'Conversazione',
  'admin.conversation.col.type': 'Tipo',
  'admin.conversation.col.community': 'Community',
  'admin.conversation.col.members': 'Membri',
  'admin.conversation.col.state': 'Stato',
  'admin.conversation.col.created': 'Creazione',
  'admin.conversation.col.lastMessage': 'Ultimo messaggio',

  'admin.conversation.fiche.loading': 'Caricamento della conversazione',
  'admin.conversation.fiche.notFound': 'Questa conversazione non esiste più',
  'admin.conversation.fiche.notFoundHint': 'È stata eliminata, oppure l’indirizzo è errato.',
  'admin.conversation.fiche.back': 'Torna alle conversazioni',
  'admin.conversation.fiche.configure': 'Configura',

  'admin.conversation.stat.members': 'Membri attivi',
  'admin.conversation.stat.messages': 'Messaggi',
  'admin.conversation.stat.shareLinks': 'Link di condivisione',
  'admin.conversation.stat.agent': 'Agente',
  'admin.conversation.stat.agent.on': 'Attivo',
  'admin.conversation.stat.agent.off': 'Inattivo',
  'admin.conversation.badge.agent': 'Agente attivo',

  'admin.conversation.meta.type': 'Tipo',
  'admin.conversation.meta.identifier': 'Identificativo pubblico',
  'admin.conversation.meta.identifierExplain': 'Il suo indirizzo leggibile, distinto dall’identificativo tecnico.',
  'admin.conversation.meta.description': 'Descrizione',
  'admin.conversation.meta.community': 'Community',
  'admin.conversation.meta.state': 'Stato',
  'admin.conversation.meta.archivedExplain': 'Archiviata: nessuno può scriverci finché non viene ripristinata.',
  'admin.conversation.meta.closedOn': 'Chiusa il',
  'admin.conversation.meta.closedBy': 'Chiusa da',
  'admin.conversation.meta.writeRole': 'Chi può scrivere',
  'admin.conversation.meta.writeRoleExplain': 'Il grado minimo richiesto per inviare un messaggio.',
  'admin.conversation.meta.announcement': 'Canale di annunci',
  'admin.conversation.meta.announcement.yes': 'Sì: solo gli amministratori vi scrivono',
  'admin.conversation.meta.announcement.no': 'No: conversazione ordinaria',
  'admin.conversation.meta.slowMode': 'Modalità lenta',
  'admin.conversation.meta.slowMode.off': 'Disattivata',
  'admin.conversation.meta.slowMode.on': 'Un messaggio ogni {duration} per membro',
  'admin.conversation.meta.slowModeExplain': 'I moderatori e i gradi superiori ne sono esentati.',
  'admin.conversation.meta.autoTranslate': 'Traduzione automatica',
  'admin.conversation.meta.autoTranslate.yes': 'Attiva: ogni lettore vede i messaggi nella propria lingua',
  'admin.conversation.meta.autoTranslate.no': 'Disattivata: i messaggi restano nella lingua originale',
  'admin.conversation.meta.autoTranslate.unknown': 'Non specificata',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inattiva: il server non può leggere i messaggi cifrati end-to-end',
  'admin.conversation.meta.encryption': 'Cifratura',
  'admin.conversation.meta.created': 'Creata',
  'admin.conversation.meta.updated': 'Ultima modifica',
  'admin.conversation.meta.lastMessage': 'Ultimo messaggio',
  'admin.conversation.meta.noMessage': 'Ancora nessun messaggio',

  'admin.conversation.members.title': 'Membri',
  'admin.conversation.members.caption': 'Partecipanti alla conversazione',
  'admin.conversation.members.count': '{count} partecipante/i',
  'admin.conversation.members.empty': 'Nessun partecipante',
  'admin.conversation.members.col.member': 'Membro',
  'admin.conversation.members.col.role': 'Ruolo',
  'admin.conversation.members.col.presence': 'Presenza',
  'admin.conversation.members.col.state': 'Stato',
  'admin.conversation.members.col.joined': 'Arrivo',
  'admin.conversation.members.col.actions': 'Azioni',
  'admin.conversation.members.state.active': 'Attivo',
  'admin.conversation.members.state.left': 'Ha lasciato la conversazione',
  'admin.conversation.members.roleOf': 'Ruolo di {name}',
  'admin.conversation.members.remove': 'Rimuovi',
  'admin.conversation.members.removeOf': 'Rimuovi {name} dalla conversazione',
  'admin.conversation.members.creatorProtected': 'Protetto: il creatore non può essere retrocesso né rimosso',
  'admin.conversation.members.creatorRefused': 'Il creatore della conversazione è protetto: non può essere retrocesso né rimosso.',
  'admin.conversation.members.motive': 'Motivo (minimo 10 caratteri)',
  'admin.conversation.members.role.confirmTitle': 'Cambia il ruolo',
  'admin.conversation.members.role.confirmBody':
    '{name} passerà da «{from}» a «{to}». La modifica viene registrata nel registro di controllo con il tuo motivo.',
  'admin.conversation.members.role.confirm': 'Cambia il ruolo',
  'admin.conversation.members.role.done': 'Ruolo modificato',
  'admin.conversation.members.remove.confirmTitle': 'Rimuovi dalla conversazione',
  'admin.conversation.members.remove.confirmBody':
    '{name} verrà rimosso dalla conversazione e non vi avrà più accesso. La rimozione viene registrata nel registro di controllo con il tuo motivo.',
  'admin.conversation.members.remove.confirm': 'Rimuovi',
  'admin.conversation.members.remove.done': 'Membro rimosso',

  'admin.conversation.reading.title': 'Leggi la conversazione',
  'admin.conversation.reading.hint':
    'Il contenuto dei messaggi si legge solo con un motivo scritto, registrato con il tuo nome nel registro di controllo. Il thread viene mostrato nelle tue lingue di lettura, come nell’app.',

  'admin.agentPanel.subtitle':
    'Le conversazioni in cui interviene l’agente: segui la sua attività, rilancialo o ferma una scansione in corso.',
  'admin.agentPanel.stat.tracked': 'Conversazioni pilotate',
  'admin.agentPanel.stat.trackedCaption': 'su {total} seguite',
  'admin.agentPanel.stat.users': 'Membri pilotati',
  'admin.agentPanel.stat.messages': 'Messaggi pubblicati',

  'admin.agentPanel.tracked.caption': 'Conversazioni seguite dall’agente',
  'admin.agentPanel.tracked.search': 'Cerca una conversazione',
  'admin.agentPanel.tracked.count': '{count} conversazione/i',
  'admin.agentPanel.tracked.empty': 'Nessuna conversazione seguita',
  'admin.agentPanel.tracked.emptyHint': 'Quando l’agente è configurato per una conversazione, compare qui.',
  'admin.agentPanel.tracked.filteredEmpty': 'Nessuna conversazione per questa ricerca',
  'admin.agentPanel.tracked.col.conversation': 'Conversazione',
  'admin.agentPanel.tracked.col.state': 'Stato',
  'admin.agentPanel.tracked.col.users': 'Membri pilotati',
  'admin.agentPanel.tracked.col.messages': 'Messaggi pubblicati',
  'admin.agentPanel.tracked.col.lastResponse': 'Ultima risposta',
  'admin.agentPanel.tracked.col.control': 'Controllo',
  'admin.agentPanel.state.on': 'Attivato',
  'admin.agentPanel.state.off': 'Disattivato',
  'admin.agentPanel.state.scanning': 'Scansione in corso',
  'admin.agentPanel.lastResponse.never': 'Nessuna risposta',

  'admin.agentPanel.logs.caption': 'Registro delle scansioni dell’agente',
  'admin.agentPanel.logs.count': '{count} scansione/i',
  'admin.agentPanel.logs.empty': 'Nessuna scansione registrata',
  'admin.agentPanel.logs.emptyHint': 'Ogni passaggio dell’agente su una conversazione lascia una riga qui.',
  'admin.agentPanel.logs.filteredEmpty': 'Nessuna scansione per questi filtri',
  'admin.agentPanel.logs.filter.outcome': 'Esito',
  'admin.agentPanel.logs.filter.trigger': 'Avvio',
  'admin.agentPanel.logs.col.conversation': 'Conversazione',
  'admin.agentPanel.logs.col.trigger': 'Avvio',
  'admin.agentPanel.logs.col.outcome': 'Esito',
  'admin.agentPanel.logs.col.messages': 'Messaggi pubblicati',
  'admin.agentPanel.logs.col.duration': 'Durata',
  'admin.agentPanel.logs.col.started': 'Inizio',
  'admin.agentPanel.logs.open': 'Apri il dettaglio della scansione di {name}',

  'admin.agentPanel.outcome.messages_sent': 'Messaggio pubblicato',
  'admin.agentPanel.outcome.messages_sent.explain': 'L’agente ha scritto nella conversazione.',
  'admin.agentPanel.outcome.reactions_only': 'Solo reazioni',
  'admin.agentPanel.outcome.reactions_only.explain': 'L’agente ha reagito ai messaggi senza pubblicarne alcuno.',
  'admin.agentPanel.outcome.skipped': 'Nessuna azione',
  'admin.agentPanel.outcome.skipped.explain': 'Il ciclo è terminato senza pubblicare nulla.',
  'admin.agentPanel.outcome.error': 'Errore',
  'admin.agentPanel.outcome.error.explain': 'Il ciclo è fallito prima di terminare.',
  'admin.agentPanel.trigger.auto': 'Automatico',
  'admin.agentPanel.trigger.auto.explain': 'Avviato dal pianificatore dell’agente.',
  'admin.agentPanel.trigger.manual': 'Manuale',
  'admin.agentPanel.trigger.manual.explain': 'Avviato dall’amministrazione.',
  'admin.agentPanel.node.observer': 'legge la conversazione',
  'admin.agentPanel.node.strategist': 'sceglie cosa dire',
  'admin.agentPanel.node.generator': 'scrive un messaggio',
  'admin.agentPanel.node.qualityGate': 'controlla la qualità',
  'admin.agentPanel.node.unknown': 'sta lavorando',

  'admin.agentPanel.detail.title': 'Dettaglio della scansione',
  'admin.agentPanel.detail.conversation': 'Conversazione',
  'admin.agentPanel.detail.started': 'Inizio',
  'admin.agentPanel.detail.reactions': 'Reazioni inviate',
  'admin.agentPanel.detail.rejected': 'Messaggi scartati',
  'admin.agentPanel.detail.rejectedExplain': 'Scritti dall’agente e poi rifiutati dal suo controllo di qualità.',
  'admin.agentPanel.detail.users': 'Membri interpretati',
  'admin.agentPanel.detail.tokens': 'Token (ingresso / uscita)',
  'admin.agentPanel.detail.cost': 'Costo stimato',

  'admin.agentPanel.conversation.title': 'Agente in questa conversazione',
  'admin.agentPanel.conversation.usersNone': 'Nessun membro pilotato per ora',
  'admin.agentPanel.conversation.messages': 'Messaggi pubblicati',
  'admin.agentPanel.conversation.lastResponse': 'Ultima risposta',
} as const satisfies AdminCatalogFragment<typeof fr>;

export default f;
