import type { AdminCatalogFragment } from './fragment';
import type fr from './conversations-agent-fr';

/**
 * THE “conversations-agent” FRAGMENT OF THE ADMINISTRATION CATALOG (#8876) —
 * Portuguese (Brazil) text for the conversation list and sheet, the sovereign reading,
 * and the agent control. Same keys as the French source, which stays the
 * reference for meaning; the `admin.enum.*` labels it relies on live in the kit.
 */
const f = {
  'admin.conversation.subtitle':
    'Todas as conversas da plataforma: quem as compõe, em que ponto estão e a que comunidade pertencem. O conteúdo das mensagens só se lê com um motivo escrito, a partir da ficha.',
  'admin.conversation.search': 'Pesquisar por título ou identificador',
  'admin.conversation.list.caption': 'Lista de conversas',
  'admin.conversation.list.count': '{count} conversa(s)',
  'admin.conversation.list.empty': 'Nenhuma conversa',
  'admin.conversation.list.emptyHint': 'As conversas criadas na plataforma aparecem aqui.',
  'admin.conversation.list.filteredEmpty': 'Nenhuma conversa com estes filtros',
  'admin.conversation.list.onCommunity': 'Conversas de uma única comunidade: remova o filtro para voltar a ver todas as conversas.',
  'admin.conversation.list.onCommunityNamed': 'Conversas da comunidade «{name}»: remova o filtro para voltar a ver todas as conversas.',
  'admin.conversation.list.onCommunityReset': 'Ver todas as conversas',

  'admin.conversation.filter.type': 'Tipo',
  'admin.conversation.filter.state': 'Estado',
  'admin.conversation.filter.state.active': 'Ativas',
  'admin.conversation.filter.state.archived': 'Arquivadas',
  'admin.conversation.filter.period': 'Criadas nos últimos',
  'admin.conversation.filter.period.all': 'Todo o período',

  'admin.conversation.col.conversation': 'Conversa',
  'admin.conversation.col.type': 'Tipo',
  'admin.conversation.col.community': 'Comunidade',
  'admin.conversation.col.members': 'Membros',
  'admin.conversation.col.state': 'Estado',
  'admin.conversation.col.created': 'Criação',
  'admin.conversation.col.lastMessage': 'Última mensagem',

  'admin.conversation.fiche.loading': 'Carregando a conversa',
  'admin.conversation.fiche.notFound': 'Esta conversa não existe mais',
  'admin.conversation.fiche.notFoundHint': 'Foi excluída, ou o endereço está incorreto.',
  'admin.conversation.fiche.back': 'Voltar às conversas',
  'admin.conversation.fiche.configure': 'Configurar',

  'admin.conversation.stat.members': 'Membros ativos',
  'admin.conversation.stat.messages': 'Mensagens',
  'admin.conversation.stat.shareLinks': 'Links de compartilhamento',
  'admin.conversation.stat.agent': 'Agente',
  'admin.conversation.stat.agent.on': 'Ativo',
  'admin.conversation.stat.agent.off': 'Inativo',
  'admin.conversation.badge.agent': 'Agente ativo',

  'admin.conversation.meta.type': 'Tipo',
  'admin.conversation.meta.identifier': 'Identificador público',
  'admin.conversation.meta.identifierExplain': 'O seu endereço legível, distinto do identificador técnico.',
  'admin.conversation.meta.description': 'Descrição',
  'admin.conversation.meta.community': 'Comunidade',
  'admin.conversation.meta.state': 'Estado',
  'admin.conversation.meta.archivedExplain': 'Arquivada: ninguém pode escrever nela até ser restaurada.',
  'admin.conversation.meta.closedOn': 'Fechada em',
  'admin.conversation.meta.closedBy': 'Fechada por',
  'admin.conversation.meta.writeRole': 'Quem pode escrever',
  'admin.conversation.meta.writeRoleExplain': 'O nível mínimo exigido para enviar uma mensagem.',
  'admin.conversation.meta.announcement': 'Canal de anúncios',
  'admin.conversation.meta.announcement.yes': 'Sim: só os administradores escrevem nele',
  'admin.conversation.meta.announcement.no': 'Não: conversa comum',
  'admin.conversation.meta.slowMode': 'Modo lento',
  'admin.conversation.meta.slowMode.off': 'Desativado',
  'admin.conversation.meta.slowMode.on': 'Uma mensagem a cada {duration} por membro',
  'admin.conversation.meta.slowModeExplain': 'Os moderadores e os níveis acima estão isentos.',
  'admin.conversation.meta.autoTranslate': 'Tradução automática',
  'admin.conversation.meta.autoTranslate.yes': 'Ativada: cada leitor vê as mensagens no seu idioma',
  'admin.conversation.meta.autoTranslate.no': 'Desativada: as mensagens ficam no idioma original',
  'admin.conversation.meta.autoTranslate.unknown': 'Não especificada',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inativa: o servidor não consegue ler mensagens criptografadas de ponta a ponta',
  'admin.conversation.meta.encryption': 'Criptografia',
  'admin.conversation.meta.created': 'Criada',
  'admin.conversation.meta.updated': 'Última modificação',
  'admin.conversation.meta.lastMessage': 'Última mensagem',
  'admin.conversation.meta.noMessage': 'Ainda sem mensagens',

  'admin.conversation.members.title': 'Membros',
  'admin.conversation.members.caption': 'Participantes da conversa',
  'admin.conversation.members.count': '{count} participante(s)',
  'admin.conversation.members.empty': 'Nenhum participante',
  'admin.conversation.members.col.member': 'Membro',
  'admin.conversation.members.col.role': 'Função',
  'admin.conversation.members.col.presence': 'Presença',
  'admin.conversation.members.col.state': 'Estado',
  'admin.conversation.members.col.joined': 'Entrada',
  'admin.conversation.members.col.actions': 'Ações',
  'admin.conversation.members.state.active': 'Ativo',
  'admin.conversation.members.state.left': 'Saiu da conversa',
  'admin.conversation.members.roleOf': 'Função de {name}',
  'admin.conversation.members.remove': 'Remover',
  'admin.conversation.members.removeOf': 'Remover {name} da conversa',
  'admin.conversation.members.creatorProtected': 'Protegido: o criador não pode ser rebaixado nem removido',
  'admin.conversation.members.creatorRefused': 'O criador da conversa está protegido: não pode ser rebaixado nem removido.',
  'admin.conversation.members.motive': 'Motivo (mínimo de 10 caracteres)',
  'admin.conversation.members.role.confirmTitle': 'Alterar a função',
  'admin.conversation.members.role.confirmBody': '{name} passará de «{from}» a «{to}». A alteração fica registrada no registro de auditoria com o seu motivo.',
  'admin.conversation.members.role.confirm': 'Alterar a função',
  'admin.conversation.members.role.done': 'Função alterada',
  'admin.conversation.members.remove.confirmTitle': 'Remover da conversa',
  'admin.conversation.members.remove.confirmBody':
    '{name} será removido da conversa e deixará de ter acesso a ela. A remoção fica registrada no registro de auditoria com o seu motivo.',
  'admin.conversation.members.remove.confirm': 'Remover',
  'admin.conversation.members.remove.done': 'Membro removido',

  'admin.conversation.reading.title': 'Ler a conversa',
  'admin.conversation.reading.hint': 'O conteúdo das mensagens só se lê com um motivo escrito, registrado com o seu nome no registro de auditoria. O fio é mostrado nos seus idiomas de leitura, como no aplicativo.',

  'admin.agentPanel.subtitle': 'As conversas em que o agente intervém: acompanhe a atividade dele, relance-o, ajuste seu modelo, seus temas e sua fila de entrega.',
  'admin.agentPanel.stat.tracked': 'Conversas controladas',
  'admin.agentPanel.stat.trackedCaption': 'de {total} configuradas',
  'admin.agentPanel.stat.users': 'Membros controlados',
  'admin.agentPanel.stat.messages': 'Mensagens publicadas',

  'admin.agentPanel.tracked.caption': 'Conversas acompanhadas pelo agente',
  'admin.agentPanel.tracked.search': 'Pesquisar uma conversa',
  'admin.agentPanel.tracked.count': '{count} conversa(s)',
  'admin.agentPanel.tracked.empty': 'Nenhuma conversa acompanhada',
  'admin.agentPanel.tracked.emptyHint': 'Quando o agente é configurado para uma conversa, ela aparece aqui.',
  'admin.agentPanel.tracked.filteredEmpty': 'Nenhuma conversa para esta pesquisa',
  'admin.agentPanel.tracked.col.conversation': 'Conversa',
  'admin.agentPanel.tracked.col.state': 'Estado',
  'admin.agentPanel.tracked.col.users': 'Membros controlados',
  'admin.agentPanel.tracked.col.messages': 'Mensagens publicadas',
  'admin.agentPanel.tracked.col.lastResponse': 'Última resposta',
  'admin.agentPanel.tracked.col.control': 'Controle',
  'admin.agentPanel.state.on': 'Ativado',
  'admin.agentPanel.state.off': 'Desativado',
  'admin.agentPanel.state.scanning': 'Análise em andamento',
  'admin.agentPanel.lastResponse.never': 'Nenhuma resposta',

  'admin.agentPanel.logs.caption': 'Registro das análises do agente',
  'admin.agentPanel.logs.count': '{count} análise(s)',
  'admin.agentPanel.logs.empty': 'Nenhuma análise registrada',
  'admin.agentPanel.logs.emptyHint': 'Cada passagem do agente por uma conversa deixa uma linha aqui.',
  'admin.agentPanel.logs.filteredEmpty': 'Nenhuma análise com estes filtros',
  'admin.agentPanel.logs.filter.outcome': 'Resultado',
  'admin.agentPanel.logs.filter.trigger': 'Acionador',
  'admin.agentPanel.logs.col.conversation': 'Conversa',
  'admin.agentPanel.logs.col.trigger': 'Acionador',
  'admin.agentPanel.logs.col.outcome': 'Resultado',
  'admin.agentPanel.logs.col.messages': 'Mensagens publicadas',
  'admin.agentPanel.logs.col.duration': 'Duração',
  'admin.agentPanel.logs.col.started': 'Início',
  'admin.agentPanel.logs.open': 'Abrir o detalhe da análise de {name}',

  'admin.agentPanel.outcome.messages_sent': 'Mensagem publicada',
  'admin.agentPanel.outcome.messages_sent.explain': 'O agente escreveu na conversa.',
  'admin.agentPanel.outcome.reactions_only': 'Só reações',
  'admin.agentPanel.outcome.reactions_only.explain': 'O agente reagiu a mensagens sem publicar nenhuma.',
  'admin.agentPanel.outcome.skipped': 'Nenhuma ação',
  'admin.agentPanel.outcome.skipped.explain': 'O ciclo terminou sem publicar nada.',
  'admin.agentPanel.outcome.error': 'Erro',
  'admin.agentPanel.outcome.error.explain': 'O ciclo falhou antes de terminar.',
  'admin.agentPanel.trigger.auto': 'Automático',
  'admin.agentPanel.trigger.auto.explain': 'Iniciado pelo planejador do agente.',
  'admin.agentPanel.trigger.manual': 'Manual',
  'admin.agentPanel.trigger.manual.explain': 'Iniciado a partir da administração.',
  'admin.agentPanel.node.observer': 'lê a conversa',
  'admin.agentPanel.node.strategist': 'decide o que dizer',
  'admin.agentPanel.node.generator': 'redige uma mensagem',
  'admin.agentPanel.node.qualityGate': 'controla a qualidade',
  'admin.agentPanel.node.unknown': 'está trabalhando',

  'admin.agentPanel.detail.title': 'Detalhe da análise',
  'admin.agentPanel.detail.conversation': 'Conversa',
  'admin.agentPanel.detail.started': 'Início',
  'admin.agentPanel.detail.reactions': 'Reações enviadas',
  'admin.agentPanel.detail.rejected': 'Mensagens descartadas',
  'admin.agentPanel.detail.rejectedExplain': 'Redigidas pelo agente e recusadas pelo controle de qualidade dele.',
  'admin.agentPanel.detail.users': 'Membros interpretados',
  'admin.agentPanel.detail.tokens': 'Tokens (entrada / saída)',
  'admin.agentPanel.detail.cost': 'Custo estimado',

  'admin.agentPanel.conversation.title': 'Agente nesta conversa',
  'admin.agentPanel.conversation.usersNone': 'Nenhum membro controlado no momento',
  'admin.agentPanel.conversation.messages': 'Mensagens publicadas',
  'admin.agentPanel.conversation.lastResponse': 'Última resposta',
  /* ─── Fiche en cartes et données servies (lot Échanges et contenus, 2026-10-05) ─── */
  'admin.conversation.cards.title': 'O detalhe, por seção',
  'admin.conversation.card.settings': 'Ajustes e metadados',
  'admin.conversation.card.community': 'Comunidade',
  'admin.conversation.card.lastMessage': 'Última mensagem {when}',
  'admin.conversation.card.reading.sovereign': 'Leitura direta, registrada no diário de auditoria.',
  'admin.conversation.card.reading.motive': 'Um motivo escrito é pedido antes da leitura, e fica registrado.',
  'admin.conversation.card.agent.users': 'Membros pilotados',
  'admin.conversation.card.agent.scanning': 'O agente está analisando a conversa neste momento.',
  'admin.conversation.card.links.none': 'Nenhum link de compartilhamento',
  'admin.conversation.card.links.hint': 'Esta conversa tem {count} link(s) de compartilhamento. Cada um se consulta e se fecha na seção de links de compartilhamento.',
  'admin.conversation.card.links.open': 'Ver os links de compartilhamento',
  'admin.conversation.members.nickname': 'Apelido: {nickname}',
  'admin.conversation.members.state.banned': 'Banido',
  'admin.conversation.members.state.leftOn': 'Saiu',
  'admin.conversation.members.state.removed': 'Removido',
  'admin.conversation.reading.missing': 'Esta conversa não existe mais: não há nada para ler.',
  'admin.conversation.reading.ephemeral': 'Efêmera · {duration}',
  /* ─── Agent : étapes servies, relance non envoyée, décomptes nommés (audit 2026-10-04) ─── */
  'admin.agentPanel.node.observe': 'lê a conversa',
  'admin.agentPanel.node.starting': 'inicia a análise',
  'admin.agentPanel.relaunch.notSent.conversation': 'Reativação não enviada: o agente está desativado para esta conversa.',
  'admin.agentPanel.relaunch.notSent.global': 'Reativação não enviada: o agente está desativado globalmente.',
  'admin.agentPanel.relaunch.notSent': 'Reativação não enviada.',
  'admin.agentPanel.tracked.hint': 'Toda conversa em que o agente tem uma configuração, papéis ou atividade, configurada ou não.',
  /* ─── Agente completo: visão geral, modelo, conversa, papéis, fila, temas, reinícios (lote Agente completo, 2026-10-05) ─── */
  'admin.agentPanel.stat.words': 'Palavras publicadas',
  'admin.agentPanel.stat.confidence': 'Confiança média',
  'admin.agentPanel.stat.confidenceCaption': 'Segurança do agente sobre os estilos que imita',
  'admin.agentPanel.cards.title': 'O resto do controle, por área',
  'admin.agentPanel.card.activity': 'Atividade recente',
  'admin.agentPanel.card.activity.count': 'Conversas recentes',
  'admin.agentPanel.card.activity.last': 'Última resposta {when} em {name}.',
  'admin.agentPanel.card.activity.none': 'Nenhuma resposta recente.',
  'admin.agentPanel.card.model': 'Modelo e ajustes globais',
  'admin.agentPanel.card.model.hint': 'Provedor, modelo, orçamento, prompt do sistema e limites da plataforma.',
  'admin.agentPanel.card.queue': 'Fila de entrega',
  'admin.agentPanel.card.queue.hint': 'O que o agente está prestes a publicar: revisar, corrigir, cancelar.',
  'admin.agentPanel.card.topics': 'Temas',
  'admin.agentPanel.card.topics.hint': 'Os temas que o agente pode lançar, seus padrões e suas instruções.',
  'admin.agentPanel.card.reset': 'Reinícios',
  'admin.agentPanel.card.reset.hint': 'Apagar o que o agente aprendeu de uma conversa, de um membro ou da plataforma inteira.',

  'admin.agentPanel.activity.search': 'Buscar uma conversa',
  'admin.agentPanel.activity.empty': 'Nenhuma resposta recente do agente',
  'admin.agentPanel.activity.filteredEmpty': 'Nenhuma conversa para esta busca',
  'admin.agentPanel.activity.line': '{messages} mensagem(ns) · {words} palavra(s) · confiança {confidence}',
  'admin.agentPanel.chart.day': 'Análises por dia',
  'admin.agentPanel.chart.week': 'Análises por semana',
  'admin.agentPanel.chart.summary': '{scans} análise(s) desde {since}, custo estimado {cost}.',
  'admin.agentPanel.chart.scans': 'Análises',
  'admin.agentPanel.chart.months': 'Período',
  'admin.agentPanel.chart.monthsValue': '{count} mês(es)',
  'admin.agentPanel.chart.bucket': 'Agrupamento',
  'admin.agentPanel.chart.bucket.day': 'Por dia',
  'admin.agentPanel.chart.bucket.week': 'Por semana',
  'admin.agentPanel.logs.filter.from': 'Desde',
  'admin.agentPanel.logs.filter.to': 'Até',
  'admin.agentPanel.logs.filter.conversation': 'Somente as análises de “{name}”.',
  'admin.agentPanel.logs.filter.conversationClear': 'Ver todas as análises',

  'admin.agentPanel.form.invalid': 'A corrigir: {fields}.',
  'admin.agentPanel.form.unchanged': 'Nenhuma alteração a salvar.',
  'admin.agentPanel.form.failed': 'Recusado pelo gateway: {error}',
  'admin.agentPanel.form.notProvided': 'Não informado',
  'admin.agentPanel.motive': 'Motivo (opcional, no mínimo 10 caracteres)',

  'admin.agentPanel.llm.title': 'Modelo de linguagem',
  'admin.agentPanel.llm.none': 'Nenhum modelo configurado: o serviço do agente mantém sua configuração padrão.',
  'admin.agentPanel.llm.key': 'Chave de API',
  'admin.agentPanel.llm.keySet': 'Salva, nunca reexibida',
  'admin.agentPanel.llm.keyMissing': 'Nenhuma chave salva',
  'admin.agentPanel.llm.keyField': 'Nova chave de API',
  'admin.agentPanel.llm.keyHint': 'Deixe vazio para manter a chave atual. Ela nunca é reexibida.',
  'admin.agentPanel.llm.sovereignOnly': 'Só o nível de criador muda o modelo: ele decide para qual provedor vai o conteúdo das conversas.',
  'admin.agentPanel.llm.save': 'Salvar o modelo',
  'admin.agentPanel.llm.confirm': 'O novo modelo atenderá todas as conversas acompanhadas a partir da próxima análise. A alteração fica no registro de auditoria.',
  'admin.agentPanel.llm.saved': 'Modelo salvo',
  'admin.agentPanel.llm.tokens': 'Tokens por resposta',
  'admin.agentPanel.llm.temperature': 'Temperatura',
  'admin.agentPanel.llm.fallback': 'Modelo reserva',
  'admin.agentPanel.llm.updated': 'Modificado',
  'admin.agentPanel.llm.provider': 'Provedor',
  'admin.agentPanel.llm.model': 'Modelo',
  'admin.agentPanel.llm.dailyBudgetUsd': 'Orçamento diário (USD)',
  'admin.agentPanel.llm.maxCostPerCall': 'Custo máximo por chamada (USD)',
  'admin.agentPanel.global.title': 'Configuração global',
  'admin.agentPanel.global.save': 'Salvar a configuração',
  'admin.agentPanel.global.confirm': 'Estes ajustes valem para a plataforma inteira a partir da próxima análise. A alteração fica no registro de auditoria.',
  'admin.agentPanel.global.saved': 'Configuração salva',
  'admin.agentPanel.global.enabled': 'Agente ativado na plataforma',
  'admin.agentPanel.global.globalScanEnabled': 'Varredura global das conversas',
  'admin.agentPanel.global.defaultProvider': 'Provedor padrão',
  'admin.agentPanel.global.defaultModel': 'Modelo padrão',
  'admin.agentPanel.global.globalDailyBudgetUsd': 'Orçamento diário global (USD)',
  'admin.agentPanel.global.maxConcurrentCalls': 'Chamadas simultâneas no máximo',
  'admin.agentPanel.global.messageFreshnessHours': 'Atualidade das mensagens lidas (horas)',
  'admin.agentPanel.global.weekdayMaxConversations': 'Conversas por dia útil',
  'admin.agentPanel.global.weekendMaxConversations': 'Conversas por dia de fim de semana',
  'admin.agentPanel.global.systemPrompt': 'Prompt do sistema',

  'admin.agentPanel.cfg.enabled': 'Agente ativado nesta conversa',
  'admin.agentPanel.cfg.autoPickupEnabled': 'Escolher sozinho os membros que conduz',
  'admin.agentPanel.cfg.scanIntervalMinutes': 'Intervalo entre duas análises (minutos)',
  'admin.agentPanel.cfg.maxControlledUsers': 'Membros conduzidos no máximo',
  'admin.agentPanel.cfg.minResponsesPerCycle': 'Respostas por ciclo, no mínimo',
  'admin.agentPanel.cfg.maxResponsesPerCycle': 'Respostas por ciclo, no máximo',
  'admin.agentPanel.cfg.reactionsEnabled': 'Reações permitidas',
  'admin.agentPanel.cfg.maxReactionsPerCycle': 'Reações por ciclo, no máximo',
  'admin.agentPanel.cfg.weekdayMaxMessages': 'Mensagens por dia útil',
  'admin.agentPanel.cfg.weekendMaxMessages': 'Mensagens por dia de fim de semana',
  'admin.agentPanel.cfg.minWordsPerMessage': 'Palavras por mensagem, no mínimo',
  'admin.agentPanel.cfg.maxWordsPerMessage': 'Palavras por mensagem, no máximo',
  'admin.agentPanel.cfg.generationTemperature': 'Temperatura de redação',
  'admin.agentPanel.cfg.qualityGateEnabled': 'Controle de qualidade antes de publicar',
  'admin.agentPanel.cfg.webSearchEnabled': 'Busca na web permitida',
  'admin.agentPanel.cfg.agentInstructions': 'Instruções próprias desta conversa',

  'admin.agentPanel.tracked.col.settings': 'Ajustes',
  'admin.agentPanel.conv.open': 'Ajustes',
  'admin.agentPanel.conv.openNamed': 'Abrir os ajustes do agente para {name}',
  'admin.agentPanel.conv.title': 'Agente: {name}',
  'admin.agentPanel.conv.settings': 'Ajustes da conversa',
  'admin.agentPanel.conv.noConfig': 'Sem configuração própria: salvar estes ajustes cria uma.',
  'admin.agentPanel.conv.save': 'Salvar os ajustes',
  'admin.agentPanel.conv.saved': 'Ajustes salvos',
  'admin.agentPanel.conv.summary': 'Resumo mantido pelo agente',
  'admin.agentPanel.conv.summary.none': 'O agente ainda não resumiu esta conversa.',
  'admin.agentPanel.conv.summary.topics': 'Temas em curso',
  'admin.agentPanel.conv.summary.tone': 'Tom geral',
  'admin.agentPanel.conv.summary.health': 'Saúde',
  'admin.agentPanel.conv.summary.healthValue': '{score} de 100',
  'admin.agentPanel.conv.summary.messages': 'Mensagens lidas',
  'admin.agentPanel.conv.summary.updated': 'Atualizado',
  'admin.agentPanel.conv.schedule': 'Programação',
  'admin.agentPanel.conv.schedule.none': 'Sem programação: a conversa não tem configuração própria.',
  'admin.agentPanel.conv.schedule.interval': 'Uma análise a cada',
  'admin.agentPanel.conv.schedule.next': 'Próxima análise',
  'admin.agentPanel.conv.schedule.last': 'Última análise',
  'admin.agentPanel.conv.schedule.never': 'Nunca',
  'admin.agentPanel.conv.schedule.upcoming': 'Análises previstas em 24 h',
  'admin.agentPanel.conv.schedule.budget': 'Mensagens do dia',
  'admin.agentPanel.conv.schedule.budgetValue': '{used} de {max}',
  'admin.agentPanel.conv.schedule.burst': 'Pausa após uma rajada',
  'admin.agentPanel.conv.schedule.burstUntil': 'Até {when}',
  'admin.agentPanel.conv.schedule.burstNone': 'Nenhuma pausa em curso',
  'admin.agentPanel.conv.roles': 'Membros conduzidos e seu papel',
  'admin.agentPanel.conv.roles.empty': 'Nenhum membro conduzido nesta conversa.',
  'admin.agentPanel.conv.roles.observed': 'Aprendido com suas mensagens',
  'admin.agentPanel.conv.roles.archetype': 'Arquétipo: {name}',
  'admin.agentPanel.conv.roles.unknown': 'Origem não reconhecida',
  'admin.agentPanel.conv.roles.confidence': 'Confiança {value}',
  'admin.agentPanel.conv.roles.locked': 'Bloqueado',
  'admin.agentPanel.conv.roles.pick': 'Arquétipo a atribuir a {name}',
  'admin.agentPanel.conv.roles.assign': 'Atribuir o arquétipo',
  'admin.agentPanel.conv.roles.assigned': 'Arquétipo atribuído',
  'admin.agentPanel.conv.roles.unlock': 'Desbloquear',
  'admin.agentPanel.conv.roles.unlockBody': 'O papel de {name} recomeça de uma confiança nula: o agente observa de novo este membro antes de imitá-lo.',
  'admin.agentPanel.conv.roles.unlocked': 'Papel desbloqueado',
  'admin.agentPanel.conv.roles.reset': 'Reiniciar este membro',
  'admin.agentPanel.conv.roles.resetBody': 'Apaga os papéis de {name} em TODAS as conversas, seu perfil global e suas pausas. O agente terá de reaprender tudo sobre este membro.',
  'admin.agentPanel.conv.roles.resetDone': 'Membro reiniciado',
  'admin.agentPanel.conv.messages': 'Mensagens publicadas pelo agente',
  'admin.agentPanel.conv.messages.empty': 'O agente não publicou nada aqui.',
  'admin.agentPanel.conv.messages.newer': 'Mais recentes',
  'admin.agentPanel.conv.messages.older': 'Mais antigas',
  'admin.agentPanel.conv.logs': 'Ver as análises desta conversa',
  'admin.agentPanel.conv.danger': 'Ações destrutivas',
  'admin.agentPanel.conv.delete': 'Excluir a configuração',
  'admin.agentPanel.conv.deleteBody': 'O agente perde os ajustes próprios desta conversa. Os papéis, o resumo e o histórico permanecem.',
  'admin.agentPanel.conv.deleted': 'Configuração excluída',
  'admin.agentPanel.conv.reset': 'Reiniciar a conversa',
  'admin.agentPanel.conv.resetBody': 'Apaga, para esta conversa, a configuração, os papéis dos membros conduzidos, o resumo, a análise e o cache do agente. As mensagens já publicadas permanecem.',
  'admin.agentPanel.conv.resetDone': 'Conversa reiniciada',

  'admin.agentPanel.archetype.curious': 'O curioso',
  'admin.agentPanel.archetype.enthusiast': 'O entusiasta',
  'admin.agentPanel.archetype.skeptic': 'O cético',
  'admin.agentPanel.archetype.pragmatic': 'O pragmático',
  'admin.agentPanel.archetype.social': 'O sociável',
  'admin.agentPanel.archetype.expert': 'O especialista',
  'admin.agentPanel.archetype.moderator': 'O moderador',
  'admin.agentPanel.archetype.gossip': 'A fofoqueira',
  'admin.agentPanel.archetype.chronicler': 'O cronista',
  'admin.agentPanel.archetype.joker': 'O piadista',
  'admin.agentPanel.archetype.diaspora': 'A voz da diáspora',
  'admin.agentPanel.archetype.elder': 'O sábio',
  'admin.agentPanel.archetype.hustler': 'O desenrolado',

  'admin.agentPanel.queue.empty': 'Nada aguardando publicação',
  'admin.agentPanel.queue.emptyHint': 'O que o agente prepara aparece aqui antes de ser publicado.',
  'admin.agentPanel.queue.count': '{count} item(ns) aguardando',
  'admin.agentPanel.queue.note': 'O gateway não reprograma: uma mensagem se corrige ou se cancela.',
  'admin.agentPanel.queue.message': 'Mensagem',
  'admin.agentPanel.queue.reaction': 'Reação {emoji}',
  'admin.agentPanel.queue.at': 'Publicação prevista {when}',
  'admin.agentPanel.queue.conversation': 'Abrir a conversa',
  'admin.agentPanel.queue.in': 'Conversa',
  'admin.agentPanel.queue.as': 'Publicado em nome de',
  'admin.agentPanel.queue.edit': 'Corrigir o texto',
  'admin.agentPanel.queue.editLabel': 'Texto da mensagem',
  'admin.agentPanel.queue.save': 'Salvar o texto',
  'admin.agentPanel.queue.saved': 'Texto corrigido',
  'admin.agentPanel.queue.cancel': 'Cancelar a publicação',
  'admin.agentPanel.queue.cancelBody': 'Este item não será publicado. A ação fica no registro de auditoria.',
  'admin.agentPanel.queue.cancelled': 'Publicação cancelada',

  'admin.agentPanel.topics.empty': 'Nenhum tema no catálogo',
  'admin.agentPanel.topics.emptyHint': 'Um tema orienta o que o agente lança quando uma conversa perde o fôlego.',
  'admin.agentPanel.topics.new': 'Novo tema',
  'admin.agentPanel.topics.active': 'Ativo',
  'admin.agentPanel.topics.inactive': 'Inativo',
  'admin.agentPanel.topics.meta': 'Prioridade {priority} · pausa de {cooldown} · {patterns} padrão(ões)',
  'admin.agentPanel.topics.edit': 'Editar “{label}”',
  'admin.agentPanel.topics.back': 'Voltar aos temas',
  'admin.agentPanel.topics.save': 'Salvar o tema',
  'admin.agentPanel.topics.saved': 'Tema salvo',
  'admin.agentPanel.topics.created': 'Tema criado',
  'admin.agentPanel.topics.field.slug': 'Identificador (minúsculas, algarismos, - e _)',
  'admin.agentPanel.topics.field.label': 'Nome',
  'admin.agentPanel.topics.field.description': 'Descrição',
  'admin.agentPanel.topics.field.keywordPatterns': 'Padrões de detecção, um por linha',
  'admin.agentPanel.topics.field.instructionTemplate': 'Instrução de redação (no mínimo 20 caracteres)',
  'admin.agentPanel.topics.field.searchHintTemplate': 'Pista de busca',
  'admin.agentPanel.topics.field.examples': 'Exemplos, um por linha',
  'admin.agentPanel.topics.field.cooldownMinutes': 'Pausa entre dois usos (minutos)',
  'admin.agentPanel.topics.field.priority': 'Prioridade (0 a 10)',
  'admin.agentPanel.topics.field.isActive': 'Tema ativo',
  'admin.agentPanel.topics.deactivate': 'Desativar',
  'admin.agentPanel.topics.deactivateBody': 'O agente deixa de propor “{label}”. O tema continua no catálogo e pode ser reativado.',
  'admin.agentPanel.topics.deactivated': 'Tema desativado',
  'admin.agentPanel.topics.delete': 'Excluir',
  'admin.agentPanel.topics.deleteBody': '“{label}” e seus ajustes são apagados do catálogo, sem volta.',
  'admin.agentPanel.topics.deleted': 'Tema excluído',
  'admin.agentPanel.topics.test': 'Testar um texto com os padrões',
  'admin.agentPanel.topics.testLabel': 'Texto a testar',
  'admin.agentPanel.topics.testRun': 'Testar',
  'admin.agentPanel.topics.testHit': '{pattern}: {count} ocorrência(s)',
  'admin.agentPanel.topics.testRefused': '{pattern}: não avaliado, {message}',
  'admin.agentPanel.topics.testNone': 'Nenhum padrão reconhece este texto.',

  'admin.agentPanel.reset.conversationHint': 'Uma conversa é reiniciada a partir dos seus ajustes, na lista de conversas acompanhadas.',
  'admin.agentPanel.reset.userHint': 'Um membro é reiniciado a partir dos membros conduzidos de uma conversa.',
  'admin.agentPanel.reset.all': 'Reiniciar tudo',
  'admin.agentPanel.reset.allBody': 'Apaga na plataforma INTEIRA: todas as configurações de conversa, todos os papéis dos membros conduzidos, todos os resumos, toda a análise, todos os perfis globais e todo o cache do agente. As mensagens já publicadas permanecem. A ação fica no registro de auditoria e não pode ser desfeita.',
  'admin.agentPanel.reset.allDone': 'Todo o estado do agente foi apagado.',
  'admin.agentPanel.form.between': 'Entre {min} e {max}',
  'admin.agentPanel.form.atLeast': 'Pelo menos {min}',
  'admin.agentPanel.form.emptyDefault': 'Vazio: o valor padrão do agente',
  'admin.agentPanel.form.idsHint': 'Um identificador de membro (24 caracteres) por linha',
  'admin.agentPanel.form.listHint': 'Um valor por linha',
  'admin.agentPanel.form.listHintMax': 'Um valor por linha, no máximo {max}, com no máximo {length} caracteres',
  'admin.agentPanel.form.unknownOption': '«{value}» (valor não reconhecido)',
  'admin.agentPanel.form.problem.range': 'Fora dos limites: {bounds}.',
  'admin.agentPanel.form.problem.integer': 'É esperado um número inteiro.',
  'admin.agentPanel.form.problem.number': 'É esperado um número.',
  'admin.agentPanel.form.problem.required': 'Este campo é obrigatório.',
  'admin.agentPanel.form.problem.length': 'No máximo {max} caracteres.',
  'admin.agentPanel.form.problem.choice': 'Escolha um valor da lista.',
  'admin.agentPanel.form.problem.count': 'No máximo {max} valores.',
  'admin.agentPanel.form.problem.item': 'Valor recusado: «{value}».',
  'admin.agentPanel.form.problem.orderLow': 'Deve ficar menor ou igual a «{other}».',
  'admin.agentPanel.form.problem.orderHigh': 'Deve ficar maior ou igual a «{other}».',
  'admin.agentPanel.global.section.general': 'Ativação e prompt',
  'admin.agentPanel.global.section.model': 'Modelo padrão e de reserva',
  'admin.agentPanel.global.section.budget': 'Orçamento e carga',
  'admin.agentPanel.global.section.scan': 'Varredura das conversas',
  'admin.agentPanel.global.fallbackProvider': 'Provedor de reserva',
  'admin.agentPanel.global.fallbackModel': 'Modelo de reserva',
  'admin.agentPanel.global.globalScanMinInterval': 'Pausa mínima entre duas conversas (segundos)',
  'admin.agentPanel.global.globalScanMaxInterval': 'Pausa máxima entre duas conversas (segundos)',
  'admin.agentPanel.global.eligibleConversationTypes': 'Tipos de conversa varridos',
  'admin.agentPanel.global.maxConversationsPerCycle': 'Conversas por ciclo de varredura',
  'admin.agentPanel.global.systemPrompt.help': 'As instruções que o agente recebe em todas as conversas, antes das próprias de cada uma.',
  'admin.agentPanel.global.fallbackProvider.help': 'Usado quando o provedor padrão não responde. Vazio: sem reserva.',
  'admin.agentPanel.global.maxConcurrentCalls.help': 'Quantas chamadas ao modelo podem sair ao mesmo tempo, em todas as conversas.',
  'admin.agentPanel.global.globalScanEnabled.help': 'Percorre as conversas uma a uma, com uma pausa aleatória entre duas.',
  'admin.agentPanel.global.eligibleConversationTypes.help': 'Só as conversas destes tipos são varridas pelo agente.',
  'admin.agentPanel.global.messageFreshnessHours.help': 'Uma conversa sem mensagem mais recente que este prazo não é varrida.',
  'admin.agentPanel.global.maxConversationsPerCycle.help': '0: sem limite.',
  'admin.agentPanel.cfg.section.general': 'Ativação e instruções',
  'admin.agentPanel.cfg.section.members': 'Membros controlados',
  'admin.agentPanel.cfg.section.rhythm': 'Ritmo e janelas',
  'admin.agentPanel.cfg.section.budget': 'Orçamento de mensagens',
  'admin.agentPanel.cfg.section.style': 'Estilo e comprimento',
  'admin.agentPanel.cfg.section.triggers': 'Gatilhos e prioridades',
  'admin.agentPanel.cfg.section.topics': 'Temas novos',
  'admin.agentPanel.cfg.agentType': 'Papel do agente',
  'admin.agentPanel.cfg.agentType.personal': 'Pessoal',
  'admin.agentPanel.cfg.agentType.animator': 'Animador',
  'admin.agentPanel.cfg.agentType.support': 'Suporte',
  'admin.agentPanel.cfg.agentType.faq': 'Perguntas frequentes',
  'admin.agentPanel.cfg.inactivityThresholdHours': 'Silêncio antes de poder ser controlado (horas)',
  'admin.agentPanel.cfg.minHistoricalMessages': 'Mensagens de histórico exigidas',
  'admin.agentPanel.cfg.weekdayMaxUsers': 'Membros interpretados por dia de semana',
  'admin.agentPanel.cfg.weekendMaxUsers': 'Membros interpretados por dia de fim de semana',
  'admin.agentPanel.cfg.manualUserIds': 'Membros controlados manualmente',
  'admin.agentPanel.cfg.excludedUserIds': 'Membros nunca controlados',
  'admin.agentPanel.cfg.excludedRoles': 'Papéis de conta nunca controlados',
  'admin.agentPanel.cfg.excludedRoles.AGENT': 'Conta de agente',
  'admin.agentPanel.cfg.spreadOverDayEnabled': 'Distribuir as mensagens ao longo do dia',
  'admin.agentPanel.cfg.minDelayMinutes': 'Atraso mínimo antes de publicar (minutos)',
  'admin.agentPanel.cfg.maxDelayMinutes': 'Atraso máximo antes de publicar (minutos)',
  'admin.agentPanel.cfg.burstEnabled': 'Rajadas de mensagens',
  'admin.agentPanel.cfg.burstSize': 'Mensagens por rajada',
  'admin.agentPanel.cfg.burstIntervalMinutes': 'Intervalo dentro de uma rajada (minutos)',
  'admin.agentPanel.cfg.quietIntervalMinutes': 'Pausa após uma rajada (minutos)',
  'admin.agentPanel.cfg.maxMessagesPerUserPer10Min': 'Mensagens por membro em 10 minutos, no máximo',
  'admin.agentPanel.cfg.qualityGateMinScore': 'Nota mínima do controle de qualidade',
  'admin.agentPanel.cfg.contextWindowSize': 'Mensagens relidas antes de redigir',
  'admin.agentPanel.cfg.useFullHistory': 'Reler todo o histórico',
  'admin.agentPanel.cfg.triggerOnTimeout': 'Responder após um silêncio',
  'admin.agentPanel.cfg.timeoutSeconds': 'Duração do silêncio (segundos)',
  'admin.agentPanel.cfg.triggerOnUserMessage': 'Responder às mensagens de certos membros',
  'admin.agentPanel.cfg.triggerFromUserIds': 'Membros que disparam uma resposta',
  'admin.agentPanel.cfg.triggerOnReplyTo': 'Responder quando uma mensagem responde a outra',
  'admin.agentPanel.cfg.prioritizeTaggedUsers': 'Fazer falar primeiro os membros mencionados',
  'admin.agentPanel.cfg.prioritizeRepliedUsers': 'Fazer falar primeiro os membros que receberam resposta',
  'admin.agentPanel.cfg.reactionBoostFactor': 'Peso das reações recebidas',
  'admin.agentPanel.cfg.freshTopicProbability': 'Probabilidade de trazer um tema novo',
  'admin.agentPanel.cfg.freshTopicCategoryHints': 'Pistas de temas novos',
  'admin.agentPanel.cfg.agentType.help': 'O comportamento geral que o agente adota nesta conversa.',
  'admin.agentPanel.cfg.agentInstructions.help': 'Somam-se ao prompt do sistema só para esta conversa. Vazio: sem instruções próprias.',
  'admin.agentPanel.cfg.webSearchEnabled.help': 'O agente pode pesquisar na web para alimentar as mensagens e os temas novos.',
  'admin.agentPanel.cfg.autoPickupEnabled.help': 'O agente escolhe sozinho, entre os membros calados, quem vai fazer falar.',
  'admin.agentPanel.cfg.inactivityThresholdHours.help': 'Um membro só é controlado após este tempo sem escrever.',
  'admin.agentPanel.cfg.minHistoricalMessages.help': 'Quantas mensagens um membro deve ter escrito para o agente imitar o seu estilo.',
  'admin.agentPanel.cfg.weekdayMaxUsers.help': 'Quantos membros diferentes o agente pode fazer falar no dia.',
  'admin.agentPanel.cfg.manualUserIds.help': 'Sempre controlados, seja qual for o silêncio.',
  'admin.agentPanel.cfg.excludedUserIds.help': 'O agente nunca escreverá em nome destes membros.',
  'admin.agentPanel.cfg.excludedRoles.help': 'As contas com algum destes papéis nunca são controladas.',
  'admin.agentPanel.cfg.spreadOverDayEnabled.help': 'Distribui o orçamento do dia com regularidade, em vez de gastá-lo de uma vez.',
  'admin.agentPanel.cfg.minDelayMinutes.help': 'O tempo aleatório entre a redação de uma mensagem e a sua publicação.',
  'admin.agentPanel.cfg.burstEnabled.help': 'Publica várias mensagens próximas e depois faz uma pausa — como uma conversa real.',
  'admin.agentPanel.cfg.maxMessagesPerUserPer10Min.help': 'Impede que um mesmo membro escreva demais seguido.',
  'admin.agentPanel.cfg.minResponsesPerCycle.help': 'Um ciclo é uma passagem do agente pela conversa.',
  'admin.agentPanel.cfg.generationTemperature.help': 'Baixo: mensagens previsíveis. Alto: mensagens mais variadas, às vezes mais surpreendentes.',
  'admin.agentPanel.cfg.qualityGateMinScore.help': 'De 0 a 1: uma mensagem com nota inferior é descartada antes da publicação.',
  'admin.agentPanel.cfg.contextWindowSize.help': 'Mais mensagens relidas: respostas mais bem situadas, porém mais caras.',
  'admin.agentPanel.cfg.useFullHistory.help': 'Além da janela de mensagens relidas; mais caro em tokens.',
  'admin.agentPanel.cfg.triggerOnTimeout.help': 'Quando ninguém escreve durante o tempo escolhido, o agente reanima a conversa.',
  'admin.agentPanel.cfg.triggerFromUserIds.help': 'Uma mensagem de um deles dispara uma resposta imediatamente.',
  'admin.agentPanel.cfg.reactionBoostFactor.help': 'Os membros cujas mensagens recebem reações falam este número de vezes mais.',
  'admin.agentPanel.cfg.freshTopicProbability.help': 'De 0 a 1, a cada passagem: com 0,2, cerca de uma em cada cinco traz um tema atual. Exige a pesquisa na web.',
  'admin.agentPanel.cfg.freshTopicCategoryHints.help': 'Temas que orientam a busca de temas novos («culinária», «futebol»…).',
} as const satisfies AdminCatalogFragment<typeof fr>;

export default f;
