import type { AdminCatalogFragment } from './fragment';
import type fr from './conversations-agent-fr';

/**
 * THE “conversations-agent” FRAGMENT OF THE ADMINISTRATION CATALOG (#8876) —
 * Spanish text for the conversation list and sheet, the sovereign reading,
 * and the agent control. Same keys as the French source, which stays the
 * reference for meaning; the `admin.enum.*` labels it relies on live in the kit.
 */
const f = {
  'admin.conversation.subtitle':
    'Todas las conversaciones de la plataforma: quién las compone, en qué punto están y a qué comunidad pertenecen. El contenido de los mensajes solo se lee con un motivo escrito, desde la ficha.',
  'admin.conversation.search': 'Buscar por título o identificador',
  'admin.conversation.list.caption': 'Lista de conversaciones',
  'admin.conversation.list.count': '{count} conversación(es)',
  'admin.conversation.list.empty': 'Ninguna conversación',
  'admin.conversation.list.emptyHint': 'Las conversaciones creadas en la plataforma aparecen aquí.',
  'admin.conversation.list.filteredEmpty': 'Ninguna conversación con estos filtros',
  'admin.conversation.list.onCommunity':
    'Conversaciones de una sola comunidad: quite el filtro para volver a ver todas las conversaciones.',
  'admin.conversation.list.onCommunityNamed':
    'Conversaciones de la comunidad «{name}»: quite el filtro para volver a ver todas las conversaciones.',
  'admin.conversation.list.onCommunityReset': 'Ver todas las conversaciones',

  'admin.conversation.filter.type': 'Tipo',
  'admin.conversation.filter.state': 'Estado',
  'admin.conversation.filter.state.active': 'Activas',
  'admin.conversation.filter.state.archived': 'Archivadas',
  'admin.conversation.filter.period': 'Creadas en los últimos',
  'admin.conversation.filter.period.all': 'Todo el período',

  'admin.conversation.col.conversation': 'Conversación',
  'admin.conversation.col.type': 'Tipo',
  'admin.conversation.col.community': 'Comunidad',
  'admin.conversation.col.members': 'Miembros',
  'admin.conversation.col.state': 'Estado',
  'admin.conversation.col.created': 'Creación',
  'admin.conversation.col.lastMessage': 'Último mensaje',

  'admin.conversation.fiche.loading': 'Cargando la conversación',
  'admin.conversation.fiche.notFound': 'Esta conversación ya no existe',
  'admin.conversation.fiche.notFoundHint': 'Se eliminó, o la dirección es incorrecta.',
  'admin.conversation.fiche.back': 'Volver a las conversaciones',
  'admin.conversation.fiche.configure': 'Configurar',

  'admin.conversation.stat.members': 'Miembros activos',
  'admin.conversation.stat.messages': 'Mensajes',
  'admin.conversation.stat.shareLinks': 'Enlaces para compartir',
  'admin.conversation.stat.agent': 'Agente',
  'admin.conversation.stat.agent.on': 'Activo',
  'admin.conversation.stat.agent.off': 'Inactivo',
  'admin.conversation.badge.agent': 'Agente activo',

  'admin.conversation.meta.type': 'Tipo',
  'admin.conversation.meta.identifier': 'Identificador público',
  'admin.conversation.meta.identifierExplain': 'Su dirección legible, distinta del identificador técnico.',
  'admin.conversation.meta.description': 'Descripción',
  'admin.conversation.meta.community': 'Comunidad',
  'admin.conversation.meta.state': 'Estado',
  'admin.conversation.meta.archivedExplain': 'Archivada: nadie puede escribir en ella hasta que se restaure.',
  'admin.conversation.meta.closedOn': 'Cerrada el',
  'admin.conversation.meta.closedBy': 'Cerrada por',
  'admin.conversation.meta.writeRole': 'Quién puede escribir',
  'admin.conversation.meta.writeRoleExplain': 'El rango mínimo exigido para enviar un mensaje.',
  'admin.conversation.meta.announcement': 'Canal de anuncios',
  'admin.conversation.meta.announcement.yes': 'Sí: solo los administradores escriben en él',
  'admin.conversation.meta.announcement.no': 'No: conversación ordinaria',
  'admin.conversation.meta.slowMode': 'Modo lento',
  'admin.conversation.meta.slowMode.off': 'Desactivado',
  'admin.conversation.meta.slowMode.on': 'Un mensaje cada {duration} por miembro',
  'admin.conversation.meta.slowModeExplain': 'Los moderadores y los rangos superiores están exentos.',
  'admin.conversation.meta.autoTranslate': 'Traducción automática',
  'admin.conversation.meta.autoTranslate.yes': 'Activada: cada lector ve los mensajes en su idioma',
  'admin.conversation.meta.autoTranslate.no': 'Desactivada: los mensajes se quedan en su idioma original',
  'admin.conversation.meta.autoTranslate.unknown': 'No especificada',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inactiva: el servidor no puede leer los mensajes cifrados de extremo a extremo',
  'admin.conversation.meta.encryption': 'Cifrado',
  'admin.conversation.meta.created': 'Creada',
  'admin.conversation.meta.updated': 'Última modificación',
  'admin.conversation.meta.lastMessage': 'Último mensaje',
  'admin.conversation.meta.noMessage': 'Aún no hay mensajes',

  'admin.conversation.members.title': 'Miembros',
  'admin.conversation.members.caption': 'Participantes de la conversación',
  'admin.conversation.members.count': '{count} participante(s)',
  'admin.conversation.members.empty': 'Ningún participante',
  'admin.conversation.members.col.member': 'Miembro',
  'admin.conversation.members.col.role': 'Rol',
  'admin.conversation.members.col.presence': 'Presencia',
  'admin.conversation.members.col.state': 'Estado',
  'admin.conversation.members.col.joined': 'Llegada',
  'admin.conversation.members.col.actions': 'Acciones',
  'admin.conversation.members.state.active': 'Activo',
  'admin.conversation.members.state.left': 'Salió de la conversación',
  'admin.conversation.members.roleOf': 'Rol de {name}',
  'admin.conversation.members.remove': 'Quitar',
  'admin.conversation.members.removeOf': 'Quitar a {name} de la conversación',
  'admin.conversation.members.creatorProtected': 'Protegido: el creador no puede ser degradado ni quitado',
  'admin.conversation.members.creatorRefused': 'El creador de la conversación está protegido: no puede ser degradado ni quitado.',
  'admin.conversation.members.motive': 'Motivo (mínimo 10 caracteres)',
  'admin.conversation.members.role.confirmTitle': 'Cambiar el rol',
  'admin.conversation.members.role.confirmBody':
    '{name} pasará de «{from}» a «{to}». El cambio queda registrado en el registro de auditoría con su motivo.',
  'admin.conversation.members.role.confirm': 'Cambiar el rol',
  'admin.conversation.members.role.done': 'Rol modificado',
  'admin.conversation.members.remove.confirmTitle': 'Quitar de la conversación',
  'admin.conversation.members.remove.confirmBody':
    '{name} será quitado de la conversación y ya no tendrá acceso a ella. La retirada queda registrada en el registro de auditoría con su motivo.',
  'admin.conversation.members.remove.confirm': 'Quitar',
  'admin.conversation.members.remove.done': 'Miembro quitado',

  'admin.conversation.reading.title': 'Leer la conversación',
  'admin.conversation.reading.hint':
    'El contenido de los mensajes solo se lee con un motivo escrito, registrado con su nombre en el registro de auditoría. El hilo se muestra en sus idiomas de lectura, como en la aplicación.',

  'admin.agentPanel.subtitle':
    'Las conversaciones en las que interviene el agente: siga su actividad, vuelva a lanzarlo o detenga un escaneo en curso.',
  'admin.agentPanel.stat.tracked': 'Conversaciones controladas',
  'admin.agentPanel.stat.trackedCaption': 'de {total} seguidas',
  'admin.agentPanel.stat.users': 'Miembros controlados',
  'admin.agentPanel.stat.messages': 'Mensajes publicados',

  'admin.agentPanel.tracked.caption': 'Conversaciones seguidas por el agente',
  'admin.agentPanel.tracked.search': 'Buscar una conversación',
  'admin.agentPanel.tracked.count': '{count} conversación(es)',
  'admin.agentPanel.tracked.empty': 'Ninguna conversación seguida',
  'admin.agentPanel.tracked.emptyHint': 'Cuando el agente se configura para una conversación, aparece aquí.',
  'admin.agentPanel.tracked.filteredEmpty': 'Ninguna conversación para esta búsqueda',
  'admin.agentPanel.tracked.col.conversation': 'Conversación',
  'admin.agentPanel.tracked.col.state': 'Estado',
  'admin.agentPanel.tracked.col.users': 'Miembros controlados',
  'admin.agentPanel.tracked.col.messages': 'Mensajes publicados',
  'admin.agentPanel.tracked.col.lastResponse': 'Última respuesta',
  'admin.agentPanel.tracked.col.control': 'Control',
  'admin.agentPanel.state.on': 'Activado',
  'admin.agentPanel.state.off': 'Desactivado',
  'admin.agentPanel.state.scanning': 'Escaneo en curso',
  'admin.agentPanel.lastResponse.never': 'Ninguna respuesta',

  'admin.agentPanel.logs.caption': 'Registro de escaneos del agente',
  'admin.agentPanel.logs.count': '{count} escaneo(s)',
  'admin.agentPanel.logs.empty': 'Ningún escaneo registrado',
  'admin.agentPanel.logs.emptyHint': 'Cada paso del agente por una conversación deja una línea aquí.',
  'admin.agentPanel.logs.filteredEmpty': 'Ningún escaneo con estos filtros',
  'admin.agentPanel.logs.filter.outcome': 'Resultado',
  'admin.agentPanel.logs.filter.trigger': 'Activador',
  'admin.agentPanel.logs.col.conversation': 'Conversación',
  'admin.agentPanel.logs.col.trigger': 'Activador',
  'admin.agentPanel.logs.col.outcome': 'Resultado',
  'admin.agentPanel.logs.col.messages': 'Mensajes publicados',
  'admin.agentPanel.logs.col.duration': 'Duración',
  'admin.agentPanel.logs.col.started': 'Inicio',
  'admin.agentPanel.logs.open': 'Abrir el detalle del escaneo de {name}',

  'admin.agentPanel.outcome.messages_sent': 'Mensaje publicado',
  'admin.agentPanel.outcome.messages_sent.explain': 'El agente escribió en la conversación.',
  'admin.agentPanel.outcome.reactions_only': 'Solo reacciones',
  'admin.agentPanel.outcome.reactions_only.explain': 'El agente reaccionó a mensajes sin publicar ninguno.',
  'admin.agentPanel.outcome.skipped': 'Ninguna acción',
  'admin.agentPanel.outcome.skipped.explain': 'El ciclo terminó sin publicar nada.',
  'admin.agentPanel.outcome.error': 'Error',
  'admin.agentPanel.outcome.error.explain': 'El ciclo falló antes de terminar.',
  'admin.agentPanel.trigger.auto': 'Automático',
  'admin.agentPanel.trigger.auto.explain': 'Iniciado por el planificador del agente.',
  'admin.agentPanel.trigger.manual': 'Manual',
  'admin.agentPanel.trigger.manual.explain': 'Iniciado desde la administración.',
  'admin.agentPanel.node.observer': 'lee la conversación',
  'admin.agentPanel.node.strategist': 'decide qué decir',
  'admin.agentPanel.node.generator': 'redacta un mensaje',
  'admin.agentPanel.node.qualityGate': 'controla la calidad',
  'admin.agentPanel.node.unknown': 'trabaja',

  'admin.agentPanel.detail.title': 'Detalle del escaneo',
  'admin.agentPanel.detail.conversation': 'Conversación',
  'admin.agentPanel.detail.started': 'Inicio',
  'admin.agentPanel.detail.reactions': 'Reacciones enviadas',
  'admin.agentPanel.detail.rejected': 'Mensajes descartados',
  'admin.agentPanel.detail.rejectedExplain': 'Redactados por el agente y rechazados por su control de calidad.',
  'admin.agentPanel.detail.users': 'Miembros interpretados',
  'admin.agentPanel.detail.tokens': 'Tokens (entrada / salida)',
  'admin.agentPanel.detail.cost': 'Coste estimado',

  'admin.agentPanel.conversation.title': 'Agente en esta conversación',
  'admin.agentPanel.conversation.usersNone': 'Ningún miembro controlado por ahora',
  'admin.agentPanel.conversation.messages': 'Mensajes publicados',
  'admin.agentPanel.conversation.lastResponse': 'Última respuesta',
} as const satisfies AdminCatalogFragment<typeof fr>;

export default f;
