import type { AdminCatalogFragment } from './fragment';
import type fr from './conversations-agent-fr';

/**
 * THE “conversations-agent” FRAGMENT OF THE ADMINISTRATION CATALOG (#8876) — the
 * conversation list and sheet, the sovereign reading, and the agent control.
 * Same keys as the French source; the other languages start from this text until
 * their translation pass.
 */
const f = {
  'admin.conversation.subtitle':
    'Every conversation on the platform: who is in it, where it stands, which community it belongs to. Message content can only be read with a written reason, from the sheet.',
  'admin.conversation.search': 'Search by title or identifier',
  'admin.conversation.list.caption': 'List of conversations',
  'admin.conversation.list.count': '{count} conversation(s)',
  'admin.conversation.list.empty': 'No conversation',
  'admin.conversation.list.emptyHint': 'Conversations created on the platform appear here.',
  'admin.conversation.list.filteredEmpty': 'No conversation matches these filters',
  'admin.conversation.list.onCommunity': 'Conversations of a single community: remove the filter to see every conversation again.',
  'admin.conversation.list.onCommunityNamed': 'Conversations of the “{name}” community: remove the filter to see every conversation again.',
  'admin.conversation.list.onCommunityReset': 'See all conversations',

  'admin.conversation.filter.type': 'Type',
  'admin.conversation.filter.state': 'State',
  'admin.conversation.filter.state.active': 'Active',
  'admin.conversation.filter.state.archived': 'Archived',
  'admin.conversation.filter.period': 'Created within',
  'admin.conversation.filter.period.all': 'Any time',

  'admin.conversation.col.conversation': 'Conversation',
  'admin.conversation.col.type': 'Type',
  'admin.conversation.col.community': 'Community',
  'admin.conversation.col.members': 'Members',
  'admin.conversation.col.state': 'State',
  'admin.conversation.col.created': 'Created',
  'admin.conversation.col.lastMessage': 'Last message',

  'admin.conversation.fiche.loading': 'Loading the conversation',
  'admin.conversation.fiche.notFound': 'This conversation no longer exists',
  'admin.conversation.fiche.notFoundHint': 'It was deleted, or the address is wrong.',
  'admin.conversation.fiche.back': 'Back to conversations',
  'admin.conversation.fiche.configure': 'Configure',

  'admin.conversation.stat.members': 'Active members',
  'admin.conversation.stat.messages': 'Messages',
  'admin.conversation.stat.shareLinks': 'Share links',
  'admin.conversation.stat.agent': 'Agent',
  'admin.conversation.stat.agent.on': 'On',
  'admin.conversation.stat.agent.off': 'Off',

  'admin.conversation.meta.type': 'Type',
  'admin.conversation.meta.identifier': 'Public identifier',
  'admin.conversation.meta.identifierExplain': 'Its readable address, distinct from the technical identifier.',
  'admin.conversation.meta.description': 'Description',
  'admin.conversation.meta.community': 'Community',
  'admin.conversation.meta.state': 'State',
  'admin.conversation.meta.archivedExplain': 'Archived: nobody can write in it until it is restored.',
  'admin.conversation.meta.closedOn': 'Closed on',
  'admin.conversation.meta.closedBy': 'Closed by',
  'admin.conversation.meta.writeRole': 'Who can write',
  'admin.conversation.meta.writeRoleExplain': 'The minimum rank required to send a message.',
  'admin.conversation.meta.announcement': 'Announcement channel',
  'admin.conversation.meta.announcement.yes': 'Yes: only administrators write in it',
  'admin.conversation.meta.announcement.no': 'No: ordinary conversation',
  'admin.conversation.meta.slowMode': 'Slow mode',
  'admin.conversation.meta.slowMode.off': 'Off',
  'admin.conversation.meta.slowMode.on': 'One message every {duration} per member',
  'admin.conversation.meta.slowModeExplain': 'Moderators and the ranks above them are exempt.',
  'admin.conversation.meta.autoTranslate': 'Automatic translation',
  'admin.conversation.meta.autoTranslate.yes': 'On: each reader sees messages in their own language',
  'admin.conversation.meta.autoTranslate.no': 'Off: messages stay in their original language',
  'admin.conversation.meta.autoTranslate.unknown': 'Not specified',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inactive: the server cannot read end-to-end encrypted messages',
  'admin.conversation.meta.encryption': 'Encryption',
  'admin.conversation.meta.created': 'Created',
  'admin.conversation.meta.updated': 'Last modified',
  'admin.conversation.meta.lastMessage': 'Last message',
  'admin.conversation.meta.noMessage': 'No message yet',

  'admin.conversation.members.title': 'Members',
  'admin.conversation.members.caption': 'Participants of the conversation',
  'admin.conversation.members.count': '{count} participant(s)',
  'admin.conversation.members.empty': 'No participant',
  'admin.conversation.members.col.member': 'Member',
  'admin.conversation.members.col.role': 'Role',
  'admin.conversation.members.col.presence': 'Presence',
  'admin.conversation.members.col.state': 'State',
  'admin.conversation.members.col.joined': 'Joined',
  'admin.conversation.members.col.actions': 'Actions',
  'admin.conversation.members.state.active': 'Active',
  'admin.conversation.members.state.left': 'Left the conversation',
  'admin.conversation.members.roleOf': 'Role of {name}',
  'admin.conversation.members.remove': 'Remove',
  'admin.conversation.members.removeOf': 'Remove {name} from the conversation',
  'admin.conversation.members.creatorProtected': 'Protected: the creator can be neither demoted nor removed',
  'admin.conversation.members.creatorRefused': 'The conversation creator is protected: they can be neither demoted nor removed.',
  'admin.conversation.members.motive': 'Reason (10 characters minimum)',
  'admin.conversation.members.role.confirmTitle': 'Change the role',
  'admin.conversation.members.role.confirmBody': '{name} will go from “{from}” to “{to}”. The change is recorded in the audit log with your reason.',
  'admin.conversation.members.role.confirm': 'Change the role',
  'admin.conversation.members.role.done': 'Role changed',
  'admin.conversation.members.remove.confirmTitle': 'Remove from the conversation',
  'admin.conversation.members.remove.confirmBody': '{name} will be removed from the conversation and will no longer have access to it. The removal is recorded in the audit log with your reason.',
  'admin.conversation.members.remove.confirm': 'Remove',
  'admin.conversation.members.remove.done': 'Member removed',

  'admin.conversation.reading.title': 'Read the conversation',
  'admin.conversation.reading.hint':
    'Message content can only be read with a written reason, recorded with your name in the audit log. The thread is shown in your reading languages, as in the app.',

  'admin.agentPanel.subtitle': 'The conversations where the agent takes part: follow its activity, relaunch it or stop a running scan.',
  'admin.agentPanel.stat.tracked': 'Conversations under control',
  'admin.agentPanel.stat.trackedCaption': 'out of {total} tracked',
  'admin.agentPanel.stat.users': 'Controlled members',
  'admin.agentPanel.stat.messages': 'Messages published',

  'admin.agentPanel.tracked.caption': 'Conversations tracked by the agent',
  'admin.agentPanel.tracked.search': 'Search a conversation',
  'admin.agentPanel.tracked.count': '{count} conversation(s)',
  'admin.agentPanel.tracked.empty': 'No tracked conversation',
  'admin.agentPanel.tracked.emptyHint': 'When the agent is set up for a conversation, it appears here.',
  'admin.agentPanel.tracked.filteredEmpty': 'No conversation for this search',
  'admin.agentPanel.tracked.col.conversation': 'Conversation',
  'admin.agentPanel.tracked.col.state': 'State',
  'admin.agentPanel.tracked.col.users': 'Controlled members',
  'admin.agentPanel.tracked.col.messages': 'Messages published',
  'admin.agentPanel.tracked.col.lastResponse': 'Last response',
  'admin.agentPanel.tracked.col.control': 'Control',
  'admin.agentPanel.state.on': 'On',
  'admin.agentPanel.state.off': 'Off',
  'admin.agentPanel.state.scanning': 'Scan running',
  'admin.agentPanel.lastResponse.never': 'No response yet',

  'admin.agentPanel.logs.caption': 'Agent scan log',
  'admin.agentPanel.logs.count': '{count} scan(s)',
  'admin.agentPanel.logs.empty': 'No scan recorded',
  'admin.agentPanel.logs.emptyHint': 'Every pass of the agent over a conversation leaves a line here.',
  'admin.agentPanel.logs.filteredEmpty': 'No scan for these filters',
  'admin.agentPanel.logs.filter.outcome': 'Outcome',
  'admin.agentPanel.logs.filter.trigger': 'Trigger',
  'admin.agentPanel.logs.col.conversation': 'Conversation',
  'admin.agentPanel.logs.col.trigger': 'Trigger',
  'admin.agentPanel.logs.col.outcome': 'Outcome',
  'admin.agentPanel.logs.col.messages': 'Messages published',
  'admin.agentPanel.logs.col.duration': 'Duration',
  'admin.agentPanel.logs.col.started': 'Started',
  'admin.agentPanel.logs.open': 'Open the scan detail of {name}',

  'admin.agentPanel.outcome.messages_sent': 'Message published',
  'admin.agentPanel.outcome.messages_sent.explain': 'The agent wrote in the conversation.',
  'admin.agentPanel.outcome.reactions_only': 'Reactions only',
  'admin.agentPanel.outcome.reactions_only.explain': 'The agent reacted to messages without publishing any.',
  'admin.agentPanel.outcome.skipped': 'No action',
  'admin.agentPanel.outcome.skipped.explain': 'The cycle ended without publishing anything.',
  'admin.agentPanel.outcome.error': 'Error',
  'admin.agentPanel.outcome.error.explain': 'The cycle failed before it finished.',
  'admin.agentPanel.trigger.auto': 'Automatic',
  'admin.agentPanel.trigger.auto.explain': 'Started by the agent scheduler.',
  'admin.agentPanel.trigger.manual': 'Manual',
  'admin.agentPanel.trigger.manual.explain': 'Started from the administration.',
  'admin.agentPanel.node.observer': 'is reading the conversation',
  'admin.agentPanel.node.strategist': 'is choosing what to say',
  'admin.agentPanel.node.generator': 'is writing a message',
  'admin.agentPanel.node.qualityGate': 'is checking the quality',
  'admin.agentPanel.node.unknown': 'is working',

  'admin.agentPanel.detail.title': 'Scan detail',
  'admin.agentPanel.detail.conversation': 'Conversation',
  'admin.agentPanel.detail.started': 'Started',
  'admin.agentPanel.detail.reactions': 'Reactions sent',
  'admin.agentPanel.detail.rejected': 'Messages set aside',
  'admin.agentPanel.detail.rejectedExplain': 'Written by the agent then refused by its quality check.',
  'admin.agentPanel.detail.users': 'Members played',
  'admin.agentPanel.detail.tokens': 'Tokens (input / output)',
  'admin.agentPanel.detail.cost': 'Estimated cost',

  'admin.agentPanel.conversation.title': 'Agent in this conversation',
  'admin.agentPanel.conversation.usersNone': 'No controlled member yet',
  'admin.agentPanel.conversation.messages': 'Messages published',
  'admin.agentPanel.conversation.lastResponse': 'Last response',
} as const satisfies AdminCatalogFragment<typeof fr>;

export default f;
