import type { AdminCatalogFragment } from './fragment';
import type fr from './conversations-agent-fr';

/**
 * THE “conversations-agent” FRAGMENT OF THE ADMINISTRATION CATALOG (#8876) —
 * German text for the conversation list and sheet, the sovereign reading,
 * and the agent control. Same keys as the French source, which stays the
 * reference for meaning; the `admin.enum.*` labels it relies on live in the kit.
 */
const f = {
  'admin.conversation.subtitle':
    'Alle Unterhaltungen der Plattform: wer daran beteiligt ist, wie weit sie sind und zu welcher Community sie gehören. Der Inhalt der Nachrichten ist nur mit schriftlicher Begründung lesbar, über die Detailseite.',
  'admin.conversation.search': 'Nach Titel oder Kennung suchen',
  'admin.conversation.list.caption': 'Liste der Unterhaltungen',
  'admin.conversation.list.count': '{count} Unterhaltung(en)',
  'admin.conversation.list.empty': 'Keine Unterhaltung',
  'admin.conversation.list.emptyHint': 'Auf der Plattform erstellte Unterhaltungen erscheinen hier.',
  'admin.conversation.list.filteredEmpty': 'Keine Unterhaltung für diese Filter',
  'admin.conversation.list.onCommunity':
    'Unterhaltungen einer einzelnen Community: Entfernen Sie den Filter, um wieder alle Unterhaltungen zu sehen.',
  'admin.conversation.list.onCommunityNamed':
    'Unterhaltungen der Community „{name}“: Entfernen Sie den Filter, um wieder alle Unterhaltungen zu sehen.',
  'admin.conversation.list.onCommunityReset': 'Alle Unterhaltungen anzeigen',

  'admin.conversation.filter.type': 'Typ',
  'admin.conversation.filter.state': 'Status',
  'admin.conversation.filter.state.active': 'Aktiv',
  'admin.conversation.filter.state.archived': 'Archiviert',
  'admin.conversation.filter.period': 'Erstellt in den letzten',
  'admin.conversation.filter.period.all': 'Gesamter Zeitraum',

  'admin.conversation.col.conversation': 'Unterhaltung',
  'admin.conversation.col.type': 'Typ',
  'admin.conversation.col.community': 'Community',
  'admin.conversation.col.members': 'Mitglieder',
  'admin.conversation.col.state': 'Status',
  'admin.conversation.col.created': 'Erstellt',
  'admin.conversation.col.lastMessage': 'Letzte Nachricht',

  'admin.conversation.fiche.loading': 'Unterhaltung wird geladen',
  'admin.conversation.fiche.notFound': 'Diese Unterhaltung existiert nicht mehr',
  'admin.conversation.fiche.notFoundHint': 'Sie wurde gelöscht, oder die Adresse ist falsch.',
  'admin.conversation.fiche.back': 'Zurück zu den Unterhaltungen',
  'admin.conversation.fiche.configure': 'Konfigurieren',

  'admin.conversation.stat.members': 'Aktive Mitglieder',
  'admin.conversation.stat.messages': 'Nachrichten',
  'admin.conversation.stat.shareLinks': 'Freigabe-Links',
  'admin.conversation.stat.agent': 'Agent',
  'admin.conversation.stat.agent.on': 'Aktiv',
  'admin.conversation.stat.agent.off': 'Inaktiv',
  'admin.conversation.badge.agent': 'Agent aktiv',

  'admin.conversation.meta.type': 'Typ',
  'admin.conversation.meta.identifier': 'Öffentliche Kennung',
  'admin.conversation.meta.identifierExplain': 'Ihre lesbare Adresse, getrennt von der technischen Kennung.',
  'admin.conversation.meta.description': 'Beschreibung',
  'admin.conversation.meta.community': 'Community',
  'admin.conversation.meta.state': 'Status',
  'admin.conversation.meta.archivedExplain': 'Archiviert: Niemand kann darin schreiben, bis sie wiederhergestellt wird.',
  'admin.conversation.meta.closedOn': 'Geschlossen am',
  'admin.conversation.meta.closedBy': 'Geschlossen von',
  'admin.conversation.meta.writeRole': 'Wer schreiben darf',
  'admin.conversation.meta.writeRoleExplain': 'Der Mindestrang, der zum Senden einer Nachricht nötig ist.',
  'admin.conversation.meta.announcement': 'Ankündigungskanal',
  'admin.conversation.meta.announcement.yes': 'Ja: Nur Administratoren schreiben darin',
  'admin.conversation.meta.announcement.no': 'Nein: gewöhnliche Unterhaltung',
  'admin.conversation.meta.slowMode': 'Langsamer Modus',
  'admin.conversation.meta.slowMode.off': 'Deaktiviert',
  'admin.conversation.meta.slowMode.on': 'Eine Nachricht alle {duration} pro Mitglied',
  'admin.conversation.meta.slowModeExplain': 'Moderatoren und höhere Ränge sind davon ausgenommen.',
  'admin.conversation.meta.autoTranslate': 'Automatische Übersetzung',
  'admin.conversation.meta.autoTranslate.yes': 'Aktiviert: Jede Leserin und jeder Leser sieht die Nachrichten in der eigenen Sprache',
  'admin.conversation.meta.autoTranslate.no': 'Deaktiviert: Die Nachrichten bleiben in ihrer Originalsprache',
  'admin.conversation.meta.autoTranslate.unknown': 'Nicht angegeben',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inaktiv: Der Server kann Ende-zu-Ende-verschlüsselte Nachrichten nicht lesen',
  'admin.conversation.meta.encryption': 'Verschlüsselung',
  'admin.conversation.meta.created': 'Erstellt',
  'admin.conversation.meta.updated': 'Zuletzt geändert',
  'admin.conversation.meta.lastMessage': 'Letzte Nachricht',
  'admin.conversation.meta.noMessage': 'Noch keine Nachricht',

  'admin.conversation.members.title': 'Mitglieder',
  'admin.conversation.members.caption': 'Teilnehmer der Unterhaltung',
  'admin.conversation.members.count': '{count} Teilnehmer',
  'admin.conversation.members.empty': 'Kein Teilnehmer',
  'admin.conversation.members.col.member': 'Mitglied',
  'admin.conversation.members.col.role': 'Rolle',
  'admin.conversation.members.col.presence': 'Anwesenheit',
  'admin.conversation.members.col.state': 'Status',
  'admin.conversation.members.col.joined': 'Beigetreten',
  'admin.conversation.members.col.actions': 'Aktionen',
  'admin.conversation.members.state.active': 'Aktiv',
  'admin.conversation.members.state.left': 'Hat die Unterhaltung verlassen',
  'admin.conversation.members.roleOf': 'Rolle von {name}',
  'admin.conversation.members.remove': 'Entfernen',
  'admin.conversation.members.removeOf': '{name} aus der Unterhaltung entfernen',
  'admin.conversation.members.creatorProtected': 'Geschützt: Der Ersteller kann weder herabgestuft noch entfernt werden',
  'admin.conversation.members.creatorRefused':
    'Der Ersteller der Unterhaltung ist geschützt: Er kann weder herabgestuft noch entfernt werden.',
  'admin.conversation.members.motive': 'Begründung (mindestens 10 Zeichen)',
  'admin.conversation.members.role.confirmTitle': 'Rolle ändern',
  'admin.conversation.members.role.confirmBody':
    '{name} wechselt von „{from}“ zu „{to}“. Die Änderung wird mit Ihrer Begründung im Prüfprotokoll festgehalten.',
  'admin.conversation.members.role.confirm': 'Rolle ändern',
  'admin.conversation.members.role.done': 'Rolle geändert',
  'admin.conversation.members.remove.confirmTitle': 'Aus der Unterhaltung entfernen',
  'admin.conversation.members.remove.confirmBody':
    '{name} wird aus der Unterhaltung entfernt und hat danach keinen Zugriff mehr. Die Entfernung wird mit Ihrer Begründung im Prüfprotokoll festgehalten.',
  'admin.conversation.members.remove.confirm': 'Entfernen',
  'admin.conversation.members.remove.done': 'Mitglied entfernt',

  'admin.conversation.reading.title': 'Unterhaltung lesen',
  'admin.conversation.reading.hint':
    'Der Inhalt der Nachrichten ist nur mit schriftlicher Begründung lesbar, die mit Ihrem Namen im Prüfprotokoll festgehalten wird. Der Verlauf wird in Ihren Lesesprachen angezeigt, wie in der App.',

  'admin.agentPanel.subtitle':
    'Die Unterhaltungen, in denen der Agent eingreift: Verfolgen Sie seine Aktivität, starten Sie ihn erneut oder halten Sie einen laufenden Lauf an.',
  'admin.agentPanel.stat.tracked': 'Gesteuerte Unterhaltungen',
  'admin.agentPanel.stat.trackedCaption': 'von {total} verfolgten',
  'admin.agentPanel.stat.users': 'Gesteuerte Mitglieder',
  'admin.agentPanel.stat.messages': 'Veröffentlichte Nachrichten',

  'admin.agentPanel.tracked.caption': 'Vom Agenten verfolgte Unterhaltungen',
  'admin.agentPanel.tracked.search': 'Unterhaltung suchen',
  'admin.agentPanel.tracked.count': '{count} Unterhaltung(en)',
  'admin.agentPanel.tracked.empty': 'Keine verfolgte Unterhaltung',
  'admin.agentPanel.tracked.emptyHint': 'Sobald der Agent für eine Unterhaltung eingerichtet ist, erscheint sie hier.',
  'admin.agentPanel.tracked.filteredEmpty': 'Keine Unterhaltung für diese Suche',
  'admin.agentPanel.tracked.col.conversation': 'Unterhaltung',
  'admin.agentPanel.tracked.col.state': 'Status',
  'admin.agentPanel.tracked.col.users': 'Gesteuerte Mitglieder',
  'admin.agentPanel.tracked.col.messages': 'Veröffentlichte Nachrichten',
  'admin.agentPanel.tracked.col.lastResponse': 'Letzte Antwort',
  'admin.agentPanel.tracked.col.control': 'Steuerung',
  'admin.agentPanel.state.on': 'Aktiviert',
  'admin.agentPanel.state.off': 'Deaktiviert',
  'admin.agentPanel.state.scanning': 'Lauf aktiv',
  'admin.agentPanel.lastResponse.never': 'Noch keine Antwort',

  'admin.agentPanel.logs.caption': 'Lauf-Protokoll des Agenten',
  'admin.agentPanel.logs.count': '{count} Lauf/Läufe',
  'admin.agentPanel.logs.empty': 'Kein Lauf aufgezeichnet',
  'admin.agentPanel.logs.emptyHint': 'Jeder Durchgang des Agenten durch eine Unterhaltung hinterlässt hier eine Zeile.',
  'admin.agentPanel.logs.filteredEmpty': 'Kein Lauf für diese Filter',
  'admin.agentPanel.logs.filter.outcome': 'Ergebnis',
  'admin.agentPanel.logs.filter.trigger': 'Auslöser',
  'admin.agentPanel.logs.col.conversation': 'Unterhaltung',
  'admin.agentPanel.logs.col.trigger': 'Auslöser',
  'admin.agentPanel.logs.col.outcome': 'Ergebnis',
  'admin.agentPanel.logs.col.messages': 'Veröffentlichte Nachrichten',
  'admin.agentPanel.logs.col.duration': 'Dauer',
  'admin.agentPanel.logs.col.started': 'Start',
  'admin.agentPanel.logs.open': 'Details des Laufs von {name} öffnen',

  'admin.agentPanel.outcome.messages_sent': 'Nachricht veröffentlicht',
  'admin.agentPanel.outcome.messages_sent.explain': 'Der Agent hat in der Unterhaltung geschrieben.',
  'admin.agentPanel.outcome.reactions_only': 'Nur Reaktionen',
  'admin.agentPanel.outcome.reactions_only.explain': 'Der Agent hat auf Nachrichten reagiert, ohne eine zu veröffentlichen.',
  'admin.agentPanel.outcome.skipped': 'Keine Aktion',
  'admin.agentPanel.outcome.skipped.explain': 'Der Zyklus endete, ohne etwas zu veröffentlichen.',
  'admin.agentPanel.outcome.error': 'Fehler',
  'admin.agentPanel.outcome.error.explain': 'Der Zyklus ist fehlgeschlagen, bevor er endete.',
  'admin.agentPanel.trigger.auto': 'Automatisch',
  'admin.agentPanel.trigger.auto.explain': 'Vom Planer des Agenten gestartet.',
  'admin.agentPanel.trigger.manual': 'Manuell',
  'admin.agentPanel.trigger.manual.explain': 'Aus der Administration gestartet.',
  'admin.agentPanel.node.observer': 'liest die Unterhaltung',
  'admin.agentPanel.node.strategist': 'wählt, was er sagt',
  'admin.agentPanel.node.generator': 'schreibt eine Nachricht',
  'admin.agentPanel.node.qualityGate': 'prüft die Qualität',
  'admin.agentPanel.node.unknown': 'arbeitet',

  'admin.agentPanel.detail.title': 'Details des Laufs',
  'admin.agentPanel.detail.conversation': 'Unterhaltung',
  'admin.agentPanel.detail.started': 'Start',
  'admin.agentPanel.detail.reactions': 'Gesendete Reaktionen',
  'admin.agentPanel.detail.rejected': 'Verworfene Nachrichten',
  'admin.agentPanel.detail.rejectedExplain': 'Vom Agenten geschrieben und von seiner Qualitätsprüfung abgelehnt.',
  'admin.agentPanel.detail.users': 'Gespielte Mitglieder',
  'admin.agentPanel.detail.tokens': 'Token (Eingabe / Ausgabe)',
  'admin.agentPanel.detail.cost': 'Geschätzte Kosten',

  'admin.agentPanel.conversation.title': 'Agent in dieser Unterhaltung',
  'admin.agentPanel.conversation.usersNone': 'Noch kein gesteuertes Mitglied',
  'admin.agentPanel.conversation.messages': 'Veröffentlichte Nachrichten',
  'admin.agentPanel.conversation.lastResponse': 'Letzte Antwort',
} as const satisfies AdminCatalogFragment<typeof fr>;

export default f;
