import type { AdminCatalogFragment } from './fragment';
import type fr from './conversations-agent-fr';

/**
 * THE “conversations-agent” FRAGMENT OF THE ADMINISTRATION CATALOG (#8876) —
 * Portuguese (Brazil) text for the conversation list and sheet, the sovereign reading,
 * and the agent control. Same keys as the French source, which stays the
 * reference for meaning; the `admin.enum.*` labels it relies on live in the kit.
 */
const f = {
  'admin.conversation.subtitle':
    'Todas as conversas da plataforma: quem as compõe, em que ponto estão e a que comunidade pertencem. O conteúdo das mensagens só se lê com um motivo escrito, a partir da ficha.',
  'admin.conversation.search': 'Pesquisar por título ou identificador',
  'admin.conversation.list.caption': 'Lista de conversas',
  'admin.conversation.list.count': '{count} conversa(s)',
  'admin.conversation.list.empty': 'Nenhuma conversa',
  'admin.conversation.list.emptyHint': 'As conversas criadas na plataforma aparecem aqui.',
  'admin.conversation.list.filteredEmpty': 'Nenhuma conversa com estes filtros',
  'admin.conversation.list.onCommunity': 'Conversas de uma única comunidade: remova o filtro para voltar a ver todas as conversas.',
  'admin.conversation.list.onCommunityNamed': 'Conversas da comunidade «{name}»: remova o filtro para voltar a ver todas as conversas.',
  'admin.conversation.list.onCommunityReset': 'Ver todas as conversas',

  'admin.conversation.filter.type': 'Tipo',
  'admin.conversation.filter.state': 'Estado',
  'admin.conversation.filter.state.active': 'Ativas',
  'admin.conversation.filter.state.archived': 'Arquivadas',
  'admin.conversation.filter.period': 'Criadas nos últimos',
  'admin.conversation.filter.period.all': 'Todo o período',

  'admin.conversation.col.conversation': 'Conversa',
  'admin.conversation.col.type': 'Tipo',
  'admin.conversation.col.community': 'Comunidade',
  'admin.conversation.col.members': 'Membros',
  'admin.conversation.col.state': 'Estado',
  'admin.conversation.col.created': 'Criação',
  'admin.conversation.col.lastMessage': 'Última mensagem',

  'admin.conversation.fiche.loading': 'Carregando a conversa',
  'admin.conversation.fiche.notFound': 'Esta conversa não existe mais',
  'admin.conversation.fiche.notFoundHint': 'Foi excluída, ou o endereço está incorreto.',
  'admin.conversation.fiche.back': 'Voltar às conversas',
  'admin.conversation.fiche.configure': 'Configurar',

  'admin.conversation.stat.members': 'Membros ativos',
  'admin.conversation.stat.messages': 'Mensagens',
  'admin.conversation.stat.shareLinks': 'Links de compartilhamento',
  'admin.conversation.stat.agent': 'Agente',
  'admin.conversation.stat.agent.on': 'Ativo',
  'admin.conversation.stat.agent.off': 'Inativo',
  'admin.conversation.badge.agent': 'Agente ativo',

  'admin.conversation.meta.type': 'Tipo',
  'admin.conversation.meta.identifier': 'Identificador público',
  'admin.conversation.meta.identifierExplain': 'O seu endereço legível, distinto do identificador técnico.',
  'admin.conversation.meta.description': 'Descrição',
  'admin.conversation.meta.community': 'Comunidade',
  'admin.conversation.meta.state': 'Estado',
  'admin.conversation.meta.archivedExplain': 'Arquivada: ninguém pode escrever nela até ser restaurada.',
  'admin.conversation.meta.closedOn': 'Fechada em',
  'admin.conversation.meta.closedBy': 'Fechada por',
  'admin.conversation.meta.writeRole': 'Quem pode escrever',
  'admin.conversation.meta.writeRoleExplain': 'O nível mínimo exigido para enviar uma mensagem.',
  'admin.conversation.meta.announcement': 'Canal de anúncios',
  'admin.conversation.meta.announcement.yes': 'Sim: só os administradores escrevem nele',
  'admin.conversation.meta.announcement.no': 'Não: conversa comum',
  'admin.conversation.meta.slowMode': 'Modo lento',
  'admin.conversation.meta.slowMode.off': 'Desativado',
  'admin.conversation.meta.slowMode.on': 'Uma mensagem a cada {duration} por membro',
  'admin.conversation.meta.slowModeExplain': 'Os moderadores e os níveis acima estão isentos.',
  'admin.conversation.meta.autoTranslate': 'Tradução automática',
  'admin.conversation.meta.autoTranslate.yes': 'Ativada: cada leitor vê as mensagens no seu idioma',
  'admin.conversation.meta.autoTranslate.no': 'Desativada: as mensagens ficam no idioma original',
  'admin.conversation.meta.autoTranslate.unknown': 'Não especificada',
  'admin.conversation.meta.autoTranslate.e2ee': 'Inativa: o servidor não consegue ler mensagens criptografadas de ponta a ponta',
  'admin.conversation.meta.encryption': 'Criptografia',
  'admin.conversation.meta.created': 'Criada',
  'admin.conversation.meta.updated': 'Última modificação',
  'admin.conversation.meta.lastMessage': 'Última mensagem',
  'admin.conversation.meta.noMessage': 'Ainda sem mensagens',

  'admin.conversation.members.title': 'Membros',
  'admin.conversation.members.caption': 'Participantes da conversa',
  'admin.conversation.members.count': '{count} participante(s)',
  'admin.conversation.members.empty': 'Nenhum participante',
  'admin.conversation.members.col.member': 'Membro',
  'admin.conversation.members.col.role': 'Função',
  'admin.conversation.members.col.presence': 'Presença',
  'admin.conversation.members.col.state': 'Estado',
  'admin.conversation.members.col.joined': 'Entrada',
  'admin.conversation.members.col.actions': 'Ações',
  'admin.conversation.members.state.active': 'Ativo',
  'admin.conversation.members.state.left': 'Saiu da conversa',
  'admin.conversation.members.roleOf': 'Função de {name}',
  'admin.conversation.members.remove': 'Remover',
  'admin.conversation.members.removeOf': 'Remover {name} da conversa',
  'admin.conversation.members.creatorProtected': 'Protegido: o criador não pode ser rebaixado nem removido',
  'admin.conversation.members.creatorRefused': 'O criador da conversa está protegido: não pode ser rebaixado nem removido.',
  'admin.conversation.members.motive': 'Motivo (mínimo de 10 caracteres)',
  'admin.conversation.members.role.confirmTitle': 'Alterar a função',
  'admin.conversation.members.role.confirmBody': '{name} passará de «{from}» a «{to}». A alteração fica registrada no registro de auditoria com o seu motivo.',
  'admin.conversation.members.role.confirm': 'Alterar a função',
  'admin.conversation.members.role.done': 'Função alterada',
  'admin.conversation.members.remove.confirmTitle': 'Remover da conversa',
  'admin.conversation.members.remove.confirmBody':
    '{name} será removido da conversa e deixará de ter acesso a ela. A remoção fica registrada no registro de auditoria com o seu motivo.',
  'admin.conversation.members.remove.confirm': 'Remover',
  'admin.conversation.members.remove.done': 'Membro removido',

  'admin.conversation.reading.title': 'Ler a conversa',
  'admin.conversation.reading.hint': 'O conteúdo das mensagens só se lê com um motivo escrito, registrado com o seu nome no registro de auditoria. O fio é mostrado nos seus idiomas de leitura, como no aplicativo.',

  'admin.agentPanel.subtitle': 'As conversas em que o agente intervém: acompanhe a atividade dele, relance-o ou interrompa uma análise em andamento.',
  'admin.agentPanel.stat.tracked': 'Conversas controladas',
  'admin.agentPanel.stat.trackedCaption': 'de {total} acompanhadas',
  'admin.agentPanel.stat.users': 'Membros controlados',
  'admin.agentPanel.stat.messages': 'Mensagens publicadas',

  'admin.agentPanel.tracked.caption': 'Conversas acompanhadas pelo agente',
  'admin.agentPanel.tracked.search': 'Pesquisar uma conversa',
  'admin.agentPanel.tracked.count': '{count} conversa(s)',
  'admin.agentPanel.tracked.empty': 'Nenhuma conversa acompanhada',
  'admin.agentPanel.tracked.emptyHint': 'Quando o agente é configurado para uma conversa, ela aparece aqui.',
  'admin.agentPanel.tracked.filteredEmpty': 'Nenhuma conversa para esta pesquisa',
  'admin.agentPanel.tracked.col.conversation': 'Conversa',
  'admin.agentPanel.tracked.col.state': 'Estado',
  'admin.agentPanel.tracked.col.users': 'Membros controlados',
  'admin.agentPanel.tracked.col.messages': 'Mensagens publicadas',
  'admin.agentPanel.tracked.col.lastResponse': 'Última resposta',
  'admin.agentPanel.tracked.col.control': 'Controle',
  'admin.agentPanel.state.on': 'Ativado',
  'admin.agentPanel.state.off': 'Desativado',
  'admin.agentPanel.state.scanning': 'Análise em andamento',
  'admin.agentPanel.lastResponse.never': 'Nenhuma resposta',

  'admin.agentPanel.logs.caption': 'Registro das análises do agente',
  'admin.agentPanel.logs.count': '{count} análise(s)',
  'admin.agentPanel.logs.empty': 'Nenhuma análise registrada',
  'admin.agentPanel.logs.emptyHint': 'Cada passagem do agente por uma conversa deixa uma linha aqui.',
  'admin.agentPanel.logs.filteredEmpty': 'Nenhuma análise com estes filtros',
  'admin.agentPanel.logs.filter.outcome': 'Resultado',
  'admin.agentPanel.logs.filter.trigger': 'Acionador',
  'admin.agentPanel.logs.col.conversation': 'Conversa',
  'admin.agentPanel.logs.col.trigger': 'Acionador',
  'admin.agentPanel.logs.col.outcome': 'Resultado',
  'admin.agentPanel.logs.col.messages': 'Mensagens publicadas',
  'admin.agentPanel.logs.col.duration': 'Duração',
  'admin.agentPanel.logs.col.started': 'Início',
  'admin.agentPanel.logs.open': 'Abrir o detalhe da análise de {name}',

  'admin.agentPanel.outcome.messages_sent': 'Mensagem publicada',
  'admin.agentPanel.outcome.messages_sent.explain': 'O agente escreveu na conversa.',
  'admin.agentPanel.outcome.reactions_only': 'Só reações',
  'admin.agentPanel.outcome.reactions_only.explain': 'O agente reagiu a mensagens sem publicar nenhuma.',
  'admin.agentPanel.outcome.skipped': 'Nenhuma ação',
  'admin.agentPanel.outcome.skipped.explain': 'O ciclo terminou sem publicar nada.',
  'admin.agentPanel.outcome.error': 'Erro',
  'admin.agentPanel.outcome.error.explain': 'O ciclo falhou antes de terminar.',
  'admin.agentPanel.trigger.auto': 'Automático',
  'admin.agentPanel.trigger.auto.explain': 'Iniciado pelo planejador do agente.',
  'admin.agentPanel.trigger.manual': 'Manual',
  'admin.agentPanel.trigger.manual.explain': 'Iniciado a partir da administração.',
  'admin.agentPanel.node.observer': 'lê a conversa',
  'admin.agentPanel.node.strategist': 'decide o que dizer',
  'admin.agentPanel.node.generator': 'redige uma mensagem',
  'admin.agentPanel.node.qualityGate': 'controla a qualidade',
  'admin.agentPanel.node.unknown': 'está trabalhando',

  'admin.agentPanel.detail.title': 'Detalhe da análise',
  'admin.agentPanel.detail.conversation': 'Conversa',
  'admin.agentPanel.detail.started': 'Início',
  'admin.agentPanel.detail.reactions': 'Reações enviadas',
  'admin.agentPanel.detail.rejected': 'Mensagens descartadas',
  'admin.agentPanel.detail.rejectedExplain': 'Redigidas pelo agente e recusadas pelo controle de qualidade dele.',
  'admin.agentPanel.detail.users': 'Membros interpretados',
  'admin.agentPanel.detail.tokens': 'Tokens (entrada / saída)',
  'admin.agentPanel.detail.cost': 'Custo estimado',

  'admin.agentPanel.conversation.title': 'Agente nesta conversa',
  'admin.agentPanel.conversation.usersNone': 'Nenhum membro controlado no momento',
  'admin.agentPanel.conversation.messages': 'Mensagens publicadas',
  'admin.agentPanel.conversation.lastResponse': 'Última resposta',
} as const satisfies AdminCatalogFragment<typeof fr>;

export default f;
