import type { AdminCatalogFragment } from './fragment';
import type fr from './diffusions-fr';

const f = {
  'admin.broadcast.list.subtitle': 'Los mensajes que escribes a todas las cuentas, o a algunas: por correo electrónico, en la aplicación, o por ambos.',
  'admin.broadcast.list.caption': 'Lista de difusiones',
  'admin.broadcast.list.search': 'Buscar por nombre o asunto',
  'admin.broadcast.list.count': '{count} difusiones',
  'admin.broadcast.list.countOne': '1 difusión',
  'admin.broadcast.list.empty': 'Todavía ninguna difusión',
  'admin.broadcast.list.emptyHint': 'Escribe un primer mensaje a tus miembros: se guarda primero como borrador y no se envía nada antes de que lo confirmes.',
  'admin.broadcast.list.filteredEmpty': 'Ninguna difusión con estos filtros',
  'admin.broadcast.filter.status': 'Estado',
  'admin.broadcast.col.name': 'Nombre',
  'admin.broadcast.col.subject': 'Asunto',
  'admin.broadcast.col.status': 'Estado',
  'admin.broadcast.col.recipients': 'Destinatarios',
  'admin.broadcast.col.sent': 'Enviados',
  'admin.broadcast.col.failed': 'Fallos',
  'admin.broadcast.col.inApp': 'En la aplicación',
  'admin.broadcast.col.created': 'Creada',
  'admin.broadcast.col.sentAt': 'Enviada el',
  'admin.broadcast.notYet': 'Todavía no',
  'admin.broadcast.inApp.never': 'No publicada',
  'admin.broadcast.new': 'Nueva difusión',

  'admin.broadcast.compose.title.create': 'Nueva difusión',
  'admin.broadcast.compose.title.edit': 'Editar el borrador',
  'admin.broadcast.compose.intro.create': 'El mensaje se guarda primero como borrador: no se envía nada hasta que lo confirme desde su página.',
  'admin.broadcast.compose.intro.edit': 'Estás editando un borrador: todavía no se ha traducido ni enviado.',
  'admin.broadcast.compose.section.message': 'Mensaje',
  'admin.broadcast.compose.section.audience': 'Audiencia',
  'admin.broadcast.compose.field.name': 'Nombre de la difusión',
  'admin.broadcast.compose.field.name.hint': 'Te ayuda a encontrarla en la lista: los destinatarios nunca lo ven.',
  'admin.broadcast.compose.field.subject': 'Asunto',
  'admin.broadcast.compose.field.subject.hint': 'El asunto del correo y el título de la notificación.',
  'admin.broadcast.compose.field.body': 'Mensaje',
  'admin.broadcast.compose.field.body.hint': 'Escrito en el idioma de abajo; se traduce a los demás idiomas cuando lo prepara.',
  'admin.broadcast.compose.field.sourceLanguage': 'Idioma del mensaje',
  'admin.broadcast.compose.activity': 'Actividad de las cuentas',
  'admin.broadcast.compose.activity.all': 'Todas las cuentas',
  'admin.broadcast.compose.activity.active': 'Cuentas activas',
  'admin.broadcast.compose.activity.inactive': 'Cuentas inactivas',
  'admin.broadcast.compose.activity.new': 'Cuentas nuevas',
  'admin.broadcast.compose.activity.all.hint': 'Sin filtro de actividad.',
  'admin.broadcast.compose.activity.active.hint': 'Activas: con sesión iniciada en los últimos 30 días.',
  'admin.broadcast.compose.activity.inactive.hint': 'Inactivas: sin iniciar sesión durante el tiempo elegido, o nunca.',
  'admin.broadcast.compose.activity.new.hint': 'Nuevas: cuentas creadas en los últimos 7 días.',
  'admin.broadcast.compose.inactiveDays': 'Inactivas desde hace (días)',
  'admin.broadcast.compose.languages': 'Idiomas de las cuentas',
  'admin.broadcast.compose.languages.hint': 'Sin selección: todos los idiomas.',
  'admin.broadcast.compose.countries': 'País de registro',
  'admin.broadcast.compose.countries.hint': 'Sin selección: todos los países.',
  'admin.broadcast.compose.choice.filter': 'Filtrar la lista',
  'admin.broadcast.compose.choice.selected': 'Seleccionados: {count}',
  'admin.broadcast.compose.choice.none': 'Nada seleccionado',
  'admin.broadcast.compose.choice.remove': 'Quitar {name}',
  'admin.broadcast.compose.choice.noMatch': 'Ningún resultado',
  'admin.broadcast.compose.audience.preview': 'Audiencia objetivo',
  'admin.broadcast.compose.save.create': 'Guardar el borrador',
  'admin.broadcast.compose.save.edit': 'Guardar los cambios',
  'admin.broadcast.compose.save.busy': 'Guardando…',
  'admin.broadcast.compose.error.name': 'Ponle un nombre a la difusión.',
  'admin.broadcast.compose.error.subject': 'Escribe el asunto del mensaje.',
  'admin.broadcast.compose.error.body': 'Escribe el mensaje.',
  'admin.broadcast.compose.error.sourceLanguage': 'Elige el idioma del mensaje.',
  'admin.broadcast.compose.error.inactiveDays': 'Introduce un número entero de días, entre 1 y 3650.',
  'admin.broadcast.compose.error.summary': 'El formulario contiene errores: corrige los campos resaltados.',

  'admin.broadcast.fiche.loading': 'Cargando la difusión',
  'admin.broadcast.fiche.notFound': 'Esta difusión ya no existe',
  'admin.broadcast.fiche.notFoundHint': 'Se eliminó, o la dirección es incorrecta.',
  'admin.broadcast.fiche.back': 'Volver a las difusiones',
  'admin.broadcast.fiche.created': 'Creada {when}',
  'admin.broadcast.fiche.createdBy': 'Creada {when} por {author}',
  'admin.broadcast.stat.recipients': 'Destinatarios',
  'admin.broadcast.stat.sent': 'Correos enviados',
  'admin.broadcast.stat.failed': 'Fallos',
  'admin.broadcast.stat.inApp': 'En la aplicación',
  'admin.broadcast.section.content': 'Contenido',
  'admin.broadcast.content.subject': 'Asunto',
  'admin.broadcast.content.body': 'Mensaje',
  'admin.broadcast.content.writtenIn': 'Escrito en {language}',
  'admin.broadcast.section.translations': 'Traducciones',
  'admin.broadcast.translations.tabs': 'Idiomas de traducción',
  'admin.broadcast.translations.none.draft': 'Todavía sin traducir: las traducciones se crean al preparar el envío.',
  'admin.broadcast.translations.none.prepared': 'No hizo falta ninguna traducción: todos los destinatarios leen el idioma del mensaje.',
  'admin.broadcast.section.audience': 'Audiencia',
  'admin.broadcast.audience.everyone': 'Todas las cuentas',
  'admin.broadcast.audience.active': 'Cuentas activas',
  'admin.broadcast.audience.inactive': 'Cuentas inactivas desde hace {duration}',
  'admin.broadcast.audience.new': 'Cuentas creadas en los últimos 7 días',
  'admin.broadcast.audience.languages': 'en {languages}',
  'admin.broadcast.audience.countries': 'registradas en: {countries}',
  'admin.broadcast.audience.explain': 'Solo las cuentas activas y no eliminadas reciben una difusión, sea cual sea la segmentación.',
  'admin.broadcast.audience.recipients': 'Cuentas objetivo',
  'admin.broadcast.audience.recipients.draft': 'Se calcula al preparar el envío',
  'admin.broadcast.audience.chart.languages': 'Destinatarios por idioma',
  'admin.broadcast.audience.chart.countries': 'Destinatarios por país',
  'admin.broadcast.audience.chart.summary': 'Grupo más numeroso: {name}, {value}.',
  'admin.broadcast.section.email': 'Entrega por correo electrónico',
  'admin.broadcast.email.progress': 'Progreso del envío: {done} de {total}',
  'admin.broadcast.email.notSent': 'Todavía no enviada por correo electrónico.',
  'admin.broadcast.email.sentAt': 'Envío iniciado',
  'admin.broadcast.email.completedAt': 'Envío terminado',
  'admin.broadcast.email.running': 'En curso',
  'admin.broadcast.email.skipped': 'Las cuentas que desactivaron los correos de difusión se omiten: enviados más fallidos puede ser inferior al número de destinatarios.',
  'admin.broadcast.section.inApp': 'Entrega en la aplicación',
  'admin.broadcast.inApp.state': 'Estado',
  'admin.broadcast.inApp.state.never': 'Todavía no publicada en la aplicación',
  'admin.broadcast.inApp.state.running': 'Publicación en curso',
  'admin.broadcast.inApp.state.done': 'Publicada en la aplicación',
  'admin.broadcast.inApp.sent': 'Notificaciones publicadas',
  'admin.broadcast.inApp.failed': 'Fallos',
  'admin.broadcast.inApp.sentAt': 'Publicación iniciada',
  'admin.broadcast.inApp.completedAt': 'Publicación terminada',
  'admin.broadcast.section.people': 'Personas',
  'admin.broadcast.people.createdBy': 'Creada por',
  'admin.broadcast.people.sentBy': 'Enviada por correo por',
  'admin.broadcast.people.inAppBy': 'Publicada en la aplicación por',
  'admin.broadcast.people.unknown': 'Cuenta no encontrada',
  'admin.broadcast.meta.status': 'Estado',
  'admin.broadcast.meta.sourceLanguage': 'Idioma del mensaje',
  'admin.broadcast.meta.targetLanguages': 'Traducida a',
  'admin.broadcast.meta.targetLanguages.none': 'Ningún idioma',
  'admin.broadcast.meta.created': 'Creada',
  'admin.broadcast.meta.updated': 'Última modificación',
  'admin.broadcast.notice.failed': 'El envío ha fallado: {message}',
  'admin.broadcast.notice.failedNoMessage': 'El envío ha fallado y la pasarela no dio ningún mensaje de error.',
  'admin.broadcast.notice.sending': 'Envío en curso: esta página se actualiza sola cada 10 segundos.',
  'admin.broadcast.notice.inAppRunning': 'Publicación en curso: esta página se actualiza sola cada 10 segundos.',
  'admin.broadcast.notice.noRecipients': 'Ninguna cuenta coincide con esta audiencia: no hay a quién escribir. Elimina esta difusión y créala de nuevo con otra segmentación.',

  'admin.broadcast.gesture.edit': 'Editar',
  'admin.broadcast.gesture.prepare': 'Traducir y preparar el envío',
  'admin.broadcast.gesture.delete': 'Eliminar',
  'admin.broadcast.gesture.send.one': 'Enviar por correo a 1 cuenta',
  'admin.broadcast.gesture.send.many': 'Enviar por correo a {count} cuentas',
  'admin.broadcast.gesture.publishInApp': 'Publicar en la aplicación',
  'admin.broadcast.confirm.prepare.title': '¿Traducir y preparar el envío?',
  'admin.broadcast.confirm.prepare.body': 'Este paso traduce el asunto y el mensaje a los idiomas de los destinatarios y luego pasa la difusión a «{status}». No se envía nada, pero el borrador ya no se podrá editar. Puede tardar unos instantes.',
  'admin.broadcast.confirm.prepare.confirm': 'Traducir y preparar',
  'admin.broadcast.confirm.send.title': '¿Enviar por correo electrónico?',
  'admin.broadcast.confirm.send.body': 'Audiencia: {audience}. Cuentas objetivo: {count}. Cada una recibe el correo en su idioma; las cuentas que desactivaron los correos de difusión se omiten. El envío no se puede cancelar.',
  'admin.broadcast.confirm.send.confirm': 'Enviar',
  'admin.broadcast.confirm.inApp.title': '¿Publicar en la aplicación?',
  'admin.broadcast.confirm.inApp.body': 'Audiencia: {audience}. Cuentas objetivo: {count}. Cada una recibe una notificación en su centro de notificaciones, con un aviso push. No se puede retirar y solo se publica una vez.',
  'admin.broadcast.confirm.inApp.confirm': 'Publicar',
  'admin.broadcast.confirm.delete.title': '¿Eliminar esta difusión?',
  'admin.broadcast.confirm.delete.body': 'La difusión y sus traducciones se eliminan para siempre. No se envió nada por correo electrónico.',
  'admin.broadcast.confirm.delete.bodyPublished': 'La difusión y sus traducciones se eliminan para siempre. No se envió nada por correo electrónico y las notificaciones ya publicadas en la aplicación no se retiran.',
  'admin.broadcast.confirm.delete.confirm': 'Eliminar la difusión',
  'admin.broadcast.done.created': 'Borrador guardado',
  'admin.broadcast.done.updated': 'Cambios guardados',
  'admin.broadcast.done.prepared': 'Difusión lista: las traducciones están creadas',
  'admin.broadcast.done.sent': 'Envío de correos iniciado',
  'admin.broadcast.done.inApp': 'Publicación en la aplicación iniciada',
  'admin.broadcast.done.deleted': 'Difusión eliminada',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
