/**
 * LE FRAGMENT « diffusions » DU CATALOGUE D’ADMINISTRATION (#8876, #6731) — la
 * liste des diffusions, la feuille de composition, la fiche, ses gestes.
 * Préfixe exclusif : `admin.broadcast.`.
 *
 * Les pluriels évitent l’accord : « Comptes visés : 1 204 » plutôt que « 1 204
 * comptes », sauf les deux libellés du bouton d’envoi (singulier, pluriel).
 */
const f = {
  'admin.broadcast.list.subtitle': 'Les messages que vous écrivez à tous les comptes, ou à une partie d’entre eux : par e-mail, dans l’application, ou les deux.',
  'admin.broadcast.list.caption': 'Liste des diffusions',
  'admin.broadcast.list.search': 'Rechercher par nom ou objet',
  'admin.broadcast.list.count': '{count} diffusions',
  'admin.broadcast.list.countOne': '1 diffusion',
  'admin.broadcast.list.empty': 'Aucune diffusion pour l’instant',
  'admin.broadcast.list.emptyHint': 'Écrivez un premier message à vos membres : il est d’abord enregistré comme brouillon, et rien ne part avant votre confirmation.',
  'admin.broadcast.list.filteredEmpty': 'Aucune diffusion pour ces filtres',
  'admin.broadcast.filter.status': 'Statut',
  'admin.broadcast.col.name': 'Nom',
  'admin.broadcast.col.subject': 'Objet',
  'admin.broadcast.col.status': 'Statut',
  'admin.broadcast.col.recipients': 'Destinataires',
  'admin.broadcast.col.sent': 'Envoyés',
  'admin.broadcast.col.failed': 'Échecs',
  'admin.broadcast.col.inApp': 'Dans l’application',
  'admin.broadcast.col.created': 'Création',
  'admin.broadcast.col.sentAt': 'Envoi',
  'admin.broadcast.notYet': 'Pas encore',
  'admin.broadcast.inApp.never': 'Non publiée',
  'admin.broadcast.new': 'Nouvelle diffusion',

  'admin.broadcast.compose.title.create': 'Nouvelle diffusion',
  'admin.broadcast.compose.title.edit': 'Modifier le brouillon',
  'admin.broadcast.compose.intro.create': 'Le message est d’abord enregistré comme brouillon : rien n’est envoyé avant que vous le confirmiez depuis sa fiche.',
  'admin.broadcast.compose.intro.edit': 'Vous modifiez un brouillon : il n’a été ni traduit ni envoyé.',
  'admin.broadcast.compose.section.message': 'Message',
  'admin.broadcast.compose.section.audience': 'Audience',
  'admin.broadcast.compose.field.name': 'Nom de la diffusion',
  'admin.broadcast.compose.field.name.hint': 'Il sert à la retrouver dans la liste : les destinataires ne le voient pas.',
  'admin.broadcast.compose.field.subject': 'Objet',
  'admin.broadcast.compose.field.subject.hint': 'L’objet de l’e-mail et le titre de la notification.',
  'admin.broadcast.compose.field.body': 'Message',
  'admin.broadcast.compose.field.body.hint': 'Écrit dans la langue ci-dessous ; il est traduit pour les autres langues à la préparation.',
  'admin.broadcast.compose.field.sourceLanguage': 'Langue du message',
  'admin.broadcast.compose.activity': 'Activité des comptes',
  'admin.broadcast.compose.activity.all': 'Tous les comptes',
  'admin.broadcast.compose.activity.active': 'Comptes actifs',
  'admin.broadcast.compose.activity.inactive': 'Comptes inactifs',
  'admin.broadcast.compose.activity.new': 'Nouveaux comptes',
  'admin.broadcast.compose.activity.all.hint': 'Aucun filtre d’activité.',
  'admin.broadcast.compose.activity.active.hint': 'Actifs : connectés au cours des 30 derniers jours.',
  'admin.broadcast.compose.activity.inactive.hint': 'Inactifs : pas connectés depuis la durée choisie, ou jamais.',
  'admin.broadcast.compose.activity.new.hint': 'Nouveaux : comptes créés au cours des 7 derniers jours.',
  'admin.broadcast.compose.inactiveDays': 'Inactifs depuis (jours)',
  'admin.broadcast.compose.languages': 'Langues des comptes',
  'admin.broadcast.compose.languages.hint': 'Aucune sélection : toutes les langues.',
  'admin.broadcast.compose.countries': 'Pays d’inscription',
  'admin.broadcast.compose.countries.hint': 'Aucune sélection : tous les pays.',
  'admin.broadcast.compose.choice.filter': 'Filtrer la liste',
  'admin.broadcast.compose.choice.selected': 'Sélection : {count}',
  'admin.broadcast.compose.choice.none': 'Aucune sélection',
  'admin.broadcast.compose.choice.remove': 'Retirer {name}',
  'admin.broadcast.compose.choice.noMatch': 'Aucun résultat',
  'admin.broadcast.compose.audience.preview': 'Audience visée',
  'admin.broadcast.compose.save.create': 'Enregistrer le brouillon',
  'admin.broadcast.compose.save.edit': 'Enregistrer les modifications',
  'admin.broadcast.compose.save.busy': 'Enregistrement…',
  'admin.broadcast.compose.error.name': 'Donnez un nom à la diffusion.',
  'admin.broadcast.compose.error.subject': 'Écrivez l’objet du message.',
  'admin.broadcast.compose.error.body': 'Écrivez le message.',
  'admin.broadcast.compose.error.sourceLanguage': 'Choisissez la langue du message.',
  'admin.broadcast.compose.error.inactiveDays': 'Indiquez un nombre entier de jours, entre 1 et 3 650.',
  'admin.broadcast.compose.error.summary': 'Le formulaire contient des erreurs : corrigez les champs signalés.',

  'admin.broadcast.fiche.loading': 'Chargement de la diffusion',
  'admin.broadcast.fiche.notFound': 'Cette diffusion n’existe plus',
  'admin.broadcast.fiche.notFoundHint': 'Elle a été supprimée, ou l’adresse est erronée.',
  'admin.broadcast.fiche.back': 'Retour aux diffusions',
  'admin.broadcast.fiche.created': 'Créée {when}',
  'admin.broadcast.fiche.createdBy': 'Créée {when} par {author}',
  'admin.broadcast.stat.recipients': 'Destinataires',
  'admin.broadcast.stat.sent': 'E-mails envoyés',
  'admin.broadcast.stat.failed': 'Échecs',
  'admin.broadcast.stat.inApp': 'Dans l’application',
  'admin.broadcast.section.content': 'Contenu',
  'admin.broadcast.content.subject': 'Objet',
  'admin.broadcast.content.body': 'Message',
  'admin.broadcast.content.writtenIn': 'Écrit en {language}',
  'admin.broadcast.section.translations': 'Traductions',
  'admin.broadcast.translations.tabs': 'Langues de traduction',
  'admin.broadcast.translations.none.draft': 'Pas encore traduite : les traductions sont créées quand vous préparez l’envoi.',
  'admin.broadcast.translations.none.prepared': 'Aucune traduction n’a été nécessaire : tous les destinataires lisent la langue du message.',
  'admin.broadcast.section.audience': 'Audience',
  'admin.broadcast.audience.everyone': 'Tous les comptes',
  'admin.broadcast.audience.active': 'Comptes actifs',
  'admin.broadcast.audience.inactive': 'Comptes inactifs depuis {duration}',
  'admin.broadcast.audience.new': 'Comptes créés ces 7 derniers jours',
  'admin.broadcast.audience.languages': 'en {languages}',
  'admin.broadcast.audience.countries': 'pays d’inscription : {countries}',
  'admin.broadcast.audience.explain': 'Seuls les comptes actifs et non supprimés reçoivent une diffusion, quel que soit le ciblage.',
  'admin.broadcast.audience.recipients': 'Comptes visés',
  'admin.broadcast.audience.recipients.draft': 'Calculé à la préparation de l’envoi',
  'admin.broadcast.audience.chart.languages': 'Destinataires par langue',
  'admin.broadcast.audience.chart.countries': 'Destinataires par pays',
  'admin.broadcast.audience.chart.summary': 'Le plus grand groupe : {name}, {value}.',
  'admin.broadcast.section.email': 'Livraison par e-mail',
  'admin.broadcast.email.progress': 'Progression de l’envoi : {done} sur {total}',
  'admin.broadcast.email.notSent': 'Pas encore envoyée par e-mail.',
  'admin.broadcast.email.sentAt': 'Envoi lancé',
  'admin.broadcast.email.completedAt': 'Envoi terminé',
  'admin.broadcast.email.running': 'En cours',
  'admin.broadcast.email.skipped': 'Les comptes qui ont désactivé les e-mails de diffusion sont ignorés : le nombre d’envois et d’échecs peut être inférieur au nombre de destinataires.',
  'admin.broadcast.section.inApp': 'Livraison dans l’application',
  'admin.broadcast.inApp.state': 'État',
  'admin.broadcast.inApp.state.never': 'Pas encore publiée dans l’application',
  'admin.broadcast.inApp.state.running': 'Publication en cours',
  'admin.broadcast.inApp.state.done': 'Publiée dans l’application',
  'admin.broadcast.inApp.sent': 'Notifications publiées',
  'admin.broadcast.inApp.failed': 'Échecs',
  'admin.broadcast.inApp.sentAt': 'Publication lancée',
  'admin.broadcast.inApp.completedAt': 'Publication terminée',
  'admin.broadcast.section.people': 'Personnes',
  'admin.broadcast.people.createdBy': 'Créée par',
  'admin.broadcast.people.sentBy': 'Envoyée par e-mail par',
  'admin.broadcast.people.inAppBy': 'Publiée dans l’application par',
  'admin.broadcast.people.unknown': 'Compte introuvable',
  'admin.broadcast.meta.status': 'Statut',
  'admin.broadcast.meta.sourceLanguage': 'Langue du message',
  'admin.broadcast.meta.targetLanguages': 'Traduite en',
  'admin.broadcast.meta.targetLanguages.none': 'Aucune langue',
  'admin.broadcast.meta.created': 'Création',
  'admin.broadcast.meta.updated': 'Dernière modification',
  'admin.broadcast.notice.failed': 'L’envoi a échoué : {message}',
  'admin.broadcast.notice.failedNoMessage': 'L’envoi a échoué, et la passerelle n’a donné aucun message d’erreur.',
  'admin.broadcast.notice.sending': 'Envoi en cours : cette page se met à jour toute seule, toutes les 10 secondes.',
  'admin.broadcast.notice.inAppRunning': 'Publication en cours : cette page se met à jour toute seule, toutes les 10 secondes.',
  'admin.broadcast.notice.noRecipients': 'Aucun compte ne correspond à cette audience : il n’y a personne à qui écrire. Supprimez cette diffusion et recréez-la avec un autre ciblage.',

  'admin.broadcast.gesture.edit': 'Modifier',
  'admin.broadcast.gesture.prepare': 'Traduire et préparer l’envoi',
  'admin.broadcast.gesture.delete': 'Supprimer',
  'admin.broadcast.gesture.send.one': 'Envoyer par e-mail à 1 compte',
  'admin.broadcast.gesture.send.many': 'Envoyer par e-mail à {count} comptes',
  'admin.broadcast.gesture.publishInApp': 'Publier dans l’application',
  'admin.broadcast.confirm.prepare.title': 'Traduire et préparer l’envoi ?',
  'admin.broadcast.confirm.prepare.body': 'Cette étape traduit l’objet et le message vers les langues des destinataires, puis passe la diffusion à « {status} ». Rien n’est envoyé, mais le brouillon ne pourra plus être modifié. Elle peut prendre quelques instants.',
  'admin.broadcast.confirm.prepare.confirm': 'Traduire et préparer',
  'admin.broadcast.confirm.send.title': 'Envoyer par e-mail ?',
  'admin.broadcast.confirm.send.body': 'Audience : {audience}. Comptes visés : {count}. Chacun reçoit l’e-mail dans sa langue ; les comptes qui ont désactivé les e-mails de diffusion sont ignorés. L’envoi ne peut pas être annulé.',
  'admin.broadcast.confirm.send.confirm': 'Envoyer',
  'admin.broadcast.confirm.inApp.title': 'Publier dans l’application ?',
  'admin.broadcast.confirm.inApp.body': 'Audience : {audience}. Comptes visés : {count}. Chacun reçoit une notification dans son centre de notifications, avec un envoi push. Elle ne peut pas être retirée, et ne se publie qu’une fois.',
  'admin.broadcast.confirm.inApp.confirm': 'Publier',
  'admin.broadcast.confirm.delete.title': 'Supprimer cette diffusion ?',
  'admin.broadcast.confirm.delete.body': 'La diffusion et ses traductions sont supprimées définitivement. Rien n’a été envoyé par e-mail.',
  'admin.broadcast.confirm.delete.bodyPublished': 'La diffusion et ses traductions sont supprimées définitivement. Rien n’a été envoyé par e-mail, et les notifications déjà publiées dans l’application ne sont pas retirées.',
  'admin.broadcast.confirm.delete.confirm': 'Supprimer la diffusion',
  'admin.broadcast.done.created': 'Brouillon enregistré',
  'admin.broadcast.done.updated': 'Modifications enregistrées',
  'admin.broadcast.done.prepared': 'Diffusion prête : les traductions sont créées',
  'admin.broadcast.done.sent': 'Envoi par e-mail lancé',
  'admin.broadcast.done.inApp': 'Publication dans l’application lancée',
  'admin.broadcast.done.deleted': 'Diffusion supprimée',
} as const;

export default f;
