import type { AdminCatalogFragment } from './fragment';
import type fr from './engagement-scale-fr';

const f = {
  'admin.scale.title': 'Baremo de puntos',
  'admin.scale.subtitle': 'Lo que aporta cada acción en puntos de participación, cómo los multiplica el impulso y hasta dónde llega.',
  'admin.scale.loadFailed': 'No se pudo cargar el baremo.',
  'admin.scale.updated': 'Ajustado el {date} por {by}',
  'admin.scale.defaults': 'Baremo por defecto — nunca ajustado.',
  'admin.scale.operations.title': 'Operaciones',
  'admin.scale.col.operation': 'Operación',
  'admin.scale.col.points': 'Puntos',
  'admin.scale.col.multiplied': 'Multiplicado',
  'admin.scale.col.cap': 'Límite',
  'admin.scale.col.frequency': 'Frecuencia',
  'admin.scale.cap.none': 'Ninguno',
  'admin.scale.pointsFor': 'Puntos — {operation}',
  'admin.scale.multipliedFor': 'Multiplicado por el impulso — {operation}',
  'admin.scale.capFor': 'Límite — {operation}',
  'admin.scale.variantFor': 'Puntos ({variant}) — {operation}',
  'admin.scale.multiplier.title': 'Multiplicador',
  'admin.scale.field.windowDays': 'Ventana móvil (días)',
  'admin.scale.field.stepPerExtraFamily': 'Paso por familia adicional',
  'admin.scale.field.standingBonus': 'Bonificación de estabilidad',
  'admin.scale.field.achievementsForStanding': 'Logros para la estabilidad',
  'admin.scale.field.highBadgeThreshold': 'Umbral de insignia alta',
  'admin.scale.field.highBadgesForStanding': 'Insignias altas para la estabilidad',
  'admin.scale.field.maxFactor': 'Multiplicador máximo',
  'admin.scale.levels.title': 'Límite por nivel',
  'admin.scale.col.minLevel': 'Desde el nivel',
  'admin.scale.col.maxFactor': 'Multiplicador máximo',
  'admin.scale.levels.empty': 'Sin límite por nivel: el multiplicador máximo vale para todos.',
  'admin.scale.levels.add': 'Añadir un nivel',
  'admin.scale.levels.remove': 'Quitar el nivel {level}',
  'admin.scale.minLevelFor': 'Nivel mínimo — fila {row}',
  'admin.scale.maxFactorFor': 'Multiplicador máximo — fila {row}',
  'admin.scale.reset': 'Volver a los valores por defecto',
  'admin.scale.save': 'Guardar',
  'admin.scale.saving': 'Guardando…',
  'admin.scale.saved': 'Baremo guardado.',
  'admin.scale.invalid': 'Baremo no válido: un valor está fuera de límites, un nivel o un tramo de racha está duplicado, o un límite de nivel supera el multiplicador máximo.',
  'admin.scale.saveFailed': 'Error al guardar: {error}',
  'admin.scale.resetDone': 'Valores por defecto restablecidos — guarda para aplicarlos.',
  'admin.scale.domain.messaging': 'Mensajería',
  'admin.scale.domain.calls': 'Llamadas',
  'admin.scale.domain.conversations': 'Conversaciones',
  'admin.scale.domain.communities': 'Comunidades',
  'admin.scale.domain.publishing': 'Publicación',
  'admin.scale.domain.feed': 'Feed social',
  'admin.scale.domain.links': 'Enlaces y afiliación',
  'admin.scale.domain.friends': 'Amigos y contactos',
  'admin.scale.domain.profile': 'Perfil y voz',
  'admin.scale.domain.tools': 'Herramientas',
  'admin.scale.freq.repeatable': 'Repetible',
  'admin.scale.freq.per-target': 'Única por destino',
  'admin.scale.freq.per-account': 'Una vez por cuenta',
  'admin.scale.freq.progressive': 'Progresivo',
  'admin.scale.scope.conversation-day': 'por día y por conversación',
  'admin.scale.scope.day': 'por día',
  'admin.scale.scope.target': 'por destino',
  'admin.scale.cap.perTarget': '1 por destino',
  'admin.scale.cap.perAccount': '1 por cuenta',
  'admin.scale.cap.linkRule': 'Regla de enlaces',
  'admin.scale.variant.public': 'pública',
  'admin.scale.variant.community': 'comunidad',
  'admin.scale.variant.friends': 'amigos',
  'admin.scale.variant.other': 'otra',
  'admin.scale.variant.live': 'en directo',
  'admin.scale.variant.static': 'estática',
  'admin.scale.op.content.text_message': 'Enviar un mensaje de texto',
  'admin.scale.op.content.audio_message': 'Enviar un mensaje de voz',
  'admin.scale.op.tool.attachment': 'Adjuntar un archivo, una foto o un vídeo',
  'admin.scale.op.tool.sticker': 'Enviar un sticker',
  'admin.scale.op.tool.reaction': 'Reaccionar a un mensaje',
  'admin.scale.op.tool.quote_reply': 'Responder citando un mensaje',
  'admin.scale.op.tool.forward': 'Reenviar un mensaje',
  'admin.scale.op.tool.pin': 'Fijar un mensaje',
  'admin.scale.op.tool.voice_listened': 'Escuchar un mensaje de voz hasta el final',
  'admin.scale.op.tool.translation_request': 'Pedir una traducción o una transcripción',
  'admin.scale.op.tool.location': 'Compartir tu ubicación',
  'admin.scale.op.conversation.call_started': 'Hacer una llamada (≥ 30 s)',
  'admin.scale.op.conversation.call_joined': 'Unirse a una llamada (≥ 30 s)',
  'admin.scale.op.conversation.call_minutes': 'Tramo de 5 minutos de llamada',
  'admin.scale.op.conversation.call_participant_added': 'Añadir a alguien a una llamada en curso',
  'admin.scale.op.conversation.private': 'Primer mensaje en una conversación privada',
  'admin.scale.op.conversation.public': 'Primer mensaje en una conversación pública',
  'admin.scale.op.conversation.community': 'Primer mensaje en una conversación de comunidad',
  'admin.scale.op.conversation.group_created': 'Crear un grupo (por conjunto de miembros)',
  'admin.scale.op.social.conversation_invite': 'Invitar a alguien a una conversación',
  'admin.scale.op.social.conversation_link_joined': 'Alguien entra con mi enlace de conversación',
  'admin.scale.op.social.community_created': 'Crear una comunidad',
  'admin.scale.op.social.community_joined': 'Unirse a una comunidad',
  'admin.scale.op.content.post': 'Crear una publicación',
  'admin.scale.op.content.story': 'Publicar una historia',
  'admin.scale.op.content.reel': 'Publicar un reel',
  'admin.scale.op.content.status': 'Publicar un estado de ánimo',
  'admin.scale.op.tool.in_app_edit': 'Crear en el editor de Meeshy',
  'admin.scale.op.tool.direct_publish': 'Publicar un medio directamente',
  'admin.scale.op.comment.text': 'Comentar por escrito',
  'admin.scale.op.comment.audio': 'Comentar con un mensaje de voz',
  'admin.scale.op.tool.post_reaction': 'Reaccionar a una publicación',
  'admin.scale.op.tool.comment_like': 'Dar me gusta a un comentario',
  'admin.scale.op.social.repost': 'Republicar una publicación',
  'admin.scale.op.social.share': 'Compartir una publicación (enlace rastreado)',
  'admin.scale.op.tool.post_bookmark': 'Guardar una publicación',
  'admin.scale.op.tool.story_viewed': 'Ver una historia hasta el final',
  'admin.scale.op.tool.poll_answered': 'Responder una encuesta',
  'admin.scale.op.social.tracked_link': 'Crear un enlace rastreado',
  'admin.scale.op.social.affiliate_link_created': 'Crear un enlace de afiliación',
  'admin.scale.op.social.conversation_link_created': 'Crear un enlace de conversación',
  'admin.scale.op.social.link_visit': 'Visita única a uno de mis enlaces',
  'admin.scale.op.social.invite_joined': 'Un referido se registra con mi enlace',
  'admin.scale.op.social.friendship': 'Amistad aceptada (ambos ganan)',
  'admin.scale.op.social.email_invite': 'Invitar por correo electrónico',
  'admin.scale.op.social.contacts_synced': 'Sincronizar tus contactos',
  'admin.scale.op.profile.avatar': 'Añadir una foto de perfil',
  'admin.scale.op.profile.bio': 'Escribir tu biografía',
  'admin.scale.op.profile.second_language': 'Configurar un segundo idioma',
  'admin.scale.op.profile.email_verified': 'Verificar tu correo electrónico',
  'admin.scale.op.profile.phone_verified': 'Verificar tu teléfono',
  'admin.scale.op.profile.two_factor': 'Activar la autenticación en dos pasos',
  'admin.scale.op.profile.voice_profile': 'Grabar tu voz (con consentimiento)',
  'admin.scale.op.tool.sticker_created': 'Crear un sticker a partir de una imagen',
  'admin.scale.op.streak.bonus': 'Bonificación por racha',
  'admin.scale.links.title': 'Regla de enlaces (visita única)',
  'admin.scale.links.intro': 'Una visita cuenta una vez por visitante, por enlace y por ventana, nunca la del creador. Su valor sube cada vez que las visitas se duplican más allá del primer tramo.',
  'admin.scale.links.basePoints': 'Valor inicial de una visita',
  'admin.scale.links.firstTier': 'Tamaño del primer tramo (visitas)',
  'admin.scale.links.stepPerDoubling': 'Aumento por cada duplicación',
  'admin.scale.links.maxPoints': 'Valor máximo de una visita',
  'admin.scale.links.dedupHours': 'Ventana de una visita única (horas)',
  'admin.scale.links.dailyCapPerCreator': 'Visitas acreditadas por creador y por día',
  'admin.scale.streak.title': 'Bonificación por racha',
  'admin.scale.streak.empty': 'Ninguna bonificación por racha.',
  'admin.scale.streak.col.days': 'Días activos seguidos',
  'admin.scale.streak.col.points': 'Puntos',
  'admin.scale.streak.daysFor': 'Días — tramo {row}',
  'admin.scale.streak.pointsFor': 'Puntos — tramo {row}',
  'admin.scale.streak.add': 'Añadir un tramo',
  'admin.scale.streak.remove': 'Quitar el tramo de {days} días',
  'admin.scale.abuse.title': 'Salvaguardas de los pesos altos',
  'admin.scale.abuse.intro': 'Una operación que vale al menos el umbral solo acredita una vez por contenido, devuelve sus puntos si el contenido se elimina dentro de la ventana y queda limitada para una cuenta sin correo ni teléfono verificado. Interactuar con tu propio contenido nunca da nada.',
  'admin.scale.abuse.heavyPoints': 'Umbral de peso alto (puntos)',
  'admin.scale.abuse.clawbackHours': 'Retirada si se elimina en (horas)',
  'admin.scale.abuse.unverifiedMaxPoints': 'Máximo para una cuenta no verificada',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
