import type { AdminCatalogFragment } from './fragment';
import type fr from './engagement-scale-fr';

const f = {
  'admin.scale.title': 'Tabela de pontos',
  'admin.scale.subtitle': 'O que cada ação rende em pontos de engajamento, como o ímpeto os multiplica e até onde vai.',
  'admin.scale.loadFailed': 'Não foi possível carregar a tabela.',
  'admin.scale.updated': 'Definida em {date} por {by}',
  'admin.scale.defaults': 'Tabela padrão — nunca definida.',
  'admin.scale.operations.title': 'Operações',
  'admin.scale.col.operation': 'Operação',
  'admin.scale.col.points': 'Pontos',
  'admin.scale.col.multiplied': 'Multiplicado',
  'admin.scale.col.cap': 'Limite por conversa e por dia',
  'admin.scale.cap.none': 'Nenhum',
  'admin.scale.pointsFor': 'Pontos — {operation}',
  'admin.scale.multipliedFor': 'Multiplicado pelo impulso — {operation}',
  'admin.scale.capFor': 'Limite diário — {operation}',
  'admin.scale.multiplier.title': 'Multiplicador',
  'admin.scale.field.windowDays': 'Janela móvel (dias)',
  'admin.scale.field.stepPerExtraFamily': 'Passo por família adicional',
  'admin.scale.field.standingBonus': 'Bônus de estabilidade',
  'admin.scale.field.achievementsForStanding': 'Conquistas para a estabilidade',
  'admin.scale.field.highBadgeThreshold': 'Limiar de medalha alta',
  'admin.scale.field.highBadgesForStanding': 'Medalhas altas para a estabilidade',
  'admin.scale.field.maxFactor': 'Multiplicador máximo',
  'admin.scale.levels.title': 'Limite por nível',
  'admin.scale.col.minLevel': 'A partir do nível',
  'admin.scale.col.maxFactor': 'Multiplicador máximo',
  'admin.scale.levels.empty': 'Sem limite por nível: o multiplicador máximo vale para todos.',
  'admin.scale.levels.add': 'Adicionar um nível',
  'admin.scale.levels.remove': 'Remover o nível {level}',
  'admin.scale.minLevelFor': 'Nível mínimo — linha {row}',
  'admin.scale.maxFactorFor': 'Multiplicador máximo — linha {row}',
  'admin.scale.reset': 'Voltar aos padrões',
  'admin.scale.save': 'Salvar',
  'admin.scale.saving': 'Salvando…',
  'admin.scale.saved': 'Tabela salva.',
  'admin.scale.invalid': 'Tabela inválida: um valor está fora dos limites, um nível está duplicado ou excede o multiplicador máximo.',
  'admin.scale.saveFailed': 'Falha ao salvar: {error}',
  'admin.scale.resetDone': 'Padrões restaurados — salve para aplicá-los.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
