import type { AdminCatalogFragment } from './fragment';
import type fr from './engagement-scale-fr';

const f = {
  'admin.scale.title': 'Points scale',
  'admin.scale.denied': 'This setting is reserved for administrators.',
  'admin.scale.loadFailed': 'The scale could not be loaded.',
  'admin.scale.retry': 'Retry',
  'admin.scale.updated': 'Set on {date} by {by}',
  'admin.scale.defaults': 'Default scale — never set.',
  'admin.scale.operations.title': 'Operations',
  'admin.scale.col.operation': 'Operation',
  'admin.scale.col.points': 'Points',
  'admin.scale.col.multiplied': 'Multiplied',
  'admin.scale.col.cap': 'Cap per conversation per day',
  'admin.scale.cap.none': 'None',
  'admin.scale.pointsFor': 'Points — {operation}',
  'admin.scale.multipliedFor': 'Multiplied by momentum — {operation}',
  'admin.scale.capFor': 'Daily cap — {operation}',
  'admin.scale.multiplier.title': 'Multiplier',
  'admin.scale.field.windowDays': 'Rolling window (days)',
  'admin.scale.field.stepPerExtraFamily': 'Step per extra family',
  'admin.scale.field.standingBonus': 'Standing bonus',
  'admin.scale.field.achievementsForStanding': 'Achievements for standing',
  'admin.scale.field.highBadgeThreshold': 'High badge threshold',
  'admin.scale.field.highBadgesForStanding': 'High badges for standing',
  'admin.scale.field.maxFactor': 'Maximum multiplier',
  'admin.scale.levels.title': 'Cap by level',
  'admin.scale.col.minLevel': 'From level',
  'admin.scale.col.maxFactor': 'Maximum multiplier',
  'admin.scale.levels.empty': 'No cap by level: the maximum multiplier applies to everyone.',
  'admin.scale.levels.add': 'Add a level',
  'admin.scale.levels.remove': 'Remove level {level}',
  'admin.scale.minLevelFor': 'Minimum level — row {row}',
  'admin.scale.maxFactorFor': 'Maximum multiplier — row {row}',
  'admin.scale.reset': 'Reset to defaults',
  'admin.scale.save': 'Save',
  'admin.scale.saving': 'Saving…',
  'admin.scale.saved': 'Scale saved.',
  'admin.scale.invalid': 'Invalid scale: a value is out of bounds, a level is duplicated or exceeds the maximum multiplier.',
  'admin.scale.saveFailed': 'Save failed: {error}',
  'admin.scale.resetDone': 'Defaults restored — save to apply them.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
