import type { AdminCatalogFragment } from './fragment';
import type fr from './engagement-scale-fr';

const f = {
  'admin.scale.title': 'سلّم النقاط',
  'admin.scale.denied': 'هذا الإعداد مخصص للمسؤولين.',
  'admin.scale.loadFailed': 'تعذّر تحميل السلّم.',
  'admin.scale.retry': 'إعادة المحاولة',
  'admin.scale.updated': 'ضُبط في {date} بواسطة {by}',
  'admin.scale.defaults': 'السلّم الافتراضي — لم يُضبط قط.',
  'admin.scale.operations.title': 'العمليات',
  'admin.scale.col.operation': 'العملية',
  'admin.scale.col.points': 'النقاط',
  'admin.scale.col.multiplied': 'مضاعَفة',
  'admin.scale.col.cap': 'الحد لكل محادثة في اليوم',
  'admin.scale.cap.none': 'لا شيء',
  'admin.scale.pointsFor': 'النقاط — {operation}',
  'admin.scale.multipliedFor': 'مضاعَفة بالزخم — {operation}',
  'admin.scale.capFor': 'الحد اليومي — {operation}',
  'admin.scale.multiplier.title': 'المضاعِف',
  'admin.scale.field.windowDays': 'النافذة المتحركة (أيام)',
  'admin.scale.field.stepPerExtraFamily': 'درجة لكل عائلة إضافية',
  'admin.scale.field.standingBonus': 'مكافأة الرسوخ',
  'admin.scale.field.achievementsForStanding': 'الإنجازات اللازمة للرسوخ',
  'admin.scale.field.highBadgeThreshold': 'عتبة الشارة العالية',
  'admin.scale.field.highBadgesForStanding': 'الشارات العالية اللازمة للرسوخ',
  'admin.scale.field.maxFactor': 'المضاعِف الأقصى',
  'admin.scale.levels.title': 'الحد حسب المستوى',
  'admin.scale.col.minLevel': 'ابتداءً من المستوى',
  'admin.scale.col.maxFactor': 'المضاعِف الأقصى',
  'admin.scale.levels.empty': 'لا حد حسب المستوى: المضاعِف الأقصى يسري على الجميع.',
  'admin.scale.levels.add': 'إضافة مستوى',
  'admin.scale.levels.remove': 'إزالة المستوى {level}',
  'admin.scale.minLevelFor': 'المستوى الأدنى — السطر {row}',
  'admin.scale.maxFactorFor': 'المضاعِف الأقصى — السطر {row}',
  'admin.scale.reset': 'العودة إلى الافتراضي',
  'admin.scale.save': 'حفظ',
  'admin.scale.saving': 'جارٍ الحفظ…',
  'admin.scale.saved': 'تم حفظ السلّم.',
  'admin.scale.invalid': 'سلّم غير صالح: قيمة خارج الحدود، أو مستوى مكرر، أو يتجاوز المضاعِف الأقصى.',
  'admin.scale.saveFailed': 'فشل الحفظ: {error}',
  'admin.scale.resetDone': 'استُعيدت القيم الافتراضية — احفظ لتطبيقها.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
