import type { AdminCatalogFragment } from './fragment';
import type fr from './engagement-scale-fr';

const f = {
  'admin.scale.title': 'Punkteskala',
  'admin.scale.denied': 'Diese Einstellung ist Administratoren vorbehalten.',
  'admin.scale.loadFailed': 'Die Skala konnte nicht geladen werden.',
  'admin.scale.retry': 'Erneut versuchen',
  'admin.scale.updated': 'Festgelegt am {date} von {by}',
  'admin.scale.defaults': 'Standardskala — nie festgelegt.',
  'admin.scale.operations.title': 'Vorgänge',
  'admin.scale.col.operation': 'Vorgang',
  'admin.scale.col.points': 'Punkte',
  'admin.scale.col.multiplied': 'Multipliziert',
  'admin.scale.col.cap': 'Obergrenze pro Unterhaltung und Tag',
  'admin.scale.cap.none': 'Keine',
  'admin.scale.pointsFor': 'Punkte — {operation}',
  'admin.scale.multipliedFor': 'Mit dem Schwung multipliziert — {operation}',
  'admin.scale.capFor': 'Tagesobergrenze — {operation}',
  'admin.scale.multiplier.title': 'Multiplikator',
  'admin.scale.field.windowDays': 'Gleitendes Fenster (Tage)',
  'admin.scale.field.stepPerExtraFamily': 'Stufe pro weiterer Familie',
  'admin.scale.field.standingBonus': 'Standbonus',
  'admin.scale.field.achievementsForStanding': 'Erfolge für den Stand',
  'admin.scale.field.highBadgeThreshold': 'Schwelle für hohe Abzeichen',
  'admin.scale.field.highBadgesForStanding': 'Hohe Abzeichen für den Stand',
  'admin.scale.field.maxFactor': 'Maximaler Multiplikator',
  'admin.scale.levels.title': 'Obergrenze nach Stufe',
  'admin.scale.col.minLevel': 'Ab Stufe',
  'admin.scale.col.maxFactor': 'Maximaler Multiplikator',
  'admin.scale.levels.empty': 'Keine Obergrenze nach Stufe: Der maximale Multiplikator gilt für alle.',
  'admin.scale.levels.add': 'Stufe hinzufügen',
  'admin.scale.levels.remove': 'Stufe {level} entfernen',
  'admin.scale.minLevelFor': 'Mindeststufe — Zeile {row}',
  'admin.scale.maxFactorFor': 'Maximaler Multiplikator — Zeile {row}',
  'admin.scale.reset': 'Auf Standardwerte zurücksetzen',
  'admin.scale.save': 'Speichern',
  'admin.scale.saving': 'Wird gespeichert…',
  'admin.scale.saved': 'Skala gespeichert.',
  'admin.scale.invalid': 'Ungültige Skala: Ein Wert liegt außerhalb der Grenzen, eine Stufe ist doppelt oder überschreitet den maximalen Multiplikator.',
  'admin.scale.saveFailed': 'Speichern fehlgeschlagen: {error}',
  'admin.scale.resetDone': 'Standardwerte wiederhergestellt — speichern, um sie anzuwenden.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
