import type { AdminCatalogFragment } from './fragment';
import type fr from './kit-fr';

const f = {
  'admin.group.overview': 'Panoramica',
  'admin.group.people': 'Persone',
  'admin.group.exchanges': 'Scambi',
  'admin.group.content': 'Contenuti',
  'admin.group.moderation': 'Moderazione',
  'admin.group.growth': 'Crescita',
  'admin.group.platform': 'Piattaforma',

  'admin.kit.breadcrumb': 'Percorso di navigazione',
  'admin.kit.retry': 'Riprova',
  'admin.kit.error': 'Impossibile caricare questi dati al momento.',
  'admin.kit.denied': 'Questo blocco è riservato: il tuo ruolo non vi dà accesso.',
  'admin.kit.offline': 'Sei offline. I dati mostrati sono quelli già ricevuti; le azioni sono disattivate.',
  'admin.kit.cached': 'L’aggiornamento è fallito: questi sono gli ultimi dati ricevuti.',
  'admin.kit.loading': 'Caricamento…',
  'admin.kit.techId': 'Identificatore tecnico',
  'admin.kit.copy': 'Copia',
  'admin.kit.copied': 'Identificatore copiato',
  'admin.kit.copyFailed': 'Copia non riuscita',
  'admin.kit.cancel': 'Annulla',
  'admin.kit.confirm.motiveCount': '{count} di almeno {min} caratteri',
  'admin.kit.confirm.busy': 'In corso…',
  'admin.kit.chart.showTable': 'Vedi i dati',
  'admin.kit.chart.hideTable': 'Nascondi i dati',
  'admin.kit.chart.empty': 'Nessun dato nel periodo',
  'admin.kit.chart.legend': 'Legenda',
  'admin.kit.chart.others': 'Altri',
  'admin.kit.chart.columnLabel': 'Etichetta',
  'admin.kit.chart.columnValue': 'Valore',
  'admin.kit.chart.columnShare': 'Quota',
  'admin.kit.stat.up': 'in aumento di {value}',
  'admin.kit.stat.down': 'in calo di {value}',
  'admin.kit.stat.flat': 'stabile',
  'admin.kit.stat.trend': 'Andamento: da {from} a {to}',
  'admin.kit.meta.title': 'Metadati',
  'admin.kit.entity.deleted': 'eliminato',
  'admin.kit.entity.open': 'Apri la scheda di {name}',
  'admin.kit.hub.signedAs': 'Accesso come {role}',
  'admin.kit.refused.permission': 'Non hai il diritto di eseguire questa azione.',
  'admin.kit.refused.invalid': 'L’azione è stata rifiutata: le informazioni non sono valide.',
  'admin.kit.refused.conflict': 'L’azione è in conflitto con lo stato attuale: ricarica e riprova.',
  'admin.kit.refused.network': 'La rete ha avuto un problema: riprova tra un istante.',
  'admin.kit.refused.server': 'Il server non ha potuto eseguire l’azione.',
  'admin.kit.period.label': 'Periodo',
  'admin.kit.period.24h': '24 ore',
  'admin.kit.period.7d': '7 giorni',
  'admin.kit.period.30d': '30 giorni',
  'admin.kit.period.90d': '90 giorni',

  'admin.value.notProvided': 'Non indicato',
  'admin.value.unrecognized': 'Non riconosciuto',
  'admin.value.unknown': 'Sconosciuto',
  'admin.value.yes': 'Sì',
  'admin.value.no': 'No',
  'admin.value.noLanguage': 'Nessuna',
  'admin.value.languageUnknown': 'Lingua sconosciuta',
  'admin.value.countryUnknown': 'Paese sconosciuto',
  'admin.value.person.unnamed': 'Account senza nome',
  'admin.value.person.unknown': 'Persona sconosciuta',
  'admin.value.guest.unnamed': 'Ospite senza nome',
  'admin.value.conversation.untitled': 'Conversazione senza titolo',
  'admin.value.conversation.moreOne': '{names} e altri 1',
  'admin.value.conversation.moreMany': '{names} e altri {count}',
  'admin.value.shareLink.unnamed': 'Link senza nome',
  'admin.value.trackingLink.unnamed': 'Link di tracciamento senza nome',
  'admin.value.post.by': '{type} di {author}',
  'admin.value.report.titled': 'Segnalazione · {reason}',
  'admin.value.invitation.label': '{sender} → {recipient}',
  'admin.value.platform.ios': 'iPhone / iPad',
  'admin.value.platform.android': 'Android',
  'admin.value.platform.web': 'Browser',
  'admin.value.platform.desktop': 'Computer',
  'admin.value.platform.unknown': 'Piattaforma sconosciuta',

  'admin.enum.role.BIGBOSS': 'Creatore',
  'admin.enum.role.BIGBOSS.explain': 'Tutti i diritti, compresi i gesti sovrani.',
  'admin.enum.role.ADMIN': 'Amministratore',
  'admin.enum.role.ADMIN.explain': 'Gestisce la piattaforma, senza i gesti sovrani.',
  'admin.enum.role.MODERATOR': 'Moderatore',
  'admin.enum.role.MODERATOR.explain': 'Tratta le segnalazioni e modera i contenuti.',
  'admin.enum.role.AUDIT': 'Revisore',
  'admin.enum.role.AUDIT.explain': 'Legge i registri e le statistiche, non modifica nulla.',
  'admin.enum.role.ANALYST': 'Analista',
  'admin.enum.role.ANALYST.explain': 'Legge le statistiche della piattaforma.',
  'admin.enum.role.USER': 'Membro',
  'admin.enum.role.USER.explain': 'Usa Meeshy senza alcun diritto di amministrazione.',

  'admin.enum.accountState.active': 'Attivo',
  'admin.enum.accountState.deactivated': 'Disattivato',
  'admin.enum.accountState.deactivated.explain': 'Non può più accedere; i suoi dati sono conservati.',
  'admin.enum.accountState.deleted': 'Eliminato',
  'admin.enum.accountState.deleted.explain': 'Eliminazione morbida: l’account può essere ripristinato.',
  'admin.enum.accountState.banned': 'Bandito',
  'admin.enum.accountState.banned.explain': 'Escluso dalla piattaforma per la durata del bando.',
  'admin.enum.accountState.locked': 'Bloccato',
  'admin.enum.accountState.locked.explain': 'Troppi tentativi di accesso: l’account si sblocca da solo o da un amministratore.',

  'admin.enum.conversationType.direct': 'Conversazione privata',
  'admin.enum.conversationType.group': 'Gruppo',
  'admin.enum.conversationType.public': 'Pubblica',
  'admin.enum.conversationType.global': 'Spazio globale',
  'admin.enum.conversationType.broadcast': 'Canale di trasmissione',

  'admin.enum.conversationState.active': 'Attiva',
  'admin.enum.conversationState.archived': 'Archiviata',
  'admin.enum.conversationState.closed': 'Chiusa alla scrittura',
  'admin.enum.conversationState.closed.explain': 'I membri possono leggerla ma non vi scrivono più.',

  'admin.enum.participantRole.creator': 'Creatore',
  'admin.enum.participantRole.admin': 'Amministratore',
  'admin.enum.participantRole.moderator': 'Moderatore',
  'admin.enum.participantRole.member': 'Membro',

  'admin.enum.writeRole.everyone': 'Tutti',
  'admin.enum.writeRole.member': 'Membri',
  'admin.enum.writeRole.moderator': 'Moderatori e superiori',
  'admin.enum.writeRole.admin': 'Amministratori e superiori',
  'admin.enum.writeRole.creator': 'Solo il creatore',

  'admin.enum.encryption.e2ee': 'Cifrata end-to-end',
  'admin.enum.encryption.e2ee.explain': 'Il server non legge i messaggi: nessuna traduzione automatica.',
  'admin.enum.encryption.server': 'Cifrata sul server',
  'admin.enum.encryption.hybrid': 'Ibrida',
  'admin.enum.encryption.none': 'Non cifrata',

  'admin.enum.messageType.text': 'Testo',
  'admin.enum.messageType.image': 'Immagine',
  'admin.enum.messageType.file': 'File',
  'admin.enum.messageType.audio': 'Messaggio vocale',
  'admin.enum.messageType.video': 'Video',
  'admin.enum.messageType.location': 'Posizione',
  'admin.enum.messageType.system': 'Messaggio di sistema',

  'admin.enum.reportStatus.pending': 'In attesa',
  'admin.enum.reportStatus.under_review': 'In esame',
  'admin.enum.reportStatus.resolved': 'Risolta',
  'admin.enum.reportStatus.rejected': 'Respinta',
  'admin.enum.reportStatus.dismissed': 'Archiviata senza seguito',
  'admin.enum.reportStatus.dismissed.explain': 'Chiusa senza azione: questo caso non rientra nel tempo medio di risoluzione.',

  'admin.enum.reportType.spam': 'Indesiderato',
  'admin.enum.reportType.inappropriate': 'Contenuto inappropriato',
  'admin.enum.reportType.harassment': 'Molestie',
  'admin.enum.reportType.violence': 'Violenza',
  'admin.enum.reportType.hate_speech': 'Discorso d’odio',
  'admin.enum.reportType.fake_profile': 'Profilo falso',
  'admin.enum.reportType.impersonation': 'Furto d’identità',
  'admin.enum.reportType.other': 'Altro motivo',

  'admin.enum.reportedEntity.message': 'Messaggio',
  'admin.enum.reportedEntity.user': 'Membro',
  'admin.enum.reportedEntity.conversation': 'Conversazione',
  'admin.enum.reportedEntity.community': 'Community',
  'admin.enum.reportedEntity.post': 'Post',
  'admin.enum.reportedEntity.story': 'Story',
  'admin.enum.reportedEntity.comment': 'Commento',
  'admin.enum.reportedEntity.sound': 'Suono',

  'admin.enum.reportAction.none': 'Nessuna azione',
  'admin.enum.reportAction.warning_sent': 'Avvertimento inviato',
  'admin.enum.reportAction.content_removed': 'Contenuto rimosso',
  'admin.enum.reportAction.user_suspended': 'Membro sospeso',
  'admin.enum.reportAction.user_banned': 'Membro bandito',
  'admin.enum.reportAction.explain': 'Registrato dal moderatore: questa etichetta non innesca nulla da sola.',

  'admin.enum.broadcastStatus.DRAFT': 'Bozza',
  'admin.enum.broadcastStatus.TRANSLATING': 'Traduzione in corso',
  'admin.enum.broadcastStatus.TRANSLATING.explain': 'Le traduzioni del messaggio sono in preparazione.',
  'admin.enum.broadcastStatus.READY': 'Pronta per l’invio',
  'admin.enum.broadcastStatus.READY.explain': 'Tradotta: resta solo da inviarla.',
  'admin.enum.broadcastStatus.SENDING': 'Invio in corso',
  'admin.enum.broadcastStatus.SENT': 'Inviata',
  'admin.enum.broadcastStatus.FAILED': 'Fallita',

  'admin.enum.postType.POST': 'Post',
  'admin.enum.postType.REEL': 'Reel',
  'admin.enum.postType.STORY': 'Story',
  'admin.enum.postType.STATUS': 'Stato',

  'admin.enum.postVisibility.PUBLIC': 'Pubblica',
  'admin.enum.postVisibility.FRIENDS': 'Amici',
  'admin.enum.postVisibility.COMMUNITY': 'Community',
  'admin.enum.postVisibility.PRIVATE': 'Solo io',
  'admin.enum.postVisibility.PRIVATE.explain': 'Visibile solo al suo autore.',
  'admin.enum.postVisibility.EXCEPT': 'Amici tranne alcuni',
  'admin.enum.postVisibility.EXCEPT.explain': 'Visibile agli amici, tranne un elenco di persone escluse.',
  'admin.enum.postVisibility.ONLY': 'Alcuni amici',
  'admin.enum.postVisibility.ONLY.explain': 'Visibile solo a un elenco scelto di amici.',

  'admin.enum.postState.published': 'Pubblicata',
  'admin.enum.postState.deleted': 'Rimossa',
  'admin.enum.postState.deleted.explain': 'Rimossa dal suo autore o dalla moderazione.',
  'admin.enum.postState.expired': 'Scaduta',
  'admin.enum.postState.expired.explain': 'Una story scompare da sola alla fine della sua durata.',

  'admin.enum.invitationStatus.pending': 'In attesa',
  'admin.enum.invitationStatus.accepted': 'Accettata',
  'admin.enum.invitationStatus.rejected': 'Rifiutata',
  'admin.enum.invitationStatus.rejected.explain': 'Rifiutata dal destinatario o annullata da un amministratore.',

  'admin.enum.shareLinkState.active': 'Attivo',
  'admin.enum.shareLinkState.expired': 'Scaduto',
  'admin.enum.shareLinkState.exhausted': 'Quota raggiunta',
  'admin.enum.shareLinkState.exhausted.explain': 'Il numero massimo di utilizzi è raggiunto.',
  'admin.enum.shareLinkState.closed': 'Chiuso',
  'admin.enum.shareLinkState.closed.explain': 'Chiuso a mano: nessuno entra più da questo link.',

  'admin.enum.trackingLinkState.active': 'Attivo',
  'admin.enum.trackingLinkState.inactive': 'Disattivato',
  'admin.enum.trackingLinkState.inactive.explain': 'I visitatori non vengono più reindirizzati.',
  'admin.enum.trackingLinkState.expired': 'Scaduto',

  'admin.enum.trackingTarget.POST': 'Post',
  'admin.enum.trackingTarget.REEL': 'Reel',
  'admin.enum.trackingTarget.STORY': 'Story',
  'admin.enum.trackingTarget.STATUS': 'Stato',
  'admin.enum.trackingTarget.CONVERSATION': 'Conversazione',
  'admin.enum.trackingTarget.PROFILE': 'Profilo',
  'admin.enum.trackingTarget.EXTERNAL': 'Sito esterno',

  'admin.enum.redirectStatus.pending': 'In attesa di conferma',
  'admin.enum.redirectStatus.pending.explain': 'Il visitatore non ha ancora confermato il reindirizzamento.',
  'admin.enum.redirectStatus.confirmed': 'Reindirizzamento riuscito',
  'admin.enum.redirectStatus.failed': 'Reindirizzamento fallito',
  'admin.enum.redirectStatus.failed.explain': 'Il visitatore non ha raggiunto la destinazione.',

  'admin.enum.severity.LOW': 'Bassa',
  'admin.enum.severity.MEDIUM': 'Media',
  'admin.enum.severity.HIGH': 'Alta',
  'admin.enum.severity.CRITICAL': 'Critica',

  'admin.enum.securityStatus.SUCCESS': 'Riuscito',
  'admin.enum.securityStatus.FAILED': 'Fallito',
  'admin.enum.securityStatus.BLOCKED': 'Bloccato',

  'admin.enum.serviceStatus.up': 'Operativo',
  'admin.enum.serviceStatus.down': 'Fuori servizio',
  'admin.enum.serviceStatus.unknown': 'Sconosciuto',

  'admin.enum.circuitState.CLOSED': 'Normale',
  'admin.enum.circuitState.CLOSED.explain': 'Le chiamate passano.',
  'admin.enum.circuitState.OPEN': 'Interrotto',
  'admin.enum.circuitState.OPEN.explain': 'Le chiamate sono rifiutate mentre il servizio si riprende.',
  'admin.enum.circuitState.HALF_OPEN': 'In prova',
  'admin.enum.circuitState.HALF_OPEN.explain': 'Alcune chiamate passano per verificare che il servizio si sia ripreso.',

  'admin.enum.quality.excellent': 'Eccellente',
  'admin.enum.quality.good': 'Buona',
  'admin.enum.quality.fair': 'Media',
  'admin.enum.quality.poor': 'Scarsa',

  'admin.enum.activityBucket.0': 'Molto attivi',
  'admin.enum.activityBucket.1': 'Attivi',
  'admin.enum.activityBucket.2': 'Occasionali',
  'admin.enum.activityBucket.3': 'Inattivi',

  'admin.enum.friendStatus.pending': 'In attesa',
  'admin.enum.friendStatus.accepted': 'Amici',
  'admin.enum.friendStatus.rejected': 'Rifiutata',
  'admin.enum.friendStatus.blocked': 'Bloccato',

  'admin.enum.presence.online': 'Online',
  'admin.enum.presence.away': 'Assente',
  'admin.enum.presence.idle': 'Inattivo',
  'admin.enum.presence.offline': 'Offline',
  'admin.enum.presence.unknown': 'Non comunicata',
  'admin.enum.presence.unknown.explain': 'La presenza è condivisa solo con gli amici accettati e gli amministratori.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
