import type { AdminCatalogFragment } from './fragment';
import type fr from './kit-fr';

const f = {
  'admin.group.overview': 'Visão geral',
  'admin.group.people': 'Pessoas',
  'admin.group.exchanges': 'Trocas',
  'admin.group.content': 'Conteúdos',
  'admin.group.moderation': 'Moderação',
  'admin.group.growth': 'Crescimento',
  'admin.group.platform': 'Plataforma',

  'admin.kit.breadcrumb': 'Caminho de navegação',
  'admin.kit.retry': 'Tentar novamente',
  'admin.kit.error': 'Não foi possível carregar estes dados agora.',
  'admin.kit.denied': 'Este bloco é restrito: o seu papel não dá acesso a ele.',
  'admin.kit.offline': 'Você está offline. Os dados exibidos são os já recebidos; as ações estão desativadas.',
  'admin.kit.cached': 'A atualização falhou: estes são os últimos dados recebidos.',
  'admin.kit.loading': 'Carregando…',
  'admin.kit.techId': 'Identificador técnico',
  'admin.kit.copy': 'Copiar',
  'admin.kit.copied': 'Identificador copiado',
  'admin.kit.copyFailed': 'Não foi possível copiar',
  'admin.kit.cancel': 'Cancelar',
  'admin.kit.confirm.motiveCount': '{count} de {min} caracteres no mínimo',
  'admin.kit.confirm.busy': 'Em andamento…',
  'admin.kit.chart.showTable': 'Ver os dados',
  'admin.kit.chart.hideTable': 'Ocultar os dados',
  'admin.kit.chart.empty': 'Sem dados no período',
  'admin.kit.chart.legend': 'Legenda',
  'admin.kit.chart.others': 'Outros',
  'admin.kit.chart.columnLabel': 'Rótulo',
  'admin.kit.chart.columnValue': 'Valor',
  'admin.kit.chart.columnShare': 'Parte',
  'admin.kit.stat.up': 'em alta de {value}',
  'admin.kit.stat.down': 'em queda de {value}',
  'admin.kit.stat.flat': 'estável',
  'admin.kit.stat.trend': 'Tendência: de {from} a {to}',
  'admin.kit.meta.title': 'Metadados',
  'admin.kit.entity.deleted': 'excluído',
  'admin.kit.entity.open': 'Abrir a ficha de {name}',
  'admin.kit.hub.signedAs': 'Conectado como {role}',
  'admin.kit.refused.permission': 'Você não tem o direito de realizar esta ação.',
  'admin.kit.refused.invalid': 'A ação foi recusada: as informações são inválidas.',
  'admin.kit.refused.conflict': 'A ação entra em conflito com o estado atual: recarregue e tente novamente.',
  'admin.kit.refused.network': 'A rede falhou: tente novamente em instantes.',
  'admin.kit.refused.server': 'O servidor não conseguiu realizar a ação.',
  'admin.kit.period.label': 'Período',
  'admin.kit.period.24h': '24 horas',
  'admin.kit.period.7d': '7 dias',
  'admin.kit.period.30d': '30 dias',
  'admin.kit.period.90d': '90 dias',

  'admin.value.notProvided': 'Não informado',
  'admin.value.unrecognized': 'Não reconhecido',
  'admin.value.unknown': 'Desconhecido',
  'admin.value.yes': 'Sim',
  'admin.value.no': 'Não',
  'admin.value.noLanguage': 'Nenhum',
  'admin.value.languageUnknown': 'Idioma desconhecido',
  'admin.value.countryUnknown': 'País desconhecido',
  'admin.value.person.unnamed': 'Conta sem nome',
  'admin.value.person.unknown': 'Pessoa desconhecida',
  'admin.value.guest.unnamed': 'Convidado sem nome',
  'admin.value.conversation.untitled': 'Conversa sem título',
  'admin.value.conversation.moreOne': '{names} e mais 1',
  'admin.value.conversation.moreMany': '{names} e mais {count}',
  'admin.value.shareLink.unnamed': 'Link sem nome',
  'admin.value.trackingLink.unnamed': 'Link de acompanhamento sem nome',
  'admin.value.post.by': '{type} de {author}',
  'admin.value.report.titled': 'Denúncia · {reason}',
  'admin.value.invitation.label': '{sender} → {recipient}',
  'admin.value.platform.ios': 'iPhone / iPad',
  'admin.value.platform.android': 'Android',
  'admin.value.platform.web': 'Navegador',
  'admin.value.platform.desktop': 'Computador',
  'admin.value.platform.unknown': 'Plataforma desconhecida',

  'admin.enum.role.BIGBOSS': 'Criador',
  'admin.enum.role.BIGBOSS.explain': 'Todos os direitos, inclusive os gestos soberanos.',
  'admin.enum.role.ADMIN': 'Administrador',
  'admin.enum.role.ADMIN.explain': 'Gerencia a plataforma, sem os gestos soberanos.',
  'admin.enum.role.MODERATOR': 'Moderador',
  'admin.enum.role.MODERATOR.explain': 'Trata as denúncias e modera os conteúdos.',
  'admin.enum.role.AUDIT': 'Auditor',
  'admin.enum.role.AUDIT.explain': 'Lê os registros e as estatísticas, não altera nada.',
  'admin.enum.role.ANALYST': 'Analista',
  'admin.enum.role.ANALYST.explain': 'Lê as estatísticas da plataforma.',
  'admin.enum.role.USER': 'Membro',
  'admin.enum.role.USER.explain': 'Usa o Meeshy sem nenhum direito de administração.',

  'admin.enum.accountState.active': 'Ativo',
  'admin.enum.accountState.deactivated': 'Desativado',
  'admin.enum.accountState.deactivated.explain': 'Não pode mais entrar; os dados são mantidos.',
  'admin.enum.accountState.deleted': 'Excluído',
  'admin.enum.accountState.deleted.explain': 'Exclusão suave: a conta pode ser restaurada.',
  'admin.enum.accountState.banned': 'Banido',
  'admin.enum.accountState.banned.explain': 'Excluído da plataforma durante o banimento.',
  'admin.enum.accountState.locked': 'Bloqueado',
  'admin.enum.accountState.locked.explain': 'Muitas tentativas de login: a conta se desbloqueia sozinha ou por um administrador.',

  'admin.enum.conversationType.direct': 'Conversa privada',
  'admin.enum.conversationType.group': 'Grupo',
  'admin.enum.conversationType.public': 'Pública',
  'admin.enum.conversationType.global': 'Espaço global',
  'admin.enum.conversationType.broadcast': 'Canal de transmissão',

  'admin.enum.conversationState.active': 'Ativa',
  'admin.enum.conversationState.archived': 'Arquivada',
  'admin.enum.conversationState.closed': 'Fechada para escrita',
  'admin.enum.conversationState.closed.explain': 'Os membros podem lê-la, mas não escrevem mais nela.',

  'admin.enum.participantRole.creator': 'Criador',
  'admin.enum.participantRole.admin': 'Administrador',
  'admin.enum.participantRole.moderator': 'Moderador',
  'admin.enum.participantRole.member': 'Membro',

  'admin.enum.writeRole.everyone': 'Todos',
  'admin.enum.writeRole.member': 'Membros',
  'admin.enum.writeRole.moderator': 'Moderadores e acima',
  'admin.enum.writeRole.admin': 'Administradores e acima',
  'admin.enum.writeRole.creator': 'Somente o criador',

  'admin.enum.encryption.e2ee': 'Criptografada de ponta a ponta',
  'admin.enum.encryption.e2ee.explain': 'O servidor não lê as mensagens: sem tradução automática.',
  'admin.enum.encryption.server': 'Criptografada no servidor',
  'admin.enum.encryption.hybrid': 'Híbrida',
  'admin.enum.encryption.none': 'Sem criptografia',

  'admin.enum.messageType.text': 'Texto',
  'admin.enum.messageType.image': 'Imagem',
  'admin.enum.messageType.file': 'Arquivo',
  'admin.enum.messageType.audio': 'Mensagem de voz',
  'admin.enum.messageType.video': 'Vídeo',
  'admin.enum.messageType.location': 'Localização',
  'admin.enum.messageType.system': 'Mensagem do sistema',

  'admin.enum.reportStatus.pending': 'Pendente',
  'admin.enum.reportStatus.under_review': 'Em análise',
  'admin.enum.reportStatus.resolved': 'Resolvida',
  'admin.enum.reportStatus.rejected': 'Rejeitada',
  'admin.enum.reportStatus.dismissed': 'Arquivada sem ação',
  'admin.enum.reportStatus.dismissed.explain': 'Encerrada sem ação: este caso não entra no tempo médio de resolução.',

  'admin.enum.reportType.spam': 'Indesejado',
  'admin.enum.reportType.inappropriate': 'Conteúdo inadequado',
  'admin.enum.reportType.harassment': 'Assédio',
  'admin.enum.reportType.violence': 'Violência',
  'admin.enum.reportType.hate_speech': 'Discurso de ódio',
  'admin.enum.reportType.fake_profile': 'Perfil falso',
  'admin.enum.reportType.impersonation': 'Falsa identidade',
  'admin.enum.reportType.other': 'Outro motivo',

  'admin.enum.reportedEntity.message': 'Mensagem',
  'admin.enum.reportedEntity.user': 'Membro',
  'admin.enum.reportedEntity.conversation': 'Conversa',
  'admin.enum.reportedEntity.community': 'Comunidade',
  'admin.enum.reportedEntity.post': 'Publicação',
  'admin.enum.reportedEntity.story': 'Story',
  'admin.enum.reportedEntity.comment': 'Comentário',
  'admin.enum.reportedEntity.sound': 'Som',

  'admin.enum.reportAction.none': 'Nenhuma ação',
  'admin.enum.reportAction.warning_sent': 'Aviso enviado',
  'admin.enum.reportAction.content_removed': 'Conteúdo removido',
  'admin.enum.reportAction.user_suspended': 'Membro suspenso',
  'admin.enum.reportAction.user_banned': 'Membro banido',
  'admin.enum.reportAction.explain': 'Registrado pelo moderador: este rótulo não aciona nada por si só.',

  'admin.enum.broadcastStatus.DRAFT': 'Rascunho',
  'admin.enum.broadcastStatus.TRANSLATING': 'Tradução em andamento',
  'admin.enum.broadcastStatus.TRANSLATING.explain': 'As traduções da mensagem estão sendo preparadas.',
  'admin.enum.broadcastStatus.READY': 'Pronta para envio',
  'admin.enum.broadcastStatus.READY.explain': 'Traduzida: só falta enviá-la.',
  'admin.enum.broadcastStatus.SENDING': 'Envio em andamento',
  'admin.enum.broadcastStatus.SENT': 'Enviada',
  'admin.enum.broadcastStatus.FAILED': 'Falha',

  'admin.enum.postType.POST': 'Publicação',
  'admin.enum.postType.REEL': 'Reel',
  'admin.enum.postType.STORY': 'Story',
  'admin.enum.postType.STATUS': 'Status',

  'admin.enum.postVisibility.PUBLIC': 'Pública',
  'admin.enum.postVisibility.FRIENDS': 'Amigos',
  'admin.enum.postVisibility.COMMUNITY': 'Comunidade',
  'admin.enum.postVisibility.PRIVATE': 'Só eu',
  'admin.enum.postVisibility.PRIVATE.explain': 'Visível somente para o autor.',
  'admin.enum.postVisibility.EXCEPT': 'Amigos, exceto alguns',
  'admin.enum.postVisibility.EXCEPT.explain': 'Visível para os amigos, exceto uma lista de pessoas excluídas.',
  'admin.enum.postVisibility.ONLY': 'Alguns amigos',
  'admin.enum.postVisibility.ONLY.explain': 'Visível somente para uma lista escolhida de amigos.',

  'admin.enum.postState.published': 'Publicada',
  'admin.enum.postState.deleted': 'Removida',
  'admin.enum.postState.deleted.explain': 'Removida pelo autor ou pela moderação.',
  'admin.enum.postState.expired': 'Expirada',
  'admin.enum.postState.expired.explain': 'Uma story desaparece sozinha ao fim da sua duração.',

  'admin.enum.invitationStatus.pending': 'Pendente',
  'admin.enum.invitationStatus.accepted': 'Aceita',
  'admin.enum.invitationStatus.rejected': 'Recusada',
  'admin.enum.invitationStatus.rejected.explain': 'Recusada pelo destinatário ou cancelada por um administrador.',

  'admin.enum.shareLinkState.active': 'Ativo',
  'admin.enum.shareLinkState.expired': 'Expirado',
  'admin.enum.shareLinkState.exhausted': 'Cota atingida',
  'admin.enum.shareLinkState.exhausted.explain': 'O número máximo de usos foi atingido.',
  'admin.enum.shareLinkState.closed': 'Fechado',
  'admin.enum.shareLinkState.closed.explain': 'Fechado manualmente: ninguém mais entra por este link.',

  'admin.enum.trackingLinkState.active': 'Ativo',
  'admin.enum.trackingLinkState.inactive': 'Desativado',
  'admin.enum.trackingLinkState.inactive.explain': 'Os visitantes não são mais redirecionados.',
  'admin.enum.trackingLinkState.expired': 'Expirado',

  'admin.enum.trackingTarget.POST': 'Publicação',
  'admin.enum.trackingTarget.REEL': 'Reel',
  'admin.enum.trackingTarget.STORY': 'Story',
  'admin.enum.trackingTarget.STATUS': 'Status',
  'admin.enum.trackingTarget.CONVERSATION': 'Conversa',
  'admin.enum.trackingTarget.PROFILE': 'Perfil',
  'admin.enum.trackingTarget.EXTERNAL': 'Site externo',

  'admin.enum.redirectStatus.pending': 'Aguardando confirmação',
  'admin.enum.redirectStatus.pending.explain': 'O visitante ainda não confirmou o redirecionamento.',
  'admin.enum.redirectStatus.confirmed': 'Redirecionamento concluído',
  'admin.enum.redirectStatus.failed': 'Redirecionamento falhou',
  'admin.enum.redirectStatus.failed.explain': 'O visitante não chegou ao destino.',

  'admin.enum.severity.LOW': 'Baixa',
  'admin.enum.severity.MEDIUM': 'Média',
  'admin.enum.severity.HIGH': 'Alta',
  'admin.enum.severity.CRITICAL': 'Crítica',

  'admin.enum.securityStatus.SUCCESS': 'Bem-sucedido',
  'admin.enum.securityStatus.FAILED': 'Falhou',
  'admin.enum.securityStatus.BLOCKED': 'Bloqueado',

  'admin.enum.serviceStatus.up': 'Operacional',
  'admin.enum.serviceStatus.down': 'Fora de serviço',
  'admin.enum.serviceStatus.unknown': 'Desconhecido',

  'admin.enum.circuitState.CLOSED': 'Normal',
  'admin.enum.circuitState.CLOSED.explain': 'As chamadas passam.',
  'admin.enum.circuitState.OPEN': 'Cortado',
  'admin.enum.circuitState.OPEN.explain': 'As chamadas são recusadas enquanto o serviço se recupera.',
  'admin.enum.circuitState.HALF_OPEN': 'Em teste',
  'admin.enum.circuitState.HALF_OPEN.explain': 'Algumas chamadas passam para verificar se o serviço se recuperou.',

  'admin.enum.quality.excellent': 'Excelente',
  'admin.enum.quality.good': 'Boa',
  'admin.enum.quality.fair': 'Média',
  'admin.enum.quality.poor': 'Ruim',

  'admin.enum.activityBucket.0': 'Muito ativos',
  'admin.enum.activityBucket.1': 'Ativos',
  'admin.enum.activityBucket.2': 'Ocasionais',
  'admin.enum.activityBucket.3': 'Inativos',

  'admin.enum.friendStatus.pending': 'Pendente',
  'admin.enum.friendStatus.accepted': 'Amigos',
  'admin.enum.friendStatus.rejected': 'Recusada',
  'admin.enum.friendStatus.blocked': 'Bloqueado',

  'admin.enum.presence.online': 'Online',
  'admin.enum.presence.away': 'Ausente',
  'admin.enum.presence.idle': 'Inativo',
  'admin.enum.presence.offline': 'Offline',
  'admin.enum.presence.unknown': 'Não informada',
  'admin.enum.presence.unknown.explain': 'A presença só é compartilhada com amigos aceitos e administradores.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
