import type { AdminCatalogFragment } from './fragment';
import type fr from './kit-fr';

const f = {
  'admin.group.overview': 'Overview',
  'admin.group.people': 'People',
  'admin.group.exchanges': 'Exchanges',
  'admin.group.content': 'Content',
  'admin.group.moderation': 'Moderation',
  'admin.group.growth': 'Growth',
  'admin.group.platform': 'Platform',

  'admin.kit.breadcrumb': 'Breadcrumb',
  'admin.kit.notReady': 'This section is coming',
  'admin.kit.notReady.hint': 'It is not yet available in this version of the administration.',
  'admin.kit.retry': 'Try again',
  'admin.kit.error': 'These data cannot be loaded right now.',
  'admin.kit.denied': 'This block is restricted: your role does not give access to it.',
  'admin.kit.offline': 'You are offline. The data shown is what was already received; actions are disabled.',
  'admin.kit.cached': 'The update failed: this is the last data received.',
  'admin.kit.loading': 'Loading…',
  'admin.kit.techId': 'Technical identifier',
  'admin.kit.copy': 'Copy',
  'admin.kit.copied': 'Identifier copied',
  'admin.kit.copyFailed': 'Copy failed',
  'admin.kit.cancel': 'Cancel',
  'admin.kit.confirm.motiveCount': '{count} of {min} characters minimum',
  'admin.kit.confirm.busy': 'In progress…',
  'admin.kit.chart.showTable': 'View the data',
  'admin.kit.chart.hideTable': 'Hide the data',
  'admin.kit.chart.empty': 'No data for this period',
  'admin.kit.chart.legend': 'Legend',
  'admin.kit.chart.others': 'Others',
  'admin.kit.chart.columnLabel': 'Label',
  'admin.kit.chart.columnValue': 'Value',
  'admin.kit.chart.columnShare': 'Share',
  'admin.kit.stat.up': 'up {value}',
  'admin.kit.stat.down': 'down {value}',
  'admin.kit.stat.flat': 'stable',
  'admin.kit.stat.trend': 'Trend: from {from} to {to}',
  'admin.kit.meta.title': 'Metadata',
  'admin.kit.entity.deleted': 'deleted',
  'admin.kit.entity.open': 'Open the record of {name}',
  'admin.kit.hub.signedAs': 'Signed in as {role}',
  'admin.kit.refused.permission': 'You are not allowed to perform this action.',
  'admin.kit.refused.invalid': 'The action was refused: the information is invalid.',
  'admin.kit.refused.conflict': 'The action conflicts with the current state: reload, then try again.',
  'admin.kit.refused.network': 'The network failed: try again in a moment.',
  'admin.kit.refused.server': 'The server could not perform the action.',
  'admin.kit.period.label': 'Period',
  'admin.kit.period.24h': '24 hours',
  'admin.kit.period.7d': '7 days',
  'admin.kit.period.30d': '30 days',
  'admin.kit.period.90d': '90 days',

  'admin.value.notProvided': 'Not provided',
  'admin.value.unrecognized': 'Not recognized',
  'admin.value.unknown': 'Unknown',
  'admin.value.never': 'Never',
  'admin.value.yes': 'Yes',
  'admin.value.no': 'No',
  'admin.value.system': 'System',
  'admin.value.noLanguage': 'None',
  'admin.value.languageUnknown': 'Unknown language',
  'admin.value.countryUnknown': 'Unknown country',
  'admin.value.person.unnamed': 'Unnamed account',
  'admin.value.person.unknown': 'Unknown person',
  'admin.value.guest.unnamed': 'Unnamed guest',
  'admin.value.conversation.untitled': 'Untitled conversation',
  'admin.value.conversation.moreOne': '{names} and 1 other',
  'admin.value.conversation.moreMany': '{names} and {count} others',
  'admin.value.shareLink.unnamed': 'Unnamed link',
  'admin.value.trackingLink.unnamed': 'Unnamed tracking link',
  'admin.value.post.by': '{type} by {author}',
  'admin.value.report.titled': 'Report · {reason}',
  'admin.value.invitation.label': '{sender} → {recipient}',
  'admin.value.platform.ios': 'iPhone / iPad',
  'admin.value.platform.android': 'Android',
  'admin.value.platform.web': 'Browser',
  'admin.value.platform.desktop': 'Computer',
  'admin.value.platform.unknown': 'Unknown platform',

  'admin.enum.role.BIGBOSS': 'Creator',
  'admin.enum.role.BIGBOSS.explain': 'Every right, including the sovereign actions.',
  'admin.enum.role.ADMIN': 'Administrator',
  'admin.enum.role.ADMIN.explain': 'Runs the platform, without the sovereign actions.',
  'admin.enum.role.MODERATOR': 'Moderator',
  'admin.enum.role.MODERATOR.explain': 'Handles reports and moderates content.',
  'admin.enum.role.AUDIT': 'Auditor',
  'admin.enum.role.AUDIT.explain': 'Reads the logs and the statistics, changes nothing.',
  'admin.enum.role.ANALYST': 'Analyst',
  'admin.enum.role.ANALYST.explain': 'Reads the platform statistics.',
  'admin.enum.role.USER': 'Member',
  'admin.enum.role.USER.explain': 'Uses Meeshy without any administration right.',

  'admin.enum.accountState.active': 'Active',
  'admin.enum.accountState.deactivated': 'Deactivated',
  'admin.enum.accountState.deactivated.explain': 'Can no longer sign in; the data is kept.',
  'admin.enum.accountState.deleted': 'Deleted',
  'admin.enum.accountState.deleted.explain': 'Soft deletion: the account can be restored.',
  'admin.enum.accountState.banned': 'Banned',
  'admin.enum.accountState.banned.explain': 'Excluded from the platform for the length of the ban.',
  'admin.enum.accountState.locked': 'Locked',
  'admin.enum.accountState.locked.explain': 'Too many sign-in attempts: the account unlocks by itself or through an administrator.',

  'admin.enum.conversationType.direct': 'Private conversation',
  'admin.enum.conversationType.group': 'Group',
  'admin.enum.conversationType.public': 'Public',
  'admin.enum.conversationType.global': 'Global space',
  'admin.enum.conversationType.broadcast': 'Broadcast channel',

  'admin.enum.conversationState.active': 'Active',
  'admin.enum.conversationState.archived': 'Archived',
  'admin.enum.conversationState.closed': 'Closed to writing',
  'admin.enum.conversationState.closed.explain': 'Members can read it but can no longer write in it.',

  'admin.enum.participantRole.creator': 'Creator',
  'admin.enum.participantRole.admin': 'Administrator',
  'admin.enum.participantRole.moderator': 'Moderator',
  'admin.enum.participantRole.member': 'Member',

  'admin.enum.writeRole.everyone': 'Everyone',
  'admin.enum.writeRole.member': 'Members',
  'admin.enum.writeRole.moderator': 'Moderators and above',
  'admin.enum.writeRole.admin': 'Administrators and above',
  'admin.enum.writeRole.creator': 'Creator only',

  'admin.enum.encryption.e2ee': 'End-to-end encrypted',
  'admin.enum.encryption.e2ee.explain': 'The server does not read the messages: no automatic translation.',
  'admin.enum.encryption.server': 'Encrypted on the server',
  'admin.enum.encryption.hybrid': 'Hybrid',
  'admin.enum.encryption.none': 'Not encrypted',

  'admin.enum.messageType.text': 'Text',
  'admin.enum.messageType.image': 'Image',
  'admin.enum.messageType.file': 'File',
  'admin.enum.messageType.audio': 'Voice message',
  'admin.enum.messageType.video': 'Video',
  'admin.enum.messageType.location': 'Location',
  'admin.enum.messageType.system': 'System message',

  'admin.enum.reportStatus.pending': 'Pending',
  'admin.enum.reportStatus.under_review': 'Under review',
  'admin.enum.reportStatus.resolved': 'Resolved',
  'admin.enum.reportStatus.rejected': 'Rejected',
  'admin.enum.reportStatus.dismissed': 'Dismissed',
  'admin.enum.reportStatus.dismissed.explain': 'Closed without action: this case is left out of the average resolution time.',

  'admin.enum.reportType.spam': 'Spam',
  'admin.enum.reportType.inappropriate': 'Inappropriate content',
  'admin.enum.reportType.harassment': 'Harassment',
  'admin.enum.reportType.violence': 'Violence',
  'admin.enum.reportType.hate_speech': 'Hate speech',
  'admin.enum.reportType.fake_profile': 'Fake profile',
  'admin.enum.reportType.impersonation': 'Impersonation',
  'admin.enum.reportType.other': 'Other reason',

  'admin.enum.reportedEntity.message': 'Message',
  'admin.enum.reportedEntity.user': 'Member',
  'admin.enum.reportedEntity.conversation': 'Conversation',
  'admin.enum.reportedEntity.community': 'Community',
  'admin.enum.reportedEntity.post': 'Post',
  'admin.enum.reportedEntity.story': 'Story',
  'admin.enum.reportedEntity.comment': 'Comment',
  'admin.enum.reportedEntity.sound': 'Sound',

  'admin.enum.reportAction.none': 'No action',
  'admin.enum.reportAction.warning_sent': 'Warning sent',
  'admin.enum.reportAction.content_removed': 'Content removed',
  'admin.enum.reportAction.user_suspended': 'Member suspended',
  'admin.enum.reportAction.user_banned': 'Member banned',
  'admin.enum.reportAction.explain': 'Recorded by the moderator: this label triggers nothing by itself.',

  'admin.enum.broadcastStatus.DRAFT': 'Draft',
  'admin.enum.broadcastStatus.TRANSLATING': 'Translating',
  'admin.enum.broadcastStatus.TRANSLATING.explain': 'The translations of the message are being prepared.',
  'admin.enum.broadcastStatus.READY': 'Ready to send',
  'admin.enum.broadcastStatus.READY.explain': 'Translated: it only remains to send it.',
  'admin.enum.broadcastStatus.SENDING': 'Sending',
  'admin.enum.broadcastStatus.SENT': 'Sent',
  'admin.enum.broadcastStatus.FAILED': 'Failed',

  'admin.enum.postType.POST': 'Post',
  'admin.enum.postType.REEL': 'Reel',
  'admin.enum.postType.STORY': 'Story',
  'admin.enum.postType.STATUS': 'Status',

  'admin.enum.postVisibility.PUBLIC': 'Public',
  'admin.enum.postVisibility.FRIENDS': 'Friends',
  'admin.enum.postVisibility.COMMUNITY': 'Community',
  'admin.enum.postVisibility.PRIVATE': 'Only me',
  'admin.enum.postVisibility.PRIVATE.explain': 'Visible only to its author.',
  'admin.enum.postVisibility.EXCEPT': 'Friends except some',
  'admin.enum.postVisibility.EXCEPT.explain': 'Visible to friends, except a list of excluded people.',
  'admin.enum.postVisibility.ONLY': 'Some friends',
  'admin.enum.postVisibility.ONLY.explain': 'Visible only to a chosen list of friends.',

  'admin.enum.postState.published': 'Published',
  'admin.enum.postState.deleted': 'Removed',
  'admin.enum.postState.deleted.explain': 'Removed by its author or by moderation.',
  'admin.enum.postState.expired': 'Expired',
  'admin.enum.postState.expired.explain': 'A story disappears on its own at the end of its lifetime.',

  'admin.enum.invitationStatus.pending': 'Pending',
  'admin.enum.invitationStatus.accepted': 'Accepted',
  'admin.enum.invitationStatus.rejected': 'Declined',
  'admin.enum.invitationStatus.rejected.explain': 'Declined by its recipient or cancelled by an administrator.',

  'admin.enum.shareLinkState.active': 'Active',
  'admin.enum.shareLinkState.expired': 'Expired',
  'admin.enum.shareLinkState.exhausted': 'Quota reached',
  'admin.enum.shareLinkState.exhausted.explain': 'The maximum number of uses is reached.',
  'admin.enum.shareLinkState.closed': 'Closed',
  'admin.enum.shareLinkState.closed.explain': 'Closed by hand: nobody enters through this link any more.',

  'admin.enum.trackingLinkState.active': 'Active',
  'admin.enum.trackingLinkState.inactive': 'Deactivated',
  'admin.enum.trackingLinkState.inactive.explain': 'Visitors are no longer redirected.',
  'admin.enum.trackingLinkState.expired': 'Expired',

  'admin.enum.trackingTarget.POST': 'Post',
  'admin.enum.trackingTarget.REEL': 'Reel',
  'admin.enum.trackingTarget.STORY': 'Story',
  'admin.enum.trackingTarget.STATUS': 'Status',
  'admin.enum.trackingTarget.CONVERSATION': 'Conversation',
  'admin.enum.trackingTarget.PROFILE': 'Profile',
  'admin.enum.trackingTarget.EXTERNAL': 'External site',

  'admin.enum.redirectStatus.pending': 'Awaiting confirmation',
  'admin.enum.redirectStatus.pending.explain': 'The visitor has not confirmed the redirection yet.',
  'admin.enum.redirectStatus.confirmed': 'Redirection succeeded',
  'admin.enum.redirectStatus.failed': 'Redirection failed',
  'admin.enum.redirectStatus.failed.explain': 'The visitor did not reach the destination.',

  'admin.enum.severity.LOW': 'Low',
  'admin.enum.severity.MEDIUM': 'Medium',
  'admin.enum.severity.HIGH': 'High',
  'admin.enum.severity.CRITICAL': 'Critical',

  'admin.enum.securityStatus.SUCCESS': 'Succeeded',
  'admin.enum.securityStatus.FAILED': 'Failed',
  'admin.enum.securityStatus.BLOCKED': 'Blocked',

  'admin.enum.serviceStatus.up': 'Operational',
  'admin.enum.serviceStatus.down': 'Out of service',
  'admin.enum.serviceStatus.unknown': 'Unknown',

  'admin.enum.circuitState.CLOSED': 'Normal',
  'admin.enum.circuitState.CLOSED.explain': 'Calls go through.',
  'admin.enum.circuitState.OPEN': 'Open',
  'admin.enum.circuitState.OPEN.explain': 'Calls are refused while the service recovers.',
  'admin.enum.circuitState.HALF_OPEN': 'Testing',
  'admin.enum.circuitState.HALF_OPEN.explain': 'A few calls go through to check that the service has recovered.',

  'admin.enum.quality.excellent': 'Excellent',
  'admin.enum.quality.good': 'Good',
  'admin.enum.quality.fair': 'Fair',
  'admin.enum.quality.poor': 'Poor',

  'admin.enum.activityBucket.0': 'Very active',
  'admin.enum.activityBucket.1': 'Active',
  'admin.enum.activityBucket.2': 'Occasional',
  'admin.enum.activityBucket.3': 'Inactive',

  'admin.enum.friendStatus.pending': 'Pending',
  'admin.enum.friendStatus.accepted': 'Friends',
  'admin.enum.friendStatus.rejected': 'Declined',
  'admin.enum.friendStatus.blocked': 'Blocked',

  'admin.enum.presence.online': 'Online',
  'admin.enum.presence.away': 'Away',
  'admin.enum.presence.idle': 'Idle',
  'admin.enum.presence.offline': 'Offline',
  'admin.enum.presence.unknown': 'Not shared',
  'admin.enum.presence.unknown.explain': 'Presence is only shared with accepted friends and administrators.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
