/**
 * LE FRAGMENT « KIT » (#8876) — les libellés du kit d’administration et de sa
 * bibliothèque d’interprétation : groupes du menu, valeurs dites en mots,
 * énumérations nommées, gestes communs. Préfixes exclusifs : `admin.kit.`,
 * `admin.group.`, `admin.value.`, `admin.enum.`.
 */
const f = {
  'admin.group.overview': 'Vue d’ensemble',
  'admin.group.people': 'Personnes',
  'admin.group.exchanges': 'Échanges',
  'admin.group.content': 'Contenus',
  'admin.group.moderation': 'Modération',
  'admin.group.growth': 'Croissance',
  'admin.group.platform': 'Plateforme',

  'admin.kit.breadcrumb': 'Fil d’Ariane',
  'admin.kit.notReady': 'Cette section arrive',
  'admin.kit.notReady.hint': 'Elle n’est pas encore disponible dans cette version de l’administration.',
  'admin.kit.retry': 'Réessayer',
  'admin.kit.error': 'Impossible de charger ces données pour le moment.',
  'admin.kit.denied': 'Ce bloc est réservé : votre rôle n’y donne pas accès.',
  'admin.kit.offline': 'Vous êtes hors ligne. Les données affichées sont celles déjà reçues ; les gestes sont désactivés.',
  'admin.kit.cached': 'La mise à jour a échoué : ces données sont les dernières reçues.',
  'admin.kit.loading': 'Chargement…',
  'admin.kit.techId': 'Identifiant technique',
  'admin.kit.copy': 'Copier',
  'admin.kit.copied': 'Identifiant copié',
  'admin.kit.copyFailed': 'Copie impossible',
  'admin.kit.cancel': 'Annuler',
  'admin.kit.confirm.motiveCount': '{count} sur {min} caractères minimum',
  'admin.kit.confirm.busy': 'En cours…',
  'admin.kit.chart.showTable': 'Voir les données',
  'admin.kit.chart.hideTable': 'Masquer les données',
  'admin.kit.chart.empty': 'Aucune donnée sur la période',
  'admin.kit.chart.legend': 'Légende',
  'admin.kit.chart.others': 'Autres',
  'admin.kit.chart.columnLabel': 'Libellé',
  'admin.kit.chart.columnValue': 'Valeur',
  'admin.kit.chart.columnShare': 'Part',
  'admin.kit.stat.up': 'en hausse de {value}',
  'admin.kit.stat.down': 'en baisse de {value}',
  'admin.kit.stat.flat': 'stable',
  'admin.kit.stat.trend': 'Tendance : de {from} à {to}',
  'admin.kit.meta.title': 'Métadonnées',
  'admin.kit.entity.deleted': 'supprimé',
  'admin.kit.entity.open': 'Ouvrir la fiche de {name}',
  'admin.kit.hub.signedAs': 'Connecté en tant que {role}',
  'admin.kit.refused.permission': 'Vous n’avez pas le droit d’effectuer ce geste.',
  'admin.kit.refused.invalid': 'Le geste a été refusé : les informations sont invalides.',
  'admin.kit.refused.conflict': 'Le geste entre en conflit avec l’état actuel : rechargez puis réessayez.',
  'admin.kit.refused.network': 'Le réseau a échoué : réessayez dans un instant.',
  'admin.kit.refused.server': 'Le serveur n’a pas pu effectuer le geste.',
  'admin.kit.period.label': 'Période',
  'admin.kit.period.24h': '24 heures',
  'admin.kit.period.7d': '7 jours',
  'admin.kit.period.30d': '30 jours',
  'admin.kit.period.90d': '90 jours',

  'admin.value.notProvided': 'Non renseigné',
  'admin.value.unrecognized': 'Non reconnu',
  'admin.value.unknown': 'Inconnu',
  'admin.value.never': 'Jamais',
  'admin.value.yes': 'Oui',
  'admin.value.no': 'Non',
  'admin.value.system': 'Système',
  'admin.value.noLanguage': 'Aucune',
  'admin.value.languageUnknown': 'Langue inconnue',
  'admin.value.countryUnknown': 'Pays inconnu',
  'admin.value.person.unnamed': 'Compte sans nom',
  'admin.value.person.unknown': 'Personne inconnue',
  'admin.value.guest.unnamed': 'Invité sans nom',
  'admin.value.conversation.untitled': 'Conversation sans titre',
  'admin.value.conversation.moreOne': '{names} et 1 autre',
  'admin.value.conversation.moreMany': '{names} et {count} autres',
  'admin.value.shareLink.unnamed': 'Lien sans nom',
  'admin.value.trackingLink.unnamed': 'Lien de suivi sans nom',
  'admin.value.post.by': '{type} de {author}',
  'admin.value.report.titled': 'Signalement · {reason}',
  'admin.value.invitation.label': '{sender} → {recipient}',
  'admin.value.platform.ios': 'iPhone / iPad',
  'admin.value.platform.android': 'Android',
  'admin.value.platform.web': 'Navigateur',
  'admin.value.platform.desktop': 'Ordinateur',
  'admin.value.platform.unknown': 'Plateforme inconnue',

  'admin.enum.role.BIGBOSS': 'Créateur',
  'admin.enum.role.BIGBOSS.explain': 'Tous les droits, y compris les gestes souverains.',
  'admin.enum.role.ADMIN': 'Administrateur',
  'admin.enum.role.ADMIN.explain': 'Gère la plateforme, sans les gestes souverains.',
  'admin.enum.role.MODERATOR': 'Modérateur',
  'admin.enum.role.MODERATOR.explain': 'Traite les signalements et modère les contenus.',
  'admin.enum.role.AUDIT': 'Auditeur',
  'admin.enum.role.AUDIT.explain': 'Lit les journaux et les statistiques, ne modifie rien.',
  'admin.enum.role.ANALYST': 'Analyste',
  'admin.enum.role.ANALYST.explain': 'Lit les statistiques de la plateforme.',
  'admin.enum.role.USER': 'Membre',
  'admin.enum.role.USER.explain': 'Utilise Meeshy sans droit d’administration.',

  'admin.enum.accountState.active': 'Actif',
  'admin.enum.accountState.deactivated': 'Désactivé',
  'admin.enum.accountState.deactivated.explain': 'Ne peut plus se connecter ; ses données sont conservées.',
  'admin.enum.accountState.deleted': 'Supprimé',
  'admin.enum.accountState.deleted.explain': 'Suppression douce : le compte peut être restauré.',
  'admin.enum.accountState.banned': 'Banni',
  'admin.enum.accountState.banned.explain': 'Exclu de la plateforme pour la durée du bannissement.',
  'admin.enum.accountState.locked': 'Verrouillé',
  'admin.enum.accountState.locked.explain': 'Trop de tentatives de connexion : le compte se déverrouille seul ou par un administrateur.',

  'admin.enum.conversationType.direct': 'Conversation privée',
  'admin.enum.conversationType.group': 'Groupe',
  'admin.enum.conversationType.public': 'Publique',
  'admin.enum.conversationType.global': 'Espace global',
  'admin.enum.conversationType.broadcast': 'Canal de diffusion',

  'admin.enum.conversationState.active': 'Active',
  'admin.enum.conversationState.archived': 'Archivée',
  'admin.enum.conversationState.closed': 'Fermée à l’écriture',
  'admin.enum.conversationState.closed.explain': 'Les membres peuvent la lire mais n’y écrivent plus.',

  'admin.enum.participantRole.creator': 'Créateur',
  'admin.enum.participantRole.admin': 'Administrateur',
  'admin.enum.participantRole.moderator': 'Modérateur',
  'admin.enum.participantRole.member': 'Membre',

  'admin.enum.writeRole.everyone': 'Tout le monde',
  'admin.enum.writeRole.member': 'Membres',
  'admin.enum.writeRole.moderator': 'Modérateurs et plus',
  'admin.enum.writeRole.admin': 'Administrateurs et plus',
  'admin.enum.writeRole.creator': 'Créateur seulement',

  'admin.enum.encryption.e2ee': 'Chiffrée de bout en bout',
  'admin.enum.encryption.e2ee.explain': 'Le serveur ne lit pas les messages : pas de traduction automatique.',
  'admin.enum.encryption.server': 'Chiffrée sur le serveur',
  'admin.enum.encryption.hybrid': 'Hybride',
  'admin.enum.encryption.none': 'Non chiffrée',

  'admin.enum.messageType.text': 'Texte',
  'admin.enum.messageType.image': 'Image',
  'admin.enum.messageType.file': 'Fichier',
  'admin.enum.messageType.audio': 'Message vocal',
  'admin.enum.messageType.video': 'Vidéo',
  'admin.enum.messageType.location': 'Position',
  'admin.enum.messageType.system': 'Message système',

  'admin.enum.reportStatus.pending': 'En attente',
  'admin.enum.reportStatus.under_review': 'En cours d’examen',
  'admin.enum.reportStatus.resolved': 'Résolu',
  'admin.enum.reportStatus.rejected': 'Rejeté',
  'admin.enum.reportStatus.dismissed': 'Classé sans suite',
  'admin.enum.reportStatus.dismissed.explain': 'Clôturé sans action : ce dossier n’entre pas dans le délai moyen de résolution.',

  'admin.enum.reportType.spam': 'Indésirable',
  'admin.enum.reportType.inappropriate': 'Contenu inapproprié',
  'admin.enum.reportType.harassment': 'Harcèlement',
  'admin.enum.reportType.violence': 'Violence',
  'admin.enum.reportType.hate_speech': 'Discours de haine',
  'admin.enum.reportType.fake_profile': 'Faux profil',
  'admin.enum.reportType.impersonation': 'Usurpation d’identité',
  'admin.enum.reportType.other': 'Autre motif',

  'admin.enum.reportedEntity.message': 'Message',
  'admin.enum.reportedEntity.user': 'Membre',
  'admin.enum.reportedEntity.conversation': 'Conversation',
  'admin.enum.reportedEntity.community': 'Communauté',
  'admin.enum.reportedEntity.post': 'Publication',
  'admin.enum.reportedEntity.story': 'Story',
  'admin.enum.reportedEntity.comment': 'Commentaire',
  'admin.enum.reportedEntity.sound': 'Son',

  'admin.enum.reportAction.none': 'Aucune action',
  'admin.enum.reportAction.warning_sent': 'Avertissement envoyé',
  'admin.enum.reportAction.content_removed': 'Contenu retiré',
  'admin.enum.reportAction.user_suspended': 'Membre suspendu',
  'admin.enum.reportAction.user_banned': 'Membre banni',
  'admin.enum.reportAction.explain': 'Consigné par le modérateur : ce libellé ne déclenche rien par lui-même.',

  'admin.enum.broadcastStatus.DRAFT': 'Brouillon',
  'admin.enum.broadcastStatus.TRANSLATING': 'Traduction en cours',
  'admin.enum.broadcastStatus.TRANSLATING.explain': 'Les traductions du message sont en cours de préparation.',
  'admin.enum.broadcastStatus.READY': 'Prête à l’envoi',
  'admin.enum.broadcastStatus.READY.explain': 'Traduite : il ne reste qu’à l’envoyer.',
  'admin.enum.broadcastStatus.SENDING': 'Envoi en cours',
  'admin.enum.broadcastStatus.SENT': 'Envoyée',
  'admin.enum.broadcastStatus.FAILED': 'Échec',

  'admin.enum.postType.POST': 'Publication',
  'admin.enum.postType.REEL': 'Reel',
  'admin.enum.postType.STORY': 'Story',
  'admin.enum.postType.STATUS': 'Statut',

  'admin.enum.postVisibility.PUBLIC': 'Publique',
  'admin.enum.postVisibility.FRIENDS': 'Amis',
  'admin.enum.postVisibility.COMMUNITY': 'Communauté',
  'admin.enum.postVisibility.PRIVATE': 'Moi seul',
  'admin.enum.postVisibility.PRIVATE.explain': 'Visible seulement par son auteur.',
  'admin.enum.postVisibility.EXCEPT': 'Amis sauf certains',
  'admin.enum.postVisibility.EXCEPT.explain': 'Visible par les amis, sauf une liste de personnes exclues.',
  'admin.enum.postVisibility.ONLY': 'Certains amis',
  'admin.enum.postVisibility.ONLY.explain': 'Visible seulement par une liste choisie d’amis.',

  'admin.enum.postState.published': 'Publiée',
  'admin.enum.postState.deleted': 'Retirée',
  'admin.enum.postState.deleted.explain': 'Retirée par son auteur ou par la modération.',
  'admin.enum.postState.expired': 'Expirée',
  'admin.enum.postState.expired.explain': 'Une story disparaît d’elle-même à la fin de sa durée de vie.',

  'admin.enum.invitationStatus.pending': 'En attente',
  'admin.enum.invitationStatus.accepted': 'Acceptée',
  'admin.enum.invitationStatus.rejected': 'Refusée',
  'admin.enum.invitationStatus.rejected.explain': 'Refusée par son destinataire ou annulée par un administrateur.',

  'admin.enum.shareLinkState.active': 'Actif',
  'admin.enum.shareLinkState.expired': 'Expiré',
  'admin.enum.shareLinkState.exhausted': 'Quota atteint',
  'admin.enum.shareLinkState.exhausted.explain': 'Le nombre maximal d’utilisations est atteint.',
  'admin.enum.shareLinkState.closed': 'Fermé',
  'admin.enum.shareLinkState.closed.explain': 'Fermé à la main : plus personne n’entre par ce lien.',

  'admin.enum.trackingLinkState.active': 'Actif',
  'admin.enum.trackingLinkState.inactive': 'Désactivé',
  'admin.enum.trackingLinkState.inactive.explain': 'Les visiteurs ne sont plus redirigés.',
  'admin.enum.trackingLinkState.expired': 'Expiré',

  'admin.enum.trackingTarget.POST': 'Publication',
  'admin.enum.trackingTarget.REEL': 'Reel',
  'admin.enum.trackingTarget.STORY': 'Story',
  'admin.enum.trackingTarget.STATUS': 'Statut',
  'admin.enum.trackingTarget.CONVERSATION': 'Conversation',
  'admin.enum.trackingTarget.PROFILE': 'Profil',
  'admin.enum.trackingTarget.EXTERNAL': 'Site externe',

  'admin.enum.redirectStatus.pending': 'En attente de confirmation',
  'admin.enum.redirectStatus.pending.explain': 'Le visiteur n’a pas encore confirmé la redirection.',
  'admin.enum.redirectStatus.confirmed': 'Redirection réussie',
  'admin.enum.redirectStatus.failed': 'Redirection échouée',
  'admin.enum.redirectStatus.failed.explain': 'Le visiteur n’a pas atteint la destination.',

  'admin.enum.severity.LOW': 'Faible',
  'admin.enum.severity.MEDIUM': 'Moyenne',
  'admin.enum.severity.HIGH': 'Élevée',
  'admin.enum.severity.CRITICAL': 'Critique',

  'admin.enum.securityStatus.SUCCESS': 'Réussi',
  'admin.enum.securityStatus.FAILED': 'Échoué',
  'admin.enum.securityStatus.BLOCKED': 'Bloqué',

  'admin.enum.serviceStatus.up': 'Opérationnel',
  'admin.enum.serviceStatus.down': 'Hors service',
  'admin.enum.serviceStatus.unknown': 'Inconnu',

  'admin.enum.circuitState.CLOSED': 'Normal',
  'admin.enum.circuitState.CLOSED.explain': 'Les appels passent.',
  'admin.enum.circuitState.OPEN': 'Coupé',
  'admin.enum.circuitState.OPEN.explain': 'Les appels sont refusés le temps que le service se rétablisse.',
  'admin.enum.circuitState.HALF_OPEN': 'En essai',
  'admin.enum.circuitState.HALF_OPEN.explain': 'Quelques appels passent pour vérifier que le service est rétabli.',

  'admin.enum.quality.excellent': 'Excellente',
  'admin.enum.quality.good': 'Bonne',
  'admin.enum.quality.fair': 'Moyenne',
  'admin.enum.quality.poor': 'Mauvaise',

  'admin.enum.activityBucket.0': 'Très actifs',
  'admin.enum.activityBucket.1': 'Actifs',
  'admin.enum.activityBucket.2': 'Occasionnels',
  'admin.enum.activityBucket.3': 'Inactifs',

  'admin.enum.friendStatus.pending': 'En attente',
  'admin.enum.friendStatus.accepted': 'Amis',
  'admin.enum.friendStatus.rejected': 'Refusée',
  'admin.enum.friendStatus.blocked': 'Bloqué',

  'admin.enum.presence.online': 'En ligne',
  'admin.enum.presence.away': 'Absent',
  'admin.enum.presence.idle': 'Inactif',
  'admin.enum.presence.offline': 'Hors ligne',
  'admin.enum.presence.unknown': 'Non communiquée',
  'admin.enum.presence.unknown.explain': 'La présence n’est partagée qu’avec les amis acceptés et les administrateurs.',
} as const;

export default f;
