/**
 * LE FRAGMENT « liens » DU CATALOGUE D’ADMINISTRATION (#8876, #6729) — les
 * libellés des liens de partage (`admin.shareLink.`), des liens de suivi
 * (`admin.tracking.`) et des demandes de contact (`admin.invitation.`). Préfixes
 * exclusifs : voir `admin-catalog-fragments.test.ts`.
 */
const f = {
  // ── Demandes de contact ────────────────────────────────────────────────────
  'admin.invitation.subtitle': 'Les demandes d’ami que les membres s’envoient : qui a demandé à qui, et où en est chaque demande.',
  'admin.invitation.list.caption': 'Demandes de contact',
  'admin.invitation.list.count': '{count} demandes',
  'admin.invitation.list.empty': 'Aucune demande de contact',
  'admin.invitation.list.emptyHint': 'Les demandes d’ami envoyées entre membres apparaîtront ici.',
  'admin.invitation.list.filteredEmpty': 'Aucune demande ne correspond à ces filtres',
  'admin.invitation.list.onSender': 'Demandes envoyées par {name}',
  'admin.invitation.list.onSenderGeneric': 'Demandes envoyées par un seul membre',
  'admin.invitation.list.onSenderReset': 'Voir toutes les demandes',
  'admin.invitation.filter.status': 'Statut',
  'admin.invitation.col.sender': 'Expéditeur',
  'admin.invitation.col.receiver': 'Destinataire',
  'admin.invitation.col.status': 'Statut',
  'admin.invitation.col.message': 'Message joint',
  'admin.invitation.col.sent': 'Envoyée',
  'admin.invitation.col.updated': 'Mise à jour',
  'admin.invitation.message.yes': 'Avec un message',
  'admin.invitation.message.no': 'Sans message',
  'admin.invitation.stat.total': 'Demandes au total',
  'admin.invitation.stat.pending': 'En attente',
  'admin.invitation.stat.pending.caption': 'attendent une réponse',
  'admin.invitation.stat.accepted': 'Acceptées',
  'admin.invitation.stat.rejected': 'Refusées',
  'admin.invitation.stat.recent': 'Envoyées en 7 jours',
  'admin.invitation.stat.rate': 'Taux d’acceptation',
  'admin.invitation.stat.rate.caption': 'des demandes sont acceptées',
  'admin.invitation.chart.title': 'Demandes des 7 derniers jours',
  'admin.invitation.chart.sent': 'Envoyées',
  'admin.invitation.chart.accepted': 'Acceptées',
  'admin.invitation.chart.rejected': 'Refusées',
  'admin.invitation.chart.summary': 'Jour le plus chargé : {day}, avec {count} demandes envoyées',
  'admin.invitation.chart.quiet': 'Aucune demande envoyée sur les 7 derniers jours',
  'admin.invitation.fiche.loading': 'Chargement de la demande',
  'admin.invitation.fiche.notFound': 'Cette demande n’existe plus',
  'admin.invitation.fiche.notFoundHint': 'Elle a pu disparaître avec l’un des deux comptes.',
  'admin.invitation.fiche.back': 'Retour aux demandes',
  'admin.invitation.fiche.secondary': 'Demande de contact envoyée {when}',
  'admin.invitation.strip.sent': 'Envoyée',
  'admin.invitation.strip.updated': 'Dernière mise à jour',
  'admin.invitation.strip.message': 'Message',
  'admin.invitation.section.people': 'Les deux membres',
  'admin.invitation.section.message': 'Message joint',
  'admin.invitation.person.sender': 'Expéditeur',
  'admin.invitation.person.receiver': 'Destinataire',
  'admin.invitation.person.senderRequests': 'Toutes les demandes envoyées par ce membre',
  'admin.invitation.message.none': 'Aucun message n’accompagne cette demande.',
  'admin.invitation.meta.status': 'Statut',
  'admin.invitation.meta.sent': 'Envoyée',
  'admin.invitation.meta.updated': 'Dernière mise à jour',
  'admin.invitation.meta.updated.explain': 'Date du dernier changement de la demande, par son destinataire ou par un administrateur.',
  'admin.invitation.explain.pending': 'Le destinataire n’a pas encore répondu.',
  'admin.invitation.explain.accepted': 'Les deux membres sont amis.',
  'admin.invitation.gesture.cancel': 'Annuler la demande',
  'admin.invitation.confirm.cancel.title': 'Annuler cette demande ?',
  'admin.invitation.confirm.cancel.body':
    'La demande passera à « Refusée » : {receiver} ne la verra plus en attente. Aucune amitié n’est créée. Le geste est consigné au journal d’audit.',
  'admin.invitation.done.cancelled': 'Demande annulée',

  // ── Liens de partage ───────────────────────────────────────────────────────
  'admin.shareLink.subtitle': 'Les liens qui ouvrent une conversation à des invités : qui les a créés, combien de personnes sont entrées, jusqu’à quand ils valent.',
  'admin.shareLink.list.caption': 'Liens de partage',
  'admin.shareLink.list.count': '{count} liens',
  'admin.shareLink.list.empty': 'Aucun lien de partage',
  'admin.shareLink.list.emptyHint': 'Les liens que les membres créent pour inviter à une conversation apparaîtront ici.',
  'admin.shareLink.list.filteredEmpty': 'Aucun lien ne correspond à ces filtres',
  'admin.shareLink.search.label': 'Rechercher un lien par son nom',
  'admin.shareLink.filter.openness': 'Ouverture',
  'admin.shareLink.filter.open': 'Ouverts',
  'admin.shareLink.filter.closed': 'Fermés',
  'admin.shareLink.col.link': 'Lien',
  'admin.shareLink.col.conversation': 'Conversation',
  'admin.shareLink.col.creator': 'Créé par',
  'admin.shareLink.col.usage': 'Utilisations',
  'admin.shareLink.col.guests': 'Invités arrivés',
  'admin.shareLink.col.state': 'État',
  'admin.shareLink.col.expires': 'Expire',
  'admin.shareLink.col.created': 'Création',
  'admin.shareLink.expires.never': 'N’expire jamais',
  'admin.shareLink.usage.limited': '{used} sur {max}',
  'admin.shareLink.usage.unlimited': '{used}, sans limite',
  'admin.shareLink.fiche.loading': 'Chargement du lien',
  'admin.shareLink.fiche.notFound': 'Ce lien n’existe plus',
  'admin.shareLink.fiche.notFoundHint': 'Il a pu disparaître avec sa conversation.',
  'admin.shareLink.fiche.back': 'Retour aux liens',
  'admin.shareLink.fiche.secondary': 'Créé par {creator} {when}',
  'admin.shareLink.strip.uses': 'Utilisations',
  'admin.shareLink.strip.visits': 'Visites',
  'admin.shareLink.strip.guests': 'Invités arrivés',
  'admin.shareLink.strip.concurrent': 'Connectés en ce moment',
  'admin.shareLink.strip.sessions': 'Sessions uniques',
  'admin.shareLink.section.conversation': 'Conversation',
  'admin.shareLink.section.permissions': 'Ce que les invités peuvent faire',
  'admin.shareLink.section.requirements': 'Ce que le lien exige',
  'admin.shareLink.section.restrictions': 'Restrictions d’accès',
  'admin.shareLink.section.guests': 'Invités récents',
  'admin.shareLink.conversation.none': 'La conversation de ce lien n’est plus disponible.',
  'admin.shareLink.description': 'Description',
  'admin.shareLink.restrict.countries': 'Pays autorisés',
  'admin.shareLink.restrict.languages': 'Langues autorisées',
  'admin.shareLink.restrict.none': 'Aucune restriction',
  'admin.shareLink.guests.empty': 'Personne n’est encore entré par ce lien.',
  'admin.shareLink.guest.present': 'Présent',
  'admin.shareLink.guest.left': 'Parti',
  'admin.shareLink.meta.state': 'État',
  'admin.shareLink.meta.expires': 'Expiration',
  'admin.shareLink.meta.expires.explain': 'Passée cette date, plus personne n’entre par ce lien.',
  'admin.shareLink.meta.created': 'Création',
  'admin.shareLink.meta.updated': 'Dernière modification',
  'admin.shareLink.meta.creator': 'Créé par',
  'admin.shareLink.perm.messages.yes': 'Les invités peuvent écrire des messages',
  'admin.shareLink.perm.messages.no': 'Les invités ne peuvent pas écrire de messages',
  'admin.shareLink.perm.files.yes': 'Les invités peuvent envoyer des fichiers',
  'admin.shareLink.perm.files.no': 'Les invités ne peuvent pas envoyer de fichiers',
  'admin.shareLink.perm.images.yes': 'Les invités peuvent envoyer des images',
  'admin.shareLink.perm.images.no': 'Les invités ne peuvent pas envoyer d’images',
  'admin.shareLink.perm.history.yes': 'Les invités peuvent lire l’historique de la conversation',
  'admin.shareLink.perm.history.no': 'Les invités ne voient que ce qui est écrit après leur arrivée',
  'admin.shareLink.perm.unknown': 'Non communiqué',
  'admin.shareLink.req.account.yes': 'Un compte Meeshy est exigé pour entrer',
  'admin.shareLink.req.account.no': 'Aucun compte n’est exigé : on peut entrer en invité',
  'admin.shareLink.req.nickname.yes': 'Les invités doivent choisir un pseudonyme',
  'admin.shareLink.req.nickname.no': 'Aucun pseudonyme n’est exigé',
  'admin.shareLink.req.email.yes': 'Les invités doivent donner une adresse e-mail',
  'admin.shareLink.req.email.no': 'Aucune adresse e-mail n’est exigée',
  'admin.shareLink.req.birthday.yes': 'Les invités doivent donner leur date de naissance',
  'admin.shareLink.req.birthday.no': 'Aucune date de naissance n’est exigée',
  'admin.shareLink.gesture.close': 'Fermer le lien',
  'admin.shareLink.gesture.reopen': 'Rouvrir le lien',
  'admin.shareLink.gesture.reveal': 'Révéler le secret',
  'admin.shareLink.confirm.close.title': 'Fermer ce lien ?',
  'admin.shareLink.confirm.close.body':
    'Les invités arrivés par ce lien perdent l’accès à la conversation tout de suite, et plus personne n’entre par lui. Le lien n’est pas supprimé : vous pouvez le rouvrir, mais les invités retirés ne reviennent pas d’eux-mêmes. Le geste est consigné au journal d’audit.',
  'admin.shareLink.confirm.reopen.title': 'Rouvrir ce lien ?',
  'admin.shareLink.confirm.reopen.body':
    'Le lien redevient joignable avec son adresse actuelle : de nouveaux arrivants peuvent entrer. Les invités retirés à la fermeture ne sont pas rétablis. Le geste est consigné au journal d’audit.',
  'admin.shareLink.confirm.reveal.title': 'Révéler le secret de ce lien ?',
  'admin.shareLink.confirm.reveal.body':
    'Les clés qui vont s’afficher ouvrent la conversation : quiconque les détient y entre. Elles ne s’affichent qu’une fois et ne sont conservées nulle part dans l’administration. Ce geste est réservé au créateur de la plateforme ; il exige un motif écrit et il est consigné au journal d’audit.',
  'admin.shareLink.confirm.reveal.motive': 'Motif (consigné au journal d’audit)',
  'admin.shareLink.done.closed': 'Lien fermé',
  'admin.shareLink.done.reopened': 'Lien rouvert',
  'admin.shareLink.done.revealed': 'Secret révélé : il ne s’affichera pas une seconde fois',
  'admin.shareLink.secret.title': 'Secret du lien',
  'admin.shareLink.secret.notice': 'Copiez-le maintenant : cette fenêtre est la seule où il s’affiche, et il ne reste dans aucune mémoire de l’administration.',
  'admin.shareLink.secret.linkId': 'Clé du lien',
  'admin.shareLink.secret.identifier': 'Identifiant du lien',
  'admin.shareLink.secret.copy': 'Copier',
  'admin.shareLink.secret.copied': 'Clé copiée',
  'admin.shareLink.secret.close': 'Fermer',

  // ── Liens de suivi ─────────────────────────────────────────────────────────
  'admin.tracking.subtitle': 'Les campagnes : chaque lien suivi, ce qu’il vise, qui l’a posé et ce qu’il rapporte en clics.',
  'admin.tracking.list.caption': 'Liens de suivi',
  'admin.tracking.list.count': '{count} liens',
  'admin.tracking.list.empty': 'Aucun lien de suivi',
  'admin.tracking.list.emptyHint': 'Les liens de suivi créés par les membres apparaîtront ici avec leurs clics.',
  'admin.tracking.list.filteredEmpty': 'Aucun lien de suivi ne correspond à ces filtres',
  'admin.tracking.list.onCreator': 'Liens créés par {name}',
  'admin.tracking.list.onCreatorGeneric': 'Liens créés par un seul membre',
  'admin.tracking.list.onCreatorReset': 'Voir tous les liens',
  'admin.tracking.search.label': 'Rechercher par nom, campagne ou adresse',
  'admin.tracking.filter.state': 'État',
  'admin.tracking.filter.active': 'Actifs',
  'admin.tracking.filter.inactive': 'Désactivés',
  'admin.tracking.filter.target': 'Cible',
  'admin.tracking.col.link': 'Lien',
  'admin.tracking.col.campaign': 'Campagne',
  'admin.tracking.col.target': 'Cible',
  'admin.tracking.col.creator': 'Créé par',
  'admin.tracking.col.clicks': 'Clics',
  'admin.tracking.col.unique': 'Visiteurs uniques',
  'admin.tracking.col.lastClick': 'Dernier clic',
  'admin.tracking.col.state': 'État',
  'admin.tracking.col.created': 'Création',
  'admin.tracking.utm.campaign': 'Campagne',
  'admin.tracking.utm.source': 'Source',
  'admin.tracking.utm.medium': 'Support',
  'admin.tracking.utm.line': '{label} : {value}',
  'admin.tracking.lastClick.never': 'Aucun clic',
  'admin.tracking.fiche.loading': 'Chargement du lien de suivi',
  'admin.tracking.fiche.notFound': 'Ce lien de suivi n’existe plus',
  'admin.tracking.fiche.notFoundHint': 'Il a pu être supprimé.',
  'admin.tracking.fiche.back': 'Retour aux liens de suivi',
  'admin.tracking.strip.clicks': 'Clics',
  'admin.tracking.strip.unique': 'Visiteurs uniques',
  'admin.tracking.strip.confirmed': 'Redirections réussies',
  'admin.tracking.strip.lastClick': 'Dernier clic',
  'admin.tracking.section.destination': 'Destination',
  'admin.tracking.section.campaign': 'Campagne',
  'admin.tracking.section.target': 'Cible',
  'admin.tracking.section.stats': 'Ce que rapportent les clics',
  'admin.tracking.section.recent': 'Derniers clics',
  'admin.tracking.dest.original': 'Adresse de destination',
  'admin.tracking.dest.original.explain': 'Là où arrivent les visiteurs.',
  'admin.tracking.dest.short': 'Adresse courte',
  'admin.tracking.dest.short.explain': 'L’adresse à partager : elle redirige vers la destination et compte chaque clic.',
  'admin.tracking.copy': 'Copier',
  'admin.tracking.copied': 'Adresse copiée',
  'admin.tracking.target.kind': 'Genre de cible',
  'admin.tracking.target.entity': 'Cible',
  'admin.tracking.target.conversation': 'Posé depuis la conversation',
  'admin.tracking.target.none': 'Ce lien mène à un site externe : aucune entité de Meeshy n’est visée.',
  'admin.tracking.chart.days': 'Clics par jour',
  'admin.tracking.chart.days.summary': 'Jour le plus chargé : {day}, avec {count} clics',
  'admin.tracking.chart.days.quiet': 'Aucun clic sur la période',
  'admin.tracking.chart.top': 'Le plus fréquent : {label} ({count})',
  'admin.tracking.chart.none': 'Aucune donnée',
  'admin.tracking.chart.countries': 'Pays des visiteurs',
  'admin.tracking.chart.devices': 'Appareils',
  'admin.tracking.chart.browsers': 'Navigateurs',
  'admin.tracking.chart.systems': 'Systèmes d’exploitation',
  'admin.tracking.chart.social': 'Sources sociales',
  'admin.tracking.chart.referrers': 'Sites d’origine',
  'admin.tracking.chart.redirects': 'Redirections',
  'admin.tracking.recent.caption': 'Les derniers clics sur ce lien',
  'admin.tracking.recent.empty': 'Aucun clic enregistré pour ce lien.',
  'admin.tracking.recent.privacy': 'Ni adresse IP ni empreinte d’appareil : ces informations ne sont pas montrées ici.',
  'admin.tracking.recent.when': 'Quand',
  'admin.tracking.recent.where': 'Lieu',
  'admin.tracking.recent.device': 'Appareil',
  'admin.tracking.recent.browser': 'Navigateur',
  'admin.tracking.recent.system': 'Système',
  'admin.tracking.recent.referrer': 'Provenance',
  'admin.tracking.recent.redirect': 'Redirection',
  'admin.tracking.recent.direct': 'Accès direct',
  'admin.tracking.recent.place': '{city}, {country}',
  'admin.tracking.device.mobile': 'Mobile',
  'admin.tracking.device.tablet': 'Tablette',
  'admin.tracking.device.desktop': 'Ordinateur',
  'admin.tracking.meta.state': 'État',
  'admin.tracking.meta.expires': 'Expiration',
  'admin.tracking.meta.expires.explain': 'Passée cette date, le lien ne redirige plus.',
  'admin.tracking.meta.creator': 'Créé par',
  'admin.tracking.meta.created': 'Création',
  'admin.tracking.meta.lastClick': 'Dernier clic',
  'admin.tracking.expires.never': 'N’expire jamais',
  'admin.tracking.gesture.deactivate': 'Désactiver le lien',
  'admin.tracking.gesture.reactivate': 'Réactiver le lien',
  'admin.tracking.confirm.deactivate.title': 'Désactiver ce lien de suivi ?',
  'admin.tracking.confirm.deactivate.body':
    'Les visiteurs qui ouvrent ce lien ne sont plus redirigés vers la destination. Les statistiques déjà collectées sont conservées, et vous pouvez le réactiver. Le geste est consigné au journal d’audit.',
  'admin.tracking.confirm.reactivate.title': 'Réactiver ce lien de suivi ?',
  'admin.tracking.confirm.reactivate.body':
    'Le lien redirige de nouveau les visiteurs vers sa destination et recommence à compter les clics. Le geste est consigné au journal d’audit.',
  'admin.tracking.confirm.motive': 'Motif (facultatif, consigné au journal d’audit)',
  'admin.tracking.done.deactivated': 'Lien de suivi désactivé',
  'admin.tracking.done.reactivated': 'Lien de suivi réactivé',
} as const;

export default f;
