import type { AdminCatalogFragment } from './fragment';
import type fr from './liens-fr';

/* TEXTE PROVISOIRE (#8876) : le texte anglais tient lieu de traduction en attendant la passe de
   traduction du lot « liens ». Les clés sont celles du fragment français, ni plus ni moins. */
const f = {
  // ── Contact requests ───────────────────────────────────────────────────────
  'admin.invitation.subtitle': 'o friend requests members send each other: who asked whom, and where each request stands.',
  'admin.invitation.list.caption': 'Pedidos de contato',
  'admin.invitation.list.count': '{count} pedidos',
  'admin.invitation.list.empty': 'No contact requests',
  'admin.invitation.list.emptyHint': 'Les pedidos d’ami envoyées entre membres apparaîtront ici.',
  'admin.invitation.list.filteredEmpty': 'No request matches these filters',
  'admin.invitation.list.onSender': 'Requests sent por {name}',
  'admin.invitation.list.onSenderGeneric': 'Requests sent por a single member',
  'admin.invitation.list.onSenderReset': 'Voir toutes les pedidos',
  'admin.invitation.filter.status': 'Estado',
  'admin.invitation.col.sender': 'Remetente',
  'admin.invitation.col.receiver': 'Destinatário',
  'admin.invitation.col.status': 'Estado',
  'admin.invitation.col.message': 'Mensagem anexada',
  'admin.invitation.col.sent': 'Enviado',
  'admin.invitation.col.updated': 'Atualizado',
  'admin.invitation.message.yes': 'With a message',
  'admin.invitation.message.no': 'No message',
  'admin.invitation.stat.total': 'Requests em total',
  'admin.invitation.stat.pending': 'Pendente',
  'admin.invitation.stat.pending.caption': 'are waiting for an answer',
  'admin.invitation.stat.accepted': 'Aceito',
  'admin.invitation.stat.rejected': 'Recusado',
  'admin.invitation.stat.recent': 'Sent em 7 days',
  'admin.invitation.stat.rate': 'Acceptance rate',
  'admin.invitation.stat.rate.caption': 'des pedidos sont acceptées',
  'admin.invitation.chart.title': 'Requests over o/a last 7 days',
  'admin.invitation.chart.sent': 'Enviado',
  'admin.invitation.chart.accepted': 'Aceito',
  'admin.invitation.chart.rejected': 'Recusado',
  'admin.invitation.chart.summary': 'Jour le plus chargé : {day}, avec {count} pedidos envoyées',
  'admin.invitation.chart.quiet': 'No request sent over o/a last 7 days',
  'admin.invitation.fiche.loading': 'Loading o/a request',
  'admin.invitation.fiche.notFound': 'This request no longer exists',
  'admin.invitation.fiche.notFoundHint': 'It may have disappeared along with one de the two accounts.',
  'admin.invitation.fiche.back': 'Back para requests',
  'admin.invitation.fiche.secondary': 'Pedido de contacto',
  'admin.invitation.strip.sent': 'Enviado',
  'admin.invitation.strip.updated': 'Última atualização',
  'admin.invitation.strip.message': 'Mensagem',
  'admin.invitation.section.people': 'o two members',
  'admin.invitation.section.message': 'Mensagem anexada',
  'admin.invitation.person.sender': 'Remetente',
  'admin.invitation.person.receiver': 'Destinatário',
  'admin.invitation.person.senderRequests': 'All requests sent por this member',
  'admin.invitation.message.none': 'No message comes with this request.',
  'admin.invitation.meta.status': 'Estado',
  'admin.invitation.meta.sent': 'Enviado',
  'admin.invitation.meta.updated': 'Última atualização',
  'admin.invitation.meta.updated.explain': 'Date de the last change to the request, by its recipient or by an administrator.',
  'admin.invitation.explain.pending': 'o recipient has not answered yet.',
  'admin.invitation.explain.accepted': 'o two members are friends.',
  'admin.invitation.gesture.cancel': 'Cancel o/a request',
  'admin.invitation.confirm.cancel.title': 'Cancel this request?',
  'admin.invitation.confirm.cancel.body': 'The request will become “Declined”: {receiver} will no longer see it as pending. No friendship is created. The gesture is recorded em the audit log.',
  'admin.invitation.done.cancelled': 'Request cancelled',

  // ── Share links ────────────────────────────────────────────────────────────
  'admin.shareLink.subtitle': 'entradas',
  'admin.shareLink.list.caption': 'Ligações',
  'admin.shareLink.list.count': '{count} links',
  'admin.shareLink.list.empty': 'No share links',
  'admin.shareLink.list.emptyHint': 'The links members create para invite people para a conversation will appear here.',
  'admin.shareLink.list.filteredEmpty': 'No link matches these filters',
  'admin.shareLink.search.label': 'Search a link por its name',
  'admin.shareLink.filter.openness': 'Openness',
  'admin.shareLink.filter.open': 'Abrir',
  'admin.shareLink.filter.closed': 'Fechado',
  'admin.shareLink.col.link': 'Ligação',
  'admin.shareLink.col.conversation': 'Conversa',
  'admin.shareLink.col.creator': 'Criado por',
  'admin.shareLink.col.usage': 'Usos',
  'admin.shareLink.col.guests': 'Convidados que entraram',
  'admin.shareLink.col.state': 'Estado',
  'admin.shareLink.col.expires': 'Expires',
  'admin.shareLink.col.created': 'Criado',
  'admin.shareLink.expires.never': 'Nunca expira',
  'admin.shareLink.usage.limited': '{used} de {max}',
  'admin.shareLink.usage.unlimited': '{used}, no limit',
  'admin.shareLink.fiche.loading': 'Loading o/a link',
  'admin.shareLink.fiche.notFound': 'This link no longer exists',
  'admin.shareLink.fiche.notFoundHint': 'It may have disappeared along with its conversation.',
  'admin.shareLink.fiche.back': 'Back para links',
  'admin.shareLink.fiche.secondary': 'Created por {creator} {when}',
  'admin.shareLink.strip.uses': 'Usos',
  'admin.shareLink.strip.visits': 'Visits',
  'admin.shareLink.strip.guests': 'Convidados que entraram',
  'admin.shareLink.strip.concurrent': 'Connected right now',
  'admin.shareLink.strip.sessions': 'Unique sessions',
  'admin.shareLink.section.conversation': 'Conversa',
  'admin.shareLink.section.permissions': 'What guests can do',
  'admin.shareLink.section.requirements': 'What o/a link requires',
  'admin.shareLink.section.restrictions': 'Access restrictions',
  'admin.shareLink.section.guests': 'Recent guests',
  'admin.shareLink.conversation.none': 'This link’s conversation is no longer available.',
  'admin.shareLink.description': 'Descrição',
  'admin.shareLink.restrict.countries': 'Allowed countries',
  'admin.shareLink.restrict.languages': 'Allowed languages',
  'admin.shareLink.restrict.none': 'No restriction',
  'admin.shareLink.guests.empty': 'Nobody has come em through this link yet.',
  'admin.shareLink.guest.present': 'Presente',
  'admin.shareLink.guest.left': 'Gone',
  'admin.shareLink.meta.state': 'Estado',
  'admin.shareLink.meta.expires': 'Expiração',
  'admin.shareLink.meta.expires.explain': 'After this date, nobody can come em through this link.',
  'admin.shareLink.meta.created': 'Criado',
  'admin.shareLink.meta.updated': 'Última modificação',
  'admin.shareLink.meta.creator': 'Criado por',
  'admin.shareLink.perm.messages.yes': 'Guests can write messages',
  'admin.shareLink.perm.messages.no': 'Guests cannot write messages',
  'admin.shareLink.perm.files.yes': 'Guests can send files',
  'admin.shareLink.perm.files.no': 'Guests cannot send files',
  'admin.shareLink.perm.images.yes': 'Guests can send images',
  'admin.shareLink.perm.images.no': 'Guests cannot send images',
  'admin.shareLink.perm.history.yes': 'Guests can read o/a conversation history',
  'admin.shareLink.perm.history.no': 'Guests only see what is written after they arrive',
  'admin.shareLink.perm.unknown': 'Não fornecido',
  'admin.shareLink.req.account.yes': 'A Meeshy account is required para come in',
  'admin.shareLink.req.account.no': 'No account is required: guests can come em without one',
  'admin.shareLink.req.nickname.yes': 'Guests must choose a nickname',
  'admin.shareLink.req.nickname.no': 'No nickname is required',
  'admin.shareLink.req.email.yes': 'Guests must give an e-mail address',
  'admin.shareLink.req.email.no': 'No e-mail address is required',
  'admin.shareLink.req.birthday.yes': 'Guests must give their date de birth',
  'admin.shareLink.req.birthday.no': 'No date de birth is required',
  'admin.shareLink.gesture.close': 'Close o/a link',
  'admin.shareLink.gesture.reopen': 'Reopen o/a link',
  'admin.shareLink.gesture.reveal': 'Reveal o/a secret',
  'admin.shareLink.confirm.close.title': 'Close this link?',
  'admin.shareLink.confirm.close.body': 'Guests who came em through this link lose access to the conversation right away, and nobody else can come in through it. The link is not deleted: you can reopen it, but removed guests do not come back on their own. The gesture is recorded in the audit log.',
  'admin.shareLink.confirm.reopen.title': 'Reopen this link?',
  'admin.shareLink.confirm.reopen.body': 'The link becomes reachable again with its current address: new arrivals can come in. Guests removed when it was closed are not restored. The gesture is recorded em the audit log.',
  'admin.shareLink.confirm.reveal.title': 'Reveal this link’s secret?',
  'admin.shareLink.confirm.reveal.body': 'The keys about to be shown open the conversation: anyone who holds them can come in. They are shown once and kept nowhere em the administration. This gesture is reserved for the platform creator; it requires a written reason and is recorded in the audit log.',
  'admin.shareLink.confirm.reveal.motive': 'Motivo',
  'admin.shareLink.done.closed': 'Link closed',
  'admin.shareLink.done.reopened': 'Link reopened',
  'admin.shareLink.done.revealed': 'Secret revealed: it will not be shown a second time',
  'admin.shareLink.secret.title': 'Link secret',
  'admin.shareLink.secret.notice': 'Copy it now: this window is the only place it is shown, and it stays em no memory of the administration.',
  'admin.shareLink.secret.linkId': 'Link key',
  'admin.shareLink.secret.identifier': 'Link identifier',
  'admin.shareLink.secret.copy': 'Copiar',
  'admin.shareLink.secret.copied': 'Key copied',
  'admin.shareLink.secret.close': 'Fechar',

  // ── Tracking links ─────────────────────────────────────────────────────────
  'admin.tracking.subtitle': 'o campaigns: every tracked link, what it points to, who placed it and how many clicks it brings.',
  'admin.tracking.list.caption': 'Ligações',
  'admin.tracking.list.count': '{count} links',
  'admin.tracking.list.empty': 'No tracking links',
  'admin.tracking.list.emptyHint': 'o tracking links members create will appear here with their clicks.',
  'admin.tracking.list.filteredEmpty': 'No tracking link matches these filters',
  'admin.tracking.list.onCreator': 'Ligações',
  'admin.tracking.list.onCreatorGeneric': 'Ligações',
  'admin.tracking.list.onCreatorReset': 'See all links',
  'admin.tracking.search.label': 'Search por name, campaign or address',
  'admin.tracking.filter.state': 'Estado',
  'admin.tracking.filter.active': 'Ativo',
  'admin.tracking.filter.inactive': 'Desativado',
  'admin.tracking.filter.target': 'Alvo',
  'admin.tracking.col.link': 'Ligação',
  'admin.tracking.col.campaign': 'Campanha',
  'admin.tracking.col.target': 'Alvo',
  'admin.tracking.col.creator': 'Criado por',
  'admin.tracking.col.clicks': 'Cliques',
  'admin.tracking.col.unique': 'Visitantes únicos',
  'admin.tracking.col.lastClick': 'Último clique',
  'admin.tracking.col.state': 'Estado',
  'admin.tracking.col.created': 'Criado',
  'admin.tracking.utm.campaign': 'Campanha',
  'admin.tracking.utm.source': 'Origem',
  'admin.tracking.utm.medium': 'Médio',
  'admin.tracking.utm.line': '{label}: {value}',
  'admin.tracking.lastClick.never': 'No click',
  'admin.tracking.fiche.loading': 'Loading o/a tracking link',
  'admin.tracking.fiche.notFound': 'This tracking link no longer exists',
  'admin.tracking.fiche.notFoundHint': 'It may have been deleted.',
  'admin.tracking.fiche.back': 'Back para tracking links',
  'admin.tracking.strip.clicks': 'Cliques',
  'admin.tracking.strip.unique': 'Visitantes únicos',
  'admin.tracking.strip.confirmed': 'Successful redirects',
  'admin.tracking.strip.lastClick': 'Último clique',
  'admin.tracking.section.destination': 'Destino',
  'admin.tracking.section.campaign': 'Campanha',
  'admin.tracking.section.target': 'Alvo',
  'admin.tracking.section.stats': 'What o/a clicks bring',
  'admin.tracking.section.recent': 'Latest clicks',
  'admin.tracking.dest.original': 'Destination address',
  'admin.tracking.dest.original.explain': 'Where visitors land.',
  'admin.tracking.dest.short': 'Short address',
  'admin.tracking.dest.short.explain': 'The address para share: it redirects para the destination and counts every click.',
  'admin.tracking.copy': 'Copiar',
  'admin.tracking.copied': 'Address copied',
  'admin.tracking.target.kind': 'Kind de target',
  'admin.tracking.target.entity': 'Alvo',
  'admin.tracking.target.conversation': 'Placed from o/a conversation',
  'admin.tracking.target.none': 'This link leads para an external site: no Meeshy entity is targeted.',
  'admin.tracking.chart.days': 'Clicks per day',
  'admin.tracking.chart.days.summary': 'Busiest day: {day}, with {count} clicks',
  'admin.tracking.chart.days.quiet': 'No click over o/a period',
  'admin.tracking.chart.top': 'Most frequent: {label} ({count})',
  'admin.tracking.chart.none': 'No data',
  'admin.tracking.chart.countries': 'Visitors’ countries',
  'admin.tracking.chart.devices': 'Devices',
  'admin.tracking.chart.browsers': 'Browsers',
  'admin.tracking.chart.systems': 'Operating systems',
  'admin.tracking.chart.social': 'Social sources',
  'admin.tracking.chart.referrers': 'Referring sites',
  'admin.tracking.chart.redirects': 'Redirects',
  'admin.tracking.recent.caption': 'o latest clicks on this link',
  'admin.tracking.recent.empty': 'No click recorded for this link.',
  'admin.tracking.recent.privacy': 'No IP address and no device fingerprint: that information is not shown here.',
  'admin.tracking.recent.when': 'Quando',
  'admin.tracking.recent.where': 'Place',
  'admin.tracking.recent.device': 'Device',
  'admin.tracking.recent.browser': 'Browser',
  'admin.tracking.recent.system': 'Sistema',
  'admin.tracking.recent.referrer': 'Origin',
  'admin.tracking.recent.redirect': 'Redirect',
  'admin.tracking.recent.direct': 'Direct access',
  'admin.tracking.recent.place': '{city}, {country}',
  'admin.tracking.device.mobile': 'Mobile',
  'admin.tracking.device.tablet': 'Tablet',
  'admin.tracking.device.desktop': 'Computer',
  'admin.tracking.meta.state': 'Estado',
  'admin.tracking.meta.expires': 'Expiração',
  'admin.tracking.meta.expires.explain': 'After this date, o/a link no longer redirects.',
  'admin.tracking.meta.creator': 'Criado por',
  'admin.tracking.meta.created': 'Criado',
  'admin.tracking.meta.lastClick': 'Último clique',
  'admin.tracking.expires.never': 'Nunca expira',
  'admin.tracking.gesture.deactivate': 'Deactivate o/a link',
  'admin.tracking.gesture.reactivate': 'Reactivate o/a link',
  'admin.tracking.confirm.deactivate.title': 'Deactivate this tracking link?',
  'admin.tracking.confirm.deactivate.body': 'Visitors who open this link are no longer redirected to the destination. Statistics already collected are kept, and you can reactivate it. The gesture is recorded em the audit log.',
  'admin.tracking.confirm.reactivate.title': 'Reactivate this tracking link?',
  'admin.tracking.confirm.reactivate.body': 'The link redirects visitors to its destination again and starts counting clicks once more. The gesture is recorded em the audit log.',
  'admin.tracking.confirm.motive': 'Motivo',
  'admin.tracking.done.deactivated': 'Ligação de rastreamento desativada',
  'admin.tracking.done.reactivated': 'Ligação de rastreamento reativada',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
