/**
 * LE FRAGMENT « personnes » DU CATALOGUE D’ADMINISTRATION (#8876, #8005, #8004,
 * #7920) — comptes, fiche membre, anonymes. Préfixe exclusif : `admin.people.`.
 * Source des clés : le français (`as const`) ; les six autres langues le reprennent
 * par `satisfies AdminCatalogFragment<typeof fr>`.
 */
const f = {
  'admin.people.list.caption': 'Comptes de la plateforme',
  'admin.people.list.empty': 'Aucun compte pour le moment.',
  'admin.people.list.emptyFiltered': 'Aucun compte ne correspond à ces filtres.',
  'admin.people.filter.phoneVerified': 'Téléphone vérifié',
  'admin.people.filter.role.administration': 'Rang d’administration (créateur et administrateurs)',
  'admin.people.filter.period': 'Inscrits depuis',
  'admin.people.sort.label': 'Trier par',
  'admin.people.sort.createdAt': 'Inscription',
  'admin.people.sort.lastActiveAt': 'Dernière activité',
  'admin.people.sort.username': 'Pseudonyme',
  'admin.people.sort.email': 'E-mail',
  'admin.people.sort.firstName': 'Prénom',
  'admin.people.sort.lastName': 'Nom',
  'admin.people.col.security': 'Sécurité',
  'admin.people.security.emailVerified': 'E-mail vérifié',
  'admin.people.security.emailUnverified': 'E-mail non vérifié',
  'admin.people.security.phoneVerified': 'Téléphone vérifié',
  'admin.people.security.twoFactor': 'Double authentification',
  'admin.people.proof.email': 'Adresse e-mail',
  'admin.people.proof.phone': 'Numéro de téléphone',
  'admin.people.proof.age': 'Âge',
  'admin.people.proof.verifiedOn': 'Vérifié le {date}',
  'admin.people.proof.verifyTitle': 'Marquer comme vérifié : {proof}',
  'admin.people.proof.verifyBody': 'La preuve est posée au nom du membre : il n’aura plus à la fournir. Le geste est inscrit au journal d’audit.',
  'admin.people.proof.verifyConfirm': 'Marquer vérifié',
  'admin.people.proof.unverifyTitle': 'Retirer la vérification : {proof}',
  'admin.people.proof.unverifyBody': 'La preuve est retirée : le membre devra la fournir de nouveau pour tout ce qui en dépend. Le geste est inscrit au journal d’audit.',
  'admin.people.proof.unverifyConfirm': 'Retirer la vérification',
  'admin.people.proof.done': 'Vérification mise à jour',
  'admin.people.unlock.title': 'Déverrouiller le compte',
  'admin.people.unlock.body': 'Le compte pourra de nouveau se connecter tout de suite : le verrou est levé et le compteur de tentatives échouées repart de zéro.',
  'admin.people.unlock.confirm': 'Déverrouiller le compte',
  'admin.people.unlock.done': 'Compte déverrouillé',
  'admin.people.lock.title': 'Verrou du compte',
  'admin.people.lock.until': 'Verrouillé jusqu’au {date}',
  'admin.people.lock.explain': 'Trop de tentatives de connexion échouées : le compte se déverrouille seul à l’échéance.',
  'admin.people.twoFactor.title': 'Retirer la double authentification',
  'admin.people.twoFactor.body': 'Le membre pourra se connecter avec son seul mot de passe. Pour la réactiver, il devra appairer de nouveau une application d’authentification. Le geste est inscrit au journal d’audit.',
  'admin.people.twoFactor.confirm': 'Retirer la double authentification',
  'admin.people.twoFactor.done': 'Double authentification retirée',
  'admin.people.twoFactor.on': 'Activée',
  'admin.people.twoFactor.off': 'Non activée',
  'admin.people.twoFactor.codes': '{count} code(s) de secours restant(s)',
  'admin.people.twoFactor.offExplain': 'Seul le membre peut l’activer, en appairant une application d’authentification.',
  'admin.people.motive.required': 'Motif écrit (obligatoire, 10 caractères au minimum)',
  'admin.people.password.neverChanged': 'Jamais changé',
  'admin.people.password.changedOn': 'Changé le {date}',
  'admin.people.consent.voiceProfile': 'Profil vocal',
  'admin.people.consent.voiceData': 'Données vocales',
  'admin.people.consent.dataProcessing': 'Traitement des données',
  'admin.people.consent.voiceCloning': 'Clonage de voix',
  'admin.people.consent.notGiven': 'Non donné',
  'admin.people.consent.givenOn': 'Donné le {date}',
  'admin.people.consent.grantTitle': 'Poser le consentement : {consent}',
  'admin.people.consent.grantBody': 'Vous attestez, au nom du membre, qu’il a donné ce consentement. C’est une pièce légale : rien ne la distingue d’un consentement donné par le membre lui-même. Un motif écrit est obligatoire.',
  'admin.people.consent.grantConfirm': 'Poser le consentement',
  'admin.people.consent.revokeTitle': 'Retirer le consentement : {consent}',
  'admin.people.consent.revokeBody': 'Le consentement est retiré : ce que le membre avait autorisé à ce titre cesse d’être permis. Un motif écrit est obligatoire.',
  'admin.people.consent.revokeConfirm': 'Retirer le consentement',
  'admin.people.consent.done': 'Consentement mis à jour',
  'admin.people.consent.analyticsReadOnly': 'Le consentement à l’analytique se lit dans les métadonnées : seul le membre peut le donner.',
  'admin.people.pref.privacy.showOnlineStatus': 'Afficher le statut en ligne',
  'admin.people.pref.privacy.showLastSeen': 'Afficher la dernière connexion',
  'admin.people.pref.privacy.showReadReceipts': 'Envoyer les accusés de lecture',
  'admin.people.pref.privacy.showTypingIndicator': 'Afficher l’indicateur de saisie',
  'admin.people.pref.privacy.showForwardSource': 'Afficher la source des transferts',
  'admin.people.pref.privacy.allowContactRequests': 'Autoriser les demandes de contact',
  'admin.people.pref.privacy.allowGroupInvites': 'Autoriser les invitations à des groupes',
  'admin.people.pref.privacy.acceptCallsFromNonContacts': 'Accepter les appels hors contacts',
  'admin.people.pref.privacy.allowCallsFromNonContacts': 'Appels hors contacts (ancienne clé)',
  'admin.people.pref.privacy.saveMediaToGallery': 'Enregistrer les médias dans la galerie',
  'admin.people.pref.privacy.allowAnalytics': 'Autoriser l’analytique',
  'admin.people.pref.privacy.shareUsageData': 'Partager les données d’usage',
  'admin.people.pref.privacy.blockScreenshots': 'Bloquer les captures d’écran',
  'admin.people.pref.privacy.hideProfileFromSearch': 'Masquer le profil de la recherche',
  'admin.people.pref.privacy.notifyContactsOnReturn': 'Prévenir mes contacts à mon retour',
  'admin.people.pref.privacy.encryptionPreference': 'Préférence de chiffrement',
  'admin.people.pref.privacy.autoEncryptNewConversations': 'Chiffrer automatiquement les nouvelles conversations',
  'admin.people.pref.privacy.showEncryptionStatus': 'Afficher l’état du chiffrement',
  'admin.people.pref.privacy.warnOnUnencrypted': 'Avertir dans une conversation non chiffrée',
  'admin.people.pref.audio.transcriptionEnabled': 'Transcription des messages vocaux',
  'admin.people.pref.audio.transcriptionSource': 'Source de la transcription',
  'admin.people.pref.audio.autoTranscribeIncoming': 'Transcrire automatiquement les vocaux reçus',
  'admin.people.pref.audio.audioTranslationEnabled': 'Traduction des messages vocaux',
  'admin.people.pref.audio.translatedAudioFormat': 'Format de l’audio traduit',
  'admin.people.pref.audio.ttsEnabled': 'Synthèse vocale',
  'admin.people.pref.audio.ttsVoice': 'Voix de synthèse',
  'admin.people.pref.audio.ttsSpeed': 'Vitesse de la synthèse vocale',
  'admin.people.pref.audio.ttsPitch': 'Hauteur de la synthèse vocale',
  'admin.people.pref.audio.audioQuality': 'Qualité audio',
  'admin.people.pref.audio.noiseSuppression': 'Réduction du bruit',
  'admin.people.pref.audio.echoCancellation': 'Annulation d’écho',
  'admin.people.pref.audio.voiceProfileEnabled': 'Profil vocal',
  'admin.people.pref.audio.voiceCloneQuality': 'Qualité du clonage vocal',
  'admin.people.pref.audio.voiceCloningExaggeration': 'Clonage vocal : expressivité',
  'admin.people.pref.audio.voiceCloningCfgWeight': 'Clonage vocal : fidélité au modèle',
  'admin.people.pref.audio.voiceCloningTemperature': 'Clonage vocal : variabilité',
  'admin.people.pref.audio.voiceCloningTopP': 'Clonage vocal : diversité (top-p)',
  'admin.people.pref.audio.voiceCloningQualityPreset': 'Clonage vocal : préréglage de qualité',
  'admin.people.pref.message.sendOnEnter': 'Envoyer avec Entrée',
  'admin.people.pref.message.showFormattingToolbar': 'Barre de mise en forme',
  'admin.people.pref.message.enableMarkdown': 'Mise en forme Markdown',
  'admin.people.pref.message.enableEmoji': 'Emojis',
  'admin.people.pref.message.emojiSkinTone': 'Teinte des emojis',
  'admin.people.pref.message.autoCorrectEnabled': 'Correction automatique',
  'admin.people.pref.message.spellCheckEnabled': 'Vérification orthographique',
  'admin.people.pref.message.linkPreviewEnabled': 'Aperçu des liens',
  'admin.people.pref.message.imagePreviewEnabled': 'Aperçu des images',
  'admin.people.pref.message.saveDrafts': 'Enregistrer les brouillons',
  'admin.people.pref.message.draftExpirationDays': 'Durée de conservation des brouillons',
  'admin.people.pref.message.defaultFontSize': 'Taille du texte des messages',
  'admin.people.pref.message.defaultTextAlign': 'Alignement du texte',
  'admin.people.pref.message.autoTranslateIncoming': 'Traduire automatiquement les messages reçus',
  'admin.people.pref.message.autoTranslateLanguages': 'Langues traduites automatiquement',
  'admin.people.pref.message.maxCharacterLimit': 'Longueur maximale d’un message',
  'admin.people.pref.notification.pushEnabled': 'Notifications push',
  'admin.people.pref.notification.emailEnabled': 'Notifications par e-mail',
  'admin.people.pref.notification.soundEnabled': 'Sons',
  'admin.people.pref.notification.vibrationEnabled': 'Vibrations',
  'admin.people.pref.notification.newMessageEnabled': 'Nouveaux messages',
  'admin.people.pref.notification.missedCallEnabled': 'Appels manqués',
  'admin.people.pref.notification.callsEnabled': 'Appels',
  'admin.people.pref.notification.voicemailEnabled': 'Messages vocaux laissés',
  'admin.people.pref.notification.systemEnabled': 'Notifications système',
  'admin.people.pref.notification.conversationEnabled': 'Conversations',
  'admin.people.pref.notification.replyEnabled': 'Réponses',
  'admin.people.pref.notification.mentionEnabled': 'Mentions',
  'admin.people.pref.notification.reactionEnabled': 'Réactions',
  'admin.people.pref.notification.contactRequestEnabled': 'Demandes de contact',
  'admin.people.pref.notification.groupInviteEnabled': 'Invitations à des groupes',
  'admin.people.pref.notification.memberJoinedEnabled': 'Arrivées de membres',
  'admin.people.pref.notification.memberLeftEnabled': 'Départs de membres',
  'admin.people.pref.notification.postLikeEnabled': 'J’aime sur mes publications',
  'admin.people.pref.notification.postCommentEnabled': 'Commentaires sur mes publications',
  'admin.people.pref.notification.postRepostEnabled': 'Repartages de mes publications',
  'admin.people.pref.notification.storyReactionEnabled': 'Réactions à mes stories',
  'admin.people.pref.notification.commentReplyEnabled': 'Réponses à mes commentaires',
  'admin.people.pref.notification.commentLikeEnabled': 'J’aime sur mes commentaires',
  'admin.people.pref.notification.friendContentEnabled': 'Publications de mes amis',
  'admin.people.pref.notification.contactActivityEnabled': 'Retour d’un contact sur Meeshy',
  'admin.people.pref.notification.dndEnabled': 'Ne pas déranger',
  'admin.people.pref.notification.dndStartTime': 'Ne pas déranger : début',
  'admin.people.pref.notification.dndEndTime': 'Ne pas déranger : fin',
  'admin.people.pref.notification.dndDays': 'Ne pas déranger : jours',
  'admin.people.pref.notification.dndUtcOffsetMinutes': 'Ne pas déranger : décalage horaire',
  'admin.people.pref.notification.showPreview': 'Aperçu du contenu',
  'admin.people.pref.notification.showSenderName': 'Nom de l’expéditeur',
  'admin.people.pref.notification.groupNotifications': 'Regrouper les notifications',
  'admin.people.pref.notification.notificationBadgeEnabled': 'Pastille de notifications',
  'admin.people.pref.video.videoQuality': 'Qualité vidéo',
  'admin.people.pref.video.videoBitrate': 'Débit vidéo',
  'admin.people.pref.video.videoFrameRate': 'Images par seconde',
  'admin.people.pref.video.videoResolution': 'Résolution vidéo',
  'admin.people.pref.video.videoCodec': 'Codec vidéo',
  'admin.people.pref.video.defaultCamera': 'Caméra par défaut',
  'admin.people.pref.video.mirrorLocalVideo': 'Miroir de ma vidéo',
  'admin.people.pref.video.videoLayout': 'Disposition des appels',
  'admin.people.pref.video.showSelfView': 'Afficher ma vidéo',
  'admin.people.pref.video.selfViewPosition': 'Position de ma vidéo',
  'admin.people.pref.video.backgroundBlurEnabled': 'Flou d’arrière-plan',
  'admin.people.pref.video.virtualBackgroundEnabled': 'Arrière-plan virtuel',
  'admin.people.pref.video.virtualBackgroundUrl': 'Image d’arrière-plan virtuel',
  'admin.people.pref.video.hardwareAccelerationEnabled': 'Accélération matérielle',
  'admin.people.pref.video.adaptiveBitrateEnabled': 'Débit adaptatif',
  'admin.people.pref.video.autoStartVideo': 'Démarrer la vidéo automatiquement',
  'admin.people.pref.video.autoMuteOnJoin': 'Couper le micro à l’arrivée',
  'admin.people.pref.document.autoDownloadEnabled': 'Téléchargement automatique',
  'admin.people.pref.document.autoDownloadOnWifi': 'Téléchargement automatique en Wi-Fi',
  'admin.people.pref.document.autoDownloadMaxSize': 'Taille maximale du téléchargement automatique',
  'admin.people.pref.document.downloadPath': 'Dossier de téléchargement',
  'admin.people.pref.document.inlinePreviewEnabled': 'Aperçu intégré',
  'admin.people.pref.document.previewPdfEnabled': 'Aperçu des PDF',
  'admin.people.pref.document.previewImagesEnabled': 'Aperçu des images',
  'admin.people.pref.document.previewVideosEnabled': 'Aperçu des vidéos',
  'admin.people.pref.document.storageQuota': 'Quota de stockage',
  'admin.people.pref.document.autoDeleteOldFiles': 'Suppression automatique des anciens fichiers',
  'admin.people.pref.document.fileRetentionDays': 'Durée de conservation des fichiers',
  'admin.people.pref.document.compressImagesOnUpload': 'Compresser les images à l’envoi',
  'admin.people.pref.document.imageCompressionQuality': 'Qualité de compression des images',
  'admin.people.pref.document.allowedFileTypes': 'Types de fichiers autorisés',
  'admin.people.pref.document.scanFilesForMalware': 'Analyse antivirus des fichiers',
  'admin.people.pref.document.allowExternalLinks': 'Liens externes autorisés',
  'admin.people.pref.application.theme': 'Thème',
  'admin.people.pref.application.accentColor': 'Couleur d’accent',
  'admin.people.pref.application.interfaceLanguage': 'Langue de l’interface',
  'admin.people.pref.application.autoTranslateEnabled': 'Traduction automatique',
  'admin.people.pref.application.fontSize': 'Taille du texte',
  'admin.people.pref.application.fontFamily': 'Police',
  'admin.people.pref.application.lineHeight': 'Interligne',
  'admin.people.pref.application.compactMode': 'Mode compact',
  'admin.people.pref.application.sidebarPosition': 'Position de la barre latérale',
  'admin.people.pref.application.showAvatars': 'Afficher les avatars',
  'admin.people.pref.application.animationsEnabled': 'Animations',
  'admin.people.pref.application.reducedMotion': 'Réduire les animations',
  'admin.people.pref.application.highContrastMode': 'Contraste élevé',
  'admin.people.pref.application.screenReaderOptimized': 'Optimisé pour lecteur d’écran',
  'admin.people.pref.application.keyboardShortcutsEnabled': 'Raccourcis clavier',
  'admin.people.pref.application.tutorialsCompleted': 'Tutoriels terminés',
  'admin.people.pref.application.betaFeaturesEnabled': 'Fonctions bêta',
  'admin.people.pref.application.telemetryEnabled': 'Télémétrie',
  'admin.people.prefValue.encryption.disabled': 'Désactivé',
  'admin.people.prefValue.encryption.optional': 'Facultatif',
  'admin.people.prefValue.encryption.always': 'Toujours',
  'admin.people.prefValue.transcriptionSource.auto': 'Automatique',
  'admin.people.prefValue.transcriptionSource.mobile': 'Sur l’appareil',
  'admin.people.prefValue.transcriptionSource.server': 'Sur le serveur',
  'admin.people.prefValue.audioQuality.low': 'Basse',
  'admin.people.prefValue.audioQuality.medium': 'Moyenne',
  'admin.people.prefValue.audioQuality.high': 'Haute',
  'admin.people.prefValue.audioQuality.lossless': 'Sans perte',
  'admin.people.prefValue.cloneQuality.fast': 'Rapide',
  'admin.people.prefValue.cloneQuality.balanced': 'Équilibrée',
  'admin.people.prefValue.cloneQuality.quality': 'Qualité maximale',
  'admin.people.prefValue.clonePreset.fast': 'Rapide',
  'admin.people.prefValue.clonePreset.balanced': 'Équilibré',
  'admin.people.prefValue.clonePreset.high_quality': 'Haute qualité',
  'admin.people.prefValue.fontSize.small': 'Petite',
  'admin.people.prefValue.fontSize.medium': 'Moyenne',
  'admin.people.prefValue.fontSize.large': 'Grande',
  'admin.people.prefValue.textAlign.left': 'À gauche',
  'admin.people.prefValue.textAlign.center': 'Centré',
  'admin.people.prefValue.textAlign.right': 'À droite',
  'admin.people.prefValue.skinTone.default': 'Par défaut',
  'admin.people.prefValue.skinTone.light': 'Clair',
  'admin.people.prefValue.skinTone.medium-light': 'Moyennement clair',
  'admin.people.prefValue.skinTone.medium': 'Moyen',
  'admin.people.prefValue.skinTone.medium-dark': 'Moyennement foncé',
  'admin.people.prefValue.skinTone.dark': 'Foncé',
  'admin.people.prefValue.videoQuality.low': 'Basse',
  'admin.people.prefValue.videoQuality.medium': 'Moyenne',
  'admin.people.prefValue.videoQuality.high': 'Haute',
  'admin.people.prefValue.videoQuality.auto': 'Automatique',
  'admin.people.prefValue.videoResolution.480p': '480p',
  'admin.people.prefValue.videoResolution.720p': '720p',
  'admin.people.prefValue.videoResolution.1080p': '1080p',
  'admin.people.prefValue.videoResolution.auto': 'Automatique',
  'admin.people.prefValue.videoLayout.grid': 'Grille',
  'admin.people.prefValue.videoLayout.speaker': 'Intervenant actif',
  'admin.people.prefValue.videoLayout.sidebar': 'Barre latérale',
  'admin.people.prefValue.selfViewPosition.top-left': 'En haut à gauche',
  'admin.people.prefValue.selfViewPosition.top-right': 'En haut à droite',
  'admin.people.prefValue.selfViewPosition.bottom-left': 'En bas à gauche',
  'admin.people.prefValue.selfViewPosition.bottom-right': 'En bas à droite',
  'admin.people.prefValue.theme.light': 'Clair',
  'admin.people.prefValue.theme.dark': 'Sombre',
  'admin.people.prefValue.theme.auto': 'Automatique',
  'admin.people.prefValue.lineHeight.tight': 'Serré',
  'admin.people.prefValue.lineHeight.normal': 'Normal',
  'admin.people.prefValue.lineHeight.relaxed': 'Aéré',
  'admin.people.prefValue.lineHeight.loose': 'Très aéré',
  'admin.people.prefValue.sidebarPosition.left': 'À gauche',
  'admin.people.prefValue.sidebarPosition.right': 'À droite',
  'admin.people.prefValue.on': 'Activé',
  'admin.people.prefValue.off': 'Désactivé',
  'admin.people.prefValue.everyDay': 'Tous les jours',
  'admin.people.prefValue.characters': '{count} caractères',
  'admin.people.prefValue.kbps': '{count} kbit/s',
  'admin.people.prefValue.count.fileTypes': '{count} type(s) de fichier autorisé(s)',
  'admin.people.prefValue.count.tutorials': '{count} tutoriel(s) terminé(s)',
  'admin.people.prefValue.count.items': '{count} élément(s)',
  'admin.people.prefValue.structured': 'Données structurées',
  'admin.people.prefValue.frameRate.15': '15 images par seconde',
  'admin.people.prefValue.frameRate.24': '24 images par seconde',
  'admin.people.prefValue.frameRate.30': '30 images par seconde',
  'admin.people.prefValue.frameRate.60': '60 images par seconde',
  'admin.people.prefValue.videoCodec.VP8': 'VP8',
  'admin.people.prefValue.videoCodec.VP9': 'VP9',
  'admin.people.prefValue.videoCodec.H264': 'H264',
  'admin.people.prefValue.videoCodec.H265': 'H265',
  'admin.people.prefValue.videoCodec.AV1': 'AV1',
  'admin.people.prefValue.audioFormat.mp3': 'MP3',
  'admin.people.prefValue.audioFormat.wav': 'WAV',
  'admin.people.prefValue.audioFormat.ogg': 'OGG',
  'admin.people.stats.withheld': 'Non communiqué',
  'admin.people.meta.identity': 'Identité et langues',
  'admin.people.meta.accountTitle': 'Métadonnées de compte',
  'admin.people.meta.sign': 'Connexions',
  'admin.people.meta.links': 'Liens et parrainages',
  'admin.people.meta.prismExplain': 'Les messages sont lus dans cet ordre de langues : principale, secondaire, puis destination.',
  'admin.people.meta.registrationCountry': 'Pays d’inscription',
  'admin.people.meta.deviceLocale': 'Langue de l’appareil',
  'admin.people.meta.deviceLocaleExplain': 'Quatrième rang du Prisme : elle ne passe jamais avant les langues choisies dans l’application.',
  'admin.people.meta.deviceCountry': 'Pays de l’appareil',
  'admin.people.meta.age': 'Âge',
  'admin.people.meta.ageValue': '{age} · né(e) le {date}',
  'admin.people.meta.ageExplain': 'Calculé depuis la date de naissance déclarée.',
  'admin.people.meta.ageVerified': 'Âge vérifié',
  'admin.people.meta.terms': 'Conditions acceptées',
  'admin.people.meta.termsValue': 'Version {version} · le {date}',
  'admin.people.meta.termsNone': 'Non acceptées',
  'admin.people.meta.onboarding': 'Parcours d’accueil',
  'admin.people.meta.onboardingDone': 'Terminé le {date}',
  'admin.people.meta.onboardingNone': 'Non terminé',
  'admin.people.meta.streak': 'Série en cours',
  'admin.people.meta.streakValue': '{current} (record : {longest})',
  'admin.people.meta.engagement': 'Score d’engagement',
  'admin.people.meta.engagementExplain': 'Mesure l’activité récente du membre sur la plateforme.',
  'admin.people.meta.meesh': 'Solde de meesh',
  'admin.people.meta.blocked': 'Comptes bloqués',
  'admin.people.meta.blockedNone': 'Aucun',
  'admin.people.meta.blockedCount': '{count} compte(s)',
  'admin.people.meta.pendingEmail': 'Changement d’e-mail en attente',
  'admin.people.meta.pendingPhone': 'Changement de téléphone en attente',
  'admin.people.meta.pendingExplain': 'La nouvelle valeur attend sa confirmation ; elle n’est jamais affichée ici.',
  'admin.people.consent.analytics': 'Analytique',
  'admin.people.meta.lastLogin': 'Dernière connexion',
  'admin.people.meta.registration': 'Inscription',
  'admin.people.meta.placeUnknown': 'Lieu inconnu',
  'admin.people.meta.signDetail': '{place} · {device}',
  'admin.people.meta.failedLoginsExplain': 'Le compteur repart de zéro à la prochaine connexion réussie.',
  'admin.people.meta.lock': 'Verrou',
  'admin.people.meta.lockNone': 'Aucun verrou',
  'admin.people.meta.backupCodes': 'Codes de secours',
  'admin.people.meta.shareLinks': 'Liens de partage créés',
  'admin.people.meta.trackingLinks': 'Liens de suivi créés',
  'admin.people.meta.affiliateTokens': 'Jetons d’affiliation créés',
  'admin.people.meta.referralsGiven': 'Parrainages donnés',
  'admin.people.meta.referralsReceived': 'Parrainages reçus',
  'admin.people.meta.requestsSent': 'Demandes de contact envoyées',
  'admin.people.meta.requestsReceived': 'Demandes de contact reçues',
  'admin.people.ban.by': 'Banni par {name} le {date}',
  'admin.people.ban.byUnknown': 'Banni le {date}',
  'admin.people.ban.until': 'Jusqu’au {date}',
  'admin.people.ban.liftedBy': 'Levé par {name} le {date}',
  'admin.people.ban.liftedBySystem': 'Levé automatiquement par le système le {date}',
  'admin.people.ban.liftedUnknown': 'Levé le {date}',
  'admin.people.ban.liftReason': 'motif de la levée : {reason}',
  'admin.people.notFound': 'Ce membre n’existe pas ou n’existe plus.',
  'admin.people.journal': 'Journal de ce membre',
  'admin.people.media.unnamed': 'Média sans nom',
  'admin.people.media.kind.image': 'Image',
  'admin.people.media.kind.video': 'Vidéo',
  'admin.people.media.kind.audio': 'Audio',
  'admin.people.media.kind.document': 'Document',
  'admin.people.secEvent.PASSWORD_RESET_REQUEST': 'Demande de réinitialisation du mot de passe',
  'admin.people.secEvent.PASSWORD_RESET_SUCCESS': 'Mot de passe réinitialisé',
  'admin.people.secEvent.PASSWORD_RESET_FAILED': 'Réinitialisation du mot de passe échouée',
  'admin.people.secEvent.PASSWORD_RESET_UNVERIFIED_EMAIL': 'Réinitialisation demandée pour une adresse non vérifiée',
  'admin.people.secEvent.PASSWORD_RESET_TOKEN_REUSE': 'Lien de réinitialisation réutilisé',
  'admin.people.secEvent.PASSWORD_RESET_REVOKED_TOKEN': 'Lien de réinitialisation révoqué utilisé',
  'admin.people.secEvent.PASSWORD_RESET_INVALID_TOKEN': 'Lien de réinitialisation invalide',
  'admin.people.secEvent.PASSWORD_RESET_EXPIRED_TOKEN': 'Lien de réinitialisation expiré',
  'admin.people.secEvent.PASSWORD_RESET_LOCKED_ACCOUNT': 'Réinitialisation demandée sur un compte verrouillé',
  'admin.people.secEvent.PASSWORD_RESET_ABUSE': 'Abus de la réinitialisation du mot de passe',
  'admin.people.secEvent.SUSPICIOUS_PASSWORD_RESET': 'Réinitialisation du mot de passe suspecte',
  'admin.people.secEvent.PASSWORD_CHANGE': 'Mot de passe changé',
  'admin.people.secEvent.LOGIN_SUCCESS': 'Connexion réussie',
  'admin.people.secEvent.LOGIN_FAILED': 'Connexion échouée',
  'admin.people.secEvent.LOGIN_BLOCKED': 'Connexion bloquée',
  'admin.people.secEvent.LOGOUT': 'Déconnexion',
  'admin.people.secEvent.ACCOUNT_LOCKED': 'Compte verrouillé',
  'admin.people.secEvent.ACCOUNT_UNLOCKED': 'Compte déverrouillé',
  'admin.people.secEvent.SESSION_CREATED': 'Session ouverte',
  'admin.people.secEvent.SESSION_REVOKED': 'Session révoquée',
  'admin.people.secEvent.SESSION_EXPIRED': 'Session expirée',
  'admin.people.secEvent.SESSION_TRUSTED': 'Session marquée de confiance',
  'admin.people.secEvent.TWO_FACTOR_ENABLED': 'Double authentification activée',
  'admin.people.secEvent.TWO_FACTOR_DISABLED': 'Double authentification désactivée',
  'admin.people.secEvent.TWO_FACTOR_SUCCESS': 'Double authentification réussie',
  'admin.people.secEvent.TWO_FACTOR_FAILED': 'Double authentification échouée',
  'admin.people.secEvent.TWO_FA_FAILED': 'Double authentification échouée',
  'admin.people.secEvent.EMAIL_CHANGE': 'Adresse e-mail changée',
  'admin.people.secEvent.PHONE_CHANGE': 'Numéro de téléphone changé',
  'admin.people.secEvent.PHONE_TRANSFERRED_OUT': 'Numéro transféré vers un autre compte',
  'admin.people.secEvent.PHONE_TRANSFERRED_IN': 'Numéro reçu d’un autre compte',
  'admin.people.secEvent.PHONE_TRANSFER_CODE_RESENT': 'Code de transfert de numéro renvoyé',
  'admin.people.secEvent.SUSPICIOUS_ACTIVITY': 'Activité suspecte',
  'admin.people.secEvent.RATE_LIMIT_EXCEEDED': 'Limite de requêtes dépassée',
  'admin.people.secEvent.BRUTE_FORCE_DETECTED': 'Tentatives de force brute détectées',
  'admin.people.secEvent.MAGIC_LINK_REQUESTED': 'Lien magique demandé',
  'admin.people.secEvent.MAGIC_LINK_LOGIN_SUCCESS': 'Connexion par lien magique',
  'admin.people.secEvent.MAGIC_LINK_REUSE_ATTEMPT': 'Lien magique réutilisé',
  'admin.people.secEvent.MAGIC_LINK_EXPIRED': 'Lien magique expiré',
  'admin.people.secEvent.EMAIL_RELEASED_BY_CLAIM': 'Adresse e-mail libérée par une revendication',
  'admin.people.dossier.contactDate': 'Depuis',
  'admin.people.dossier.memberLeft': 'Parti',
  'admin.people.dossier.eventStatus': 'Résultat',
  'admin.people.anonymous.count': '{count} anonymes',
  'admin.people.anonymous.kind': 'Invité sans compte',
  'admin.people.anonymous.notFound': 'Ce participant n’existe pas ou n’existe plus.',
  'admin.people.anonymous.presence': 'Présence',
  'admin.people.anonymous.list.caption': 'Participants anonymes',
  'admin.people.anonymous.list.empty': 'Aucun participant anonyme pour le moment.',
  'admin.people.anonymous.list.emptyFiltered': 'Aucun anonyme ne correspond à ces filtres.',
  'admin.people.anonymous.state.left': 'Parti',
  'admin.people.anonymous.state.left.explain': 'N’est plus dans la conversation depuis la date indiquée.',
  'admin.people.anonymous.state.revoked': 'Accès retiré',
  'admin.people.anonymous.state.revoked.explain': 'N’est plus actif dans la conversation : son accès a été retiré, par exemple quand le lien d’invitation a été fermé.',
  'admin.people.anonymous.section.conversation': 'Conversation',
  'admin.people.anonymous.section.entry': 'Lien d’entrée',
  'admin.people.anonymous.section.permissions': 'Ce qu’il peut faire',
  'admin.people.anonymous.section.permissions.hint': 'Figées à son arrivée d’après les règles du lien : modifier le lien ensuite ne retire rien à qui est déjà entré.',
  'admin.people.anonymous.entry.none': 'Aucun lien d’entrée n’est enregistré pour ce participant.',
  'admin.people.anonymous.entry.expires': 'Échéance du lien',
  'admin.people.anonymous.entry.noExpiry': 'Sans échéance',
  'admin.people.anonymous.stat.messages': 'Messages envoyés',
  'admin.people.anonymous.stat.permissions': 'Permissions accordées',
  'admin.people.anonymous.stat.permissionsValue': '{granted} sur {total}',
  'admin.people.anonymous.stat.arrived': 'Arrivé',
  'admin.people.anonymous.meta.languageExplain': 'La langue dans laquelle cet invité lit la conversation : les messages lui sont traduits dans cette langue.',
  'admin.people.anonymous.meta.left': 'Parti le',
  'admin.people.anonymous.perm.canSendMessages.yes': 'Peut écrire des messages',
  'admin.people.anonymous.perm.canSendMessages.no': 'Ne peut pas écrire de messages',
  'admin.people.anonymous.perm.canSendImages.yes': 'Peut envoyer des images',
  'admin.people.anonymous.perm.canSendImages.no': 'Ne peut pas envoyer d’images',
  'admin.people.anonymous.perm.canSendFiles.yes': 'Peut envoyer des fichiers',
  'admin.people.anonymous.perm.canSendFiles.no': 'Ne peut pas envoyer de fichiers',
  'admin.people.anonymous.perm.canSendVideos.yes': 'Peut envoyer des vidéos',
  'admin.people.anonymous.perm.canSendVideos.no': 'Ne peut pas envoyer de vidéos',
  'admin.people.anonymous.perm.canSendAudios.yes': 'Peut envoyer des messages vocaux',
  'admin.people.anonymous.perm.canSendAudios.no': 'Ne peut pas envoyer de messages vocaux',
  'admin.people.anonymous.perm.canSendLocations.yes': 'Peut partager sa position',
  'admin.people.anonymous.perm.canSendLocations.no': 'Ne peut pas partager sa position',
  'admin.people.anonymous.perm.canSendLinks.yes': 'Peut envoyer des liens',
  'admin.people.anonymous.perm.canSendLinks.no': 'Ne peut pas envoyer de liens',
  'admin.people.anonymous.perm.canViewHistory.yes': 'Voit les messages écrits avant son arrivée',
  'admin.people.anonymous.perm.canViewHistory.no': 'Ne voit pas les messages écrits avant son arrivée',
} as const;

export default f;
