import type { AdminCatalogFragment } from './fragment';
import type fr from './personnes-fr';

const f = {
  'admin.people.list.caption': 'Platform accounts',
  'admin.people.list.empty': 'No accounts yet.',
  'admin.people.list.emptyFiltered': 'No account matches these filters.',
  'admin.people.filter.phoneVerified': 'Phone verified',
  'admin.people.filter.role.administration': 'Administration rank (creator and administrators)',
  'admin.people.filter.period': 'Signed up within',
  'admin.people.sort.label': 'Sort by',
  'admin.people.sort.createdAt': 'Sign-up date',
  'admin.people.sort.lastActiveAt': 'Last activity',
  'admin.people.sort.username': 'Username',
  'admin.people.sort.email': 'E-mail',
  'admin.people.sort.firstName': 'First name',
  'admin.people.sort.lastName': 'Last name',
  'admin.people.col.security': 'Security',
  'admin.people.security.emailVerified': 'E-mail verified',
  'admin.people.security.emailUnverified': 'E-mail not verified',
  'admin.people.security.phoneVerified': 'Phone verified',
  'admin.people.security.twoFactor': 'Two-factor authentication',
  'admin.people.proof.email': 'E-mail address',
  'admin.people.proof.phone': 'Phone number',
  'admin.people.proof.age': 'Age',
  'admin.people.proof.verifiedOn': 'Verified on {date}',
  'admin.people.proof.verifyTitle': 'Mark as verified: {proof}',
  'admin.people.proof.verifyBody': 'The proof is recorded on the member’s behalf: they will no longer have to provide it. The action is written to the audit log.',
  'admin.people.proof.verifyConfirm': 'Mark verified',
  'admin.people.proof.unverifyTitle': 'Remove the verification: {proof}',
  'admin.people.proof.unverifyBody': 'The proof is removed: the member will have to provide it again for everything that depends on it. The action is written to the audit log.',
  'admin.people.proof.unverifyConfirm': 'Remove verification',
  'admin.people.proof.done': 'Verification updated',
  'admin.people.unlock.title': 'Unlock the account',
  'admin.people.unlock.body': 'The account will be able to sign in again right away: the lock is lifted and the failed-attempt counter starts over.',
  'admin.people.unlock.confirm': 'Unlock the account',
  'admin.people.unlock.done': 'Account unlocked',
  'admin.people.lock.title': 'Account lock',
  'admin.people.lock.until': 'Locked until {date}',
  'admin.people.lock.explain': 'Too many failed sign-in attempts: the account unlocks by itself when the lock expires.',
  'admin.people.twoFactor.title': 'Remove two-factor authentication',
  'admin.people.twoFactor.body': 'The member will be able to sign in with their password alone. To turn it back on, they will have to pair an authenticator app again. The action is written to the audit log.',
  'admin.people.twoFactor.confirm': 'Remove two-factor authentication',
  'admin.people.twoFactor.done': 'Two-factor authentication removed',
  'admin.people.twoFactor.on': 'On',
  'admin.people.twoFactor.off': 'Off',
  'admin.people.twoFactor.codes': '{count} backup code(s) left',
  'admin.people.twoFactor.offExplain': 'Only the member can turn it on, by pairing an authenticator app.',
  'admin.people.motive.required': 'Written reason (required, 10 characters minimum)',
  'admin.people.password.neverChanged': 'Never changed',
  'admin.people.password.changedOn': 'Changed on {date}',
  'admin.people.consent.voiceProfile': 'Voice profile',
  'admin.people.consent.voiceData': 'Voice data',
  'admin.people.consent.dataProcessing': 'Data processing',
  'admin.people.consent.voiceCloning': 'Voice cloning',
  'admin.people.consent.notGiven': 'Not given',
  'admin.people.consent.givenOn': 'Given on {date}',
  'admin.people.consent.grantTitle': 'Record the consent: {consent}',
  'admin.people.consent.grantBody': 'You attest, on the member’s behalf, that they gave this consent. It is a legal record: nothing tells it apart from a consent given by the member. A written reason is required.',
  'admin.people.consent.grantConfirm': 'Record the consent',
  'admin.people.consent.revokeTitle': 'Withdraw the consent: {consent}',
  'admin.people.consent.revokeBody': 'The consent is withdrawn: what the member had allowed under it stops being permitted. A written reason is required.',
  'admin.people.consent.revokeConfirm': 'Withdraw the consent',
  'admin.people.consent.done': 'Consent updated',
  'admin.people.consent.analyticsReadOnly': 'Analytics consent is read in the metadata: only the member can give it.',
  'admin.people.pref.privacy.showOnlineStatus': 'Show online status',
  'admin.people.pref.privacy.showLastSeen': 'Show last seen',
  'admin.people.pref.privacy.showReadReceipts': 'Send read receipts',
  'admin.people.pref.privacy.showTypingIndicator': 'Show typing indicator',
  'admin.people.pref.privacy.showForwardSource': 'Show the source of forwarded messages',
  'admin.people.pref.privacy.allowContactRequests': 'Allow contact requests',
  'admin.people.pref.privacy.allowGroupInvites': 'Allow group invitations',
  'admin.people.pref.privacy.acceptCallsFromNonContacts': 'Accept calls from non-contacts',
  'admin.people.pref.privacy.allowCallsFromNonContacts': 'Calls from non-contacts (legacy key)',
  'admin.people.pref.privacy.saveMediaToGallery': 'Save media to the gallery',
  'admin.people.pref.privacy.allowAnalytics': 'Allow analytics',
  'admin.people.pref.privacy.shareUsageData': 'Share usage data',
  'admin.people.pref.privacy.blockScreenshots': 'Block screenshots',
  'admin.people.pref.privacy.hideProfileFromSearch': 'Hide profile from search',
  'admin.people.pref.privacy.notifyContactsOnReturn': 'Tell my contacts when I come back',
  'admin.people.pref.privacy.encryptionPreference': 'Encryption preference',
  'admin.people.pref.privacy.autoEncryptNewConversations': 'Encrypt new conversations automatically',
  'admin.people.pref.privacy.showEncryptionStatus': 'Show encryption status',
  'admin.people.pref.privacy.warnOnUnencrypted': 'Warn in an unencrypted conversation',
  'admin.people.pref.audio.transcriptionEnabled': 'Voice message transcription',
  'admin.people.pref.audio.transcriptionSource': 'Transcription source',
  'admin.people.pref.audio.autoTranscribeIncoming': 'Transcribe incoming voice messages automatically',
  'admin.people.pref.audio.audioTranslationEnabled': 'Voice message translation',
  'admin.people.pref.audio.translatedAudioFormat': 'Translated audio format',
  'admin.people.pref.audio.ttsEnabled': 'Speech synthesis',
  'admin.people.pref.audio.ttsVoice': 'Synthesis voice',
  'admin.people.pref.audio.ttsSpeed': 'Speech synthesis speed',
  'admin.people.pref.audio.ttsPitch': 'Speech synthesis pitch',
  'admin.people.pref.audio.audioQuality': 'Audio quality',
  'admin.people.pref.audio.noiseSuppression': 'Noise suppression',
  'admin.people.pref.audio.echoCancellation': 'Echo cancellation',
  'admin.people.pref.audio.voiceProfileEnabled': 'Voice profile',
  'admin.people.pref.audio.voiceCloneQuality': 'Voice cloning quality',
  'admin.people.pref.audio.voiceCloningExaggeration': 'Voice cloning: expressiveness',
  'admin.people.pref.audio.voiceCloningCfgWeight': 'Voice cloning: fidelity to the model',
  'admin.people.pref.audio.voiceCloningTemperature': 'Voice cloning: variability',
  'admin.people.pref.audio.voiceCloningTopP': 'Voice cloning: diversity (top-p)',
  'admin.people.pref.audio.voiceCloningQualityPreset': 'Voice cloning: quality preset',
  'admin.people.pref.message.sendOnEnter': 'Send with Enter',
  'admin.people.pref.message.showFormattingToolbar': 'Formatting toolbar',
  'admin.people.pref.message.enableMarkdown': 'Markdown formatting',
  'admin.people.pref.message.enableEmoji': 'Emoji',
  'admin.people.pref.message.emojiSkinTone': 'Emoji skin tone',
  'admin.people.pref.message.autoCorrectEnabled': 'Auto-correct',
  'admin.people.pref.message.spellCheckEnabled': 'Spell check',
  'admin.people.pref.message.linkPreviewEnabled': 'Link previews',
  'admin.people.pref.message.imagePreviewEnabled': 'Image previews',
  'admin.people.pref.message.saveDrafts': 'Save drafts',
  'admin.people.pref.message.draftExpirationDays': 'Draft retention',
  'admin.people.pref.message.defaultFontSize': 'Message text size',
  'admin.people.pref.message.defaultTextAlign': 'Text alignment',
  'admin.people.pref.message.autoTranslateIncoming': 'Translate incoming messages automatically',
  'admin.people.pref.message.autoTranslateLanguages': 'Languages translated automatically',
  'admin.people.pref.message.maxCharacterLimit': 'Maximum message length',
  'admin.people.pref.notification.pushEnabled': 'Push notifications',
  'admin.people.pref.notification.emailEnabled': 'E-mail notifications',
  'admin.people.pref.notification.soundEnabled': 'Sounds',
  'admin.people.pref.notification.vibrationEnabled': 'Vibration',
  'admin.people.pref.notification.newMessageEnabled': 'New messages',
  'admin.people.pref.notification.missedCallEnabled': 'Missed calls',
  'admin.people.pref.notification.callsEnabled': 'Calls',
  'admin.people.pref.notification.voicemailEnabled': 'Voicemail',
  'admin.people.pref.notification.systemEnabled': 'System notifications',
  'admin.people.pref.notification.conversationEnabled': 'Conversations',
  'admin.people.pref.notification.replyEnabled': 'Replies',
  'admin.people.pref.notification.mentionEnabled': 'Mentions',
  'admin.people.pref.notification.reactionEnabled': 'Reactions',
  'admin.people.pref.notification.contactRequestEnabled': 'Contact requests',
  'admin.people.pref.notification.groupInviteEnabled': 'Group invitations',
  'admin.people.pref.notification.memberJoinedEnabled': 'Members joining',
  'admin.people.pref.notification.memberLeftEnabled': 'Members leaving',
  'admin.people.pref.notification.postLikeEnabled': 'Likes on my posts',
  'admin.people.pref.notification.postCommentEnabled': 'Comments on my posts',
  'admin.people.pref.notification.postRepostEnabled': 'Reposts of my posts',
  'admin.people.pref.notification.storyReactionEnabled': 'Reactions to my stories',
  'admin.people.pref.notification.commentReplyEnabled': 'Replies to my comments',
  'admin.people.pref.notification.commentLikeEnabled': 'Likes on my comments',
  'admin.people.pref.notification.friendContentEnabled': 'Posts from my friends',
  'admin.people.pref.notification.contactActivityEnabled': 'A contact coming back on Meeshy',
  'admin.people.pref.notification.dndEnabled': 'Do not disturb',
  'admin.people.pref.notification.dndStartTime': 'Do not disturb: start',
  'admin.people.pref.notification.dndEndTime': 'Do not disturb: end',
  'admin.people.pref.notification.dndDays': 'Do not disturb: days',
  'admin.people.pref.notification.dndUtcOffsetMinutes': 'Do not disturb: time offset',
  'admin.people.pref.notification.showPreview': 'Content preview',
  'admin.people.pref.notification.showSenderName': 'Sender name',
  'admin.people.pref.notification.groupNotifications': 'Group notifications',
  'admin.people.pref.notification.notificationBadgeEnabled': 'Notification badge',
  'admin.people.pref.video.videoQuality': 'Video quality',
  'admin.people.pref.video.videoBitrate': 'Video bitrate',
  'admin.people.pref.video.videoFrameRate': 'Frame rate',
  'admin.people.pref.video.videoResolution': 'Video resolution',
  'admin.people.pref.video.videoCodec': 'Video codec',
  'admin.people.pref.video.defaultCamera': 'Default camera',
  'admin.people.pref.video.mirrorLocalVideo': 'Mirror my video',
  'admin.people.pref.video.videoLayout': 'Call layout',
  'admin.people.pref.video.showSelfView': 'Show my video',
  'admin.people.pref.video.selfViewPosition': 'Position of my video',
  'admin.people.pref.video.backgroundBlurEnabled': 'Background blur',
  'admin.people.pref.video.virtualBackgroundEnabled': 'Virtual background',
  'admin.people.pref.video.virtualBackgroundUrl': 'Virtual background image',
  'admin.people.pref.video.hardwareAccelerationEnabled': 'Hardware acceleration',
  'admin.people.pref.video.adaptiveBitrateEnabled': 'Adaptive bitrate',
  'admin.people.pref.video.autoStartVideo': 'Start video automatically',
  'admin.people.pref.video.autoMuteOnJoin': 'Mute on joining',
  'admin.people.pref.document.autoDownloadEnabled': 'Automatic download',
  'admin.people.pref.document.autoDownloadOnWifi': 'Automatic download on Wi-Fi',
  'admin.people.pref.document.autoDownloadMaxSize': 'Maximum automatic download size',
  'admin.people.pref.document.downloadPath': 'Download folder',
  'admin.people.pref.document.inlinePreviewEnabled': 'Inline preview',
  'admin.people.pref.document.previewPdfEnabled': 'PDF previews',
  'admin.people.pref.document.previewImagesEnabled': 'Image previews',
  'admin.people.pref.document.previewVideosEnabled': 'Video previews',
  'admin.people.pref.document.storageQuota': 'Storage quota',
  'admin.people.pref.document.autoDeleteOldFiles': 'Delete old files automatically',
  'admin.people.pref.document.fileRetentionDays': 'File retention',
  'admin.people.pref.document.compressImagesOnUpload': 'Compress images on upload',
  'admin.people.pref.document.imageCompressionQuality': 'Image compression quality',
  'admin.people.pref.document.allowedFileTypes': 'Allowed file types',
  'admin.people.pref.document.scanFilesForMalware': 'Malware scan of files',
  'admin.people.pref.document.allowExternalLinks': 'External links allowed',
  'admin.people.pref.application.theme': 'Theme',
  'admin.people.pref.application.accentColor': 'Accent color',
  'admin.people.pref.application.interfaceLanguage': 'Interface language',
  'admin.people.pref.application.autoTranslateEnabled': 'Automatic translation',
  'admin.people.pref.application.fontSize': 'Text size',
  'admin.people.pref.application.fontFamily': 'Font',
  'admin.people.pref.application.lineHeight': 'Line spacing',
  'admin.people.pref.application.compactMode': 'Compact mode',
  'admin.people.pref.application.sidebarPosition': 'Sidebar position',
  'admin.people.pref.application.showAvatars': 'Show avatars',
  'admin.people.pref.application.animationsEnabled': 'Animations',
  'admin.people.pref.application.reducedMotion': 'Reduce motion',
  'admin.people.pref.application.highContrastMode': 'High contrast',
  'admin.people.pref.application.screenReaderOptimized': 'Optimized for screen readers',
  'admin.people.pref.application.keyboardShortcutsEnabled': 'Keyboard shortcuts',
  'admin.people.pref.application.tutorialsCompleted': 'Completed tutorials',
  'admin.people.pref.application.betaFeaturesEnabled': 'Beta features',
  'admin.people.pref.application.telemetryEnabled': 'Telemetry',
  'admin.people.prefValue.encryption.disabled': 'Disabled',
  'admin.people.prefValue.encryption.optional': 'Optional',
  'admin.people.prefValue.encryption.always': 'Always',
  'admin.people.prefValue.transcriptionSource.auto': 'Automatic',
  'admin.people.prefValue.transcriptionSource.mobile': 'On the device',
  'admin.people.prefValue.transcriptionSource.server': 'On the server',
  'admin.people.prefValue.audioQuality.low': 'Low',
  'admin.people.prefValue.audioQuality.medium': 'Medium',
  'admin.people.prefValue.audioQuality.high': 'High',
  'admin.people.prefValue.audioQuality.lossless': 'Lossless',
  'admin.people.prefValue.cloneQuality.fast': 'Fast',
  'admin.people.prefValue.cloneQuality.balanced': 'Balanced',
  'admin.people.prefValue.cloneQuality.quality': 'Maximum quality',
  'admin.people.prefValue.clonePreset.fast': 'Fast',
  'admin.people.prefValue.clonePreset.balanced': 'Balanced',
  'admin.people.prefValue.clonePreset.high_quality': 'High quality',
  'admin.people.prefValue.fontSize.small': 'Small',
  'admin.people.prefValue.fontSize.medium': 'Medium',
  'admin.people.prefValue.fontSize.large': 'Large',
  'admin.people.prefValue.textAlign.left': 'Left',
  'admin.people.prefValue.textAlign.center': 'Centered',
  'admin.people.prefValue.textAlign.right': 'Right',
  'admin.people.prefValue.skinTone.default': 'Default',
  'admin.people.prefValue.skinTone.light': 'Light',
  'admin.people.prefValue.skinTone.medium-light': 'Medium-light',
  'admin.people.prefValue.skinTone.medium': 'Medium',
  'admin.people.prefValue.skinTone.medium-dark': 'Medium-dark',
  'admin.people.prefValue.skinTone.dark': 'Dark',
  'admin.people.prefValue.videoQuality.low': 'Low',
  'admin.people.prefValue.videoQuality.medium': 'Medium',
  'admin.people.prefValue.videoQuality.high': 'High',
  'admin.people.prefValue.videoQuality.auto': 'Automatic',
  'admin.people.prefValue.videoResolution.480p': '480p',
  'admin.people.prefValue.videoResolution.720p': '720p',
  'admin.people.prefValue.videoResolution.1080p': '1080p',
  'admin.people.prefValue.videoResolution.auto': 'Automatic',
  'admin.people.prefValue.videoLayout.grid': 'Grid',
  'admin.people.prefValue.videoLayout.speaker': 'Active speaker',
  'admin.people.prefValue.videoLayout.sidebar': 'Sidebar',
  'admin.people.prefValue.selfViewPosition.top-left': 'Top left',
  'admin.people.prefValue.selfViewPosition.top-right': 'Top right',
  'admin.people.prefValue.selfViewPosition.bottom-left': 'Bottom left',
  'admin.people.prefValue.selfViewPosition.bottom-right': 'Bottom right',
  'admin.people.prefValue.theme.light': 'Light',
  'admin.people.prefValue.theme.dark': 'Dark',
  'admin.people.prefValue.theme.auto': 'Automatic',
  'admin.people.prefValue.lineHeight.tight': 'Tight',
  'admin.people.prefValue.lineHeight.normal': 'Normal',
  'admin.people.prefValue.lineHeight.relaxed': 'Relaxed',
  'admin.people.prefValue.lineHeight.loose': 'Loose',
  'admin.people.prefValue.sidebarPosition.left': 'Left',
  'admin.people.prefValue.sidebarPosition.right': 'Right',
  'admin.people.prefValue.on': 'On',
  'admin.people.prefValue.off': 'Off',
  'admin.people.prefValue.everyDay': 'Every day',
  'admin.people.prefValue.characters': '{count} characters',
  'admin.people.prefValue.kbps': '{count} kbit/s',
  'admin.people.prefValue.count.fileTypes': '{count} allowed file type(s)',
  'admin.people.prefValue.count.tutorials': '{count} completed tutorial(s)',
  'admin.people.prefValue.count.items': '{count} item(s)',
  'admin.people.prefValue.structured': 'Structured data',
  'admin.people.prefValue.frameRate.15': '15 frames per second',
  'admin.people.prefValue.frameRate.24': '24 frames per second',
  'admin.people.prefValue.frameRate.30': '30 frames per second',
  'admin.people.prefValue.frameRate.60': '60 frames per second',
  'admin.people.prefValue.videoCodec.VP8': 'VP8',
  'admin.people.prefValue.videoCodec.VP9': 'VP9',
  'admin.people.prefValue.videoCodec.H264': 'H264',
  'admin.people.prefValue.videoCodec.H265': 'H265',
  'admin.people.prefValue.videoCodec.AV1': 'AV1',
  'admin.people.prefValue.audioFormat.mp3': 'MP3',
  'admin.people.prefValue.audioFormat.wav': 'WAV',
  'admin.people.prefValue.audioFormat.ogg': 'OGG',
  'admin.people.stats.withheld': 'Not shared',
  'admin.people.meta.identity': 'Identity and languages',
  'admin.people.meta.accountTitle': 'Account metadata',
  'admin.people.meta.sign': 'Sign-ins',
  'admin.people.meta.links': 'Links and referrals',
  'admin.people.meta.prismExplain': 'Messages are read in this order of languages: primary, secondary, then destination.',
  'admin.people.meta.registrationCountry': 'Country of registration',
  'admin.people.meta.deviceLocale': 'Device language',
  'admin.people.meta.deviceLocaleExplain': 'Fourth rank of the Prism: it never comes before the languages chosen in the app.',
  'admin.people.meta.deviceCountry': 'Device country',
  'admin.people.meta.age': 'Age',
  'admin.people.meta.ageValue': '{age} · born on {date}',
  'admin.people.meta.ageExplain': 'Computed from the declared birth date.',
  'admin.people.meta.ageVerified': 'Age verified',
  'admin.people.meta.terms': 'Terms accepted',
  'admin.people.meta.termsValue': 'Version {version} · on {date}',
  'admin.people.meta.termsNone': 'Not accepted',
  'admin.people.meta.onboarding': 'Onboarding',
  'admin.people.meta.onboardingDone': 'Completed on {date}',
  'admin.people.meta.onboardingNone': 'Not completed',
  'admin.people.meta.streak': 'Current streak',
  'admin.people.meta.streakValue': '{current} (record: {longest})',
  'admin.people.meta.engagement': 'Engagement score',
  'admin.people.meta.engagementExplain': 'Measures the member’s recent activity on the platform.',
  'admin.people.meta.meesh': 'Meesh balance',
  'admin.people.meta.blocked': 'Blocked accounts',
  'admin.people.meta.blockedNone': 'None',
  'admin.people.meta.blockedCount': '{count} account(s)',
  'admin.people.meta.pendingEmail': 'Pending e-mail change',
  'admin.people.meta.pendingPhone': 'Pending phone change',
  'admin.people.meta.pendingExplain': 'The new value is waiting for confirmation; it is never shown here.',
  'admin.people.consent.analytics': 'Analytics',
  'admin.people.meta.lastLogin': 'Last sign-in',
  'admin.people.meta.registration': 'Registration',
  'admin.people.meta.placeUnknown': 'Unknown place',
  'admin.people.meta.signDetail': '{place} · {device}',
  'admin.people.meta.failedLoginsExplain': 'The counter starts over at the next successful sign-in.',
  'admin.people.meta.lock': 'Lock',
  'admin.people.meta.lockNone': 'No lock',
  'admin.people.meta.backupCodes': 'Backup codes',
  'admin.people.meta.shareLinks': 'Share links created',
  'admin.people.meta.trackingLinks': 'Tracking links created',
  'admin.people.meta.affiliateTokens': 'Affiliate tokens created',
  'admin.people.meta.referralsGiven': 'Referrals made',
  'admin.people.meta.referralsReceived': 'Referrals received',
  'admin.people.meta.requestsSent': 'Contact requests sent',
  'admin.people.meta.requestsReceived': 'Contact requests received',
  'admin.people.ban.by': 'Banned by {name} on {date}',
  'admin.people.ban.byUnknown': 'Banned on {date}',
  'admin.people.ban.until': 'Until {date}',
  'admin.people.ban.liftedBy': 'Lifted by {name} on {date}',
  'admin.people.ban.liftedBySystem': 'Lifted automatically by the system on {date}',
  'admin.people.ban.liftedUnknown': 'Lifted on {date}',
  'admin.people.ban.liftReason': 'lift reason: {reason}',
  'admin.people.notFound': 'This member does not exist or no longer exists.',
  'admin.people.journal': 'This member’s log',
  'admin.people.media.unnamed': 'Unnamed media',
  'admin.people.media.kind.image': 'Image',
  'admin.people.media.kind.video': 'Video',
  'admin.people.media.kind.audio': 'Audio',
  'admin.people.media.kind.document': 'Document',
  'admin.people.secEvent.PASSWORD_RESET_REQUEST': 'Password reset requested',
  'admin.people.secEvent.PASSWORD_RESET_SUCCESS': 'Password reset',
  'admin.people.secEvent.PASSWORD_RESET_FAILED': 'Password reset failed',
  'admin.people.secEvent.PASSWORD_RESET_UNVERIFIED_EMAIL': 'Password reset requested for an unverified address',
  'admin.people.secEvent.PASSWORD_RESET_TOKEN_REUSE': 'Reset link reused',
  'admin.people.secEvent.PASSWORD_RESET_REVOKED_TOKEN': 'Revoked reset link used',
  'admin.people.secEvent.PASSWORD_RESET_INVALID_TOKEN': 'Invalid reset link',
  'admin.people.secEvent.PASSWORD_RESET_EXPIRED_TOKEN': 'Expired reset link',
  'admin.people.secEvent.PASSWORD_RESET_LOCKED_ACCOUNT': 'Password reset requested on a locked account',
  'admin.people.secEvent.PASSWORD_RESET_ABUSE': 'Password reset abuse',
  'admin.people.secEvent.SUSPICIOUS_PASSWORD_RESET': 'Suspicious password reset',
  'admin.people.secEvent.PASSWORD_CHANGE': 'Password changed',
  'admin.people.secEvent.LOGIN_SUCCESS': 'Sign-in succeeded',
  'admin.people.secEvent.LOGIN_FAILED': 'Sign-in failed',
  'admin.people.secEvent.LOGIN_BLOCKED': 'Sign-in blocked',
  'admin.people.secEvent.LOGOUT': 'Sign-out',
  'admin.people.secEvent.ACCOUNT_LOCKED': 'Account locked',
  'admin.people.secEvent.ACCOUNT_UNLOCKED': 'Account unlocked',
  'admin.people.secEvent.SESSION_CREATED': 'Session opened',
  'admin.people.secEvent.SESSION_REVOKED': 'Session revoked',
  'admin.people.secEvent.SESSION_EXPIRED': 'Session expired',
  'admin.people.secEvent.SESSION_TRUSTED': 'Session marked as trusted',
  'admin.people.secEvent.TWO_FACTOR_ENABLED': 'Two-factor authentication turned on',
  'admin.people.secEvent.TWO_FACTOR_DISABLED': 'Two-factor authentication turned off',
  'admin.people.secEvent.TWO_FACTOR_SUCCESS': 'Two-factor check succeeded',
  'admin.people.secEvent.TWO_FACTOR_FAILED': 'Two-factor check failed',
  'admin.people.secEvent.TWO_FA_FAILED': 'Two-factor check failed',
  'admin.people.secEvent.EMAIL_CHANGE': 'E-mail address changed',
  'admin.people.secEvent.PHONE_CHANGE': 'Phone number changed',
  'admin.people.secEvent.PHONE_TRANSFERRED_OUT': 'Number transferred to another account',
  'admin.people.secEvent.PHONE_TRANSFERRED_IN': 'Number received from another account',
  'admin.people.secEvent.PHONE_TRANSFER_CODE_RESENT': 'Number transfer code resent',
  'admin.people.secEvent.SUSPICIOUS_ACTIVITY': 'Suspicious activity',
  'admin.people.secEvent.RATE_LIMIT_EXCEEDED': 'Request limit exceeded',
  'admin.people.secEvent.BRUTE_FORCE_DETECTED': 'Brute-force attempts detected',
  'admin.people.secEvent.MAGIC_LINK_REQUESTED': 'Magic link requested',
  'admin.people.secEvent.MAGIC_LINK_LOGIN_SUCCESS': 'Sign-in by magic link',
  'admin.people.secEvent.MAGIC_LINK_REUSE_ATTEMPT': 'Magic link reused',
  'admin.people.secEvent.MAGIC_LINK_EXPIRED': 'Magic link expired',
  'admin.people.secEvent.EMAIL_RELEASED_BY_CLAIM': 'E-mail address released by a claim',
  'admin.people.dossier.contactDate': 'Since',
  'admin.people.dossier.memberLeft': 'Left',
  'admin.people.dossier.eventStatus': 'Outcome',
  'admin.people.anonymous.count': '{count} guests',
  'admin.people.anonymous.kind': 'Guest without an account',
  'admin.people.anonymous.notFound': 'This participant does not exist or no longer exists.',
  'admin.people.anonymous.presence': 'Presence',
  'admin.people.anonymous.list.caption': 'Anonymous participants',
  'admin.people.anonymous.list.empty': 'No anonymous participant yet.',
  'admin.people.anonymous.list.emptyFiltered': 'No guest matches these filters.',
  'admin.people.anonymous.state.left': 'Left',
  'admin.people.anonymous.state.left.explain': 'Has not been in the conversation since the date shown.',
  'admin.people.anonymous.state.revoked': 'Access removed',
  'admin.people.anonymous.state.revoked.explain': 'No longer active in the conversation: their access was removed, for example when the invitation link was closed.',
  'admin.people.anonymous.section.conversation': 'Conversation',
  'admin.people.anonymous.section.entry': 'Entry link',
  'admin.people.anonymous.section.permissions': 'What they can do',
  'admin.people.anonymous.section.permissions.hint': 'Fixed on arrival from the link’s rules: changing the link afterwards takes nothing away from people already in.',
  'admin.people.anonymous.entry.none': 'No entry link is recorded for this participant.',
  'admin.people.anonymous.entry.expires': 'Link expiry',
  'admin.people.anonymous.entry.noExpiry': 'No expiry',
  'admin.people.anonymous.stat.messages': 'Messages sent',
  'admin.people.anonymous.stat.permissions': 'Permissions granted',
  'admin.people.anonymous.stat.permissionsValue': '{granted} of {total}',
  'admin.people.anonymous.stat.arrived': 'Arrived',
  'admin.people.anonymous.meta.languageExplain': 'The language in which this guest reads the conversation: messages are translated for them into it.',
  'admin.people.anonymous.meta.left': 'Left on',
  'admin.people.anonymous.perm.canSendMessages.yes': 'Can write messages',
  'admin.people.anonymous.perm.canSendMessages.no': 'Cannot write messages',
  'admin.people.anonymous.perm.canSendImages.yes': 'Can send images',
  'admin.people.anonymous.perm.canSendImages.no': 'Cannot send images',
  'admin.people.anonymous.perm.canSendFiles.yes': 'Can send files',
  'admin.people.anonymous.perm.canSendFiles.no': 'Cannot send files',
  'admin.people.anonymous.perm.canSendVideos.yes': 'Can send videos',
  'admin.people.anonymous.perm.canSendVideos.no': 'Cannot send videos',
  'admin.people.anonymous.perm.canSendAudios.yes': 'Can send voice messages',
  'admin.people.anonymous.perm.canSendAudios.no': 'Cannot send voice messages',
  'admin.people.anonymous.perm.canSendLocations.yes': 'Can share their location',
  'admin.people.anonymous.perm.canSendLocations.no': 'Cannot share their location',
  'admin.people.anonymous.perm.canSendLinks.yes': 'Can send links',
  'admin.people.anonymous.perm.canSendLinks.no': 'Cannot send links',
  'admin.people.anonymous.perm.canViewHistory.yes': 'Sees messages written before they arrived',
  'admin.people.anonymous.perm.canViewHistory.no': 'Does not see messages written before they arrived',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
