import type { AdminCatalogFragment } from './fragment';
import type fr from './statistiques-fr';

const f = {
  'admin.analytics.subtitle': 'Activity, messages and calls across the platform. No message content is read here.',
  'admin.analytics.tabs.label': 'Analytics sections',
  'admin.analytics.tab.activity': 'Activity',
  'admin.analytics.tab.messages': 'Messages',
  'admin.analytics.tab.calls': 'Calls',
  'admin.analytics.window.note': 'Period: {window}',
  'admin.analytics.window.24h': 'last 24 hours',
  'admin.analytics.window.7d': 'last 7 days',
  'admin.analytics.window.30d': 'last 30 days',
  'admin.analytics.window.90d': 'last 90 days',
  'admin.analytics.peak.day': 'Peak on {day}: {count} messages',
  'admin.analytics.peak.hour': 'Peak at {hour}: {count} messages',
  'admin.analytics.types.title': 'Message types',
  'admin.analytics.types.summary': '{type}: {percent} of messages',

  'admin.analytics.activity.now.title': 'Right now',
  'admin.analytics.activity.now.updated': 'Measured {moment}',
  'admin.analytics.activity.now.online': 'Online now',
  'admin.analytics.activity.now.online.caption': 'Accounts active in the last 5 minutes',
  'admin.analytics.activity.now.messages': 'Messages (last hour)',
  'admin.analytics.activity.now.messages.caption': 'Messages written in the past hour',
  'admin.analytics.activity.now.conversations': 'Active conversations',
  'admin.analytics.activity.now.conversations.caption': 'Conversations where someone wrote in the past hour',
  'admin.analytics.activity.health.title': 'Usage health',
  'admin.analytics.activity.health.engagement': 'Engagement rate',
  'admin.analytics.activity.health.engagement.caption': 'Active accounts out of all accounts',
  'admin.analytics.activity.health.growth': 'Growth',
  'admin.analytics.activity.health.growth.caption': 'New accounts, as a share of all accounts',
  'admin.analytics.activity.health.perUser': 'Messages per account',
  'admin.analytics.activity.health.perUser.caption': 'Average across all accounts',
  'admin.analytics.activity.health.active': 'Active accounts',
  'admin.analytics.activity.health.active.caption': 'Accounts seen at least once in the period',
  'admin.analytics.activity.trends.title': 'Trends',
  'admin.analytics.activity.volume.title': 'Message volume',
  'admin.analytics.activity.hourly.title': 'Activity by 3-hour slot',
  'admin.analytics.activity.hourly.hint': 'Each bar counts the messages of the 3 hours after the time shown, over the last 24 hours. Times in UTC.',
  'admin.analytics.activity.hourly.summary': 'Busiest slot: from {hour}, {count} messages',
  'admin.analytics.activity.distribution.title': 'Account engagement',
  'admin.analytics.activity.distribution.hint': 'Very active: wrote in the last 7 days. Active: seen in the last 7 days without writing. Occasional: seen 7 to 30 days ago. Inactive: not seen for over 30 days, or never.',
  'admin.analytics.activity.distribution.summary': '{label}: {count} accounts, or {percent}',

  'admin.analytics.messages.overview.title': 'Overview',
  'admin.analytics.messages.total': 'Messages',
  'admin.analytics.messages.total.caption': 'Sent in the period, deleted messages excluded',
  'admin.analytics.messages.deleted': 'Deleted messages',
  'admin.analytics.messages.deleted.caption': 'Removed in the period, counted separately',
  'admin.analytics.messages.edited': 'Edited messages',
  'admin.analytics.messages.edited.caption': 'Corrected after sending',
  'admin.analytics.messages.length': 'Average length',
  'admin.analytics.messages.length.value': '{count} characters',
  'admin.analytics.messages.length.caption': 'Per message',
  'admin.analytics.messages.translated': 'Translated messages',
  'admin.analytics.messages.translated.caption': '{count} messages with at least one translation',
  'admin.analytics.messages.attachments': 'With an attachment',
  'admin.analytics.messages.attachments.caption': '{count} messages with an image, file or voice note',
  'admin.analytics.messages.timeline.title': 'Messages per day',
  'admin.analytics.messages.timeline.single': 'Only one day in this period: its total is in the cards above.',
  'admin.analytics.messages.senders.title': 'Most active members',
  'admin.analytics.messages.senders.hint': 'The ten accounts that sent the most messages in the period.',
  'admin.analytics.messages.senders.count': '{count} messages',
  'admin.analytics.messages.trends.title': 'Weekly rhythm',
  'admin.analytics.messages.trends.hint': 'Always over the last 7 days. Hours and days counted in UTC.',
  'admin.analytics.messages.trends.peakHour': 'Peak hour',
  'admin.analytics.messages.trends.peakDay': 'Busiest day',
  'admin.analytics.messages.trends.peak.caption': '{count} messages over 7 days',
  'admin.analytics.messages.trends.none': 'No messages in the period',
  'admin.analytics.messages.trends.hours.title': 'Messages by hour of the day',
  'admin.analytics.messages.trends.days.title': 'Messages by day of the week',
  'admin.analytics.messages.engagement.title': 'Engagement',
  'admin.analytics.messages.engagement.reactionRate': 'Reaction rate',
  'admin.analytics.messages.engagement.reactionRate.caption': '{count} messages received at least one reaction',
  'admin.analytics.messages.engagement.replyRate': 'Reply rate',
  'admin.analytics.messages.engagement.replyRate.caption': '{count} messages received at least one reply',
  'admin.analytics.messages.engagement.reactionsPer': 'Reactions per message',
  'admin.analytics.messages.engagement.reactionsPer.caption': '{count} reactions in total',
  'admin.analytics.messages.engagement.repliesPer': 'Replies per message',
  'admin.analytics.messages.engagement.repliesPer.caption': '{count} replies in total',

  'admin.analytics.calls.sampled': 'Sample capped at 5,000 calls: the figures cover the 5,000 most recent reports of the period.',
  'admin.analytics.calls.empty.title': 'No call reports in this period',
  'admin.analytics.calls.empty.hint': 'These statistics come from the telemetry each participant sends when a call ends.',
  'admin.analytics.calls.reliability.title': 'Reliability',
  'admin.analytics.calls.total': 'Call reports',
  'admin.analytics.calls.total.caption': 'One report per participant: a two-person call counts twice',
  'admin.analytics.calls.video': 'Video calls',
  'admin.analytics.calls.video.caption': 'Share of reports with video',
  'admin.analytics.calls.connect': 'Connection rate',
  'admin.analytics.calls.connect.caption': 'Calls that actually went through',
  'admin.analytics.calls.failure': 'Technical failures',
  'admin.analytics.calls.failure.caption': 'Declined and missed calls excluded',
  'admin.analytics.calls.timing.title': 'Timing and duration',
  'admin.analytics.calls.setup': 'Average setup time',
  'admin.analytics.calls.setup.caption': 'From dialing to connection, connected calls only',
  'admin.analytics.calls.negotiation': 'Average negotiation',
  'admin.analytics.calls.negotiation.caption': 'Technical exchange between the two devices',
  'admin.analytics.calls.duration': 'Average duration',
  'admin.analytics.calls.duration.caption': 'Per report',
  'admin.analytics.calls.reconnection': 'Calls with a reconnection',
  'admin.analytics.calls.reconnection.caption': 'On average {count} reconnections per call',
  'admin.analytics.calls.network.title': 'Network',
  'admin.analytics.calls.rtt': 'Average latency',
  'admin.analytics.calls.rtt.caption': 'Round trip, connected calls only',
  'admin.analytics.calls.loss': 'Average packet loss',
  'admin.analytics.calls.loss.caption': 'Connected calls only',
  'admin.analytics.calls.lossMax': 'Worst packet loss',
  'admin.analytics.calls.lossMax.caption': 'The worst report of the period',
  'admin.analytics.calls.transitions': 'Network changes',
  'admin.analytics.calls.transitions.caption': 'On average per call, such as Wi-Fi to mobile',
  'admin.analytics.calls.quality.title': 'Quality during calls',
  'admin.analytics.calls.quality.summary': '{label}: {percent} of measurements',
  'admin.analytics.calls.platform.title': 'Calls by platform',
  'admin.analytics.calls.platform.summary': '{label}: {count} reports',
  'admin.analytics.calls.reasons.title': 'How calls end',
  'admin.analytics.calls.reasons.summary': '{label}: {count} reports',
  'admin.analytics.calls.reasons.hint': 'Technical failures are connection failure, lost connection, lost signal and cleanup by the server.',
  'admin.analytics.calls.reason.completed': 'Ended normally',
  'admin.analytics.calls.reason.local': 'Hung up by this participant',
  'admin.analytics.calls.reason.remote': 'Hung up by the other party',
  'admin.analytics.calls.reason.missed': 'Unanswered',
  'admin.analytics.calls.reason.rejected': 'Declined',
  'admin.analytics.calls.reason.failed': 'Connection failed',
  'admin.analytics.calls.reason.connectionLost': 'Connection lost',
  'admin.analytics.calls.reason.heartbeatTimeout': 'Signal lost',
  'admin.analytics.calls.reason.garbageCollected': 'Cleaned up by the server',
  'admin.analytics.calls.reason.busy': 'Line busy',
  'admin.analytics.calls.reason.permission': 'Microphone or camera denied',
  'admin.analytics.calls.reason.removed': 'Removed from the call',
  'admin.analytics.calls.reason.in_progress': 'Reported during the call',
  'admin.analytics.calls.reason.unknown': 'Reason not reported',
  'admin.analytics.calls.feedback.title': 'Participant feedback',
  'admin.analytics.calls.feedback.rated': 'Rated calls',
  'admin.analytics.calls.feedback.rated.caption': 'Ratings left after the call',
  'admin.analytics.calls.feedback.average': 'Average rating',
  'admin.analytics.calls.feedback.average.value': '{rating} / 5',
  'admin.analytics.calls.feedback.average.caption': 'Out of 5',
  'admin.analytics.calls.feedback.empty': 'No feedback left in this period.',
  'admin.analytics.calls.feedback.stars': '{count} ★',
  'admin.analytics.calls.feedback.distribution.title': 'Rating distribution',
  'admin.analytics.calls.feedback.distribution.summary': 'Most given rating: {stars} out of 5, {count} ratings',
  'admin.analytics.calls.feedback.issues.title': 'Reported problems',
  'admin.analytics.calls.feedback.issues.summary': '{label}: {count} reports',
  'admin.analytics.calls.issue.audio_quality': 'Audio quality',
  'admin.analytics.calls.issue.video_quality': 'Video quality',
  'admin.analytics.calls.issue.dropped': 'Call dropped',
  'admin.analytics.calls.issue.echo': 'Echo',
  'admin.analytics.calls.issue.sync': 'Sound and picture out of sync',
  'admin.analytics.calls.issue.other': 'Other problem',

  'admin.lang.subtitle': 'Which languages are written on Meeshy, which get translated, and how reliably.',
  'admin.lang.overview.title': 'Overview',
  'admin.lang.messages': 'Messages analysed',
  'admin.lang.messages.caption': 'Sum of the {count} languages shown',
  'admin.lang.count': 'Languages written',
  'admin.lang.count.capped': 'Limited to the {limit} most written languages',
  'admin.lang.count.all': 'Every language written in the period',
  'admin.lang.top': 'Most written language',
  'admin.lang.top.caption': '{percent} of the messages shown',
  'admin.lang.empty.title': 'No language written in this period',
  'admin.lang.empty.hint': 'No message was sent in this period.',
  'admin.lang.share.title': 'Messages by language',
  'admin.lang.share.summary': '{language}: {percent} of messages',
  'admin.lang.detail.title': 'Detail by language',
  'admin.lang.detail.caption': 'The most written languages in the period, with their messages, authors, share and trend',
  'admin.lang.detail.language': 'Language',
  'admin.lang.detail.messages': 'Messages',
  'admin.lang.detail.authors': 'Authors',
  'admin.lang.detail.share': 'Share',
  'admin.lang.detail.growth': 'Trend',
  'admin.lang.detail.note': 'Trend: change in the number of messages compared with the previous period of the same length. +100% flags a new language (no messages before) or a doubled volume. Authors are accounts: guests are not counted.',
  'admin.lang.users.title': 'Members’ main language',
  'admin.lang.users.hint': 'The interface language each account chose, across all accounts, regardless of the period.',
  'admin.lang.users.summary': '{language}: {count} accounts',
  'admin.lang.users.others': 'Other languages',
  'admin.lang.pairs.title': 'Translated pairs',
  'admin.lang.pairs.hint': 'Translations produced in the period, from the original language to the target language.',
  'admin.lang.pairs.caption': 'Language pairs translated in the period, with their number of translations and average confidence',
  'admin.lang.pairs.pair': 'Pair',
  'admin.lang.pairs.translations': 'Translations',
  'admin.lang.pairs.confidence': 'Average confidence',
  'admin.lang.pairs.empty': 'No translations in this period.',
  'admin.lang.pair': '{from} → {to}',
  'admin.lang.confidence.none': 'Not measured',
  'admin.lang.timeline.title': 'Languages over the days',
  'admin.lang.timeline.hint': 'The three most written languages of the period; the others are grouped.',
  'admin.lang.timeline.others': 'Other languages',
  'admin.lang.timeline.summary': '{language} leads: {count} messages in the period',
  'admin.lang.accuracy.title': 'Translation accuracy',
  'admin.lang.accuracy.hint': 'Average confidence of the translation engine per language pair, across all periods. Excellent above 90%, good above 70%, fair above 50%, poor below.',
  'admin.lang.accuracy.caption': 'Translation accuracy per language pair',
  'admin.lang.accuracy.quality': 'Quality',
  'admin.lang.accuracy.empty': 'No translation measured.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
