import type { AdminCatalogFragment } from './fragment';
import type fr from './statistiques-fr';

const f = {
  'admin.analytics.subtitle': 'نشاط المنصة ورسائلها ومكالماتها. لا تُقرأ هنا أي محتويات للرسائل.',
  'admin.analytics.tabs.label': 'أقسام الإحصاءات',
  'admin.analytics.tab.activity': 'النشاط',
  'admin.analytics.tab.messages': 'الرسائل',
  'admin.analytics.tab.calls': 'المكالمات',
  'admin.analytics.window.note': 'الفترة: {window}',
  'admin.analytics.window.24h': 'آخر ٢٤ ساعة',
  'admin.analytics.window.7d': 'آخر ٧ أيام',
  'admin.analytics.window.30d': 'آخر ٣٠ يومًا',
  'admin.analytics.window.90d': 'آخر ٩٠ يومًا',
  'admin.analytics.peak.day': 'الذروة يوم {day}: {count} رسالة',
  'admin.analytics.peak.hour': 'الذروة عند {hour}: {count} رسالة',
  'admin.analytics.types.title': 'أنواع الرسائل',
  'admin.analytics.types.summary': '{type}: {percent} من الرسائل',

  'admin.analytics.activity.now.title': 'في هذه اللحظة',
  'admin.analytics.activity.now.updated': 'قِيس {moment}',
  'admin.analytics.activity.now.online': 'متصلون الآن',
  'admin.analytics.activity.now.online.caption': 'حسابات نشطة خلال آخر ٥ دقائق',
  'admin.analytics.activity.now.messages': 'الرسائل (آخر ساعة)',
  'admin.analytics.activity.now.messages.caption': 'رسائل كُتبت خلال الساعة الماضية',
  'admin.analytics.activity.now.conversations': 'المحادثات النشطة',
  'admin.analytics.activity.now.conversations.caption': 'محادثات كُتبت فيها رسائل خلال الساعة الماضية',
  'admin.analytics.activity.health.title': 'صحة الاستخدام',
  'admin.analytics.activity.health.engagement': 'معدل التفاعل',
  'admin.analytics.activity.health.engagement.caption': 'الحسابات النشطة قياسًا إلى جميع الحسابات',
  'admin.analytics.activity.health.growth': 'النمو',
  'admin.analytics.activity.health.growth.caption': 'الحسابات الجديدة كنسبة من جميع الحسابات',
  'admin.analytics.activity.health.perUser': 'الرسائل لكل حساب',
  'admin.analytics.activity.health.perUser.caption': 'المتوسط على جميع الحسابات',
  'admin.analytics.activity.health.active': 'الحسابات النشطة',
  'admin.analytics.activity.health.active.caption': 'حسابات ظهرت مرة واحدة على الأقل خلال الفترة',
  'admin.analytics.activity.trends.title': 'الاتجاهات',
  'admin.analytics.activity.volume.title': 'حجم الرسائل',
  'admin.analytics.activity.hourly.title': 'النشاط لكل فترة من ٣ ساعات',
  'admin.analytics.activity.hourly.hint': 'يحسب كل عمود رسائل الساعات الثلاث التي تلي الوقت المعروض، خلال آخر ٢٤ ساعة. التوقيت بالتوقيت العالمي (UTC).',
  'admin.analytics.activity.hourly.summary': 'أنشط فترة: ابتداءً من {hour}، {count} رسالة',
  'admin.analytics.activity.distribution.title': 'تفاعل الحسابات',
  'admin.analytics.activity.distribution.hint': 'نشطون جدًا: كتبوا خلال آخر ٧ أيام. نشطون: ظهروا خلال آخر ٧ أيام دون كتابة. عرضيّون: ظهروا قبل ٧ إلى ٣٠ يومًا. غير نشطين: لم يظهروا منذ أكثر من ٣٠ يومًا أو لم يظهروا قط.',
  'admin.analytics.activity.distribution.summary': '{label}: {count} حسابًا، أي {percent}',

  'admin.analytics.messages.overview.title': 'نظرة عامة',
  'admin.analytics.messages.total': 'الرسائل',
  'admin.analytics.messages.total.caption': 'أُرسلت خلال الفترة، دون الرسائل المحذوفة',
  'admin.analytics.messages.deleted': 'الرسائل المحذوفة',
  'admin.analytics.messages.deleted.caption': 'سُحبت خلال الفترة وتُحسب على حدة',
  'admin.analytics.messages.edited': 'الرسائل المعدَّلة',
  'admin.analytics.messages.edited.caption': 'صُحّحت بعد الإرسال',
  'admin.analytics.messages.length': 'متوسط الطول',
  'admin.analytics.messages.length.value': '{count} حرفًا',
  'admin.analytics.messages.length.caption': 'لكل رسالة',
  'admin.analytics.messages.translated': 'الرسائل المترجمة',
  'admin.analytics.messages.translated.caption': '{count} رسالة فيها ترجمة واحدة على الأقل',
  'admin.analytics.messages.attachments': 'مع مرفق',
  'admin.analytics.messages.attachments.caption': '{count} رسالة فيها صورة أو ملف أو رسالة صوتية',
  'admin.analytics.messages.timeline.title': 'الرسائل في كل يوم',
  'admin.analytics.messages.timeline.single': 'يوم واحد فقط في هذه الفترة: مجموعه في البطاقات أعلاه.',
  'admin.analytics.messages.senders.title': 'الأعضاء الأكثر نشاطًا',
  'admin.analytics.messages.senders.hint': 'الحسابات العشرة التي أرسلت أكبر عدد من الرسائل خلال الفترة.',
  'admin.analytics.messages.senders.count': '{count} رسالة',
  'admin.analytics.messages.trends.title': 'إيقاع الأسبوع',
  'admin.analytics.messages.trends.hint': 'دائمًا على آخر ٧ أيام. الساعات والأيام محسوبة بالتوقيت العالمي (UTC).',
  'admin.analytics.messages.trends.peakHour': 'ساعة الذروة',
  'admin.analytics.messages.trends.peakDay': 'أنشط يوم',
  'admin.analytics.messages.trends.peak.caption': '{count} رسالة خلال ٧ أيام',
  'admin.analytics.messages.trends.none': 'لا رسائل خلال الفترة',
  'admin.analytics.messages.trends.hours.title': 'الرسائل حسب ساعة اليوم',
  'admin.analytics.messages.trends.days.title': 'الرسائل حسب يوم الأسبوع',
  'admin.analytics.messages.engagement.title': 'التفاعل',
  'admin.analytics.messages.engagement.reactionRate': 'معدل التفاعل بالإعجاب',
  'admin.analytics.messages.engagement.reactionRate.caption': '{count} رسالة تلقّت تفاعلًا واحدًا على الأقل',
  'admin.analytics.messages.engagement.replyRate': 'معدل الردود',
  'admin.analytics.messages.engagement.replyRate.caption': '{count} رسالة تلقّت ردًا واحدًا على الأقل',
  'admin.analytics.messages.engagement.reactionsPer': 'التفاعلات لكل رسالة',
  'admin.analytics.messages.engagement.reactionsPer.caption': '{count} تفاعلًا في المجموع',
  'admin.analytics.messages.engagement.repliesPer': 'الردود لكل رسالة',
  'admin.analytics.messages.engagement.repliesPer.caption': '{count} ردًا في المجموع',

  'admin.analytics.calls.sampled': 'العيّنة محدودة بـ ٥٠٠٠ مكالمة: الأرقام تخص أحدث ٥٠٠٠ سجل في الفترة.',
  'admin.analytics.calls.empty.title': 'لا سجلات مكالمات في هذه الفترة',
  'admin.analytics.calls.empty.hint': 'تأتي هذه الإحصاءات من بيانات القياس التي يرسلها كل مشارك عند انتهاء المكالمة.',
  'admin.analytics.calls.reliability.title': 'الموثوقية',
  'admin.analytics.calls.total': 'سجلات المكالمات',
  'admin.analytics.calls.total.caption': 'سجل لكل مشارك: المكالمة بين شخصين تُحسب مرتين',
  'admin.analytics.calls.video': 'مكالمات الفيديو',
  'admin.analytics.calls.video.caption': 'نسبة السجلات التي فيها فيديو',
  'admin.analytics.calls.connect': 'معدل الاتصال',
  'admin.analytics.calls.connect.caption': 'المكالمات التي تمّ إجراؤها فعلًا',
  'admin.analytics.calls.failure': 'الأعطال التقنية',
  'admin.analytics.calls.failure.caption': 'دون المكالمات المرفوضة والفائتة',
  'admin.analytics.calls.timing.title': 'الأزمنة والمدة',
  'admin.analytics.calls.setup': 'متوسط زمن الإنشاء',
  'admin.analytics.calls.setup.caption': 'من البدء إلى الاتصال، للمكالمات المتصلة فقط',
  'admin.analytics.calls.negotiation': 'متوسط زمن التفاوض',
  'admin.analytics.calls.negotiation.caption': 'التبادل التقني بين الجهازين',
  'admin.analytics.calls.duration': 'متوسط المدة',
  'admin.analytics.calls.duration.caption': 'لكل سجل',
  'admin.analytics.calls.reconnection': 'مكالمات أُعيد اتصالها',
  'admin.analytics.calls.reconnection.caption': 'في المتوسط {count} إعادة اتصال لكل مكالمة',
  'admin.analytics.calls.network.title': 'الشبكة',
  'admin.analytics.calls.rtt': 'متوسط زمن الاستجابة',
  'admin.analytics.calls.rtt.caption': 'ذهابًا وإيابًا، للمكالمات المتصلة فقط',
  'admin.analytics.calls.loss': 'متوسط فقدان الحزم',
  'admin.analytics.calls.loss.caption': 'للمكالمات المتصلة فقط',
  'admin.analytics.calls.lossMax': 'أسوأ فقدان للحزم',
  'admin.analytics.calls.lossMax.caption': 'أسوأ سجل في الفترة',
  'admin.analytics.calls.transitions': 'تغيّرات الشبكة',
  'admin.analytics.calls.transitions.caption': 'في المتوسط لكل مكالمة، من الواي فاي إلى الجوال مثلًا',
  'admin.analytics.calls.quality.title': 'الجودة أثناء المكالمات',
  'admin.analytics.calls.quality.summary': '{label}: {percent} من القياسات',
  'admin.analytics.calls.platform.title': 'المكالمات حسب المنصة',
  'admin.analytics.calls.platform.summary': '{label}: {count} سجلًا',
  'admin.analytics.calls.reasons.title': 'كيف تنتهي المكالمات',
  'admin.analytics.calls.reasons.summary': '{label}: {count} سجلًا',
  'admin.analytics.calls.reasons.hint': 'الأعطال التقنية هي فشل الاتصال وانقطاعه وفقدان الإشارة وتنظيف الخادم للمكالمة.',
  'admin.analytics.calls.reason.completed': 'انتهت بشكل طبيعي',
  'admin.analytics.calls.reason.local': 'أنهاها هذا المشارك',
  'admin.analytics.calls.reason.remote': 'أنهاها الطرف الآخر',
  'admin.analytics.calls.reason.missed': 'بلا رد',
  'admin.analytics.calls.reason.rejected': 'مرفوضة',
  'admin.analytics.calls.reason.failed': 'فشل الاتصال',
  'admin.analytics.calls.reason.connectionLost': 'انقطع الاتصال',
  'admin.analytics.calls.reason.heartbeatTimeout': 'فُقدت الإشارة',
  'admin.analytics.calls.reason.garbageCollected': 'نظّفها الخادم',
  'admin.analytics.calls.reason.busy': 'الخط مشغول',
  'admin.analytics.calls.reason.permission': 'رُفض الميكروفون أو الكاميرا',
  'admin.analytics.calls.reason.removed': 'أُخرج من المكالمة',
  'admin.analytics.calls.reason.in_progress': 'سُجّل أثناء المكالمة',
  'admin.analytics.calls.reason.unknown': 'السبب غير مُبلَّغ',
  'admin.analytics.calls.feedback.title': 'آراء المشاركين',
  'admin.analytics.calls.feedback.rated': 'المكالمات المقيَّمة',
  'admin.analytics.calls.feedback.rated.caption': 'تقييمات تُركت بعد المكالمة',
  'admin.analytics.calls.feedback.average': 'متوسط التقييم',
  'admin.analytics.calls.feedback.average.value': '{rating} / ٥',
  'admin.analytics.calls.feedback.average.caption': 'من ٥',
  'admin.analytics.calls.feedback.empty': 'لا آراء في هذه الفترة.',
  'admin.analytics.calls.feedback.stars': '{count} ★',
  'admin.analytics.calls.feedback.distribution.title': 'توزيع التقييمات',
  'admin.analytics.calls.feedback.distribution.summary': 'أكثر تقييم: {stars} من ٥، {count} رأيًا',
  'admin.analytics.calls.feedback.issues.title': 'المشكلات المُبلَّغ عنها',
  'admin.analytics.calls.feedback.issues.summary': '{label}: {count} بلاغًا',
  'admin.analytics.calls.issue.audio_quality': 'جودة الصوت',
  'admin.analytics.calls.issue.video_quality': 'جودة الفيديو',
  'admin.analytics.calls.issue.dropped': 'انقطاع المكالمة',
  'admin.analytics.calls.issue.echo': 'صدى',
  'admin.analytics.calls.issue.sync': 'الصوت والصورة غير متزامنين',
  'admin.analytics.calls.issue.other': 'مشكلة أخرى',

  'admin.lang.subtitle': 'أي اللغات تُكتب على Meeshy، وأيها تُترجم، وبأي موثوقية.',
  'admin.lang.overview.title': 'نظرة عامة',
  'admin.lang.messages': 'الرسائل المحلَّلة',
  'admin.lang.messages.caption': 'مجموع اللغات المعروضة وعددها {count}',
  'admin.lang.count': 'اللغات المكتوبة',
  'admin.lang.count.capped': 'مقتصر على أكثر {limit} لغات كتابةً',
  'admin.lang.count.all': 'كل اللغات المكتوبة خلال الفترة',
  'admin.lang.top': 'أكثر لغة كتابةً',
  'admin.lang.top.caption': '{percent} من الرسائل المعروضة',
  'admin.lang.empty.title': 'لا لغة مكتوبة في هذه الفترة',
  'admin.lang.empty.hint': 'لم تُرسل أي رسالة في هذه الفترة.',
  'admin.lang.share.title': 'توزيع الرسائل حسب اللغة',
  'admin.lang.share.summary': '{language}: {percent} من الرسائل',
  'admin.lang.detail.title': 'التفصيل حسب اللغة',
  'admin.lang.detail.caption': 'أكثر اللغات كتابةً في الفترة، مع رسائلها وكتّابها وحصتها وتطورها',
  'admin.lang.detail.language': 'اللغة',
  'admin.lang.detail.messages': 'الرسائل',
  'admin.lang.detail.authors': 'الكتّاب',
  'admin.lang.detail.share': 'الحصة',
  'admin.lang.detail.growth': 'التطور',
  'admin.lang.detail.note': 'التطور: تغيّر عدد الرسائل مقارنةً بالفترة السابقة ذات المدة نفسها. تشير +١٠٠٪ إلى لغة جديدة (لا رسائل قبلها) أو إلى حجم تضاعف. الكتّاب حسابات: لا يُحتسب الضيوف.',
  'admin.lang.users.title': 'اللغة الرئيسية للأعضاء',
  'admin.lang.users.hint': 'لغة الواجهة التي اختارها كل حساب، على جميع الحسابات ودون ارتباط بالفترة.',
  'admin.lang.users.summary': '{language}: {count} حسابًا',
  'admin.lang.users.others': 'لغات أخرى',
  'admin.lang.pairs.title': 'الأزواج المترجمة',
  'admin.lang.pairs.hint': 'الترجمات المنتَجة خلال الفترة، من لغة الأصل إلى اللغة الهدف.',
  'admin.lang.pairs.caption': 'أزواج اللغات المترجمة خلال الفترة، مع عدد ترجماتها ومتوسط الثقة',
  'admin.lang.pairs.pair': 'الزوج',
  'admin.lang.pairs.translations': 'الترجمات',
  'admin.lang.pairs.confidence': 'متوسط الثقة',
  'admin.lang.pairs.empty': 'لا ترجمات في هذه الفترة.',
  'admin.lang.pair': '{from} ← {to}',
  'admin.lang.confidence.none': 'غير مقيسة',
  'admin.lang.timeline.title': 'اللغات على مدى الأيام',
  'admin.lang.timeline.hint': 'أكثر ثلاث لغات كتابةً في الفترة؛ وتُجمع بقية اللغات معًا.',
  'admin.lang.timeline.others': 'لغات أخرى',
  'admin.lang.timeline.summary': '{language} تتصدّر: {count} رسالة خلال الفترة',
  'admin.lang.accuracy.title': 'دقة الترجمات',
  'admin.lang.accuracy.hint': 'متوسط ثقة محرك الترجمة لكل زوج لغات، على كل الفترات. ممتازة فوق ٩٠٪، جيدة فوق ٧٠٪، متوسطة فوق ٥٠٪، وسيئة دون ذلك.',
  'admin.lang.accuracy.caption': 'دقة الترجمات لكل زوج لغات',
  'admin.lang.accuracy.quality': 'الجودة',
  'admin.lang.accuracy.empty': 'لا ترجمة مقيسة.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
