import type { AdminCatalogFragment } from './fragment';
import type fr from './statistiques-fr';

const f = {
  'admin.analytics.subtitle': 'A atividade, as mensagens e as chamadas da plataforma. Nenhum conteúdo de mensagem é lido aqui.',
  'admin.analytics.tabs.label': 'Seções das estatísticas',
  'admin.analytics.tab.activity': 'Atividade',
  'admin.analytics.tab.messages': 'Mensagens',
  'admin.analytics.tab.calls': 'Chamadas',
  'admin.analytics.window.note': 'Período: {window}',
  'admin.analytics.window.24h': 'últimas 24 horas',
  'admin.analytics.window.7d': 'últimos 7 dias',
  'admin.analytics.window.30d': 'últimos 30 dias',
  'admin.analytics.window.90d': 'últimos 90 dias',
  'admin.analytics.peak.day': 'Pico em {day}: {count} mensagens',
  'admin.analytics.peak.hour': 'Pico às {hour}: {count} mensagens',
  'admin.analytics.types.title': 'Tipos de mensagens',
  'admin.analytics.types.summary': '{type}: {percent} das mensagens',

  'admin.analytics.activity.now.title': 'Neste momento',
  'admin.analytics.activity.now.updated': 'Medido {moment}',
  'admin.analytics.activity.now.online': 'Online agora',
  'admin.analytics.activity.now.online.caption': 'Contas ativas nos últimos 5 minutos',
  'admin.analytics.activity.now.messages': 'Mensagens (última hora)',
  'admin.analytics.activity.now.messages.caption': 'Mensagens escritas na última hora',
  'admin.analytics.activity.now.conversations': 'Conversas ativas',
  'admin.analytics.activity.now.conversations.caption': 'Conversas em que se escreveu na última hora',
  'admin.analytics.activity.health.title': 'Saúde do uso',
  'admin.analytics.activity.health.engagement': 'Taxa de engajamento',
  'admin.analytics.activity.health.engagement.caption': 'Contas ativas em relação ao total de contas',
  'admin.analytics.activity.health.growth': 'Crescimento',
  'admin.analytics.activity.health.growth.caption': 'Contas novas, como parte do total de contas',
  'admin.analytics.activity.health.perUser': 'Mensagens por conta',
  'admin.analytics.activity.health.perUser.caption': 'Média sobre todas as contas',
  'admin.analytics.activity.health.active': 'Contas ativas',
  'admin.analytics.activity.health.active.caption': 'Contas vistas pelo menos uma vez no período',
  'admin.analytics.activity.trends.title': 'Tendências',
  'admin.analytics.activity.volume.title': 'Volume de mensagens',
  'admin.analytics.activity.hourly.title': 'Atividade por faixa de 3 horas',
  'admin.analytics.activity.hourly.hint': 'Cada barra conta as mensagens das 3 horas seguintes à hora indicada, nas últimas 24 horas. Horas em UTC.',
  'admin.analytics.activity.hourly.summary': 'Faixa mais ativa: a partir das {hour}, {count} mensagens',
  'admin.analytics.activity.distribution.title': 'Engajamento das contas',
  'admin.analytics.activity.distribution.hint': 'Muito ativos: escreveram nos últimos 7 dias. Ativos: vistos nos últimos 7 dias sem escrever. Ocasionais: vistos há 7 a 30 dias. Inativos: sem serem vistos há mais de 30 dias, ou nunca.',
  'admin.analytics.activity.distribution.summary': '{label}: {count} contas, ou seja {percent}',

  'admin.analytics.messages.overview.title': 'Visão geral',
  'admin.analytics.messages.total': 'Mensagens',
  'admin.analytics.messages.total.caption': 'Enviadas no período, sem as mensagens excluídas',
  'admin.analytics.messages.deleted': 'Mensagens excluídas',
  'admin.analytics.messages.deleted.caption': 'Removidas no período, contadas à parte',
  'admin.analytics.messages.edited': 'Mensagens editadas',
  'admin.analytics.messages.edited.caption': 'Corrigidas após o envio',
  'admin.analytics.messages.length': 'Comprimento médio',
  'admin.analytics.messages.length.value': '{count} caracteres',
  'admin.analytics.messages.length.caption': 'Por mensagem',
  'admin.analytics.messages.translated': 'Mensagens traduzidas',
  'admin.analytics.messages.translated.caption': '{count} mensagens com pelo menos uma tradução',
  'admin.analytics.messages.attachments': 'Com anexo',
  'admin.analytics.messages.attachments.caption': '{count} mensagens com imagem, arquivo ou áudio',
  'admin.analytics.messages.timeline.title': 'Mensagens por dia',
  'admin.analytics.messages.timeline.single': 'Apenas um dia neste período: o total dele está nos cartões acima.',
  'admin.analytics.messages.senders.title': 'Membros mais ativos',
  'admin.analytics.messages.senders.hint': 'As dez contas que enviaram mais mensagens no período.',
  'admin.analytics.messages.senders.count': '{count} mensagens',
  'admin.analytics.messages.trends.title': 'Ritmo da semana',
  'admin.analytics.messages.trends.hint': 'Sempre sobre os últimos 7 dias. Horas e dias contados em UTC.',
  'admin.analytics.messages.trends.peakHour': 'Hora de pico',
  'admin.analytics.messages.trends.peakDay': 'Dia mais ativo',
  'admin.analytics.messages.trends.peak.caption': '{count} mensagens em 7 dias',
  'admin.analytics.messages.trends.none': 'Nenhuma mensagem no período',
  'admin.analytics.messages.trends.hours.title': 'Mensagens por hora do dia',
  'admin.analytics.messages.trends.days.title': 'Mensagens por dia da semana',
  'admin.analytics.messages.engagement.title': 'Engajamento',
  'admin.analytics.messages.engagement.reactionRate': 'Taxa de reação',
  'admin.analytics.messages.engagement.reactionRate.caption': '{count} mensagens receberam pelo menos uma reação',
  'admin.analytics.messages.engagement.replyRate': 'Taxa de resposta',
  'admin.analytics.messages.engagement.replyRate.caption': '{count} mensagens receberam pelo menos uma resposta',
  'admin.analytics.messages.engagement.reactionsPer': 'Reações por mensagem',
  'admin.analytics.messages.engagement.reactionsPer.caption': '{count} reações no total',
  'admin.analytics.messages.engagement.repliesPer': 'Respostas por mensagem',
  'admin.analytics.messages.engagement.repliesPer.caption': '{count} respostas no total',

  'admin.analytics.calls.sampled': 'Amostra limitada a 5000 chamadas: os números referem-se aos 5000 registros mais recentes do período.',
  'admin.analytics.calls.empty.title': 'Nenhum registro de chamada neste período',
  'admin.analytics.calls.empty.hint': 'Estas estatísticas vêm da telemetria que cada participante envia ao fim de uma chamada.',
  'admin.analytics.calls.reliability.title': 'Confiabilidade',
  'admin.analytics.calls.total': 'Registros de chamada',
  'admin.analytics.calls.total.caption': 'Um registro por participante: uma chamada entre duas pessoas conta duas vezes',
  'admin.analytics.calls.video': 'Chamadas de vídeo',
  'admin.analytics.calls.video.caption': 'Parte dos registros com vídeo',
  'admin.analytics.calls.connect': 'Taxa de conexão',
  'admin.analytics.calls.connect.caption': 'Chamadas que realmente se completaram',
  'admin.analytics.calls.failure': 'Falhas técnicas',
  'admin.analytics.calls.failure.caption': 'Sem contar recusas e chamadas perdidas',
  'admin.analytics.calls.timing.title': 'Tempos e duração',
  'admin.analytics.calls.setup': 'Estabelecimento médio',
  'admin.analytics.calls.setup.caption': 'Do início à conexão, somente chamadas conectadas',
  'admin.analytics.calls.negotiation': 'Negociação média',
  'admin.analytics.calls.negotiation.caption': 'Troca técnica entre os dois aparelhos',
  'admin.analytics.calls.duration': 'Duração média',
  'admin.analytics.calls.duration.caption': 'Por registro',
  'admin.analytics.calls.reconnection': 'Chamadas com reconexão',
  'admin.analytics.calls.reconnection.caption': 'Em média {count} reconexões por chamada',
  'admin.analytics.calls.network.title': 'Rede',
  'admin.analytics.calls.rtt': 'Latência média',
  'admin.analytics.calls.rtt.caption': 'Ida e volta, somente chamadas conectadas',
  'admin.analytics.calls.loss': 'Perda média de pacotes',
  'admin.analytics.calls.loss.caption': 'Somente chamadas conectadas',
  'admin.analytics.calls.lossMax': 'Pior perda de pacotes',
  'admin.analytics.calls.lossMax.caption': 'O pior registro do período',
  'admin.analytics.calls.transitions': 'Mudanças de rede',
  'admin.analytics.calls.transitions.caption': 'Em média por chamada, do Wi-Fi ao celular por exemplo',
  'admin.analytics.calls.quality.title': 'Qualidade durante as chamadas',
  'admin.analytics.calls.quality.summary': '{label}: {percent} das medições',
  'admin.analytics.calls.platform.title': 'Chamadas por plataforma',
  'admin.analytics.calls.platform.summary': '{label}: {count} registros',
  'admin.analytics.calls.reasons.title': 'Como as chamadas terminam',
  'admin.analytics.calls.reasons.summary': '{label}: {count} registros',
  'admin.analytics.calls.reasons.hint': 'As falhas técnicas são a falha de conexão, a conexão perdida, o sinal perdido e a limpeza pelo servidor.',
  'admin.analytics.calls.reason.completed': 'Terminada normalmente',
  'admin.analytics.calls.reason.local': 'Encerrada por este participante',
  'admin.analytics.calls.reason.remote': 'Encerrada pela outra parte',
  'admin.analytics.calls.reason.missed': 'Sem resposta',
  'admin.analytics.calls.reason.rejected': 'Recusada',
  'admin.analytics.calls.reason.failed': 'Falha de conexão',
  'admin.analytics.calls.reason.connectionLost': 'Conexão perdida',
  'admin.analytics.calls.reason.heartbeatTimeout': 'Sinal perdido',
  'admin.analytics.calls.reason.garbageCollected': 'Limpa pelo servidor',
  'admin.analytics.calls.reason.busy': 'Linha ocupada',
  'admin.analytics.calls.reason.permission': 'Microfone ou câmera negados',
  'admin.analytics.calls.reason.removed': 'Removido da chamada',
  'admin.analytics.calls.reason.in_progress': 'Registro durante a chamada',
  'admin.analytics.calls.reason.unknown': 'Motivo não informado',
  'admin.analytics.calls.feedback.title': 'Avaliações dos participantes',
  'admin.analytics.calls.feedback.rated': 'Chamadas avaliadas',
  'admin.analytics.calls.feedback.rated.caption': 'Avaliações deixadas após a chamada',
  'admin.analytics.calls.feedback.average': 'Nota média',
  'admin.analytics.calls.feedback.average.value': '{rating} / 5',
  'admin.analytics.calls.feedback.average.caption': 'Em 5',
  'admin.analytics.calls.feedback.empty': 'Nenhuma avaliação neste período.',
  'admin.analytics.calls.feedback.stars': '{count} ★',
  'admin.analytics.calls.feedback.distribution.title': 'Distribuição das notas',
  'admin.analytics.calls.feedback.distribution.summary': 'Nota mais dada: {stars} em 5, {count} avaliações',
  'admin.analytics.calls.feedback.issues.title': 'Problemas relatados',
  'admin.analytics.calls.feedback.issues.summary': '{label}: {count} relatos',
  'admin.analytics.calls.issue.audio_quality': 'Qualidade de áudio',
  'admin.analytics.calls.issue.video_quality': 'Qualidade de vídeo',
  'admin.analytics.calls.issue.dropped': 'Chamada interrompida',
  'admin.analytics.calls.issue.echo': 'Eco',
  'admin.analytics.calls.issue.sync': 'Som e imagem dessincronizados',
  'admin.analytics.calls.issue.other': 'Outro problema',

  'admin.lang.subtitle': 'Quais idiomas se escrevem no Meeshy, quais são traduzidos e com que confiabilidade.',
  'admin.lang.overview.title': 'Visão geral',
  'admin.lang.messages': 'Mensagens analisadas',
  'admin.lang.messages.caption': 'Soma dos {count} idiomas exibidos',
  'admin.lang.count': 'Idiomas escritos',
  'admin.lang.count.capped': 'Limitado aos {limit} idiomas mais escritos',
  'admin.lang.count.all': 'Todos os idiomas escritos no período',
  'admin.lang.top': 'Idioma mais escrito',
  'admin.lang.top.caption': '{percent} das mensagens exibidas',
  'admin.lang.empty.title': 'Nenhum idioma escrito neste período',
  'admin.lang.empty.hint': 'Nenhuma mensagem foi enviada neste período.',
  'admin.lang.share.title': 'Distribuição das mensagens por idioma',
  'admin.lang.share.summary': '{language}: {percent} das mensagens',
  'admin.lang.detail.title': 'Detalhe por idioma',
  'admin.lang.detail.caption': 'Os idiomas mais escritos do período, com suas mensagens, autores, parte e evolução',
  'admin.lang.detail.language': 'Idioma',
  'admin.lang.detail.messages': 'Mensagens',
  'admin.lang.detail.authors': 'Autores',
  'admin.lang.detail.share': 'Parte',
  'admin.lang.detail.growth': 'Evolução',
  'admin.lang.detail.note': 'Evolução: variação do número de mensagens em relação ao período anterior de mesma duração. +100 % indica um idioma novo (sem mensagens antes) ou um volume dobrado. Os autores são contas: os convidados não são contados.',
  'admin.lang.users.title': 'Idioma principal dos membros',
  'admin.lang.users.hint': 'O idioma de interface escolhido por cada conta, entre todas as contas, sem relação com o período.',
  'admin.lang.users.summary': '{language}: {count} contas',
  'admin.lang.users.others': 'Outros idiomas',
  'admin.lang.pairs.title': 'Pares traduzidos',
  'admin.lang.pairs.hint': 'As traduções produzidas no período, do idioma de origem para o idioma de destino.',
  'admin.lang.pairs.caption': 'Pares de idiomas traduzidos no período, com o número de traduções e a confiança média',
  'admin.lang.pairs.pair': 'Par',
  'admin.lang.pairs.translations': 'Traduções',
  'admin.lang.pairs.confidence': 'Confiança média',
  'admin.lang.pairs.empty': 'Nenhuma tradução neste período.',
  'admin.lang.pair': '{from} → {to}',
  'admin.lang.confidence.none': 'Não medida',
  'admin.lang.timeline.title': 'Idiomas ao longo dos dias',
  'admin.lang.timeline.hint': 'Os três idiomas mais escritos do período; os demais são agrupados.',
  'admin.lang.timeline.others': 'Outros idiomas',
  'admin.lang.timeline.summary': '{language} domina: {count} mensagens no período',
  'admin.lang.accuracy.title': 'Precisão das traduções',
  'admin.lang.accuracy.hint': 'Confiança média do mecanismo de tradução por par de idiomas, em todos os períodos. Excelente acima de 90 %, boa acima de 70 %, média acima de 50 %, ruim abaixo.',
  'admin.lang.accuracy.caption': 'Precisão das traduções por par de idiomas',
  'admin.lang.accuracy.quality': 'Qualidade',
  'admin.lang.accuracy.empty': 'Nenhuma tradução medida.',
} satisfies AdminCatalogFragment<typeof fr>;

export default f;
